### ISSUE TITLE
Fiat on-ramp for RMRK in KodaDot

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1]
From apps created by [yangwao](https://github.com/yangwao): vue-polkadot/apps#161  

As [Ramp.network]() has support for DOT, they will have also for KSM 
* https://kusama.polkassembly.io/motion/249
* https://ramp.network/buy/?swapAsset=KSM
* https://docs.ramp.network/sdk-reference/

This will add a huge surplus into onboarding new users to RMRK.

**Comment by yangwao** [comment]
done for now

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 100.01 USD/KSM ~ 1 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0xd2b30a50011edd4729941beeed2a3d32591111253889a048f4ac24592e89f2be](https://kusama.subscan.io/extrinsic/0xd2b30a50011edd4729941beeed2a3d32591111253889a048f4ac24592e89f2be)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by roiLeo** [comment]
> 😍 Perfect, I’ve sent the payout 💵 $100 @ 100.01 USD/KSM ~ 1 $KSM 🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW) 🔗 [0xd2b30a50011edd4729941beeed2a3d32591111253889a048f4ac24592e89f2be](https://kusama.subscan.io/extrinsic/0xd2b30a50011edd4729941beeed2a3d32591111253889a048f4ac24592e89f2be)
> 
> 🪅 Let’s grab another issue and get rewarded! 🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

Who's this?
