### ISSUE TITLE
Create better user journey 

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#100]
Create two subroutes to create:
 - [x] collectibles (Collection + NFTs)
 - [x] single NFT (ex #42 )

In collectibles:
 - [ ] [Steps](https://buefy.org/documentation/steps/)
 - [ ] First step -> choose collection or create new one
 - [ ] Second step -> NFTs as is

Show users flow

- [ ] link to polkadot extension
- [ ] how to top up wallet
- [ ] what are next steps

**Comment by yangwao** [comment]
probably preliminary it's done thanks to simple mint
