### ISSUE TITLE
Different collection volumes on RMRK and Kodadot

### ISSUE THREAD

**Issue by yumiarts** [kodadot/nft-gallery#1000]
Hi!
RMRK and Kodadot started to show different collection volumes of my collection. RMRK shows 329.1 KSM and Kodadot 322.5376

I noticed it happened after this Kitty got sold, Kodadot didn't count the sale and numbers started to differ on both marketplaces

https://kodadot.xyz/rmrk/detail/9839389-800f8a914281765a7d-KITTY-KITTY_PARADISE_157-0000000000000157

I didn't check other collections, but there might be same issues too

**Comment by yangwao** [comment]
Hey, it's problem on RMRK Singular side, they add commission calculation. 
cc @vikiival 

![image](https://user-images.githubusercontent.com/5887929/139831458-76394d1d-12a6-4f8f-b01e-b3caec8b7138.png)

Someone was already asking this on our Discord
https://discord.com/channels/840514076538830888/842771087251341344/899282480383819827

**Comment by yangwao** [comment]
I guess we should notice this in our FAQ? 
I know it might be a duplicate, but for sure, we should take evidence of this one. 

Would be good to have this one in https://docs.kodadot.xyz 

📟 @cryptodamsky  @thea-exe
