### ISSUE TITLE
Footer not available in Drops

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10008]
Just curious, why we are not showing footer once we scroll below the drop page:

This Footer: 
<img width="1435" alt="Screenshot 2024-04-05 at 16 08 43" src="https://github.com/kodadot/nft-gallery/assets/104380776/ff2a92ac-b006-402c-842f-cce8d03ec98f">

On the end of this:
https://github.com/kodadot/nft-gallery/assets/104380776/e7c1773b-3e5f-4d47-85df-eb4b3d4432bf

**Comment by prury** [comment]
@JustLuuuu 
- https://github.com/kodadot/nft-gallery/issues/8542

**Comment by exezbcz** [comment]
> Just curious, why we are not showing footer once we scroll below the drop page:

there is infinity scroll for the items minted, causing more issues - removed

**Comment by JustLuuuu** [comment]
oh, got it, then I guess close
