### ISSUE TITLE
Shapes: Same NFTs minted as preview

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10009]
These two NFTs are the same. Something went wrong while minting: 
https://kodadot.xyz/ahp/gallery/116-2404276843
https://kodadot.xyz/ahp/gallery/116-2404256490

They look like preview picture of the collection.

**Comment by preschian** [comment]
same with https://github.com/kodadot/nft-gallery/issues/9987
fixed on canary
https://canary.kodadot.xyz/ahp/gallery/116-2404276843
https://canary.kodadot.xyz/ahp/gallery/116-2404256490

Feel free to reopen if you find that not fixed even on Canary
