### ISSUE TITLE
More pics

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10043]
<img width="1695" alt="Screenshot 2024-04-10 at 10 51 43" src="https://github.com/kodadot/nft-gallery/assets/104380776/d3343ea4-10c9-40bb-b3f2-787d4ff364cc">
I just noticed that the sidebar is big and there is actually space for more pictures. 

I would maybe align it to middle or make it possible to add more pics?

**Comment by exezbcz** [comment]
check: 
- https://github.com/kodadot/nft-gallery/issues/9634

![image](https://github.com/kodadot/nft-gallery/assets/90852205/f784f6a2-47ca-4517-973b-c56a4835eaf0)

**Comment by JustLuuuu** [comment]
it's possible to do it, Viki told me how to do it.
