### ISSUE TITLE
Packing drop empty card on landing/drop page

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10048]
https://kodadot.xyz/ahp/drops/packing

![image](https://github.com/kodadot/nft-gallery/assets/36627808/59b6e1cb-0b56-49ec-a52b-aaaba4308d39)

**Comment by vikiival** [comment]
![Screenshot 2024-04-10 at 21 14 43](https://github.com/kodadot/nft-gallery/assets/22471030/bdbae973-8a27-4015-ae10-c27023e76d85)
