### ISSUE TITLE
something goes wrong when going through the gallery pages

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1007]
some of the page appear with one ntf 
i use chrome on windows 10 

![02](https://user-images.githubusercontent.com/71472224/139890396-49d3ed89-b669-4f71-97e1-bea9528d9474.png)
![03](https://user-images.githubusercontent.com/71472224/139890408-78b6f448-5565-454c-b214-615e6df1a161.png)
![04](https://user-images.githubusercontent.com/71472224/139890420-7a768307-71a7-4b2d-91c2-7786320ba150.png)

 
![01](https://user-images.githubusercontent.com/71472224/139890366-8e7cda89-325b-49b0-be26-73c2063284fd.png)

**Comment by TK-Development** [comment]
I'll take a look.

**Comment by roiLeo** [comment]
see #525 for references

**Comment by TK-Development** [comment]
some of the page appear with few nfts

**PR type**

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

**Screenshot**

Before
![image](https://user-images.githubusercontent.com/86540499/139950736-d9261e27-1af1-43c3-8c2d-3faebaa7a66d.png)

After
![image](https://user-images.githubusercontent.com/86540499/139950884-72f1f1d8-5aa8-45b5-a788-7223b957315f.png)

**Comment by onerawartist** [comment]
![01](https://user-images.githubusercontent.com/71472224/139973481-a2417b94-4570-4c94-8b98-ac3c4c1a4937.png)
![02](https://user-images.githubusercontent.com/71472224/139973510-762248eb-8853-49c3-97f0-1d553b6b151d.png)

i think the page problem happens only where there's copies of an NFT

**Comment by onerawartist** [comment]
its a feature not a bug type of situations , but i think its actually good ^^ instead of flooding the feed with emojis.
i just think there should be an icon on the NFT saying there's 100 of it, instead of it taking pages, and people thinking its a bug in the website

**Comment by onerawartist** [comment]
> some of the page appear with few nfts
> 
> **PR type**
> 
> * [x]  Bugfix
> * [ ]  Feature
> * [ ]  Refactoring
> 
> **Screenshot**
> 
> Before ![image](https://user-images.githubusercontent.com/86540499/139950736-d9261e27-1af1-43c3-8c2d-3faebaa7a66d.png)
> 
> After ![image](https://user-images.githubusercontent.com/86540499/139950884-72f1f1d8-5aa8-45b5-a788-7223b957315f.png)

there is a 100 NFT looking the same, thats why its taking all those pages, visit the collection of that NFT

**Comment by TK-Development** [comment]
Yes. 
It happens only when there are many same NFTs(that is same collection).
So what is your idea for this case? Show only 1 collection? or Show 9 items(same collection)?

**Comment by yangwao** [comment]
> its a feature not a bug type of situations , but i think its actually good ^^ instead of flooding the feed with emojis. i just think there should be an icon on the NFT saying there's 100 of it, instead of it taking pages, and people thinking its a bug in the website

When you shower on the collection, you can see this which tells you grouped NFTs 
![image](https://user-images.githubusercontent.com/5887929/140071719-ffdb66eb-be4d-4e7e-ac7d-b8cff72bfb54.png)

I agree we can figure out to have better design to show it much better.

**Comment by onerawartist** [comment]
@Top-Kraken @yangwao , any updates ?

**Comment by XyloDrone** [comment]
I'll add an option in the design that the user can choose to see only unique NFTs. This would be just a check box.

**Comment by onerawartist** [comment]
@XyloDrone make it ''On'' by default

**Comment by roiLeo** [comment]
I think this can be closed as we introduced in #942 user preferences to display a certain numbers of items by page (12 by default).

**Comment by yangwao** [comment]
> I think this can be closed as we introduced in #942 user preferences to display a certain numbers of items by page (12 by default).

This is about merging afaik to uniques
