### ISSUE TITLE
Artists abusing the platform !

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1008]
they keep changing the price of the artwork to stay on top of the gallery "last interacted" filter to be exact, im not gonna talk about the most expensive option lol 
 
![p2](https://user-images.githubusercontent.com/71472224/139904071-d803f553-212f-4529-9aa8-eb0e05f09a06.png)

![p1](https://user-images.githubusercontent.com/71472224/139904233-3e140ef1-4c38-4c22-9290-abad9a6d6c47.png)

the website really needs few options to filter out what spammer artists are doing
here are few:
follow option on profiles
follow option or add to fav for collections, specially open ones, so you can always visit your fav collection to check new drops 
and the gallery should have something like youtube, a feed of new nfts from only the profiles and the collections you follow 
and another feed "explore" from profiles you dont follow

**Comment by yangwao** [comment]
Closing in favour of passion issues we have
- #744 

https://github.com/kodadot/nft-gallery/issues?q=is%3Aopen+is%3Aissue+label%3Apassion
