### ISSUE TITLE
Base collection not visible on KodaDot

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10104]
Yesterday we did a Base drop:
- https://github.com/kodadot/ops-internal/issues/1582
- https://warpcast.com/vikiival/0x86ba6499 - warpcast link
- https://unfoldings.kodadot.workers.dev/

The collection in not visible on kodaDot:

<img width="1494" alt="Screenshot 2024-04-19 at 11 37 27" src="https://github.com/kodadot/nft-gallery/assets/104380776/618a314e-7e20-4dc6-aca5-5cf5d7ab29d2">

**Comment by vikiival** [comment]
Fixed by Indexer
