### ISSUE TITLE
Electronik: Again on the end of the list

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10107]
Please move [Electronik](https://kodadot.xyz/ahp/drops/electronik) to the front of the page.

<img width="1858" alt="Screenshot 2024-04-19 at 15 38 05" src="https://github.com/kodadot/nft-gallery/assets/104380776/3d6470b6-f4fc-4c46-a428-172f071eb288">

Also not visible here at all )9even after moving):
<img width="1873" alt="Screenshot 2024-04-19 at 15 38 11" src="https://github.com/kodadot/nft-gallery/assets/104380776/abefc758-fd7a-4087-8727-62ca154f1248">

**Comment by hassnian** [comment]
@vikiival `electronik` it's missing `start_at` date 

pls add this and it should appear in the landing strip 

thanks

![CleanShot 2024-04-20 at 10 45 14@2x](https://github.com/kodadot/nft-gallery/assets/44554284/db897ed0-095a-4150-91cf-fbbc446d7221)

**Comment by preschian** [comment]
added
