### ISSUE TITLE
Unfolding: Horrible quality of the minted NFTs + missing animation

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10117]
Unfoldings - https://kodadot.xyz/base/collection/0xc029b380f8a451cfd9e5124fa9fcad4397b8c119
Base collection minted via frames on Farcaster. The quality of the pictures is very low.

Check how original art looked like in code-checker:
[Unfoldings.v1_9 (1).zip](https://github.com/kodadot/nft-gallery/files/15060969/Unfoldings.v1_9.1.zip)

Original code art quality:
<img width="2560" alt="Screenshot 2024-04-22 at 11 44 22" src="https://github.com/kodadot/nft-gallery/assets/104380776/5a3ff7e7-f15d-43ce-a5c0-fa29575f5447">

When you open on full-screen [any NFt from the collection](https://kodadot.xyz/base/collection/0xc029b380f8a451cfd9e5124fa9fcad4397b8c119), you can see that the quality is very low. 

Looks like gallery on koda outputting only prerendered image instead actual canvas. 

Bacuse also animations are not working (click on picture + press A to start the animation)

**Comment by hassnian** [comment]
@JustLuuuu [try with this link](https://deploy-preview-10075--koda-canary.netlify.app/base/gallery/0xc029b380f8a451cfd9e5124fa9fcad4397b8c119-5) will be fixed by #10075

**Comment by hassnian** [comment]
fixed by 

- https://github.com/kodadot/nft-gallery/pull/10075
- https://github.com/kodadot/nft-gallery/pull/10092

![CleanShot 2024-04-30 at 13 09 32](https://github.com/kodadot/nft-gallery/assets/44554284/8644c46f-8db9-400a-8ef4-1f0953c4c88e)
