### ISSUE TITLE
Basescape #3: mint with no preview

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10122]
Basescape number 3 is not opening properly; since I cannot see the collection on KodaDot yet, I don't know if the issue is also on kodaDot. But on Opensea you can see it like this: 
- https://opensea.io/assets/base/0xd9a2c93ba2e9fae10fe762a42ee807bbf95764cc/3 
<img width="1706" alt="Screenshot 2024-04-22 at 16 39 03" src="https://github.com/kodadot/nft-gallery/assets/104380776/db354d1f-883a-4c7d-98cf-77eccd8c6ed1">

Ref:
-#10121 - collection not visible on koda

**Comment by daiagi** [comment]
in the meantime:

![image](https://github.com/kodadot/nft-gallery/assets/22791238/7e513b30-a87f-4e16-bb5e-37231be110b3)

**Comment by JustLuuuu** [comment]
I love it when things fix themselves.
