### ISSUE TITLE
Add new sharing icon

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1012]
Current our icon is pretty OG,

Or right top arrow in abstract box

![image](https://user-images.githubusercontent.com/5887929/140039814-24d3fbfc-3fef-421c-b33c-ac906c5e3ca7.png)

Found at font awesome v6, seems they are using it for link as well 
https://fontawesome.com/v6.0/icons/arrow-up-right

![image](https://user-images.githubusercontent.com/5887929/140040574-390d11e7-8150-48c4-a084-0977b9e57aee.png)

related #796 

![image](https://user-images.githubusercontent.com/5887929/140039761-e9858f1d-14ad-4c10-b56b-ca66cffe725f.png)

Have a reading https://en.wikipedia.org/wiki/Share_icon

# Ref
- #796 
- #2692 
- #2081

**Comment by yangwao** [comment]
Please, someone 😄
Upgrade to font-awesome v6

**Comment by vikiival** [comment]
**fort** awesome does not support FA6 https://fortawesome.com/sets/starter

**Comment by yangwao** [comment]
> **fort** awesome does not support FA6 https://fortawesome.com/sets/starter

and if they will ,they are making it only for Vue3, screwed.

**Comment by yangwao** [comment]
Will be closed in #4111 

![image](https://user-images.githubusercontent.com/5887929/195871606-b7293c8e-dfff-46c7-a3b2-20c06eeecd40.png)
