### ISSUE TITLE
IPFS upload not loading modal but loading button state 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10149]
We already discussed this with @hassnian and it would make more sense to have one consistent flow for both minting multiple and one 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/ddb83266-a4fc-4869-ab8c-5e8ac310f2c4)

that means there wont be this loading modal 
- instead, it will have the same button state as when minting multiple nfts

**Comment by exezbcz** [comment]
looks like it shows quite randomly? tried minting the aeroloom again and it did not display this state

**Comment by hassnian** [comment]
thanks to #10095 there is no more "uploading data to ipfs"

try `canary` , this hasn't been deployed to prod yet
