### ISSUE TITLE
Followers UX improvements

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10165]
Took me a while to find out that those buttons were clickable: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/a763bebd-9228-4785-b757-c05fb316d791)
is there something we can do to make it more obvious? 

i do think it would be good if those profiles could be clickable and would redirect to clicked profile: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/c42e3f33-7e3f-4d5e-a794-8b7f1909884b)

@exezbcz 

after #10160

**Comment by exezbcz** [comment]
> is there something we can do to make it more obvious?

can do, good idea 




> i do think it would be good if those profiles could be clickable and would redirect to clicked profile:

it should be, afaik i mentioned that somewhere, if not, my bad :D
