### ISSUE TITLE
update NeoButtonVariants

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#10162]
ref #10018

1.Make NeoButton sizes and variants sync with those in Figma
2. keep `text` and `icon` variants but make them `no-shadow` by default
3.  properly expose both `icon-left` and `icon-right` props 
4. replace **ALL** usage of `NeoButton` with new variants/props

https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=5311-18771&mode=design&t=rBEuuLInIN2HWbO7-0

**Comment by exezbcz** [comment]
ref: 
- https://github.com/kodadot/nft-gallery/issues/10210
