### ISSUE TITLE
Gallery item icon not perfect square

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#10163]
after #10066

> gallery item in share <img alt="image" width="167" src="https://private-user-images.githubusercontent.com/90852205/323834696-155348e8-e2b5-4f5f-91fd-f405761d8611.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzU1NDYsIm5iZiI6MTcxNDM3NTI0NiwicGF0aCI6Ii85MDg1MjIwNS8zMjM4MzQ2OTYtMTU1MzQ4ZTgtZTJiNS00ZjVmLTkxZmQtZjQwNTc2MWQ4NjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA3MjA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MjZiYWZlMDdjNjExNzM3OGNkMDg5MzFiNzQ4MjkwOWFjODgxZmE3ODU3MDVkZmEzMmMwNGRiYWQwZTdlYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TSGJuSfvrrhukHeC6bO9AmQecucA1r3WEHd0kyZJnsU">
> 
> * perfect square please
> * 40x40
> 
> _Originally posted by @exezbcz in [#10066 (comment)](https://github.com/kodadot/nft-gallery/pull/10066#issuecomment-2065750505)_
> 
remove class here 

`GalleryItemMoreActionBtn.vue`

![CleanShot 2024-04-29 at 12 18 56@2x](https://github.com/kodadot/nft-gallery/assets/44554284/d7fb9a26-a854-4135-bfe1-a3ddf0bc475f)

and update here 

![CleanShot 2024-04-29 at 11 59 37@2x](https://github.com/kodadot/nft-gallery/assets/44554284/3a024b0f-69af-4bb9-9c15-bae4c3c90874)

**Comment by hassnian** [comment]
> after #10066
> 
> gallery item in share <img alt="image" width="167" src="https://private-user-images.githubusercontent.com/90852205/323834696-155348e8-e2b5-4f5f-91fd-f405761d8611.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzU1NDYsIm5iZiI6MTcxNDM3NTI0NiwicGF0aCI6Ii85MDg1MjIwNS8zMjM4MzQ2OTYtMTU1MzQ4ZTgtZTJiNS00ZjVmLTkxZmQtZjQwNTc2MWQ4NjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA3MjA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MjZiYWZlMDdjNjExNzM3OGNkMDg5MzFiNzQ4MjkwOWFjODgxZmE3ODU3MDVkZmEzMmMwNGRiYWQwZTdlYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TSGJuSfvrrhukHeC6bO9AmQecucA1r3WEHd0kyZJnsU">
> 
> * perfect square please
> * 40x40
> 
> _Originally posted by @exezbcz in [#10066 (comment)](https://github.com/kodadot/nft-gallery/pull/10066#issuecomment-2065750505)_
> 
remove class here 

`GalleryItemMoreActionBtn.vue`

![CleanShot 2024-04-29 at 12 18 56@2x](https://github.com/kodadot/nft-gallery/assets/44554284/d7fb9a26-a854-4135-bfe1-a3ddf0bc475f)


and update here 

![CleanShot 2024-04-29 at 11 59 37@2x](https://github.com/kodadot/nft-gallery/assets/44554284/3a024b0f-69af-4bb9-9c15-bae4c3c90874)

**Comment by prachi00** [comment]
I think we should remove the icon action class instead since min-w-10 and h-10 is the way to go now according to figma? minimum is w-10

**Comment by asterism0115** [comment]
Has this issue been resolved?

**Comment by hassnian** [comment]
@asterism0115 nope, up for grabs

**Comment by AnmolBansalDEV** [comment]
👋

**Comment by AnmolBansalDEV** [comment]
👋
