### ISSUE TITLE
Created by disappearing on drop 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10161]
https://github.com/kodadot/nft-gallery/assets/90852205/ed2a111b-63df-4424-985d-ec564080e049

tested on canary

**Comment by Jarsen136** [comment]
Feel free to reopen it if it's still there.

![image](https://github.com/kodadot/nft-gallery/assets/31397967/351cec82-c31f-436a-97df-0b2e2edfc1ad)
