### ISSUE TITLE
Check social media preview on collections

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1017]
Best would be to see use collection picture for social media preview if it's present 

You can test with https://nft.kodadot.xyz/rmrk/collection/96A4D072A809BD211F-0XV

![image](https://user-images.githubusercontent.com/5887929/140099417-557ccf37-988e-4c0d-ac98-27be0d333fd0.png)

Maybe @AndriiHrynchuk 👀

**Comment by prachi00** [comment]
I think for this, we would have to change meta tag on the fly?  Is there any other way? @vikiival @roiLeo

**Comment by AndreyGrin** [comment]
Just redeployed Vercel app for social previews. Works good for NFT items.
Collections page shows up image of the first items in the collection but needs code updates to be shown on Twitter, I can add. We could also build preview by using Versel app if you want to add some details to the image.

**Comment by AndreyGrin** [comment]
With Vercel can be like this 
<img width="362" alt="image" src="https://user-images.githubusercontent.com/2453346/140609661-821d7770-aeab-49a9-8eb9-09e21b4d3874.png">

**Comment by yangwao** [comment]
on https://beta.kodadot.xyz it works well but on kodadot @preschian tried something worked for while till we had some error and retracted, maybe time to revisit this one?

**Comment by roiLeo** [comment]
![Capture d’écran 2022-11-02 à 10 12 52 AM](https://user-images.githubusercontent.com/9987732/199454830-7f77055f-93f1-4afd-a847-b773669df13d.png)


Closing this for https://github.com/kodadot/nft-gallery/issues/2136#issuecomment-1296541256
