### ISSUE TITLE
Base: Add Concordante collection to Base collections

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10179]
Similar as with this collection: #10121, it needs to be added manually to Koda. Please add the newest collection from Base there too: 

Post with frame: https://warpcast.com/eduxdux/0xb25177a5
Frame link: https://k-frame.kodadot.workers.dev/base/0x2cc76e51c4ae3ed7b0dcada34c1ea4fe059d5881

Add it [here](https://kodadot.xyz/base/explore/collectibles). 

At the moment Im not sure if there were any mints, as I have no idea how to check that.

**Comment by vikiival** [comment]
Hey it is issue on my side check - https://github.com/kodadot/ops-internal/discussions/1610

**Comment by roiLeo** [comment]
Safe to close?
