### ISSUE TITLE
[DX] Generate auto types from graphql and rest api

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#10185]
Related:
- https://github.com/kodadot/nft-gallery/issues/8500
- https://github.com/kodadot/nft-gallery/issues/4544

Graphql queries are higher priorities.

**Comment by daiagi** [comment]
- https://github.com/dotansimha/graphql-code-generator
- https://github.com/MichalLytek/type-graphql

**Comment by preschian** [comment]
- https://gql-tada.0no.co/
