### ISSUE TITLE
Save Art: make it more user-friendly

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10199]
Issue
---
This was bothering me for a while, but I could have survived without this. But now also more people noticed this. Saving of full-sized image is possible only when you open full-sceen. 

<img width="214" alt="Screenshot 2024-05-03 at 10 57 14" src="https://github.com/kodadot/nft-gallery/assets/104380776/3660d1da-42f0-4df1-8077-5c1040ece832">

Proposed solution
---
Can we have a save button below the pic? 
<img width="513" alt="Screenshot 2024-05-03 at 10 59 16" src="https://github.com/kodadot/nft-gallery/assets/104380776/a14278db-a5fe-40e3-b2cb-c59164ebc6eb">

Or any other suggestions how to make it simple and quick?

**Comment by panda6151025** [comment]
👋

**Comment by hassnian** [comment]
![CleanShot 2024-10-22 at 10 10 05@2x](https://github.com/user-attachments/assets/d3e246e7-c5e3-43ae-8658-6ede6b7375ef)
