### ISSUE TITLE
Make possible it possible not to be necessary to enter all fields on Profile

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10204]
when creating a new off-chain profile, a user may not want to fill all the social media fields, let`s make it possible to leave them all unfilled. 

for the ones that are required, lets show error message stating that the field is required in order to the profile to be created.

**Comment by daiagi** [comment]
@Jarsen136 socials are alreayd optional

what is reuired is to make banner optional

ref https://github.com/kodadot/private-workers/issues/137

**Comment by Jarsen136** [comment]
> @Jarsen136 socials are already optional
> 
> 
> 
> what is required is to make banner optional
> 
> 
> 
> ref https://github.com/kodadot/private-workers/issues/137

okay, I will make it.
