### ISSUE TITLE
Button states (active, focus) - revisions 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10210]
followup for: 
- #10066 

in the components, there is defined focus state, by focus state i mean the state that happens when you navigate tab using tab

![image](https://github.com/kodadot/nft-gallery/assets/90852205/cc4b65fb-b908-4a2d-bad5-9e2a7e0cbf75)
- it should not be the state when you hold the button 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/8c83c133-f628-4497-84ca-6463d2f532fe)

on thing are dropdowns, when clicking, it turns the black stroke to white one

![image](https://github.com/kodadot/nft-gallery/assets/90852205/454ff9a9-2612-4d55-b2b5-9c6957a0bb48)

https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=5311-18771&mode=design&t=wIR4vUyhVh1KHnUu-11

**Comment by exezbcz** [comment]
this should not really be a focus state
<img width="452" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/9fc634fb-44a7-4917-91d1-8d71f276bee5">


that should be "active"

**Comment by exezbcz** [comment]
would probably need more revisions 


https://github.com/kodadot/nft-gallery/assets/90852205/ab297011-6ee2-4f3f-a7c8-27912571629d

**Comment by exezbcz** [comment]
dropdown styling should also be a bit different 


mainly there should not be a hover animation after the button is already active 

https://github.com/kodadot/nft-gallery/assets/90852205/fd190ac1-0dc1-4721-adfd-ef4253b72f92


can any CSS ninja jump on this please @kodadot/internal-dev

**Comment by Victor0355** [comment]
👋

**Comment by exezbcz** [comment]
@hassnian probably or?
