### ISSUE TITLE
Turn on batch minting on .hdd 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10215]
Weird things happened, lets turn this on because then it does not make sense having the item selector there 

<img width="568" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/93ed5373-60c8-40f4-9eed-c69373540fc2">

**Comment by exezbcz** [comment]
cc @Jarsen136 @preschian

**Comment by preschian** [comment]
ok, on it

**Comment by Jarsen136** [comment]
related to https://github.com/kodadot/nft-gallery/issues/10190
