### ISSUE TITLE
cookie popup styling 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10212]
since this got recently merged, lets sync it with our design change that was few weeks ago 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/be2c3f5a-88cf-4716-bc73-7d85771f2930)

## Data collecting 
google analytics are off by default? 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/ae3bf0af-222e-4ee3-8f7d-da46a70667b4)

## styling 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/d6ad20b2-057f-4383-8f52-9c437eb4fca2)

Accept should be the "main" button 

link to figma: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1287-18959&mode=design&t=wIR4vUyhVh1KHnUu-11

**Comment by hassnian** [comment]
fix: the cookie banner styles are applying to the regular buttons 

![CleanShot 2024-05-04 at 13 50 31](https://github.com/kodadot/nft-gallery/assets/44554284/d668c1ba-f879-4a81-94d4-fdfebe819e80)

**Comment by exezbcz** [comment]
these buttons can be button secondary outline rounded 
<img width="452" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/540bc28b-f63d-4ae2-8eeb-dbad74f9e05a">



![image](https://github.com/kodadot/nft-gallery/assets/90852205/6df62261-4662-4355-a821-7177d2aadcf6)
