### ISSUE TITLE
New wallets: Autoteleport: Got stuck on checking funds

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10225]
I tried to buy one [hdd](https://kodadot.xyz/ahp/drops/hdd) NFT. I had 0 DOT on AHK, so I used auto teleport, apparently I teleported 0.081 DOT.

Transaction here - teleport: https://polkadot.subscan.io/extrinsic/0x8f238f4bcb6a745e8d717274f3641f22370954ccedf656b9978dbe4353a6ed31 

I got stuck on checking funds. 
<img width="1199" alt="Screenshot 2024-05-05 at 13 50 32" src="https://github.com/kodadot/nft-gallery/assets/104380776/9d2f0c9b-bbe8-4a7f-bc14-45e635c413e3">

Wallet: 14SsBi9vrcKZciZTqyCrF5EzD2SPGmaEAcbyeuiDzsLUNC6Q

**Comment by JustLuuuu** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/104380776/4041206d-bf82-4550-b828-88f9c3aca447)

another person - first time buying NFT on KodaDot got stuck

**Comment by JustLuuuu** [comment]
I found out that probably happening only to new wallets. Not sure maybe @prury can test.

**Comment by prury** [comment]
> I found out that probably happening only to new wallets. Not sure maybe @prury can test.

made some tests and the problem happened to both new and old accounts

@hassnian may want to take a look at this

**Comment by hassnian** [comment]
@prury can't reproduce , can you provide a video ?

video: tried polkadot: 2.5 DOT -> ahp: 0 DOT , teleported 0.53 DOT and balance checked worked 


https://github.com/kodadot/nft-gallery/assets/44554284/f09e9055-d8c7-4091-a298-abf8a81bf77c

**Comment by prury** [comment]
> @prury can't reproduce , can you provide a video ?
> 
> video: tried polkadot: 2.5 DOT -> ahp: 0 DOT , teleported 0.53 DOT and balance checked worked
> CleanShot.2024-05-07.at.06.41.56.mp4

maybe the problem is with HDD drop/small teleported value:

[eternal check funds new account.webm](https://github.com/kodadot/nft-gallery/assets/36627808/6102462b-62af-4050-84d0-661ddfd54634)
