### ISSUE TITLE
information toast has close button out of the box 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10223]
<img width="704" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/32666b42-e80f-4133-9857-8098f30833e6">
<img width="93" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/f7192572-9f8a-4176-a60d-62cb78322366">

It probably can be renamed from "information" to "transaction is in block" 

and then: Transaction hash: 69Z802OH(long string here)  plus see the transaction id 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/cf0b2f78-2596-4203-a4e0-227e68f4a431)

**Comment by Jarsen136** [comment]
> <img alt="image" width="704" src="https://private-user-images.githubusercontent.com/90852205/327993914-32666b42-e80f-4133-9857-8098f30833e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTA3MzYsIm5iZiI6MTcxNDkxMDQzNiwicGF0aCI6Ii85MDg1MjIwNS8zMjc5OTM5MTQtMzI2NjZiNDItZTgwZi00MTMzLTk4NTctODA5OGYzMDgzM2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEyMDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YzViZjVhOTBmY2ZjMDk1YTA1NWYwODc0MjJkZmY4NzliZTg4ZmRkMGE2NzgwMWQ0ODU4YTk2NWZkNGQ3MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iuNdtTbYEh9jsI84QxznlF911KGxk6LwVDE-pNQAZqE"> <img alt="image" width="93" src="https://private-user-images.githubusercontent.com/90852205/327993920-f7192572-9f8a-4176-a60d-62cb78322366.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTA3MzYsIm5iZiI6MTcxNDkxMDQzNiwicGF0aCI6Ii85MDg1MjIwNS8zMjc5OTM5MjAtZjcxOTI1NzItOWY4YS00MTc2LWE2MGQtNjJjYjc4MzIyMzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEyMDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2OGMwNDhkYjJlNDQwMzY5ZDBmNjA4NDhlNjIyOTI4YzM2YTk3NDc4OTcxYmYwNDliNGQ5OGU3NmMwZTUyYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RW2lxMBj9vDZNGlxzNVc_4ALrHmvwDEIKleKb2P4bzQ">
> It probably can be renamed from "information" to "transaction is in block"
> 
> and then: Transaction hash: 69Z802OH(long string here) plus see the transaction id


As I got from the code, the transaction has not yet been sent to block when the information notification shows up. It means we could not show `View Tx` for it at that time.

No matter what, the issue of "information toast has close button out of the box  " could be fixed.

**Comment by exezbcz** [comment]
> As I got from the code, the transaction has not yet been sent to block when the information notification shows up. It means we could not show `View Tx` for it at that time.

then lets not even show the transaction hash, what can user do with that?

**Comment by Jarsen136** [comment]
> > As I got from the code, the transaction has not yet been sent to block when the information notification shows up. It means we could not show `View Tx` for it at that time.
> 
> then lets not even show the transaction hash, what can user do with that?

It just informs that tx has been generated and started broadcasting to the block.
When the tx is confirmed in the block, there will be another successful notification showing the block Id.

**Comment by exezbcz** [comment]
> It just informs that tx has been generated and started broadcasting to the block. When the tx is confirmed in the block, there will be another successful notification showing the block Id.

then lets skip the hash notif

**Comment by exezbcz** [comment]
we wont show the hash notif, can we please solve the x-mark out of the box for these notifs (check all please) 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/1804201d-cdb0-487d-a178-95ada00a4929)
