### ISSUE TITLE
Enable links in bio 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10237]
It is a small detail, but a nice feature if we plan to push farcaster 

it would be nice if the links in the bio are also links on koda 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/c2fa6d63-ffb0-4a0d-bbbf-16502c766b88)

![image](https://github.com/kodadot/nft-gallery/assets/90852205/3b411865-748e-482e-9ad3-4fdd3923e785)

same with probably twitter links etc. 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/85ee72a1-22c2-47bb-8b66-b78a4a326f74)

**Comment by panda6151025** [comment]
I want to fix it,

**Comment by panda6151025** [comment]
👋👋

**Comment by exezbcz** [comment]
@panda6151025 send the wave emoji only once
