### ISSUE TITLE
Confirm connection - information notif 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10234]
## GM

**When connecting the profile with farcaster, we should make it seamless** 

This notification will hopefully help 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/7f502a27-cb13-4a79-918c-3baaf4ec8a5c)

ideally, it should be displayed if the user got to the confirmation tab, but came back without confirming the connection - not sure if it's possible 
- if not, display it after a 4-second delay (the notifications timer only goes down when the user is present on the tab, right?) 

## Other warning toasts 

    if (userData?.data?.state !== 'completed') {
      console.error('No user data found')
      return
    }
    if (userData.data.nonce !== channel.data.nonce) {
      console.error('nonce mismatch')
      return
    }
    farcasterUserData.value = userData.data
 	} else {
    console.error('URL not found in channel data')
 	}

- user warning toast component

ref: 
- https://github.com/kodadot/nft-gallery/pull/10195#discussion_r1590313569

can anyone please rewrite the error codes to more user friendly language? 
- plus add something like "please try again later" or "report issue" if its farcaster thing or koda thing

**Comment by Victor0355** [comment]
👋
