### ISSUE TITLE
Option to remove img and clear profile 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10233]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/c10d478b-9d65-4c35-89b8-31d2b3502ad0)
- this will enable clearing the profile, once confirmed, it will close the modal and user will have "cleared" profile without any customizations 
- this state will display 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/eb77ccca-9616-4e67-93f3-92e768109ed4)

## confirmation 
- please add a small delay before the "you sure" link becomes clickable so there are no accidental clicks 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/63651e43-5f5d-4499-8695-aa6444400cea)

# Removing imgs
- one thing left compared to design is the option to remove the img when uploaded (currently we don't have the functionality) 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/4a24813b-0887-4b59-9f76-b484b97150ff)

please add the x-mark there 

### Notes
- updated in profile v3 figma
- https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=2116-13786&mode=design&t=neRjoavRuafpIGjV-11
![image](https://github.com/kodadot/nft-gallery/assets/90852205/9c2f4f1b-6e34-4cc0-b6bd-b9a0acdc8540)

**Comment by Victor0355** [comment]
👋
