### ISSUE TITLE
Display success message after transaction is in block 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10231]
**Display success message after transaction is in block** 

with @vikiival we discussed that it should be possible (preview should be already ready to display in the modal" 

Why it would be nice? Since the block time is quite long, and it takes ~30 seconds from signing to success, displaying the success message a bit earlier would decrease waiting times and make Polkadot feel a bit faster 

## Design and changes 
- after a transaction is in the block, display a success message 
- success message will have a different transaction status

![image](https://github.com/kodadot/nft-gallery/assets/90852205/a6bd2792-9a50-4646-a7b3-586de359efa2)
https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=6886-20058&mode=design&t=neRjoavRuafpIGjV-11

When it gets confirmed, it switches to the "confirmed status"

**Comment by Victor0355** [comment]
👋

**Comment by hassnian** [comment]
@Victor0355 are you working on this ?

**Comment by hassnian** [comment]
@preschian any way we can speed up this section, 

<details>
<summary>section inside `useUpdateMetadata`</summary>

![CleanShot 2024-05-14 at 17 05 01@2x](https://github.com/kodadot/nft-gallery/assets/44554284/17838635-65bc-4cd5-ae0a-f64e9af11e91)
</details>

would like to show the success step before the transaction status moves to `finalized`

atm it's requiring the transaction to be `finalized` to get the index

**Comment by preschian** [comment]
Ooh, I think it would be good if we could speed this up. This section is used to call the update metadata endpoint.

The solution I’m considering now is to create a queue service. Move that section to this service and ensure that the retry queue works if the index is not found or any other error occurs.
