### ISSUE TITLE
duplicated zeros in decimals

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10230]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/5f467eb4-0aaa-4971-a55f-6f354a9daad8)
It would be nice to make it consistent, the input shows 0,5 and the price is 0.5 

I am not sure if its automatic somehow, but i would prefer seeing 0.5 everywhere

**Comment by Victor0355** [comment]
👋

**Comment by asterism0115** [comment]
👋

**Comment by Victor0355** [comment]
👋

**Comment by exezbcz** [comment]
you got 24 hours to fix it @Victor0355

**Comment by exezbcz** [comment]
up for grabs

**Comment by uDaiko** [comment]
@exezbcz Is the issue here only linked to the 0.5 0,5 mismatch ( which seems to be fixed ) or also to the trailing zeroes with values such as 0.5000 ( which still seems to be the case )

**Comment by exezbcz** [comment]
@uDaiko true, tested it right now and seems like its fixed 

yeah, we can convert this issue to the trailing zero, would you like to be assigned? 👀

**Comment by uDaiko** [comment]
@exezbcz yeah you can assign me, thanks.
