### ISSUE TITLE
Remove giant squid from the code

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10268]
### Context

Giant Squid is not longer working and it is just throwing errors.

### Task

Remove usage of giantSquid from the app
and replace with profile fetch 

### REF

tried again, checking funds error seems to be gone, cancelled mint and tried again, received an error that i was not receiving before: 

[Gravação de tela de 09-05-2024 10:44:37.webm](https://github.com/kodadot/nft-gallery/assets/36627808/daa5c09c-de2b-4674-af38-7a936f48c518)

_Originally posted by @prury in https://github.com/kodadot/nft-gallery/issues/10264#issuecomment-2102697929_

**Comment by vikiival** [comment]
Assigning @daiagi to explain API for `profiles` then anyone can take

**Comment by daiagi** [comment]
GET https://profile-beta.kodadot.workers.dev/profiles

returns all profiles, without socials links and without followers info

GET https://profile-beta.kodadot.workers.dev/profiles/<substrate address format>

such as https://profile-beta.kodadot.workers.dev/profiles/5CfsizJUWeKfCDRgs91eMbQdFMcis9if9JM96vgpaCyxJ4j9


returns specific profile, including social links


notice that profiles are saved under **substrate** address


anything else?

**Comment by vikiival** [comment]
cc @kodadot/internal-dev up to grab

**Comment by Jarsen136** [comment]
👋
