### ISSUE TITLE
Top Collection buttons got reduced

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10267]
[Gravação de tela de 09-05-2024 12:07:42.webm](https://github.com/kodadot/nft-gallery/assets/36627808/080aaf60-ba4f-4beb-b915-eb67e3771ecf)

**Comment by FG-HJ** [comment]
how can i work to fix this

**Comment by FG-HJ** [comment]
:wave:

**Comment by prury** [comment]
> how can i work to fix this? I dont know how i can assign this work. then when bug appear? Explain correctly

check the browser address, you just need to compare canary.kodadot.xyz with beta.kodadot.xyz

**Comment by FG-HJ** [comment]
which style do we use? kodadot or sanary.kodadot?

**Comment by FG-HJ** [comment]
I checked project on my local pc.
but it has not issue like that.
I think server doesnt update with latest version.
please check again

**Comment by FG-HJ** [comment]
on my pc it is working as well
i think it is preview version, 
i want to check after latest version update.

**Comment by FG-HJ** [comment]
![Uploading Screenshot_2.png…]()

**Comment by FG-HJ** [comment]
![Screenshot_4](https://github.com/kodadot/nft-gallery/assets/168608006/016d7f90-9d5b-4d6c-8ad8-430c6d8407b1)

![Screenshot_3](https://github.com/kodadot/nft-gallery/assets/168608006/709a1fb5-fe89-4fab-85f2-8f6980e9fd67)
![Screenshot_4](https://github.com/kodadot/nft-gallery/assets/168608006/3e32eea6-b3be-4ee7-b4e8-edee6ff8b75f)
![Screenshot_2](https://github.com/kodadot/nft-gallery/assets/168608006/5c435881-d675-406a-ad38-f3b14e2de98b)

**Comment by FG-HJ** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/168608006/7af40c7c-d983-4c45-b245-98aea4fd1eb5)
This is git history
I think this happened when project is built or kodadot isnt updated.

**Comment by hassnian** [comment]
> ![image](https://private-user-images.githubusercontent.com/168608006/329428493-7af40c7c-d983-4c45-b245-98aea4fd1eb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTE1MDAsIm5iZiI6MTcxNTQxMTIwMCwicGF0aCI6Ii8xNjg2MDgwMDYvMzI5NDI4NDkzLTdhZjQwYzdjLWQ5ODMtNGM0NS1iMjQ1LTk4YWVhNGZkMWViNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNzA2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTBhODVhMDVlYWVjZTY1ZTEyNGViYjczNDYyY2Y2NjE5MWE3MmQ2ZWZlZWUzZmEyOTg1NTA4MTMwNTkzZDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.daR7zQr7V30gbtq5wjscO7gRtYpmlWePdlYNMVAIS4Y) This is git history I think this happened when project is built or kodadot isnt updated.

there was a change in the `NeoButton` styles

you need to override those styles where `NeoButton` is being used , in this case `TopCollections.vue`, [hint](https://tailwindcss.com/docs/configuration#important-modifier) :)

**Comment by FG-HJ** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/168608006/cc699f21-3870-4a73-9004-23488a42a097)
i cannt check your image
can you upload it again?

**Comment by hassnian** [comment]
it's your image , the link has expired
![CleanShot 2024-05-13 at 10 02 56@2x](https://github.com/kodadot/nft-gallery/assets/44554284/880df80d-0139-428a-a206-ef4d9eaba24b)

**Comment by FG-HJ** [comment]
can you check this issue
i think it is fix already.
or can you give me correct width.

**Comment by FG-HJ** [comment]
why did you unassigned this issue from me?
