### ISSUE TITLE
Button style bug

### ISSUE THREAD

**Issue by FG-HJ** [kodadot/nft-gallery#10269]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

button style bug
![Screenshot_1](https://github.com/kodadot/nft-gallery/assets/168608006/569eb188-bb30-4e4e-8272-f90d77554d50)

### Please reproduce in steps

After page load, we can see bug on page right button of  "Stay in the loop and Get"

### Expected Behavior

page load
scroll down
show button

### Are you logged in?

None

### Screenshots

![Screenshot_1](https://github.com/kodadot/nft-gallery/assets/168608006/26e3ab0e-91eb-4365-acc8-692af4f858eb)

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by springshine0925** [comment]
👋

**Comment by 0129general** [comment]
👋

**Comment by springshine0925** [comment]
Excuse me.
Who is it?

**Comment by springshine0925** [comment]
I have just fixed this bug but this bug was fixed in kodadot.xyz already.
what I can I do that?
