### ISSUE TITLE
Base collections on Koda: missing description

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10279]
All (6 that we have) Base collections on Koda have missing descriptions.

<img width="1672" alt="Screenshot 2024-05-12 at 15 05 41" src="https://github.com/kodadot/nft-gallery/assets/104380776/65724066-26c0-4483-ac0a-ee49f6743666">

[This](https://kodadot.xyz/base/collection/0x25194dfc7981d8a13367fe19b5b1c5fc010d535f?page=Infinity) collection for example has description but we are not showing it. Description can be found on Zora marketplace [here](https://zora.co/collect/base:0x25194dfc7981d8a13367fe19b5b1c5fc010d535f).

**Comment by Jarsen136** [comment]
The direct reason is missing `meta` data for `Base` chain from the indexer .  cc @vikiival 

![image](https://github.com/kodadot/nft-gallery/assets/31397967/982fc301-ba35-4b08-a9d6-aed61417307e)

![image](https://github.com/kodadot/nft-gallery/assets/31397967/c1306c6c-211a-40e4-b110-dcc80c4f492b)
