### ISSUE TITLE
Code-checker: Error message

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10271]
Hello, one artist is working on his art, and the code-checker is working only like the half-baked product. Artist: pizza punk.

Code: [Between_the_bars_Cool3_-_Koda_2024_05_10_07_27_03.zip](https://github.com/kodadot/nft-gallery/files/15271674/Between_the_bars_Cool3_-_Koda_2024_05_10_07_27_03.zip)
Code as a URL: https://editor.p5js.org/codingJM/sketches/CGGtX6ul6

Generate button with art works, but the checkpoints are not working. Art is animated, looks that its very rersponsive:
<img width="1656" alt="Screenshot 2024-05-10 at 09 31 35" src="https://github.com/kodadot/nft-gallery/assets/104380776/50bff49c-12f6-4b56-a6cc-4ed494105841">

Pls, can someone check this? Artist needs to know whats happening + we need a proper message explaining why is there an error.

**Comment by daiagi** [comment]
update:

the art is not reading url params. hence this error

we need to convert this to a :x: / :heavy_check_mark:  checkpoint with explanation and link

like the rest of them

**Comment by JustLuuuu** [comment]
pls once we have an explanation and the suggested solution, also let me know so I can add it to the Hello page. Also not sure why he cannot see the rest of checkpoints

**Comment by daiagi** [comment]
> Also not sure why he cannot see the rest of checkpoints

these were the specs in the original design.
