### ISSUE TITLE
Make EVM wallet connector

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10284]
### Is your feature request related to a problem?

I would like to connect my EVM wallets:
- Metamask
- Talisman
- Coinbase wallet

To the Koda. 

### Describe the solution you would like

I would like to see a tabs DOT / EVM where default will be determined by active chain

You can obtain it by `chainProperties.vm` https://github.com/kodadot/nft-gallery/blob/541d7f500e31e025294cbe4aeed57fd5643059c3/libs/static/src/types.ts#L32

![Screenshot 2024-05-13 at 12 40 09](https://github.com/kodadot/nft-gallery/assets/22471030/92b658b9-d97f-4435-935d-e18d4884430e)

## Impl

amazing @brano-hozza hacked EVM login last weekend so code can be reused

https://github.com/Retiazky/shuffle-dao

### Describe alternatives you have considered

We have considered Web3Modal - https://github.com/kodadot/nft-gallery/issues/10137
But that does not work

**Comment by hassnian** [comment]
@exezbcz need a design , thanks

**Comment by vikiival** [comment]
Exez is OOO until end of may. 

Proposed solution is already described above

**Comment by exezbcz** [comment]
letsgo with this 
<img width="293" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/b7a656f7-978a-4ce4-a3ef-cd723db51219">

not sure if this solution is super optimal but don't want to block

**Comment by exezbcz** [comment]
when switched to evm, lets show metamask, rabby, rainbow, walletconnect

**Comment by hassnian** [comment]
> or @exezbcz why cannot we use web3modal for evm only?

👀

**Comment by exezbcz** [comment]
@hassnian sorry for the late response, yup sure, lets use web3modal
- its not optimal solution, but IMO good for start
- change the "substrate" to "polkadot" 
- once evm is clicked, it switches the tab and displays login with web3modal




once you connect evm wallet, you can only see evm network, polkadot is disabled
 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/a7a91ad2-2578-463e-b4d4-38d045a9d7d0)
