### ISSUE TITLE
Royalty is not correctly shown

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10288]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

We have set the collection royalty to 10% that is does not shown on the page

### Please reproduce in steps

1. Go to https://kodadot.xyz/ahp/collection/130
2. there is just `%` logo

### Expected Behavior

I expect to see `10 %`

### Are you logged in?

None

### Screenshots

![Screenshot 2024-05-13 at 17 47 33](https://github.com/kodadot/nft-gallery/assets/22471030/202ccf6a-04c0-4333-850c-f08001b1adb8)

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
It's because of missing `royalty` data from subsquid  @vikiival 
(This only happened to this collection, other collections show royalty correctly `/ahp/collection/117`)

![image](https://github.com/kodadot/nft-gallery/assets/31397967/7e8c8b1a-3faf-4192-bbb3-d2d58731976c)

The royalty section and `%` sign should not be there if the `royalty` data is null.

**Comment by vikiival** [comment]
subquid has the data 

![Screenshot 2024-05-14 at 11 51 43](https://github.com/kodadot/nft-gallery/assets/22471030/6ca81a60-ddcc-4bcb-a2f2-ffa33b1256e5)

**Comment by Jarsen136** [comment]
> subquid has the data
> 
> ![Screenshot 2024-05-14 at 11 51 43](https://private-user-images.githubusercontent.com/22471030/330379665-6ca81a60-ddcc-4bcb-a2f2-ffa33b1256e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODEzNjAsIm5iZiI6MTcxNTY4MTA2MCwicGF0aCI6Ii8yMjQ3MTAzMC8zMzAzNzk2NjUtNmNhODFhNjAtZGRjYy00YmNiLWEyZjItZmZhMzNiMTI1NmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEwMDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NDE2YjJkMmYwNWM4NTRlOWQ0NWQ5YjNhMzBlZjBiNmYyYmQxMTA1NzRiN2RlNGU5MGU4OTlkNmRlZDVkNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zhXh99TmG5eN48qq2rXz6-H-FY_1J-91zTfGd0KWEPY)

That's why it got fixed now. Yesterday it's null : ) @vikiival 
![image](https://github.com/kodadot/nft-gallery/assets/31397967/94e06ade-1750-40de-9536-f6425a0bdb70)

**Comment by vikiival** [comment]
Prob ultra long cache!
