### ISSUE TITLE
Base collections on Koda: naming is off

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10280]
We are showing the number of the NFT double. . Choose Base network, explore collections, open for example this collection: https://kodadot.xyz/base/collection/0x25194dfc7981d8a13367fe19b5b1c5fc010d535f

### Name of the NFT on **Koda**:
<img width="511" alt="Screenshot 2024-05-12 at 15 04 00" src="https://github.com/kodadot/nft-gallery/assets/104380776/6001a1eb-0f72-42b8-abad-b7081f718001">

### Original naming:
<img width="436" alt="Screenshot 2024-05-12 at 15 10 22" src="https://github.com/kodadot/nft-gallery/assets/104380776/bca8bc11-c073-4603-ba0d-18c471052fbf">

**Comment by Jarsen136** [comment]
There are two solutions but on the indexer side. @vikiival 
1. Move the SN `#11` to the name's tail 
2. Remove the SN from the nft name

![image](https://github.com/kodadot/nft-gallery/assets/31397967/33af5e92-674c-45a7-b995-df04aab43161)

**Comment by vikiival** [comment]
Please consider non-koda collections as obsolete
