### ISSUE TITLE
Fill up return types 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1028]
As we are migrating to #843 #912 Would be perfect to mitigate these errors in the Nuxt implementation

![image](https://user-images.githubusercontent.com/5887929/140337391-a6df6308-834d-4d1d-b8c3-0b50f7448d4f.png)

**Comment by yangwao** [comment]
@dezine2dev is this resolved?

**Comment by dezine2dev** [comment]
Yes
