### ISSUE TITLE
incosistent 'buy now' / 'listed' filter label

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#10283]
go to exlpore/items

toggle chains

filter label is sometimes 'listed' sometimes 'buy now'

![image](https://github.com/kodadot/nft-gallery/assets/22791238/52e8b9ff-793c-4c83-85b5-897b833af572)

![image](https://github.com/kodadot/nft-gallery/assets/22791238/a6478b9c-49c5-4c5a-b91f-3793bc8341bf)

assuming it all should be 'listed'

and it  is weird that it is even chain related

cc @exezbcz

**Comment by prury** [comment]
@daiagi i made that change, if you are on RMRK chain it will show listed because buy is deactivated there

**Comment by Jarsen136** [comment]
> @daiagi i made that change, if you are on RMRK chain it will show listed because buy is deactivated there

Then I would close the issue for now
