### ISSUE TITLE
Code checker incorrectly checks for WEBGL

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10282]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

We have already issues in the past regarding WebGL art
where codechecker issued false negatives

- https://github.com/kodadot/ops-internal/issues/1579
- https://github.com/kodadot/ops-internal/issues/1639

### Please reproduce in steps

Use any art linked above code checker will report 

✅ NO WEBGL

### Expected Behavior

I expect that codechecker will check for usages of either

```js
createCanvas(a, b, WEBGL)
```

or 

```js
createGraphics(size, size, WEBGL)
```

> This could also trigger strange behaviour
Or the simplest solution is to check for `WEBGL` in the code :) 

### Screenshots

![Screenshot 2024-05-13 at 12 06 07](https://github.com/kodadot/nft-gallery/assets/22471030/cd1c8a9f-b8e5-4dc9-abd6-6028ad432f82)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daiagi** [comment]
as for Steve's work

the webgl is not inside the main `sketch.js` file
but hidden inside `bgAndText.js`

therefore what is required is to expend canvas realted checks to run on all `.js` files
not only on `sketch.js`



```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Simple Strokes</title>
    <script src="./p5.min.js"></script>
    <link rel="stylesheet" type="text/css" href="style.css">
    <meta charset="utf-8" />
  </head>
  <body>
    <main>
    </main>
    <script src="./sketch.js"></script>
     <script src="./colors.js"></script>
    <script src="./grain.js"></script>
    <script src="./bgAndText.js"></script>
  </body>
</html>
```

**Comment by vikiival** [comment]
all .js files
 
 except p5.js :D
