### ISSUE TITLE
Put dotscanner into profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1029]
Would be nice to have at least two block explorers, I would put it next to sub scan in profile

This is for this address
https://dotscanner.com/Kusama/account/Ef8Yfnnc2xcWsHPxYrMccYBEB4dTmqYsC2D9vtc9cqRr7cX

**Comment by prachi00** [comment]
@yangwao I'll pick this up, just need more clarity, so this should be put somewhere here?
<img width="391" alt="Screenshot 2021-11-05 at 12 43 48 PM" src="https://user-images.githubusercontent.com/39299315/140472374-ad689490-1a1e-421a-95a6-dc1478ef3347.png">
