### ISSUE TITLE
I can try to follow someone without having a profile setup

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#10290]
### What happened?

I do not have a profile made

When I try to follow it does not ask me to setup a profile first 

https://github.com/kodadot/nft-gallery/assets/44554284/48cedabe-dc29-473f-a032-9a7fd0836063

**Comment by Jarsen136** [comment]
Maybe show a notification to explain you should set up a profile first. Or directly open the profile-creating modal?
wdyt? @exezbcz

**Comment by springshine0925** [comment]
👋

**Comment by hassnian** [comment]
@springshine0925 this issue is not ready to be picked , as you can see [here](https://github.com/kodadot/nft-gallery/issues/10290#issuecomment-2109522446) we have to first define what needs to be done.

**Comment by exezbcz** [comment]
Directly opening the modal would be a better solution
