### ISSUE TITLE
Showing wrong number of NFTs in Drops

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10297]
memoverse showing 0 NFTs

<img width="1454" alt="Screenshot 2024-05-14 at 15 07 33" src="https://github.com/kodadot/nft-gallery/assets/104380776/2c1f3468-522a-400a-8d5a-e9623091590c">
<img width="996" alt="Screenshot 2024-05-14 at 15 07 40" src="https://github.com/kodadot/nft-gallery/assets/104380776/fabc0367-10ba-470c-a843-4bac3cf1efd4">

**Comment by Jarsen136** [comment]
There is a delay in the data on chain
 
![image](https://github.com/kodadot/nft-gallery/assets/31397967/722dc134-0473-4a17-bc31-92795a85ba03)
