### ISSUE TITLE
Mass mint: Wrong pricing

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10308]
This artist: 14ihwHKSUX9UNTvHqq8ppUtBLh1i271U8wvR4TwZvUFvvLCz minting this collection wrote me that she had an issue with minting using mass mint. She selected the price to be 1 DOT and after mass mint the price of the art was 100 DOT. She had to manually change pricing for each NFT. 

<img width="1650" alt="Screenshot 2024-05-16 at 12 15 01" src="https://github.com/kodadot/nft-gallery/assets/104380776/3ae0079e-4496-49f7-9ea3-37744e0e49c9">

can anyone check what happened? She is sure that she selected price 1.

**Comment by prury** [comment]
@JustLuuuu it went fine for me, listed some items using kodadot.xyz on AHP: 

[mass listing.webm](https://github.com/kodadot/nft-gallery/assets/36627808/339c468f-b49e-4396-b3e6-6d5ad591a794)
