### ISSUE TITLE
Enough: Change the date on the upcoming drop 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10303]
This drop:
https://kodadot.xyz/ahp/drops/enough

Move date from 16th to 23rd pls.

There is an issue with the code artist is trying to change. @vikiival maybe?

**Comment by vikiival** [comment]
Moved on CF 

![Screenshot 2024-05-15 at 13 42 46](https://github.com/kodadot/nft-gallery/assets/22471030/2dcfb312-aa23-4108-a1e2-25ebe462721f)

**Comment by JustLuuuu** [comment]
Thank you!
