### ISSUE TITLE
ESTRUTURA: Missing mints

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10317]
Our newerst Drop on Farcaster has some error mints. I cannot verify this on KodaDot as we are not showing Base mints, but if you check Opensea some mints are missing. 
<img width="1295" alt="Screenshot 2024-05-17 at 09 30 36" src="https://github.com/kodadot/nft-gallery/assets/104380776/1a52f368-eaa2-4612-8739-0836ea55aea0">

Collection
---

Collection: ESTRUTURA by Morbeck
Opensea collection: https://opensea.io/collection/estrutura
KodaDot Mintframe: https://warpcast.com/morbeck-art/0x20eaf96a

Missing NFTs 
---
- https://opensea.io/assets/base/0xbbf5c72ac002f4f6e074c7ad47fd278deb5c740e/5
- https://opensea.io/assets/base/0xbbf5c72ac002f4f6e074c7ad47fd278deb5c740e/4
- https://opensea.io/assets/base/0xbbf5c72ac002f4f6e074c7ad47fd278deb5c740e/2
- https://opensea.io/assets/base/0xbbf5c72ac002f4f6e074c7ad47fd278deb5c740e/3

Pls fix, its been almost one day after mint and they are still not showing.

**Comment by FG-HJ** [comment]
:wave:

**Comment by preschian** [comment]
This is a similar issue to what we had. On OpenSea, you can click the "Refresh metadata" button (top right section)

<img width="281" alt="Screenshot 2024-05-18 at 10 43 20" src="https://github.com/kodadot/nft-gallery/assets/734428/1f1eba29-7848-4784-b2c5-516731c8d4e2">

On tofunft had a good explicit description about it. related: https://github.com/kodadot/nft-gallery/issues/5214
