### ISSUE TITLE
Do not show empty collections

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1031]
Right now it doesn't matter to open empty collections as users would like to peak or collect it. 
Collections which doesn't offer anything inside for them, i.e. has 0 items, do not show them

![image](https://user-images.githubusercontent.com/5887929/140482211-05dca17b-96ea-49f1-baf3-3639b32b3571.png)

**Comment by TK-Development** [comment]
I'll take a look.

**Comment by yangwao** [comment]
Continue to #1357
