### ISSUE TITLE
Fold description by default

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1032]
We would put emphasis on content of collections and let's fold description by default

![image](https://user-images.githubusercontent.com/5887929/140482907-11e03b89-3a25-47c3-a04b-68c1d2884ac7.png)

**Comment by prachi00** [comment]
@yangwao put emphasis on collectors, what exactly does this mean?

**Comment by yangwao** [comment]
> @yangwao put emphasis on collectors, what exactly does this mean?

It was a typo, it should be there "We would put emphasis on the content of collections and let's fold description by default"
So let's use fold component from Buefy to fold Description by default :)
