### ISSUE TITLE
General reconsideration of "Voucher feature"

### ISSUE THREAD

**Issue by ThomasssArt** [kodadot/nft-gallery#10332]
First of all, I would like to say that this is my opinion and not everyone has to share it!

To me this "Sign up and receive a 20$ voucher..." looks like I'm shopping at a discount store. It does not evoke the feeling that im on a marketplace which will be one of the leading marketplaces in the future! To me, it just doesn't look professional.

I dont know how many subscribers you got with this offer but i would really think of deleting it!

![image](https://github.com/kodadot/nft-gallery/assets/60002234/b196f69b-2b1e-45b3-aa4e-e31f15258a74)

**Comment by exezbcz** [comment]
yeah redundant right now, newsletter service is not that active now 

can you please remove it? @kodadot/internal-dev
