### ISSUE TITLE
Minting previews not showing

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10340]
both in modals or recent mints: 
the art can only be seen on gallery item

![image](https://github.com/kodadot/nft-gallery/assets/36627808/d5095155-433b-4b0c-be46-8452b268656a)

**Comment by ThomasssArt** [comment]
Isnt this the gallery view?
![image](https://github.com/kodadot/nft-gallery/assets/60002234/30bdbc6b-2647-4298-9f9d-fb8fc75f5701)

**Comment by ThomasssArt** [comment]
Thats how it looks in my profile
![image](https://github.com/kodadot/nft-gallery/assets/60002234/54b8bfff-17b3-4f89-9d22-9f11c67d8efe)

**Comment by prury** [comment]
> Or is this the gallery item? 

this is the gallery item

**Comment by prury** [comment]
> Thats how it looks in my profile ![image](https://private-user-

same, unfortunately

**Comment by ThomasssArt** [comment]
Cant see the image you shared Ramo. 

How is it possible that we again have such huge issues on a drop?! This is not just a small bug this is a huge issue imo. 

This should be fixed ASAP! With asap i mean today. Collectors cant see their mints thats worst case scenario!

**Comment by vikiival** [comment]
Capture is returning response, checking

![Screenshot 2024-05-23 at 21 48 33](https://github.com/kodadot/nft-gallery/assets/22471030/459136c2-0ae6-4b93-b07b-1d0aede2487a)

**Comment by ThomasssArt** [comment]
Still not fixed...
![image](https://github.com/kodadot/nft-gallery/assets/60002234/129c6c32-4527-4678-bf5b-8413cd5dbf35)

**Comment by vikiival** [comment]
Cc @preschian

**Comment by preschian** [comment]
try open in incognito, that was from cache

**Comment by ThomasssArt** [comment]
In icognito mode it worked (on mobile phone)
