### ISSUE TITLE
Experimental Add shadow under pagination buttons

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1034]
We should bit starting removing contrast feature from kodadot, 
to not be much intrusive to eye and ease visual perception 

I would tentatively try to change on control buttons
- add shadows under buttons 
- change text color from white to silver #c0c0c0 
- for headers and text user reads we could gainsboro #dcdcdc  

Also check where we have overides.

![image](https://user-images.githubusercontent.com/5887929/140492529-fcadbf0e-d701-4dea-b79e-61c9d4b99a9e.png)
![image](https://user-images.githubusercontent.com/5887929/140492651-82e2c03d-46d1-4599-847a-576cd349b58e.png)

**Comment by prachi00** [comment]
@yangwao I'll take a look at this

**Comment by yangwao** [comment]
> @yangwao I'll take a look at this

Assigned! Let's do it! :)

**Comment by yangwao** [comment]
> We should bit starting removing contrast feature from kodadot, to not be much intrusive to eye and ease visual perception
> 
> I would tentatively try to change on control buttons
> 
> * add shadows under buttons

shadows like we use on other stuff in kodadot, you may seem one we use under cards in gallery for example. 
> * change text color from white to silver #c0c0c0

text color on buttons where is white right now
> * for headers and text user reads we could gainsboro #dcdcdc


for headers and text -- I mean that was for something like description and title where is white present. 

For pink borders, let's go with opacity 0.4
rgb(255 20 147 / 40%);
![image](https://user-images.githubusercontent.com/5887929/141463548-06424d11-69fb-4088-b6f7-2c36f153fa53.png)

Looks great with pagination component 
rgb(255 20 147 / 40%);
with #c0c0c0 color
![image](https://user-images.githubusercontent.com/5887929/141463991-52e4ec96-fbd2-4ac8-8bae-99dfe47158cd.png)
