### ISSUE TITLE
Time for loading drop description increased

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10342]
Looking at recent tests made me realize that drops description are taking longer than normal to load(more than 5 seconds). (also happens to the `created by` field)

Can i increase the test timeout? sure

but what caused this problem? 

[Screencast from 2024-05-23 17-59-49.webm](https://github.com/kodadot/nft-gallery/assets/36627808/d8d40772-8d5d-46a0-9787-9323ba8f1adc)

**Comment by Jarsen136** [comment]
https://kodadot.xyz/ahp/drops/aeroloom
![image](https://github.com/kodadot/nft-gallery/assets/31397967/702647e1-f1f1-47f5-a90e-bea90f6e7e5e)
![image](https://github.com/kodadot/nft-gallery/assets/31397967/6ea34bd1-0374-463e-9c5e-ee1d8956a6e0)
![image](https://github.com/kodadot/nft-gallery/assets/31397967/f96f489b-a50b-4d44-bf92-2b12a3f79830)

There are several invalid and empty requests sent before fetching the collection data. It costs double the graphql query time to get the final data. I will fix it.
