### ISSUE TITLE
Enough: Predefined function not working!

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10348]
Hey guys, another issue with collection Enough: https://kodadot.xyz/ahp/gallery/130-2405249231

You can not use the function (just press "s" key) to save the work when you open art on fullscreen.

**Comment by ThomasssArt** [comment]
@JustLuuuu use the keyboard keys is never possible in this view. What you see is just a thumbnail and not the "work" itself. You need to open it with the "open in new tab" feature and there you see hte "real" work and you can also save it with using the keyboard keys.
