### ISSUE TITLE
Metadata not working : All Drops

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10346]
previews for #12 #13 not working

https://kodadot.xyz/ahp/drops/enough

![image](https://github.com/kodadot/nft-gallery/assets/104380776/03f6031b-b7b9-43d0-959a-d3edf1ec062a)

**Comment by preschian** [comment]
This is not a preview, but the metadata has not been updated. So, it will fall back into the collection image.

Does anyone know about [waifu.deno.dev](https://github.com/kodadot/private-workers/blob/94eef689858a6331905931f926ec87ca74efacb3/services/fxart/src/utils/mint.ts#L3) service? @kodadot/internal-dev. As far as I know, only @vikiival knows about that service. The endpoint returned 200, but extrinsic never triggered https://assethub-polkadot.subscan.io/account/15CoYMEnJhhWHvdEPXDuTBnZKXwrJzMQdcMwcHGsVx5kXYvW. Both `ahk` and `ahp` don't work; **it will affect all drops minting**.

The last extrinsic is this one. Does anyone have a clue about this one?
```
collection: 139
item: 1
data: https://media.exiledracers.com/dot/metadata/koda_test_poap3.json
```

Currently, these are the affected items on ahp:
```
Items: [
  'https://kodadot.xyz/ahp/gallery/130-2405264300',
  'https://kodadot.xyz/ahp/gallery/130-2405249231',
  'https://kodadot.xyz/ahp/gallery/127-2405420603'
]
```

**Comment by vikiival** [comment]
Yes, It has been a victim of ddos attack. Looks like cron is glitched now

**Comment by preschian** [comment]
i see, anything that we can help?

**Comment by vikiival** [comment]
running again 
https://assethub-polkadot.subscan.io/extrinsic/0x84c00b2e1f5853362cd6bef28668e9d5ecb01951c7b979c06291c15bd28cb105

**Comment by preschian** [comment]
> running again

thank you~
safe to close
