### ISSUE TITLE
Switch drop creators to artists offchain profiles (created by) 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10359]
This took us quite a long time, but we should slowly switch the drops to show the actual artist

<img width="784" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/69ee4baa-1dc1-4b0a-afea-b2a086aca769">

will drop how it will look

**Comment by exezbcz** [comment]
could you please point me if there is anything needed on the backend side? 
cc @vikiival

**Comment by vikiival** [comment]
> could you please point me if there is anything needed on the backend side?

Yes, EVM won't work :) 
@daiagi

**Comment by exezbcz** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/644af4df-ae40-4732-a408-2af527adc3d0)

this is how it could work
- first row - offchain name, if not present, there will be address
- second row, address

**Comment by exezbcz** [comment]
@JustLuuuu could you please tell few of the recent artist to create their profile? So we can start assigning them the drop

**Comment by JustLuuuu** [comment]
> @JustLuuuu could you please tell few of the recent artist to create their profile? So we can start assigning them the drop

Here I will try to add all artists soon: https://github.com/kodadot/ops-internal/issues/1718#issuecomment-2173578189

**Comment by exezbcz** [comment]
gm gm, I am waiting for this to show artist on the drop card as well

**Comment by vikiival** [comment]
can someone check pls ?

**Comment by hassnian** [comment]
> can someone check pls ?

on it
