### ISSUE TITLE
Mint modals no longer showing on canary - vue query hooks

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10356]
Trying to mint in any drop page: 

transaction occurs normally, but modals are not displayed.
production env working normally.

[Screencast from 2024-05-27 10-42-50.webm](https://github.com/kodadot/nft-gallery/assets/36627808/1b52717b-ce1b-4484-9cef-d33e159ab8b2)

![Video](https://github.com/kodadot/nft-gallery/assets/36627808/1b52717b-ce1b-4484-9cef-d33e159ab8b2)

**Comment by vikiival** [comment]
Cc @Jarsen136 / @hassnian
