### ISSUE TITLE
Use new logo on our app 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10369]
![KODA_fill_dark](https://github.com/kodadot/nft-gallery/assets/90852205/0919bc1c-9061-4f57-a75d-7346138f5e38)
![KODA_fill_dark](https://github.com/kodadot/nft-gallery/assets/90852205/e04ea409-9e81-4b35-9ad9-134bd60d7c36)
![KODA_transparent_dark](https://github.com/kodadot/nft-gallery/assets/90852205/c3f1ad22-6c9b-4b0a-bc2a-d6d4468baf25)
![KODA_transparent_dark](https://github.com/kodadot/nft-gallery/assets/90852205/fd195159-e627-4961-9c55-4c09c64aab92)
------------

Light mode:
![KODA_fill](https://github.com/kodadot/nft-gallery/assets/90852205/7d0331c4-3979-4080-9295-a2ed575df7b6)
![KODA_fill](https://github.com/kodadot/nft-gallery/assets/90852205/fc4bb929-1a83-47c7-82ed-412f3e37ef9c)
![KODA_transparent](https://github.com/kodadot/nft-gallery/assets/90852205/09dc20de-bafb-4118-a646-ca4a29daea7d)
![KODA_transparent](https://github.com/kodadot/nft-gallery/assets/90852205/30cee792-519a-443b-822e-1d3e035ae2d9)

## Info
- there is both filled and transparent, png and SVG

**Comment by Jarsen136** [comment]
@exezbcz Thanks for putting all the images into the description of this issue. Unfortunately, Github does not allow us to download the image resources directly, so you have to move them into Figma for us.

**Comment by exezbcz** [comment]
@Jarsen136 ah did not know that, on it

**Comment by vikiival** [comment]
>  Unfortunately, Github does not allow us to download the image resources directly, so you have to move them into Figma for us.


Or am I missing something?


![Screenshot 2024-06-03 at 15 34 23](https://github.com/kodadot/nft-gallery/assets/22471030/54cb388a-f6d1-4a4d-928a-b86f18119301)

**Comment by exezbcz** [comment]
here in the handoff: 
<img width="789" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/6f96748e-6fb7-4f4f-9d9f-f098454cc884">

https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=1287-18959&t=G2zvZIs0tHFhrVS2-11

**Comment by Jarsen136** [comment]
> > Unfortunately, Github does not allow us to download the image resources directly, so you have to move them into Figma for us.
> 
> Or am I missing something?
> 

It works now but I don't know why. It may be my first internet use ; )

**Comment by Jarsen136** [comment]
Oh, I just found an issue. The `beta` logo should also be there... Could you please add it? @exezbcz 

![image](https://github.com/kodadot/nft-gallery/assets/31397967/5f23e51c-4747-4224-bca2-b8775f03461f)
![image](https://github.com/kodadot/nft-gallery/assets/31397967/22da89bc-c8dd-4216-be9f-257169c47e28)

**Comment by exezbcz** [comment]
> Oh, I just found an issue. The `beta` logo should also be there... Could you please add it? @exezbcz 
> 
> 
> 
> ![image](https://github.com/kodadot/nft-gallery/assets/31397967/5f23e51c-4747-4224-bca2-b8775f03461f)
> 
> ![image](https://github.com/kodadot/nft-gallery/assets/31397967/22da89bc-c8dd-4216-be9f-257169c47e28)
> 
> 

True, forgot like always when changing the logo xd

**Comment by exezbcz** [comment]
@Jarsen136 added

<img width="954" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/4c11e438-9e0c-4a22-9132-066beb344272">


feel free to export the desired format from figma - the logo is grouped wit the "beta" 

https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=1287-18959&t=z6pQYJPkqEu9NtEj-11
