### ISSUE TITLE
Put collections status to between artist and actions

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1037]
Till we figure out better design for collection, to save space on smaller screens, let's put collection status like 
items, owned, floor price, traded, &c between artist profile and actions.

Put it in order like
| items | floor price | volume traded | 
| :--: | :--: | :--: |
| owned | distribution  | 24h volume traded |

distribution == owned items by users / unique owners 

![image](https://user-images.githubusercontent.com/5887929/140496634-c3e0fa13-b27f-42f2-8ef9-a263a574e7ad.png)

**Comment by prachi00** [comment]
@yangwao I will pick this up

**Comment by yangwao** [comment]
> @yangwao I will pick this up

Sure, go on!

**Comment by prachi00** [comment]
<img width="1438" alt="Screenshot 2021-11-09 at 9 15 28 PM" src="https://user-images.githubusercontent.com/39299315/140956608-a5293fb8-0e95-4ee3-9024-0f7acdc33239.png">

@yangwao is this looking okay? any changes I must do before raising PR?
