### ISSUE TITLE
Fontawesome on koda.art 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10371]
Right now we dont have icons on this domain 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/b0fb6957-d513-4712-a4d9-65051289b728)
![image](https://github.com/kodadot/nft-gallery/assets/90852205/ebab7cf3-d1d0-48b9-8362-66ba13f99c7d)

**Comment by exezbcz** [comment]
cc @preschian

**Comment by preschian** [comment]
Added, it probably takes some time to resolve the DNS update

```
koda.art
*.koda.art
```

**Comment by vikiival** [comment]
@exezbcz can we close?

**Comment by preschian** [comment]
looks ok

<img width="2672" alt="Screenshot 2024-06-04 at 22 56 51" src="https://github.com/kodadot/nft-gallery/assets/734428/4895283c-dc0e-4b15-b19e-fcd9025be848">
