### ISSUE TITLE
Create profile dies on Base

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10382]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

Since the button allowes me to to it, I tried to create a profile with my EVM wallet.
Sadly the whole component died

### Please reproduce in steps

1. - https://github.com/kodadot/nft-gallery/pull/10354
2. Log in
3. Go to profile
4. Try to create profile

### Expected Behavior

1. I expect that I am able to create a profile

### Are you logged in?

None

### Screenshots

![Screenshot 2024-06-03 at 13 59 52](https://github.com/kodadot/nft-gallery/assets/22471030/6e81e632-389b-4ce4-a3e4-9dadd5a89bca)

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
will take a look after the EVM wallet PR was merged.

**Comment by exezbcz** [comment]
waiting for: 
- https://github.com/kodadot/nft-gallery/pull/10354

**Comment by vikiival** [comment]
> waiting for:
> 
> * [feat: Make EVM wallet connector #10354](https://github.com/kodadot/nft-gallery/pull/10354)

So let's go with for now :) 
- #10401
