### ISSUE TITLE
Temp fix: Hide elements in sidebar for EVM 

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10380]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

As a normal user I would be waiting for balances to load.

![Screenshot 2024-06-03 at 13 18 16](https://github.com/kodadot/nft-gallery/assets/22471030/83b33b90-9d43-42c5-b8f0-84e327207b52)

Unfortunatelly it is not possible.

### Please reproduce in steps

1. - #10354 
2. log in
3. balances not loaded

### Expected Behavior

Currently I would hide:
- balances in the sidebar if vm === 'EVM'
- additional things like transfer, teleport ...

### Are you logged in?

None

### Screenshots

![Screenshot 2024-06-03 at 13 18 39](https://github.com/kodadot/nft-gallery/assets/22471030/c9b2e0ec-4a43-4064-8677-66b0e6d44d9c)

### Wallet Address & Transaction hash

~

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by exezbcz** [comment]
would not be easier to use some already existing solution etc.? 

<img width="476" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/a6196e20-9a9c-41c0-96e4-bbe25d4a0521">


1inch does it quite fast to load the funds


just idea

**Comment by vikiival** [comment]
> would not be easier to use some already existing solution for the funds etc.?

Yes, but this is a temp fix, it is ugly to show non-working sidebar to users.

**Comment by hassnian** [comment]
![CleanShot 2024-09-16 at 17 26 12@2x](https://github.com/user-attachments/assets/6ef62279-f2f6-47ab-be44-7d076b8945d0)
