### ISSUE TITLE
Make default /rmrk/profile for users 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1040]
Whenever we want to link users from outside to their profile, we need to know their address for now.

Let's make a universal route, where they can land on their profile right away as they are logged in.
The route could be https://kodadot.xyz/rmrk/profile
Which will redirect you to your own address 

![image](https://user-images.githubusercontent.com/5887929/140503156-6a535304-935d-4c19-a5d6-ab33e8706896.png)

**Comment by roiLeo** [comment]
No longer relevant
