### ISSUE TITLE
Top collections: show ALL by default (looks better)

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10409]
See:

<img width="1240" alt="Screenshot 2024-06-05 at 17 42 20" src="https://github.com/kodadot/nft-gallery/assets/104380776/8dde3cca-dcd3-4136-b5eb-909b52a471f1">

On production - volume showing 0 for top collections. Even though they are not empty

**Comment by hassnian** [comment]
@JustLuuuu the data seems ok, collections with 0 volume haven't had any sale in the period of time.

**Comment by JustLuuuu** [comment]
> @JustLuuuu the data seems ok, collections with 0 volume haven't had any sale in the selected period of time.

ah my bad I didnt realized that. I thought its in total. So now I noticed that when I refresh the page it automatically show the 30 days. 

I would change that to ALL. so the numbers look better. :D When you open the platform - option ALL will be selected by default.
