### ISSUE TITLE
Previews of the NFT is created too early

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10407]
This collection: https://kodadot.xyz/base/collection/0x724d751106fc124583a3a27476c3700e776d2796?page=Infinity

Related issue: https://github.com/kodadot/ops-internal/issues/1661

<img width="368" alt="Screenshot 2024-06-05 at 14 43 21" src="https://github.com/kodadot/nft-gallery/assets/104380776/f6e5f8ed-7987-461f-b340-934f387221e1">

**Comment by vikiival** [comment]
Hello, currently the capture worker has delay for 3sec :) 
as the hello states that [Variation loading time < 3 seconds](https://hello.kodadot.xyz/generative/code-checker#id-5-variation-loading-time-less-than-3-seconds) art that loads for 7sec should be rendered faster.
