### ISSUE TITLE
Add buy now from gallery feed when there is grouped NFTs

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1041]
Whenever you are surfing with BUY NOW turned on, we should show BUY somewhere on the card.

I would add to the bottom right corner shop button on hover https://fontawesome.com/v5.15/icons/shopping-cart?style=solid

![image](https://user-images.githubusercontent.com/5887929/140506613-24ac06be-513c-45c9-9c29-0b03e5deb10a.png)

**Comment by TK-Development** [comment]
I'll take a look.

**Comment by TK-Development** [comment]
You mean this one?
![image](https://user-images.githubusercontent.com/86540499/140743835-6e78ab84-769b-421b-afc1-740230b6f582.png)

**Comment by yangwao** [comment]
Sure, where I can test it?

**Comment by TK-Development** [comment]
https://github.com/kodadot/nft-gallery/pull/1050
I pushed these changes

**Comment by JustLuuuu** [comment]
<img width="593" alt="Screenshot 2024-07-31 at 14 08 07" src="https://github.com/user-attachments/assets/4180b40f-6cd4-411d-aadf-f3118c488b10">
