### ISSUE TITLE
Profiles: Missing popup

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10421]
There was supposed to be a pop-up window calling for action - to create your profile on Koda. It should have appeared for people who haven't set up their profiles yet. I didn't get any pop-ups on the 3 profiles I tried to connect with. (same kind of popup as for a drop party for example)

**Comment by Jarsen136** [comment]
I guess there was the same issue. https://github.com/kodadot/nft-gallery/issues/10290
It had been solved but has not been deployed.
