### ISSUE TITLE
Deprecate and remove create 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10427]
Time has come

<img src="https://media4.giphy.com/media/f4D5MDTpwbNRgBnmOf/giphy.gif"/>

# What
removing create as in: 
- https://github.com/kodadot/nft-gallery/issues/10390

-> not our product, our scope is gen art, not single nfts - we will introduce minter for generative drops

for now, there will be a placeholder page that will redirect traffic if anyone accidentally enters the page

# Task
- remove nft minter
- remove ai minter
- remove collection minter
- remove navbar link
- move navbar link to footer 
- add placeholder page
- save the code somewhere if we need it (really small probability) 

# Placeholder page
design updated here: https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=1287-18959&t=Dt9j4HyS2vIGJGpV-11

![image](https://github.com/kodadot/nft-gallery/assets/90852205/63d45e12-d6b7-42c9-b721-0cac1af3fa38)

- super simple, just text and links
- form redirects here: https://form.kodadot.xyz/drop-interest
- documentation here: https://hello.kodadot.xyz/generative/generative-art

**Comment by prachi00** [comment]
<img width="1282" alt="Screenshot 2024-06-07 at 3 04 43 PM" src="https://github.com/kodadot/nft-gallery/assets/39299315/50124782-9bb1-4d6d-b15d-99ae7bec4e2d">
@exezbcz so we are removing all this? and the content inside these pages as well?

**Comment by prachi00** [comment]
👋🏻

**Comment by exezbcz** [comment]
@prachi00 

> remove nft minter
remove ai minter
remove collection minter
remove navbar link
move navbar link to footer
add placeholder page
safe the code somewhere if we need it (really small probability)


yes

**Comment by exezbcz** [comment]
you got 12 hours to raise pr @prachi00

**Comment by exezbcz** [comment]
nominating @hassnian
