### ISSUE TITLE
Remove onchain id

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10425]
The link does not work anyway, lol

https://github.com/kodadot/nft-gallery/assets/90852205/04c3ede4-d7cc-4d58-98da-f56e5e95a4a9

If anyone asks, there are alternatives: 
- https://support.polkadot.network/support/solutions/articles/65000181981-how-to-set-and-clear-an-identity

# task
- remove it
- say bye

<img src="https://media4.giphy.com/media/JshL4uZk1tZt5W0TWV/giphy.gif"/>

**Comment by prachi00** [comment]
👋🏻
