### ISSUE TITLE
Profiles: Banner picture not loading fast enough

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10420]
I created my profile and later decided to add a banner picture. I selected a banner picture from my Twitter and uploaded it. It did not show, + I didn't get any notif that there may be a problem.  

https://github.com/kodadot/nft-gallery/assets/104380776/125d178b-c1d9-47dd-b042-514b70928e18

Profile stayed without banner picture. Here is my KodaDot profile: https://kodadot.xyz/ahp/u/1NFfEH3yspdEgLnhZ5QWgb7B2z5LNCAE3HUo5nDxF5MqTcj

**Comment by JustLuuuu** [comment]
Im taking it back, now I can see the picture (maybe add somewhere a text that loading may take bit longer?).

Can you try it @prury or is it just problem on my side? Maybe my internet is slow

**Comment by prury** [comment]
> Im taking it back, now I can see the picture (maybe add somewhere a text that loading may take bit longer?).
> 
> Can you try it @prury or is it just problem on my side? Maybe my internet is slow

it is indeed taking longer than usual, 20s to load here

skeleton appears but just briefly and it loads a blank banner instead of the image, then later it loads the correct image, maybe @hassnian can take a look
