### ISSUE TITLE
Enable following of non-created profiles

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10424]
I tried but Im unable to follow anyone.

https://github.com/kodadot/nft-gallery/assets/104380776/a1bc932a-faca-4de1-bf1c-ece8e023f0a1

**Comment by Jarsen136** [comment]
We can only follow the address that has already created his profile.

**Comment by JustLuuuu** [comment]
> We can only follow the address that has already created his profile.

can we have that in hover text above follow button? @exezbcz

**Comment by JustLuuuu** [comment]
I agree with exez, it would be nicer for people to follow accounts they like. This way they have to search who has profile and who not, which makes the whole process less enjoyable. 

And then for the case when Im missing my profile and cannot follow pls make hover text with something like: "to follow others, you need to set up your profile first".

**Comment by exezbcz** [comment]
> And then for the case when Im missing my profile and cannot follow pls make hover text with something like: "to follow others, you need to set up your profile first".

when you try to follow someone without profile setup, it will popup the modal to create the profile

**Comment by Jarsen136** [comment]
> @Jarsen136 would personally enable that
> 
> * i would only limit the user if he did not created yet profile, if you try to follow anyone who does not have profile yet, but you have profile created, it should work

It's doable technologyly, though I do not know why it has not been implemented like this before. 
I will give it a shot.
