### ISSUE TITLE
Hide create profile 

### ISSUE THREAD

**Issue by ThomasssArt** [kodadot/nft-gallery#10430]
First of all im still not able to add labels to my issues... Ok where to start...

I tried to setup my profile (not import with Farcaster). 

It is recommended to use a file <= 2MB
![image](https://github.com/kodadot/nft-gallery/assets/60002234/48873923-abf2-4ffe-8eca-88a8f9bbd36d)

It is also possible to use a file > 2MB. I think its needed to get a warning or error message when the file is too big! Same issue for cover image!

Even when i choose a pfp and cover image with correct sizing it doesnt show on the profile... 
![image](https://github.com/kodadot/nft-gallery/assets/60002234/bb732a9a-8502-4438-96ee-5305e862c734)

I tried several pfps and covers... I even created a cover with an exact 4:1 ratio but this also doesnt help. For the case you need more information regarding the images:

PFP:
![image](https://github.com/kodadot/nft-gallery/assets/60002234/90d5553d-8495-43da-b44d-641922dd6e73)

Cover:
![image](https://github.com/kodadot/nft-gallery/assets/60002234/ffa9f8b3-8dfd-45b7-8087-934df5746fe5)

**Comment by ThomasssArt** [comment]
The only thing that worked is if i import via Farcaster it shows my pfp but i still cant set a cover!

**Comment by JustLuuuu** [comment]
link ti his profile: https://kodadot.xyz/ahp/u/13sKcT6tSFRR6HfonaTt4pahd8J4q2m7Q4Kq2FPvzLWh9N7

**Comment by exezbcz** [comment]
i see the cover 

<img width="1710" alt="image" src="https://github.com/kodadot/nft-ga@kodadot/internal-dev ssets/90852205/381c3c1a-cdc3-43af-ae3b-897d2b140fd7">



maybe it takes too long to upload? 
cc @kodadot/internal-dev

**Comment by ThomasssArt** [comment]
maybe its upload time but maybe its also because i set everything up again on beta.kodadot.xyz?!

can someone explain me the difference between beta.kodadot.kyz and kodadot.xyz?

**Comment by JustLuuuu** [comment]
> can someone explain me the difference between beta.kodadot.kyz and kodadot.xyz?

beta is where issues are fixed first, tented and then we release changes to Koda.

**Comment by ThomasssArt** [comment]
ok this means beta is a test environment and should not be available or known by "public"?!

**Comment by exezbcz** [comment]
@ThomasssArt as we are opensource we dont really need to gatekeep this

**Comment by ThomasssArt** [comment]
ok but in my opinion artist and collectors should never use the beta version! 

my understanding:
- bug appears
- bug gets fixed
- bug gets implemented to beta

if everything works on beta it gets implemented to the "main" koda site?!

**Comment by Jarsen136** [comment]
https://github.com/kodadot/nft-gallery/pull/10521
