### ISSUE TITLE
Things needed to search profiles 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10448]
<img width="712" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/069a3be1-9a40-4a18-8e10-e29b61dc38ec">

question:
**what do we need to have the capability to search profiles**

**Comment by Jarsen136** [comment]
> what do we need to have the capability to search profiles

Introducing profile searches is much easier now, as we have off-chain profiles. There is something we need to implement on the worker side.

**Comment by exezbcz** [comment]
@Jarsen136 amazing. Will you create a chief issue for workers, please?

**Comment by Jarsen136** [comment]
> @Jarsen136 amazing. Will you create a chief issue for workers, please?

yup, here's the issue. https://github.com/kodadot/private-workers/issues/178
