### ISSUE TITLE
Unable to remove picture from the profile

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10451]
I was testing yesterday's profiles, and I added a profile picture for my account. Today, I realized that I don't have the option to remove the picture from my profile. I can just replace it. Is that intentional? If not, maybe we should have an option to "clear profile" or something like that. 

<img width="372" alt="Screenshot 2024-06-11 at 11 41 40" src="https://github.com/kodadot/nft-gallery/assets/104380776/713014bb-3613-408e-a593-bd3dfd2d7fac">

**Comment by hassnian** [comment]
#10434
