### ISSUE TITLE
Add new check to code-checker

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10454]
Everything looks good in code-checker with this artist but anyways there is still some issue in the code is not covered yet on the code-checker page.

Code from the artist: 
[xest_2024_06_08_15_02_54 (1).zip](https://github.com/user-attachments/files/15787675/xest_2024_06_08_15_02_54.1.zip)

We are unable to open the canvas page. If we use this code in code-checker and the user clicks "open in the new tab" from our gallery detail page, it will show a blank page. Error in the console:

<img width="740" alt="Screenshot 2024-06-11 at 17 59 27" src="https://github.com/kodadot/ops-internal/assets/734428/088e174c-8907-40a7-8039-eed059c3fc7a">

- https://playground-r2.koda.art/codeChecker/348371ba-4461-4afd-81a2-f7f8447f708a.html?hash=0xeb00330d03a53748d2f2b010086752684e3a34b7ec97aeabe208d0986524be09

### We need this issue to be spotted in the code-checker

**Comment by hassnian** [comment]
@JustLuuuu the artist should not use external resources

![CleanShot 2024-06-18 at 14 53 39@2x](https://github.com/kodadot/nft-gallery/assets/44554284/d75f32cd-6a8b-494b-80fc-4ce8082066dd)

those 2 files are already present inside the zip, he should link those

![CleanShot 2024-06-18 at 14 52 44@2x](https://github.com/kodadot/nft-gallery/assets/44554284/09a7d51d-2793-4db0-a46b-3ba3cd8961d0)
  
new check #10484
