### ISSUE TITLE
Streamline mass-airdrop count for simple edition

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1046]
When I choose a pre-made set of addresses, 
probably you want to have an exact number of editions to be minted and not make any spare.

Otherwise, make a button to enable this SYNC?

![image](https://user-images.githubusercontent.com/5887929/140518030-43c50285-471a-4b25-a3e7-e9daae34c938.png)

**Comment by jkdizajn** [comment]
hey guys, technical question about airdrop: 
if I have 100pcs of nft in my collection, say 25 people have joined airdrop, I enter their addresses and set 25% to be distributed?
Thx :)

**Comment by JustLuuuu** [comment]
we dont do aidrops anymore
