### ISSUE TITLE
Base drop: strigae - previews are BLACK

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10464]
Drop link: https://warpcast.com/antoniowerli/0xf666170a
Collection on Koda: https://kodadot.xyz/base/collection/0xb67bedc5e80a7913b92da0a56fc8aba6c1273a6a?page=Infinity

Preview is black:
<img width="273" alt="Screenshot 2024-06-12 at 13 14 50" src="https://github.com/kodadot/nft-gallery/assets/104380776/30e17e81-68cc-4e63-bb58-40b06a13fc30">

**Comment by preschian** [comment]
fixed
