### ISSUE TITLE
Unable to follow other profiles (even after setting my profile)

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10479]
It worked a few days ago. Then I had this issue: 
<img width="1669" alt="Screenshot 2024-06-18 at 09 07 09" src="https://github.com/kodadot/nft-gallery/assets/104380776/e5dc532c-2405-439d-b43d-94c1716f0d6d">

I re-uploaded my profile. Now I cannot follow anyone, even if they have a profile.

https://github.com/kodadot/nft-gallery/assets/104380776/21755030-1e92-4e2e-9caf-d92492622d5e

**Comment by Jarsen136** [comment]
All profile related bugs should be fixed now as we just did a release
