### ISSUE TITLE
Error: Expected a valid key to convert when clicking on following

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10472]
![image](https://github.com/kodadot/nft-gallery/assets/36627808/b148f9ee-d7c2-43eb-9ad4-b192d63a17d7)

**Comment by Jarsen136** [comment]
It should be fixed after all these PRs are merged into one branch. 
https://github.com/kodadot/nft-gallery/pull/10467 
https://github.com/kodadot/nft-gallery/pull/10444
