### ISSUE TITLE
What happened to Koda Testing profile? 

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10471]
information was lost and the images also defaulted to something else:

[Screencast from 2024-06-14 09-46-08.webm](https://github.com/kodadot/nft-gallery/assets/36627808/e631de1c-0d4f-46c3-8846-7e89de643950)

https://canary.kodadot.xyz/ahp/u/1CBmjqJvV1ha8BPQ5JAXGEzeJBLmGHNG9gYg96eC1dnjH5W

**Comment by exezbcz** [comment]
happened to me as well 

<img width="379" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/c2c7ea3d-f5ae-4496-ac36-7f7307757904">

**Comment by JustLuuuu** [comment]
Happened to me, too. 
<img width="1669" alt="Screenshot 2024-06-18 at 09 07 09" src="https://github.com/kodadot/nft-gallery/assets/104380776/e59c268d-8429-486b-8239-ebc668ead334">

**Comment by vikiival** [comment]
hey can you please dm me your addresses ?

**Comment by JustLuuuu** [comment]
Mine? https://kodadot.xyz/ahp/u/1NFfEH3yspdEgLnhZ5QWgb7B2z5LNCAE3HUo5nDxF5MqTcj, but I already reuploaded my profile.
