### ISSUE TITLE
[code-checker] files is not uploaded to r2 bucket

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#10470]
Hi @kodadot/internal-dev, does anyone know why this file fails to upload to r2 buckets? Or did I miss anything?

[xest3.zip](https://github.com/user-attachments/files/15836907/xest3.zip)

And can we add one button somewhere to open a new link to the public bucket after the file is uploaded?

**Comment by hassnian** [comment]
> Hi @kodadot/internal-dev, does anyone know why this file fails to upload to r2 buckets? Or did I miss anything?

it's working fine for me , is the issue still persisting?

![CleanShot 2024-06-15 at 10 33 39@2x](https://github.com/kodadot/nft-gallery/assets/44554284/7571ee3c-159c-4f90-8cde-a73a6599b1df)

**Comment by preschian** [comment]
interesting, this is on my end 🧐


https://github.com/kodadot/nft-gallery/assets/734428/e0c78be4-64fa-4aa0-907a-83b58921f561
