### ISSUE TITLE
Electronik #34 preview missing

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10487]
In [this](https://kodadot.xyz/ahp/collection/121) generative collection, one NFT is not loading preview properly. Even though the art is there when you open it. NFT link: https://kodadot.xyz/ahp/gallery/121-2405633641

Missing preview
---
<img width="1660" alt="Screenshot 2024-06-18 at 16 16 10" src="https://github.com/kodadot/nft-gallery/assets/104380776/16c9b2b9-c9d7-43a9-9888-7c53a4c2632c">

**Comment by preschian** [comment]
Updated, the thumbnails are captured before the fix on a blank canvas. If the error persists, you need to clear the browser cache. Or you can check it out on our koda.art domain

<img width="2168" alt="Screenshot 2024-06-19 at 07 25 08" src="https://github.com/kodadot/nft-gallery/assets/734428/22d05c54-b1db-47cc-a54c-d99fcddfb7c1">

**Comment by preschian** [comment]
> you need to clear the browser cache

will adjust in this PR, so the user don't need to clear the browser cache
https://github.com/kodadot/private-workers/pull/179
