### ISSUE TITLE
Profiles: Issue with profile creation

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10486]
Artist Buitrago had issue:
- https://koda.art/ahp/u/15GcteQcQbLtWQA1zEJyUpGk3Ehjqod4R9zwLJvxbLgLo7wm

Message from him: I clicked "Create Profile", then I clicked "Import from Farcaster", then I filled all the data, and then clicked "Finish customization" and the error appears.

![2024-06-18 14 55 49](https://github.com/kodadot/nft-gallery/assets/104380776/cf0a6cea-81c5-4497-9c75-8c16549016dd)

**Comment by hassnian** [comment]
same issues as https://github.com/kodadot/nft-gallery/issues/10485#issuecomment-2177912848
