### ISSUE TITLE
Limit image size when upload images to profile

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10490]
Editing profile, we have a text explaining the recommended image sizes to user (2mb, 10mb), but we don`t really check the size of the uploaded image, would be good check it and prevent user from sending large images.

i also think the 10mb for background is too much

![image](https://github.com/kodadot/nft-gallery/assets/36627808/6a94b426-c35d-4423-9e38-ffd9ba9a2890)

thank you @JustLuuuu

**Comment by JustLuuuu** [comment]
also add text - if trying to upload bigger image and it will not o though - Image too large. Upload smaller image. or something like that
