### ISSUE TITLE
Drop Calendar: Possibility to have Base drops in calendar

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10498]
I have added two base drops to Cloudflare so we can see them in the Drops Calendar.
<img width="786" alt="Screenshot 2024-06-19 at 10 59 32" src="https://github.com/kodadot/nft-gallery/assets/104380776/e6b86e10-39f5-4349-aa9b-4cde816e4741">

In the chain field, I added the _base_, and in the external link, I added just a l_ink to our Farcaster channel_.
<img width="699" alt="Screenshot 2024-06-19 at 10 59 39" src="https://github.com/kodadot/nft-gallery/assets/104380776/a2d9ef95-2cd7-411a-a580-b9eecdddcd48">

Drops are still not showing up in the calendar. Not sure what needs to be adjusted. But it would be nice if these drops could be on the Calendar. Viki told me to assign you to it Hassan.

**Comment by hassnian** [comment]
@JustLuuuu  atm on prod you will only see ahp drop calendars

I can think of couple of ways of doing this, either we:

1. show all drop calendars  regardless of selected chain, (ahp, base, ...) , url goes from `/ahp/drops` to `/drops`
2. enable `/base/drops`

**Comment by JustLuuuu** [comment]
> @JustLuuuu atm on prod you will only see ahp drop calendars
> 
> I can think of couple of ways of doing this, either we:
> 
> 1. show all drop calendars  regardless of selected chain, (ahp, base, ...) , url goes from `/ahp/drops` to `/drops`
> 2. enable `/base/drops`

Idk what is the better solution from technical side. Im okay with both.

**Comment by hassnian** [comment]
> > @JustLuuuu atm on prod you will only see ahp drop calendars
> > I can think of couple of ways of doing this, either we:
> > 
> > 1. show all drop calendars  regardless of selected chain, (ahp, base, ...) , url goes from `/ahp/drops` to `/drops`
> > 2. enable `/base/drops`
> 
> Idk what is the better solution from technical side. Im okay with both.

I think we should maybe keep `/ahp/drops` drops are from ahp, and drop calendars are from all chains , I dont know if this is confusing, but this way people will have a chance of seeing drops calendars from other chains without having to change chains 

design will need to show the chain inside the drop calendar card cc @exezbcz 

> Idk what is the better solution from technical side

shouldn't be an issue, we should focus on what makes more sense UX wise

**Comment by exezbcz** [comment]
what needs to be designed: 

- identifier in the chain
- reconnect evm wallet if you are connected with polkadot and try to mint evm

**Comment by exezbcz** [comment]
updated as part of card 2.5


<img width="1707" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/3b7cf031-f807-4f41-89d7-9e5f22e28db3">


## File
https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=394-6126&t=7MPHrkmwOPoQQRVY-11


## Tag
14px font size plus icon of the network

**Comment by exezbcz** [comment]
after this we need this: 
- https://github.com/kodadot/nft-gallery/issues/10458
