### ISSUE TITLE
Drop Calendar: Showing/not showing dates

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10499]
I noticed that some calendar drops are showing drop date and time also in the card and some not. The format of the date/time used in both is same. 

<img width="438" alt="Screenshot 2024-06-19 at 10 52 43" src="https://github.com/kodadot/nft-gallery/assets/104380776/846977ee-738a-46eb-a764-587a053d244f">

Once you open the Drop where you cannot see the date/time - you can see it in side-bar - which is nice but in cards they also should show it. **Its either all cards are showing it or they are not.** 

<img width="1100" alt="Screenshot 2024-06-19 at 10 54 22" src="https://github.com/kodadot/nft-gallery/assets/104380776/480b8ec3-4a6e-478f-a5b4-1f3ac85898ec">

**Comment by hassnian** [comment]
@JustLuuuu xest's date is invalid, pls update it inside cloudlfare's ui

should be `"date": "2024-06-20 15:00:00",` no extra `\n`

![CleanShot 2024-06-19 at 15 33 30@2x](https://github.com/kodadot/nft-gallery/assets/44554284/e7bd1ed1-ebd0-4d17-a361-d72f96a01a00)

**Comment by JustLuuuu** [comment]
Lol the \n was not visible as it was written with white on the white background. Thx adjusted
