### ISSUE TITLE
Todays drop missing information

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10509]
https://canary.kodadot.xyz/ahp/drops/xest

![image](https://github.com/kodadot/nft-gallery/assets/36627808/3def521b-40b8-4573-9384-b30f0f13511f)

![image](https://github.com/kodadot/nft-gallery/assets/36627808/fcfe5782-1a80-43ff-a0ce-985e95ba61a3)

**Comment by preschian** [comment]
old issue, fixed
