### ISSUE TITLE
Follow acting weird

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10501]
I have set my profile previously. I tried to follow someone on **CANARY**, and it asked me to create a profile even though I have a profile. I cannot follow the person because the popup is asking me to create a new profile.
- if I click on skip and then again on follow popuo will jump again
- If I click create profile - I have to start from zero - empty profile (I dont want that)

My profile: https://kodadot.xyz/ahp/u/1NFfEH3yspdEgLnhZ5QWgb7B2z5LNCAE3HUo5nDxF5MqTcj

Video explanation
---

https://github.com/kodadot/nft-gallery/assets/104380776/1d15386c-3d2a-40f8-a763-a4443bd2093b

**Comment by Jarsen136** [comment]
> I have set my profile previously. I tried to follow someone on CANARY, and it asked me to create a profile even though I have a profile. I cannot follow the person because the popup is asking me to create a new profile.

The CANARY environment has added verification, and profiles / follow users can only be updated through signature verification. As the PR has not merged, so there is some weird behaviour related to profiles. 

The environment where profile can be used normally: https://deploy-preview-10480--koda-canary.netlify.app/
