### ISSUE TITLE
Profile function - following button not working

### ISSUE THREAD

**Issue by ThomasssArt** [kodadot/nft-gallery#10512]
The follow button in the profile is not working.

Steps to reproduce:

Visit profile:
![grafik](https://github.com/kodadot/nft-gallery/assets/60002234/6a078f64-bebe-436e-9ee4-ca61b79dcd78)

Click on followers on the right:
![grafik](https://github.com/kodadot/nft-gallery/assets/60002234/1adb06ad-65a2-4922-8f0f-40090960f9ae)

Try to follow Luuu:
![grafik](https://github.com/kodadot/nft-gallery/assets/60002234/908da24d-bdcb-4590-a5df-0bc3576cbca4)

I can click but it doesnt work. After i clicked the first time on the button the following happens to the button:

When i not hovered over the button its "grayed":
![grafik](https://github.com/kodadot/nft-gallery/assets/60002234/bf582d09-ee71-48e6-9bee-5a71bfab1cce)

If i hover over the button its "normal black":
![grafik](https://github.com/kodadot/nft-gallery/assets/60002234/08c86dd2-68a8-4cac-9303-a09f798aca7f)

Shouldnt this be the other way around? It doesnt make sense like this?!

**Comment by JustLuuuu** [comment]
https://github.com/kodadot/nft-gallery/issues/10479

**Comment by ThomasssArt** [comment]
sorry missed this
