### ISSUE TITLE
xest: Swap Drop Image to be same as Collection image

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10518]
Artist specificly chose collection picture. Why is a different picture on the drop page? please use the same picture as collection picture for the drop page (picture attached in the end of this issue)

Drop page
---
<img width="921" alt="Screenshot 2024-06-20 at 15 47 28" src="https://github.com/kodadot/nft-gallery/assets/104380776/16b346bb-f602-4c60-89fa-971b83063195">

Collection image
---
<img width="632" alt="Screenshot 2024-06-20 at 15 47 35" src="https://github.com/kodadot/nft-gallery/assets/104380776/b9beca0c-639a-4019-97bc-f1c397ce7c8c">

Correction
---

Please use this picture:
![0x0a36960c60b84dc8f5d45e08422b8a6535eb125ba1ab6a559896d7ef6d3a68a0](https://github.com/kodadot/ops-internal/assets/104380776/4a3af063-1ad7-4cbe-a449-2826b5c09811)

For the drop page too

**Comment by preschian** [comment]
@JustLuuuu updated

**Comment by JustLuuuu** [comment]
thank you!
