### ISSUE TITLE
Appereance on mobile devices

### ISSUE THREAD

**Issue by ThomasssArt** [kodadot/nft-gallery#10513]
This is probably not the issue with the highest priority but imo its nowadays important that everything looks good on different devices. 

Here an example of my profile Laptop vs Mobile Phone:

Laptop
![grafik](https://github.com/kodadot/nft-gallery/assets/60002234/f1e60cc6-0f4a-4e2e-b9aa-698c6ce58908)

Mobile Phone:
![grafik](https://github.com/kodadot/nft-gallery/assets/60002234/6ab325a7-993b-4857-9c6a-c4710b0ba607)

First i thought the cover image doesnt even get displayed but after i checked with Luuus profile i think the issue is that just the top middle part is displayed on mobile devices and therefore it just shows black.

For comparison Luuus profile:
![grafik](https://github.com/kodadot/nft-gallery/assets/60002234/fb6c245e-7dee-4189-8ed9-b3bfc419f27f)

![grafik](https://github.com/kodadot/nft-gallery/assets/60002234/eee0dd8f-be84-492d-93ed-bfd9159bd2da)

This is just one example but overall i think there should be no difference in the appereance.

**Comment by hassnian** [comment]
cc @exezbcz

**Comment by exezbcz** [comment]
@hassnian the banner should scale down

**Comment by exezbcz** [comment]
continue to 
- #10564
