### ISSUE TITLE
Drop minting wrong price

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10510]
![image](https://github.com/kodadot/nft-gallery/assets/36627808/3b2a1045-fbb3-43a0-aec4-6d4ba591c6e2)

100 dot for one piece

**Comment by Jarsen136** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/31397967/5b8246b3-1e87-426e-8c38-3f39a889cb05)

It should have been fixed
