### ISSUE TITLE
Invalid type error when uploading images to profile

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10525]
![image](https://github.com/kodadot/nft-gallery/assets/36627808/ca66481d-05e1-457b-a0ec-874d47034a11)

![image](https://github.com/kodadot/nft-gallery/assets/36627808/84a13fc1-5809-4691-93bb-e4546ece1d1c)

**Comment by Jarsen136** [comment]
It should be fixed in #https://github.com/kodadot/nft-gallery/pull/10478

**Comment by vikiival** [comment]
is this blocked?

**Comment by Jarsen136** [comment]
> It should be fixed in ##10478

Merged
