### ISSUE TITLE
No popup for signature when minting step on autoteleport 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10532]
<img width="1722" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/f254c822-4951-4ba2-9f50-316b34794528">
<img width="3008" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/a1709997-ba56-4c84-890a-23d6c5053e8f">

Everything went well until the mint step 

tested on canary

**Comment by exezbcz** [comment]
@prury do you know what is causing it?

**Comment by prury** [comment]
@exezbcz both in firefox/chrome, canary/production, i was able to reach this screen first:
![image](https://github.com/kodadot/nft-gallery/assets/36627808/40f9923a-bdfe-44ab-9137-8fd3640b5b83)

do you have any sort of adblocker on?

**Comment by exezbcz** [comment]
> @exezbcz both in firefox/chrome, canary/production, i was able to reach this modal first:

the issue is not about the modal, its about the final step in the teleport flow. I got this modal as well, but the last step did not popup the wallet popup

**Comment by hassnian** [comment]
> > @exezbcz both in firefox/chrome, canary/production, i was able to reach this modal first:
> 
> the issue is not about the modal, its about the final step in the teleport flow. I got this modal as well, but the last step did not popup the wallet popup

iirc there's already an issue regarding this, wasn't able to reproduce it last time, will check again ASAP

**Comment by exezbcz** [comment]
> iirc there's already an issue regarding this (@exezbcz opened it), wasn't able to reproduce it last time, will check again ASAP

will try to find it

**Comment by prury** [comment]
> > @exezbcz both in firefox/chrome, canary/production, i was able to reach this modal first:
> 
> the issue is not about the modal, its about the final step in the teleport flow. I got this modal as well, but the last step did not popup the wallet popup

ah, i see. 
i was able to reach the final step and signed with my wallet normally

**Comment by exezbcz** [comment]
@prury weird
