### ISSUE TITLE
Profiles: not working - unable to create, change or update 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10540]
Reported by more than one person. When fix? This is not working for more than a week guys...

<img width="553" alt="Screenshot 2024-06-25 at 13 56 44" src="https://github.com/kodadot/nft-gallery/assets/104380776/65fc4d49-155c-4940-b2e4-2b197c165209">

**Comment by hassnian** [comment]
forgot we had the verify account issue on beta

one of the last `profile` worker deployments had that code 

just re-deployed `production` of the `profile` worker to a version of the code before the verify account functionality

![CleanShot 2024-06-25 at 18 11 44@2x](https://github.com/kodadot/nft-gallery/assets/44554284/5b7b02fb-015e-45ef-968e-4e365933b686)

prod of the profile worker  it's working again 

kodadot.xyz

<img src="https://github.com/kodadot/nft-gallery/assets/44554284/87dcb8cf-27b3-44a3-96e4-7fbb58044be7" />

**Comment by prury** [comment]
related, i opened it 4 days ago:
- https://github.com/kodadot/nft-gallery/issues/10525
