### ISSUE TITLE
On Kodadot my NFT belongs to other wallet

### ISSUE THREAD

**Issue by lazywalker2** [kodadot/nft-gallery#10548]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

I bougth NFT on singular:
https://singular.app/collectibles/kusama/b6e98494bff52d3b1e-SPIRIT/15023551-b6e98494bff52d3b1e-SPIRIT-SPIRIT261-00000261

My KSM adress: D3KCRCzttmxjsrtuiRDcTzR54dM4q1DrUKh97xCbEcAwMss

But i found the same NFT on Kodadot, but owner is different wallet:

https://kodadot.xyz/ksm/gallery/15023551-b6e98494bff52d3b1e-SPIRIT-SPIRIT261-00000261

So, how it happens and what to do if i want to to trade it on kodadot?

### Please reproduce in steps

big surprise that on one network, two platforms work as fake news

### Expected Behavior

i want to trade my nft on kodadot, that i bought on other NFT platforms

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Asset Hub Kusama, Kusama

### Screenshots

<img width="1347" alt="image" src="https://github.com/kodadot/nft-gallery/assets/161769944/cb105ce2-8d3a-46ad-8528-a678b44121cb">

### Wallet Address & Transaction hash

https://kusama.subscan.io/block/23741940

0xe125c94fc1f39bc61dc59476c5cb71908272530b6fdb5e0c3572467c53c2eeaa

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lazywalker2** [comment]
any news, any porgression?

**Comment by hassnian** [comment]
rmrk is no longer supported #10686
