### ISSUE TITLE
Drop page does not work on mobile

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10557]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

If someone opens Koda drops on mobile, it won't work for them.

### Please reproduce in steps

1. On your phone open kodadot.xyz/drops
2. Go to any drop
3. Drop page has _blank_ art

### Expected Behavior

I expect to have art visible on mobile.

### What browsers are you seeing the problem on?

Mobile iOS Safari (WebKit)

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

None

### At which chain did you encounter bug?

Asset Hub Polkadot

### Screenshots

![IMG_8148](https://github.com/kodadot/nft-gallery/assets/22471030/bf4b19ae-c026-4251-982d-8adc5b446fc9)

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
Seems like Nova Wallet does not work for me either

**Comment by vikiival** [comment]
Seems Nova Wallet works 👀

**Comment by hassnian** [comment]
@vikiival for me all of them loaded, I did get the white screen but it ended up loading.

a couple of weeks ago I had chatted with @exezbcz about introducing some kind of loader there so we wouldn't have that white screen

**Comment by exezbcz** [comment]
@hassnian ahhh now i see what is the issue


lets put a loader there: 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/ea700a2d-3d76-464a-8a40-7e53fd29d2ce)
in: https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=1287-18959&t=4JMKlxLIltW0cmZV-11
