### ISSUE TITLE
Wrong size of NFT preview

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10558]
This NFT: https://kodadot.xyz/ksm/gallery/15023551-b6e98494bff52d3b1e-SPIRIT-SPIRIT261-00000261

Looks like this:

<img width="1627" alt="Screenshot 2024-07-01 at 10 01 43" src="https://github.com/kodadot/nft-gallery/assets/104380776/dc46c17b-ba60-455b-9b78-f599d28fee39">

Not sure how many NFTs are affected.

**Comment by vikiival** [comment]
The problem is that image is treated as iframe
