### ISSUE TITLE
Profile mobile followup 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10564]
ref: 
- https://github.com/kodadot/nft-gallery/issues/10513

as mobile was not really optimized, here are some changes 

## Changes 
- banner height and size
	- the banner img should scale down, on mobile, the height will be 160px 
- profile picture scale down, from 144px to 100px, centered vertically in the banner
- name font size reduced (from 31 to 25 - subtitle bold in figma)
- profile statistics font size reduced as well, to our good old 16px

these changes are applied on the mobile breakpoint 

figma: 
https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=1287-18959&t=4JMKlxLIltW0cmZV-11

## pics 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/08579421-c11b-4de5-8f6e-9fa4180a5d14)

## area of changes
![image](https://github.com/kodadot/nft-gallery/assets/90852205/879da050-333b-4d65-8fe5-55068c755667)
![image](https://github.com/kodadot/nft-gallery/assets/90852205/03efacb7-da59-4525-ade1-208742774ff3)
![image](https://github.com/kodadot/nft-gallery/assets/90852205/274f2df2-4414-4424-b475-72ccc5ee458a)

**Comment by roiLeo** [comment]
:wave:

**Comment by roiLeo** [comment]
Same goes for collection pages
