### ISSUE TITLE
Add number of trades on series

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1057]
When I'm eyeballing the collection, an interesting fact could be, 
how many trades happened compared to volume.

Add a column to show the number of total BUYs

![image](https://user-images.githubusercontent.com/5887929/140709235-81c923c8-5d25-4a06-954c-d12f70b7aac3.png)

**Comment by devVenus1202** [comment]
I will update this.

**Comment by roiLeo** [comment]
closed in #1112
