### ISSUE TITLE
Profiles: unable to follow some profiles

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10581]
I have set up my profile before, but Im unable to follow some of the profiles - idk why. It was a weird issue because I opened more profiles I wanted to follow, and I was able to follow some of them and some not. Check video:

https://github.com/kodadot/nft-gallery/assets/104380776/3e15a9ea-62d4-4b73-8a13-be262426eb46

Profiles I cannot follow (even though we both have set profiles)
- https://koda.art/ahp/u/13DgGuPvoJgtgtARyATbAEjjQWtepnC8mBjrEgzWYRSTS5mN
- https://koda.art/ahp/u/16iMazd1dask2PQfWbJbeMTTStvSj81bpgtFUWVUVLbQ5yYg
- https://koda.art/ahp/u/12C3cnVUW5FmKbpy3err4BkXwPH24BVEsaSBAgfaLzPdbnZv
- https://koda.art/ahp/u/13DVkU7wKdGyY5X53KzQaQhZj1EcR6CmZpjKLkknjcnhBWd7
- https://koda.art/ahp/u/16GASGn5QofWzBEvfdi9bfD755n9PStDByWj6XLcyVfrwvwZ
- https://koda.art/ahp/u/15GcteQcQbLtWQA1zEJyUpGk3Ehjqod4R9zwLJvxbLgLo7wm

**Comment by Jarsen136** [comment]
The same problem as fixed here https://github.com/kodadot/nft-gallery/pull/10496 
It seems that the fix has not been deployed to the `koda.art` environment yet  cc @hassnian 

![image](https://github.com/kodadot/nft-gallery/assets/31397967/02df8649-f354-41ce-97b3-abbf682e3526)

**Comment by hassnian** [comment]
#10496 it's part of `release(beta) Early July ` #10574 

@vikiival can we deploy that fix on prod

**Comment by Jarsen136** [comment]
It should be fixed now

**Comment by vikiival** [comment]
> @vikiival can we deploy that fix on prod ?

- #10600
