### ISSUE TITLE
Add magic random where we have pagination component

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1058]
This is continued from #1044  #1036

We should add it on 
- collection view, [test on Talisman](https://deploy-preview-1044--nftkodadot.netlify.app/rmrk/collection/b6e98494bff52d3b1e-SPIRIT?page=6)
- artist profile, test on [Zeitgeist Tarot Minter](https://deploy-preview-1044--nftkodadot.netlify.app/rmrk/u/CwXa36Dddsm4h7T1LDnXvtdTFmSfUg7ZVygZ7mv8m6DE19s?page=8) 
- spotlight 

@prachi00 delivered previously, may she want to do this as well?

**Comment by prachi00** [comment]
yes @yangwao I'll do these

**Comment by prachi00** [comment]
@yangwao @roiLeo Hey, for the spotlight right, I see that the pagination component isn't being used and its a `<b-table component ` , I am not sure if we can do the magic button here since we don't have pagination here and the data is loaded all at once

**Comment by roiLeo** [comment]
> @yangwao @roiLeo Hey, for the spotlight right, I see that the pagination component isn't being used and its a `<b-table component ` , I am not sure if we can do the magic button here since we don't have pagination here and the data is loaded all at once

Something could be done with ```:current-page``` here. cf buefy [doc](https://buefy.org/documentation/table/#pagination-and-sorting)

@prachi00
Could you fix the spacing between toggle & pagination too?
![Screenshot 2021-11-08 at 11-56-03 NFT Artist Profile on KodaDot](https://user-images.githubusercontent.com/9987732/140730371-64dd11e8-50c6-450d-8f48-8c9b6b706954.png)
