### ISSUE TITLE
Reporting Bug/Error when creating/minting NFT

### ISSUE THREAD

**Issue by nine73** [kodadot/nft-gallery#10588]
### What happened?

I sign on via my wallet, I go to create a new NFT under my collection 
then when I click to publish and mint, I get this error, it's been happening for 3-4 days... 

Warning
Error: [NFT::STORAGE] Unable to PIN File for reasons HTTP status server error (503 Service Unavailable) for url (https://api.nft.storage/upload)

### Please reproduce in steps

I sign on via my wallet, I go to create a new NFT under my collection 
then when I click to publish and mint, I get this error, it's been happening for 3-4 days... 

Warning
Error: [NFT::STORAGE] Unable to PIN File for reasons HTTP status server error (503 Service Unavailable) for url (https://api.nft.storage/upload)

### Expected Behavior

Warning
Error: [NFT::STORAGE] Unable to PIN File for reasons HTTP status server error (503 Service Unavailable) for url (https://api.nft.storage/upload)

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### Screenshots

<img width="1728" alt="Screen Shot 2024-07-05 at 11 59 38 AM" src="https://github.com/kodadot/nft-gallery/assets/39445390/90b35c8b-e4bd-466f-9087-ce41ac639e77">

### Wallet Address & Transaction hash

Address: 16iaMiYDty42YDzuPdpvWBA6YDXeZ7eXhbi5ba2dowNWvDE9

### Relevant log output

```shell
Url: https://kodadot.xyz/create/nft
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Wallet: talisman
Chain: ahp
Error: Error: [NFT::STORAGE] Unable to PIN File for reasons HTTP status server error (503 Service Unavailable) for url (https://api.nft.storage/upload)
```

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
Hello,

thanks for openning an issue
Since our provider (nft.storage) has discontinued their services.

We have deprecated the create
https://github.com/kodadot/nft-gallery/releases/tag/0.0.33

![Screenshot 2024-07-08 at 10 16 59](https://github.com/kodadot/nft-gallery/assets/22471030/7b918da5-f5b7-49ed-b2e2-cfd40ab60a33)
