### ISSUE TITLE
HTTP error to upload images on IPFS

### ISSUE THREAD

**Issue by Juminstock** [kodadot/nft-gallery#10590]
### What happened?

Trying to create a NFT collection in Polkadot AssetHub I have had a problem, basically it does not let me upload the image to IPFS and throws me an error 503, error when making the HTTP request.

### Please reproduce in steps

First I clicked to upload the image, then I filled in all the fields, I clicked "create collection" and it doesn't go any further, I get the error and it keeps loading for more than 2 minutes, it doesn't process the transaction.

### Expected Behavior

Creating an NFT collection in Polkadot AssetHub

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

SubWallet

### Screenshots

<img width="652" alt="Screenshot 2024-07-05 at 16 35 48" src="https://github.com/kodadot/nft-gallery/assets/105810861/cc877485-9668-4d9a-88d9-bf6b63a97844">
<img width="652" alt="Screenshot 2024-07-05 at 16 35 56" src="https://github.com/kodadot/nft-gallery/assets/105810861/4fef0929-01ba-4f47-8868-ba1341023e08">
<img width="1440" alt="Screenshot 2024-07-05 at 16 36 30" src="https://github.com/kodadot/nft-gallery/assets/105810861/0651565d-184f-4008-93ff-de66a42f0648">

### Wallet Address & Transaction hash

Address: 12jNpcKMqYbiDhucsr6TDrto3MdRtrBLbuDvTh3FprZeVbpb
Transaction hash: none

### Relevant log output

```shell
Url: https://kodadot.xyz/create/collection
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Wallet: subwallet-js
Chain: ahp
Error: Error: [NFT::STORAGE] Unable to PIN File for reasons HTTP status server error (503 Service Unavailable) for url (https://api.nft.storage/upload)
```

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
Hello,

thanks for openning an issue
Since our provider (nft.storage) has discontinued their services.

We have deprecated the create
https://github.com/kodadot/nft-gallery/releases/tag/0.0.33

![Screenshot 2024-07-08 at 10 16 59](https://github.com/kodadot/nft-gallery/assets/22471030/7b918da5-f5b7-49ed-b2e2-cfd40ab60a33)

**Comment by Juminstock** [comment]
@vikiival 
Hey, thank you fot your quickly response. Okey, I got it, it that case what can I do for create a collection in your platform?

**Comment by vikiival** [comment]
Depends on what are your intentions.
best way is to [Join our telegram channel](https://t.me/koda_eco)
and @JustLuuuu can help you ^^

**Comment by JustLuuuu** [comment]
> @vikiival Hey, thank you fot your quickly response. Okey, I got it, it that case what can I do for create a collection in your platform?

Generative collection?

**Comment by Juminstock** [comment]
@JustLuuuu 
Actually a simple collection, I just need to create a collection with 5 items to certify the participation in a workshop
