### ISSUE TITLE
Talisman wallet fails when signing `ahk` transactions

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#10591]
## Mint 

Minting a `ahk` drop 

https://github.com/kodadot/nft-gallery/assets/44554284/a349adf2-1839-4f8f-aedf-59f5a698c663

## Teleport

I'm  using the `/teleport` page and when I try to  teleport `ahk -> ksm` the talisman wallet shows an error

Any other than `ahk -> ksm` works fine

doesn't work on both canary and prod 

**Wallet:** Talisman 

https://github.com/kodadot/nft-gallery/assets/44554284/f9a34c60-7b88-47f1-90cb-a49127fb053f

**Comment by dudo50** [comment]
Does it wotk for you now?
When we try it at our [playground](https://playground.paraspell.xyz/xcm-sdk-sandbox) it works for us.

<img width="1099" alt="Snímka obrazovky 2024-07-06 o 10 34 48" src="https://github.com/kodadot/nft-gallery/assets/55763425/a6245143-117d-4152-bbb1-a7d32ceeed80">

It also works for us on Kodadot
<img width="1398" alt="Snímka obrazovky 2024-07-06 o 10 36 35" src="https://github.com/kodadot/nft-gallery/assets/55763425/1f52b474-0bd0-429c-9999-0bb7ee1f0dc7">

**Comment by hassnian** [comment]
Tried with Brave instate Arc of which had a older version of talisman `v1.27.1` instate of `v1.29.1` on Arc.

and that worked, What version of Talisman do you have installed?,  that might the issue.

![CleanShot 2024-07-06 at 14 07 58@2x](https://github.com/kodadot/nft-gallery/assets/44554284/913ef943-fc12-4056-95fc-27a1b22163d9)

**Comment by hassnian** [comment]
yup, that fixed the issue 

https://github.com/kodadot/nft-gallery/assets/44554284/e7db29b6-21e8-471e-9b56-33489655beaf
