### ISSUE TITLE
Base network missing

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10605]
Why is Base network missing?

<img width="594" alt="Screenshot 2024-07-10 at 10 22 45" src="https://github.com/kodadot/nft-gallery/assets/104380776/4cbaebfd-84fc-421e-96f1-969174c1853a">

**Comment by JustLuuuu** [comment]
What is going on????? Now I have these options:
<img width="1614" alt="Screenshot 2024-07-10 at 10 59 26" src="https://github.com/kodadot/nft-gallery/assets/104380776/e2ad673c-7464-4630-b495-31b96c52ee99">


Thomas has different options too:
![2024-07-10 11 00 47](https://github.com/kodadot/nft-gallery/assets/104380776/eaff4aac-32f9-401e-bf1b-b06eef3c9ee0)

**Comment by hassnian** [comment]
not a bug, a decision was made to filter available chains once a wallet is connected

so basically atm once you connect to  a`evm` wallet you can't select a `Substrate` chain and vice versa
