### ISSUE TITLE
koda art announcement message on landing 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10602]
once confirmed by devs, we will soon post about it on twitter and it would be nice to put a announcement on a landing page 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/1c6b97c4-4fc3-4dae-9fa1-737cbf568037)

its in the figma handoff - small things page 
https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=1287-18959&t=CTRefK6KIq5Q9YQM-11

## design 
its the same as when announcing our warpcast drops, but instead of the preview there is information icon

## notes 
merge the pr once twitter post is done - will let you know

**Comment by Jarsen136** [comment]
> its the same as when announcing our warpcast drops, but instead of the preview there is information icon

It also displays in the same position on landing page? @exezbcz 
I'm think about we could still show warpcast drops announcement on the landing if user has already using koda.art.
