### ISSUE TITLE
Update image placeholders

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#10617]
### What happened?

the one without the `dot`seems to be the latest 

@exezbcz can we unify or update if needed?

<img src="https://github.com/kodadot/nft-gallery/assets/44554284/95c1251d-6dee-41f7-8b6d-846a9d00d9a7" width="400" />

<img src="https://github.com/kodadot/nft-gallery/assets/44554284/2bcc08f4-59d8-457a-80ab-526d68f3015a" width="400" />

<img src="https://github.com/kodadot/nft-gallery/assets/44554284/bf3a2cf1-09d9-4c87-ad12-5929c9cbf419" width="400" />

**Comment by exezbcz** [comment]
- https://github.com/kodadot/nft-gallery/issues/10415
