### ISSUE TITLE
Support minting drops on EVM 

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#10648]
make minting drops on evm possible

use
- https://wagmi.sh/

**Comment by vikiival** [comment]
- https://koda.art/base/drops/quadz

How does it work:

https://basescan.org/address/0x61fa91bc4df01c199f2c9576a2fe10ea206a55e1#writeContract

You basically need to call function safeMint

which takes one parameter (to) that is `accountId` in our case.

value in this particular example, for others it is coded in the indexer.

**Comment by codomposer** [comment]
:wave: -> :wave:

**Comment by vikiival** [comment]
> :wave: -> :wave:

Issue already assigned
