### ISSUE TITLE
Listing popup displayed with listing modal

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10646]
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/6e85cf69-cabe-4f54-98f5-b4fb51990d2e">

# What
when minting nft, waiting for the congrats modal, then clicking listing, it shows the small mass select dialog. 

Task: remove it

**Comment by codomposer** [comment]
Still working

**Comment by exezbcz** [comment]
@codomposer you got 24 hours to raise pr
