### ISSUE TITLE
Deprecation of RMRK 

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/nft-gallery#10643]
### Task

1. Remove logic related to rmrk and ksm prefixes

**Comment by vikiival** [comment]
Just checking with @damskyftw

**Comment by damskyftw** [comment]
> Just checking with @damskyftw

Yes as discussed this is ok. All the collections that migrated, they migrated and nobody is minting using rmrk or anything related.

It would be cool to somehow still show collections or keep an archive of it, but it’s not mandatory and we are not paid for that per say
