### ISSUE TITLE
Sharing button needs more love

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1065]
Sharing button needs some love
Connect it with #1012 

![image](https://user-images.githubusercontent.com/5887929/140744527-6c8a2372-874d-454f-8255-200152398097.png)

**Comment by roiLeo** [comment]
This has been fixed in #1083

**Comment by yangwao** [comment]
> This has been fixed in #1083

you mean #1082 #1063 probably 👀
