### ISSUE TITLE
Searched word not applied as filter after clicking see all

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10650]
<img width="658" alt="image" src="https://github.com/user-attachments/assets/5e931913-7a45-48f0-b457-b597d3f1affa">
<img width="1271" alt="image" src="https://github.com/user-attachments/assets/43d29ca6-63fb-4a91-b949-7312dd95b9de">

## Reproduce
- search dot, scroll down, press see all

**Comment by codomposer** [comment]
👋

**Comment by exezbcz** [comment]
one note is that it works when searching a keyword and then hitting enter - then the searched word is applied as filter 


https://canary.kodadot.xyz/?search=like+this


<img width="786" alt="image" src="https://github.com/user-attachments/assets/a9275c01-f97a-4912-81b2-772f8ae6dab4">



and sometimes not even that work

**Comment by codomposer** [comment]
@exezbcz 
Can you check this issue, I can't run the app
![image](https://github.com/user-attachments/assets/97f67892-b822-4beb-a582-a7967ab5e7ac)

**Comment by yangwao** [comment]
@codomposer any progress?

**Comment by codomposer** [comment]
@yangwao 
I fixed this issue
Can you check this PR?
https://github.com/kodadot/nft-gallery/pull/10704
