### ISSUE TITLE
icon gone - connect wallet sidebar 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10651]
<img width="480" alt="image" src="https://github.com/user-attachments/assets/0ccdce67-f840-4244-b84d-16370f2b6a4c">
<img width="347" alt="image" src="https://github.com/user-attachments/assets/16ddf9b8-0ecc-4861-a2b3-77a3e39fe201">

**Comment by codomposer** [comment]
👋

**Comment by exezbcz** [comment]
@codomposer gm, pr was already raised. 


looking forward to your contributions on issue that is not assigned and not worked on, thanks!
