### ISSUE TITLE
Reviewdog is failing

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10669]
### Context 

Failing reviewdog is currently blocking all PRs 

### Task

Fix eslint issues so reviewdog can work normally

### Original

 reviewdog is failing

![Screenshot 2024-07-23 at 10 33 12](https://github.com/user-attachments/assets/a9b5938f-1569-4319-8da2-26628c3bc157)

_Originally posted by @vikiival in https://github.com/kodadot/nft-gallery/issues/10661#issuecomment-2244590133_

**Comment by preschian** [comment]
related: https://github.com/kodadot/nft-gallery/issues/10631
