### ISSUE TITLE
Show price in USD in Drops

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10674]
our drops now have different price not only 0.5 DOT. To make it easier to collect it would be nice to see the price on https://kodadot.xyz/ahp/drops. With small text - gray. Maybe in USD? Lets make it easy to collect the art. So people are not discouraged if they open drop that is expensive first.

<img width="1587" alt="Screenshot 2024-07-23 at 17 47 22" src="https://github.com/user-attachments/assets/dfb26b06-811c-499c-a510-71c26b67f2c5">

**Comment by exezbcz** [comment]
there is already quite a lot of info

<img width="416" alt="image" src="https://github.com/user-attachments/assets/2e38b028-102e-4e75-ba2d-207dcf07ac8b">



either we drop the minted by section or decide to have it without the USD price

**Comment by exezbcz** [comment]
linking 
- https://github.com/kodadot/nft-gallery/issues/7881

**Comment by JustLuuuu** [comment]
I dont want to drop the number of minted pieces... so idk lets leave this open for discussion

**Comment by exezbcz** [comment]
# Continue in https://github.com/kodadot/nft-gallery/issues/10731
