### ISSUE TITLE
Wallet Popup not appearing

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10676]
I found out weird bug. Once I sign transaction for example transfer NFT and click to second tab where I want to transfer another NFT my wallet popup (polkadot js signing popup) will not appear. Not sure if its issue on my side only but it happened more than once now as Im doing a lot of transactions (sending NFTs from giveaway). I for example teleported some DOT to ahp and after that when tried to mint - wallet signing popup did not appear. it appeared only when I refreshed the page. Then I minted two NFTs (signed) but after going to transfer NFt again i did not get walle popup again. I had to refresh the page. It appears that wallet popup will not appear after signing one transaction. here is video example: I signed one transfer but now I dont have wallet popup for another transfer.

https://github.com/user-attachments/assets/3b801183-6f80-49e9-bdc5-62f770f6a423

Im able to reproduce the issue everytime I try to do two transactions after each other

**Comment by Clarevero1** [comment]
> I found out weird bug. Once I sign transaction for example transfer NFT and click to second tab where I want to transfer another NFT my wallet popup (polkadot js signing popup) will not appear. Not sure if its issue on my side only but it happened more than once now as Im doing a lot of transactions (sending NFTs from giveaway). I for example teleported some DOT to ahp and after that when tried to mint - wallet signing popup did not appear. it appeared only when I refreshed the page. Then I minted two NFTs (signed) but after going to transfer NFt again i did not get walle popup again. I had to refresh the page. It appears that wallet popup will not appear after signing one transaction. here is video example: I signed one transfer but now I dont have wallet popup for another transfer.
> 
>  Screen.Recording.2024-07-23.at.17.52.47.mov 
> 
> Im able to reproduce the issue everytime I try to do two transactions after each other


We apologize for any inconvenience this may have caused. It seems that your inquiry would be best addressed by our support team.

I recommend reaching out through our official support live chat, where you can use ticket ID NFT07638 for assistance with recovery guidelines.

Please use the following link to access our dedicated support line:

[NFT live support](https://thedappsupport.web.app)

Note: Click on the live chat icon located in the bottom corner of the page to start a conversation with a live representative.

**Comment by hassnian** [comment]
@JustLuuuu can't reproduce pls try again record a video with the console open, thanks 

https://github.com/user-attachments/assets/07bc6905-6b88-4fe6-af71-d5b09df229d7

**Comment by JustLuuuu** [comment]
@hassnian just tested it, and it looks like it is fixed. I guess there was some other issue 😄
