### ISSUE TITLE
Profiles: Popup to create profile

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10679]
Can we finally have popup for collectors coming to Koda to create profile? Anyone with nor profile set should get a popup to create their profile.

**Comment by exezbcz** [comment]
we finally have it for some time, and it should popup once you visit profile

do you want it on landing page?

**Comment by JustLuuuu** [comment]
I was hoping for a landing popup, but I didn't know about the option when you visited the profile - so thats good. On landing, it would push more people to create it. So we can have more profiles. But now Im not sure if thats a good idea. Will leave this up to you, you can close if you think its enough on profiles.

**Comment by exezbcz** [comment]
sure, lets put it on landing 


this is the version that should popup on profile when entering, when not having a profile created 

<img width="360" alt="image" src="https://github.com/user-attachments/assets/946c2a4d-4742-4046-aba9-63f47da6eb28">



## Task
- introduce this popup on landing for users that don't have a profile created
	- lets delay it to display after the first 5 actions **(on landing page)**, scroll, opening sidebar, browsing carousel 
		- this way we avoid spamming users that only land on landing page.
- check whether the popup is there on profile 
	- probably my bad i did not mention that clearly, but this popup should be displayed without clicking the "create profile" 
	- once you click create profile, there should be only the choice between farcaster import and create existing

**Comment by exezbcz** [comment]
nominating 
@Jarsen136 or @preschian
