### ISSUE TITLE
Missing mints

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10678]
This collection - https://kodadot.xyz/ahp/collection/175
AHP - not sure where is the issue

Looks like this:

https://github.com/user-attachments/assets/bb413929-801d-4d9d-bca5-4621d8cdb449

**Comment by mikechao2022** [comment]
@JustLuuuu I checked it and it works well. 
![Screenshot_18](https://github.com/user-attachments/assets/9e2c233d-b0ea-493d-9037-8c40c501360e)
![Screenshot_19](https://github.com/user-attachments/assets/32168c61-6461-4f4a-abbd-badaad2ab181)

**Comment by JustLuuuu** [comment]
Ok then Im closing, I checked and its working now.
