### ISSUE TITLE
Green notifications: Make them nicer green

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10683]
Every time I see this Im like 🤮
<img width="268" alt="Screenshot 2024-07-24 at 10 23 44" src="https://github.com/user-attachments/assets/8184254e-0085-4872-b836-16d4975cd8a3">

Can we have it in a nice green? Like "submit new issue green". That khaki green is just weird. 
<img width="209" alt="Screenshot 2024-07-24 at 10 25 16" src="https://github.com/user-attachments/assets/d4eb9ba2-da48-4bf4-990e-a77c1371f666">

**Comment by roiLeo** [comment]
might be good to reuse https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=10766-13026&t=L9j6UCt5VCWcT3R0-0
