### ISSUE TITLE
No items.

### ISSUE THREAD

**Issue by gurucrypto23** [kodadot/nft-gallery#1068]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vikiival** [comment]
Looks like empty issue, please fix the description in the 24hrs otherwise we will close it. 


![image](https://user-images.githubusercontent.com/22471030/140824297-4eb26b48-c956-43d1-b8bc-c36b8f0ee1c6.png)

**Comment by yangwao** [comment]
I sense was trying fill out issues
