### ISSUE TITLE
When logged in with EVM wallet: Show switch wallet on Drops

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10691]
It took me a minute till I realized why I could not mint Polkadot drop. Im logged with evm wallet.

<img width="1323" alt="Screenshot 2024-07-26 at 11 27 25" src="https://github.com/user-attachments/assets/572de827-ae0e-4fb0-808e-f35bce1b4cbb">

Can we come up with some user-friendly solution how to make clear for users that they need to switch wallet in order to mint this drop?

**Comment by exezbcz** [comment]
yup, chatted with hassnian, we will introduce some sort of modal when clicking mint with polkadot wallet connected

**Comment by exezbcz** [comment]
<img width="819" alt="image" src="https://github.com/user-attachments/assets/499d4ebf-6762-4907-8715-f0586552fe4c">
https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=1287-18959&t=G6qvR8Ll5e0ZNTPS-11


design here

when clicked, it will open the web3modal (while disconnecting the polkadot wallet) 


when connected to evm wallet, redirect to the drop page 


same when going from evm frontend to polkadot drop
