### ISSUE TITLE
Remove/Reword code-checker parts

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#10705]
related: https://github.com/kodadot/ops-internal/issues/1774

Some checkers are probably unrelated since we changed how the capture service works.
- "Not Using WebGL" (now we can capture it, so it is safe to remove. Or is there any concern related to WebGL?)
- "Art Is Consistent" & "Automatic Sizing - Responsiveness" (need manual review for these? Maybe use gray question mark icon instead?)
- "Variation loading time < 3 seconds" (should we adjust this? since we already have an art that > 3s. less than **30s** should be fine, I think)

wdyt? @ThomasssArt @JustLuuuu 
cc @kodadot/internal-dev

**Comment by JustLuuuu** [comment]
"Variation loading time < 3 seconds"  - I still want to focus on art that doesn't need much to render; animations and infinite loops can be allowed. Once in a while we do an exception with art that needs more time to load, but I would keep this more as an exception

**Comment by ThomasssArt** [comment]
- Automatic sizing: I dont know if this is really needed. It only checks if resizeCanvas() was used in the code right? Many artists are using different resizing methods.

- WEBGL: Yes i guess thats not needed anymore.

- Variation loading time < 3 seconds: What if we replace adjustment time < 3s with "adjustment time" and thats it. If it fails we can check it and decide if it is ok or not.
