### ISSUE TITLE
Drops max count mismatch for a moment 

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#10706]
### What happened?

seems like we are getting the collection max from different places

![CleanShot 2024-07-30 at 14 37 04@2x](https://github.com/user-attachments/assets/32f3838f-20c3-4311-ac58-07aaf50599a2)

it goes from loading to -> see listing -> mint

ideally that `see listing` should not appear 

https://github.com/user-attachments/assets/ba5ca125-a32b-4405-a5d7-997cdfa90430

**Comment by vikiival** [comment]
because 256 is imo hardcoded :)

**Comment by preschian** [comment]
this is why I raise this docs: https://github.com/kodadot/ops-internal/discussions/1745
