### ISSUE TITLE
Cover image quality

### ISSUE THREAD

**Issue by ThomasssArt** [kodadot/nft-gallery#10729]
Cover image quality is always really bad. Does it compress the image so much? It would look so much better with a clean and sharp presentation. Maybe the size of the text of the description could be increased a bit too?!

Related issue:
- https://github.com/kodadot/ops-internal/issues/1819

![image](https://github.com/user-attachments/assets/7d8a4cbb-6433-416e-883b-b34903880e04)

**Comment by ThomasssArt** [comment]
I dont know which person is exactly responsible for this issue but i think one of you guys. @JustLuuuu @vikiival @exezbcz

**Comment by exezbcz** [comment]
cc @Jarsen136 @preschian 


is there anything that can be made without losing loading speed?

**Comment by vikiival** [comment]
> is there anything that can be made without losing loading speed?

Yes you can either:
- do load first the optimized variant and then load full
- make bigger variant on kodadot / would prob require reuplad few pieces

**Comment by exezbcz** [comment]
the recommended resolution is: 
![image](https://github.com/user-attachments/assets/63c7ac4f-8b43-434f-a108-869246f99ddf)

**Comment by vikiival** [comment]
@kodadot/internal-dev lets use the detail variant ![image](https://github.com/user-attachments/assets/710fc00b-7f87-4a45-8c7c-908e2a63d37c)

May some fix from @preschian would be needed 

Cc @Jarsen136

**Comment by preschian** [comment]
forgot to reply this, for higher resolution change from `public` to `detail`

from: https://imagedelivery.net/jk5b6spi_m_-9qC4VTnjpg/695df7b1-0f90-437d-bacd-3d71d99ecd7f-banner/public
to: https://imagedelivery.net/jk5b6spi_m_-9qC4VTnjpg/695df7b1-0f90-437d-bacd-3d71d99ecd7f-banner/detail

cc @Jarsen136
