### ISSUE TITLE
New charts engine

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1072]
@roiLeo has raised awareness of the big bundle of current chart

Proposed to use https://www.chartjs.org/ 
If we manage to keep original functionality, I'm up to it! 

Mind making PR against `main-nuxt` branch

**Comment by vikiival** [comment]
Since @yangwao is faster than light here is my issue

- Currently a price chart component has around ~2mb which can be slow for some device

<img width="1499" alt="Screenshot 2021-11-09 at 10 11 55" src="https://user-images.githubusercontent.com/22471030/140896916-027a6628-74d6-4986-b7da-fa64d01d80b0.png">
s

**Comment by yangwao** [comment]
Referring #279

**Comment by yangwao** [comment]
If we would figure out time scaling, I'm up to it https://www.chartjs.org/docs/latest/samples/scales/time-line.html

Seems quite light weight!

**Comment by rhaicode** [comment]
Interested

**Comment by yangwao** [comment]
Stradford was DM me about this, let's try do this

**Comment by rhaicode** [comment]
Hello! I'm Stradford from the cord. I'll start working on this now

**Comment by vikiival** [comment]
Chart.JS
<img width="385" alt="Screenshot 2021-11-10 at 14 36 40" src="https://user-images.githubusercontent.com/22471030/141122995-45337740-da00-484c-93df-964b8a8be2c6.png">

ECharts
<img width="399" alt="Screenshot 2021-11-10 at 14 37 00" src="https://user-images.githubusercontent.com/22471030/141123023-e7b66ba3-b707-4348-94cb-2e5a40ed4635.png">

<img src="https://http.cat/100" alt="continue" />

**Comment by vikiival** [comment]
>  I'll start working on this now

stage is yours

**Comment by rhaicode** [comment]
Hello! The progress for this issue is linked in this PR #1110
