### ISSUE TITLE
Koda Profile Text

### ISSUE THREAD

**Issue by ThomasssArt** [kodadot/nft-gallery#10730]
Text "not followed by anyone you're following" does not make sense in your own profile.

Related issue:
- https://github.com/kodadot/ops-internal/issues/1819

![image](https://github.com/user-attachments/assets/b9585bd6-dbbc-4028-9b4b-3514cd2c96f9)

**Comment by ThomasssArt** [comment]
I dont know which person is exactly responsible for this issue but i think one of you guys. @JustLuuuu @vikiival @exezbcz

**Comment by vikiival** [comment]
@ThomasssArt and what should be the output there?

**Comment by exezbcz** [comment]
@vikiival no text on your own profile probably

**Comment by ThomasssArt** [comment]
> @ThomasssArt and what should be the output there?

Exactly what @exezbcz wrote. Text in general is good just not on your own profile. Does this make sense for you?
