### ISSUE TITLE
Raise security bar on process 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1073]
Need to review what's we need to set up from shop 

https://github.com/kodadot/nft-gallery/security/code-scanning
new to me
![image](https://user-images.githubusercontent.com/5887929/140902874-23c4eb0f-8dc7-4df4-9f49-7cec3e1c6290.png)
![image](https://user-images.githubusercontent.com/5887929/140902903-6d2a28af-3ed9-40b7-8c9f-ea547db448bc.png)

**Comment by roiLeo** [comment]
IMO, we can add [Renovate](https://github.com/renovatebot/renovate) to chek dependencies update

**Comment by yangwao** [comment]
Ref #1858
