### ISSUE TITLE
Image tag on gen art on evm

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10736]
![image](https://github.com/user-attachments/assets/00c33c45-477d-47df-a145-64d29df537ed)

these things should not have a img tag

**Comment by exezbcz** [comment]
cc @Jarsen136 @preschian

**Comment by vikiival** [comment]
> @vikiival base is fixed, mantle has the same issue

- https://github.com/kodadot/basick/pull/61

**Comment by hassnian** [comment]
no image tag ✅

![CleanShot 2024-09-16 at 14 35 53@2x](https://github.com/user-attachments/assets/9f39ef79-2e69-4c32-9044-2f9fa969240f)
