### ISSUE TITLE
Pricing on drop cards

### ISSUE THREAD

**Issue by ThomasssArt** [kodadot/nft-gallery#10731]
Hi. This issue is to discuss about the topic of showing the price on drop cards. I agree that there is def. a lot of text/information already on the card and we should not overfill them. I still think it is important and i would like to discuss the topic with you guys.

![image](https://github.com/user-attachments/assets/4815083b-21c7-40b3-9960-f9cbe6257a06)

Related issues:
- https://github.com/kodadot/ops-internal/issues/1819
- https://github.com/kodadot/nft-gallery/issues/10674#issuecomment-2253791363

What if we just write the pricing in front of the already existing DOT (see picture below in red)?
![image](https://github.com/user-attachments/assets/63ab5cb6-0e90-4fd0-aa5c-d0e50f22a7d3)

**Comment by ThomasssArt** [comment]
Let me know your thoughts @JustLuuuu @vikiival @exezbcz

**Comment by exezbcz** [comment]
> What if we just write the pricing in front of the already existing DOT (see picture below in red)?

that is a network indicator and it could be confusing on other networks. For example base, you don't have "0.5 base" price

**Comment by exezbcz** [comment]
okay here is hybrid, maybe we can conduct some testing what the user/collector actually finds the most useful and the most useless. 

My bet is that its gonna be the part with profiles that minted the drop as not much people have created one and there is not much profiles that are recognizable/famous/highsignal yet

**Comment by exezbcz** [comment]
cc @hassnian

**Comment by ThomasssArt** [comment]
> okay here is hybrid, maybe we can conduct some testing what the user/collector actually finds the most useful and the most useless.
> 
> My bet is that its gonna be the part with profiles that minted the drop as not much people have created one and there is not much profiles that are recognizable/famous/highsignal yet

I really like your hybrid solution. But price needs to be in dot and not usd right? For me the drop card is not overfilled like this. I also really like that you see the profiles (even tough a lot of people havent created their profile yet).

Maybe you can discuss about the future look but from my side i think your hybrid is def an improvement!

**Comment by exezbcz** [comment]
@ThomasssArt hi, thanks for the feedback


the USD price is reacting to this: 
https://github.com/kodadot/nft-gallery/issues/10674#issuecomment-2253791363

**Comment by ThomasssArt** [comment]
But what i dont get is how can you show the price in USD? Or is this in the end a "live view" because otherwise its not possible to show the current price in USD. 0.5dot are not the same amount of USD during the day.

**Comment by vikiival** [comment]
> But what i dont get is how can you show the price in USD? 

Please check https://github.com/kodadot/nft-gallery/pull/10741

**Comment by exezbcz** [comment]
@ThomasssArt its dynamic based on the current price

**Comment by ThomasssArt** [comment]
> @ThomasssArt its dynamic based on the current price

Ok didnt know that. I mean in this case its quite ok. I still would def go for the price in DOT. 99% of all marketplaces are showing the price in ETH/TEZ/SOL and not USD... It is more connected to the nft and crypto space. 

But def up to you guys.

**Comment by JustLuuuu** [comment]
Price in USD is good too, lets have this and see how it goes, if people will be complaining we can change it in the future.

**Comment by ThomasssArt** [comment]
Ok in this case we have a solution :)
