### ISSUE TITLE
Popup does not recognize whether i already created a profile 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10743]
followup for: 
- https://github.com/kodadot/nft-gallery/issues/10679

# What
![image](https://github.com/user-attachments/assets/506e3cae-ad97-44a5-be7e-81c4bb519914)
- i already have created a profile, but i got this profile creation popup anyway 

## Task
- recognize whether the user has already created one. If so, don't display it 

cc @Jarsen136

**Comment by hassnian** [comment]
oh didn't see the issue mb https://github.com/kodadot/nft-gallery/issues/10745 #10745

@Jarsen136 if you find another better solution feel free to close my pr
