### ISSUE TITLE
Make sure that EVM connectors work properly

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10747]
### Context

Me and @exezbcz are experiencing an issues with signing both with Metamask and Talisman.
As Metamask is frequently used wallet I would be in favour of making it work.

### Task 

1. review the current implementation of Web3 modal 
2. consult the docs - https://docs.walletconnect.com/appkit/vue/core/installation
3. Test minting of both free drops and paid drops with - Metamask, Coinbase, Talisman?

![Screenshot 2024-08-05 at 12 25 17](https://github.com/user-attachments/assets/641286ca-3de1-4754-a850-de300737fd41)

In any case feel free to reach me in issue / TG

**Comment by yangwao** [comment]
are using eip6963 properly? 

https://walletconnect.com/blog/web3modal-v31-industry-leading-eip-6963-support-live
