### ISSUE TITLE
Optimize subscription 

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10749]
### Context

At this point we have it a very fancy behaviour of SubSquid API that it causes memory leak 

> [!NOTE]
> for humans - it means that app feels ultra slow

This is 99% caused by subscriptions and their incorrect usage

### Task

1. identify subscriptions in our app
2. if possible optimize their size
  - if not possible we can always update schema
3. if possible replace subscription with polling :)

### Convos 

Global

![Screenshot 2024-08-05 at 14 55 39](https://github.com/user-attachments/assets/3dc975b4-f337-4a4c-b8dd-455dc436d74b)

![Screenshot 2024-08-05 at 15 01 34](https://github.com/user-attachments/assets/924449c2-86f7-4603-a5c4-0979934d78d0)

**Comment by vikiival** [comment]
Assigning @preschian as he probably was implementing subscriptions last time, also help from anyone from @kodadot/internal-dev is welcomed :)

**Comment by preschian** [comment]
> Assigning @preschian as he probably was implementing subscriptions last time

Hah, me? I think it is false mention

one more reason for this: https://github.com/kodadot/ops-internal/discussions/1745

**Comment by vikiival** [comment]
> Hah, me? I think it is false mention

noted

> one more reason for this: https://github.com/kodadot/ops-internal/discussions/1745

Won't help :), you will get same issue on other drops, chains etc
+ app is already slow

**Comment by preschian** [comment]
> Won't help :), you will get same issue on other drops, chains etc

Why? 

For example, this PR works fine: https://github.com/kodadot/nft-gallery/pull/10713. unless, I just found some drops doesn't have `supply` functions
