### ISSUE TITLE
xmark does not close reconnect modal + styling

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10754]
https://github.com/user-attachments/assets/fecbcf31-d7cf-4196-a1f9-efb1d33dc5b9

x mark does not close modal, clicking outside does. 

cc @hassnian

**Comment by exezbcz** [comment]
annnd one small thing, on all modals there should be our drop shadow, sorry that i did not added it in the figma 
![image](https://github.com/user-attachments/assets/19b34acf-09c6-4f5b-ba4f-f3be4a2abdcd)

**Comment by dvelikiy** [comment]
👋
