### ISSUE TITLE
After connecting with EVM wallet and clicking on "Drops" Im redirected to ahp drops

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10751]
Problem
---
Im unable to find Base drops after logging in with EVM wallet. I only found ahp drops.

Reproduce
---
- log in with evm wallet - Base
- click on "drops" 
- you will be redirected to ahp drops. 

Here
---

https://github.com/user-attachments/assets/538c88db-970b-4edf-8edd-3368686fc0af

I was only able to find base drops by going to explore - opening collection and then clicking on the drop.

**Comment by Jarsen136** [comment]
It has been fixed on canary env. Waiting for the next release.

 https://canary.kodadot.xyz/
