### ISSUE TITLE
Switch nft creator to artist on nft 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10760]
Ref: 
- https://github.com/kodadot/ops-internal/issues/1822
![image](https://github.com/user-attachments/assets/e17630d1-b0be-4a2b-b9d8-356b6cf49091)

# Task
- on all our generative drops, please change the "creator" to the artist of the drop, and the owned by to the minter/current holder

**Comment by vikiival** [comment]
Well the is more issue of the data than the collection itself

**Comment by hassnian** [comment]
![CleanShot 2024-10-16 at 08 54 49@2x](https://github.com/user-attachments/assets/6cdbf699-e1ce-4fe8-8e5b-d7b5ec9103bf)
