### ISSUE TITLE
Sync main branch into main-nuxt

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1077]
It's time to continue on handovering to new branch stuff so we can be in sync and avoid ppl making PRs into old code.

- [x] merge `main` into `main-nuxt` 
- [x] delete all stuff root connected with old **SPA** in `main-nuxt`
- [x] put the context of folder `/nuxt` to the upper directory
- [ ] re-set deploy from root directory -- that's on @yangwao 
- [ ] enjoy new PRs!

# ref
#1060

**Comment by yangwao** [comment]
let's see 
![image](https://user-images.githubusercontent.com/5887929/141159599-f4b617af-d396-4e8b-82e1-b44fad922724.png)

![image](https://user-images.githubusercontent.com/5887929/141159670-ff588b86-2eeb-4d43-bb83-cf9600cf1387.png)

**Comment by yangwao** [comment]
Seems it's building! 
![image](https://user-images.githubusercontent.com/5887929/141160796-60de0746-f5cf-4097-8f82-a2148caa4493.png)

**Comment by vikiival** [comment]
Migrating from SPA to SSG 

<img src="https://http.cat/101" />
