### ISSUE TITLE
Minting: Steps missing

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10780]
I minted two NFTs from [the latest drop](https://koda.art/ahp/drops/linear). And this is how it looked like. 
<img width="1236" alt="Screenshot 2024-08-10 at 12 50 17" src="https://github.com/user-attachments/assets/b6a880c9-4516-4ef3-8a33-07e429042185">

Follow steps: EMPTY. 

Once I clicked on mint this window appeared I signed first transaction -bridging (it still looked the same) I signed the second transaction (it still looked the same). There are missing those three steps where it shows that bridging is happening, checking funds and minting is happening

**Comment by exezbcz** [comment]
linking
- https://github.com/kodadot/nft-gallery/issues/10726

i had the same thing even after the pr, so it does not seem to be fixed

**Comment by exezbcz** [comment]
this issue is already solved on canary.kodadot.xyz


could you please try there and let us know if it persists?

**Comment by JustLuuuu** [comment]
works
