### ISSUE TITLE
Following of polkadot account with evm wallet connected 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10785]
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/97e6ab69-3c6f-4342-8ca4-3126bb1cef60">
yeah this is tricky, i have connected a evm wallet (or idk, but in sidebar it shows it) and I am trying to follow account that has profile created but on polkadot wallet

# What I expect to happen
- wallet modal switch for this action, then automatically follow him.

**Comment by exezbcz** [comment]
nominating either @Jarsen136 or @preschian

**Comment by Jarsen136** [comment]
> yeah this is tricky, i have connected a evm wallet (or idk, but in sidebar it shows it) and I am trying to follow account that has profile created but on polkadot wallet
> # What I expect to happen
> * wallet modal switch for this action, then automatically follow him.

I don't see any problem here. Under the current architecture, Evm accounts can follow both evm and Substrate addresses, because the profile relationship is off-chain.

**Comment by exezbcz** [comment]
<img width="434" alt="image" src="https://github.com/user-attachments/assets/bbf360ab-8186-4e3a-b31c-cd9fdcb95696">


ah did not add the thing it displayed 


- i don't see any issue with that if its already working

**Comment by Jarsen136** [comment]
> <img alt="image" width="434" src="https://private-user-images.githubusercontent.com/90852205/356811218-bbf360ab-8186-4e3a-b31c-cd9fdcb95696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTYxMDYsIm5iZiI6MTcyMzI5NTgwNiwicGF0aCI6Ii85MDg1MjIwNS8zNTY4MTEyMTgtYmJmMzYwYWItODE4Ni00ZTNhLWIzMWMtY2Q5ZmRjYjk1Njk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDEzMTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkM2IzZmY3YjIwMTlhNTBmOWJhNTI2NWM4NjRlZmZlMmJhM2ViZTg4OThiNmEwZmE4M2NmNTAzNzQzNzY4ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gA-BJHPIDokfI9xSiLdxrzZoknxNwSI-z0eo0HhmSYo">
> ah did not add the thing it displayed
> 
> * i don't see any issue with that if its already working

oh I see.

It's related to the evm connection.  Probably it have been fixed in https://github.com/kodadot/nft-gallery/pull/10762

**Comment by hassnian** [comment]
evm -> dot 
dot -> evm

both are working
