### ISSUE TITLE
All Base drop shows only 1 minted NFT

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10804]
<img width="1667" alt="Screenshot 2024-08-13 at 12 56 30" src="https://github.com/user-attachments/assets/d0e90da5-e0bc-41d4-b5a8-35f194dd8ba7">

**Comment by JustLuuuu** [comment]
This one shows two but there are 4:
https://canary.kodadot.xyz/base/drops/hopa

**Comment by hassnian** [comment]
fixed by #10713

![CleanShot 2024-08-14 at 15 55 46@2x](https://github.com/user-attachments/assets/08e78bf3-9705-4db6-bd40-71554efecb14)
