### ISSUE TITLE
Artist not able to create profile on Base

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10819]
Artist: Eduxdux
<img width="356" alt="Screenshot 2024-08-15 at 12 27 26" src="https://github.com/user-attachments/assets/3e9a7005-2b4e-4060-be29-4fd18932f6b0">
His Drop: https://canary.kodadot.xyz/base/drops/cncrdnte
His address: 0x22D02786f813A70c5699621810D0ea85efA07332

Error:
![358193676-10901f40-63aa-4224-ac20-41e8f723b2c0](https://github.com/user-attachments/assets/da77c77d-1b96-4709-9c7f-5666cc2c6850)

**Comment by JustLuuuu** [comment]
Artist: Reza Milani
Issue: Cannot read properties
Profile: https://canary.kodadot.xyz/base/u/0x618E7c40f1793d021Bb0c9c50AAF37B2D589a08c

<img width="1367" alt="Screenshot 2024-08-15 at 14 27 48" src="https://github.com/user-attachments/assets/ee32184d-846f-4bdd-94cf-13ac92f3cfc0">

**Comment by hassnian** [comment]
fixed by #10799

yesterday beta got a release with the fix  #10832

already working https://beta.kodadot.xyz/

pls reopen if anything
