### ISSUE TITLE
Greyed out profile 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10814]
![image](https://github.com/user-attachments/assets/1731737c-079e-46da-b901-cafeed25edc0)
somehow managed to get a invisible modal when going from drop -> my profile with a evm wallet connected 

scroll is disabled and clicking anywhere closes the modal and everything is alright

https://github.com/user-attachments/assets/8c213ce6-73e9-49a0-a6ec-8aa9935c76c7

![image](https://github.com/user-attachments/assets/ad0a3858-e089-4ff8-b708-7a4c11cf9d11)

**Comment by hassnian** [comment]
should by fixed by #10834
