### ISSUE TITLE
Follow not working on Base

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10818]
Im logged in with my EVM wallet and I cannot follow anyone. Getting this message: 
<img width="331" alt="Screenshot 2024-08-15 at 12 09 02" src="https://github.com/user-attachments/assets/c7091b10-5040-42ec-82d4-0a33ff163a2c">

https://github.com/user-attachments/assets/c7b0bf38-ce98-482f-8006-c47243949ea4

**Comment by hassnian** [comment]
can't reproduce, it has seen been a while so it's likely already fixed 

seems like the same issue as #10785

![CleanShot 2024-10-16 at 09 02 38](https://github.com/user-attachments/assets/6d0dafc8-b248-45fd-b655-47987bfe2d14)
