### ISSUE TITLE
Mass minting drops on evm 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10815]
seems like we dont have this enabled, can we have a look at this? 

![image](https://github.com/user-attachments/assets/c96f0176-d8cc-480a-9ba1-f34012ce7146)

design is the same as with polkadot

**Comment by exezbcz** [comment]
nominating the person who did the mass mint integration on polkadot

**Comment by hassnian** [comment]
it's not available at this moment with the current implementation of [gensol](https://github.com/kodadot/gensol) 

will discuss https://github.com/kodadot/ops-internal/discussions/1855

-----

interesting 

- https://www.erc721a.org/

**Comment by vikiival** [comment]
Yes can be part of dev talk

**Comment by hassnian** [comment]
`batchMint ` added to gensol https://github.com/kodadot/gensol/pull/9

blocker: drop with the new version of the contract

**Comment by vikiival** [comment]
I can reupload Quadz with batch mint :)

**Comment by hassnian** [comment]
> I can reupload Quadz with batch mint :)

yes please + updated ABI

**Comment by vikiival** [comment]
- https://github.com/kodadot/basick/pull/52

[abi](https://github.com/user-attachments/files/16761027/basegen.json)

**Comment by hassnian** [comment]
@vikiival 
1. `/base/collection/0x8e985d2804d2d4d9e7b2aad0e4a2f35212e5420a`it's not indexed 
![CleanShot 2024-09-09 at 16 29 56@2x](https://github.com/user-attachments/assets/72b52761-bbd8-4f67-9d66-3d4247040d57)


2. `quadz` drop should also have `collection` field updated

**Comment by vikiival** [comment]
@hassnian can you try this one ?

- https://github.com/kodadot/ops-internal/issues/1888#issuecomment-2340032800
