### ISSUE TITLE
Hopa: Base drop: connect drop with proper artist

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10827]
Drop: https://kodadot.xyz/base/drops/hopa
Artist profile + address: https://kodadot.xyz/base/u/0x651DA61ec8c9512b816086835c7f90c485850b62

Set Artist wallet as a creator for this collection

**Comment by roiLeo** [comment]
> Set Artist wallet as a creator for this collection

Nothing wrong, original minter is Kodadot Address (0xE844...)

**Comment by JustLuuuu** [comment]
Updated in ipfs: https://kodadot.xyz/base/drops/hopa
