### ISSUE TITLE
Drop: SKY Address issues

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10824]
**This drop**: https://kodadot.xyz/base/collection/0x3cdd2e17f89013aee84315205b07d252f0c7106b
**When you click on the creator**, this is set to be the artist profile: https://kodadot.xyz/base/u/0x3e00e8a658924c4b5fd37784393e0932bb269189
**Reality, this is artists profile**: https://kodadot.xyz/base/u/0x3E00E8a658924C4b5fD37784393e0932bB269189

What is the issue? Compare profile links: 
https://kodadot.xyz/base/u/0x3e00e8a658924c4b5fd37784393e0932bb269189 (all small letters)
https://kodadot.xyz/base/u/0x3E00E8a658924C4b5fD37784393e0932bB269189 (some letters are in capital)

Related to: https://github.com/kodadot/nft-gallery/issues/10821

**Comment by vikiival** [comment]
![Uploading Screenshot 2024-08-19 at 12.45.35.png…]()
