### ISSUE TITLE
Not showing artist at his Base drop

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10820]
Drop: https://canary.kodadot.xyz/base/collection/0x2cc76e51c4ae3ed7b0dcada34c1ea4fe059d5881

Problem
---
Creator is on both to be set as Koda minter. Where is artist mention?

Artist address: 0x22D02786f813A70c5699621810D0ea85efA07332
Adress set as a creator on drop page: 0xe844b2a0a6453250c920bd2b4b7741946ab16c08
Adress set as a creator on collection view: 0xE844b2a0a6453250c920BD2b4B7741946aB16C08

Last two addresses are same just some letters are big and some small in one of them - wtf (will open a separate issue for this separately)

<img width="1687" alt="Screenshot 2024-08-15 at 12 30 47" src="https://github.com/user-attachments/assets/db906be1-afff-476f-9e86-158209a9171c">
<img width="1542" alt="Screenshot 2024-08-15 at 12 30 34" src="https://github.com/user-attachments/assets/d440c1b1-69f1-4cf5-80c3-0ca048f193e0">

**Comment by Jarsen136** [comment]
> Drop: https://canary.kodadot.xyz/base/collection/0x2cc76e51c4ae3ed7b0dcada34c1ea4fe059d5881
> 
> ## Problem
> Creator is on both to be set as Koda minter. Where is artist mention?
> 
> Artist address: 0x22D02786f813A70c5699621810D0ea85efA07332 Adress set as a creator on drop page: 0xe844b2a0a6453250c920bd2b4b7741946ab16c08 Adress set as a creator on collection view: 0xE844b2a0a6453250c920BD2b4B7741946aB16C08
> 


In order to show the real artist's address, we need to manually update the `creator` of the drop. It should be able to be edited on cloudflare. @JustLuuuu  

![image](https://github.com/user-attachments/assets/6f4059ed-5528-4e46-807a-181dbda17ece)

**Comment by roiLeo** [comment]
looks like `0xE844b2a0a6453250c920BD2b4B7741946aB16C08` is the right one

**Comment by JustLuuuu** [comment]
Updated all creators on old Base drops.
