### ISSUE TITLE
Landing create modal still appearing with a profile

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#10828]
### What happened?

![CleanShot 2024-08-15 at 17 34 57@2x](https://github.com/user-attachments/assets/1906f94c-9d96-4a79-9cce-d8e76a47c2d6)

### How to reporduce

- visit carousel 
- toggle sidebar
- connect wallet (with profile)
- modal appears :d

**Comment by Jarsen136** [comment]
https://github.com/kodadot/nft-gallery/pull/10829#issuecomment-2291610976
