### ISSUE TITLE
Transfer not loading balance

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10835]
Transfer is not loading balance for me. I have funds in my wallet but I cannot see them in transfer. Tried reloading. Tried koda.art and kodadot.xyz and canary.

<img width="1649" alt="Screenshot 2024-08-16 at 12 04 13" src="https://github.com/user-attachments/assets/b694be70-4b96-499b-9029-6c3cbaf18907">

**Comment by hassnian** [comment]
fixed #10801  :)
