### ISSUE TITLE
Drops on Base show AHP drops

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10831]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

/base/drops shows ahp drops!

### Please reproduce in steps

open https://koda.art/base/drops
you see drops from https://koda.art/ahp/drops

### Expected Behavior

I expect to see base drops

### Are you logged in?

None

### Screenshots

![Screenshot 2024-08-15 at 18 38 28](https://github.com/user-attachments/assets/f3a3757a-4faa-413e-83d6-472d4bf7cbb7)

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
It should have been fixed on canary 👀  @vikiival 
https://canary.kodadot.xyz/base/drops

**Comment by vikiival** [comment]
It's also working on beta 
Just production seems to be fokked

**Comment by vikiival** [comment]
- https://github.com/kodadot/nft-gallery/pull/10832
