### ISSUE TITLE
4. cancel / accept offer

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/nft-gallery#10846]
## Cancelling offer
<img width="914" alt="image" src="https://github.com/user-attachments/assets/01fef2fc-638a-41c3-833d-423bceab7667">

Cancel offer is the same button as for unfollow, without hover effect, just the cursor pointer 

## Accept offer

![image](https://github.com/user-attachments/assets/be134f5f-0baf-4c70-b165-b7f5596c85f7)

more details cc @exezbcz

**Comment by exezbcz** [comment]
added accept offer 
![image](https://github.com/user-attachments/assets/3d1776e6-2ede-4d65-9575-f780b89c79b3)


updated in figma: 
https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=11027-1025&t=xJkvYJfCeC2BLVk2-11


button has no hover
