### ISSUE TITLE
2. creating offer signing design

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/nft-gallery#10844]
Linked with https://github.com/kodadot/nft-gallery/issues/10807

# Signing
![image](https://github.com/user-attachments/assets/d17256b6-5c01-427a-8280-092ba79ad4fd)
in the figma, there is a diagram of the flow

### Once you click Create offer
- waiting for signing, once you sign, the whole flow moves to toasts 
<img width="1101" alt="image" src="https://github.com/user-attachments/assets/b1094046-b0bd-45c5-9452-95e988b7441c">
- if you cancel signing, this is displayed
<img width="966" alt="image" src="https://github.com/user-attachments/assets/0cd96a77-8e17-412d-93b2-e456f181e31b">
please reuse existing toasts designs and flow from signing drops etc.

**Comment by exezbcz** [comment]
one note, when you are signing, you should not get the congrats modal, follow the flow chart
