### ISSUE TITLE
Future drop is in the past drops

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10847]
### Context

I was looking for `turbulent` drop and found it as a past drop

![Screenshot 2024-08-16 at 21 06 40](https://github.com/user-attachments/assets/2b44f5ba-8e0a-4dd0-ba31-ed707bfbd258)

However per DB it will be dropped 17th of August

![Screenshot 2024-08-16 at 21 08 23](https://github.com/user-attachments/assets/7c8036ec-1fce-42c1-a1a4-ad0b1bcbbe93)

### Task

make sure that future drop is considered as future drop, not in the past section

**Comment by vikiival** [comment]
https://koda.art/base/drops/turbulent

**Comment by hassnian** [comment]
seems to be fixed 

![CleanShot 2024-08-17 at 09 37 58@2x](https://github.com/user-attachments/assets/8b34482b-685b-4f30-b160-24202ff05020)

**Comment by hassnian** [comment]
seems to be fixed 

![CleanShot 2024-08-17 at 09 37 58@2x](https://github.com/user-attachments/assets/8b34482b-685b-4f30-b160-24202ff05020)
