### ISSUE TITLE
3. Offers tab in gallery item

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/nft-gallery#10845]
linked with https://github.com/kodadot/nft-gallery/issues/10807

# Offers tab in gallery item
slight refresh for the gallery item offer tab
![image](https://github.com/user-attachments/assets/060b518e-6ab7-4d0a-b26c-1c4048559188)

- it will be the second tab 
- there is amount, expiration, from and a button for accept if you are the owner of the nft 

## Mobile layout
- added in there
<img width="444" alt="image" src="https://github.com/user-attachments/assets/634323d2-c3eb-41e0-bcec-fff68fa5c08a">

**Comment by Jarsen136** [comment]
Could you please help with this issue and also #10846?  @hassnian

**Comment by hassnian** [comment]
> Could you please help with this issue and also #10846?  @hassnian 

Sure
