### ISSUE TITLE
wallet switching from evm wallet to polkadot drop 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10853]
please checkback once this one is merged: 
- https://github.com/kodadot/nft-gallery/pull/10720

![image](https://github.com/user-attachments/assets/6d9e0a93-6be5-41c8-a707-986e5b0f2a7f)

currently, having a evm wallet connected and clicking on the polkadot drop, it displayes wallet reconnect, but it wants you to connect to **EVM** wallet

**Comment by roiLeo** [comment]
> currently, having a evm wallet connected and clicking on the polkadot drop, it displayes wallet reconnect, but it wants you to connect to **EVM** wallet

not able to reproduce it
