### ISSUE TITLE
Art Card "infinite symbol"

### ISSUE THREAD

**Issue by ThomasssArt** [kodadot/nft-gallery#10855]
Just wanted to ask/suggest if it is possible to replace the number "100000...." with an infinite symbol "∞"? Would look much better.

![grafik](https://github.com/user-attachments/assets/7e1a2b95-045e-4f82-a5cb-24f7ff9573db)

**Comment by hassnian** [comment]
It's already implemented :D

https://canary.kodadot.xyz/base/drops


<img src=https://github.com/user-attachments/assets/4af7b4fe-d64a-43a3-89b7-b3fa99f738c2 width=400 /> 

<img src=https://github.com/user-attachments/assets/763d5e00-b9b2-45d1-adeb-0d72a94bbf07 width=400 />

**Comment by vikiival** [comment]
Hey @ThomasssArt I plan to do a release just wanna recheck other PRs

**Comment by ThomasssArt** [comment]
Thats great. Happy to hear :)

**Comment by ThomasssArt** [comment]
Btw i just recognized this:
![image](https://github.com/user-attachments/assets/f3feb5b9-75dc-4705-8e52-f02d195c1cc2)

I guess this will be also fixed right?

**Comment by ThomasssArt** [comment]
And sorry, last question i only can mint 1 and not multiple?

**Comment by hassnian** [comment]
> I guess this will be also fixed right?

yep, already fixed see my screenshot 

> And sorry, last question i only can mint 1 and not multiple?

issue https://github.com/kodadot/nft-gallery/issues/10815

**Comment by ThomasssArt** [comment]
> > I guess this will be also fixed right?
> 
> yep, already fixed see my screenshot
> 
> > And sorry, last question i only can mint 1 and not multiple?
> 
> issue #10815

Missed the second screenshot sorry...
