### ISSUE TITLE
Rename `KodaDot` to `Koda` throughout the app 

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#10854]
since

<img src=https://github.com/user-attachments/assets/8d0d018f-0f80-48e9-a6b0-41237d3d9745 width=400 />

translation files should also be updated to reflect that

**Comment by JKrupinski** [comment]
:wave:

**Comment by hassnian** [comment]
only names  

> translation files should also be updated to reflect that

replace kodadot with koda
