### ISSUE TITLE
Drop card having overflow 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10850]
if there is a huge number in the database, let's replace it with infinity symbol 
![image](https://github.com/user-attachments/assets/730c3667-fc8b-46d7-9239-497ecf75fab6)

heard damsky and viki had issues with having the big numbers even on the drop page and in the confirm modal

# ∞

**Comment by exezbcz** [comment]
Reference: 
- https://github.com/kodadot/nft-gallery/pull/10849

as per the states we had for the old card, i would like to still see the price + supply 
![image](https://github.com/user-attachments/assets/8dc357fe-f78e-44f6-8a27-f07a18250bed)

currently in the pr, there is only the date

**Comment by vikiival** [comment]
This overflows because there is time there

![Screenshot 2024-08-19 at 12 38 53](https://github.com/user-attachments/assets/96e4c60d-a509-41b3-af02-5c4f4dcfc112)

**Comment by vikiival** [comment]
cc @kodadot/internal-dev ?
