### ISSUE TITLE
Sharing of evm drop results with internal server error 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10867]
![image](https://github.com/user-attachments/assets/acbbaa21-f177-4ee9-84b8-5c8a6cbe8600)
![image](https://github.com/user-attachments/assets/a95d8299-8acc-4444-bcc0-70dbf840aceb)

https://frame.kodadot.workers.dev/gallery/base/0x9789b13d485b124255f9dbf42aa7091aa22e87f8

i was sharing that i have minted this nft 
![image](https://github.com/user-attachments/assets/1a9e73d7-f6cd-45b6-8794-2c2c8934a03e)

https://canary.kodadot.xyz/base/gallery/0x9789b13d485b124255f9dbf42aa7091aa22e87f8-4

**Comment by exezbcz** [comment]
cc @vikiival

**Comment by vikiival** [comment]
Can you please describe your issue?

**Comment by exezbcz** [comment]
@vikiival the frame is not created

**Comment by vikiival** [comment]
Found, thanks

https://warpcast.com/vikiival/0x99d72fa5
