### ISSUE TITLE
Evm Gallery Item missing animation 

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#10875]
### What happened?

https://github.com/user-attachments/assets/debacecf-adab-41ca-b4c5-926e786064ad

**Comment by hassnian** [comment]
waiting https://github.com/kodadot/nft-gallery/issues/10736#issuecomment-2345482782

**Comment by vikiival** [comment]
fixed?

**Comment by hassnian** [comment]
yes
