### ISSUE TITLE
Format collection description on collection view

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1087]
Let's make it better for mobile and by default looks nicer, to save some space

|Items | unique owners |
| :--: | :--: |
|Floor | volume traded |

![Screenshot_20211111-081959.jpg](https://user-images.githubusercontent.com/5887929/141255248-bb9cac1f-3d1e-49d0-9377-093090cca398.jpg)

**Comment by prachi00** [comment]
@yangwao I'll try to do this

**Comment by yangwao** [comment]
😍

**Comment by prachi00** [comment]
@yangwao is this same as #1217 ?

**Comment by yangwao** [comment]
ah yeah true, it's was really tingling my mind as you can see! 😄
Thank you for making #1217 !

**Comment by prachi00** [comment]
> ah yeah true, it's was really tingling my mind as you can see! 😄 Thank you for making #1217 !

yeah I was going to do this next, then I was like wait I just did this 😄
