### ISSUE TITLE
Error .hdd #323 .hdd #322

### ISSUE THREAD

**Issue by kirillmcq2012** [kodadot/nft-gallery#10879]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

There is some error in the collection . HDD , #322 #323 NFT is repeated, if possible please correct it.

### Please reproduce in steps

There is some error in the collection . HDD , #322 #323 NFT is repeated, if possible please correct it.

### Expected Behavior

if possible please correct it.

### What browsers are you seeing the problem on?

Desktop Chrome, Mobile Android Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### At which chain did you encounter bug?

Asset Hub Polkadot

### Screenshots

![5345832831852602801](https://github.com/user-attachments/assets/4a201485-a99f-4078-ae31-6e23ae388fde)
![5345832831852602799](https://github.com/user-attachments/assets/7bfb67c6-052e-4e28-860a-1a0ffaf5162f)
![5345832831852602800](https://github.com/user-attachments/assets/41d664fb-3be6-4190-9b77-5e4c86a6e2b2)

### Wallet Address & Transaction hash

14dD5NVB7iT4YSjjQNja1dawfYJZQVyzVDCAQVrbndxdeSDv

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by preschian** [comment]
need to resync the indexer cc @vikiival 
for this item, metadata already returns `#338` instead of `#323`

I'm checking on the generate ID function

**Comment by preschian** [comment]
Thanks for reporting the issue. Feel free to reopen if you find this bug again
