### ISSUE TITLE
error  Ezop #60 

### ISSUE THREAD

**Issue by kirillmcq2012** [kodadot/nft-gallery#10878]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

Some kind of bug in the collection  Ezop, #60 NFT repeated, if it can be fixed please.

### Please reproduce in steps

Some kind of bug in the collection  Ezop, #60 NFT repeated, if it can be fixed please.

### Expected Behavior

 if it can be fixed please.

### What browsers are you seeing the problem on?

Desktop Chrome, Mobile Android Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Nova Wallet

### At which chain did you encounter bug?

Asset Hub Polkadot

### Screenshots

![5345832831852602796](https://github.com/user-attachments/assets/51897382-baca-42db-b031-e4208f69d295)
![5345832831852602795](https://github.com/user-attachments/assets/6f0ce443-1f07-41b0-b041-f061fc2a79b1)
![5345832831852602794](https://github.com/user-attachments/assets/9388be04-d13c-4b3b-b046-98920ab85977)

### Wallet Address & Transaction hash

14dD5NVB7iT4YSjjQNja1dawfYJZQVyzVDCAQVrbndxdeSDv 

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by kirillmcq2012** [comment]
Wallet Address  13nFqQNWrXewKfNW9esRPsSDVsnguNqUmXi3LTRpQn54ymxP

**Comment by vikiival** [comment]
should be gone?

**Comment by JustLuuuu** [comment]
<img width="1352" alt="Screenshot 2024-08-29 at 12 45 47" src="https://github.com/user-attachments/assets/19b941e4-bb5d-4476-a768-c96e09622c94">
I see only 1 Ezop 60 now, so it should be fixed. 😊
