### ISSUE TITLE
Rapha nyc wrong supply displayed

### ISSUE THREAD

**Issue by ThomasssArt** [kodadot/nft-gallery#10888]
I just recognized that on Raphas drop, the wrong supply on the art card gets displayed:
![grafik](https://github.com/user-attachments/assets/8f2d2c76-7476-4ff7-962e-30e6f1d5f8d8)

It should be 64 like in the minting view:
![grafik](https://github.com/user-attachments/assets/77c24578-2e55-416f-8233-816b149defba)

**Comment by vikiival** [comment]
Thanks

![Screenshot 2024-08-22 at 11 18 02](https://github.com/user-attachments/assets/8d8a72f3-bc3d-46c6-bca6-32832c9efc96)
