### ISSUE TITLE
Show only collections with traded volume

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1088]
For example, you would like to see only collections with activity, ie traded volume

There might one similar issue to filtering collections with attributes

There could be two filters from a time range
- 30d 
- 180d

If probably there is not activity since then, collection might be dead?

**Comment by yangwao** [comment]
Connect it with https://github.com/kodadot/nft-gallery/issues/1023

**Comment by joelamouche** [comment]
So just to clarify: this on the collection page (https://kodadot.xyz/rmrk/explore?page=1) ?

**Comment by petersopko** [comment]
> So just to clarify: this on the collection page (https://kodadot.xyz/rmrk/explore?page=1) ?

that's the plan with this feature, yes, we'd like to add more filters to the collections search section
