### ISSUE TITLE
Drop profile picture not existing - mettle 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10883]
https://canary.kodadot.xyz/base/drops/mettle
![image](https://github.com/user-attachments/assets/46e8a766-04e0-4fda-9309-bf6896909c30)

**Comment by exezbcz** [comment]
cc @preschian

**Comment by preschian** [comment]
added for the quick fix, that was because missing value from database. for proper fix, let's adjust it to get value from on-chain data

related: https://github.com/kodadot/ops-internal/discussions/1745

**Comment by vikiival** [comment]
![Screenshot 2024-08-22 at 09 59 42](https://github.com/user-attachments/assets/150fdb9c-324e-4c04-a271-36acbddb0b7b)
