### ISSUE TITLE
Ezop collection indexing problem

### ISSUE THREAD

**Issue by ThomasssArt** [kodadot/nft-gallery#10882]
I think there is an indexing problem (or at least there is a problem) with the last mint in the Ezop collection. #63 looks the same as #60.

[Collection Link](https://koda.art/ahp/drops/ezop)

![image](https://github.com/user-attachments/assets/43511d27-4434-4a5e-aa7f-a2ea4cd67edb)

**Comment by preschian** [comment]
similar with this: https://github.com/kodadot/nft-gallery/issues/10879#issuecomment-2301808393

**Comment by ThomasssArt** [comment]
> similar with this: [#10879 (comment)](https://github.com/kodadot/nft-gallery/issues/10879#issuecomment-2301808393)

ok. can i close this issue or keep it open?

**Comment by vikiival** [comment]
should be gone?

**Comment by ThomasssArt** [comment]
Not for me...
![grafik](https://github.com/user-attachments/assets/bb3de7d0-3fe7-46ab-8395-a118fa44f985)

**Comment by vikiival** [comment]
Cc @preschian ?

**Comment by preschian** [comment]
@ThomasssArt could you try again, or open it on incognito. I just cleared the thumbnails cache

**Comment by ThomasssArt** [comment]
> @ThomasssArt could you try again, or open it on incognito. I just cleared the thumbnails cache

Looks good now. Just #60 needs to get in front of #61.
![grafik](https://github.com/user-attachments/assets/4fff3991-bdd5-4462-9354-d8283b914a7a)

**Comment by preschian** [comment]
Thanks for reporting the issue. Feel free to reopen if you find this bug again
