### ISSUE TITLE
eco drop - wrong supply displayed

### ISSUE THREAD

**Issue by ThomasssArt** [kodadot/nft-gallery#10895]
Hi Viki. Same issue as yesterday with rapha nyc's drop:

Art card shows 256:
![image](https://github.com/user-attachments/assets/78b16522-9e5e-4dc4-ab26-82dc94cffa89)

Correct would be 64:
![image](https://github.com/user-attachments/assets/67fc046c-3b75-4c2c-aed1-58183a0dbe19)

**Comment by vikiival** [comment]
Should be fixed imo

**Comment by ThomasssArt** [comment]
yes perfect thx
