### ISSUE TITLE
error - island #4 , #5 

### ISSUE THREAD

**Issue by kirillmcq2012** [kodadot/nft-gallery#10894]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

 again  error #4 , #5 repeated . collection island

### Please reproduce in steps

 again  error #4 , #5 repeated . collection island

### Expected Behavior

if possible please correct it.

### What browsers are you seeing the problem on?

Mobile Android Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Nova Wallet

### At which chain did you encounter bug?

Asset Hub Polkadot

### Screenshots

![5350474858275922377](https://github.com/user-attachments/assets/b5c995a0-baca-4432-8bb3-9f5ac90477cf)
![5350474858275922376](https://github.com/user-attachments/assets/903d244f-923d-43d0-9da7-9f8c86e56994)

### Wallet Address & Transaction hash

13nFqQNWrXewKfNW9esRPsSDVsnguNqUmXi3LTRpQn54ymxP

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
Can confirm that is the bug

![Screenshot 2024-08-23 at 10 43 32](https://github.com/user-attachments/assets/bf86713a-ecef-4cb6-8c28-ca13eacf7f80)

**Comment by vikiival** [comment]
should be gone?

**Comment by preschian** [comment]
Thanks for reporting the issue. Feel free to reopen if you find this bug again
