### ISSUE TITLE
Base: Minting issue

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10905]
Artist (Reza Milani received this message). One of her collectors is not able to collect:

Collection: https://kodadot.xyz/base/drops/waitw

<img width="657" alt="Screenshot 2024-08-26 at 13 09 12" src="https://github.com/user-attachments/assets/ae0cc2e0-66ab-477b-962a-16bc05b721ce">

Contract Call: address:0x56942507f0078dac2811fe32551e26fca6a933b
function: safeMint(address to) args:(0x5133135153964675f9fd2eD6D234572129af3a87)
sender: 0x5133135153964675f9fd2eD6D234572129af3a87

**Comment by vikiival** [comment]
The drop had incorrect price 0.002 was set 0.005 expected

![Screenshot 2024-08-27 at 11 12 28](https://github.com/user-attachments/assets/e143f41f-adce-4846-8ced-729c0d778c73)


![Screenshot 2024-08-27 at 11 12 56](https://github.com/user-attachments/assets/7c16a6a5-0092-4402-bffd-7fce8393eceb)

- https://kodadot.xyz/base/drops/waitw

- https://github.com/kodadot/ops-internal/issues/1714
