### ISSUE TITLE
Circuits drop isn’t loading at all

### ISSUE THREAD

**Issue by damskyftw** [kodadot/nft-gallery#10914]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/5e677775-47c6-487a-836e-d3270348dbe6">

- production - kodadot.xyz
- chrome
- MNT

https://kodadot.xyz/mnt/drops/circuits

**Comment by JustLuuuu** [comment]
For me it looks like this:

<img width="1349" alt="Screenshot 2024-08-29 at 12 12 30" src="https://github.com/user-attachments/assets/7fa27c8c-30bb-4b6b-9ec8-bd02b12023fc">

**Comment by damskyftw** [comment]
> For me it looks like this:

Same now
