### ISSUE TITLE
Format balance assertion failed Infinite number 12 ksm 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1091]
Happens on series https://deploy-preview-1052--nftkodadot.netlify.app/series-insight?rows=100&sort=-uniqueCollectors
Could be an upstream issue

![image](https://user-images.githubusercontent.com/5887929/141287354-9623493a-4c9f-401e-a31b-50c6a72dc511.png)

**Comment by yangwao** [comment]
Does this seem solved? @vikiival 
if so close this one

**Comment by vikiival** [comment]
We replaced `console.error` with `console.warn` in 16d0d82324b6d4e70036ec55f38d841ecf740967

The thing is that native polkadot-js implementation cannot parse Infinity to number :) But it's usefull for us to know about it
