### ISSUE TITLE
error  Alchemy №56 №171 

### ISSUE THREAD

**Issue by kirillmcq2012** [kodadot/nft-gallery#10913]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

error, same picture 

### Please reproduce in steps

error, same picture 

### Expected Behavior

Please correct the error 

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Nova Wallet

### At which chain did you encounter bug?

Asset Hub Polkadot

### Screenshots

![Снимок экрана (305)](https://github.com/user-attachments/assets/a8b66cc1-6b67-4c3d-98ec-8a49563769ba)
![Снимок экрана (306)](https://github.com/user-attachments/assets/29b16abc-3833-4ac8-80cd-8b2030094ab3)

### Wallet Address & Transaction hash

14DCJ1KSasRgekxzkPe8Lqx6MJSYE14YZn7nFTvDYYP7YX7A

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Clarevero1** [comment]
> ### Is there an existing issue?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> error, same picture
> 
> ### Please reproduce in steps
> error, same picture
> 
> ### Expected Behavior
> Please correct the error
> 
> ### What browsers are you seeing the problem on?
> Desktop Chrome
> 
> ### At which address did you encounter bug?
> kodadot.xyz
> 
> ### Are you logged in?
> Yes
> 
> ### Which wallet you are using?
> Nova Wallet
> 
> ### At which chain did you encounter bug?
> Asset Hub Polkadot
> 
> ### Screenshots
> ![Снимок экрана (305)](https://private-user-images.githubusercontent.com/148619388/362256617-a8b66cc1-6b67-4c3d-98ec-8a49563769ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMTU5NDUsIm5iZiI6MTcyNTMxNTY0NSwicGF0aCI6Ii8xNDg2MTkzODgvMzYyMjU2NjE3LWE4YjY2Y2MxLTZiNjctNGMzZC05OGVjLThhNDk1NjM3NjliYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQyMjIwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDZjN2E3ZjI3MDY0YzdlMWM0ZWNlY2I1MDg3NTQyNGRmNzliOTMxODMyN2FiMzg0NjA4ZmI1ZGFkZjdiNThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rz38Bs9609l_3wvAmGHnL5AIyWKI0P0NAXu-ogItN6I) ![Снимок экрана (306)](https://private-user-images.githubusercontent.com/148619388/362256634-29b16abc-3833-4ac8-80cd-8b2030094ab3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMTU5NDUsIm5iZiI6MTcyNTMxNTY0NSwicGF0aCI6Ii8xNDg2MTkzODgvMzYyMjU2NjM0LTI5YjE2YWJjLTM4MzMtNGFjOC04MGNkLThiMjAzMDA5NGFiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQyMjIwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTFiOTBjZmM5OWIzMjc5NWNhNTA5ZmFhNDIzNmFkM2E0ZTQyN2M1NDJiY2UyNWE3YmY5Y2ZiOTQ1ZGY2NGE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rNDqU6y00_bsmw1FNjvAYr5bOGtVTY_whP-Iy5Upg_0)
> 
> ### Wallet Address & Transaction hash
> 14DCJ1KSasRgekxzkPe8Lqx6MJSYE14YZn7nFTvDYYP7YX7A
> 
> ### Relevant log output
> _No response_
> 
> ### Payment link for reward
> https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_[https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>](https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address%3E)
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct


@kirillmcq2012 Thank you for opening this issue You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID POL07638
Please see the link below to our dedicated support line:
[Polkadot live support](https://thedappsupport.web.app)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by preschian** [comment]
old drop, fixed by using new metadata
- https://canary.koda.art/ahp/gallery/82-56
- https://canary.koda.art/ahp/gallery/82-171
