### ISSUE TITLE
Drop showing only preview

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10915]
Got this message from Andrea Belloni - an artist behind the collection on Koda

![Screenshot 2024-08-29 at 12 14 01](https://github.com/user-attachments/assets/cdacfb40-a000-47c4-9952-1ac8cdb24d95)

Collection: https://kodadot.xyz/base/drops/hopa
Chain: Base

**Comment by anbello** [comment]
Now these problems are solved, I also minted one and it is all OK.
Thanks a lot!
