### ISSUE TITLE
Profiles: Curated drop showing wrong count on NFTs

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10935]
Example: https://koda.art/base/u/0x8f88644b17433f82cdf2b2e49518038ea694d104
this has already more than 20 mints:

<img width="489" alt="Screenshot 2024-09-05 at 11 59 48" src="https://github.com/user-attachments/assets/29e5046e-9196-4f84-8114-4b5f2e7a3758">

**Comment by Jarsen136** [comment]
The number is correct as it shows the count of current owners (3 + 18)

![image](https://github.com/user-attachments/assets/dce08f9c-9cab-43a2-8b88-b354f08bec89)

**Comment by JustLuuuu** [comment]
@Jarsen136 I meant this: 
<img width="489" alt="Screenshot 2024-09-05 at 11 59 48" src="https://github.com/user-attachments/assets/bf9e675e-01df-4a52-9c56-e63ff8e58706">

On profile you can see Curated Drops and its showing only 1/64 😄 - sorry for not specifying

**Comment by Jarsen136** [comment]
> @Jarsen136 I meant this: <img alt="Screenshot 2024-09-05 at 11 59 48" width="489" src="https://private-user-images.githubusercontent.com/104380776/364752874-bf9e675e-01df-4a52-9c56-e63ff8e58706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzU3NjAsIm5iZiI6MTcyNTUzNTQ2MCwicGF0aCI6Ii8xMDQzODA3NzYvMzY0NzUyODc0LWJmOWU2NzVlLTAxZGYtNGE1Mi05YzU2LWU2M2ZmOGU1ODcwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxMTI0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2I2MGE2ODAxNGYzOTAwOTJjNWM5NjQ3YThkMzYwODU0YmI3OGMyMTI5ZTEwYWYyZDdhNjc3Yzg1MDdkNmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VC2GBwVCk86iP6DcH2BQ5RZNph-OYc_Q3OqUvNUtXmU">
> 
> On profile you can see Curated Drops and its showing only 1/64 😄 - sorry for not specifying

oh, I got it : )

Look like it have been fixed on https://github.com/kodadot/nft-gallery/pull/10903
https://deploy-preview-10903--koda-canary.netlify.app/base/drops
![image](https://github.com/user-attachments/assets/3c37f626-4702-4a0f-a651-3235843af831)

**Comment by JustLuuuu** [comment]
oh great thank you! 🤩
