### ISSUE TITLE
Remove Art view from Advanced

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10931]
At the moment, it doesn't make sense to hide this under extra settings. The sidebar doesn't have that many options. Please can we remove it from advanced setting to save that one click for users? Can we do that @exezbcz? 

What: Open any collection, open sidebar with filters, advanced setting - Art View

https://github.com/user-attachments/assets/a88741c1-1e62-4800-a03b-0c4d92270728

For future: consider adding Art View also in the menu above the collection, where we can play with how many NFTs we see. Art view is nice small feature that doesn't need to be hidden.

**Comment by exezbcz** [comment]
sure, just remove the dropdown please

**Comment by JustLuuuu** [comment]
@hassnian can you do it? :)
