### ISSUE TITLE
Navbar collection search not working

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#10930]
### What happened?

![CleanShot 2024-09-04 at 11 11 16@2x](https://github.com/user-attachments/assets/19c0eb0a-6a51-47d8-987b-355a0507e86d)

![CleanShot 2024-09-03 at 10 11 45@2x](https://github.com/user-attachments/assets/3893f8af-0bd5-45d3-a011-faf6b5dc83fa)

**Comment by hassnian** [comment]
fix: https://github.com/kodadot/runners/pull/8

**Comment by vikiival** [comment]
should be already fixed or ?

**Comment by hassnian** [comment]
> should be already fixed or ?

https://github.com/kodadot/runners/pull/10

**Comment by vikiival** [comment]
I have updated the db manually few days ago :)

**Comment by hassnian** [comment]
hmm still not working

![CleanShot 2024-09-09 at 16 57 33@2x](https://github.com/user-attachments/assets/c74b4e39-4502-4d91-b0d4-6a537c8982fb)

**Comment by vikiival** [comment]
![Screenshot 2024-09-10 at 17 48 53](https://github.com/user-attachments/assets/2769ba75-97a5-4e89-bb2a-3ba2e000ea98)

item is in the db, 
probably the search could be broken?

**Comment by vikiival** [comment]
I forgot to deploy that funny thing, 
should operate now
![Screenshot 2024-09-10 at 17 59 24](https://github.com/user-attachments/assets/ac741e17-d060-4f3d-b721-da823e0934a2)

**Comment by hassnian** [comment]
> Should work now

yep

![CleanShot 2024-09-11 at 09 52 58@2x](https://github.com/user-attachments/assets/55f678af-51c2-43f7-83cc-7a122bf93eed)
