### ISSUE TITLE
Base Drops: Count not working on older collections

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10948]
**Base: Open Drops:** https://kodadot.xyz/base/drops - scoll to check older drops. Some collections have much more mints. 

**All these numbers are not correct:**
<img width="1696" alt="Screenshot 2024-09-09 at 13 24 18" src="https://github.com/user-attachments/assets/fd670c90-24d1-4260-ac5f-b7427ec705b5">
<img width="1668" alt="Screenshot 2024-09-09 at 13 25 42" src="https://github.com/user-attachments/assets/81aa4f75-ed12-4757-85ad-0d82a69fe3f6">

**Comment by JustLuuuu** [comment]
I see its working on Canary, so it means with next release it will be on production? @preschian do you know 😸?

**Comment by preschian** [comment]
oh, sorry, just saw this issue 
yes, already be fixed with this: https://github.com/kodadot/nft-gallery/pull/10903
and should be included in the next release: https://github.com/kodadot/nft-gallery/pull/10969
