### ISSUE TITLE
Profile: Weird link formating from warpcast

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10949]
Artist: https://warpcast.com/morbeck-art/

Profile on Koda
---
Look properly at that link. Somehow its not taking the link as a whole. Also the link is not working. 
<img width="714" alt="Screenshot 2024-09-09 at 15 14 27" src="https://github.com/user-attachments/assets/e761792e-2f63-462e-b191-04e6060ff177">

Profile on Warpcast
---

<img width="616" alt="Screenshot 2024-09-09 at 15 14 12" src="https://github.com/user-attachments/assets/0086d488-5e19-4e3f-9217-33f41d8e39f3">

**Comment by woniuppp** [comment]
因为数据源就是
<pre>
Brazilian Artist and architect | \nVisual Arts, Photography and GenArt | https:/[/linktr](https://warpcast.com/~/channel/linktr).ee[/mateusmorbeck](https://warpcast.com/~/channel/mateusmorbeck)
</pre>

**Comment by woniuppp** [comment]
`{
    "address": "5EZdSLPuEwSafwxABL7RYU1AXqjma5qRo3qE2kk61wKLjckx",
    "name": "Morbeck 💎",
    "description": "Brazilian Artist and architect | \nVisual Arts, Photography and GenArt | https:/[/linktr](https://warpcast.com/~/channel/linktr).ee[/mateusmorbeck](https://warpcast.com/~/channel/mateusmorbeck)",
    "created_at": "2024-09-09 13:09:08",
    "image": "https://imagedelivery.net/BXluQx4ige9GuW0Ia56BHw/bd14ba58-a115-4f1e-2acc-34c445edb500/original",
    "banner": null,
    "socials": [
        {
            "handle": "morbeck-art",
            "platform": "Farcaster",
            "link": "https://warpcast.com/morbeck-art"
        },
        {
            "handle": "morceck_art",
            "platform": "Twitter",
            "link": "https://twitter.com/morceck_art"
        }
    ]
}`
