### ISSUE TITLE
what takes so long to create offer

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10952]
<img width="472" alt="image" src="https://github.com/user-attachments/assets/17c51fe6-c98a-4d94-ac52-c0d45e003db1">

waiting at least 40 seconds for offer to be created is quite a lot

**Comment by exezbcz** [comment]
cc @hassnian @Jarsen136

**Comment by hassnian** [comment]
@exezbcz  atm it's waiting for the transaction to be `finalized`, we can show the success state once it the transaction is in `block`

but the offer wont be shown in the page immediately after the transaction is 'completed'

we would still need something like [this](https://github.com/kodadot/nft-gallery/pull/10903#issuecomment-2324043010)

![CleanShot 2024-09-10 at 11 24 56@2x](https://github.com/user-attachments/assets/32bab486-e82e-41df-bf57-69b56045f2b7)

**Comment by exezbcz** [comment]
> we would still need something like [this](https://github.com/kodadot/nft-gallery/pull/10903#issuecomment-2324043010)

yeah that looks good, let me iterate the design and do that

**Comment by exezbcz** [comment]
ups, forgot to post


![image](https://github.com/user-attachments/assets/166d53a1-6970-4500-8b84-fc8b7bbb2e4a)




its next to the offer infographics

- copy changed a bit and added small contextual message 

![image](https://github.com/user-attachments/assets/c70993a3-ef0f-4b3b-884f-afdab3a1c3e9)
