### ISSUE TITLE
Offer expiration dropdown moving on scroll 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10951]
https://github.com/user-attachments/assets/83cfdc95-fd7e-4598-802c-e1d3cc9513df

followup for: 
- https://github.com/kodadot/nft-gallery/pull/10909

**Comment by Jarsen136** [comment]
> will users need to claim manually back their funds once the offer expires? Can we do it automatically that the funds will not stay blocked?

The users have to cancel the expired offer on their profiles page.

<img width="865" alt="image" src="https://github.com/user-attachments/assets/e3206a3d-773f-4c75-91fb-d3cd5f39a89f">

**Comment by exezbcz** [comment]
> The users have to cancel the expired offer on their profiles page.

it cant be automatic right

**Comment by Jarsen136** [comment]
> > The users have to cancel the expired offer on their profiles page.
> 
> it cant be automatic right

AFAIK, yes.

**Comment by exezbcz** [comment]
@Jarsen136 bruh

**Comment by JustLuuuu** [comment]
I would focus on making it automatic, I remember from bsx that no one was claiming their offers back 😸

**Comment by Jarsen136** [comment]
@vikiival Could you confirm about the automatic returning deposit?
