### ISSUE TITLE
No success modal after offer is created 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10953]
<img width="502" alt="image" src="https://github.com/user-attachments/assets/6e68d901-077a-43f0-b668-d7c7d08b2c9d">

this green toast is completely missing right now

followup for: 
- https://github.com/kodadot/nft-gallery/pull/10909

**Comment by exezbcz** [comment]
cc @hassnian or @Jarsen136

**Comment by Jarsen136** [comment]
> this green toast is completely missing right not

It works well for me and shows the green toast finally. 
Could you expand more about how to reproduce the issue that occurs?

![x](https://github.com/user-attachments/assets/a155cec3-4142-4ac5-9460-da406606f78d)

**Comment by exezbcz** [comment]
weird, it did not display for me

**Comment by exezbcz** [comment]
oki tried again, nothing for me, it did not popup for me

**Comment by Jarsen136** [comment]
should be fixed
