### ISSUE TITLE
Remove Quadz

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10962]
The artist is asking us to hide the testing collection that was created thx to his code. He is not happy that its visible. 
**Collection**: https://kodadot.xyz/base/drops/quadz 

Pls Remove or Hide or whatever.  

<img width="598" alt="Screenshot 2024-09-10 at 13 31 44" src="https://github.com/user-attachments/assets/aa64fa41-a838-461f-b0f4-1dd826bbf272">

**Comment by vikiival** [comment]
I cannot find proof right now, but I am 100000% confident that we have asked you if we can fork the art and use it for the testing.

As far as I know we got AYE from the artist. 
Art will be removed from the indexer
- https://github.com/kodadot/basick/pull/58

**Comment by vikiival** [comment]
Should not be visible anymore

![Screenshot 2024-09-10 at 16 34 05](https://github.com/user-attachments/assets/ca208194-1425-4cd1-9920-b57e87068cab)

**Comment by preschian** [comment]
it's still there on the past drops section. should be removed now

<img width="1128" alt="Screenshot 2024-09-11 at 12 15 12" src="https://github.com/user-attachments/assets/cdf1b20f-f401-49e3-bb7f-f3956922cfed">

I just realized, vortices also already removed from the database: https://github.com/kodadot/private-workers/issues/215
