### ISSUE TITLE
related to installing chrome extension

### ISSUE THREAD

**Issue by 7Love7code7** [kodadot/nft-gallery#1097]
### What happened?

I am new to KodaDot.
Login button indicated me to install chrome extension so I installed it, but it was saying same message "install".
After refresh site, it  showed me option to login.
I am not sure if this is a bug but just suggestion to make site more user-experienced.
Regards

### Please reproduce in steps

all new users will experience same.

### Expected Behavior

I've expected ...

### What browsers are you seeing the problem on?

Chrome

### Screenshots

![image](https://user-images.githubusercontent.com/66752541/141318345-ee252404-efbe-44a3-99ae-39d147f35c1e.png)

![image](https://user-images.githubusercontent.com/66752541/141318678-f174cb48-76d6-4898-82a6-9c6f0a86d766.png)
![image](https://user-images.githubusercontent.com/66752541/141318935-4abb14d0-9d4d-48c5-95b3-439595fb6401.png)
![image](https://user-images.githubusercontent.com/66752541/141319086-fb3812b0-26d5-481b-900c-be4a1118f344.png)
![image](https://user-images.githubusercontent.com/66752541/141319246-0bd33259-fb48-4d8d-94d7-11167d49d66a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Hey can you record this and put recording here what you mean?

**Comment by 7Love7code7** [comment]
I uploaded screenshots,

**Comment by XyloDrone** [comment]
Hey @7Love7code7 Do you have a polkadot.js account? You need to have one in order to mint, regardless if your extension is in the browser. Once you've passed the installation phase, there should be a "+" button at the top right corner to create an account. Let me know if you are still experiencing issues.

**Comment by yangwao** [comment]
We've got how to create wallet in docs https://docs.kodadot.xyz/tutorials/how-to-create-wallet.html#video-tutorial
