### ISSUE TITLE
Hide mint count bar unlimited drops  

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#10979]
### What happened?

 @exezbcz wdyt ?

<img src=https://github.com/user-attachments/assets/5566ad47-eae0-4c36-8d1d-abe5a23788a0 width=500 />

**Comment by uDaiko** [comment]
Is this still being discussed? Otherwise I would like to take it, should be an easy fix to just not render the bar when there is unlimited drops

**Comment by exezbcz** [comment]
> @exezbcz wdyt ?

yes

**Comment by exezbcz** [comment]
@uDaiko do you want to be assigned?

**Comment by uDaiko** [comment]
:wave:

**Comment by exezbcz** [comment]
@uDaiko assigned, you got 48 hours to raise pr

thanks!
