### ISSUE TITLE
Remove notif on landing 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#10995]
<img width="518" alt="image" src="https://github.com/user-attachments/assets/7ff15203-6173-4312-b245-330acc0d6772">

**Comment by Jarsen136** [comment]
@exezbcz  how about this one? Should we keep it?  

"Connect on Farcaster"

<img width="835" alt="image" src="https://github.com/user-attachments/assets/91fbe1b5-4819-43d6-ad7f-6cb11f054743">

#10924

**Comment by exezbcz** [comment]
yeah you can leave the farcaster one, thank you
