### ISSUE TITLE
Motherboard not minted out? 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10999]
Motherboard collection should be minted out. Its not possible to mint it anymore but its showing between ACTIVE drops: Collection: https://kodadot.xyz/ahp/drops/motherboard

Issues
---
1) Showing 1023/1024
2) Still between active Drops - should be in PAST drops as mint is closed

<img width="857" alt="Screenshot 2024-09-18 at 13 11 00" src="https://github.com/user-attachments/assets/82c7ecea-015a-4aa0-8acc-a84ec18e81bf">

<img width="1554" alt="Screenshot 2024-09-18 at 13 11 18" src="https://github.com/user-attachments/assets/f802bc16-6baf-425c-80c0-bb3962b094fe">

**Comment by Jarsen136** [comment]
cc @preschian

**Comment by preschian** [comment]
Yes, it was not minted out. And someone just did some hacking to mint it: https://koda.art/ahp/gallery/50-0. So, right now it should be minted out.

afaik, if someone burns some tokens on AssethHub, the burned tokens are not counted. This means the supply count will be reduced
