### ISSUE TITLE
Missing border on dialog for qr-code scanner on profile and collection

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1100]
https://kodadot.xyz/rmrk/collection/10c369c57194165634-92YIT
![image](https://user-images.githubusercontent.com/5887929/141319256-369862b2-6a64-42d8-b5ab-20f58d76479c.png)

https://kodadot.xyz/rmrk/u/CxJLK5bYbVQgH7r1axUbxymmaQhUoMPkTfuvQsb2djehgVU
![image](https://user-images.githubusercontent.com/5887929/141319322-ff72b806-f0af-46bd-95cb-c5e18eac7d0b.png)

**Comment by XyloDrone** [comment]
IMO a border isn't needed here, but I differ.

**Comment by roiLeo** [comment]
There is a border because of the global css defined in GalleryItem component. By default, there should be none.

#1348 related
