### ISSUE TITLE
I dont see my BASE NFTs in my profile

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#11006]
My profile: https://kodadot.xyz/base/u/0xe4ebb5bd96c08F0adaBFe20B9b60E07075Ca262e
Im logged in under my ETH Metamask wallet I always use and when I open my profile I see 0 NFTs collected. Im sure I collected a bunch of our Base drop NFTs.

<img width="1681" alt="Screenshot 2024-09-19 at 11 19 04" src="https://github.com/user-attachments/assets/c7da988d-2771-42e7-b10c-3e4cd1f544eb">

**Comment by roiLeo** [comment]
No data for this address
<img width="891" alt="Capture d’écran 2024-09-19 à 11 53 30 AM" src="https://github.com/user-attachments/assets/30ec1437-8211-4c08-8388-51e45a1386f6">

Maybe indexer issue (https://github.com/kodadot/basick)

**Comment by vikiival** [comment]
@roiLeo all addresses in indexer are treated in lowercase

```graphql
{
  uppercase: nftEntities(where: { currentOwner_eq: "0xe4ebb5bd96c08F0adaBFe20B9b60E07075Ca262e" }) {
    name
    sn
  }
  lowercase: nftEntities(where: { currentOwner_eq: "0xe4ebb5bd96c08f0adabfe20b9b60e07075ca262e" }) {
    name
    sn
  }
}
```

![Screenshot 2024-09-23 at 11 14 04](https://github.com/user-attachments/assets/1dd5c12e-5458-47db-83f9-fac8d8f21bf7)

It comes from here 
- https://github.com/kodadot/basick/blob/fdd44276e099fb8db5770d180221c8272c8f6093/src/mappings/utils/extract.ts#L16
