### ISSUE TITLE
Code-Checker error

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#11010]
I got this weird error while testing a code from the artist. I tried the zip file before and it was working, so Im not sure why it is not working now. Where can be the issue? is it on my side?

The code I tried, can be found here: https://github.com/kodadot/artists/issues/103#issuecomment-2360656656

<img width="726" alt="Screenshot 2024-09-19 at 12 50 51" src="https://github.com/user-attachments/assets/a9cc3679-caff-43a6-982b-03594458590a">

Video
---
https://github.com/user-attachments/assets/d128b9c9-9146-4d60-a801-4fc2addedf13

**Comment by Jarsen136** [comment]
wfm on both https://canary.kodadot.xyz/code-checker and https://koda.art/code-checker

<img width="1455" alt="image" src="https://github.com/user-attachments/assets/b1c70e1f-9add-44a3-9993-c0e05f9dbe31">
