### ISSUE TITLE
Offers: Manage offers - change link

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#11018]
After I created an offer, in the corner, it showed me a popup as **successful** with the button: **Manage Offers**. I clicked on it and it took my to my profile. For a few seconds I was confused because I didn't see where the offers are right away. 

The link took me to my Profile - Owned. Can we change that clicking on manage offers will take me directly to **Profile - Offers** instead? 

<img width="1646" alt="Screenshot 2024-09-20 at 11 22 48" src="https://github.com/user-attachments/assets/d8f71795-be6c-43d6-9eb2-bc3be01e0029">

**Comment by Jarsen136** [comment]
I just tested it and it works. It should have been fixed on canary env.
