### ISSUE TITLE
Horizontal Alignment on Artist profile 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1102]
Same as https://github.com/kodadot/nft-gallery/issues/1081 but for an artist profile 

@prachi00 maybe you want to take a look? 👀

**Comment by prachi00** [comment]
@yangwao Sure, will do

**Comment by prachi00** [comment]
@yangwao Didn't receive the payout for this

**Comment by yangwao** [comment]
Thanks for the notice, sent! 
https://github.com/kodadot/nft-gallery/pull/1166#issuecomment-972891373
