### ISSUE TITLE
Profile: creation error

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#11029]
An artist: Richard Boeser cannot create his profile due to an error 

**Url**: https://kodadot.xyz/ahp/u/13dRFKyfiviFYpwnBaC56n85Um2oEHasyc7DMBbVUUB2dPGR
**Browser**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
**Wallet**: talisman
**Chain**: ahp
**Error**: Error: [PROFILE::CREATE] ERROR: undefined

It also fails when trying a different image. But the image is small enough. It shouldn't be the issue.

**Console**
![image_2024-09-23_10-11-04](https://github.com/user-attachments/assets/d58d5d3e-f10d-4129-be89-ca297ee34efb)

**Comment by hassnian** [comment]
![CleanShot 2024-09-23 at 15 03 16@2x](https://github.com/user-attachments/assets/d7af5a8d-b667-4c96-b18d-2b86612dc4de)
