### ISSUE TITLE
Ugly preview on Warpcast chat

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#11048]
Someone wrote koda.art in the chat on warpcast and this is how preview looks. ![image](https://github.com/user-attachments/assets/56d87edb-219a-4a38-9a4e-fc5734851e14)

Can we have something like: Generative Art Martketp´ace instead of the nuxt thingy?

**Comment by roiLeo** [comment]
should be good now

**Comment by JustLuuuu** [comment]
@roiLeo yes thank you!
