### ISSUE TITLE
Profile is not syncing properly with wallet

### ISSUE THREAD

**Issue by lukastrips** [kodadot/nft-gallery#11049]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

I have synchronized my profile with the wallet and when I log in I don't see the pieces I have collected. I have been checking and the problem lies in the URL of each profile. In one case some values ​​are in uppercase and in the other in lowercase, I understand that this is why it is not synchronized correctly:

https://koda.art/base/u/0x9D7EC1B4AeBebBE686b2Ec3b22Ef6240A9Aa2bc2 -> Uppercase

https://koda.art/base/u/0x9d7ec1b4aebebbe686b2ec3b22ef6240a9aa2bc2 -> Lowercase

### Please reproduce in steps

https://koda.art/base/u/0x9D7EC1B4AeBebBE686b2Ec3b22Ef6240A9Aa2bc2 -> Uppercase

https://koda.art/base/u/0x9d7ec1b4aebebbe686b2ec3b22ef6240a9aa2bc2 -> Lowercase

### Expected Behavior

Synchronize my profile with my wallet correctly so I can see the collected pieces in my profile

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Other

### At which chain did you encounter bug?

Asset Hub Polkadot

### Screenshots

![image](https://github.com/user-attachments/assets/84eaab2d-a473-411a-a1e2-c8e828af71b6)

### Wallet Address & Transaction hash

https://koda.art/base/u/0x9D7EC1B4AeBebBE686b2Ec3b22Ef6240A9Aa2bc2

https://koda.art/base/u/0x9d7ec1b4aebebbe686b2ec3b22ef6240a9aa2bc2

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by exezbcz** [comment]
good find!
