### ISSUE TITLE
Autoteleport does incorrect calculations

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#11059]
### Context

For testing I was minting some NFTs and I found out that app is doing incorrect calculations.

Test case. 

1. I had some DOT (less than 0.27 DOT) and the minting price was 3 DOT
2. [App decided to teleport 2.73 DOT](https://assethub-polkadot.subscan.io/xcm_message/polkadot-754cc374ad7364bc1aed254d1f2a8231b638ccb0)
3. So in result I had 3 DOT (bear in mind that I need ED and tx fee)
4. Minting failed

### Fix 

Ensure that enough DOT is teleported :) (I need at least  3.05 DOT in total to have enough)

### SCR 

![Screenshot 2024-09-30 at 12 04 51](https://github.com/user-attachments/assets/77e0fd95-22bf-40e0-a2aa-7388c8f3b6f3)

**Comment by exezbcz** [comment]
here we go again
