### ISSUE TITLE
Royalty Rate (%) - not intiutive in Create

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#11071]
Create a collection—scroll to royalties. I'm a bit confused because the button is toggled on, but when I toggle it off, the address for royalties appears. Does that mean that the grey button is when it's on and pink when it is off? Shouldn't it be the opposite?

https://github.com/user-attachments/assets/907cab32-6688-4f89-a08c-bbb55cf9d3f5

**Comment by Jarsen136** [comment]
> Does that mean that the grey button is when it's on and pink when it is off? Shouldn't it be the opposite?

No.  Here are two cases of how it works now.
switch on (pink) -> pay royalties to the creator account
switch off (grey)-> pay royalties to a custom address which is in the input

It's quite confusing when I see it for the first time. The interaction could be optimized a bit.
