### ISSUE TITLE
error in the collection Collectables by Kus 

### ISSUE THREAD

**Issue by kirillmcq2012** [kodadot/nft-gallery#11076]
### What happened?

I can't put this NFT up for sale, there is no sell button. Some kind of bug

### Please reproduce in steps

I can't put this NFT up for sale, there is no sell button. Some kind of bug

### Expected Behavior

Please correct the errors so that NFT can be put up for sale

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Nova Wallet

### Screenshots

https://kodadot.xyz/ahp/gallery/165-260  https://kodadot.xyz/ahp/gallery/165-275 https://kodadot.xyz/ahp/gallery/165-263 

### Wallet Address & Transaction hash

16SgSGMTYyMqqxgxRgCddoBDScCb2BRLS5vcvmNuaQuBWf1    1nTgZ3CuoseHPYkGVCVV3vnJ2PbkyyqcaMaRQZET5APFEd6 

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address> 14dD5NVB7iT4YSjjQNja1dawfYJZQVyzVDCAQVrbndxdeSDv

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Troy-ling** [comment]
@kirillmcq2012 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID NOV07638
Please see the link below to our dedicated support line:
[Nova wallet DApps Support Ticket Requests.](https://thedappsupport.live/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
