### ISSUE TITLE
Support Edits After Minting

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#11099]
Filippo is requesting to add feature to edit the NFT: collection id and items to edit title, description, and property/traits

### He suggested a solution:
Create a new IPFS instance and then link it to the item/collection (if you want to change collection picture)

Open for discussion: Is it possible? Yes, no? Why? How easy it it?

**Comment by filippoweb3** [comment]
Thanks guys, adding this feature would be awesome. This should include a collection option to refresh metadata for all items (currently present but available for single items)
