### ISSUE TITLE
When I click on in gallery on text I should land on item detail

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1109]
Let's fix that whenever you [click from the gallery feed](https://kodadot.xyz/rmrk/gallery) you should land on NFT detail, not in the collection.

**Comment by PonyJackal** [comment]
I will take this issue

**Comment by roiLeo** [comment]
is it still relevant? what are the steps to reproduce it?

**Comment by yangwao** [comment]
go to the https://beta.kodadot.xyz/rmrk/gallery/ and click on NFT and you will land on the collection, instead of item detail


https://user-images.githubusercontent.com/5887929/147667092-53a96482-174e-4694-8214-b16d1facfa9e.mov
