### ISSUE TITLE
Polkawow collection - NFTs not visible

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#11106]
This was poap collection: https://kodadot.xyz/ahp/collection/192
poap page used to be here: https://kodadot.xyz/ahp/collection/192

Related issue: https://github.com/kodadot/ops-internal/issues/1829

**Comment by roiLeo** [comment]
looks like someone already fixed it

![Screenshot 2024-10-15 at 13-40-47 PolkaWoW One Stop Shop for Polkadot NFTs](https://github.com/user-attachments/assets/eb854c4a-69e3-4cae-a6a6-e2b0eb9918ba)
