### ISSUE TITLE
Action Buttons: Implement Withdraw Functionality

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#11136]
Develop a Withdraw action for swaps, allowing users to withdraw a swap after it has expired.

**Comment by exezbcz** [comment]
use the same logic as for offers please


![image](https://github.com/user-attachments/assets/f9d5dbe0-a7f5-4a24-89ab-86c963bcd626)



or was it changed somehow in the meantime? There was the automatic withdraw iirc? 

cc @hassnian

**Comment by hassnian** [comment]
> use the same logic as for offers please

works the same as offers, this is already implemented forgot to close the issue 


> ![image](https://private-user-images.githubusercontent.com/90852205/392533711-f9d5dbe0-a7f5-4a24-89ab-86c963bcd626.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNjU3MDUsIm5iZiI6MTczMzM2NTQwNSwicGF0aCI6Ii85MDg1MjIwNS8zOTI1MzM3MTEtZjlkNWRiZTAtYTdmNS00YTI0LTg5YWItODZjOTYzYmNkNjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDAyMjMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMjJiOWQ4N2Q3YzBiYWI1MmNiMWE0MjUyYzA1M2Y2YzU0ZjNhYTQ0MTY4N2M3OTA5ZWNhMzBmMWRhOWUzNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PxzJODfWWlGeztg6rysjpWXy5NgrgrGjMMoUz7S8V9U)
> 
> or was it changed somehow in the meantime? There was the automatic withdraw iirc?
> 


we should change the wording , since `Withdraw Amount` only `Cancels the offer`

#11204 pr has been created
