### ISSUE TITLE
Action Buttons: Implement Cancel Functionality

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#11135]
Create a Cancel action for swaps, allowing users to cancel an existing swap before it is accepted or expired.

**Comment by exezbcz** [comment]
this one is finished? 

- https://github.com/kodadot/nft-gallery/pull/11182

**Comment by hassnian** [comment]
> this one is finished?
> 
> * [feat: Display Swap in Item View & Profile View  #11182](https://github.com/kodadot/nft-gallery/pull/11182)

yep

![CleanShot 2024-12-05 at 08 05 02@2x](https://github.com/user-attachments/assets/3353221c-84e2-454f-b6fe-0b27f3f32afa)
