### ISSUE TITLE
Nuxt has some issues and deploy previews fails to fetch data 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1114]
Let's have look and be interested in what it causes, web page doesn't load at all

https://deploy-preview-1110--koda-nuxt.netlify.app/en/rmrk/collection/2644199cf3652aaa78-KK01

![image](https://user-images.githubusercontent.com/5887929/141447643-4048aa3c-9984-4370-a626-ecce68e78aac.png)
![image](https://user-images.githubusercontent.com/5887929/141447875-05f95b54-9061-439d-af9d-bde42b48cc11.png)

**Comment by vikiival** [comment]
`Variable \"$first\" of required type \"Int!\" was not provided.`

Looks like the collection detail is missing the newly added pagination. So the best fix would be to migrate it

**Comment by yangwao** [comment]
@dezine2dev is this fixed in recent `main-nuxt` ?

**Comment by dezine2dev** [comment]
Yes it is fixed. @yangwao
