### ISSUE TITLE
Collection Edit: Support Name Update

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#11143]
Add functionality to the collection edit modal allowing users to update the collection name. Ensure that the updated name is reflected on-chain.

**Comment by hassnian** [comment]
I'm not working on any of those issues, so no overlap from my side. I will assign the issue to myself if I do so.

I only closed the ones I was sure are completed, others are just linked

![CleanShot 2024-11-29 at 09 11 58@2x](https://github.com/user-attachments/assets/eb24d880-5e6d-4b4d-8f03-5d96e72c82bc)
