### ISSUE TITLE
Discretew: some artwork is shown as images not as animation

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#11158]
This collection should be animated: https://koda.art/ahp/drops/discretew

There are few pieces that are not. 
- https://koda.art/ahp/gallery/250-4229170433
- https://koda.art/ahp/gallery/250-4229170802
- https://koda.art/ahp/gallery/250-4229179180

Pls fix! And check all NFTs in the collection if they are correct!

**Comment by Jarsen136** [comment]
<img width="845" alt="image" src="https://github.com/user-attachments/assets/9823797b-9cc2-40cc-b16c-0e6c042d348c">

All should be fixed after clicking the `refresh metadata` button
