### ISSUE TITLE
Binarylands: Wrong preview on the NFT 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#11173]
https://koda.art/ahp/gallery/263-4230985174
This NFT has wrong preview:

<img width="498" alt="Screenshot 2024-11-07 at 14 20 01" src="https://github.com/user-attachments/assets/5db05b92-fbfa-421f-98cf-19cb82170e83">
<img width="997" alt="Screenshot 2024-11-07 at 14 20 45" src="https://github.com/user-attachments/assets/97ebdc70-f00d-4e6d-8d36-88ff2c7d1bd3">

**Comment by preschian** [comment]
<img width="656" alt="Screenshot 2024-11-13 at 13 20 49" src="https://github.com/user-attachments/assets/dc75dfbb-96c4-4c94-bb1d-2f6327cd0bb3">

cache updated, lmk if you found similar issue
