### ISSUE TITLE
Collected by not updated

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#11172]
Drop: https://koda.art/ahp/drops/binarylands

<img width="1001" alt="Screenshot 2024-11-07 at 14 15 49" src="https://github.com/user-attachments/assets/30f57e9e-5dfc-4cb5-82a8-881f50560c46">

**Comment by JustLuuuu** [comment]
Correction: showing only profiles with created profiles:
<img width="210" alt="Screenshot 2024-11-07 at 14 17 45" src="https://github.com/user-attachments/assets/6ddac17a-33db-47ac-bf99-776b883677ab">

**Comment by roiLeo** [comment]
Nothing wrong with this component it work as seen on other drop
![Screenshot 2024-11-12 at 12-10-05 ANOMALY One Stop Shop for Polkadot NFTs](https://github.com/user-attachments/assets/ce05f183-09c8-46a1-9472-70da8096c93e)

safe to close
