### ISSUE TITLE
Massmint not checking balance 

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#11189]
a couple of weeks ago patricia was having issues mass-minting a large amount of NFTs 

apparently she had enough funds on-chain but she could not mint (transaction would fail), after checking her address she did not have funds on `AHP` after transferring funds to her wallet everything worked.   

that's how I found that the **massmint does not check the user balance at all** 

it should 

1. take minting cost (**itemDeposit** and a **base transaction fee**) into consideration
2. ideally support auto-teleport  

<img src=https://github.com/user-attachments/assets/2c97b051-5043-4421-bb2d-9b1425ab469b width=500 />

_Originally posted by @hassnian in https://github.com/kodadot/nft-gallery/issues/11188#issuecomment-2502633458_

**Comment by hassnian** [comment]
Support auto-teleport in `/massmint `

**Comment by vikiival** [comment]
1a. It should also take metadata deposit into consideration
