### ISSUE TITLE
Hide Created and Sold when collector has 0 created NFTs

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1120]
Hide Created and Sold when query resolves that Artist profile did not issued any NFT

![image](https://user-images.githubusercontent.com/5887929/141482144-182385ad-f4c3-4082-a8e6-4b3137340f36.png)

Test case https://kodadot.xyz/rmrk/u/DgCNKpvqeg29wsMsUDLcYP7Kqcc4pW963F7mj2uRe8Kk6Jm?tab=nft

**Comment by prachi00** [comment]
@yangwao I'll pick this up

**Comment by yangwao** [comment]
This was already solved in #1120 afaik
