### ISSUE TITLE
 Swap Landing link

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#11216]
how do you land on the Swap Page  `/prefix/swap`

maybe we can add it in the footer

![CleanShot 2024-12-05 at 09 36 29@2x](https://github.com/user-attachments/assets/40094e99-2b41-4f4c-8ad1-6d80c2d11935)

**Comment by exezbcz** [comment]
![image](https://github.com/user-attachments/assets/a51ab39e-fe61-4fce-9bb7-66a51d794506)


lets add it to the profile sidebar
