### ISSUE TITLE
Swap Page Review Step follow up

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#11215]
- `surcharge` is missing 
- if the amount of tokens being swapped is large the bottom part gets hidden, maybe we can make it sticky

![CleanShot 2024-12-05 at 08 40 51@2x](https://github.com/user-attachments/assets/30c8f97b-b2d1-4860-8f9a-b9c216d52b99)

**Comment by exezbcz** [comment]
hmm, yup 


lets wrap in container and remove drop shadow from the buttons


like this: 
![image](https://github.com/user-attachments/assets/1017c289-73d5-470f-88ce-2481541a498e)

**Comment by exezbcz** [comment]
will create amount card that will have the same size as the nft card and it will represent the surcharge amount

**Comment by exezbcz** [comment]
okay, second part are funds 


![image](https://github.com/user-attachments/assets/9b8a002f-3427-4eb6-a8b9-33e1f57bf47d)

updated in figma: 
https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=9007-36740&node-type=canvas&t=VEZq2N3rCwP7Lq4x-11
