### ISSUE TITLE
Showing median line from BUY events and H-spread

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1121]
- Show median line from BUY events on the chart
- Add H-spread #1119 
- Trailing avg 

### ref
Once #1110 is merged, you can continue into `main-nuxt` 

![image](https://user-images.githubusercontent.com/5887929/141482637-2ae4c254-e513-4504-8eb0-acfe94e58f94.png)

**Comment by yangwao** [comment]
@rhaicode might be interested into this?

**Comment by rhaicode** [comment]
Sure, I'll learn things first about H-spread and see how it can be implemented to chartjs

**Comment by rhaicode** [comment]
Hello @yangwao I'd like to ask which lines below correctly represents a median line?

![median](https://user-images.githubusercontent.com/22829115/143196724-a5ec2c1d-c326-44b1-b014-6ada6abfe515.PNG)
This median line is derived by sorting all values in the array by ascending order and then selecting the middle value.

![median-2](https://user-images.githubusercontent.com/22829115/143197391-7c3895ad-a162-4703-8345-37c64221b4f8.PNG)
This median line is derived by getting the max and min values on the array and then dividing by 2.

**Comment by yangwao** [comment]
> Hello @yangwao I'd like to ask which lines below correctly represents a median line?

First one is probably arithmetic mean which could be useful too! 
Second might be median yup!
https://en.wikipedia.org/wiki/Median 

I'm thinking if would be possible showing sliding average? (> trailing avg prob works)

https://en.wikipedia.org/wiki/Moving_average probably this is the one

**Comment by rhaicode** [comment]
Hello @yangwao. Here's the current progress.

H-spread (in-progress):
The yellow dots represent the min and max points of the h-spread
The aqua dots represent the q1 and q3
The orange is the median (q2)

The H-Spread values are derived from all values of the Sold NFT Price (having "Buy events"), sorted in ascending order then followed the logic for determining the values for this KhanAcademy resource: https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics/cc-6th-box-whisker-plots/v/box-and-whisker-plot-exercise-example

I feel that the H-Spread was incorrect and would ask for guidance on this one. Should I gather all events from the Sold NFT Price? Or should I just provide constant values in each point, for example [min=actual_point_value - 10, actual_point_value , max=actual_point_value + 10]?

The trailing average is on the blue line, but let me know what color to use then. This uses a 3-day moving average.

Watch the screen recording: https://screencast-o-matic.com/watch/crXTf3VIp8K

![Capture](https://user-images.githubusercontent.com/22829115/143378867-18c3bcad-d86a-4203-9d11-17562c53db19.PNG)

**Comment by yangwao** [comment]
Hey, let's make PR and it will be auto deployed so we can play around. 

Live demo is way better than screen recording, I can check then!

**Comment by rhaicode** [comment]
Oh sure thing, I'm sorry I forgot to mention a PR 😅. Here's the related PR for this issue:
https://github.com/kodadot/nft-gallery/pull/1291
