### ISSUE TITLE
NFT and Collection minting error

### ISSUE THREAD

**Issue by Johnny1110** [kodadot/nft-gallery#11218]
### What happened?

failed when mint NFT.

### Please reproduce in steps

create NFT -> mint NFT -> error

### Expected Behavior

Mint NFT

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

![2024-12-06 004744](https://github.com/user-attachments/assets/b2d82caf-070e-4d0f-a52d-1fad6396b259)

### Wallet Address & Transaction hash

Address: 14uCU9MxrdwJ87FyWMALqgcg3w3J1Zv6MszrN8jVC2vPL5Ep

### Relevant log output

```shell
Url: https://kodadot.xyz/create/collection
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Wallet: polkadot-js
Chain: ahp
Error: Minting Cogga failed
```

### Payment link for reward

POLKADOTHUB: 14uCU9MxrdwJ87FyWMALqgcg3w3J1Zv6MszrN8jVC2vPL5Ep

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Susankaten** [comment]
> ### What happened?
> failed when mint NFT.
> 
> ### Please reproduce in steps
> create NFT -> mint NFT -> error
> 
> ### Expected Behavior
> Mint NFT
> 
> ### What browsers are you seeing the problem on?
> Chrome
> 
> ### At which address did you encounter bug?
> kodadot.xyz
> 
> ### Are you logged in?
> Yes
> 
> ### Which wallet you are using?
> PolkadotJS
> 
> ### Screenshots
> ![2024-12-06 004744](https://private-user-images.githubusercontent.com/32870491/392912626-b2d82caf-070e-4d0f-a52d-1fad6396b259.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MTg5NDUsIm5iZiI6MTczMzQxODY0NSwicGF0aCI6Ii8zMjg3MDQ5MS8zOTI5MTI2MjYtYjJkODJjYWYtMDcwZS00ZDBmLWE1MmQtMWZhZDYzOTZiMjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE3MTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMWE5ODg5MDFlZWE5YzU5N2U3YzUwZjMzYWQ0YmIwZGE5MjljYzg4ZDQ2NDZlNTBmNDhlNmE4YjMyZjQ4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5MuhgvKnSD3YpwahBw0Om-0lo_1oDX2Y9a57Ng5RCLc)
> 
> ### Wallet Address & Transaction hash
> Address: 14uCU9MxrdwJ87FyWMALqgcg3w3J1Zv6MszrN8jVC2vPL5Ep
> 
> ### Relevant log output
> ```shell
> Url: https://kodadot.xyz/create/collection
> Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
> Wallet: polkadot-js
> Chain: ahp
> Error: Minting Cogga failed
> ```
> 
> ### Payment link for reward
> POLKADOTHUB: 14uCU9MxrdwJ87FyWMALqgcg3w3J1Zv6MszrN8jVC2vPL5Ep
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Hello @Johnny1110 
You are experiencing the transcript error,
It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID NFT91224
Please see the link below to our dedicated support line:
[Polkadot Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
