### ISSUE TITLE
Percentual price change index for NFT 

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1123]
### Is your feature request related to a problem?

Sometimes the artist puts the price too high and it takes a while that someone buys it.

Example (Art): 
- Artists puts it firstly for 1 KSM
- relist it fo 0.75
- relist it 0.5
- someone buys it

### Describe the solution you would like

The index should tell the price change from beginning to sale and then average (in this case -50/-50)

### Describe alternatives you have considered

If you have any ideas how to do it better lmk

### Screeenshots

👀

**Comment by yangwao** [comment]
Like AI which recommends you best price for listing? I guess thinking about this back in 
- #1483 
- #1119

**Comment by vikiival** [comment]
> Like AI which recommends you best price for listing

For the first buy:

first list 1 KSM

current list 0.5 KSM

App: -50% off since the first list

For other buys/lists: 

First buy 1 KSM
Current list 3 KSM

App: +300% since first buy
