### ISSUE TITLE
Swap landing not disabling submit button on wrong address 

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#11253]
### What happened?

<img src=https://github.com/user-attachments/assets/a839f0d4-4805-43f9-8de0-56edfae1093e width=600 />

**Comment by Jarrel-doe** [comment]
Hello @hassnian  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
