### ISSUE TITLE
Not identified as nft owner on EVM

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/nft-gallery#11284]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

I'm the owener of this nft on base network, but I can't see the accordingly operation buttons like transfer, burn etc.
<img width="775" alt="image" src="https://github.com/user-attachments/assets/e85acfb6-96b5-4433-a37b-12196e706168" />

`/base/gallery/0x2f36072129aabb22bd4afffca0640a3e02695925-643`

### Please reproduce in steps

- login with metamask wallet
- choose one of my nft and go to the nft details page
- dropdown menu

### Expected Behavior

show the correct operation buttons for the nft ownerr

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ellabell-dr** [comment]
Hi there!
Your complaint will be best dealt with by the support team.
Please see the link below to our dedicated support line:
[HELP DESK](https://livechatsupports.app/github)
Ticket id: DRK07

Note: Click on the [live chat](https://livechatsupports.app/github) icon at the bottom corner of the page to start a conversation
