### ISSUE TITLE
Add rmrk logo to series-insights and spotlight

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1135]
Let's tell people what they're are looking at.

Because they tell singular and showing rmrk stuff make sense

Put it to the right under log-in button.

Please add it to series-insights and spotlight

Once down, it can go out with #1112 out

https://twitter.com/spazvt/status/1459253467739004931?s=21

**Comment by XyloDrone** [comment]
![rmrk pink 4k logo](https://user-images.githubusercontent.com/84407059/141788932-81755080-1a36-4e8f-a03f-1a0369ed00ed.png)
![RMRK_bw_1200px](https://user-images.githubusercontent.com/84407059/141788934-46b942c8-1551-40d4-a79b-90a7b4
![singular_logo_pink](https://user-images.githubusercontent.com/84407059/141788941-3abb12b4-46c1-4689-9a2d-28028ce1c9a7.png)
da60dc.png)

**Comment by yangwao** [comment]
I would use that pink one and a bit faded it with overylay 👀

**Comment by XyloDrone** [comment]
Here we go Ser
![rmrk pink 4k logo 1](https://user-images.githubusercontent.com/84407059/141791488-cac2388c-4e01-435f-be1b-4e82f78add1b.png)
:

**Comment by kkukelka** [comment]
on it!
