### ISSUE TITLE
Specialized Twitter Cards for each view

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1136]
@xylodrone could help us on this page.

We can use the current template which is this one [on Series](https://kodadot.xyz/series-insights) 
![image](https://user-images.githubusercontent.com/5887929/141657355-2d87e85d-fb77-43df-8b16-ea49a836f0c7.png)

Let's use this as a template and add text under it.
- [Series](https://kodadot.xyz/series-insight) should have "Series Insights"
  - Title: Series Insights
  - Description: Ape into NFTs based on data points
- [Spotlight](https://kodadot.xyz/spotlight) -- "Creators Directory"
  - NFT Artist Rank
  - Discover new artists based on rank
- [Collections](https://kodadot.xyz/rmrk/collections) -- "Collections"
  - Collections 
  - Collect new mints with collection insights
- [Gallery](https://kodadot.xyz/rmrk/gallery) -- "Explore new mints"
  - Explorer
  - Ape into newest mints

**Comment by XyloDrone** [comment]
![Kodadot_Twitter Card_Collections](https://user-images.githubusercontent.com/84407059/141732454-58fabf6a-8674-4505-bbac-6f4240a48cc9.png)
![Kodadot_Twitter Card_Creators Directory](https://user-images.githubusercontent.com/84407059/141732470-1f85f077-a193-4a49-828a-c5bbdc66ef9d.png)
![Kodadot_Twitter Card_Gallery](https://user-images.githubusercontent.com/84407059/141732471-c85954d1-a3de-4375-9c69-93665a0360e7.png)
![Kodadot_Twitter Card_Series Insights](https://user-images.githubusercontent.com/84407059/141732472-f5674b1a-28c1-4a9d-9b22-0feeaa1dbb2b.png)

Figma Files: https://www.figma.com/file/tcq6xYg9aq06c9CPwXbgSg/?node-id=30%3A2

**Comment by yangwao** [comment]
Thinking how it would looks like once online as open graph cards are bit small, let's try with this one, better than current ones 😄

**Comment by yangwao** [comment]
On twitter card validator seems distorted 
![image](https://user-images.githubusercontent.com/5887929/141767721-6056641b-0271-483a-a8cb-3836c91cf37a.png)
Even on normal twitter somehow it's blurred?
![image](https://user-images.githubusercontent.com/5887929/141767834-d3fb0ace-d907-4126-b08a-9e1deff5d7ab.png)


but telegram looks good! 
![image](https://user-images.githubusercontent.com/5887929/141767766-5322dc15-ff20-4665-a3e4-084cab0842c6.png)

Thinking out loud.
@XyloDrone let's try put proportionally smaller (50%?) KodaDot logo, as branding and put that text bigger (+50%)?

**Comment by XyloDrone** [comment]
Let me know your thoughts on this one. It's made in a smaller resolution:
![Kodadot_Twitter Card_Creators Directory](https://user-images.githubusercontent.com/84407059/141771745-253f5db5-8610-4b3e-b322-70d711df88ca.png)

**Comment by yangwao** [comment]
What if we can make it even a bit bigger, 
like edges will be horizontal aligned

Edges of border of text on the left, with logo on the right 👀

**Comment by XyloDrone** [comment]
Update 3
![Kodadot_Twitter Card_Collections](https://user-images.githubusercontent.com/84407059/141790184-3ce3f399-9eea-46c0-a500-5d51b9de91a6.png)
![Kodadot_Twitter Card_Creators Directory](https://user-images.githubusercontent.com/84407059/141790193-7f64ee53-a75c-4b61-92ef-90453e01ce32.png)
![Kodadot_Twitter Card_Gallery](https://user-images.githubusercontent.com/84407059/141790200-f9f583e3-b1cb-4e65-9498-a74ea53818f4.png)
![Kodadot_Twitter Card_Series Insights](https://user-images.githubusercontent.com/84407059/141790202-862eabc5-19ce-4566-8ab0-73a0eb0d7d74.png)
:

**Comment by yangwao** [comment]
Oh yeah, let's fire this #1149 @roiLeo 👀

> Update 3 ![Kodadot_Twitter Card_Collections](https://user-images.githubusercontent.com/84407059/141790184-3ce3f399-9eea-46c0-a500-5d51b9de91a6.png) ![Kodadot_Twitter Card_Creators Directory](https://user-images.githubusercontent.com/84407059/141790193-7f64ee53-a75c-4b61-92ef-90453e01ce32.png) ![Kodadot_Twitter Card_Gallery](https://user-images.githubusercontent.com/84407059/141790200-f9f583e3-b1cb-4e65-9498-a74ea53818f4.png) ![Kodadot_Twitter Card_Series Insights](https://user-images.githubusercontent.com/84407059/141793080-f7ca02eb-6b2e-49b3-a6fd-6e5bf0cd7e72.png)
> 
> :

**Comment by XyloDrone** [comment]
Here we go again | Resize images belo
![Kodadot_Twitter Card_Collections](https://user-images.githubusercontent.com/84407059/141799927-64362342-01f0-4ba6-a8aa-c191329b2d68.png)
![Kodadot_Twitter Card_Creators Directory](https://user-images.githubusercontent.com/84407059/141799943-a5d8c064-3345-4e38-929f-f40fcdfd5eb0.png)
![Kodadot_Twitter Card_Gallery](https://user-images.githubusercontent.com/84407059/141799947-2cb52764-4d5e-4703-af37-90c74f2dd279.png)
![Kodadot_Twitter Card_Series Insights](https://user-images.githubusercontent.com/84407059/141799949-917c407f-1cc5-4e65-90f0-df9898b10e49.png)
![Kodadot_Twitter Card_Standard](https://user-images.githubusercontent.com/84407059/141799952-af3fdb41-ddd6-4836-b783-7dcd5bf89996.png)
w

**Comment by XyloDrone** [comment]
Here we go again, resize below 
![Kodadot_Twitter Card_Collections](https://user-images.githubusercontent.com/84407059/141800238-8655019f-8f79-4f55-9697-b556e525e73c.png)
![Kodadot_Twitter Card_Creators Directory](https://user-images.githubusercontent.com/84407059/141800253-a2be09b6-64ad-44de-9a43-a133fb4a4d78.png)
![Kodadot_Twitter Card_Gallery](https://user-images.githubusercontent.com/84407059/141800258-1ef3ea26-3377-4bb7-bbbe-16e149ba5168.png)
![Kodadot_Twitter Card_Series Insights](https://user-images.githubusercontent.com/84407059/141800263-6812e113-e354-4fc2-a248-108f09ff4086.png)
![Kodadot_Twitter Card_Standard](https://user-images.githubusercontent.com/84407059/141800268-9f625be8-0466-451f-af37-2b459d36db57.png)

**Comment by XyloDrone** [comment]
Landing and Mint

**Comment by yangwao** [comment]
> > Here we go again, resize below
> 
> pushed on #1149
> 
> What are the last two images for?

Yup 5th is for landing `/` 
6th should go for `/rmrk/mint` `/rmrk/create` `/permafrost/create`

**Comment by roiLeo** [comment]
Reopen for #1274 as we don't have the v3 cards.
ping @XyloDrone

**Comment by XyloDrone** [comment]
New cards here: 
https://github.com/kodadot/weyland/issues/11

**Comment by yangwao** [comment]
Lol, @vikiival accidentally close stuff, it's here @roiLeo https://github.com/kodadot/nft-gallery/issues/1529
