### ISSUE TITLE
Webshare api is gone on mobile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1137]
On item detail 

Take code from #797  #731 

![Screenshot_20211114-081204.jpg](https://user-images.githubusercontent.com/5887929/141671273-b51c66c5-239f-411c-b647-b4c250551128.jpg)

**Comment by yangwao** [comment]
Hey, @prachi00 are you keen to bring this code back to work? Someone apparently fired it off 😄
I've linked previous PR and issue as well.

**Comment by prachi00** [comment]
@yangwao sure I'll take a look

**Comment by yangwao** [comment]
> @yangwao sure I'll take a look

perfect ❤️‍🔥
