### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#114]
We have 44 branches so far!

**Comment by yangwao** [comment]
Removed merged.

![image](https://user-images.githubusercontent.com/5887929/117568738-6c2d8a80-b0c2-11eb-988c-9ce23f17b5ba.png)

**Comment by vikiival** [comment]
<img src=“https://http.cat/200” />

**Comment by yangwao** [comment]
Feel free reduce others https://github.com/kodadot/nft-gallery/branches/all?page=1

![image](https://user-images.githubusercontent.com/5887929/117568823-e958ff80-b0c2-11eb-8ecb-d333de117b6e.png)

**Comment by vikiival** [comment]
13 branches sounds fine
