### ISSUE TITLE
Fix identation for hound

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1141]
I've noticed the same hound in many PRs recently, is it fixed in `main`? 😄

![image](https://user-images.githubusercontent.com/5887929/141681065-739a87b3-1892-4f40-b079-2d3aa5db0762.png)

**Comment by prachi00** [comment]
@yangwao I'll check this

**Comment by prachi00** [comment]
@yangwao I don't think this is happening anymore

**Comment by yangwao** [comment]
okay closing then!
