### ISSUE TITLE
Layout on collection view is small 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1155]
https://beta.kodadot.xyz/en/rmrk/collection/58805bce8156c8b76e-3VB0P

![image](https://user-images.githubusercontent.com/5887929/141773375-2f81f036-9c9f-4054-8687-32a8a2e2f059.png)

How it looks on production rn
https://kodadot.xyz/rmrk/collection/58805bce8156c8b76e-3VB0P
![image](https://user-images.githubusercontent.com/5887929/141773403-b4c858ea-9206-443d-8868-19eba9d86cdb.png)

**Comment by roiLeo** [comment]
closed in #1403
