### ISSUE TITLE
Filter for file type

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1162]
Community demand https://twitter.com/ClownWorldHouse/status/1460078112851513350

We had a filter in the past, it was discarded with old implementation, need to have it in a new one.

https://twitter.com/KodaDot/status/1460231292084277257

**Comment by nick-dev123** [comment]
@yangwao What are the supported file types? Are the file types the one mentioned in #1744?
IS this issue related https://github.com/kodadot/rubick/issues/104?

**Comment by roiLeo** [comment]
> What are the supported file types? 

```
{
  bmp: 'image/bmp',
  gif: 'image/gif',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  png: 'image/png',
  svg: 'image/svg+xml',
  tiff: 'image/tiff',
  webp: 'image/webp',
  mp4: 'video/mp4',
  ogv: 'video/ogg',
  mov: 'video/quicktime',
  qt: 'video/quicktime',
  webm: 'video/webm',
  glb: 'model/gltf-binary',
  gltf: 'model/gltf+json',
  flac: 'audio/flac',
  mp3: 'audio/mpeg',
  json: 'application/json'
}
```
and more

> IS this issue related [kodadot/rubick#104](https://github.com/kodadot/rubick/issues/104)?

more or less, imo file type need to be fetch from indexer. currently it's not suported all type are null.

**Comment by JustLuuuu** [comment]
yeah we have #7786 opened for this
