### ISSUE TITLE
Add pagination under collected 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1170]
Hey seems #1166 blown out pagination on the top of the collected tab.
Once you attention is there let's put layout switcher to the pagination for collections on artist as well

https://main--nftkodadot.netlify.app/rmrk/u/CdA62JpyfEyEASA5XKYJAyYZmdQPqe5X9x8MLnoTWtc9rNn?tab=collected
![image](https://user-images.githubusercontent.com/5887929/141970587-5a49a6c7-f532-4c37-9e26-824e8edc9293.png)

https://main--nftkodadot.netlify.app/rmrk/u/CdA62JpyfEyEASA5XKYJAyYZmdQPqe5X9x8MLnoTWtc9rNn?tab=collection
![image](https://user-images.githubusercontent.com/5887929/141970779-3cc1a2e2-8489-4b5b-954d-e8bc49366770.png)

Please check it on sold tab as well
![image](https://user-images.githubusercontent.com/5887929/141971158-eb34c86c-c1dd-44b5-b6b7-8841fd7576fe.png)

**Comment by prachi00** [comment]
@yangwao I'll do this

**Comment by roiLeo** [comment]
closed in #1179
