### ISSUE TITLE
Swap description with tabs on collection

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1173]
Let's put the collection description above tabs 

It would look much more aligned 

![image](https://user-images.githubusercontent.com/5887929/141985943-df38c42f-be06-471b-9b4a-08b271475d78.png)

### Ref
https://kodadot.xyz/rmrk/collection/0E54E51D92AECA5749-KLIFE?tab=collection

**Comment by prachi00** [comment]
@yangwao I'll pick this up
