### ISSUE TITLE
Show NFTs by most emoted 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1174]
Expand sort by most emoted NFTs
Test on 
- gallery feed
- profile
- collection detail
- collections

kodadot/ideas#7 could be added to Flip as well

**Comment by roiLeo** [comment]
Status:
- ✅ gallery feed
- ✅ profile
- ✅ collection detail
- ❌ collections (CollectionList, `collectionSortOption` sortBy `CollectionEntityOrderByInput` need to be replaced by `NFTEntityOrderByInput`)

**Comment by vikiival** [comment]
Emotes are not longer present on AHP/AHK 

Happy to respin on EVM 
- https://github.com/kodadot/gibanica/issues/3
