### ISSUE TITLE
Fetch random items to feed - shuffle

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1176]
Now magic wand shuffles between pages which is good and we would add functionality that it would shuffle from the whole set of NFTs new feed. 
It could be expanded with an existing magic wand

Implement it for
- gallery feed
- collection detail
- collections
- profile

**Comment by prachi00** [comment]
@yangwao Can you explain more? You mean now the magic random button should shuffle nfts by staying on page 1 only?

**Comment by yangwao** [comment]
> @yangwao Can you explain more? You mean now the magic random button should shuffle nfts by staying on page 1 only?

It should fetch random NFTs, not just pages. that mean to have more variance. 
let me draft on explainer.

when I click on random button now, I see NFTs in fixed range of 12, so I land either on [24-36] [36-48] [48-60]

but with shuffle I would like to have NFTs on page fetched from page 25, page 46, page 56, and so on.
So you can randomize page and order of NFTs and then assemble whole new "page"

Probably we can think of putting the address of that NFTs into address bar so that your shuffle roll is shareable

**Comment by prachi00** [comment]
@yangwao by new page, you mean user should go the nft detail route? `/rmrk/detail` this one, with the random nft ?
Also, where should the shuffle button show up? near the magic wand?

**Comment by yangwao** [comment]
> @yangwao by new page, you mean user should go the nft detail route? `/rmrk/detail` this one, with the random nft ? Also, where should the shuffle button show up? near the magic wand?

Oh, actually that's a good idea as well. 
Let's add a random button to the item detail if possible.

Yes, on gallery feed next to the magic wand.

**Comment by prachi00** [comment]
@yangwao also when we do shuffle, like suppose in gallery, what happens to the pagination in gallery? is it hidden?

**Comment by prachi00** [comment]
@yangwao do let me know more on this, thank you

**Comment by yangwao** [comment]
> @yangwao also I have two more doubts:
> 
> 1. How are we suppose to fetch random nfts from different pages because we have pagination, so we don't really have all the data initially?

Good question! Probably it will be heavy, let's summon @vikiival if have idea how to do it efficiently.

> 2. when we do shuffle, like suppose in gallery, what happens to the pagination in gallery? is it hidden?

Yeah, pagination will be effectively gone because pagination from my point is something comparing to known index/position where in shuffle you are creating new "index" on your own.
