### ISSUE TITLE
Error on main-nuxt development mode

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1189]
### What happened?

Infinite loader

### Please reproduce in steps

- fresh install
- `yarn dev`
- Go to localhost
- local website not working

### Expected Behavior

Throw error?

### Are you logged in?

Not yet

### At which address did you encounter bug?

http://localhost:3000/

### Screenshots

![Screenshot 2021-11-17 at 08-44-01 KodaDot - Polkadot Kusama NFT Explorer](https://user-images.githubusercontent.com/9987732/142157273-a8de8b3d-97c3-4cc2-9886-ebd621f1eeb3.png)

### Relevant log output

```shell
Uncaught ReferenceError: __VUE_HMR_RUNTIME__ is not defined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dezine2dev** [comment]
@roiLeo , do you still see this issue in your local?

**Comment by roiLeo** [comment]
> @roiLeo , do you still see this issue in your local?

Yes, I still have this error
<img width="760" alt="Capture d’écran 2021-11-18 à 3 59 05 PM" src="https://user-images.githubusercontent.com/9987732/142440000-6ac2b288-ab75-43e1-a727-5f988cb32669.png">

**Comment by roiLeo** [comment]
#### additional information
- tried to install project on windows and it worked fine
- still got this error on macOS 11.6 with node (v14.18.1, v15.3.0, v16.13.0)

**Comment by yangwao** [comment]
> * still got this error on macOS 11.6 with node (v14.18.1, v15.3.0, v16.13.0)

What was commands you did so I can try to replicate? tl;dr worked for me locally on v16 osx 11.6.1

**Comment by yangwao** [comment]
did fresh clone against `main-nuxt` & yarn;yarn dev and localhost:3000 worked

I'm testing it with `node v15.12.0`

maybe purge your yarn cache? 
![image](https://user-images.githubusercontent.com/5887929/142768818-74c874de-92f6-4e58-8460-ef54902fa2b4.png)
![image](https://user-images.githubusercontent.com/5887929/142768823-e7d4b74c-b2bb-49fd-b53b-58e5a5e0ffb5.png)

**Comment by yangwao** [comment]
> can't put recording here, but WFM sadly 😄 

Did checkout #1212 1212 and works for me.

![image](https://user-images.githubusercontent.com/5887929/142769023-a1213bef-0de4-458f-91f9-97f02ff9ddb7.png)

**Comment by vikiival** [comment]
WFM


<img width="1792" alt="Screenshot 2021-11-22 at 12 44 15" src="https://user-images.githubusercontent.com/22471030/142856085-acb79401-e195-41a3-bc5d-fb7c0cbf967b.png">

**Comment by yangwao** [comment]
Interesting case... 

![image](https://user-images.githubusercontent.com/5887929/142868116-9acae76b-3791-4d5f-b87d-80678f7d3155.png)

**Comment by yangwao** [comment]
Probably it's time to summon almighty port 5858 https://nodejs.org/en/docs/guides/debugging-getting-started/

**Comment by roiLeo** [comment]
Why?  I still have this problem 😢
