### ISSUE TITLE
Show me owned NFT from collection detail and collections

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1190]
Let's add a view that would show NFTs from Collections you've collected
- collection detail
- collections #1023 - so showing only NFTs if I already own part of that collection

Right now we are showing only green shadow under, whenever you are owner
![image](https://user-images.githubusercontent.com/5887929/142190987-38f55ffc-627a-426c-b226-dd5b64a3df49.png)

# Ref 
testcase - I.e. https://kodadot.xyz/rmrk/u/HnxhadMWP6SBFqJgqzRknw35y1LqgViH7PfpKkCWeVG5dAA

**Comment by XyloDrone** [comment]
Related to #678

**Comment by roiLeo** [comment]
Meanwhile "[Own](https://beta.kodadot.xyz/explore/explore/items?listed=false&page=1&owned=true)" filter 
![Screenshot 2023-03-24 at 16-23-59 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer](https://user-images.githubusercontent.com/9987732/227568893-fc9c4d9c-660b-445a-9204-e1a57902faef.png)
