### ISSUE TITLE
fy_iceworld map for gallery

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1193]
Who would help us create gltf model map for the gallery?
Bounty may be higher if it's delivered faster!

![image](https://user-images.githubusercontent.com/5887929/142199836-ed0420b8-647e-45b3-9598-e975ecc7b144.png)

**Comment by Mohammadrazakhan** [comment]
I can create 3d model for the gallery

**Comment by onerawartist** [comment]
Im an architect ^^ tell me what you need ? How many items is gonna be displayed ? How big do you want the gallery to be ?

**Comment by onerawartist** [comment]
![post1 (1 of 1)](https://user-images.githubusercontent.com/71472224/142257923-da8f67c5-a903-4adc-8841-bfc5dfea7f03.jpg)
![wall2 (1 of 1)](https://user-images.githubusercontent.com/71472224/142257959-2f002de8-612a-45b5-9bf6-2973bbbc886b.jpg)
![wall3 (1 of 1)](https://user-images.githubusercontent.com/71472224/142257980-727b2caa-6232-476d-919e-059be193ec96.jpg)
![wall4 (1 of 1)](https://user-images.githubusercontent.com/71472224/142258009-bbf38a56-dc7b-4749-a080-30b1629f3204.jpg)



i can ICE this out ? or do you need it to be open to the sky ?

**Comment by rchovatiya88** [comment]
@yangwao Let's start "Create Koda Gallery" collection contest? we can use many galleries 
@onerawartist  that model is sick!  

So here's the deal  
- We need private rooms for users to display my collection of NFTs (kinda like /Collections tab) 
- We need big Galleries for artists to display their Art (like when user go to /gallery/artis) 

Here is problem 
We have different number of paintings to display per artist and collection ( 1000 vs 10 displays) 
- How do we keep a standard positions of painting and switch the gallery environment. 



![Screen Shot 2021-11-17 at 1 41 26 PM](https://user-images.githubusercontent.com/16197756/142262328-6001674b-0b97-468d-a191-93d1c5056116.png)
![Screen Shot 2021-11-17 at 1 41 21 PM](https://user-images.githubusercontent.com/16197756/142262332-56288e29-a53e-4f46-a525-441c5853d9c8.png)

See Depending on the type of gallery we have to position dynamic data (NFTS) on the specific glb model - we don't know where the walls are unless we tell where to put images n what walls. 
**So let's try to think more on abstraction layer, meaning - different types of rooms with diff colors , textures lighting, but walls stay same so we only have position the images once** 

Different types of Private rooms (gaming room, living room etc) but walls position stay same 
Different types of galleries (outside, inside, multiple floors, textures, etc) but most walls stay same 
_This will allow us to scale to various users faster and add customization without too much manual efforts_

**Comment by onerawartist** [comment]
https://user-images.githubusercontent.com/71472224/142271733-ea6c7918-cf40-4fba-8b3a-8422abe49e8f.mp4https://user-images.githubusercontent.com/71472224/142271754-4bac983d-deb0-4aa2-9f72-b14c92a39b6c.mp4https://user-images.githubusercontent.com/71472224/142271760-389f439c-a8cb-4905-84ac-a24c345e0485.mp4

**Comment by onerawartist** [comment]
https://user-images.githubusercontent.com/71472224/142271943-fe7cd874-17be-420e-a4ea-21171cde01de.mp4

**Comment by onerawartist** [comment]
https://user-images.githubusercontent.com/71472224/142272034-3f1ad582-c234-4f8a-9b49-1aca5b422b19.mp4

**Comment by onerawartist** [comment]
Theborder is messed up ^^ but here's my first draft for the ice nft gallery , ice blocks to be used as holders for the art

**Comment by onerawartist** [comment]
@rchovatiya88 i get what you're trying to do ,but i think that will affect the quality of the design , its always bad to design ''one thing fits all'' i prefer we design something original for each event and for each artist

**Comment by rchovatiya88** [comment]
@onerawartist yeh agree, it will probably a bit of both but makes sense 

*One Note* 
For WebXR to work we need our `.glb` files to have navmesh (where users can walk around and not crash into objects or walls) 
Please watch this vid, it has great tips for higher performance models and adding navmesh to 3D models - https://youtu.be/Ts2pGrKEnHI
- Thanks⚔️

**Comment by onerawartist** [comment]
we need feedback from @yangwao @vikiival

**Comment by onerawartist** [comment]
https://user-images.githubusercontent.com/71472224/142294222-32501af8-4c1c-4eb6-80bf-5ec3ed0726df.mp4

**Comment by yangwao** [comment]
> I have just made the model shown above
> 
>  Substance.Painter.-.Gallery.2021-11-18.00-37-46_Trim.mp4

Yeah, this works! Let's post gltf model somewhere, highlight me at our discord https://discord.gg/35hzy2dXXh in xr-dev channel I'll pick it up, hope you accept $KSM !

**Comment by yangwao** [comment]
>  2021-11-17.23-41-30.mp4

@onerawartist  Yes, this model is perfect, if you can add some ways to place 2d images and 3d models and we can take it from there, I'm confident we will have more worlds coming up! I really like your hi-fi designs as well! Happy to come up with new name for your creation! :)

**Comment by yangwao** [comment]
> @yangwao Let's start "Create Koda Gallery" collection contest? we can use many galleries @onerawartist that model is sick!

Oh yeah, that's music for my ear, we can definitely open convo on this! Happy to put some bounties and start making more worlds for this

> So here's the deal
> 
> * We need private rooms for users to display my collection of NFTs (kinda like /Collections tab)
> * We need big Galleries for artists to display their Art (like when user go to /gallery/artis)
> 
> Here is problem We have different number of paintings to display per artist and collection ( 1000 vs 10 displays)

I agree we should have pre-curated 3d galleries for particular amount of items, one size doesn't fits all probably

> **So let's try to think more on abstraction layer, meaning - different types of rooms with diff colors , textures lighting, but walls stay same so we only have position the images once**

I'm pretty aligned on this! :)

> ...This will allow us to scale to various users faster and add customization without too much manual efforts_

Agree 100%

**Comment by onerawartist** [comment]
@yangwao 
i will be working the place holders next , i just wanna know if you want me to keep going with the "ice theme" or design my own thing that goes with the rest of the pavilion style? 
and for the name of it ofc ^^ give me your suggestions

**Comment by Mohammadrazakhan** [comment]
> > I have just made the model shown above
> > Substance.Painter.-.Gallery.2021-11-18.00-37-46_Trim.mp4
> 
> Yeah, this works! Let's post gltf model somewhere, highlight me at our discord https://discord.gg/35hzy2dXXh in xr-dev channel I'll pick it up, hope you accept $KSM !

Ye sure I'll send u by mail

**Comment by vikiival** [comment]
This was cute ❤️
