### ISSUE TITLE
Install conventional commits for contributing.md

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1196]
## Ref

- https://www.conventionalcommits.org/en/v1.0.0/
- https://www.youtube.com/watch?v=KjYBh7rq0-Y
- maybeee? https://gitmoji.dev/
- is this same https://robinpokorny.github.io/git3moji/
- maybbeeeee https://gist.github.com/parmentf/035de27d6ed1dce0b36a

**Comment by roiLeo** [comment]
- 👀 vscode [gitmoji](https://marketplace.visualstudio.com/items?itemName=Vtrois.gitmoji-vscode) extension
