### ISSUE TITLE
Add narrator voices for the rooms

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1197]
Inspired by dakaguia world so we can add narrator voices for galleries

**Comment by rchovatiya88** [comment]
https://www.freecodecamp.org/news/a-primer-on-a-frame-audio-52dd56e54876/

**Comment by yangwao** [comment]
It could work in a way that when the author mints NFT collection, it can include NFT audio which would be as voice-narrator for that particular collection which could offer people to drive their rooms in "customized" way
