### ISSUE TITLE
Integrate sketchfab embeds into virtual worlds

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1198]
Let's try integrate, check ToS if not violating this embedding in our rooms 

https://sketchfab.com/3d-models/robot-izhevsk-mechanics-draft-9b9354d1de4744b6890ecab57b72c7c4

![image](https://user-images.githubusercontent.com/5887929/142211770-b4d9617c-e06e-404d-9064-c1c292784ce3.png)

**Comment by rchovatiya88** [comment]
Adding Sketchfab integration would be great!
