### ISSUE TITLE
Check on kodadot_preloader.svg weird routes

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1199]
Found in server logs that this is happening, lot of requests are coming on this weird routes 

```
/rmrk/collection/kodadot_preloader_1.svg | 1026
/rmrk/detail/kodadot_preloader_1.svg | 850
/rmrk/u/kodadot_preloader_1.svg | 605
/rmrk/kodadot_preloader_1.svg | 567
```

![image](https://user-images.githubusercontent.com/5887929/142273902-66436ac3-1b40-4d6c-a763-50c2d33f107d.png)

**Comment by roiLeo** [comment]
closing this one since there is no `kodadot_preloader_1` reference in project
