### ISSUE TITLE
Add tracking so we can better understand users

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1200]
Yeah, the time has come, we need bit gain insights where bugs happens before are being reported 

> We need to gain some insights how app behaves etc to give us hints where to improve

**Comment by vikiival** [comment]
May best option https://usefathom.com/

**Comment by yangwao** [comment]
👀  let's crack on this later this week
![image](https://user-images.githubusercontent.com/5887929/142886705-1dae7f6f-af57-4968-8f2d-0411b9b119d2.png)

**Comment by vikiival** [comment]
[Snippet injection](https://docs.netlify.com/site-deploys/post-processing/snippet-injection/)

**Comment by yangwao** [comment]
Prepare #1267 and let's add it.

> May best option https://usefathom.com/

WFM 
![image](https://user-images.githubusercontent.com/5887929/143018516-7676aa43-a395-499c-aa5c-b110602faf6b.png)

**Comment by yangwao** [comment]
Time is now

**Comment by yangwao** [comment]
what's about yolo https://github.com/nuxt-community/google-analytics-module

**Comment by roiLeo** [comment]
Google analytics is an easy solution, now it depends on your choices if you want to do with or without GAFA tools.
You should consider adding a cookie notice for European users. (we already send data through discord widget)

**Comment by yangwao** [comment]
It's GA4 code 
```G-R21B1E85QE```

@roiLeo yes, if you can put something super easy! Thinking something in the top?

Gonna crack on some new PR with code etc:)
We need to preserver data as now we are locked in Netlify which isn't inherently bad, but we don't have any other measurement and not sure about CF what can offer, more insights, more data, higher odds we can see what's happening and why! :)

**Comment by yangwao** [comment]
Probably making it as optional environment variable as it's not hardcoded tho and we can test this one for beta.kodadot.xyz if everything works and then I can create another one for productions so we are briefly in numbers, flow etc bounces

**Comment by yangwao** [comment]
okay seems easy to go https://google-analytics.nuxtjs.org/setup/
