### ISSUE TITLE
Router on pagination should have complete history

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1210]
Once I push random or paginate it's not stacking into history.

So then when the user clicks back it pushes the user to somewhere else (to previous complete different view) than expected

Probably need to check how pagination works.

Stop using replace and use push probably?

Probably use push only for random for now as it may broke search and filter to needs re render components

**Comment by prachi00** [comment]
@yangwao I'll do this

**Comment by yangwao** [comment]
> @yangwao I'll do this

Found this issue searching for something else, how this is looking this?

**Comment by prachi00** [comment]
@yangwao tried doing router.push instead of replace, did not work as expected

**Comment by iMac7** [comment]
@yangwao I don't get the description, may I see a screen recording of this?
