### ISSUE TITLE
Collections on mobile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1217]
Let's put to description in table like 2x2 so it's costs less room on mobile to scroll

![Screenshot_20211120-000531.jpg](https://user-images.githubusercontent.com/5887929/142702230-0cf0b452-3b55-4350-bb61-55687d3f4588.jpg)

**Comment by prachi00** [comment]
@yangwao I'll do this

**Comment by yangwao** [comment]
Let's go! I'll assigned you @prachi00 :)
