### ISSUE TITLE
Option to list or consume is gone on owned NFTs

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1221]
[13:56] one_raw_artist: the option to list or consume my NFT is gone in this new UI update
[13:56] one_raw_artist: it works fine when the NFT is not mine

![image](https://user-images.githubusercontent.com/5887929/142724114-5e5f8903-38e4-41f3-9866-e58107445f7f.png)
![image](https://user-images.githubusercontent.com/5887929/142724119-8fc02c56-f806-4992-8700-1868962c4f30.png)

@onerawartist please post your address, I'll send you bug bounty

**Comment by onerawartist** [comment]
@yangwao i'm not a coder in any way but im glad to be part of the development of kodadot ^^, here's my address:
JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7

**Comment by yangwao** [comment]
> @yangwao i'm not a coder in any way but im glad to be part of the development of kodadot ^^, here's my address: JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7

Sent payout https://kusama.subscan.io/extrinsic/10175825-2

**Comment by roiLeo** [comment]
closed in #1215
