### ISSUE TITLE
Routing error on collections view

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1224]
When I'm at https://deploy-preview-1212--koda-nuxt.netlify.app/rmrk/collections and I click on picture I end up on `/` route

https://user-images.githubusercontent.com/5887929/142725990-7fffd0ca-3f73-4a66-b049-af3bcb2ee846.mov

**Comment by yangwao** [comment]
Still happening on the current beta.kodadot.xyz during writing this

**Comment by roiLeo** [comment]
Closed in #1255 & #1471
