### ISSUE TITLE
Annoying warning on Transfer

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1227]
Every time I load transfer with an address like https://kodadot.xyz/transfer/?target=HcEvTkvAPYEEGEndFV9sMmS3P83jdtwhwZq37GfdzA3mLrL it this pops up

Probably it would be a harder one.

![image](https://user-images.githubusercontent.com/5887929/142727378-654c6e11-13f7-4f7d-af21-9b0c3b39ca06.png)

**Comment by prachi00** [comment]
@yangwao I'll do this

**Comment by yangwao** [comment]
I haven't seen it while

**Comment by vikiival** [comment]
Looks like it was closed by https://github.com/kodadot/nft-gallery/pull/1263
