### ISSUE TITLE
Add the Option to search for the name on the collection

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1231]
### Is your feature request related to a problem?

I'm always frustrated when [i can't find a collection, even if i know its name]

### Describe the solution you would like

I would like to see an option to search like we have when exploring the gallery

### Describe alternatives you have considered

a search bar 

### Screeenshots

![03](https://user-images.githubusercontent.com/71472224/142730954-16728e4e-b3b2-496c-9aa1-932d71fc65fa.png)

**Comment by yangwao** [comment]
Continue to #1023 
Thanks for reporting! We will put it higher in our pipeline!

Me personally want it as well! :)

**Comment by preschian** [comment]
hello @XyloDrone , can you elaborate more about this.
is the feature different from currently running?
<img width="1624" alt="Screen Shot 2022-03-31 at 11 16 54 PM" src="https://user-images.githubusercontent.com/734428/161102481-e716ff39-7188-44ec-baec-d341be2a4722.png">

**Comment by XyloDrone** [comment]
Well spotted I think this has been resolved. @yangwao shall we close the issue?

**Comment by yangwao** [comment]
yes, closing as meanwhile we have it, we will be doing unification explorer+collections 
#2719

**Comment by onerawartist** [comment]
> Hmm, seems like we can search for artists, just collections and NFTs?

can't*

**Comment by roiLeo** [comment]
> Hmm, seems like we can't search for artists, just collections and NFTs?

What did you have in mind? a new screen? or from the search bar?

**Comment by XyloDrone** [comment]
Just from the search bar. Seems like collections and NFTs are easily searchable, just missing artists :D.

**Comment by yangwao** [comment]
i'm pretty sure we talked w @vikiival about indexing artist, maybe we just forgot to put into issue lol, searching for it

**Comment by yangwao** [comment]
<img src="https://media1.giphy.com/media/lVhFOxFmaJezm/giphy.gif"/>

it was creators, not artists that's why :D 
adding issue SEO 
https://github.com/kodadot/nft-gallery/issues/2112

**Comment by yangwao** [comment]
Also want to highlight we have that issue 
- #1562 which focuses on search stuff

**Comment by XyloDrone** [comment]
Sweet, cheers!

**Comment by vikiival** [comment]
> i'm pretty sure we talked w Viki

Yup it's tracked in rubick and magick
https://github.com/kodadot/rubick/issues/31

https://github.com/vikiival/magick/issues/19
