### ISSUE TITLE
add in the filters list '' By artist name " and " By collection name" 

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1232]
### Is your feature request related to a problem?

i know some artists on the platform and i always have hard time finding their profiles 

### Describe the solution you would like

more options in the filter list ^^ 

### Describe alternatives you have considered

so when i type the name of an artist i know i can find all his collections Or his nfts 

### Screeenshots

![04](https://user-images.githubusercontent.com/71472224/142731054-4e2791de-8fb3-4f01-b209-753ede0f8cd4.png)

**Comment by yangwao** [comment]
gallery feed as itself might be discontinued for some new rework, with #348 hopefully! 
rest is being done in #1023
