### ISSUE TITLE
Spotlight page should have the option to flip pages at the bottom

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1233]
### Is your feature request related to a problem?

I'm always frustrated when [i have to scroll all the way up each time i wanna go to the next page]

### Describe the solution you would like

option to change the page on the bottom like we have on the top

### Describe alternatives you have considered

option to flip pages or a shortcut to take you to the top of the page

### Screeenshots

![05](https://user-images.githubusercontent.com/71472224/142731512-dc10d00d-4641-485b-953b-9e3014c704a4.png)

**Comment by yangwao** [comment]
@onerawartist let's post your KSM address in this format down. This was legit feedback.
https://kodadot.xyz/transfer/?target=<My_Kusama_Address>

**Comment by onerawartist** [comment]
@yangwao 
JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7

**Comment by onerawartist** [comment]
@yangwao 
<JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7>

**Comment by onerawartist** [comment]
@yangwao 

I don't know if i did it wrong or it was supposed to hide my address lol im new to github ^^

**Comment by yangwao** [comment]
> @yangwao

https://kodadot.xyz/transfer/?target=JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7

There I've fixed it for you, markdown format is `[link](url)` so `[Payout](https://kodadot.xyz/transfer/?target=JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7)` will look like this [Payout](https://kodadot.xyz/transfer/?target=JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7)

**Comment by yangwao** [comment]
Payout sent https://kusama.subscan.io/extrinsic/10193226-2 @onerawartist
