### ISSUE TITLE
Add tooltip to explain switches at while minting for creators

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1234]
### Is your feature request related to a problem?

its not easy for new users to understand what these options mean 
![06](https://user-images.githubusercontent.com/71472224/142731928-bb5c5b4e-db62-4c6c-8ec6-732b84be56cf.png)

### Describe the solution you would like

I would like to see a small option where you can hover the mouse and see a small window explaining what that option is for 
![07](https://user-images.githubusercontent.com/71472224/142731997-7b73600b-646f-4f5c-9ae0-5e25d83dfe31.png)
 like the one in the photo " the small "i"

### Describe alternatives you have considered

I have tried this alternative

### Screeenshots

Paste your vision

**Comment by yangwao** [comment]
Adding tooltip section to explain all switches would be more than welcome. Probably link it to the FAQ. Add explainers there

Texts which could be put into `en.json`
Cover costs mean that users help to support initial costs for KodaDot which stores your JPEG on your behalf.
Carbonless NFT means that you are helping cover costs for carbon credits and planting trees https://kodadot.xyz/carbonless
Using Arweave means that you are storing your multimedia forever on Arweave, good for small assets like JPEG.

@onerawartist if you will make Pull Request to the https://github.com/kodadot/nft-gallery/blob/main/src/locales/en.json it would help others as well and can make bounty for that!

**Comment by onerawartist** [comment]
@yangwao i don't know how to do that 😅 i only know how to report an issue in github

**Comment by yangwao** [comment]
> @yangwao i don't know how to do that 😅 i only know how to report an issue in github

You can see manual here https://github.com/kodadot/nft-gallery/tree/main/src/locales

**Comment by onerawartist** [comment]
@yangwao 
i tried my best to understand what im doing but i couldn't, i'm sorry i can't learn to code right now, i have a taste in design and colors , i will always be reporting UI and UX ideas, but i can't go through the code to change it my self

**Comment by jbienesdev** [comment]
Hi @yangwao . It's my first time to contribute to the repo. Can I take this issue?

**Comment by onerawartist** [comment]
@jbienesdev please do ^^
