### ISSUE TITLE
the Language button is not clear when saying "GB" / windows doesnt show emoji flags

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1235]
### Is your feature request related to a problem?

I'm always frustrated when [...]
![08](https://user-images.githubusercontent.com/71472224/142732105-2c857a3c-6890-464b-bd0d-62917eff7949.png)

### Describe the solution you would like

i would like to see "GB" replaced with "English" , so the visitor knows that's the place to choose a language 

### Describe alternatives you have considered

/

### Screeenshots

/

**Comment by roiLeo** [comment]
Hey, could you give us more infos about your browser and system?
Because there should be emojis like this:
![Screenshot 2021-11-20 at 19-09-24 KodaDot - Kusama NFT Market explorer](https://user-images.githubusercontent.com/9987732/142736847-220f1b51-6640-4cd0-906f-24f67465576d.png)

**Comment by onerawartist** [comment]
Windows 10 ''in french'' 
And the latest google chrome ''in English''

**Comment by onerawartist** [comment]
@roiLeo

**Comment by yangwao** [comment]
> Windows 10 ''in french'' And the latest google chrome ''in English''

Strange, Windows should work okayish.

**Comment by yangwao** [comment]
@d14 may check in w10, but heard that w10 lacks flags lol

**Comment by yangwao** [comment]
Seems more complex problem https://answers.microsoft.com/en-us/windows/forum/all/flag-emoji/85b163bc-786a-4918-9042-763ccf4b6c05

**Comment by onerawartist** [comment]
Windows is always messing things up with updates lol

**Comment by onerawartist** [comment]
@yangwao , why not remove the emojis and put just a simple text.

![Annotation 2021-12-03 213934](https://user-images.githubusercontent.com/71472224/144670191-d32a4c86-b88d-4023-b629-4fe173bf6f6f.png)

**Comment by onerawartist** [comment]
@vikiival @prachi00 is it possible?

**Comment by vikiival** [comment]
Oooor maybe flags ? Cc @roiLeo

**Comment by roiLeo** [comment]
> Oooor maybe flags ? Cc @roiLeo

+1 to use svg/png flags. Let's find a nice pack.

**Comment by roiLeo** [comment]
I can see emoji flags on windows with firefox.
![Screenshot 2021-12-17 at 10-58-14 nft-gallery-nuxt](https://user-images.githubusercontent.com/9987732/146526410-ad919052-5c3d-4f66-824e-f1cb66b212ec.png)

Can't with Microsoft Edge and Google Chrome (Chromium based browser)
![image](https://user-images.githubusercontent.com/9987732/146526784-8fc1e99d-f722-4799-b3ae-6f06d20eb6c7.png)

Note: Weird font style on firefox

**Comment by roiLeo** [comment]
App ui is different now

**Comment by vikiival** [comment]
cc @exezbcz check screenshots
