### ISSUE TITLE
Enable owner to control own NFT item

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1243]
I Can not LIST, UNLIST, CONSUME 
Reported by @jkdizajn

https://kodadot.xyz/rmrk/detail/9864694-0E76E3AC15B4C1FA1E-EDOTSAMALX-EARLY_DOTSAMA_LISBOA_2021_9-0000000000000009
![image](https://user-images.githubusercontent.com/5887929/142769770-d3746b93-151a-44f3-b561-703e4a93ed89.png)

**Comment by vikiival** [comment]
fixed in 978547e759c2188ae321c24e28ae9c0ad1642545
