### ISSUE TITLE
Make 3d models full width 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1244]
I guess we can put glb models on full width as offers more roam to interact on desktop and bigger detail.

https://kodadot.xyz/rmrk/detail/10164463-FC77C33AB229A2056A-RAWCONCEPT-THE_PORTABLE_EXPO-0000000000000012

![image](https://user-images.githubusercontent.com/5887929/142770887-0cb04084-750c-43a8-b2dd-aa6fceda2afd.png)

**Comment by roiLeo** [comment]
closed in #1298
