### ISSUE TITLE
Fix ss58 handling for KSM on transfer 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1253]
That's it
users will be pasting default addresses and we should fix it for KSM right now :)

![image](https://user-images.githubusercontent.com/5887929/142867263-99795679-aa70-4edc-8418-f89e05f97108.png)

**Comment by yangwao** [comment]
5HbsVS3M36Gy3dtwiLuwswJBZtuWCdebgk48Ek2BCGdD38Lj -> J7V9kPDfTHtoHiPV3izmtfBiVBk1JTn97tsdQJ8g4qhnH3z

**Comment by vikiival** [comment]
Merged in #1263
