### ISSUE TITLE
Error on vuex 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1257]
Error on `nodejs v16.13` on `main-nuxt` `bc9acdec8407b7ccb61ce61fb496620a87d5d191`

![image](https://user-images.githubusercontent.com/5887929/142876749-40d5126f-918b-4d2f-af06-673b2b0db211.png)

**Comment by dezine2dev** [comment]
can not reproduce error in node16.13.0
can I have more detail regarding the enviroment

**Comment by vikiival** [comment]
Is this obsolete ?

**Comment by dezine2dev** [comment]
I do not see the issue
