### ISSUE TITLE
Revisit Docker images for `main` 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1258]
Check for the current codebase if we are building Docker images so we have fewer issues for future devs like this one weird happened #1189 

Updated Docker section in Readme.md as well https://github.com/kodadot/nft-gallery#-docker

Use community guidelines which helps recognize using our codebase through docker as well 

https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
https://docs.docker.com/desktop/mac/install/

**Comment by yangwao** [comment]
https://github.com/vue-polkadot/apps/blob/develop/dashboard/Dockerfile
```
FROM node:16 as builder

### RUN npm install -g yarn

# RUN yarn global add http-server

WORKDIR /

### leverage docker fs cache http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/
COPY package.json .

COPY yarn.lock .

RUN yarn

COPY . .

# RUN yarn build

EXPOSE 3000
CMD ["yarn", "dev"]

**Comment by yangwao** [comment]
> https://github.com/vue-polkadot/apps/blob/develop/dashboard/Dockerfile
> 
> ```
> FROM node:16 as builder
> 
> ### RUN npm install -g yarn
> 
> # RUN yarn global add http-server
> 
> WORKDIR /
> 
> ### leverage docker fs cache http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/
> COPY package.json .
> 
> COPY yarn.lock .
> 
> RUN yarn
> 
> COPY . .
> 
> # RUN yarn build
> 
> EXPOSE 3000
> CMD ["yarn", "dev"]
> ```

This one might work, I've assembled it by my best past knowledge 😄

**Comment by roiLeo** [comment]
> This one might work, I've assembled it by my best past knowledge 😄

Didn't work for me.

#### Dockerfile
```dockerfile
# Dockerfile
FROM node:16

WORKDIR /kodadot-app

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY . .

ENV HOST 0.0.0.0
EXPOSE 3000

CMD [ "yarn", "dev" ]
```

This one finally worked for me! 🎉
