### ISSUE TITLE
Remove Subsocial from Nuxt 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1259]
remove subsocial packages and rest stuff which is connected to it 

`yarn remove @subsocial/api @subsocial/types @subsocial/utils`

![image](https://user-images.githubusercontent.com/5887929/142880875-e5015f4b-f64e-42a8-a60d-c6c7579f3fdf.png)

**Comment by vikiival** [comment]
pls observe #892

**Comment by dezine2dev** [comment]
Is there anything more that I need to do here
