### ISSUE TITLE
On-chain ID not being fetched from JSON wallet

### ISSUE THREAD

**Issue by AvaLock** [kodadot/nft-gallery#1260]
### What happened?

I had previously set an onchain identity and verified my KSM address w/a Kusama validator, but my ID "Ava Lock" is not showing up on Kodadot at [https://kodadot.xyz/rmrk/u/GHuTwhh9txr69tHBM2f1mPE6tWn9XCYKMi3nRNFrYvGv9Yy
](url).

### Please reproduce in steps

After logging in and authorizing my wallet, click on "Identity".
I get an empty form to fill in, but this has already been done in the JSON wallet.

### Expected Behavior

I've expected my verified ID to show up on both my profile and in these fields with maybe an "all done nothing to do here" message.

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

![Screen Shot 2021-11-22 at 7 40 12 AM](https://user-images.githubusercontent.com/94850986/142890802-e00bdf6f-9de0-497b-bcae-f81c28306dfa.png
![Screen Shot 2021-11-22 at 6 02 20 AM](https://user-images.githubusercontent.com/94850986/142890828-f5cc3af8-bbe4-46ec-abce-e71d46177e9f.png)
)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
It's beautiful! :)

![image](https://user-images.githubusercontent.com/5887929/163416930-02972f1f-d193-4622-b28b-fb8f56acb55e.png)
