### ISSUE TITLE
Nudge to set on-chain identity on profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1262]
- When user open their profile, show them hint they can set their identity "`[Add on-chain recognition for X](URL-to-identity-form)`" @vikiival -- what's the price for identity?  
- direct people to set up their on-chain identity https://kodadot.xyz/identity
- show costs for identity on form

![image](https://user-images.githubusercontent.com/5887929/142922576-6ea1f974-3f19-48f8-bfcd-2b02ee02a57f.png)

**Comment by vikiival** [comment]
>  what's the price for identity?

Currently Kusama locks 0.0333 KSM
