### ISSUE TITLE
Add manual what to do with $KSM bounties for developers

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1269]
Some devs are withdrawing it to fiat (awww inflation) and some don't move it that at all.

Let's prepare guide on what they can do it with it effortlessly w/o requiring much attention. 

My easiest bet if they don't want to put on decision paralysis with crowd loans, let's introduce how staking works etc and have some recommended validators in house 

### Ref
- https://guide.kusama.network/docs/learn-staking/

**Comment by yangwao** [comment]
@thea-exe would be genuinely great to navigate through this:)

let's add one-pager to our docs, and what people can do with their KSM.
You will learn and can introduce to others in DotSama ecosystem

**Comment by petersopko** [comment]
@thea-exe it would be great to help us navigate the ecosystem and for example, some general guidlines for staking would be very much appreciated

**Comment by thea-exe** [comment]
Thanks for the suggestion! I'll take on after gathering ideas and finishing up the last pages of the documentation

Other than staking, is there something else I should add for "what you can do with your KSM"? To be honest, staking and converting it to fiat only comes to mind. We can also say some jazz about putting it back into KodaDot to support other creators haha

**Comment by thea-exe** [comment]
I will take this

**Comment by petersopko** [comment]
> Thanks for the suggestion! I'll take on after gathering ideas and finishing up the last pages of the documentation
> 
> Other than staking, is there something else I should add for "what you can do with your KSM"? To be honest, staking and converting it to fiat only comes to mind. We can also say some jazz about putting it back into KodaDot to support other creators haha

I'm thinking, guide on how to turn $KSM into cash without KYC? 🚀

**Comment by petersopko** [comment]
> I will take this

not sure what happened here

**Comment by thea-exe** [comment]
Close this

**Comment by petersopko** [comment]
> Close this 

There's built in GH function to close issues by PRs, check it out, maybe add it to the contributing.md as well? 😄 works across repos https://github.blog/2013-03-18-closing-issues-across-repositories/

(Also, pls note that in order to close multiple issues, the correct format is `closes #XY, closes #XYZ` etc.)

**Comment by thea-exe** [comment]
HAHHAHAHAH THANK YOU FOR LETTING ME KNOW 😅😅
