### ISSUE TITLE
Add field to include CC types of licenses

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1283]
We would ease people.minting with some sort of licences for CC to be easier, with all respect we should add cc4.0 &c and include it into metadata under Copyright field

Can expand on this later

We can test this on minting tetrix stuff

With composable licensing, this will get bit complex. 
Metadata and on-chain data can have different license
Questions are
remix/mashups licensing etc

**Comment by JustLuuuu** [comment]
stale
