### ISSUE TITLE
Make submit buy green 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1289]
When a user clicks on BUY, do BUY.

Merge logic of button **Submit BUY** into BUY so user doesn't need to click twice.

![image](https://user-images.githubusercontent.com/5887929/143327585-9e3d5d5c-1369-454f-aed2-915e682684c5.png)

**Comment by prachi00** [comment]
@yangwao I'll do this

**Comment by vikiival** [comment]
In commit of 49a623512af2f108c778ba0a543a7c63dcec6913 , the buy logic was broken

**Comment by yangwao** [comment]
This missing on `main-nuxt`

**Comment by prachi00** [comment]
@yangwao sure, I'll do this in nuxt
