### ISSUE TITLE
Refresh history component after actions user has made

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1290]
When I do listing on my own item, it leaves me open List input after submitting transaction.

User: What's happening? Was it listed?

We should hide it once tx was submitted to not mislead people list again accidentally

![image](https://user-images.githubusercontent.com/5887929/143328104-74c8bb29-5bc3-450f-bbbd-704b577f3a7c.png)

**Comment by MubarakSULAYMAN** [comment]
@yangwao, how can I get to this page and recreate?
