### ISSUE TITLE
Add to show number of recent searches to input field

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1294]
Create component which 

- show last recent (3-5-10?) searches -- could be set in preferences #942 #1160 
- would suggest people what they would like to search -- show recent top 3 BUYs - small preview name of the collection

Inpisration from gmail
![image](https://user-images.githubusercontent.com/5887929/147355764-0b05333f-625b-49a1-8779-047ba7dc7de3.png)

**Comment by rhaicode** [comment]
I'd like to take this one

**Comment by vikiival** [comment]
Please follow good code patterns from #1308

**Comment by rhaicode** [comment]
Blocked until #1308 is resolved

**Comment by rhaicode** [comment]
I'm now resuming work for this. Does it mean I have to also work on #942  and #1160 ? @yangwao

**Comment by roiLeo** [comment]
> Blocked until #1308 is resolved

Should be good now, you can start adding stuff in store/preferences.ts

**Comment by yangwao** [comment]
#349 is probably related!

**Comment by yangwao** [comment]
@pandasamanvaya has something working on recently, if you can join forces with @rhaicode that would be amazing!

**Comment by pandasamanvaya** [comment]
I added the images and gifs to the left of each nft. It works for most of the gifs("Appul" nfts)
![Screenshot from 2021-12-18 15-54-36](https://user-images.githubusercontent.com/44033666/146637845-ddc122fc-40fb-4bf6-bfab-e6a2cdd32fa1.png)
 
But throws an error while reading animation_url of few gifs("Spaceship" nfts). So an empty image is rendered. Any ideas?
![Screenshot from 2021-12-18 16-01-08](https://user-images.githubusercontent.com/44033666/146637954-180d96c5-e49b-4f16-b09d-245afeb26bdb.png)

**Comment by pandasamanvaya** [comment]
Btw @rhaicode, if you could comment your discord handle here then we could use discord for better communication.

**Comment by yangwao** [comment]
Already done 
![image](https://user-images.githubusercontent.com/5887929/152360183-242b3bb8-435a-48f6-91a6-3f1b5f9795ac.png)
