### ISSUE TITLE
Add Twitter from on-chain Identity to NFT detail

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#13]
on-chain identity from Kusama, other chains

- show Twitter if has it an on-chain id next to author?
![image](https://user-images.githubusercontent.com/5887929/106746815-5623b000-6623-11eb-8b43-fa1d2b31bbc1.png)

**Comment by roiLeo** [comment]
Something like this ?
![Screenshot 2021-07-05 at 16-38-54 Singularity Bits #023](https://user-images.githubusercontent.com/9987732/124487932-8d071900-ddaf-11eb-9d66-b39f953bf359.png)

**Comment by yangwao** [comment]
@roiLeo I guess putting a Twitter icon would be better so people know it's twitter :)
but yeah, that's the approach I thought. 
There is some stuff done on profile tho, maybe component could be borrowed from there :)

**Comment by vikiival** [comment]
@roiLeo identity component has now event which propagate these fields
