### ISSUE TITLE
Identity module is super slow

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#130]
Identity module resolves too late :)
I'll rewrite it.

**Comment by yangwao** [comment]
better be late, like no show up 👯‍♂️

**Comment by yangwao** [comment]
Seems shortAddress filter needs to be tuned as well 

![image](https://user-images.githubusercontent.com/5887929/109650027-f3a7cc00-7b5c-11eb-9ade-956a2a4b037b.png)
![image](https://user-images.githubusercontent.com/5887929/109650045-f9051680-7b5c-11eb-86a6-ade39702ac2f.png)
