### ISSUE TITLE
Replace background asset with webp

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1300]
@xylodrone will put webp which could be used to put there as a background asset to cut on initial loading times for users. as now it takes time to show up.

# Ref 
- #1129 
- https://github.com/kodadot/nft-gallery/issues/1202

**Comment by yangwao** [comment]
Let's downgrade it to this jpeg, we will figure out later new background pic:D

![2021-11-25 18 52 32](https://user-images.githubusercontent.com/5887929/143485151-eb0ec05a-8d76-416e-bd5e-d52092b0e5b6.jpg)

**Comment by roiLeo** [comment]
closing this since we don't use background on landing page anymore
