### ISSUE TITLE
A weird organisation of the nfts in a collection

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1305]
### What happened?

![01](https://user-images.githubusercontent.com/71472224/143518046-83b74b47-fa1a-400a-885d-8f93aede26bc.png)
![02](https://user-images.githubusercontent.com/71472224/143518051-f68c1695-3e74-4352-b472-2bfad04a886e.png)
![03](https://user-images.githubusercontent.com/71472224/143518054-9d372673-a290-4b8b-add6-9e584672849a.png)
![04](https://user-images.githubusercontent.com/71472224/143518057-c430f7b9-3218-43af-846f-52702c41ee99.png)
![05](https://user-images.githubusercontent.com/71472224/143518061-e651364e-143c-4456-9f14-faa210a68465.png)

### Please reproduce in steps

https://nft.kodadot.xyz/rmrk/collection/FC77C33AB229A2056A-BTFLSUZANN

------------
its should be from 1 to 30: 
1 - 2 - 3 - 4 - 5 - 6 - 7 - 8 - 9 - 10 - 11 - 12 - 13 - 14 - 15 - 16 - 17 - 18 - 19 - 20 - 21 - 22 - 23 - 24 - 25 - 26 - 27 - 28 - 29 - 30 
but its going like this:
1 -  10 - 11 - 12 - 13 - 14 - 15 - 16 - 17 - 18 - 19 - 2 - 20 - 21 - 22 - 23 - 24 - 25 - 26 - 27 - 28 - 29 -  3 - 30 - 4 - 5 - 6 - 7 - 8 - 9 

### Expected Behavior

its should be from 1 to 30: 
1 - 2 - 3 - 4 - 5 - 6 - 7 - 8 - 9 - 10 - 11 - 12 - 13 - 14 - 15 - 16 - 17 - 18 - 19 - 20 - 21 - 22 - 23 - 24 - 25 - 26 - 27 - 28 - 29 - 30

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

/

### Relevant log output

```shell
/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
I guess it's a matter of sorting, good point! 

Let's post your address, best from kodadot.xyz/transfer and I'm happy to payout you bug report! :)

**Comment by onerawartist** [comment]
^^ 

https://kodadot.xyz/transfer/?target=JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7

**Comment by onerawartist** [comment]
forgot to mention you ^^ 
@yangwao

**Comment by vikiival** [comment]
fix is to put order by serial number

ht/ @yangwao

**Comment by onerawartist** [comment]
@yangwao when are the bounties served ? 😁👀 I started to lose count on my reports lol
I got 12 open issues

**Comment by yangwao** [comment]
> ^^
> 
> https://kodadot.xyz/transfer/?target=JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7

sent! https://kusama.subscan.io/extrinsic/0xe1ee393f84e3bc52de472a06dbb9da35b26b5510f620b88817a437c17f5a302b

**Comment by roiLeo** [comment]
Tested on /rmrk/collection/d08ff136a2fe19974d-CRAZY_CANARY order is OK
I don't know why it's happening on this particular collection.

**Comment by preschian** [comment]
> fix is to put order by serial number
> 
> ht/ @yangwao

Hi, I will try this one by adding sort by serial number
