### ISSUE TITLE
Refactoring vuex store

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1308]
- [x] change Vuex design pattern
- [ ] use constants for [mutation](https://vuex.vuejs.org/guide/mutations.html#using-constants-for-mutation-types)
- [x] refactoring to multiple [modules](https://vuex.vuejs.org/guide/modules.html#modules) file (Lang, Fiat, Preferences, Indexer)
- [ ] prepare futur [TS](https://next.vuex.vuejs.org/guide/typescript-support.html) support?
- [x] move fetchIndexer to vuex

**Comment by vikiival** [comment]
It's about time ⌛️

**Comment by yangwao** [comment]
Probably let's start working on it for `main-nuxt` now? 
Introducing new stuff to `main` would be a wasted time investment.
