### ISSUE TITLE
scaling of text in profiles

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1310]
### What happened?

when changing view from large display to small display , the name of the nft should also change 
 

### Please reproduce in steps

visit any profile and change the size 

### Expected Behavior

I've expected ...

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

![02](https://user-images.githubusercontent.com/71472224/143585384-4e37bae9-a690-44bf-bb97-df954c7e38e4.png)
![03](https://user-images.githubusercontent.com/71472224/143585395-8f26c28a-8304-4cb8-b72f-9467c20789d7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
> when changing view from large display to small display , the name of the nft should also change

I don't get it or I'm over-worked today. 
If you can be more verbose it would help me to understand what you mean.

**Comment by onerawartist** [comment]
@yangwao 
the problem is when we use the option to show the nfts in small size
the name of the artwork stays big, and that makes it impossible to read as shown in this pic 
![01_LI](https://user-images.githubusercontent.com/71472224/143618824-5f2612fe-764b-4493-90a2-5b360f02e9ab.jpg)
.
the text showing the name of the nft should also scale down

**Comment by onerawartist** [comment]
@yangwao do u understand it now ? Or should i make a draft using Photoshop? 
And  can u change the name of the issue to '' scaling of text '' ?

**Comment by yangwao** [comment]
> @yangwao do u understand it now ? Or should i make a draft using Photoshop? 
> And  can u change the name of the issue to '' scaling of text '' ? 
> 

Yeah more descriptive issue name way better.

Ah I got it. So text should be smaller on smaller layout

@roiLeo may check on that 👀

**Comment by onerawartist** [comment]
@yangwao i'm learning lol ^^

**Comment by onerawartist** [comment]
@yangwao No more bounties ? lol im no where near ''funded'' for a new laptop 😂

**Comment by onerawartist** [comment]
@yangwao this problem still exist on: https://beta.kodadot.xyz/

**Comment by roiLeo** [comment]
> @yangwao this problem still exist on: https://beta.kodadot.xyz/

This will be added soon 👍

**Comment by onerawartist** [comment]
great ^^
