### ISSUE TITLE
"Buy now" is scary , it should be " for sale " 

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1311]
### Is your feature request related to a problem?

/

### Describe the solution you would like

I would like to see

### Describe alternatives you have considered

it should be " for sale " or " available 

### Screeenshots

![04](https://user-images.githubusercontent.com/71472224/143586384-683f15ac-cffb-471b-acfd-e94e6da6a8b3.png)

**Comment by onerawartist** [comment]
even "Buy Now" looks better than "BUY NOW" , the second one looks like someone is screaming ^^

**Comment by yangwao** [comment]
> even "Buy Now" looks better than "BUY NOW" , the second one looks like someone is screaming ^^

I see. For "BUY NOW" was back then to be more straightforward and I guess it was quick hack back then. we can think about that in new UI bit #899 

For now, fix would be changed to "Buy now" 
let's make it #70b364 -- some colour which is not white closer to greyish with green pastel soul to trigger people more for buying art

**Comment by onerawartist** [comment]
@yangwao 

yes " Buy now " is better , and a pastel " Buy " is much better

**Comment by onerawartist** [comment]
![ON](https://user-images.githubusercontent.com/71472224/143619326-be891a22-a9d0-48f4-b276-149fae677add.png)
 
@yangwao 
this would great for the switch button, but in green when on , and grey when off

**Comment by yangwao** [comment]
@roiLeo asked in #1382 so let's push it to `main` and probably to `main-nuxt` as well

> **For now, fix would be**
> 
> * Change it to "Buy now"
> * let's make it `#70b364` -- some colour which is not white, closer to greyish with green pastel soul to trigger people more for buying art, close how Buy looks on actions component at item detail.
