### ISSUE TITLE
Generate payment link for transfer

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1316]
User can input their address and put the amount in dollars

In return, users can generate payment links and share them with others by clicking button

- Add button to generate this payment link and copy to clipboard

Add it probably next to USD? 
Choose icon which best represents "creating payment link"
![image](https://user-images.githubusercontent.com/5887929/143619408-bb1390e5-aab1-409c-9dad-9a8c849933de.png)

**Comment by prachi00** [comment]
@yangwao I'll try to do this

**Comment by yangwao** [comment]
> @yangwao I'll try to do this

Lfg

**Comment by vikiival** [comment]
Closed in #1329
