### ISSUE TITLE
Show on-chain identity for destination address in transfer

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1317]
Right now user could be unsure where is sending money to,
let's start showing destination address on-chain identity, show it next to the shortened address.

![image](https://user-images.githubusercontent.com/5887929/143621886-d5bad372-8ed8-41bb-9922-496e9fc8517a.png)

**Comment by jbienesdev** [comment]
Hi @yangwao . For this issue are we going to just append the on-chain identity at the end of the shortened address like this?

![image](https://user-images.githubusercontent.com/17470909/144707055-fb326f48-9e63-41a5-b0bf-cfdc94ece3ed.png)

**Comment by yangwao** [comment]
> Hi @yangwao . For this issue are we going to just append the on-chain identity at the end of the shortened address like this?
> 
> ![image](https://user-images.githubusercontent.com/17470909/144707055-fb326f48-9e63-41a5-b0bf-cfdc94ece3ed.png)

yes, this should be enough :)
