### ISSUE TITLE
 Artist Profile and UI upgrades

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1322]
### Is your feature request related to a problem?

/

### Describe the solution you would like

![what to do](https://user-images.githubusercontent.com/71472224/143660200-a4ecb19d-6761-4e31-8a70-fb2c17e3b296.png)
![simple preview](https://user-images.githubusercontent.com/71472224/143660204-c4bcfdd8-982f-4588-ba07-5bf41474e24c.png)

1 - when u put the new logo , it should be bigger 
2 - center the tabs on top 
3 - rounder corners for the language and the log in 
4 - more saturated pink for the name of the artist
5 - make the area bigger 
6 - remove this line and make four separate lines 

### Describe alternatives you have considered

/

### Screeenshots

/

**Comment by onerawartist** [comment]
![ON](https://user-images.githubusercontent.com/71472224/143660418-23b881e1-6162-4875-9b64-80263de0a451.png)

and one last thing , but i already mentioned it in the " BUY NOW is scary issue , to use this type of switch

**Comment by onerawartist** [comment]
![popup  copy](https://user-images.githubusercontent.com/71472224/143660775-5595a764-40cf-422b-b7c0-7b12632f44f4.png)
.
.
The pop up that shows when you hover the mouse over this places should show these informations :
1 - created by " the name of the artist"
2 - collections created by " the name of the artist "
3 - show only nfts available for purchase  
4 - nfts collected by " the name of the profile "
5 - previous page
6 - next page
7 - go to random page

**Comment by onerawartist** [comment]
@yangwao @vikiival 
thats all i wish to see in an artist profile

**Comment by yangwao** [comment]
> ![ON](https://user-images.githubusercontent.com/71472224/143660418-23b881e1-6162-4875-9b64-80263de0a451.png)
> 
> and one last thing , but i already mentioned it in the " BUY NOW is scary issue , to use this type of switch 

You can reference issues, hit # and type name of it :) it would help us link 🔗 together.

**Comment by yangwao** [comment]
> ![popup  copy](https://user-images.githubusercontent.com/71472224/143660775-5595a764-40cf-422b-b7c0-7b12632f44f4.png)
> .
> .
> The pop up that shows when you hover the mouse over this places should show these informations :

#1326

**Comment by yangwao** [comment]
I guess some of these were tackled? 

📟 @XyloDrone

**Comment by roiLeo** [comment]
continue in #6663
