### ISSUE TITLE
Support  for Glass material maybe ? 

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1323]
### Is your feature request related to a problem?

i wish i could put glass in my models 
and i found this article online , i didn't understand much but i loved the result and i wonder is this possible to add to kodadot
.
.
https://threejs.org/examples/#webgl_loader_gltf_transmission

### Describe the solution you would like

/

### Describe alternatives you have considered

/

### Screeenshots

/

**Comment by onerawartist** [comment]
![13](https://user-images.githubusercontent.com/71472224/143663564-80b65700-c11f-499c-aed8-8396a129b851.jpg)

this would be amazing

**Comment by onerawartist** [comment]
one more useful link:

https://tympanus.net/codrops/2021/10/27/creating-the-effect-of-transparent-glass-and-plastic-in-three-js/

**Comment by yangwao** [comment]
Hey, curious if this is still a thing? 
Maybe it's parameter to be added to model-viewer?

**Comment by onerawartist** [comment]
@yangwao yes, 3D nfts are going big, you definitely need to focus on the 3D viewer
