### ISSUE TITLE
KodaDot v3 -- Op Paperclip

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1327]
Once we finish #1060 we can continue to introduce the plugin's structure.

Probably we could join it by upgrading straight to the Vue3 and Nuxt3? What will be sooner, stable nuxt3 or our structure lol
Eta 22Q1Q2 weather might change

### Consists 
- bsx
- statemine
- xr (kodaverse)
- RMRK2
- ... (others are in my obsidian I'm not disclosing bc copycats are swimming around, cheers)

### UI kit -- should be Vue 3 ready
- CSS framework candidate https://tailwindcss.com/docs/installation
- Chakra https://chakra-ui.com/docs/getting-started
- https://www.naiveui.com/en-US/dark - has super responsive developer from ex-ByteDance, plus they do autonomous truck
- https://oruga.io

### Helpers
- https://storybook.nuxtjs.org/

**Comment by vikiival** [comment]
UI libs for Vue 3:
- Naive UI - https://www.naiveui.com/en-US/dark
- Vuestic - https://vuestic.dev/

**Comment by vikiival** [comment]
Already migrated to nuxt 3
