### ISSUE TITLE
Another NFT previews directly on the NFT page

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#1331]
### Is your feature request related to a problem?

While looking through the art in the collection, I ran into a problem.If I want to view other art in the collection I have to go back in the browser. Or click on the link with the collection :) 
![obrázok](https://user-images.githubusercontent.com/81104034/143769475-ce9e6dd8-febb-423e-b14f-f4382e91edb8.png)

### Describe the solution you would like

From a user's perspective, it would be nicer for me to have previews of other NFT's in the collection under the NFT I'm currently viewing. Something like a mini gallery.

Now:
![obrázok](https://user-images.githubusercontent.com/81104034/143769574-f9f01382-9275-41ee-912b-3112f86322b9.png)

My suggestion
![Untitled](https://user-images.githubusercontent.com/81104034/143769922-055178ed-5b86-4333-8300-a24f1e1b94c1.jpg)
:

### Describe alternatives you have considered

Description above

### Screeenshots

Description above

**Comment by yangwao** [comment]
Yes, meanwhile five months later we have
- arrow on NFT collections
- More from this collection
- Your History 

![image](https://user-images.githubusercontent.com/5887929/167295983-93dda20b-312a-42a7-91a8-3e1567f9f49c.png)
