### ISSUE TITLE
Refactor Create components

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1346]
### Is your feature request related to a problem?

Refactor CreateCollection and CreateToken Into more reusable pieces

### Describe the solution you would like

I would like to see

### Describe alternatives you have considered

I have tried this alternative

### Screeenshots

Paste your vision

**Comment by roiLeo** [comment]
I was thinking of changing "Creation" flow with [stepper component](https://buefy.org/documentation/steps/) to simplify user experience and to lighten UI.

**Comment by vikiival** [comment]
Closing in favour of #1678
