### ISSUE TITLE
i18n translations

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1347]
### What happened?

- can't change content language

### Please reproduce in steps

- Go to /rmrk/faq/ 
- Change language
- Content is not updating

### Expected Behavior

- Updating content from selected language
- see main branch for references

### Screenshots

![Screenshot 2021-11-30 at 09-59-38 KodaDot - Kusama NFT Market Explorer Low Carbon NFTs](https://user-images.githubusercontent.com/9987732/144016585-1aaf1075-8996-4c67-8ea7-e29cd72adfdc.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
Markdown link in FAQ doesn't work too. Maybe 'MarkdownIt' package isn't installed or properly configured.

**Comment by yangwao** [comment]
Is this still thing?

**Comment by roiLeo** [comment]
> Is this still thing?

YES! French language, content is not updating but navbar is.
![Screenshot 2021-12-21 at 16-05-54 nft-gallery-nuxt](https://user-images.githubusercontent.com/9987732/146952150-ebde1be8-a972-4eff-a54f-56131cdf2a2a.png)

**Comment by roiLeo** [comment]
I discovered that i18n was configured in two different places.
One on `nuxt.config.js` and the other one on `i18n.ts`
