### ISSUE TITLE
Tooltip for GIFS

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#135]
It happens that people upload GIF as animated.
It's not an issue but image is not displayed in gallery preview.

**Comment by vikiival** [comment]
Possible workaround is to chceck if animated is image :D

**Comment by yangwao** [comment]
IF metaverse incoming

**Comment by yangwao** [comment]
I guess this is solved @vikiival  ?

**Comment by vikiival** [comment]
Yeah simple mint #337 can handle it
