### ISSUE TITLE
Move meta outside of the components

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1352]
### Is your feature request related to a problem?

Meta tags are super nice to have but it generates a lot of noise in the components.

### Describe the solution you would like

I would like to see separated file in each directory like `meta.[json|js|ts]` which will handle these meta tags :)

### Describe alternatives you have considered

I have tried this alternative

### Screeenshots

Paste your vision

**Comment by yangwao** [comment]
already done iirc
