### ISSUE TITLE
New Preloader contest 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1353]
Let's come up with the **best preloader out there**, it's time to upgrade preloader for Beta.

Come up with a great storyline of preloader, **give it soul**, **make it your best craft**, which would be seen by 50k unique users/monthly, ppl on daily basis in the future using KodaDot

@XyloDrone can lead this, [I've created a coordination channel on Discord!](https://discord.gg/HSptp8evGg)

Bounty is 1KSM and fame in eternal KodaDot codebase

Current preloader when the user interacts with KodaDot
![image](https://user-images.githubusercontent.com/5887929/144057845-9f4540c5-91e8-4d2b-896b-2c4012ddc18c.png)

Post your final submissions here with Twitter URL.
You have unlimited submissions.

Submission with the most engagement on Twitter and votes from internal team will win bounty

**Comment by onerawartist** [comment]
https://user-images.githubusercontent.com/71472224/144750216-89919ff3-235f-43b9-82fa-a952cb67e8b0.mp4

@yangwao @XyloDrone can we use this ? i made it for the discord logo initially , but it will be cool here too ^^

**Comment by yangwao** [comment]
> 

This is quite big, should be something simple, however I like usage of our v2 logo. Let's try make something with kodadot logo v3 👀 

Something which has simple outlines best and works on b&w screens and is memorable and not annoying after seeing it thousand time :D

**Comment by yangwao** [comment]
has posted one really good and let's close v1 for this one for now 
https://kodadot.xyz/rmrk/gallery/10207184-F4F2348BD911773F76-TD-KODA_INFINITY_12-0000000000000012

https://discord.com/channels/840514076538830888/915236766640898119/932561004871684096

and later we can turn on another contest :)

**Comment by Dexxx3** [comment]
https://user-images.githubusercontent.com/95619333/150487972-72e545de-e7e1-4365-a634-9074b4109684.mp4

**Comment by Dexxx3** [comment]
https://user-images.githubusercontent.com/95619333/150488073-bc106b81-74f4-4e52-a6fb-54b5e952454f.mp4

**Comment by Dexxx3** [comment]
![Pixelated Gif](https://user-images.githubusercontent.com/95619333/150488705-387a7f83-712b-4dbe-a9fc-a8bce42c2e36.gif)

**Comment by Dexxx3** [comment]
![3D Smooth Gif](https://user-images.githubusercontent.com/95619333/150489077-3a8b1652-01e1-4d2c-944e-f830a74a0770.gif)

**Comment by yangwao** [comment]
We've decided with @Dexxx3 that he will take a step up the game and try to generate something more sophisticated, as his current work is in mp4 and we need more pixelated art to fit our current design. Will try use play in https://www.svgator.com/

Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x2e5107af7ad8df93ab8e66415f7ffafdb51030ca8eed4bdc9704cdc872c99b72

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Comment by Dexxx3** [comment]
Final Preloader
 Kodadot Preloader.rar
<https://drive.google.com/file/d/1pqxMJbsd9yKLQjRhEpYITF8SWTBDyTS8/view?usp=drive_web>
