### ISSUE TITLE
Reflect new logo v3 in collections preloader

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1355]
#1207 #1274 

Please crack on this as well with new logo 😄  
Either let's use previews that green one loading SVGs or new logo, just to get rid of this one as well :)
![image](https://user-images.githubusercontent.com/5887929/144071380-c6215ebf-9b7d-446b-b10f-eaad5daf5131.png)

**Comment by roiLeo** [comment]
> #1207 #1274
> 
> Please crack on this as well with new logo 😄 Either let's use previews that green one loading SVGs or new logo, just to get rid of this one as well :)

Isn't this already done? Are you refering images placeholder or page preloader?

**Comment by yangwao** [comment]
> > #1207 #1274
> > Please crack on this as well with new logo 😄 Either let's use previews that green one loading SVGs or new logo, just to get rid of this one as well :)
> 
> Isn't this already done? 

Is? 

> Are you refering images placeholder or page preloader?

Both probably! 😄

**Comment by yangwao** [comment]
> > #1207 #1274
> > Please crack on this as well with new logo 😄 Either let's use previews that green one loading SVGs or new logo, just to get rid of this one as well :)
> 
> Isn't this already done? Are you refering images placeholder or page preloader?

can't tell as let's merge recent `main-nuxt` to that branch? 

By these hard to tell for me
https://deploy-preview-1274--koda-nuxt.netlify.app/rmrk/collection/1a5eac9a904a098255-%F0%9F%A7%A6
![image](https://user-images.githubusercontent.com/5887929/144303645-c57608b6-26f8-42bf-8956-c83c86c9cf1a.png)

**Comment by roiLeo** [comment]
This has been replace with image skeleton, we can close this one
