### ISSUE TITLE
Pool on indexer health 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1356]
I know this would add load for Subquery Subquid in the future, but w/o users need to reload, let's add pooling on the health of the indexer once per minute or half a minute as users don't need to reload for example. 

![image](https://user-images.githubusercontent.com/5887929/144072351-9ff0fcd1-3b99-4dd4-b67b-e513178b829a.png)

**Comment by vikiival** [comment]
Better to have tooltip with a button thb

**Comment by yangwao** [comment]
Bump 👀 seems it's happens often everytime and now

![image](https://user-images.githubusercontent.com/5887929/144225640-cb030922-e3b4-4797-b742-559d40c0ee19.png)

**Comment by yangwao** [comment]
We've got meanwhile offline screen 
- #2645 
- #2249
