### ISSUE TITLE
Replace router link with nuxt link

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1359]
### Is your feature request related to a problem?

[What is the advantage of using nuxt-link over router-link?](https://stackoverflow.com/questions/62543010/what-is-the-advantage-of-using-nuxt-link-over-router-link)

### Describe the solution you would like

Replace router link with nuxt link as it adds a lot of cool features and hope will tackle current routing bugs

### Describe alternatives you have considered

I have tried this alternative

### Screeenshots

Paste your vision

**Comment by roiLeo** [comment]
Closed in #1350
