### ISSUE TITLE
Refactoring code outside layout

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1360]
With #1350, we need to refactor code (chainproperty, checkindexer, etc..) and move it outside layout directory as it's not first entry point.  

#### Suggestions
- We could move check Indexer to Vuex (#1308)
- Or we could create a [plug-in](https://nuxtjs.org/docs/directory-structure/plugins/#vue-plugins)
- Check Nuxt [lifecycle](https://nuxtjs.org/docs/concepts/nuxt-lifecycle/)

**Comment by yangwao** [comment]
Someone might appear @ironwebstar if so!

**Comment by ironwebstar** [comment]
@yangwao  Could you add more details in description? chainproperty, checkindexer... little confused about refactoring instruction.

**Comment by roiLeo** [comment]
> @yangwao Could you add more details in description? chainproperty, checkindexer... little confused about refactoring instruction.

The goal is to move code outside layouts file (`layouts/default.vue` for example), and use them when we actually need it.
If I'm right some of the property are used by `NavbarProfileDropdown` and `GalleryItem` components

**Comment by roiLeo** [comment]
Partially done. All that remains is to remove/move KeyboardShortcutsModal component that has been introduce in #2297
