### ISSUE TITLE
Generate payment link for transfer v2

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1361]
> > @prachi00 let's update the URL live in the address bar once I'll put the address and USD amount there :)
> 
> @yangwao @roiLeo have done the changes mentioned, you can test now, let me know if there are still any issues you see, thanks

Seems when I open https://deploy-preview-1329--nftkodadot.netlify.app/transfer?usdamount=100&target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU it won't make me able to submit the transaction

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/1329#issuecomment-983522450_

**Comment by prachi00** [comment]
checking this

**Comment by prachi00** [comment]
@yangwao @vikiival So this is happening because the value of `this.$store.getters.getCurrentKSMValue ` is undefined initially, hence it isn't calculating the ksm value and the button is disabled, any idea why it is undefined?

**Comment by vikiival** [comment]
May #1374 can fix 👀

**Comment by prachi00** [comment]
> May #1374 can fix 👀

Let's wait until that is merged then?

**Comment by prachi00** [comment]
@vikiival @yangwao is this still an issue?

**Comment by vikiival** [comment]
<img width="709" alt="Screenshot 2022-03-04 at 21 24 25" src="https://user-images.githubusercontent.com/22471030/156836458-c0e37ab5-a034-4d4e-8d01-5b2e68c6eb1e.png">

Looks Oki to me
<img src="https://trap.ltd/oki" />

**Comment by yangwao** [comment]
yes, works, made test tx https://kusama.subscan.io/extrinsic/0x13ab78b1d6976752eaec291eff508222176580e7227695dbf7a020e6c511f42f
