### ISSUE TITLE
can't unlist my NFT or consume it

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1366]
### What happened?

i was making the video for " how to create a collection , how to mint an nft" , and when i came to " how to consume an nft" 
i got this error:

here's the link to my collection:
https://nft.kodadot.xyz/rmrk/collection/FC77C33AB229A2056A-THECUBES

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

![sddsdsf](https://user-images.githubusercontent.com/71472224/144339863-cc3ed46c-fb89-42fe-9753-940df25eae4a.png)

### Relevant log output

```shell
/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onerawartist** [comment]
![fixed](https://user-images.githubusercontent.com/71472224/144344572-20862744-d491-44d2-aae3-901b34b5c998.png)


its back , i don't know what happened lol , is there a limit of time between minting and consuming ? 
maybe that what happened

**Comment by roiLeo** [comment]
> ![fixed](https://user-images.githubusercontent.com/71472224/144344572-20862744-d491-44d2-aae3-901b34b5c998.png)
> 
> its back , i don't know what happened lol , is there a limit of time between minting and consuming ? maybe that what happened

It happened because the Indexer was down. 
There is already an issue about this error, we can close this in favor of #1356.
