### ISSUE TITLE
Hide empty collection on users profile

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1367]
### What happened?

i used ( extra > Admin panel ) to consume the collection i created by mistake but its still here:

https://nft.kodadot.xyz/rmrk/collection/FC77C33AB229A2056A-THECUBE
 all the nfts in it are gone, but it is still shown in my profile

### Please reproduce in steps

/

### Expected Behavior

to not be shown in my profile

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

![admin](https://user-images.githubusercontent.com/71472224/144340458-97814265-3ec8-4c17-9e01-f4ac3f9ff4aa.png)

----

![admin 2](https://user-images.githubusercontent.com/71472224/144340484-d7288813-f722-4478-bd80-a4768ac4a991.png)

### Relevant log output

```shell
/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onerawartist** [comment]
the collection doesn't show up in ( extra > Admin panel ), but its still there in my profile when i see " collections "

**Comment by onerawartist** [comment]
when i visited my profile through singular i don't see the collection i removed using Admin panel

![singular](https://user-images.githubusercontent.com/71472224/144346372-07a0d4b5-8f05-49d1-9749-f9eb20dc1ae2.png)

**Comment by onerawartist** [comment]
@vikiival im not saying there's something wrong with admin panel, 
I created a collection , added some nfts in it 
Then i used the admin panel to consume the nfts, 
The result should be: the empty collection not showing up in my profile.
There must be a hack around , to hide collections when they become empty

**Comment by onerawartist** [comment]
I don't want all the tutorials showing up in my profile in the future.
Change the option in profiles , to only show a collection if it has an nft in it or more.
And stay invisible if its empty 
@vikiival @yangwao

**Comment by onerawartist** [comment]
![kodadot](https://user-images.githubusercontent.com/71472224/144461794-75539280-ab6e-4f26-b275-e5d6b5dccc5b.png)
![singular](https://user-images.githubusercontent.com/71472224/144461826-34d0bf65-c235-40e1-8a36-7b5c162050d8.png)

**Comment by onerawartist** [comment]
kodadot shows the empty collection, while singular don't, i really think you should add feature to kodadot

**Comment by roiLeo** [comment]
#1357 related

**Comment by onerawartist** [comment]
@yangwao  , can't we try to fix this one first , then work on #1357 . because this looks like a simple thing to do, to just hide the empty collections ?

**Comment by kkukelka** [comment]
this can only be solved on the api-level through rewriting the respective resolver for the "collectionListWithSearch" query, since graphql queries cant filter out items with empty arrays in one of their properties

<img width="772" alt="Screenshot 2021-12-05 at 18 52 12" src="https://user-images.githubusercontent.com/17953978/144757636-8ec25098-b24e-45f5-8885-10462fdcad57.png">

**Comment by vikiival** [comment]
Ref https://github.com/vikiival/magick/issues/11

**Comment by onerawartist** [comment]
@vikiival @yangwao 
can you also hide the number of the consumed nfts , from the collection statistics ? 
i removed most of the nfts , because you guys added the thumbnail option, so i burned all my nfts , and minted them again, but when the statistics are shown like that , it gives bad image to the collection and to me 
----------
![01](https://user-images.githubusercontent.com/71472224/145451308-2c621ff4-aad8-4a11-8d3f-055a393421b0.png)

**Comment by onerawartist** [comment]
Hide empty collections and hide consumed nfts from collection statistics

**Comment by onerawartist** [comment]
@vikiival @yangwao  i'm hating how my profile is looking :( , when can we get this feature ?

**Comment by yangwao** [comment]
> Hey, according to the implementation standards of [RMRK](https://github.com/rmrk-team/rmrk-spec/tree/master/standards/rmrk1.0.0) you cannot delete the collection.
> 
> > the collection doesn't show up
> 
> We do not want to show people empty collections in admin panel (as you can't do any action)

Well, you mean floating RMRK standard, yah? :D 

I mean, let's add KODA::HIDE or something like that! :) later we can evolve into zkHIDE ;D

**Comment by onerawartist** [comment]
im still waiting for this to be solved because i hate how my profile looks right now lol , its a mess.

@yangwao @vikiival @XyloDrone @kkukelka please help

**Comment by XyloDrone** [comment]
Explorer has been redesigned, profile in the works, landing page is a priority atm :)

**Comment by vikiival** [comment]
As @XyloDrone asked me if we could do that asap @roiLeo opened issue months ago

**Comment by vikiival** [comment]
So the correct answer for this issue is:

1. Rework query from SubQuery to Subsquid (made for you) 
**PLEASE NOTE THAT THIS NEW QUERY HAS TO GO UNDER `queries/rmrk/subsquid` directory.

```graphql
query collectionListByAccount($account: String!, $first: Int!, $offset: Int) {
  collectionEntities(where: {issuer_eq: $account, nfts_some: {}}, orderBy: blockNumber_DESC, limit: $first, offset: $offset) {
    ...collection
    ...collectionDetails
  }
}
```

2. change client from SubQuery to SubSquid
in `ProfileDetail.vue` **line 318** change the value to `subsquid`
3. updated `handleCollectionResult` accordingly

I heard @Jarsen136 wanted to pick that up :)

**Comment by Jarsen136** [comment]
> So the correct answer for this issue is:
> 
> 1. Rework query from SubQuery to Subsquid (made for you)
>    **PLEASE NOTE THAT THIS NEW QUERY HAS TO GO UNDER `queries/rmrk/subsquid` directory.
> 
> ```graphql
> query collectionListByAccount($account: String!, $first: Int!, $offset: Int) {
>   collectionEntities(where: {issuer_eq: $account, nfts_some: {}}, orderBy: blockNumber_DESC, limit: $first, offset: $offset) {
>     ...collection
>     ...collectionDetails
>   }
> }
> ```
> 
> 2. change client from SubQuery to SubSquid
>    in `ProfileDetail.vue` **line 318** change the value to `subsquid`
> 3. updated `handleCollectionResult` accordingly
> 
> I heard @Jarsen136 wanted to pick that up :)

Well, I will have a try later!

**Comment by Jarsen136** [comment]
> ```graphql
> query collectionListByAccount($account: String!, $first: Int!, $offset: Int) {
>   collectionEntities(where: {issuer_eq: $account, nfts_some: {}}, orderBy: blockNumber_DESC, limit: $first, offset: $offset) {
>     ...collection
>     ...collectionDetails
>   }
> }
> ```

this Subsquid seem not works well as it return all collections including the one with consumed nfts.
I think we need to do some change on `nfts_some: {}`
Could you give me some help? @vikiival 

I test it on the account: /rmrk/u/JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7?tab=collection
request payload:  
<img width="791" alt="image" src="https://user-images.githubusercontent.com/31397967/160425930-e7580b34-1479-4883-88d9-4690ffc115de.png">
responce:  
<img width="740" alt="image" src="https://user-images.githubusercontent.com/31397967/160425547-cd69f168-ab6d-4d33-b183-48f0e9039afa.png">

**Comment by vikiival** [comment]
Good catch!

```graphql
query collectionListByAccount($account: String!, $first: Int!, $offset: Int) {
  collectionEntities(where: {issuer_eq: $account, nfts_some: { burned_eq: false }}, orderBy: blockNumber_DESC, limit: $first, offset: $offset) {
    ...collection
    ...collectionDetails
  }
}
```
