### ISSUE TITLE
Public Office hours 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1371]
Probably once more people will show up, more questions they (creators, developers, architects, you name personas) will have with deeper progress we will make, we should determine some usual weekday, where we can answer questions ppl might have tho, later stage there will be more people coming around so probably they will answer the questions in peer fashion way.

I would propose a window on Friday, something after 4 pm UTC+1, on weekly basis. 
Just to be around on Discord and be helpful, when people need something to be answered.

It can open doors to wonderful new avenues.

**Comment by onerawartist** [comment]
@yangwao i agree, something like (blender today) , 

a weekly live show on youtube, here's an episode:

https://www.youtube.com/watch?v=vkFu3fbhj4I&ab_channel=Blender
.
and the questions are asked on another website: 
https://blender.community/c/today/?sorting=hot
.
he makes a post at the start of the show and try to asnwer as many question as possible each week ^^ ,
its a great way to build a community

**Comment by XyloDrone** [comment]
Might be worth doing this on Twitter spaces as the account has 12k followers? Keep it to Wednesdays? On Fridays people usually go out after work.

**Comment by yangwao** [comment]
@cryptodamsky 👀

**Comment by yangwao** [comment]
We can still do it anyways.
