### ISSUE TITLE
Bring Mono/Chromatic plugin/user preferences

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1372]
- all colours could be chosen in user preferences
  - on scale to choose
    - [color temperature](https://en.wikipedia.org/wiki/Color_temperature) -> 0 -> warmest.
    - saturation -> 0 -> Vivid (0 means grayscale) 

It will put a chromatic effect overlay on the whole KodaDot

# Ref 
- https://github.com/kodadot/nft-gallery/issues/1370
- #153

**Comment by vikiival** [comment]
Reading: [CSS filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)

**Comment by vikiival** [comment]
[BulmaCssVars](https://buefy.org/extensions/bulmacssvars)
