### ISSUE TITLE
Do we need all this polkadot stuff?

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1376]
### Is your feature request related to a problem?

> This could be a dumb question, but why do we need all this polkadot stuff? 332K for 'keyring' import it's like 3 times the size of nuxt

ht/ @ro

### Describe the solution you would like

It think we only need `@polkadot/js-api` and `extension`

### Describe alternatives you have considered

Do we need `@vue-polkadot/vue-api`? 

May check Talisman API and wrap it around

### Related

#439

**Comment by vikiival** [comment]
- [ ] Load keyring as plugin

**Comment by yangwao** [comment]
> * [ ]  Load keyring as plugin

#1327

**Comment by yangwao** [comment]
@vikiival is this resolved?

**Comment by vikiival** [comment]
Yup

7f47424972b0ffc40b830926e9aba1f42ea54e8b
