### ISSUE TITLE
Broken user menu

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#1379]
### What happened?

When the user profile is displayed, the page appears to be broken... 
Test profile: https://beta.kodadot.xyz/rmrk/u/HXAi8NoJHQUU1FQUJrHYGtAECN1upNKgPPnJMj7er1eFRK8

### Please reproduce in steps

Check UI pages

### Expected Behavior

I've expected that it loads correctly :) 

### What browsers are you seeing the problem on?

Firefox, Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz

### Screenshots

![obrázok](https://user-images.githubusercontent.com/81104034/144475120-6ff77d45-c7a5-4066-8653-c52822d48e4a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkdizajn** [comment]
> So it's on beta ?

yes

**Comment by yangwao** [comment]
#1385
