### ISSUE TITLE
Replace buy button text with yolo

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1382]
Do it for the lulz 

https://twitter.com/mattigags/status/1466444838140841987?t=sfR6Ld7NZcFefiNZY91W_g&s=19

**Comment by roiLeo** [comment]
#1311 related, what will be the final solution?

**Comment by yangwao** [comment]
> #1311 related, what will be the final solution?

Yeah let's update it with YOLO and this so we can move forward :)

> **For now, fix would be**
> 
> * Change it to "Buy now"
> * let's make it `#70b364` -- some colour which is not white, closer to greyish with green pastel soul to trigger people more for buying art, close how Buy looks on actions component at item detail.

**Comment by roiLeo** [comment]
Feel free anyone to edit this line
https://github.com/kodadot/nft-gallery/blob/a6d902cd01cf109a8524ee8ccae013c388d6fa83/langDir/en.json#L190

**Comment by yangwao** [comment]
> Feel free anyone to edit this line
> 
> https://github.com/kodadot/nft-gallery/blob/a6d902cd01cf109a8524ee8ccae013c388d6fa83/langDir/en.json#L190

Let's edit colors https://github.com/kodadot/nft-gallery/commit/5c4c2172b2a23d8e3387c2930e672b4939607af2
