### ISSUE TITLE
Found weird alien looking at me

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1385]
### What happened?

I've stared into Abyss 

### Please reproduce in steps

Opened collection,
went to next page 2

### Expected Behavior

I'm fine with interstellar civilizations

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

No

### At which address did you encounter bug?

beta.kodadot.xyz

### Screenshots

![image](https://user-images.githubusercontent.com/5887929/144604695-643aafdb-59fb-4da4-8015-221a79878944.png)

### Relevant log output

```shell
no errors in console
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
Looks like Identicon somehow renders whole gallery component

<img width="280" alt="Screenshot 2021-12-03 at 15 25 41" src="https://user-images.githubusercontent.com/22471030/144618655-d8d8d1f0-6850-4187-a7fe-9ca77f87981c.png">

CC @dezine2dev

**Comment by roiLeo** [comment]
clear browser cache.
Things that don't work for me is pagination on profile as it rewriting url:
rmrk/u?page=2

**Comment by yangwao** [comment]
okay on recent beta.kodadot.xyz it's not happening for me 
![image](https://user-images.githubusercontent.com/5887929/145598214-6d1a6ff8-2904-4329-9bbb-62491c891858.png)
