### ISSUE TITLE
White space in front of Twitter Identity

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1388]
On nuxt branch, there is a "space" between twitter icon & name.

![Screenshot 2021-12-03 at 17-04-41 nft-gallery-nuxt](https://user-images.githubusercontent.com/9987732/144634109-07d6792b-3bbe-4855-a358-edb56862b175.png)

![Capture d’écran 2021-12-03 à 5 06 29 PM](https://user-images.githubusercontent.com/9987732/144634399-21ea10e6-c9aa-48b7-9c90-64e87a595ae5.png)

**Comment by lohba** [comment]
I will fix this
