### ISSUE TITLE
Migrate indexer under kodadot 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1394]
Once we've finished Beta rolling to production, we should migrate this and update URLs as well to new org etc 

More ppl want to build around KodaDot so it would be easier for them find this under one org

### Ref
https://github.com/vikiival/magick

**Comment by vikiival** [comment]
YOLO

<img width="375" alt="Screenshot 2022-04-08 at 13 13 30" src="https://user-images.githubusercontent.com/22471030/162424910-8eb8bab8-5d1f-43ad-8d92-2903f06a8696.png">
