### ISSUE TITLE
Service to verify provenance of each NFT

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#14]
What if same artist deploy same art on KodaDot and then on niftygateway, who is true owner afterwards?

**Comment by yangwao** [comment]
So, it just happened what we've been expecting.

> Discuss content, I guess we're up to being complaint and in kodadot implement flag feature and not showing stolen art, opinions? https://t.me/rmrkimpl/1212
>  I get being permissionless but at NFT we could probably being sued as domain owners for steal - https://t.me/rmrkimpl/1213

> Thinking add mint on approval or some dao curator who will doing back check to sort of have group responsibility - https://t.me/rmrkimpl/1228

![image](https://user-images.githubusercontent.com/5887929/110202372-63250080-7e68-11eb-88d0-46b68ea58f87.png)

**Comment by aarton** [comment]
An important point of start is, when you mint something you can interact with blockchain ecosystems and claim some ownership around creation but there is another topic that doesn't fully apply or not yet, is about Intellectual property... 
Ownership is about possession but the problem also, is about moral and ethical action creators, artist, curators, and any person maybe we can start a public and inclusive chat to discuss and educate each other on this subject.

**Comment by vikiival** [comment]
Maybe use some sort of reverse image search ? 

It's like 3 LOC

**Comment by abhisar2006** [comment]
I tried a couple of Reverse Image searches.. Doesn't seem to work properly. 

I just downloaded an image off google and search results says "No Matches Found"

I only see manual checking but I don't think that's practical. Is there a method to check history via on-chain identity?
