### ISSUE TITLE
Create @kodadot/apps-config

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1405]
### Is your feature request related to a problem?

Similar to @polkadot-js/apps config we need one for KodaDot.

### Describe the solution you would like

Why so? 

now we have routes:
/rmrk - needs kusama WS
/unique - needs statemine

future
/bsx

First draft => Map<prefix, url>

### Describe alternatives you have considered

I have tried this alternative

### Screeenshots

Paste your vision

**Comment by vikiival** [comment]
WIP: 🚧 
<img width="993" alt="Screenshot 2021-12-09 at 15 24 48" src="https://user-images.githubusercontent.com/22471030/145414313-c70a9ab2-47a6-4db4-af53-621d007ae6b9.png">

**Comment by vikiival** [comment]
🏗️  Most of the work done in 

```json
{
    "@vue-polkadot/vue-settings": "0.0.38-rc.2",
}
```

**Comment by yangwao** [comment]
Is this still uptodate?

**Comment by roiLeo** [comment]
might be related with kodadot/packages#102

**Comment by vikiival** [comment]
Ref:


- kodadot/packages#110

**Comment by roiLeo** [comment]
Still relevant?
