### ISSUE TITLE
hide burned nft from stats

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1410]
We shouldn't add burned nft in stats as we don't show them anymore.

tested on:
/rmrk/collection/54eea4ff69b8f03873-8C7BN

![Screenshot 2021-12-07 at 10-37-54 nft-gallery-nuxt](https://user-images.githubusercontent.com/9987732/145004568-0544b3b5-094d-4554-9fd3-e82509c0bd9c.png)

![Screenshot 2021-12-07 at 10-38-15 nft-gallery-nuxt](https://user-images.githubusercontent.com/9987732/145004634-d56e3832-40ac-4041-92bf-aedb546a99b4.png)

**Comment by onerawartist** [comment]
this is a must
