### ISSUE TITLE
Handle non existing collection

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1413]
When I open 
https://kodadot.xyz/rmrk/collection/10352274-409E451AFD98397563-AURA3D-AURA-V-0000000000000006

Keeps loading, but users really don't know if it's an issue in internet, our bug or what's happening.

We should handle somehow that user is opening non-existing collection, item, etc.

![image](https://user-images.githubusercontent.com/5887929/145009212-a32c3888-b67b-4d31-a65a-858de80470ff.png)

**Comment by prachi00** [comment]
maybe we can handle this by routing the user to /collection if the collection doesn't exist? @yangwao
