### ISSUE TITLE
Old links doesn't work with new Nuxt

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1414]
Testing case `/rmrk/detail/10414739-a88e885b621631ab0f-888-537_OR_DECOM888-0000000000001500`

Works https://kodadot.xyz/rmrk/detail/10414739-a88e885b621631ab0f-888-537_OR_DECOM888-0000000000001500 on old version

Does not work https://main-nuxt--koda-nuxt.netlify.app/rmrk/detail/10414739-a88e885b621631ab0f-888-537_OR_DECOM888-0000000000001500

**Comment by roiLeo** [comment]
This has been replaced by:
/rmrk/gallery/{id} -> will show nft details
/rmrk/gallery -> will show nfts list

**Comment by yangwao** [comment]
> This has been replaced by: /rmrk/gallery/{id} -> will show nft details /rmrk/gallery -> will show nfts list

Oh and why? 
I mean if someone already linking to us, 
this will break old links and we want to avoid that tho.

**Comment by roiLeo** [comment]
#1459 related
