### ISSUE TITLE
Creator Twitter doesn't show on legacy version

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1416]
https://kodadot.xyz/rmrk/u/E33bfGiaTKhJ3q6F1c6WFhfaNpcu5f68E2WQLLL1vR7RiYi

![image](https://user-images.githubusercontent.com/5887929/145011928-65119e82-2ebd-4930-9ce3-445224968693.png)

Where on Beta it show's up 
https://deploy-preview-1395--koda-nuxt.netlify.app/rmrk/u/E33bfGiaTKhJ3q6F1c6WFhfaNpcu5f68E2WQLLL1vR7RiYi

![image](https://user-images.githubusercontent.com/5887929/145011975-8f629c64-543a-4fc2-9299-138313f52979.png)

**Comment by ritsuyan** [comment]
Hi, I will fix this.

**Comment by roiLeo** [comment]
> Hi, I will fix this.

This has already been fixed, it can be closed now.

**Comment by ritsuyan** [comment]
> 

Hi, I just open link above the problem still exists in both environments. please check

**Comment by ritsuyan** [comment]
> Hi, I just open link above the problem still exists in both environments. please check

**Comment by ritsuyan** [comment]
I think there are two problems in this page: 1. the creator twitter location in left bottom of the page not showing.
2.  should show the creator name not the wallet address. 
I had fix the point2.

**Comment by yangwao** [comment]
Hey as pointed sooner, this seems was connected to our old SPA I guess. 
It's seems been already fixed as on beta works for me https://beta.kodadot.xyz/rmrk/u/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd?tab=collected


To show the creator's name, creators actually need to set it up on-chain.

I guess it's showing well for me, or feel free correct me what's still wrong, otherwise can close this

**Comment by yangwao** [comment]
Continue to #2468
