### ISSUE TITLE
Add YOLO to user preference 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1417]
- replace for user Buy Now with Yolo at particular places
- in collection filter, gallery, collections etc
- Replace BUY button at item detail with Yolo

### Ref
- https://github.com/kodadot/nft-gallery/issues/1382
- #942 
- #1160 
- https://github.com/kodadot/nft-gallery/issues/1311
- https://github.com/kodadot/nft-gallery/pull/1395

**Comment by prachi00** [comment]
@yangwao I'll pick this up

**Comment by prachi00** [comment]
@yangwao About this, so the text should be replaced with YOLO right?

**Comment by yangwao** [comment]
> @yangwao About this, so the text should be replaced with YOLO right?

yes! :)
