### ISSUE TITLE
Add Vite to main so we can be at awesome-vite

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1418]
Because, why not?
![image](https://user-images.githubusercontent.com/5887929/145016855-d4a29c4a-0a1d-4471-b4c4-aee3caeb4770.png)

Seems we can use bridge right away https://v3.nuxtjs.org/getting-started/bridge/

## Ref 
- https://github.com/vitejs/awesome-vite
- https://github.com/nuxt/vite -- seems Vite is part of NuxtBridge 
- https://v3.nuxtjs.org/getting-started/bridge/

**Comment by kkukelka** [comment]
@yangwao development build is still a mess with NuxtBridge 🥲 ... i will probably give it another show once Nuxt 3 is out of beta

<img width="932" alt="Screenshot 2021-12-08 at 12 27 04" src="https://user-images.githubusercontent.com/17953978/145200946-b7ce9f2f-7f7e-456f-bcf8-c1b6887f805c.png">

**Comment by yangwao** [comment]
> @yangwao development build is still a mess with NuxtBridge 🥲 ... i will probably give it another shot once Nuxt 3 is out of beta
> 

Oh no! I guess yeah that's where we will go with #1327

**Comment by yangwao** [comment]
@kkukelka since #2653 we are powered by webpack v5 (apparently), @vikiival 🛐 believe we can use Vite now... let's give it kick to speed up development and build times? 🫣 🤞

Somehow package-cleanup could be joined w #2658 (dropping 📦 we don't need anymore)

**Comment by kkukelka** [comment]
> @kkukelka since #2653 we are powered by webpack v5 (apparently), @vikiival 🛐 believe we can use Vite now... let's give it kick to speed up development and build times? 🫣 🤞
> 
> Somehow package-cleanup could be joined w #2658 (dropping 📦 we don't need anymore)

Sure, I'll give it another try! 🚀

**Comment by yangwao** [comment]
I guess `ts-loader` could be then removed if things work out! 
https://github.com/kodadot/nft-gallery/issues/2675

**Comment by kkukelka** [comment]
@yangwao @vikiival 
actually got Nuxt Bridge working but I'm struggling with this error
<img width="1321" alt="Screenshot 2022-03-25 at 16 03 49" src="https://user-images.githubusercontent.com/17953978/160146824-730987e3-cfba-4fe0-9f76-0b3bab4c90c9.png">

already tried    
```
config.resolve.alias.vue = 'vue/dist/vue.common' //https://github.com/nuxt/nuxt.js/issues/1142#issuecomment-317272538
config.resolve.alias['vue$'] = 'vue/dist/vue.esm.js'
```
in nuxt.config

also
```
 vue: {
    config: {
      runtimeCompiler: true
    },
  },
```

also tried to define  plugin via 
```
Import Identicon from '@polkadot/vue-identicon'

Vue.component('VueIdenticon', Identicon')
```

problem seems to be template in this file https://github.com/polkadot-js/ui/blob/master/packages/vue-identicon/src/Identicon.ts

**Comment by vikiival** [comment]
@kkukelka do you have a branch somewhere ? 👀 I would love to take a look

**Comment by kkukelka** [comment]
ok somehow the error went away after reinstalling everything again.... but alot of other stuff to fix i feel like

**Comment by vikiival** [comment]
I used this https://github.com/kodadot/nft-gallery/issues/1418#issuecomment-1079212344 and works like a charm

**Comment by vikiival** [comment]
Found possible workaround if the error appears again https://github.com/vuejs/router/issues/858

**Comment by kkukelka** [comment]
> Found possible workaround if the error appears again [vuejs/router#858](https://github.com/vuejs/router/issues/858)

wow, good find. ill definitely bookmark it ⭐

**Comment by yangwao** [comment]
Small, and it counts 👉👈🥹

https://github.com/kodadot/nft-gallery/blob/main/package.json#L167

**Comment by yangwao** [comment]
we can remove webpack finally and add vite?

**Comment by roiLeo** [comment]
issue no longer relevant Nuxt3 provide vite + nitro, closing for now
