### ISSUE TITLE
Would it be better to have current nft minting fee in common file (@.common:data.KSM.fee) or something like that?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1419]
wouldn't it be better to have current nft minting fee in common file (@.common:data.KSM.fee) or something like that?

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/1399#pullrequestreview-825002527_

**Comment by kkukelka** [comment]
@yangwao this can be closed as I additionally implemented it in #1399 👍

**Comment by yangwao** [comment]
ah I see! make sense
