### ISSUE TITLE
Add preview hover card 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1422]
Like on Github, seems [hic.af](https://hic.af/o/528559) has it as well, was thinking about this a long time ago so it can help preview on a particular artist

Would be great just to prepare components for this as it will be reusable for other contextual stuff

The first implementation could carry this information about the artist
- 🕛 Time from the first mint. Like "3 months ago"
- 💸 number of collected - Bought 
- 🖌 created NFTs - Created
- 💰 Sales - Sold 

https://hic.af/o/528559
![image](https://user-images.githubusercontent.com/5887929/145024906-beaa2b45-81e1-4922-8744-ebc3dc14deae.png)

[From GoodReads](https://www.goodreads.com/choiceawards/best-science-fiction-books-2021) 

![image](https://user-images.githubusercontent.com/5887929/145383882-7a1e64c6-f8a9-4522-b8fe-a3acaeec2713.png)

### Ref
- https://github.com/kodadot/nft-gallery/issues/1421

**Comment by jbienesdev** [comment]
@yangwao 
Coded 2 sample layouts. Which one do you prefer or any suggestions you might have.

![image](https://user-images.githubusercontent.com/17470909/145053800-df4434a3-4694-4b6b-bd71-8ca6b6abff65.png)

![image](https://user-images.githubusercontent.com/17470909/145053919-ed420c5f-ae60-4458-ad19-4bcf1f9cfce3.png)

**Comment by roiLeo** [comment]
> @yangwao Coded 2 sample layouts. Which one do you prefer or any suggestions you might have.
> 
> ![image](https://user-images.githubusercontent.com/17470909/145053800-df4434a3-4694-4b6b-bd71-8ca6b6abff65.png)
> 
> ![image](https://user-images.githubusercontent.com/17470909/145053919-ed420c5f-ae60-4458-ad19-4bcf1f9cfce3.png)

I prefer the second one, would it be possible to try a version with bottom content centered?

**Comment by jbienesdev** [comment]
Yes we can do that. Here's the bottom content centered version
![image](https://user-images.githubusercontent.com/17470909/145057149-b1129407-3af1-41ce-9bc1-44adccd9b321.png)

**Comment by jbienesdev** [comment]
Hi @roiLeo @yangwao 

I used [vue-tippy](https://github.com/KABBOUCHI/vue-tippy) to handle the popover feature. All static content for now.

https://user-images.githubusercontent.com/17470909/145204025-3496cfe3-6f01-4f0d-a0e8-03af4776035e.mp4

**Comment by yangwao** [comment]
> Hi @roiLeo @yangwao
> 
> I used [vue-tippy](https://github.com/KABBOUCHI/vue-tippy) to handle the popover feature. All static content for now.
> 
>  screencast.2021-12-08.19-46-54.1.mp4

amazing, let's make PR! 

was thinking would be great instead of K logo 
we could put there identicon of the creator 
till we implement a way to show creators avatars :)

**Comment by jbienesdev** [comment]
@yangwao quick question on the PR, where should I get the information for Description, Collected, Created, Sold, and Started minting? Or will I just be hardcoding values for now for the generic component?

**Comment by jbienesdev** [comment]
Identicon has been disabled recently https://github.com/kodadot/nft-gallery/commit/36677acdd7515957d8460201949d8f90615be6b5 . Am I still going to continue using it or you have any image generators in mind.
