### ISSUE TITLE
Set default world fy_ice_world and make it fly

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1430]
- [ ] set default world - https://github.com/kodadot/nft-gallery/issues/1193
- [ ] missing navmesh @rchovatiya88 
- [ ] positioning picture frames on the map
- [ ] adding portals/teleports to the map 
- [x] place 3d models on top of island

**Comment by onerawartist** [comment]
Www.onerawartist.com
I built a business in the last 3 years haha ^^, you were there guys when it all started @vikiival @yangwao .
Lem me know if you need anything
