### ISSUE TITLE
Add roles based on their on-chain activity

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1437]
Actually this could be more part of Portcullis so it would be nice to beta test ahead.

If ppl mint and buy something through KodaDot, we can mark them in Discord as "verified" creator/buyer through Discord role so we can create special channels for them.

h/t d14 for hint!

### Ref
- https://twitter.com/spooncave_nft/status/1468291646748086282?s=20

**Comment by JustLuuuu** [comment]
we dont use discord anymore
