### ISSUE TITLE
History browsing component of user history

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1439]
Would be nice to 
- add an icon to the navbar so you can return to previously browsed NFTs
- Store it into Vuex for the last 50 NFTs?

In the popup, on the click -- fetch data from indexer? render toast to show them
- small preview of NFT
- name
- price if it's still available for sale
- X for removing it from the store
- Order it by days -- with headlines Today, yesterday, 2 days ago &c

![image](https://user-images.githubusercontent.com/5887929/145190159-19df6cc7-5f58-4b0d-b1a5-29e2d93f42c2.png)

https://user-images.githubusercontent.com/5887929/145190674-8dbb5800-ce38-4fc4-8b28-4376ed16743b.mov

### Answers

Someone has asked me where it's from, so I'm using this for modern Wikipedia https://chrome.google.com/webstore/detail/modern-design-for-wikiped/emdkdnnopdnajipoapepbeeiemahbjcn

by modernwiki.app Modern Design for Wikipedia

### Ref 
- #990 
- #1172

**Comment by kkukelka** [comment]
@yangwao I'm on it.

**Comment by yangwao** [comment]
I'm thinking, let's make it bit advanced as we do have collections.

So if someone visits collection, 
just add collection there.
If someone visits NFT from particular collection, add there collection and NFT under it.

Tricky part is how to visualize it easier there.

![Screenshot_20211211-104524.jpg](https://user-images.githubusercontent.com/5887929/145672095-5d66111e-3244-4112-81c6-2654a31e491c.jpg)
