### ISSUE TITLE
Onboarding experience v0

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1445]
We will need to work out onboarding experience. 
From freshly non-tech-savvy users you would take care for 
- making that really weird questions
- creating answers to them, if have doubts, looking after others to help you with that
- take care of creating video tutorials (English native speaker required)
- explain how to install the extension
- how to do the first mint
- how to collect stuff
- what numbers can one see in the KodaDot
- explain all views we currently have - gallery, collections, item detail, collection detail
- explain data insights we have like - series-insight, spotlight kodadot/ideas#7 kodadot/ideas#16 &c
- admin function for mass mint
- how to make a mass airdrop
- potential future functionality

Happy to extend bounty if this would be good!

**Comment by onerawartist** [comment]
@yangwao @vikiival 
https://drive.google.com/file/d/1LH2eITqR4h0dBMq3b_9ErmW8nEk3QoIf/view?usp=sharing
if you liked the video i can take this, i'm not a coder and i can share my own experience

**Comment by cryptodamsky** [comment]
Tutorial on how to create polkadot js.wallet and add it to browser.

Watchable [here](https://youtu.be/zproVh7qzxY)

I'd like to get green light and fast-forward this to KodaDot youtube channel and KodaDot wiki, for that i'll need access to both. @yangwao 

This tutorial will also be part of #2064

**Comment by yangwao** [comment]
This one is super old issue. 
Good recheck with https://hello.kodadot.xyz what is already done there.
