### ISSUE TITLE
Extend Entrance points for users

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#145]
Right now we have these entrance points
- https://nft.kodadot.xyz/
- https://nft.kodadot.xyz/rmrk/gallery
  - Search & Sort #49 #35  
  - [x] New Mints
  - [ ] Top Selection - most appreaciated
  - [ ] Featured Curations
  - [ ] Discount deals?:D
  - [ ] Categories
- https://nft.kodadot.xyz/u/Dx6nVUy6f2znn4ZwNZ3TGbEyUz3FLbCRGQGKAut4LxjCVRs
  - add links to 
  - [ ] NFTs
  - [ ] Collections
  - [ ] Packs
- https://nft.kodadot.xyz/rmrk/detail/6463071-3CD8C53D036D48B952-FYEO-FOR_YOUR_EYES_ONLY-0000000000000001
- https://nft.kodadot.xyz/rmrk/pack/0E76E3AC15B4C1FA1E-SELF-REPLICATION

**Comment by XyloDrone** [comment]
I will design this for the landing page

**Comment by yangwao** [comment]
Meanwhile added
#1115 
#876 
#1112 
#1165 
#531 

Can be connected with #899

**Comment by XyloDrone** [comment]
Cheers Ser.
