### ISSUE TITLE
Things to do before Meta Hours as speaker

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1450]
Turn of sensitivity as it breaks sound 

on OSX, go to the preference
![image](https://user-images.githubusercontent.com/5887929/145247565-b85e152c-d418-4716-b8d0-e53d2e643eeb.png)

![image](https://user-images.githubusercontent.com/5887929/145247371-28d0e4b2-eb38-4081-886b-0924403bb070.png)

![image](https://user-images.githubusercontent.com/5887929/145247399-15efa621-67ad-4e57-8a4a-b4ea505a4257.png)

**Comment by vikiival** [comment]
May add to [Wiki](https://github.com/kodadot/nft-gallery/wiki)

**Comment by yangwao** [comment]
May can go to the docs @cryptodamsky for future speaker

**Comment by cryptodamsky** [comment]
> May can go to the docs @cryptodamsky for future speaker

Yup, just seen this yesterday.

Done

https://docs.kodadot.xyz/meta_hours.html#what-to-do-before-meta-hours-as-a-speaker

**Comment by yangwao** [comment]
https://docs.kodadot.xyz/meta-hours.html#what-to-do-before-meta-hours-as-a-speaker
