### ISSUE TITLE
Add setting identity to FAQs

### ISSUE THREAD

**Issue by anettrolikova** [kodadot/nft-gallery#146]
Can we have this link in FAQs
https://guide.kusama.network/docs/en/kusama-claims#using-polkadotjs-extension-chromebrave-or-firefox

Also this one https://wiki.polkadot.network/docs/en/learn-identity and optional https://guide.kusama.network/docs/en/mirror-learn-registrar 

And maybe add a line or two why people need on- chain identity or lets create a blog post about it

**Comment by XyloDrone** [comment]
I saw we have this video turotial in Spanish. Can we link this [one](https://www.youtube.com/watch?v=mT7rUlQh660) as well, as it is in English

**Comment by yangwao** [comment]
> I saw we have this video turotial in Spanish. Can we link this [one](https://www.youtube.com/watch?v=mT7rUlQh660) as well, as it is in English

We've got meanwhile https://kodadot.xyz/identity

**Comment by XyloDrone** [comment]
Might be worth pointing out somewhere that people can set identities. Also I think we need a tutorial in english somewhere on how to create polkadot js account. I know it sounds absurd but it took me ages to figure out how to do it :D

**Comment by yangwao** [comment]
> Might be worth pointing out somewhere that people can set identities. Also I think we need a tutorial in english somewhere on how to create polkadot js account. I know it sounds absurd but it took me ages to figure out how to do it :D

Make it more native to set identity https://github.com/kodadot/nft-gallery/issues/1262

@XyloDrone let's take care of that!

**Comment by cryptodamsky** [comment]
I'm on it.

**Comment by yangwao** [comment]
> I'm on it.

👀

**Comment by roiLeo** [comment]
- closed by https://hello.kodadot.xyz/tutorial/identity-creation
