### ISSUE TITLE
Randomize quotes on preloader

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1460]
Seems when I'm hitting shuffle again I don't receive new quote 👀https://user-images.githubusercontent.com/5887929/145406405-8d38bd4f-ece5-4151-811c-34c0c01c5038.mp4

**Comment by kkukelka** [comment]
will fix it asap!

**Comment by vikiival** [comment]
@kkukelka looks like funfacts shifted css of the status 

<img width="510" alt="Screenshot 2021-12-16 at 11 50 49" src="https://user-images.githubusercontent.com/22471030/146358204-9f34fb0c-4b6f-41dc-916a-4fa0711d45b0.png">

<img width="569" alt="Screenshot 2021-12-16 at 11 07 33" src="https://user-images.githubusercontent.com/22471030/146358216-14573695-4ddc-4aa9-a447-b9a1fbc7021a.png">
