### ISSUE TITLE
remove unused compiled route

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1466]
in your project's directory navigate to this:
`.nuxt/router.js`
and you will see all avaible routes.
Some of them will never be used
![Capture d’écran 2021-12-09 à 3 48 50 PM](https://user-images.githubusercontent.com/9987732/145418331-b8a66a62-d72a-47cd-b3b6-4fcb0319f222.png)

### Suggestion
- looks like nuxt i18n is generating wrong route

**Comment by yangwao** [comment]
yes, that's bug with 700+ generated unusual routes? that could help us to cut on builds minutes!
