### ISSUE TITLE
add discord badge to readme.md

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1472]
idk how it works or where to find it :D

![image](https://user-images.githubusercontent.com/5887929/145441311-64a2c7c4-8ddd-4741-8400-98b98970b481.png)

**Comment by roiLeo** [comment]
Added in https://github.com/kodadot/nft-gallery/commit/3dc61ce67fd8f67d92f87d0286b2579913008e42

**Comment by yangwao** [comment]
yup
