### ISSUE TITLE
i cant select the text in collection description / or click on the link

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#1473]
### What happened?

i cant select the text in collection description / or click on the link
![01](https://user-images.githubusercontent.com/71472224/145452781-6a581c58-1531-474c-b15a-23d7f83b8013.png)

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

/

### Relevant log output

```shell
/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
New UI will fix this.
![Screenshot 2021-12-10 at 10-45-17 nft-gallery-nuxt](https://user-images.githubusercontent.com/9987732/145553230-1f43073e-1563-4484-af5a-c70e98ba1d8d.png)


@onerawartist fyi, if you want to display link in collection description you can use [Markdown link](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links)

**Comment by MubarakSULAYMAN** [comment]
[Fix text selection in collection description](https://github.com/kodadot/nft-gallery/pull/1621)
