### ISSUE TITLE
Set access discord bot based by roles 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1476]
To have much more streamlined community etc, we will be adding access roles based on what you are doing etc and have less channels and noise to look on.

I guess current roles we can have are
- creators - channels related to collab, creators hangout etc
- collectors - whale chat, proofing your holdings etc
- developers - ones who doing development for kodadot
- rest?

Inspired by psychadelic.ooo collective 

![telegram-cloud-photo-size-4-5881947782363854580-x](https://user-images.githubusercontent.com/5887929/145568450-41a36a93-d5a8-45c6-8e25-2bba727c1145.jpg)

**Comment by JustLuuuu** [comment]
we dont use discord anymore
