### ISSUE TITLE
Create dashboard status.kodadot

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1492]
For particular reason to be aware if we are up or not would be great to have handsome endpoints to see what's needed to have seamless working with users

### spec
We should be able monitoring endpoints and route on minute basis, hope that's enough using serverless functions

- [ ] subquery endpoint (magick)
- [ ] SubSquid endpoint (rubick)
- [ ] snek 
- [ ] unique
- [ ] Netlify edge performance points 
- [ ] Pinata
- [ ] Estuary

Then we could measure amount of time to resolve particular queries for routes
- [ ] series-insight
- [ ] spotlight
- [ ] gallery
- [ ] collection
- [ ] random item detail
- [ ] collections
- [ ] random profile artist
- [ ] other upcoming bigger query routed

### 
- [ ] Link "Status" to footer at KodaDot 

### stack
@roiLeo suggested https://github.com/juliomrqz/statusfy

probably it could be written as serverless function, we have some spare capacity on Netlify but for the reason, later it should be running outside Netlify to verify if there is everything ok

**Comment by yangwao** [comment]
This is like great candidate https://calibreapp.com/

**Comment by yangwao** [comment]
Free public status page https://www.atlassian.com/software/statuspage/pricing?tab=public

**Comment by preschian** [comment]
hello, I will try to create this status page

**Comment by preschian** [comment]
two submissions from me:

## Upptime
Repo: https://github.com/preschian/kodadot-status
URL: https://preschian.github.io/kodadot-status/

Pros:
- free, open source

Cons:
- minimum 5 minutes interval (limitation from github actions)

## Better Uptime
URL: https://kodadot.betteruptime.com/

Pros:
- can integrated with infrastructure monitoring (datadog, grafana, prometheus)

Cons:
- free version only support 10 urls

**Comment by yangwao** [comment]
I'm impressed! 

I guess thinking for the easier check we should have one list of all URLs we need to check for a client to work?

Do we have a global list of endpoints we are using? If not, let's create one and we can merge it with #1492

**Comment by yangwao** [comment]
I've noticed we should add there Estuary endpoint.
Is there anything missing from list ?

**Comment by yangwao** [comment]
> bsx & moon endpoints ?
yes for both

plus we've added nft.storage which is currently passing through workers but would be good anyway, but bet it should be stable.

**Comment by preschian** [comment]
updated remaining endpoints here https://github.com/preschian/kodadot-status/pull/97

what is the moon endpoint? I couldn't find from here https://github.com/kodadot/nft-gallery/blob/main/utils/constants.ts

**Comment by yangwao** [comment]
wow, https://preschian.github.io/kodadot-status/ beautiful! 

> what is the moon endpoint? I couldn't find from here [`main`/utils/constants.ts](https://github.com/kodadot/nft-gallery/blob/main/utils/constants.ts?rgh-link-date=2022-07-23T12%3A45%3A27Z)

https://github.com/kodadot/click

**Comment by preschian** [comment]
if we are good to go, I think it's better to move the repo under https://github.com/kodadot

I just realized og-image on vercel had a couple of downtimes in this three days
better to move [og-image repo](https://github.com/AndreyGrin/og-image) under kodadot also

<img width="2032" alt="Screen Shot 2022-07-27 at 18 00 24" src="https://user-images.githubusercontent.com/734428/181234040-9fcbe8af-f9bd-4fca-a9b8-4281aa4ca46e.png">

**Comment by yangwao** [comment]
> if we are good to go, I think it's better to move the repo under [@kodadot](https://github.com/kodadot)

let's proceed :) 

> better to move [og-image repo](https://github.com/AndreyGrin/og-image) under kodadot also

that's would be great; I can reach out to Andrey and probably would need to redeploy on vercel?

**Comment by preschian** [comment]
> let's proceed :)

ok, let me try to move the repository

> that's would be great; I can reach out to Andrey and probably would need to redeploy on vercel?

It would be great if the output of the URL were still the same

**Comment by preschian** [comment]
unable to move the repository
`You don’t have the permission to create public repositories on kodadot`

**Comment by yangwao** [comment]
handovering from Discord from Vik

```
Hey @Contributing Developer,
I just released a small API to check if our indexers are running. 

Currently it has just two routes:
- /list - get list of all indexers
- /status/:id - status of the indexer

the API is awailable on the route https://squiki.kodadot.workers.dev/

Example
to get a status of rubick just call:
https://squiki.kodadot.workers.dev/status/rubick

I hope it can help you to debug things :pepemeow: 
```

**Comment by preschian** [comment]
> Example
> to get a status of rubick just call:
> https://squiki.kodadot.workers.dev/status/rubick

hooo, I like that endpoint status 👍

hhmm, for next, how to update that endpoint automatically in the status repo 🤔

**Comment by vikiival** [comment]
We have uptime
