### ISSUE TITLE
Make Mass Airdrop function More Vissible 

### ISSUE THREAD

**Issue by XyloDrone** [kodadot/nft-gallery#1495]
### Is your feature request related to a problem?

This function is currently listed under "advance settings". This terminolgy is a bit intimidating and does not imply that the mass airdrop function is hidden within it. This should be more obvious. 

### Describe the solution you would like

I would like to see: "Multiple Airdrop" option pop up below the the editions setting once the user inputs this. 

### Describe alternatives you have considered

TBC with design 

### Screeenshots

<img width="651" alt="Screenshot 2021-12-11 at 16 15 44" src="https://user-images.githubusercontent.com/84407059/145683664-a5e00a01-adc4-4f34-9a40-37655c067b1e.png">

**Comment by yangwao** [comment]
Well, when the user goes for multiple airdrops, the intent is clear before, so having some dedicated view would be way easier and more narrow for ppl to drive stuff plus we could make way to make it addressable, i.e. have ready made link where one just pass parameters to URL and can smash the button mint way easier so every fields would be pre-made!

**Comment by XyloDrone** [comment]
Agreed!

**Comment by JustLuuuu** [comment]
no need
