### ISSUE TITLE
Total sales dashboard

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1496]
I will need show up in daily market sales on RMRK for reason

Best would be, take what we have on series insights columns and spotlight columns and squash them into one view like total overall

Mind showing there when was snapshot taken, this query could be potentially huge over time.

Combining with other dataviews would be imminent

Graph could be on top of https://github.com/kodadot/nft-gallery/issues/1818 on same page

**Comment by vikiival** [comment]
https://colab.research.google.com/drive/1XExu4LqnRn1TVEjEl6zk860epQuPkows?usp=sharing

**Comment by vikiival** [comment]
```json
{
  "data": {
    "collections": {
      "totalCount": 4380
    },
    "tokens": {
      "totalCount": 89884
    }
  }
}
```

**Comment by vikiival** [comment]
[Rubick playground](https://app.gc.subsquid.io/beta/rubick/005/graphql)

```graphql
query MyQuery {
  collections: collectionEntitiesConnection(orderBy: version_ASC) {
    total: totalCount
  }
  nfts: nftEntitiesConnection(orderBy:createdAt_ASC) {
    total: totalCount
  }
}
```

current result

```json
{
  "data": {
    "collections": {
      "total": 5778
    },
    "nfts": {
      "total": 177694
    }
  }
}
```

**Comment by vikiival** [comment]
Via SubQuery

```graphql
query MyQuery {
  nfts: nFTEntities {
    aggregates {
      unique: distinctCount {
        creator: issuer
        owner: currentOwner
      }
    }
  }
}
```

current result

```json
{
  "data": {
    "nfts": {
      "aggregates": {
        "unique": {
          "creator": "2107",
          "owner": "29004"
        }
      }
    }
  }
}
```

**Comment by KngZhi** [comment]
@vikiival do you think we should write a resolver inside sales-feed for this issue?

**Comment by vikiival** [comment]
> @vikiival do you think we should write a resolver inside sales-feed for this issue?

There should be a new entity for that IMO

**Comment by KngZhi** [comment]
> > @vikiival do you think we should write a resolver inside sales-feed for this issue?
> 
> 
> 
> There should be a new entity for that IMO
> 
> 

New entity! I like it. New field to do.
