### ISSUE TITLE
3D marketplace

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1497]
### Is your feature request related to a problem?

It would be nice to setup 3d only marketplace

### Describe the solution you would like

--

### Describe alternatives you have considered

--

### Screeenshots

 vision by @yangwao

**Comment by yangwao** [comment]
Having 3d.kodadot.xyz just showing 3d objects or in other way have something dedicated URL tho.

Definitely, something we can front-run into #1327 with ease into plugins to demo our dog flooding ability

**Comment by onerawartist** [comment]
i would like that, but i don't know about using a different link for it 
it should be shown in the tabs on top, next to gallery and collections

**Comment by prury** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/36627808/0626dce3-eb3c-4637-86d7-25bfddb88c48)
![image](https://github.com/kodadot/nft-gallery/assets/36627808/ca14da3f-1dff-4f9f-9db7-299ae86f96f5)
