### ISSUE TITLE
History browsing v2

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1499]
Continue from 
- https://github.com/kodadot/nft-gallery/issues/1439
- https://github.com/kodadot/nft-gallery/pull/1488 (once merged)

### Spec
- crack how to show videos and 3d objects in the history component
- show items that are still only for buy (be smart here, but keep them in history if users is off, meanwhile new owner put them on sale again so it should persist probably)
- https://github.com/kodadot/nft-gallery/issues/1493
- sort it as per collections, [described here](https://github.com/kodadot/nft-gallery/issues/1439#issuecomment-991578791)

![image](https://user-images.githubusercontent.com/5887929/145712871-d91fa3ca-dce8-45bd-8df3-8056e557ac63.png)

**Comment by yangwao** [comment]
Probably we can sort it on scrolling per day as modern Wikipedia has it 👀

https://user-images.githubusercontent.com/5887929/145805472-1882cd48-22b9-4912-8660-18cba0d289e8.mov

**Comment by roiLeo** [comment]
I don't know if this is the expected behavior but while using History browsing I found that we don't save/show video media, for exemple: 
- /rmrk/detail/10512872-1455048def8aac1e30-6ZO0S-SNOW_GLOBE_2-0000000000000202
- /rmrk/detail/10507958-7e982817a2d2575031-ZWXW0-KUSAMA_BIRD_COLOURFULLMOOD28-0000000000000110

**Comment by yangwao** [comment]
> I don't know if this is the expected behavior but while using History browsing I found that we don't save/show video media, for exemple:
> 
> * /rmrk/detail/10512872-1455048def8aac1e30-6ZO0S-SNOW_GLOBE_2-0000000000000202
> * /rmrk/detail/10507958-7e982817a2d2575031-ZWXW0-KUSAMA_BIRD_COLOURFULLMOOD28-0000000000000110

True, I was about to mention it into PR but noted it just in my brain, not the external world. 

Probably we don't have previews for video media so that one would be tricky until we find a way to add "frame" from videos by the user or automatically. 

Could be done for history v3 😄
