### ISSUE TITLE
Fill up more test cases to our testsuite 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1503]
We would be looking for more real-world events to test new UI and features of KodaDot
Make PR against TESTSUITE.md with 
URL to 
- kodadot.xyz 
- beta.kodadot.xyz
- bulk `rmrk/...`

### Profile
- lot of interaction per profile means 
  - lot of created art - 3 entries
  - lot of sold art - 3 entries
  - lot of collected art  - 3 entries

### Collection
- lot of buy events
- lot of list events per collection
- with lot of burns

### Lot of interactions per NFT
- lot of buys per NFT
- lot of LISTSs per NFT 
- lot of SEND

### SVG NFTS
- more SVG nfts with animations 

### Ref
[https://github.com/kodadot/nft-gallery/blob/main/TESTSUITE.md]()

**Comment by onerawartist** [comment]
@yangwao i don't understand , should i repport more ?

**Comment by onerawartist** [comment]
@vikiival @yangwao ??

**Comment by rchovatiya88** [comment]
@onerawartist https://medium.com/@ronchoqa/how-to-write-test-cases-to-improve-software-quality-f0c05c99ee3c

**Comment by roiLeo** [comment]
continue #7826
