### ISSUE TITLE
Language translation v2

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1506]
We should revamp pushing ppl to help us to translate KodaDot.

- check where we miss translations to en.json
- prepare onboarding videos on how to translate @cryptodamsky could help us on this probably!
- #1891 -- set bounties for translation 
- make a shout out

**Comment by roiLeo** [comment]
It might be time to look at #2 to simplify contribution for non-developers

**Comment by yangwao** [comment]
> It might be time to look at #2 to simplify contribution for non-developers

Yes, good point. Yet, contributors will loose attribution I guess? 👀

**Comment by yangwao** [comment]
Chatted with @cryptodamsky and we should upgrade our guide.
Old version could be found here https://github.com/kodadot/nft-gallery/tree/main/src/locales

**Comment by yangwao** [comment]
We should have also prepared a way when someone is making a new language and how to be added to this list 

![image](https://user-images.githubusercontent.com/5887929/148068462-691588d3-b5f0-469e-ba8a-9c2ac7751a41.png)

**Comment by cryptodamsky** [comment]
The updated and actual version of the tutorial is running at: https://docs.kodadot.xyz/tutorials/language-translations.html#conditions
