### ISSUE TITLE
Next and previous chevrons on NFT item detail 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1508]
To keep easy continuous browsing experience, show user chevrons and keyboard shortcuts if there are more NFTs for a particular collection or particular artist

### Spec
- show user chevrons on hover
- When the user opens NFT which is part of a bigger collection where is 1+ NFT, offer on gallery item detail right and left chevron on hover
- Add keyboard shortcuts, on keys left and right.
- prefetch two next and one previous NFT 
- Make it as a component.

### Demo
Make them a square background as the full-screen button has.

Left 
![image](https://user-images.githubusercontent.com/5887929/145806341-ad6a324b-fee3-4c90-be6e-5f198042f96c.png)

Right
![image](https://user-images.githubusercontent.com/5887929/145806083-c8523b88-bc6e-4c61-8eb4-f23c3468da25.png)

**Comment by kkukelka** [comment]
on it!
