### ISSUE TITLE
The bottom border and persistence on history browser after action

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1509]
- Could be joined together with #1499 
- When I don't have anything in history, probably hide the button at all? 
https://github.com/kodadot/nft-gallery/pull/1488#issuecomment-992373361

- the bottom border should be fixed? 
![image](https://user-images.githubusercontent.com/5887929/145805716-ae904a05-ad35-4c23-9afe-69a5f26ba222.png)

- I would preserve dialog once remove button is clicked as user might want to remove more than one from browsing history, like 2-3 and don't want to open dialog each time.

https://user-images.githubusercontent.com/5887929/145807133-f646dab0-5d8b-44eb-9a31-76c2064be451.mov

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/pull/1488#issuecomment-992389018_

**Comment by kkukelka** [comment]
On it. Sorry about the weird headline issue if nothing is in history.
