### ISSUE TITLE
Reimplement Service worker and cache 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1510]
I've just had an occasion where toast came, clicked X, fetched a new version and collection links on collections view stopped working... then I opened a new window for beta.kodadot.xyz and their collections have worked.

Not sure what witchcraft is here, but I sense that service worker, pwa, cache reload doesn't work as intended should be.
It's quite hard to test out stuff but just raising awareness that we have this kind of glitches here and there and that's bit no go for production.

**Comment by roiLeo** [comment]
is it still relevant?
<img width="926" alt="Capture d’écran 2021-12-27 à 10 21 51 AM" src="https://user-images.githubusercontent.com/9987732/147456886-a2077e7b-5944-40de-9cc1-14f009bdb702.png">

**Comment by yangwao** [comment]
Continue to #2237
