### ISSUE TITLE
Wrong minting dates at hover card 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1511]
I strongly sense there are wrong times on hover cards 
@jbienesdev 👀

This author has something which was made way weeks ago https://beta.kodadot.xyz/rmrk/u/J9cppW5x7akmWG6yTiEMHy5Cx8VVZ9YTQKV3AGfABvFXrFN

Also please recheck other numbers as well:)

![image](https://user-images.githubusercontent.com/5887929/145812039-fa2433ec-6037-4d98-a7c0-1a5e9337b00f.png)

**Comment by jbienesdev** [comment]
Sure! Will take a look on this
