### ISSUE TITLE
Prefetch query on hover from preview card

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1512]
Once the user hovers with a card on artists or collection, 
Let **do prefetch of data** as there is a high probability it will click there.

This could significantly improve UX and performance while browsing

### Ref
- #1422 
- #1474

**Comment by Phantom20320** [comment]
Hello!
I started working on this issue.

**Comment by MubarakSULAYMAN** [comment]
@Phantom20320, are you still working on it?

**Comment by yangwao** [comment]
I guess hover cards are super quick now.
