### ISSUE TITLE
KodaTree minimal reference data snapshot

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1517]
We are playing with the idea of having a static snapshot to probably avoid cases of what's happening due #1513 and this could unpack at the client way faster than handling each network per se, using IPFS addressing system for this. 

It would be needed in cases like if user visits collection, we can have linked all NFT in that collections, so what happens you can get everything.

At some point, SubSquid might help solve this but still adds one round-trip per request and hence static immutable NFTs won't change much this static mapping could be faster on clients locally.  

The purpose of the tree would be super-charge fetching data about items, collections &c as for binary items we would have #1515

**Comment by vikiival** [comment]
Prob already solved by stellate
