### ISSUE TITLE
Create video tutorial how to create mints

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#152]
- [ ] how to create collection
- [ ] how to create token
- [ ] how to create 1-1 token
- [ ] how to operate with actions

**Comment by XyloDrone** [comment]
Happy to do this once draft preview has been deployed.

**Comment by yangwao** [comment]
forwarded to Alejandro if we have all of this

**Comment by XyloDrone** [comment]
Do we have this in English ?

**Comment by vikiival** [comment]
> Do we have this in English ?

Lady Xylo,
we do not possess the english version of this video

**Comment by XyloDrone** [comment]
I shall ask One Raw Artist if he is up for it. What's the bounty?

**Comment by onerawartist** [comment]
i can work on it in my next mint, if the bounty is good ^^ 
@yangwao

**Comment by yangwao** [comment]
> I shall ask One Raw Artist if he is up for it. What's the bounty?

it's great, up to $300

**Comment by onerawartist** [comment]
@yangwao i'm working on it ^^

**Comment by onerawartist** [comment]
@vikiival @yangwao , i finished it
 DM me so i send you the link to check it out

**Comment by onerawartist** [comment]
@yangwao i sent the link of the video to @vikiival

**Comment by onerawartist** [comment]
@XyloDrone @yangwao @vikiival 
.
https://drive.google.com/drive/folders/1zr1KpjQKlBXRPipvOa02tZyesLgH4bWR?usp=sharing

**Comment by yangwao** [comment]
I guess we fairly got this covered in https://docs.kodadot.xyz ? :)
If so, we can close this
📟 @cryptodamsky
