### ISSUE TITLE
Update template-typescript-w-decorator.vue to use nuxt

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1522]
- We will need to update .vscode/vetur/snippetstemplate-typescript-w-decorator.vue to 
```js
import { Vue } from 'nuxt-property-decorator'
```

**Comment by arcadioramos** [comment]
Is juts to update those import lines? If so I would like to work on it

**Comment by yangwao** [comment]
@arcadioramos sure let's do it
