### ISSUE TITLE
Gaming dashboard - Traits oriented

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1526]
We should catch the upcoming blockchain gaming wave by preparing a gaming interface for uploading NFT with various traits
- add an interface to mint in-game items and virtual worlds 
- add #1162 #1357 #903 #349 #348 
- dedicated interface where you could see traits on NFTs

I'll expand more later. If you want to work on this issue, feel free highlight me in war-room

How it works on Statemine now
![telegram-cloud-photo-size-4-5895361931596904257-y](https://user-images.githubusercontent.com/5887929/146184564-2b04d0ad-1991-41bf-94db-4ed2f5dc61b0.jpg)

### Ref
- #575 
- #417 
- #738

**Comment by JustLuuuu** [comment]
not fopcused on gaming anymore
