### ISSUE TITLE
Unify translations

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1527]
### Is your feature request related to a problem?

So far we do not have any normal structure in translations

### Describe the solution you would like

I would like to see unified translations

```json
{
  "mint": {
    "collection": {},
    "token": {},
    "general": {}
  }
}
```

### Describe alternatives you have considered

I have tried this alternative

### Screeenshots

Paste your vision

**Comment by yangwao** [comment]
Translation is not that worth

**Comment by vikiival** [comment]
> Translation is not that worth

Good task for LLM imo
