### ISSUE TITLE
Update social media cards 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1529]
- Collections - https://beta.kodadot.xyz/rmrk/collections
![image](https://user-images.githubusercontent.com/5887929/146190002-1f05eb72-8ff1-471c-b517-ee52590dd607.png)

- Spotlight - https://beta.kodadot.xyz/spotlight
![image](https://user-images.githubusercontent.com/5887929/146190032-6de6f26f-2ec2-4380-a0a7-931830538973.png)

- Gallery feed - https://beta.kodadot.xyz/rmrk/gallery
![image](https://user-images.githubusercontent.com/5887929/146190058-0c5a57cc-0fdf-4972-a61d-7ea969c3bbf0.png)

- on all Create dialogs - https://beta.kodadot.xyz/rmrk/create - https://beta.kodadot.xyz/rmrk/mint
![image](https://user-images.githubusercontent.com/5887929/146190103-3d74ab94-f433-4b87-9b13-f819529f0762.png)

- Series Insights - https://beta.kodadot.xyz/series-insight
![image](https://user-images.githubusercontent.com/5887929/146190132-3762da76-a60a-4f21-9372-3632b9702c3f.png)

- Default elsewhere, like at / &c
![image](https://user-images.githubusercontent.com/5887929/146190164-59e0e8b9-e406-44e0-8f30-089f0ab67590.png)
 
### Ref
#1612

**Comment by codiini** [comment]
hi @yangwao I'd like to take this up

**Comment by yangwao** [comment]
> hi @yangwao I'd like to take this up

Any progress so far?

**Comment by vikiival** [comment]
<img width="455" alt="Screenshot 2022-01-02 at 15 49 40" src="https://user-images.githubusercontent.com/22471030/147879574-0ba842f2-dc0e-479d-adef-1ab5b98b9d11.png">
there was update with new logos

**Comment by yangwao** [comment]
But, why it doesn't work then? 

![image](https://user-images.githubusercontent.com/5887929/147879595-58cc8f69-6f58-4890-9897-9163e28c3b97.png)

**Comment by yangwao** [comment]
Seems like / giving me old one still https://beta.kodadot.xyz/

![image](https://user-images.githubusercontent.com/5887929/147879623-3153422d-0ab8-4b18-9522-c909b1592c85.png)

**Comment by yangwao** [comment]
Okay seems it's not changed as relative path at https://beta.kodadot.xyz/
![image](https://user-images.githubusercontent.com/5887929/147879689-1ddcf941-2bf1-4745-bfe3-dfd1cbdaf37b.png)

**Comment by yangwao** [comment]
Seems doesn't work at all 
![image](https://user-images.githubusercontent.com/5887929/147879855-398b8514-98e6-425d-ba51-21dd788bd9ff.png)

![image](https://user-images.githubusercontent.com/5887929/147879860-306cb071-89e7-4351-b0f0-6bfdfa522dbd.png)

**Comment by roiLeo** [comment]
we've got weird glitch with nuxt seo something is missing or not working on beta. I'll keep looking.

**Comment by yangwao** [comment]
> we've got weird glitch with nuxt seo something is missing or not working on beta. I'll keep looking.

I've noticed there is build error on https://github.com/kodadot/nft-gallery/pull/1660 https://app.netlify.com/sites/koda-nuxt/deploys/61d1e498cc22870007bada1c

**Comment by yangwao** [comment]
With some magic potion, our `nuxt generate` doesn't copy files over during generate event

![image](https://user-images.githubusercontent.com/5887929/147940074-f1528bf3-1359-4c73-9897-c64758530dbb.png)

**Comment by yangwao** [comment]
okay where to go from here https://deploy-preview-1676--koda-nuxt.netlify.app/_nuxt/img/kodadot_card_root.64aab32.png

**Comment by yangwao** [comment]
mm 
![image](https://user-images.githubusercontent.com/5887929/147946337-cf161de3-a54e-470a-ad2c-a076f8f14882.png)
