### ISSUE TITLE
New preloader on NFTs item details

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1530]
We've passed @jkdizajn new kodadot v3 so we can update it new SVG preloader with https://github.com/kodadot/kodadot-presskit/tree/main/v3 and close on #1216  #1274

**Comment by skwsccss** [comment]
how to create branch here to create new PR
@yangwao

**Comment by jkdizajn** [comment]
Can JSON also be used? I converted SVG graphics to JSON using LottieFiles. 
Here is the result:
[https://lottiefiles.com/web-player?lottie_url=https%3A%2F%2Fassets10.lottiefiles.com%2Fpackages%2Flf20_vlz0oz9b.json](url)
and here is gif:
![kodadot_preloader_gif](https://user-images.githubusercontent.com/81104034/146239625-a02a3259-b78e-44df-8126-402b7c07aa94.gif)
@yangwao @skwsccss

**Comment by jkdizajn** [comment]
Version 2 (animated SVG)

https://user-images.githubusercontent.com/81104034/146267596-0dbbd792-79c9-4d63-a74a-101ac872d975.mp4
