### ISSUE TITLE
Invalid component name

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1533]
### What happened?

```
[Vue warn]: Invalid component name: "pages/rmrk/gallery/index.vue". Component names should conform to valid custom element name in html5 specification.
```

### Please reproduce in steps

Open any component name under `index.vue` or `_id.vue`

### Expected Behavior

to fix:

extend Component with `@Component` from ` 'nuxt-property-decorator'`
and pass the name inside

Example:
```ts
import { Component, Vue } from 'nuxt-property-decorator'

@Component({ name: 'GalleryPage' })
export default class GalleryPage extends Vue {
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codiini** [comment]
Hi @vikiival can I take this up?

**Comment by vikiival** [comment]
Rise and shine :) @codiini

**Comment by codiini** [comment]
@vikiival I've created a PR for this, please check it out and let me know. Thanks
