### ISSUE TITLE
New template for social media cards 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1541]
@XyloDrone has an idea to draft a new "template", 
ill then it would be perfect to replace it with a new logo for the template so we can reflect new logo everywhere:)

Let's use this one as a new logo in the upper right corner https://github.com/kodadot/kodadot-presskit/blob/main/v3/K_outline_logo.png
Paging 📟 @AndriiHrynchuk

**Comment by AndriiHrynchuk** [comment]
Hey @yangwao, just deployed updated version with new logo

**Comment by XyloDrone** [comment]
Here are the design suggestions: https://www.figma.com/file/Pq0mMRkwcUCjFtVBFXnQ0Q/KodaDot%2FMetaPrime-Share-cards?node-id=0%3A1

We can either go for the square or landscape version. Besides having the logo and the price I'd remove everything from the card, as there is no point in having the name/author in the image when it is in the card itself. 

Previous image from #1017 
 
<img width="362" alt="140609661-821d7770-aeab-49a9-8eb9-09e21b4d3874" src="https://user-images.githubusercontent.com/84407059/146425983-05f8a071-fa0c-49ab-ae58-3ea65935417b.png">

**Comment by AndriiHrynchuk** [comment]
ok, new template has logo in left corner and no one in top right. Do we go fully for new template @yangwao ? @XyloDrone could I export new logo in svg from Figma?

**Comment by XyloDrone** [comment]
You can grab the logo here(svgs are in zip folders)
https://github.com/kodadot/kodadot-presskit/issues/16#issuecomment-994914580

**Comment by AndreyGrin** [comment]
just updated design @yangwao

**Comment by AndreyGrin** [comment]
hey, @yangwao! Does all good with the design update?

**Comment by roiLeo** [comment]
Closing this one, design has been update so far continue to #4143
