### ISSUE TITLE
KodaDot ambassador program

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#155]
We could establish this governance part for kodadot nft gallery as rewarding ambasadorship to growing community efforts and be deeply community owned platform. 
Each ambassador should have custom link to bring new artists or collectors on board

### Ref
- #1722 
- #2040

**Comment by XyloDrone** [comment]
Do we have some kind of form for this or doc?

**Comment by yangwao** [comment]
Continue to
- #2040 

Meanwhile, @cryptodamsky made 
https://docs.kodadot.xyz/ambassador-program/ambassador-intro#the-opportunity
