### ISSUE TITLE
Move most of stuff from / to some utils folder or where it fits best

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1559]
Let's move most of the stuff files which don't have strong requirements to be in / somewhere else so users visit our "frontpage" readme.md doesn't need to scroll through like Eiffel tower 
![](https://media.giphy.com/media/mNz7UVEEoZOxy/giphy.gif)

TIL https://en.wikipedia.org/wiki/Gustave_Eiffel
https://en.wikipedia.org/wiki/Eiffel_Tower

current status
![image](https://user-images.githubusercontent.com/5887929/146547505-1e536f8b-8d13-4466-b842-c8bee468369c.png)

**Comment by yangwao** [comment]
this could be merged with something else https://github.com/kodadot/nft-gallery/blob/main-nuxt/TESTING.md

**Comment by yangwao** [comment]
testsuite could be relocated as well https://github.com/kodadot/nft-gallery/blob/main-nuxt/TESTSUITE.md

**Comment by roiLeo** [comment]
We could remove travis config file too, I don't think it's used right now

**Comment by prachi00** [comment]
@yangwao I'll try to do this cleanup
