### ISSUE TITLE
Infinite scrolling on demand 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1582]
I sense that purpose of this is you don't lose context when you are scrolling back wherewith pagination you do.

This is a chief issue.

### Spec
- Make a component that adds infinite scrolling on demand on any view we have right now
- apply on collection view #1411  as well
- mobile compatible
- future compatible
- [ ] explorer
- [ ] `collection/id`
- [x] collections #2781 

### Demo
[you can try here](https://www.alza.sk/luxusne-najdrahsie-sluchadla-do-usi/18859903.htm#f&cst=null&cud=0&pg=1-4&pn=2&prod=&sc=10968)

https://user-images.githubusercontent.com/5887929/147076759-2cac8473-9149-41e2-ba19-f9d864d73b7a.mov

**Comment by roiLeo** [comment]
related with #1411

**Comment by yangwao** [comment]
> related with #1411

True! I Like we think along! 😄 Marking this as chief (parent) and other as worker issue
Edited main description

**Comment by vikiival** [comment]
Need to hack addressable pagination for infinite scroll

**Comment by Jarsen136** [comment]
as https://github.com/kodadot/nft-gallery/issues/2650#issuecomment-1085850592
I will have a try.
