### ISSUE TITLE
Hide prices from UI

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1585]
Part of user preference issue 
#942 #1581 

Hide prices at gallery view (by default?)
Collection view &c

**Comment by prachi00** [comment]
@yangwao I'll try to do this

**Comment by yangwao** [comment]
Let's try! I'm plan to do following issue after merging recent PR creating user preference screen @kkukelka and it could be easily done :)

**Comment by prachi00** [comment]
@yangwao hiding prices in gallery and collection view should be different checkbox options or combined in one in user preferences?

**Comment by yangwao** [comment]
> @yangwao hiding prices in gallery and collection view should be different checkbox options or combined in one in user preferences?

Probably could be one for now for easier way to do
