### ISSUE TITLE
Migrate pictures from Pinata to CDN

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1594]
We will be migrating pictures from Pinata for faster UX to Cloudflare Images/R2 or Netlify Large media

It's prior research how to do it best but I guess we already got written scrapper by @vikiival 

https://github.com/kodadot/nft-gallery/pull/1576#discussion_r774384969

**Comment by vikiival** [comment]
https://github.com/kodadot/cloudflare-jpeg

**Comment by vikiival** [comment]
https://github.com/kodadot/rubick/issues/25
