### ISSUE TITLE
Add custom discord widget to landing page

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1596]
Yeah, I'd quote someone, 
> it's like you have a basic flat and you put Versace chair into the room.

Here starts the idea to have a better discord widget so people could easier find us!
### Spec 
- fits design of our page 
- logo / users / online users / join button
- @ins0mn1a will sketch something! 

### Ref 
- [Discord API](https://discord.com/developers/docs/resources/guild#list-guild-members)
- https://github.com/sveenxx/discord-widget
- https://devbest.com/threads/custom-discord-widget.92305/
- [![KodaDot NFT Discord](https://badgen.net/discord/members/35hzy2dXXh)](https://discord.gg/35hzy2dXXh)
- [![KodaDot NFT Discord](https://badgen.net/discord/online-members/35hzy2dXXh)](https://discord.gg/35hzy2dXXh)

We will avoid a lot of small unnecessary requests tho! 
![image](https://user-images.githubusercontent.com/5887929/147880901-dfc57010-e371-4f94-acaa-cc44b51d8fe7.png)

**Comment by atharva3010** [comment]
I can do this. I'll need the guild `id` of the server to be able to fetch data relevant to the discord server, can you please provide me with that?
The steps to find the guild id is:

> In Discord, open your User Settings by clicking the Settings Cog next to your user name on the bottom.
> Go to Appearance and enable Developer Mode under the Advanced section, then close User Settings.
> Open your Discord server, right-click on the server name, then select Copy ID
> Paste the Server ID on your text editor for later
> If desired, you can disable Developer Mode now.

The API call that we'll use is: `GET/guilds/{guild.id}/preview`
https://discord.com/developers/docs/resources/guild#get-guild-preview

**Comment by yangwao** [comment]
I guess it's this one? 
`840514076538830888`

seems matching with widget https://github.com/kodadot/nft-gallery/blob/main/components/landing/Landing.vue#L72

**Comment by yangwao** [comment]
@atharva3010 any progress on this?
