### ISSUE TITLE
Create user profiles signup smooth experience with magic

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#16]
Go with flow https://magic.link/pricing
Explore if we can store some private bytes

**Comment by yangwao** [comment]
Actually, they made it through! :) https://medium.com/fortmatic/fortmatic-is-now-magic-reinventing-identity-for-a-more-secure-and-authentic-web-4c6a1608ddcb

**Comment by yangwao** [comment]
https://docs.magic.link/blockchains/polkadot

**Comment by yangwao** [comment]
Shh https://twitter.com/magic_labs/status/1366833277403754499

**Comment by yangwao** [comment]
https://magic.link/posts/magic-vue can't be real

**Comment by vikiival** [comment]
https://github.com/magiclabs/magic-js/issues/188

**Comment by abhisar2006** [comment]
Best to close this for now. As we are using the Polkadot JS extension for user login. 

At a later stage, we can have a sign-up and login form, we can verify users with their KSM Addresses.

**Comment by yangwao** [comment]
Magic is for interaction w/o PolkadotJS and it lifts out having installing extension for user :)

**Comment by vikiival** [comment]
![image](https://github.com/user-attachments/assets/40411817-9215-41f3-bbb2-b664a9f5b62d)
