### ISSUE TITLE
Replace magic wand with dice

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1602]
Seems when I google "random", more dices appears than magic wands, so it would be way more recognized what it does for now

![image](https://user-images.githubusercontent.com/5887929/147406565-697d2dc9-f363-4458-934f-54b12b66dff1.png)

**Comment by vikiival** [comment]
Choose your dice

<img width="1232" alt="Screenshot 2021-12-26 at 12 51 47" src="https://user-images.githubusercontent.com/22471030/147407132-c00566fa-ff28-48b2-a522-d7a714fec4a9.png">
