### ISSUE TITLE
Change background colour for loader

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1603]
Once facts are over some white background, it's quite invisible to eye.
Maybe adding some border with slight grey background to white can stand out?

![image](https://user-images.githubusercontent.com/5887929/147407069-4e82c3e3-f2f6-48e2-b0b8-33a0cf234673.png)

**Comment by vikiival** [comment]
```scss
$loading-background: rgba(255,255,255,0.5);
$loading-background-legacy: #7f7f7f;
```

Source: [Buefy Docs](https://buefy.org/documentation/loading#variables-view)

**Comment by lohba** [comment]
I'll take a look

**Comment by prachi00** [comment]
![Uploading Screenshot 2021-12-26 at 6.26.40 PM.png…]()
@vikiival @yangwao something like this?

**Comment by yangwao** [comment]
> <img alt="Screenshot 2021-12-26 at 6 27 14 PM" width="1433" src="https://user-images.githubusercontent.com/39299315/147408781-ea8c6e27-2e61-4446-a23e-7459d48e1d03.png">
> 
> @vikiival @yangwao something like this?
> 
> also the buefy background variable didn't work, as it gave the background to the whole screen

Maybe bit bigger and it might work! 
Is it mobile friendly?

**Comment by prachi00** [comment]
> > <img alt="Screenshot 2021-12-26 at 6 27 14 PM" width="1433" src="https://user-images.githubusercontent.com/39299315/147408781-ea8c6e27-2e61-4446-a23e-7459d48e1d03.png">
> > @vikiival @yangwao something like this?
> > also the buefy background variable didn't work, as it gave the background to the whole screen
> 
> Maybe bit bigger and it might work! Is it mobile friendly?

@yangwao I'll check

**Comment by vikiival** [comment]
> also the buefy background variable didn't work, as it gave the background to the whole screen

yup I would make the whole loading darker
