### ISSUE TITLE
Change price of your NFTs under one collection

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1606]
Mass adjust the price in your collection, i.e. set a new LIST price

### Spec
- select which NFTs, with preview + name
- select ALL
- add price per selected NFT 
- add price for whole selected NFTs together

![image](https://user-images.githubusercontent.com/5887929/147411734-3c316d8c-5fbe-4e9d-ba4c-11305d2ad147.png)

**Comment by chandradot99** [comment]
@yangwao I can pick this issue, need to clarify two things
1. Do we have some designs for this, or I can add any UI for this according to me.
2. What are the API's for updating single selected NFT price or whole selected NFTs together.

**Comment by roiLeo** [comment]
🤔 
- #6941
