### ISSUE TITLE
Share to instagram -> Share to Facebook

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#161]
Maybe instagram has some URI, would be nice to add button to share is as insta story?

**Comment by BrightReach** [comment]
I'd like to give that a go. Whereabouts would you like implement the feature? How do you want it to work?

**Comment by yangwao** [comment]
Well, we want to be generally complaint with sharing to Instagram, thus I guess now it works as posting it as story or post?

**Comment by JKrupinski** [comment]
Looks like it possible only for Android/iOS
https://developers.facebook.com/docs/instagram/sharing-to-feed
https://developers.facebook.com/docs/instagram/sharing-to-stories

I didn't find anything which can help share data to instagram from a web page

**Comment by yangwao** [comment]
Oh probably we can pass on this if it's hard to no-near to make it :)

Or probably choose other popular social network, maybe facebook would be good?

**Comment by yangwao** [comment]
it's there 
![image](https://user-images.githubusercontent.com/5887929/115385479-7a316f00-a1d8-11eb-83ea-28b12d5afa8a.png)

Closing
