### ISSUE TITLE
font-style is not loaded correctly

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1611]
#### Browser
- Google Chrome OSX Version 96.0.4664.110
- It happened on Windows too
- 🆗 on Safari
- 🆗 on Firefox

<img width="1366" alt="Capture d’écran 2021-12-27 à 10 25 09 AM" src="https://user-images.githubusercontent.com/9987732/147457172-6694d914-5edd-4ac7-b649-1da07cdc2f8b.png">

**Comment by yangwao** [comment]
Wait, how did it happen you have an old logo? What URL is that?
Can you recheck on https://beta.kodadot.xyz?

**Comment by roiLeo** [comment]
> Wait, how did it happen you have an old logo? What URL is that? Can you recheck on https://beta.kodadot.xyz?

Same as before
![Capture d’écran 2022-01-04 à 11 34 54 AM](https://user-images.githubusercontent.com/9987732/148046416-3e5f5f1d-06e2-4930-af56-c32bea856bd0.png)

**Comment by yangwao** [comment]
Version 96.0.4664.110 (Official Build) (arm64)
OSX 12.1 (21C52)

Have you tried disabled plugins or incognito? Or a new profile in chrome?

![image](https://user-images.githubusercontent.com/5887929/148065213-02ddb99c-6ff6-42cc-888e-4d98de9a0b50.png)

**Comment by roiLeo** [comment]
> Version 96.0.4664.110 (Official Build) (arm64) OSX 12.1 (21C52)
> 
> Have you tried disabled plugins or incognito? Or a new profile in chrome?

Tried all these suggestions, still same.
After inspecting code, "Fira code" font is never loaded it's been replaced by monospace.
[This](https://nuxtjs.org/docs/directory-structure/assets/#fonts) could help to setup font.

**Comment by yangwao** [comment]
> > Version 96.0.4664.110 (Official Build) (arm64) OSX 12.1 (21C52)
> > Have you tried disabled plugins or incognito? Or a new profile in chrome?
> 
> Tried all these suggestions, still same. After inspecting code, "Fira code" font is never loaded it's been replaced by monospace. [This](https://nuxtjs.org/docs/directory-structure/assets/#fonts) could help to setup font.

let's try tho! 
But still weird it wfm! :D
