### ISSUE TITLE
Tracking issue for Beta

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1612]
There are some diffs between prod and beta

If you find a difference please drop the screenshot and url

- [x] #1633
- [x] #1683
- [x] #1684
- [x] #1687

**Comment by roiLeo** [comment]
`/rmrl/collection/{id}`

#### Prod
![Screenshot 2021-12-27 at 11-19-39 Crypto Parrots](https://user-images.githubusercontent.com/9987732/147462251-3ec477f8-14e4-431b-bef1-ff464647fc39.png)

#### Beta
![Screenshot 2021-12-27 at 11-19-31 nft-gallery-nuxt](https://user-images.githubusercontent.com/9987732/147462276-d4c81f3a-6da7-4284-9672-46b4d918baa2.png)

**Comment by yangwao** [comment]
> `/rmrk/collection/{id}`
> 
> #### Prod
> ![Screenshot 2021-12-27 at 11-19-39 Crypto Parrots](https://user-images.githubusercontent.com/9987732/147462251-3ec477f8-14e4-431b-bef1-ff464647fc39.png)
> 
> #### Beta
> ![Screenshot 2021-12-27 at 11-19-31 nft-gallery-nuxt](https://user-images.githubusercontent.com/9987732/147462276-d4c81f3a-6da7-4284-9672-46b4d918baa2.png)
> 
> #### //TODO: beta
> * default collapse description
> * card column size
> * BUY now button is not v-centered

#1633

**Comment by yangwao** [comment]
Found that 
- #1289 is no on beta yet

**Comment by vikiival** [comment]
- [ ] Search is missing on the collection page

Original:

![Screenshot 2022-01-04 at 09 10 50](https://user-images.githubusercontent.com/22471030/148028696-48af75f3-18e3-4fa5-841b-3bd5d320f631.png)

Beta:

<img width="1428" alt="Screenshot 2022-01-04 at 09 11 40" src="https://user-images.githubusercontent.com/22471030/148028726-9f3c07e7-cff9-4b84-8616-924657e6a1dc.png">

**Comment by vikiival** [comment]
- [ ] Identicon is gone

Original:
![Screenshot 2022-01-04 at 09 17 29](https://user-images.githubusercontent.com/22471030/148029485-f866f2c0-3295-49db-aac8-13d8b09de74b.png)

Beta:

<img width="675" alt="Screenshot 2022-01-04 at 09 18 16" src="https://user-images.githubusercontent.com/22471030/148029511-30609c26-6419-4aa8-ad1a-b2ae2c9132e2.png">

**Comment by vikiival** [comment]
Yaay we made this batch!

<img src="https://http.cat/100" />

**Comment by yangwao** [comment]
Anything missing to be done?
