### ISSUE TITLE
Mobile/ipad friendly collection view

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1613]
Probably one-col less on the filter, one less on search filter and it should be okay? Or if we can make it somehow more "flexible" like with Flexbox? 

![image](https://user-images.githubusercontent.com/5887929/147476172-a140dd76-49d8-4947-8fb3-e46c6a37fd15.png)

**Comment by prachi00** [comment]
<img width="418" alt="Screenshot 2021-12-27 at 7 20 46 PM" src="https://user-images.githubusercontent.com/39299315/147477956-342a12bb-8e87-45e5-9591-f6e315cb7f72.png">

@yangwao currently it is like this, so it is already kind of responsive right?

**Comment by roiLeo** [comment]
I was thinking about setting a fixed width of 200px on select component.
We could reduce the size of the searchBar too.

**Comment by prachi00** [comment]
Okay I'll see what I can do

**Comment by yangwao** [comment]
continue to #1793
