### ISSUE TITLE
Routing bug on collection tab at artist profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1618]
When you click on cube collection, should open collection, not item

https://beta.kodadot.xyz/rmrk/u/J7V9kPDfTHtoHiPV3izmtfBiVBk1JTn97tsdQJ8g4qhnH3z?tab=collection you should land here https://beta.kodadot.xyz/rmrk/collection/F4F2348BD911773F76-DC 

Try legacy here https://kodadot.xyz/rmrk/u/J7V9kPDfTHtoHiPV3izmtfBiVBk1JTn97tsdQJ8g4qhnH3z?tab=collection will land you here https://kodadot.xyz/rmrk/collection/F4F2348BD911773F76-DC

**Comment by kkukelka** [comment]
on it!
