### ISSUE TITLE
Portcullis beta enroll

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1627]
We would like to start collecting Discord servers, where we can provide our NFT gating solution provided by the KodaDot grassroots, using RMRK and KODA NFTs on Kusama and further NFTs on Metaprime, Statemine, MoonRiver, Muralis, Basilisk &c

Name your 
- Discord - what's the subject of your Discord 
- size - total number of members / avg online
- Post infinite Discord invite
- Admin/Founder handle on Discord
- why do you want to be in beta
- DM @yangwao for next steps & coordination with link to your comment

**Comment by Framsynt** [comment]
Anon Society
- Exclusive NFT riddle game
- Incubated in 0xVentures
- Small server, we are in the planning phase
- https://discord.gg/bE3PeRSPDP
- Founder: Framsynt
- We want to work with KodaDot. Due to nature of our game, we need discord fencing to allow user cooperation to progress the game.

**Comment by JustLuuuu** [comment]
we dont use discord anymore
