### ISSUE TITLE
Merge preloader component for transactions with facts preloader

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1632]
Is there a possibility to merge these two into one component?

Like till user waits for confirmation it can read that fact and we have their attention tho till then, rather than looking on "2/3"

![image](https://user-images.githubusercontent.com/5887929/147653105-0bf63760-aaee-465a-b935-4c19a3d53a5c.png)

**Comment by kkukelka** [comment]
huh, doesn't it use the same `<Loader />` component?

**Comment by yangwao** [comment]
I think this is already being done
