### ISSUE TITLE
2 columns seems gone on artits and collection, can we please have them back 😇 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1633]
Seems 2 column view on artists and collection is gone 

https://beta.kodadot.xyz/rmrk/u/DoND1kMSH5rSMW1wsqmfRAD4JYBAbXYzD7bvZYhqsaaVXZQ?tab=nft
![image](https://user-images.githubusercontent.com/5887929/147654265-a8208518-cf61-4031-9432-bc2ece127f91.png)

**Comment by vikiival** [comment]
#1688
