### ISSUE TITLE
imgcmp.yml github workflow

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1634]
Currently we have imgcmp workflow that keep getting errors when pushing on `main-nuxt` branch 
Here's the log:
![Screenshot 2021-12-29 at 12-57-17 Merge pull request #1624 from prachi00 feat-user-pref-hide-price · kodadot nft-gallery 18](https://user-images.githubusercontent.com/9987732/147659837-78ae7f34-431c-4b1d-8209-0c288765769c.png)

Looks like he doesn't have the writing access/rights to open a PR on the project

**Comment by yangwao** [comment]
oh I've seen something on contributing network graph and was scratching why it's forking but never merging, not it exaplins all

**Comment by atharva3010** [comment]
I can figure this out, I’d need to pair with some who has admin rights to this repository though, need to see GitHub permissions.

**Comment by yangwao** [comment]
not using it anymore I guess
