### ISSUE TITLE
Add ability to change colours in user preference

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1638]
Let's add fields where users can change colours in settings

Plus pls revert to previous colours 😄

![image](https://user-images.githubusercontent.com/5887929/147748818-2386c648-59e7-4a36-aafc-0723ec034dba.png)

**Comment by roiLeo** [comment]
alpha value for primary color is really bad :/
i've changed light text (silver color) for something more "clean" (#f8f4f6), it was used on .active class

**Comment by prachi00** [comment]
so you mean user can change these 3 variables from settings?

**Comment by vikiival** [comment]
Closing for #3134
