### ISSUE TITLE
New preloader for item detail 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1639]
I recall we have around a new svg for preloading by @jkdizajn ?
Referring to #1612 

![image](https://user-images.githubusercontent.com/5887929/147749609-a019bc22-23ee-4374-b073-0a3da970f5bc.png)

**Comment by prachi00** [comment]
I'll check this

**Comment by jkdizajn** [comment]
> I recall we have around a new svg for preloading by @jkdizajn ? Referring to #1612
> 
> ![image](https://user-images.githubusercontent.com/5887929/147749609-a019bc22-23ee-4374-b073-0a3da970f5bc.png)

Yes, here: https://github.com/kodadot/nft-gallery/issues/1530

**Comment by jkdizajn** [comment]
Here is
https://github.com/jkdizajn/kodadot-presskit/blob/main/KODADOT_preloader_2_animated.svg
https://github.com/jkdizajn/kodadot-presskit/blob/main/KODADOT_preloader_2_pink_animated.svg

**Comment by prachi00** [comment]
@yangwao so which one are we suppose to use, I see there are two?

**Comment by XyloDrone** [comment]
@jkdizajn Could I ask you to change the font into a filled one instead of outline, please? Also, can it be Fira Code for consistency across the site? Great work on the loader btw:) 
@prachi00 Let's wait for @yangwao to confirm, but in our last conversation we agreed on the pink version to maintain color consistency.

**Comment by jkdizajn** [comment]
> @jkdizajn Could I ask you to change the font into a filled one instead of outline, please? Also, can it be Fira Code for consistency across the site? Great work on the loader btw:) @prachi00 Let's wait for @yangwao to confirm, but in our last conversation we agreed on the pink version to maintain color consistency.

Here it is modified, I haven't learned how to animate the filled objects yet, so the slogan and logo remain static. 

If you need it in green, just message me :) 
https://github.com/jkdizajn/kodadot-presskit/blob/main/JKdizajn/30.12.21_KODADOT_preloader_2_pink_animated.svg

**Comment by XyloDrone** [comment]
Thank you ser, very much appreciated 

> > @jkdizajn Could I ask you to change the font into a filled one instead of outline, please? Also, can it be Fira Code for consistency across the site? Great work on the loader btw:) @prachi00 Let's wait for @yangwao to confirm, but in our last conversation we agreed on the pink version to maintain color consistency.
> 
> Here it is modified, I haven't learned how to animate the filled objects yet, so the slogan and logo remain static.
> 
> If you need it in green, just message me :) https://github.com/jkdizajn/kodadot-presskit/blob/main/JKdizajn/30.12.21_KODADOT_preloader_2_pink_animated.svg

**Comment by yangwao** [comment]
> I'll check this

sure let's put new one up

This has really gratified me, issues are starting working! )
