### ISSUE TITLE
Draft NFT 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#164]
Artists want to prepare mints ahead of release thus save drafts
will mint it later
it could be as premium storage as we need to cover storage till it's minted
May be related to #207

**Comment by XyloDrone** [comment]
If possible let's implement this asap so we can do minting tutorials: 

![Screenshot 2021-05-19 at 00 01 10](https://user-images.githubusercontent.com/84407059/118733995-5859f500-b835-11eb-9c89-dd844610d8a8.png)

**Comment by yangwao** [comment]
Go to #419
