### ISSUE TITLE
new event "unlist" in History

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1640]
tested on:
`/rmrk/gallery/10403656-daf9e25824d4bd9357-DAO-CLIFFORD-0000000000000001`

on singular:
![Screenshot 2021-12-30 at 13-47-05 Singular Kusama-native NFTs #RMRK #NFT](https://user-images.githubusercontent.com/9987732/147753252-7198632e-256c-4d2f-96c9-8f5d3deff759.png)

on kodadot:
![Screenshot 2021-12-30 at 13-46-33 nft-gallery-nuxt](https://user-images.githubusercontent.com/9987732/147753223-9a624029-945f-4e71-aae3-b76e9f674851.png)

**Comment by yangwao** [comment]
I guess delist is list with 0 or it just should disappear from feeds and not be discoverable at all? cc @vikiival 

I guess it's like when you put on youtube private listing accessible only with link?

**Comment by vikiival** [comment]
Yeah @yangwao is correct.

**Comment by yangwao** [comment]
> Yeah @yangwao is correct. 
> 
> 

Actually, what if we could make koda:: private to have nft collection hidden in zk way, like you would need some secret to found path to ipfs hash and metadata.

Ipfs is quite big search space to easy hide in the ☁️☁️☁️

**Comment by roiLeo** [comment]
Same thing happened on: 
`/rmrk/gallery/8682218-4a87d67106c2d9c06e-EG3QW-HOPE_-0000000000000005`
in history we can see `LIST` event at price 0
