### ISSUE TITLE
New pwa icon seems doesn't work

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1650]
Seems doesn't offer new icon 👀 from #1647

@kkukelka any idea 💡 why it doesn't work 🤔

https://user-images.githubusercontent.com/5887929/147846330-36bcb6be-dd51-44d3-ba9d-9b060728721e.mp4

**Comment by kkukelka** [comment]
@yangwao Whoops, error on my end. #1651 should fix it, let me know if it still causes issues.
