### ISSUE TITLE
Wider items in feeds

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1652]
Seems we have narrow preview on feeds
#1612

### spec
Fix it where items are narrow, i.e gallery, collections, artists profile (all tabs incl), collection detail 

### doc
Comparing on beta

![Screenshot_20220101-093439.jpg](https://user-images.githubusercontent.com/5887929/147847057-01167cce-7e4b-46d3-90e1-f304b6021353.jpg)

Vs on legacy

![Screenshot_20220101-093411.jpg](https://user-images.githubusercontent.com/5887929/147847060-a112263d-892c-40c8-9226-b37c5e8f27a9.jpg)

**Comment by prachi00** [comment]
@yangwao I'll check this
