### ISSUE TITLE
Review beta vs legacy on new features

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1654]
To briefly introduce what we've been actually working on the beta would be really nice if somebody could like take part and go from old legacy version since October and see what was actually added since October November and December till now and best if linked with the all issues which should have been merged and closed

Format should be like medium article which will be published on our KodaDot medium.

Article should be written as for end user and non tech saving people who doesn't understand what are nfts

Length of the article should be at least three to five pages with screenshots and lots of explanation with pictures are description per features what's are value add in KodaDot comparing to other nft explorers

**Comment by kkukelka** [comment]
@yangwao I'm on it. Just a few question before I start:

1. Should the article be written in markdown (like as a `.md` file?)
2. Should the issues be linked in the article itself? Or is it just a reference for you in order to double-check, if everything has been closed accordingly?
3. Who can I talk to regarding editing & proof-reading purposes?

**Comment by yangwao** [comment]
> @yangwao I'm on it. Just a few question before I start:
> 
> 1. Should the article be written in markdown (like as a `.md` file?)

Let's make it a medium post, share a draft link and once ready, you can submit it to https://medium.com/kodadot publication.

> 2. Should the issues be linked in the article itself? Or is it just a reference for you in order to double-check, if everything has been closed accordingly?

yes. every links should be best related for reader... or.. I'm thinking to keep "graph" as whole, would be nice to create one parent/chef issue to link all stuff there so we can have references. Even just open and close issue, for evidence whatosver, something like "milestone" issue in retrospect.

> 3. Who can I talk to regarding editing & proof-reading purposes?

@XyloDrone is good for proof reading I guess! :)

**Comment by kkukelka** [comment]
@yangwao @XyloDrone 
Link to article draft:
https://medium.com/@kilian.kukelka/road-to-kodadot-v3-recapping-the-last-chapter-of-2021-9709fb4f3ee7

**Comment by yangwao** [comment]
It's published https://medium.com/kodadot/road-to-kodadot-v2-recapping-the-last-chapter-of-2021-9709fb4f3ee7

Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0xdf8dbbb1fbecbf03ed0be47cf9e40117bacb69b142004ce40925a2b8629e7887

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/
