### ISSUE TITLE
Search input suggestion and history seems broken/gone

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1655]
I recall we had working search suggestions?  https://github.com/kodadot/nft-gallery/pull/1576

you can try it here https://deploy-preview-1576--koda-nuxt.netlify.app/rmrk/gallery?page=2196 search for "kusama" for example

![image](https://user-images.githubusercontent.com/5887929/147859764-4155587c-b5f2-45b7-bb91-d36354a705d3.png)

Search is broken as well https://beta.kodadot.xyz/rmrk/gallery/?search=kusama&page=10

### Ref 
- #1612

**Comment by pandasamanvaya** [comment]
Hmm, I noticed something strange. If you are on the 10th page of a search and search for something new, you go to the 10th page of the latest search result. Happens for collection as well. 

Gallery
----------
https://user-images.githubusercontent.com/44033666/150073410-1060e63d-208b-4206-9bac-deac78d3dd5e.mp4

Collections
---------------
https://user-images.githubusercontent.com/44033666/150073443-b03afc96-26a1-4838-8d69-6c3f1fbac25d.mp4

**Comment by yangwao** [comment]
> Hmm, I noticed something strange. If you are on the 10th page of a search and search for something new, you go to the 10th page of the latest search result. Happens for collection as well.

I've added bug-hunt 🏷, nothing more I can do it rn. 
If you would love to crack on that, let's go, bounty is there! :)

**Comment by Jarsen136** [comment]
hi, I will fix this bug!

**Comment by yangwao** [comment]
Partially this issue was fixed, suggestions are working

<img width="536" alt="image" src="https://user-images.githubusercontent.com/5887929/157034317-cc726551-347e-4534-b0b5-1b0ae3172743.png">
