### ISSUE TITLE
Sync model-viewer properties from legacy

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1656]
Seems we are missing some properties from legacy 

Objects are not moving
https://beta.kodadot.xyz/rmrk/gallery/10780126-900D19DC7D3C444E4C-AVATARSH-METAPRIME_GIRL_RUMBA-0000000000000004

The object is moving https://nft.kodadot.xyz/rmrk/detail/10780126-900D19DC7D3C444E4C-AVATARSH-METAPRIME_GIRL_RUMBA-0000000000000004

### Ref
#1612

**Comment by kkukelka** [comment]
on it!
