### ISSUE TITLE
Clear out errors from manifest.json

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1657]
Seems we've got some errors

![image](https://user-images.githubusercontent.com/5887929/147878838-f7e6bd30-1dcb-43d4-8b3c-aa3de1b98bee.png)

![image](https://user-images.githubusercontent.com/5887929/147879071-ea9b043e-f62b-4a47-8fea-714842993240.png)

![image](https://user-images.githubusercontent.com/5887929/147879096-449eba2d-529e-4465-b70b-a766ef4f0581.png)

too much glitches in this desert cake

**Comment by kkukelka** [comment]
on it
