### ISSUE TITLE
Fix Queries for #1662

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1663]
Currently, the queries in #1662 can't process some data

Spotlight:
- [x] Volume
- [x] Unique collectors 
- [x] Sold?

Series:
- [x] Volume
- [ ] #1680
- [x] floor
- [x] buys

**Comment by yangwao** [comment]
Sorting doesn't work.

**Comment by yangwao** [comment]
On mobile spotlight is somehow taking a while to load, it was over 60s, whereas on desktop is super fast. Any idea? 

Can someone test it on mobile?

**Comment by vikiival** [comment]
5sec for me
