### ISSUE TITLE
Can not mint on beta

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1664]
### What happened?

When I click "create" it sends me to create collection by default, I think it should be the other way arounda 

### Please reproduce in steps

https://beta.kodadot.xyz/rmrk/create

### Expected Behavior

Mint stuff

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz

### Screenshots

![image](https://user-images.githubusercontent.com/5887929/147887907-1997aa67-a08f-4346-8614-cf3c3b065709.png)
![image](https://user-images.githubusercontent.com/5887929/147887964-df07e894-2526-4907-ba2f-09320c662816.png)

### Relevant log output

Thank to ClownWorldHouse !

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
Should be fine now since redeploy.
API seems to be working

**Comment by yangwao** [comment]
meanwhile working
