### ISSUE TITLE
Seems I've lost my browsing history

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1668]
I haven't emptied cache on https://beta.kodadot.xyz for specific reason to see which stuff glitches, but seems my history was wiped.

Any idea why could be like that?

Maybe @kkukelka would know 👀
![image](https://user-images.githubusercontent.com/5887929/147918270-a56ea664-ee06-40ee-931a-f228861c3ad0.png)

Proof of past history in my window 👀

https://user-images.githubusercontent.com/5887929/147918388-1b0ee4ae-1c4e-4cc1-b8d8-bd0b83c4338f.mov

Remember, we can always blame it on cosmic rays.

**Comment by kkukelka** [comment]
@yangwao didn't you clear application cache for beta yesterday because of the pwa icon issue? this would also have cleared localstorage

**Comment by yangwao** [comment]
Hmmmm, okay will observe it later, when this happens again, probably reopen for investigation. Thanks for the hint! :)
