### ISSUE TITLE
Remove glowing effect from everywhere

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1669]
Remove background glowing from cards

![image](https://user-images.githubusercontent.com/5887929/147917797-873491be-e2d8-4baa-9ea0-d44fbd1b31cc.png)

![image](https://user-images.githubusercontent.com/5887929/147918495-7237958b-fe3b-4c98-8d75-3c7647a61a25.png)

![image](https://user-images.githubusercontent.com/5887929/147918506-ebcc64b0-5066-4963-b5c8-0321b807d567.png)

![image](https://user-images.githubusercontent.com/5887929/147918527-ba3a769c-e1b5-4e30-b034-cdb88a0b4c36.png)

**Comment by prachi00** [comment]
@yangwao I'll do this
