### ISSUE TITLE
Speed up loads for gallery

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#167]
We are now have issues with quite big assets and distributed network IPFS, takes time to load and ruins impression. 

Ways to solve it 
- [x] add pagination, i.e. show first 3-6-9 arts https://buefy.org/documentation/pagination
- [ ] thumbs nails - adds complexity and storage costs for us or minters - worst scenario 
- [ ] on the fly downsize through cloudflare/cloudinary

**Comment by vikiival** [comment]
or not; maybe using [Cloudinary](https://cloudinary.com/pricing) would do the trick

**Comment by yangwao** [comment]
Writing it now, we've made around 21G since 21/2 by Netlify, not accounting Pinata, which could be much larger I guess.
![image](https://user-images.githubusercontent.com/5887929/110774466-20936780-825e-11eb-9e4c-8e4179cdf507.png)

$224 for 600G is still pricey
![image](https://user-images.githubusercontent.com/5887929/110774455-1c674a00-825e-11eb-8bb2-fd5d171191a9.png)

I mean still, a good option compared to Cloudflare.
Maybe we can solve it on another level, how App works.

Have in mind a single column feed.

**Comment by yangwao** [comment]
Fixed I guess
