### ISSUE TITLE
Research more about low carbon minting NFTs and add to FAQ

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#168]
We are getting more climate activists asking and interested in minting on top of us. 
We should not miss this opportunity, capture and grow on this as we are running on top of [kusama.network](https://kusama.network) which is [nPoS](https://wiki.polkadot.network/docs/en/learn-staking) and low carbon or almost carbon neutral

Easiest is to calculate **node numbers * costs per server to determine co2 per network and then deduct RMRK** --suggest from @joshua-mir

The output could be dynamically adjusted numbers, some sort of calculator per address like [carbon.fyi](https://carbon.fyi)

**Comment by yangwao** [comment]
I'm personally funding this issue as a bounty as a reward for hard numbers.

**Comment by joshua-mir** [comment]
> and then deduct RMRK

I think a pretty important step here is to determine what to do with the "deduction" you would make here? I don't think a fee makes sense unless it's going somewhere productive. perhaps this should even be something at the blockchain level, not application level, currently treasury burns go to the Society but if we have a productive "destination" we can make treasury burns go to carbon offset or capture or something, and quite likely be a carbon *negative* network.

**Comment by yangwao** [comment]
Yup, we will be partnering with Offsetra they just need to integrate KSM fiat off-ramp.

We will be adding users to add to users mints `carbonless` tag and we aim something like $1 should be fair for one NFT and later once we will have hard numbers for Kusama we can tell X leverage they made against real carbon credits bought per that $1. Artists could be obligated to mint after that if they are under it or feel good they already bought some carbon credits for future mints.

My gut sense tells me that $1 should cover at least 100 RMRK NFTs, but I'm patiently waiting to estimate some numbers.

Redirecting thus closing this issue as we already got some tasks to do under label carbonless https://github.com/kodadot/nft-gallery/issues?q=is%3Aissue+label%3Acarbonless
