### ISSUE TITLE
Identicon is gone

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1684]
Basically we have 3 options now:
- try again [@polkadot/vue-identicon](https://www.npmjs.com/package/@polkadot/vue-identicon)
- reincarnate [@vue-polkadot/vue-identicon](https://www.npmjs.com/package/@vue-polkadot/vue-identicon)
- use [@vue-polkadot/sigil-js](https://www.npmjs.com/package/@vue-polkadot/sigil-js)

**Comment by roiLeo** [comment]
#1407 related

**Comment by vikiival** [comment]
Updated description with alternatives
- the our identicon had some problem with the build afaik
- the polkadot would be like the simplest fix
- sigil-js is really nice but the package is huge (1.4MB vs 110 KB)

WDYT @roiLeo, @yangwao ?

**Comment by roiLeo** [comment]
>     * the our identicon had some problem with the build afaik
I thought that the problem with identicon came from PWA.

>     * the polkadot would be like the simplest fix
yeah, this one seems the best for now

>     * sigil-js is really nice but the package is huge (1.4MB vs 110 KB)
the question doesn't arise, package is to big


Have you thought about creating your own Hashvatar component?

**Comment by vikiival** [comment]
> Hashvatar

this looks really nice!
This is mine
![Screenshot 2022-01-04 at 10 53 47](https://user-images.githubusercontent.com/22471030/148041370-ec9ef66e-abe0-46a4-8c31-b94ecc6e248f.png)
