### ISSUE TITLE
Checkbox to show only artists with identity/pseudonyms

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#169]
Our best shielding could be to put an option for users to turn on see only people with an identity.
Thus we are positively taking a step against scammers actions

**Comment by vikiival** [comment]
Two possible hacks;

1. use mingo (less verbose, lot of async magic)
2. use just checkbox and let component decide if it should render (not so performant, easier)

**Comment by yangwao** [comment]
let's start with 2.?  🥲

Related #35 #49

**Comment by yangwao** [comment]
#455
