### ISSUE TITLE
SEO and magic social cards - spiritual issue

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1691]
It's real, it's haunting my dreams.
Let's try to battle it.
A recent `main-nuxt` there is this release which seems does show links okays in open graph debugger

![image](https://user-images.githubusercontent.com/5887929/148044765-ce6be9e2-d13f-42af-84a7-bf8e4d37541e.png)

Plus for a special glitch reason, in our OG:Description, we have embedded README.md :D 

![image](https://user-images.githubusercontent.com/5887929/148045253-1e24a6de-4bff-4ca2-b8aa-390cdf37a370.png)

For special reasons, it simply doesn't work.
We've tried clear cache on CDN, even after hours, doesn't work.

https://www.opengraph.xyz/url/https%3A%2F%2Fbeta.kodadot.xyz%2Fspotlight/
https://developers.facebook.com/tools/explorer/
https://en.rakko.tools/tools/9/
https://opentags.io/url/https:%20%20beta.kodadot.xyz

![image](https://user-images.githubusercontent.com/5887929/148044930-e84e6a1c-6ddd-45d4-b699-891101f2e96d.png)

Play well! 

Here are some free weapons https://chrome.google.com/webstore/detail/meta-debugger/jfpdemgdamgplelnlmaecbonkfgfgomp

Hints, we have enabled env in our builds so feel free peak at logs during build!

**Comment by kkukelka** [comment]
@yangwao may I ask why we are even using `metaInfo()` (from vue-meta) at all? Nuxt uses vue-meta under the hood and provides much more powerful hooks via `head()` and `meta`. May be worth thinking about refactoring it alltogether. https://nuxtjs.org/docs/features/meta-tags-seo/

**Comment by vikiival** [comment]
also this could help for faster SEO https://github.com/kodadot/rubick/issues/13

**Comment by vikiival** [comment]
> refactoring it alltogether.

good idea: https://github.com/kodadot/nft-gallery/issues/1700
