### ISSUE TITLE
List new jobs opportunities

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1694]
Add to https://kodadot.xyz/jobs so yeah could be pushed to `main-nuxt` 

We will be looking for 
- developer advocate -- very needed for a hackathon to start
--Description -> We need you to help us with incoming developers, creating tutorials for developers on how to hack on our stuff, making streamlined flow when bugs occur and the rest of the greatly known avocados. Making good demos. Being an english-native speaker is highly needed for a lot of educational videos
- Technical writer -- Creating technical writings to help better understand what we are doing with KodaDot and Metaprime

Add Discord link for **Learn more** https://discord.gg/35hzy2dXXh

**Comment by kkukelka** [comment]
on it

**Comment by LatinSoul** [comment]
Many jobs seem to be expired. Shouldn't they be removed from the website ?

**Comment by kkukelka** [comment]
> Many jobs seem to be expired. Shouldn't they be removed from the website ?

@LatinSoul Let me know which ones should be removed. It just takes me a matter of seconds to edit 😝

**Comment by LatinSoul** [comment]
Almost all of them! hahaha. More seriously, here is the list of those tagged as "expired", at list in cryptojoblist.com : 
https://cryptojobslist.com/jobs/senior-business-and-operations-manager-at-metaprime-berlin
https://cryptojobslist.com/jobs/senior-business-and-operations-manager-at-metaprime-berlin
https://cryptojobslist.com/jobs/technical-product-manager-at-metaprime-kodadot-berlin
https://cryptojobslist.com/jobs/vuejs-frontend-engineer-at-nft-gallery-on-kusama-polkadot-at-metaprime-kodadot-berlin

I'd gladly remove them as well. Just let me know :P

**Comment by kkukelka** [comment]
all done 👍

**Comment by yangwao** [comment]
Ah, I see, where it comes from... 
Thinking... 
@kkukelka let's add those back I left a comment in #1696 and put there same Discord link!  It should drop person to introduction, probably I don't need specify job position if they know what they are applying for, intent is just to virtue signal potential seekers we have those positions open :)
