### ISSUE TITLE
Refactor vue-meta to the Nuxt approach

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#1700]
### Is your feature request related to a problem?

> why we even use `metaInfo()` (from vue-meta) at all? Nuxt uses vue-meta under the hood and provides much more powerful hooks via head() and meta. May be worth thinking about refactoring it all together. https://nuxtjs.org/docs/features/meta-tags-seo/

ht/ @kkukelka 

### Describe the solution you would like

- Use nuxt seo principles and use more reusable pieces 
- something like /utils/seo

### Describe alternatives you have considered

- 

### Screeenshots

-

**Comment by vikiival** [comment]
Tracked in #1691

**Comment by yangwao** [comment]
@kkukelka want to flex on this one?

**Comment by kkukelka** [comment]
> @kkukelka want to flex on this one?
> 
> it's definitely something which is blocking us for release :)

Sure thing! I'll get onto it first thing tomorrow.

**Comment by yangwao** [comment]
continue in #1691
