### ISSUE TITLE
Admin panel doesnt work

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1701]
- make send window at least three times height of original one 
![image](https://user-images.githubusercontent.com/5887929/148271638-9a90ee87-223c-462a-9bef-c9d35d15efb2.png)

- on beta, could not load collections 
![image](https://user-images.githubusercontent.com/5887929/148271688-f69a0809-a544-450e-9612-44c004265943.png)

**Comment by kkukelka** [comment]
just some starting points if someone wants to tackle this:
- definitely caused by $apollo being called before it is being initialised (see `fetchCollections` in `/rmrk/admin.vue`)
- readup on: https://github.com/apollographql/apollo-client/issues/6816
