### ISSUE TITLE
Muzak -- aka elevator music for next meta_hours_3

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1706]
Let's research on some chilly elevator music, in short muzak https://en.wikipedia.org/wiki/Muzak for upcoming meta_hours_3 :)

ooo even better, let's generate music fo meta_hours 
> More recent types of elevator music may be computer-generated, with the actual score being composed entirely algorithmically.

bpm should match usual speaking speed, not something speedy! :D 
Probably something Lo-FI?
oh and no vocals! :)
probably something Royalty Free 8-Bit could be best as we are heading to the gaming! :)

### Candidates
- Captive Portal Me AsToy Sounds Vol. 1

### Ref
- https://en.wikipedia.org/wiki/Elevator_music
- https://freemusicarchive.org/curator/Creative_Commons/
- https://freepd.com/
- https://www.fesliyanstudios.com/royalty-free-music/downloads-c/8-bit-music/6
- https://freemusicarchive.org/genre/Chiptune

**Comment by jkdizajn** [comment]
My candidates:
https://play.generative.fm/browse

or paste all Kodadot code hehe: https://typatone.com/m/HPufRDurgH

:P

**Comment by yangwao** [comment]
Plus would be nice to figure out how to play music on background?
ps: spotify keeps stopping it tho. Maybe just play it from the browser and pipe it to audio input?

**Comment by cryptodamsky** [comment]
i kinda like this one :) https://www.youtube.com/watch?v=g6hY7dB54bc

> 1. Can I use this in my video/stream/film/game/project/podcast etc.?
> - Yes, my music is 100% copyright free so you can use it in ANY creative project, just credit me "music by Karl Casey @ White Bat Audio". What you CANNOT do is take my music and redistribute it as a product.

I'm not sure if it would be good to have one beat repeating, although i found some pretty ones, it'll get annoying after time.
With this youtube mix, it seems there are no complaints to it, wanna give it a shot?

Also, i kinda like the typatone deepologic sent, just paste ton of text and let it play :D

**Comment by cryptodamsky** [comment]
> Plus would be nice to figure out how to play music on background? ps: spotify keeps stopping it tho. Maybe just play it from the browser and pipe it to audio input?

Will try it asap, maybe we can jump for a second to the discord channel and test it if it works. I think i might have a way, but would make me possible to only broadcast.

**Comment by jkdizajn** [comment]
I found this tutorial, just need to test it to see if you can talk into it...
[How To Play Music in Discord](https://playerassist.com/play-music-discord/)
or this is probably what we are looking for>>>  [How to Bring Music Into Your Live Stream Using VoiceMeeter Banana](https://www.youtube.com/watch?v=Z7WUabMlKYQ)

**Comment by yangwao** [comment]
We've used royalty-free Japanese music https://www.youtube.com/watch?v=MzgMBrtrFc4
it's calming and nurturing discussions
