### ISSUE TITLE
Update logo on Subquery Featured projects

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1707]
https://github.com/kodadot/kodadot-presskit/tree/main/v3

![image](https://user-images.githubusercontent.com/5887929/148383761-d3dcc540-4f88-4301-a6c2-deb622ad8079.png)

**Comment by vikiival** [comment]
<img width="1792" alt="Screenshot 2022-01-07 at 11 54 49" src="https://user-images.githubusercontent.com/22471030/148533860-4142682d-51f2-4ec3-9669-93bba1b7009f.png">
