### ISSUE TITLE
The slider in the collection browser responds to any keystroke :)

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#1719]
### What happened?

I found a bug while browsing my collection. When you open a particular NFT in the beta version, there is a slider that simply takes you to the next NFT in that particular collection - that's great, I like it a lot. I like it up until I press any key on my keyboard it automatically skips the swipe to the next NFT. I figured it out by accident, I wanted to copy the text to my NFT (ctrl+c)

### Please reproduce in steps

I figured it out by accident, I wanted to copy the text to my NFT (ctrl+c) and it automatically skips the swipe to the next NFT

### Expected Behavior

I've expected ... that the scroll bar will only respond to a mouse command or pressing an arrow on the keyboard

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz

### Screenshots

video here

https://user-images.githubusercontent.com/81104034/148569390-f2d1b850-b12d-4d9a-a124-8ae11e5217bc.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
May @kkukelka

**Comment by kkukelka** [comment]
> May @kkukelka can fix

I'll take a look at it! 👍

**Comment by jkdizajn** [comment]
Perfect!!! <3
