### ISSUE TITLE
Spotlight page is not loaded 

### ISSUE THREAD

**Issue by rchovatiya88** [kodadot/nft-gallery#1724]
### What happened?

When user visit https://nft.kodadot.xyz/spotlight

The page is blank

### Please reproduce in steps

When user visit https://nft.kodadot.xyz/spotlight

The page is blank

### Expected Behavior

Page should be displayed 

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

Link https://nft.kodadot.xyz/spotlight
![Screen Shot 2022-01-07 at 10 19 10 PM](https://user-images.githubusercontent.com/16197756/148630750-1973704a-f1dc-4dd2-980c-d0a86a4c0fbf.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Yup, we are pretty aware of that, on https://beta.kodadot.xyz/spotlight is working well, we've been implementing a new indexing partner SubSquid for this. :)
