### ISSUE TITLE
Dotscanner profile missing text

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1728]
@prachi00 I've found bug 👀

at https://beta.kodadot.xyz/rmrk/gallery/10834735-6ae6618638b0779c05-13-SCORPIO-0000000000000008

![image](https://user-images.githubusercontent.com/5887929/148647164-537b49f0-c75e-4b96-a4f3-1d0718695647.png)

### Ref
- #1029 
- #1703

**Comment by prachi00** [comment]
@yangwao checking this

**Comment by roiLeo** [comment]
Don't we miss sub.id link too?

**Comment by yangwao** [comment]
> Don't we miss sub.id link too?

that's was only on artist profile afaik, but hmm, to be consistent maybe would not be bad to add,
