### ISSUE TITLE
Missing collections stats

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1734]
https://beta.kodadot.xyz/rmrk/collections?page=2

https://user-images.githubusercontent.com/5887929/148657550-b85a0675-ed63-4a51-a1d9-2ae9ec48f16f.mov

**Comment by kkukelka** [comment]
@yangwao still working for me

https://user-images.githubusercontent.com/17953978/148671411-25edc21d-e0a7-47dc-b216-d3f28e98c60d.mov

**Comment by roiLeo** [comment]
This just happened to me too, worked again after clearing my browser cache.
Could be an issue with pwa

**Comment by yangwao** [comment]
Closing as haven't occurred so far and working tho 

![image](https://user-images.githubusercontent.com/5887929/152787384-97f8c1b6-6644-4030-bf5e-815333dfd7f5.png)
