### ISSUE TITLE
Animated Server Banner

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1737]
Let's make an animated server banner and make it ready once we will reach boosted level 3 of our discord https://discord.gg/35hzy2dXXh

It's commissioned work as a contest, something pretty easy, nothing shocking so people with psychotic behaviour could peacefully live on our discord 

Post your material in this thread

### Ref
- https://support.discord.com/hc/en-us/articles/360028716472-Server-Banners
- https://github.com/kodadot/kodadot-presskit/tree/main/v3

**Comment by yangwao** [comment]
🥳 😘

![image](https://user-images.githubusercontent.com/5887929/150117491-52f456ea-350a-4448-a7f1-9f41df48eae4.png)

Plus we have 30 slots for stickers, higher audio quality and a custom invite link https://discord.gg/kodadot

![image](https://user-images.githubusercontent.com/5887929/150117528-bf4790db-2385-4a31-a6f9-8329238db121.png)

**Comment by jkdizajn** [comment]
I'm going for it :)

**Comment by jkdizajn** [comment]
Here is me artwork :P 
**960x540 pixels in a 16:9 aspect ratio**

![KodaDot Discord banner](https://user-images.githubusercontent.com/81104034/150691955-ad6006c1-58dd-4702-ac43-c7b8370a63b9.gif)

**Comment by jkdizajn** [comment]
Nr.2
![KodaDot Discord banner_2](https://user-images.githubusercontent.com/81104034/150694813-30abb7d4-5dab-4f6e-a0cc-ea285ab88b20.gif)

**Comment by yangwao** [comment]
seems it changing something in discord as I've unable to upload tho

ok edit save button sometimes simple just doesn't update


https://user-images.githubusercontent.com/5887929/150978243-988a502e-e8e0-440a-803c-bc630eca6742.mov

**Comment by yangwao** [comment]
> Here is my artwork :P **960x540 pixels in a 16:9 aspect ratio**
> 
> ![KodaDot Discord banner](https://user-images.githubusercontent.com/81104034/150691955-ad6006c1-58dd-4702-ac43-c7b8370a63b9.gif)

It's a solid candidate! 
Second one as well

@jkdizajn if we can make something which is in the infinite loop would be best I guess :)

**Comment by jkdizajn** [comment]
Nr.3 
![KodaDot Discord banner_3](https://user-images.githubusercontent.com/81104034/151215884-14c499af-e844-4e9f-9d7c-f310c614ea0e.gif)

**Comment by yangwao** [comment]
hmm apparently discord has some issue and can't upload it, however previous had 7M and went through, barely works with 5M, but tried download this one from tenor as test https://tenor.com/view/kodadot-nft-rmrk-kusama-gif-24578154 but did not worked when used their dialog, straaaange

**Comment by yangwao** [comment]
> Nr.3 ![KodaDot Discord banner_3](https://user-images.githubusercontent.com/81104034/151215884-14c499af-e844-4e9f-9d7c-f310c614ea0e.gif)

less blink/zap stuff :D so I can peacefully read rest of discord

**Comment by yangwao** [comment]
pretty much done, yet we can still run it later again :)
