### ISSUE TITLE
Research on maintainers health of packages we are using

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1742]
Hey, as we would like to take an antifragile approach here and avoid further burnout or whatever happened to the author of `colors` & `faker` we would like to prevent it as soon as possible.
We believe and have the intent to sponsor OSS packages and give back once our revenue/sustainability allows.

### todo
- inspect our current [package.json](https://github.com/kodadot/nft-gallery/blob/main-nuxt/package.json)
- made a rich report which packages are on the edge to replace
- use tools like https://snyk.io/advisor/ and others to inspect "healthfulness" of maintainer-set particular package

### Ref
- https://snyk.io/blog/open-source-npm-packages-colors-faker/
- https://snyk.io/advisor/

**Comment by kkukelka** [comment]
on it!

**Comment by yangwao** [comment]
yolo made some dashboard @kkukelka https://app.snyk.io/invite/link/accept?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlSWQiOiJkOGJhMjkwYi1hYTllLTQ5NTctOWYwYi05NDA5ZDdiNGY4ODMiLCJpYXQiOjE2NDE5ODUwMjUsImV4cCI6MTY0MzAyMTgyNSwiaXNzIjoiNTRhNzIwZTQtMzI3Ny00Mzc5LWJlODAtYjYzZmFmM2Q2YzYxIiwic3ViIjoiZTc5MjQwZjctN2IwMC00NGZjLThlOGYtNTlkMDVkMTI4NmVlIiwianRpIjoiYTVjMTExYzgtNzlhNS00Mzc0LTkxYTctNWJiZWQ3MTI2YWEwIn0.BXJvdOEGP2E_D9krZz44LPQSDcij1PmcWJx3dD5HunA&utm_source=link_invite&from=link_invite

**Comment by yangwao** [comment]
added snyk tho https://github.com/kodadot/nft-gallery/commit/e378e8543ee62327c64ac1764339e1b726675c9b

but that's for security not for health of packages

**Comment by kkukelka** [comment]
@yangwao report in Discussion #1851

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x3173d40fc5e04b9d2817b23b33236f1c0e2434300090258438a2bd5fbebbabfd

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/
