### ISSUE TITLE
Media type icon on gallery card image

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1744]
### Is your feature request related to a problem?

I'm always frustrated when I don't know what media type I'll be looking at

### Describe the solution you would like

I would like to see an icon on gallery image (like we show event icon or price on card) for what media type nft is

### Describe alternatives you have considered

I would put these icons in the top left corner

- [VIDEO](https://fontawesome.com/v5.15/icons/video?style=solid)
- [IMAGE](https://fontawesome.com/v5.15/icons/image?style=solid)
- [3D](https://fontawesome.com/v5.15/icons/cube?style=solid)
- [VR](https://fontawesome.com/v5.15/icons/vr-cardboard?style=solid)
- [MUSIC](https://fontawesome.com/v5.15/icons/music?style=solid)

### Screeenshots

WIP: Paste your vision

**Comment by yangwao** [comment]
I guess let's go, maybe we can highlight this in NFT item detail as well, what's mediatype it's 

Also I would make it as option in settings to turn off to keep minimal UI :)

**Comment by JustLuuuu** [comment]
no need, we have generative art - lets focus on that.
