### ISSUE TITLE
Move DeviceOrientation.ts to utils?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1745]
Curious where we could have this, utils should be best new home for this?

https://github.com/kodadot/nft-gallery/blob/main-nuxt/directives/DeviceOrientation.ts

**Comment by prachi00** [comment]
@yangwao I'll check this

**Comment by yangwao** [comment]
I'm checking that some stuff could be moved elsewhere, regarding this https://github.com/kodadot/nft-gallery/issues/1559

Namely
`vue-audio-visual.d.ts`
`emoji-unicode.d.ts`
`gql.d.ts`

maybe put them into `/types` ?

Referring to #1614 by @roiLeo as well

**Comment by prachi00** [comment]
> I'm checking that some stuff could be moved elsewhere, regarding this #1559
> 
> Namely `vue-audio-visual.d.ts` `emoji-unicode.d.ts` `gql.d.ts`
> 
> maybe put them into `/types` ?
> 
> Referring to #1614 by @roiLeo as well

Sure, I'll see what all can be moved

**Comment by roiLeo** [comment]
- remove docker_koda
- move src-functions ?

**Comment by prachi00** [comment]
> * docker_koda

wheres docker_koda? cant find it

**Comment by prachi00** [comment]
<img width="586" alt="Screenshot 2022-01-11 at 4 31 10 PM" src="https://user-images.githubusercontent.com/39299315/148930931-4c57f027-057d-4637-acf5-fcce7aa079db.png">
also if I move src-functions, do I have to change the path here as well? not sure about this @roiLeo

**Comment by roiLeo** [comment]
> wheres docker_koda? cant find it

It was on my side, no need to worry

> also if I move src-functions, do I have to change the path in netlify.toml as well? not sure about this @roiLeo

Yes!

**Comment by yangwao** [comment]
> src-functions

that actually could stay! that's for netlify stuff

**Comment by prachi00** [comment]
> > src-functions
> 
> that actually could stay! that's for netlify stuff
> 
> > remove justfile
> 
> @vikiival has objections on this one ! :D so probably no

@yangwao @roiLeo okay, I'll revert the justfile and src-functions change then
