### ISSUE TITLE
Transfer seems broken on Beta 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1749]
Seems it's missing
Test at https://beta.kodadot.xyz/transfer/?usdamount=100&target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU

- the current price of $KSM
- when I enter USD value, doesn't update KSM amount
- when I enter KSM amount, doesn't update USD amount
- missing unit for native asset?

### Ref
![image](https://user-images.githubusercontent.com/5887929/148782465-a67dbef4-dfa8-4f84-9630-04bdd2703a8a.png)

**Comment by prachi00** [comment]
I'll check if I can figure this out

**Comment by prachi00** [comment]
![Uploading Screenshot 2022-01-10 at 8.23.36 PM.png…]()

I see this on console

**Comment by prachi00** [comment]
@yangwao @vikiival  Also this.$store.getters.getCurrentKSMValue this is undefined, so teleport is not working either 
https://beta.kodadot.xyz/teleport

**Comment by roiLeo** [comment]
> @yangwao @vikiival Also `this.$store.getters.getCurrentKSMValue` this is undefined, so teleport is not working either https://beta.kodadot.xyz/teleport

replace this line:
```js
this.$store.dispatch('fiat/fetchFiatPrice')
```

**Comment by roiLeo** [comment]
@prachi00 I forgot about all getters.

Should be 
```js
this.$store.getters['fiat/getCurrentKSMValue']
```
instead of 
```js
this.$store.getters.getCurrentKSMValue
```

**Comment by prachi00** [comment]
> ```js
> this.$store.getters['fiat/getCurrentKSMValue']
> ```

Thank you, I'll try doing this
