### ISSUE TITLE
SubSquid integration views

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1751]
What's missing to speed up for us and where we could have advantage using SubSquid?

### Potential targets
- #1838 collection activity graph
- artist profile - various tabs
- collections list (new resolver to drop collections with 0 nft)

Would be great we could deliver it to v2.2

**Comment by vikiival** [comment]
- collection activity graph - done
- artist profile - various tabs - done as separated service
- collections list (new resolver to drop collections with 0 nft) - hidden by default on Koda
