### ISSUE TITLE
Distinguish between sold and sent?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1752]
I guess it would help to see distinguish between these actions as it's not the same?
Probably would need to new query?

![image](https://user-images.githubusercontent.com/5887929/148816156-3d74fc72-d33d-45f5-8d14-39674220281c.png)

**Comment by roiLeo** [comment]
We can group it with #678 & #898 
Best option could be to create a new resolver ProfileStats on squid

**Comment by yangwao** [comment]
Continue to
- https://github.com/kodadot/nft-gallery/issues/898
