### ISSUE TITLE
Weird chart error?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1755]
At the buy event, I've received this 
plus seems reloader doesn't go away even on-chain action is finished 
![image](https://user-images.githubusercontent.com/5887929/148818917-080f3f8d-28d6-4b9d-87bb-b2bf3a96af58.png)

### ref
#1692 related?

**Comment by yangwao** [comment]
Seems due the crash, it wont close the modal.

![image](https://user-images.githubusercontent.com/5887929/149100859-5d1373ec-b726-4f4c-a731-200f91c1426b.png)

**Comment by pandasamanvaya** [comment]
I guess whenever you interact with an NFT(buy, list, etc), a new point is added to the chart. So to re-render the point on the same canvas, the old chart must be first removed and a new chart must be created. I think this also happens in #1692.
