### ISSUE TITLE
Framing gdpr toast

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1765]
We should add a countdown to accept toast, or formulate it in a way that people keeping on our site over 30 seconds give us consent to accept it on their behalf and probably that's it :)

![image](https://user-images.githubusercontent.com/5887929/148966028-827955b7-90b8-4346-a571-4bb0dbfdfd19.png)

**Comment by roiLeo** [comment]
Hmmm.. this is not gdpr compliant

**Comment by yangwao** [comment]
> this is not gdpr compliant

silent consent

we will be probably putting default opt-in if user won't leave site. They can redeploy frontend w/o it anytime on their own.

- #6010 
- #5413
