### ISSUE TITLE
New preview social cards v3

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1766]
summoning @AndriiHrynchuk for card preview 

For previews and better branding awareness, I would like to use either 
- outlined logo https://github.com/kodadot/kodadot-presskit/blob/main/v3/kodadot_outline_logo.png
- simple https://github.com/kodadot/kodadot-presskit/blob/main/v3/K_outline_logo.png
and removing probably background?

![image](https://user-images.githubusercontent.com/5887929/148967906-df640ca0-c4dc-4a5a-9d11-9008ade4efad.png)

**Comment by AndreyGrin** [comment]
![test-outline-with-bg](https://user-images.githubusercontent.com/2453346/149647794-db6a47af-9613-4515-8acc-a7fb9ea25bef.png)
![test-small-outline](https://user-images.githubusercontent.com/2453346/149647799-4cce2ff9-0df8-4d63-a9b6-6e40ea8bc9cb.png)
![test-full-outline](https://user-images.githubusercontent.com/2453346/149647803-d0d54981-81be-42ba-b49f-a3a695d1e921.png)
I've tried these 3 options. I think full outlined with BG looks the best. Maybe, could be also good option to have full outlined filled black and then use it without background. @yangwao

**Comment by yangwao** [comment]
> ![test-outline-with-bg](https://user-images.githubusercontent.com/2453346/149647794-db6a47af-9613-4515-8acc-a7fb9ea25bef.png) 

Yup let's go with first tho :)

also, seems previews are not generated since 13/1  https://twitter.com/hashtag/KodaDot?src=hashtag_click&f=live

**Comment by AndreyGrin** [comment]
was there any changes in the code regarding meta tags?
Looks weird, when I share this link https://kodadot.xyz/rmrk/gallery/10997530-8000262b13545ea72d-MPUNKS-META_PUNK_004-0000000000000008 it doesn't show preview but if I just open link from og:image tag https://og-image-green-seven.vercel.app/Meta%20punk%20-%20%23004.png?price=0.1960KSM&image=https://kodadot.mypinata.cloud/ipfs/bafkreib6qyr7w6tbynfrtmyoxrlqkxqi6be7ua2hl6nedv2d7ztowz7vni&mime= it shows correct image. Might be that on the moment of page generation meta tags are not generated yet.

**Comment by yangwao** [comment]
> was there any changes in the code regarding meta tags? Looks weird, when I share this link https://kodadot.xyz/rmrk/gallery/10997530-8000262b13545ea72d-MPUNKS-META_PUNK_004-0000000000000008 it doesn't show preview but if I just open link from og:image tag https://og-image-green-seven.vercel.app/Meta%20punk%20-%20%23004.png?price=0.1960KSM&image=https://kodadot.mypinata.cloud/ipfs/bafkreib6qyr7w6tbynfrtmyoxrlqkxqi6be7ua2hl6nedv2d7ztowz7vni&mime= it shows correct image. Might be that on the moment of page generation meta tags are not generated yet.

@kkukelka can speak about some #1790

**Comment by kkukelka** [comment]
@yangwao i believe we don't have a baseUrl env variable set for production? it works fine on beta though
<img width="881" alt="Screenshot 2022-01-17 at 19 21 37" src="https://user-images.githubusercontent.com/17953978/149821205-0f7d460f-3c5d-4c3b-b30c-c301aceadae4.png">

**Comment by AndreyGrin** [comment]
Facebook open graph debugger shows this:
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/2453346/149888747-9ccd32b5-4a37-4f1e-9a89-3e555aff8b3b.png">
page itself has correct `og:image` content 
<img width="557" alt="image" src="https://user-images.githubusercontent.com/2453346/149888903-cf357eb0-adc5-453b-8e19-02472e35e71a.png">
https://og-image-green-seven.vercel.app/Tree%20Ape.png?price=0.0980KSM&image=https://kodadot.mypinata.cloud/ipfs/bafybeibkt2nusg5yomau6htq6y7f2qmi4i74eyaz5jgs6bxx5hlgus2wia&mime= can show generated image. 
I really feel that problem that opengraph tags generated after page is loaded, this is bad approach. All meta tags should be available right away, otherwise crawlers can't see them.

**Comment by kkukelka** [comment]
With the current setup I cannot see how we could do it otherwise. Maybe there is an option with cloudflare images, but we would need to rerender the image everytime the price of an nft changes. 

Or can you somehow communicate to opengraph crawler when metadata is complete?

**Comment by niklasp** [comment]
i am interested, what should i implement now? For me it looks like this (telegram)
<img width="423" alt="Bildschirmfoto 2022-06-11 um 23 50 34" src="https://user-images.githubusercontent.com/1685139/173206059-dd1e5a8e-1691-4640-b5e5-4d296170cfa7.png">

**Comment by roiLeo** [comment]
ref #3038

**Comment by roiLeo** [comment]
> ref #3038

meanwhile this has been done
