### ISSUE TITLE
Let user know further expect action to check extension event

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1776]
Once there is action event-triggered let the user know further, to expect action from them, to what to do next.

Like we should put text probably into action area, there is waiting for a request for them to sign a transaction in extension/wallet and check their extension for further steps

Now we don't have any sort of dialog.

Thinking it could be part of the preloader component if so, to tell them to check for an extension to proceed?

**Comment by MubarakSULAYMAN** [comment]
@yangwao, can you elaborate on this, please?

**Comment by exezbcz** [comment]
done in signing modal + wallet connect has this sort of loader
