### ISSUE TITLE
Add fixed height to detail item

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1777]
To prevent random jumping content despite we know ahead height of item would be nice to avoid for users unpleasant jumping of other components.
Probably add skeleton with height https://buefy.org/documentation/skeleton/ but I guess we have preloader there yet something is happening inside before load

Or add transition until is full media loaded?

https://user-images.githubusercontent.com/5887929/149102928-2c0e764f-9246-4dc9-9ad9-49fe7fdcfd8d.mov

**Comment by kkukelka** [comment]
on it!

**Comment by yangwao** [comment]
> on it!

don't forget to eat!
