### ISSUE TITLE
Add to collections sort by 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1778]
Sort by 
- biggest collections by assets
- most buys 
- most owners
- volume 
- floor price

![image](https://user-images.githubusercontent.com/5887929/149098333-ef99116b-8e43-4215-889d-b95dfd8e2fc1.png)

Hints are in series insight https://deploy-preview-1775--koda-nuxt.netlify.app/series-insight/

Probably would require a write resolver to https://github.com/kodadot/rubick

### Ref
- #1357

**Comment by MubarakSULAYMAN** [comment]
@yangwao, do you mean to remove the sorting functionality as a separate button instead of how it is currently implemented? Presently, you click on each column header to toggle the sort function.

**Comment by yangwao** [comment]
> @yangwao, do you mean to remove the sorting functionality as a separate button instead of how it is currently implemented? Presently, you click on each column header to toggle the sort function.

Probably you can remove that one that doesn't work well.
Seems interacted and long time no interaction works. old and new first as well
From most expensive and from cheaper doesn't work

**Comment by preschian** [comment]
> > @yangwao, do you mean to remove the sorting functionality as a separate button instead of how it is currently implemented? Presently, you click on each column header to toggle the sort function.
> 
> Probably you can remove that one that doesn't work well. Seems interacted and long time no interaction works. old and new first as well From most expensive and from cheaper doesn't work
> 
> Notice that #1357 is related issue so you can make it as one PR as you can check on that one

hello @yangwao can I do this issue partially? I was only able to remove "expensive" and "cheaper" from the collection page.
I have no idea how to exclude empty array (nodes) from graphql or how to update the API (resolver). need learning more about it

**Comment by yangwao** [comment]
> > > @yangwao, do you mean to remove the sorting functionality as a separate button instead of how it is currently implemented? Presently, you click on each column header to toggle the sort function.
> > 
> > 
> > Probably you can remove that one that doesn't work well. Seems interacted and long time no interaction works. old and new first as well From most expensive and from cheaper doesn't work
> > Notice that #1357 is related issue so you can make it as one PR as you can check on that one
> 
> hello @yangwao can I do this issue partially? I was only able to remove "expensive" and "cheaper" from the collection page. I have no idea how to exclude empty array (nodes) from graphql or how to update the API (resolver). need learning more about it

Sure, create an issue with backreference and I can update it here :)
