### ISSUE TITLE
Add keyboard shortcuts 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1783]
We want to control kodadot with keyboard shortcuts for much pleasant and faster browsing

- g n - go to next page on gallery/collections/collections detail
- g p - go to the previous page on gallery/collections/collections detail
- g a - go-to own artist profile
- g c - go to your collected items
- g s - go to your sold items 
- g m - go-to simple mint
- g t - go to transfer
- g i - go to series insights
- g d - go to creators directory 
- g r - go to the random page at a particular view 

#### on item detail
- e p - expand price chart
- e h - expand history chart
- e d - expand the description

#### filter toggle on gallery/collection view
- f b - filter buy now
- f n - filter new first
- f e - filter expensive first
- f c - filter cheap one

#### actions
- a b - buy the item
- a s - send the item
- a c - consume
- a l - list

### probably everywhere
- c c - copy current URL where is used to clipboard and show notification about that

Add a way to recall this manual for shortcuts like overlay, check gmail and smash shift / 

### Ref
- #349 
- ref gmail https://support.google.com/mail/answer/6594?hl=en

**Comment by prachi00** [comment]
I'll check how we can do this

**Comment by prachi00** [comment]
https://www.npmjs.com/package/vue-shortkey
can we use a package for this?

**Comment by vikiival** [comment]
<img width="177" alt="Screenshot 2022-01-12 at 15 07 53" src="https://user-images.githubusercontent.com/22471030/149155597-a37eb3bd-0b89-44a6-b569-3802a1ae7fd3.png">

That's Huuuge

**Comment by atharva3010** [comment]
@vikiival @prachi00 You can do keybinding without using that package, just use the appropriate keycodes from https://keycode.info/

An example for using W A S D as arrow keys is: https://stackoverflow.com/a/22766391

**Comment by MubarakSULAYMAN** [comment]
[v-hotkey](https://www.npmjs.com/package/v-hotkey) can be a good alternative. It has lesser issues, opened PR and just a year old
.

**Comment by atharva3010** [comment]
@MubarakSULAYMAN what `v-hotkey` does is already supported by vue natively, using `@keyup`

**Comment by yangwao** [comment]
@chandradot99 would be nice to add tooltips where is possible to add to

Like on page previous, next and randomize could add tooltip with a hint in ( ) round brackets

![image](https://user-images.githubusercontent.com/5887929/151780203-8f2ae906-3491-4a12-8cad-88a3cf1d46ef.png)

**Comment by chandradot99** [comment]
sure @yangwao I will add tooltips as well.
