### ISSUE TITLE
seo revisit 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1790]
Seems recent deployment from `main-nuxt` doesn't work well @kkukelka 👀

maybe it's just cache on edge cdn servers or so

![image](https://user-images.githubusercontent.com/5887929/149169037-977f28af-1469-49f4-bfe0-dc4b88392dc0.png)

however telegram works hmm 
![image](https://user-images.githubusercontent.com/5887929/149169490-2783661c-eebd-420f-b269-fc9891a06477.png)

**Comment by kkukelka** [comment]
@yangwao I bet it's cache-related. I'll give it a look tomorrow!
