### ISSUE TITLE
need unregister old service-worker.js for old instance and remove old cache storage

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1797]
I've tried `workbox.swdest`which works if I use it as `yarn dev` but doesn't work for `yarn generate` 

https://github.com/kodadot/nft-gallery/blob/main-nuxt/nuxt.config.js#L151

You can see `dist/` made by `yarn generate` vs folder `/` made by `yarn dev` 

### Ref
Workbox docs -- https://pwa.nuxtjs.org/workbox/ 
our old `service-worker.js` -- https://github.com/kodadot/nft-gallery/blob/main/src/registerServiceWorker.ts

![image](https://user-images.githubusercontent.com/5887929/149209882-ce2475ad-6cd4-45d5-a21f-b3c5e7590d73.png)

**Comment by atharva3010** [comment]
@yangwao Service Workers are a PWA concept, running `yarn generate` or `nuxt generate` means you are doing Static Site Generation (SSG), it's expected that it will not contain a service worker.

When you run it locally, you are running it as a single page progressive web application, which supports service worker, hence you see it when running `yarn dev`.

To setup a PWA, you need to build it as one, the command for that is `yarn build` or `nuxt build`.

**Comment by yangwao** [comment]
@atharva3010 to briefly onboard you, check branch `main`, that's current running code for olde users. Way to solve this would be to unregister service worker from the previous instance of users (it's still running here https://nftkodadot.netlify.app/ ) as it serves old user content (which was previously at https://kodadot.xyz) from old cache and service worker won't refetch new stuff until we will tell them to fetch by new manifests as it's bumps to https://kodadot.xyz/service-worker.js .. which is not there yet as new nuxt code from `main-nuxt` generates sw.js which is actually irrelevant to old istance.

Found helpful hints here https://github.com/GoogleChrome/workbox/issues/2080
Probably gonna try.

> To setup a PWA, you need to build it as one, the command for that is yarn build or nuxt build.
Yes, that would be the next case we will try on beta, right now point is to unregister old service worker for old user, bc currently they have none way to learn there is new deployment.

**Comment by atharva3010** [comment]
```js
self.addEventListener('install', function(e) {
  self.skipWaiting();
});

self.addEventListener('activate', function(e) {
  self.registration.unregister()
    .then(function() {
      return self.clients.matchAll();
    })
    .then(function(clients) {
      clients.forEach(client => client.navigate(client.url))
    });
});
```

**Comment by yangwao** [comment]
> ```js
> self.addEventListener('install', function(e) {
>   self.skipWaiting();
> });
> 
> self.addEventListener('activate', function(e) {
>   self.registration.unregister()
>     .then(function() {
>       return self.clients.matchAll();
>     })
>     .then(function(clients) {
>       clients.forEach(client => client.navigate(client.url))
>     });
> });
> ```

Yes, that's what I was thinking use y'day, it's being generated by `yarn dev` 
https://github.com/NekR/self-destroying-sw

But, nuxt uses already `sw.js` 
![image](https://user-images.githubusercontent.com/5887929/149322708-6a3051b1-d470-4ab2-b360-80653cada2ae.png)

```
const options = {
    "workboxURL": "https://cdn.jsdelivr.net/npm/workbox-cdn@5.1.4/workbox/workbox-sw.js",
    "importScripts": [],
    "config": {
        "debug": false
    },
    "cacheOptions": {
        "cacheId": "nft-gallery-nuxt-prod",
        "directoryIndex": "/",
        "revision": "8q9FD9VWMlA8"
    },
    "clientsClaim": true,
    "skipWaiting": true,
    "cleanupOutdatedCaches": true,
    "offlineAnalytics": false,
    "preCaching": [{
        "revision": "8q9FD9VWMlA8",
        "url": "/?standalone=true"
    }],
    "runtimeCaching": [{
        "urlPattern": "/_nuxt/",
        "handler": "CacheFirst",
        "method": "GET",
        "strategyPlugins": []
    }, {
        "urlPattern": "/",
        "handler": "NetworkFirst",
        "method": "GET",
        "strategyPlugins": []
    }],
    "offlinePage": null,
    "pagesURLPattern": "/",
    "offlineStrategy": "NetworkFirst"
}

importScripts(...[options.workboxURL, ...options.importScripts])

initWorkbox(workbox, options)
workboxExtensions(workbox, options)
precacheAssets(workbox, options)
cachingExtensions(workbox, options)
runtimeCaching(workbox, options)
offlinePage(workbox, options)
routingExtensions(workbox, options)

function getProp(obj, prop) {
    return prop.split('.').reduce((p,c)=>p[c], obj)
}

function initWorkbox(workbox, options) {
    if (options.config) {
        // Set workbox config
        workbox.setConfig(options.config)
    }

    if (options.cacheNames) {
        // Set workbox cache names
        workbox.core.setCacheNameDetails(options.cacheNames)
    }

    if (options.clientsClaim) {
        // Start controlling any existing clients as soon as it activates
        workbox.core.clientsClaim()
    }

    if (options.skipWaiting) {
        workbox.core.skipWaiting()
    }

    if (options.cleanupOutdatedCaches) {
        workbox.precaching.cleanupOutdatedCaches()
    }

    if (options.offlineAnalytics) {
        // Enable offline Google Analytics tracking
        workbox.googleAnalytics.initialize()
    }
}

function precacheAssets(workbox, options) {
    if (options.preCaching.length) {
        workbox.precaching.precacheAndRoute(options.preCaching, options.cacheOptions)
    }
}

function runtimeCaching(workbox, options) {
    const requestInterceptor = {
        requestWillFetch({request}) {
            if (request.cache === 'only-if-cached' && request.mode === 'no-cors') {
                return new Request(request.url,{
                    ...request,
                    cache: 'default',
                    mode: 'no-cors'
                })
            }
            return request
        },
        fetchDidFail(ctx) {
            ctx.error.message = '[workbox] Network request for ' + ctx.request.url + ' threw an error: ' + ctx.error.message
            console.error(ctx.error, 'Details:', ctx)
        },
        handlerDidError(ctx) {
            ctx.error.message = `[workbox] Network handler threw an error: ` + ctx.error.message
            console.error(ctx.error, 'Details:', ctx)
            return null
        }
    }

    for (const entry of options.runtimeCaching) {
        const urlPattern = new RegExp(entry.urlPattern)
        const method = entry.method || 'GET'

        const plugins = (entry.strategyPlugins || []).map(p=>new (getProp(workbox, p.use))(...p.config))

        plugins.unshift(requestInterceptor)

        const strategyOptions = {
            ...entry.strategyOptions,
            plugins
        }

        const strategy = new workbox.strategies[entry.handler](strategyOptions)

        workbox.routing.registerRoute(urlPattern, strategy, method)
    }
}

function offlinePage(workbox, options) {
    if (options.offlinePage) {
        // Register router handler for offlinePage
        workbox.routing.registerRoute(new RegExp(options.pagesURLPattern), ({request, event})=>{
            const strategy = new workbox.strategies[options.offlineStrategy]
            return strategy.handle({
                request,
                event
            }).catch(()=>caches.match(options.offlinePage))
        }
        )
    }
}

function workboxExtensions(workbox, options) {
}

function cachingExtensions(workbox, options) {
}

function routingExtensions(workbox, options) {
}
```

**Comment by yangwao** [comment]
This done the job, even reloaded on Firefox and Chrome, Safari keeps hanging
```js
self.addEventListener('install', function (e) {
  console.log('installListener')
  self.skipWaiting();
});

self.addEventListener('activate', function (e) {
  console.log('activeListener')
  self.registration.unregister()
    .then(function () {
      console.log('unregister')
      return self.clients.matchAll();
    })
    .then(function (clients) {
      // maybe this is not needed at all and leaving as very last option to try
      // window.sessionStorage.clear()
      // window.localStorage.clear()
      // window.location.reload()
      clients.forEach(client => client.navigate(client.url))
    });
});
```

Seems it works!

![image](https://user-images.githubusercontent.com/5887929/149333523-8598c9b7-e679-4e51-bd80-98fc28664d5a.png)

@atharva3010 sent a payment link, I guess owe you some small payout for engagement and hint! :)

**Comment by yangwao** [comment]
@atharva3010 sent you $100 ;)
https://kusama.subscan.io/extrinsic/0xd4d0fb93feb14bf3c5192c395cae150a8a0a1ae16d8e4887d0c24dad2c16d3b4
