### ISSUE TITLE
Change facts in preloader after 10 seconds

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1804]
Let's change the quote after a while, probably 10 seconds it should be enough to read every quote?

Bonus stage: bring your own quote! 

![image](https://user-images.githubusercontent.com/5887929/149332402-87ad8a39-49b1-46e7-975e-8928ac7328a3.png)

**Comment by prachi00** [comment]
@yangwao I'll try to do this

**Comment by prachi00** [comment]
@yangwao @vikiival @roiLeo do we know how many countries people are contributing from? I think that would make an interesting fact like 

```
Did you know...
that people from 80 countries are contributing to our codebase
```
