### ISSUE TITLE
Check if we could link directly to that discord user from profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1811]
Checking if we could link directly to that user.. https://www.swipetips.com/how-to-send-a-link-to-a-discord-profile/

seems needs to be there like 
`https://discordapp.com/users/prachi#4004/`
So this should reach @prachi00 on discord? https://discordapp.com/users/prachi#4004/

edit seems doesn't work now.

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/pull/1771#issuecomment-1013057590_

**Comment by kkukelka** [comment]
username won't work here, it actually needs to be a 18-char long id

**Comment by roiLeo** [comment]
Meanwhile we added posibility to fill discord in Identity, continue in #4751
