### ISSUE TITLE
History component v1.1

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1814]
- Show day fixed on the top in a component while scrolling
- check on the bottom & top pixel border
- add shadow to show its depth of component?
- add fade in/out for background shadow so it slowly follows cursor? 
- once NFT is loaded on the background (check video) it could not be scrolled, we should avoid blocking UI here, as blocking OP could take fair amount bandwidth of user internet connection (ie bee there longer than anticipated)

### Ref
- #1499 

![image](https://user-images.githubusercontent.com/5887929/149518823-7551cceb-b26b-4fda-8958-14f3b55f2e03.png)

![image](https://user-images.githubusercontent.com/5887929/149519241-4f901bd8-4d2e-416b-81c0-1a9a62baef32.png)

https://user-images.githubusercontent.com/5887929/149519052-aa234698-907f-4ad6-ba77-64c6794b41c1.mov

**Comment by prachi00** [comment]
@yangwao I'll see what I can do

**Comment by prachi00** [comment]
@roiLeo @vikiival not sure about the last bullet point here, any idea if it can fixed or not?

**Comment by yangwao** [comment]
> @roiLeo @vikiival not sure about the last bullet point here, any idea if it can fixed or not? 

I guess there is some await which seems blocks whole UI

**Comment by prachi00** [comment]
> > @roiLeo @vikiival not sure about the last bullet point here, any idea if it can fixed or not?
> 
> I guess there is some await which seems blocks whole UI

@yangwao maybe we can create this one as a separate issue, as it isn't probably related with the history component

**Comment by yangwao** [comment]
> once NFT is loaded on the background (check video) it could not be scrolled, we should avoid blocking UI here, as blocking OP could take fair amount of bandwidth of user internet connection (ie bee there longer than anticipated)
