### ISSUE TITLE
hover card v1.1

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1816]
- border let be $primary
- add depth effect some like MS-DOS, ncurses ui
- depth could be made by black shadow or use texture in the third picture on the floor, yet really don't know its name @XyloDrone may whisper!

![image](https://user-images.githubusercontent.com/5887929/149520030-1732b158-ef96-43b7-9f00-37d638f38b3c.png)

![image](https://user-images.githubusercontent.com/5887929/149520772-585050ab-be37-460b-89c0-fe102ad67b79.png)

![image](https://user-images.githubusercontent.com/5887929/149521132-b0cf2fc2-612c-41c3-aacd-34bfead287f6.png)

**Comment by kkukelka** [comment]
I'll see what I can do!
