### ISSUE TITLE
Probably adjust background image 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1830]
As homepage-bg.jpeg has 238kb would be nice to optimize it to way lower and something smaller, destinable to something under 50-80kB ~

![image](https://user-images.githubusercontent.com/5887929/149568400-055c4b81-fa50-4b12-a58a-d4a52eb936db.png)

**Comment by kkukelka** [comment]
i could implement https://github.com/juliomrqz/nuxt-optimized-images
its the best solution out there for optimising local assets at build time

**Comment by yangwao** [comment]
> i could implement https://github.com/juliomrqz/nuxt-optimized-images its the best solution out there for optimising local assets at build time

yeah that's the thing I've tried with github actions #1634 but need check back

meanwhile it's done in https://github.com/kodadot/nft-gallery/pull/1832 for now, 

will keep monitoring which assets are trouble some, I see infinity.svg for some reason but isn't that big so curious

**Comment by kkukelka** [comment]
> > i could implement https://github.com/juliomrqz/nuxt-optimized-images its the best solution out there for optimising local assets at build time
> 
> yeah that's the thing I've tried with github actions #1634 but need check back
> 
> meanwhile it's done in #1832 for now,
> 
> will keep monitoring which assets are trouble some, I see infinity.svg for some reason but isn't that big so curious

very weird. infinity.svg file-size is actually impressively small for an animated vector graphic

**Comment by yangwao** [comment]
yeah will keep it eventually monitoring, we will see :)
![image](https://user-images.githubusercontent.com/5887929/149626665-dcd72099-90c6-431a-a605-9901232daf58.png)
