### ISSUE TITLE
Search upgrades v1.2

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1839]
When navigating, 
- prefer show collection item (let's try https://fontawesome.com/v5.15/icons/align-justify?style=solid or https://fontawesome.com/v5.15/icons/layer-group?style=solid )
- (only desktop) while on the collection, show the right arrow on the right edge. while press right arrow keyboard show another contextual dialog with series insight numbers like Volume, Buys, Owners, Assets
- (only desktop) while on an item, show a right arrow on the right edge. while pressing the right arrow keyboard, show chart engine of nft item, price if on sale, number of total owners, relative date how old is nft, i.e. since MINT event
- #1840  continue

![image](https://user-images.githubusercontent.com/5887929/149620082-e83f4526-846e-47e5-abd3-303656d82053.png)

### Ref
- https://github.com/vinibiavatti1/TuiCss
- #1824 
- #1837

**Comment by FG-HJ** [comment]
:wave:

**Comment by vikiival** [comment]
My search and your search are not the same


![Screenshot 2024-07-31 at 15 24 46](https://github.com/user-attachments/assets/406c61d6-6b7e-4ae4-adb4-851b056fbcbb)
