### ISSUE TITLE
Service notice of renaming branch main-nuxt to main

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1844]
@kkukelka @roiLeo @vikiival 

![image](https://user-images.githubusercontent.com/5887929/149623833-0e374fdd-e9ad-44f4-8661-19fe5f1f6fd3.png)

**Comment by kkukelka** [comment]
@yangwao do existing pull requests need to be updated in any way or are they now being merged into main automatically?

**Comment by yangwao** [comment]
> @yangwao do existing pull requests need to be updated in any way or are they now being merged into main automatically?

that's automatically.


Actually found that best is to clone repository as new as github toast did not expect there was previous branch at `main` :D

**Comment by yangwao** [comment]
and i've upgraded https://github.com/kodadot/nft-gallery/blob/main/FIRST_TIME.md#quick-setup--%EF%B8%8F

**Comment by yangwao** [comment]
how to sync your fork https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by yangwao** [comment]
Added to FIRST_TIME 

https://github.com/kodadot/nft-gallery/blob/main/FIRST_TIME.md#notice-for-contributors-before-15012022-%EF%B8%8F
