### ISSUE TITLE
Mastery of on-chain data v1.1

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1847]
We should add new data views and extract a few more on-chain data views for users

![image](https://user-images.githubusercontent.com/5887929/149626156-53a5361e-5160-4963-a01f-a5bf60cfec89.png)

- kodadot/nft-gallery#1818
- kodadot/nft-gallery#1548
- kodadot/nft-gallery#1496 
- kodadot/nft-gallery#1386
- kodadot/nft-gallery#1285
- kodadot/nft-gallery#1236 
- kodadot/ideas#16 
- kodadot/ideas#7

**Comment by vikiival** [comment]
No 🧇s for this one
