### ISSUE TITLE
Hello, question regarding WIV token

### ISSUE THREAD

**Issue by grijsz** [kodadot/nft-gallery#186]
Hello Kodadot, 

where can I see the NFT I bought ?

Can you please check, if I successfully bought this NFT of WIV
https://nft.kodadot.xyz/rmrk/detail/6572635-3A9B1D934EB8D5A712-WIV-LA_DAME_DE_MONTROSE_2017-0000000000000001
I've send 1 KSM , please see the tx
https://kusama.subscan.io/account/EacNR1G8kKAapJqaq3NqkSGBPaLTHdgneG565Ra6ozEEasM
But I don't know where to find the NFT

Please help.
Best regards, Hans

**Comment by yangwao** [comment]
Yup, it was replied in DMs, you are new owner! :)
