### ISSUE TITLE
Call to introduce UPGRADE action for all previous MINTs to be compatible

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#187]
More reading starts here https://t.me/rmrkapp/2061
Screenshots for the immutability of convo.

This issue would be funded if someone wants to help us out -- https://t.me/rmrkapp/2076

![image](https://user-images.githubusercontent.com/5887929/111064764-2f745700-84b6-11eb-988f-17ba3584e0aa.png)
![image](https://user-images.githubusercontent.com/5887929/111064772-3e5b0980-84b6-11eb-97c1-8e7d6cf367b3.png)

**Comment by yangwao** [comment]
To underline these efforts, most likely this function would be part of the migration of NFTs to orml-nft once it would be available on Kusama and elsewhere :)

**Comment by vikiival** [comment]
Pass.
