### ISSUE TITLE
Hide disabled pagination buttons

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1887]
Let's remove pagination buttons if they are disabled.

- Collection detail
- Artist tabs 
- where else?

https://kodadot.xyz/rmrk/u/EzZjBjv9bRPYJEbUdijzgjb9VMSqrqwx2eqnfjQcY5YvXCk?search=&listed=true

![image](https://user-images.githubusercontent.com/5887929/149785037-dc2f0801-853c-4fe4-a303-9d5a40049e50.png)

![image](https://user-images.githubusercontent.com/5887929/149784883-128c6716-9a3e-4fa1-971c-28f3aaea3497.png)

**Comment by prachi00** [comment]
@yangwao I'll do this
