### ISSUE TITLE
long Emotes list on nft

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1897]
on `/rmrk/gallery/6802639-24d573f4dfa1d7fd33-KAN-KANL-0000000000006001` I came across a big list of Emotes (Appreciations), some of them where duplicated when they should be grouped

![Screenshot 2022-01-17 at 16-45-02 Limited Edition Kanaria Egg](https://user-images.githubusercontent.com/9987732/149800339-5353ddab-4643-4643-afd2-4131df6ce6da.png)

#### Possible solution
- show a certain amount of emojis

#### Bonus
- sort Emoji List by most reacted

**Comment by prachi00** [comment]
@roiLeo @yangwao I'll try to work on this

**Comment by prachi00** [comment]
@roiLeo the emojis that are same they supposedly have different keys, that is why they arent getting grouped together  
<img width="584" alt="Screenshot 2022-01-19 at 4 11 00 PM" src="https://user-images.githubusercontent.com/39299315/150114549-86ff7749-17d1-4f13-a991-fd4ff197c73c.png">

**Comment by roiLeo** [comment]
> @roiLeo the emojis that are same they supposedly have different keys, that is why they arent getting grouped together 

Did you find out why the emoji keys are different but the emoji is the same?

**Comment by preschian** [comment]
hello, what is the status of this issue? can I take a look at this issue?

**Comment by prachi00** [comment]
@preschian I couldn't figure out why the keys are different, feel free to take this up.

**Comment by yangwao** [comment]
> hello, what is the status of this issue? can I take a look at this issue?

Seems would be great to have this fixed! :)
