### ISSUE TITLE
Should be those assets in /static folder?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1898]
I'm curious if we could have this in `static/` folder as we don't manipulate anything with them and we could save time  (seconds) on builds without not manipulating and just copy from static folder?

![image](https://user-images.githubusercontent.com/5887929/149801636-dd466a05-c37b-4f17-8134-a5a4778c7646.png)

**Comment by atharva3010** [comment]
Yes and should.

**Comment by yangwao** [comment]
Builds fast af
