### ISSUE TITLE
Preloader text seems overflowing

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1902]
@prachi00 seems like bug and sometimes at longer facts it's even more overflowed 👀

![Screenshot 2022-01-17 at 17 29 06](https://user-images.githubusercontent.com/5887929/149806989-5e299ac4-480d-4d68-9134-1fb2da565038.png)

**Comment by prachi00** [comment]
> @prachi00 seems like bug and sometimes at longer facts it's even more overflowed 👀
> 
> ![Screenshot 2022-01-17 at 17 29 06](https://user-images.githubusercontent.com/5887929/149806989-5e299ac4-480d-4d68-9134-1fb2da565038.png)

@yangwao yeah probably because we fixed height and width, I'll try increasing the height more
