### ISSUE TITLE
Go for unlicense type of license

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1906]
Hence we are having MIT License would be interesting as we are doing this as public good to switch to unlicense

https://twitter.com/jakerumbles/status/1482945484671049731?t=UiIrVN5hhl1e6RMV34lRfg&s=19

**Comment by roiLeo** [comment]
MIT is good otherwise [DBAD](https://github.com/philsturgeon/dbad/blob/master/LICENSE.md) 😉

**Comment by vikiival** [comment]
Let's stick with MIT
