### ISSUE TITLE
Move toggles from Simple Mint to settings

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1910]
We would like to make it as simple as possible for newcomers

### Move toggles from simple mint to be moved to settings like
- cover costs
- making carbonless NFTs
- use arweave (default off till we will deploy permafrost)

### Keep
- NSFW switch could stay
- Copyright ownership as well

### Bonus

Put submit button on the bottom

![image](https://user-images.githubusercontent.com/5887929/149917375-c218d580-b2f4-4862-9de3-bc56af6189d5.png)

**Comment by kkukelka** [comment]
on it!
