### ISSUE TITLE
Show which user has sent an emote to nft

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#1918]
### Is your feature request related to a problem?

I'm always frustrated when someone react on my NFT but I don't know who this is.

### Describe the solution you would like

I would like to see, on hover emoji, to show me wich identity reacted to the nft.

### Describe alternatives you have considered

Logic could be in `EmotionList` component & we can reuse `IdentityPopover`

### Screeenshots

Paste your vision

group it with #1897

**Comment by yangwao** [comment]
I mean, like this? That would be fantastic! 
![Screenshot 2022-01-31 at 12 43 29](https://user-images.githubusercontent.com/5887929/151788069-522cc8a8-2c07-49d6-b4e9-c59237e35065.png)

We can use the hover cards component to explore groups of that senders or show the first/last three in bubbles? We will have avatars later in the day tho.

Actually good to make with this issue would make group by emotes (by user preference) but I would add it as default if so as some spammmm
