### ISSUE TITLE
Spotlight columns sorting which would need to be fixed later

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1929]
Spotlight columns sorting which would need to be fixed later 

### Column not working
- `unique` => message: "syntax error at or near "ASC"" (reserved sql term)
- `uniqueCollectors` => message: "column \"uniquecollectors\" does not exist"
- `count` => message: "column "count" does not exist"

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/1924#issuecomment-1016310788_

**Comment by roiLeo** [comment]
The only one missing so far is `unique`

**Comment by roiLeo** [comment]
meanwhile this has been done, closing it
