### ISSUE TITLE
Embed Contributing.md & First_time.md to kodadot web

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1933]
I guess for a single point of truth (file) and SEO reasons, would be nice to embed currently existing Contributing.md and First_time to help easily onboard developers.

@roiLeo suggests https://content.nuxtjs.org/
The best would be probably to leverage the existing markdown module we are using? [vue-markdown-render](https://github.com/kodadot/nft-gallery/blob/main/package.json#L94) I guess?

routes could be 
- kodadot.xyz/contribute
- kodadot.xyz/first_time 

### Ref 
- #361
- #1075
- maybe https://github.com/wxsms/vue-md-loader ?

**Comment by prachi00** [comment]
@yangwao I'll check this

**Comment by prachi00** [comment]
Ill check this out

**Comment by mattreallycodes** [comment]
Let me know if help is still needed on this

**Comment by preschian** [comment]
Hi, I will take this
