### ISSUE TITLE
Time visit dog shelter

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1960]
Seems the review dog with eslint has some issues?
Probably time to fix our workflow and get the green check working:)
Happened on this PR 
https://github.com/kodadot/nft-gallery/pull/1952

![image](https://user-images.githubusercontent.com/5887929/150315635-32b763e7-87e7-4752-8287-19155cfcc976.png)

**Comment by roiLeo** [comment]
little angel gone too early, I can handle it, it's time to bring him back to the shelter.

![](https://i.pinimg.com/originals/84/96/67/8496676214f35c844b761f8b6e0b9a43.jpg)
