### ISSUE TITLE
Write article about our past, present and future storage options 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1965]
- With the recent merge start using https://estuary.tech instead of Pinata
- we will be introducing a way to store your NFTs using Arweave with using Permafrost 
- Compare traditional other NFT marketplaces using AWS S3 for storing pictures
- Explain way how we are pre-caching JPEGs and other multimedia over CloudFlare images
- How we keep it decentralized and distributed using IPFS & Filecoin (Estuary)
- How we keep it permanent using Arweave (PermaFrost)
- Highlight upsides of estuary and combination of PermaFrost (Arweave) for artist
- Conclusion
- Options for Skynet?

### Ref 
- https://github.com/kodadot/nft-gallery/pull/1925

**Comment by yangwao** [comment]
> I'll gladly take this. ✍️ @yangwao Medium workflow again right? (draft -> submit -> publish)

Yup, yes sir!

**Comment by yangwao** [comment]
Dropping link https://estuary.tech/ecosystem

**Comment by kkukelka** [comment]
> Dropping link https://estuary.tech/ecosystem as we are part of this graph! :)
> 
> ![image](https://user-images.githubusercontent.com/5887929/152535990-36332654-2fc5-47e5-86d6-388e0230e007.png)

sweet, thanks!! already close to the finish line on this one. opening a draft later today or tomorrow 👍

**Comment by kkukelka** [comment]
Draft link: https://medium.com/@kilian.kukelka/on-the-past-present-and-future-of-data-storage-at-kodadot-7634a0c32530

**Comment by yangwao** [comment]
@petersopko said he can proofread tho and better in English than me probably 😍

**Comment by petersopko** [comment]
@kkukelka I've made some changes (some grammar, some styling) and stored them here https://justpaste.it/7xxhg  
Feel free to use what you like and discard the rest.

**Comment by vikiival** [comment]
@kkukelka I would maybe link the cron for cf images (kodadot/bao) repo

**Comment by kkukelka** [comment]
@petersopko thanks for the proof-read -> implemented your feedback 😃 (btw you can leave notes and feedback directly in medium, maybe you need to create an account for it)

@vikiival linked to repo 👍 

@yangwao added cover image and submitted for publish 


![article-cover](https://user-images.githubusercontent.com/17953978/152681275-45ad1405-c4af-4261-b975-880b5881e959.jpg)

**Comment by petersopko** [comment]
> @petersopko thanks for the proof-read -> implemented your feedback 😃 (btw you can leave notes and feedback directly in medium, maybe you need to create an account for it)

np. ah, my bad, I'll try to use medium next time :)

**Comment by yangwao** [comment]
> ![article-cover](https://user-images.githubusercontent.com/17953978/152681275-45ad1405-c4af-4261-b975-880b5881e959.jpg)

beautiful! I would also add Filecoin & Estuary logo hence we are using it :)

Overall is perfect! 

- Once the hero is updated in the article
- submit it to publication
-  I can approve and get back with a link here 
- so you can make PR with a link to README.md https://github.com/kodadot/nft-gallery/blob/main/README.md#writings-on-development-%EF%B8%8F
- and I can proceed payout )

**Comment by kkukelka** [comment]
i think i just accidentally published ...

**Comment by vikiival** [comment]
Really nice article @kkukelka 🚀

**Comment by kkukelka** [comment]
> Really nice article @kkukelka 🚀

much appreciated 😘
