### ISSUE TITLE
Integrate SubSocial comments to KodaDot

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#199]
To promote ecosystem dogfooding in Polkadot/Kusama environment we could show comments under gallery items.

**Comment by siman** [comment]
I would love to have a JS library for Subsocial embedded comments that would allow anyone to attach comments to any web site / page. 

I have been thinking about using Shadow DOM + Web Components for maximum flexibility.

What do you think?

**Comment by vikiival** [comment]
From @siman 

[this is our API package](https://github.com/dappforce/subsocial-js/tree/master/packages/api)

[this is an example of how we use it on our backend](https://github.com/dappforce/subsocial-offchain/blob/master/src/connections/subsocial.ts)

[this is usage on web UI](https://github.com/dappforce/subsocial-web-app/blob/w3f-grant2/src/components/substrate/SubstrateContext.tsx)

**Comment by XyloDrone** [comment]
If it becomes possible one day to implement this than it should  be embeded as such in the artist profile: 
![Screenshot 2021-05-18 at 23 57 37](https://user-images.githubusercontent.com/84407059/118733786-e08bca80-b834-11eb-9e1e-a7093807b8e7.png)

**Comment by yangwao** [comment]
yup this is done.
Continue to feedback #498
