### ISSUE TITLE
Mint not work "RefferenceError: Networ Error"

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#2002]
### What happened?

I try to mint a 3D file (GLTF) and I always get an error message... "RefferenceError: Network Error"
![obrázok](https://user-images.githubusercontent.com/81104034/150502021-f7246400-173e-4f6c-bc83-bbe86dda9f17.png)

### Please reproduce in steps

I send video

https://user-images.githubusercontent.com/81104034/150502176-2a7297f0-9c48-47b0-83e4-16fe2f14ce97.mp4

### Expected Behavior

I've expected ...

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

![obrázok](https://user-images.githubusercontent.com/81104034/150503070-60cb667b-eae0-4826-89f1-6d0bc01a66cb.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
can you try if minting works on https://beta.kodadot.xyz for you?
We've pushed #2030 but doubt it was some fix there.
One thing is that it might your browser did not refresh new content 👀 As something like this was been already fixed on Simple mint

**Comment by jkdizajn** [comment]
> can you try if minting works on https://beta.kodadot.xyz for you? We've pushed #2030 but doubt it was some fix there. One thing is that it might your browser did not refresh new content 👀 As something like this was been already fixed on Simple mint

Same problem

https://user-images.githubusercontent.com/81104034/150676319-ffa89ea7-2017-42d2-9692-628f069628d2.mp4

**Comment by jkdizajn** [comment]
Send log console
![obrázok](https://user-images.githubusercontent.com/81104034/150678899-34f0b573-81ae-4a7e-8f84-8e223be8119c.png)

[console-export-2022-1-23_13-40-19.txt](https://github.com/kodadot/nft-gallery/files/7920491/console-export-2022-1-23_13-40-19.txt)

**Comment by yangwao** [comment]
Seems it's related to Firefox, in Chrome it works for me.

**Comment by jkdizajn** [comment]
> Seems it's related to Firefox, in Chrome it works for me. We are still investigating

Ok i found a bug. 
The problem is that KodaDot can't upload 3D files. I didn't think it was a problem at all. As soon as I uploaded something else, in this case SVG, everything went fine by default. 

Please check it out. 
Here are the 3D files I wanted to mint (Github not support GLTF files):
https://send.vis.ee/download/412eca554193e329/#TtBNG2KdcQ4oDkMF49oUDg

**Comment by yangwao** [comment]
@jkdizajn I guess this one was meanwhile solved?

**Comment by jkdizajn** [comment]
> @jkdizajn I guess this one was meanwhile solved?

I'm not sure, but I think it already works

**Comment by yangwao** [comment]
perfect!
