### ISSUE TITLE
Initial tests framework

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2006]
Everytime we upgrade something, we break something else, somehow, sometime, really unintentionally.

Would be nice to have first **end to end** 
tests written for basic functionality.

Make it as GitHub Action, hence we have it for free.
Probably to run on every pull request probably.

### test cases
- simple mint
- actions (buy, list, consume, send, unlist)
- visual feeds - if feeds like collections, collection detail, gallery item, gallery feed loads content
- data feeds - spotlight, series-insight

### ref
- kodadot/minimark

**Comment by rchovatiya88** [comment]
![Untitled_ Jan 28, 2022 10_05 PM (1)](https://user-images.githubusercontent.com/16197756/151645182-3e447d8b-8062-4dbe-975f-94f51b0ff1a6.gif)

initialing cypress.io e2e test framework 
- Intergration tests 
- Regression tests
- headless tests (run test in CI pipeline)
- Create a pass/fail report

**Comment by petersopko** [comment]
partially solved in 

- #3451 

following up in:

- #3681 
- #3680
