### ISSUE TITLE
Group by NFTs by same picture/metadata

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#201]
<img width="1113" alt="Screenshot 2021-03-17 at 20 41 24" src="https://user-images.githubusercontent.com/22471030/111528271-3e326680-8761-11eb-9aea-db74041e4a6e.png">

**Comment by yangwao** [comment]
> Some will misinterpret this as extra promotion of a specific artist/work also. Just a thought & hope it helps! by Obxium

**Comment by yangwao** [comment]
meanwhile done, continue to #232
