### ISSUE TITLE
KodaDot v0 API 📦

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2013]
To better integrate the stuff we've done in KodaDot, 
we need provide external API to welcome more integrations 

### Intents
- we would need an abstract package with breeze installation to your hackathon app
- easy understand readme and instructions
- great manual (gitbook documentation?)
- future-proof compatible `/v0` - `/v1` &c 
- least breaking changes if possible
- put into [awesome-kodadot](https://github.com/kodadot/awesome-kodadot//)

### Goal
- we would publish it as npm package
- incentivize usage of the package for the hackathon

### Ref
- #2077 -- @vikiival is making sub-api with new shiny stuff

**Comment by yangwao** [comment]
- pulling auction data
- make offer data from BSX would be nice

**Comment by vikiival** [comment]
> pulling auction data

auction not implemented

> make offer data from BSX would be nice

Marked in https://github.com/vikiival/kodapi/issues/4 sir

**Comment by JustLuuuu** [comment]
https://github.com/vikiival/kodaquery
