### ISSUE TITLE
pre-loader pixelized ms-dos candidates

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2014]
Our current preloader was generated https://loading.io/spinner/infinity/-infinity-dash-line-curve-rotate-cycle
Marketplace https://loading.io/spinner/

### Criteria
- something small in terms of size 50-70kb, lower better
- pixelizated
- SVG best or any savvy format for low bandwidth users

### Candidates
- https://loading.io/spinner/dna/-dna-biology-rna-biohazard-spiral-helix-spin-ball
- https://loading.io/spinner/atom/-orbit-atom-electron-proton-circular

### Ref
- https://github.com/kodadot/nft-gallery/issues/1353#issuecomment-1019166249

**Comment by jkdizajn** [comment]
> 

Hey, what do you mean by "pixelated" - as a graphic style, but as a graphic output? 
because SVG output and pixelated are mutually exclusive :P 
what should be the resolution in px?

I can suggest something if it's still up to date....

**Comment by yangwao** [comment]
Yyash made one which seems about good one, but if you want to make another one, I guess we can have two different preloaders lol 

![Comp_1_1_1](https://user-images.githubusercontent.com/5887929/150976686-7b7724d5-f6c9-42dc-ab22-3bc1bb933611.gif)

**Comment by Dexxx3** [comment]
![data](https://user-images.githubusercontent.com/95619333/150981692-c143d6b6-0287-4eaf-a7e4-594ea32f2b79.svg)

**Comment by Dexxx3** [comment]
![Comp 1_1 (1)](https://user-images.githubusercontent.com/95619333/150982241-8fac9d06-9c68-4870-87bd-c77fe7a62196.gif)

**Comment by jkdizajn** [comment]
Here is my animated SVG 
**JS version, transparent_bg, responsive**
![KodaDot_preloader_js_transparent_bg_responsive](https://user-images.githubusercontent.com/81104034/152652751-b6f03ff9-c749-486e-abdd-7300d72a4077.svg)

**CSS version, transparent bg with responsive**
![KodaDot_preloader_css_transparent_bg_responsive](https://user-images.githubusercontent.com/81104034/152652777-c74f6b42-8ba7-456c-8e14-87a4ae741a8a.svg)

**and CSS version with black bg, responsive**
![KodaDot_preloader_css_black_bg_responsive](https://user-images.githubusercontent.com/81104034/152652913-75284ca3-4b71-4fb8-8f66-01022cc217c3.svg)

**Comment by yangwao** [comment]
> Here is my animated SVG 
> **JS version, transparent_bg, responsive**
> ![KodaDot_preloader_js_transparent_bg_responsive](https://user-images.githubusercontent.com/81104034/152652751-b6f03ff9-c749-486e-abdd-7300d72a4077.svg)
> 
> **CSS version, transparent bg with responsive**
> ![KodaDot_preloader_css_transparent_bg_responsive](https://user-images.githubusercontent.com/81104034/152652777-c74f6b42-8ba7-456c-8e14-87a4ae741a8a.svg)
> 

Yas let's have this as preloader, transparent version, one JS doesn't animate on mobile tho 

Maybe @kkukelka will be around 😜

**Comment by kkukelka** [comment]
> Yas let's have this as preloader, transparent version, one JS doesn't animate on mobile tho
> 
> Maybe @kkukelka will be around 😜

Will do!

**Comment by jkdizajn** [comment]
Speed UPDATE

- added rotation 

- enlarged tail

- reduced speed 
![Update_KodaDot_preloader_css_transparent_bg_responsive](https://user-images.githubusercontent.com/81104034/152674765-3eb1329c-0610-4376-8ed0-569ae67923d2.svg)
![Update_KodaDot_preloader_css_black_bg_responsive](https://user-images.githubusercontent.com/81104034/152674766-b403992a-0cfe-4dfb-a241-5a7091367723.svg)

**Comment by kkukelka** [comment]
> Speed UPDATE
> 
> * added rotation
> * enlarged tail
> * reduced speed
>   ![Update_KodaDot_preloader_css_transparent_bg_responsive](https://user-images.githubusercontent.com/81104034/152674765-3eb1329c-0610-4376-8ed0-569ae67923d2.svg)
>   ![Update_KodaDot_preloader_css_black_bg_responsive](https://user-images.githubusercontent.com/81104034/152674766-b403992a-0cfe-4dfb-a241-5a7091367723.svg)

could you create a version where you trim the empty space as much as possible?

**Comment by jkdizajn** [comment]
> could you create a version where you trim the empty space as much as possible?

HERE is
![Update_2_KodaDot_preloader_css_transparent_bg_responsive](https://user-images.githubusercontent.com/81104034/152676806-744da098-8c4d-4240-acb9-6c817b4f0b6a.svg)

**Comment by kkukelka** [comment]
> > could you create a version where you trim the empty space as much as possible?
> 
> HERE is 

perfect, thanks!
