### ISSUE TITLE
Rework landing page a bit - add recent mints for sale

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2018]
### Spec
- remove from footer substack, telegram, reddit (as we don't maintain them right now) Pic1
- add to footer https://docs.kodadot.xyz as Documentation 

```graphql
query lastListed {
  events(limit: 20, where:{ interaction_eq: LIST }, orderBy: blockNumber_DESC) {
    meta
    nft {
      name
      meta {
        image
      }
    }
  }
}
```

![Screenshot_2022-02-06-20-11-41-11_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/5887929/152697428-9eeaa150-4c8b-4747-aa67-a699bd13e1f1.jpg)

###
Being done in #2172 
- [x] add shadows to the buttons [Create,...,What Are NFTs] -- buttons are gone meanwhile
- [x] copy box Recent Sales over and add showing newest NFTs for sale in the same format
- [x] put inside the last three NFT items previews where sales have happened once the user came to the site
- [x] collection detail could be like is at gallery feed, check pt3 
- [x] in the recent sales box add the text "Recently Sold" so newcomers will know
- [x] remove CTA text from homepage__box, make it extended, add shadow there as well
- [x] remove background
- [x] clicking on NFTs will lead you to NFT item detail 

pt1
![image](https://user-images.githubusercontent.com/5887929/150638283-8b8c4f77-8896-4a1c-88b1-b50e3d42c9c1.png)

pt2
![image](https://user-images.githubusercontent.com/5887929/150638316-a5d40025-70f1-4fc4-94cc-da0ce4587ae1.png)

pt3
![image](https://user-images.githubusercontent.com/5887929/150638381-a9e40e98-5f3a-4fa0-8fd4-92db0547b057.png)

### Ref
- #876 bit start for this
- #1596 
- https://github.com/kodadot/nft-gallery/issues/2180

**Comment by vikiival** [comment]
```graphql
query lastSold {
  events(limit: 3, where:{ interaction_eq: BUY }, orderBy: blockNumber_DESC) {
    meta
    nft {
      name
      meta {
        image
      }
    }
  }
}
```

**Comment by prachi00** [comment]
is there a design for this?

**Comment by yangwao** [comment]
> is there a design for this that we can reference?

Not any, but I can be helpful to guide you! :) 

![](https://tenor.com/view/wizard-magic-wand-dance-changing-colors-gif-17883390)

**Comment by prachi00** [comment]
@yangwao 1st point, ` remove background `  from where exactly?

**Comment by yangwao** [comment]
> @yangwao 1st point, `remove background` from where exactly?

From `/`, I've now realized that I've already removed it at screenshot but haven't committed it tho :) 
So yeah that big background picture could be removed.

**Comment by prachi00** [comment]
@yangwao can you explain this point as well
`remove CTA text from homepage__box, make it extended, add shadow there as well`

**Comment by XyloDrone** [comment]
Hey everyone, landing page design was here... 
https://www.figma.com/file/GeVzZKVORd9L8kAWrlKtZv/KodaDot-UX%2FUI?node-id=0%3A1

No feedback was left so far.

**Comment by prachi00** [comment]
@yangwao @XyloDrone should I reference this then?  seems there are lot more changes than mentioned tho

**Comment by XyloDrone** [comment]
> @yangwao @XyloDrone should I reference this then? seems there are lot more changes than mentioned tho

I suppose we'd need to wait for @yangwao to comment on the design, as mentioned there wasn't any feedback so far so I'm not sure.

**Comment by XyloDrone** [comment]
> @yangwao @XyloDrone should I reference this then? seems there are lot more changes than mentioned tho

Seems like we are good to go with this one, Figma valid for reference :D + some extras that have been mentioned after :D

**Comment by XyloDrone** [comment]
@prachi00 , @yangwao I don't think it's very optimal for UX to have a carousel on the landing for displaying NFTs, any chance we could consider having 2 rows instead and "View all" button as per design? I think this is much more user friendly and it requires less interaction to view NFTs.

**Comment by prachi00** [comment]
@yangwao this ticket needs more clarity as to what exactly is to be done

**Comment by yangwao** [comment]
Current state 
![image](https://user-images.githubusercontent.com/5887929/153853351-baff99a5-e140-4f59-8399-929c746ab849.png)

- Recent mints are gone, subsquid issue seems, we are investigating, but majority people remember it was there and working :D 
- I've updated the rest of the actionable tasks for this issue

- yes we had quick call w @XyloDrone about this and we need breakdown components and will be adding curation feed with hero probably  and same fashion most bought NFTs https://github.com/kodadot/nft-gallery/issues/2180

> I don't think it's very optimal for UX to have a carousel on the landing for displaying NFTs, any chance we could consider having 2 rows instead and "View all" button as per design? I think this is much more user friendly and it requires less interaction to view NFTs.

Yes and no. Having 2 rows is optimal for desktop, but despite we will want to target more mobile users till we have dedicated mobile app, we need some sacrifice. Like I was thinking for mobile have maybe instagram/fleet like component and thus we don't need horizontal, who knows, I'm really not UX/UI mobile, I'm just trying optimize way better. On this hand, would be actually cool to survey existing collectors using KodaDot what they think, or maybe where they see defects in Singular and we can take advantage in form of UX :)

I mean, @XyloDrone  let's create/open issue to research and comparing best landing pages out there of NFT marketplaces? We can fund it if it could be done quickly! It would help us make way better decision based on data rather on intuition.

**Comment by prachi00** [comment]
@yangwao yes I will be working on this

**Comment by XyloDrone** [comment]
@yangwao Understood. 
I've looked at quite a bit of NFT platforms for the purpose of redesigning Koda so I can post some of these up. 
Shall I submit screenshots and notes on both desktop and mobile?

**Comment by yangwao** [comment]
last bits finished in #2412
