### ISSUE TITLE
Show denomination in $ in transaction fees without clicking

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2022]
Things need to be polished in simple mint

- add 0.1 steps into the price 
- show transaction fees denomination in KSM and dollars without clicking
- probably watch for new input every 3-5 seconds? 
- move transaction fees label under button [click to create nfts]

![image](https://user-images.githubusercontent.com/5887929/150639164-65a32284-ec6e-4742-8115-ce98837908a0.png)
![image](https://user-images.githubusercontent.com/5887929/150639338-89168095-09d0-43a1-9f2f-39f8672c971e.png)

**Comment by prachi00** [comment]
@yangwao I'll do this
