### ISSUE TITLE
Search on mobile v1.1

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2025]
What's about the mobile 📱 interface for search? 

![Screenshot_20220122-181403.jpg](https://user-images.githubusercontent.com/5887929/150648738-0bd89d25-3db1-4760-98be-de4573f29aab.jpg)

I guess for 📱 we should do a whole overlay, suggestions by google

![Screenshot_20220122-181650.jpg](https://user-images.githubusercontent.com/5887929/150648806-edb5be88-1856-42f4-afac-8078d05bbce1.jpg)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/1952#issuecomment-1019312157_

**Comment by petersopko** [comment]
I'd like to do this one.

**Comment by petersopko** [comment]
Looks like this one is resolved in #1952, please correct me if I'm wrong
![image](https://user-images.githubusercontent.com/73316633/150836128-88ad21c8-2139-4882-ac8e-dd38b67f0a17.png)

**Comment by yangwao** [comment]
> Looks like this one is resolved in #1952, please correct me if I'm wrong ![image](https://user-images.githubusercontent.com/73316633/150836128-88ad21c8-2139-4882-ac8e-dd38b67f0a17.png)

 <img src="https://media1.giphy.com/media/RMwqvqV9RDOgr3XTDw/giphy.gif"/>

yes and no

check the second picture, on mobile, it should look different, like open google.com on mobile, it should be overlay on whole screen for best results

**Comment by petersopko** [comment]
> check the second picture, on mobile, it should look different, like open google.com on mobile, it should be overlay on whole screen for best results

okay, I'll look into it!
