### ISSUE TITLE
Carefully remove unused components 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2031]
https://www.npmjs.com/package/vue-unused-components-checker

I've ran 
```
npx check-unused-comp .
```

but seems some components we are using, probably doesn't handle nuxt well? Are we using all from pages and well linked?

Anyway, let's check which we can drop as aren't used anymore.
![image](https://user-images.githubusercontent.com/5887929/150676794-f04913ac-d11c-4fe4-959d-57e43f2db120.png)

**Comment by prachi00** [comment]
@yangwao I'll check this

**Comment by prachi00** [comment]
yeah its not showing correctly since some of the components such as `<CookieBanner` are not imported but being used 
instead of this, I'll check manually all the components and remove the unused ones, might take a little time tho
