### ISSUE TITLE
Are we using markdown-it library? If not, let's remove it

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2036]
I'm confused, by search result we are using markdown-it but it's not in package.json? 

If it's not used, let's remove it.

Probably we are using `vue-markdown-render`

### Ref
- https://github.com/kodadot/nft-gallery/search?q=markdown-it
- https://github.com/kodadot/nft-gallery/blob/main/package.json#L105
- https://github.com/kodadot/nft-gallery/pull/2034

**Comment by roiLeo** [comment]
We're using it currently to render markdown from `.json` in langDir files cf. https://github.com/kodadot/nft-gallery/blob/83f8ff91d30437023985ea4847ea597d7e73eb83/utils/config/i18n.ts#L8
ref in #1614 for i18n plugin config

**Comment by kkukelka** [comment]
we still need it. re-checked in #2096

**Comment by roiLeo** [comment]
closing this for now since we need it, might be time to check [@nuxt/content](https://content.nuxtjs.org/) for #2692
