### ISSUE TITLE
Check if we need @vue/cli-plugin family 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2037]
@vikiival said it's bundled in @nuxt packages tho, let's review and remove unnecessary packages

https://github.com/kodadot/nft-gallery/blob/main/package.json#L109

```json
 "@vue/cli-plugin-babel": "^3.12.1",
    "@vue/cli-plugin-pwa": "^4.5.15",
    "@vue/cli-plugin-typescript": "^4.5.15",
    "@vue/cli-service": "^4.5.15",
```

### Ref
- https://github.com/kodadot/nft-gallery/pull/2035

**Comment by prachi00** [comment]
@yangwao I;ll do this
