### ISSUE TITLE
Ambassador program

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#2040]
### Is your feature request related to a problem?

We'd like to onboard some ambasadors from other nations to take care of native-speaking users. Since we have some channels in other languages that need moderation, we definitely want to work on this idea. 

### Ambassador would do:

- take care of native users in your language
- translate KodaDot articles to your native language
- Build your local community around KodaDot and Dotsama ecosystem
- Provide support with KodaDot UX/UI (minting, faq)

### Rewards:

- I would like to work on this idea as this is (probably) not full time work and the reward for this should be accurate to time spent, activity and so on. 
- What are your thoughts of rewards for ambasadors?

### Requirements

- Basic knowledge of KodaDot workflow
- Possibly prefered to already have some kind of community/twitter followers from your country
- Activity
- Organic interest for NFTs on DotSama and KodaDot in general

**Comment by yangwao** [comment]
Can close it when we have it here or is there some difference missing?

https://docs.kodadot.xyz/ambassador-program/ambassador-intro#the-opportunity

**Comment by cryptodamsky** [comment]
Yup this is finished :)
