### ISSUE TITLE
Replace Sort & Filter text with Filter icon

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2049]
- Replace sort filter text with filter icon https://fontawesome.com/v5.15/icons/filter?style=solid
- put it filter icon in front of search 
- on mobile, put icon filter on the same line as pagination to save precious vertical space
- put result numbers (position, total) in the border, check pic 3, make text smaller, check for mobile and other responsive sizes as well 
- turn **buy now** on by default
- remove the whole big border around search,filter,total,pagination,random like is on collections and make it align with container of cards, see pic 4
- make search box $primary color and on focus make it white
 
![image](https://user-images.githubusercontent.com/5887929/150752345-10a88faa-6cea-4ac7-bbe0-c14677df4261.png)

![image](https://user-images.githubusercontent.com/5887929/150752177-a7188aae-4e41-4a50-b0d4-b6cb902b204a.png)

![image](https://user-images.githubusercontent.com/5887929/150753720-fb815bcf-166e-4f9b-97fa-6b64b13d4128.png)

![image](https://user-images.githubusercontent.com/5887929/150755159-b436779e-3f22-47f8-a6fd-6773e40bb6d2.png)

### Ref
- https://github.com/kodadot/nft-gallery/issues/2053 continue

**Comment by kkukelka** [comment]
On it!
