### ISSUE TITLE
Make fixed search component at collection detail if nothing is on sale

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2051]
On collection when there is nothing on sale, it hops **buy now** here and there and missing pagination breaks the melody

Probably make it fixed so it can stay at one place?

EDIT, make **Buy now** disabled if there is nothing on sale and it's even easier fix as doesn't make sense to show user empty screen at all 

Test at https://deploy-preview-1952--koda-nuxt.netlify.app/rmrk/collection/76df001719ad77e748-LZRO?search=&listed=false 

(bug works until author making something on sale)

https://user-images.githubusercontent.com/5887929/150760135-12c0fec2-8ab5-42ce-b3f8-da5e57cc718c.mov

**Comment by prachi00** [comment]
@yangwao I'll check this

**Comment by yangwao** [comment]
> @yangwao I'll check this

i've updated issue, best would be query collection if there is something on sale and if nothing, make buy now disabled
