### ISSUE TITLE
Unify collection detail and collections view with $primary

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2053]
### At collection detail 
- Make tab line pink, on selected it can be under text white and selected text can be kept pink
- filter border $primary
- search box $primary

![image](https://user-images.githubusercontent.com/5887929/150760940-07156a51-84fc-4507-a30c-e46ced98c68c.png)

Test at https://kodadot.xyz/rmrk/collection/d23ec8e0b831b65917-LTIDO?search=&listed=false
### Collection
- same $primary for filter & search bar

![image](https://user-images.githubusercontent.com/5887929/150761485-dcdea2dd-23c1-4782-b64b-590d443aa5d8.png)

**Comment by prachi00** [comment]
@yangwao I'll do this one

**Comment by yangwao** [comment]
<img src="https://media0.giphy.com/media/l3vRcttCynxJoxIrK/giphy.gif"/>
