### ISSUE TITLE
When you go directly to the unique asset the app fails

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2058]
### What happened?

When you visit directly ani Statemine art directly
[Anatomy of a cryptocanary](https://kodadot.xyz/statemine/gallery/0-2)
The app will fail

### Please reproduce in steps

1. Visit any statemine detail [Anatomy of a cryptocanary](https://kodadot.xyz/statemine/gallery/0-2)

### Expected Behavior

The app should show the art

### Screenshots

<img width="1676" alt="Screenshot 2022-01-24 at 12 24 53" src="https://user-images.githubusercontent.com/22471030/150774652-ebd15f9f-8138-4528-89d7-725ff0843b60.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
It has loaded well from [this netlify preview link](https://deploy-preview-2057--koda-nuxt.netlify.app/statemine/gallery/0-2)
![Screenshot 2022-01-24 at 14-57-06 KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/150796221-510212c9-9bd2-4930-9962-c24ba65e32b7.png)

Don't work locally but when I check the logs I see some differences
- **localhost**: 
```
API-WS: disconnected from wss://kusama-statemine-rpc.paritytech.net: 1015:: TLS Handshake
```
- **netlify preview**: 
```
API-WS: disconnected from wss://pub.elara.patract.io/statemine: 1001:: Going Away
```
maybe it's related I dunno
