### ISSUE TITLE
Use only border-top on control buttons/actions

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2059]
Time to lightweight our UI for easier adoption.

- Let's remove the border and keep only border-top like on pic1
- Use border-top on emojis as well 
- remove the white shadow from accordion/cards at price chart and history
- rename "Price Chart" -> "Chart"
- at history button, language and profile button as well, pic4

Test case https://kodadot.xyz/rmrk/gallery/11079135-00da54310732f6437d-QBCVI-ONI_10125-0000000000000016
![image](https://user-images.githubusercontent.com/5887929/150778129-6fab17d8-89bb-44a2-9cb0-37d1fab71fe8.png)
![image](https://user-images.githubusercontent.com/5887929/150778526-70b228f2-9c05-442a-83ac-0959dc34db68.png)
![image](https://user-images.githubusercontent.com/5887929/150778905-8c545a4e-dd4e-4d24-9161-473cd56870e3.png)
![image](https://user-images.githubusercontent.com/5887929/150779457-2dc5b168-5bda-447d-9064-35e4ae83c0b0.png)

**Comment by prachi00** [comment]
@yangwao I;ll work on this

**Comment by prachi00** [comment]
@yangwao in 3rd point, what do you mean by white shadow? I cant see any
