### ISSUE TITLE
Add ability to send same emoji at nft item detail

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2060]
When there is already emoji at nft, you want to let the user click on the same to send it 

![image](https://user-images.githubusercontent.com/5887929/150779285-b24e973d-9820-45c2-a176-3d6e2ce8be5c.png)

Test case - https://kodadot.xyz/rmrk/gallery/10843795-0a8ce195286c168f19-DONKEY-DONKEY_GANG_473-0000000000000473

**Comment by kkukelka** [comment]
I'll give it a look!
