### ISSUE TITLE
Rework discord entry experience for newcomers

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#2061]
### Is your feature request related to a problem?

This is how it actually is, to get to the server for a new user.

![step1](https://user-images.githubusercontent.com/92786519/150782485-94fe14bf-1e1e-4bb1-a357-aa7b9e73e0bb.png)

Accept invitation

![step2](https://user-images.githubusercontent.com/92786519/150782499-447bf832-1768-4c73-997e-9c711839d3e2.png)

Click "Complete"

![Step 3](https://user-images.githubusercontent.com/92786519/150782514-8222911a-dfd5-460d-9bdc-3ff58ec0c58e.png)

Scroll through this list

![step4](https://user-images.githubusercontent.com/92786519/150782518-5f4d674f-f484-48db-bbdb-87826549e628.png)

More scrolling

![step5](https://user-images.githubusercontent.com/92786519/150782523-890b7883-a1f4-46c2-a28d-04d4b4a9031e.png)

Tick the box and continue

![step6](https://user-images.githubusercontent.com/92786519/150782538-3e8f0cc6-558a-47d0-a08b-6a39733766f0.png)

meanwhile, message comes from carl-bot, yet the process is not done yet
- contest-preloader visibility will be denied (bug)

![step7](https://user-images.githubusercontent.com/92786519/150784610-65f0c483-10f3-4ebf-86d2-e3e42ebbb466.png)

Go to k-verify-here
By reacting to the message, server opens for you.

![step 8](https://user-images.githubusercontent.com/92786519/150784694-6d6d7214-981c-4c98-8b17-7b61247247fc.png)

The verify-here channel disappears(on purpose) and only k-overview is visibe. By default, those verified can only see k-overview channel and the verification channel is visible only for moderators and those who didn't verify yet.

- Bot automatically gives all verified a Wagmi role and they can freely continue.

--- 

**Where the heck is the welcome screen? I'd actually love to keep/implement this one but it seems it doesn't even show to new user? (since we manipulated with roles etc, ofc it doesnt show)**

![ws](https://user-images.githubusercontent.com/92786519/150786806-2e121b90-0126-4adf-b6e8-0f652eb15b19.png)

-------

My opinion is, having so many bullet points before you enter the server is:

- a bit overwhelming and since most of the users behave well, those who don't care won't read them 
- it is a mix of promoting our functions and rules - which is confusing
- those who usually behave well,(probably, judging by me) won't read all of them because after some time there's a basic behavioral structure established on most of discords therefore it's obvious that promoting your discord server on someone's server is not permitted.

Also, having so many links right away on the welcome page does the opposite of what we want to achieve. 

## Membership screening

- Remove obsolete and obvious rules
- Less bullet points, less links (it's confusing to mix rules with functions)
- Focus on **quick** and **comfortable** entrance to the server from where one can navigate through links in k-overview
- Would keep it to max 5-6 basic rules, skip the rest

## Welcome message from carl-bot

- Remove/edit the message from Carl-bot ( i personally vote for remove )

## Welcome screen

- fix welcome screen

## Verification message 

- Work a little bit more on the verification-reaction message so it's obvious where to click and secure a fast and understandable access to the server.

### Connection to other issues:

- #1445 
- #2020

**Comment by yangwao** [comment]
>  ![image](https://user-images.githubusercontent.com/5887929/151376295-eb275bc9-c391-446e-b91e-7ba046dfe7d3.png)

Probably we can remove those channels who has warnings?

> a bit overwhelming and since most of the users behave well, those who don't care won't read them

yes, we can significantly reduce them

**Comment by cryptodamsky** [comment]
Current state: 

- Disabled the message from carl
- Cut down the Membership screening

https://user-images.githubusercontent.com/92786519/151990757-959b0615-40b7-4b13-83ae-a34e8d9a2911.mp4

Followup: 
- #2020 
- [ ] Find out why welcome screen is not working

**Comment by cryptodamsky** [comment]
- New customization channel is in play for some time, working fine.

![custom](https://user-images.githubusercontent.com/92786519/156120492-0a2e8749-a550-4bf6-b0cc-95cb2abd3b5a.png)

- updates regarding discord onboarding are now in ok state, phase 2 would be definitely considering some complete re-structuralizaton.
