### ISSUE TITLE
Generative frameworks to implement

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2065]
We've been longer in talks implementing p5.js and others so this would serve as a discussion on which frameworks we want to implement?
Best if they run in the browser.
No inherently needs to be visual, could be for audio generation as well

- #2164 
- https://p5js.org/ (a really popular one)
- https://github.com/sepandhaghighi/samila
- https://levelup.gitconnected.com/generative-art-3-fundamental-concepts-to-get-you-started-44205dae167b
- https://www.fxhash.xyz/articles/guide-mint-generative-token
- ???

### Ref
- https://medium.com/processing-foundation/open-call-p5-js-editor-lead-fellowship-1c050efa4cb5

**Comment by JustLuuuu** [comment]
done
