### ISSUE TITLE
Scheduled mints

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#207]
I mean there are scenarios where artists want to plan the release of particular mints on some occasion and want to prepare stuff.

Add calendar entry for that as well

![image](https://user-images.githubusercontent.com/5887929/154075940-24fb8a44-d442-44cd-9f34-bd1e0eb01565.png)

**Comment by XyloDrone** [comment]
Something to add in the future, artists can choose to mint now or later, see image, add to minting process 
![Screenshot 2021-05-18 at 23 54 20](https://user-images.githubusercontent.com/84407059/118733662-9acf0200-b834-11eb-83f8-39c2258e0940.png)

**Comment by Miyazm** [comment]
hiya, I was wondering if a prepared minting could be implemented.
that was my post in Kodadot tlg community :"wanna mint countdown nft when time reach the wanted day & time “celebration day” an nft could be sent automatically to one or several persons"
 
That would be amazing to have such features :D

**Comment by yangwao** [comment]
We will roll it with drop page. If you want to access this feature, DM us at https://t.me/kodadot_eco
