### ISSUE TITLE
it should be showing m name instead of my address

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#2070]
### Is your feature request related to a problem?

/

### Describe the solution you would like

it should be showing m name instead of my address, and not just there, but in all the popups 

### Describe alternatives you have considered

/

### Screeenshots

/
![01](https://user-images.githubusercontent.com/71472224/150875767-d8994eaf-58c2-4f34-bc1c-09d8c01d5f23.jpg)

**Comment by rashikaqureshi** [comment]
Do you have some api call for this . can you tell the steps how to reach here

**Comment by yangwao** [comment]
It should use identity we use elsewhere

**Comment by Jarsen136** [comment]
I will fix it!
