### ISSUE TITLE
Global profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2071]
Probably we would need make global profile once we will support more chains.

Ie rmrk, bsx, moonriver, statemine, &c

Agregate profile for each of one.

Tricky would be which address to use.. 42?

**Comment by XyloDrone** [comment]
A few things to consider: 

- choose chain / account when connecting wallet 
- select which chain to browse on in explore and profile

**Comment by yangwao** [comment]
Maybe it's coming this szn 😉

- https://github.com/kodadot/research/issues/66
