### ISSUE TITLE
KodaDot@Next w/ Vue3 Vite and Nuxt3

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2081]
This is mostly to set KodaDot3 MVP and research issues to explore possibilities as we want to upgrade further to the Vue3 and gain all beautiful features there.

- we would like to see a new working MVP of Kodadot using recent Vue3, Vite and Nuxt3 
- this issue is for experienced developers who know what they are doing
- probably push it to directory `kodadot3/` in root with instruction to run it.
- write down a breakdown of which components would not work and which would need to be upgraded or replaced
- write down a breakdown of which packages would not work and which would need to be upgraded or replaced with modern ones or alternatives
- all weapons are allowed

### Ref
- #2013 
- As webpack4 used by Nuxt is ancient ("@types/webpack": "^4.41.32") we want to upgrade anyway 
- https://github.com/polkadot-js/api/issues/4500#issuecomment-1022189111 
- nuxt/framework#2013

**Comment by vikiival** [comment]
I tried to make an MVP of [Nuxt bridge](https://v3.nuxtjs.org/getting-started/bridge/) which can be the best approach for us 

<img width="965" alt="Screenshot 2022-01-26 at 17 18 34" src="https://user-images.githubusercontent.com/22471030/151202623-d9b1faff-4b0b-493a-a038-5bdaf395c831.png">


but stucked until this is not resolved
https://github.com/nuxt/framework/issues/2934

**Comment by yangwao** [comment]
Once is done 
- #2692 
Ref
- #2690

**Comment by yangwao** [comment]
For fun and profit, continue to 
- #4704 
- #2690 
- https://github.com/kodadot/nft-gallery/issues/4750

**Comment by roiLeo** [comment]
continue to #2690
