### ISSUE TITLE
open graph protocol url

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#2086]
### What happened?

- og url is referencing to localhost instead of https://kodadot.xyz  
- as a result, for example, when sharing a link on twitter, result is this:  
![image](https://user-images.githubusercontent.com/73316633/151215156-4be6d204-76ef-4131-bb40-3e6c2307246e.png)

### Please reproduce in steps

check elements and metatags in head

### Expected Behavior

i'd expect it to be pointing to right image source which shows this 
![image](https://user-images.githubusercontent.com/73316633/151215538-9cb38bc5-e08a-4f45-9c04-ee9b7c48ab8b.png)
from this url:
https://kodadot.xyz/kodadot_card_root.png

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

![image](https://user-images.githubusercontent.com/73316633/151214790-23a77391-edea-4420-b946-940a0287a83c.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
nice catch! will review it soon

**Comment by yangwao** [comment]
Left clarification 

https://github.com/kodadot/nft-gallery/pull/2087#issuecomment-1025136316
