### ISSUE TITLE
mobile dropdown menu misbehaves in collection/item

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#2088]
### What happened?

mobile dropdown menu misbehaves when checking on item in specific collection. can be checked at https://kodadot.xyz/rmrk/gallery/10190000-26902bc2f7c20c546a-1FVG7-VACUOM-0000000000000012
![image](https://user-images.githubusercontent.com/73316633/151218780-3170e17a-68f1-41a5-98d2-ef16f4fdfe82.png)

### Please reproduce in steps

described above

### Expected Behavior

I've expected menu to act properly and elements to be aligned in pleasing way

### What browsers are you seeing the problem on?

Chrome, Safari

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

here's one from my actual iphone
![image](https://user-images.githubusercontent.com/73316633/151219628-2674be21-7348-4dee-a1bc-e6fd745450bb.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petersopko** [comment]
I'm gonna fix this

**Comment by yangwao** [comment]
woah! 

<img src="https://media4.giphy.com/media/xUOrwihszfWZgSIHJK/giphy.gif"/>
