### ISSUE TITLE
Rework actions component bit - show account select box only when NFT is for sale

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2094]
At NFTs, if NFT is not at the sale (LISTed), we should not show an account select box.

![image](https://user-images.githubusercontent.com/5887929/151419373-b9323103-f074-41bc-aa82-6638146a840f.png)

**Comment by petersopko** [comment]
I can do this

**Comment by yangwao** [comment]
> I can do this

LFG! 👯

**Comment by yangwao** [comment]
Hey @petersopko had to revert commit as it doesn't work properly and you accidentally removed actions for users for their NFTs apparently?

Plus best would be to have it aligned in the upper section, not vertically centred.

https://github.com/kodadot/nft-gallery/pull/2105
Reverted at - https://github.com/kodadot/nft-gallery/pull/2128
![image](https://user-images.githubusercontent.com/5887929/151761474-b3f76e3e-635f-4a41-9caf-71ea8b1dc3db.png)

**Comment by petersopko** [comment]
> 

I'll check it out right away.

**Comment by petersopko** [comment]
> Hey @petersopko had to revert commit as it doesn't work properly and you accidentally removed actions for users for their NFTs apparently?
> 
> Plus best would be to have it aligned in the upper section, not vertically centred.

I've checked it out again on the branch I was working on, it seems that there were made additional changes in one of the merged PRs from yesterday which caused this as it looks like the picture you attached. Regardless, I need to do more testing with the view of user checking out his NFTs. Will add changes you mentioned in the evening.
