### ISSUE TITLE
Check if @/utils/config/i18n and markdown-it is necessary 📦 

### ISSUE THREAD

**Issue by kkukelka** [kodadot/nft-gallery#2096]
followup for #2039

Research task regarding `@/utils/config/i18n.ts` file and it utilising package `markdown-it`

Glancing over it I'm not even certain if this file does anything useful or is necessary for our needs.

- [x] check purpose of `@/utils/config/i18n.ts`
- [x] check for necessity of `markdown-it`
- [x] If it provides actual value, I want to check if we can abstract it into `nuxt.config.js`
- [x]  further refactor every occurrence of `i18n.t` into `this.$i18n.t`
- [x]  in `spotlight/utils.ts` and `series/utils.ts` columns property needs to move to component in order to use $i18n context

**Comment by kkukelka** [comment]
I'm already onto it. Just want to separate from package refactor since this will require more widespread changes

**Comment by roiLeo** [comment]
related with #1614  bonus point
