### ISSUE TITLE
Collection is created while using only simple mint

### ISSUE THREAD

**Issue by damskyftw** [kodadot/nft-gallery#2098]
### Is your feature request related to a problem?

I'd possibly state this as a bug? Automatically when i simple mint, i don't expect collection to be created with it.

### Describe the solution you would like

I would like to use simple mint really simply, just see it in "created" and that's it. 

### Describe alternatives you have considered

/

### Screeenshots

![why](https://user-images.githubusercontent.com/92786519/151541790-8da08523-4e4a-4b8c-846a-be0097c2e7e6.png)

**Comment by yangwao** [comment]
How rmrk works is that like photo album. You need add something as front cover (collection) and than photo inside. 

Simple mint is way for people who doesn't understand classic minting which is original approach for minting.
