### ISSUE TITLE
search url doesn't update

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#2100]
### What happened?

while fixing another issue, I've discovered that search in gallery doesn't react to changes as I'd expect it to. 
![image](https://user-images.githubusercontent.com/73316633/151604070-6a88b869-1df1-493b-85c2-2a16c092c126.png)

### Please reproduce in steps

1. go to https://kodadot.xyz/rmrk/gallery/
2. search random term such as 'random test search bar' and hit enter
3. notice this term has appeared in URL -> https://kodadot.xyz/rmrk/gallery?search=random%20test%20search%20bar
4. click on sort and filter
![image](https://user-images.githubusercontent.com/73316633/151603222-cec3152c-65e3-4141-805a-1950a91de6e3.png)

5. delete contents of search bar ('random test search bar' changes to empty search bar)
5. try either changing order or toggling 'Buy now'
6. page reloads
7. URL adds the search criteria, in this case let's say 'Buy now' listed/unlisted  but DOESN'T update the search query based on the contents of search bar. URL -> https://kodadot.xyz/rmrk/gallery?search=random%20test%20search%20bar&listed=true

This also happens whenever you change the search query to some other term, but you don't pick one of the suggestions (you click elsewhere on the screen) and then, after toggling listing / unlisting, after reload, search bar stays empty but url and result still shows previous query. 

### Expected Behavior

I've expected the url and search result itself change after reloading according to what is happening in the search section.

### Screenshots

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petersopko** [comment]
I'd also like to fix this.

**Comment by yangwao** [comment]
Yeah when I was approving initial search url v1.1 it was bit wonky, so yeah this occured to me when founding some edge case!

Let's fix it

**Comment by yangwao** [comment]
Related #2247
