### ISSUE TITLE
Display identities instead of accounts in creators spotlight on front page

### ISSUE THREAD

**Issue by anettrolikova** [kodadot/nft-gallery#211]
Why not to display identity names on the front page instead of just having creators spotlight just as a bunch of numbers and alphabetical signing on front page. Most of the creators have set up their identity already so it can be cool to have it displayed.

**Comment by yangwao** [comment]
related #169 
we want to incentivize artists to have pseudonyms.
Sadly not everyone has it yet, but eventually, 50x price decrease, deposits for ksm will go down as well

**Comment by anettrolikova** [comment]
This is not about displaying real names but pseudonyms as well :) 

Anyway I made PR
