### ISSUE TITLE
Add to search price range min - max

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2110]
People love to sort by price

- add to filter to gallery component to search from min - max price range
- add a slide to choose from price
- add it as a range slider, probably range slider https://buefy.org/documentation/slider/#range-slider with min 0.5 and max up to 30, steps 0.5 for try

Query by @vikiival is coming soon

## Ref
- #842

**Comment by petersopko** [comment]
I'll work on this.

**Comment by vikiival** [comment]
```graphql


for subsquid

```graphql
query nftPriceRange {
  min: nFTEntities(orderBy: price_ASC, limit: 1, where: {
    price_gt: 0
  }) {
    price
  }
  max: nFTEntities(orderBy: price_DESC, limit: 10, where: {
    price_lte: 30000000000000
  }) {
    price
  }
}
```
