### ISSUE TITLE
Prevent spamming in recent listings

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2113]
We would need to prevent users to prevent spamming 
As noticed here https://deploy-preview-2091--koda-nuxt.netlify.app/rmrk/gallery/10174132-92b68c8f6d834e8f12-AL-YUI-0000000000000020
It has tons of events for the same price users actually wanted to hammer for cheap action (KSM fees) to appear on Recent List view somewhere.

Sub-optimal option would be showing only the previous 24h of recently listed? 
As fandom of particular artist know their releases well and can find him, should not spam mainstream and mainstream should have little more disadvantage for discovery of collection

![image](https://user-images.githubusercontent.com/5887929/151700702-fc6c4422-ef74-4f79-8b96-4361d25221ba.png)

### Ref
- #842

**Comment by JustLuuuu** [comment]
loooks different now
