### ISSUE TITLE
Reuse folding component from NFT item detail to collection description

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2114]
I guess let's show only the first row from the description and replace the old one 
Make default folded 

@roiLeo was right on this one 😇

![image](https://user-images.githubusercontent.com/5887929/151701053-83fc6297-848b-445f-963a-aa93d4c9c961.png)

how it looks like at item detail
![image](https://user-images.githubusercontent.com/5887929/151701070-03666a2e-84d3-4e6b-a390-af7e2596c64d.png)

**Comment by yangwao** [comment]
random comment to trigger bot delete me later

**Comment by prachi00** [comment]
@yangwao I'll do this
