### ISSUE TITLE
Add shade to footer by default, show on hover 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2117]
- I guess reducing text visibility 
- set footer to black same as the background
- add alpha to icons and text, opacity to 0.3 should work
- when user goes on footer it should set opacity to 1.0

https://user-images.githubusercontent.com/5887929/151703146-475d5c36-06c8-457e-bf55-52f0617e3ec8.mov

**Comment by prachi00** [comment]
@yangwao I'll do this
