### ISSUE TITLE
Check if the symbol is unique for particular user

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#212]
Validation like `Symbol already in use` could be nice

**Comment by niklasp** [comment]
when minting?

**Comment by vikiival** [comment]
> when minting?

Can u be more descriptive please 🥺 ?

**Comment by zhengow** [comment]
Is this issue talking about giving user hint that the symbol name he or she want to mint is occupied?

**Comment by niklasp** [comment]
@zhengow 👈 I did not know at which point of the user interactions this should be implemented so I wanted to know if it was in the mint process

**Comment by vikiival** [comment]
It was already implemented here 1717549c2138ed1e55c075ed9766ca3ebc9aca33
