### ISSUE TITLE
When not logged in the pop up window stays on the page for very long time

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#2124]
### What happened?

If a user comes to kodadot.xyz without polkadot.js wallet and clicks on login, the popup window doesn't go away, obviously when you click on it second time, it stacks up

### Please reproduce in steps

went to kodadot xyz, clicked on log in, pop up window doesn't go away

### Expected Behavior

/

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

No

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/92786519/151751939-d5d4da10-0788-4cb1-a3c1-fcc26c6fc01b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Is this still thing?

**Comment by cryptodamsky** [comment]
> Is this still thing?

No, this issue was resolved by the latest update.

Tried to replicate the bug and it's gone thanks to the change of UI.
