### ISSUE TITLE
Routing on clicking on collections broken?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2127]
Seems I can't replicate it on kodadot.xyz as it did not happen for me, must be something in recent `main` ?
Funny enough, the first page it has worked okay, when I listed through the next pages, it started happening on other collections.

Seems like some routing is terrible broken?

Could this be this warning related? 

![image](https://user-images.githubusercontent.com/5887929/151759680-31d84ec2-9ba7-4bfc-8bf9-ab48858c6626.png)
Hint for this would be issue to sync paginations up and down? Maybe make new component for this?

https://deploy-preview-2123--koda-nuxt.netlify.app/rmrk/collections/

https://user-images.githubusercontent.com/5887929/151759422-1a20f493-dedc-49b7-8f6d-9ee97c0e6683.mov

**Comment by prachi00** [comment]
@yangwao I'll check this
