### ISSUE TITLE
Seems our support address doesn't have enough love

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2129]
Add backup key to payout bot 

I mean best spend money are going to develop right now either so let's go 

ss58
`5FWXi8GTpHvAFC8KXTarvxwW4bwX2HWJEqwcFqMFYNy83DPb`
ksm
`G29NScLSew5zqwmJAPupvJWDCDkpxKUhDnMeVdD2BBcnHar`

https://github.com/kodadot/nft-gallery/blob/418cfd2aee79fc0b64b11f0726e2a553609fbe3d/utils/support.ts#L46

Our current support address seems received the last payment 18 days ago https://kusama.subscan.io/account/CykZSc3szpVd95PmmJ45wE4ez7Vj3xkhRFS9H4U1WdrkaFY

![image](https://user-images.githubusercontent.com/5887929/151768125-3cd7ea5c-6cb1-4d90-b8a3-b15ea63643fa.png)

At least the backup key worked and vikiival received donations for his commitments :D 
https://kusama.subscan.io/transfer?address=Fksmad33PFxhrQXNYPPJozgWrv82zuFLvXK7Rh8m1xQhe98

![image](https://user-images.githubusercontent.com/5887929/151768751-e4f22550-197e-4e1c-a27f-09e2c22938f0.png)

Seems might Nuxt would be issue on resolving stuff?

**Comment by yangwao** [comment]
Reengineer sustainability program

**Comment by vikiival** [comment]
So the issue was that getters from the Vuex store stopped working so getter always returned `undefined`
