### ISSUE TITLE
Add writing interface for texts and support PDFs

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#213]
- [ ] Research available libs for Vue
- [ ] Create wrapper to show pdfs in a readable way

**Comment by yangwao** [comment]
@all-contributors please add @vikiival  for text and media types

**Comment by yangwao** [comment]
@all-contributors please add @vikiival  for design and code

**Comment by yangwao** [comment]
I would extend it for support 
- [ ] extend container to show styled texts
- [ ] add your own font? 
- [ ] markdown support #62 #101 -- we have some work in i18n and markdown already
- [ ] markdown wyswig editor probably, in obsidian style?

One can start minting texts

**Comment by vikiival** [comment]
For PDF
https://github.com/arkokoley/pdfvuer
