### ISSUE TITLE
Open Graph social cards doesn't work 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2136]
Hmm, I guess we've tackled this one @kkukelka 👀🥺

Seems BASE_URL `https://kodadot.xyz` is already present on production, but doesn't render right hm
Maybe cache?

![image](https://user-images.githubusercontent.com/5887929/151791281-25fc2cff-7752-40a2-9f16-cef362ff3d7f.png)
 
https://kodadot.xyz/rmrk/gallery/11202498-9692fa834afcce2d3e-AC99-BASILISK_SNAKE_WARRIOR-0000000000000006

**Comment by kkukelka** [comment]
Ugh, yes I'll take a look :)

**Comment by kkukelka** [comment]
@yangwao ok the problem seems to be out of our hands with current setup.
facebook's og-crawler doesn't care for dynamic tags, therefore it ignores the images that we generate on the fly. only way to solve this is by pre-rendering pages that we show to crawler, which would be ridiculous to do for every single nft. 
https://stackoverflow.com/questions/34281862/dynamic-facebook-open-graph-tags-possible

**Comment by kkukelka** [comment]
EDIT2: oh i just realized everything is wrong....

**Comment by yangwao** [comment]
Maybe that vercel instance by Andrii doesn't handle some stuff okayish?

**Comment by vikiival** [comment]
Soo since OG by @preschian was implemented and deployed:

ref impl: https://github.com/kodadot/workers/pull/12

![photo_2022-10-31 12 30 41](https://user-images.githubusercontent.com/22471030/198998148-31d1ff3c-52a1-41fd-8347-a363ff49a163.jpeg)

**Comment by yangwao** [comment]
I can look on this 👀

**Comment by yangwao** [comment]
https://kodadot.xyz/bsx/gallery/1437594557-20
https://www.opengraph.xyz/url/https%3A%2F%2Fkodadot.xyz%2Fbsx%2Fgallery%2F1437594557-20

Any idea? Is that worker working, or something somewhere needs to be tuned to work? I recall it worked in past for while 

![image](https://user-images.githubusercontent.com/5887929/211147688-fe4ea38d-45ea-4aa4-a070-cbac18aa0ee0.png)


![image](https://user-images.githubusercontent.com/5887929/211147688-fe4ea38d-45ea-4aa4-a070-cbac18aa0ee0.png)

**Comment by yangwao** [comment]
Continue in 
- #5567
