### ISSUE TITLE
Show prices when BUY now is on artist profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2139]
I guess we should check to show prices by default when the user turns on buy now on the artist profile in the same manner as it on gallery view.

@kkukelka was making PR before so might be handy to do this? 

![image](https://user-images.githubusercontent.com/5887929/151795286-d8aadfa6-ef94-45d3-bab5-223aa61f4de5.png)

**Comment by kkukelka** [comment]
Yes I'll do this!
