### ISSUE TITLE
Sort is broken on Profile Artist

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2141]
When I sort by new first at my profile I should see newly minted I guess https://kodadot.xyz/rmrk/u/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd?tab=collected&search=&listed=false&sort=BLOCK_NUMBER_DESC&page=1

When I sort by last time interacted, probably should show recent sends/buys for user?

Anyway, seems filter is broken :)

**Comment by kkukelka** [comment]
Seems like none of the filters do anything 😅

**Comment by roiLeo** [comment]
`OrderBy` is no longer in query, I'll take care of this one
