### ISSUE TITLE
Generate symbol at simple mint from name

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2150]
Plus add a check if under the same artists doesn't exist the same symbol if does, short it one char and add increment number? 

Like if I have NFTLOVE, the next symbol could not be NFTLOVE so it would generate NFTLOV2 simple as that.
OR 
use https://www.npmjs.com/package/nanoid for generating symbol as collision would be super low I bet

We want to lower the barrier for entry users, really :)

Check which symbols could be used according to spec https://github.com/rmrk-team/rmrk-spec

![image](https://user-images.githubusercontent.com/5887929/151947193-53138f77-5bfc-4ecd-8c12-2d97e14a05b9.png)

**Comment by zhengow** [comment]
I'd like to take a look at it

**Comment by yangwao** [comment]
> I'd like to take a look at it

how it's going?

**Comment by zhengow** [comment]
https://user-images.githubusercontent.com/38389586/156399407-59bad18c-03d9-40bd-b846-4c138ceff75f.mp4
