### ISSUE TITLE
Remove background from celebrating toast after minting

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2152]
Or make it more readable please with some hints to be really nicer :)

![image](https://user-images.githubusercontent.com/5887929/151949664-f9120a32-753f-41d3-836c-9d11675a55e1.png)

**Comment by prachi00** [comment]
@yangwao I'll do this

**Comment by yangwao** [comment]
> @yangwao I'll do this

🪄

<img src="https://media3.giphy.com/media/WtgSF7NgP8aZjCYzcu/giphy.gif"/>

**Comment by prachi00** [comment]
@yangwao which one looks better A or B? 
A
<img width="1426" alt="Screenshot 2022-02-01 at 3 56 04 PM" src="https://user-images.githubusercontent.com/39299315/151952848-38765e9e-d9d9-4c79-953c-4fc3a74bff47.png">

B
<img width="1439" alt="Screenshot 2022-02-01 at 4 01 37 PM" src="https://user-images.githubusercontent.com/39299315/151952862-c6d80d5d-5e91-4d45-8609-34dfcd33f9b2.png">

**Comment by yangwao** [comment]
> @yangwao which one looks better A or B? A <img alt="Screenshot 2022-02-01 at 3 56 04 PM" width="1426" src="https://user-images.githubusercontent.com/39299315/151952848-38765e9e-d9d9-4c79-953c-4fc3a74bff47.png">
> 
> B <img alt="Screenshot 2022-02-01 at 4 01 37 PM" width="1439" src="https://user-images.githubusercontent.com/39299315/151952862-c6d80d5d-5e91-4d45-8609-34dfcd33f9b2.png">

B works
