### ISSUE TITLE
Remove console.log and replace it with consola package v0

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2153]
It's time to step up the game on debugging our application and would be superior to have some classy logger

The suggestion is by @vikiival using https://openbase.com/js/consola which comes from the Nuxtjs team
https://github.com/unjs/consola 

Use it with pluggable reporter FancyReporter https://github.com/unjs/consola/blob/master/src/reporters/fancy.js

The best would be if you manage to tell where in the file is console log located so it would short times to locating issue :)

Next is to integrate some Sentry, RollBar, BugSng Trackjs, Honeybaddger, Raygun or what we love 

### Ref
- https://github.com/kodadot/nft-gallery/issues/834

**Comment by rashikaqureshi** [comment]
Hey i am new here. Can you help me with first timer issues ?

**Comment by vikiival** [comment]
Hey @rashikaqureshi,
sure!

I recommend going through [FIRST_TIME](https://github.com/kodadot/nft-gallery/blob/main/FIRST_TIME.md) and [CONTRIBUTING](https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md)

also do not forget to join our [discord](https://discord.gg/kodadot)
