### ISSUE TITLE
Rework card information on collections view

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2155]
It's around clock to pimp collections view.

- This would require writing resolver to https://github.com/kodadot/rubick 
- You can join it with #1850  (it's literally the same issue, just in different detail)

Let's show their same stats as under collections detail, ie, you can see it here https://kodadot.xyz/rmrk/collection/dac5c7f54029d0e73c-1MSUV?tab=collection
 
L / T Items - <#number>     Floor - <#number>
U / O - <#numbers>      Total Vol - <#number>

![image](https://user-images.githubusercontent.com/5887929/151956107-d3f367e1-a978-4351-9945-ce279798d8ed.png)

A particular view where you are changing is at https://kodadot.xyz/rmrk/collections

![image](https://user-images.githubusercontent.com/5887929/151956396-7b245f31-3347-41c9-98f6-d9686743079a.png)

### Ref
- #1850

**Comment by yangwao** [comment]
We can pass this one to 
- #2650 hence
- #2719 collections will be merged under explorer

**Comment by yangwao** [comment]
Okay changed my mind, keep this one open.

**Comment by roiLeo** [comment]
> Okay changed my mind, keep this one open.

![90f3c2b9fca4f1efa215f680ba2114e1](https://user-images.githubusercontent.com/9987732/212079645-06690f24-ff15-4417-af4a-650641783c4d.jpg)

**Comment by roiLeo** [comment]
completed
