### ISSUE TITLE
Remove KSM from Spotlight & Series insight 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2156]
Hence we have right now support only KSM, apply DRY method and remove repeating stuff which doesn't help you at all just noise the dashboard

Remove KSM from columns where it repeats :)

![image](https://user-images.githubusercontent.com/5887929/151966796-3bcf81bd-b269-4bc5-88a6-0b597991306e.png)

![image](https://user-images.githubusercontent.com/5887929/151966836-bb23af89-a32d-4c10-88b0-9a22dbbddd15.png)

**Comment by prachi00** [comment]
@yangwao I'll check this

**Comment by kkukelka** [comment]
just too fast for me hahaha

**Comment by prachi00** [comment]
@kkukelka if you want you can go ahead and take this one :slight_smile:

**Comment by kkukelka** [comment]
@prachi00 first come, first serve. it's all yours 😘
