### ISSUE TITLE
Statemine review log before publication 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2161]
- [x]  history component is no-data -> #2167 
![image](https://user-images.githubusercontent.com/5887929/151983152-e890784b-e3ed-4e3b-87f6-f390cd01ee28.png)
- [x] gallery doesnt load
![image](https://user-images.githubusercontent.com/5887929/151980577-e95a3f1e-c6cc-4548-96d6-098a46aa25f8.png)
- [x] ??? Collection can have attributes? 
![image](https://user-images.githubusercontent.com/5887929/151989853-0eed7b75-ac69-4b06-b315-6f59bfa01c94.png)
 
- [x] add attribute to the bottom and extend it to 10 
![image](https://user-images.githubusercontent.com/5887929/151990214-51b5d2ae-0462-42b3-a226-9839923cec24.png)
- [x] Add dropdown to switch between statemine and ksm in navbar

- [x] spotted old logo
https://user-images.githubusercontent.com/5887929/151981052-71d2126c-4c1d-47b6-a4ce-7088c32c5cea.mov

- [x] theatre view by default
![image](https://user-images.githubusercontent.com/5887929/151981201-c31f683e-0eeb-4b94-aa02-14b47811bad6.png)

- [x] update actions component to recent
![image](https://user-images.githubusercontent.com/5887929/151986180-fe4a4cc5-1c62-4d56-9e5b-4bc356943e62.png)

- [x] showing traits in some table https://buefy.org/documentation/table
![image](https://user-images.githubusercontent.com/5887929/151986916-815922b6-e0be-4182-bd6b-5d2e15c8c74c.png)

- [ ] speedy ticket of instances 
![image](https://user-images.githubusercontent.com/5887929/151997321-06482fa7-24dd-4c65-ad1e-d9ea1a827580.png)
![image](https://user-images.githubusercontent.com/5887929/151997420-8996d5d5-cc1c-41fa-80ab-5b9783c4ab1e.png)
 
- [ ] from unknown to unknown 
![image](https://user-images.githubusercontent.com/5887929/152001264-be9a982c-b007-4f30-9f0a-88fa5e05b0ce.png)

- [ ] balance doesnt show properly right 
![image](https://user-images.githubusercontent.com/5887929/152001660-e499e91f-3544-452a-ac47-d8c2a4659438.png)

**Comment by vikiival** [comment]
https://github.com/kodadot/nft-gallery/pull/2158
