### ISSUE TITLE
Trait system for gaming NFTs

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2164]
Would be nice to add a way to show traits for NFTs, but for two ways.
Simple and advanced. 
As our current metadata hosting is quite cheap compared to statemine, would prefer to account 

## Simple 
is simple what we already have, we can add infinitely limit for users which would help them what they want to do with that
![image](https://user-images.githubusercontent.com/5887929/151990629-81cbe4e8-d75f-47b4-9c68-5f369777147b.png)

## Advanced.

Here we are thinking that the key could be like body settings and the payload could be JSON Object.
JSON could carry another kv pairs, like body colour, height, head size, head width, neck, legs leg length, foot size &c  
How it would look like?

```json
{  
 "body" : { 
	"body": { "color" : "pink", "height" : 1.83 }, 
	"head" : { "size" : 1.17, "width" : 3.25 }, 
	"legs": { "length": 0.37, "foot_size": 1.34 } 
},
 "head" : { 
	"hairstyle" : { 
		"color": { "brown", "style": 39 }, 
		"bangs" : { "color": "brown", "style": 7 }, 
		"back": { "color": "brown", "style": 9 } 
}   
```

The point would be adding a table with searching traits as traits would be future omega how people would collect these NFTs

![image](https://user-images.githubusercontent.com/5887929/151992695-72954d04-e8a8-4774-8f76-53ef0d3580c3.png)

### Ref
- https://github.com/rmrk-team/rmrk-spec/issues/44
- #1526 
- #575
- #417
- https://buefy.org/documentation/table/
- https://kodadot.xyz/rmrk/gallery/11232278-d483a43afae30f4a4f-KUSAMA_HIPPIE_GIRLS-KUSAMA_HIPPIE_GIRL-0000000000000021
- https://github.com/HashLips/hashlips_art_engine
- https://app.traitsniper.com/phunkyapeyachtclub
- https://docs.treattoolbox.com/
- https://github.com/theskeletoncrew/treat-toolbox
- https://github.com/PatrickAlphaC/all-on-chain-generated-nft

**Comment by JustLuuuu** [comment]
we dont to gaming anymore
