### ISSUE TITLE
Mitigation to support Ledger hardware wallet

### ISSUE THREAD

**Issue by gre** [kodadot/nft-gallery#218]
I've been able to use Ledger hardware wallet with the Kusama application in combination with Chrome's `polkadot{.js} extension` support.

- I've been able to see my account
- I've been able to mint a collection
- but as soon as I tried to mint a NFT in that collection, i got an error "not supported"

It seems that this bug relates to limitation of the current Kusama Ledger nano app: the device does not fully support batching yet (it could happen in future, but still, signing huge things with a ledger will not be easily possible).

I was wondering if we could consider a mitigation on the web app side, ultimately it's a decision to bundle all operations or make multiple calls, and it could help Ledger hardware wallet support.

Thanks a lot,
gre

**Comment by vikiival** [comment]
Hey,
I would love to support Legder in KodaDot.

> I was wondering if we could consider a mitigation on the web app side
Yeah you are right we would have to split operations into multiple transactions.

P.S. Is it possible to get a Ledgder testing unit?

**Comment by vikiival** [comment]
// Dev
Looks like it is possible to [detect origin of the account](https://github.com/polkadot-js/extension/blob/695cea8babba85e2f4f2179e7777196613a807d4/packages/extension-inject/src/types.ts#L26)

**Comment by vikiival** [comment]
So v5.90 supports `utility.batchAll` however the latest app on Ledger Live is v5.30.1
<img width="725" alt="Screenshot 2021-07-13 at 11 09 57" src="https://user-images.githubusercontent.com/22471030/125425974-287ae40d-1549-402a-8d38-f004e377b3fe.png">

**Comment by vikiival** [comment]
cc @gre 
https://github.com/Zondax/ledger-kusama/issues/83#issuecomment-878993197

**Comment by roiLeo** [comment]
- https://github.com/Zondax/ledger-substrate-js 👀
