### ISSUE TITLE
Ratio'd 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2184]
oh no

approx location https://beta.kodadot.xyz/rmrk/gallery/?page=34

![image](https://user-images.githubusercontent.com/5887929/152210050-9d0da99f-aa77-4e34-9127-0e219bb3dd4a.png)

**Comment by vikiival** [comment]
May @roiLeo css mage? 🧙

**Comment by yangwao** [comment]
https://kodadot.xyz/rmrk/gallery?page=2

![image](https://user-images.githubusercontent.com/5887929/152225327-aa7e31e9-cdb9-4d40-8ac3-a3ad86b2da39.png)
