### ISSUE TITLE
Load profile if it's only collector profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2187]
If the user won't click, it won't see loaded NFTs it's address is only collecting and hasn't created anything so far.

Test case
- https://kodadot.xyz/rmrk/u/D16ENaBqHLq2ZRmMgumtjNkeC4yc1vmF8Gpu4wx4Ra1q3V
- https://beta.kodadot.xyz/rmrk/u/H7Zt3JeRnPH7AFpJE8UuXo3Ni5aHxCfRAjes4AQe7QfDjDN

https://user-images.githubusercontent.com/5887929/152226151-e2a4b522-1bcb-45ac-8d25-8da849cd09ae.mov

b

**Comment by kkukelka** [comment]
I'll see what I can do

**Comment by yangwao** [comment]
Any progress 🥺  as we will be rolling #2231 to landing would be really nice to have there! :)

**Comment by kkukelka** [comment]
> Any progress 🥺 as we will be rolling #2231 to landing would be really nice to have there! :)

I'll will give it priority 👍
