### ISSUE TITLE
Twitter sharing has bugs and needs some care 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2188]
We've found something special about that twitter sharing 👀

@prachi00 may take look as need some proper testing:)

Apparently it put my handle instead owner :) 
![image](https://user-images.githubusercontent.com/5887929/152236909-6a6468de-5d7f-4d35-b439-84db8b31afd1.png)

![image](https://user-images.githubusercontent.com/5887929/152236867-1672f717-db65-438f-9313-9bd9d78b4e2b.png)

![image](https://user-images.githubusercontent.com/5887929/152236890-122fd03b-2a7f-4b0f-927e-fee50f17faa8.png)

https://kodadot.xyz/rmrk/gallery/11062915-8000262b13545ea72d-KPIZZA-LASER_PIZZA-0000000000000010

**Comment by prachi00** [comment]
@yangwao checking this
