### ISSUE TITLE
Unlockable Content 

### ISSUE THREAD

**Issue by akudless** [kodadot/nft-gallery#219]
It would be great to have a feature that allows artists to create unlockable content that can be accessed by buyer. For example, links to higher resolution files, vector artwork, the original code (for generative art), or even the ability to send the buyer a physical print of the work. For starters, this could be simply a link field where the artist could save the link before minting.

**Comment by yangwao** [comment]
okay, so it should be some field(s) with string inside, probably using some symmetric encryption :)

**Comment by XyloDrone** [comment]
Add this option in the minting process where artists can allow unlockable content 

![Screenshot 2021-05-18 at 23 54 20](https://user-images.githubusercontent.com/84407059/118733548-63605580-b834-11eb-9c62-303229763209.png)

**Comment by anettrolikova** [comment]
Hey @XyloDrone, I think "Let's mint this shit" sounds a bit profane, what about replacing it with "Put your artwork on chain" or "Let your work be recorded on blockchain" or something along those lines... Also having this title in one line would look better IMO :)

**Comment by XyloDrone** [comment]
@anettrolikova Heya. Thank you for the feedback. "Let's mint this shit" is just there as sample text. We didn't decide if any text will be added to the top of the page. Based on responsive web and mobile I am not sure that the proposed sentences would fit into one line on smaller screens, but it is something that can be tested out if we decide to include text at the top of the page.

**Comment by yangwao** [comment]
Unlockable content we can figure out in Koda protocol I guess?

📟 @vikiival

**Comment by yangwao** [comment]
Entering the time machine, I've met someone in Lisbon who could help us with this as they have a dedicated product.

**Comment by exezbcz** [comment]
continue to: 
- #5839
