### ISSUE TITLE
Searchbar not working

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#2192]
#### To replicate
- Goto `/gallery/`
- Goto page "20" for example
- Search something
- no result & error in console

![Capture d’écran 2022-02-03 à 8 43 37 AM](https://user-images.githubusercontent.com/9987732/152301265-19ce61b0-3cc0-434b-9aa8-f8cf08e6e25f.png)

#### Test case
`/rmrk/gallery?page=10&search=yeet`

#### Possible Solution
remove/initialise the page parameter from the query on SearchInput

**Comment by yangwao** [comment]
And when I enter it to https://beta.kodadot.xyz/rmrk/gallery?page=7&search=gandalf yeah it's gone.. I guess bc it sends you on 7 page of search results which aren't there?

![image](https://user-images.githubusercontent.com/5887929/152325198-6f49e009-154c-4b64-8d7b-e79a507b9d71.png)
