### ISSUE TITLE
Preloader is gone 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2193]
We are quite missing preloader in recent PRs, can someone please bring him back? 🥺 

Seems doesn't work on the beta only

on `hyper-jpeg` which is production it works

![image](https://user-images.githubusercontent.com/5887929/152327639-8a301c6a-bc94-4205-90b7-d946e5453d6b.png)

**Comment by yangwao** [comment]
Somehow is back lol, suspicious

![image](https://user-images.githubusercontent.com/5887929/152330874-016ec6ab-af5b-4e0e-95b6-05a04d7f6ccc.png)

**Comment by yangwao** [comment]
@prachi00 👀 

Probably related #2188  #2190 #2138

![image](https://user-images.githubusercontent.com/5887929/152331419-8c9bec69-785f-4d8c-93b1-ffa4e8a47979.png)

**Comment by prachi00** [comment]
@yangwao it should be solved when #2190 is merged I guess

**Comment by yangwao** [comment]
yup working 

<img src="https://media2.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif"/>
