### ISSUE TITLE
Mini pulse history component

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2195]
We are looking for this kind of component to be added to the series and spotlight.

This is blocker #1680 probably?
The component should feed data of recent buy events.

In the series, show buys for the last 30 days 
In the spotlight of particular authors sales for the last 30 days

![image](https://user-images.githubusercontent.com/5887929/152328222-7babc6ed-acef-439f-895f-abfe79e9eef0.png)

### Ref
- https://steamdb.info/ ht @vikiival 
- https://github.com/kodadot
- https://github.com/unjs
- #1680

**Comment by KngZhi** [comment]
I'll check this.

**Comment by yangwao** [comment]
Meanwhile done 
![image](https://user-images.githubusercontent.com/5887929/186941607-90a47e5b-bbee-418f-b2b5-ef989896068c.png)
