### ISSUE TITLE
Has search on emoji panel ever worked?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2200]
Probably check and fix 
Plus I've noticed we showing some limited subset of emojis, curious why?

https://user-images.githubusercontent.com/5887929/152356419-4eb44272-c69d-451d-a275-57c2ad434224.mov

**Comment by roiLeo** [comment]
It does work for me
![Screenshot 2022-02-04 at 09-39-21 Kitty Paradise #261](https://user-images.githubusercontent.com/9987732/152497986-cd56f4a5-4419-48a0-b33f-0fc44ba49c52.png)
![Screenshot 2022-02-04 at 09-40-19 Kitty Paradise #261](https://user-images.githubusercontent.com/9987732/152498075-7e8d127f-0951-42af-aee5-76c94918691e.png)

**Comment by yangwao** [comment]
I feel special

**Comment by yangwao** [comment]
search works, yet keyboard shortcuts listen everytime which I guess should not
 
<img width="413" alt="image" src="https://user-images.githubusercontent.com/5887929/158018975-e2a27ef8-408a-48db-8418-f9cba0707383.png">
