### ISSUE TITLE
Show only first row from description at collection

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2208]
Let's make it show only the first line from the description of the collection
Test at https://kodadot.xyz/rmrk/collection/54563af23dba417622-CAT
https://user-images.githubusercontent.com/5887929/152416447-a8365828-2643-4584-a36d-682cc6ca2b02.mov

**Comment by prachi00** [comment]
@yangwao I;ll do this

**Comment by yangwao** [comment]
<img src="https://media2.giphy.com/media/MdqE46HziuFJTlIwjw/giphy.gif"/>
