### ISSUE TITLE
Show liked NFTs by user

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#221]
The idea:
We should have a tab under profiles that shows liked NFTs by a particular account.

**Comment by yangwao** [comment]
🔮

**Comment by yangwao** [comment]
> What should we rely on now? subsquid ? magick?

subsquid/rubick team is more versatile, in our timezone and for our use case right now more flexible:)

**Comment by vikiival** [comment]
I agree with Wao.
We aim to have SubSquid as a first indexer
