### ISSUE TITLE
Add overlay dialog for shortcuts to learn them faster - Tekken  

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2216]
I can't find where I've seen it but with upcoming PR #2097 would be super nice to add shortcuts to control the app much faster.

The goal of the overlay would be to pro-actively learn users how to control the app with keyboard shortcuts
I.e. when I press `g` it will roll out which keyboard shortcuts would be next for a particular action.

Something like in mortal combat or Tekken tho when it suggests further combos, can't really recall where I've seen it recently

![image](https://user-images.githubusercontent.com/5887929/152525130-c0b7b81f-0d8e-4f5d-9348-a46b82cd3d7d.png)

**Comment by XyloDrone** [comment]
is it worth considering adding this command to the nav bar and/or landing?

**Comment by niklasp** [comment]
@yangwao are you thinking about an overlay like the cookie notice? We could toggle that overlay on keypress "i"  😀 e.g. or have some trigger to show it. E.g. after the 2nd wallet connect.

I imagine highlighting available shortcuts based on the view.
