### ISSUE TITLE
Align navbar with recent style changes

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2218]
At navbar, at hover would be nice to have top-border and slow fade-in highlight effect around the text

![image](https://user-images.githubusercontent.com/5887929/152529158-d7a81659-7d77-4e95-ae6d-6755f077d661.png)

https://user-images.githubusercontent.com/5887929/152529137-39a91110-6b9a-425e-8c9f-ce693562f522.mov

**Comment by prachi00** [comment]
@yangwao Ill pick this
