### ISSUE TITLE
Make pr to dotapps to add kodadot to profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2221]
Add KodaDot to dotapps to account/addressbook
https://cloudflare-ipfs.com/ipns/dotapps.io/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/addresses

![image](https://user-images.githubusercontent.com/5887929/152531225-bccec01d-1f63-4c6c-a63b-49df6607eb3c.png)

### Ref
- https://github.com/polkadot-js/
- https://github.com/kodadot/kodadot-presskit/tree/main/v3

**Comment by zhengow** [comment]
done.
https://github.com/polkadot-js/apps/issues/7074

**Comment by yangwao** [comment]
> done. [polkadot-js/apps#7074](https://github.com/polkadot-js/apps/issues/7074)

oh, that's opened an issue, not PR :)

I guess someone with React experience would be able to do that :)

**Comment by preschian** [comment]
deployed to https://polkadot.js.org/apps/#/accounts 🎉

<img width="2032" alt="Screen Shot 2022-03-17 at 8 20 06 PM" src="https://user-images.githubusercontent.com/734428/158817289-ab9f6f19-b24d-4b62-b951-2cfe742ae632.png">

**Comment by preschian** [comment]
finally, released 🎉
- https://cloudflare-ipfs.com/ipns/dotapps.io/#/explorer
- https://github.com/polkadot-js/apps/releases/tag/v0.110.1

<img width="2032" alt="Screen Shot 2022-03-21 at 10 05 52 PM" src="https://user-images.githubusercontent.com/734428/159290218-e40c50a8-99af-41ad-9b46-38581890bcc4.png">

**Comment by yangwao** [comment]
oh, that's amazing! 
Can we push the outline version as on small space, outlined version might be better recognized? 
https://github.com/kodadot/kodadot-presskit/blob/main/v3/K_outline_logo.png

Feel free to put the payment link through transfer here to receive reward :)

**Comment by preschian** [comment]
> oh, that's amazing! Can we push the outline version as on small space, outlined version might be better recognized? https://github.com/kodadot/kodadot-presskit/blob/main/v3/K_outline_logo.png
> 
> Feel free to put the payment link through transfer here to receive reward :)

Noted, I will try out the outline logo tomorrow.

here it is, my [KSM address](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

**Comment by preschian** [comment]
@yangwao  preview when using that logo, is that ok for you? if yes, I will raise the PR again

<img width="397" alt="Screen Shot 2022-03-23 at 8 19 51 PM" src="https://user-images.githubusercontent.com/734428/159708820-7130b2eb-763a-48c0-b896-41c60c590109.png">
<img width="304" alt="Screen Shot 2022-03-23 at 8 20 36 PM" src="https://user-images.githubusercontent.com/734428/159708931-51d387b4-3e36-4b5b-a75a-0078207d5fcf.png">

**Comment by yangwao** [comment]
oh, probably we need a better icon for this small space
cc @XyloDrone

**Comment by XyloDrone** [comment]
> finally, released 🎉
> 
>     * https://cloudflare-ipfs.com/ipns/dotapps.io/#/explorer
> 
>     * https://github.com/polkadot-js/apps/releases/tag/v0.110.1
> 
> 
> <img alt="Screen Shot 2022-03-21 at 10 05 52 PM" width="2000" src="https://user-images.githubusercontent.com/734428/159290218-e40c50a8-99af-41ad-9b46-38581890bcc4.png">

I think this logo works nicely :D

**Comment by yangwao** [comment]
okay, let's close this then :) 

@preschian sent payout!
https://kusama.subscan.io/extrinsic/0x8d961fe0d4b85664b1651d6ebd48859ce2decbaf24238c7a64015d3c0a567c28
