### ISSUE TITLE
Use cloudflare r2 for pre-caching glb/gltf objects

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2229]
Let's leverage cf r2 for faster load of glb objects as it's our core thesis of 3d nft marketplace ;)

might be optionally for some textures which I don't know formats out of head 

Right now we are not much incentivized to store movies tbh and we will opt-out to using Estuary/Pinata Gw for that

### Ref
- https://blog.cloudflare.com/introducing-r2-object-storage/
- https://news.ycombinator.com/item?id=28702997
- https://www.lastweekinaws.com/blog/the-compelling-economics-of-cloudflare-r2/
- https://filebase.com/pricing

**Comment by yangwao** [comment]
![image](https://user-images.githubusercontent.com/5887929/197216017-c018fda0-258e-4b56-8f97-b1d4c1475c62.png)

**Comment by yangwao** [comment]
but it would work ok with glb/gltf bigger files ok? doesn't need any specific tunes?

**Comment by vikiival** [comment]
Our worker should work in unbundled mode, so it can handle big file. 

I think next step would be introduction of direct pin for non image files

**Comment by yangwao** [comment]
https://ar-fees.arweave.dev/ 
100MB -> $0.68

![image](https://user-images.githubusercontent.com/5887929/229837592-edc809c1-1e77-4ea0-9b05-c5dfa1160062.png)

**Comment by vikiival** [comment]
> https://ar-fees.arweave.dev/

![Screenshot 2024-07-31 at 15 10 56](https://github.com/user-attachments/assets/cc1240ee-29c6-44a4-8c76-0ca3b7e3eca2)

**Comment by vikiival** [comment]
Already storing content on ipfs with r2
