### ISSUE TITLE
Move 'default view' to bottom right 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2230]
In the upper corner, we have a button default / theatre view 
- move it to bottom right next to full screen mode and replace it with icon cube https://fontawesome.com/v5.15/icons/cube?style=solid
- replace icon for full screen with expand https://fontawesome.com/v5.15/icons/expand?style=solid
- on full screen replace minimize with compress https://fontawesome.com/v5.15/icons/compress?style=solid
![image](https://user-images.githubusercontent.com/5887929/152637917-aaec9ece-8966-4b21-800a-ca66195ad38e.png)
- remove border from NFT art
- for icons only keep top-border 
- on arrow keep only top-border as well 
 

![image](https://user-images.githubusercontent.com/5887929/152638013-eedfccc1-16d9-48af-bc12-d6bad490b4c9.png)
![image](https://user-images.githubusercontent.com/5887929/152637572-c6463ba9-e730-464f-bdc3-b062aa45843a.png)

**Comment by prachi00** [comment]
@yangwao I'll pick this one up

**Comment by prachi00** [comment]
<img width="595" alt="Screenshot 2022-02-07 at 5 20 43 PM" src="https://user-images.githubusercontent.com/39299315/152783049-c038be8e-9230-45c9-ac73-03f5045e020d.png">
@yangwao what happens to this button? this would also be moved to bottom right

**Comment by prachi00** [comment]
> <img alt="Screenshot 2022-02-07 at 5 20 43 PM" width="595" src="https://user-images.githubusercontent.com/39299315/152783049-c038be8e-9230-45c9-ac73-03f5045e020d.png">
> 
> @yangwao what happens to this button? this would also be moved to bottom right

and also what should be the icon for theatre view?

**Comment by yangwao** [comment]
> > <img alt="Screenshot 2022-02-07 at 5 20 43 PM" width="595" src="https://user-images.githubusercontent.com/39299315/152783049-c038be8e-9230-45c9-ac73-03f5045e020d.png">
> > @yangwao what happens to this button? this would also be moved to bottom right

yes, updated issue

> and also what should be the icon for theatre view?

I guess this one could be fit https://fontawesome.com/v5.15/icons/image?style=regular
