### ISSUE TITLE
Seems transfer needs fix 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2241]
I guess it requires Math.trunc() to round number

https://kodadot.xyz/transfer/

tried transfer 0.54 
![image](https://user-images.githubusercontent.com/5887929/152648847-97860b07-62fd-4fd7-81a3-318a272e22a3.png)

![image](https://user-images.githubusercontent.com/5887929/152648879-4daff6eb-57ea-46f9-8370-15c96c8831eb.png)

**Comment by zhengow** [comment]
i'd like to fix it
