### ISSUE TITLE
calling force-clip squad to the rescue

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2246]
I guess the latest sales broke due way too long identity

plus would be nice to rework previous CSS hacks more sophisticated with clip )

![image](https://user-images.githubusercontent.com/5887929/152674004-784b05e3-52c5-4102-b14e-ff8895d80eb0.png)

identity could be found here
https://kodadot.xyz/rmrk/gallery/10812187-66241b171becfd500e-EGG-KU_EGG_371-0000000000000371

**Comment by shixin-guo** [comment]
maybe fixed

**Comment by yangwao** [comment]
yeah most probably yes, thank you!
