### ISSUE TITLE
Handle offline-first screen

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2249]
Tell users they are out of the internet and once they are back, they should see NFTs

![image](https://user-images.githubusercontent.com/5887929/152675447-e9500a50-c687-4329-88d9-948b1660f799.png)

**Comment by KngZhi** [comment]
Hi @yangwao, I'd like to pick up this issue, but do I need to wait until the UX had been designed?

Or Is there any traditional way(components) to show alerts that users are out of the internet?

**Comment by yangwao** [comment]
> Hi @yangwao, I'd like to pick up this issue, but do I need to wait until the UX had been designed?
> 
> Or Is there any traditional way(components) to show alerts that users are out of the internet?

I guess we don't have anything like a design for this case, cc @XyloDrone 

if none, let's inspire with the 404 page we are having now. Probably rely on navigator state, check #2512 will introduce way to check if there is connection available in vuex store iirc
