### ISSUE TITLE
Navbar sorting & cleaning

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2252]
- Probably we could move Tutorial into Log In dropdown

From Extra move to Profile, put them 
- Transfer - it's not possible to do until you logged anyway
- Teleport - same as above
- Admin -  same as above

The final state under profile should be, in a particular order
```MD
- Profile
- Settings
---------
- Admin
- Credit
- Identity
- Teleport
- Transfer
----------
- FAQ
- Tutorial
----------
- Language (icon?)
- Change Account
```
Thus you can remove the Extra, Tutorial, Language selector
The reasoning is lightweight UI doesn't show the user what's is needed. 

Once it's done @cryptodamsky could reflect in docs.kodadot.xyz :)

![image](https://user-images.githubusercontent.com/5887929/152677812-e0a9f80e-b46f-4bf6-94b5-845d65c051b0.png)

![image](https://user-images.githubusercontent.com/5887929/152677825-decd2eba-8b10-46fe-8a69-4df1be5f5eac.png)

**Comment by kkukelka** [comment]
On it!

**Comment by kkukelka** [comment]
@yangwao
1. I really dislike the idea of putting language switcher into profile dropdown, as it would result in a nested dropdown... kind of a no-go don't you think?
2. What to do about Twitter and Discord link in Profile Dropdown? Its already pretty loaded now and I don't see how they are related to user profile anyways? We also link to them in the footer

<img width="447" alt="Screenshot 2022-02-06 at 19 32 04" src="https://user-images.githubusercontent.com/17953978/152696002-d46aa69b-d1fc-4c17-acef-023439bd7788.png">
