### ISSUE TITLE
Calling css mage for landing

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2255]
I guess we need to preserve some mobile experience and avoid scrolling to horizontal whole page 🥶😶‍🌫️🫠🫥🤐🫣🥹😬

https://user-images.githubusercontent.com/5887929/152697326-97bd1e65-2007-4eeb-ae3f-0640b8b498a1.mp4

Plis firefox focus doesn't show it all 😬

![Screenshot_2022-02-06-21-09-30-32_fd7367fd0afc7e864f00091a00b3d0b0.jpg](https://user-images.githubusercontent.com/5887929/152699453-ad64283c-8dea-4cc0-9ce8-1fd34820718f.jpg)

Css council wouldn't like this much

![Screenshot_2022-02-06-21-12-49-55_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/5887929/152699563-39c31e73-0cf3-40d7-b2b9-e6e95d7c1623.jpg)

![image](https://user-images.githubusercontent.com/5887929/152972178-d3e38c08-4ce9-49ce-bb1b-54045ece04bc.png)

**Comment by roiLeo** [comment]
> I guess we need to preserve some mobile experience and avoid scrolling to horizontal whole page 🥶😶‍🌫️🫠🫥🤐🫣🥹😬
> Record_2022-02-06-20-08-19.mp4

Video not loading ☹️ 

> Plis firefox focus doesn't show it all 😬

on firefox focus it doesn't even show `/gallery` nfts, could be related with some css property not applied on firefox? 

> Css council wouldn't like this much

Can't reproduce, what was the navigator?

**Comment by yangwao** [comment]
> > I guess we need to preserve some mobile experience and avoid scrolling to horizontal whole page 🥶😶‍🌫️🫠🫥🤐🫣🥹😬
> > Record_2022-02-06-20-08-19.mp4
> 
> Video not loading ☹️

yeah noticed few videos uploaded through gh mobile app is gone forever :|

> Can't reproduce, what was the navigator?

It's android chrome but it does only sometimes, so some class is overlapping? Will keep watching on this one.

**Comment by yangwao** [comment]
@roiLeo pretty please, can you spell CSS for us 🥺

<img src="https://media0.giphy.com/media/xUOwFToDIeaXgTblII/giphy.gif"/>

**Comment by roiLeo** [comment]
> @roiLeo pretty please, can you spell CSS for us 🥺

Where should I cast my spell?
I need more infos to replicate the bugs

**Comment by yangwao** [comment]
lol I haven't pasted pic lmao, my clipboard is acting weird as its user. 

![image](https://user-images.githubusercontent.com/5887929/152977308-e653c96e-c195-4134-a270-bab42e928935.png)
