### ISSUE TITLE
Add keyboard shortcuts cheat sheet on kbd short cut

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2259]
I guess we should add some keyboard shortcuts board like this 
Once the user presses `?` it will show 

Once is done #2097 
![image](https://user-images.githubusercontent.com/5887929/152776090-2a5a8bf4-41ee-432b-bdeb-91055fa2fc57.png)

**Comment by chandradot99** [comment]
@yangwao I will look into it.
