### ISSUE TITLE
Unite search experience in Collections with Gallery

### ISSUE THREAD

**Issue by ins0mn1a** [kodadot/nft-gallery#2261]
### Is your feature request related to a problem?

When you try search in "Collections" you are getting realtime results with loading progress while you typing.
It's messy and not much user friendly.
<img width="822" alt="Screenshot 2022-02-07 at 12 22 51" src="https://user-images.githubusercontent.com/10535692/152779991-070f4b88-0c8f-44f5-a13f-0e8cfe40a34f.png">

### Describe the solution you would like

It will be nice to implement same search experience that is used in "Gallery".

<img width="732" alt="Screenshot 2022-02-07 at 12 23 22" src="https://user-images.githubusercontent.com/10535692/152780135-f5766d83-c387-4354-b36c-4687f26a0d40.png">

**Comment by petersopko** [comment]
related to (or included in) issue https://github.com/kodadot/nft-gallery/issues/2100 . As discussed with @vikiival there's difference in queries used in these two components. I'd like to work on unification of search between gallery / collections. There's actually even design difference for some reason, which I don't see right now:  
  
Gallery (after toggling filter -> default is hiddenbottom section with newest / buynow toggle) 
![image](https://user-images.githubusercontent.com/73316633/152785149-61cadea4-6e3b-4886-8a2d-c6fccb50debb.png)
Collections  
![image](https://user-images.githubusercontent.com/73316633/152785198-5830350f-8f17-4dce-ab8a-33778f4e9650.png)

**Comment by yangwao** [comment]
Collections have legacy search iirc. 
Gallery is definitely a few iterations further as we've been focusing there.

Unify those two components would be really much needed, #1678 

In collections queries need major rehaul iirc to work properly, collection view is still experimental, where gallery showing NFTs per se and collections should offer way essential on recent new collections.

**Comment by petersopko** [comment]
@yangwao I've fixed the edgecases in #2100. Now to your comment :
> Gallery is definitely a few iterations further as we've been focusing there.

Should I make Collection search same as Gallery search then? Perhaps as a starting point and we'll keep them updated together from now on?

**Comment by yangwao** [comment]
Will be resolved in https://github.com/kodadot/nft-gallery/issues/2719
