### ISSUE TITLE
Add Statemine to docs 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2266]
- Take recent article made by Viki and make more human introduction to Statemine

- https://medium.com/kodadot/wen-statemine-by-kodadot-b35ae13b70ff

**Comment by cryptodamsky** [comment]
All these kind of rewritings/simplified versions will be running here: https://docs.kodadot.xyz/simplified-writings.html

https://docs.kodadot.xyz/statemine.html#statemine-the-nft-pallet

Would love some feedback from non-tech savy users if it's fine or need to simplify more
