### ISSUE TITLE
Add what's are fees for minting to faq

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2276]
Can we fast track this @cryptodamsky 😇

- explainer how much are fees and why is that
- would be higher if so at what load
- link to some recent minting transaction

![Screenshot_2022-02-08-09-50-05-44_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/5887929/152951246-1531e162-10a1-4a13-ae8f-7d5268a7f836.jpg)

**Comment by kkukelka** [comment]
> Actually right we've had it... #1399
> 
> Okay seems @kkukelka accidentally removed it here [70a51e4#diff-b2d865775cff44fecbd4d58199019c245fcc726314efeadbee3fb9c71b0600d1L111](https://github.com/kodadot/nft-gallery/commit/70a51e4427ccdfe47ce1933b863149f771d85f28#diff-b2d865775cff44fecbd4d58199019c245fcc726314efeadbee3fb9c71b0600d1L111)
> 
> Anyway, great opportunity to rework this 😄

not accidentally 😛  i rewrote all the FAQ entries according to #1604

**Comment by yangwao** [comment]
I'm getting used that with our code is like tides at beach, sometimes it's high, sometimes low and yet it's still evolve 😅

**Comment by kkukelka** [comment]
@yangwao sooo i could basically close this by just re-adding question from #1399 right? where should i put it in terms of order? my best guess would be right below `HOW CAN I MINT NFTS?` right?

**Comment by cryptodamsky** [comment]
Yeah the question was removed because it was a mixup of tutorial and other information that deserve to be solo. We can have a question for example:

Q: How much will it cost me to mint an nft?
A: Answer as per current fees

**Comment by cryptodamsky** [comment]
> @yangwao sooo i could basically close this by just re-adding question from #1399 right? where should i put it in terms of order? my best guess would be right below `HOW CAN I MINT NFTS?` right?

I agree with the positioning. It's probably one of the first thing a beginner will be looking to find out.

**Comment by cryptodamsky** [comment]
> Can we fast track this @cryptodamsky 😇
> 
>     * explainer how much are fees and why is that
> 
>     * would be higher if so at what load
> 
>     * link to some recent minting transaction
> 

Yup would also like to add this to docs. But as i'm trying to find an answer either on polkadot wiki or rmrk docs, can't really find much about fees or how would it act with higher load. Are there any materials i could get this from and transform it to some understandable 'answer' for newbie?

As for now i can't even see the transaction calculator while minting, so not really sure where to fetch all this info

**Comment by cryptodamsky** [comment]
Basic explanation is currently running in docs, now i have to chew 6 pages of explaining ksm fees to some understandable way for beginners - once done let's update the faq

https://docs.kodadot.xyz/FAQ.html#what-are-fees-and-why-do-i-need-to-pay-them
https://docs.kodadot.xyz/FAQ.html#what-are-the-transfer-fees-on-kusama

**Comment by yangwao** [comment]
#2514 🥺

**Comment by zhengow** [comment]
> #2514 🥺

Thanks for let me know this:)

Can a creator see how much fees exactly or approximate range that he have to pay while minting?

**Comment by cryptodamsky** [comment]
> 

Hey so i believe we used to have a calculator which can calculate the minting costs, but since the price of the transaction is so low at the moment, you can always look back in your profile on subscan - for example here 

https://kusama.subscan.io/extrinsic/11705319-2

Just minted this couple seconds ago and the fee is in current prices 0.022408$. Doesn't get much higher than that usually, of course depending on the kusama price but even with high load a higher price, it usually doesnt go above 0.01$ afaik.

I've just minted nft without setting the price and the calculator wasn't there, is this on purpose? @yangwao

**Comment by yangwao** [comment]
> I've just minted nft without setting the price and the calculator wasn't there, is this on purpose? @yangwao

Good catch, will be solved in #2530 )

**Comment by kkukelka** [comment]
@cryptodamsky what's the latest status on this issue?

**Comment by cryptodamsky** [comment]
> @cryptodamsky what's the latest status on this issue?

I've been talking with @yangwao yesterday, we've got fixed fee for minting but it isn't shown anywhere, and i don't know the values, so once i have this information we can put it to FAQ and exchange it for question number "5".

Would also put it straight under the calculator to the minting process, to be transparent on how much is charged.

**Comment by cryptodamsky** [comment]
Regarding the fee changing on higher load, i'd leave that be, since we haven't suffered from this yet and probably won't for some time. Once it happens, we can try to explain the mechanics behind it somehow, but i don't think it's necessary to have it in FAQ. It's more of our issue than user's.

**Comment by yangwao** [comment]
> > @cryptodamsky what's the latest status on this issue?
> 
> I've been talking with @yangwao yesterday, we've got fixed fee for minting but it isn't shown anywhere, and i don't know the values, so once i have this information we can put it to FAQ and exchange it for question number "5".
> 
> Would also put it straight under the calculator to the minting process, to be transparent on how much is charged.

Flat collection fee It's here #1967

**Comment by kkukelka** [comment]
> > > @cryptodamsky what's the latest status on this issue?
> > 
> > 
> > I've been talking with @yangwao yesterday, we've got fixed fee for minting but it isn't shown anywhere, and i don't know the values, so once i have this information we can put it to FAQ and exchange it for question number "5".
> > Would also put it straight under the calculator to the minting process, to be transparent on how much is charged.
> 
> Flat collection fee It's here #1967

Ah sweet. And NFT fee is also flat?

**Comment by yangwao** [comment]
> Ah sweet. And NFT fee is also flat?

I guess so :)

**Comment by thea-exe** [comment]
<img width="656" alt="Screen Shot 2022-07-11 at 10 29 43 AM" src="https://user-images.githubusercontent.com/65369742/178288131-886f8385-fb85-4240-a1e3-8c802b05638b.png">
Currently what's in the docs rn

**Comment by yangwao** [comment]
we can extend this with basilisk fees 🤔

**Comment by yangwao** [comment]
Probably we can extend this with various mintings fees 👀
- RMRKv1, RMRKv2
- Basilisk
- MoonRiver/MoonBeam
- Astar

**Comment by roiLeo** [comment]
- https://hello.kodadot.xyz/multi-chain/fees
