### ISSUE TITLE
Show available balance at NFTs for BUY

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2282]
When people are eyeballing for NFTs, show them the available balance next to the name 
This would avoid some future failed transactions and UX Foppa

Optionally disable BUY when not enough balance but keep it there, tell the user why is disabled.
Don't forget to add it to translations
Subscribe pooling for balance to see and avoid edge case if someone refuelled their wallet meanwhile.
Please test all edge cases I was might not think of 

Optionally make it to hide in user preferences

![image](https://user-images.githubusercontent.com/5887929/152987803-d6671b88-911f-475b-a4cc-924960eeca84.png)

test case 
https://kodadot.xyz/rmrk/gallery/11163449-6ec662611f161fd10a-DDWORLD-DOODLE_ANIMATRONIC_CARACAL-0000000000000034

**Comment by chandradot99** [comment]
I am on this @yangwao
