### ISSUE TITLE
spookie skeleton on gallery/:id

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#2291]
We will need to rework a bit the [skeleton](https://buefy.org/documentation/skeleton/) on gallery item when the page is loading because it became non sense

#### Screenshot
![Capture d’écran 2022-02-08 à 4 56 04 PM](https://user-images.githubusercontent.com/9987732/153025159-d8e5791c-8e77-45ab-9cc5-09fe91d2f83f.png)

**Comment by yangwao** [comment]
I could point where or when it has happened 😅 yet remain 😶 I've noticed that change hmm 🤣
