### ISSUE TITLE
Icon sizes needs put sizing back?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2298]
That one time I've skipped skip netlify builds :D

I guess the recent update fontawesome-svg-core made this change https://github.com/kodadot/nft-gallery/pull/2294

check https://beta.kodadot.xyz/rmrk/collection/160a6f4320f11acb25-LCKWV

![image](https://user-images.githubusercontent.com/5887929/153163898-0aa9e9f3-9fb5-47f5-a2ea-52d6de1aef94.png)

**Comment by kkukelka** [comment]
I'll take a look

**Comment by yangwao** [comment]
We've used this back then

https://github.com/vue-polkadot/apps/blob/develop/dashboard/src/main.ts#L30

**Comment by kkukelka** [comment]
> We've used this back then
> 
> https://github.com/vue-polkadot/apps/blob/develop/dashboard/src/main.ts#L30

i'm losing my mind over here.
<img width="334" alt="Screenshot 2022-02-09 at 16 53 35" src="https://user-images.githubusercontent.com/17953978/153238195-b203c5ae-aaf9-4b11-ba26-b8991e2ab8a6.png">
something in bulma config just straight up overwrites `is-small` class

reverted all relevant changes (package.json, scss stuff) from past week but cant seem to find issue

**Comment by roiLeo** [comment]
Don't know if these could help but I noticed that we missed the `.fa-w-` class on svg

**Comment by kkukelka** [comment]
related to https://github.com/FortAwesome/Font-Awesome/pull/18654

**Comment by yangwao** [comment]
I've reverted it `06dd0752..06003a5c`
