### ISSUE TITLE
(JS-0306) Missing explicit return and argument types

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2300]
## Description
Explicit types are considered in three ways: - It serves as self-documenting code - It guard against bugs in function implementation - It acknowledge and change the explicit return type on the function signature

## Occurrences
There are 7 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/kodadot/nft-gallery/issue/JS-0306/occurrences/](https://deepsource.io/gh/kodadot/nft-gallery/issue/JS-0306/occurrences/)

![image](https://user-images.githubusercontent.com/5887929/153178058-834e9ad2-6b46-4acb-acd9-1e0b803ab3d8.png)
![image](https://user-images.githubusercontent.com/5887929/153178092-73e7d1e1-cfac-4f8c-a50b-560b55f25bf7.png)

**Comment by kkukelka** [comment]
on it!
