### ISSUE TITLE
Account selector broken

### ISSUE THREAD

**Issue by Swader** [kodadot/nft-gallery#231]
Sometimes the account selector is broken.

![image](https://user-images.githubusercontent.com/1430603/112482625-8dd3ec00-8d78-11eb-9a39-bcc837c2d5fc.png)

It was fine a minute ago, but after refresh it broke. I did not reject access to the extension.

**Comment by yangwao** [comment]
We are aware of this, when you directly go through the link and not through extension, initializing is wrong on our side.
This would be probably fixed in - #226
