### ISSUE TITLE
Getting rid of warnings while installing packages

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2315]
At current head commit `06003a5ced1ac8ce415f04643aba672de05cd037` we have these warnings

Would be nice if we can mitigate a few of them. 
Warnings are usually there for reasons to raise awareness something might be bug risk in the future.
![image](https://user-images.githubusercontent.com/5887929/153387691-af8e135a-2e8b-4d09-b2d9-9b327a29f823.png)

**Comment by ritsuyan** [comment]
ok, I will do this task.

**Comment by preschian** [comment]
Hello, it seems no progress on this issue. So I tried to make a PR based this issue. There are still some warnings on `graphql` dependencies. It might be better if we replace the package.

old: [@nuxtjs/apollo](https://snyk.io/advisor/npm-package/@nuxtjs/apollo#security)
new: [nuxt-graphql-request](https://snyk.io/advisor/npm-package/nuxt-graphql-request)
source: https://modules.nuxtjs.org/?q=graphql&version=2.x
