### ISSUE TITLE
Focus on input when using keyboard shortcuts list and send

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2317]
when I hit a+l for listing my nft, it should focus to list input 
same for a+s, to send to address

![image](https://user-images.githubusercontent.com/5887929/153389930-a36ab900-34b2-44a0-8cbf-86bf72071171.png)

![image](https://user-images.githubusercontent.com/5887929/153390009-2d549570-10fa-4e82-bfcf-71aececea74b.png)

**Comment by kkukelka** [comment]
I'll take a look!
