### ISSUE TITLE
When searching include in result collection link first

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2318]
When someone is looking for a collection and NFT items are named similar, show collection link first

In this example, I could from search directly land on collection page https://kodadot.xyz/rmrk/collection/160a6f4320f11acb25-LCKWV
![image](https://user-images.githubusercontent.com/5887929/153390805-dcf46540-17b9-4925-aa2d-d9bcce213423.png)

**Comment by petersopko** [comment]
I'd like to work on this one.

**Comment by petersopko** [comment]
This is the task I've mentioned on Friday, sorry for stalling, do you still want this one done? I've just checked https://github.com/kodadot/nft-gallery/pull/2446 and I am wondering how would two of these play together.

**Comment by petersopko** [comment]
> This is the task I've mentioned on Friday, sorry for stalling, do you still want this one done? I've just checked #2446 and I am wondering how would two of these play together.

@yangwao in other words, should "items" have collection links?

**Comment by yangwao** [comment]
mm I guess https://github.com/kodadot/nft-gallery/issues/2376 is more mature for now

Yeah showing extra collection would be nice but I'm afraid that would noise results too much.

Something like recent plays in spotify, or in we discussed it tho #1499
