### ISSUE TITLE
(JS-0387) Prefer that unbound methods are called with their expected scope

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2321]
## Description
Warning is raised when a method is used outside of a method call. Class functions don&#x27;t preserve the class scope when passed as standalone variables.

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/kodadot/nft-gallery/issue/JS-0387/occurrences/](https://deepsource.io/gh/kodadot/nft-gallery/issue/JS-0387/occurrences/)

![image](https://user-images.githubusercontent.com/5887929/153404315-36c0dc54-5ce5-442d-b32a-e9a6aacc59ac.png)

**Comment by kkukelka** [comment]
I'll take this
