### ISSUE TITLE
Find solution to formatting issue of formatBalance helper 👀 

### ISSUE THREAD

**Issue by kkukelka** [kodadot/nft-gallery#2327]
### What happened?

If price point is to high (over 12 decimals), formatBalance helper method has issues correctly formatting value to string.

### Please reproduce in steps

This problem occurs on numerous occasions throughout the app and can easily reproduced if you go to https://beta.kodadot.xyz/spotlight and order by price in descending order (from highest to lowest).

You should see a console warning like this:
<img width="986" alt="Screenshot 2022-02-11 at 07 38 16" src="https://user-images.githubusercontent.com/17953978/153548126-b6b5f8d8-ad39-4651-b7a5-464fdb4e159f.png">

**Comment by yangwao** [comment]
Oh mighty format balance, I recall having headaches in some edge cases, it comes back. 
@kkukelka if you want crack on this, let's do it and then we can merge it to #2316 


<img src="https://media4.giphy.com/media/l0ExsgrTuACbtPaqQ/giphy.gif"/>

**Comment by kkukelka** [comment]
@yangwao I'll give it a look if I find the time. Currently kinda busy IRL 🥵 
Why do we currently format to 12 decimals by default? Has this something to do with the chain itself ?

**Comment by yangwao** [comment]
> @yangwao I'll give it a look if I find the time. Currently kinda busy IRL 🥵 Why do we currently format to 12 decimals by default? Has this something to do with the chain itself ?

Yes, it's 12 decimals set by a chain, each chain has different decimals chosen by their best decision and client-side code should respect it 

Is #2509 related fix?
