### ISSUE TITLE
wallpaper users artist profile and collections

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2329]
Till we implement RMRK::BANNER or our own version of banners, we would be happy for users to by default repeat on x and y with nfts on random basis from recent NFTs 
- by particular aritst
- inside particular collection

Preferably show only static pictures, not moving stuff like gif,SVG,mp4 and 3d objects. 

Put it as background with some light grey scale filter to make other components hover over it.
Probably put behind tabs as well if would not be complicated and won't harm readability 

Thinking let's try with one or two rows, how it would looks like?

![image](https://user-images.githubusercontent.com/5887929/153577055-7fb100d9-ca1b-4306-82e4-f54444c1c01b.png)

inspiration from singular
![image](https://user-images.githubusercontent.com/5887929/153576681-7b533042-3233-4e3a-8f6a-cfcaaebda65d.png)

How to implement: 
1. From the identity call fetch field `additional` where you find md5 hash for profile pic and background
2. Create new query for Subsquid `nftMetaByHash` where you query 

```graphql
query nftMetaByHash($hashes: [String!]!) {
  nftEntities(where: {hash_in: $hashes}) {
    id
    hash
    meta {
      id
      image
      animationUrl
    }
  }
}
```

This query should you return `zero`, `one` or `two` results :)

3. properly handle the image using Cloudflare image cache
4. ???
5. Profit

There is an edge case where we cache identities so having another button in settings for clearing identity cache would be perfect!

### Ref
- https://github.com/kodadot/nft-gallery/issues/2180

**Comment by prachi00** [comment]
@yangwao I'll do this

**Comment by roiLeo** [comment]
Hey! Why don't we try to fetch banner instead? @vikiival told me a while ago: 
> It is stored as the md5 hash of NFT in the on-chain identity (under the attribute additional)

I've already tried to make something work but I didn't know what to do with that hash.

**Comment by yangwao** [comment]
> Hey! Why don't we try to fetch banner instead? @vikiival told me a while ago:
> 
> > It is stored as the md5 hash of NFT in the on-chain identity (under the attribute additional)
> 
> I've already tried to make something work but I didn't know what to do with that hash.

Okay, for artists we can do it in that way use what they set, otherwise fallback to fetch on their behalf and decorate their "home" by their craft.

For collection we can still use it tho.

**Comment by vikiival** [comment]
There is one catch, I need to calculate the md5 hash of the NFT.

It will be added in the upcoming version of rubick 
https://github.com/kodadot/rubick/issues/32

**Comment by vikiival** [comment]
OFC!

I'll update the description

**Comment by yangwao** [comment]
<img src="https://media0.giphy.com/media/26BRuo6sLetdllPAQ/giphy-downsized-medium.gif"/>

**Comment by kkukelka** [comment]
let me take the steering wheel for a sec

**Comment by yangwao** [comment]
<img src="https://media1.giphy.com/media/1hMdSOKEj1ppjftUUY/giphy.gif"/>

**Comment by roiLeo** [comment]
Tested on `/rmrk/u/GZDqGUs564c2pG9K6BjVnEgTnANc8Pr4FfqFr1USBDQ3r62`

**toJson**
```json
{
  "judgements": [],
  "deposit": 49999999500,
  "info": {
    "additional": [
      [
        {
          "raw": "0x75736572706963"
        },
        {
          "raw": "0x3531343961376539393238313635373937353365393061393836333761636631"
        }
      ],
      [
        {
          "raw": "0x6261636b67726f756e64"
        },
        {
          "raw": "0x3566613032333462323431663263363161373664343264306538633464646563"
        }
      ]
    ],
    "display": {
      "raw": "0x43727970746f4456"
    },
    "legal": {
      "none": null
    },
    "web": {
      "none": null
    },
    "riot": {
      "none": null
    },
    "email": {
      "none": null
    },
    "pgpFingerprint": null,
    "image": {
      "none": null
    },
    "twitter": {
      "raw": "0x4063727970746f6476"
    }
  }
}
```

**toHuman**
```json
{
  "judgements": [],
  "deposit": "49,999,999,500",
  "info": {
    "additional": [
      [
        {
          "Raw": "userpic"
        },
        {
          "Raw": "5149a7e992816579753e90a98637acf1"
        }
      ],
      [
        {
          "Raw": "background"
        },
        {
          "Raw": "5fa0234b241f2c61a76d42d0e8c4ddec"
        }
      ]
    ],
    "display": {
      "Raw": "CryptoDV"
    },
    "legal": "None",
    "web": "None",
    "riot": "None",
    "email": "None",
    "pgpFingerprint": null,
    "image": "None",
    "twitter": {
      "Raw": "@cryptodv"
    }
  }
}
```

we have the information in the "additional" property but don't really know what to do with this stuff, can it be used?

**Comment by vikiival** [comment]
yup this is legit, I would just spin up new indexer for on-chain identities

**Comment by yangwao** [comment]
Most likely will be closed in favour
- https://github.com/kodadot/nft-gallery/issues/5286
