### ISSUE TITLE
Add max buy and reorder collection insights 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2330]
Merge 24h volume traded and total volume into one field and put on the original position of floor price.

Put floor price on the position of current 24h volume traded

On position, the total volume traded add 

- the highest buy within the collection.
- number of buys that happened in the collection (like is on series)

The easiest way is to use a subquery.
For higher bounty, writing resolver to subsquid.

![image](https://user-images.githubusercontent.com/5887929/153577798-75ad88dd-7566-4c7c-b59b-07968d5f8f14.png)

**Comment by Jarsen136** [comment]
I will do this task.
