### ISSUE TITLE
Summoning css brain for landing

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2331]
Seems "less than a minute ago" breaking my heart 💔

![Screenshot 2022-02-11 at 12 23 29](https://user-images.githubusercontent.com/5887929/153587658-c22988a7-75f5-4b86-8890-e68fea7ab3b0.png)

**Comment by kkukelka** [comment]
<img width="694" alt="Screenshot 2022-02-11 at 16 42 33" src="https://user-images.githubusercontent.com/17953978/153622147-f41ca93c-39e7-419f-a260-9addaab7b44d.png">

huh...

**Comment by roiLeo** [comment]
> huh...

Responsive breakpoint 🥲

**Comment by yangwao** [comment]
I bet guess so, can't replicate
