### ISSUE TITLE
Adjust sorting to be descending at first click v2

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2337]
- Blocked by #2327
- check series and spotlight

When I click on Price it puts first 4 0.00 as first and then it goes desc.. it's string/bignum issue?

![image](https://user-images.githubusercontent.com/5887929/153457790-08c22edd-fdc9-4218-9247-d75694599952.png)

Score, unique items and unique collections could not be sorted hmm, I recall @roiLeo was looking on this one?

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2316#issuecomment-1035167663_

**Comment by MSghais** [comment]
I work on it !

**Comment by nullscript** [comment]
@yangwao This problem is still caused by formatting issue of formatBalance. Can we just use math division instead of formatting?

**Comment by nullscript** [comment]
217777560000000000
98000000000000000 
23142594502346668 
15758922666666668 
This four numbers can cause formatting issue according to logs

**Comment by preschian** [comment]
hi, I will take a look at this issue
