### ISSUE TITLE
Revisit admin panel v2 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2347]
I guess we should revisit how admin panel works and revisit actual functionality.

- add burn collection #1367 
- burn NFTs one-by-one

![image](https://user-images.githubusercontent.com/5887929/153777761-407437a6-350b-474f-95cf-851485b9dab7.png)

**Comment by yangwao** [comment]
> @yangwao can I take this

hey there, I'm not sure right now if burn collections functionality was actually finished yet? @vikiival 

But burn nfts one-by-one or by the group would be doable.

**Comment by vikiival** [comment]
> I'm not sure right now if burn collections functionality was actually finished yet

I think there was a drama around `CHANGEISSUER` back then :), but both rubick & magick support our own flavour without `ACCEPT`

**Comment by roiLeo** [comment]
Meanwhile Admin panel has been removed
