### ISSUE TITLE
Carbonless Movement v2 -- Own real tree NFT for each 10 mints 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2349]
Climate change has terrible impact on planet, thus we've decided to step up game and contribute in reverting effects on the planet through NFTs. Experimentally we bought credits from offsetra and yet we've decided to go planting with RMTerra for green projects.
Despite Polkadot it lowest carbon footprint (link doc someone from recent tweets pls) we actually would like setup right scheme to help planet and incentivize creators to mint on KodaDot.

Thus my briefly enumaration would be keep numbers simple and plant 1 tree for each 10 mints you make on KodaDot. Plant 1 tree for each 30-50 mints you buy on KodaDot and so on.

I just need get proper number from Pedro and deep dive into numbers to be more in touch with reality and tha's the situation down there in Portugal where we are actually finished first phase of planting trees :)

Actually point would be nice to *own* one tree, so I guess you would be way more incentivized to mint on KodaDot, as we will not giving carbon credits or offsets but hard tree you can pay a visit in Portugal ;)

### Ref
- https://kodadot.xyz/carbonless/
- https://www.youtube.com/watch?v=tFo3vftXsdg
- [13:17] Lightsonemusic: Hi guys from 19 to 20 this month we will be planting more 330 trees for Koda forest 
- ![image](https://user-images.githubusercontent.com/5887929/153850478-a552ee6f-ee68-4230-bf72-b68c541526a0.png)

**Comment by JustLuuuu** [comment]
obsolate
