### ISSUE TITLE
Owners gone missing from series insight?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2358]
I've noticed now that we're missing some columns and now I've realized, we had their unique owners per collection? 

As a number of unique owners tell you the distribution of collection/collectible, it's super needed to have it there
Let's bring it back 😍😇 🙏
![image](https://user-images.githubusercontent.com/5887929/154036791-8029f42b-86b5-437d-8c07-ea11c48eec20.png)

**Comment by roiLeo** [comment]
> I've noticed now that we're missing some columns and now I've realized, we had their unique owners per collection?
> 
> As a number of unique owners tell you the distribution of collection/collectible, it's super needed to have it there Let's bring it back 😍😇 🙏

This one on me, I've removed this column when implementing backend sorting.
- `Collected` column is the number of unique owner
- `Buys` column is the number of owned assets (not owned by nft creator)

What would you like to reflect with `owners` column?

**Comment by yangwao** [comment]
aaah no worries, so it's just a wording issue, can we have `Collected` renamed as `Owners`  please? 🥺 It prevents confusion tho  

Referencing on Opensea https://opensea.io/rankings
