### ISSUE TITLE
MP4 Doesn't Load on Mobile

### ISSUE THREAD

**Issue by akudless** [kodadot/nft-gallery#236]
It seems there is a loading and preview issue with MP4s on mobile. I [minted a MP4 today](https://nft.kodadot.xyz/rmrk/detail/6773661-B2BAC0CE6A55449E03-MOTSURE-MOTSURE_III-0000000000000001) and the preview loads and then you are able to play it on desktop. However, on mobile (iOS, haven't tried android), there is no preview and when play button is pressed, nothing loads.

**Comment by vikiival** [comment]
[HTML5 Video tag not working in Safari , iPhone and iPad
](https://stackoverflow.com/questions/20347352/html5-video-tag-not-working-in-safari-iphone-and-ipad)

**Comment by yangwao** [comment]
I guess introducing own mp4 player might do the job.
Putting $$ if someone want's to hack on this.

**Comment by vikiival** [comment]
Looks like some props fixed the issue
