### ISSUE TITLE
Create twitter bot which will looking for singular links on twitter and posting kodadot links under it to raise awareness about alternative UI

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2369]
This is amazing opportunity to create gpt3 bot which it's sort of make it test humans against artificial audience.

Best not disclose bots name :)

Goal would be drive some more traffic and raise awareness there is also other explorer on top of Rmrk 

https://twitter.com/Fluffy_F_o_x/status/1493651675059527683?t=K24XQR-tI63SUTXb9wDIcg&s=19

**Comment by vikiival** [comment]
![200](https://user-images.githubusercontent.com/22471030/154455679-c43fa64b-944d-4c1b-8a7a-2c501c19537b.gif)

**Comment by yangwao** [comment]
> RMRK team is also putting up a bounty to create a bot that will comment under Kodadot bot's comment with “That’s sad” and "NGMI" gifs

What's sad about it, I don't get it, care to elaborate?

**Comment by Yuripetusko** [comment]
The sad part is that instead of building your own community you are piggybacking on other communities. Other than that I have no objections. We never tried to silence anyone

**Comment by yangwao** [comment]
> The sad part is that instead of building your own community you are piggybacking on other communities.

Why do you think people using RMRK can't be part of KodaDot? I thought we share an audience and we can grow it together in such a small ecosystem.

**Comment by niklasp** [comment]
The first strange fight I experience in DotSama. What is this all about? Money in the end?

**Comment by yangwao** [comment]
uuh 

https://github.com/w3f/polkadot-wiki/commit/bbbb184094d3238fa7c02fca883f59ae9e92320c#diff-e179bfe48b35f5378e985b13eada6c8b2d00e1d2ff485a43c6594f125a887c2cL151

![Screenshot_20230126_182527_GitHub.png](https://user-images.githubusercontent.com/5887929/214906193-9cea2bf7-1cb8-422d-b7be-556753964c3e.png)

![Screenshot_20230126_182544_GitHub.png](https://user-im![Screenshot_20230126_182519_GitHub.png](https://user-images.githubusercontent.com/5887929/214906191-773c395e-6bf1-494d-ade0-9b3eb2aa7464.png)

4d-4045-b000-7534e8931c44.png)

![Uploading Screenshot_20230126_182519_GitHub.png …]()

**Comment by yangwao** [comment]
> What is this all about? Money in the end?

I guess market share and fear. 
Yet RMRK is not even protocol. 
Now RMRK/Singular founder has removed us from official Polkadot Wiki :)
