### ISSUE TITLE
Price range v2

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2370]
While testing for edge cases I found out that "Buy Now" toggle is working well in one way, i.e. to select for prices greater than 0. Doesn't work the other way around, "unlisted" option also shows listed NFTs just without price (this is the case for production as well, not just this branch). Couldn't find solution right away. 
 
I added requested changes, kept the "price range info" style simple in the style of the above search info. 

![image](https://user-images.githubusercontent.com/73316633/154065735-ea1fcabd-8f08-462c-b560-9ddfae950317.png)

Plus 

![image](https://user-images.githubusercontent.com/5887929/154239072-a7a4447a-4f77-4dfc-bb2c-682530ae8b82.png)

_Originally posted by @petersopko in https://github.com/kodadot/nft-gallery/issues/2307#issuecomment-1040241969_

**Comment by petersopko** [comment]
Let me finish this.
