### ISSUE TITLE
Categorize search results in search bar

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2376]
I guess it's time to show collections name match first and items as last.

Once we will have Search for artists as well, we can add it showing users as well

Probably add button on bottom [All Results]

Inspiration from Rarible
<img width="607" alt="image" src="https://user-images.githubusercontent.com/5887929/154325288-6a39aef0-eb3f-49ad-81fa-d25350df6334.png">

**Comment by zhengow** [comment]
I'll take this
