### ISSUE TITLE
Pre-emptively fix Dart Sass 2.0.0 migration warnings

### ISSUE THREAD

**Issue by kkukelka** [kodadot/nft-gallery#2394]
### What happened?

During building the app locally, Sass throws warnings in regards to Dart Sass 2.0.0

```
: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($colorpicker-radius, 1.75) or calc($colorpicker-radius / 1.75)
```

### Screenshots

<img width="607" alt="Screenshot 2022-02-18 at 10 34 35" src="https://user-images.githubusercontent.com/17953978/154656945-daf8b890-a394-4aaa-a613-80417a4b7f02.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kkukelka** [comment]
I'm already onto it.

**Comment by yangwao** [comment]
Sure :) 
Can sponsor it lol

**Comment by kkukelka** [comment]
never mind. fixed through https://github.com/buefy/buefy/releases/tag/v0.9.16
