### ISSUE TITLE
Tile the art 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2397]
For our upcoming physical presence of KodaDot, we would need this functionality to show NFTs in bigger telly screens in gallery :)

Probably add a button next to our current buttons

Icon https://fontawesome.com/icons/table-cells-large?s=solid ?

inspiration is from giphy
https://user-images.githubusercontent.com/5887929/154676690-f15fe446-93f6-4dc1-b307-7a03a3348383.mov

**Comment by ritsuyan** [comment]
Hi, I will do this task.

**Comment by ritsuyan** [comment]
I didn't find this page in main branch.

**Comment by yangwao** [comment]
It should be on item page. Inspiration is from giphy

**Comment by Jarsen136** [comment]
Hello, I will finish this task. @yangwao
