### ISSUE TITLE
Repetitive search shows empty results 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2399]
When I set price filter and then wanted to search for `mug` I've got empty results. If I hit reload it appears back.
Where in that price range Mug was showing.

![image](https://user-images.githubusercontent.com/5887929/154693735-7f534af6-bcb7-40d8-b3bb-e4d28c9099e6.png)

**Comment by newraina** [comment]
> @yangwao I believe whats happening is that price range isn't queried on reload. Can't reproduce your exact case somehow.
> 
>  price-range.mov 
> Should i proceed to fix this in this issue.

As [kkukelka](https://github.com/kkukelka) said, the main problem is not repetitive search but price range prams not works on reload
