### ISSUE TITLE
Show price range next to the filter

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2400]
Show price range next to showing results 

Whenever the filter is folded, users don't see what price range is looking at.

![image](https://user-images.githubusercontent.com/5887929/154693579-c8dae286-85c7-40cb-b28c-21bb66de6205.png)

![image](https://user-images.githubusercontent.com/5887929/154693549-3ac0c555-c658-4ade-8f59-8a15b7d47285.png)

**Comment by prachi00** [comment]
@yangwao I;ll do this

**Comment by zhengow** [comment]
Because of the order of MR, one of my PR leads to this change invalid, plz check the PR #2425
