### ISSUE TITLE
Seems search bar was accidentally reverted to old one

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2405]
I guess it happened here https://github.com/kodadot/nft-gallery/pull/2396

@kkukelka 🥺

![image](https://user-images.githubusercontent.com/5887929/154798446-9f31ed63-67b3-460f-907f-2cfefa374a44.png)

The original one we have 

![image](https://user-images.githubusercontent.com/5887929/154798475-0303368e-211f-4dc3-8cc4-ebdd70cf2fe6.png)

**Comment by kkukelka** [comment]
> I guess it happened here #2396
> 
> @kkukelka 🥺
> 
> ![image](https://user-images.githubusercontent.com/5887929/154798446-9f31ed63-67b3-460f-907f-2cfefa374a44.png)
> 
> The original one we have
> 
> ![image](https://user-images.githubusercontent.com/5887929/154798475-0303368e-211f-4dc3-8cc4-ebdd70cf2fe6.png)

removed `scoped` for now in Navbar.vue... no time currently to investigate further. at least old state is restored.
