### ISSUE TITLE
fix searchbar on mobile

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#2420]
### What happened?

As discussed in #beta, searchbar is gone from Gallery on mobile as presented on the screenshot below. I suggest the following:

While on mobile, in gallery (or collections), keep the searchbar in the container of Gallery/Collections as up until now. When clicked inside, the searchbar moves up, as was done in #2253 . I would remove it from the navbar in this case.

Other than that, it can stay in navbar. 

I think this could both prevent duplicit searchbars and keep easy access to search.

![image](https://user-images.githubusercontent.com/73316633/155004417-6eca7489-59b0-480b-aece-c731d733a21b.png)

### Please reproduce in steps

Go to ... Click on .... See error

### Expected Behavior

I've expected ...

### Screenshots

Paste from your clipboard or upload screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petersopko** [comment]
@yangwao I'd like to fix this if I can proceed with the suggested fix.

**Comment by yangwao** [comment]
Let's go )
