### ISSUE TITLE
Add a wallet selector and add support for Talisman wallet

### ISSUE THREAD

**Issue by helloitsbirdo** [kodadot/nft-gallery#2427]
### Is your feature request related to a problem?

When trying to connect the Talisman wallet ( https://talisman.xyz/ ), it's not `officially` supported and while it DOES work (you can sign TX to mint / buy NFTs), it's not the smoothest experience. 
I've raised this issue which would also need to be looked at when this feature request is picked up!
https://github.com/kodadot/nft-gallery/issues/2426

Talisman have created an easy library for dapps to implement (See below). If the KodaDot designers want to keep their style, you can use just part of the package (to do most of the hardwork for you!) and add your own UI on top.
https://github.com/TalismanSociety/talisman-connect

As more wallets come to the dotsama ecosystem, dapps will need a better way to manage them, this feature request provides some future proofing and also let's KodaDot support Talisman! 

### Describe the solution you would like

As a user on KodaDot
Given I click, `Login`
Then I want to see a modal display which allows me to select my preferred wallet

**first time user of KodaDot**
When I select `Talisman`
Then I want to see a dialog appear showing the different wallets I could link (this is handled by the extension)
And after selecting one or more wallets, the modal should disappear and the dapp should re-load with my data

**I've connected to KodaDot before and I'm a returning user**
Then when I click the wallet of choice, and I select `Talisman`
And after selecting one or more wallets, the modal should disappear and the dapp should re-load with my data

### Describe alternatives you have considered

It's still possible to connect your Talisman wallet and it works, but it's pretty clunky and not a great user experience. 

### Screeenshots

You can see a working implementation of this at -> https://app.talisman.xyz/

![image](https://user-images.githubusercontent.com/93915849/155056678-ebf37c02-3f3e-43a7-b78b-2ee7e51153f9.png)
![image](https://user-images.githubusercontent.com/93915849/155056705-17e290e8-5f0c-4a71-ad5b-ca440cf87c62.png)

**Comment by roiLeo** [comment]
Hey! I really like the idea of being able to select different wallet provider.
Do you have any idea when is the vuejs version of talisman is planned?

**Comment by helloitsbirdo** [comment]
Just wanted to flag there is a $500 bounty for getting this work done!
No plan for vuejs - but you can use the main package (which does most of the work) and then build your own UI @roiLeo
