### ISSUE TITLE
Kodadot / Hiring for NFTs

### ISSUE THREAD

**Issue by btcmacroecon** [kodadot/nft-gallery#2435]
### Discussed in https://github.com/kodadot/nft-gallery/discussions/2433

<div type='discussions-op-text'>

<sup>Originally posted by **btcmacroecon** February 23, 2022</sup>
Hello, 
I am carrying over conversation from social media here. I found my way to Discord after strongly considering boycotting it for eternity last week (it's a pile of crap of a site....but has lots of cool features), but they made me put my phone number in, I hate that kind of control freak, but I wanted to talk with you. I just want to ground myself in reality that I want part time work. I'm tired of fiddle farting around looking, and gave up on commuting 35 miles away to a part time job and got tired of the job that ended with Covid, only to reemerge and they require covid vaxx. It's not that great of an employer and mismanaged. I did enjoy some aspects....and hockey fights.
I have a passion for NFTs and use cases, and why I am interested in Kodadot. I do believe I created one of the first NFTs there. I was impressed early on about the inclusivity, I don't see that normally with blockchain projects, seems there is dev only egotism. I am a non coder. I am not PC. I am an individual.
I have a great deal of skill in blockchain. You may mock my github as I am a non coder, but I know a lot. 
I just want a part time job and would like to fast track this process and create a part time job for myself. I am looking at 15-20 hours worth of work and I would like to team up with 2-3 people, perhaps get some help in the process be it a proposal writer or just find the right people (founders) at Kodadot.
I am interested in use cases and gamification - and using NFTs. I have posted some ideas about use cases I am interested in - things that go far beyond blockchain or just NFTs. I have some ideas around creating equality and a place for civil discourse. I want to work on Oxford Style debates or better yet, a place where people can voice their concerns or a place a team can work in private. I use the Debate Arena often, but it's a use case that is for private teams and full on debate for civil discourse - and would like to create forums for full on debate for the most important topics of the day. For example, don't get me wrong, or poo poo me because I am an environmentalist that DOES NOT BELIEVE IN CLIMATE CHANGE. I won't fault you for the carbonless comment! ok? 
Let's get that out of the way. My point is, I do not believe carbon is even an issue and it is a debatable item.
These facts can be aggregated and looked at on the blockchain. I think it's good civil discourse, but then again I believe the science is in the ice cores, but my whole point is, I am an environmentalist, and just believe we need to have a debate. 
My point of this is to objectify that which we can - via code. We can reify social realm into science. I am a methodologist and a technologist. It's just I am passionate about blockchain and think we can have debates or simply discussions.
I use the DEBATE ARENA example but it can be for a 3-4 person team or non profit. And what I am interested in is creating an equal system of governance and that includes mentorship and a complete black belt system -it's just too elaborate for me, but just an idea. 
I want to find a way to pay people for doing via p2p and mentorship to attain skillsets for sovereign ID where people can learn what they want and advance in a RANK system (like black belt and karate). That black belt can't be taken away, but rather it is credible like a degree. I trained in MMA. The ranks I earned, you can't take them away.But it's like dust in the wind. We need to create like NFTs that are verifiable. We need to create a mentorship  and pilot projects and I guess that is what I am here for. I want to work in Pilot Projects if any interest, or merely I can shut up and dig in and do part time work, it's just shouldn't we do what we want and get paid when it's something of passion?
I want to create NFTs for redemption value for partnerships and alongside sponsors, and I believe KodaDot can achieve this. I am going far beyond blockchain and cartoons. I am going with use cases - for example, say I want to learn MMA either as a student or a coach, I should get paid. A student would need to prove skillsets in a p2p setting. A student should get paid. Hear me out.
Say I want to learn guitar. ( I am a beginner) I should get paid to learn guitar and we can do this. Say I learn a guitar lesson and can prove competency and proof of work. Should I not earn (maybe not a rank) but say I do achieve rank(s), should I not be able to redeem for guitar strings, or picks or even a new guitar? I guarantee you we will find guitar sponsors, open the doors for merchandise - like picks, strings, etc. Same could go for DRUMS. Say I want to learn coding or C++. I should get paid. So this debate arena turns into free education model. Sure beats student debt and corrupt parties politicizing it.
Say we gamify this, and the debate arena can be run as a forum. Say people on the other side of the planet could care less about NFTs but want to get paid to clean up trash or rid the oceans of plastic. We can do this and achieve this at KodaDot.
We must gamify this. A debate can begin as 1 debate. 
A concert series can start with one concert.
A martial arts lesson / mentorship can start small (as a use case)
Same with guitar or drums.
It's just this is where the use cases come in and sponsorships and parters to pay for it and scale it up.
Again, I just want part time work. I have no grande scheme to be much more than someone plugging away at my passions. But this is why I like KodaDot, is because it is inclusive and not egotistical. Often my "words" are taken out of context but I believe we need something much more 3D or 4D than 1D chats. Discord is one step above that or twitter.
I want to create opportunity for NFTs, say how to garden (not just mixed martial arts or guitar). 
Say we create a debate arena but it is really just a forum for classic motorcycles and people can contribute in the forum for quality posts and get paid for pictures and step by step for repairs? Say a sponsor steps up to allow redemption value with the NFTs. 
It is possible. 
These are just ideas. I don't want to beat my head with proposal writing at Polkadot or Kusama. I don't. Those forums are a waste of my time. I delegate that to someone else or better yet, take my ideas elsewhere where people can actually contribute.
What I am trying to do. 
Enough said. </div>

**Comment by yangwao** [comment]
Hey, it's hard for me to decode from issue, which particular part you are interested in to KodaDot help/co-op by your writing.
Let's become our ambassador and let's go from there.

https://docs.kodadot.xyz/ambassador-program/ambassador-intro#the-opportunity
