### ISSUE TITLE
some search suggestion doesn't match the true search result

### ISSUE THREAD

**Issue by zhengow** [kodadot/nft-gallery#2437]
### What happened?

A bug happened!

### Please reproduce in steps

Click # 47

### Expected Behavior

I've expected ...

search # 47

### What browsers are you seeing the problem on?

Microsoft Edge

### Screenshots

Paste from your clipboard or upload screenshots

https://user-images.githubusercontent.com/38389586/155561080-8a5a569e-af49-4b31-96db-df362f415fc5.mp4

see above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Seems I can't reproduce, maybe it's fixed? 

Uploading Screen Recording 2022-03-01 at 10.58.13.mov…
