### ISSUE TITLE
Refresh some page page then redirect to other page

### ISSUE THREAD

**Issue by shixin-guo** [kodadot/nft-gallery#2447]
### What happened?

refresh in Spotlight/series-insight page but redirect to '/rmrk/gallery' when URL includes a query params

### Please reproduce in steps

go to https://beta.kodadot.xyz/series-insight,
change table sort by volume
then refresh page 
will redirect to 
https://beta.kodadot.xyz/rmrk/gallery?sort=-volume&search=&page=1

### Expected Behavior

The page refreshes successfully and the search conditions are correct

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### At which address did you encounter bug?

beta.kodadot.xyz, nft.kodadot.xyz / kodadot.xyz

### Screenshots

Paste from your clipboard or upload screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shixin-guo** [comment]
maybe need change to 
![image](https://user-images.githubusercontent.com/12186221/155749881-11480411-7333-4dc2-9f78-c0d12a44bd54.png)

components/rmrk/Gallery/Search/SearchBar.vue

**Comment by yangwao** [comment]
Legit, I can reproduce.

@shixin-guo go to the https://kodadot.xyz/transfer?usdamount=100 and click on copy payout address while you are logged and I can process your bug report reward once this is merged PR in `main`

**Comment by shixin-guo** [comment]
maybe I can fix it
