### ISSUE TITLE
Create Bumper/Intro for KodaDot youtube channel

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#2459]
Hey we would like to make quick contest for some video/graphic editor to create bumper/intro video for KodaDot youtube channel.

Must meet these conditions:

- KodaDot logo as a main focus
- Multi-use functionality (so it fits for every video)
- Short, quick and high quality animation
- easy to use, with propriate sound (probably mp4 format)
- KodaDot "mindset" related (?-be creative)

Latest [presskit](https://github.com/kodadot/kodadot-presskit/tree/main/v3)

Please post your submissions in this issue.
This contest is open - once suitable work is chosen, the contest will close.

**Comment by jkdizajn** [comment]
Hi, here is my first KodaDot intro video
how do you like it?
https://user-images.githubusercontent.com/81104034/155986651-765cdaad-9b9a-41e0-8511-7dfd66ff126a.mp4

**Comment by cryptodamsky** [comment]
Wow great job @jkdizajn, will definitely use this in the next video!

**Comment by jkdizajn** [comment]
> Wow great job @jkdizajn, will definitely use this in the next video!
> 
> Can you please upload it somewhere so i can download it?

No problemo, here is link: https://drive.google.com/file/d/13zF6cqdEUc51QAVu-mOfYFTy27Dh5vp8/view?usp=sharing

**Comment by ghifari444222** [comment]
hello, tried to make it too :D

here u go:
https://drive.google.com/drive/folders/1OjVdsu3Ow43XCs6aRRvC191S4PeMkI8I

**Comment by ghifari444222** [comment]
bumper koda 2-1 is the one with fading effects at the end :)

**Comment by yangwao** [comment]
> Hi, here is my first KodaDot intro video how do you like it? [user-images.githubusercontent.com/81104034/155986651-765cdaad-9b9a-41e0-8511-7dfd66ff126a.mp4](https://user-images.githubusercontent.com/81104034/155986651-765cdaad-9b9a-41e0-8511-7dfd66ff126a.mp4)

mmm chiptune effects mmm :)

**Comment by yangwao** [comment]
Sent @jkdizajn https://kusama.subscan.io/extrinsic/0xd4620cb4b46417c0d793f57604922d6c7122e2a84d10005a035cca20e8193822

Sent @ghifari444222 
https://kusama.subscan.io/extrinsic/0x0a97e87034b59d60d509e7c0d6275586ddb256715339228e4187a75b39ae6fdf

**Comment by cryptodamsky** [comment]
Thanks everyone for contributing, currently there are 3 intros in use.
