### ISSUE TITLE
KSM address prefix does not match but sent successfully

### ISSUE THREAD

**Issue by magrisya** [kodadot/nft-gallery#2460]
### What happened?

at first I wanted to try to send my NFT to my address.
but i found this 
![Screenshot_4](https://user-images.githubusercontent.com/43703018/155941574-1a814f2e-12f2-4e3b-bcc7-24fbbe414e02.png)
`prefix mismatch expected 2, found 0`
then I tried to send it to the address : `123123123123123`
and I signed my polkadot.js and the result was sent, because there is no correct address filter

### Please reproduce in steps

1. go to https://beta.kodadot.xyz
2. open your profile and go to the Created menu
3. click the NFT you want to send
4. then click the send button
5. then enter free address
6. and send

### Expected Behavior

it shouldn't happen if the address entered is wrong. but here when you want to send to the address 123123123123123 it is actually sent 
![Screenshot_5](https://user-images.githubusercontent.com/43703018/155943052-6cadd0be-ae98-400d-9ea1-1e8981a1afe7.png)
its prof of https://kusama.subscan.io/extrinsic/0x9f0116a2a1163daaf540942e48bd85c9abc92977d45d34712e2e2fdc9d511e7f

profile kodadot : https://beta.kodadot.xyz/rmrk/u/123123123123123?tab=collected

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Mobile iOS Safari, Mobile Android Chrome, Mobile Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz, nft.kodadot.xyz / kodadot.xyz

### Screenshots

https://user-images.githubusercontent.com/43703018/155944222-a8926514-8435-4a1a-b5e8-8b9711f8d8d1.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by magrisya** [comment]
basically the Transfer feature has turned off this invalid address..
but not with Send NFT

![Screenshot_6](https://user-images.githubusercontent.com/43703018/155945961-c6b03501-1f80-45e1-88ef-e10d86127a93.png)

**Comment by yangwao** [comment]
Let's post your payment link so I can payout once this is merged. 
Meanwhile, you should supervise the fixing of this and help with testing when someone makes PR on this to receive bug report bounty earliest.

Put bounty label and priority.

**Comment by magrisya** [comment]
this is my payment address : 
https://kodadot.xyz/transfer/?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq

ok sir i will keep an eye on this fix and will test it when someone finishes doing PR on this issue

**Comment by zhengow** [comment]
> ### What happened?
> at first I wanted to try to send my NFT to my address. but i found this ![Screenshot_4](https://user-images.githubusercontent.com/43703018/155941574-1a814f2e-12f2-4e3b-bcc7-24fbbe414e02.png) `prefix mismatch expected 2, found 0` then I tried to send it to the address : `123123123123123` and I signed my polkadot.js and the result was sent, because there is no correct address filter
> 
> ### Please reproduce in steps
> 1. go to https://beta.kodadot.xyz
> 2. open your profile and go to the Created menu
> 3. click the NFT you want to send
> 4. then click the send button
> 5. then enter free address
> 6. and send
> 
> ### Expected Behavior
> it shouldn't happen if the address entered is wrong. but here when you want to send to the address 123123123123123 it is actually sent ![Screenshot_5](https://user-images.githubusercontent.com/43703018/155943052-6cadd0be-ae98-400d-9ea1-1e8981a1afe7.png) its prof of https://kusama.subscan.io/extrinsic/0x9f0116a2a1163daaf540942e48bd85c9abc92977d45d34712e2e2fdc9d511e7f
> 
> profile kodadot : https://beta.kodadot.xyz/rmrk/u/123123123123123?tab=collected
> 
> ### What browsers are you seeing the problem on?
> Firefox, Chrome, Safari, Microsoft Edge, Mobile iOS Safari, Mobile Android Chrome, Mobile Firefox
> 
> ### Are you logged in?
> Yes
> 
> ### At which address did you encounter bug?
> beta.kodadot.xyz, nft.kodadot.xyz / kodadot.xyz
> 
> ### Screenshots
>  bandicam.2022-02-28.07-18-21-030.mp4 
> ### Relevant log output
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

already fix it, plz take a look

**Comment by yangwao** [comment]
sent payout for bug reporting https://kusama.subscan.io/extrinsic/0x6acfea3b6e8429c3cff42b229a9ed195cb9a552687f648f9be2cd30169b0522c
