### ISSUE TITLE
Website unresponsive if Talisman installed

### ISSUE THREAD

**Issue by helloitsbirdo** [kodadot/nft-gallery#2480]
### What happened?

If the user has Talisman installed,
Upon first loading the Kodadot website,
The website will pop the Talisman extension asking them to Auth their Talisman account
Upon authing, the website will actually load - but no wallet is connected
The user can only select their wallet when clicking `connect`

### Please reproduce in steps

See above

### Expected Behavior

The website should load, without a wallet auth

https://user-images.githubusercontent.com/93915849/156279849-d0d8c210-ace9-4816-9a27-7224266c634d.mp4

### Screenshots

See vide

https://user-images.githubusercontent.com/93915849/156279849-d0d8c210-ace9-4816-9a27-7224266c634d.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
@helloitsbirdo can you check now on `beta.kodadot.xyz` ? I guess it should be resolved :)

**Comment by roiLeo** [comment]
can we close this one?

**Comment by yangwao** [comment]
If @helloitsbirdo can confirm it on https://kodadot.xyz pretty sure! 
Can do close as confirmation it's working well :)

**Comment by roiLeo** [comment]
Closing this since it may have been fixed by #2516 & #2574 
Feel free to reopen if this happens again
