### ISSUE TITLE
Artist profile is broke, missing tabs

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2483]
Seems I can't see artists' categories like
- created
- collections
- sold
- collected

Test case
https://kodadot.xyz/rmrk/u/FSJkXLHuWYfB8DYejjFKX4bkFjb7dMt9RvVpq6D5LUQLY6x
https://beta.kodadot.xyz/rmrk/u/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/5887929/156366790-42935fcc-d076-47a7-adb7-9d5f9681b483.png">

Maybe related https://github.com/kodadot/nft-gallery/pull/2242 ?

**Comment by vikiival** [comment]
There is a lot of errors in the console
<img width="1680" alt="Screenshot 2022-03-02 at 14 06 36" src="https://user-images.githubusercontent.com/22471030/156367376-805d40f5-04a8-4f65-9602-14e7f67a2f12.png">

**Comment by yangwao** [comment]
> There is a lot of errors in the console <img alt="Screenshot 2022-03-02 at 14 06 36" width="1680" src="https://user-images.githubusercontent.com/22471030/156367376-805d40f5-04a8-4f65-9602-14e7f67a2f12.png">

they came with free tax
