### ISSUE TITLE
Showing wrong wallet name in the alert when trying to connect to Subwallet

### ISSUE THREAD

**Issue by sinzii** [kodadot/nft-gallery#2484]
### What happened?

Showing wrong wallet name in the alert when trying to connect to Subwallet

### Please reproduce in steps

1. Prerequisite: Don't have Subwallet installed
2. Click `Connect` on the header
3. Click `Subwallet` in the popup
4. Look at the blue alert

### Expected Behavior

Current behavior showing: `You need to install the - talisman - browser extension`
Expected showing: `You need to install the - Subwallet - browser extension`

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

No

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

![typo](https://user-images.githubusercontent.com/6867026/156351937-7f33a545-656b-40bf-a35b-e4de3a35a428.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
I'll fix this with the others wallet issue
