### ISSUE TITLE
Sticky header broken at Series

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2489]
### What happened?

seems sticky navbar is sticky but not at previous locationthe 

### Please reproduce in steps

go to series insight
scroll down
observe

### Expected Behavior

stay at origin place :)

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz

### Screenshots

https://user-images.githubusercontent.com/5887929/156382609-99b624b7-da42-42b9-aa03-3fa489877481.mov

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prachi00** [comment]
@yangwao I'll check this

**Comment by yangwao** [comment]
Seems this is back and broken :(

**Comment by prachi00** [comment]
Ill check this

**Comment by yangwao** [comment]
> Ill check this

any progress on this?

**Comment by prachi00** [comment]
Thought it was p3, now that its p2, I'll start working on this @yangwao
