### ISSUE TITLE
Typing Errors Cause Blinks

### ISSUE THREAD

**Issue by magrisya** [kodadot/nft-gallery#2490]
### What happened?

I don't know whose fault it is..
is it possible that this is my browser's fault?, because if you type in the letters the send column looks blinking.
i tested it with Chrome V.98.0.4758.102 and Firefox 91.6.0esr.

### Please reproduce in steps

1. Go to profile
2. Go to the Created menu and click one of the NFTs in your wallet.
3. Scroll down
4. Click the Send button

### Expected Behavior

Typing Errors Cause Blinks :ge

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

https://user-images.githubusercontent.com/43703018/156383804-3e64a2bd-c912-4de4-92cb-a92e95e0d38a.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Seems we are missing state it was 📤 sent 🤔

**Comment by magrisya** [comment]
> Seems we are missing state it was 📤 sent 🤔

looks like this problem hasn't been fixed :/

**Comment by yangwao** [comment]
> > Seems we are missing state it was 📤 sent 🤔
> 
> looks like this problem hasn't been fixed :/

let's get someone to fix this and you will be eligible for a bug bounty. 
added bounty and priority.

**Comment by magrisya** [comment]
> > > Seems we are missing state it was 📤 sent 🤔
> > 
> > 
> > looks like this problem hasn't been fixed :/
> 
> let's get someone to fix this and you will be eligible for a bug bounty. added bounty and priority.

Hello mr @yangwao  it looks like this issue is fixed in the current update.
The `Submit Send` button is working fine it will fire if the address is correct and it won't work if the address is wrong even with the same number of characters :)

https://user-images.githubusercontent.com/43703018/159242601-2192911b-4052-40c8-b720-ce3b92a1552a.mp4

**Comment by magrisya** [comment]
sir @yangwao can we close this issue? 👀

**Comment by magrisya** [comment]
sir @yangwao can we close this issue? 👀

**Comment by yangwao** [comment]
Do you know which one resolved this? As don't see which issues is linked 🤔💭

**Comment by magrisya** [comment]
> Apakah Anda tahu yang mana yang menyelesaikan ini? Karena tidak melihat masalah mana yang terkait🤔.💭.
> 
> Jangan ragu untuk mengirim alamat ke barang pembayaran

I don't understand who solved this, because I can't read coding, 
it's clearly something to do with the keyboard 😅

https://kodadot.xyz/transfer/?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq 😅

**Comment by yangwao** [comment]
payout sent https://kusama.subscan.io/extrinsic/12076261-7
