### ISSUE TITLE
Navbar UI not showing via Nova Wallet DApps

### ISSUE THREAD

**Issue by magrisya** [kodadot/nft-gallery#2493]
### What happened?

when I want to open the ***.kodadot.xyz** site via Nova Wallet via DApps,
i don't see any navbar on my andriod phone.
i tested it with 2 devices but the result is the same the navbar is still missing.
affected sites: 
`kodadot.xyz`
`nft.kodadot.xyz`
`beta.kodadot.xyz`

### Please reproduce in steps

Open`kodadot.xyz` `nft.kodadot.xyz` `beta.kodadot.xyz` via DApps Nova wallet.

### Expected Behavior

please check this issues

### What browsers are you seeing the problem on?

Mobile Android Chrome

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Screenshots

![mobile1](https://user-images.githubusercontent.com/43703018/156406786-f7d850ff-791a-4ea8-a69f-9bdb03b9c67e.png)
![mobile2](https://user-images.githubusercontent.com/43703018/156406807-ed17d164-cef3-4abc-addf-598aa3e71680.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Yeah this and missing actions at NFT. We are pretty aware of that however don't know how to debug this. 

Which version of NovaWallet you have?

**Comment by magrisya** [comment]
> Yeah this and missing actions at NFT. We are pretty aware of that however don't know how to debug this.
> 
> Which version of NovaWallet you have?

Is that true? I use nova wallet version 2.4.1-market

but it works on iOS nova with version 2.4.5
and oddly enough the Profile button also seems to be covered by the URL bar : 
![IMG_3869](https://user-images.githubusercontent.com/43703018/156427562-f5dcd97c-6774-4d94-bd7c-3d56e8667637.jpg)

**Comment by roiLeo** [comment]
The default page in nova Wallet is `/rmrk/gallery`, if you keep browsing the app, the navigation bar will appear at some point, weird bug.
We have another issue with nova Wallet as it won't ask at the start of the app to: 
"Allow 'Kodadot' to access your account addresses" wich is blocking the account selection.

**Comment by roiLeo** [comment]
The navigation bar not displaying may come from `isShareMode` from layouts, we could try to remove it to see if it fix the issue

**Comment by yangwao** [comment]
> The navigation bar not displaying may come from `isShareMode` from layouts, we could try to remove it to see if it fix the issue

oh share mode is very old approach we had idea to embed stuff but due some security stuff we discarded I guess. 
Let's give it a hit?

**Comment by roiLeo** [comment]
@vikiival this has most likely been fixed in #2613 😉

**Comment by magrisya** [comment]
![Screenshot_2022-03-24-20-45-30-964_io novafoundation nova market](https://user-images.githubusercontent.com/43703018/159929948-57016fc7-ae5a-423b-bc1a-3d912d2464b4.jpg)

Nah this issue has been patched on  PR #2613
