### ISSUE TITLE
Address KSM does not match but successfully sent

### ISSUE THREAD

**Issue by magrisya** [kodadot/nft-gallery#2494]
### What happened?

this is like a bug I encountered in issue #2460
but this time I found the page https://kodadot.xyz/rmrk/admin/,

in the column "Distribute NFTs to multiple addresses" there is no correct address filter,
so that anything written with 1-3 digit words can be sent even if it is the wrong address.

### Please reproduce in steps

I found it with Google Dork.

> 1. Go to Google and search for "site:kodadot.xyz inurl:admin"
> 2. Click https://nft.kodadot.xyz/ or https://beta.kodadot.xyz/ (it's the same)
> 3. Connect the wallet and select NFT from the collection
> 4. Click the SEND button
> 5. Fill in the invalid address into the field MINT.EXPERT.BATCHSEND. 
> then CLICK TO SEND NFT(S)

### Expected Behavior

supposedly the "**CLICK TO SEND NFT(S)**" button won't light up if it's the wrong address.
"**CLICK TO SEND NFT(S)**" button will light up if the address matches

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Mobile iOS Safari, Mobile Android Chrome, Mobile Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Screenshots

https://user-images.githubusercontent.com/43703018/156430340-40778c0a-8aa9-47c5-a424-2ae9135242e0.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
Hi, I will fix this bug.

**Comment by magrisya** [comment]
> Hi, I will fix this bug.

Letsgoo @Jarsen136

**Comment by magrisya** [comment]
Priority 2 and bug label @yangwao 

https://kodadot.xyz/transfer/?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq

**Comment by magrisya** [comment]
Priority 2 and bug label @yangwao

https://kodadot.xyz/transfer/?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq

**Comment by yangwao** [comment]
> Priority 2 and bug label @yangwao
> 
> [kodadot.xyz/transfer/?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq](https://kodadot.xyz/transfer/?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq)

https://kusama.subscan.io/extrinsic/0x22803d613b1a7d0fd0bba7c6b09b56842444ea977089756ea60ca35745aab4ea

payment sent ;)
