### ISSUE TITLE
Intorducing Aero CSS

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2498]
We got a nice navbar (thx @prachi00) with a new update, which looks pleasing to my eyes. 

<img width="1218" alt="Screenshot 2022-03-04 at 20 22 59" src="https://user-images.githubusercontent.com/22471030/156828311-34c3dd45-ccb6-454f-afa7-599f438ec8e4.png">

I want to utilize this so-called "Aero CSS" (Inspired by Windows) in the other parts of our app.

- [ ] Use Aero effect for Card detail
- [ ] Use Aero effect for login (wallet select) modal
- [ ] Use Aero effect for loader (if not implemented yet)

Moodboard: 
<img width="880" alt="Screenshot 2022-03-04 at 20 21 40" src="https://user-images.githubusercontent.com/22471030/156828955-cc453816-cb69-41ed-a329-cf6452f9c6de.png">

<img width="639" alt="Screenshot 2022-03-04 at 20 28 07" src="https://user-images.githubusercontent.com/22471030/156828995-95c6801b-1768-4753-9fe9-59d2eea87e81.png">

https://regen-vs-degen.com

<img width="1680" alt="Screenshot 2022-03-04 at 20 55 12" src="https://user-images.githubusercontent.com/22471030/156832653-a000fa80-c85d-4b96-9303-505a8b06b4c2.png">

**Comment by prachi00** [comment]
@vikiival I'll try to do this

**Comment by vikiival** [comment]
Just to be clear
### Card detail

<img width="396" alt="Screenshot 2022-03-05 at 10 44 19" src="https://user-images.githubusercontent.com/22471030/156877852-77e97441-7526-47f4-94cf-c2ce03525fee.png">


### login (wallet select)
<img width="431" alt="Screenshot 2022-03-05 at 10 31 11" src="https://user-images.githubusercontent.com/22471030/156877838-5d7b3f8e-a11d-44d3-8b83-f170dd7d6ac4.png">

### loader

Looks like it's like semi-implemented

**Comment by Jarsen136** [comment]
@vikiival hello, I have done this task！
