### ISSUE TITLE
Remove border from gallery & collection item 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2503]
To make UI more lightweight, let's remove the border from the card at

- gallery items 
- collections items
- collection items
- on an artist profile (created,collections,sold,collected)

Remove radius on corners as well

<img width="459" alt="image" src="https://user-images.githubusercontent.com/5887929/156878454-d7a798b1-ba3a-4d60-941e-cb2b610c3463.png">

**Comment by prachi00** [comment]
@yangwao I can do thisss
