### ISSUE TITLE
Cache request from Identity popover

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2505]
### Is your feature request related to a problem?

I just realized that spotlight does more than **140** queries to magick, a vast number.

### Describe the solution you would like

I would like to see that these requests are cached for 12hrs or so

### Describe alternatives you have considered

Use Vuex :)

### Screeenshots

<img width="474" alt="Screenshot 2022-03-05 at 17 47 58" src="https://user-images.githubusercontent.com/22471030/156892425-7a5f3121-a68b-4313-a8b2-6cb9d5fb2081.png">

<img width="407" alt="Screenshot 2022-03-05 at 17 48 20" src="https://user-images.githubusercontent.com/22471030/156892437-00701e37-ffec-49b6-ae3c-368206d9f068.png">

**Comment by zhengow** [comment]
I'd like to do this

**Comment by zhengow** [comment]
> ### Is your feature request related to a problem?
> I just realized that spotlight does more than **140** queries to magick, a vast number.
> 
> ### Describe the solution you would like
> I would like to see that these requests are cached for 12hrs or so
> 
> ### Describe alternatives you have considered
> Use Vuex :)
> 
> ### Screeenshots
> <img alt="Screenshot 2022-03-05 at 17 47 58" width="474" src="https://user-images.githubusercontent.com/22471030/156892425-7a5f3121-a68b-4313-a8b2-6cb9d5fb2081.png">
> 
> <img alt="Screenshot 2022-03-05 at 17 48 20" width="407" src="https://user-images.githubusercontent.com/22471030/156892437-00701e37-ffec-49b6-ae3c-368206d9f068.png">

I think the requests are from components/rmrk/Gallery/GalleryItem.vue

![image](https://user-images.githubusercontent.com/38389586/156972627-ca1ad34a-8b6b-4e3c-ba0f-ab5a1ec645cf.png)

![image](https://user-images.githubusercontent.com/38389586/156972590-6db51d5d-930b-4f05-9a88-03faeaf34c5d.png)

![image](https://user-images.githubusercontent.com/38389586/156972695-0de78023-8d10-4bec-9af4-5ffd46981965.png)

**Comment by roiLeo** [comment]
> I think the requests are from components/rmrk/Gallery/GalleryItem.vue

not on `gallery/:id`, check `/spotlight` page and you'll see lot of query that comes from `IdentityPopover` component

**Comment by vikiival** [comment]
> I just realized that spotlight


yup this issue is related to spotlight.

> I think the requests are from components/rmrk/Gallery/GalleryItem.vue

@zhengow this poll request is intentional as we need to update the price and current owner

**Comment by zhengow** [comment]
> > I just realized that spotlight
> 
> yup this issue is related to spotlight.
> 
> > I think the requests are from components/rmrk/Gallery/GalleryItem.vue
> 
> @zhengow this poll request is intentional as we need to update the price and current owner

Got it. I pull a request about this issue, plz check.
About "cached for 12hrs or so". Does vuex support expire time? Or maybe I have to use something like "sessionStorage"/"localStorage" ?

**Comment by vikiival** [comment]
> Does vuex support expire time?

no but there is a supper easy solution to implement this

**Comment by zhengow** [comment]
> > Does vuex support expire time?
> 
> no but there is a supper easy solution to implement this

guess setInterval?
