### ISSUE TITLE
Some develop questions about project

### ISSUE THREAD

**Issue by zhengow** [kodadot/nft-gallery#2514]
Hi there!
Q1. API document: I'm wonder when developer write the graphql request, where's the document that explains what's the input parameters and output.

Q2. Terms Document: Where can I learn the terms in this project? For example, I am confused about the difference between the name and symbol. So I simply create one to figure them out. 

Q3. Mint fee: continue with Q2, mint costs me a lot, I have no idea how much I have to pay for mint, is there any hint or document to explain this?

**Comment by vikiival** [comment]
Hei!

### 1. Where API

For implementation of RMRK we use two indexers: [magick by SubQuery](https://github.com/vikiival/magick) and [rubick by SubSquid](https://github.com/kodadot/rubick)

Both implementations are super similar however rubick offers a bit more features.
Schemas are visible in `schema.graphql`

### 2. Bruno the Witcher

Currently KodaDot is using RMRK 1.0 for the NFTs. [The specification can be found here](https://github.com/rmrk-team/rmrk-spec/tree/master/standards/rmrk1.0.0)

### 3. Mint fee

Minting fee is usually a matter of cents but I recommend to use test-net instead of burning KSM. Just switch to the Westend as you can see on the screenshot
<img width="666" alt="Screenshot 2022-03-07 at 11 44 01" src="https://user-images.githubusercontent.com/22471030/157016407-94450ce0-67e2-4a1f-b74e-f9f79e0fdf74.png">

**Comment by zhengow** [comment]
> Hei!
> 
> ### 1. Where API
> For implementation of RMRK we use two indexers: [magick by SubQuery](https://github.com/vikiival/magick) and [rubick by SubSquid](https://github.com/kodadot/rubick)
> 
> Both implementations are super similar however rubick offers a bit more features. Schemas are visible in `schema.graphql`
> 
> ### 2. Bruno the Witcher
> Currently KodaDot is using RMRK 1.0 for the NFTs. [The specification can be found here](https://github.com/rmrk-team/rmrk-spec/tree/master/standards/rmrk1.0.0)
> 
> ### 3. Mint fee
> Minting fee is usually a matter of cents but I recommend to use test-net instead of burning KSM. Just switch to the Westend as you can see on the screenshot <img alt="Screenshot 2022-03-07 at 11 44 01" width="666" src="https://user-images.githubusercontent.com/22471030/157016407-94450ce0-67e2-4a1f-b74e-f9f79e0fdf74.png">
> 
> ### Other FAQ
> Other information can be found in our [docs](https://docs.kodadot.xyz)
> 
> cc @damsky (if you can find something docs worthy here)

Got it, thanks:)

**Comment by zhengow** [comment]
have no idea I have to pay 1.5KSM to mint T_T
![image](https://user-images.githubusercontent.com/38389586/157169737-d1c65e30-5846-4488-9e4a-0fadf820d2b6.png)

**Comment by cryptodamsky** [comment]
hey @zhengow have you read my reply to you in #2276?

I've done a fresh mint transaction for you to see how much the fees are. Did you actually try to mint?

You might have a look at it again. 

https://kusama.subscan.io/extrinsic/11705319-2

**Comment by cryptodamsky** [comment]
ok, i see, can you paste the transaction hash (extrinsic ID) here so we can have a look? @zhengow

**Comment by zhengow** [comment]
> ok, i see, can you paste the transaction hash (extrinsic ID) here so we can have a look? @zhengow

Sure, it's 0xa8618bcdd574a805438ea360873d60889e3ec154c0a3938fb1585e68914e780f

**Comment by vikiival** [comment]
Oh related to fees: 
we have a flat fee policy (#1967) (metahours #2/#3) which means: 0.5$ to cover pinning services && 0.5$ to support KodaForrest 

This can be turned off in the settings

but your tx for 1.5 KSM look def strange

**Comment by yangwao** [comment]
> Q1. API document: I'm wonder when developer write the graphql request, where's the document that explains what's the input parameters and output.

We will have a workshop on how to write queries into KodaDot this Thursday 7/4 5pm UTC+2, it will be also recorded
https://discord.com/events/840514076538830888/960568698593222717

> have no idea I have to pay 1.5KSM to mint T_T

Hey @zhengow we are checking on this and most likely we will refund you 1.5KSM back as seems some weird glitch happened. If you could elaborate on what you've been doing? I know it's a month ago just happy to nail down the bug if maybe was meanwhile fixed.

https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws?tab=transfer
![image](https://user-images.githubusercontent.com/5887929/161731929-414bd5bc-8b0b-4b9a-ae6e-e45d9f9a840d.png)

**Comment by zhengow** [comment]
> > Q1. API document: I'm wonder when developer write the graphql request, where's the document that explains what's the input parameters and output.
> 
> We will have a workshop on how to write queries into KodaDot this Thursday 7/4 5pm UTC+2, you are invited to come over! it will be also recorded https://discord.com/events/840514076538830888/960568698593222717
> 
> > have no idea I have to pay 1.5KSM to mint T_T
> 
> Hey @zhengow we are checking on this and most likely we will refund you 1.5KSM back as seems some weird glitch happened. If you could elaborate on what you've been doing? I know it's a month ago just happy to nail down the bug if maybe was meanwhile fixed.
> 
> https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws?tab=transfer ![image](https://user-images.githubusercontent.com/5887929/161731929-414bd5bc-8b0b-4b9a-ae6e-e45d9f9a840d.png)
> 
> @zhengow please let me know if I can refund you at the same address 1.5 KSM https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws

Yes, I still use this address, thanks a lot:)

**Comment by vikiival** [comment]
> maybe was meanwhile fixed.

Yup :) https://github.com/kodadot/nft-gallery/pull/2784

**Comment by niklasp** [comment]
> We will have a workshop on how to write queries into KodaDot this Thursday 7/4 5pm UTC+2, you are invited to come over! it will be also recorded
> https://discord.com/events/840514076538830888/960568698593222717

Is there a recording of this, I am interested as well, or could there be a new workshop on that?

**Comment by vikiival** [comment]
> Is there a recording of this, I am interested as well, or could there be a new workshop on that?

https://github.com/kodadot/nft-gallery/issues/2715#issuecomment-1114708124
