### ISSUE TITLE
Make non-blocking connection to the extensions

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2516]
Currently the app is blocked when until you don't accept/reject extensions. 

<img width="1061" alt="Screenshot 2022-03-05 at 10 29 09" src="https://user-images.githubusercontent.com/22471030/156877459-ce5cbff8-fca6-486c-8f16-ccbc890fcd72.png">

The good approach would be to only request extension when user clicks on it. 

The edge case is that we should somehow cache the last logged wallet (e.g which extenstion and address you used)

So using any storage (vuex, localStorage would be a good option) // I prefer Auth vuex here

Ref #2480

_Originally posted by @vikiival in https://github.com/kodadot/nft-gallery/issues/2482#issuecomment-1060368537_

**Comment by SubWalletApp** [comment]
I tested it still not working properly at my computer. Pls check.
https://www.loom.com/share/a186677f0e24452497bda6cf7e28edb0

**Comment by yangwao** [comment]
Added bounty labels plus please record test cases in PR, that's it's working and solved :)
