### ISSUE TITLE
Do not listen keyboard shortcuts while in focus input

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2531]
search works, yet keyboard shortcuts listen every time, even in input which I guess should not
 
Make it that keyboard shortcuts don't listen once you are focused on input.

https://user-images.githubusercontent.com/5887929/158019026-07ebc057-64d7-4fe8-a9a3-2c07e79e3399.mov

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2200#issuecomment-1065879948_

**Comment by Jarsen136** [comment]
Let me have a try to fix it.
