### ISSUE TITLE
Post fixes in sales feed of collection

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2539]
Post fixes in sales feed of collection
- show default BUY events when you open History
- fix CSS to show it in one line, probably clip long identities

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/5887929/158189355-e459a888-7cb1-46ec-b447-4d1ea739e6e9.png">

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2523#issuecomment-1066839622_

**Comment by prachi00** [comment]
@yangwao I'll do this

**Comment by prachi00** [comment]
@yangwao the css thing is not happening for me

**Comment by yangwao** [comment]
Meanwhile #2552 has done some stuff I guess so
