### ISSUE TITLE
Showing context of page in navbar

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2540]
Whenever someone is browsing 
- collection
- profile
- item

It's not needed to show them buttons like Create, Explore, Stats, chain, Language and would rather strip it as probably don't use it all.  
 
Instead would be nice to show on that place name of 
- collection
- artist 
- title of nft item

So desired results would be once user scrolls down, fading away buttons and replace it with text. 
If it's long, strip it from end, as in case of similar named collection, higher chance number will be on the end of collection.

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/5887929/158192385-89cf3e9a-ed8e-449d-9852-c4120e0c429c.png">

The best inspiration is at how the GitHub app on mobile works. Best check video and how navbar behaves there

https://user-images.githubusercontent.com/5887929/158193913-060d8711-2bbb-4572-8c98-0a962a1ecc5f.mp4

Plus on the desktop looks like this (tbh haven't noticed till noticed, pretty used for it like it's been there forever)

https://user-images.githubusercontent.com/5887929/158206518-e3f09ea1-89b5-4fa3-937e-835430976ecb.mov

**Comment by Jarsen136** [comment]
I will work on this task.
