### ISSUE TITLE
Create validation component or filter 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2541]
Probably systematic move would create a component or filter to validate these kinds (is it right ksm address? is it able to send? is it legitimate action to make? I'm owner to do so? &c) of inputs as we are having these inputs pretty more places and actionable components.
It would make us more robust and probably antifragile to the future cases as well.

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2494#issuecomment-1066971742_

**Comment by shixin-guo** [comment]
I can help to do this,

**Comment by yangwao** [comment]
Sure, let's go

**Comment by vikiival** [comment]
👀

**Comment by shixin-guo** [comment]
so sorry, these days we are focusing on other things, can you help to fix it @yangwao @vikiival

**Comment by roiLeo** [comment]
We currently have `AddressInput` component that will check the address correct format, we may need to modify it a little to check the recipient's account(s)/name

**Comment by vikiival** [comment]
>  we may need to modify it a little to check the recipient's account(s)/name

Do you have something specific on your mind?

**Comment by roiLeo** [comment]
> Do you have something specific on your mind?

I was thinking to display identity from address and maybe add a warning message when no identity is found

**Comment by vikiival** [comment]
That's actually smart 🚀

**Comment by roiLeo** [comment]
- https://github.com/kodadot/nft-gallery/blob/main/components/shared/AddressChecker.vue
- https://github.com/kodadot/nft-gallery/blob/main/components/shared/AddressInput.vue
