### ISSUE TITLE
Bug in history component for list, unlist, mint?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2546]
As I guess list and unlist is made just by owner and why is in To other address?

check at https://beta.kodadot.xyz/rmrk/collection/2644199cf3652aaa78-KK01?tab=history

The list should be only by owner I guess? 

list
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/5887929/158365389-be118da8-4ac9-40de-9dfa-51ea90f268f5.png">

unlist
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/5887929/158366473-bc220986-8a58-4530-89a8-3682de25bf18.png">

same go for mint? 

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/5887929/158366662-683a1464-f86b-42db-ab05-d9b5d557588c.png">

**Comment by zhengow** [comment]
> IMO, this will be fixed in #2545 ![Screenshot 2022-03-15 at 17-08-04 Kusama Kings](https://user-images.githubusercontent.com/9987732/158421389-61b2b962-0cfc-4f34-96ad-bc6769831a20.png)

I think this issue is related to Vue Vdom algorithm. And I don't see the :key attribute in #2545, so I PR with this.
What do u think:)
`<b-table :data="data" class="mb-4" hoverable :key="Date.now()">`
