### ISSUE TITLE
Made search bar more transparent and bit wider 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2549]
Once #2540 done 

Make search bar 
- transparent, like rgba `.1` or `.0` 
- wider 400px 
- keep only border-top 1px pink line

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/5887929/158371288-a6b30337-f4bb-4430-bd1d-56d721628170.png">

**Comment by prachi00** [comment]
@yangwao I'll do this

**Comment by yangwao** [comment]
> @yangwao I'll do this

curious what's update? would be nice to push it into planned release :)
I guess #2548 is mergeable and don't expect any major changes there

**Comment by prachi00** [comment]
> > @yangwao I'll do this
> 
> curious what's update? would be nice to push it into planned release :) I guess #2548 is mergeable and don't expect any major changes there

@yangwao shouldnt #2540 be merged first before doing this?

**Comment by yangwao** [comment]
On your PR deployment is perfectly fine!

<img width="640" alt="image" src="https://user-images.githubusercontent.com/5887929/158808244-7b287318-ebad-4ea5-8457-e11601aa91f3.png">

but somehow merged to `main` it's not, but has some CSS properties there.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/5887929/158808372-5450e07a-f1ac-4fc5-9961-724f9479afb8.png">

care to look on it? 🥺 🫶

**Comment by prachi00** [comment]
@yangwao checking this
