### ISSUE TITLE
Add ability to download asset you own from actions

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2557]
As we disabled right-click context menu #2443 
despite PFP culture, we would like to enable owners, to download their assets and used them elsewhere. (twitter, discord, telegram,steam, elsewhere social network)

Add to action list 
[Right-Click-Save] use club-mate yellow, posting pic for reference:D
 
and it will download the asset at which you are the owner.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/5887929/158590529-5f99b737-9e76-4bbf-b15a-9200cba81733.png">

![image](https://user-images.githubusercontent.com/5887929/158591186-60cff65f-3d84-4e54-bb77-390dc245fc1a.png)

**Comment by Jarsen136** [comment]
I will work on this task.

**Comment by Jarsen136** [comment]
> Add to action list [Right-Click-Save] use club-mate yellow, posting pic for reference:D
> 
> and it will download the asset at which you are the owner.
> 

Only right-clic button can save the image? Or maybe single click button to save image, which is my preference.
@yangwao

**Comment by yangwao** [comment]
> > Add to action list [Right-Click-Save] use club-mate yellow, posting pic for reference:D
> > and it will download the asset at which you are the owner.
> 
> Only right-click button can save the image? Or maybe single click button to save image, which is my preference. @yangwao

for simplicity, we would like to keep the disabled right-click context menu.

and enable a single-click button on actions to save the image.
