### ISSUE TITLE
Add link to collection history into series 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2562]
Adding a link similar to a link to a chart like when someone clicks on the icon next to chart will land on history tab of the collection.

i.e. someone will want to see Donkey Gang, will directly go from Series to History tab like https://deploy-preview-2552--koda-nuxt.netlify.app/rmrk/collection/0a8ce195286c168f19-DONKEY?tab=history

Plus for activity and history, 
once user clicks, scroll viewport directly to chart or history tab

**Comment by Jarsen136** [comment]
I will work do this task.
