### ISSUE TITLE
Wrong Items count in social media preview

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2563]
curious, from where that 16 item comes from?  https://beta.kodadot.xyz/rmrk/collection/0a8ce195286c168f19-DONKEY?tab=history

![image](https://user-images.githubusercontent.com/5887929/158689355-9e4750dd-5337-4768-a7cf-c620cbb5c75f.png)

![image](https://user-images.githubusercontent.com/5887929/158689368-f52b0173-05b4-4e62-afb4-7e3150e973c4.png)

**Comment by Jarsen136** [comment]
Hello, I will deal with it.

**Comment by kkukelka** [comment]
just glancing over the code it should work as intended 🤔 
```javascript
numberOfItems: this.collection?.nfts?.length || 0,
```

**Comment by roiLeo** [comment]
> just glancing over the code it should work as intended 🤔
> 
> ```js
> numberOfItems: this.collection?.nfts?.length || 0,
> ```

This won't work it will always show the `first` length which is 16
Solution could be 
```js
numberOfItems: this.total || 0,
```

**Comment by kkukelka** [comment]
> > just glancing over the code it should work as intended 🤔
> > ```js
> > numberOfItems: this.collection?.nfts?.length || 0,
> > ```
> 
> This won't work it will always show the `first` length which is 16 Solution could be
> 
> ```js
> numberOfItems: this.total || 0,
> ```

Ahh, interesting. Will fix this asap
