### ISSUE TITLE
Don't show buy when it's not for sale

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2575]
I guess we don't want to show the buy button when art is not on sale, even it's disabled?
But hence we can show related NFTs from particular collection/artist re #990

happened at https://deploy-preview-2558--koda-nuxt.netlify.app/rmrk/gallery/10279780-0a8ce195286c168f19-DONKEY-DONKEY_GANG_120-0000000000000120

<img width="351" alt="image" src="https://user-images.githubusercontent.com/5887929/158796423-72607478-dcb1-41f5-bfe7-3f8538158f94.png">

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/5887929/158796502-81753ec7-cdf2-40ea-a15c-6aad02bd5837.png">

### Ref
- https://github.com/kodadot/nft-gallery/issues/957
- https://github.com/kodadot/nft-gallery/issues/990

**Comment by Jarsen136** [comment]
Hi, I will work on this.
