### ISSUE TITLE
Keep only top-border on pagination and sharing buttons

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2578]
- Keep only top-border on pagination buttons

Probably reflect everywhere where we are using pagination
- gallery
- collections
- artists profile
- collection detail

<img width="643" alt="image" src="https://user-images.githubusercontent.com/5887929/158810127-1434eb46-b0e8-4e13-9ac2-4f10f8a28f75.png">
<img width="382" alt="image" src="https://user-images.githubusercontent.com/5887929/158810964-d8d14d2a-da2c-45bf-b070-aefc0681e185.png">

On collection detail like at https://beta.kodadot.xyz/rmrk/collection/0a8ce195286c168f19-DONKEY?tab=collection
- Keep only top-border on sharing and make it 1px
<img width="190" alt="image" src="https://user-images.githubusercontent.com/5887929/158810217-e496cc4a-09e1-4eda-8201-2afd4549c1a6.png">

For item action buttons and sharing do the same 🥺
<img width="340" alt="image" src="https://user-images.githubusercontent.com/5887929/158810300-b1bb6ab5-a5da-4f56-8307-ff9b0ac35fa0.png">

**Comment by prachi00** [comment]
@yangwao I'll do this
