### ISSUE TITLE
Pagination on history collection component is wonky

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2582]
I guess happens bc it's in history component? Thus smaller component somehow?

![Screenshot_2022-03-18-08-11-17-49_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/5887929/158953893-69771d18-c7c1-44d9-9aea-06fb2938bc6f.jpg)

**Comment by prachi00** [comment]
@yangwao I'll check this
