### ISSUE TITLE
Keyboard shortcuts on the "Create" page

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#2584]
### What happened?

Keyboard shortcuts to delete text
this is caused by keyboard shortcuts
especially g+a

### Please reproduce in steps

When writing text in a newly created NFT, I noticed that sometimes the page loads itself, for example to the gallery or to my profile. Then, of course, the whole text was washed away and I had to write it again....
![obrázok](https://user-images.githubusercontent.com/81104034/158958747-c391a167-5607-4eaf-8990-b9e0ecf88e30.png)
I suggest disabling keyboard shortcuts wherever text can be typed, i.e. when creating new collections and NFTs

### Expected Behavior

I expected that not to happen :) 
this is caused by keyboard shortcuts
especially g+a
I suggest disabling keyboard shortcuts wherever text can be typed, i.e. when creating new collections and NFTs

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

https://user-images.githubusercontent.com/81104034/158958997-86ce00db-ff22-4f4b-8db7-19f71f4ff5af.mp4

### Payment link for reward

https://kodadot.xyz/transfer?target=FqCJeGcPidYSsvvmT17fHVaYdE2nXMYgPsBn3CP9gugvZR5&usdamount=10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
#(disable keyboard shortcuts in input) there was issue about that and apparently didn't cover create as well )

**Comment by Jarsen136** [comment]
I will fix the bug.

**Comment by yangwao** [comment]
Payout sent for bug reporting @jkdizajn 
https://kusama.subscan.io/extrinsic/0x13344480bcea11ee38958f206be9a153fff7a488c7ecd62f4ec65f3304424040 

:)
