### ISSUE TITLE
Apparently Subwallet doesn't work on Connect

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2590]
Apparently, Subwallet doesn't work on Connect, let's crack on this why in another issue to push this forward :)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2574#issuecomment-1072989339_

**Comment by Jarsen136** [comment]
Hello, I can do this task.

**Comment by vikiival** [comment]
<img width="130" alt="Screenshot 2022-03-20 at 11 37 28" src="https://user-images.githubusercontent.com/22471030/159158463-3fa8d396-7ff4-4600-8697-8b7a96c54af8.png">

Looks like my account was disabled ://

**Comment by Jarsen136** [comment]
> <img alt="Screenshot 2022-03-20 at 11 37 28" width="130" src="https://user-images.githubusercontent.com/22471030/159158463-3fa8d396-7ff4-4600-8697-8b7a96c54af8.png">
> 
> Looks like my account was disabled ://

Maybe you need to reinstall the wallet extension ?

I find that it does not load the address list as my wallet account is visible. Then I fix it in my pr.

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/31397967/159159002-c4ee5f44-6d04-4de1-859d-61d2f80aa8db.png">

**Comment by roiLeo** [comment]
I just tested it (on firefox & chrome) and it does work for me
