### ISSUE TITLE
Sharing search url with page number is broken

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2591]
Plus I've found another issue, when I share someone's URL https://beta.kodadot.xyz/rmrk/gallery/?search=nft&page=10 it actually pushes me on page 1, rewriting the 10th page to first. If you can fix it with this that would be superior! :)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2513#issuecomment-1072998406_

**Comment by Jarsen136** [comment]
Hey, I can fix it!
