### ISSUE TITLE
When I want to search particular term from landing, won't redirect me to search

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2592]
when I try to search nothing in item name or collection, on pressing enter I should land on the gallery with searched term and showing results

I.e. I should land at here https://beta.kodadot.xyz/rmrk/gallery?search=Talisman&page=1

https://user-images.githubusercontent.com/5887929/159120788-601192c5-815c-4dd0-a79e-51c0275d134a.mov

### Ref
- #1655 
- #2513
- #2591

**Comment by Jarsen136** [comment]
Hi, I will deal with it.
