### ISSUE TITLE
Show only identities that are verified

### ISSUE THREAD

**Issue by magrisya** [kodadot/nft-gallery#2595]
### What happened?

i used a fake identity and i stole that name in the top spotlight and it worked.
maybe it will affect my account if i sell NFT and will get profit myself.
because someone will be fooled and unknowingly to buy it, because of the NFT maker of RMRK Official.

![Screenshot_2](https://user-images.githubusercontent.com/43703018/159123517-53ef0bbe-8ad9-47c2-a0f1-423968e99e76.png)

### Please reproduce in steps

go to profile --> identy --> and then steal the name of a famous identity

### Expected Behavior

this shouldn't have happened if that identity was already in use :)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Mobile iOS Safari, Mobile Android Chrome, Mobile Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Screenshots

https://user-images.githubusercontent.com/43703018/159123642-19162b51-1481-451c-a4e4-29ad855bc78a.mp4

### Payment link for reward

https://kodadot.xyz/transfer?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq&usdamount=10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
I guess identity 🆔 is not unique like ENS, but we're thinking make it more unique.

>used a fake identity and i stole that name in the top spotlight and it worked.

Can you post recording from this?

**Comment by magrisya** [comment]
> I guess identity 🆔 is not unique like ENS, but we're thinking make it more unique.
> 
> > used a fake identity and i stole that name in the top spotlight and it worked.
> 
> Can you post recording from this?

yeah right i also think so identity is not like ens but can you make it unique in kodadot? so that the name that has been used can not be used again?.

for example I have cloned the official name and nft rmrk :

![Screenshot_1](https://user-images.githubusercontent.com/43703018/159132228-3bf4dc3c-6dbc-4dc4-b603-158a882f5c0f.png)

https://kodadot.xyz/rmrk/detail/11238345-e0b9bdcc456a36497a-RMRKBNNRS-BREACH-0000000000000001 <-- REAL
https://kodadot.xyz/rmrk/gallery/11877427-A2421E1ACB58485A27-BREACH-BREACH-0000000000000001 <--- FAKE

Isn't it almost the same as the original?
someone who is drunk will buy a fake one, so someone who cheats installs fake nft at a lower price and in the name of the RMRK official

**Comment by vikiival** [comment]
The possibility is to show only verified identities: 
The second option is that we can probably give the other color (like green for verified addr)

**Comment by magrisya** [comment]
> The possibility is to show only verified identities: The second option is that we can probably give the other color (like green for verified addr)

if it's just to give color maybe the new face in kodadot will feel confused.
how to add a blue tick or something.
that if it can be achieved and if you want :)

**Comment by magrisya** [comment]
hey someone has bought this nft and they are selling it for a higher price. @yangwao will you prioritize this issue or not?. :))
I want to thank him for testing this invention, I will buy it if the price will go back to the way it was.

It's a good idea if you create a red flag display like this: 
![IMG_20220324_052805](https://user-images.githubusercontent.com/43703018/159807030-d9b7a96b-9121-4726-b389-29a17e1ca40a.jpg)

**Comment by vikiival** [comment]
> It's a good idea if you create a red flag display like this:
Hey we don't have any centralized DB where we can mark people as plagiators
with upcoming token we can solve this by decentralized way

**Comment by yangwao** [comment]
> @yangwao will you prioritize this issue or not?

sure putting in pipe :)

**Comment by vikiival** [comment]
ref: https://github.com/kodadot/rubick/issues/56
