### ISSUE TITLE
Chance to embed/link RMRK to cryptovoxels

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#26]
Yup, we got requests from famous NFT creators and they want to show their KodaDot mints in metaverses.
This issue will help resolve how to embed KodaDot NFTs there. We already support iframes. 
If we need to be integrated by virtual world, it's good to have them chat

- [ ] Decentraland
- [ ] Cryptovoxels
- [ ] Somnium
- [ ] bit.country
- [ ] What are other metaverse worlds?

**Comment by hiimbobdcl** [comment]
Im looking into it.

**Comment by hiimbobdcl** [comment]
iframes can't be embedded into DCL I'm afraid, the engine has no way to interpret HTML elements
perhaps you could import an image from an ipfs hash, just as you would import any image for a texture from an external URL
I haven't tried this, but if there's a URL you can point to it, it should work
https://docs.decentraland.org/development-guide/materials/#using-textures

**Comment by jozanek** [comment]
@yangwao can you elaborate more about how this integration looks like? Are there any requirements from metaverse worlds? Do they use some standardised way? Is it also part of this ticket to answer that? What was proposed by @hiimbobdcl with ipfs hash is still valid?
