### ISSUE TITLE
Write article about Rubick (SubSquid in KodaDot) as implementation differs.

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2605]
We discussed that would be nice to write another article about Rubick (SubSquid in KodaDot) as implementation differs.
https://github.com/kodadot/rubick/

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/1501#issuecomment-1073237371_

**Comment by yangwao** [comment]
its on medium waiting for proof read plus probably we could publish it to dev.to?

**Comment by vikiival** [comment]
yup :)
