### ISSUE TITLE
Unable to retrieve keypair 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2607]
Seems I can't dispatch tx :| 
But I guess it's related https://docs.kodadot.xyz/tutorials/how-to-fix-error-keypair.html#_1-are-you-using-a-ledger-hardware-wallet :|

https://kodadot.xyz/transfer/?target=G29NScLSew5zqwmJAPupvJWDCDkpxKUhDnMeVdD2BBcnHar&usdamount=500

![image](https://user-images.githubusercontent.com/5887929/159162236-0ff76829-d5b1-4aed-b055-1d5917e108a7.png)

![image](https://user-images.githubusercontent.com/5887929/159162092-84d31345-1469-4179-8255-aa283c686094.png)

no update here 
![image](https://user-images.githubusercontent.com/5887929/159162192-89594307-cd3e-4ea6-b889-448cea9520b1.png)

@cryptodamsky 🥺

**Comment by jkdizajn** [comment]
confirm error also when minting new NFT
@yangwao 

https://user-images.githubusercontent.com/81104034/159170191-c891835e-aca5-4b00-bf30-faa2667c24bc.mp4

**Comment by magrisya** [comment]
this is the same problem on my report  #2594

**Comment by kkukelka** [comment]
same here. just tried to create my first nft 😢

**Comment by yangwao** [comment]
@vikiival is investigating it already, somehow merging something broke it. 

I heard it's a special time to highlight, that we need better QA on the pipeline, writing tests &c, as we are adding way too much stuff without robust testing  😅 🫶

https://docs.kodadot.xyz/incentives/incentivized-qa.html#code-of-conduct

**Comment by magrisya** [comment]
> @vikiival is investigating it already, somehow merging something broke it.
> 
> I heard it's a special time to highlight, that we need better QA on the pipeline, writing tests &c, as we are adding way too much stuff without robust testing 😅 🫶
> 
> https://docs.kodadot.xyz/incentives/incentivized-qa.html#code-of-conduct

Sir @yangwao why u not label my report at #2594 It seems this is the same case :)
