### ISSUE TITLE
Add nudge text when first time user authorize wallet 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2615]
When first-time user authorize a wallet, add a nudge to authorize
do it for 
- polkadot
- talisman
- subwallet

**Comment by prachi00** [comment]
@yangwao ill do this

**Comment by prachi00** [comment]
@yangwao can you explain this a little bit more?

**Comment by yangwao** [comment]
@cryptodamsky can drop some suggestions on this where it fits by onboarding research best.

**Comment by roiLeo** [comment]
**DotMarketCap**

![Screenshot 2022-06-01 at 09-34-02 Polkadot Ecosystem Projects DotMarketCap](https://user-images.githubusercontent.com/9987732/171351961-86de444b-4f58-457a-8816-6ffdb4b12f47.png)
