### ISSUE TITLE
Make Renovate to prefer major version (v16)

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2617]
> btw, how about using a major version (`v16`) instead of a specific patch version (`v16.14.2`)?
> 
> * [https://github.com/kodadot/nft-gallery/blob/main/package.json#L46](https://github.com/kodadot/nft-gallery/blob/main/package.json?rgh-link-date=2022-03-21T08%3A21%3A49Z#L46)
> * [https://github.com/kodadot/nft-gallery/blob/main/Dockerfile#L2](https://github.com/kodadot/nft-gallery/blob/main/Dockerfile?rgh-link-date=2022-03-21T08%3A21%3A49Z#L2)
> * [https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/build.yml#L17](https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/build.yml?rgh-link-date=2022-03-21T08%3A21%3A49Z#L17)
> * [https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/reviewdog.yml#L17](https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/reviewdog.yml?rgh-link-date=2022-03-21T08%3A21%3A49Z#L17)

I guess so would be nice, yet renovate has updating it whenever new version or security version node is out to particular version, let's give it a shot if you can find in renovate docs to opt out from bumping nodejs version as it's send immortal PRs :)
Making this as extra issue

### Ref 
- https://github.com/kodadot/nft-gallery/issues/2340

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2611#issuecomment-1073693610_

**Comment by yangwao** [comment]
Accidentally merged https://github.com/kodadot/nft-gallery/pull/2681 without realizing consequences :D
now I had to bump 
- https://github.com/kodadot/nft-gallery/commit/bfc92a0b55866cb1b45d37a5d2c5310e361432d6 
- https://github.com/kodadot/nft-gallery/commit/5cc507b2b423fb9d240f622538e74ac15224252d
 to have checks passing 🫣

**Comment by preschian** [comment]
aw, rennovate updated the engines in package.json https://github.com/kodadot/nft-gallery/pull/2681 🤔

will check later, leave traces...
nodejs, prefer latest and LTS, no need to update engines in package.json
- https://github.com/renovatebot/renovate/discussions/13725
- https://github.com/renovatebot/renovate/discussions/14643

dependencies and devDependencies, minor and patch first
