### ISSUE TITLE
NFT name is in navbar when scrolled down

### ISSUE THREAD

**Issue by magrisya** [kodadot/nft-gallery#2618]
### What happened?

I don't know what happened if it's a new feature or a bug..
didn't you turn off right click on image.
if its a new feature now right click works again on current feature after update

### Please reproduce in steps

Click one of the nft on your homepage/profile and scroll your mouse down

### Expected Behavior

new feature or bug

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Screenshots

![Screenshot_4](https://user-images.githubusercontent.com/43703018/159240133-883eed12-d8c4-4181-b523-2d1c3bd97d1c.png)

### Payment link for reward

https://kodadot.xyz/transfer/?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by magrisya** [comment]
check my attachment mr @yangwao 

https://user-images.githubusercontent.com/43703018/159241166-00adfd86-0517-4edd-9fd2-0acded71bf1f.mp4

**Comment by yangwao** [comment]
I'm confused, what's wrong here? 

like right click works again?
re name in navbar #2548 it's feature :)

btw, for future bug reporting, would be nice if you can test on https://beta.kodadot.xyz as there is most recent features which might not been pushed to production :)

**Comment by magrisya** [comment]
Dope sorry
