### ISSUE TITLE
Passion Emotes component

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2620]
The next step would be to show on click in that modal which addresses has emoted.

### Ref
- #744 
- #1918 
- #2226 
- #2223 
- #2222 

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2610#issuecomment-1073849135_

**Comment by roiLeo** [comment]
could be related with #1918

**Comment by yangwao** [comment]
Seems my brain state is almost the same compared to past me. 
https://github.com/kodadot/nft-gallery/issues/1918#issuecomment-1025654647

interlinked!
