### ISSUE TITLE
Collection pagination

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#2626]
#### Steps to reproduce
- go to any collection (tested on `/rmrk/collection/800f8a914281765a7d-KITTY`)
- click on page 3
- click on any nft
- click on go back to previous page
- you're now on page 1 while you have page 3 in url

#### Expected Behavior
I should be on page 3 instead of page 1

#### video
https://user-images.githubusercontent.com/9987732/159443990-d0c98a5b-6e07-4226-9c6f-cbaa572da9f5.mov

**Comment by Jarsen136** [comment]
I will handle with it.

**Comment by yangwao** [comment]
Seems same bug as we had on the gallery?

**Comment by Jarsen136** [comment]
> Seems same bug as we had on the gallery?

I think yes. The same problem in different components.
