### ISSUE TITLE
Fix deepsource configuration

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2627]
https://deepsource.io/gh/kodadot/nft-gallery/run/6c9a4785-d45e-4867-9910-b90feafde43f/javascript/

![image](https://user-images.githubusercontent.com/5887929/159458015-ace2a172-27f2-43b6-bced-082ed74b939b.png)

**Comment by Jarsen136** [comment]
Hi, I will have a try!

**Comment by Jarsen136** [comment]
Hi, It seems that this problems has been solved in recent pr. @yangwao 

<img width="838" alt="image" src="https://user-images.githubusercontent.com/31397967/159473217-e8270757-aa88-4638-acec-e5bdf58f6add.png">


ref: https://deepsource.io/gh/kodadot/nft-gallery/run/382e2f7d-d376-4e87-964e-7da3856c1f1c/javascript

**Comment by yangwao** [comment]
interesting, okay

**Comment by roiLeo** [comment]
It looks like it's back with recent build/deploy

**Comment by preschian** [comment]
Hello @Jarsen136 🙋‍♂️

in yesterday seems like you are trying to fix this issue, but the PR closed https://github.com/kodadot/nft-gallery/pull/2648
are you still looking into that issue? If not, can I take a look at this issue?

**Comment by Jarsen136** [comment]
> Hello @Jarsen136 🙋‍♂️
> 
> in yesterday seems like you are trying to fix this issue, but the PR closed #2648 are you still looking into that issue? If not, can I take a look at this issue?

Not, feel free to check this issue~

**Comment by preschian** [comment]
@Jarsen136 thank you Jarsen 🙏🏻
