### ISSUE TITLE
Default nft view size is really big

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#2629]
When you click on any NFT the view size of the image is really big, talked about this yesterday with @XyloDrone, can we actually do something about it?

User has to scroll down 2-3x to get to the buying point --> annoying

ref:
![1](https://user-images.githubusercontent.com/92786519/159467729-05f83fdc-1851-4c90-8134-bfaa8dda957a.png)

**Comment by prachi00** [comment]
@cryptodamsky @yangwao @XyloDrone should we decrease the width? I can do this

**Comment by XyloDrone** [comment]
Might even be height, ideally the image would take up 30% of the screen with the possibility of a full screen view.

**Comment by yangwao** [comment]
I would default to something people with 13"-15" notebooks can see on the whole screen? 

https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide

also we have this one there 👀  
screenshot taken on iPad 
<img width="696" alt="image" src="https://user-images.githubusercontent.com/5887929/159475890-f90a0c87-fb0e-4158-8108-ebc650c2324c.png">

**Comment by vikiival** [comment]
Opened the #2634

**Comment by yangwao** [comment]
@cryptodamsky https://deploy-preview-2634--koda-nuxt.netlify.app/rmrk/gallery/11922317-2045da46c79661c147-CHAOSMASKS-CHAOS_MASK_53-0000000000000053 like this 👀

**Comment by cryptodamsky** [comment]
> @cryptodamsky https://deploy-preview-2634--koda-nuxt.netlify.app/rmrk/gallery/11922317-2045da46c79661c147-CHAOSMASKS-CHAOS_MASK_53-0000000000000053 like this 👀

Lovely! Feel like thats the ideal size

**Comment by vikiival** [comment]
> Lovely! Feel like thats the ideal size

Feel free to merge https://github.com/kodadot/nft-gallery/pull/2634

**Comment by XyloDrone** [comment]
Has this been deployed? :D As I am still seeing a massive image when looking on the actual site :)

**Comment by cryptodamsky** [comment]
> Has this been deployed? :D As I am still seeing a massive image when looking on the actual site :)

It's currently running in Beta i think

https://beta.kodadot.xyz/rmrk/gallery/12000638-5A37C441DF4354913E-SLEEPCUTIE-SPACE_CUTIE-0000000000000006

**Comment by XyloDrone** [comment]
Coolio :3
