### ISSUE TITLE
Nova & Math wallet connection

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#2630]
It's not possible to connect your wallet throught Kodadot with nova or math wallet mobile app.
It used to work when we requested access to the extension on Kodadot app loading but since we introduce multiple wallet extension, it won't ask for extension permission on mobile.

It look like the `window` is undefined in mobile app browser and we can't acces nor inject extension for now.

#### working preview (before wallet)
https://deploy-preview-2419--koda-nuxt.netlify.app/

#### non-working preview (recent)
https://deploy-preview-2628--koda-nuxt.netlify.app/

**Comment by yangwao** [comment]
> we requested access to the extension on the Kodadot app loading

I would ask a dumb question, it would be possible to request access right now by clicking to connect?

**Comment by roiLeo** [comment]
> I would ask a dumb question, it would be possible to request access right now by clicking to connect?

On #2628 I've managed to ask access on start if it's a mobile app, but i didn't succeed to get acces to user's accounts

**Comment by roiLeo** [comment]
closed in #2720 ?
