### ISSUE TITLE
Add "More from this collection" at the bottom of nft buying page

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#2631]
### Is your feature request related to a problem?

Based on some survey report we got from our recent survey, it would be good to raise buying traction by showing more nfts from actual viewed collection. Definitely  it would be way more interesting than the History function, which could go below this feature.

### Describe the solution you would like

Let's say i'm viewing a random nft which belongs to some collection. By adding this feature i'll have possibility to maybe look for better nft from the same collection, or have a peak on some price differences. 

Talked about this with @XyloDrone and it would definitely be nice addition to the buying process

**- Add something in similiar fashion like we have "Latest sales" on landing page.**

Simply if there would be no nfts in the collection, this wouldn't even show up.

### Describe alternatives you have considered

/

### Screeenshots

/

**Comment by yangwao** [comment]
👀
- #782 

adding to #2622

**Comment by yangwao** [comment]
Maybe we can close? 

![image](https://user-images.githubusercontent.com/5887929/163239122-5cc7ec00-9c05-475f-93ff-3b4e70118a3c.png)
