### ISSUE TITLE
Filter function seems to be broken in Explore > Collections

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#2632]
### What happened?

The filtering function seems to be acting weird, it sometimes shows the same nfts and it definitely doesn't load the last interacted collections, based on "latest sales" on landing page.

### Please reproduce in steps

Go to kodadot.xyz
Click on Explore>Collections>Filter by

### Expected Behavior

/

### What browsers are you seeing the problem on?

Mozilla/Chrome

### Are you logged in?

yes

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

https://user-images.githubusercontent.com/92786519/159474570-9c32dcfa-f4a3-416c-8560-7e27c3289339.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
Hi, I will fix it.

**Comment by vikiival** [comment]
👀

**Comment by Jarsen136** [comment]
It seems that there is something wrong with the request

<img width="787" alt="image" src="https://user-images.githubusercontent.com/31397967/159482071-ee9caca3-6982-4604-a826-0cd5df92f791.png">

Both 'PRICE_DESC' and 'PRICE_ASC' are not supported to return data.  Any ideas about it? @vikiival 
<img width="256" alt="image" src="https://user-images.githubusercontent.com/31397967/159482222-a887ad34-6eb7-4fd4-b61c-f17bf7b25851.png">

**Comment by vikiival** [comment]
Yup, don't use PRICE should be visible only in NFTs
