### ISSUE TITLE
Aarhus milestone

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2646]
Once kodadot/nft-gallery#2622 is finished, Aarhus is next.

- https://github.com/kodadot/nft-gallery/issues/1285
- https://github.com/kodadot/ideas/issues/7
- https://github.com/kodadot/nft-gallery/issues/1722
- https://github.com/kodadot/nft-gallery/issues/1348

**Comment by vikiival** [comment]
Last opened was migrated - https://github.com/kodadot/ideas/issues/7
