### ISSUE TITLE
Remove gyroscopic effect i.e. picture transformation on nft item detail

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2656]
Ook, remove gyro effect on mobile as well and optionally on the desktop to be turned on in settings

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2634#issuecomment-1077473927_

**Comment by prachi00** [comment]
@yangwao is this just for navbar gyro effect or overall?

**Comment by yangwao** [comment]
ah, I guess let's close it in favour https://github.com/kodadot/nft-gallery/pull/2698 

it was meant I guess it's that picture on NFT item detail was moving or using mobile gyroscope so it was changing dimension while being bit interactive 

we can remove that gyroscope effect until someone would like to keep it.
