### ISSUE TITLE
When we upgrade to webpack v5 I can live in Norway for free.

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2658]
@vikiival told me that when we upgrade to webpackV5 I can live in Norway for free.
jk, we can drop some packages like ...

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2653#issuecomment-1077491946_

**Comment by roiLeo** [comment]
remember that webpack can be replaced by #1418, it would speedup development server and improve performance

**Comment by vikiival** [comment]
> Love to have Vite && Vitest in the repo

**Comment by yangwao** [comment]
Closing in favour 

- #3908
