### ISSUE TITLE
Placement should be in front of you to the ground, 1m before

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2666]
> placement should be in front of you to the ground, 1m before

_Originally posted by @vikiival in https://github.com/kodadot/nft-gallery/issues/1321#issuecomment-1067065034_

**Comment by prachi00** [comment]
@yangwao can you expand more? I'll take this

**Comment by vikiival** [comment]
> can you expand more?

When you open a 3D moded using `Show in AR` the object should be placed 1 meter in front of you.

The current mode is that object is rendered somewhere around you

**Comment by prachi00** [comment]
@vikiival where is `Show in AR`?

**Comment by vikiival** [comment]
[When you open this on mobile](https://kodadot.xyz/rmrk/detail/10249854-FC77C33AB229A2056A-BTFLSUZANN-BEAUTIFUL_SUZANNE_13-0000000000000013) you will see the button ;D

**Comment by Jarsen136** [comment]
Hello! @prachi00 
Do you still work on this issue? If not, I would like to take it~

**Comment by prachi00** [comment]
@Jarsen136 sure you can take this one

**Comment by Jarsen136** [comment]
> @Jarsen136 sure you can take this one
Thanks a lot! @prachi00

**Comment by vikiival** [comment]
from @Jarsen136 

Seem that the distance to AR model could not be set.

ref: https://github.com/google/model-viewer/discussions/1938#discussioncomment-300556
official docs: https://modelviewer.dev/examples/augmentedreality/#ar
