### ISSUE TITLE
Seems recent sales and listings are broken on landing?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2668]
Seems since we deployed #2660 something went go black and there are no new updates from mints and sales.
The last one is 6 hours ago. But when you click on https://kodadot.xyz/rmrk/gallery?search=&sort=UPDATED_AT_DESC&page=1 shows recent listings 
Maybe #2637 ?

<img width="331" alt="image" src="https://user-images.githubusercontent.com/5887929/159965991-f9599820-c49e-494c-a01a-11aef6699a8e.png">

**Comment by Jarsen136** [comment]
Seem that there is something wrong in server side, as I revert the #2637, the problems still there. 👀

**Comment by yangwao** [comment]
The investigation, our recent rubick@005 is broke.

mmm
#1492

**Comment by vikiival** [comment]
https://github.com/kodadot/rubick/issues/44

**Comment by preschian** [comment]
curious, how to detect/capture this error? because I only get `200` from the network tab

<img width="2032" alt="Screen Shot 2022-03-25 at 7 38 20 PM" src="https://user-images.githubusercontent.com/734428/160122182-4ea4d301-4db8-4c97-86e0-46a576348bce.png">

**Comment by vikiival** [comment]
Deployed fast fix so we won't have old data on the landing

The original issue is still in the process

(https://github.com/kodadot/rubick/issues/44)
