### ISSUE TITLE
handle offline-first v2

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2672]
I guess it's fair.
Now would be amazing to make handle offline-first v2 to add things 
- like notice user visually that's it's offline, but keep showing content - i.e. now when I'm offline and have cached pictures, why I can't see them if I don't interact with them?
- disable buttons probably 
- write service worker to cache stuff, i.e. add the ability for user return to pages were previously been?
- learn from https://offlinefirst.org/
- https://hasura.io/blog/design-guide-to-offline-first-apps/
- https://techbeacon.com/app-dev-testing/offline-first-web-mobile-apps-top-frameworks-components

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2645#issuecomment-1078925031_

**Comment by Jarsen136** [comment]
Hi, I will have a try!

**Comment by exezbcz** [comment]
is this worth doing? cc @vikiival

**Comment by vikiival** [comment]
I am not sure how Progressive web app is currently handled - maybe @preschian can explain

, but probably not

**Comment by preschian** [comment]
> I am not sure how Progressive web app is currently handled

currently we are removing the some of service workers parts: https://github.com/kodadot/nft-gallery/pull/10443



> is this worth doing?

I think this one keep it as p4 or p5, less prioritise
