### ISSUE TITLE
pnpm builds taking on first time quite long 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2696]
I guess switching to pnpm from yarn it seems from cached they do amazing work but on the first time they take quite a long time to build

Now
> Build time: 6m 3s. Total deploy time: 6m 7s
https://app.netlify.com/sites/koda-nuxt/deploys/62403dedcfa58900095b76d1

Before
> Build time: 4m 5s. Total deploy time: 4m 9s
https://app.netlify.com/sites/koda-nuxt/deploys/6239dbdd27c5220009cec772

this is quite scary lol 
> 3:34:06 PM: Finished processing build request in 10m39.002735083s

### Ref
- #2692

**Comment by preschian** [comment]
IMO, build times is not really relevant with pnpm, especially we recently migrated to nuxt-bridge can be related with that also

pnpm installation benchmark https://pnpm.io/benchmarks

**Comment by yangwao** [comment]
but I guess once we are not adding a new package, we should somehow leverage cache?

**Comment by preschian** [comment]
can be related with that installation global also, because netlify does not support pnpm built-in. meanwhile in vercel https://vercel.com/changelog/projects-using-pnpm-can-now-be-deployed-with-zero-configuration

**Comment by yangwao** [comment]
> can be related with that installation global also, because netlify does not support pnpm built-in. meanwhile in vercel [vercel.com/changelog/projects-using-pnpm-can-now-be-deployed-with-zero-configuration](https://vercel.com/changelog/projects-using-pnpm-can-now-be-deployed-with-zero-configuration)

So we can expecting netlify having it soon?

**Comment by preschian** [comment]
hopefully, requested from 2020 🙈
<img width="926" alt="Screen Shot 2022-03-27 at 6 41 45 PM" src="https://user-images.githubusercontent.com/734428/160279807-7acfdb12-bf8b-4b9d-93c4-6ce1cd5699cd.png">

**Comment by zhyd1997** [comment]
It's my first time to use Netlify and I deployed my forked [nft-gallery](https://github.com/kodadot/nft-gallery/) repo on Netlify but I got a different build time 👀 :
> Build time: 5m 23s. Total deploy time: 5m 27s

https://app.netlify.com/sites/inquisitive-chebakia-1caea0/deploys/62405d7c18bfda372acfe634

**Build command (default)**: 
```bash
npm i -g pnpm && npm run generate:pnpm
```

**Comment by zhyd1997** [comment]
After comparing the deploy logs above in the issue description, the most redundant time spend on

| stage  | yarn | pnpm | diff time |
| ------------- | ------------- | ------------- | ------------- |
| before `Starting build script`  | **1 m 6 s** (10:23:27 PM - 10:24:33 PM)  | **1 m 35 s** (6:35:28 PM - 6:37:03 PM) | + 29 s |
| install deps  | **0** (totally cached) | **12s** (6:37:32 PM - 6:37:44 PM) | + 12 s |
| during `generate` command |  **2 m 22 s** (10:25:04 PM - 10:27:26 PM) | **3 m 27 s** (6:37:51 PM - 6:41:18 PM) | + 65 s |

and seems that `pnpm` can not speed `build` time, but only can save`install` time.

so, maybe this is not a bug.

**Comment by preschian** [comment]
interesting, on my end:

stage | pnpm | yarn
--- | --- | ---
source | https://github.com/preschian/nft-gallery/pull/11 | https://github.com/preschian/nft-gallery/pull/12
netlify 1st time | Build time: **5m 4s**. <br />Total deploy time: **5m 8s** | Build time: **4m 39s**. <br />Total deploy time: 4m 43s
netlify (cached) | Build time: **1m 14s**. <br />Total deploy time: **1m 17s** | Build time: **1m 20s**. <br />Total deploy time: **1m 23s**
github actions (install deps) | **20s** | **55s**
github actions (run generate) | **2m 2s** | **2m 43s**

I'm not quite sure about the build times, seems like the range is fluctuating. it seems can catch up with each other. especially when referring to this table https://v3.nuxtjs.org/getting-started/introduction#comparison stability status on Nuxt Bridge is "semi-stable". It might be related to that

but for the installation speed results, it seems stable

**Comment by yangwao** [comment]
Once there is no change to code, `generate` is superior fast and the same for `pnpm` seems take ~ 21s

https://app.netlify.com/sites/koda-nuxt/deploys/624add20a8ca7a0009fa4ae3

I guess with #2692 we could speed up stuff and cut times, hence nuxt-bridge did not introduce a significant boost to build times, just a compatibility layer.

Even that, I'm super happy that Github actions are superior fast and shorten cycles to test the code if builds well.

**Comment by yangwao** [comment]
Seems we are at 5m now, not bad, not even perfect

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/5887929/222240818-863c0297-4f54-4f5d-a68c-ceb5cdde1b30.png">
