### ISSUE TITLE
Dashboard to show the health status of the indexers

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2699]
### Is your feature request related to a problem?

It would be nice to have a route like `/health` which pings:

#### 1. indexers
- magick

- rubick

- unique

- snek

    
#### 2. services/workers

If they are working as they should 

### Describe the solution you would like

Some dashboard like UI (mobile friendly ofc)

### Blocking

I need to implement some of this checking features to the workers and find out these metrics for subsquid

**Comment by yangwao** [comment]
How it's different from 
- #1492

**Comment by vikiival** [comment]
Nice was looking for that
Closing in favour of #1492
