### ISSUE TITLE
Collection history tab doesn't work 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2700]
I recall we had recent SubSquid fixes, but this seems different as it doesn't work and we don't see there any errors? 

https://beta.kodadot.xyz/rmrk/collection/dac5c7f54029d0e73c-HXAI8?tab=history

![image](https://user-images.githubusercontent.com/5887929/160389636-e47cf20b-a1e0-4afa-821c-a2dec59d000e.png)

@vikiival is aware of that one if you want to help elaborate your help is more than welcome!

Might be related? 
https://github.com/kodadot/nft-gallery/pull/2670 but when I've been checking this one seems to work for me well.

**Comment by prachi00** [comment]
@yangwao I'll check this

**Comment by vikiival** [comment]
already fixed

**Comment by prachi00** [comment]
@vikiival is it? I still see it happening and gave figured out the fix though

**Comment by prachi00** [comment]
> @vikiival is it? I still see it happening and gave figured out the fix though

its because of a default boolean check added recently, should be a minor fix

**Comment by vikiival** [comment]
> its because of a default boolean check added recently

check #2701
