### ISSUE TITLE
Add tab named Holders to collections to show owned assets by particular holders

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2707]
We would like to see in the collection that the owner has which NFTs.

It would work we can list owners as a table and on click, it would show custom detailed rows
- headers would be 
  - owner / nft name
  - Bought - price bought for (BUY to user)
  - Sale - price selling for (LIST), 
  - Date (relative with a tooltip with exact one)
- link NFT name to particular nft item detail 
- link date to transaction same as in history table 

Use https://buefy.org/documentation/table/#custom-detailed-rows

Might need to write a resolver for this? 

### Ref
- #2222 
- #(collection by holders) something in passion feed iirc

**Comment by Jarsen136** [comment]
I will do this.

**Comment by Jarsen136** [comment]
@yangwao  There are some details that need to be made clear：
1. I wonder which date should be shown.  purchase date 、 list date 、 send date and mint date.  Or the last update date?
2. Which transaction should be linked ?  It is similar to the previous question.

**Comment by Jarsen136** [comment]
Hi @yangwao , I need your opinion so that I can continue 👀

**Comment by yangwao** [comment]
> @yangwao There are some details that need to be made clear：
> 
> 1. I wonder which date should be shown.  purchase date 、 list date 、 send date and mint date.  Or the last update date?

The last activity makes sense, plus you can link on each amount list and bought dates on hover as well, hence we have that information.

> 2. Which transaction should be linked ?  It is similar to the previous question.
- for Bought - last BUY transaction with owner in query
- for Sale - last LIST from owner
> 3. If nft is consumed, does it still need to be displayed?
- probably no, want to show potentially valuable assets only. Once consumed, NFT is burned literally.

Oh good questions, I haven't realized.

**Comment by yangwao** [comment]
> Cool! I will try to implement it.
> 
> But I still have a little confused about the 1st point. why we show all bought and list price on hover the date. An nft may have several pages of records, which should be viewed in the gallery page and history page. it's too heavy.

oh maybe you misread, *last* event for LIST and BUY where is the owner and date column with last activity event

> 
> > plus you can link on each amount list and bought dates on hover as well, hence we have that information.
> 
> Maybe I can make a version first to see the effect.

Yes, looking forward for PR

**Comment by Jarsen136** [comment]
Oh, I see. It does make sense!
