### ISSUE TITLE
Bug on 3D assets

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#2710]
### What happened?

A bug happened! Maybe it could be cache related

### Please reproduce in steps

Tested on `/rmrk/gallery/11105476-7cf9daa38281a57331-BSS-LB_SPACESHIP_363-0000000000000363`

### Expected Behavior

I've expected to see good data infos (in navbar too)

### What browsers are you seeing the problem on?

Firefox

#### beta.kodadot.xyz
![Screenshot 2022-03-30 at 08-55-05 lb Spaceship #363](https://user-images.githubusercontent.com/9987732/160770590-65cd5398-ca6e-49b6-9561-564293e26fd0.png)

#### kodadot.xyz
![Screenshot 2022-03-30 at 08-55-22 Beautiful Suzanne #13](https://user-images.githubusercontent.com/9987732/160770476-351fc69d-61cb-4773-beb6-c67e1ab90d07.png)

#### preview 2709
![Screenshot 2022-03-30 at 08-55-53 KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/160770278-5987af50-8d44-4a75-97a3-f8a49b190455.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
Hi,I will check it.
