### ISSUE TITLE
Some setting in the preferences do not make any change on UI

### ISSUE THREAD

**Issue by prachi00** [kodadot/nft-gallery#2712]
### What happened?

All the options in search preferences not working for me

### Please reproduce in steps

https://user-images.githubusercontent.com/39299315/160831069-3d111055-29e0-4551-b232-61c38742530f.mov

### Expected Behavior

 Even though `yolo` is on, it isnt showing up in buttons, happening for all the other options as well

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### Screenshots

<img width="752" alt="Screenshot 2022-03-30 at 5 28 57 PM" src="https://user-images.githubusercontent.com/39299315/160830377-04199a0f-5bbb-4f12-a99f-56888a0bb99b.png">
<img width="450" alt="Screenshot 2022-03-30 at 5 29 01 PM" src="https://user-images.githubusercontent.com/39299315/160830384-986fb1b2-a5ca-40d9-84af-725e2482efbd.png">
<img width="406" alt="Screenshot 2022-03-30 at 5 29 08 PM" src="https://user-images.githubusercontent.com/39299315/160830388-a8370cec-3af3-4547-b1bf-ecf6ff5291cb.png">

### Payment link for reward

https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prachi00** [comment]
@vikiival its not just yolo, its happening for all the other preference option as well

**Comment by vikiival** [comment]
Hey,
thanks for opening the issue. 
I went through some settings and some does not work:

- Fold history ...
- Fold description ..
-

**Comment by vikiival** [comment]
The 'YOLO' is applicable for the 'BUY NOW' (in filter)

**Comment by prachi00** [comment]
yeah I am currently checking why its happening

**Comment by prachi00** [comment]
@vikiival unable to figure out the reason, not even sure when this got introduced, any idea?

**Comment by prachi00** [comment]
> @vikiival unable to figure out the reason, not even sure when this got introduced, any idea?

Also I have noticed it works fine if you are on the same tab, issue occurs only with 2 different tabs, is this expected?

**Comment by vikiival** [comment]
> this got introduced, any idea?

Hey, not sure what `this` means in the context. Could you clarify please 🥺

**Comment by prachi00** [comment]
> > this got introduced, any idea?
> 
> Hey, not sure what `this` means in the context. Could you clarify please? 🥺

I meant how long ago it started happening
