### ISSUE TITLE
GraphQL tutorial

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2715]
Idea is to create a video tutorial to demonstate how to write queries for both SubSquid and SubQuery :)

**Comment by preschian** [comment]
Woah, this is great. cant wait for this one

some questions:
- what is the difference between subsquid and subquery
- why do we use both of them?

**Comment by vikiival** [comment]
> what is the difference between subsquid and subquery

I will cover that in the tutorial :)

> why do we use both of them?

In the past, we were relying only on the SubQuery (therefore 80% of the queries are for SQ) but once the indexer was stuck, users were unable to use KodaDot. Therefore we implemented an alternative SubSquid (SSQ) to avoid #762

**Comment by vikiival** [comment]
[Slides for the tutorial](https://github.com/vikiival/slides/tree/master/graphql-intro)

Getting into GraphQL video

[![Getting into GraphQL](http://img.youtube.com/vi/7eQu_KS1TJk/0.jpg)](http://www.youtube.com/watch?v=7eQu_KS1TJk "Getting into GraphQL")

**Comment by yangwao** [comment]
Is this somewhere in https://docs.kodadot.xyz ? 
Maybe @thea-exe can add this if not :)

**Comment by thea-exe** [comment]
Will do!

**Comment by yangwao** [comment]
> Will do!

@thea-exe  is linked somewhere in docs or PR? 
IF so, let's close this one :)

**Comment by thea-exe** [comment]
Yep in PR :) let's close!

**Comment by vikiival** [comment]
ref kodadot/docs#57
