### ISSUE TITLE
Unification explorer + collections into one 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2719]
Based on the discussion from #2511 

For the sake and easier maintenance would be superior nice to have merged explorer and collections, so we don't need to maintain these two components as extra. It would simplify architecture in @petersopko words, which I can agree, keep it simple stupid.

The flow would look like when a user searches for "something" it can drive it to tabs, where the first highlighted tab could be collectables, other items and once we will have #2112  we can add that one as well    

>  we could merge the Gallery + Collections under one tab in the navbar (Explore) and have it separated by tabs within the search section

![image](https://user-images.githubusercontent.com/5887929/161061693-abece2ee-a078-45e6-8ee1-addf7bdea173.png)

> As still, we haven't thought what merger of explore+collections feed would look like I'm open to new ideas and sense this is the time

**Comment by prachi00** [comment]
<img width="219" alt="Screenshot 2022-04-04 at 4 18 36 PM" src="https://user-images.githubusercontent.com/39299315/161528751-14e5466d-cfed-4ef9-8a1a-ed12609ba685.png">

will we also merge these two and have it under only **Explore**?

**Comment by yangwao** [comment]
> <img alt="Screenshot 2022-04-04 at 4 18 36 PM" width="219" src="https://user-images.githubusercontent.com/39299315/161528751-14e5466d-cfed-4ef9-8a1a-ed12609ba685.png">
> 
> will we also merge these two and have it under only **Explore**?

yes you are right
