### ISSUE TITLE
profile Tabs not working properly sometimes

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#2723]
### What happened?

when i login to my account then visit my profile i get this:
.
![01](https://user-images.githubusercontent.com/71472224/161096969-9c56ddee-451a-4e67-afa9-8e1b3c047780.jpg)
 
 its only showing the collected tab 
 
 when i refresh the page sometime i get this: 
.
![02](https://user-images.githubusercontent.com/71472224/161097170-98154ef9-7f92-4960-8ae1-4a346a644c20.jpg)

it still says collected but its actually showing the Created nfts 
.
as a way around it i go to explore page then i go back to my profile using the login tab (top right corner) 
and voila i see everything as it should look 
Note: this only happens when i don't visit kodadot for more than 24hours, and after it starts working fine, it stays like that for the rest of the day ^^ 

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

/

### Relevant log output

```shell
/
```

### Payment link for reward

https://nft.kodadot.xyz/transfer?target=JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7&usdamount=10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
I will check it!

**Comment by yangwao** [comment]
> Note: this only happens when i don't visit kodadot for more than 24hours, and after it starts working fine, it stays like that for the rest of the day ^^

notice you are using prefix `nft.`, have you tried log in on https://beta.kodadot.xyz if there is happening the same?

I've opened your profile and works well https://kodadot.xyz/rmrk/u/JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7

![image](https://user-images.githubusercontent.com/5887929/161110918-3b13d607-c2d1-406a-b67b-d5ff466a5c3b.png)


I can't reproduce even on mine


https://kodadot.xyz/rmrk/u/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd

![image](https://user-images.githubusercontent.com/5887929/161110144-b10eb108-0335-43bc-b50e-91a3c0639590.png)

**Comment by onerawartist** [comment]
same thing happened of beta 

https://beta.kodadot.xyz/rmrk/u/JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7?tab=collected


![04](https://user-images.githubusercontent.com/71472224/161111630-df68cf01-7562-450d-acce-b7f9edcf87b9.jpg)

**Comment by yangwao** [comment]
I see your profile is somehow special? 

but when I removed `?tab=collected` and opened it one more time it is ok! 
Strange. 

![image](https://user-images.githubusercontent.com/5887929/161116651-d9419694-d080-4745-aacd-3bf15c4fae78.png)

**Comment by yangwao** [comment]
hey @onerawartist can you test on https://beta.kodadot.xyz like in a few minutes from now, 13:10 like at 13:20? and let me know if still happening!
