### ISSUE TITLE
Add best practices to Contributing

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2729]
To increase a code readability and reusability of the components, it would be super nice to create a code guide related to:
- naming
- folder structure
- reusability

**Comment by kkukelka** [comment]
I would like to set that one up :)

**Comment by vikiival** [comment]
Rise and shine 🌞

**Comment by vikiival** [comment]
https://v2.vuejs.org/v2/guide/class-and-style.html

**Comment by vikiival** [comment]
<img width="426" alt="Screenshot 2022-04-01 at 13 13 24" src="https://user-images.githubusercontent.com/22471030/161252755-faae0999-4459-4364-9166-e89a3abde56d.png">
