### ISSUE TITLE
Review bot

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2730]
### Is your feature request related to a problem?

Sometimes it happens that PRs are open without any requested reviewer

### Describe the solution you would like

I would like to see some sort of bot or github action that will asign randomly (pseudo-random, or based on some metric).

It just need to check that PR author != requested reviewer

### Describe alternatives you have considered

The alternative is that people who open PRs will ask for a review.

People that are good candidates for making reviews (in alphabetical order):
- @kkukelka 
- @roiLeo 
- @vikiival 

I also believe that @prachi00 is pretty familiar with the codebase already (as she is leading the payout chart)

### Screeenshots

![photo_2022-04-01 11 43 25](https://user-images.githubusercontent.com/22471030/161238975-825aee42-c9d3-46a8-8eac-0ebab0d87ac1.jpeg)

<img width="1676" alt="Screenshot 2022-04-01 at 11 38 08" src="https://user-images.githubusercontent.com/22471030/161238813-513a2060-e702-4f20-a1ff-d7e9dcc90cb7.png">

ht/ to @yangwao for the idea

**Comment by prachi00** [comment]
@vikiival 
https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#about-auto-assignment
wouldnt something like this work?

**Comment by yangwao** [comment]
> @vikiival [docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#about-auto-assignment](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#about-auto-assignment) wouldnt something like this work?

you are sweet! I remembered that I've seen it somewhere already as native but could not find it lol 🫣😅 

Thank you will look on it!

**Comment by yangwao** [comment]
Let's go with round robin and then let's see! 

> The round robin algorithm chooses reviewers based on who's received the least recent review request, focusing on alternating between all members of the team regardless of the number of outstanding reviews they currently have.

> The load balance algorithm chooses reviewers based on each member's total number of recent review requests and considers the number of outstanding reviews for each member. The load balance algorithm tries to ensure that each team member reviews an equal number of pull requests in any 30 day period.

**Comment by yangwao** [comment]
okay it's up https://github.com/orgs/kodadot/teams/code-review-guild/members just wait to accept invites :)

**Comment by vikiival** [comment]
> okay it's up

Perfect!

**Comment by yangwao** [comment]
maybe now as probably need add this team

**Comment by yangwao** [comment]
oh, that's.. when team of reviewers is requested and then it's load balanced.

**Comment by yangwao** [comment]
hmm https://github.blog/changelog/2021-09-29-new-code-review-assignment-settings-and-team-filtering-improvements/

**Comment by vikiival** [comment]
<img width="338" alt="Screenshot 2022-04-04 at 13 40 46" src="https://user-images.githubusercontent.com/22471030/161536470-922f3e1b-902b-4701-abea-d36a70cd885f.png">


<img width="879" alt="Screenshot 2022-04-04 at 13 40 58" src="https://user-images.githubusercontent.com/22471030/161536478-c4113dea-47f5-4fec-8af7-2cd5936e12e7.png">

So we need still something like gh action which adds kodadot guild as a reviewer on opened PR :)

**Comment by yangwao** [comment]
yeah technically speaking it does work...but requires trigger but on last link I posted should be working without it

**Comment by vikiival** [comment]
> should be working without it

Worst case we will convince it :)

**Comment by yangwao** [comment]
atlesat i know it was paid service by pullpanda https://pullpanda.com/assigner that what's under hood by GH

**Comment by yangwao** [comment]
learning https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by vikiival** [comment]
<img width="1652" alt="Screenshot 2022-04-04 at 13 58 49" src="https://user-images.githubusercontent.com/22471030/161539127-688cd685-f8e4-4ef8-9916-77364559bd88.png">

**Comment by yangwao** [comment]
oooh, maybe permissions were issues all time from start lol 
![image](https://user-images.githubusercontent.com/5887929/161539413-2426f8a7-4fb3-4722-82d2-ecfa02c3e7b3.png)

**Comment by yangwao** [comment]
![image](https://user-images.githubusercontent.com/5887929/161539455-1348602c-1d52-4b18-a860-dda5ff09e628.png)

**Comment by yangwao** [comment]
yas 
![image](https://user-images.githubusercontent.com/5887929/161539640-004e485a-3b7f-435d-97d0-81fb6c856493.png)

cherry on top 
![image](https://user-images.githubusercontent.com/5887929/161539666-3bd7c327-616c-408c-a300-cfa6334fa73e.png)

**Comment by vikiival** [comment]
🍒 🍒 🍒 🍒 🍒 🍒
