### ISSUE TITLE
Change payout address to reward me in transfer

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2731]
In transfer dialkog, kodadot.xyz/transfer/

- We rename "Copy Payout Address" to "Copy Reward Me link", 
- Show Copy Reward Me link without need adding amount

the payout might get lost in translation and to ease the process we should be showing it despite the need to enter an amount to make it easier for first-time devs.

Once this is done, #2717 can be updated accordingly

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2717#issuecomment-1085761331_

**Comment by prachi00** [comment]
@yangwao I'll do this
