### ISSUE TITLE
Show user Twitter on hover card 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2735]
Whenever it's available, show Twitter on a hovercard 

Like [eiffel] seems got identity and Twitter set 

![image](https://user-images.githubusercontent.com/5887929/161257345-9b1ab121-0ad2-4024-be09-6f4cb8ff7d32.png)

https://deploy-preview-2724--koda-nuxt.netlify.app/rmrk/u/H6fSwoEZ8n3i6tPLBmCewPyes7B5Q6sG5YQiGNxWPs86AFi?tab=collected
![image](https://user-images.githubusercontent.com/5887929/161257259-e71f9013-91e7-4402-b27a-e8819ad574ed.png)

**Comment by prachi00** [comment]
@yangwao on this!
