### ISSUE TITLE
Hunting the burned once

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2738]
### What happened?

Viki was like: let me try Darshana's PR on this fish

<img width="1680" alt="Screenshot 2022-04-01 at 16 25 47" src="https://user-images.githubusercontent.com/22471030/161283359-48dfcbc0-e2c9-451f-a2bc-b4babdef673f.png">

Fish is burned
<img width="1680" alt="Screenshot 2022-04-01 at 16 25 37" src="https://user-images.githubusercontent.com/22471030/161283447-5a6c88b0-91df-400e-aaf9-e6bb4e84181f.png">

Task is:
- Go through app
- check where we can find this edgecases - (burned should not be visible on any list page)
- fix the queries

### Please reproduce in steps

🔥 

### Expected Behavior

I've expected see only existing NFTs on the app

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

No

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

Paste from your clipboard or upload screenshots/video

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prachi00** [comment]
@vikiival I'll check this
