### ISSUE TITLE
Holdings by User 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2739]
Seems KodaDot NFT marketplace is getting popular and taking lead in the best analytics, we would like to help users better scope on users activity.

In a similar manner, we have right now merging #2707  #2724 would be superior bringing a similar view with expanding custom rows and adding another tab "Holdings".
It would show a table. 
- Headers would be the name of Collection, Amount, Bought, Sale, Last Activity 
- Link Collection name to collections view
- link items in the collection to items 
- last activity in relative time with on hover with precise time

Best to reuse components if it's possible! 

Retrospect realized, we already have a very similar issue but from creator's perspective
- #1285 

Holdings by the user should be for collectors to show off, however, might be somehow merged in future.

![image](https://user-images.githubusercontent.com/5887929/161285387-af863da6-e3d8-412a-9dc3-37fe97e74b42.png)

ht ShawnLin for the suggestion

**Comment by Jarsen136** [comment]
I will do this 😄

**Comment by vikiival** [comment]
Just need to clarify a few things

> Bought

I guess this is for price at which user obtained the NFT

> Sale

The current list price?

**Comment by Jarsen136** [comment]
> Just need to clarify a few things
> 
> > Bought
> 
> I guess this is for price at which user obtained the NFT
> 
> > Sale
> 
> The current list price?
> 
Yup, you are right.
ref: https://github.com/kodadot/nft-gallery/issues/2707#issue-1184798294
