### ISSUE TITLE
Implement sorting by date under address 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2741]
Implementing sorting by date under address could be interesting

sort them by last bought (date)?

https://user-images.githubusercontent.com/31397967/161295939-684a00a5-096a-480c-8de7-5308c6b9d643.png

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2724#issuecomment-1086136418_

**Comment by Jarsen136** [comment]
I will take it.
