### ISSUE TITLE
Mobile container 🫙 is broken on mobile again 😬 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2744]
Found container 🫙 is broken on mobile again 😬 and it's moving, but I guess we can postpone it to another following issue.

https://user-images.githubusercontent.com/5887929/161374871-2edd68c8-ee2e-4395-833a-a5359da66682.mp4

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/pull/2722#issuecomment-1086590712_

**Comment by prachi00** [comment]
I'll check this

**Comment by prachi00** [comment]
@yangwao is this still happening for you? not happening for me

**Comment by yangwao** [comment]
on item is already fixed meanwhile on beta
on landing, it's there, you can move horizontaly.

**Comment by yangwao** [comment]
Is it blank or works?


https://user-images.githubusercontent.com/5887929/161936472-2112e3da-b235-4514-b63a-50e2df2e62aa.mp4

**Comment by yangwao** [comment]
https://photos.app.goo.gl/Z2CzRG5T6RpKJ68D6 

Awkward gh app or my phone 📱 is broken

**Comment by roiLeo** [comment]
Blank for me
![image](https://user-images.githubusercontent.com/9987732/161936803-c6c6254d-a88f-4de2-aa15-3373e77f0f41.png)

**Comment by prachi00** [comment]
Blank for me too
