### ISSUE TITLE
Redesign collection advanced stats 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2746]
Hence we are the aspiring leading platform for analytics on RMRK, we are looking way to simplify ways to show collections stats and insights

Right now we added some which are important basic rules of thumb to detect if wash trading occurred if the collection has organic growth or velocity of adoption per collection for future collectors.

I'm opening the discussion to bit simplify without dropping numbers in this table to to be sensible incorporated into collection view.

One way I was thinking adding some fold or switch to see "advanced stats" 

![image](https://user-images.githubusercontent.com/5887929/161378704-d5db1c08-9ff0-4cab-831d-f4cb82eae592.png)

To better support any argument you have, best to post pictures+link from other platforms of how they are having it so we can better gauge something good from great to perfect! 

@XyloDrone might want to speak on this! :)

**Comment by prachi00** [comment]
@yangwao I'll see what we can dooo

**Comment by yangwao** [comment]
> @yangwao I'll see what we can dooo

yes, it's open for discussion to see for example how other platforms are showing it :)

**Comment by prachi00** [comment]
Yes Ill do some research and post the links here

**Comment by prachi00** [comment]
https://rarible.com/azuki/items

maybe something like this, clean with borders?

**Comment by prachi00** [comment]
https://opensea.io/collection/0xmons-xyz

they have a simple one too with simplified texts and borders

**Comment by JustLuuuu** [comment]
stats changed
