### ISSUE TITLE
Seems newest list from landing is gone 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2747]
```log
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
    at 41d068c.js:1:10873
    at Array.map (<anonymous>)
    at f.<anonymous> (41d068c.js:1:10838)
    at v (152af89.js:2:16194)
    at Generator._invoke (152af89.js:2:15982)
    at Generator.next (152af89.js:2:16623)
    at r (152af89.js:2:2747)
    at l (152af89.js:2:2950)
    at 152af89.js:2:3009
    at new Promise (<anonymous>)
```

![image](https://user-images.githubusercontent.com/5887929/161380022-1a9c91c2-2be8-460a-87ca-70d3a04fcbcf.png)

**Comment by Jarsen136** [comment]
I will check it

**Comment by preschian** [comment]
strange, seems fixed for now? Does something change from the server-side?

**Comment by Jarsen136** [comment]
It seems work well now. I think that maybe back-end interface just now is not stable.

**Comment by yangwao** [comment]
Some nft from that list wasn't properly handled I bet https://kodadot.xyz/rmrk/gallery?search=&sort=UPDATED_AT_DESC&page=1

naturally people are listing new nft so hard to see what was making issue :)

**Comment by Jarsen136** [comment]
Oh I see. I will try to reproduce it.

**Comment by yangwao** [comment]
Yeah hence it isn't occurring lowering priority, if we don't solve it happy to close it and snipping if it happen again lol 😅

**Comment by Jarsen136** [comment]
>  Yeah hence it isn't occurring lowering priority, if we don't solve it happy to close it and snipping if it happen again lol 😅

Don't worry. I have caught the error. Give me some time to fix it  🚶 

<img width="717" alt="image" src="https://user-images.githubusercontent.com/31397967/161382472-cd5d026e-15df-4712-9b79-293c7c0594c5.png">

**Comment by preschian** [comment]
woaah, the meta = null

**Comment by yangwao** [comment]
> >  Yeah hence it isn't occurring lowering priority, if we don't solve it happy to close it and snipping if it happen again lol 😅
> 
> Don't worry. I have caught the error. Give me some time to fix it  🚶 
> 
> <img width="717" alt="image" src="https://user-images.githubusercontent.com/31397967/161382472-cd5d026e-15df-4712-9b79-293c7c0594c5.png">
> 

Seems you're a new superior bug hunter 🤟🤘 engineering

**Comment by XyloDrone** [comment]
Hey sers, what's the deal with this issue? Seems fixed?
