### ISSUE TITLE
Rework tabs in user profile 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2753]
I guess with upcoming bug tackling in 
- #2725 
- #2751 

Seems some tabs can't be seen if the address they did not create NFTs and see for example collections.
This issue is for someone to help to refactor how profile tabs are appearing based on users' holding.

For example, at Shawns Lin I try opened https://deploy-preview-2751--koda-nuxt.netlify.app/rmrk/u/FXUxw9Xp98gTzrU2z63D2G92kcx1oznd6xYa8WdqRgTcEDo?tab=holdings and I got redirected to collected.

Test as many possible scenarios if things are working.
- Users with or without NFTs
- Users with or without collected NFTs

Bounty could be higher if refactor is well made!

**Comment by prachi00** [comment]
@yangwao I'll see what I can do

**Comment by yangwao** [comment]
> @yangwao I'll see what I can do

merged #2725 into #2751 so let me see if it is fixed , but even though I see someone could refactor it if not.

**Comment by prachi00** [comment]
@yangwao this is still an issue right?

**Comment by yangwao** [comment]
don't know, maybe test to find out :)

**Comment by prachi00** [comment]
https://deploy-preview-2751--koda-nuxt.netlify.app/rmrk/u/FXUxw9Xp98gTzrU2z63D2G92kcx1oznd6xYa8WdqRgTcEDo?tab=holdings  
 
 clicking on this redirect to holdings tab now

**Comment by prachi00** [comment]
this doesn't seem to be an issue anymore, closing this.
