### ISSUE TITLE
App does not list user's collections in create/admin

### ISSUE THREAD

**Issue by ltfschoen** [kodadot/nft-gallery#2756]
I helped someone I know who is an artist / graphic designer setup a Kusama account that has the following public key SS58 address on Kusama network D7xZ4QxGmtim6CP1XKxpFhbaCbuUJLg6TCPmTuFwk34a47S for a friend who is an artist / graphic designer and they added some KSM to pay transaction fees.

They then **successfully** created a collection at kodadot.xyz by using the menu "Create > Classic > Collection" approach.
The collection appears **successfully** when they go to menu "Explore > Collections", at this link https://kodadot.xyz/rmrk/collection/182147F2EAE72A963B-LART

But there are **issues**:
* If they go to kodadot.xyz/rmrk/admin (Admin panel) with that same account loaded using Polkadot.js Extension, it says "You have no collections".
* If they try to add an NFT to that collection with their account already loaded with the Polkadot.js extension, by going to kodadot.xyz/rmrk/create/ with menu "Create > Classic > NFT", and selecting the "NFT" tab, it shows their account is loaded, and then they click "Select a collection", but instead of showing their collection so they can select it, it just displays "--" in the dropdown menu.

Why isn't it associating the new collection that was created successfully with their account so they can create NFTs for that collection and view it in their profile? Why does it only show that their account is associated with that collection when you view it in the Kodadot explorer?

Note that they are using the latest Brave browser and the latest version of the Polkadot.js Extension, as both were installed on 3rd April 2022.

**Comment by vikiival** [comment]
Thanks for the issue!

Both cases are using the same query, so the problem would be somewhere there.

It is also possible that subquery is timing out these requests
