### ISSUE TITLE
collection minted without description

### ISSUE THREAD

**Issue by hueeeeee** [kodadot/nft-gallery#2757]
### What happened?

the collection description that I entered did not get posted, collection has no text under header image

### Please reproduce in steps

clicked on Create > Classic > Collection, uploaded image, entered Symbol, filled out Collection Description, created collection and verified tx in Talisman. 

### Expected Behavior

a short paragraph would be posted underneath the collection header image

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
hey, thank you for your report. 
It's hard to elaborate without a screenshot, address and best particular tx to go through stuff with you.
once you fill up at least two above, feel free re-open the issue.
