### ISSUE TITLE
Navbar breakpoints on 1037px

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2760]
Should be folding.. or we can think of hiding particular buttons based on importance?

Like hide button in a particular order
- Language
- Create
- Chain/protocol switch
- history
- stats
- profile

![image](https://user-images.githubusercontent.com/5887929/161530481-c865e013-dd61-4a35-b127-1bc26b6c7789.png)

**Comment by Jarsen136** [comment]
I will do this

**Comment by prachi00** [comment]
@yangwao will do this

**Comment by yangwao** [comment]
time to deploy #2448 @petersopko 🫣

![image](https://user-images.githubusercontent.com/5887929/161532898-887cf430-f58a-4a15-af9f-c840d3638288.png)

![image](https://user-images.githubusercontent.com/5887929/161532914-454c3583-c988-4afb-91ba-26104e7ec4bb.png)

**Comment by prachi00** [comment]
> time to deploy #2448 @petersopko 🫣
> 
> ![image](https://user-images.githubusercontent.com/5887929/161532898-887cf430-f58a-4a15-af9f-c840d3638288.png)
> 
> ![image](https://user-images.githubusercontent.com/5887929/161532914-454c3583-c988-4afb-91ba-26104e7ec4bb.png)

lol just noticed this, @Jarsen136 you can take this one
