### ISSUE TITLE
Write article about tech stack of KodaDot 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2766]
Hence to ease onboarding for new contributors, would be nice to have a lightweight article on how KodaDot actually works in the background. How KodaDot is actually middleware and leveraging existing web3 infrastructure to drive end-user experience and how can anyone use us as a template to make spinoffs with existing components.

I would suggest mentioning
- subquery (vikiival/magick, kodadot/unique)
- subsquid (kodadot/rubick, kodadot/snek)
- Cloudflare / workers
- bao (pictures)
- packages (subapi, minimark, vuex-options)
- Nuxt 
- Infra providers (Netlify, CF)
- Storage, [you can recycle from @kkukelka article about past, present and future of data storage](https://medium.com/kodadot/on-the-past-present-and-future-of-data-storage-at-kodadot-7634a0c32530?source=collection_home---------2-------------------------------)

Bonus stage (required for better awareness for new comers)
- Make a dedicated page on docs.kodadot.xyz for tech-stack for better reachability

Anything I'm missing? 📟 @vikiival 

h/t @thea-exe for amazing nudge and spotting blind spot

**Comment by vikiival** [comment]
Updated

**Comment by kkukelka** [comment]
I would be up for this! 🐹

**Comment by yangwao** [comment]
> Updated

I was searching for Vue3 in update 🫣 🥹

**Comment by yangwao** [comment]
https://medium.com/@kilian.kukelka/8a83880f8624 

👀 @vikiival

**Comment by vikiival** [comment]
added few comments

**Comment by kkukelka** [comment]
@vikiival @yangwao 
added Open positions and link to hiring page + all comments you mentioned
