### ISSUE TITLE
Rework+Refactor the navbar code

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2770]
We should rework and refactor the navbar code in a much more sensible way and what's should be merged and exclude on different widths.

Hidding least popular buttons from first, hence we don't have any UX research I can only bet.
- language
- chain/protocol selector
- create
- history
- stats
- profile

With search bar should be flexible and fill up the rest space next to the buttons.

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2769#issuecomment-1088467364_

**Comment by Jarsen136** [comment]
I will rework it later.
