### ISSUE TITLE
Mobile menu is overlapping

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#2772]
Searchbar width is breaking on iPhone 12
<img width="450" alt="Capture d’écran 2022-04-05 à 2 12 24 PM" src="https://user-images.githubusercontent.com/9987732/161751084-9727c9a1-4357-4131-ab98-6d3528b8021c.png">
We can delete the small gap in navbar item button (left margin) because it is not present on the right.
History button could be move outside burger menu.
I would also put the connect button full width as a call to action (change to primary color) to encourage users to log in.

As I tap to "create" something is wrong with focus  
![image](https://user-images.githubusercontent.com/9987732/161756329-dce5d878-707c-47e6-81ad-8af4f464c7be.png)

When using searchBar the navbar is overlapping and we can see the logo behind
<img width="450" alt="Capture d’écran 2022-04-05 à 2 10 32 PM" src="https://user-images.githubusercontent.com/9987732/161750912-e965d39c-c3c5-45fb-9095-0be2aa201326.png">

We could try to add a search Icon near burger menu that would display the search bar and hide logo on mobile
something like this: 
<img width="450" alt="Capture d’écran 2022-04-05 à 2 35 28 PM" src="https://user-images.githubusercontent.com/9987732/161754780-4993a1c0-a0ef-44cc-be5d-9fef165f3081.png">

**Comment by Jarsen136** [comment]
I will take it.

**Comment by Jarsen136** [comment]
Hi, I'm not sure where do you prefer to place History button? Or just remove it on mobile?

And how about the image below?
<img width="410" alt="image" src="https://user-images.githubusercontent.com/31397967/162101806-f96cd94f-87b9-4bf9-8050-d38fa2ad2778.png">


What's more, I don't know where to put the search box as you said : )

**Comment by Jarsen136** [comment]
> 
> When using searchBar the navbar is overlapping and we can see the logo behind <img alt="Capture d’écran 2022-04-05 à 2 10 32 PM" width="450" src="https://user-images.githubusercontent.com/9987732/161750912-e965d39c-c3c5-45fb-9095-0be2aa201326.png">
> 

How about just adding a black color background for the search-bar, so that it can cover the logo.  👁️

**Comment by roiLeo** [comment]
> Hi, I'm not sure where do you prefer to place History button? Or just remove it on mobile?

I was thinking something like this:
![image](https://user-images.githubusercontent.com/9987732/162160088-ef9e89b4-803b-4f25-916e-4b6482bf4619.png)

and when search icon is click (touched) it will toggle the navbar & hide logo
![Capture d’écran 2022-04-07 à 10 51 26 AM](https://user-images.githubusercontent.com/9987732/162160628-39d06401-2ff3-41ee-85ae-fc47aa9220c8.png)

this will need to rework the Navbar component for the mobile experience

> How about just adding a black color background for the search-bar, so that it can cover the logo. 👁️

we won't know where the input start/end since it will have the same bg and it's not good for UX
