### ISSUE TITLE
List live auctions on landing

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2776]
Once we will have Snek in 3 weeks, 
we can show live auctions running on their NFT marketplace.

We should show the most popular auctions with the most users, sorted by most users. 

![image](https://user-images.githubusercontent.com/5887929/161780936-d6c230a6-4257-48d8-ae5d-ec20246221e0.png)

**Comment by vikiival** [comment]
> live auctions running 

@jgreen what's the status of the auction pallet? :)

**Comment by XyloDrone** [comment]
Shall we have auctions on landing bellow featured collections? Or users can switch between tabs which show featured collections/auctions?

**Comment by green-jay** [comment]
@vikiival Auction pallet is done and well tested. we need to add benchmarks and then we can merge to `master`. if somebody is keen to build already before that happens, it is available on the `feat/auctions` branch of the [Basilisk repo](https://github.com/galacticcouncil/Basilisk-node/tree/feat/auctions)

**Comment by vikiival** [comment]
> Auction pallet is done and well tested.

@green-jay can we get it for kodadot-basilisk node? 🥺

**Comment by green-jay** [comment]
> > Auction pallet is done and well tested.
> 
> @green-jay can we get it for kodadot-basilisk node? 🥺

There is no such node. If you mean the kodadot testnet deployment, we have to wait until any feature is merged to basilisk `master`. The other option is, as mentioned, run the node locally via polkadot-launch and then test it.

**Comment by vgantchev** [comment]
Reference PR for English NFT auctions: https://github.com/galacticcouncil/Basilisk-node/pull/592

**Comment by roiLeo** [comment]
- BSX nft auctions been on hold since January
- Asset Hub auction is not yet scheduled

**Comment by roiLeo** [comment]
Closed as auctions abandoned
