### ISSUE TITLE
Weird floor price when sorted 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2783]
Check on 19. Babies Kusama shows **floor price 98**

![image](https://user-images.githubusercontent.com/5887929/161949895-7a06c4f3-c4be-4796-aa4d-85baf1350eef.png)

when I click on collections shows 0.0490 KSM

![image](https://user-images.githubusercontent.com/5887929/161950017-67485db9-77fc-4b6d-ae01-be01335f0d31.png)

https://beta.kodadot.xyz/rmrk/collection/7e982817a2d2575031-MAGK1

**Comment by kkukelka** [comment]
on it

**Comment by vikiival** [comment]
https://github.com/kodadot/nft-gallery/pull/2786#issuecomment-1093836026

Looks like there is a data glitch on the rubick

I track it in here https://github.com/kodadot/rubick/issues/50

**Comment by yangwao** [comment]
How is this going?
