### ISSUE TITLE
Add hover card to holdings by user

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2785]
A hovercard could be added as well as now it doesn't work :|

Once you hover on the username in the user's holdings, it should show the hover user profile card 

Reserved for @Jarsen136 👀

![image](https://user-images.githubusercontent.com/5887929/161990171-f360f95e-78e0-4ceb-8f50-03fe172eef23.png)

![image](https://user-images.githubusercontent.com/5887929/161948026-eff95015-9cec-4816-8d69-92099f71e0fc.png)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2751#issuecomment-1090075164_

**Comment by Jarsen136** [comment]
take this
pls tell me more about what kind of card you would like to add 👀

**Comment by yangwao** [comment]
this one :)

https://user-images.githubusercontent.com/5887929/161991695-a3faf804-c8c3-477d-bfbb-82053ab36071.mov
