### ISSUE TITLE
Top performing collection 

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#2790]
I would like to see a new component that will show the top performing collection (weekly, monthly, yearly) based on sales (or volume), something like magic eden tweet
![image](https://user-images.githubusercontent.com/9987732/162146728-dd3aa852-afe5-41f4-9085-ebfee8ee4a8e.png)

### Specs
- reusable component
- use chartjs [Bar Chart](https://www.chartjs.org/docs/latest/charts/bar.html)
- add collection image on top of chart ([this](https://www.youtube.com/watch?v=sfR2tLYaxxQ) could help)
- link bar to collection

### Ref
- kodadot/ideas#24 
- kodadot/nft-gallery#2638 
- kodadot/nft-gallery#2775

**Comment by yangwao** [comment]
<img src="https://media2.giphy.com/media/xsF1FSDbjguis/giphy.gif"/>

I've just came from future on my DeLorean 
and I've just added three references :P 


> 1. Is there already a an endpoint for the required data?

I saw answers in 
- #2359  

> 2. Where should the component be implemented?

- #2775

**Comment by ghifari444222** [comment]
will try to make it too ;)

**Comment by roiLeo** [comment]
>     1. Is there already a an endpoint for the required data?

IMO, we'll need this one https://github.com/kodadot/rubick/issues/26 to make it easier

>     2. Where should the component be implemented?

Could be on landing, or in a new stats page where we would put multiple charts (I like pie charts)
