### ISSUE TITLE
Add Flippers to Collection

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2791]
A useful metric would be to see people entered into the collection and for much they actually sold. It would work as a collection hyper-local leaderboard/rank.

Hence in current holders, we can't show people who sold as it would be a bit of noise, adding the next tab Flippers would work. 

Add there same table where 
- headers will be following User, Amount, Bought, Sold, Last Activity
- on unfolding you can see each NFT there which you can inspect 

### To do
- Forking Holders in collection
- Adjusting table instead of Sale (LIST event) there will be Sold (BUY from that user)
- Probably we would need to write Rubick resolver for this so it's fast?

![image](https://user-images.githubusercontent.com/5887929/162198765-d1759ec7-a439-4fca-aef5-ef1cba922fe6.png)

ht [@thefvk](https://twitter.com/TheFVK)

**Comment by Jarsen136** [comment]
Hi, I will have a try.
