### ISSUE TITLE
PermaLogin for recurring users even after updates

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2794]
For recurring users, keep them logged in, even updates happen, like when we push new build to `main`

Right now, when we push new stuff, users are getting logged out, at least at my Chrome house.

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/837#issuecomment-1091806537_

**Comment by roiLeo** [comment]
On firefox OSX I feel like I'm still logged in even after updates (tested on beta & some preview branch)
