### ISSUE TITLE
Renovate has stopped bumping dependencies?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2798]
I recall every 2-3 days we had a bump from renovating to bump new deps or package updates to running the most recent code.
The last merge is 13 days ago from renovate.

Since this commit https://github.com/kodadot/nft-gallery/commit/e01c64b268890ce379758a9ab3a2d91b9fadd712 which **was 12 days ago,** we closed open Node.js upgrade but nothing seen so far. 

Maybe @preschian can elaborate 🤔

![image](https://user-images.githubusercontent.com/5887929/162399708-2432fc2f-e11d-4c68-a8a6-43b5e5a4aaa9.png)

**Comment by kkukelka** [comment]
i believe adding back the packages like in #2802 should suffice. @yangwao  any way to test it in advance?

**Comment by yangwao** [comment]
> 

forking repo installing rennovate but let me try merge into `main`

**Comment by yangwao** [comment]
removed schedule d485932 so chances of praying are higher
usually it show's up in 2 minutes. hmm

**Comment by kkukelka** [comment]
> maybe there is no new package to bump after 12 days? 🫣

seems unlikely, i feel like i have overlooked some property

**Comment by kkukelka** [comment]
just reset to pre-prachi commit config in my fork https://github.com/kkukelka/nft-gallery/commit/1df3d31801aaf2f6c10f9143a170fe858b66be51 but also no PRs from renovate yet

**Comment by yangwao** [comment]
<img src="https://media3.giphy.com/media/7SF5scGB2AFrgsXP63/giphy.gif"/>

Maybe renovate bot feels offended :|

**Comment by preschian** [comment]
@yangwao let me check again in my forked repo

this patch version should be triggered 🤔
already add `pin` https://docs.renovatebot.com/dependency-pinning/, maybe some missconfiguration
<img width="663" alt="Screen Shot 2022-04-09 at 2 12 04 PM" src="https://user-images.githubusercontent.com/734428/162561166-4a2d6ace-b56b-49dc-b853-1636487ef2b9.png">
