### ISSUE TITLE
Search bar is broken (again?)

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#2800]
#### Step to reproduce
- go to `/rmrk/faq/` or any page that doesn't show nfts
- type in searchbar
- press enter or click data
- `?search=` is append on url

#### Expected Behavior 
- redirect user to search result

**Comment by Jarsen136** [comment]
i will check it

**Comment by yangwao** [comment]
Yes, it happens only in your search term and not select an item or collection.
