### ISSUE TITLE
Match top-border style where we miss it

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2806]
I noticed a few inconsistencies, so tried to name them down. 
Would be nice if we can have it merged with #2791 so we can push to production and make probably a release.

In the actions component, make borders top-border only and 1px, including input.
Thinking for Buy we could also try to have just top-border.

![image](https://user-images.githubusercontent.com/5887929/162527131-fc7c6981-b34c-461b-8773-6fb167292e57.png)

Search bar on input make top-border 1px, now it seems is 2px 
![image](https://user-images.githubusercontent.com/5887929/162527196-784aceee-5e2a-49a8-b667-ee785b716993.png)

In the profile dropdown, the logout button needs top-border 1px love

![image](https://user-images.githubusercontent.com/5887929/162527490-79211032-d25a-47d2-a99f-a74aa36fcb22.png)

On the item detail, the control buttons remove top-border

![image](https://user-images.githubusercontent.com/5887929/162527776-c9e315e0-d209-407f-8d89-2e267d85c852.png)

on left and right arrow - top-border 1px 
![image](https://user-images.githubusercontent.com/5887929/162528323-857e2184-05c5-44af-926b-614071470349.png)
![image](https://user-images.githubusercontent.com/5887929/162528329-314ba5b2-fefa-4643-9ac6-769bcb3ebd46.png)

Let's make Action, Chart, History top-border 1px as well 

![image](https://user-images.githubusercontent.com/5887929/162528701-fb5d260f-18bb-4e7f-82ed-f1ae38ce6960.png)

![image](https://user-images.githubusercontent.com/5887929/162528768-34433f7b-e3fd-4aeb-a225-d07d9588854b.png)

Emoji button as well 1px 

![image](https://user-images.githubusercontent.com/5887929/162528812-2def8a57-4db2-4aee-8a90-4764953898d8.png)

**Comment by Jarsen136** [comment]
I will do this
