### ISSUE TITLE
Remove pinterest and iframe from sharing button

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2807]
For simplicity and to keep the focus on the majority 
let's remove </> (does iframe even work with our XSS headers anyway?
Pinterest.

Probably make a tooltip with a black background and borders?

![image](https://user-images.githubusercontent.com/5887929/162529319-925fa919-3231-46cc-b69d-ce97bcc17c52.png)

**Comment by Jarsen136** [comment]
I will take it but I'm not sure what else to do except removing the `</>` icon.

And Is this what you want?
<img width="306" alt="image" src="https://user-images.githubusercontent.com/31397967/162550257-a28236be-3dda-454b-b868-00aacec19275.png">
