### ISSUE TITLE
App should show network status

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#281]
We should show color based on connected network

> May be strange request, is it feasible to integrate the 'network connection status' to dashboard something like

![image](https://user-images.githubusercontent.com/22471030/113831119-8ef91600-9787-11eb-8bc5-4de349aff871.png)

> To be honest, no way for the user to judge the connection status

> "Node URL" | It's falling back to default value. 
Would be nice, if it remembers the last chosen 'Node URL' option.

![image2](https://user-images.githubusercontent.com/22471030/113832245-b69cae00-9788-11eb-9c29-9f4983efd803.png)

**Comment by vikiival** [comment]
There is someting in app called `colors.ts` and it should show color accoring to the chain

**Comment by yangwao** [comment]
Could not find /apps issue but we have discussed this early tho, valid.

**Comment by yangwao** [comment]
Definitely worth it, at least #660 implementation and Statemine integration is coming.

**Comment by yangwao** [comment]
We have a chain selector in the corner, closing in that favour.
