### ISSUE TITLE
For flippers table use average gain instead of total investment / total profit

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2820]
So in the off-chain convo with @yangwao we iterated to the point where the current best metric would be to show is `average flip` 

What it means? 

https://github.com/kodadot/nft-gallery/pull/2804#issuecomment-1094930071

If you look on the table
<img width="163" alt="Screenshot 2022-04-11 at 13 38 21" src="https://user-images.githubusercontent.com/22471030/162734096-37ace39e-ea05-4cb8-a377-033fda08261f.png">

the first number should become (`46,66`)
![photo_2022-04-11 13 55 18](https://user-images.githubusercontent.com/22471030/162734376-0453a0fa-550c-4e2f-8e22-d9874a9f4f96.jpeg)

it's the `sum of all percetage changes / number of items`

📟 @Jarsen136

_Originally posted by @vikiival in https://github.com/kodadot/nft-gallery/issues/2804#issuecomment-1094961779_

**Comment by Jarsen136** [comment]
> @Jarsen136 🫣

Okay
