### ISSUE TITLE
Missing nfts in profile created tab

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#2836]
### What happened?

A bug happened!

### Please reproduce in steps

- Go to `/rmrk/u/DVa676uebTkgH8uZyS2umio7JtmkcSHHoPvPJJQY3bbYoAu`
- See missing nfts

### Expected Behavior

I've expected to see all nfts

### What browsers are you seeing the problem on?

Firefox

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Screenshots

![Capture d’écran 2022-04-13 à 8 41 49 AM](https://user-images.githubusercontent.com/9987732/163116165-60685327-4dd2-4dd1-a949-c0da890aad02.png)

### Relevant log output

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prachi00** [comment]
@roiLeo I can check this

**Comment by yangwao** [comment]
Hmm noticed like this yesterday at explorer at beta but when I went back through pages it showed again.

Isn't there an issue with how we fallback to Pinata from CF? 

📟 @vikiival

**Comment by prachi00** [comment]
https://beta.kodadot.xyz/rmrk/detail/12009176-289d0e953cbdc59a73-HHK-0072_HYPEHELL_KEYCHAIN-0000000000000072

it doesnt load either

**Comment by yangwao** [comment]
I see https://beta.kodadot.xyz/rmrk/collection/289d0e953cbdc59a73-HHK
And no errors in the console. Strange.


![image](https://user-images.githubusercontent.com/5887929/163409632-7dfedc6f-5873-4058-9a5c-fb5e7af8efaf.png)

**Comment by roiLeo** [comment]
> I see https://beta.kodadot.xyz/rmrk/collection/289d0e953cbdc59a73-HHK And no errors in the console. Strange.

Check this out https://singular.rmrk.app/collections/289d0e953cbdc59a73-HHK 😕 it might be related with rmrk 2.0 migration

**Comment by yangwao** [comment]
but thought they should use Burn?

**Comment by vikiival** [comment]
> Isn't there an issue with how we fallback to Pinata from CF?

I think it's related to something else (I bet we have some `v-if` which causes random NFTs to disappear)
