### ISSUE TITLE
Add Bookmark/Watch list

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2837]
![image](https://user-images.githubusercontent.com/5887929/210785836-553287d5-31ed-44ce-904e-de89933592f9.png)

I recall we had designed packs/lists back then using Textile but then we pulled out (don't even recall why) and now it's probably time to recycle ♻️ implementation (if we can) so people can create lists?

This could be used of course in a multidimensional way. I.e. ppl sorting stuff like on GoodReads, i.e. Twitter lists are working, i.e. 📂 folders 

Let's see if we can have this mostly as an off-chain way to go

Lists being private/public

**Comment by vikiival** [comment]
Continue in
- #5547
