### ISSUE TITLE
Link in /collection/{id} are broken on beta

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#2838]
### What happened?

- something i guess

### Please reproduce in steps

- Go to `/rmrk/collection/800f8a914281765a7d-KITTY` or any collection
- Click on any nft
- you're redirect to `/explore/?tab=GALLERY`

### Expected Behavior

I've expected to be redirected to the nft details

### What browsers are you seeing the problem on?

Firefox

### Screenshots

https://user-images.githubusercontent.com/9987732/163121224-6e2ec948-cd90-4320-8c6b-552036f18e8e.mov

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prachi00** [comment]
@roiLeo I;ll check this one
