### ISSUE TITLE
Can we have collection first in explore?

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#2840]
I feel like it's in reverse

+ I would like to see the tabs in Sentence case (first letter capitalised) 
+ plural "Collection" since it show multiple collections
+ missing "Showing result of ..." in `/explore/?tab=COLLECTION`
+ missing sort in collections tab

**Comment by prachi00** [comment]
@roiLeo I;ll check this as well, also I think we were adding it in preference for tab position

**Comment by prachi00** [comment]
#2819

**Comment by roiLeo** [comment]
> @roiLeo I;ll check this as well, also I think we were adding it in preference for tab position

Can we have Collections first by default?

**Comment by yangwao** [comment]
> > @roiLeo I;ll check this as well, also I think we were adding it in preference for tab position
> 
> Can we have Collections first by default?

Yes, would like to once we will have filters there. Now Filters are missing on top of collections :|

**Comment by prachi00** [comment]
> > > @roiLeo I;ll check this as well, also I think we were adding it in preference for tab position
> > 
> > 
> > Can we have Collections first by default?
> 
> Yes, would like to once we will have filters there. Now Filters are missing on top of collections :|

Fixed it in #2844

**Comment by yangwao** [comment]
I see Buy now on the empty collection? 

Maybe #2718 can tackle this?

![image](https://user-images.githubusercontent.com/5887929/163168390-e870014b-0965-44fe-b9b7-2f68d3924895.png)
