### ISSUE TITLE
List of funky KodaDot names

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2841]
Through our history we have seen many funky names. 

If you have seen some please drop in the comment

**Comment by yangwao** [comment]
KudaDot my fav
KondaDot my other fav

**Comment by vikiival** [comment]
> **Me On the conference**
> Someone: "Oh Koda, I heard about you"
> Me: "It's actually KodaDot"
> Someone: "Wtf, never heard about that"

meanwhile koda.art ;D
