### ISSUE TITLE
Collections Sort by

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2845]
I guess we should add there BUY now which should show you if there is anything to buy from that particular collection.

Some filters might be working in #2844 already?

> Sure, new issue will be to display again Collections Sort & Filters

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/issues/2718#issuecomment-1097859351_

**Comment by prachi00** [comment]
@yangwao ill pick this

**Comment by prachi00** [comment]
also we can still see collection sort right?

**Comment by roiLeo** [comment]
> also we can still see collection sort right?

not on beta nor on `main`, but you re-introduce it in #2844

**Comment by prachi00** [comment]
yes with 2844 it will start showing up
<img width="640" alt="Screenshot 2022-04-13 at 5 15 30 PM" src="https://user-images.githubusercontent.com/39299315/163173143-92a6e75f-6509-400c-85cd-493caf23a8be.png">

**Comment by roiLeo** [comment]
#### Progress
- [x] collections sorting
- [ ] collections search sensitive
- [ ] collections filter listed

**Comment by roiLeo** [comment]
filters on beta don't work anymore I think something break with infinite scoll

**Comment by roiLeo** [comment]
missing sort by: 
- "Last interacted" -> NFTEntity `updatedAt_DESC`
- "Least interacted" -> NFTEntity `updatedAt_ASC`
