### ISSUE TITLE
Social media cards v2

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2849]
Right now card has generic text.
Would be nice to add
Add title of NFT 
Collection name?
Aritst name?

![image](https://user-images.githubusercontent.com/5887929/163250134-a0fd20a8-bf17-4b87-b0e5-09eac83b0b67.png)

Hence @preschian is great with workers can take a look :)

**Comment by preschian** [comment]
just realized it's already up and seems worked well on the newest listing item
will take a look at this. I will try to add `price` also

**Comment by preschian** [comment]
hi, I already applied for these routes. need to test it @yangwao @jkdizajn
let me know if you getting this error again https://github.com/kodadot/nft-gallery/issues/2874
<img width="1050" alt="Screen Shot 2022-04-18 at 6 24 15 PM" src="https://user-images.githubusercontent.com/734428/163801687-32876abf-025b-4ec9-9f6b-88467a7288b0.png">

collection | gallery | detail | previously broken
--- | --- | --- | ---
<img width="470" alt="Screen Shot 2022-04-18 at 6 32 27 PM" src="https://user-images.githubusercontent.com/734428/163802411-0741c5de-140d-4c56-acf9-97a9af54ec56.png"> | <img width="468" alt="Screen Shot 2022-04-18 at 6 29 02 PM" src="https://user-images.githubusercontent.com/734428/163802236-eb00ff9b-bca1-4796-813c-5fc390dbf499.png"> | <img width="459" alt="Screen Shot 2022-04-18 at 6 33 23 PM" src="https://user-images.githubusercontent.com/734428/163802537-236cb5b5-d730-49ab-82c6-fae4aecdd0c2.png"> | <img width="462" alt="Screen Shot 2022-04-18 at 6 34 43 PM" src="https://user-images.githubusercontent.com/734428/163802667-19b375e3-f319-46e2-aa63-991bd1149b5a.png">

**Comment by preschian** [comment]
still getting error in some paths, will check it
<img width="492" alt="Screen Shot 2022-04-19 at 10 31 47 AM" src="https://user-images.githubusercontent.com/734428/163914835-cebd1f62-0523-435e-861a-fd8aec64ff01.png">

**Comment by preschian** [comment]
no error related to cf-workers so far, in the past 3 days
<img width="955" alt="Screen Shot 2022-04-22 at 17 38 48" src="https://user-images.githubusercontent.com/734428/164699300-41ce2955-27b5-41f2-b97d-10d146a7d58c.png">

**Comment by preschian** [comment]
hi @yangwao, is this what you expected? 

results:
| URL | image |
| --- | --- |
| /rmrk/collection/<br> https://kodadot.xyz/rmrk/collection/00da54310732f6437d-QBCVI | ![www opengraph xyz_url_https%3A%2F%2Fkodadot xyz%2Frmrk%2Fcollection%2F00da54310732f6437d-QBCVI](https://user-images.githubusercontent.com/734428/180412579-93b794ee-a2fe-49d6-9fdf-d6d62ad9ac51.png) |
| /rmrk/detail/<br> https://kodadot.xyz/rmrk/detail/11079135-00da54310732f6437d-QBCVI-ONI_10125-0000000000000016 | ![www opengraph xyz_url_https%3A%2F%2Fkodadot xyz%2Frmrk%2Fcollection%2F00da54310732f6437d-QBCVI (1)](https://user-images.githubusercontent.com/734428/180413371-baca4ea1-9b2c-4734-a64d-547de1877f5f.png) |
| /rmrk/gallery/<br> https://kodadot.xyz/rmrk/gallery/13433183-00da54310732f6437d-QBCVI-ONI_116125-0000000000000094 | ![www opengraph xyz_url_https%3A%2F%2Fkodadot xyz%2Frmrk%2Fgallery%2F11079135-00da54310732f6437d-QBCVI-ONI_10125-0000000000000016 (1)](https://user-images.githubusercontent.com/734428/180414234-7471e959-fb26-4dc9-9728-112dd83246da.png) |

**Comment by yangwao** [comment]
Continue in 
- #5567
