### ISSUE TITLE
Check on @google/model-viewer@^1.11.1

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2852]
Check on new recent latest google/model-viewer 

### Backlog
Seems to skip @google/model-viewer for now
- [x] add to ignore packages into renovate.json 
- [x] make an issue about it to add why it's there if someone wants to tackle that in parallel
- [x] update minor packages :)
![image](https://user-images.githubusercontent.com/5887929/162725368-76ce1b0e-5bba-42d4-ab51-ca51d3e472a0.png)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2811#issuecomment-1094902743_

**Comment by kkukelka** [comment]
Ill take a look
