### ISSUE TITLE
Missing tile switcher on collection/id

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2853]
I just noticed that on collection tile switcher (large display small display) went missing?
![image](https://user-images.githubusercontent.com/5887929/163391352-3bfb53f5-4dd6-4b93-b1ad-63ce129f371a.png)

https://kodadot.xyz/rmrk/collection/d6e71489d50f818c09-TEWIN
![image](https://user-images.githubusercontent.com/5887929/163391302-1c27d256-9681-473f-8fdb-911dfb1ecc88.png)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2813#issuecomment-1099138699_

**Comment by Jarsen136** [comment]
i will check it
