### ISSUE TITLE
Profile issues with default substrate address - ss58 issues on profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2857]
I guess we should tackle this stuff as users. as users lands on their default address ss58 42 and they can not see their holdings.

Once users landed on their ss58 42 substrate address, falling back to Kusama address would be probably the easiest fix for right now.
Also consider adding something like that trying to fetch other address NFT balances when users seeing nothing.

I recall this is probably the second report we are having users are not seeing their holdings

![image](https://user-images.githubusercontent.com/5887929/163553308-6fec7f17-95ee-401f-9b11-b2548efb8c78.png)

### Ref
- #2071 
- #1322

**Comment by roiLeo** [comment]
I'm not sure I understand the problem, can we have more information?
Is it possible to reproduce the bug?
