### ISSUE TITLE
Error on infinity scroll at collections

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2860]
When I land at https://beta.kodadot.xyz/rmrk/explore/?page=160

Seems the error is timeouts SubSquid and can't browse previous and next 

Happens only if I scroll too fast. 

Oh, sometimes when I click the random button doesn't work at all going upper or down.
Backward scrolling fetches almost all time but next forward most likely doesn't work :)

![image](https://user-images.githubusercontent.com/5887929/163564113-44c59417-aa2d-4241-8150-fa3024ac6f73.png)

Sometimes doesn't scroll at all :| 

![image](https://user-images.githubusercontent.com/5887929/163564479-210e5c67-484b-4e9d-a4eb-c05a0b7f2f13.png)

**Comment by Jarsen136** [comment]
I will check it 👀
