### ISSUE TITLE
Make default sorted by highest percentage in flippers

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2861]
Make default showing by the highest percentage to show "smart" people :)

https://beta.kodadot.xyz/rmrk/collection/800f8a914281765a7d-KITTY?tab=flippers

![image](https://user-images.githubusercontent.com/5887929/163564864-4ead8604-c088-4baa-b928-b1c47f171572.png)

**Comment by Jarsen136** [comment]
I will do this
