### ISSUE TITLE
App is fragile to the indexer swap 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2862]
I think we are having downtime.

https://deploy-preview-2859--koda-nuxt.netlify.app/rmrk/collection/800f8a914281765a7d-KITTY?tab=holders

![image](https://user-images.githubusercontent.com/5887929/163567329-a75ab6cc-9a8b-43a5-b512-7f8f1479d0bc.png)

![image](https://user-images.githubusercontent.com/5887929/163567595-d323bbd7-cf15-4fff-8ebe-10d1f2254e6e.png)

![image](https://user-images.githubusercontent.com/5887929/163567649-a9e72ebf-5e9c-4cd4-9456-6fbfec83f1b9.png)

![image](https://user-images.githubusercontent.com/5887929/163567664-9494f58f-ebe8-40ae-a176-7f0780f5087a.png)

![image](https://user-images.githubusercontent.com/5887929/163566309-bd006534-fc7f-4144-ac9a-f1694497e386.png)

**Comment by Jarsen136** [comment]
I also met a few times today 👀

**Comment by vikiival** [comment]
Looks like the apollo went down. 
Talking with SubQuery.


<img width="1222" alt="Screenshot 2022-04-15 at 13 43 21" src="https://user-images.githubusercontent.com/22471030/163567044-267f9d24-add3-4ec3-a95e-61d9b2d042cd.png">

For me it's working oki

![Screenshot 2022-04-15 at 13 46 14](https://user-images.githubusercontent.com/22471030/163567117-c7bfeefc-052f-4e82-ad3e-086d6c5512d3.png)

Next time please attach the error logs from the `network` tab, 

without it it's super hard to debug

**Comment by yangwao** [comment]
It's seems it's related to #2859

**Comment by yangwao** [comment]
I put there payload screenshosts as well

**Comment by yangwao** [comment]
Make a protocol on what to report for network bugs to best tackle them

**Comment by vikiival** [comment]
Yup looks like it's broken by #2859

**Comment by vikiival** [comment]
```
0: "GraphQLError: Variable \"$orderBy\" got invalid value \"blockNumber_DESC\"; Value \"blockNumber_DESC\" does not exist in \"NftEntitiesOrderBy\" enum. Did you mean the enum value \"BLOCK_NUMBER_DESC\" or \"BLOCK_NUMBER_ASC\"?"
1: "    at /usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/values.js:116:15"
2: "    at coerceInputValueImpl (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/utilities/coerceInputValue.js:131:9)"
3: "    at coerceInputValue (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/utilities/coerceInputValue.js:37:10)"
4: "    at _loop (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/values.js:109:69)"
5: "    at coerceVariableValues (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/values.js:121:16)"
6: "    at getVariableValues (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/values.js:50:19)"
7: "    at buildExecutionContext (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/execute.js:203:61)"
8: "    at executeImpl (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/execute.js:101:20)"
9: "    at execute (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/execute.js:60:35)"
10: "    at execute (/usr/local/lib/node_modules/@subql/query/node_modules/apollo-server-core/dist/requestPipeline.js:206:48)"
message: "Variable \"$orderBy\" got invalid value \"blockNumber_DESC\"; Value \"blockNumber_DESC\" does not exist in \"NftEntitiesOrderBy\" enum. Did you mean the enum value \"BLOCK_NUMBER_DESC\" or \"BLOCK_NUMBER_ASC\"?"
```

**Comment by Jarsen136** [comment]
Yup, it may related to my pr : )
 I will try to fix it.

**Comment by vikiival** [comment]
It's related to the PR 
https://github.com/kodadot/nft-gallery/pull/2859/files#r851231558

**Comment by yangwao** [comment]
related https://github.com/kodadot/magick/issues/24

**Comment by roiLeo** [comment]
friendship ended with magick now rubick is my best friend
