### ISSUE TITLE
Refactor: GalleryItem.vue cleanup 🧹 

### ISSUE THREAD

**Issue by kkukelka** [kodadot/nft-gallery#2866]
### Is your feature request related to a problem?

Since we abstracted a lot of logic into Base component there is much cleanup to do

Todo:
- ~~Remove unnecessary poll requests~~
- Simplify overcomplicated logic
- Remove unused imports, properties and css
- Lazy Import some components

**Comment by yangwao** [comment]
I guess that every second fetch is to avoid double spending 😅 

📟  @vikiival

**Comment by roiLeo** [comment]
> I guess that every second fetch is to avoid double spending 😅

Wouldn't be better to fetch data until an action is made?

**Comment by Jarsen136** [comment]
> 
> Wouldn't be better to fetch data until an action is made?

However, you don't know when should fetch data if the action is submitted by others : )
IMO, for the gallery item, poll fetch is necessary. Or maybe need a long connect? like WebSocket

**Comment by kkukelka** [comment]
> I guess that every second fetch is to avoid double spending 😅
> 
> 📟 @vikiival

Oh damn I didn't think about that at all. I will reintroduce the smartquery then
