### ISSUE TITLE
Use image from last NFT as og:image for user's profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#287]
Now it looks quite fugly and we can do better.

I would propose to show user's last mint from user profile.

![IMG_20210411_065400](https://user-images.githubusercontent.com/5887929/114292970-b7885500-9a92-11eb-80e0-88d98854796b.jpg)

https://twitter.com/yangWao/status/1381107901989855232?s=19

**Comment by miguel-quezada63** [comment]
I am interested in contributing to this issue. Specifically how would you like this implemented?

**Comment by miguel-quezada63** [comment]
Bump on this issue. Currently have the og:image for a user's profile working, still need to get video functionality working. However, would including the user's profile username or address as the og:title also be a good idea as well?

**Comment by miguel-quezada63** [comment]
Added this feature in #306

**Comment by yangwao** [comment]
> Bump on this issue. Currently have the og:image for a user's profile working, still need to get video functionality working. However, would including the user's profile username or address as the og:title also be a good idea as well?

Yes, [search in Google shows item like this](https://www.google.com/search?q=site:nft.kodadot.xyz&rlz=1C5CHFA_enSK944SK945&sxsrf=ALeKk03GTBdO1GuoKXAXyVhkxWAAG-7-EQ:1619688697296&ei=-XyKYPL4DPCkrgTA5JfICQ&start=10&sa=N&ved=2ahUKEwiy2cbLkqPwAhVwkosKHUDyBZkQ8tMDegQIARA3&biw=2844&bih=2312)

![image](https://user-images.githubusercontent.com/5887929/116530587-7e4b4400-a8de-11eb-84c0-8d5093e42dfe.png)

@miguel-quezada63 I mean love to merge it with #243 if you are up to it!

**Comment by yangwao** [comment]
You can use https://cards-dev.twitter.com/validator to check if it works

**Comment by miguel-quezada63** [comment]
Sounds good regarding the merge. I will also take a look at #243, looks pretty doable for me.

**Comment by yangwao** [comment]
> However, would including the user's profile username or address as the og:title also be a good idea as well?
Oh somehow I've missed this, yes, showing users name would be perfect I guess, but I'm afraid there might be issues with resolving identity on-chain, but at least showing address will motivate an artist to set their identity on-chain :)

Maybe we could set to og:title name of nft token?

**Comment by yangwao** [comment]
Seems done
