### ISSUE TITLE
Sort visited NFTs by time user has visited them

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2873]
I visited Kusama bots last but still, appear as third and fourth.

Would be nice to sort it by the time the user has visited it. 

I guess now it's sorted by the time being minted or actions?
now I check on the far right is 6 months ago on the very left 3 days and middle 1 day :D

![image](https://user-images.githubusercontent.com/5887929/163672167-f6756ee3-1dd2-4bd5-8644-fee06fd818f0.png)

**Comment by prachi00** [comment]
Ill check this

**Comment by prachi00** [comment]
@yangwao isnt the time mentioned in these cards referencing to minting date? do you want to sort them by minting date?

**Comment by prachi00** [comment]
@vikiival what is the default order for **nftEntities** as the `ids` in query is being sent in the right order but returned in a different one, even when no value in `orderBy` is provided

**Comment by yangwao** [comment]
@vikiival 👀

**Comment by vikiival** [comment]
> what is the default order for nftEntities as the ids

Not sure what you mean. Could you (@prachi00) rephrase your q?

**Comment by prachi00** [comment]
Sure, 
So what I mean is we store these in the localstorage and that is stored in the correct order that is by when the user visited them and the ids are also sent to the api in the correct order that is recent one is at the top
However, the response returned from the api is not in order

**Comment by vikiival** [comment]
> However, the response returned from the api is not in order

Imagine that you pass your shopping list to a shop assistant. 

Shop assistant will go from the beginning of the store to the end and puts items to the basket if the item is `in` the shopping list.

After the shopping assistant go to the end of the store you may have probably all items however they won't be sorted in the correct order. 


It means that the api can't guarantee you correct order (see the stackowerflow Q). The solution is to create sort of the matching function or do multiple queries 🤷

**Comment by prachi00** [comment]
> 

yeah makes sense, I guess creating a sorting function is then the ideal way
