### ISSUE TITLE
Error 1101 - Worker threw exception

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#2874]
### What happened?

After minting a new NFT, my page crashed into that mode: 
![obrázok](https://user-images.githubusercontent.com/81104034/163674687-3f32fb82-fdd5-46b9-8d33-b45a94a949ae.png)

### Please reproduce in steps

it happened to me with this NFT
https://kodadot.xyz/rmrk/gallery/12277672-900D19DC7D3C444E4C-KSMBOT-THE_FIRST_PIXEL_GIFT-0000000000000135

### Expected Behavior

I've expected ...page loading correctly

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

![obrázok](https://user-images.githubusercontent.com/81104034/163675045-a88bc4b6-d251-42e9-9a41-21c093e3959d.png)

### Payment link for reward

https://kodadot.xyz/transfer?target=FqCJeGcPidYSsvvmT17fHVaYdE2nXMYgPsBn3CP9gugvZR5&usdamount=0&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptodamsky** [comment]
It's actually weird that for me the page works fine, for deepologic it doesn't want to load.

**Comment by yangwao** [comment]
@preschian might check logs for this one

**Comment by preschian** [comment]
Hi, sorry for the error. I have already deployed the fixes. I hope that there is no error again.

the root cause for this error is that the `meta` is null, so the script need to fetch the image by `metadata` in another endpoint
```JSON
{
  "data": {
    "nftEntityById": {
      "id": "12277672-900D19DC7D3C444E4C-KSMBOT-THE_FIRST_PIXEL_GIFT-0000000000000135",
      "meta": null,
      "metadata": "ipfs://ipfs/bafkreiagyfkwy4isl7axi2inkylkaywx7t2tdxf776xc3olhf5v2xg6ozu"
    }
  }
}
```

**Comment by jkdizajn** [comment]
Hi @preschian it works on beta, but not on kodadot.xyz
I attach a video:

https://user-images.githubusercontent.com/81104034/163986037-f5135a60-d17f-4980-b50c-d4328af04fd6.mp4

**Comment by preschian** [comment]
Hi, @jkdizajn can you try to refresh the page? I think this case should be not related to cf-workers. In this case, maybe our graphql query takes a long time to response

https://user-images.githubusercontent.com/734428/163987177-55f11793-964f-4528-8593-b5c34267c3a9.mov

**Comment by niklasp** [comment]
Updates on this?

**Comment by jkdizajn** [comment]
> 

yes, it's okay now
thx <3
