### ISSUE TITLE
Adding activity on collection 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2881]
I guess hence we prior showing important events like BUYs, we should probably in future show the total amount of events like make offers/bids collection wisely to determine demand on collection trending valuation.

I guess it might worth to show LIST, GIFTs accounting for activity to determine if washtrading is occuring, one more pseudometric to go

![20220417_100115.jpg](https://user-images.githubusercontent.com/5887929/163706002-9c9cef7b-a598-4a94-979a-c1d478422f07.jpg)

**Comment by petersopko** [comment]
@yangwao I see this related to basilisk, is this basilisk specific requirement? seems to me like more general issue

**Comment by yangwao** [comment]
> seems to me like more general issue

yes, offers and bids are basilisk specific.

> total amount of events like make offers/bids collection wisely to determine demand on collection trending valuation.
