### ISSUE TITLE
Can we put instagram link somewhere on our landing page?

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#2886]
### Is your feature request related to a problem?

Since we are currently starting with KodaDot instagram account, let's put link to our landing page and officially release it on twitter etc. There is currently 9 posts so it's ready to get some proper attention.

https://instagram.com/kodadot.xyz/

### Describe the solution you would like

Only thing i'm asking - where would be the ideal placement?

### Describe alternatives you have considered

/

### Screeenshots

/

**Comment by prachi00** [comment]
@damsky maybe at the footer? I can do this

**Comment by prachi00** [comment]
<img width="1421" alt="Screenshot 2022-04-19 at 5 22 11 PM" src="https://user-images.githubusercontent.com/39299315/163997415-e2d87ead-acab-4488-ab98-607d1bc6e1ae.png">
here with the other socials would be apt I think

**Comment by cryptodamsky** [comment]
Yup let's start with that :)
