### ISSUE TITLE
Create a connector api in Autocode to integrate w kodapi

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2890]
I guess once our query builders would be out would be interesting make module to autocode to integrate stuff way faster from dev side in autocode. Spoke w @petersopko so I guess would be superior to have and hack faster way

It should be showing in autocomplete in their IDE 
<img width="225" alt="image" src="https://user-images.githubusercontent.com/5887929/168482830-2e252952-0a78-43d3-9244-8d1916c782c0.png">

my bet it's this when you login https://autocode.com/dashboard/

<img width="304" alt="image" src="https://user-images.githubusercontent.com/5887929/168482962-1a42f632-4905-4a8b-a581-f6b9bf25fb8a.png">

### Ref
- https://docs.autocode.com/projects/what-are-projects/standard-library-apis/
- https://docs.autocode.com/standard-library-of-apis/adding-your-own-apis/creating-a-connector-api/
- https://autocode.com/lib/?p=3 (hopefully we can get verified badge!)

**Comment by vikiival** [comment]
meanwhile Autocode is gone
