### ISSUE TITLE
Vue Composition API migration

### ISSUE THREAD

**Issue by aito-hideki** [kodadot/nft-gallery#2893]
### Is your feature request related to a problem?

Vue Composition API is core feature of Vue 3, so it's the way towards Vue 3.

### Describe the solution you would like

This will include replacing mixins and options api to composition api using @nuxt/composition-api

- Replace all mixins with composables.
- Replace options API with composition API
- Also include replacing filters with member functions as filters are deprecated

### Describe alternatives you have considered

https://vuejs.org/guide/extras/composition-api-faq.html
https://vuejs.org/api/sfc-script-setup.html
https://vuejs.org/api/composition-api-setup.html
https://vuejs.org/guide/typescript/composition-api.html

### Screeenshots

Components should look like this.
![image](https://user-images.githubusercontent.com/56869402/164648724-7decaa49-ee7b-43d0-9bf6-2a396ff4f0df.png)

**Comment by yangwao** [comment]
Let us know how this goes :)

**Comment by yangwao** [comment]
@aito-hideki is there any progress on this? Haven't heard from you for a while. 
let me know if you want to continue on this, if not hear from you in 7 days, someone can take over this.

**Comment by aito-hideki** [comment]
Hi @yangwao 
I am still working on that.
I am pushing forward with Vue Composition API, Vue3, Vite migration together along with Vite SSG.
As the scope of work is so huge, I am still working on that but haven't finished working.

**Comment by niklasp** [comment]
any update @aito-hideki would like to adress it otherwise

**Comment by yangwao** [comment]
Meanwhile, efforts have started with the composition API
- https://github.com/kodadot/nft-gallery/pull/3718
- #3714

**Comment by yangwao** [comment]
It's stalled, continue to
- #4750 
- #2690
- #2081
