### ISSUE TITLE
Probably move activity batches from Readme.md to Activity.md

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2899]
@skylla54 suggested that we should lightweight stuff from our Readme into dedicated Activity.md to make it more streamable and readable for others

@skylla54 will propose some PR to make something

**Comment by thea-exe** [comment]
I'm in the process of doing this actually! Please assign this to me :D @yangwao

**Comment by thea-exe** [comment]
Thank you @kkukelka :D
