### ISSUE TITLE
see who reacted to nft even if you are not connected

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#2917]
When i haven't connected my wallet, I can't see who has reacted to the nft
I would like to be able to access user's profile who sent an emote

Is this done on purpose?

#### Screenshot
<img width="1023" alt="Capture d’écran 2022-04-29 à 8 32 04 AM" src="https://user-images.githubusercontent.com/9987732/165895315-f4ec4e84-042d-4b0d-84ed-77cd33ca1d70.png">

**Comment by Jarsen136** [comment]
hi, i will take it

**Comment by Jarsen136** [comment]
i will take this

**Comment by Jarsen136** [comment]
Even if you are connected, we still could not see who reacted to nft  : )
