### ISSUE TITLE
Add quality tool services for code quality and fun

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#292]
- [x] deepsource - https://deepsource.io/pricing/
- [ ] ~code climate~ - https://codeclimate.com/quality/pricing/ > Looks like kodadot/nft-gallery is a Vue project, but we don't support Vue yet on Code Climate.
- [ ] https://github.com/marketplace/codacy
- https://github.com/marketplace/deepscan
- https://github.com/marketplace/codefactor
- https://github.com/marketplace/actions/lgtm-reaction
- https://github.com/marketplace/actions/pr-chatter
- https://github.com/marketplace/actions/telegram-action or https://github.com/marketplace?category=chat&query=telegram

**Comment by jai-deepsource** [comment]
Hey @yangwao 👋🏼 -- thanks for considering DeepSource. I forked the repo and ran an analysis. Here are the issues we found - https://deepsource.io/gh/jai-deepsource/nft-gallery/issues/

**Comment by yangwao** [comment]
Oh, thanks for pro-active support @jai-deepsource ! 
What's our rank? Or maybe you could add some averages on the appropriate size of the repository to ours? 
Hard to know how bad or good we are 😅
![image](https://user-images.githubusercontent.com/5887929/115399729-ca183200-a1e8-11eb-99ab-515fa2dde8d5.png)
Thank you one more time, we will put @deepsource into works! 🤍

**Comment by yangwao** [comment]
ayay some code smells https://codeclimate.com/github/kodadot/nft-gallery/issues?category=complexity&engine_name%5B%5D=structure&engine_name%5B%5D=duplication

**Comment by srijan-deepsource** [comment]
Hey @yangwao,
I'm pitching in here to reply to that: we are working on adding complexity issues. It is in our roadmap and would be released down the line.
Regarding issues for function/module length: we have stayed away from adding these at the moment because they are opinionated.

**Comment by JustLuuuu** [comment]
@preschian do you think this is still relevant? If no pls close

**Comment by preschian** [comment]
> do you think this is still relevant? If no pls close

I think already enough with what we have right now. let's close this for now
