### ISSUE TITLE
Unify shopping logic for multichain

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2965]
> I think one is used for Rmrk and the other one for Statemine, Westmint, Bsx. it would be good to unify all this

Could we open another issue to handle this unification of these two components?
I think it's not in the description of the original issue and maybe will cost much more time : )

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/2948#issuecomment-1119630405_

**Comment by roiLeo** [comment]
links with #1678
