### ISSUE TITLE
Handle accounts with ss58 format more properly

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3019]
### Is your feature request related to a problem?

With upcoming parachain implementations the problems with ss58 would rise :)

### Describe the solution you would like

I would like to see some smart implementation how to solve issues like: 
- bad address 
- account equality

### Describe alternatives you have considered

I have tried this alternative:
- on the app level have a subscriber that would handle the address format
- have middleware that would convert address from any ss58 format to correct one

### Screeenshots

<img width="1175" alt="Screenshot 2022-05-14 at 13 59 32" src="https://user-images.githubusercontent.com/22471030/168424736-a4c1309b-da08-4e84-b7df-ababe2ece38d.png">

**Comment by yangwao** [comment]
maybe fixed in one of these? 

- #2857 
- #3118 
- #3121 
- #2998

**Comment by vikiival** [comment]
This is marked as enhancment, not a bug

**Comment by vikiival** [comment]
Discussed in 
- https://github.com/kodadot/nft-gallery/discussions/4754
