### ISSUE TITLE
SEO: card UI update

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#3038]
Some changes need to be done [here](https://github.com/AndreyGrin/og-image):
- remove background on logo
- (replace logo with TransparentWhite version)
- update price tag background color `#363636` & padding `3px 8px`

Tested on `/rmrk/collection/d08ff136a2fe19974d-CRAZY_CANARY`

#### collection card

- edit price tag: "XXX items"
- parse markdown (#889)

![Screenshot 2022-05-20 at 16-07-16 Card Validator Twitter Developers](https://user-images.githubusercontent.com/9987732/169545578-7c2e2a31-0584-4daa-95ec-89b927832151.png)

#### gallery item

- edit price tag: "XXX KSM"
- parse markdown 

![Screenshot 2022-05-20 at 16-07-56 Card Validator Twitter Developers](https://user-images.githubusercontent.com/9987732/169545632-feeb0f8c-09cc-4b01-ae1b-4a7e00d8569c.png)

**Comment by AndreyGrin** [comment]
![image](https://user-images.githubusercontent.com/2453346/176556575-4a9275cc-c31a-4c0e-9fc9-2aafcdc7ff31.png)
What about this? Is it correct logo?
Parsing markdown and showing it on social card isn't possible. But we can try to remove markdown syntax and show plain text instead.

Markdown, XXX items, XXX KSM should be done on KodaDot, I could make PR for this once I know what you expect for markdown.

**Comment by roiLeo** [comment]
> What about this? Is it correct logo? 

yes, I really like this one. 
Can you try to change bottom right padding too?

> Parsing markdown and showing it on social card isn't possible. But we can try to remove markdown syntax and show plain text instead.

👍 

> Markdown, XXX items, XXX KSM should be done on KodaDot, I could make PR for this once I know what you expect for markdown.

Feel free, stage is yours 🕺

**Comment by roiLeo** [comment]
🚀 merged in https://github.com/AndreyGrin/og-image/pull/3

continue #889
