### ISSUE TITLE
Make curated list of collections per chain

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3047]
### Is your feature request related to a problem?

I'm always frustrated when I see a list of collections for RMRK in other chains

### Describe the solution you would like

I would like to see a curated list for each chain or else the app should take last 5 created collections

### Describe alternatives you have considered

~

### Screeenshots

<img width="1792" alt="Screenshot 2022-05-22 at 14 25 39" src="https://user-images.githubusercontent.com/22471030/169695027-3fdd432b-03cc-48af-81ab-7ff382b2890d.png">

**Comment by prachi00** [comment]
@vikiival currently there is no `passionFeed` query implemented https://app.gc.subsquid.io/beta/snekk/003/graphql
how do we show the curated list on all other chains?

**Comment by roiLeo** [comment]
👋 I already start on this one
