### ISSUE TITLE
Leverage Functions to proxy API keys

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#305]
We are aware that we are serverless NFT gallery, thus due security issues we need hide some secrets.

Would be nice to use https://docs.netlify.com/functions/build-with-typescript/ probably?
Seems pricing is fair https://www.netlify.com/pricing/#add-ons-functions

Don't forget to regenerate keys for 
- [x] pinata
- [ ] textile

Once done

**Comment by vikiival** [comment]
Closed by #535

**Comment by vikiival** [comment]
I made textile keys invalid

**Comment by yangwao** [comment]
> I made textile keys invalid

 ♿️
