### ISSUE TITLE
Date information in Holders page is acting weird

### ISSUE THREAD

**Issue by damskyftw** [kodadot/nft-gallery#3050]
### What happened?

Do we need to show the time information 2 times per one address? It looks a bit weird

### Please reproduce in steps

Go to collections, choose your collection, choose holders, tick "Date" and have a look at the history

### Expected Behavior

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/92786519/169712297-3c212aef-9879-41d4-913e-02b756efd653.png">

Expected behavior would be to show the time when it was changed or sent only once per address

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

https://kodadot.xyz/rmrk/collection/D897AB7EF966497D4B-KODA?tab=holders&page=1

### Payment link for reward

/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
However, for those address owns several nfts, the date information are different from each other.
So seems every nft should have a single date?

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/31397967/169721443-211ff50d-3441-4f23-8df5-c4c80bcc9b46.png">

**Comment by yangwao** [comment]
> Expected behavior would be to show the time when it was changed or sent only once per address

per NFT make sense when it was acquired and per address makes sense when the last activity has happened on collection. Maybe we should add there something like - "the last activity of address" on the address line?

Or change Date to Activity?
