### ISSUE TITLE
Sales feed doesn't work?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3051]
### What happened?

opened https://beta.kodadot.xyz/sales/

### Please reproduce in steps

open https://beta.kodadot.xyz/sales/

### Expected Behavior

probably seeing recent sales?

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz

### Screenshots

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/5887929/169779573-7b055291-3960-4449-b40a-75012a4cdb19.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
> ◷ The new squid will be available as soon as the deployment is complete.

**Comment by yangwao** [comment]
seems working 

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/5887929/170859959-0182ba3b-8eb5-4102-a2e5-fd6e066faa4d.png">
