### ISSUE TITLE
Implement ink! nft marketplace into KodaDot 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3084]
This is a pure research stage issue

- https://github.com/gear-tech/apps/tree/master/nft-marketplace
- https://github.com/gear-tech/apps/tree/master/nft-marketplace/nft

**Comment by roiLeo** [comment]
Apply for ink! Grant => https://github.com/use-inkubator/Ecosystem-Grants

**Comment by vikiival** [comment]
Duplicate of - https://github.com/kodadot/ops-internal/issues/292
