### ISSUE TITLE
Astar v0 implementation

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3099]
We are in intense chat with Astar and Shiden and once we will see support by SubSquid for Contracts pallet, we can kick of this stuff.

- [ ] NFT marketplace written ink!
  - [ ] Orderbook v0 
  - [ ] Royalties
  - [ ] Swaps
  - [ ] Make Offers
  - [ ] Bundles

### NFT standards we want to see implemented
- [ ] [PSP34](https://docs.openbrush.io/smart-contracts/PSP34/psp34/
)
- [ ] [PSP1155](https://docs.openbrush.io/smart-contracts/PSP1155/psp1155)

### KodaDot compatibility
- [ ] Update existing components using ink! contract
- [ ] Gallery item - actions within ink! contracts
- [ ] Explorer - browsing 
- [ ] Basic Filters - for sale, price 
- [ ] Minter - minting with traits

### Indexer
- [ ] We can anticipate support for WASM indexing end of June from SubSquid 
- [ ] Support for Factory contracts 

### Ref
- Partially inspired by [Reactive NFTs by Koda](https://docs.kodadot.xyz/reactive-nfts.html)
- https://github.com/AstarNetwork/AstarBounties/issues/6

**Comment by vikiival** [comment]
For reference

- vikiival/mimick#2

**Comment by vikiival** [comment]
Releavant for solidity - impl - https://github.com/kodadot/gibanica/issues/2
