### ISSUE TITLE
Basilisk v0 post-merge fixes

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3116]
Hey as there are a lot of post reviews, we would like to split load off @vikiival head and we want to speed up BSX integration.

Feel free to take a peek at PRs conversations in #3060, which weren't resolved. 
Help to contribute and coordinate and put label Basilisk or BSX prefix to name for the PRs so we can merge it to `main`.

We will for sure paid-up individual bounties to participants.

Best to write which part of BSX components you would like to fix, so we would avoid double work.

🐍

### Ref
- https://github.com/kodadot/nft-gallery/issues/3115
- https://github.com/kodadot/nft-gallery/issues/3039
- https://github.com/kodadot/nft-gallery/issues/1015
- https://github.com/kodadot/nft-gallery/issues/3047
- https://github.com/kodadot/nft-gallery/issues/3118
- https://github.com/kodadot/nft-gallery/issues/3119

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/3060#issuecomment-1149814261_

**Comment by vikiival** [comment]
👋

**Comment by vikiival** [comment]
👋

**Comment by petersopko** [comment]
all of the referenced issues which are not done are linked, closing this one for duplicity 
- https://github.com/kodadot/nft-gallery/issues/660
