### ISSUE TITLE
BSX issue with ss58?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3118]
this might be an issue with ss58? 
I switched to BSX and showed 2 while the BSX testnet should be 10041 ?

<img width="453" alt="image" src="https://user-images.githubusercontent.com/5887929/172605485-3e35d897-0b03-4856-bb2f-b72adede024e.png">

**Comment by roiLeo** [comment]
https://github.com/kodadot/nft-gallery/blob/9e767abda32dd00b96d7ac5666f44ca64631702b/utils/config/wallets/BaseDotsamaWallet.ts#L102
&
https://github.com/kodadot/nft-gallery/blob/9e767abda32dd00b96d7ac5666f44ca64631702b/utils/config/wallets/BaseDotsamaWallet.ts#L130

I can try to take care of it

**Comment by vikiival** [comment]
👍
