### ISSUE TITLE
Seems build times take a while on beta 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3123]
I've noticed that sometimes builds now last like for 7-10m, on average 7minutes +
On average we've been somewhere between 4-5m. 

before
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/5887929/172619410-6c49c078-24fa-40fb-9670-e4d801ee60f6.png">

now
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/5887929/172622256-496624d3-11db-4a0f-bae7-3c5201f1c224.png">

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/5887929/172622319-6f6293e8-7fca-4e1e-b2b0-f3af506c8b11.png">

**Comment by roiLeo** [comment]
duplicate of #2696?

**Comment by roiLeo** [comment]
Nuxt 3 incommingn less build time

**Comment by yangwao** [comment]
I mean, it's definitely better! and hence netlify add bunch of minutes and we got 3 concurrent builds it's okayish

![image](https://github.com/kodadot/nft-gallery/assets/5887929/c658c622-ddcb-49c1-a509-efccb6fd23ca)
