### ISSUE TITLE
PASSION FEED in GALLERY

### ISSUE THREAD

**Issue by zhengow** [kodadot/nft-gallery#3148]
### What happened?

When i choose `passion feed`, there is no nft to show.
I think it will confuse the explorers.

### Please reproduce in steps

Go to https://kodadot.xyz/rmrk/explore/?tab=GALLERY&page=1 Click on `Passion Feed` See error

### Expected Behavior

I've expected that I can see nfts

### Screenshots

Paste from your clipboard or upload screenshots/video
![image](https://user-images.githubusercontent.com/38389586/173180003-821df8d8-3351-4187-a8a1-0d9506eff7c0.png)

![image](https://user-images.githubusercontent.com/38389586/173180010-16b24c97-bee0-417a-8d6c-5036bacdc2cf.png)

### Payment link for reward

Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KngZhi** [comment]
Passion feed means the list of issuers from NFTs you already bought.

So, in this case, if you haven't bought any NFT, then yes, it should be empty. 😄

**Comment by niklasp** [comment]
it should rather show a link to buy some

**Comment by prachi00** [comment]
This would have been solved with #3103
