### ISSUE TITLE
When creating collection on BSX too low priority tx?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3156]
Seems like no errors in logs, nothing red in the network. 

To reproduce
Been minting the collection on BSX and the preloader just disappeared.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/5887929/173569353-2bdd7389-de95-413b-abc7-6a151cf67db2.png">

On the second try 

> RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (1050 vs 1050): The transaction has too low priority to replace another transaction already in the pool.
> DRR: 1014: Priority is too low: (1050 vs 1050): The transaction has too low priority to replace another transaction already in the pool.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/5887929/173569746-fd18b4c6-8143-4bbd-88ca-4d6f9bb32bbd.png">

> DRR: 1014: Priority is too low: (3140 vs 1050): The transaction has too low priority to replace another transaction already in the pool.
> RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (3140 vs 1050): The transaction has too low priority to replace another transaction already in the pool.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/5887929/173571352-79c7ebaa-ec47-48e9-9e5c-a63040640c4c.png">

Seems I can't mint collection at all and can't mint nft within collection.

Might be issue within block finality on network?

um yes.
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbasilisk-kodadot.hydration.cloud#/explorer

<img width="262" alt="image" src="https://user-images.githubusercontent.com/5887929/173571933-fe9cc653-11eb-4160-b0cd-58d48c586ea2.png">

**Comment by yangwao** [comment]
Reset of chain and reindexing in progress tho

**Comment by vikiival** [comment]
<img width="512" alt="Screenshot 2022-06-15 at 09 10 48" src="https://user-images.githubusercontent.com/22471030/173765185-e2ba0045-15be-4bc6-b57b-2c22a1966afb.png">

-1 sir 🫡

**Comment by yangwao** [comment]
solved meanwhile
