### ISSUE TITLE
Adjust Basilisk to Basilisk (testnet) to chain selector

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3162]
To avoid any confusion people in production, let's rename there Basilisk to "Basilisk (testnet)" 

<img width="219" alt="image" src="https://user-images.githubusercontent.com/5887929/174095552-595b0d04-90c1-4981-927f-2c7e9fc20261.png">

**Comment by zhengow** [comment]
👋

**Comment by yangwao** [comment]
@zhengow seems doesn't work on https://beta.kodadot.xyz after merging #3164 ? 

<img width="274" alt="image" src="https://user-images.githubusercontent.com/5887929/174294368-6c8b09d7-aeeb-4c8d-8e88-7c57e6fa2f1e.png">

https://github.com/kodadot/nft-gallery/pull/3164#issuecomment-1158711796

**Comment by zhengow** [comment]
let me see later



发自我的iPhone


------------------ Original ------------------
From: Matej yangwao ***@***.***&gt;
Date: Fri,Jun 17,2022 8:02 PM
To: kodadot/nft-gallery ***@***.***&gt;
Cc: zhengow ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [kodadot/nft-gallery] Adjust Basilisk to Basilisk (testnet) tochain selector (Issue #3162)

**Comment by yangwao** [comment]
it's on https://beta.kodadot.xyz in incognito but doesn't update in previous instance tho, whatever, hopefully for new ones doesn't break anything in production

<img width="275" alt="image" src="https://user-images.githubusercontent.com/5887929/174312944-7ac164ac-f0fb-4e07-a47f-205074fe4ad0.png">

**Comment by zhengow** [comment]
> 

Right, it's related to cache something. It will not break anything in production because the only change is `basilisk text`
