### ISSUE TITLE
SearchSortDropdown [Vue warn]: Invalid default value for prop "value"

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#3165]
#### Step to reproduce:
- go to landing
- switch to bsx chain
- error in console: `[Vue warn]: Invalid default value for prop "value": Props with type Object/Array must use a factory function to return the default value.`

found in

---> <SearchSortDropdown> at components/rmrk/Gallery/Search/SearchSortDropdown.vue

<img width="754" alt="Capture d’écran 2022-06-17 à 11 26 57 AM" src="https://user-images.githubusercontent.com/9987732/174270194-39b9256d-3646-47e9-9f13-1f215ec14974.png">

**Comment by Jarsen136** [comment]
👋
