### ISSUE TITLE
Subsquid / GraphQL crashing randomly

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#3168]
### What happened?

When i revisit my profile the collections etc don’t load

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

Paste from your clipboard or upload screenshots/video

https://user-images.githubusercontent.com/92786519/174310852-7b416bf9-bc71-4bfb-b07b-78f80ebf4213.mov

### Relevant log output

```shell
Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 124
da68234.modern.js:1:2600410
2022-06-17 15:43:44          API-WS: disconnected from wss://kusama.api.onfinality.io/public-ws: 1001:: Going Away da68234.modern.js:1:1877867
[API] disconnected 1538a12.modern.js:1:778475
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. HUJv6Xy5V4fAYzyjx8QDE9U2R7qEgsUv9Sc5QVCELbaQmvw:8:1
[API PLUGIN] wss://kusama.api.onfinality.io/public-ws 1538a12.modern.js:1:485154
XHROPTIONShttps://app.gc.subsquid.io/beta/rubick/006/graphql
CORS Missing Allow Origin

XHROPTIONShttps://app.gc.subsquid.io/beta/rubick/006/graphql
CORS Missing Allow Origin

XHROPTIONShttps://app.gc.subsquid.io/beta/rubick/006/graphql
CORS Missing Allow Origin

XHROPTIONShttps://app.gc.subsquid.io/beta/rubick/006/graphql
CORS Missing Allow Origin

XHROPTIONShttps://app.gc.subsquid.io/beta/rubick/006/graphql
CORS Missing Allow Origin

XHROPTIONShttps://app.gc.subsquid.io/beta/rubick/006/graphql
CORS Missing Allow Origin

XHROPTIONShttps://app.gc.subsquid.io/beta/rubick/006/graphql
CORS Missing Allow Origin

XHROPTIONShttps://app.gc.subsquid.io/beta/rubick/006/graphql
CORS Missing Allow Origin

XHROPTIONShttps://app.gc.subsquid.io/beta/rubick/006/graphql
CORS Missing Allow Origin

XHROPTIONShttps://app.gc.subsquid.io/beta/rubick/006/graphql
CORS Missing Allow Origin

XHROPTIONShttps://app.gc.subsquid.io/beta/rubick/006/graphql
CORS Missing Allow Origin

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 504.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 504.
7
Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 124
da68234.modern.js:1:2600410
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 504.
2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).
4
Error Network error: NetworkError when attempting to fetch resource. 2 da68234.modern.js:1:2692397
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 124
da68234.modern.js:1:2600410
Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 124
da68234.modern.js:1:2600410
Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 124
da68234.modern.js:1:2600410
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 92
da68234.modern.js:1:2600410
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 124
da68234.modern.js:1:2600410
Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 124
da68234.modern.js:1:2600410
Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 87
da68234.modern.js:1:2600410
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 504.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 124
```

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Seems like CORS issue on SubSquid? 
What's your URL to debug?
Can you still replicate it? Want to know if the error still occurs.
Is it happening on https://beta.kodadot.xyz as well? 

WFM https://kodadot.xyz/rmrk/u/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd

<img width="419" alt="image" src="https://user-images.githubusercontent.com/5887929/174474735-068f2950-61a0-4b8d-a5ad-81ed3d20bf46.png">

**Comment by cryptodamsky** [comment]
Apparently it works now on both beta and kodadot.xyz

Interesting 🗡️ 

Anyway, when i posted this, it was after replication, so not one time thing tho. Let’s see if it comes back

**Comment by cryptodamsky** [comment]
_Hello darkness my old friend_

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/92786519/175909516-bc470c3e-1194-4ce4-9df6-f98a5469a36f.png">



log

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 504.
15
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 6
[81b5587.modern.js:1:70664](https://kodadot.xyz/_nuxt/81b5587.modern.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

error Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 6
[da68234.modern.js:1:942157](https://kodadot.xyz/_nuxt/da68234.modern.js)
error Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 6
[da68234.modern.js:1:942157](https://kodadot.xyz/_nuxt/da68234.modern.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).
5
error Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 6
[da68234.modern.js:1:942157](https://kodadot.xyz/_nuxt/da68234.modern.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).
4
Error Network error: NetworkError when attempting to fetch resource. [da68234.modern.js:1:2692397](https://kodadot.xyz/_nuxt/da68234.modern.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).
4
Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 6
9 [da68234.modern.js:1:2600410](https://kodadot.xyz/_nuxt/da68234.modern.js)

​

**Comment by roiLeo** [comment]
Backend (graphql) endpoint crash

**Comment by cryptodamsky** [comment]
This is coming up now, same issue

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.
2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.
2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.
2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.
2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.
2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 6
[81b5587.modern.js:1:70664](https://kodadot.xyz/_nuxt/81b5587.modern.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

error Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 6
[da68234.modern.js:1:942157](https://kodadot.xyz/_nuxt/da68234.modern.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

error Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 6
[da68234.modern.js:1:942157](https://kodadot.xyz/_nuxt/da68234.modern.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

error Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 6
[da68234.modern.js:1:942157](https://kodadot.xyz/_nuxt/da68234.modern.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).
2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).
3
Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 6
3 [da68234.modern.js:1:2600410](https://kodadot.xyz/_nuxt/da68234.modern.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).

Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 6
4 [da68234.modern.js:1:2600410](https://kodadot.xyz/_nuxt/da68234.modern.js)
Error Network error: NetworkError when attempting to fetch resource. [da68234.modern.js:1:2692397](https://kodadot.xyz/_nuxt/da68234.modern.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.gc.subsquid.io/beta/rubick/006/graphql. (Reason: CORS request did not succeed). Status code: (null).
2
Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.
    NuxtJS 6

**Comment by petersopko** [comment]
this seems to be a recuring problem, not directly connected to the profile, but in general, subsquid / indexer keeps having crashes. I've added the `research` label, if anybody feels like digging around and finding out why does this keep happening, it would be great

**Comment by yangwao** [comment]
We've cut limits to 450 recently, observing if it would happen again.   
- #3287

**Comment by petersopko** [comment]
okay, just noticed this cors error is for rubick while I'm on bsx so perhaps this is more related to 
- https://github.com/kodadot/nft-gallery/issues/3364

**Comment by yangwao** [comment]
Meanwhile solved by removing queries.
Queries needs to have refactor  
- #3426
