### ISSUE TITLE
Not possible to send nfts - "Unable to Retrieve keypair"

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#3169]
### What happened?

Wanted to send nfts, got this pop-up

The issue is, i used to solve this problem by going to polkadot js apps and update metadata, but its updated already.

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

https://user-images.githubusercontent.com/92786519/174312867-ae684dce-eb59-4b0e-944a-69a3661df9cb.mov

 

### Relevant log output

```shell
[EXTENSION] No Addr 5GxhFnC6T83jQuBXyFKMKGnTspqbS24JTmbrgkDEkYP5feLT 1538a12.modern.js:1:468298
Error: Unable to retrieve keypair 'HUJv6Xy5V4fAYzyjx8QDE9U2R7qEgsUv9Sc5QVCELbaQmvw'
    NuxtJS 60
        y
        get
        getPair
        getPair
        O
        t
        r
        l
        promise callback*r
        l
        promise callback*r
        l
        o
        o
        f
        howAboutToExecute
        r
        l
        o
        o
        howAboutToExecute
        submit
        r
        l
        o
        o
        submit
        ne
        n
        _wrapper
        yo
        be
        wo
        x
        v
        ui
        _update
        r
        get
        Rn
        mount
        $mount
        $mount
        init
        v
        v
        k
        k
        ui
        _update
        r
        get
        run
        On
        he
        ce
        promise callback*ie
        he
        update
        update
3124e32.modern.js:1:6955

​
```

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
have you tried changing different RPC endpoints at https://kodadot.xyz/settings ?

<img width="224" alt="image" src="https://user-images.githubusercontent.com/5887929/174314437-a6dc8c56-5f6b-4f7a-a76d-aee8199906ff.png">

**Comment by cryptodamsky** [comment]
> have you tried changing different RPC endpoints at https://kodadot.xyz/settings ?
> 
> <img alt="image" width="224" src="https://user-images.githubusercontent.com/5887929/174314437-a6dc8c56-5f6b-4f7a-a76d-aee8199906ff.png">

That worked, but this is not long term solution? Cannot we automatize this in the background so end user doesn’t have to care? Or we cannot change user’s endpoints?

**Comment by yangwao** [comment]
Seems related, but fixed automatically, when I updated Chrome lol 

- #3127 
- #2607

**Comment by yangwao** [comment]
Fixed in 
- #3170 
- #3173
