### ISSUE TITLE
Minting on Basilisk yield CORS error

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3171]
Seems can't mint 🤔

<img width="671" alt="image" src="https://user-images.githubusercontent.com/5887929/174327390-1d11589a-3ef1-45a6-a65f-30063d161384.png">

**Comment by vikiival** [comment]
This is because indexer is down

**Comment by vikiival** [comment]
But create collection should not be dependable on indexer 🤔

**Comment by roiLeo** [comment]
can we postpone prod release? I find bsx stuff a bit whacky

**Comment by yangwao** [comment]
can someone wake up indexer?

<img src="https://media1.giphy.com/media/7pU22QtrGLbAk/giphy-downsized-medium.gif"/>

**Comment by yangwao** [comment]
> bit whacky

been looking for this word

**Comment by vikiival** [comment]
>  postpone prod release?

jj but still we need to do a working release until 20.06 to be eligible for the bounty

**Comment by yangwao** [comment]
sounds like 72 hours and counting 

<img src="https://media0.giphy.com/media/xT1XGLSb5E1VjIUw4E/giphy.gif"/>

**Comment by yangwao** [comment]
Meanwhile, there is a new bsx endpoint https://github.com/kodadot/nft-gallery/commit/ed3e26b72b16aef78ca433ef5f6fadc282ed5249

can someone try?

**Comment by vikiival** [comment]
> can someone try?

@petersopko is minting imo

**Comment by vikiival** [comment]
Looks like it's working again.

<img width="1680" alt="Screenshot 2022-06-19 at 12 11 51" src="https://user-images.githubusercontent.com/22471030/174476115-379b0784-afb4-4d89-99f0-277e8899689d.png">

Once peter mints we can close

**Comment by petersopko** [comment]
minting wfm on both nfts and collections

**Comment by yangwao** [comment]
It Seems collections show something, but in an explorer-like gallery, I see nothing?

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/5887929/174476882-a94ff1ad-ddb6-4855-9909-bd5ea8e7ae96.png">
