### ISSUE TITLE
Add support for Moonsama to endpoint chain selector

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3177]
### Ref 
- #3176 
- #3161

**Comment by zhengow** [comment]
https://github.com/subsquid/squid/blob/master/test/moonsama-erc721/.env
Hey, is this node URL for moonsama?
Need I help to PR for this [repo](https://github.com/kodadot/packages/blob/main/vuex-options/src/defaults/endpoints.ts)? 
@vikiival

**Comment by vikiival** [comment]
Imo this should have been issue for kodadot/packages

> Hey, is this node URL for moonsama?

Currently it's a draft

For vuex-options
- [ ] add new prefix (@yangwao can help to pickup)
- [ ] add new endpoint for moonriver
- [ ] add new indexer (feel free to leave there http://localhost:4350/graphql as a placeholder)

**Comment by yangwao** [comment]
> add new prefix (@yangwao can help to pickup)
"Moonsama" is would be ok

> add a new endpoint for moon river
I guess waiting for #3176 ?

**Comment by vikiival** [comment]
> I guess waiting for https://github.com/kodadot/nft-gallery/issues/3176 ?

`Moonriver !== moonsama`

**Comment by yangwao** [comment]
so we need one RPC for MoonRiver and one for querying MoonSama?

But for RO version #3176 should be enough or for what we need MoonRiver RPC now?
I guess for MoonRiver RPC we can use `wss://wss.api.moonriver.moonbeam.network` ?

**Comment by vikiival** [comment]
Every chain/impl requires
- prefix
- indexer
- RPC Node

> so we need one RPC for MoonRiver and one for querying MoonSama?

We need this URL `wss://wss.api.moonriver.moonbeam.network` registered as RPC node for moonsama

**Comment by zhengow** [comment]
> Imo this should have been issue for kodadot/packages
> 
> > Hey, is this node URL for moonsama?
> 
> Currently it's a draft
> 
> For vuex-options
> 
> * [ ]  add new prefix (@yangwao can help to pickup)
> * [ ]  add new RPC endpoint for moonriver
> * [ ]  add new indexer (feel free to leave there http://localhost:4350/graphql as a placeholder)

 [kodadot/packages#23](https://github.com/kodadot/packages/pull/23#issue-1276099698)

`
{
    info: 'moonriver',
    text: 'MoonRiver(Moonbeam)',
    value: 'wss://wss.api.moonriver.moonbeam.network'
  }
`
@yangwao How about this prefix?

**Comment by yangwao** [comment]
> @yangwao How about this prefix?

yup, let's go, works! :)

**Comment by zhengow** [comment]
> > @yangwao How about this prefix?
> 
> 
> 
> yup, let's go. I would remove part "MoonBeam" as that's a different para chain. 

😊ok.

@vikiival Could you help to approve my PR and publish a new npm package? 🥺

**Comment by vikiival** [comment]
> @vikiival Could you help to approve my https://github.com/kodadot/packages/pull/23 and publish a new npm package? 🥺

Did not get any ping there :/

**Comment by vikiival** [comment]
`+ @kodadot1/vuex-options@0.0.1-rc.9`

published

**Comment by zhengow** [comment]
I am wonder where can i find find
 node url for moonsama🤣

**Comment by vikiival** [comment]
> node url for moonsama

Moonsama = set of smart contracts on the top of Moonbeam :)
