### ISSUE TITLE
Show EVM based Moonsama NFTs in explorer

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3178]
Add basic fetching metadata and NFTs to be shown in explorer

### Ref 
- #3161

**Comment by vikiival** [comment]
Except the known bug of
- #3342 

it should be oki

**Comment by petersopko** [comment]
> Except the known bug of
> 
> * [Pagination and infinity scrolling is broken on Basilisk & Moonsama #3342](https://github.com/kodadot/nft-gallery/issues/3342)
> 
> it should be oki

yep, let's close this one and let @Jarsen136 do the magic 🪄 with infinite scroll
