### ISSUE TITLE
Add support to see holders chart for Moonsama based collections

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3180]
On the holders chart in collections, we would like to see holders' addresses for Moonsama based contracts

### Ref
- #3180

**Comment by vikiival** [comment]
Should be oki 

[Moonsama collection](https://beta.kodadot.xyz/moonsama/collection/0xb654611f84a8dc429ba3cb4fda9fad236c505a1a?tab=holders)

<img width="2003" alt="Screenshot 2022-07-09 at 11 40 06" src="https://user-images.githubusercontent.com/22471030/178100355-78989efe-7ed0-49d9-9a8f-35c8e70348c0.png">

**Comment by petersopko** [comment]
> Should be oki
> 
> [Moonsama collection](https://beta.kodadot.xyz/moonsama/collection/0xb654611f84a8dc429ba3cb4fda9fad236c505a1a?tab=holders)

wfm
