### ISSUE TITLE
Add support for History chart for collection on Moonsama

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3183]
In collections, we have a history chart table where users can see activity, would be nice to install their support for Moonsama

### Ref
- #3161

**Comment by vikiival** [comment]
[History OKI?](https://beta.kodadot.xyz/moonsama/collection/0xb654611f84a8dc429ba3cb4fda9fad236c505a1a?tab=history)

<img width="2226" alt="Screenshot 2022-07-09 at 12 03 09" src="https://user-images.githubusercontent.com/22471030/178101081-43e95e9b-18e1-4d48-a438-3f3909553acb.png">

**Comment by petersopko** [comment]
> [History OKI?](https://beta.kodadot.xyz/moonsama/collection/0xb654611f84a8dc429ba3cb4fda9fad236c505a1a?tab=history)

wfm
