### ISSUE TITLE
wrong redirect to rmrk

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3187]
clicking on collection in profile detail redirects to rmrk collection (should be bsx)
![image](https://user-images.githubusercontent.com/73316633/174476704-916be171-376d-4611-9492-6804aa67eefe.png)
![image](https://user-images.githubusercontent.com/73316633/174476749-7e649115-5aa7-4fb3-adf4-4df50892edda.png)

**Comment by yangwao** [comment]
@vikiival why blocked?

**Comment by petersopko** [comment]
> @vikiival why blocked?

it's fixed on branch, viki blocked so nobody takes it
