### ISSUE TITLE
Explorer on BSX gallery don't show any items

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3188]
It Seems collections show something, but in an explorer-like gallery, I see nothing?

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/5887929/174476882-a94ff1ad-ddb6-4855-9909-bd5ea8e7ae96.png">

Collections seems ok 

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/5887929/174476956-9ceda1db-651e-4421-ac82-c8806f8f4399.png">

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/3171#issuecomment-1159684521_

**Comment by vikiival** [comment]
Fixed along with @petersopko
