### ISSUE TITLE
Can't list NFT on BSX 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3189]
After entering price 99000BSX can't list it. 

Seems type issue?

https://beta.kodadot.xyz/bsx/gallery/855280514-1

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/5887929/174477215-e5b00069-9b89-4531-bd6e-2fc9d16e1eba.png">

**Comment by vikiival** [comment]
Still the same err as #3186 
:)

**Comment by vikiival** [comment]
![Screenshot 2022-06-19 at 13 39 47](https://user-images.githubusercontent.com/22471030/174479023-b0678cae-b0f0-4490-8fc5-9fbafbad869a.png)

**Comment by petersopko** [comment]
fixed here: 
- https://github.com/kodadot/nft-gallery/pull/3194
