### ISSUE TITLE
Show categories of NFTs on landing

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#319]
Would be nice to peak on new users and offer creators to give them the spotlight on their recent mints.
Thus showing mint on landing would be really appealing. 
Inspired by https://makersplace.com/

Featured Creators - those who are reputable, 1k+ on twitter
Top Collectors - sorted by highest price, their recent collects
Popular Creations - most emojis 
Featured creations -

**Comment by vikiival** [comment]
I think it would be nice to have separated landing from app

**Comment by yangwao** [comment]
kodadot.xyz -- writings, /carbonless, /sustainibility 
nft.kodadot.xyz -- default to gallery view and rest? 

Right now it's jointed deploy, but sure, we can split it.

**Comment by XyloDrone** [comment]
![Screenshot 2021-05-18 at 23 29 06](https://user-images.githubusercontent.com/84407059/118731336-e5e71600-b830-11eb-8be6-821c60b0cbb6.png)

**Comment by XyloDrone** [comment]
Featured creators to be decided via community votes. I would reccommend having the main banner switch between: voted featured artist, most popular and most sales. 

Top and popular added in buttons bellow the search bar as options. 

![Gallery – NEW - Artworks](https://user-images.githubusercontent.com/84407059/118870388-69ab0c00-b8de-11eb-82f7-dd85b45ed94e.png)

**Comment by yangwao** [comment]
#455 related?

**Comment by XyloDrone** [comment]
Shall we add this to landing or make a separate page? 
I also think it is related to this issue: #145 , correct me if I am wrong
