### ISSUE TITLE
After minting collection on BSX doesn't show up proper name

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3190]
Seems we don't store metadata of collection?

<img width="533" alt="image" src="https://user-images.githubusercontent.com/5887929/174477540-06ab4187-c0dc-4b75-b655-7df29dd09f25.png">

Seems can replicate

<img width="484" alt="image" src="https://user-images.githubusercontent.com/5887929/174477785-0220633b-9095-4a97-95e9-d5a6fae0da63.png">

Seems metadata doesn't fetch either 

<img width="607" alt="image" src="https://user-images.githubusercontent.com/5887929/174487916-d7b47640-8119-4a22-ae23-40310c17b5ec.png">

**Comment by vikiival** [comment]
<img width="452" alt="Screenshot 2022-06-19 at 13 33 27" src="https://user-images.githubusercontent.com/22471030/174478842-549450f5-14e6-4359-804a-fe5e00920a5e.png">

**Comment by vikiival** [comment]
this will be fixed by:
- [ ] simple impl of Promise race in minimark
- [ ] integrated into KodaDot

**Comment by vikiival** [comment]
LALA: 
61fb098f3e4321866b6e792a41aa827e4d5ef1b1

**Comment by yangwao** [comment]
> LALA:
> [61fb098](https://github.com/kodadot/nft-gallery/commit/61fb098f3e4321866b6e792a41aa827e4d5ef1b1)

let's do PR

**Comment by vikiival** [comment]
#3201
