### ISSUE TITLE
Can't add NFT to collection on BSX

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3191]
Seems minting of collections somehow works, but minting of NFT is not possible?

Apparently, #3171 @petersopko somehow managed to mint

<img width="639" alt="image" src="https://user-images.githubusercontent.com/5887929/174477623-4416d3a1-b7a0-4053-96fc-03b619e96b43.png">

**Comment by vikiival** [comment]
:) #3186
