### ISSUE TITLE
Add possibility to remove collection

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3206]
Currently, empty collections don't show up in the explorer. However, in order to delete a collection (`destroy class` from the initial implementation requirements, ref. #660) it must be empty.

Catch 22 with collections, I'm thinking, adding option to show user his/her empty collections and add option to delete them. This could be done under profile tab Collections with simple checkbox such as `Show empty collections`

/edit with @roiLeo idea:

can't we create a /bsx/admin like for rmrk? Is this page used for that kind of stuff?

**Comment by petersopko** [comment]
as @roiLeo mentioned in 
- #3347 

the trash button only works if you have link to empty collection, example here:
https://kodadot.xyz/bsx/collection/845595670

![image](https://user-images.githubusercontent.com/73316633/177996089-e2868817-826c-4b1e-8b6c-0f332bbfe14f.png)

**Comment by roiLeo** [comment]
If I understand, the goal here is to add a feature (on /admin ?) when creator decide to burn collection it will burn all nfts from this collection & burn the collection.

**Comment by vikiival** [comment]
> If I understand, the goal here is to add a feature

Yup, somehow in the UX friendly manner

**Comment by roiLeo** [comment]
### Step By Step

- check that you own all NFTs present in collection (in order to enable trash button)
- query non_burned NFTs & fetch their id
- loop args & finish with `destroy_collection`
```ts
const api = await this.useApi()
const cb = api.tx.utility.batchAll
const args = [
  api.tx.nft.burn(collectionId, non_burnedNftId1),
  api.tx.nft.burn(collectionId, non_burnedNftId2),
  api.tx.nft.burn(collectionId, non_burnedNftId3),
  ...
  api.tx.nft.destroyCollection(collectionId),
]
```
- send TX
- profit.

**Comment by vikiival** [comment]
Yes!
