### ISSUE TITLE
Notify artist when sale on craft was made

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#321]
Would be nice whenever artist put creation on sale and someone will buy it, it could be notified.
We can leverage here [textile mail service](https://docs.textile.io/users/) to send for example email
We can leverage desktop notification for example
We can have telegram bot which would send webhook.
@vikiival > webhook can sent you a dm on twitter if you have on-identity

**Comment by XyloDrone** [comment]
Notification would be ideal as every time the user logs in they can see it. 
Maybe people can also choose if they want email or telegram?

**Comment by yangwao** [comment]
Maybe we can hookit up with kodadotbot.
But yeah at least have something to hand off them in-app would be pretty fair at least!

Email has downside that people could be hijacked for phising once they learned that we sending emails.

Textile mailbox would work on this?
Once need still change pointer till where user seen it's own activity.

**Comment by XyloDrone** [comment]
Any follow up on this? Can we link the notifications via email?

**Comment by vikiival** [comment]
We can make simple lambda and if creator has mail set through on-chain identity we can send a mail

**Comment by XyloDrone** [comment]
Sounds like a plan

**Comment by yangwao** [comment]
@XyloDrone  partially would be good to have this one as a start https://github.com/kodadot/nft-gallery/issues/1285

**Comment by JustLuuuu** [comment]
we have notifications now
