### ISSUE TITLE
Search Api failing for statemine and westmint 

### ISSUE THREAD

**Issue by prachi00** [kodadot/nft-gallery#3211]
### What happened?

CORS error and 400 error
<img width="675" alt="Screen Shot 2022-06-19 at 10 52 20 PM" src="https://user-images.githubusercontent.com/39299315/174533966-c3f4b98e-5fb7-4388-a660-f04b5577d3ae.png">

https://www.loom.com/share/99024ac40ef446d6be48078da2360824

### Please reproduce in steps

Go to ... Click on .... See error

### Expected Behavior

I've expected ...

### Are you logged in?

Yes

### Screenshots

Paste from your clipboard or upload screenshots/video

### Payment link for reward

https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
![what-year-is-it-robin-williams](https://github.com/kodadot/nft-gallery/assets/9987732/39e4279e-8295-465f-b0fa-464aa3e8d0ae)

meanwhile https://github.com/kodadot/stick
