### ISSUE TITLE
Fractional mass mints

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#322]
Right now we don't have the ability to mint more than one NFT. 
I guess introducing mass mint would be really helpful for those who are keen mint more NFTs
Probably we could add how many times mint the same token in the particular collection?

**Comment by vikiival** [comment]
This is a part of single mint task.
Xylodrome added so called “Editions” field which solve this issue :)

**Comment by yangwao** [comment]
There fore I close this
