### ISSUE TITLE
Glitch on make offer in basilisk

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3220]
Sometimes I can't make an offer 🤔

![image](https://user-images.githubusercontent.com/5887929/174584539-3630cc13-eeb8-4183-aef4-6ab05ae14d3b.png)

**Comment by vikiival** [comment]
It's the case when you have SOME KSM intstance running in the background

**Comment by yangwao** [comment]
> SOME KSM intstance running in the background

seems switching between chains is making this
