### ISSUE TITLE
Rare pokemon at Transfer

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3221]
I sense we've already fixed this buut, 
here is the case it doesn't work at 
Seems when I do conversion from other than BSX address it appears?

https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU&usdamount=52930000000

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/5887929/174587124-16242cd6-06fa-4de7-b4f9-72a3e776636b.png">

at here it worked https://beta.kodadot.xyz/transfer/?target=bXj1N8PuXSaZAR3TdMxmXAce32FhZpW3qy8NSj9djB1SAPhz7&usdamount=0

**Comment by petersopko** [comment]
tested right now with multiple kusama / moonsama addresses and it worked without a problem
