### ISSUE TITLE
GraphQL error: pgbouncer cannot connect to server

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#3228]
#### Step to reproduce
- go to beta.kodadot.xyz
- rmrk chain
- go to explorer
- infinite loader
- profit

`Uncaught (in promise) Error: GraphQL error: pgbouncer cannot connect to server`

**Comment by petersopko** [comment]
same problem on kodadot.xyz / local instance, seems that we need @vikiival here 🥺

**Comment by vikiival** [comment]
Just spotted there
