### ISSUE TITLE
Sunset rubick 004

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3232]
Just please check if we are not using 004 somewhere

**Comment by roiLeo** [comment]
We don't use it on kodadot anymore, but I'm using it from [here](https://app.subsquid.io/aquarium/rubick)

**Comment by vikiival** [comment]
> We don't use it on kodadot anymore, but I'm using it from [here](https://app.subsquid.io/aquarium/rubick)

It will be replaced by 005 by default
