### ISSUE TITLE
Minting collection doesn't work

### ISSUE THREAD

**Issue by DeluneClaire** [kodadot/nft-gallery#3235]
### What happened?

I wanted to mint collection, but it takes so much time, and it doesn't work in the end.

### Please reproduce in steps

-

### Expected Behavior

-

### What browsers do you see the problem on?

Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

https://user-images.githubusercontent.com/104791453/174835694-9b8b03c4-d5cf-46ba-83b1-3491771f41bc.mov

### Relevant log output

```shell
Uncaught TypeError: e.error.toNumber is not a function
    NuxtJS 105
        findMetaError
        onTxError
        v
        y
        l
        setTimeout handler*xg/</l<
        next
        _next
        next
        En
        _next
        next
        _next
        next
        En
        _next
        next
        r
        _next
        next
        _next
        next
        sn
        _next
        next
        next
        zd
        next
        next
        _next
        next
        Nf
        _next
        next
        _next
        next
        nd
        _next
        next
        f
        _next
        next
        r
        _next
        next
        next
        zd
        next
        next
        _next
        next
        c
        promise callback*_createMethodSend/c</</<
        _trySubscribe
        subscribe
        zd
        subscribe
        connect
        Gf
        _trySubscribe
        subscribe
        zd
        subscribe
        ql
        _trySubscribe
        subscribe
        fl
        subscribe
        wd
        _next
        next
        sn
        _next
        next
        Zt
        promise callback*Zt/<
        _trySubscribe
        subscribe
        mt
        subscribe
        sn
        Qt
        subscribe
        mt
        subscribe
        wd
        Yl
        subscribe
        mt
        subscribe
        ql
        _trySubscribe
        subscribe
        fl
        subscribe
        f
        fd
        f
        ld
        fd
        ld
        _trySubscribe
        subscribe
        fl
        subscribe
```

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduc

**Comment by yangwao** [comment]
have you tried minting on https://beta.kodadot.xyz ? 
Maybe it's fixed there, but I see first time this error 🤔

**Comment by vikiival** [comment]
However you find really good edge case #3244

**Comment by vikiival** [comment]
>  thought it would write something like not enough KSM...

Yeah that's the goal of issue mentioned above.

**Comment by yangwao** [comment]
> Yeah, that's true. I was trying to see if it would work, but I thought it would write something like not enough KSM...

We have this somewhere that should work normally 😏🫣

**Comment by vikiival** [comment]
> should work normally 

DNFTL.

**Comment by yangwao** [comment]
> DNFTL

<img src="https://media2.giphy.com/media/3o6ozls6Glf1v0KIAE/giphy.gif"/>

**Comment by vikiival** [comment]
Definitely normal

**Comment by DeluneClaire** [comment]
🤣

**Comment by yangwao** [comment]
related with ?
- #3384

**Comment by yangwao** [comment]
@DeluneClaire is it working for you already on Basilisk?

**Comment by petersopko** [comment]
this already works, the only problem left with minting on basilisk is talisman, ref:
- #4017
