### ISSUE TITLE
Update KodaDot to Polkadot v8

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3244]
### Is your feature request related to a problem?

We are currently running v7 of polkadot-api

### Describe the solution you would like

I would like to see polkadot v8

There is already a branch for that `polkadot-v8` so feel free to start there.

If you need to update any internal package please ping @vikiival

**Comment by yangwao** [comment]
What amount of work is there? 
Should we put it into the upcoming release or can wait?

**Comment by vikiival** [comment]
> can wait?

yes, this can wait.

**Comment by roiLeo** [comment]
https://github.com/kodadot/packages/pull/77 might be related

**Comment by vikiival** [comment]
Continue in #4499
