### ISSUE TITLE
Can't connect to RPC in Transfer for BSX

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3247]
Once I signed the transaction for submission I get some errors on BSX in the Transfer 

<img width="443" alt="image" src="https://user-images.githubusercontent.com/5887929/175077295-3279d93f-852d-4dcb-85c5-c9bcb0a133b3.png">

**Comment by yangwao** [comment]
okay seems snackiee is off the field again 🤔
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbasilisk-kodadot.hydration.cloud#/explorer
<img width="238" alt="image" src="https://user-images.githubusercontent.com/5887929/175078651-2b90931c-6fa3-46d8-95e5-3eb52b56ba90.png">

**Comment by vikiival** [comment]
Maybe 🐍 has 🏖️ mode

![45033941-9755483-A_massive_snake_became_stranded_at_Wild_Cattle_Beach_in_Tannum_S-a-5_1625449020079](https://user-images.githubusercontent.com/22471030/175081826-775ec972-260d-4745-a4eb-abae920c9a83.jpg)
