### ISSUE TITLE
Show royalties under the price in basilisk

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3250]
### Is your feature request related to a problem?

Currently afaik we do not show how much percent of the price are royalties.

### Describe the solution you would like

It would be good to show them under the price

### Describe alternatives you have considered

~

### Screeenshots

I added a couple of screenshots from the past :)

![1_i2tmRmrqqWVov8HiDUECVw](https://user-images.githubusercontent.com/22471030/175268090-a9d13e17-6de9-4328-aa72-d2bc1eb146c2.png)

![1_uow2nQEO4vNG4FogVXPwuw](https://user-images.githubusercontent.com/22471030/175268114-42d61879-d233-4b6a-a3f5-220efabc4262.png)

**Comment by kkukelka** [comment]
👋

**Comment by kkukelka** [comment]
@vikiival 
<img width="803" alt="Screenshot 2022-06-23 at 16 25 27" src="https://user-images.githubusercontent.com/17953978/175323108-9348e690-72de-4540-a7ba-5d1eaff75d3b.png">
is this the interaction to look out for?

**Comment by prachi00** [comment]
pay 100 usd
