### ISSUE TITLE
Fetching fresh new mints on Basilisk

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3253]
Seems Pinata isn't an issue here, happening same on CF ipfs gw :/ 

<img width="604" alt="image" src="https://user-images.githubusercontent.com/5887929/175300930-ba7f6749-3fd6-4085-b4c9-d3d419473cb3.png">

### Ref
- https://github.com/kodadot/nft-gallery/issues/3212 seems same issue

**Comment by petersopko** [comment]
this one could be related
- https://github.com/kodadot/nft-gallery/issues/3291

**Comment by yangwao** [comment]
should be fixed 
- #3358
