### ISSUE TITLE
Showing KSM and BSX at once

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3263]
I recall being talking about this and someone said this should not happen after the recent fix?

1. Opened https://beta.kodadot.xyz
2. switched to BSX
3. went to the gallery 
4. clicked item
5. see price as in KSM

<img width="632" alt="image" src="https://user-images.githubusercontent.com/5887929/175531418-8b1995ed-7d19-4f86-bbbd-0e3ab54bea8c.png">

**Comment by kkukelka** [comment]
@yangwao can you link the specific nft it occurred with? cannot reproduce

**Comment by yangwao** [comment]
It was this one but can't replicate it tho :| 
I guess it's something to do with chain switcher, when some part of client things it's still on KSM but it is not :)

https://beta.kodadot.xyz/bsx/gallery/2444376227-1

**Comment by prachi00** [comment]
<img width="1473" alt="Screen Shot 2022-06-24 at 9 54 36 AM" src="https://user-images.githubusercontent.com/39299315/175607267-9acf5703-5eff-4fc9-bf2e-f7e7d743ad2b.png">
I see KSM too
