### ISSUE TITLE
Infinite api calls being made 

### ISSUE THREAD

**Issue by prachi00** [kodadot/nft-gallery#3269]
### What happened?

[A bug happened!]
(https://nft.kodadot.xyz/rmrk/gallery/10249720-466e8b6338599eaf1e-GAVCUBE-GAV_CUBE_101-0000000000000101?page=1)
infinite calls being made to `nftByIdMinimal` query 

https://www.loom.com/share/9a217118fa4b426aaac5ef4a7cd55cf9

### Please reproduce in steps

Go to ... Click on .... See error

### Expected Behavior

I've expected ...

maybe implement caching for this?

### Screenshots

Paste from your clipboard or upload screenshots/video

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kkukelka** [comment]
Heh, I noticed that too a while ago. But @vikiival explained to me that we need this in order to prevent double spending on an NFT. That's why the call also only fetches very few properties.

**Comment by vikiival** [comment]
Yup, new fire-squid will have subscription :) 
for now we need to poll minimal data every couple of secs :)
