### ISSUE TITLE
Freshly minted collection doesn't show up

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3291]
After creating new collection, I'm being redirected to https://beta.kodadot.xyz/bsx/create where I can mint new NFT, however, I don't see the created collection in the dropdown select. After some time and after I refresh the page, collection ID shows up in the dropdown (number) but not the name of the collection. 
![image](https://user-images.githubusercontent.com/73316633/176089723-69ae62e7-b56a-44f9-acb5-77915ad26054.png)

2 problems here: 
-  It's possible this will always take time regardless, but if that's the case, I'd suggest showing up message which will let the user know, to refresh in 5 mins or so. 
- 10 minutes after the mint, I can still see only the ID of the collection (number) not the name I've selected before

**Comment by yangwao** [comment]
The collection name is being shown up already, yet it still takes some time for a fresh collection is being shown.

**Comment by yangwao** [comment]
Explainer will be added 
- https://github.com/kodadot/nft-gallery/issues/3333

The fix could be adding 
- fetching for a user recent new collections through indexer as right now we are doing it on a fresh load 
- fetch from the chain by address recent collections from last blocks by user-id

**Comment by petersopko** [comment]
ok, the explainer was added and this also doesn't seem to be an issue after I've tested this a bunch of times in the past couple of days, idk whether you want to move forward with:
> The fix could be adding

> fetching for a user recent new collections through indexer as right now we are doing it on a fresh load
> fetch from the chain by address recent collections from last blocks by user-id

But in case yes, maybe we should include this as part of our refactor, wdyt @yangwao 

![image](https://user-images.githubusercontent.com/73316633/183417485-98160513-7049-40ff-9007-f8d5d1d411db.png)

**Comment by petersopko** [comment]
just tested this couple of times, we have both the message included and also, I just saw the collection show up instantly.
