### ISSUE TITLE
Search in gallery BSX

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3293]
updated:

- [x] searchbar queries + suggestions 
- https://github.com/kodadot/nft-gallery/pull/3491
- https://github.com/kodadot/nft-gallery/issues/3504
- [x] range slider transforming into input fields here:
- https://github.com/kodadot/nft-gallery/issues/3461
- [x] ~passion feed results in neverending loader, should be temporarily resolved by this:~
- ~https://github.com/kodadot/nft-gallery/pull/3424~
- [x] ~buy now button doesn't seem to be altering search results at all~
- [x] ~sorting broken~:
- ~https://github.com/kodadot/nft-gallery/issues/3266~
- ~https://github.com/kodadot/nft-gallery/pull/3442~

**Comment by roiLeo** [comment]
👋 
I'll be fixing sort & buy now

**Comment by petersopko** [comment]
done
