### ISSUE TITLE
Basilisk Subscan link

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3294]
Basilisk will have Subscan, rather just hide it for now and once we will run on official testnets it can be add again.

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/3280#issuecomment-1166582210_

// Once Basilisk becomes available on Subscan, let's add the functionality we've hidden in 
- #3280

**Comment by petersopko** [comment]
👀 
![image](https://user-images.githubusercontent.com/73316633/178144067-af359ed0-2f54-49b9-b9fd-2fb8d0f03233.png)

**Comment by petersopko** [comment]
hiding / altering more stuff here until we have subscan/bsx
- https://github.com/kodadot/nft-gallery/pull/3406

**Comment by yangwao** [comment]
Seems we just need to figure out for live network rather for sandbox tho https://basilisk.subscan.io/
