### ISSUE TITLE
[ERR] AxiosError: Request failed with status code 500

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#3295]
### What happened?

When creating a new collection, the action ends with an error message:
**[ERR] AxiosError: Request failed with status code 500**

### Please reproduce in steps

Go to ... Click on .... See error

### Expected Behavior

I've expected ...

### Screenshots

https://user-images.githubusercontent.com/81104034/176128546-82837eff-4643-4c0d-8f5a-c4dbe8430740.mp4

### Payment link for reward

https://kodadot.xyz/transfer?target=FqCJeGcPidYSsvvmT17fHVaYdE2nXMYgPsBn3CP9gugvZR5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
Same on `beta.kodadot.xyz`, look like pinning endpoint is in error
<img width="543" alt="Capture d’écran 2022-06-28 à 10 19 49 AM" src="https://user-images.githubusercontent.com/9987732/176130391-fe3fe4dc-3fed-4119-aea6-90f7d26a3dbb.png">

**Comment by jkdizajn** [comment]
> Same on `beta.kodadot.xyz`, look like pinning endpoint is in error <img alt="Capture d’écran 2022-06-28 à 10 19 49 AM" width="543" src="https://user-images.githubusercontent.com/9987732/176130391-fe3fe4dc-3fed-4119-aea6-90f7d26a3dbb.png">

yes, I confirm

**Comment by vikiival** [comment]
Hey,
Our pinning service does not work today. 

![image](https://user-images.githubusercontent.com/22471030/176173097-29cd7505-3bf0-456a-929f-e934f5f24a4e.png)

**Comment by vikiival** [comment]
@jkdizajn looks like Estuary is working again!
