### ISSUE TITLE
Summer Refactor 

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3311]
As discussed in multiple places here, we got to a point where our codebase deserves serious refactor. Except for making our life easier, this would be great help for newcomers, since some things became quite messy/chaotic over the months of remote/async development.

following up from discussion here: 

- https://github.com/kodadot/nft-gallery/discussions/3068

When it comes to the folder structure, I prefer the way @kkukelka described his approach in the [discussion](https://github.com/kodadot/nft-gallery/discussions/3068#discussioncomment-2857979):
> I like to divide stuff in either context-specific or functionality-specific folders
> e.g. for context-specific:

```
/payment
/payment/CheckoutComponent.vue
/payment/BillingComponent.vue
```
- [ ] #3883
- [ ] #3299
- [ ] #3308
- [ ] #3310
- [x] #3309
- [x] #3355
- [x] #3379
- [x] #3579
- [x] #1348
- [x] #3706
- [x] #3774
- [x] #3865
- [x] #3772
- [x] #3714 
- [x] #3706
- [ ] #3868
- [x] #3360
- [x] #3747 
- [x] #3749
- [x] #3773

**Comment by petersopko** [comment]
@kkukelka @roiLeo @vikiival I've moved the ideas from discussion about this into more actionable version, please feel free to add / modify whatever you find valuable

**Comment by vikiival** [comment]
So far short list

```md

# Components we need

## Shared
- Auth
- Avatar
- Identity
- CollapseWrapper
- CommonTable
- LabeledText - (label, slot)

## Form
- DropUpload
- SubmitButton
- Collection Select
- Basic
  - Input
  - Switch
  - CheckBoxButton
  - NumberInput
  - Slider
- BalanceInput
  - Simple
  - Multicurrency
- AddressInput
  - Simple
  - Strict
  - WithHint
- AttributeTagInput

## View
- Money (with currency, decimal places)
- AccountBalance
- Titles (h1, h2, h3, h4, h5, h6)
- GalleryCard
- Percentage
- Image (rounded, square)


## Profile Specific
- Stats
  - Stats Column (label, slot)
- Web3 Social - sub.id, subscan, polkascan
- Sharing - donate, QR, link, share


## Lists
- GalleryCardList

## Search / Sort / Filter
- Pagination
- Buy Now
- SortDropdown
- Go to random
- ChangeLayout
- SearchInput

## Table
- Pagination (backend pagination)
- Cells
  - Type (BUY, SEND...)
  - Link (detail,) (just icon)
  - External
  - Money
  - Percentage
  - Identity?
  - Common - Just show it as text
  - RelativeDate - (9 months ago)
- WithDetail
  - list
  - gallery cards

## Charts

## Galery Item
- Navigation (through collection)
- Image
- ImageResize (fill, full-screen, grid)
- Emote?
- Title
- Description
- Attributes


### Carousel - Landing, Visited NFTs
- Image
- Title
- Money
- Creator
- current Owner

### Notification

## Chain Specific

### RMRK

### BSX

#### Offers

# Utils


```

**Comment by prachi00** [comment]
@vikiival dont we already have some of these components that is shared? like `Identity`

**Comment by vikiival** [comment]
> @vikiival dont we already have some of these components that is shared? like Identity

Yes, we have component called `Identity` but it is doing too much logic. & has more than 200 lines of code

**Comment by vikiival** [comment]
Just found out there is a new version of [Vue 2.7](https://github.com/vuejs/vue/blob/main/CHANGELOG.md#270-2022-07-01) that we can implement before full Vue3

Only blocking
- https://github.com/buefy/buefy/issues/3768

**Comment by prachi00** [comment]
> Just found out there is a new version of [Vue 2.7](https://github.com/vuejs/vue/blob/main/CHANGELOG.md#270-2022-07-01) that we can implement before full Vue3
> 
> Only blocking
> 
> * [Update to Vue 2.7 buefy/buefy#3768](https://github.com/buefy/buefy/issues/3768)

this is not a blocker then right? If not, we can follow this https://blog.vuejs.org/posts/vue-2-7-naruto.html
to upgrade to 2.7

**Comment by kkukelka** [comment]
> Just found out there is a new version of [Vue 2.7](https://github.com/vuejs/vue/blob/main/CHANGELOG.md#270-2022-07-01) that we can implement before full Vue3
> 
> Only blocking
> 
> * [Update to Vue 2.7 buefy/buefy#3768](https://github.com/buefy/buefy/issues/3768)

i've updated vue to 2.7.5 in here https://github.com/kodadot/nft-gallery/pull/3689
buefy seems to work nonetheless

**Comment by preschian** [comment]
some questions:
1. it's time to remove `nuxt-property-decorator` and use [`vue composition API`](https://vuejs.org/guide/extras/composition-api-faq.html) instead?
2. do we need [storybook](https://storybook.js.org/) to manage and preview our components?

**Comment by vikiival** [comment]
> it's time to remove nuxt-property-decorator and use [vue composition API](https://vuejs.org/guide/extras/composition-api-faq.html) instead?

Yup, best time is to write new components in composition api and also refactor some.

**Comment by preschian** [comment]
ok then, I will start with some components on the landing page https://github.com/kodadot/nft-gallery/issues/3714

**Comment by vikiival** [comment]
@preschian 
https://github.com/histoire-dev/histoire

**Comment by preschian** [comment]
> @preschian [histoire-dev/histoire](https://github.com/histoire-dev/histoire)

looks cool, thanks, will try to experiment with it later 👍
