### ISSUE TITLE
CORS in rubick 006 

### ISSUE THREAD

**Issue by zhengow** [kodadot/nft-gallery#3322]
### What happened?

A bug happened!
when query data from `https://app.gc.subsquid.io/beta/rubick/006/graphql`, it failed with `CORS`

### Please reproduce in steps

Go to ... Click on .... See error

### Expected Behavior

I've expected ...

### At which address did you encounter bug?

beta.kodadot.xyz

### Screenshots

Paste from your clipboard or upload screenshots/video
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/38389586/177024792-af427167-aeea-4285-9057-dff2c20b123e.png">
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/38389586/177024800-49470d6a-3d94-4824-bc8c-3aca6c98b975.png">

### Payment link for reward

https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petersopko** [comment]
connected to 
- https://github.com/kodadot/nft-gallery/issues/3287

same problem as usual, it was breaking for me as well. Just noticed, that after I opened [playground](https://app.gc.subsquid.io/beta/rubick/006/graphql) as usual, problem disappear even on https://beta.kodadot.xyz? maybe complete coincidence. @vikiival

**Comment by vikiival** [comment]
There are big queries which are still big and node simply goes out of the memory. 
- kodadot/rubick#97

**Comment by zhengow** [comment]
got it
