### ISSUE TITLE
Differences between amount of items in collection

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3337]
Seems the collection is supposed to have two items, but see only one here 

https://beta.kodadot.xyz/bsx/collection/2526524581?tab=items&page=1

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/5887929/177525321-79e15ab5-1c51-4b6a-94f4-425eb6d5dd14.png">

and at the same time I see two items at create dialog

<img width="489" alt="image" src="https://user-images.githubusercontent.com/5887929/177525481-f92cc96f-060c-41d7-869a-b2d3e15f44c0.png">

**Comment by yangwao** [comment]
Might be related with #3334 on subsquid level

**Comment by petersopko** [comment]
I cannot reproduce this after we introduced the new nft.storage, if it's the same for you, maybe let's close this one
