### ISSUE TITLE
Request: new favicon

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#3345]
![Capture d’écran 2022-07-06 à 1 56 40 PM](https://user-images.githubusercontent.com/9987732/177551238-c6d59972-52cf-450f-86f2-282c13adbb20.png)

Can we update kodadot favicon with something new (& fancy)?

#### multiple proposals
- Transparent bg

- Black logo on white bg
![K_black](https://user-images.githubusercontent.com/9987732/177961009-11979ea3-86f6-4439-94d8-5bc1165cc53a.png)

- White logo on black bg
![K_black(2)](https://user-images.githubusercontent.com/9987732/177960899-cdc45de5-b52c-4afc-87f4-823a0cb0d9d2.png)

- Bordered bg 
- Rounded bg
- Github style

Bonus: manifest & multiple size

Let me know wich version you would like to see

**Comment by prachi00** [comment]
transparent would look nice i think

**Comment by yangwao** [comment]
>  White logo on black bg

let's try go with this

**Comment by roiLeo** [comment]
![01-favicon](https://user-images.githubusercontent.com/9987732/184915172-452258a1-bf24-4e52-a17b-3e04606b865c.png)

![03-android-icon](https://user-images.githubusercontent.com/9987732/184915154-85b323d7-ff2f-480a-87d1-efca7305aad6.png)

**Comment by roiLeo** [comment]
closed in #3757

**Comment by roiLeo** [comment]
Tried my best in #3757, maybe i'll give another try

**Comment by yangwao** [comment]
Yes continue to
- https://github.com/kodadot/nft-gallery/issues/6784
