### ISSUE TITLE
royalty event missing?

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3349]
Upon testing buying listed NFT with royalties, I don't see the event PAY_ROYALTY in history component of collection or in snek playground. This is the mentioned NFT https://beta.kodadot.xyz/bsx/gallery/235937109-8
It had royalty set, it has changed user and there was no royalty paid in the end. Not sure if I'm missing something here, but I was expecting to see royalty paid everytime NFT changes owner? 

![image](https://user-images.githubusercontent.com/73316633/177567247-6b40379b-bdbc-4656-ae7c-9f96ecafcaaa.png)

**Comment by yangwao** [comment]
Hey if anyone can check on this one? 
I've raised a bounty for this one :)

**Comment by roiLeo** [comment]
🚶‍♂️ 👋

**Comment by roiLeo** [comment]
Oops my bad it's more of a Backend issue reference https://github.com/kodadot/snek/issues/36

**Comment by petersopko** [comment]
@KngZhi you wanna take a look? You have some experience with indexers 😄

**Comment by KngZhi** [comment]
😄 okay, I will give it shot.

**Comment by KngZhi** [comment]
@petersopko it looks like `PAY_ROYALTY` is back. on my localhost graphql

![Screen Shot 2022-07-25 at 12 15 07 PM](https://user-images.githubusercontent.com/11361147/180697751-963e432f-df06-4286-8753-bec6ee6d3a8a.png)

**Comment by petersopko** [comment]
hmm, I don't see much from the screenshot. The point of PAY_ROYALTY event is, that there should be royalty paid based on the original percentage set upon minting of NFT. Therefore, every time NFT is sold, there's royalties paid to the original creator. Can you confirm / verify that is the current behavior in KodaDot?

**Comment by petersopko** [comment]
Still in dire need of bughunt and fix here:

```graphql
query MyQuery {
  nftEntities(where: {id_eq: "2916213696-5"}) {
    events {
      interaction
      timestamp
    }
    price
    name
  }
}
```

above query is returning 0 PAY_ROYALTY events, even though, there was a set royalty and I have purchased it

![image](https://user-images.githubusercontent.com/73316633/181228676-ea7b7369-6aeb-4b4c-8e3c-5ac5bd028cea.png)
![image](https://user-images.githubusercontent.com/73316633/181228726-ee2cd85e-eefa-480d-ad47-e0c7a00e7182.png)


However, when looking specifically for `PAY_ROYALTY` interactions (events), I have found a bunch:

```graphql
query MyQuery {
  events(where: {interaction_eq: PAY_ROYALTY}) {
    id
    nft {
      name
      id
      price
      royalty
    }
  }
}

```

Check it out at https://app.gc.subsquid.io/beta/snekk/003/graphql @KngZhi :) Your help here will be much appreciated!

**Comment by KngZhi** [comment]
Thanks, Peter I will check that. Snek is too black box for me, 😂

**Comment by petersopko** [comment]
> Thanks, Peter I will check that. Snek is too black box for me, 😂

Okay @vikiival just figured it out, it all makes sense at works 😆, this wasn't a bug in the first place:
1. first transaction from `creator` to `first buyer` isn't supposed to emit event `PAY_ROYALTY` since the full price is being paid
2. `PAY_ROYALTY` should be emitted on second order trades -> this works well
