### ISSUE TITLE
ES Translation on Sustainibility page

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#335]
- [x] create sparate page like https://nft.kodadot.xyz/sustainability
- [x] put it on /es/sustentabilidad
- [x] make PR 

Sustentabilidad de KodaDot 
micro-dao-bedrock-bootstrap-experimento 

Como parte de nuestro micro-dao-bootstrap-experimento, nos gustaría mantener nuestros esfuerzos sostenibles en el largo plazo y crear esa confianza de la cultura y la economía de los creadores para KodaDot y darles esa seguridad de que no desapareceremos mañana y seguiremos funcionando mientras podamos cubrir nuestros esfuerzos para mantenerlo en línea y funcionando. 

Estaremos elaborando lentamente lo que es la mejor posible opcion para apoyar a la economia de los Creadores y ayudarles a realizar una vida sostenible de su trabajo. Estamos aqui para apoyar esta causa. Por otra parte, debemos tener en cuenta nuestra sostenibilidad a largo plazo. Estamos en posición de ser espectadores universales y de no ser propietarios de una plataforma como actualmente lo hacen otras galerias. 

Por el momento nuestro unico ingreso ha sido aprobado *propuesta#384 & motion#256 de Kusama Treasury Funding por milestone1. Principalmente este fondo se destinó a los costos del desarrollo y no para su funcionamiento y/o mantenimiento. 

Nuestro flujo de los fondos estará dividio en 3 partes: Un programa para el apoyo de los Artistas, Costos de funcionamiento y para el Costo de la investigacion y desarrollo de KodaDot. Desde el inicio, vamos a poner una parte de nuestros ahorros en el fondo de bedrock. 

Los costos por el funcionamento de KodaDot consisten en pagar Netlify (http, cdn, CI&CD), Pinata (IPFS), Arweave (por ahora es gratuito, despues tendremos que pagar), Textile.io (esperamos que este costo sea el mismo por un tiempo, y despues aumente). Mantenimiento, los costos de R&D deben ser pagados a medida que nuevas funciones en KodaDot vayan apareciendo y estamos tratando de invitar a mas desarrolladores a nuestros circulos poniendo recompensas en problemas. Cualquiera podrá unirse y ayudar con nuestro esfuerzo. 

Como nos gustaría establecer nuestro vector de acumulación para el fondo de sostenibilidad e introducir una pequeña tarifa gracias a que podra mintear su obra a través de KodaDot, agregaremos un botón en el que aún puede optar por no participar voluntariamente y poder mintear su obra sin apoyarnos en lo absoluto. 

Para devolver valor a la comunidad, estamos a punto de establecer un programa para el apoyo a los artistas el cual fluirá de regreso a los artistas. Estamos tratando de crear un ciclo de acumulacion de autorefuerzo, 

donde usted, como creador que apoya la galería de KodaDot, el apoyo regresará y será destinado a nuevos artistas, creando así efectos de red para los primeros usuarios y la próxima ola de adoptantes, etc., Que luego podrían ser autopropulsados ​​en algún momento si logramos desarrollar la estategia correcta.  Solo necesitamos jugar un poco más con las curvas de flujo correctas.  Es un experimento. 

Los poseedores actuales de multisig son los fundadores de KodaDot "yangwao" & "vikiival" y luego se expandirá, ya que creemos confianza con una comunidad mas amplia a la que le gustaria participar y adentrarse en KodaDot ya que esperamos que la tesoreria pueda crecer ampliamente algun dia. 

Definicion de Sustentabilidad 
sustantivo 

Es la abilidad de sostener o apoyar. 

Ciencia Ambiental. Es la cualidad de no ser dañino al Ambiente o estar agotando los recursos naturales por lo tanto se estaria apoyando el balance ecologico a una visión a largo plazo.

Thanks to Alejandro Cuadras/@CdrsAlejandro for the Spanish translation.

**Comment by ThibltJ** [comment]
Hi, 

I'm not sure to completely understand the request. Could you help me? 

Do you want a new page with url "/es/sustentabilidad" or do you want to translate the page via the already existing translation mechanism and so, in the future, be able to translate it in other languages?

**Comment by pandasamanvaya** [comment]
Hi @yangwao. Added pull request #416 for this issue. Check it out.

**Comment by yangwao** [comment]
Hey thank you @pandasamanvaya, I've just merged it! let's post your KSM address

**Comment by pandasamanvaya** [comment]
KSM address:- EoPy4MicziTRwnQLzocVq16ZyK1gL9xMEAuyFRko8wwW6L2

**Comment by yangwao** [comment]
> KSM address:- EoPy4MicziTRwnQLzocVq16ZyK1gL9xMEAuyFRko8wwW6L2

Sent https://kusama.subscan.io/extrinsic/7712359-10
