### ISSUE TITLE
burning nft produces error in console

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3350]
burning/consuming NFT in the end works, however it produces error in console and network, might wanna check this out
![image](https://user-images.githubusercontent.com/73316633/177574230-c1c75a62-65bd-42da-b0f0-ae82a2934a19.png)
![image](https://user-images.githubusercontent.com/73316633/177574336-4227f58e-7a52-4f95-8dce-3e5e37ebe1af.png)

**Comment by roiLeo** [comment]
Same thing happened to me
<img width="911" alt="Capture d’écran 2022-08-26 à 2 55 03 PM" src="https://user-images.githubusercontent.com/9987732/186908269-261dc962-b9f5-40d9-821d-4687b9235d43.png">

Tested on `/bsx/gallery/2444376227-6`

**Comment by roiLeo** [comment]
After investigation nft data is still present on 

Tested on: `/snek/gallery/1631038496-1`

**Comment by petersopko** [comment]
This is still true, also, I get redirected back to the NFT (technically speaking, it's a reload) and NFT doesn't appear to be burned. Needs another reload to see NFT being burned.
