### ISSUE TITLE
loading popup could be better

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3351]
whenever I'm processing any transaction (buy/mint/burn etc.) I see the loading popup and one thing bugs me about it. The loading starts with trivia (did you know) without any numbers, then proceeds into screenshot below:
![image](https://user-images.githubusercontent.com/73316633/177575700-8295f02f-ca0a-4cfe-86e0-78ef59f7a592.png)

After which it completely disappears. Since we're showing user 2/3 steps in the process, maybe we should also show 1/3 and 3/3 ? It's always just 2/3. Maybe I'm, not getting something here, but I'd like to see 1/3, then 2/3, then 3/3.

**Comment by roiLeo** [comment]
Random note: I find that when app is in error we can't escape this loading screen, it would be nice if we could cancel this popup


https://user-images.githubusercontent.com/9987732/177577323-4db48578-fa08-451e-a49e-6150f7298dcf.mov

**Comment by yangwao** [comment]
- #5458 
- #4979
