### ISSUE TITLE
Minting on BSX doesn’t work on Firefox?

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#3352]
### What happened?

Went to mint nfts, this pops up

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz

### Screenshots

<img width="492" alt="image" src="https://user-images.githubusercontent.com/92786519/177576269-f65f412a-d6fa-45d0-8133-53962a2fa351.png">

----

<img width="500" alt="image" src="https://user-images.githubusercontent.com/92786519/177576382-ba31e3d0-fb3c-474f-b055-45eaa2f8f780.png">

### Relevant log output

```shell
2022-07-06 16:32:51          API-WS: disconnected from wss://rpc-01.basilisk.hydradx.io: 1006:: Abnormal Closure 72c210f.modern.js:2:1883904
Firefox can’t establish a connection to the server at wss://rpc-01.basilisk.hydradx.io/. 72c210f.modern.js:2:525476
2022-07-06 16:32:56          API-WS: disconnected from wss://rpc-01.basilisk.hydradx.io: 1006:: Abnormal Closure 72c210f.modern.js:2:1883904
Firefox can’t establish a connection to the server at wss://rpc-01.basilisk.hydradx.io/. 72c210f.modern.js:2:525476
2022-07-06 16:33:03          API-WS: disconnected from wss://rpc-01.basilisk.hydradx.io: 1006:: Abnormal Closure 72c210f.modern.js:2:1883904
Firefox can’t establish a connection to the server at wss://rpc-01.basilisk.hydradx.io/. 72c210f.modern.js:2:525476
2022-07-06 16:33:14          API-WS: disconnected from wss://rpc-01.basilisk.hydradx.io: 1006:: Abnormal Closure 72c210f.modern.js:2:1883904
Firefox can’t establish a connection to the server at wss://rpc-01.basilisk.hydradx.io/. 72c210f.modern.js:2:525476
[ESTUARY] Pin Image 200 8b117ff.modern.js:1:549506
[PINNING] Pin JSON 200 8b117ff.modern.js:1:548749
error TypeError: n is undefined
    NuxtJS 3
72c210f.modern.js:2:929810
Firefox can’t establish a connection to the server at wss://rpc-01.basilisk.hydradx.io/. 72c210f.modern.js:2:525476
2022-07-06 16:33:30          API-WS: disconnected from wss://rpc-01.basilisk.hydradx.io: 1006:: Abnormal Closure 72c210f.modern.js:2:1883904
2022-07-06 16:33:54          API-WS: disconnected from wss://rpc-01.basilisk.hydradx.io: 1006:: Abnormal Closure 72c210f.modern.js:2:1883904
Firefox can’t establish a connection to the server at wss://rpc-01.basilisk.hydradx.io/. 2 72c210f.modern.js:2:525476
2022-07-06 16:34:30          API-WS: disconnected from wss://rpc-01.basilisk.hydradx.io: 1006:: Abnormal Closure 72c210f.modern.js:2:1883904
2022-07-06 16:35:24          API-WS: disconnected from wss://rpc-01.basilisk.hydradx.io: 1006:: Abnormal Closure 72c210f.modern.js:2:1883904
Firefox can’t establish a connection to the server at wss://rpc-01.basilisk.hydradx.io/. 72c210f.modern.js:2:525476
[ESTUARY] Pin Image 200 8b117ff.modern.js:1:549506
[PINNING] Pin JSON 200 8b117ff.modern.js:1:548749
error TypeError: n is undefined
    NuxtJS 3
        submit
        r
        l
72c210f.modern.js:2:929810
    NuxtJS 8
GETwss://rpc-01.basilisk.hydradx.io/
[HTTP/1.1 403 Forbidden 141ms]

Firefox can’t establish a connection to the server at wss://rpc-01.basilisk.hydradx.io/. 72c210f.modern.js:2:525476
2022-07-06 16:36:24          API-WS: disconnected from wss://rpc-01.basilisk.hydradx.io: 1006:: Abnormal Closure 72c210f.modern.js:2:1883904
GETwss://rpc-01.basilisk.hydradx.io/
[HTTP/1.1 403 Forbidden 203ms]

Firefox can’t establish a connection to the server at wss://rpc-01.basilisk.hydradx.io/. 72c210f.modern.js:2:525476
2022-07-06 16:37:25          API-WS: disconnected from wss://rpc-01.basilisk.hydradx.io: 1006:: Abnormal Closure 72c210f.modern.js:2:1883904

​
```

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptodamsky** [comment]
What i do:

Open beta.kodadot.xyz

Switch address i want to mint from to Basilisk in polkadot JS like so:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/92786519/177584887-fa4ec009-809d-4ba8-b8d6-bcbad08367ae.png">

Then i hit connect, select polkadot JS, but my address(bsx one) doesnt show up

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/92786519/177585046-a62298e3-63cb-4633-bb14-a3690222461c.png">

PS: I’m on firefox

**Comment by petersopko** [comment]
after further testing with @cryptodamsky here, it seems that chain keeps getting stuck in firefox. i.e. he's switched to BSX in navbar, but he can still see his KSM address etc.

**Comment by cryptodamsky** [comment]
Just loaded all the addresses - but lets see after mint or tommorow

**Comment by cryptodamsky** [comment]
Even managed to mint a collection but cannot mint any nfts into it 

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/92786519/177595162-8b4c2a1b-23a6-463a-9773-0840c886f5de.png">

**Comment by yangwao** [comment]
@cryptodamsky can you try now on https://beta.kodadot.xyz ? 
https://kodadot.xyz should work as well 

if works, please close this one

**Comment by cryptodamsky** [comment]
Still same issue:)

**Comment by yangwao** [comment]
@cryptodamsky it's still an issue even after we've merged #3500 ?

**Comment by preschian** [comment]
seems already fixed, works for me

**Comment by yangwao** [comment]
> works for me

@cryptodamsky 👀😅

**Comment by yangwao** [comment]
don't forget clear all your cache in Firefox 
(found way where it somehow cache previous version on beta)

**Comment by cryptodamsky** [comment]
Yup, works now
