### ISSUE TITLE
Clarify reward currency in REWARD page

### ISSUE THREAD

**Issue by joelamouche** [kodadot/nft-gallery#3356]
### Is your feature request related to a problem?

In https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md , it is not clear in the table that the reward amount is in USD (and not KSM since it is your favorite currency)

### Describe the solution you would like

I would like to see the currency clearly stated, like in the label

### Describe alternatives you have considered

Put the KSM amount ^^

**Comment by petersopko** [comment]
thanks for the feedback :), this is more of an docs issue, moving it here https://github.com/kodadot/docs/issues/67
