### ISSUE TITLE
Bug: country flags stopped displaying next to abbreviations 

### ISSUE THREAD

**Issue by matenji** [kodadot/nft-gallery#336]
@yangwao: including country flags is easily more identifiable than using 2-char country abbreviations alone.

**Comment by yangwao** [comment]
Can you check if you are on the latest version or try in incognito?
Seems WFM 
![image](https://user-images.githubusercontent.com/5887929/116973833-66e4d000-acbd-11eb-9f07-756f3019d456.png)

**Comment by yangwao** [comment]
![image](https://user-images.githubusercontent.com/5887929/117287203-6473a900-ae6a-11eb-9f5e-87ca78eb2f74.png)
Feel free re-open if bug persists, check your cache or so, may we pushed some version and some where where we fixed it :)
