### ISSUE TITLE
Fetching for collection for KSM chain while on BSX

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3364]
Seems singleton instance might cause some issues but seems this is not the case as don't have opened another window as it is the only one point to kodadot

Mind **set correct address 2** after connected to basilisk. 
Seems this is the culprit of many issues we have there.

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/5887929/177748520-db5fcb6b-0d18-4ca5-a3e3-121b4af90d56.png">

### you can replicate it
- open incognito
- open console
- https://beta.kodadot.xyz/bsx/explore/?tab=GALLERY&page=1
- check logs

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5887929/177750342-2074e329-a101-4690-aede-3666c517bbc7.png">

**Comment by yangwao** [comment]
I know @Jarsen136 might be great for investigation 😄
I've also raised the amount as it's becoming a bit culprit of other issues. 

### hints 
- vuex-persist
- https://github.com/kodadot/nft-gallery/blob/main/store/index.ts#L33
- https://github.com/kodadot/nft-gallery/blob/main/store/identity.ts#L112 
- https://github.com/kodadot/nft-gallery/blob/main/store/chain.ts

**Comment by yangwao** [comment]
Seems somewhere internally it connects to Kusama for the very first time. 

This time it played well, but usually, it goes in a different order. 
Check network and WS network tab in incognito for first time

<img width="795" alt="image" src="https://user-images.githubusercontent.com/5887929/178145903-f14ae028-3f0e-4e69-ac76-faf8f9881927.png">

**Comment by yangwao** [comment]
Seems there is a desync of operations once first time client connects to the default endpoint and first initial requests comes afterwards once already client is reporting connected to BSX

https://github.com/kodadot/packages/blob/99d6be9c0ad2dc62000c67945a4e3ebfcaf4c15e/vuex-options/src/defaults/endpoints.ts#L84

**Comment by yangwao** [comment]
The suggestion is to remove vuex-persist 

We might loose permanent settings  

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/5887929/178146665-6a8c9724-60e1-4e74-ad20-989109bfcc62.png">

**Comment by yangwao** [comment]
@vikiival any updates? 😄

**Comment by vikiival** [comment]
> @vikiival any updates? 😄

Yup, 

polishing tests https://github.com/kodadot/packages/tree/brand-new-sub-api
