### ISSUE TITLE
Identity at item is shown twice?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3367]
Showing two times identity on gallery item? 

https://beta.kodadot.xyz/bsx/gallery/3195582573-3

- #3357  seems related by @zhengow

<img width="256" alt="image" src="https://user-images.githubusercontent.com/5887929/177761999-bf2cf163-719f-4ae7-a2b4-3eaef3d5b0da.png">

yup, in 
- #3324 doesn't happen
 
<img width="251" alt="image" src="https://user-images.githubusercontent.com/5887929/177762365-32f83426-df6c-4e8a-95c5-55373afa9541.png">

**Comment by Jarsen136** [comment]
👋

**Comment by zhengow** [comment]
Already see MR. Sorry for the bug😅
