### ISSUE TITLE
Bugs on Basilisk v0

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3368]
Current bugs we are aware of and which are making some sort of **p1 issue and breaking experience** to have fully comfortable usage of NFT marketplace on Basilisk within KodaDot.

@petersopko would keep editing this issue & monitoring upcoming issues reported by users as there might be a lot of other errors that might arise during testing we need to nail down actively.

### Sorted by severity (higher more important)
- [ ] #3291 
- [ ] #3395

### Done:
- [x] #3349
- [x] #3333
- [x] #3513
- [x] #3560
- [x] #3589
- [x] #3293
- [x] #3364
- [x] #3459
- [x] #3292
- [x] #3339 
- [x] #3282 (social media cards are working here)
- [x] #3409
- [x] #3342 
- [x] #3346

**Comment by roiLeo** [comment]
- [ ] `/bsx/detail/{id}` is using `rmrk` GalleryItem instead of `bsx` GalleryItem like `/bsx/gallery/{id}`

**Comment by prachi00** [comment]
> * /bsx/detail

can you explain more about this? like which url exactly?` /bsx/gallery/2151001007-2` this one?

**Comment by prachi00** [comment]
> > * /bsx/detail
> 
> @roiLeo  can you explain more about this? like which url exactly?` /bsx/gallery/2151001007-2` this one?

**Comment by roiLeo** [comment]
> > > * /bsx/detail
> > 
> > @roiLeo  can you explain more about this? like which url exactly?` /bsx/gallery/2151001007-2` this one?
> 
> 

https://github.com/kodadot/nft-gallery/blob/main/pages/bsx/detail/_id.vue#L8

**Comment by prachi00** [comment]
> > > > * /bsx/detail
> > > 
> > > 
> > > @roiLeo  can you explain more about this? like which url exactly?` /bsx/gallery/2151001007-2` this one?
> 
> https://github.com/kodadot/nft-gallery/blob/main/pages/bsx/detail/_id.vue#L8

in the code, I don't see any route redirection to `/bsx/detail `, how will the user get redirected to this?

**Comment by roiLeo** [comment]
> * [ ]  `/bsx/detail/{id}` is using `rmrk` GalleryItem instead of `bsx` GalleryItem like `/bsx/gallery/{id}`

resolved in #3282

**Comment by yangwao** [comment]
Continue to #3756
