### ISSUE TITLE
Sometimes price is not showing in local env

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#3374]
Tested on `/bsx/collection/4011142362`

don't know how to reproduce it yet

and Theater mode is not saved in preferences?

https://user-images.githubusercontent.com/9987732/177952386-f57814d8-6a27-46d8-94bf-eda3c37d3bac.mov

**Comment by yangwao** [comment]
Roomba nft doesn't have price set 👀

**Comment by yangwao** [comment]
can you try now @roiLeo ? we've re-run Snek indexer so some data might start showing up. 

like stats started showing up 

<img width="872" alt="image" src="https://user-images.githubusercontent.com/5887929/178103387-7cd3ad0c-737a-4ffc-a125-79c973834b0f.png">

**Comment by roiLeo** [comment]
tested again, clean install/repo
Price is doing weird glitch same with vuex preferences

https://user-images.githubusercontent.com/9987732/178113643-d8018b08-3830-4db9-9b4a-3e0c8bbfa999.mov

I can see prices on `/bsx/stats`

<img width="740" alt="Capture d’écran 2022-07-09 à 6 08 04 PM" src="https://user-images.githubusercontent.com/9987732/178113719-34d81323-7cb3-4dcb-a53a-c73d151ebed3.png">

**Comment by roiLeo** [comment]
updated pnpm to 7.5.0 and now its working again :dizzy_face:

**Comment by roiLeo** [comment]
nvm...

**Comment by yangwao** [comment]
> & I still see my account name

the account name is quite okayish as it's if an address has set on-chain identity on Kusama. It's the same address on basilisk, and basilisk doesn't offer an identity pallet now, but in the future will, so I bet we can keep it for now against KSM 😄

We can implement an on-chain identity from Basilisk to be independent of KSM in the future.

**Comment by roiLeo** [comment]
![Screenshot 2022-07-19 at 17-25-36 Hill KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/179788710-d4a9a97e-5841-4329-8c6a-948d3234459f.png)

closing this since I manage to make it work on local, how you may ask

answer:
by runing `pnpm install` instead of `pnpm i`

![jerry](https://user-images.githubusercontent.com/9987732/179789424-7b3ae9ec-1539-43e7-b73e-cfa667bc780d.jpg)
