### ISSUE TITLE
Refactor: NFT storage

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3379]
Next candidate for refactor: 
- #3358

_Originally posted by @vikiival in https://github.com/kodadot/nft-gallery/issues/3310#issuecomment-1177253672_

I take it, that as @vikiival mentioned, we should refactor / rethink the way our current NFT storage option work

- #3334

**Comment by vikiival** [comment]
Closed in https://github.com/kodadot/nft-gallery/pull/3741
