### ISSUE TITLE
Kodadot metrics for carbon calculator

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#338]
#### most important metrics
- number of NFTs
- (average) storage of NFTs

#### good to have metrics
- numbers of trades per NFT
- account number of BURNed NFTs
- account how much costs actions
    - MINT
    - SEND
    - CONSUME
    - LIST

**Comment by vikiival** [comment]
Must have metrics are possible with current setup.

> numbers of trades per NFT;
> account number of BURNed NFTs
:: we don't have any history in textile for that
 
 > account how much costs actions
 is this one time time calculation  @yangwao  ? Because we can predict the price of each action (cc #69) +- cents depends on byte size

**Comment by yangwao** [comment]
We can use https://github.com/kodadot/nft-gallery/issues/334#issuecomment-833444903 for this to have live data

**Comment by JustLuuuu** [comment]
not relevant
