### ISSUE TITLE
Firefox errors when using KodaDot

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3384]
I'm trying to test KodaDot with Firefox incognito, and my console is very red. Seems that every click/operation within the app produces the same error. 
`
Uncaught (in promise) DOMException: A mutation operation was attempted on a database that did not allow mutations. 
`
On top of that, there are various network errors:

Network errors: 
![image](https://user-images.githubusercontent.com/73316633/178103091-625db22b-ce20-4dbc-a94a-4337af246308.png)
![image](https://user-images.githubusercontent.com/73316633/178103109-cdcbf174-a557-4e8b-b2ec-72e96a205968.png)

Console:
![image](https://user-images.githubusercontent.com/73316633/178102988-a7a81790-6ece-4b0e-b09e-f1d1a0328cca.png)

This happens when I'm trying to use KodaDot without login:
![image](https://user-images.githubusercontent.com/73316633/178103145-bfea6220-1fbe-4b5e-b62a-5ef3833711ec.png)

Even after restarting the firefox, sometimes I land into infinite loading window:
![image](https://user-images.githubusercontent.com/73316633/178103190-11a1451a-b83c-419a-b493-cd8f494fbd16.png)

tested with both polkadotJs and Talisman accounts

**Comment by petersopko** [comment]
Not sure if this is because of my firefox settings, but I currently can't even get to minting
- https://github.com/kodadot/nft-gallery/issues/3352

**Comment by yangwao** [comment]
With Safari happens likewise I see a bunch of errors in explorer (504 on pictures).  
Probably we will put it on hold, make firefox and safari less supported browsers with KodaDot 
Curious, is the passion filter default on there? Seems that takes bit much more time to resolve on the user side.

**Comment by petersopko** [comment]
> Curious, is the passion filter default on there? Seems that takes bit much more time to resolve on the user side.

passion filter was previously on by default, but we turned it off since user without bought nfts didn't see anything,
same thing will be on landing page, off by default:
- https://github.com/kodadot/nft-gallery/pull/3151
