### ISSUE TITLE
moonsama collections images

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3388]
currently, I'm not seeing moonsama collection images as opposed to what I'm seeing at https://marketplace.moonsama.com/collections

explore:
![image](https://user-images.githubusercontent.com/73316633/178106609-298f91d6-6487-4443-b4ba-94c20e13b71d.png)

landing
![image](https://user-images.githubusercontent.com/73316633/178106619-a0d66395-5adf-42e6-8fa8-a72bf1d39296.png)

**Comment by vikiival** [comment]
This was mentioned in #3340 that it does not work because I forgot to index it.

The fix is in kodadot/click@573504fb8b4dc604b37bd410376566e1d43152a8
