### ISSUE TITLE
Filtering in Gallery on Basilisk is broken 🐛 

### ISSUE THREAD

**Issue by kkukelka** [kodadot/nft-gallery#3398]
### What happened?

Having trouble filtering items on `/bsx/explore`
- No matter what I try to filter by, results are always the same
- Furthermore, filter selections seem to get stuck in their state?
- Querying for only listed items via "Buy now"-switch also doesn't work as intended it seems?

Scope of ticket:
- Fix `SearchBar.vue` such that it works with basilisk explorer

https://user-images.githubusercontent.com/17953978/178134508-66c79bfd-a192-4ffe-b893-9dccf2f3dcd9.mov

### Please reproduce in steps

see video

### Expected Behavior

actual filtered results

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which chain did you encounter bug?

Basilisk

### Payment link for reward

https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petersopko** [comment]
hmm, I think we're sufficiently tracking this in
- https://github.com/kodadot/nft-gallery/issues/3293

let's close to avoid having this scattered in multiple places
