### ISSUE TITLE
Shifted kodadot logo on social card preview 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3402]
Hence previews work again! 

<img width="498" alt="image" src="https://user-images.githubusercontent.com/5887929/178144215-3af7a1e2-651a-4be2-b751-c489d9dd5797.png">

can we fix the background of our logo 🙄

<img width="103" alt="image" src="https://user-images.githubusercontent.com/5887929/178144199-28ae7267-be6e-468e-bc74-a5d0f0175105.png">

once 
- #3282 
is merged could this one be done

**Comment by roiLeo** [comment]
#3038 related

**Comment by roiLeo** [comment]
Might be time to move og image preview repo to Kodadot org
https://github.com/AndreyGrin/og-image/pull/3 related

**Comment by roiLeo** [comment]
✅ Done 

<img width="448" alt="Capture d’écran 2022-07-20 à 10 14 57 AM" src="https://user-images.githubusercontent.com/9987732/179932430-5891eb6f-b7be-4682-a88b-4941363ea164.png">
