### ISSUE TITLE
I’m trying to explore, but it doesn’t load

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#3419]
### What happened?

/

### Please reproduce in steps

Go to kodadot.xyz, click explore

### Expected Behavior

/

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

No

### At which chain did you encounter bug?

RMRK

### Screenshots

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/92786519/178343686-ae09af3f-093f-4154-8fa6-1fdcde942186.png">

### Relevant log output

```shell
Access to fetch at 'https://app.gc.subsquid.io/beta/rubick/006/graphql' from origin 'https://kodadot.xyz' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
app.gc.subsquid.io/beta/rubick/006/graphql:1          Failed to load resource: net::ERR_FAILED
54a4b95.modern.js:1 Uncaught (in promise) Error: Network error: Failed to fetch
    at new t (54a4b95.modern.js:1:2612666)
    at 54a4b95.modern.js:1:2633504
    at 54a4b95.modern.js:1:2639561
    at Set.forEach (<anonymous>)
    at 54a4b95.modern.js:1:2639537
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (54a4b95.modern.js:1:2639487)
    at 54a4b95.modern.js:1:2632132
54a4b95.modern.js:1 2022-07-11 21:30:03        API/INIT: RPC methods not decorated: mmr_generateBatchProof
O @ 54a4b95.modern.js:1
90fc138.modern.js:1 [API] Connect to <3 wss://kusama.api.onfinality.io/public-ws Object
54a4b95.modern.js:1  [SET CORRECT ADDRESS FORMAT] 2
DevTools failed to load source map: Could not load content for chrome-extension://fijngjgcjhjmmpcmkeiomlglpeiijkld/content_script.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://fijngjgcjhjmmpcmkeiomlglpeiijkld/page.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
```

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petersopko** [comment]
sorry for late reply, this is something we were observing elsewhere, issue was with the queries but after @vikiival disabled some queries and fixed this yesterday, I can't reproduce this anymore (thankfully). for the future purposes, same thing is being tracked here: 
- https://github.com/kodadot/rubick/issues/109
- https://github.com/kodadot/nft-gallery/issues/3287
