### ISSUE TITLE
State that we are NFT gallery on kodadot.js.org 

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#343]
There is no info on  kodadot.js.org about NFT gallery
<img width="1678" alt="Screenshot 2021-05-05 at 10 24 29" src="https://user-images.githubusercontent.com/22471030/117114410-1c7e5480-ad8c-11eb-9869-e07a46001a63.png">

**Comment by yangwao** [comment]
Meanwhile done, forgot to link up 

![image](https://user-images.githubusercontent.com/5887929/186936023-6e101590-a4b7-4490-abe6-fe66536d76ae.png)
