### ISSUE TITLE
Unable to mint in Basilisk

### ISSUE THREAD

**Issue by zhengow** [kodadot/nft-gallery#3447]
### What happened?

A bug happened!
it shows `network error`.
Is this my network problem?

### Please reproduce in steps

Go to ... Click on .... See error

### Expected Behavior

I've expected ...

### What browsers are you seeing the problem on?

Chrome

### Screenshots

Paste from your clipboard or upload screenshots/video
<img width="2527" alt="image" src="https://user-images.githubusercontent.com/38389586/179341548-29779816-44a0-42e5-824a-15c86658335a.png">

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petersopko** [comment]
just minted both collection and NFT without any problems, perhaps some outage with nft.storage?

**Comment by yangwao** [comment]
Maybe we could handle this in case the endpoint is down, with something like retry after a while?

**Comment by vikiival** [comment]
Just tried the endpoint both `pinJson` and `pinFile` works oki for me.

**Comment by yangwao** [comment]
Continue to #3458
