### ISSUE TITLE
Integrate Replicate API to mint dall-e NFTs 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3455]
We would like to speed up the dall-e minting process right away from Kodadot.
You can either integrate it to the classic one on basilisk or copy a whole new minter, which one is more manageable.

Integrate replicate API to minting for Basilisk where user can 
- enter prompt for model prediction https://replicate.com/kuprel/min-dalle (now we are hardcoding this model)
- user will see rendered prediction and can use it as a file to mint
- add the ability to change the grid size; the default could be 3 or 4 as it's super speedy with fewer tiles
- add prompt to traits of NFTs  
- choose which is easier to implement, either HTTP or replicate-js library
- To make its way, we can add the ENV variable for API token on deployment/production

Ping me for the key or just subscribe (it's $10/mo)

### Ref
- https://replicate.com/docs
- https://github.com/replicate/replicate-discord-bot
- https://github.com/nicholascelestin/replicate-js
- https://replicate.com/docs/api/http
- https://app.wombo.art/
- https://replicate.com/afiaka87/retrieval-augmented-diffusion
- https://promptbase.com/marketplace
- https://unstock.ai/
- https://promptomania.com/
- https://promptomania.com/prompt-builder/
- https://github.com/aihubgg/MidJourney-Wiki/blob/f87a32cd2cd3129d65a48eefacd24d5153ca4913/docs/External-Resources/Prompt-Builders/promptoMANIA.md
- https://phraser.tech/
- https://huggingface.co/spaces/doevent/prompt-generator/
- https://github.com/midjourney/docs/blob/f102e3bccbcbec33aae04f267b17a7b71c85e01f/resource-links/README.md
- https://www.the-ai-art.com/
- https://multimodal.art/news/1-week-of-stable-diffusion

**Comment by FrankBevr** [comment]
Let me give it a try, but I am in Paris and have to sweat my gut out, literally 🥵 

But I can give it a week and see how far I can get.
If someone is faster, because "more familar with the codebase" please go ahead 🙃 

I will write you on Sunday for the key Stuff.

Cheers 🌤️

**Comment by vikiival** [comment]
kodadot/workers#14

**Comment by vikiival** [comment]
AI x Frames ❤️ 
Continue in
- https://github.com/kodadot/ops-internal/issues/1807
