### ISSUE TITLE
Add? See how many offers has been made by certain address:

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#3462]
### Is your feature request related to a problem?

I’d like to know, who is making most offers and how many they have.

### Describe the solution you would like

Have a page where i’d insert address and see address activity 

### Describe alternatives you have considered

/

### Are there opened related issues?

This might be related and kinda similiar to 

- #3453
- #3203

**Comment by yangwao** [comment]
Great idea, I guess we can later make a functional component with an address as param and input and merge these three

- #3450 
- #3203 
- #2801

**Comment by yangwao** [comment]
Continue to #3463
