### ISSUE TITLE
Double BURNing -  bXiGvoYjMbEEUe27h3zFCnabsu367zEDEivu8ZHjVSm5v8mC2

### ISSUE THREAD

**Issue by AVD061975** [kodadot/nft-gallery#3466]
### What happened?

A bug happened!

Wallet: bXiGvoYjMbEEUe27h3zFCnabsu367zEDEivu8ZHjVSm5v8mC2

![image](https://user-images.githubusercontent.com/96058877/179530239-27450c08-8812-4af1-bd3e-22b9df727acd.png)

### Please reproduce in steps

Go to ... Click on .... See error

1.  Burn new NFT.
![image](https://user-images.githubusercontent.com/96058877/179530492-0cb98698-b1ab-4c10-a5e3-d07401e3c0e9.png)

2.  Success burning:
![image](https://user-images.githubusercontent.com/96058877/179530731-05090dfa-8bd8-4643-a80e-61b983d4b3b0.png)

3.  After (2 point),  dont refresh the page.  You see previous page, as at 1 point.
Click  BURN again and get an Error:
![image](https://user-images.githubusercontent.com/96058877/179531202-d1ef81c8-164a-4f93-b9c0-ecf560c37388.png)

### Expected Behavior

I've expected to automatically refresh the page after first BURNing 

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

![image](https://user-images.githubusercontent.com/96058877/179531461-7ced01a4-f9a3-4171-bd7b-5ea6561ab649.png)

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

bXiGvoYjMbEEUe27h3zFCnabsu367zEDEivu8ZHjVSm5v8mC2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
👋
