### ISSUE TITLE
Seems Magick down on collection detail 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3467]
Seems Magick down? 

Can't view collection detail 
https://beta.kodadot.xyz/rmrk/collection/C6E2CA836BD86CBD05-PLACE

Are we using Magick differently for collection or to rewrite it with subsquid? 

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/5887929/179536020-90684b43-7a46-4fd5-b995-87da72869b88.png">

at collection seems it works

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/5887929/179536248-0df484e9-a05f-4e0f-bda8-19a53518ff11.png">

even gallery

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/5887929/179536317-d91a3434-9783-4801-ac05-03879e9cdf2a.png">

**Comment by Jarsen136** [comment]
👋
