### ISSUE TITLE
Add to NFT item detail creator and current owner

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#347]
Once sale happens, 
we should clearly state to the user 
- [ ] who is now the current owner of NFT 
- [ ] who was the creator/issuer - probably owner of collection?

**Comment by XyloDrone** [comment]
![Screenshot 2021-05-18 at 22 55 33](https://user-images.githubusercontent.com/84407059/118728571-4f185a80-b82c-11eb-8f2b-ed78f79f834a.png)

Add this in artowrk under acticity

**Comment by XyloDrone** [comment]
artist profile full page example 
![Screenshot 2021-05-18 at 22 58 02](https://user-images.githubusercontent.com/84407059/118728692-84bd4380-b82c-11eb-86c7-50beb5945ceb.png)
