### ISSUE TITLE
Can`t create colection

### ISSUE THREAD

**Issue by svzem1** [kodadot/nft-gallery#3475]
### What happened?

oe: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

### Please reproduce in steps

Go to: Create collection 
Click on: Drop collection logo -> Write Collection name and description -> Create collection.... 
See error: oe: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

### Expected Behavior

I've expected vy collection creating
![1](https://user-images.githubusercontent.com/109521684/179582600-ae917fe8-2193-4449-8462-d391763110f8.jpg)

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

No

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Basilisk

### Screenshots

![image](https://user-images.githubusercontent.com/109521684/179583130-74ca0eb0-20a9-4571-8c58-d5b7eae41c73.png)

### Payment link for reward

[CdYDyPE7TRJ5mYWE7k7tQvkaQEbzG7UZvwNCZzCkeJHYVaT](https://kodadot.xyz/transfer?target=CdYDyPE7TRJ5mYWE7k7tQvkaQEbzG7UZvwNCZzCkeJHYVaT&usdamount=0&donation=true)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
It's he same issue related to https://github.com/kodadot/nft-gallery/issues/3459
