### ISSUE TITLE
I couldn't Burn NFT

### ISSUE THREAD

**Issue by Pavel333333** [kodadot/nft-gallery#3489]
### What happened?

I couldn't Burn NFT . the transaction failed with an error.

### Please reproduce in steps

On the NFT page, I tried to use the Burn function. Pressed the button, confirmed the transaction.

### Expected Behavior

I expected the NFT to be removed

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

![Uploading image.png…]()

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petersopko** [comment]
@Pavel333333 thanks for participating, but we are going to need more detail in order to do anything about this. If you encounter this bug again, please attach screenshot and make sure you have enough balance, ideally get us a screenshot from console :)
