### ISSUE TITLE
Wrong text after accepting incoming offer?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3498]
I've accepted the incoming offer, and it says since block NFT is yours? 
Probably there should be "Since block <number> NFT has new owner" or something like that?

https://deploy-preview-3453--koda-nuxt.netlify.app/bsx/incomingoffers/

<img width="457" alt="image" src="https://user-images.githubusercontent.com/5887929/180021954-42bb8b2d-892e-4316-8a78-eda3462b7573.png">

**Comment by Jarsen136** [comment]
👋
