### ISSUE TITLE
Filter on Gallery/Market

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#35]
- [x] art by author
- [ ] currency? right now all are Native
- [ ] by project/collection
- [ ] on sale
- [ ] by price
- [ ] by date
- [ ] time constraints
- [ ] single vs bundles
- [ ] art/domain names/ virtual worlds/ trading cards/collectibles/utility

![image](https://user-images.githubusercontent.com/5887929/107143536-ecaee480-6935-11eb-940c-65308f8ba50a.png)

inspiration https://opensea.io/assets/polkapets?search[sortAscending]=false&search[sortBy]=BIRTH_DATE

**Comment by yangwao** [comment]
#49

**Comment by yangwao** [comment]
Worth mentioning https://www.wdl.org/en/search/?institution=brown-university-library#view=map
![image](https://user-images.githubusercontent.com/5887929/112318169-0bcac100-8cad-11eb-9814-ab66972937f9.png)

**Comment by yangwao** [comment]
Google 
![image](https://user-images.githubusercontent.com/5887929/112321923-c0b2ad00-8cb0-11eb-9b0d-cfa0828f7225.png)
![image](https://user-images.githubusercontent.com/5887929/112321966-cb6d4200-8cb0-11eb-83ac-8676c388f6e0.png)
![image](https://user-images.githubusercontent.com/5887929/112321995-d0ca8c80-8cb0-11eb-9441-972a7ea5477b.png)
![image](https://user-images.githubusercontent.com/5887929/112322014-d58f4080-8cb0-11eb-86f6-6c93cb572279.png)
![image](https://user-images.githubusercontent.com/5887929/112322028-d88a3100-8cb0-11eb-9db6-4f29ed1bad9a.png)
![image](https://user-images.githubusercontent.com/5887929/112322038-db852180-8cb0-11eb-9c74-2738f4724f64.png)

**Comment by yangwao** [comment]
Github
Author ![image](https://user-images.githubusercontent.com/5887929/112445658-ada2ea00-8d4f-11eb-8100-efc42893d7f1.png)
Label
![image](https://user-images.githubusercontent.com/5887929/112445687-b4c9f800-8d4f-11eb-919a-0d425787c628.png)
Projects 
![image](https://user-images.githubusercontent.com/5887929/112445704-b98eac00-8d4f-11eb-9b9f-efd038b694ad.png)
Sort
![image](https://user-images.githubusercontent.com/5887929/112445744-c4494100-8d4f-11eb-8d52-efb96928e86e.png)

**Comment by chris-saburo** [comment]
@yangwao @vikiival I think we don't need to add the filter feature here because we have been working to implement the Search component which also can filter as described like the above. so I think we need to think more whether or not we might need to place the filter component in gallery page.

**Comment by chris-saburo** [comment]
If you would like to also add filter feature, let me implement it after done searching component.

**Comment by XyloDrone** [comment]
I would say that trading cards are collectibles, so best just to keep that category, otherwise it ends up confusing.
