### ISSUE TITLE
Searching in gallery at Basilisk

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3505]
When I search some term, it yields a fair amount of errors 

https://beta.kodadot.xyz/bsx/explore?page=1&tab=GALLERY&search=simpson

Is it somewhere already being fixed? 
![image](https://user-images.githubusercontent.com/5887929/180175634-3f3c6500-6168-451e-82b4-3c581d36ac62.png)

**Comment by petersopko** [comment]
yep, here's gallery in general:
- https://github.com/kodadot/nft-gallery/issues/3293

here's suggestions, should be ready to merge soon: 
- https://github.com/kodadot/nft-gallery/pull/3491

here's the last piece:
- https://github.com/kodadot/nft-gallery/issues/3504
