### ISSUE TITLE
toggling 'BUY NOW' should show only prices > 0 

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3515]
@petersopko Oups since my last review, I totaly forgot that not listed nfts have a price of 0, so when we toggle "BUY NOW" it will filter nfts with a price greaterThanOrEqualTo 0 (which corresponds to all nfts)

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/3474#issuecomment-1191383795_

**Comment by roiLeo** [comment]
closed by #3474
