### ISSUE TITLE
Where can I get bsx(not in testnet)

### ISSUE THREAD

**Issue by zhengow** [kodadot/nft-gallery#3521]
### Is your feature request related to a problem?

Missed the `First Basilisk Crowdloan`

### Describe the solution you would like

Is there any way to get bsx?

### Describe alternatives you have considered

For example, some dex?

**Comment by roiLeo** [comment]
Maybe from https://bsx.play.hydration.cloud/#/trade but I don't know if it's working well

**Comment by yangwao** [comment]
They've just recently launched live their XYK pools.
You can get BSX for KSM or aUSD. 

https://app.basilisk.cloud/#/trade?assetIn=1&assetOut=0

![image](https://user-images.githubusercontent.com/5887929/181736388-f69dceec-33af-4232-aa1a-b2341da0ecd3.png)
