### ISSUE TITLE
can't mint NFT

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3541]
I'm facing this error when trying to mint new NFT, not sure what asset instance ID means, but:

- it's new picture
- new name
- new description
- tried in new window (incognito) - same thing

Nothing seemingly matches any previously existing NFT.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/73316633/180595329-d999547a-4508-4a4a-a3cc-e7060d0d6829.png">

**Comment by preschian** [comment]
I got different errors currently in beta
<img width="2032" alt="Screen Shot 2022-08-10 at 17 09 01" src="https://user-images.githubusercontent.com/734428/183877413-60b7a112-f08f-4ad3-a2c5-a832a8cf1198.png">
