### ISSUE TITLE
Unique already exists 

### ISSUE THREAD

**Issue by Shivaproject** [kodadot/nft-gallery#3544]
### What happened?

1. Made an offer, commission paid, but it gives an error. Photo attached
2. Can't upload photos to a specific collection, although the file has not been used anywhere yet,  commission paid
3. When uploading the last two files, it shows the sale price of zero
4. Such a question, why can't I change the price of a file after I put it up for sale?

### Please reproduce in steps

1. Made an offer, commission paid, but it gives an error. Photo attached
2. Can't upload photos to a specific collection, although the file has not been used anywhere yet,  commission paid
3. When uploading the last two files, it shows the sale price of zero
4. Such a question, why can't I change the price of a file after I put it up for sale?

### Expected Behavior

1. Made an offer, commission paid, but it gives an error. Photo attached
2. Can't upload photos to a specific collection, although the file has not been used anywhere yet,  commission paid
3. When uploading the last two files, it shows the sale price of zero
4. Such a question, why can't I change the price of a file after I put it up for sale?

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

1. ![Снимок экрана (135)](https://user-images.githubusercontent.com/108521974/180597533-33625dcb-af64-4621-afdf-ec4af2575455.png)
2. ![Снимок экрана (136)](https://user-images.githubusercontent.com/108521974/180597548-96406d5b-da43-48cb-b97e-ca01224cd2a1.png)
3. ![Снимок экрана (137)](https://user-images.githubusercontent.com/108521974/180597572-cb9ed898-9bfd-42a9-81e4-1fd4f1d2f65a.png)

 

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petersopko** [comment]
Hey, thanks for reporting this :) can we get more details please? Such as link to the NFT and your wallet address? Starts with bX...

**Comment by Shivaproject** [comment]
https://beta.kodadot.xyz/bsx/gallery/1679439669-5
https://beta.kodadot.xyz/bsx/gallery/1707670769-9?page=1
https://beta.kodadot.xyz/bsx/gallery/1707670769-5?page=1
bsx adress    bXhHkrZkzV9LXuwk3AyQ186tVkz6wGQcrxM2cBByGEsNEE1c6

**Comment by Shivaproject** [comment]
Problem with basilisk eye collection. Added 10 files to the collection in total, and now I can't upload any files. The error is visible in the screenshot at number two.

**Comment by yangwao** [comment]
Same as 
- #3565 ? 

Maybe fixed in 
- #3566

@Shivaproject you can try to test here if it's still happen for you
https://deploy-preview-3566--koda-nuxt.netlify.app/

**Comment by Shivaproject** [comment]
The problem with the price. After signing the transaction everything is successful, but the price on the platform is zero.
bsx adress bXhHkrZkzV9LXuwk3AyQ186tVkz6wGQcrxM2cBByGEsNEE1c6
![Снимок экрана (142)](https://user-images.githubusercontent.com/108521974/181456065-197f5e20-1a68-4b9b-b658-83230fd6dd65.png)

**Comment by yangwao** [comment]
> but the price on the platform is zero.
yes, we are aware of it; the anticipated hotfix will come today 😅🤞😁

continue tracking it in 
- #3560

**Comment by Shivaproject** [comment]
Thanks a lot)
