### ISSUE TITLE
1f994.png is missing

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#355]
**Describe the bug**
missing emoji png?

**To Reproduce**
Open for example https://nft.kodadot.xyz/rmrk/detail/7373514-e8fe2f9cd718f4c43f-HQP8Q-HEDGEHOG-0000000000000001
check console
![image](https://user-images.githubusercontent.com/5887929/117568279-b6613c80-b0bf-11eb-8753-52030dd8d695.png)

**Comment by vikiival** [comment]
Ohhh I know, 

someone EMOTED with 🦔 . 
Maybe we should allow full emoji set ?

**Comment by yangwao** [comment]
Sent svg premium pack over the phone 🤙

**Comment by vikiival** [comment]
Closed as we have migrated to full emoji picker
