### ISSUE TITLE
Balance Input emit wrong value after unit change

### ISSUE THREAD

**Issue by KngZhi** [kodadot/nft-gallery#3558]
### What happened?

As title suggested.the 

### Please reproduce in steps

Any Gallery Item could reproduce this.

### Expected Behavior

BSX should be the base unit, and emit the right value with bsx unit after the value changed or unit changed.

### Screenshots

![image](https://user-images.githubusercontent.com/11361147/180717868-374d4934-5bde-4c99-b35f-1ab83c2cf27f.png)

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Maybe fixed in #3500 ?

**Comment by KngZhi** [comment]
Nah, this is kind a front-end bug.

e.g., If I input 100 kilo, it should emit 100 * 1000 BSX;

I'm working on it, would make a PR tonight.
