### ISSUE TITLE
missing Unit in simple mint 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#356]
**Describe the bug**
Missing unit in simple mint

**To Reproduce**
Go to https://nft.kodadot.xyz/rmrk/mint

**Expected behavior**
Show KSM

**Screenshots**
![image](https://user-images.githubusercontent.com/5887929/117568396-456e5480-b0c0-11eb-9765-cf94db95a663.png)

**Comment by vutran6853** [comment]
It seen to by default the option is blank. In `BalanceInput` Component have `unit` state . One of option is `{ name: '---', value: 1 },` in array. Might cause the bug

**Comment by yangwao** [comment]
@vutran6853 let's make PR, can send you $ :)

**Comment by chris-saburo** [comment]
@yangwao @vikiival @roiLeo  let me figure it out this current issue.

**Comment by yangwao** [comment]
Meanwhile fixed
