### ISSUE TITLE
Chain selection shouldn't always redirect to landing

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3569]
I'd like to see better user experience when it comes to switching between BSX<->KSM, current implementation is always redirecting back to landing page (suboptimal). Issue is labeled as research as this could introduce bunch of edge cases, but here's what I can see working:

1. When user browses either of Explore tabs (collections/gallery), changing chain shouldn't redirect to landing, but rather reload explore
2. When user looks at item detail, changing chain may redirect back to explore (if user previously got to item detail through explore)
3. what happens when the user clicks on back button when they are on another chain?
4. ....?

**Comment by prachi00** [comment]
what happens when the user clicks on back button when they are on another chain?

**Comment by petersopko** [comment]
> what happens when the user clicks on back button when they are on another chain?

expanded by your comment :)

**Comment by yangwao** [comment]
This will be obsoleted in 
- #4379
