### ISSUE TITLE
Add download button to the NFT detail

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#357]
It would be nice to have separate download button for the main nft asset. 

The button only shows when the user is owner.

h/t [@deeplogic](https://twitter.com/deepologic)

**Comment by yangwao** [comment]
maybe we can combine it with #219 ?

**Comment by roiLeo** [comment]
Meanwhile 
![Screenshot 2023-04-14 at 09-16-19 Wine dogo KodaDot - NFT Market Explorer](https://user-images.githubusercontent.com/9987732/231971556-28a0a206-1843-45cf-972f-934c399801bc.png)
