### ISSUE TITLE
Vote for KodaDot font

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#358]
It's time to have own which will be used along with design things https://fonts.google.com/
I would like to have something with ligatures and technical font like, Firacode https://github.com/tonsky/FiraCode

Generally, we could stick with Sans styled font? I was looking for google sans but probably it's not public yet

- https://fonts.google.com/specimen/Exo+2?query=exo
- https://fonts.google.com/specimen/Montserrat?query=mont
- https://github.com/nongthaihoang/unicode_google_sans_font ?
- https://fonts.google.com/specimen/PT+Sans?category=Serif,Sans+Serif,Display,Monospace&sort=popularity
- https://fonts.google.com/specimen/Nunito?category=Serif,Sans+Serif,Display,Monospace&sort=popularity
- https://fonts.google.com/specimen/Oxygen?category=Serif,Sans+Serif,Display,Monospace&sort=popularity
- https://fonts.google.com/specimen/Rajdhani?category=Serif,Sans+Serif,Display,Monospace&sort=popularity

**Comment by archnomics** [comment]
Roboto, Newsreader, and Didact Gothic are some.

You can preview it here, I've also added a tagline that could suit Kodadot: Mint your moments, forever.

https://fonts.google.com/?preview.text=Kodadot:%20Mint%20your%20moments,%20forever.&preview.text_type=custom&category=Sans+Serif,Monospace

**Comment by yangwao** [comment]
I've started 🧵 for Obsidian fonts as well, we may inherit some of them from there :)
https://forum.obsidian.md/t/your-favourite-fonts-choice-and-why-thread/18129

**Comment by XyloDrone** [comment]
Is this ready to close and we have decided on Fira Code?

**Comment by roiLeo** [comment]
#1611 related

**Comment by yangwao** [comment]
> Is this ready to close and we have decided on Fira Code?

Yes, it's already done.
