### ISSUE TITLE
Burning NFT should cancel Offers

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3584]
Expanding from @roileo comment here:

why do we need to show burned content?
If it's burned, the offer shouldn't exist anymore

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/3575#pullrequestreview-1051999846_

Currently, burning NFT doesn't affect offers around the NFT at all. I suppose, this is not ideal since it would be only logical to have burning NFT with offers trigger withdrawal / cancellation of offers. 

@vikiival wdyt, what would it take to have it working like this

**Comment by vikiival** [comment]
The joke is:
- that you can burn the nft 
- mint new under the same `id` (we do not support reminting).
- and then the offers are still valid :)

**Comment by roiLeo** [comment]
I'm not able to `withdrawOffer` when I'm the nft creator & the offer has expired or is valid.

how to make it happen?

**Comment by vikiival** [comment]
Back then I made a check that owner should note make offer to its own NFT 🥲. It should be actually an easy fix in the OfferTable
