### ISSUE TITLE
Can't place offers

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#3589]
The minimum offer was supposed to be 10 000 or more; I tried to make an offer and got error:
![image](https://user-images.githubusercontent.com/104380776/181254933-31735d6e-f555-41a8-9a26-13aa0e859375.png)

_Originally posted by @JustLuuuu in https://github.com/kodadot/nft-gallery/issues/3578#issuecomment-1196744902_

**Comment by petersopko** [comment]
zero price at listing is already being tracked here, seems that for the past three days, every NFT has price 0
- https://github.com/kodadot/nft-gallery/issues/3560

however, I'm facing the same error with offer, so I'll just rename this :)

**Comment by petersopko** [comment]
currently unable to place offer, happens both on beta and prod
