### ISSUE TITLE
Error: Unable to retrieve keypair 

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#3591]
### What happened?

Mint not working last 4 hours on RMRK network....

### Please reproduce in steps

classic NFT minting for the collection...

### Expected Behavior

classic NFT minting for the collection

### What browsers are you seeing the problem on?

Chrome, Firefox

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

RMRK

### Screenshots

![obrázok](https://user-images.githubusercontent.com/81104034/181283414-40765d67-54aa-4908-bebf-8fe8367b9d6d.png)

### Payment link for reward

https://kodadot.xyz/transfer?target=FqCJeGcPidYSsvvmT17fHVaYdE2nXMYgPsBn3CP9gugvZR5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
@KngZhi occurred this error recently 🤔🤔🤔

**Comment by KngZhi** [comment]
@jkdizajn  https://docs.kodadot.xyz/tutorials/how-to-fix-error-keypair.html

by the way, @yangwao could you merge [this PR](https://github.com/kodadot/docs/pull/71)?

**Comment by yangwao** [comment]
Seems we should probably handle unable ot retrieve keypair better. Apparently it's some keyring issue?

https://user-images.githubusercontent.com/5887929/181906209-0ab7bcc2-cc2a-4554-ad7b-05434d1421f2.mp4
