### ISSUE TITLE
Spanish translations needs to be updated and other languages as well 

### ISSUE THREAD

**Issue by jcbm123143** [kodadot/nft-gallery#3599]
### What happened?

I changed the language from English to Espanol but not all the words changed to Espanol. Same in other languages.

### Please reproduce in steps

1) Go to change the language selection 
2) Change language 

### Expected Behavior

Other words should also be translated

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Basilisk

### Screenshots

![image](https://user-images.githubusercontent.com/22148449/181595891-b647d6ba-8f17-4b6a-aa90-b4ed7454bbe1.png)

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CFRd1rG6vs8qCW43BVK3KgCdWLyF7HqgT5HxdhN9nWmfq7Em 
https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prachi00** [comment]
Hi , feel free to add your language content here, you can find more information on the [Kodadot documentation](https://docs.kodadot.xyz/contrib-helpers.html#translating-kodadot)

**Comment by spacesmutje** [comment]
Hey there, since I took it upon me to provide the german translation some questions popped up.

I made the fork and started to edit and also checked on some other translations how they went through it, I noticed that it's not making sense to translate every line e.g. gallery/Gallery. Since I want to do it right i would appreciate some guidance :)

Thank you 💯

**Comment by spacesmutje** [comment]
> Hey there, since I took it upon me to provide the german translation some questions popped up.
> 
> I made the fork and started to edit and also checked on some other translations how they went through it, I noticed that it's not making sense to translate every line e.g. gallery/Gallery, since there is basically only a noun. What also puzzled me was that the first line consist of 'translation' and 'english', from my understanding i would fill in the translations under translation and not under english.

Since I want to do it right i would appreciate some guidance :)
> 
> Thank you 💯

**Comment by roiLeo** [comment]
closed in #4001, continue in #3935
