### ISSUE TITLE
Collections Sort Features

### ISSUE THREAD

**Issue by jcbm123143** [kodadot/nft-gallery#3601]
### Is your feature request related to a problem?

Collections are hard to find

### Describe the solution you would like

There should be other sorting features such as lowest to highest, Alphabets A-Z, Hot and Favorites

### Describe alternatives you have considered

To speed up the search of users or collectors

### Screeenshots

![image](https://user-images.githubusercontent.com/22148449/181600309-0efc71a8-66de-43c9-905b-720814f91e77.png)

**Comment by yangwao** [comment]
Something like we have in the gallery? 

![image](https://user-images.githubusercontent.com/5887929/181723018-e6361345-8bb0-4252-8514-a3a95a553728.png)
