### ISSUE TITLE
Profile QR code - unable to scan

### ISSUE THREAD

**Issue by jcbm123143** [kodadot/nft-gallery#3602]
### What happened?

The profile QR code unable to scan using my phone

### Please reproduce in steps

1) Go to Profile
2) Click QR code
3) Scan 

### Expected Behavior

It should be possible to scan my profile QR code using my phone

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

![image](https://user-images.githubusercontent.com/22148449/181602474-b78bf4ee-1a78-47c6-ae1e-2e77377cdeab.png)

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CFRd1rG6vs8qCW43BVK3KgCdWLyF7HqgT5HxdhN9nWmfq7Em https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
https://user-images.githubusercontent.com/5887929/181723508-d54eb19c-1f0e-4f06-901e-8aad0fecec0b.mp4


Seems wfm, maybe you had glare or we can add some checksum to code? Not sure if that's speed's up

**Comment by petersopko** [comment]
wfm without problems
