### ISSUE TITLE
BSX Asset page

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3606]
### Is your feature request related to a problem?

Since BSX on Rococo / Kusama will support Kusama as the currency we will need new /bsx/assets page

### Describe the solution you would like

The solution is pretty straightforward:

- [ ] make a table - asset, balance, actions
- [ ] list tokens that are available to the user
- [ ] make it settable to the chain.

Where to get the data? 
Best to start with the [BalanceList.tsx ;D](https://github.com/galacticcouncil/Basilisk-ui/blob/develop/src/pages/WalletPage/containers/WalletPage/BalanceList/BalanceList.tsx)

### Describe alternatives you have considered

~

### Screeenshots

I really like the implementation of @maht0rz

<img width="1025" alt="Screenshot 2022-07-29 at 12 16 42" src="https://user-images.githubusercontent.com/22471030/181739332-a7036c44-9a5d-4b34-bcab-2f864d699096.png">

[Link](https://app.basilisk.cloud/#/wallet)

**Comment by yangwao** [comment]
We already have one, but deserves better than current bulky design 

https://beta.kodadot.xyz/bsx/assets

**Comment by exezbcz** [comment]
> We already have one, but deserves better than current bulky design
> 
> https://beta.kodadot.xyz/bsx/assets

we already have one, but it is only design :D 

![Desktop - 14 (2)](https://user-images.githubusercontent.com/90852205/211093408-2929ae7a-42b0-460b-bbf7-afc3f27b6bca.png)

**Comment by yangwao** [comment]
Continue to 
- #4119
