### ISSUE TITLE
Developers sub-page

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#361]
We embrace community PRs and PRs made through gitcoin support.

as we plan to be community owned project we would like to have more landing area for new developers

**Comment by yangwao** [comment]
This should go for the /developers or /contribute-to-nft-explorer section? with image of developers, how to enroll, tell we are having bounties, discord &c

**Comment by yangwao** [comment]
We've already have https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md baseline here

**Comment by mattreallycodes** [comment]
I would like to take on this task. I am mattliveshere from Discord. I am estimating 20 hours if I am creating the design and everything to do with this. I can also create any needed graphic assets. Is there a branding guide already established anywhere?

**Comment by yangwao** [comment]
> I am estimating 20 hours if I am creating the design and everything to do with this.

Hey, I guess you can reuse https://nft.kodadot.xyz/carbonless what we have here for this section, 
What would be an advantage of having design or what you want to put there, can you be more verbose about your spent 20 hours?

> Is there a branding guide already established anywhere? 

https://github.com/kodadot/presskit
There is presskit, but we might will be doing rebranding, so for now it would be wasted resource afaik

**Comment by mattreallycodes** [comment]
When is the rebrand happening? 

I want to create something with a nice UI that is like a documentation section where people have a good navigation and content that clearly explains contributing. Part of this would be me creating a wireframe, the content and the other part would be actually implementing this in code.

**Comment by yangwao** [comment]
> I want to create something with a nice UI that is like a documentation section where people have a good navigation and content that clearly explains contributing. Part of this would be me creating a wireframe, the content and the other part would be actually implementing this in code.

How it will be different from https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md ?
So you want to create more like gitbook?

**Comment by mattreallycodes** [comment]
Yes exactly. I would rather do something like that. Is going with Gitbook also a possible option?

**Comment by mattreallycodes** [comment]
@yangwao What are your thoughts? Can we go ahead and put this in the pipeline of tasks being worked on?

**Comment by yangwao** [comment]
Hey, we meanwhile having gitbook, so don't want to waste resources on creating a wheel. Better keep it lean if you want to make it

**Comment by hisergiorojas** [comment]
I would like to work on this issue.

**Comment by yangwao** [comment]
Continue to #1933
