### ISSUE TITLE
BSX check which asset is used for the fees

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3610]
### Is your feature request related to a problem?

Since you can pay fees in multiple currencies it would be nice to have a visual component that talks about says about it.

<img width="242" alt="Screenshot 2022-07-29 at 13 48 44" src="https://user-images.githubusercontent.com/22471030/181752511-aa5f969d-5223-41a2-9c98-a228d1c82cb5.png">

### Describe the solution you would like

This component should be visible in: 
- [ ] Create Collection
- [ ] Create Token
- [ ] Gallery Item (aka actions)
- [ ] Transfer?

### Describe alternatives you have considered

Alternatively we can show the fees and currency

<img width="306" alt="Screenshot 2022-07-29 at 15 58 59" src="https://user-images.githubusercontent.com/22471030/181776308-63e7ddff-e1f7-4e82-9884-f4172157e1c5.png">

<img width="297" alt="Screenshot 2022-07-29 at 15 58 46" src="https://user-images.githubusercontent.com/22471030/181776363-9761b4f9-efff-47c1-93e3-1ddef6b669e6.png">

the inspiration could be a simple mint

<img width="558" alt="Screenshot 2022-07-29 at 16 00 08" src="https://user-images.githubusercontent.com/22471030/181776610-38ccd4b9-bbc3-4914-b921-9b54442e46df.png">

**Comment by roiLeo** [comment]
🤔

**Comment by roiLeo** [comment]
![2rxo07](https://github.com/kodadot/nft-gallery/assets/9987732/123482dc-c9ff-432d-ab8d-dc1fc4a698bc)
