### ISSUE TITLE
It gets stuck sometimes in the mobile version - Novawallet

### ISSUE THREAD

**Issue by jrafaelangarita** [kodadot/nft-gallery#3623]
### What happened?

sometimes it doesn't optimize well and won't let me navigate through the sections, this means it won't let me go down or up

### Please reproduce in steps

go to, novawallet, paste the link of the beta, and do it several times, at least once it must happen

sometimes when it refreshes it already lets me move freely

### Expected Behavior

that you can always navigate without problems, without having to refresh until the page optimizes well

### What browsers are you seeing the problem on?

Mobile Android Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Screenshots

https://user-images.githubusercontent.com/84519335/181916188-5a56d48d-f18f-4c22-979c-26002b73f06f.mp4

https://user-images.githubusercontent.com/84519335/181916190-3504acd7-ac27-40ee-8d4e-fdd677d5a150.mp4

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petersopko** [comment]
I can confirm, that current NovaWallet experience has it's flaws, I was unable to mint from my phone recently

**Comment by yangwao** [comment]
hey @jrafaelangarita it's still happening?

**Comment by daiagi** [comment]
ancient bug on old ui
assuming we can close it
@yangwao
