### ISSUE TITLE
I can't upload files from novawallet - to create a collection

### ISSUE THREAD

**Issue by jrafaelangarita** [kodadot/nft-gallery#3624]
### What happened?

try to create a collection in novawallet, but it does not open the file folder, to be able to upload

### Please reproduce in steps

open novawallet, go to beta link, connect your account, click on create - classic - try to upload some file

### Expected Behavior

the file folder opens and you can upload your img or file

### What browsers are you seeing the problem on?

Mobile Android Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Screenshots

https://user-images.githubusercontent.com/84519335/181916852-ea15e311-2998-4aaa-a87e-953873d6acf1.mp4

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
hey @jrafaelangarita thanks for reporting, is this still happening?

**Comment by jrafaelangarita** [comment]
Hey, not, i just tried now, and work from my side in Novawallet

**Comment by yangwao** [comment]
> [jrafaelangarita](/jrafaelangarita)

thank you!
