### ISSUE TITLE
minting on rmrk currently doesn't work

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3630]
we're once again facing problems with our minting, according to what I've gathered from @vikiival, there's an issue with our indexer and subsquid. we know about this and it should be hopefully resolved soon

**Comment by cryptodamsky** [comment]
What’s the status of this? I just minted a collection, re https://kusama.subscan.io/extrinsic/13857023-5 but it isn’t anywhere. Should i start new issue?

**Comment by yangwao** [comment]
there was just recent push to the production, should be live in 5-10 minutes https://github.com/kodadot/nft-gallery/commit/d560fc381a1ebd2f3233b280760acfe933d43aa2

**Comment by petersopko** [comment]
minted collection, minted nft
