### ISSUE TITLE
MoonRiver & MoonBeam compatibility v0

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3647]
Currently, we are using for Moonsama [Click](https://github.com/kodadot/click), which is using an old implementation of SubSquid. 
For example, we encounter some bugs on the old version, like not correctly catching mint events, and it's not supported by SQ team. We will be upgrading to FireSquid, from the fresh template.

### What will be done
- Migrate Click to FireSquid 
  - https://github.com/kodadot/click/issues/22 
- Data for rarities
  - https://github.com/kodadot/click/issues/12
  - https://github.com/kodadot/click/issues/23
  - #3181
- Holdings 
  - #3182 
- Deploy indexer for MoonBeam 
- #4019
  - add endpoints to the vuex-options 
- https://github.com/kodadot/nft-gallery/issues/3891
- making sure current components work with MoonRiver & MoonBeam (can expand on the issues once it is live)
  - explorer
  - https://github.com/kodadot/nft-gallery/issues/4020
  - https://github.com/kodadot/nft-gallery/issues/4021
  - https://github.com/kodadot/nft-gallery/issues/4022
  - https://github.com/kodadot/nft-gallery/issues/4023
  - https://github.com/kodadot/nft-gallery/issues/4028
      - gallery item detail
      - collection view
      - holders
      - flippers
      - charts
      - history of the collection

### minor 
- https://github.com/kodadot/nft-gallery/issues/3931 

### Are you the owner of the EVM collection based on MoonRiver or MoonBeam?
- We will be dropping survey form where we will be collecting particular information like
  - Technical ones
    - At which network is your collection? MoonBeam/MoonRiver
    - What's the contract address?
    - It's ERC721 / ERC1155 ? (boolean)
    - URL to verified contract on Moonscan.io https://moonriver.moonscan.io/ https://moonbeam.moonscan.io/
    - Github repository for contract (optional)
    - Technical person who we can reach in case futher technical questions (tg/discord best)
  - What's a Twitter of your collection?
  - What's the website of your collection?
  - What's the discord of your collection?
  - What's Twitter of collection creator?

### Ref
- https://github.com/kodadot/nft-gallery/issues/3161

**Comment by cryptodamsky** [comment]
https://form.kodadot.xyz/evm Let’s see.
