### ISSUE TITLE
remove the units of the market place

### ISSUE THREAD

**Issue by jrafaelangarita** [kodadot/nft-gallery#3657]
### Is your feature request related to a problem?

this will only bring confusion, in the basilisk swap test people hated it and it was removed

### Describe the solution you would like

stay with the base unit, be it bsx or ksm, no micro ksm or micro bsx, etc

### Describe alternatives you have considered

.

### Screeenshots

![Screenshot_89](https://user-images.githubusercontent.com/84519335/182628830-61dbb18e-52b8-470b-804e-5fbb92b7f0f8.png)

**Comment by petersopko** [comment]
@vikiival is working already on implementation of this

**Comment by petersopko** [comment]
@jrafaelangarita thanks for bringing this to our attention tho :)
