### ISSUE TITLE
Implement block explorer for BSX

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3671]
### Is your feature request related to a problem?

Currently both SandBox and Rococo does not contain blockexplorer

### Describe the solution you would like

I would like to have Calamari block explorer by @topmonks for better debugging 

### Describe alternatives you have considered

Other parachains have subscan

https://basilisk.subscan.io/

### Are there opened related issues?

Blocked by topmonks/calamar#10

**Comment by vikiival** [comment]
Blocked by topmonks/calamar#10

**Comment by roiLeo** [comment]
closed in #3661
