### ISSUE TITLE
E2E and Unit Testing

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3682]
Cypress E2E: 
- [x] #3965
- [x] #3841
- [x] #3971
- [ ] #3681
- [ ] #3764
- [ ] #3775
- [ ] #3776 
- [x] #3755
- [x] #3679
- [x] #3680
- [x] #3760
- [x] #3750

Vitest Unit tests:
- [x] #3586 
- [x] #2964

GraphQL queries test:
- [ ] #2028

**Comment by roiLeo** [comment]
- link #7826

**Comment by vikiival** [comment]
Closing for sake of #7826
