### ISSUE TITLE
Issue re: Unlist the nft, after it was sent as a gift

### ISSUE THREAD

**Issue by jrafaelangarita** [kodadot/nft-gallery#3687]
### What happened?

I sent an nft as a gift, to check that it was fixed and when entering the other account (n2), the nft is still listed (action performed in the original account or n1)

### Please reproduce in steps

list a nft, send it like gift, check on the receive adress, that is still listed

### Expected Behavior

being a gift, it should not save the previous action, and should  unlist the nft, otherwise, it may be bought and the owner does not notice

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### Screenshots

![Screenshot_98](https://user-images.githubusercontent.com/84519335/183131487-4108f293-72e3-440a-b7d6-f96fdba36775.png)
![Screenshot_99](https://user-images.githubusercontent.com/84519335/183131490-27f4e260-93fb-4e65-99bd-6aec9e6872d3.png)

### Payment link for reward

https://kodadot.xyz/transfer?target=Hy8UnZSNvchEzKLBZ6X6qXq6xc8gVNGyo8ALuuNUXeTiD6K&usdamount=10&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
@petersopko 👀

**Comment by petersopko** [comment]
tested this, still a problem, I've followed up in https://github.com/kodadot/snek/issues/56 since this is most likely going to get solved at indexer level

**Comment by vikiival** [comment]
This should be implemeted by either:
- [ ] in Basilisk Node as extension of the runtime pallet
- [ ] in KodaDot NFT gallery that should perform `batchAll[unlist, transfer]`

_Originally posted by @vikiival in https://github.com/kodadot/snek/issues/56#issuecomment-1255604590_

**Comment by roiLeo** [comment]
Can't this be fixed with kodadot/snek#99 since we do the same for rmrk chain?

**Comment by vikiival** [comment]
> Can't this be fixed with https://github.com/kodadot/snek/pull/99 since we do the same for rmrk chain?

Unfortunately no. The Basilisk works way differently than "RMRK", If we unlist the token on the `snek's` side,the NFT is still available on-chain to buy :)

So the only possible options are two mentioned above

**Comment by yangwao** [comment]
@jrafaelangarita hey thanks for reporting; it was "fixed" you can try it now

sending bounty for reporting it! 

pay 30 USD

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 22.29 USD/KSM ~ 1.346 $KSM
🧗 [Hy8UnZSNvchEzKLBZ6X6qXq6xc8gVNGyo8ALuuNUXeTiD6K](https://kusama.subscan.io/account/Hy8UnZSNvchEzKLBZ6X6qXq6xc8gVNGyo8ALuuNUXeTiD6K)
🔗 [0xb4728427053fd947a79c4d94b170deb3756ed9164e7385cf5c5d62bfd510d53e](https://kusama.subscan.io/extrinsic/0xb4728427053fd947a79c4d94b170deb3756ed9164e7385cf5c5d62bfd510d53e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
