### ISSUE TITLE
Popular collection list for bsx once we will be live

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3694]
Do I need to show popular collection list for bsx? Currently I hide it because there is no issue for it.
```
<div v-if="prefix === 'rmrk' || prefix === 'bsx'">
        <LazyGalleryLatestSales class="my-5" />
        <LazyGalleryPopularCollections class="my-5" />
        <span v-if="prefix === 'rmrk'">
          <LazyGalleryPopularCollections class="my-5" />
        </span>
        <LazyGalleryNewestList class="my-5" />
</div>
```

> I think once we will be live we can show some popular collections :)

_Originally posted by @zhengow in https://github.com/kodadot/nft-gallery/issues/3693#issuecomment-1207352638_

**Comment by roiLeo** [comment]
Meanwhile this has been replaced by `CarouselTypeSpotlight` on new landing
