### ISSUE TITLE
Packs (collection of collections)

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#37]
- Similiar to this https://opensea.io/collection/meme-ltd
- Show # 
  - [x] items
  - [ ] owners 
  - [ ] price but I would discard it as lot of counting
- List of collection covers
- List of particular items in collections
- Links to the 
  - [ ] medium
  - [ ] twitter
  - [ ] telegram
  - [ ] website

**Comment by vikiival** [comment]
Fields 
- [ ] image (cover) 
- [ ] metadata (socials)
- [ ] owner
- [ ] List<Collection>
- [ ] List<NFTs>

**Comment by vikiival** [comment]
So far packs can save only NFTs (We will see if Collection is needed).
Links can be extracted from #134 
Other data are omitted for readability.
