### ISSUE TITLE
Minted a collection, it’s nowhere

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#3704]
### What happened?

Minted a collection, it’s nowhere

### Please reproduce in steps

Minted a collection, went to nft section, can’t choose it

TX id: https://kusama.subscan.io/extrinsic/13928664-6

### Expected Behavior

/

### What browsers are you seeing the problem on?

Firefox

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

RMRK

### Screenshots

<img width="762" alt="image" src="https://user-images.githubusercontent.com/92786519/183606763-2b7c7595-75fe-4201-8903-be8f30f30fc6.png">

The collection was called "9 days to dusk campaign POAP"

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petersopko** [comment]
just minted collection and it appeared after a while, that's the reason we added the explainer to wait 😄 If you still cannot see yours, maybe there's something else wrong.

**Comment by cryptodamsky** [comment]
I mean, it has been 12 minutes at the time of post, how long should i wait? 🗡️

**Comment by petersopko** [comment]
> I mean, it has been 12 minutes at the time of post, how long should i wait? 🗡️
> 
> Users coming to mint wanna wait like 15 seconds, then go elsewhere

obviously that's a lot, it's usually within 1 minute max for me, my guess is, it's Firefox again.

Can you try to delete your cookies/open up browser in incognito mode, log in again and see if the collection shows up or not?

**Comment by vikiival** [comment]
So the issue is: 

You minted collection `9 Days to Dusk gleam campaign POAP`
```json
{
  "id": "1A7D6F18E9619FEF3E-POAP",
  "symbol": "POAP",
  "issuer": "DB42NYKDERAAK8fbgJtuYCsxNMmLrbzT1m4DNAK9Koxez3S",
  "name": "9 Days to Dusk gleam campaign POAP",
  "max": 0,
  "metadata": "ipfs://ipfs/bafkreiclydw2vzne2vgostuki6ldz2uog43hkc3wqidnnvcl2izqgju2zm"
}
```

But your collection `Metahours 12 POAP`

```json
{
  "id": "1A7D6F18E9619FEF3E-POAP",
  "symbol": "POAP",
  "issuer": "DB42NYKDERAAK8fbgJtuYCsxNMmLrbzT1m4DNAK9Koxez3S",
  "name": "Metahours 12 POAP",
  "max": 0,
  "metadata": "ipfs://ipfs/bafkreieqy34m6gu35srzyrlgaagnpn5egf6hvf3aeuefngevnuxucjtxd4"
}
```

has the same `ID` field - which is illegal - therefore collection hasn't been processed.

Please try to mint it with different symbol (it has to be unique).

Meanwhile we can top up the issue existing issue:

- #212

**Comment by cryptodamsky** [comment]
Yeah ok but why can’t we have more than one symbol? I’d like to use that symbol for poap stuff, otherwise i dont really understand why its there if i cant use the same symbol again. Imagine thousands come minting and cannot create collection bcz of used symbol :D

**Comment by vikiival** [comment]
>  Imagine thousands come minting and cannot create collection bcz of used symbol :D

Soooo if i'll make a smart contract and i'll name it USDC can I tell u it's a stable coin? 

The alternative is just to remove the sybol and yolo

**Comment by cryptodamsky** [comment]
> > Imagine thousands come minting and cannot create collection bcz of used symbol :D
> 
> The alternative is just to remove the sybol and we will generate it

I’d go for that. Right now when i’m minting something, im feeling like.. hmm.. what if this symbol was used already. It’s sort of pointless to have it there for end user
