### ISSUE TITLE
RMRK 2.0 implementation v0

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3725]
Been briefly chatting with @vikiival and decided to support RMRKv2 as well

Right now, chatting within internal circles as it consists few issues across our ecosystem tools to extend support for this.
Also looking candidates who made more than few PRs to Rubick to be eglible for this task ;)

### Ref 
- Tests for RMRK 2.0 https://github.com/rmrk-team/rmrk-tools/tree/master/test/2.0.0
- https://github.com/kodadot/rubick/issues/60
- https://github.com/kodadot/packages/issues/42
- extend minimark with RMRK 2.0 https://github.com/kodadot/packages/tree/main/minimark
- https://github.com/kodadot/nft-gallery/issues/4013

**Comment by vikiival** [comment]
🫡 yes sir we'll be prio for next few days

**Comment by yangwao** [comment]
> yes sir we'll be prio for next few days
- @joelamouche check #5028 it's moving 😎

@vikiival probably list all outstanding rmrk2 issues we have across KodaDot org?

**Comment by yangwao** [comment]
Use `rmrk` label for 🔎

https://github.com/kodadot/nft-gallery/issues?q=is%3Aissue+is%3Aopen+label%3Armrk

**Comment by vikiival** [comment]
> @vikiival probably list all outstanding rmrk2 issues we have across KodaDot org?

I think the most critical ones were flexed by @preschian.

I am currently flexing this
- https://github.com/kodadot/rubick/issues/188 

and will do redeploy

**Comment by yangwao** [comment]
Phase 0 done ✅

Continue to 
- #5493 


Hey @joelamouche feel free to test https://rmrk2.kodadot.xyz/rmrk2/explore/items?listed=true&page=1 and feel free report any bug you notice https://github.com/kodadot/nft-gallery/issues/new?assignees=&labels=rmrk2%2Cbug%2Cp2&template=rmrk2_bug.yml&title=Be+descriptive+and+short

**Comment by joelamouche** [comment]
Nice! The Subtraknight items are displaying web. I will make a deeper review later...
When will equipable NFTs implemented with rmrk2.0? This is a very important feature for Substraknights

**Comment by vikiival** [comment]
> When will equipable NFTs implemented with rmrk2.0? This is a very important feature for Substraknights

Should be implemented but happy to have a call for deeper understanding
