### ISSUE TITLE
Token management

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3728]
### Is your feature request related to a problem?

Last things to implement for Basilisk Rococo 
- [ ] fetch and subscribe balances for the tokens.
- [ ] replace fetch in snek components to use state
- [ ] fetch tokens in the beginning of the app
- [ ] fallback for single tokened chains (kusama, bsx sandbox)

### Describe the solution you would like

~

### Describe alternatives you have considered

~

**Comment by yangwao** [comment]
when landing 👀
<img src="https://media2.giphy.com/media/3orif8CHtteQvHcYM0/giphy.gif"/>

**Comment by yangwao** [comment]
All done in ?
- #3784
