### ISSUE TITLE
websocket is not connected

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3732]
Minted NFT but second transaction (list) threw an error:
![image](https://user-images.githubusercontent.com/73316633/184661063-172a2456-f52d-470e-a0f0-e09529cf1b53.png)

**Comment by petersopko** [comment]
trying to transfer some BSX:
![image](https://user-images.githubusercontent.com/73316633/184667876-85b71471-dea5-4e84-b518-10daf05fd8ef.png)

**Comment by roiLeo** [comment]
continue in #7670
