### ISSUE TITLE
Audio previews on twitter

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#375]
Hi all my friends, for a better social sharing of audio tracks we could do twitter previews like audius? It is possible?

https://user-images.githubusercontent.com/81104034/118238579-f8f88f80-b498-11eb-9207-c91ab8577df7.mp4

**Comment by yangwao** [comment]
Seems there is under https://ogp.me/ `og:audio`, we just need to determine what kind of media type is it for crawlers. 
We can also use og:type for music extension:)

**Comment by roiLeo** [comment]
ref #3242

**Comment by JustLuuuu** [comment]
we have that
