### ISSUE TITLE
3D objects are broken on gallery item detail 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3751]
https://beta.kodadot.xyz/rmrk/gallery/14024356-7CF9DAA38281A57331-APO-11-0000000000000011

![image](https://user-images.githubusercontent.com/5887929/184874931-e9f55f2d-53a1-4a62-8692-11dfd768d31c.png)
l

please test with basilisk 3D objects as well �

It seems in "more from this collection", it works 👀

https://user-images.githubusercontent.com/5887929/184875364-0c257064-56e0-4872-939f-9e42fc93d69a.mov

**Comment by zhengow** [comment]
It works for me:
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/38389586/184875788-8a71d751-138a-4c08-803e-49ccd8ddf615.png">

Maybe network problem?

**Comment by yangwao** [comment]
more likely sounds like some weird cache issues even on incognito? 
because in strip below it's loaded 👀 but when I click on it it won't load 😅🤔
and when I hit empty cache at least two times then it loads 😅 

https://user-images.githubusercontent.com/5887929/184876747-98b4a68d-03f6-44f2-8354-9bb885b97515.mov

**Comment by yangwao** [comment]
Seems to be related issue on the creator's profile as well.
Some loads, some not?

https://beta.kodadot.xyz/rmrk/u/FQBgFrkzevAZCvFZB485rQa6h7gsZQz3UXRuYwxAzG7zQ4w?tab=nft&page=1

![image](https://user-images.githubusercontent.com/5887929/184879678-0645d84e-2e3d-46bb-b13a-58d6ecbbc47b.png)

**Comment by yangwao** [comment]
3D objects are not showing 😄

https://beta.kodadot.xyz/rmrk/collection/7CF9DAA38281A57331-APO?tab=items

![image](https://user-images.githubusercontent.com/5887929/184880206-ef321090-a532-49e0-8449-9d36fd6faa38.png)

**Comment by roiLeo** [comment]
> 3D objects are not showing 😄

Loads well for me in #3718 

https://deploy-preview-3718--koda-nuxt.netlify.app/rmrk/collection/7CF9DAA38281A57331-APO?tab=items&page=1

**Comment by yangwao** [comment]
oh nice, yes works for me 

https://deploy-preview-3718--koda-nuxt.netlify.app/rmrk/u/FQBgFrkzevAZCvFZB485rQa6h7gsZQz3UXRuYwxAzG7zQ4w

![image](https://user-images.githubusercontent.com/5887929/184886491-9115bd82-9ff9-4c19-9e81-32e28a358165.png)
