### ISSUE TITLE
Newest list has showing recent listing price instead old one?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3752]
- I've bought NFT for 10000 BSX 
- List it for 333333 BSX 
- Noticed on landing it's shows at newest list, recent price on second card, where should show old one - 10000 BSX 

![image](https://user-images.githubusercontent.com/5887929/184882998-6c9e3586-be26-4e55-8b29-d10b6e649b08.png)

### Case 
https://beta.kodadot.xyz/bsx/gallery/1643292083-2

![image](https://user-images.githubusercontent.com/5887929/184883353-90c631b9-2513-414c-9399-34c683991a06.png)

**Comment by zhengow** [comment]
👋

**Comment by zhengow** [comment]
So it should show the latest trade price instead of listing price? What about the fresh mint nft without trade history?
