### ISSUE TITLE
Bugs on Basilisk v0.2 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3756]
Current bugs we are aware.
Same flow as from #3368 

# Sorted by severity (higher, more critical)
- [ ] #3790
- [ ] #3138
- [ ] #3350
- [x] #3395 
- [x] #3291
- [x] #3235 
- [x] #3423 
- [x] https://github.com/kodadot/nft-gallery/issues/4000
- [x] #3752

**Comment by petersopko** [comment]
closing this since we're tracking rest of the issues (not all of them bugs) in 
- #3648
