### ISSUE TITLE
Writing interface for NFT novels ✍️

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#378]
- [ ] markdown-first
- [ ] choose from 7 fonts - we can use fron https://github.com/kodadot/nft-gallery/issues/358
- [ ] add your own font
- [ ] long form text interface
- [ ] short form reading
- [ ] writing interface like what you see what you get
- [ ] highlight interface
- [ ] quotations
- [ ] nested forms, like 🔗 it together
- [ ] map of 🔗🔗 texts
- [ ] support mermaid for graphs?

**Comment by XyloDrone** [comment]
I can do the UI for this when I come back from my break. How urgent is it?

**Comment by katerwauler** [comment]
Very excited to see this on the docket 😀 I have previous written a serial novel (well, about 50k words of it, it was never fully finished as it was a fan work and I decided my time was best spent on original works) and I posted it to a simple Wordpress blog interface. I think it's important to have at least everything I had there in order for this kind of interface to catch on. Here's an example post: https://piratesinspace.augustwritesabook.com/post/145152343526/a-mutiny-of-pirates-being-an-account-of-the-damn

- [ ] Image/illustration, upload + rendering with story
- [ ] Tags so posts and chapters are easily searchable
- [ ] Easy-to-read formatting - fonts are important but more important is spacing and contrast
- [ ] A place for credits (in Wordpress I just add a paragraph and links at the end, would be neat to formalize this as a UI component)
- [ ] A way to create pages for world-establishing info like character bios or a summary of the story itself
- [ ] Links to the next and previous posts

As I think of more I will add 😊

**Comment by yangwao** [comment]
What lovely feedback! 

> Image/illustration, upload + rendering with story

How would that rendering work? Do you mean something like the preview?

> Tags so posts and chapters are easily searchable

I guess we already have tags and the search is already there, so hopefully won't be an issue :)

> A place for credits (in WordPress I just add a paragraph and links at the end, would be neat to formalize this as a UI component)

Something like references block or for footnotes?

> Links to the next and previous posts

This would be quite harder to be on-chain, however, it can be computed if it would be serialized posts for example

Pretty excited to see this live :)

**Comment by katerwauler** [comment]
> How would that rendering work? Do you mean something like the preview?

Basically, the way the image-based NFT viewing works now, there's the image showing at the top, but that is also the main "product" itself, so it makes sense to display it front and center that way. I am imagining that for NFT novels, the main "product" is the words, with the image providing a supplementary opportunity for the writer to express themselves. So maybe it would need to be rendered a bit differently on the page when it was a text-first NFT vs. an image-first NFT.

> Something like references block or for footnotes?

Yes, that would be great! Some pieces require explanation that does not belong in the main text itself, and footnotes or references are pretty conventional for all kinds of successful publishing today :)

> This would be quite harder to be on-chain, however, it can be computed if it would be serialized posts for example

I know very little about blockchain so not sure how possible it is ;) but it is important for navigating through a serial story, which I imagine a collector would do before buying.

**Comment by yangwao** [comment]
Find the part of issues writing interface that could be fetched here https://github.com/kodadot/nft-gallery/issues/213#issuecomment-838127837 but seems closed already.

**Comment by yangwao** [comment]
Just for inspiration what's used by **PRO** writers out there https://www.literatureandlatte.com/scrivener/overview

**Comment by yangwao** [comment]
> Basically, the way the image-based NFT viewing works now, there's the image showing at the top, but that is also the main "product" itself, so it makes sense to display it front and center that way. I am imagining that for NFT novels, the main "product" is the words, with the image providing a supplementary opportunity for the writer to express themselves. So maybe it would need to be rendered a bit differently on the page when it was a text-first NFT vs. an image-first NFT.

@katerwauler I mean, would be nice to sketch something in Figma maybe? Or if we find UI/UX person on this, you can help us through to guide? :)

> Yes, that would be great! Some pieces require explanation that does not belong in the main text itself, and footnotes or references are pretty conventional for all kinds of successful publishing today :)

Agree here, citations, quotation and references are important IP properties:)

> I know very little about blockchain so not sure how possible it is ;) but it is important for navigating through a serial story, which I imagine a collector would do before buying.

This is where we can help navigate through, happy to be on this adventure! 🤍

**Comment by katerwauler** [comment]
@yangwao - love Scrivener! (Ava is a master.) it has tons of inspiration and ideas we can use.

> I mean, would be nice to sketch something in Figma maybe? Or if we find UI/UX person on this, you can help us through to guide? :)

yes, somehow I didn't realize Figma was free to access since I have to have a license for my work 😂 I will put this on my list of to-dos and get back to you soon!

**Comment by XyloDrone** [comment]
Any updates on this? happy to jump on the ux/ui design

**Comment by cryptodamsky** [comment]
Inspiration: 

https://github.com/bencodezen/vuepress-blog-boilerplate

**Comment by JustLuuuu** [comment]
we have this: https://kodadot.xyz/blog
