### ISSUE TITLE
Search while write doesn't work

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3782]
We've recently added Indices to make the search work while you typing fast.

https://github.com/kodadot/rubick/issues/123#event-7177423257

but seems it doesn't work

Might it be resolved in #3360 ?

### Testing cases
- Spirit Key
- Skullz Art

![image](https://user-images.githubusercontent.com/5887929/185402993-74a505fa-d173-4f5c-aa97-610055b52668.png)

![image](https://user-images.githubusercontent.com/5887929/185403273-fa619cf9-2577-4f7a-b4b0-c7e935897431.png)

![image](https://user-images.githubusercontent.com/5887929/185403589-b37d5471-f71f-4454-aace-69e8dbbafec0.png)

OR it works on some terms only? why 👀

![image](https://user-images.githubusercontent.com/5887929/185403684-73b5d513-0910-4c2f-880e-5b805767dc22.png)

**Comment by Jarsen136** [comment]
> Might it be resolved in #3360 ?
> 

Yeah, I think so.

**Comment by yangwao** [comment]
yes, seems it's working in #3763
