### ISSUE TITLE
"See More" button not work

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#3793]
### What happened?

"See more" button is not working properly
When clicked, the message "Network error: response not successful: received status code 400" appears.

The button points to the following link: 
https://kodadot.xyz/rmrk/explore/?page=1&sort=UPDATED_AT_DESC&tab=GALLERY

Please fix its functionality

![obrázok](https://user-images.githubusercontent.com/81104034/185683197-683f03f9-f5f1-4cf0-84ca-f7eca6eb5bbd.png)
![obrázok](https://user-images.githubusercontent.com/81104034/185683306-bcb6b22e-dc30-4f4f-a8f1-cf90475b9c11.png)

### Please reproduce in steps

1. Open https://kodadot.xyz/
2. Scrol down to "Newest List, Discover the latest items on sale"
![obrázok](https://user-images.githubusercontent.com/81104034/185683847-bb5ef5f1-8b31-4c6a-b11b-ddc0172ad1f9.png)
3. Click "See more"

### Expected Behavior

I was expecting to see the last NFTs for sale

### What browsers are you seeing the problem on?

Firefox

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

RMRK

### Screenshots

screenshots are above

### Payment link for reward

https://kodadot.xyz/transfer?target=FqCJeGcPidYSsvvmT17fHVaYdE2nXMYgPsBn3CP9gugvZR5&usdamount=&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
This will be fix in new release (works on beta.kodadot.xyz)

**Comment by roiLeo** [comment]
This will be fix in new release (works on beta.kodadot.xyz)

**Comment by yangwao** [comment]
yes, this is already fixed on https://beta.kodadot.xyz will be in released in ten minutes on https://kodadot.xyz
