### ISSUE TITLE
Statemine explorer not working

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#3796]
#### Step to reproduce
- go to beta
- click on statemine chain
- click on explorer (https://beta.kodadot.xyz/statemine/explore)
- infinite loading (#3351 related)
- profit

Should we keep maintain this chain?

Some logs:
```
Object { message: "Unknown  type \"CollectionEntityWhereInput\". Did you mean  \"CollectionEntitiesEdge\", \"CollectionEntityFilter\",  \"CollectionEntitiesOrderBy\", or \"CollectionEntity\"?", extensions: {…} }
--
1 | Object { message: "Unknown  type \"CollectionEntityOrderByInput\". Did you mean  \"CollectionEntitiesOrderBy\", \"CollectionEntityFilter\",  \"CollectionEntitiesEdge\", or \"CollectionEntity\"?", extensions: {…} }
2 | Object { message: "Value  \"blockNumber_DESC\" does not exist in \"CollectionEntitiesOrderBy\"  enum. Did you mean the enum value \"BLOCK_NUMBER_DESC\" or  \"BLOCK_NUMBER_ASC\"?", extensions: {…} }
3 |  
```
I sense it still use old magick endpoint (not subsquid)

**Comment by petersopko** [comment]
this is still relevant, I wonder whether we should temporarily disable Statemine as an option in chain-select, since it's non-functional? or raise priority / give bounty to fixing this? @yangwao

**Comment by yangwao** [comment]
We've deprecated Statemine and will be rolling it back in

- #4088 

> Should we keep maintain this chain?

not now
