### ISSUE TITLE
BSX landing lastNftListEvent

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#3797]
Since #3786 we don't have data in bsx landing page (Latest Sales & Newest List components)

Error log:
```
0 | Object { message: "Cannot query field \"animationUrl\" on type \"LastEventEntity\".", extensions: {…} }
-- | --
message | "Cannot query field \"animationUrl\" on type \"LastEventEntity\"."
extensions | Object { code: "GRAPHQL_VALIDATION_FAILED", exception: {…} }
code | "GRAPHQL_VALIDATION_FAILED"
```

We need to extend https://github.com/kodadot/snek with the same PR done in https://github.com/kodadot/rubick

**Comment by roiLeo** [comment]
meanwhile https://github.com/kodadot/snek/pull/58

**Comment by yangwao** [comment]
Nice catch!
More likely subsquid 
![image](https://user-images.githubusercontent.com/5887929/185752831-e234f184-6234-4375-aba1-7d6d81a0f4e6.png)

**Comment by vikiival** [comment]
Releasing!
https://github.com/kodadot/snek/actions/runs/2895166670

**Comment by yangwao** [comment]
✅

![image](https://user-images.githubusercontent.com/5887929/185754433-ba575e07-a910-476f-8660-b33578c437a8.png)

**Comment by vikiival** [comment]
⌘
