### ISSUE TITLE
Buy order fails

### ISSUE THREAD

**Issue by spacesmutje** [kodadot/nft-gallery#3821]
### What happened?

Wanted to buy a fine NFT on kodadot.xyz, but after clicking buy i receive this error message:

![Screenshot 2022-08-23 21 39 32](https://user-images.githubusercontent.com/106772187/186251375-5e50e51a-830b-4f51-accb-979e66ec97a6.png)

### Please reproduce in steps

- I went into the collection via this link posted on Discord [link](https://discord.com/channels/840514076538830888/844878365520691210/1010466665542189067)
- browsed the collection [Dog Sunset](https://kodadot.xyz/rmrk/collection/900D19DC7D3C444E4C-DOGSUN)
- decided to go for no. 22
- connected my wallet via talisman
- clicked on buy
- received the error code as shown in the screenshot

### Expected Behavior

After clicking the buy button, i expected to have this fine piece of art in my wallet. I don't know what else to say here :

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### At which chain did you encounter bug?

RMRK

### Screenshots

[Screen recording 2022-08-23 22.00.27.webm](https://user-images.githubusercontent.com/106772187/186254769-f68beb5d-4548-4cec-8234-a1f19d86fdf9.webm)

### Relevant log output

```shell
DevTools failed to load source map: Could not load content for chrome-extension://cmndjbecilbocjfkibfbifhngkdmjgog/lib/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://fijngjgcjhjmmpcmkeiomlglpeiijkld/content_script.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://fijngjgcjhjmmpcmkeiomlglpeiijkld/page.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
63d76e4.modern.js:1          POST https://api.subquery.network/sq/vikiival/magick 400
(anonymous) @ 63d76e4.modern.js:1
e @ 63d76e4.modern.js:1
value @ 63d76e4.modern.js:1
(anonymous) @ 63d76e4.modern.js:1
Promise.then (async)
(anonymous) @ 63d76e4.modern.js:1
e @ 63d76e4.modern.js:1
value @ 63d76e4.modern.js:1
(anonymous) @ 63d76e4.modern.js:1
e @ 63d76e4.modern.js:1
value @ 63d76e4.modern.js:1
e.getObservableFromLink @ 63d76e4.modern.js:1
(anonymous) @ 63d76e4.modern.js:1
e.fetchRequest @ 63d76e4.modern.js:1
(anonymous) @ 63d76e4.modern.js:1
(anonymous) @ 63d76e4.modern.js:1
(anonymous) @ 63d76e4.modern.js:1
(anonymous) @ 63d76e4.modern.js:1
lo @ 63d76e4.modern.js:1
e.fetchQuery @ 63d76e4.modern.js:1
e.observeQuery @ 63d76e4.modern.js:1
t.setUpQuery @ 63d76e4.modern.js:1
t.onSubscribe @ 63d76e4.modern.js:1
(anonymous) @ 63d76e4.modern.js:1
e @ 63d76e4.modern.js:1
value @ 63d76e4.modern.js:1
(anonymous) @ 63d76e4.modern.js:1
t.result @ 63d76e4.modern.js:1
(anonymous) @ 63d76e4.modern.js:1
e.query @ 63d76e4.modern.js:1
e.query @ 63d76e4.modern.js:1
value @ 63d76e4.modern.js:1
(anonymous) @ 5df22ec.modern.js:1
r @ 357a4ab.modern.js:1
l @ 357a4ab.modern.js:1
(anonymous) @ 357a4ab.modern.js:1
(anonymous) @ 357a4ab.modern.js:1
checkBuyBeforeSubmit @ 5df22ec.modern.js:1
(anonymous) @ 5df22ec.modern.js:1
r @ 357a4ab.modern.js:1
l @ 357a4ab.modern.js:1
Promise.then (async)
r @ 357a4ab.modern.js:1
l @ 357a4ab.modern.js:1
(anonymous) @ 357a4ab.modern.js:1
(anonymous) @ 357a4ab.modern.js:1
submit @ 5df22ec.modern.js:1
handleAction @ 5df22ec.modern.js:1
click @ 5df22ec.modern.js:1
ne @ 357a4ab.modern.js:1
n @ 357a4ab.modern.js:1
c._wrapper @ 357a4ab.modern.js:1
Show 10 more frames
63d76e4.modern.js:1 error Error: Network error: Response not successful: Received status code 400
    at new t (63d76e4.modern.js:1:2668673)
    at 63d76e4.modern.js:1:2689511
    at 63d76e4.modern.js:1:2695568
    at Set.forEach (<anonymous>)
    at 63d76e4.modern.js:1:2695544
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (63d76e4.modern.js:1:2695494)
    at 63d76e4.modern.js:1:2688139
```

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Can you check it if you can buy it on https://beta.kodadot.xyz ? 👀

**Comment by spacesmutje** [comment]
Resolved! Sometimes it's the easy stuff that keeps you going 💯 Thanks for your help!

**Comment by yangwao** [comment]
It's should be fixed on https://kodadot.xyz as well in ten minutes! :) 
Enjoy! 

Ht for meme contribution ;) 

https://github.com/kodadot/nft-gallery/releases/tag/0.0.17
