### ISSUE TITLE
Text in Name, symbol, price and other fields is dark  (on dark mode)

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#3837]
### What happened?

Went to mint through simple mint, but can’t see what i’m writing

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Firefox

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

RMRK

### Screenshots

https://user-images.githubusercontent.com/92786519/186643532-d330bff5-8ff7-4bb0-9b55-f1a0ef237b3d.mov

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
the friendship ended with dark mode, 
light mode is my new best friend 

<img width="483" alt="image" src="https://user-images.githubusercontent.com/5887929/186643950-c9652bc0-4c78-4d1c-b646-99580d095554.png">

- #3830 
- #3831 

@cryptodamsky can you test in #3831 ?

**Comment by petersopko** [comment]
I suppose, thanks to #3831, this is already fixed on beta
