### ISSUE TITLE
Carousel Card List has no shadow on the left side

### ISSUE THREAD

**Issue by wmahendra1994** [kodadot/nft-gallery#3847]
### What happened?

( BUG ) Look at the arrows, you can see that on the right side there are annoying white/black shadows, while on the left side the view is clean without shadows

### Please reproduce in steps

improve the UI display, place the menu, and add the transaction history feature in the wallet menu

### Expected Behavior

Simple UI display, easy to operate. menu placement and features that are not difficult to use

### What browsers are you seeing the problem on?

Mobile Android Chrome, Mobile Firefox

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Basilisk

### Screenshots

![IMG_20220826_221502](https://user-images.githubusercontent.com/104789820/186942358-b237db92-6804-4158-967b-20a6fe54ea83.jpg)
![IMG_20220826_221605](https://user-images.githubusercontent.com/104789820/186942379-71303ea8-f8b7-40a0-ad9e-2c3d3055d9ad.jpg)
![IMG_20220826_221728](https://user-images.githubusercontent.com/104789820/186942414-c0d95847-dce1-4bb2-ac8b-fb719cd8d602.jpg)

### Payment link for reward

https://kodadot.xyz/transfer/?target=bXmuLmKmaiPiec1bLbx5MJJgySEt3Pr6svb8dYKJPD5upmEQu

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Sending you payout for reporting
pay 20 usd

Hence we moved to a new design of the landing page, we value your feedback @wmahendra1994 

if you found something on our current landing, feel free to get back to us 

You can sneak peak on our beta https://beta.kodadot.xyz

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 24.42 USD/KSM ~ 0.819 $KSM
🧗 [bXmuLmKmaiPiec1bLbx5MJJgySEt3Pr6svb8dYKJPD5upmEQu](https://kusama.subscan.io/account/bXmuLmKmaiPiec1bLbx5MJJgySEt3Pr6svb8dYKJPD5upmEQu)
🔗 [0x4876afeffb7bfbf4ba7cd7571fa09470997459ca6b6587ee78ebe4ce994fe5df](https://kusama.subscan.io/extrinsic/0x4876afeffb7bfbf4ba7cd7571fa09470997459ca6b6587ee78ebe4ce994fe5df)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
