### ISSUE TITLE
Motion #256 | KodaDot NFT Explorer | Intake review observations

### ISSUE THREAD

**Issue by rajesh-nodle** [kodadot/nft-gallery#387]
As discussed, Motion #256 | KodaDot NFT Explorer | Treasury Intake review observations are captured in below review report.

https://docs.google.com/document/d/1BhHwDe_jVu_sp64psIyCWAcAjKfNOkrO88Uh8_veOIE/edit?usp=sharing

**Comment by vikiival** [comment]
Awesome work @rajesh-nodle

I'm missing info for this figure
![Uploading Screenshot 2021-05-17 at 13.33.30.png…]()


Morever, Issue no. 5 was fixed in #362

**Comment by vikiival** [comment]
![Uploading Screenshot 2021-05-17 at 13.33.30.png…]()

**Comment by yangwao** [comment]
Briefly run over issues linked doc, seems all of them are fixed, tentatively closing.

@rajesh-nodle please reopen if you don't agree. Happy to collaborate and fix if I missed some.
