### ISSUE TITLE
Postfixes SearchBar Refactor & Redesign

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3877]
It's time to do postfixes in the search bar

- [ ] refactor into smaller components 
- [ ] search bar doesn't open up on displays with 481px > width. 
- [ ] I don't see suggestions on mobile 

![image](https://user-images.githubusercontent.com/5887929/187231549-e82f2d31-886d-4f20-ad54-0683daf030db.png)

as on beta, it worked in the past 
![image](https://user-images.githubusercontent.com/5887929/187231925-c31d0bde-6f2b-4150-91f7-4185ec71257e.png)

- Is there anything else?

@petersopko can take it from here 

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/3763#issuecomment-1230434765_

**Comment by petersopko** [comment]
> * [ ]  search bar doesn't open up on displays with 481px > width.
> * [ ]  I don't see suggestions on mobile

following up these two in 
- https://github.com/kodadot/nft-gallery/issues/3882

**Comment by petersopko** [comment]
> * [ ]  refactor into smaller components

- https://github.com/kodadot/nft-gallery/issues/3883
