### ISSUE TITLE
Proposed navigation 

### ISSUE THREAD

**Issue by XyloDrone** [kodadot/nft-gallery#389]
Add Leaderboard to main Nav when implemented. 

Add to footer: 

- about us
- faq
- contact us
- social icons
- Partnerships and ambassadors 

![Screenshot 2021-05-19 at 00 32 02](https://user-images.githubusercontent.com/84407059/118736098-a53fca80-b839-11eb-9137-86d47366b2bb.png)

**Comment by yangwao** [comment]
Confirmed, it's meanwhile there! 
![image](https://user-images.githubusercontent.com/5887929/134132959-c35be687-6db4-4887-9a63-dc331376115c.png)
