### ISSUE TITLE
Multi-currency Transfer for /snek

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3897]
It seems that as of now, Transfer at /snek allows only for transfer of BSX tokens. If I'm understanding this multicurrency implementation correctly, it should be possible to transfer KSM as well and therefore, we should give users an option to select which tokens they'd like to transfer.

**Comment by petersopko** [comment]
this issue is still up for grabs and needs an upgrade:
1. we support (and show) only BSX at /snek transfer (regardless of the KSM labels there):
![image](https://user-images.githubusercontent.com/73316633/189325031-5e03e24f-e40e-446d-9994-5dd67104dd89.png)

2. after successful transfer of BSX, the generated link leads nowhere on Calamar (I remember Jarsen was fixing this, maybe you can take a look at the rest of this issue as well? 👀):

![image](https://user-images.githubusercontent.com/73316633/189326388-2b337d88-6fbb-4f37-9f57-4c4d22ab6949.png)
![image](https://user-images.githubusercontent.com/73316633/189326870-6807933b-5504-409b-a4f4-0962dd2d74e5.png)

**Comment by petersopko** [comment]
I've tried transfer some KSM on /snek and I couldn't (balance too low, even when I had enough ksm), I guess the balances are mixed here
![image](https://user-images.githubusercontent.com/73316633/191916243-1ccfb48f-c15c-4c3d-94f3-231aad7660c8.png)

**Comment by roiLeo** [comment]
- continue #6460 & #6696
