### ISSUE TITLE
Put price on preview social card bigger

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#391]
https://twitter.com/deepologic/status/1395315053335875585
Right now it's quite an unreadable price when shared elsewhere than Telegram
I propose to 
- [ ] make it pink
- [ ] probably double size?
- [ ] try downscale generated image -- as may result faster reply vercel <-> crawler <-> user browser

Maybe @andreygrin could help out ;)

**Comment by AndriiHrynchuk** [comment]
Deployed all changes to Vercel

**Comment by yangwao** [comment]
Perfect 
![image](https://user-images.githubusercontent.com/5887929/119105586-c06b2f80-ba1d-11eb-9dc0-31c23a28b38a.png)
Let's send KSM address :)
