### ISSUE TITLE
Refactor: i18n module

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#3916]
rewrite i18 module with Nuxt3 migration

possible candidate:
- i18 next: https://v8.i18n.nuxtjs.org/getting-started/setup (w/ or w/o bridge)
- intlify: https://github.com/intlify/nuxt3

**Comment by yangwao** [comment]
If someone want to take this one, it's up for grab!

**Comment by roiLeo** [comment]
> If someone want to take this one, it's up for grab!

Still blocked by Nuxt3 migration

**Comment by stephenjason89** [comment]
Maybe we can close this #7045
It's now implemented on Nuxt branch 😄

**Comment by yangwao** [comment]
Could you let me know if this is open for a reason? Marked as done in 
- #7034

**Comment by roiLeo** [comment]
> Could you let me know if this is open for a reason? Marked

Meanwhile done in nuxt branch
