### ISSUE TITLE
Indexer: add collection name in lastEvent query

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#3927]
how to proper way to add collection properties in `lastEvent` query?
currently, there is no collection in that query

<img width="228" alt="Screen Shot 2022-09-08 at 21 48 56" src="https://user-images.githubusercontent.com/734428/189154152-5b55b461-915d-4611-b067-81e324a9a8ab.png">

**Comment by roiLeo** [comment]
you can check `lastNftListByEvent` query:
```graphql
    collection: name
```

**Comment by preschian** [comment]
> you can check `lastNftListByEvent` query:

seems already using that query, but this line `collection: name` is using nftName right? not collectionName? CMIIW. so, currently, output for fields `name` and `collection` will be the same

**Comment by roiLeo** [comment]
> seems already using that query, but this line `collection: name` is using nftName right? not collectionName? CMIIW. so, currently, output for fields `name` and `collection` will be the same

my bad you right it looks like it show nft name and not collection name

ref:
https://github.com/kodadot/snek/blob/5cd19f51b705e0812492ad683997d39a0f657bdd/src/server-extension/query/event.ts

**Comment by roiLeo** [comment]
meanwhile this has been done
![Capture d’écran 2022-10-04 à 4 02 19 PM](https://user-images.githubusercontent.com/9987732/193840205-61b9fe73-0a02-46ac-bd33-eb252d14fb2f.png)
![Capture d’écran 2022-10-04 à 4 01 49 PM](https://user-images.githubusercontent.com/9987732/193840221-2aa4636c-e789-4b72-a645-4bb3d53f5d0e.png)
