### ISSUE TITLE
Redesign: Carousel - call multi-chain endpoint

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#3928]
support multi-chain endpoints
<img width="999" alt="Screen Shot 2022-09-08 at 21 53 47" src="https://user-images.githubusercontent.com/734428/189155046-d9070994-229e-42b5-b6ca-ef69f9809437.png">

**Comment by roiLeo** [comment]
maybe [uniquery](https://github.com/kodadot/packages/tree/main/uniquery) will do the work? @vikiival

**Comment by vikiival** [comment]
Uniquery wont help, :) 
However api should return the origin prefix

**Comment by preschian** [comment]
> However api should return the origin prefix

can you elaborate more?
What is the proper way to call multi-chain API?
is it ok to call rubick, snek, and click simultaneously in one component?

**Comment by vikiival** [comment]
> is it ok to call rubick, snek, and click simultaneously in one component?

Yup but make sure you do not make huge queries on the endpoint :)

**Comment by vikiival** [comment]
and maybe ideally split into the card list for chain

**Comment by preschian** [comment]
> Yup but make sure you do not make huge queries on the endpoint :)
> and maybe ideally split into the card list for chain

I see, thanks. will try it then

**Comment by petersopko** [comment]
solved in: 
- https://github.com/kodadot/nft-gallery/pull/4011

ironed out in: 
- https://github.com/kodadot/nft-gallery/pull/4066
