### ISSUE TITLE
Trait boxes on 📱 

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3932]
currently, trait boxes on gallery item are not responding well to different sizes of screens, please check and make sure it works on every size of screen (not overflowing like now):
![image](https://user-images.githubusercontent.com/73316633/189315768-1a4d04c8-d139-4a19-9fb9-3598c4109168.png)

**Comment by roiLeo** [comment]
👋 
could you share item link?

**Comment by petersopko** [comment]
> 👋 could you share item link?

I've found this while testing MOVR, from #3904 here's another example:
https://deploy-preview-3904--koda-nuxt.netlify.app/movr/gallery/0xb6e9e605aa159017173caa6181c522db455f6661-3000
