### ISSUE TITLE
Add MoonBeam to KodaDot

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3934]
The first batch of NFTs from Moonbeam on KodaDot 

Need some links till Sunday 🥹🫡 🚀 for 🇩🇪 Berlin
--- 
<details>
  <summary>Target collection on Moonbeam </summary>

Exiled Racers Pilots 
- 738 
- https://moonbeam.moonscan.io/address/0x515e20e6275CEeFe19221FC53e77E38cc32b80Fb/contracts

Exilred Racers Racecrafts 
- 654 
- https://moonbeam.moonscan.io/address/0x104b904e19fBDa76bb864731A2C9E01E6b41f855/contracts

GLMR Apes 
- 107 
- https://moonbeam.moonscan.io/address/0x8fBE243D898e7c88A6724bB9eB13d746614D23d6/contracts

MoonPets
- 608 
- https://moonbeam.moonscan.io/address/0x2159762693C629C5A44Fc9baFD484f8B96713467/contracts

GLMR Jungle 
- 470 
- https://moonbeam.moonscan.io/address/0xcB13945Ca8104f813992e4315F8fFeFE64ac49cA/contracts

GLMR punks 
- 423 
- https://moonbeam.moonscan.io/address/0x25714FcBc4bE731B95AE86483EF97ef6C3deB5Ce/contracts

Moonbeam Punks 
- 1142 
- https://moonbeam.moonscan.io/address/0xFD86D63748a6390E4a80739e776463088811774D/contracts

Moonbeam legendary punks 
- 596 
- https://moonbeam.moonscan.io/address/0xAdc88EbB18d8F9a54890303C9Ba4501B1E8A221E/contracts

Clipper Survivor Patch 
- 310 
- https://moonbeam.moonscan.io/address/0x292cfCB8E1455Ac95B45B35bccCD7e09a840fEFc/contracts

GLMR Apes boost 
- 98 
- https://moonbeam.moonscan.io/address/0xb9F2d4BbfDCCAD1e2239a4f7B8c917c984e9b863/contracts

Hamsters Gang 
- 395 
- https://moonbeam.moonscan.io/address/0xD105E0da7fDc86192469654FB565c2f584920DA0/contracts

MoonFit - Mint Pass 
- 1364
- https://moonbeam.moonscan.io/address/0x6758053c0b27E478edE1E4882adFF708Fc4FA72D/contracts

---

Canary Network Agency 
- 197
- https://moonbeam.moonscan.io/address/0x139e9BA28D64da245ddB4cF9943aA34f6d5aBFc5/contracts

Groomlins 
- 1709
- https://moonbeam.moonscan.io/address/0xF27A6C72398eb7E25543d19fda370b7083474735/contracts

MoonFit Beast and Beauty (MFBB) 
- 359  
- https://moonbeam.moonscan.io/token/0x02a6dec99b2ca768d638fcd87a96f6069f91287c 

Bored Puppet Yacht Club (BPYC) 
- 276  
- https://moonbeam.moonscan.io/token/0xd364fB95989F5A47dDb9665149DD750782d37c7f

EXR Mint Pass (EXRMP)
- 268 
- https://moonbeam.moonscan.io/token/0x3507FD182dC5BD1B29214950fdcDe40BD167114F

EXR Inventory (EXRI)
- 534 
- https://moonbeam.moonscan.io/token/0xa0B48010Ff75136bBb5c8a12fEdFa37160819834

The Ultimate Harvest Moon Campaign 
- 9476 
- https://moonbeam.moonscan.io/address/0x51737fA634e26f5687E45c6ca07604E064076350/contracts

--- 
maybe skip those for now?

OnChainDudes - generative SVG on moonbeam by mohd
- https://moonbeam.moonscan.io/token/0xa0c72e1c6616888cb5a9e6393F96183c1aA4f17d
- 2 

Moonbean unicorns 
- 46 
- https://moonbeam.moonscan.io/address/0xe088cdcc176c3907fa8c02a789498e826dc46a14/contracts

The Flighters
- 44 
- https://moonbeam.moonscan.io/token/0xF786d99c00EA512e1a8dD41aa99488B819a992D8
</details>

**Comment by vikiival** [comment]
Throws errors on ethers.js
  // Groomlins = '0xf27a6c72398eb7e25543d19fda370b7083474735',
  // EXRMintPass = '0x3507fd182dc5bd1b29214950fdcde40bd167114f',
  // EXRInventory = '0xa0b48010ff75136bbb5c8a12fedfa37160819834',
