### ISSUE TITLE
Indexer: checkIndexer query not working properly

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#3938]
### What happened?

I got "Indexer Error" on the gallery item page

### Please reproduce in steps

open gallery item page such as: https://beta.kodadot.xyz/rmrk/gallery/10938663-0488b1a94fd8d61738-SHIBITS-SHIBITS_OR_PHARAOH_NIKU_OR_KUSAMA_KINGS-0000000000000354

### Expected Behavior

should not error indexer

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

No

### At which chain did you encounter bug?

RMRK

### Screenshots

<img width="2032" alt="Screen Shot 2022-09-11 at 18 53 43" src="https://user-images.githubusercontent.com/734428/189526206-b7d3f815-fe5d-4b22-846e-ed358ed18302.png">

### Payment link for reward

https://kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by preschian** [comment]
seems like the e2e test will throw an error because of this bug

**Comment by vikiival** [comment]
#2929 👀

**Comment by preschian** [comment]
> Hey, this is a legacy query which should not be there
> 
> * [SubSquid as a default indexer #2929](https://github.com/kodadot/nft-gallery/discussions/2929)

I see, it means safe to remove that parts?
