### ISSUE TITLE
Redesign: Featured Articles

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#3944]
parent task: https://github.com/kodadot/nft-gallery/issues/3844

- [ ] Redesign: Articles - Prepare UI
- [ ] Redesign: Articles - Dark Mode
- [ ] Redesign: Articles - Integrate API
- [ ] Redesign: Articles - Responsive

**Comment by preschian** [comment]
feel free to pick this task

**Comment by prachi00** [comment]
I can do this, but I have some doubts - 
is the API for featured articles already there?

**Comment by preschian** [comment]
> I can do this, but I have some doubts - is the API for featured articles already there?

I think we can open another PR for integration with real API later. need to ask @yangwao for the API

**Comment by yangwao** [comment]
We have three options
- A - hard code some articles with some blogging system, hardest option to go
- B - fetch from directly medium or hardcode links to medium with picture & header & intro paragraph
- C - Same as B, with Substack links/content

pinged @cryptodamsky to chime in

**Comment by cryptodamsky** [comment]
Yeah let’s put substack to people’s attention since it’s less technical and has longer run.

C.

**Comment by prachi00** [comment]
> * Substack

so which articles are we picking from substack?

**Comment by cryptodamsky** [comment]
Hello,

https://kodadot.substack.com/p/the-story-behind-our-t-shirt-waifu
https://kodadot.substack.com/p/the-artists-inside-1-clown-world
https://kodadot.substack.com/p/ride-on-art-1-zluchkayaaa

**Comment by preschian** [comment]
hi @prachi00 how is the progress of this task?

**Comment by prachi00** [comment]
Hi,I havent started working on this one yet, I'll start in a day or two if thats okay

**Comment by yangwao** [comment]
> Hi,I havent started working on this one yet, I'll start in a day or two if thats okay

hey, I've chatted with @preschian and I would prefer him to finish this as it's the very last missing thing to do here to close #3844  :)
