### ISSUE TITLE
Nova Wallet is polkadot-js

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3955]
### What happened?

In order to log in properly on mobile device (Using nova wallet) you need to select Polkadot-js

### Please reproduce in steps

- go to the NFT with nova wallet (rmrk/detail/14445658-8cc1b91e899d9be40e-2CENTS-MULTICOLORS-0000000000000007)
- log in using whatever
- do emote
- it will fail

### Expected Behavior

- Nova Wallet should be the only option when logging in via mobile

![image](https://user-images.githubusercontent.com/22471030/190135579-94ed4801-dd7d-46c2-a4ca-a75953eb826b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
Was it before or after Confirmation screen?

Regarding the wallet modal something changed on Nova app it is not detected anymore as a mobile device

**Comment by vikiival** [comment]
My major issue is that it shows only these wallets on mobile 

Cc @roiLeo 

![image](https://user-images.githubusercontent.com/22471030/190141230-8d79d247-fc32-4748-be1f-205bb1c91e27.png)
