### ISSUE TITLE
Nova Wallet: app crash on make_offer

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#3961]
#### Step to reproduce
- on nova wallet app
- go on beta.kodadot.xyz
- conect your wallet
- /snek chain
- click any nft
- click on "MAKE OFFER"
- submit
- app is closing before Confirmation screen

**Comment by yangwao** [comment]
Still thing?

**Comment by roiLeo** [comment]
> Still thing?

Offer is blocked rn, will test it soon when snek release

**Comment by roiLeo** [comment]
link #3628 
close as won't fix
