### ISSUE TITLE
What have I missed on hackhatons?

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#3976]
### Setup

- [ ] KodaDot hack template (Nuxt3 + Naive UI)
- [ ] Make mint SDK
- [x] Finish Uniquery

**Comment by yangwao** [comment]
<img src="https://media2.giphy.com/media/l2R013mIf1ZXdvoyI/giphy.gif"/>

😅

**Comment by vikiival** [comment]
> drawing of the cricket lying on the green grass, background consists of mountains, vaporwave style

![replicate-prediction-oglacjy6ofcenicmtrutblcymm](https://user-images.githubusercontent.com/22471030/191254292-8ba3de8a-dfb7-40e7-a4f6-3484a274abcb.png)

**Comment by yangwao** [comment]
- #2517 
- #816 

Missing Vue3 starter pack 👀

**Comment by yangwao** [comment]
meanwhile elsewhere
