### ISSUE TITLE
balance doesn't load on /snek

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3981]
I assume there's something wrong with our connection to rococo, other reported bug was that users can't mint:

![image](https://user-images.githubusercontent.com/73316633/191024275-2cce1101-6737-47bb-86fa-c28e0182b012.png)

**Comment by petersopko** [comment]
offer cancelation: 
![image](https://user-images.githubusercontent.com/73316633/191025448-40fb47a1-f15a-40c9-9c2b-de8beea632a2.png)

**Comment by green-jay** [comment]
please switch to this RPC: `wss://rococo-basilisk-rpc.hydration.dev`
