### ISSUE TITLE
can't mint on snek

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3992]
not sure if I'm doing something wrong, but I'm unable to mint with snek through talisman wallet. can anybody else try please?
![image](https://user-images.githubusercontent.com/73316633/191463133-de433abd-01d7-4e81-9898-cf20178c0caa.png)

**Comment by roiLeo** [comment]
work for me with polkadot.js, any errors in console?

**Comment by petersopko** [comment]
> work for me with polkadot.js, any errors in console?

no error, and also works with polkadot js hmm. I'll try this again with talisman in some time

**Comment by petersopko** [comment]
this is just talisman issue on my part
