### ISSUE TITLE
Don't see fresh mint in explorer on SNEK

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4000]
I've made a fresh new mint https://beta.kodadot.xyz/snek/gallery/1559871636-2?page=1&message=congrats&search, and I don't see it in explorer at https://beta.kodadot.xyz/snek/explore?tab=GALLERY&page=1
No errors in the console. 

Is it known bug?

![image](https://user-images.githubusercontent.com/5887929/191718789-5890a0f2-9240-4bb9-bd33-87df0358ace1.png)

plus seems I don't see Creator & Collection on mint
![image](https://user-images.githubusercontent.com/5887929/191719805-cdf0ea72-9cdb-4abe-bde3-630f2f385f79.png)

**Comment by vikiival** [comment]
This looks like an issue of the recent snek release

**Comment by petersopko** [comment]
> This looks like an issue of the recent snek release

something weird with snek happening, this is screenshot from yesterday's query
![image](https://user-images.githubusercontent.com/73316633/191727405-2d3238f2-2842-4de5-82b0-a59a6dc8b609.png)

today I can't find any collections except for one:
![image](https://user-images.githubusercontent.com/73316633/191727626-831bc357-03aa-4a0d-9c95-546197bdac55.png)

**Comment by vikiival** [comment]
Sirs I have been informed that a runtime upgrade has happened.
Issue is tracked here

- https://github.com/kodadot/snek/issues/65


<img width="716" alt="Screenshot 2022-09-22 at 16 06 05" src="https://user-images.githubusercontent.com/22471030/191769345-dcb12808-be63-40fe-b96e-006955f5953a.png">

**Comment by petersopko** [comment]
> maybe I'm doing something wrong

I was doing something wrong, I somehow misunderstood and thought we're already using snek005. 

However, the problem seems to be fixed in 
- #4008

**Comment by vikiival** [comment]
We can close as this was issue of non-working indexer
