### ISSUE TITLE
When I click on "x" I except the searchInput to be empty/erased on mobile

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/nft-gallery#4007]
![Capture d’écran 2022-09-22 à 9 12 46 AM](https://user-images.githubusercontent.com/9987732/191681989-168d84ee-49ab-46fb-9b42-09467c2bdfda.png)

- [ ]  When I click on a suggestion Item I'm redirected but I still see the searchbar open 
- [ ] When I click on "x" I except the searchInput to be empty/erased

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/3996#pullrequestreview-1116506508_

**Comment by kkukelka** [comment]
I'll give this a shot 👋

**Comment by JustLuuuu** [comment]
this issue is too old to reproduce
