### ISSUE TITLE
Clarify simple mint

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#401]
Simple mint is tool to create a NFT with following properties;
- you are allowed to define number of copies through editions
- app automatically creates a wrapping collection for that

**Comment by vikiival** [comment]
<img src="https://http.cat/401" />

**Comment by yangwao** [comment]
What's this 
![image](https://user-images.githubusercontent.com/5887929/134131458-dc378c08-5bac-489a-8051-843fd7277542.png)

edit, ahah it loaded now!

Anyway, @archnomics let's check on this please! 
Reflect in FAQ

**Comment by archnomics** [comment]
Added now: https://kodadot.gitbook.io/knowledgebase/general/minting/minting-faq

Is the issue resolved?

**Comment by yangwao** [comment]
I don't see it here https://kodadot.xyz/rmrk/faq 👀

How we will manage the translations of knowledge base?

**Comment by cryptodamsky** [comment]
Simple mint has been clarified both in [FAQ](https://kodadot.xyz/rmrk/faq) and [docs](https://docs.kodadot.xyz/FAQ.html)

Also a tutorial has been aded on [simple mint](https://docs.kodadot.xyz/minting.html#how-can-i-simple-mint-on-kodadot) to our doccumentation 

Closing
