### ISSUE TITLE
Traits on Basilisk

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#4010]
We are still by default attaching 1 trait (carbonless) to every NFT which I find weird
![Pasted image 20220923084319](https://user-images.githubusercontent.com/73316633/191908420-4bc5c740-ec07-4d68-9296-f889a0e61a1f.png)
and it would be perhaps desirable to get rid of it or give user an option to select it voluntarily (I remember talking about this with @roiLeo somewhere)
![image](https://user-images.githubusercontent.com/73316633/191908334-dc4decf1-74c6-42e2-9b40-7924e96becfc.png)

**Comment by petersopko** [comment]
@vikiival what's the state of the traits on Snek? Is there a reason we are attaching carbonless to every NFT without an option to add more traits / remove this one?

**Comment by roiLeo** [comment]
ref #3265
