### ISSUE TITLE
Creating collection fails with Talisman

### ISSUE THREAD

**Issue by spacesmutje** [kodadot/nft-gallery#4017]
### What happened?

Tried creating a collection on beta. and kodadot.xyz with talisman and it failed.

I guess it's related to todays update of the Talisman wallet.

### Please reproduce in steps

- clicked on create
- Added the cover, description, etc
- clicked on create collection
- clicked on approve in the talisman pop up

### Expected Behavior

A succesful creation of a collection.

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### Screenshots

![Screenshot 2022-09-23 21 46 05](https://user-images.githubusercontent.com/106772187/192060787-8a7af508-1b7e-4ad0-9303-e7eb9d292c87.png)

### Relevant log output

```shell
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
f6663a6.js:1 2022-09-23 23:38:48        REGISTRY: Unknown signed extensions CurrencyBalanceCheck found, treating them as no-effect
O @ f6663a6.js:1
f6663a6.js:1 2022-09-23 23:38:48        API/INIT: RPC methods not decorated: lbp_getPoolAccount, xyk_getPoolAccount, xyk_getPoolBalances
O @ f6663a6.js:1
f6663a6.js:1 2022-09-23 23:38:48        API/INIT: Not decorating unknown runtime apis: 0x78572f7e6636df1d/1, 0xc0f5e1b9ea09a80f/1
O @ f6663a6.js:1
f6663a6.js:1 2022-09-23 23:40:24        API/INIT: Not decorating unknown runtime apis: 0x78572f7e6636df1d/1, 0xc0f5e1b9ea09a80f/1
O @ f6663a6.js:1
f6663a6.js:1 2022-09-23 23:40:43        API/INIT: Not decorating unknown runtime apis: 0x78572f7e6636df1d/1, 0xc0f5e1b9ea09a80f/1
O @ f6663a6.js:1
4f6663a6.js:1 warn No NFT with ID 6 fallback to RPC Node
value @ f6663a6.js:1
bafybeib2hrxgrieoxd552bssphfg7qc3vft5gddfd2up64v5htxjbm243e:1          Failed to load resource: the server responded with a status of 504 ()
DevTools failed to load source map: Could not load content for chrome-extension://cmndjbecilbocjfkibfbifhngkdmjgog/lib/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://fijngjgcjhjmmpcmkeiomlglpeiijkld/content_script.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://fijngjgcjhjmmpcmkeiomlglpeiijkld/page.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
```

### Payment link for reward

https://kodadot.xyz/transfer/?target=EFYwtJuqDVjrFXoh6uH5tv37XbLnujyRrBtrMX8v78XxVKN

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petersopko** [comment]
ah I see you're facing similar issue, I've thought I had somehow messed up my extension
- https://github.com/kodadot/nft-gallery/issues/3992

**Comment by spacesmutje** [comment]
I was looking for similar issues before creating mine. Must have missed yours, sorry.

**Comment by yangwao** [comment]
@spacesmutje it's still happening?

**Comment by spacesmutje** [comment]
@yangwao i will give it a shot later on, but on our discord artists are reporting that it's working again!

**Comment by yangwao** [comment]
hope it won't break again
