### ISSUE TITLE
Collections sort on Moonriver doesn't work

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#4021]
Sorting filter at explore doesn't work, since it have to options (new first/old first), I guess it has something to do with the screenshot attached below. 

I suggest two moves here
1. disable the sorting option until we start indexing the age of these collections (I'm not sure why it's not possible now, or what's the issue there @vikiival)
2. I assume it's related to this? (if not pls update)
- https://github.com/kodadot/click/issues/34

![image](https://user-images.githubusercontent.com/73316633/192095551-14bf2be5-3210-4960-bff7-15778f32cc6f.png)

**Comment by vikiival** [comment]
Yup

**Comment by vikiival** [comment]
The problem is that with current setup I do not know the real date when the collection was created

**Comment by roiLeo** [comment]
Moonriver integration discontinued
