### ISSUE TITLE
Cannot load gallery item detail from specific collection /snek

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#4025]
While browsing https://beta.kodadot.xyz/snek/collection/807893860, I cannot load the item detail when I click on any of the items, I get loaded just the placeholder. Happens specifically with this collection, not sure why (most of the others)
![image](https://user-images.githubusercontent.com/73316633/192144534-2bbad6c4-0ef9-4026-862e-91f84981f810.png)
![image](https://user-images.githubusercontent.com/73316633/192144612-951bd7ac-a1a5-45a0-909d-e43487c1e912.png)

**Comment by Jarsen136** [comment]
Hey, I have fixed this bug in #4008 https://github.com/kodadot/nft-gallery/pull/4008/commits/703c29da7554aec522cc2dbb249a19339b6f1cfb

preview: 
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/31397967/192149787-ecca35ba-a28a-4a23-9c5c-568d534d6d75.png">

https://deploy-preview-4008--koda-nuxt.netlify.app/snek/gallery/807893860-4
