### ISSUE TITLE
Statistics on Moonriver

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#4028]
There are at least two major problems which result in bugs, with the data we have for Moonriver collections:

1. We're not indexing price of the NFTs, i.e. we don't have any price related data, partially covered here:
- #4022

2. We have only two types of event interactions on Moonriver, `MINTNFT` (mint in app) and `SEND` (gift in app):
![image](https://user-images.githubusercontent.com/73316633/192212053-89c8a71f-6953-43b5-8c6e-bb5d26ad4ed0.png)

The options going forward (as I see it, pls feel free to add yours):

1. As with #4022, we can proceed into hiding features related to event interactions which we currently don't have indexed
2. We can alter the way we handle `SEND` event interactions and treat them as `BUY` ones (this would add some level of detail, although may be a bit misleading since we can't currently differentiate between actual gifting (sending) and buying)
3. There is a change coming to the data we currently and therefore, we should wait for this before moving forward (@vikiival is there any change coming, or should we just build UI around these two event interactions?)

Marking this as research until we have clear answers, also if there is no change coming to the data we have, I need decision whether to proceed with option 1., 2. or something entirely different @yangwao

**Comment by roiLeo** [comment]
moonriver integration discontinued
