### ISSUE TITLE
Implement fees

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#4038]
### What happened?

Currently we do not take fees on Basilisk for sales. 

### Please reproduce in steps

Go to snek
List NFT
Sell 
No tokens goes to the fund

### Expected Behavior

How to implement:

- in Available actions check if action is buy
- use api.tx.utility.batchAll
- Where first arg is the buy callback cb(…args)
- Second I have to check since we use non-native tokens

### Screenshots

~

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
I guess two options could be done is
- natively through proxied royalties, there fore bsx devs would need to extend pallet for it, so we can put our address own royalty and open doors for some revenue sharing
- adding it through the proposed solution above

**Comment by vikiival** [comment]
Continue in #5130
