### ISSUE TITLE
Nuxt3 change deployment style

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4040]
With refactoring to Nuxt3 I guess we have the opportunity to fiddle with deployment
ht @vikiival showing tweet

<img width="588" alt="image" src="https://user-images.githubusercontent.com/5887929/192758471-ed9d77d8-f906-45bf-80f3-2953203326bc.png">

https://twitter.com/danielcroe/status/1575038802871332864?s=46&t=_LkxcC3VaCU5UkH60zzrAg

https://github.com/kodadot/nft-gallery/blob/2cbbb6372e6f5ac1b64296a3c066d49f118312bb/nuxt.config.js#L34

**Comment by yangwao** [comment]
hmm

**Comment by roiLeo** [comment]
continue #8489
