### ISSUE TITLE
Zero balance on Basilisk even showing non-zero in assets page 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4043]
Does it seem in drop down we are showing zero when on the Assets page I see some BSX?

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/5887929/192767270-fab6448a-4430-4306-98eb-da754bc369c3.png">

**Comment by vikiival** [comment]
<img width="238" alt="Screenshot 2022-09-28 at 13 38 51" src="https://user-images.githubusercontent.com/22471030/192769660-070c674f-eed5-4fc1-9006-809e21c8f1d7.png">
