### ISSUE TITLE
og:image doesn't render on Twitter? 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4058]
I recall it worked before(?) 😅

- https://kodadot.xyz/bsx/gallery/3231523574-2
- https://cards-dev.twitter.com/validator

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/5887929/193406419-3f358a9e-30ec-4193-9afe-6755c9417384.png">

on telegram it works only with beta  
<img width="455" alt="image" src="https://user-images.githubusercontent.com/5887929/193406523-f217cac3-8303-4c53-90cd-7b0890d168b4.png">

**Comment by roiLeo** [comment]
ref #2759

**Comment by preschian** [comment]
> ref #2759

yes, correct, related to that issue. maybe we can improve https://github.com/preschian/prerender-cf-workers to use workers cache before hitting prerender.io

**Comment by vikiival** [comment]
https://kodadot.xyz/rmrk/gallery/15067511-7E982817A2D2575031-KDMN-KODAMONEY_002-0000000000000003

<img width="1082" alt="Screenshot 2022-10-31 at 12 33 52" src="https://user-images.githubusercontent.com/22471030/198998705-f56c772f-08e5-4219-95ac-2a88c968a986.png">


https://twitter.com/vikiival/status/1587045749451366400

**Comment by vikiival** [comment]
Looks like it is still an issue

**Comment by vikiival** [comment]
WFM in incognito

<img width="588" alt="Screenshot 2022-10-31 at 13 22 18" src="https://user-images.githubusercontent.com/22471030/199006798-410e0e36-912c-4b5c-8177-c58053fcefbd.png">

**Comment by yangwao** [comment]
Continue in 
- #5567
