### ISSUE TITLE
Enable 🎩 Top Collections on landing for Basilisk once there will be data

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4059]
Current State:
- :white_check_mark: working on /rmrk old landing
- :white_check_mark: working on /snek old landing (but only 2 results, rest has `null` floorprice)
- ✅ working on new landing, /?redesign=true
- 🔴  no data on /bsx old landing, I'm hidding component for now
- 🔴 got some cleaning to do in component 🧹

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/issues/3869#issuecomment-1260803799_

**Comment by petersopko** [comment]
I've just now noticed that the size of boxes here is not unified, maybe we want it like this, maybe we don't?
![image](https://user-images.githubusercontent.com/73316633/193442896-ca73044d-a96a-4f54-b8b4-bb07753534a0.png)

**Comment by roiLeo** [comment]
> I've just now noticed that the size of boxes here is not unified, maybe we want it like this, maybe we don't? ![image](https://user-images.githubusercontent.com/73316633/193442896-ca73044d-a96a-4f54-b8b4-bb07753534a0.png)

size of screen? Numbers are big, it make multiple lines, I might reduce the collection name text

**Comment by roiLeo** [comment]
We might need to remove `floorPrice_isNull: false` filter for now ref https://github.com/kodadot/snek/pull/116#issue-1433211484
