### ISSUE TITLE
Newest list contains items with empty metadata

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#4073]
Redesigned multichain `Newest list` is now showing minted collection (without preview, but that's secondary). I assume this wasn't the plan and we should only be showing NFTs not whole collections
![image](https://user-images.githubusercontent.com/73316633/193802258-ffbecc19-21ce-4763-8f9b-2b9d2795cdc5.png)

**Comment by preschian** [comment]
hhmm, maybe need to fix on the indexer side?
it should show `The Metadater` item, it works on Explore menu
<img width="1624" alt="Screen Shot 2022-10-05 at 18 11 48" src="https://user-images.githubusercontent.com/734428/194047654-02a8edc4-6e38-4cac-aa62-abe4c26446fb.png">

some properties from queries are missing
<img width="568" alt="Screen Shot 2022-10-05 at 18 17 09" src="https://user-images.githubusercontent.com/734428/194048410-81b49ce0-983d-4500-992c-230aef369dae.png">

so, it would produce the same error on the current landing page
<img width="1624" alt="Screen Shot 2022-10-05 at 18 12 16" src="https://user-images.githubusercontent.com/734428/194048185-273f8c31-b5d8-487d-9c18-6ad1bb214659.png">

**Comment by roiLeo** [comment]
issue is comming from `lastEvent` resolver

### possible solution
- fix resolver and add new filters
- use `events` query instead

**Comment by JustLuuuu** [comment]
this issue is too old to reproduce
