### ISSUE TITLE
Statemine: take two

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4088]
In the past, we've integrated Statemine, and we can put Unique V2 in our roadmap for integration. 

We will expand this issue once we gain more insight into how we can leverage particular incoming features with other NFTs primitives within other parachains

## Ref
- https://forum.polkadot.network/t/uniques-pallet-nfts-september-update/410
- https://github.com/paritytech/substrate/issues/11783

--- 
Hello from [KodaDot](https://kodadot.xyz); 
In the past, we've received a [Kusama Treasury grant for integrating Statemine](https://kusama.polkassembly.io/motion/349) and [delivered integration](https://twitter.com/KodaDot/status/1489575517892325382); we did a quick write up & usage, but then we decided to sunset it (codebase is still partially working) it because of maintenance costs. 

We instead focused on more liquid and potent networks from an end-user perspective like [Basilisk](https://beta.kodadot.xyz/bsx/) & Astar & [MoonBeam](https://beta.kodadot.xyz/glmr) & [MoonRiver](https://beta.kodadot.xyz/movr/) as we are a pretty small team.

Now the situation has changed a bit in our favour and grown a bit; we had 84 contributors in the repository's lifetime, many (200+)forks & (300+)stars. and gave away over $150k in bounties to onboard more frontend developers to the Dotsama ecosystem and helped other parachains teams.  Steady growth with the code review guild and q&a guild; we would be happy to take on this in the future. 

Our goal is to make more libraries, SDKs and valuable public goods for others projects, where we found our endpoints have been used by many projects out there.

I've backlogged it in our repository [Statemine: Take Two](https://github.com/kodadot/nft-gallery/issues/4088), and once we finish our complete rehaul of KodaDot with a new design, we are happily looking at this. 

## Ref
- deletion some old Unique implementation 
  - https://github.com/kodadot/nft-gallery/pull/4870/files

**Comment by jsidorenko** [comment]
Yay, happy to hear that guys! Feel free to ask any questions you'll get re Uniques V2, would be happy to answer them.

**Comment by yangwao** [comment]
It seems things are ready to work on for KodaDot 
- https://github.com/paritytech/substrate/pull/12765

Time to research on this and we will be looking to bring it back to K having XCMv3 too.

**Comment by yangwao** [comment]
Time to make issues for UI components and indexer for nft-gallery so we can start working on this. 
Use label `statemine`

**Comment by yangwao** [comment]
First phase v0 for UniquesV2 
- https://github.com/kodadot/nft-gallery/issues/5879

**Comment by yangwao** [comment]
Bit writing on forum
- https://forum.polkadot.network/t/polkadot-nft-assets-hub-indexer-by-kodadot/3528

**Comment by vikiival** [comment]
https://github.com/paritytech/substrate/tree/master/frame/nfts

**Comment by vikiival** [comment]
already running on kodadot.xyz/ahp
