### ISSUE TITLE
Remove infinity scroll on collection on the top

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4089]
At https://beta.kodadot.xyz/movr/collection/0xb6e9e605aa159017173caa6181c522db455f6661?page=23

When the user wants to scroll to the top, it adds extra pictures, which is not good behaviour.
Same when the user go the next page, it resets me to the middle, add an extra 12(?) on the top and an extra 12(?) to the bottom. 

The intended behaviour would be to remove the infinite scroll on the top, so the user can browse to the top and keep the infinity scroll only on the bottom.
On pagination would be desired no to reset the user to the middle of the collection but keep the user at the same position so they can click on the previous and next page afterwards. 

Goal is to not reset state for the user where is located once it browse pages back and forth 

https://user-images.githubusercontent.com/5887929/194555072-d49a7151-696f-4250-a81f-733fe56f327f.mov

**Comment by Jarsen136** [comment]
👋
