### ISSUE TITLE
Error when tryying to create identity on basilisk

### ISSUE THREAD

**Issue by antoine-dowgo** [kodadot/nft-gallery#4091]
### What happened?

Create on-chain identity on Basilisk with a zero KSM balance: clicking on the button does nothing and throws errors in the console.

https://kodadot.xyz/identity

![Screen Shot 2022-10-07 at 3 41 59 PM](https://user-images.githubusercontent.com/102977626/194567648-cf428460-fbd7-4484-8892-1e740d4a5333.png)

### Please reproduce in steps

https://kodadot.xyz/identity

zero balance in KSM on basilisk

try to create identity

nothing happens

### Expected Behavior

seems like connection is the problem but maybe balance too

### Screenshots

![Screen Shot 2022-10-07 at 3 41 59 PM](https://user-images.githubusercontent.com/102977626/194567648-cf428460-fbd7-4484-8892-1e740d4a5333.png)

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by preschian** [comment]
It seems like same with this issue https://github.com/kodadot/nft-gallery/issues/3842#issuecomment-1256039281

hi @antoine-dowgo, could you try to relogin, does it fixed on your side?

**Comment by antoine-dowgo** [comment]
Yes it works ;:)
