### ISSUE TITLE
Gracefully handle if client didn't connect

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4103]
When a user goes to https://beta.kodadot.xyz/bsx/offers/ will see **computing** prop in expiration doesn't tell much. 

I will probably add some refresh stuff in case the user can handle it?
Probably wasn't properly implemented subapi on connect handler?

btw on refresh is gone but on crappy networks might happen 

![image](https://user-images.githubusercontent.com/5887929/194845091-ab898702-4b5a-4bfa-b9c2-e111c6eac082.png)

**Comment by roiLeo** [comment]
link #9076
