### ISSUE TITLE
Money component: comma replacement

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#4109]
![Capture d’écran 2022-10-11 à 1 55 49 PM](https://user-images.githubusercontent.com/9987732/195084195-2a15486c-bbbd-469f-ab0a-fdee4ae37c11.png)

Instead of having `0,30` I would like to see `0.3` 

may related with #3868

**Comment by alabo-excel** [comment]
Hello, I'll love to work on this task please assign it to me.
