### ISSUE TITLE
New hover card 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4117]
Maybe it would be nice to redesign hovercard to neobrutalism as well.

Probably we can add it to landing page.

Currently would be interesting add to showing art under address created or collected. 

<img width="373" alt="image" src="https://user-images.githubusercontent.com/5887929/196003090-a800c15a-7fc9-42e7-a5eb-3cf8bdc76d8a.png">

<img width="378" alt="image" src="https://user-images.githubusercontent.com/5887929/196003063-9546aa9b-ed9c-4089-8078-7c5b690d2f2f.png">

## Ref
- https://hic.af/

**Comment by exezbcz** [comment]
In the case of the landing page, there are no addresses/profiles to hover over. We were talking about making something for collections because I think I already have something. But there is a profile that would need it in the gallery item. Does that make sense?

**Comment by exezbcz** [comment]
After a chat with @yangwao I think we have an idea of how it could be made. 
The first thing would be to tweak nft card a bit. Adding something like "details" or "info" would work just fine. The position could be under the network. 
Card:
- flexible
- reusable for other cases, so for example creator hover card would have the same layout/design as a single nft hovercard. 
- simple with insights after hovering 

Use cases: 
Card brief info - no need to open the gallery item. There could be something like - properties, and the highest offer and if the card will be on explore page, information about the collection could be there too. For example floor. 

Address info - created, collected

Collection insights on explore collections page.

**Comment by yangwao** [comment]
Premise here to show second-order information which are not needed when you are browsing first order view

Hover card would be used on top of view of 
**- profile**
  - you want to know more about a particular address on-chain activity
  - showing 
    - collected - showing amount of on-chain buys address has made
    - created - the amount of NFTs created/minted
    - total sales, sales short - the amount of in some highest currency address has made 
    - 3 pictures with the highest sale
**- collection view**
  - hint collection numbers https://beta.kodadot.xyz/rmrk/collection/0a8ce195286c168f19-DONKEY
  - you want to know more about particular collection statistics
  - unique owners
  - highest sale
  - floor price
  - total volume in base currency
  - 3 pictures with highest sale/offer
- NFT view
  - collection - unique owners
  - traits rarity score open rarity score
  - highest offer in the collection
  - 3 highest sold NFTs

**Comment by exezbcz** [comment]
where would you imagine nft view to be? 
I mean the hovercard is for extending information on the card - could be collection or owner. 

What is the use case for nft view? You don't usually have somewhere to hover for more info. 
For example, here you hover over the collection and you get more info 
![image](https://user-images.githubusercontent.com/90852205/197355440-d64ad071-dc04-4222-ba58-11587abf1e74.png)
I can also imagine the use for user view, right here: 
![image](https://user-images.githubusercontent.com/90852205/197355462-dd9bbce5-0649-462b-be94-13262ec2d0ca.png)
Do you want to add another property to the nft card to create a place for hover over?

**Comment by prachi00** [comment]
@exezbcz @yangwao is this something that is ready to pick up?

**Comment by exezbcz** [comment]
> @exezbcz @yangwao is this something that is ready to pick up?

Hey, not yet, i will ping you once its ready

**Comment by exezbcz** [comment]
hey @prachi00 here are the designs
- nft hover card tbd
![image](https://user-images.githubusercontent.com/90852205/200194560-844653fd-d5b7-44cd-8c4f-f954eb19b4c0.png)
figma: landing page handoff

**Comment by exezbcz** [comment]
> <img alt="Screen Shot 2022-11-09 at 6 19 08 PM" width="305" src="https://user-images.githubusercontent.com/39299315/200984335-e708f536-3896-4a36-8b4d-1248fabb91c8.png">
> 
> @exezbcz is this name a url? If yes, what happens when it is clicked as currently it isnt clickable. Also, the hover state?

yup, it should redirect you to the profile. For hover states please see #4111 section links.

**Comment by yangwao** [comment]
> * you want to know more about a particular address on-chain activity

oh, I see now we forgot to add Twitter to the design. 

making follow up issue from this one?

**Comment by roiLeo** [comment]
Any chance that we can add a "Copy address" feature? I use it very often when hovering profile cards

**Comment by exezbcz** [comment]
> Member

yup, i will make it. It should also be in the wallet icon hover.

**Comment by yangwao** [comment]
Follow up for making for user hover card 
- add a Twitter link to the design
- copy address feature
