### ISSUE TITLE
Assets screen easily miss-leading KSM which is not on BSX

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4118]
Hey, seems we don't correctly show assets on the user address, i.e. KSM on Basilisk

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/5887929/196051473-d62fc079-b3ff-48af-bdc4-5a527fb63b2a.png">

As user will check for example sub.id will be miss leaded that has KSM, but actually not KSM on Basilisk
<img width="910" alt="image" src="https://user-images.githubusercontent.com/5887929/196050349-ad39282a-adbd-4ff9-ac30-906a458f4db0.png">
src https://sub.id/5CPfqy2jZX2EghfzY4oG5kpW8NgUhgAZ6Rhqt5PjrGbS4YdM/balances

Proposed quick changes, at least change some naming to avoid confusion. 
Maybe KSM@BSX ?

Also, can we add a link somewhere to the footer for Karura Bridge? https://apps.karura.network/bridge

**Comment by vikiival** [comment]
> Maybe KSM@BSX ?

Sounds like trading pair

One option is to write that something like: "assets shown below are stored on chain ${chain}"

**Comment by yangwao** [comment]
> Sounds like trading pair

that would be `/`

<img width="103" alt="image" src="https://user-images.githubusercontent.com/5887929/196052488-c0b72a69-6cfb-4d68-8443-a9599c81abf6.png">



> One option is to write that something like: "assets shown below are stored on chain ${chain}"

- #4119
