### ISSUE TITLE
Change notifications to be more user-friendly

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4121]
### Is your feature request related to a problem?

I bought an NFT piece on BSX today (same on RMRK), + I burned one that I minted in the past. In both cases, I got a notification like this: 
Buying: 
![image](https://user-images.githubusercontent.com/104380776/196053725-17161fb1-75b1-4438-b15b-3d958eb4e1b3.png)

Burning:
 ![image](https://user-images.githubusercontent.com/104380776/196052125-72ba0e4b-9ead-417a-800e-4982b8ff91be.png)
It would be nice to change them to something more user-friendly with fewer numbers. 

@exezbcz 

### Describe the solution you would like

"You just successfully bought this NFT (name of the piece)"
"Your NFT was burned/consumed."

+ check other actions (creating, unlisting, etc.) if they also need to be changed.

### Describe alternatives you have considered

hm.. not showing them at all? :D

**Comment by hassnian** [comment]
closed by https://github.com/kodadot/nft-gallery/pull/10096
