### ISSUE TITLE
Add composition API as required contributon practice 

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#4128]
### Is your feature request related to a problem?

>Some notes to help us migrate to vue3/nuxt3:
> We need to reduce using `nuxt-property-decorator` first and use composition API instead. 
> It will help us to migrate to vue3/nuxt3
https://github.com/nuxt-community/nuxt-property-decorator/issues/83#issuecomment-1245139696. at least for newer components
related: https://github.com/kodadot/nft-gallery/issues/2893

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/2690#issuecomment-1280409802_
      

### The task

- [ ] Edit style guide https://github.com/kodadot/nft-gallery/blob/main/STYLE_GUIDE.md
- [ ] Add examples how should components looks like
- [ ] Best we should follow [Vue3 style guide](https://vuejs.org/style-guide/rules-essential.html)

**Comment by vikiival** [comment]
I am checking that the majority was written by @kkukelka 

Would you like to take it sir?

https://github.com/kodadot/nft-gallery/blob/main/STYLE_GUIDE.md

**Comment by roiLeo** [comment]
link it with #3789

**Comment by kkukelka** [comment]
👋

**Comment by kkukelka** [comment]
@vikiival the style guide you posted is only partially applicable to our codebase, as its examples use the Options API
