### ISSUE TITLE
Burned NFTs still displayed

### ISSUE THREAD

**Issue by marvelet** [kodadot/nft-gallery#4129]
### What happened?

I mistakenly mistakenly minted twice, I already burned the NFT as shown here :
https://basilisk.subscan.io/extrinsic/2005188-2
https://basilisk.subscan.io/extrinsic/2004274-2

but until now it's still shown in my collection. like in this screenshots
*crossmarked images are the burnt one
 

### Please reproduce in steps

here's my collection page
https://kodadot.xyz/bsx/collection/2373313459?page=1

### Expected Behavior

All burned NFTs are not shown

### What browsers are you seeing the problem on?

Chrome, Mobile Android Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

![report kodadot](https://user-images.githubusercontent.com/87793956/196168164-683fa344-1f6c-4daa-8f85-41e7a9a442f1.png)

### Payment link for reward

https://kodadot.xyz/transfer?target=FCoN5YTCkGDphQNcDFFPNNMGuTxuDpRFW5G36DMEz5JvwNc&usdamount=0&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KngZhi** [comment]
Seems *burned* right now

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/11361147/196575877-feebf596-31a5-46bd-aaee-ad0b6a4465ed.png">

**Comment by marvelet** [comment]
I see all already fixed as expectes now. Many thanks
