### ISSUE TITLE
Doesn't load particular collection on Basilisk 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4132]
Seems doesn't load picture, but metadata are there.
~~no errors in console~~

okay 504 on pinata seems like that  

![image](https://user-images.githubusercontent.com/5887929/196415162-8c1814cd-e3b6-44f7-86a5-39cc3cfa9992.png)

![image](https://user-images.githubusercontent.com/5887929/196415208-e98b60cb-1a2a-49ba-a17b-2b6f113fcfa8.png)

![image](https://user-images.githubusercontent.com/5887929/196415748-8794f3a9-5b0d-4de8-a6f2-932b8fcfc4f0.png)

oh I see 

![image](https://user-images.githubusercontent.com/5887929/196415975-12b71c67-ce80-4d6f-b46b-522429197671.png)

**Comment by JustLuuuu** [comment]
The ones that wao sent are visible now.
Another not-visible collection: https://kodadot.xyz/bsx/collection/3134362679?page=2
This piece also doesn't load: https://kodadot.xyz/bsx/gallery/2608295324-3
I hope it will work soon :)

**Comment by yangwao** [comment]
> Gonna merge [kodadot/packages#54](https://github.com/kodadot/packages/pull/54)

and now smash hard reset on snek-dexer?

**Comment by yangwao** [comment]
Turns out our Cloudflare images integration was discarded or accidentally deleted from Basilisk explorer? 

It should hit fetch from this URL 
https://imagedelivery.net/jk5b6spi_m_-9qC4VTnjpg/e7260d0c-4fc4-4d07-64c8-9dfccbadf100/public
at this item https://beta.kodadot.xyz/bsx/gallery/1437594557-1

**Comment by yangwao** [comment]
Probably resolved by 
- https://github.com/kodadot/snek/pull/104
- https://github.com/kodadot/snek/pull/103

But on landing, there is still some issue like
- #4169
