### ISSUE TITLE
New social media cards SEO/OG 

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#4143]
Finally we have new release out!

![Screenshot 2022-10-19 at 12 28 04](https://user-images.githubusercontent.com/22471030/196667380-55508887-17c5-4c6a-a90e-87cbd82bcb4c.png)

It would be cute to have new preview cards.
I bet that @exezbcz has something in his sleeve.

**Comment by yangwao** [comment]
> Affirm. Do you mean with the new logo? 👀😄

more like with new neobrutalism background, keep current logo 🥹

**Comment by exezbcz** [comment]
Hmm, what about this? It still keeps some elements from the old banner, but it's in a different style. :DDD
![Slide 16_9 - 2 (1)](https://user-images.githubusercontent.com/90852205/197020604-06cacef6-d300-47a9-ab17-f9a022d49420.png)

**Comment by vikiival** [comment]
Waaaai love it!

**Comment by roiLeo** [comment]
Here are the rest of preview cards used on different pages

|  Collections | Gallery  | Mint  | Series | Spotlight |
|---|---|---|---|---|
|  ![k_card_collections](https://user-images.githubusercontent.com/9987732/197722726-8238054f-4598-461a-ad47-f16878ba2f73.png) | ![k_card_gallery](https://user-images.githubusercontent.com/9987732/197722831-2560c393-4203-436e-acff-e180e5bcd0cd.png) |  ![k_card_mint](https://user-images.githubusercontent.com/9987732/197722888-a1f2be7b-a4de-4921-bb59-79dd00e6719c.png) |  ![k_card_series](https://user-images.githubusercontent.com/9987732/197722926-537378ac-1722-4db2-a109-d65516e91b7d.png)  |  ![k_card_spotlight](https://user-images.githubusercontent.com/9987732/197722965-8a05c8a0-154b-4e3c-8a22-34c8918d3680.png) |

**Comment by vikiival** [comment]
Let's just use one for now ?

**Comment by exezbcz** [comment]
Agree, I would use only this one or the former one. I will make the different pages once the final design is finished and the full rebrand is done.

**Comment by yangwao** [comment]
Agree, as we will be changing it soon in the future, one for every view would be enough I guess :)
