### ISSUE TITLE
Show what's going on while minting to user

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#415]
While people use simple or classic mint, some bugs may happen or process goes successfully.
However if a user is on slow internet, the user really doesn't know if something is **happening** in the background

Would be probably nice to show the user what's happening in the background in some meaningful way.

**Comment by AndreyGrin** [comment]
I could take this one

**Comment by yangwao** [comment]
@AndreyGrin are you working on that? If so, can assign you! :)

Could be joined with #722 I guess, it could be upper bounty range ;)

**Comment by yangwao** [comment]
If someone wants to work on this 👀
Take charge whole experience of minting is important as first touch for new artists

**Comment by yangwao** [comment]
It would be time to revisit and handle what's happening in the background for the user.

**Comment by jkdizajn** [comment]
> It would be time to revisit and handle what's happening in the background for the user.

can you imagine it as an infographic - animated SVG
I think there are 3 phases of minting going on:
1. upload to IPFS
2. writing to the blockchain
3. listing on the blockchain

or is it something else?

**Comment by thea-exe** [comment]
Do you have an idea of how the toast notification will look like?  @yangwao

**Comment by yangwao** [comment]
> > It would be time to revisit and handle what's happening in the background for the user.
> 
> can you imagine it as an infographic - animated SVG I think there are 3 phases of minting going on:
> 
> 1. upload to IPFS
> 2. writing to the blockchain
> 3. listing on the blockchain
> 
> or is it something else?

the process is a bit more complex but sure, @vikiival might expand on this and @thea-exe might take it :)

> Do you have an idea of how the toast notification will look like?

we can re-use our fun facts loader or modal with infinity animation, or if you want to come up with something very own, let's go :)

**Comment by vikiival** [comment]
> Do you have an idea of how the toast notification will look like?
Yup we use notifications from buefy 
https://buefy.org/documentation/notification

> we can re-use our fun facts loader or modal with infinity animation,
Yeah this would be better

> the process is a bit more complex but sure,
 
1. First tell user about publishing to ipfs
2. Then say upload success
3. user should sign the payload 
4. waiting for tx processing
5. waiting for block finalization

**Comment by jkdizajn** [comment]
> 



> * First tell user about publishing to ipfs
> 
> * Then say upload success
> 
> * user should sign the payload
> 
> * waiting for tx processing
> 
> * waiting for block finalization

I can do:
 5+1 (the sixth will be "done") SVG animations that will be loaded during the process

or one that explains the 5 points 
example: https://codepen.io/madetoday/pen/MYxYeo/

what do you say?  @vikiival @yangwao @thea-exe

**Comment by JustLuuuu** [comment]
we have something like that now
