### ISSUE TITLE
Loading the NFT when using the NFT link

### ISSUE THREAD

**Issue by DeluneClaire** [kodadot/nft-gallery#4173]
### Is your feature request related to a problem?

When you want to share your NFT on socials or anywhere, and you use the link, it shows this:

<img width="592" alt="Snímek obrazovky 2022-10-25 v 13 21 54" src="https://user-images.githubusercontent.com/104791453/197760104-d3c832f1-b8c9-4c0b-9ced-dc2bf4ac7435.png">

### Describe the solution you would like

I would instead want to see my NFT and not our logo; I think it would be much better for users when they want to share their NFTs or when we want to share their art.

### Describe alternatives you have considered

I think in the case of using the link for NFT; it's better if it shows the NFT and not the logo.

### Screeenshots

-

### Are there opened related issues?

-

**Comment by roiLeo** [comment]
Closing this since it's a know issue ref #4058, #2759, #2388, #2136
