### ISSUE TITLE
Royalty toggle reversed behaviour

### ISSUE THREAD

**Issue by green-jay** [kodadot/nft-gallery#4189]
### What happened?

Royalty toggle turns on royalty when it's off and vice versa

### Please reproduce in steps

Mint NFT -> use royalty toggle

### Expected Behavior

When I turn toggle ON, i will be able to set royalty

### Screenshots

![image](https://user-images.githubusercontent.com/75261756/198363169-98b637da-ccdc-48fc-b264-a049a4dc5446.png)

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
Thanks for the feedback, here's how I see the feature.

Current behavior:
- when royalties switch is on: royalties are sent to the creator address 
- when royalties switch is off: you can set an address where the royalties will be sent

it is true that it's disturbing for the user

**Comment by green-jay** [comment]
> Thanks for the feedback, here's how I see the feature.
> 
> Current behavior:
> 
> * when royalties switch is on: royalties are sent to the creator address
> * when royalties switch is off: you can set an address where the royalties will be sent
> 
> it is true that it's disturbing for the user
> 
> What we need to fix:
> 
> * make it possible for the creator to disable royalties

Ok I see, it is a bit confusing, I would expect the royalty to be disabled when the toggle is OFF. And when it is ON to have a possibility to change the default creator address.

A simple way how to achieve disabling it would be setting royalty to 0 - that also means it could never be set again by anyone else which should be exactly what we want given there is no scenario where you would like to set royalty after ownership change.
