### ISSUE TITLE
Save draft of NFT while making NFT

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#419]
Would be nice to introduce a system for drafts for minting.
To avoid accidentally to back in the page and not to lost prepared mint. What a loss a time.
Save to local storage probably or check to use offline textile. If we want to save to textile, allow only for users for example who did at least 3-10mints?

- [ ] introduce Drafts section?
- [ ] picked file - it's on slate now anyways?
- [ ] name
- [ ] tag
- [ ] description
- [ ] price
- [ ] tags
- [ ] make PR
- [ ] post your KSM

### Bonus 
If you manage to save draft per address account for the user

### Additional info
Check #164 #207 for additional info

**Comment by yangwao** [comment]
We can use textile for this?

**Comment by JustLuuuu** [comment]
not relevant antmore
