### ISSUE TITLE
Graphql error on landing

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#4191]
on landing beta, might come from lastEvent query?

![Screenshot 2022-10-28 at 08-51-13 KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/198522329-9ef1dba2-1546-4f97-9784-b7e65c482eba.png)

**Comment by KngZhi** [comment]
yes, it is the same error with #4172

**Comment by Jarsen136** [comment]
> yes, it is the same error with #4172

Merged
