### ISSUE TITLE
Error on Landing due snek@005 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4195]
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/5887929/198580953-f3cf45ea-d02b-48fa-88dc-d2b2b79770cb.png">

**Comment by vikiival** [comment]
Exaclty 3 min ago I made hard reset. 
<img width="1680" alt="Screenshot 2022-10-28 at 13 55 18" src="https://user-images.githubusercontent.com/22471030/198581450-8bd9aa75-a7de-4b5f-97e4-cf0fa5b3bc21.png">

**Comment by yangwao** [comment]
<img src="https://media0.giphy.com/media/45d2TL6t0JzaT46ofC/giphy.gif"/>

works meanwhile
