### ISSUE TITLE
Undefined on preview on social media

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#420]
Interesting what has happened here
https://nft.kodadot.xyz/rmrk/detail/7653557-900D19DC7D3C444E4C-AIW-AI_WOMAN_11-0000000000000001
![image](https://user-images.githubusercontent.com/5887929/120222400-2d619f00-c240-11eb-9812-525a4ac3c59e.png)

**Comment by AndriiHrynchuk** [comment]
hey, this is pretty weird. I've checked yesterday and saw the same issue. No changes made and today it works.
<img width="783" alt="Screenshot 2021-06-03 at 16 22 03" src="https://user-images.githubusercontent.com/65897232/120660769-f2ea4300-c487-11eb-876d-7d4df38d8983.png">

**Comment by AndriiHrynchuk** [comment]
or maybe we shouldn't cache generated images forever? Anyway, I could look deeply there in 1,5 week

**Comment by yangwao** [comment]
@AndriiHrynchuk probably makes sense. 
Only thing I can came up is that price change won't be reflected but I guess a tradeoff for speed generation would be better here :)
I guess found it randomly for that one particular image, maybe some data wasn't resolved for a crawler.

Also, I guess we should have some defaults for next scenarios like this, better than undefined 😃

**Comment by yangwao** [comment]
Seems did not happen again, closing as it's stale issue
