### ISSUE TITLE
Priority is too low on Basilisk 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4205]
Seems we should gracefully handle situations like that even I think it's more issue which should be handled by wallet?

Is there something user can do in this?

bXn2WtSvE61qcDCJBuepdaSoy2HxpyBb8UE2hWvgZQiZ9hFnr

https://basilisk.subscan.io/account/bXn2WtSvE61qcDCJBuepdaSoy2HxpyBb8UE2hWvgZQiZ9hFnr

![telegram-cloud-photo-size-4-5974222367284639784-w](https://user-images.githubusercontent.com/5887929/198828536-b7439010-d297-4639-aacd-214ce43efbd8.jpg)

**Comment by vikiival** [comment]
This is issue that you made same tx twice
