### ISSUE TITLE
Artist has a problem with minting

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4221]
### What happened?

Problem with minting process. NFT did not load.

### Please reproduce in steps

After minting an NFt on RMRK, it did not mint. Weird notification - check screenshot.

Minting from this address: EF9zLDJj2cvMpUBwd4EeloPQHeEofKAl
Ro8XLKPP9V7dTZn

### Expected Behavior

loading minted NFT

### What browsers are you seeing the problem on?

Safari

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Screenshots

![91A4F5B9-3454-4EA9-B7D1-8F05423B74D2](https://user-images.githubusercontent.com/104380776/199314870-9013131e-d8d6-4b2c-b732-7b732f6bacec.jpeg)

![image](https://user-images.githubusercontent.com/104380776/199317686-62b127ec-30db-44ec-a806-02aac2345cff.jpeg)

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
Is there any wallet on safari?

**Comment by yangwao** [comment]
Related
https://docs.kodadot.xyz/tutorials/how-to-fix-error-keypair.html

**Comment by yangwao** [comment]
> Is there any wallet on safari?

Enkrypt apparently? 

https://www.reddit.com/r/Polkadot/comments/xvizuv/enkrypt_launches_on_safari_the_first_web3_wallet/

**Comment by yangwao** [comment]
This is resolved I guess meanwhile.
Novawallet works well
