### ISSUE TITLE
redesign: Offers section

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#4233]
requirements: https://github.com/kodadot/nft-gallery/issues/4111#offers-section

## <a href="#offers-section" id="offers-section">Offers</a>
![image](https://user-images.githubusercontent.com/5887929/195137148-ba291855-4978-40d7-a07e-c4e0497826ec.png)
This would actually work only on Basilisk, as there support for offers. 
We will show all offers on particular NFT.
Columns like we have in current offers.
It has a column price in assets; this will be in future multi-currency. 
**Price** in asset, in future, can be KSM, BSX, aUSD and so on
**USD** denomination of those assets... this will be tricky as there might be assets which are not always will be traded.. we will need figure out write wrapper probably for this one
**Floor Differences** will be query which will check against floor of current collection and calculate if offer is above or below from nominal floor
**Expiration** of offer in relative time, like hours, days, weeks, months
**From** would show the address with resolver for identity on top of the address

**Comment by exezbcz** [comment]
Yup, good points. Its mainly for future. It was also meant for collections with the same items. For example spirit keys - or other acces keys - same item, same properties, different listing price. If that doesnt make sense we can easilly remove it. 
What do you think?

**Comment by exezbcz** [comment]
Another thing I forgot to include in the designs was accepting and canceling offers. I'll try to add it soon.
