### ISSUE TITLE
redesign: Item Activity section

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#4234]
requirements: https://github.com/kodadot/nft-gallery/issues/4111#activity-section

## <a href="#activity-section" id="activity-section">Item Activity</a>
![image](https://user-images.githubusercontent.com/5887929/195137490-44d1ca1e-668a-4e85-8456-00c11bddf315.png)
An important one, it's coming. 
Instead of dropdown, we plan to have selecting boxes, where multi-checkbox is possible. So for example you could see Listings and Sales at once. 
Default could be Sales.
**Event** column would be name of events
**Price** column would be denominated in that asset
**From** column address 
**Date** will be relative date with possibility hover to get exact date

**Comment by exezbcz** [comment]
> hi, @exezbcz do we already have a tooltip style in the new design?

do you mean tooltip for the exact date?

**Comment by yangwao** [comment]
> do you mean tooltip for the exact date?

Yup I guess means for absolute date
