### ISSUE TITLE
Cosmetic adjustment pagination version

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#425]
With merged #423 some issues arosed.
Make two major showing modes 

- [ ] When you are using 27" 4k, make sense to keep it like 3x4 tiles, together 12 so people can just tap next page easier and doesn't need to scroll down

![image](https://user-images.githubusercontent.com/5887929/120829778-14b5f980-c55e-11eb-9f7c-e56eaa1f818c.png)

- [ ] When you are at 13", make it like for 3x2, together 6 tiles, similar scenario as above, people doesn't need to scroll down
![image](https://user-images.githubusercontent.com/5887929/120829917-3f07b700-c55e-11eb-86e0-420e6138bb83.png)

~- [ ] Probably put prev and fwd button into search bar~

**Comment by vikiival** [comment]
OK point is to keep set new max per page eg `first`

**Comment by roiLeo** [comment]
is this still relevent?
I think we can close this since we introduce new version with Layout & top pagination

**Comment by yangwao** [comment]
We have infinite scroll meanwhile and changed a layout a lot since then 
- #2859 
- #2921 
- #1411 
- #1582
