### ISSUE TITLE
minting on snek not displaying nft

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#4251]
#### What happened

I've mint a new nft on BSX (Rococo) and it won't display after I'm redirected
Brought same nft with another wallet account, it worked nft owner changed but still don't have collection name nor creator

Tested on `/snek/gallery/331660682-4`

- ✅ mint
- ✅ buy success
- 🟥 return `null` on nftEntitybyId

#### Relevant log

```
⚠️  warn No NFT with ID 4 fallback to RPC Node
```
```
 Uncaught (in promise) TypeError: metacall is not a function
```

**Comment by yangwao** [comment]
Still related?

**Comment by roiLeo** [comment]
Throw error:
```bash
n: 1014: Priority is too low: (1250 vs 56): The transaction has too low priority to replace another transaction already in the pool.
```

![Capture d’écran 2023-01-18 à 11 59 38 AM](https://user-images.githubusercontent.com/9987732/213154641-245b2422-9b80-454f-b086-0d139324b30b.png)

**Comment by roiLeo** [comment]
closed as fixed

(by workers & snek upgrade)

![Screenshot 2023-03-06 at 09-36-37 FLAME ROYALTY 50 KodaDot - NFT Market Explorer](https://user-images.githubusercontent.com/9987732/223058733-63165e66-9100-4a9a-81a8-64f5542a2eda.png)
