### ISSUE TITLE
Small visual details for consideration

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4254]
### Is your feature request related to a problem?

Not related to any problem, just minor details to consider.
kodadot.xyz: 
- blurry logo
- too much text?

![image](https://user-images.githubusercontent.com/104380776/199978470-07671a63-9c81-459e-a75a-8d066646facf.png)

### Describe the solution you would like

First, **the logo** on the top-left corner of our webpage seems blurry and in bad quality. I would also consider making it bigger. It's visible that the picture was not uploaded in good quality. I also think that we don't need to have a Beta sign there anymore.

Second, look at the picture. _**Basilisk (Kusama) RMRK (Kusama)**_, having 4 words in 1 row connected to 2 things is a little bit confusing (?). Maybe not confusing, but it just doesn't look correct and smooth. Maybe I would try to put Kusama under it? Maybe even with smaller letters?

### Describe alternatives you have considered

already described before

**Comment by yangwao** [comment]
> Second, look at the picture. _**Basilisk (Kusama) RMRK (Kusama)**_,

Try logging in and logging out in your wallet, seems your browser has an old version; this is from kodadot.xyz 

![image](https://user-images.githubusercontent.com/5887929/200000468-6227cbd6-dfc7-46ea-b647-533e7b6d2e86.png)

With logo, yeah having svg version would be best I guess, or putting back that one with Koda

**Comment by exezbcz** [comment]
> > Second, look at the picture. _**Basilisk (Kusama) RMRK (Kusama)**_,
> 
> Try logging in and logging out in your wallet, seems your browser has an old version; this is from kodadot.xyz
> 
> ![image](https://user-images.githubusercontent.com/5887929/200000468-6227cbd6-dfc7-46ea-b647-533e7b6d2e86.png)
> 
> With logo, yeah having svg version would be best I guess, or putting back that one with Koda

i thought its a svg. I personally think that the shorter one would look better. I will upload it here
