### ISSUE TITLE
Show different picture for burned NFTs

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#426]
This how burned NFT looks like 
![image](https://user-images.githubusercontent.com/5887929/120831317-b427bc00-c55f-11eb-8913-1a0a22e531b2.png)

we should have a dedicated picture for this

**Comment by anettrolikova** [comment]
Probably we can use this as picture for burned NFT: 
![image](https://user-images.githubusercontent.com/44020788/120994412-bdde3900-c784-11eb-9bcf-4ffadd1cc078.png)
or probably this version looks better 
![image](https://user-images.githubusercontent.com/44020788/120995035-54aaf580-c785-11eb-911b-c0e229f6eb20.png)

**Comment by vikiival** [comment]
Maybe have a blur and 🔥  as overlay ?

**Comment by anettrolikova** [comment]
Another ideas: 
![image](https://user-images.githubusercontent.com/44020788/121175468-5d6dfb00-c85b-11eb-8166-c28b2fc04888.png)
![image](https://user-images.githubusercontent.com/44020788/121176509-95297280-c85c-11eb-906c-12bc063aaaf3.png)
![image](https://user-images.githubusercontent.com/44020788/121176960-20a30380-c85d-11eb-9914-88acd2dfbbb4.png)
![image](https://user-images.githubusercontent.com/44020788/121177061-3dd7d200-c85d-11eb-8ce0-d6a553dbb605.png)

**Comment by anettrolikova** [comment]
Added green flame as suggested by @yangwao 
![image](https://user-images.githubusercontent.com/44020788/121332311-0aa64900-c918-11eb-8801-08886db80e6e.png)

**Comment by yangwao** [comment]
> Added green flame as suggested by @yangwao
> ![image](https://user-images.githubusercontent.com/44020788/121332311-0aa64900-c918-11eb-8801-08886db80e6e.png)

this one would work!

**Comment by anettrolikova** [comment]
Isn’t this solved ? Or still looking for suggestions ?

**Comment by roiLeo** [comment]
I really like the one with the text "This NFT was burned"

**Comment by prachi00** [comment]
If we have a finalized image, I can pick this up? I like the green flame one.

**Comment by yangwao** [comment]
As we don't show burned anymore, closing in favour of #679
