### ISSUE TITLE
Redesign: Top collection data on landing leftovers

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4263]
## Top collections
- On the bigger screens, there are 3 columns next to each other of top/trending collection cards. 
![image](https://user-images.githubusercontent.com/90852205/194553600-4ed211e7-035c-47fb-80bb-8eb957febc65.png)
- In the design, there are only 2. 
- content inside card: 
![image](https://user-images.githubusercontent.com/90852205/194553736-0dafad53-e8b2-4c1b-9681-746695c64d0a.png)
now it's missing network, USD volume, and % change. 
![image](https://user-images.githubusercontent.com/90852205/194553971-c72a8416-06a4-49df-bd88-192d015c3fa5.png)
- missing filters for the time period and network. 
- "see more link" should be on hover similarly to the nav bar/footer links. 
- https://github.com/kodadot/nft-gallery/issues/4185#issuecomment-1295015373

## Tasks
- https://github.com/kodadot/nft-gallery/issues/4265
- https://github.com/kodadot/nft-gallery/issues/4380
- https://github.com/kodadot/nft-gallery/issues/4264
- https://github.com/kodadot/nft-gallery/issues/4266

_Originally posted by @exezbcz in https://github.com/kodadot/nft-gallery/issues/4090#issuecomment-1303984638_

**Comment by prachi00** [comment]
@yangwao @exezbcz this isn't an issue anymore right?

**Comment by exezbcz** [comment]
> @yangwao @exezbcz this isn't an issue anymore right?

yup, i think there is only one thing left  in this issue and then we can close this. 
- #4380

**Comment by roiLeo** [comment]
closed in favor of #4380
