### ISSUE TITLE
Add floor to top collections on landing 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4265]
Missing Floor on Basilisk currently.

![image](https://user-images.githubusercontent.com/5887929/200121622-1e13adee-be81-421d-bc0e-c21e2c79fb58.png)

**Comment by roiLeo** [comment]
> Missing Floor on Basilisk currently.

related with kodadot/snek#116

This is not really the floor price that is displaying on TopCollection component

**Comment by yeshealer** [comment]
Currently `floorPrice` get NULL when chain is `Basilisk`.

```
query seriesInsightList(
  $limit: Int
  $orderBy: SeriesOrderByInput!
  $where: SeriesWhereInput
) {
  collectionEntities: series(
    limit: $limit
    orderBy: [$orderBy]
    where: $where
  ) {
    id
    **floorPrice**
    averagePrice
    image
    metadata
    sold
    name
    total
    buys
    unique
    uniqueCollectors
    volume
  }
}
```

Here is screenshot when chain is `Basilisk`
![image](https://user-images.githubusercontent.com/88679102/205432240-e0102bf7-9c18-4931-83ce-8de0a901013a.png)

Here is screenshot when chain is `RMRK`
![image](https://user-images.githubusercontent.com/88679102/205432274-6703d905-1f2e-444b-a301-c4ace97f1256.png)

I'm not familiar with `graphQL`, so where can I calculate and get `floorPrice`?

**Comment by yangwao** [comment]
> I'm not familiar with `graphQL`, 
It's easy! :)

> so where can I re-calculate and get `floorPrice`?

Rubick is for RMRK - https://github.com/kodadot/rubick
Snek is for Basilisk - https://github.com/kodadot/snek

**Comment by yangwao** [comment]
> I'm not familiar with `graphQL`, so where can I re-calculate and get `floorPrice`?

hey have you managed to progress with this one? :)
