### ISSUE TITLE
The social media share button on the profile is not completely displayed 

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#427]
The social media share button on the profile page is not completely displayed

https://user-images.githubusercontent.com/81104034/120852218-36bd7500-c57a-11eb-92a2-bd20c9e0a399.mp4

**Screenshots**
![obrázok](https://user-images.githubusercontent.com/81104034/120852486-8e5be080-c57a-11eb-9c20-b43571fc64fc.png)

**Desktop (please complete the following information):**
 - OS: win 10 pro
 - Browser Firefox 
 - Version 89.0

**Comment by JKrupinski** [comment]
Thanks, it will be fixed in #424

**Comment by yangwao** [comment]
Seems done 
![image](https://user-images.githubusercontent.com/5887929/120987679-1c53e900-c77e-11eb-808b-40784841eb7f.png)

**Comment by jkdizajn** [comment]
> 
> 
> Seems done
> ![image](https://user-images.githubusercontent.com/5887929/120987679-1c53e900-c77e-11eb-808b-40784841eb7f.png)

or not... 

the problem is not solved, continues on the profile page, also on the collection page
![obrázok](https://user-images.githubusercontent.com/81104034/124238302-b3f7ed80-db18-11eb-9e48-7a234aa3e958.png)
![obrázok](https://user-images.githubusercontent.com/81104034/124238376-cf62f880-db18-11eb-8649-319e003442df.png)

**Comment by yangwao** [comment]
Thanks for reporting @jkdizajn 
@JKrupinski seems we should re:think this 👀

**Comment by yangwao** [comment]
Fixed in ee02deb
![image](https://user-images.githubusercontent.com/5887929/124293405-ea545d80-db56-11eb-8210-2e79252a04e9.png)
