### ISSUE TITLE
i have enough fund but it's always rejected "error balance is not sufficient"

### ISSUE THREAD

**Issue by RyGithubQ** [kodadot/nft-gallery#4280]
### What happened?

 I've tried to mint in kodadot several times but it always failed. It says "insufficient balance" eventhough there's enough balance on the wallet. 
 I'm using KSM & i've already explored koda in rmrk. 
I've reinstalled Google Chrome & the problem still persist

My internet connection is stable. It's 7.48 mbps download & 6.51 mbps upload
Is this perhaps caused by blocked connection (because of the government in my area) ? do i need VPN/changing my DNS ?

### Please reproduce in steps

i go to Create > Classic > Collection > NFT > select a collection > Filled all the details > press "CLICK TO CREATE NFTS"

### Expected Behavior

it'll failed to mint & there'll be a pink pop up in the right corner that says "error insufficient balance"

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### At which chain did you encounter bug?

RMRK

### Screenshots

![image](https://user-images.githubusercontent.com/117632581/200261030-6f6225af-8481-402e-bd90-248860bfcd47.png)
![image](https://user-images.githubusercontent.com/117632581/200261120-3f56ae58-2f6a-4c40-8efd-bd7fb6327943.png)

### Relevant log output

```shell
[
  {
    name: "calls",
    type: "Vec<Call>",
    type_name: "Vec<<T as Config>::RuntimeCall>",
    value: [
      {
        call_index: "0001",
        call_module: "System",
        call_name: "remark",
        params: [
          {
            name: "remark",
            type: "Vec<U8>",
            value: "RMRK::MINT::1.0.0::%7B%22id%22%3A%22F410E6CB4468D3EF31-YJIYO_FILE%22%2C%22_id%22%3A%22%22%2C%22symbol%22%3A%22YJIYO_FILE%22%2C%22issuer%22%3A%22J6LDrc7eUiZ5gAqgGaDXCGeQ3r72gWocjxHxh2P8VYv3YTf%22%2C%22version%22%3A%221.0.0%22%2C%22name%22%3A%22Yojiyo%20File%22%2C%22max%22%3A1%2C%22metadata%22%3A%22ipfs%3A%2F%2Fipfs%2Fbafkreif5lpt7pvif2rbksl6q3gbtc7piu4gf4uir5ycgk4m5qijzpzam3e%22%7D"
          }
        ]
      },
      {
        call_index: "0001",
        call_module: "System",
        call_name: "remark",
        params: [
          {
            name: "remark",
            type: "Vec<U8>",
            value: "RMRK::MINTNFT::1.0.0::%7B%22events%22%3A%5B%5D%2C%22name%22%3A%22Yojiyo%20File%22%2C%22instance%22%3A%22YOJIYO_FILE%22%2C%22transferable%22%3A1%2C%22collection%22%3A%22F410E6CB4468D3EF31-YJIYO_FILE%22%2C%22sn%22%3A%220000000000000001%22%2C%22_id%22%3A%22%22%2C%22id%22%3A%22%22%2C%22metadata%22%3A%22ipfs%3A%2F%2Fipfs%2Fbafkreif5lpt7pvif2rbksl6q3gbtc7piu4gf4uir5ycgk4m5qijzpzam3e%22%2C%22currentOwner%22%3A%22J6LDrc7eUiZ5gAqgGaDXCGeQ3r72gWocjxHxh2P8VYv3YTf%22%7D"
          }
        ]
      },
      {
        call_index: "0400",
        call_module: "Balances",
        call_name: "transfer",
        params: [
          {
            name: "dest",
            type: "sp_runtime:multiaddress:MultiAddress",
            value: {
              Id: "0x11def1c5947cbe4396b8765f69cf23fdc3f9e5736359f53797aedc3a352f7b3a"
            }
          },
          {
            name: "value",
            type: "compact<U128>",
            value: "44816253361"
          }
        ]
      }
    ]
  }
]
```

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
can you please drop transaction hash, best subscan link?

**Comment by RyGithubQ** [comment]
https://kusama.subscan.io/extrinsic/15138864-2

**Comment by JustLuuuu** [comment]
this issue is too old to reproduce, please check if you have balance on correct chain
