### ISSUE TITLE
Wrong ticker on the user's page

### ISSUE THREAD

**Issue by Julissa0001** [kodadot/nft-gallery#4288]
### What happened?

The main and beta versions have the wrong currency - BSX instead of KSM

### Please reproduce in steps

You have to go to any buyers, for example, here:
 https://beta.kodadot.xyz/bsx/u/bXkaQPkcaNytoF6rAg5nbmrMy5wWGZrykUMGD39yqxvzivRTr?tab=offers&page=1
 and then click on the "offers made" tab.
 In addition, you can also see the wrong currency in the profile header. 

### Expected Behavior

All prices must be specified in the KSM

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Which wallet you are using?

PolkadotJS

### Screenshots

![W9WoKvl](https://user-images.githubusercontent.com/115104650/200722432-199a2d55-88d9-4d47-876e-d2f5d25b168f.png)

### Payment link for reward

https://kodadot.xyz/transfer?target=bXismpoTnigDrWfCGbHdp21gjECttbXPM6aQjo1a664LsFgGj&usdamount=0&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
pay 30

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 27.05 USD/KSM ~ 1.109 $KSM
🧗 [bXismpoTnigDrWfCGbHdp21gjECttbXPM6aQjo1a664LsFgGj](https://kusama.subscan.io/account/bXismpoTnigDrWfCGbHdp21gjECttbXPM6aQjo1a664LsFgGj)
🔗 [0xa1e2eaba04d665d9f19e422d16ee138030036ed07d245094d6a693e9964a4f38](https://kusama.subscan.io/extrinsic/0xa1e2eaba04d665d9f19e422d16ee138030036ed07d245094d6a693e9964a4f38)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by Julissa0001** [comment]
Fine! Thanks, but it looks like the transaction failed

**Comment by Julissa0001** [comment]
Hmm.. I used the KSM address, the same as last time

**Comment by roiLeo** [comment]
pay 30

**Comment by Julissa0001** [comment]
Hey! :) Any updates?
