### ISSUE TITLE
Differentiate minting between RMRK and Basilisk 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4296]
Right now I sense we had few issues where people though they're minting on Basilisk and turns out they minted on RMRK

We will be creating network selector for minting with network names and network logo. Once people click on that will land them to particular network minter.

- /bsx/create
- /rmrk/create

Will chat with @exezbcz and deliver designs

Once designs are around, someone can take it.

**Comment by exezbcz** [comment]
imo it's associated with redesigning the minting process. Also, it could be done similarly to the portfolio(xcm + teleport) page - the selector of the network.

**Comment by yangwao** [comment]
> imo it's associated with redesigning the minting process.

yes

Continue to 
- #4752
