### ISSUE TITLE
overlapping search bar results

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#4309]
![image](https://user-images.githubusercontent.com/90852205/201473385-d81bb6c3-8d42-4d60-b3af-468060085ece.png)
when scrolling down on landing page, then focusing on search bar and then  quickly type something.

**Comment by daiagi** [comment]
@exezbcz  
can you clarify? 
I don't understand what is the issue / how to reproduce

**Comment by exezbcz** [comment]
> @exezbcz can you clarify? I don't understand what is the issue / how to reproduce

there are two search results opened at once. Idk if it was trigerred on lower internet speed, I just scrolled down and hit "K" and then quickly start typing.

**Comment by roiLeo** [comment]
fixed somewhere, can't reproduce it. feel free to reopen
