### ISSUE TITLE
Low contrast of buy button does not work well with low contrast screens

### ISSUE THREAD

**Issue by Tomen** [kodadot/nft-gallery#4331]
### Is your feature request related to a problem?

The low contrast of the "Buy" button makes it hard to discover it quickly on older low contrast screens.

### Describe the solution you would like

better contrast for the primary CTA

### Describe alternatives you have considered

-

### Screenshots

![image](https://user-images.githubusercontent.com/317186/201889340-8e3282d2-32c7-49f4-83f8-c6486766a4e4.png)

**Comment by roiLeo** [comment]
Hey! Thank you for reporting this, but it will be changed in the upcoming new design.

**Comment by yangwao** [comment]
> The low contrast of the "Buy" button makes it hard to discover it quickly on older low-contrast screens.

Hey @Tomen, thanks for reporting this; we already thought about this in the new design
- #4111 
- feel free to explore more about what's coming to the new KodaDot 3.0 😏
- if that satisfies this, feel free to close issue or, if not elaborate on what could be done till we implement a new one till it's time
<img width="943" alt="image" src="https://user-images.githubusercontent.com/5887929/202474655-b431645f-38c3-42a7-9130-27319dd28780.png">

**Comment by Tomen** [comment]
looks good to me. godspeed!
