### ISSUE TITLE
Redesign toast notification

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4341]
It can be triggered whenever you copy address for example

for example here Share -> Copy Link
https://deploy-preview-4330--koda-nuxt.netlify.app/bsx/gallery/2548799063-43?redesign=true

<img width="291" alt="image" src="https://user-images.githubusercontent.com/5887929/202200464-cea24880-df12-4872-9b34-757176fa98dd.png">

As always @exezbcz will drop some designs 😎✨

**Comment by exezbcz** [comment]
lets use this style for now. Its a 12px text (small) in a button secondary
![image](https://user-images.githubusercontent.com/90852205/202458902-a86a31a6-1da0-4f2c-ae55-44487b13fea0.png)
its in figma landing page handoff, next to the hover card. 
![image](https://user-images.githubusercontent.com/90852205/202459002-48107190-fea9-4ebc-80f9-0b4c0fc850c3.png)
https://www.figma.com/file/3iOjW12ERFRDSVnpLuhQmf/landing-page-handoff?node-id=0%3A1&t=RoEcjbvfoU42pwPO-1

**Comment by exezbcz** [comment]
![image](https://user-images.githubusercontent.com/90852205/203105324-3d2a9a8b-78bb-4a31-9d06-b3b06f120803.png)
btw, the font doesnt look like 12px, also make it please solid color so its not transparent.

**Comment by roiLeo** [comment]
> ![image](https://user-images.githubusercontent.com/90852205/203105324-3d2a9a8b-78bb-4a31-9d06-b3b06f120803.png) btw, the font doesnt look like 12px, also make it please solid color so its not transparent.

On it.
