### ISSUE TITLE
expanded container color v2

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#4348]
its happening again on kodadot.xyz 
Description in #4342 
![image](https://user-images.githubusercontent.com/90852205/202450241-ee826f96-41a3-46fa-8076-aaf70fb068cb.png)

**Comment by roiLeo** [comment]
Hey @exezbcz, when issue closed and PR merged refer to beta.kodadot.xyz not kodadot.xyz (production)
@yangwao will make a new release in the upcoming days

**Comment by exezbcz** [comment]
> Hey @exezbcz, when issue closed and PR merged refer to beta.kodadot.xyz not kodadot.xyz (production) @yangwao will make a new release in the upcoming days

Ic, my bad, thanks!
