### ISSUE TITLE
Align to the black 🖤, minor tweaks

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#435]
In the gallery, we have still white background on these cards
![image](https://user-images.githubusercontent.com/5887929/120993154-9044c000-c783-11eb-8788-e6c2d5630d65.png)

Remove theatre view mobile as it does nothing :)
https://user-images.githubusercontent.com/5887929/120993211-9b97eb80-c783-11eb-9425-c0cde1f25990.mp4

Emojis needs to have black background as well 
![image](https://user-images.githubusercontent.com/5887929/120993860-3d1f3d00-c784-11eb-8b82-a27c3f5bd7fc.png)
https://nft.kodadot.xyz/rmrk/detail/7801000-88DBAB15CE82B3DD71-KD-1._VASTIUS-0000000000000001

**Comment by pandasamanvaya** [comment]
Hi @yangwao. To hide the ``default view`` button in mobile/tablets, I used the threshold screen-width = 768px. I got this value by experimenting with the screen-width and observed that when screen-width=768px, the image overlaps with the ``default view`` button and it zooms in. If you have any other way of determining the threshold, please let me know.

**Comment by yangwao** [comment]
yeah merged #436, sent to production, awesome stuff!
