### ISSUE TITLE
Unable to finish minting collection

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4358]
Artist have an issue with minting on RMRK. He minted 2 pieces, then this issue appeared:

![image](https://user-images.githubusercontent.com/104380776/202899401-1fc39c5f-1a27-4820-9ae0-a33193c34877.png)

He have enough ksm in wallet (Talisman).

**Comment by yangwao** [comment]
We should gracefully handling if user has enough balance to do operation on UI and if not don't allow to do so

**Comment by AshutoshSingh72** [comment]
@JustLuuuu address

**Comment by exezbcz** [comment]
There is confirmation for that, insufficient modal style; it looks like the disabled button does not always work. 

- https://github.com/kodadot/nft-gallery/pull/7241

**Comment by JustLuuuu** [comment]
> @JustLuuuu address

hello, this issue is from 2022, sadly I dont recall who was the artist. Probably close this issue?

**Comment by roiLeo** [comment]
> Probably close this issue?

say no more
