### ISSUE TITLE
Follow up top collection data volume and & change v2

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4364]
// TODO:
- missing translation 
- missing some types `(nft)`
- transform `<TopCollections />` component nuxt3 way
  - #4381 	
- refactor `timeFilters` with `<NeoButton />` from #4330 
<details>
  <summary>Code</summary>
  
```vue
      <b-field>
        <p class="control">
          <NeoButton :class="{ active: state.timeRange == 'Day' }" label="24 Hours" @click="setTimeRange('Day')" />
        </p>
        <p class="control">
          <NeoButton :class="{ active: state.timeRange == 'Day' }" label="7 Days" @click="setTimeRange('Week')" />
        </p>
        <p class="control">
          <NeoButton :class="{ active: state.timeRange == 'Day' }" label="30 Days" @click="setTimeRange('Month')" />
        </p>
        <p class="control">
          <NeoButton :class="{ active: state.timeRange == 'Day' }" label="All" @click="setTimeRange('All')" />
        </p>
      </b-field>
```
  
</details>

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/4332#pullrequestreview-1183865135_

**Comment by daiagi** [comment]
@yangwao @roiLeo 
Hi guys
I would be happy to add translations but tbh I don't know how
can you provide some guidance on that?
does it have to be all languages?

**Comment by roiLeo** [comment]
> can you provide some guidance on that? 

You can find some infos on [kodadot documentation](https://docs.kodadot.xyz/contrib-helpers.html#getting-started) 
We use [nuxt-i18n](https://i18n.nuxtjs.org/) as translation system ([vue i18n](https://kazupon.github.io/vue-i18n/introduction.html) wrapper for nuxt), feel free to check any component and you can find out how it's implemented/working.

> does it have to be all languages?

not necessarily but English is required
