### ISSUE TITLE
Landing page colors broken

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#4367]
![image](https://user-images.githubusercontent.com/90852205/203159224-48fd3218-275d-4ebc-973a-a249463820e8.png)
beta.kodadot.xyz
- first heading invisible - light mode

![image](https://user-images.githubusercontent.com/90852205/203159864-83f7d4f7-0247-40fb-b936-855087be45f8.png)
- colors broken

![image](https://user-images.githubusercontent.com/90852205/203160309-68b3c62a-c937-4d70-a991-7d1a179aeb7a.png)

font color should be black
![image](https://user-images.githubusercontent.com/90852205/203160234-1f08c418-05de-47c3-a7c7-c0e045bb1b8d.png)

- same with "featured articles"

**Comment by prachi00** [comment]
👋

**Comment by yangwao** [comment]
Probably related 

- #4364
- #4334

**Comment by yangwao** [comment]
Probably related 

- #4346

**Comment by prachi00** [comment]
yeah seems like, @daiagi would you mind taking a look at this one?

**Comment by prachi00** [comment]
![Screen Shot 2022-11-21 at 7 29 33 PM](https://user-images.githubusercontent.com/39299315/203214314-bdf2d132-6dce-4a0a-a600-2076b2a7fb0a.png)
wallet popup text isnt visible either

**Comment by daiagi** [comment]
@prachi00 
> wallet popup text isnt visible either

1. I'm not seeing that 
![image](https://user-images.githubusercontent.com/22791238/203215484-005d1f90-a26a-46a9-9024-c35162e55067.png)


2. I've got the fixed css ready
should i submit a PR or paste it here or?


![image](https://user-images.githubusercontent.com/22791238/203215864-7c2c1a11-14f0-4cc1-aa07-e3645198491c.png)

**Comment by exezbcz** [comment]
> btw, is this expected? show chain name in spotlight carousel? if not, can we also fix this issue or need a separate one? ![image](https://user-images.githubusercontent.com/734428/203216264-257552ae-036c-496d-a7b5-33e238b96da3.png)

nope

**Comment by roiLeo** [comment]
related with https://github.com/kodadot/nft-gallery/commit/20b0212edd86a82798a0f47f1aed3643f6b81c93
