### ISSUE TITLE
wrap oruga `table`, `tabs` and `tooltip` in histoire

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#4368]
unable to put `oruga-table` in histoire, will check later in seperate issue
![image](https://user-images.githubusercontent.com/734428/203224939-84236560-56dc-4819-a6f1-56a48933282d.png)

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/4233#issuecomment-1323063536_

**Comment by roiLeo** [comment]
wfm 
![Capture d’écran 2022-11-29 à 12 01 57 PM](https://user-images.githubusercontent.com/9987732/204512643-acc276df-67a5-4e21-b653-d33a899a3155.png)

**Comment by roiLeo** [comment]
> wfm ![Capture d’écran 2022-11-29 à 12 01 57 PM](https://user-images.githubusercontent.com/9987732/204512643-acc276df-67a5-4e21-b653-d33a899a3155.png)

Why didn't you push your code?! goddam!

continue in #5852
