### ISSUE TITLE
Explorer tweak before new design v0.9

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4378]
We will work with @exezbcz about some small and impactful changes to explorer before we come back to redesign the whole explorer after the collection view.

Primary, we will be putting filters on the side like any other marketplace has, which we will be pretty great about. 
Plus, we can update buttons to upcoming styles too. 
The thing is, we probably won't have time to circle back sooner than 6 weeks tbh

We mostly likely keep all functionality we have 
If you have suggestions for explorer, now is your time. 

## Proposed changes 
- put filters on the side
- update pagination button to neobrutalism style
- change the grid of items default based on min-width per card, i.e. @ 1024px will be 4, at @ 1920px be 6-8
- anything else you are wishing for xmas
- rename Gallery -> Items
- add blockchain switch 

## Current state
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/5887929/203386037-96353a20-5b13-46e7-a077-dd797edca638.png">

## Ref
- https://github.com/kodadot/nft-gallery/issues/4444

**Comment by roiLeo** [comment]
A while ago (#2947) I had started to work on something like this.

![167655522-86e1d19c-dc6d-4503-a55d-19718f85259c](https://user-images.githubusercontent.com/9987732/203506689-19aa234f-500a-4c92-acf9-e8b9bdf5ccd1.png)

> If you have suggestions for explorer, now is your time.

I would like to:
- be able to collapse side filters
- move sorting option in the top right
- change grid card size
- filter by media type (#1162)

Note:
- should we keep pagination?  I don't find so much use since we have infinite scroll

**Comment by exezbcz** [comment]
> A while ago (#2947) I had started to work on something like this.
> 
> ![167655522-86e1d19c-dc6d-4503-a55d-19718f85259c](https://user-images.githubusercontent.com/9987732/203506689-19aa234f-500a-4c92-acf9-e8b9bdf5ccd1.png)
> 
> > If you have suggestions for explorer, now is your time.
> 
> I would like to:
> 
> * be able to collapse side filters
> * move sorting option in the top right
> * change grid card size
> * filter by media type ([Filter for file type #1162](https://github.com/kodadot/nft-gallery/issues/1162))
> 
> Note:
> 
> * should we keep pagination?  I don't find so much use since we have infinite scroll

Nice! good ideas.
For version 0.9, I believe we will keep things basic before returning to it once the collection detail and other tasks are completed.
Thus we won't be adding many new features to the makeover. It would be only layout change and bit of a reorganizational change. 
Things that are going to be in the makeover: 
- collapsible burger menu
- layout change of the filters
- items in grid

I dont think we will add filter by media to this version. 

ad pagination - @yangwao said its a feature 

Thanks!

**Comment by yangwao** [comment]
> * should we keep pagination?  I don't find so much use since we have infinite scroll
> ad pagination - @yangwao said its a feature

Yes, we can drop pagination (looking R & OS), doesn't make sense now and eats some space. 
yet pimp infinite scroll to randomly not bounce on scroll up and test addressing properly. I recall we have bug when you go on item and return back it jumps you on different view port of page

**Comment by yangwao** [comment]
Closing and continue to #4474
