### ISSUE TITLE
ES Translation on Carbonless page

### ISSUE THREAD

**Issue by CdrsAlejandro** [kodadot/nft-gallery#438]
- [ ]  create sparate page like https://nft.kodadot.xyz/carbonless
- [ ]  put it on /es/MovimientoNFTSinEmisionesDeCarbono 
- [ ] link it to the about section
- [ ]  make PR

Movimiento NFT Sin Emisiones de Carbono 
KodaDot aportará a la huella de Carbono sin emitir Emisiones de Carbono, por defecto. 
Estamos tratando de establecer un movimiento en donde los artistas puedan compensar sus creaciones al mintearlas en KodaDot. Así de simple. Incluso estamos en una blockchain la cual es baja en emisiones de carbono Kusama.network, y planeamos lanzar nuestra propia infraestructura en una parachain llamada MetaPrime.network, creemos que debemos de dar un paso adelante y ser más neutrales en carbono y luego contribuir a ser una galería de carbono negativo de manera que impulse la forestación global. 

Misión de Carbono Neutral de KodaDot 
La misión de la galeria KodaDot es hacer fluir los recursos de los coleccionistas hacia la creación de arte digital con conciencia ambiental de manera que se pueda abordar la actual creciente crisis ambiental en la Tierra. Tenemos la intención de brindar una Calculadora que analice las Emisiones de Carbono y ayudar a hacer forestaciones impulsando a que sean la nueva normalidad y de facil acceso. Para poner en marcha este esfuerzo, nos hemos asociado con Offsetra que permite a los usuarios a apoyar "proyectos de alta calidad a favor del clima mediante la compra de creditos de compensacion de carbono" 

Los créditos de compensación de Carbono provienen de una variedad de proyectos orientados a la sostentabilidad. Offsetra solo obtiene compensaciones de proyectos validados y verificados bajo estrictos estándares reconocidos internacionalmente. Puede encontrar más informacion sobre el proceso de Offsetra disponible en su sitio web. 

Acciones Humildes 
Estamos concientes que el comprar compensaciones de Carbono no resolveremos el problema, pero podemos crear un pequeño efecto mariposa, y luego impulsar acciones impactantes para iniciar un movimiento de forestacion a mayor escala, donde seria nativo que las galerias NFT traigan con cada minteo, comprando compensaciones, de manera que destinaria un pequeño porcentaje de la compra de compensaciones de carbono y forestación. Intentaremos poner al menos una cierta cantidad de las ganancias de los artistas en función su decisión para impulsar la compra de compensaciones de crédito. No solo de sentirse bien, sino con una forma realmente impactante de probarlo. 

Construyendo un Impacto Ambiental Positivo 
Nuestro inicio es añadir un interruptor a la interfaz en donde se mintean los NFTs en donde cada artista elige puede elegir si quiere apoyar a los créditos de Carbono o no. Estaremos añadiendo la etiqueta 🌱 Carbonless al NFT donde luego podría rastrearse a través de la Interfaz de búsqueda y revisarse en la blockchain. Por lo tanto, los coleccionistas pueden encontrar innovador el coleccionar NFTs Carbonless. Una vez que Offsetra (u otros socios) descubran una forma de realizar pagos fiduciarios de Kusama para que se realicen las compensaciones de carbono, haremos una integración completa criptográfica nativa de extremo a extremo junto con ellos, por lo que cada NFT consistirá en un hash que dependa de Carbon Credit. Para llevar la visión a Casa, estamos realmente ansiosos por trabajar junto con Terraformation of Planet Earth donde se puede participar en distintas áreas para poseer parte del bosque, e incluso introducir el concepto de Forest as a Service. La imaginación es el límite. 

No somos los únicos y eso es genial 
Somos realmente conscientes de que el movimiento está a punto de comenzar cuando los medios de comunicación comenzaron a calentar la discusión y el movimiento #cleanNFT ha empezado. Una opción para el creador es elegir entre la variedad de plataformas de creación de NFTs que corren sobre blockchains bajas en carbono, lo que es realmente un gran comienzo. Otra opción es impulsar activamente el movimiento para que sea una galería de Carbono negativo.

Nuestra prueba de trabajo 
Nosotros (KodaDot) nos sentimos inspirados para unirnos a este movimiento a nuestra manera, como el agregar la opción para los creadores de poder mintear un NFT sin dejar huella de carbono y comenzar a mostrar cuales NFTs son 🌱 Carbonless y cuales no lo son. Para completar nuestra reserva de Créditos de Carbono, ya hemos comprado los créditos de carbono de KodaDot y planeamos automatizarlos de manera más sostenible en un futuro. 
Puede leer más en la página del perfil de KodaDot en Offsetra 

Una vez que hayas minteado un NFT 🌱 Carbonless en KodaDot estas invitado a unirte a nuestro canal oficial en Telegram y al Discord Oficial de KodaDot. 

Lista de Lectura 
Siempre que desee obtener más información sobre #cleanNFT, aquí te dejamos algo de material de lectura.

Check this out @yangwao

**Comment by yangwao** [comment]
Seems done
