### ISSUE TITLE
Loading page - text does not fit

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4385]
### What happened?

Tried to mint a new collection, and the text on the loading page did not fit in it.
<img width="1383" alt="Screenshot 2022-11-23 at 14 07 20" src="https://user-images.githubusercontent.com/104380776/203567683-7b2b15c3-1c6c-4b21-bb57-38bdd8093691.png">
You can see that did you know fact is outside the frame

### Please reproduce in steps

creating new collection on Basilisk

### Expected Behavior

everything would fit

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Basilisk

### Screenshots

already did

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
might have been fix by #4344, feel free to test it again on [beta.kodadot.xyz](beta.kodadot.xyz/)

**Comment by JustLuuuu** [comment]
@yangwao tested, its working, Im closing the issue

**Comment by JustLuuuu** [comment]
@yangwao tested, its working, Im closing this issue
