### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#439]
KodaDot is started as a fork of vue-polkadot and we took a lot of components from that which are now useless.

Deliverables: 
- [ ] check and remove unnecessary components 
- [ ] check and remove unnecessary node packages
- [ ] test it properly
- [ ] Optional: If there is some logic which could be reused add it to the report

**Comment by yangwao** [comment]
With recent `depcheck`

~/Projects/kodadot/nft-gallery landing-flex
12:51:02 ❯ npx depcheck
Unused dependencies
* @google/model-viewer
* @polkadot/vue-identicon
* @types/file-saver
* emoji-unicode
* file-saver
* freezeframe
* lazysizes
* markdown-it-vue
* netlify-lambda
* v-emoji-picker
* vue-class-component
* vue-cli-plugin-sitemap
Unused devDependencies
* @babel/helper-define-map
* @babel/helper-regex
* @intlify/vue-i18n-loader
* @types/webpack
* @vue/cli-plugin-babel
* @vue/cli-plugin-pwa
* @vue/cli-plugin-typescript
* @vue/cli-service
* all-contributors-cli
* sass
* sass-loader
* typescript
* vue-cli-plugin-i18n
* vue-debounce-decorator
* vue-template-compiler
Missing dependencies
* @polkadot/keyring: ./src/utils/WithKeyring.ts
* @polkadot/extension-inject: ./src/utils/WithKeyring.ts
* bn.js: ./src/utils/filters.ts
* @polkadot/api: ./src/utils/transactionExecutor.ts
* bulma: ./src/styles/index.scss

**Comment by yangwao** [comment]
Related #474

**Comment by roiLeo** [comment]
Current bundle size
![Capture d’écran 2022-02-10 à 9 43 14 AM](https://user-images.githubusercontent.com/9987732/153370651-d8ca6030-425a-4f0b-b3a6-4b4621287f51.png)

**Comment by yangwao** [comment]
Can we mint it 🥺 looks nice!

**Comment by vikiival** [comment]
Woah :octocat:

**Comment by yangwao** [comment]
Might be related 
- #2816

**Comment by roiLeo** [comment]
link #6707

**Comment by vikiival** [comment]
```
➜ npx depcheck
```

Unused dependencies
* @chenfengyuan/vue-qrcode
* @google/model-viewer
* @kodadot1/minipfs
* @nuxtjs/apollo
* @nuxtjs/i18n
* @nuxtjs/sitemap
* @paraspell/sdk
* @pinia/nuxt
* @polkadot/api-base
* @polkadot/apps-config
* @polkadot/vue-identicon
* @ramp-network/ramp-instant-sdk
* apollo-boost
* chartjs-adapter-date-fns
* chartjs-plugin-annotation
* chartjs-plugin-zoom
* css-loader
* emoji-unicode
* highlight.js
* keen-slider
* lazysizes
* nuxt-buefy
* nuxt-edge
* vue-markdown-render
