### ISSUE TITLE
Not possible to mint new collection on Basilisk

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4399]
### What happened?

For some time, new artists cannot mint on Basilisk - KodaDot.

### Please reproduce in steps

Create a new collection - add NFT, name and description. Click on create - it's loading, but the collection will not be created. You will get this notification:
<img width="1405" alt="Screenshot 2022-11-23 at 14 02 56" src="https://user-images.githubusercontent.com/104380776/203778965-0b8a6760-7acb-4549-8e93-094c87056b8c.png">

Same on beta; I tried both. One artist brought this issue to my attention.

### Expected Behavior

Minting without issues. 

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

beta same notification:
<img width="767" alt="Screenshot 2022-11-24 at 11 45 05" src="https://user-images.githubusercontent.com/104380776/203779898-bdfcbe4b-0bd9-492f-b701-1bf572761ec8.png">

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
Looks like the step fails after the upload

<img width="260" alt="Screenshot 2022-11-24 at 12 20 23" src="https://user-images.githubusercontent.com/22471030/203783172-c8dfd113-ffb6-4ef3-8247-8272f185c790.png">
