### ISSUE TITLE
Twitter/Discord/Telegram bot that would post feed of newly minted art

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#44]
This should be as a notification system of new mints primarily. 
Where collectors can hook up and listen for new art being minted.
Would be nice to use Subquery -- https://explorer.subquery.network/subquery/vikiival/magick as it does a lot of heavy lifting

### Functions to have 
- [ ] make a new post when there is a new mint on-chain detected
- [ ] on daily basis, create a Twitter thread, like a digest of new mints
  - [ ] whenever artists have set their identity, mention them on Twitter
- [ ] Making every n-hour basis thread of new mints
from 
  - hashtags #kodadot  
  - @kodadot mention
   - mention in the text URL (nft.kodadot.xyz, kodadot.xyz) to that minted art

### Post should be made to -- by order of importance
- twitterbot feed
- discord feed
- a telegram bot 

#### Bonus stage
Later with Telegram or Discord, you could make that Collectors could set see new mints from a particular address
Bonus points being in Rust 🦀 
Deploy it and make it live, 
Post screenshot of its workings

**Comment by abhisar2006** [comment]
Discord is already doing this on the KodaDot_Mint channel.. Can you confirm for Twitter and telegram as well?

**Comment by yangwao** [comment]
https://twitter.com/kodadotbot
Telegram was a bit borky but might figure out for sales only, it's getting way too spammy tbh.

So next would be posting only once sales happen than having new mints tho or could be different channel.
