### ISSUE TITLE
Residuals from Unique v2 upgrade

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#4401]
When Basilisk got stuck they upgraded underlying runtime pallet to V2 that changed names for collections and tokens.

I think that some residuals are still affected.

Task:

- check if sp,e calls can be affected:

old:
```
create_class
mint
transfer
burn
destroy_class
```

new:

```
create_collection
mint
transfer
burn
destroy_collection
```

**Comment by yangwao** [comment]
This is meanwhile fixed no?

**Comment by vikiival** [comment]
Yup I think everything works on BSX
