### ISSUE TITLE
Redesign Gallery item v1.1

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4403]
This issue will carry feedback from the original redesign, as we decided to freeze the current addition for till another rollout 

## Things we will be looking for next redesign
- can we redesign emojis box too? (on RMRK) ht @roiLeo 
- rmrk v1 emotes 
- with full-screen view
- feel free to drop what we should have 
- next item in collection, left/right arrows ?
- we need pagination for activity tabs
  - https://github.com/kodadot/nft-gallery/issues/4552
- showing user balance with connected wallet 
- qr code generation

## Express 
- offers buttons in table
- burn button

## Ref
- #4111

**Comment by yangwao** [comment]
> offers buttons in table
> burn button

@exezbcz let's make a separate issue on these two please, with design

**Comment by exezbcz** [comment]
> @exezbcz maybe consider multi-line in one row, to make it looks simpler. something like this
image
![image](https://user-images.githubusercontent.com/90852205/214118666-35fdb173-60a7-41d3-ac39-41e350d9e3f4.png)

posted by @preschian in #4724

**Comment by exezbcz** [comment]
maybe also implement this? 
- #4917
