### ISSUE TITLE
All the new collections are getting the same name: "Basilisk-Sama"

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4421]
### What happened?

I tried to create a collection with a different name("Bridge"), and after creating it, it was named "Basilisk-Sama". I tried again twice with totally different names.... now I have 3 Basilisk Sama collections.

### Please reproduce in steps

Create new BSX collection - classic - fill everything.

### Expected Behavior

I want my collection to be named after what I came up with. Imagine you will have your own baby, you will name it Suzanne but you will get her birth certificate with the name Ignacio. 

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

<img width="1468" alt="Screenshot 2022-11-26 at 13 10 31" src="https://user-images.githubusercontent.com/104380776/204090897-5d17d073-120c-4abd-ae8c-63ba98292514.png">

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
This was fixed, I guess? 

<img width="174" alt="image" src="https://user-images.githubusercontent.com/5887929/205488568-129721a4-2dfc-4ab4-93b8-11eeccd20fe6.png">

<img width="219" alt="image" src="https://user-images.githubusercontent.com/5887929/205488576-1a1b242f-c86e-4a19-9ba7-bcf151d759a2.png">

yes, looks like that.
