### ISSUE TITLE
`nuxt-img` for reduce images size

### ISSUE THREAD

**Issue by shashkovdanil** [kodadot/nft-gallery#4426]
### Is your feature request related to a problem?

There are images on the site that are over 5MB in size. It is so bad for people with a slow internet connection or a limited internet tariff plan. It also affects the Google Lighthouse ranking, and Google will lower the site in search results

### Describe the solution you would like

Using https://image.nuxtjs.org/components/nuxt-img

### Describe alternatives you have considered

N/A

### Screenshots

I made the little experiment:

**with `nuxt-img` 359KB**
![photo_2022-11-25_00-13-32](https://user-images.githubusercontent.com/19692986/204321609-0b9e2939-963c-429b-8b7d-ed51d99b91d9.jpg)

**without `nuxt-img` 5.2MB**
![photo_2022-11-28_15-50-34](https://user-images.githubusercontent.com/19692986/204321614-795b9a8f-a6bb-4ba9-9c77-067b95ddc627.jpg)

### Are there opened related issues?

N/A

**Comment by yangwao** [comment]
Hey, we've used AVIF from Cloudflare to radically reduce file size, but seems it's not working on Basilisk or we break something. 

- https://image.nuxtjs.org/providers/cloudflare
- Reading that they have some Cloudflare integration but that's just for pages which optimise only local images, not remote ones.

I mean, we have a quite different image architecture, in this case, tho as your original case is for remote images.

Yet, I guess it is worth to use for some "static" images right now @shashkovdanil ?

**Comment by yangwao** [comment]
Continue to 
- https://github.com/kodadot/nft-gallery/issues/7807
