### ISSUE TITLE
Return to original view-port after pressing esc 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#443]
When I have "fullscreen" on NFT detail would be nice to have some shortcut to press ESC (or any shortcut) to revert it back.

Similar like you are exiting full-screen video :)

**Comment by davidbonnaud** [comment]
Hi I'd like to pick up this issue, to be clear do you mean when you click on the fullscreen-view button on the GalleryItem component?

**Comment by yangwao** [comment]
yes, works, closing #444
