### ISSUE TITLE
Re-listing and changing price: not showing correct price everywhere

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4439]
### What happened?

Our artist changed the price of his NFTs in his collection (from 2 KSM to 1KSM). The new price is not showing **in the newest list** (on the main landing page): (showing the old price) 
![image](https://user-images.githubusercontent.com/104380776/205460162-f5c6ff71-de8c-4674-abb8-cacb73496dfd.png)

This collection: https://kodadot.xyz/bsx/collection/3579963603?page=1 

### Please reproduce in steps

Changed price - you can see the correct price in the collection but not in the newest list

### Expected Behavior

Showing good price

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

uploaded

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
I guess this might be already resolved?

**Comment by JustLuuuu** [comment]
I guess yes, its okay now.
