### ISSUE TITLE
redesign: dynamic change grid card size

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4444]
>  change grid card size

Right now current trends and our anticipation of bringing dynamics cards as now we have columns of fixed ones. It's nice, but not everyone has same screensize and we would maximalize unified experience at each of screen size. Ranging from mobile, folding phones, tablet, notebook to desktop. 

You can currently see trend on R & OS that dynamic cards has some properties where they sizing these cards dynamically on picture and description. 
In similar manner we will set some break points to have it

Just backlogging as can easily sink through our thought process among others and I found it really important stuff to have.  

Of course, we will welcome to have some sort of override where user can set "size" of card, but amount of columns will be adjusted dynamically for best user experience

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/4378#issuecomment-1326372557_
      
Please reflect on foldable phones. ht @exezbcz finding foldable explainer for proper CSS ninjas :P

## Ref
- https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Foldables/explainer.md
- https://devblogs.microsoft.com/surface-duo/dual-screen-web-game-foldship/
- https://github.com/w3c/csswg-drafts/issues/4736
- https://w3c.github.io/device-posture/
- https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/236

**Comment by exezbcz** [comment]
> as mentioned in issue #4496, we have some sort of minimal card size.
> 
> The grid, size of the cards and the number of cards will change based on few factors
> 
> * there is going to be fixed gap between them - for bigger cards in normal view its 32px and for the smaller cards its 24px
> * once the card can not be smaller without lowering/increasing the gap, the amount will be lowered by one/required.
> * other cards will scale up so there is the demanded gap - Same when scaling up.
> 
> Have a look at rarible/opensea.
> 
> in our case - explore with filter with menu opened/closed.
> 
> <img alt="image" width="510" src="https://user-images.githubusercontent.com/90852205/207570596-7450d5e6-ec20-4681-b3c5-a01e79a04681.png">
> 
> - at the bottom there are the minimum size cards and demanded gap between them. - Once we open the filter menu, they would not fit. Certain number of cards are removed and the others scale up.
> explore v0.9 figma here: https://www.figma.com/file/OwAEyE0QDPn3tHXZbyot1o/Explore-v0.9?node-id=0%3A1&t=Mp5WHz4Ig8kbcIsy-3

lmk if the approach is not great or it could be done differently

**Comment by yangwao** [comment]
At collection, we should apply it as well once the following PR is merged, that we should preserve some card size on collection view as well 

- https://github.com/kodadot/nft-gallery/pull/4518
![image](https://user-images.githubusercontent.com/5887929/208705013-af8e84c1-9aff-465f-88ca-4cc48fde1eed.png)

**Comment by exezbcz** [comment]
Anyone 🥺

**Comment by exezbcz** [comment]
Me every month checking this issue: 
<img src="https://media3.giphy.com/media/RKS1pHGiUUZ2g/giphy.gif"/>

**Comment by yangwao** [comment]
This will be reused for 
- #5000 
- #4474

**Comment by yangwao** [comment]
We should think of height of collection cards on wider screens 
![image](https://user-images.githubusercontent.com/5887929/220606944-b9101279-0efe-4b77-b51a-e2decf4fac6a.png)

**Comment by exezbcz** [comment]
@preschian uuu nice, it seems like things are improving! I'll play with it for a while and give feedback; at first glance, it looks to be good.

**Comment by yangwao** [comment]
> you can check it in here

very nice! I think the card ratio is close to perfect for me on 13"

**Comment by yangwao** [comment]
Ah, collection is solved in
- #5135
