### ISSUE TITLE
Keep right ratio on full-screen view

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#445]
I am not sure if it's **bug** or **feature** but the image ratio is crippled on full screen. Check the video below.

https://user-images.githubusercontent.com/22471030/121515778-da30de80-c9ed-11eb-9ee3-758de2c64867.mov

h/t deeplogic

**Comment by yangwao** [comment]
Yup, it was just the first implementation from @AndriiHrynchuk feel free to fix ratio

**Comment by davidbonnaud** [comment]
picking up this issue
