### ISSUE TITLE
Report System for copymints

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#4465]
## ⭐️ Feature request 

In the past we had problems with copycats, to counter this it would be interesting to integrate a reporting system.

### Spec

- Report User
- Report Collection
- Report Nft

### Current implementation

[DenyList](https://github.com/kodadot/nft-gallery/blob/main/utils/constants.ts) mixed with [Prefix](https://github.com/kodadot/nft-gallery/blob/main/utils/prefix.ts)

### Possible solution

For the moment, I would set up a mailto button to a kodadot mod address.
Then we will add the reported token in denyList.

Let me know if you have a better alternative.

### Linked issue

- kodadot/nft-gallery#1177 
- kodadot/nft-gallery#4077

**Comment by yangwao** [comment]
> 1. link to Github issue with an "report" template but user will need to have a github account

That would help at some point ppl preventing spamming, but yes best would be token weighted report system with spam protection and probably fastest solution for now as GH servers as tracking system for many things in K

2. discord would be doable, everyone having Discord nowadays

3. we can think of something, have it on sight, write some cf-worker for this  

5. oauth2 for gmail/twitter/discord ?

6. it would be highly needed when we launch public referral campaign 
- #4635

**Comment by vikiival** [comment]
Nice idea, however people can reach us on tg
