### ISSUE TITLE
extend on chain identity with image

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4466]
vik just discovered that onchain identity supports picture this would be nice we could include on user profile their pictures

**Comment by vikiival** [comment]
https://github.com/paritytech/substrate/blob/15cfd9c5dbbfa1f3ed49623eb55b67354d1645e9/frame/identity/src/types.rs

**Comment by vikiival** [comment]
Looks like image field was added 😌❤️

**Comment by JustLuuuu** [comment]
> Looks like the image field was added 😌❤️
is this working on KodaDot? This would be AWESOME once it will be done. 
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/104380776/213158601-571ee80e-db20-4b88-9037-4237546e11c8.png">

**Comment by yangwao** [comment]
Continue to 
- #4751
