### ISSUE TITLE
Redirect people to grants form 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#447]
Let's have redirected to /grants. I.e. whenever someone hits https://kodadot.xyz/grants will redirect to 
https://tally.so/r/mVP06w

That's our form where we will collect feedback and support artists.

**Comment by archnomics** [comment]
Here's the code to embed it to full page

`<html> <head> <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"> <title>KodaDot Artist Grant Program</title> <style type="text/css">html { margin: 0; height: 100%; overflow: hidden; } iframe { position: absolute; top: 0; right: 0; bottom: 0; left: 0; border: 0; }</style> </head> <body> <iframe src="https://tally.so/embed/mVP06w?hideTitle=1" width="100%" height="100%" frameborder="0" marginheight="0" marginwidth="0" title="KodaDot Artist Grant Program"></iframe> </body> </html>`

If transparent background, here's the one:

`<html> <head> <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"> <title>KodaDot Artist Grant Program</title> <style type="text/css">html { margin: 0; height: 100%; overflow: hidden; } iframe { position: absolute; top: 0; right: 0; bottom: 0; left: 0; border: 0; }</style> </head> <body> <iframe src="https://tally.so/embed/mVP06w?hideTitle=1&transparentBackground=1" width="100%" height="100%" frameborder="0" marginheight="0" marginwidth="0" title="KodaDot Artist Grant Program"></iframe> </body> </html>`
