### ISSUE TITLE
Redesign Explorer v0.9 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4474]
## <a href="#tasks" id="tasks">Tasks</a>
In particular order 
- #4497 
- #4496 
- #4555
- #4825
- #4886
- #4882
- #4532
- #4533
- #4444 
- #4893
- #4982 
- #4906 
- #5143 
- #5078 

The cat is out of the bag.
<img src="https://media1.giphy.com/media/jTf83ZnIn7A1dKRqvQ/giphy.gif"/>

Backlog for Explorer v2
---
- #2650 

---

We've been quickly making the redesign explorer to bit speed run upcoming collection reading and try to recycle as much possible logic so we can deliver the finest user experience, in short time.

Most of the logic should be already there, so I bet this should not be delayed as a gallery item.

What you can see down is the basic view when the user first time opens `https://kodadot.xyz/explorer`. By default showing collections, aggregating collections from all networks we are indexing. 

Each headline could be separate task I guess. 

## Default collections view
<img width="686" alt="image" src="https://user-images.githubusercontent.com/90852205/207573722-a1d9c028-d624-4c96-ba93-40c040ab5e19.png">
- there is no button for changing the grid and the number of cards.
- network change 

## Explorer Tabs
Switching between Collections and Items. Here we would like to rethink URL path

Currently, we have on Collections `/bsx/explore?tab=COLLECTION` and we would like to have `/explore/collectibles` its more human friendly URL. Hopefully Nuxt Router won't be wonky here

For Items I would propose change from `/bsx/explore?tab=GALLERY&page=1` -> `/explore/items`

## All Networks switch
Currently, we are waiting for
- #4257 
so till then, we can opt to show NFTs pre-selected by networks like RMRK, Basilisk, MoonRiver, MoonBeam

## Collection card
![image](https://user-images.githubusercontent.com/5887929/207083573-d4b0a6bc-b488-44c2-ac63-c8f587a67e42.png)

- #4497 
- For banner background we probably use banners, but as functionality is not there, we will use the last NFT from collection or avatar picture of collection.
Then we are showing avatar,  collection name which we probably be wrapping after some length (@exezbcz can hint length as we probably want to introduce dynamic grid?) 
Than numbers we already have are volume, highest sale and items in collections.

## Explorer Items
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/90852205/207589301-b14d465b-f673-4609-8317-d2f9be618b00.png">
Here you can see it added sort filter and grid settings

## Sort By
![image](https://user-images.githubusercontent.com/5887929/207088474-fe4ea0d1-4223-40e7-a190-11de75486efa.png)

We right now support two options to sort by. Why? Because sometime we want to see low to high from recently listed and not all low priced since first indexed data.  
- #4430 could be used here? 

## Explore Menubar
![image](https://user-images.githubusercontent.com/5887929/207089175-9e0112af-4c56-43ac-be41-773aef857e59.png)

The default state we are thinking of would be the open section `Status` with a checked "Buy Now" option 
### Sections will be 
- Properties
- Price 
- Status

### Price
![image](https://user-images.githubusercontent.com/5887929/207093327-b3ec52bd-787a-4c80-8b83-845f695d456a.png)

Our current price filter, I guess there are none changes.
Extra add is that when after applying price range you will change one of inputs, color of Apply button will change

### Status
- Buy Now -- Listed NFTs available to buy
- Own -- NFTs your logged in address own

### Properties
I guess we don't have screenshot here?

## Filter Breadcumbs
![image](https://user-images.githubusercontent.com/5887929/207093694-240a2ab5-d124-4747-a8b1-0da31495e474.png)

If user clicks in Menubar, there will be adding filters as tags, with option to cancel those filters
By default there will be Buy Now, it's test and incentivize artist to always have something on sale
On the very end, we will show number of result item user has ability to see after filtered
filter tag behavior here: 
<img width="699" alt="image" src="https://user-images.githubusercontent.com/90852205/207588843-70eafc88-a40d-46c1-b9f2-3b25fdddc6c2.png">

## Card Item 
<img width="305" alt="image" src="https://user-images.githubusercontent.com/90852205/207578223-56df7376-4269-4564-aa67-fde51f64bec8.png">

Classic.
- Item name - here on hover we will be showing NFT hover card 
  - #4340 
- collection name
- price plus token
- network in corner

## Mobile ui 
<img width="970" alt="image" src="https://user-images.githubusercontent.com/90852205/207587685-de2f1533-cda6-44bd-b55b-e8c3c59452ca.png">

- explore items 
  - menu is 100% vh and vw, bottom part is fixed, i will update this so there is also clear all button. 
  - sort by changed to an icon. When clicking, there will be dropdown 
  - same with network switch
- explore collection 
  - only network switch

## Figma
https://www.figma.com/file/OwAEyE0QDPn3tHXZbyot1o/Explore-v0.9?node-id=0%3A1&t=lu1bdZZIvVezlcsc-3
- if you want edit rights, lmk

I'll go with @exezbcz and fill gaps in description 

## Ref
- #4378 
- #4257

**Comment by exezbcz** [comment]
issue updated ✅

**Comment by exezbcz** [comment]
> just want to make sure, is the next/prev/random page removed in the new design? <img alt="Screenshot 2023-01-18 at 23 21 16" width="177" src="https://user-images.githubusercontent.com/734428/213234065-7ecd2e10-2414-4816-9d73-09547dfe9c24.png">

yes

**Comment by exezbcz** [comment]
> oh nvm, I missed this `- there is no button for changing the grid and the number of cards. - network change`

no problem, you dont need that on explore, there is not something like minimalized collection cards yet

**Comment by exezbcz** [comment]
> no sort options on collectibles/collections?

based on what data you would like to sort it? I think its not that important, there are only few use cases. I would personally skip this.

**Comment by exezbcz** [comment]
> > > no sort options on collectibles/collections?
> > 
> > 
> > based on what data you would like to sort it? I think its not that important, there are only few use cases. I would personally skip this.
> 
> oh nothing, I just compared with current state. just want to make sure <img alt="Screenshot 2023-01-21 at 10 29 18" width="265" src="https://user-images.githubusercontent.com/734428/213841669-53a620fc-0059-4a25-8c71-e9877a4af8ab.png">

I didn't mean to be offensive :D but I could have missed something actually good. Nope we dont have any sorting on top of collection explore

**Comment by yangwao** [comment]
> no sort options on collectibles/collections?

we can think of adding something to v1 explorer, found something from our backlog. 
right now we can probably keep new/old  

- https://github.com/kodadot/nft-gallery/issues/3601
- https://github.com/kodadot/nft-gallery/issues/3523
- https://github.com/kodadot/nft-gallery/issues/2845
- https://github.com/kodadot/nft-gallery/issues/1778

**Comment by yangwao** [comment]
I guess most of stuff for explorer is done @exezbcz ? 
I don't see any p2 with explorer label https://github.com/kodadot/nft-gallery/issues?q=is%3Aissue+is%3Aopen+label%3Aexplorer+label%3Ap2

If so, we can close this one

**Comment by exezbcz** [comment]
yup, only the price in breadcrumbs is left - but that applies to the collection too so it could be made there 
- #5167
