### ISSUE TITLE
footer image overlap content

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#4480]
> The message "Offers are not available on rmrk" does not appear when I hover over the offers on this nft

Footer image `position: absolute;` overlap the content and does not allow clicking on the elements near it.

Might be coming from #4463 (#4440)

![Capture d’écran 2022-12-12 à 2 08 17 PM](https://user-images.githubusercontent.com/9987732/207052869-bcdda531-1d30-4c02-a6fd-4a884a6feb83.png)

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/issues/4460#issuecomment-1346465227_

**Comment by exezbcz** [comment]
If the image is causing lot of trouble i think its duable that we limit that to the footer. But it would be better if not :D

**Comment by Jarsen136** [comment]
It seems that something zindex changed in the origin issue #4460, which introduce this bug again : )

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/31397967/207064390-c241d400-6de4-44c1-8f86-6a96f36a5106.png">

**Comment by exezbcz** [comment]
yup but now the image is overflowing the gallery containers. 
![image](https://user-images.githubusercontent.com/90852205/207065161-cc96f1fd-9f85-4288-98fa-3542d2f1fc51.png)

**Comment by Jarsen136** [comment]
> yup but now the image is overflowing the gallery containers.

That's OK. Just setting the dark background for the container could fix this one. Now the background of the gallery containers is transparent.

**Comment by roiLeo** [comment]
> It seems that something zindex changed in the origin issue #4460, which introduce this bug again : )

Any idea why we need to set `z-index: 1` on main, layout & body? If we keep it like this in #4460, we won't be able to show tooltip on disabled tab

**Comment by Jarsen136** [comment]
> > It seems that something zindex changed in the origin issue #4460, which introduce this bug again : )
> 
> Any idea why we need to set `z-index: 1` on main, layout & body? 

Not sure why set `z-index`. I guess it was only made for showing the footer accordingly. 

>If we keep it like this in #4460, we won't be able to show tooltip on disabled tab

I dont know their relation. How about creating a new issue to show the tooltip? I bet it may have a better approach. If not, let's remove the `z-index`. WDYT

**Comment by roiLeo** [comment]
> I dont know their relation. How about creating a new issue to show the tooltip? I bet it may have a better approach. If not, let's remove the `z-index`. WDYT

I have a feeling that with this z-index we could have strange behaviour like that, but lmk if you have any idea how to fix.

Replacing the image with a background doesn't work? Even when resizing the image?

**Comment by Jarsen136** [comment]
> > I dont know their relation. How about creating a new issue to show the tooltip? I bet it may have a better approach. If not, let's remove the `z-index`. WDYT
> 
> I have a feeling that with this z-index we could have strange behaviour like that, but lmk if you have any idea how to fix.
> 
Yes, after a quick research. I found that when setting the z-index to 100, both these problems could be solved. (footer background & showing tooltip on tab)
However, It may be the final or best approach. I mean that this bug (tooltip invisible) may cause by the incorrect style setting on the tooltip component. I guess there would be a better way to display the tooltip.

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/31397967/207102656-9507cfb2-c176-45ef-bcff-723ae2198ab3.png">
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/31397967/207103178-09c3adac-1f16-4f03-887b-f0bae8d1ce62.png">

**Comment by Jarsen136** [comment]
> Replacing the image with a background doesn't work? Even when resizing (or re export) the image?

No, because in that way it could not fit the design. 
https://github.com/kodadot/nft-gallery/pull/4463#issuecomment-1343089294

**Comment by roiLeo** [comment]
Done in https://github.com/kodadot/nft-gallery/pull/4460#issuecomment-1354213066
