### ISSUE TITLE
Add SubWallet (mobile) as an option to connect to Kodadot dapp

### ISSUE THREAD

**Issue by RyanDinh8** [kodadot/nft-gallery#4492]
### Is your feature request related to a problem?

SubWallet has now released the mobile app (we released the public testing phase in early November 2022 and has about 2,500 installs as of December 14, 2022). 
- https://twitter.com/subwalletapp/status/1587403200105451520

However, SubWallet is not supported on Kodadot dapp on mobile yet (see the attached picture)

![2022-12-14 15 45 37](https://user-images.githubusercontent.com/102496727/207550319-9e70b40b-84b6-4658-ab8c-27c1512f7588.jpg)

### Describe the solution you would like

Please add SubWallet (mobile) as an option to connect to the dapp. Thank you very much. 

### Describe alternatives you have considered

There's no alternative for this

**Comment by yangwao** [comment]
@RyanDinh8 😍 thank you! looking forward for this to have your wallet around ☺️
