### ISSUE TITLE
After minting, show author dialog/notification to tweet it

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#45]
- everyone loves to engage and see it first.
- nudge minter to have broader engage

**Comment by yangwao** [comment]
$$ if it would be well packed!

**Comment by anettrolikova** [comment]
Would look shiny if after minting NFT as user you would get redirect to a page that will show you your NFT that you just minted, text "Congratulations for minting NFT on KodaDot, your art looks amazing! Share it with world" and a button that will link you to Twitter to share artwork

**Comment by yangwao** [comment]
Already recently merged on production.
