### ISSUE TITLE
Add links to tutorials

### ISSUE THREAD

**Issue by JKrupinski** [kodadot/nft-gallery#452]
**Describe the bug**
Tutorial links are not set

**To Reproduce**
Go to https://nft.kodadot.xyz/tutorials

**Expected behavior**
Tutorials link should redirect to proper pages

**Comment by JKrupinski** [comment]
@yangwao please provide proper links and I'll update them:
1. Create polkadot JS account
2. Get KSM
3. Minting

**Comment by virtugrana** [comment]
https://virtugrana.substack.com/p/kodadotoverview
https://stakenode.medium.com/dont-panic-and-mint-your-nft-s-on-kodadot-kusama-polkadot-first-nft-explorer-4273f789e585
https://nft.kodadot.xyz/rmrk/collection/10D77F8B699437BB50-KODA

Portuguese:
Getting KSM
https://virtugranapt.substack.com/p/comprando-ksm-com-fiat

**Comment by CdrsAlejandro** [comment]
https://nft.kodadot.xyz/tutorials

Spanish: 
1. Create a Polkadot JS Account | Crear una cartera Polkadot JS : https://www.youtube.com/watch?v=iG8iQrONnYo&t=21s
2. Get KSM | Obtener Kusama: https://www.youtube.com/watch?v=cYaZWDzU1Yc
3. Minting: Crear un NFT: https://www.youtube.com/watch?v=pPsbQyJRGVQ&t=1s

**Comment by chris-saburo** [comment]
@yangwao @vikiival let me fix the about issues.

**Comment by chris-saburo** [comment]
Now I am working to fix this current issue.

**Comment by yangwao** [comment]
@archnomics let's take care of this one, I guess you are able to handle it! :)

Probably sort out content accordingly

**Comment by yangwao** [comment]
> Can we live-link GH to Gitbook? That needs authentication on the repository tho.

why is that needed? or what will be benefits, I may not understand it clearly. To be a repository on GH so anyone can contribute?

> Main Docs: https://kodadot.gitbook.io/knowledgebase/

Now let's link that knowledge base. 
How user can find them apart from this issue?

**Comment by yangwao** [comment]
This is already done by this https://kodadot.xyz/tutorials 
But I guess we should revisit and add more tutorials there

**Comment by onerawartist** [comment]
@yangwao if you liked what i made, i'm open to making more tutorials ^^

**Comment by yangwao** [comment]
I guess, hence we have https://docs.kodadot.xyz I would probably remove this page? 
It's not even linked in landing anyway 

📟  @cryptodamsky
