### ISSUE TITLE
Chuckles reviewing last payments

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4523]
oh probably handling check balance before sending would be nice to preserve close to reality state 

![image](https://user-images.githubusercontent.com/5887929/208300253-85f1b26c-0293-4902-84f8-9b01ae22468c.png)

<img src="https://media2.giphy.com/media/qPa9vUYCUrx6w/giphy.gif"/>

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/4488#issuecomment-1356795611_
      
If someone would help takeover on this till I get to it would be amazing to mitigate this kind of situations tho

Reviewing failed transactions now
## Ref
- #2116

**Comment by yangwao** [comment]
quick forensic science

<img src="https://media4.giphy.com/media/3o6gbaeZ4EGzj8IvVS/giphy.gif"/>

- https://github.com/kodadot/nft-gallery/pull/4488
- https://github.com/kodadot/nft-gallery/pull/4503
- https://github.com/kodadot/nft-gallery/pull/4508
- https://github.com/kodadot/nft-gallery/pull/4473

![image](https://user-images.githubusercontent.com/5887929/208301236-d9e3c6a0-c8cc-4c75-ab67-2a7e725f9003.png)

**Comment by daiagi** [comment]
>     oh probably handling check balance before sending would be nice to preserve close to reality state 

@yangwao shall i open an issue to check balance before sending? 
ill be happy to tackle that
