### ISSUE TITLE
Redesign Explorer Menubar

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4532]
## Explore Menubar
![image](https://user-images.githubusercontent.com/5887929/207089175-9e0112af-4c56-43ac-be41-773aef857e59.png)

The default state we are thinking of would be the open section `Status` with a checked "Buy Now" option 
### Sections will be 
- Properties
- Price 
- Status

### Price
![image](https://user-images.githubusercontent.com/5887929/207093327-b3ec52bd-787a-4c80-8b83-845f695d456a.png)

Our current price filter, I guess there are none changes.
Extra add is that when after applying price range you will change one of inputs, color of Apply button will change

### Status
- Buy Now -- Listed NFTs available to buy
- Own -- NFTs your logged in address own

### Properties
I guess we don't have screenshot here?

## Figma
- https://www.figma.com/file/OwAEyE0QDPn3tHXZbyot1o/Explore-v0.9?node-id=0%3A1&t=lu1bdZZIvVezlcsc-3

**Comment by yangwao** [comment]
<img src="https://media4.giphy.com/media/H6QiTmcMh98mxMLieC/giphy.gif"/>

**Comment by prachi00** [comment]
whats in properties? 
Also, when would the menubar show up, only in case of items? not for collections?

**Comment by roiLeo** [comment]
✌️

**Comment by roiLeo** [comment]
> same with this, what is the sidebar content for collections?

From [figma](https://www.figma.com/file/OwAEyE0QDPn3tHXZbyot1o/Explore-v0.9?node-id=0%3A1&t=6dKqMo3tqTn9yfv7-0) file I can see that sidebar toggle button is disabled for Explore/collection

**Comment by exezbcz** [comment]
> whats in properties? Also, when would the menubar show up, only in case of items? not for collections?

um, sorry for the delay, its just placeholder text :D

**Comment by yangwao** [comment]
Looking on Sidebar, we should add some animation tho?

Otherwise most of things are done?

**Comment by daiagi** [comment]
anything left to do here?

**Comment by roiLeo** [comment]
> anything left to do here?

Closing for #5078 & #4906
