### ISSUE TITLE
Artist spotlight 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#455]
I guess Art creation is not a contest or competition and we would like to give the spotlight to great artists around.
In this issue, we would like to have an array of artist's addresses, let's start with 10 of them(?) and it should show three gallery items from their recent mints, each row should be one artist. 
We would make (bi)weekly voting rounds on Discord on artists spotlights in KodaDot Spotlight

- [ ] https://nft.kodadot.xyz/leaderboard rename route to spotlight
- [ ] array of artist where we can easily change who is showed up
- [ ] create subquery grapql to show particular artists 3 last mints
- [ ] links to artist profile and show their on-chain identity in the /spotlight for their particular row
- [ ] show address KSM balance, number of NFTs, collections, sales

**Comment by anettrolikova** [comment]
I'd suggest to write articles something like interviews to give the artists the best spotlight. 
Hosting discussions on discord with artist could be cool too, something like community call but with artist as host.

Probably relates to have on the front page art - recent mints maybe ?
