### ISSUE TITLE
Introduce using AVIF back

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4551]
Seems right now, when users browse collections & explorer, doesn't seem we are using AVIF, especially on a slower net, and when people want to browse fast, it would improve the experience a lot. 
Back in days, we had it, but it seems not anymore.

Let's review that. 
The best would be to make some image container handlers to include this support. 
 

![image](https://user-images.githubusercontent.com/5887929/209168936-1535dc7a-cf7e-41cd-9d22-a2819d097759.png)

![image](https://user-images.githubusercontent.com/5887929/209168979-69b7e9c5-910e-4705-8d85-99d52750b20f.png)

## Ref
- https://github.com/kodadot/nft-gallery/issues/4426
- https://github.com/kodadot/nft-gallery/issues/3829
- https://github.com/kodadot/nft-gallery/issues/3828
- https://blog.cloudflare.com/images-avif-blur-bundle/
- https://avif.io/blog/tutorials/cloudflare/
- https://blog.cloudflare.com/generate-avif-images-with-image-resizing/
- https://caniuse.com/avif

**Comment by yangwao** [comment]
Someone can review this on https://beta.kodadot.xyz if we are using AVIF already? If so let's close this one

**Comment by yangwao** [comment]
It's bettwe with webp, yet I guess it's not avif? 

![image](https://user-images.githubusercontent.com/5887929/210591343-fcf60f23-2d43-416c-9552-a45c1f779082.png)

Seems for AVIF needs client to tell supports it? 

```js
const WEBP_ACCEPT_HEADER = /image\/webp/i;
const AVIF_ACCEPT_HEADER = /image\/avif/i;

addEventListener("fetch", (event) => {
  event.respondWith(handleRequest(event));
});

async function handleRequest(event) {
  const request = event.request;
  const url = new URL(request.url);
  
  const headers = new Headers(request.headers);

  const accept = headers.get("accept");

  let format = undefined;

  if (WEBP_ACCEPT_HEADER.test(accept)) {
    format = "webp";
  }

  if (AVIF_ACCEPT_HEADER.test(accept)) {
    format = "avif";
  }

  const resizingReq = new Request(url, {
    headers,
    cf: {
      image: { ..., format },
    },
  });

  return fetch(resizingReq);
}
```

learn more - https://blog.cloudflare.com/images-avif-blur-bundle/

**Comment by preschian** [comment]
Closing this since cf-images automatically serve AVIF based on browser support. this is on chrome

![image](https://github.com/kodadot/nft-gallery/assets/734428/d0c82869-fdad-4715-b1d7-cff53600c577)
