### ISSUE TITLE
Pagination for activity tabs 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4552]
> events query without limit, is this not a problem?

eh, I think we need pagination in this section. so, temporary I will limit the results to `100`

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/4411#issuecomment-1342642044_

**Comment by exezbcz** [comment]
what is required from me? 👀

**Comment by roiLeo** [comment]
improved by #5608
