### ISSUE TITLE
Add tip jar on user profile 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#457]
Add a button where collectors or patrons could easily donate funds to artists. 

By clicking **it would assemble transaction for patrons to sign their transaction and broadcast it.** 

There should be a notification where it states successfully send and probably show-up link to explorer  (kusama.subscan.io) tx so they can tweet or share it

- [ ] fields with default tip, like $10 or it could be fairly defined in KSM, at writing this issue KSM is at ~ $400, so 0.025 would be a nice fit 
- [ ] button to send Tip
- [ ] make it as a component so it could be reusable under NFT item as well
- [ ] show denomination value in USD

**Comment by yangwao** [comment]
What do you think, could you try to handle this one @prachi00 ?

**Comment by prachi00** [comment]
@yangwao sure, let me see what I can do
