### ISSUE TITLE
CSS Variables for theming 

### ISSUE THREAD

**Issue by prachi00** [kodadot/nft-gallery#4584]
@roiLeo @yangwao @vikiival @Jarsen136 @petersopko @preschian 
I am really tired of writing double css, once in light mode and then in dark mode, I researched and figured this would be the best way to make sure that css is only written once for all themes
With this approach, we can get rid of _Dark.scss and _light.scss files

Let me know if this seems okay to you, or you would prefer some other way of doing it? 
I couldnt really find anything for using scss variables theming directly without any mixins

I have some time because of the holidays going on, I can do this transition, I feel like it would speed up our development by doing this once and for all

_Originally posted by @prachi00 in https://github.com/kodadot/nft-gallery/issues/4579#issuecomment-1366981984_

**Comment by prachi00** [comment]
Waiting for more inout before I start working on this :)

**Comment by yangwao** [comment]
I really appreciate the effort to make it easier to manage code. 
Hence we are getting a bit complex app, and with the redesign on top, I see a lot of quirky back-and-forth visual conflicts repeating.
I would nominate for suggestions from others; probably @roiLeo @preschian @Jarsen136 can have some great suggestions and the best approach. :)
