### ISSUE TITLE
Bump new @polkadot packages

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4585]
Seems would be nice to align the versions we are using with https://github.com/kodadot/packages/tree/main/sub-api to recent one  

![image](https://user-images.githubusercontent.com/5887929/210217277-8f9ab0d2-33ab-4da5-8a1d-8b8b820e281d.png)

**Comment by vikiival** [comment]
https://github.com/kodadot/packages/issues/81

**Comment by roiLeo** [comment]
yolo kodadot/packages#86

**Comment by vikiival** [comment]
Released under: 
+ @kodadot1/sub-api@0.1.1-alpha.5

**Comment by preschian** [comment]
we face this issue again in development
