### ISSUE TITLE
Dark mode background colour to grey eingrau

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4591]
We've been chatting in past that as current dark mode has strong black is introducing contracts issues.

Having something close to github grey eingrau or something around that would be more doable I sense 
I guess once it's closed, following issue 
- #4584 

<img width="857" alt="image" src="https://user-images.githubusercontent.com/5887929/210408697-e0e7e010-26a2-4e07-9cd7-3e28eadf3523.png">

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/5887929/210408755-9321f3eb-bd07-46aa-8e93-836eec545646.png">

**Comment by exezbcz** [comment]
this one is it 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/18374cba-0280-467d-83fe-e27a52c734ae)
