### ISSUE TITLE
Faster Response.redirect() for image proxy

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#4595]
> That is something I would like to avoid. That's why we have the worker as it serves as proxy and we do not need to rework the component

> maybe make a separate issue and can be done as supplement PR?

noted, so the task is to cache `Response.redirect()` on the workers side. it will help the proxy to resolve faster to cf-images

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/4587#issuecomment-1370866557_

**Comment by yangwao** [comment]
> it will help the proxy to resolve faster to cf-images

yes, I've noticed on your demo seems it takes ages and not so fast load times :|

**Comment by vikiival** [comment]
> yes, I've noticed on your demo seems it takes ages and not so fast load times :|

It is because you are hitting the worst case of the worker - it needs to do the roundtrip to other ipfs gateway

**Comment by vikiival** [comment]
> CORS error

Why so?

**Comment by yangwao** [comment]
Merged
- https://github.com/kodadot/workers/pull/20

**Comment by yangwao** [comment]
Checking, when it was published, it did some spikes? 

Keeping monitoring it or it will fade away?

<img width="658" alt="image" src="https://user-images.githubusercontent.com/5887929/211601323-b7f65bea-dbed-4c28-b9b1-fb741ae67be0.png">

**Comment by vikiival** [comment]
> Checking, when it was published, it did some spikes?

![Screenshot 2023-01-10 at 17 46 17](https://user-images.githubusercontent.com/22471030/211611913-2b9f879d-baef-42b2-87ce-9500d591cc03.png)

**Comment by yangwao** [comment]
Will keep it monitoring, after deploy seems to have a higher average so not sure about that  

![image](https://user-images.githubusercontent.com/5887929/211790123-3b71086f-0ff2-4d9b-897a-5a1d1239aeae.png)

**Comment by yangwao** [comment]
It's strange, that cache looks like flushed every once a while?

![image](https://user-images.githubusercontent.com/5887929/212397722-9e93b277-b70e-4ad5-9fe4-84bdd9e0fe03.png)

![image](https://user-images.githubusercontent.com/5887929/212397774-7c2ca6ca-51f0-4ef0-9691-a4452e0e8557.png)

![image](https://user-images.githubusercontent.com/5887929/212397794-9b5e7358-c253-446b-83d3-13afa7934cba.png)

what's lifecycle of that worker cache?

**Comment by yangwao** [comment]
Or we need to benchmark and burst some more requests to see it working I guess as it's good as warm cache, not cold one

**Comment by yangwao** [comment]
It's for some collection with some more giant media. It seems it's not happening now.

It seems Subrequests vs median CPU time correlates 
![image](https://user-images.githubusercontent.com/5887929/212677790-c6449bae-85af-4ac3-aae8-b939c7ad2b93.png)

![image](https://user-images.githubusercontent.com/5887929/212677884-35ef73f0-33da-4ee4-9c1e-307c28b1acd4.png)

![image](https://user-images.githubusercontent.com/5887929/212678000-024f740e-3e6e-459b-8918-f01fa640bb43.png)

**Comment by yangwao** [comment]
> interesting, stress test to see it can affect CPU time or not 🤔

I'm up to it!
Better to waste a few dollars now, to later realize some bad outcome of this implementation.

Maybe run some cypress test which will go through some less popular collections for example with bigger media/video best?

**Comment by yangwao** [comment]
okay seems it improves with more requests so just need to flood more requests lol
okay probably closing this 

![image](https://user-images.githubusercontent.com/5887929/212753365-ccf4be7d-fa8f-47e6-a120-2033d06977d1.png)
![image](https://user-images.githubusercontent.com/5887929/212753376-2f049cd5-d1b6-459c-b343-c7a744ac0ffc.png)

**Comment by yangwao** [comment]
> tested with 600rps for 5 minutes [app.warp.dev/block/cRkOftHWmknKkoTu7BZdOd](https://app.warp.dev/block/cRkOftHWmknKkoTu7BZdOd) there is no significant spike with the others metrics
> 
> requests

thank you for testing this!
