### ISSUE TITLE
Remove Durable object cache

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#4597]
### Is your feature request related to a problem?

Currently we integrated our custom IPFS gateway for IPFS images and therefore we do not need Durable object for cache.

To spot usage of Durable object look for 

```ts
const imageLinks = await getCloudflareImageLinks(metadataList)
```

### Describe the solution you would like

Remove code related to the cloudflare durable objects.

### Describe alternatives you have considered

also open issue what could refactored.
- https://github.com/kodadot/nft-gallery/issues/4598

## Ref
- #4596

**Comment by vikiival** [comment]
@yangwao can I deprecate the worker? 

- https://github.com/kodadot/workers/issues/19

**Comment by yangwao** [comment]
Thank you for your amazing and quick response! @holopin-bot @vikiival

**Comment by yangwao** [comment]
> @yangwao can I deprecate the worker?

yup, seems it's gone anyway? @vikiival
