### ISSUE TITLE
Rework image serving gateways 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4598]
We should rework `components/rmrk/utils.ts` and how it's used, and in the main objection, it's not `rmrk` only tools anymore.

We should put it in some config best plus handle image serving to be prioritized from https://image.w.kodadot.xyz 

@vikiival can input best practices what we should be done here

### Ref
[`258c7de` (#4596)](https://github.com/kodadot/nft-gallery/pull/4596/commits/258c7deb30663e9a0100e8e09e72acf92e72d526#diff-23f4d28ea6c1dced01ff7dc49c47048b1299702926107fb9e54c9e10362560aaR34)
- #4596

**Comment by Jarsen136** [comment]
👋

**Comment by vikiival** [comment]
@Jarsen136 good time to use https://github.com/kodadot/packages/tree/main/minipfs

If you miss something can implement on the fly

**Comment by Jarsen136** [comment]
> @Jarsen136 good time to use https://github.com/kodadot/packages/tree/main/minipfs
> 
> If you miss something can implement on the fly

Thanks, will check it tomorrow.
