### ISSUE TITLE
Add field for referrals at simple minting

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#460]
Whenever we will introduce referrals, grants, scholarships for artists
Would be nice to add into the simple mint field where one will refer to address from who was invited

like one who will be onboarding people will generate for themselves "affiliate" link like https://nft.kodadot.xyz/rmrk/mint?ref=CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd and once someone visits it, will mint with this.

Not sure if it should be put off from RMRK, put inside kRMRK fork, I'll let creativity on you.

Retroactive we could drop people tokens accordingly to their onboarding efforts, ambassadorship &c

Together ideated with @archnomics

**Comment by JustLuuuu** [comment]
<img width="599" alt="Screenshot 2024-07-31 at 13 25 53" src="https://github.com/user-attachments/assets/31283513-c366-4201-bfea-8f319f88c4a1">
<img width="606" alt="Screenshot 2024-07-31 at 13 25 58" src="https://github.com/user-attachments/assets/616a0bea-ec1c-4bb2-87c6-73510e68fa8a">

They dont exist anymore
