### ISSUE TITLE
Add multi-chain support to the search 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4617]
We still need essential parts to be more multi-chain robust, like search.
I briefly chatted with Viki that we will have a cheap hack to aggregate results from other chains for search, for example. 

Current results show only one chain.

I guess we would leverage this on top collections too.
![image](https://user-images.githubusercontent.com/5887929/200118135-196b6fce-19d6-418b-b9a6-a0b402a4beca.png)

## Continue
- https://github.com/kodadot/nft-gallery/issues/4380

---
First draft of schema

Collection

```sql
-- create table collection_entities with following columns
-- id (uuid, primary key, auto increment)
-- animation_url (text)
-- block_number (bigint)
-- chain (enum, default 'rmrk')
-- collection_id (text)
-- count (integer, default 0)
-- created_at (timestamp, default now())
-- floor_price (bigint, default 0)
-- hash (text)
-- image (text)
-- issuer (text, foreign key to creators table)
-- max (integer)
-- metadata (text)
-- name (text)
-- supply (integer, default 0)
-- updated_at (timestamp, default now())
-- version (integer, default 0)
```

NFT: 
```sql
-- create table nft_entities with following columns
-- block_number (bigint)
-- chain (enum, default 'rmrk')
-- collection_id (text, foreign key to collection_entities table)
-- issuer (text, foreign key to creators table)
-- id (uuid, primary key, auto increment)
-- metadata (text)
-- name (text)
-- image (text)
-- animation_url (text)
-- created_at (timestamp, default now())
-- updated_at (timestamp, default now())
-- hash (text)
-- serial_number (integer)
-- version (integer, default 0)
```

--- 
Follow up what can be done with new endpoint

So I managed to pushed the data into `Supabase`
If anyone wants to play with that here is the URL

```
https://xtnvtbdyvpbbnonbbcif.supabase.co/graphql/v1
```

You need to add `apiKey` header into your request. You can find the key in the discord group.

Sample Query
```graphql
query findCollections {
	collectionsCollection(first: 10) {
		edges {
			node {
				name
			}
		}
	}
}
```

## Ref
- https://github.com/kodadot/nft-gallery/discussions/4457#discussioncomment-4555921
- https://developers.cloudflare.com/d1/platform/client-api/
- https://github.com/kodadot/nft-gallery/issues/1824
- https://github.com/kodadot/nft-gallery/issues/4257

**Comment by yangwao** [comment]
> You need to add `apiKey` header into your request. You can find the key in the discord group.

Make worker wrap it?

**Comment by Jarsen136** [comment]
> > You need to add `apiKey` header into your request. You can find the key in the discord group.
> 
> @vikiival make worker to wrap it?

That would be better. I'm not sure why need to use this apiKey.

I would like to pick this issue. But seems that I could not find the `apiKey` in the discord group. 😄 
Pls tell me where to find it or DM me the key.

**Comment by yangwao** [comment]
> Pls tell me where to find it or DM me the key.

@vikiival

**Comment by vikiival** [comment]
> > Pls tell me where to find it or DM me the key.
> 
> @vikiival

https://github.com/kodadot/nft-gallery/discussions/4457#discussioncomment-4656461

**Comment by vikiival** [comment]
Continue in 
- https://github.com/kodadot/nft-gallery/issues/9615
