### ISSUE TITLE
Integration with tryshowtime

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#462]
As we have artists and we would like to help highlight them, their artwork seamlessly, we should have integration with them
As this should be an effort against RMRK "protocol", we can be helpful here once we will have our own API.

ref https://twitter.com/plha_se_hlasi/status/1404789137694203911

**Comment by JustLuuuu** [comment]
<img width="599" alt="Screenshot 2024-07-31 at 13 25 53" src="https://github.com/user-attachments/assets/87d592b7-806b-4f48-a030-66c5f3bbb1f1">
<img width="606" alt="Screenshot 2024-07-31 at 13 25 58" src="https://github.com/user-attachments/assets/e67fa1e8-a1ec-419d-a170-fea713b70a6b">

They don't exist anymore
