### ISSUE TITLE
List KodaDot at Oruga Expo 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4640]
As a heavy project of Oruga, we should not be missing on vue-telescope of Oruga, it seems we are among the greatest projects using Oruga 
- https://github.com/oruga-ui/oruga/network/dependents 

## Ref 
- https://oruga.io/expo/

**Comment by jtommy** [comment]
@yangwao the Expo uses Vue Telescope api (Nuxt team project).

When it will be ready and public on web you have just to lookup it by https://www.vuetelescope.com/ 😉

**Comment by yangwao** [comment]
Let's see, maybe @jtommy could help me out on this
- https://github.com/oruga-ui/oruga/issues/539

**Comment by yangwao** [comment]
shared code w/ Oruga team
