### ISSUE TITLE
Make directUpload as composable

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#4644]
- create `directUpload` composable?

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/4637#pullrequestreview-1240083555_

Maybe @roiLeo can be more descriptive here 

Lableled blocker until not clarified

**Comment by roiLeo** [comment]
either we move this to `services` folder or create a new `useDirectUpload` composable

usage: `const [filePath] = useDirectUpload(file, hash)` but I don't get the impression that we are expecting a function return.

By the way if we could replace axios with $fetch
