### ISSUE TITLE
User profile OG cards doesn't show up properly 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#465]
for example https://nft.kodadot.xyz/rmrk/u/J6mwrrDE5ZywDe8T4mWgsdgHCcrDcrVtoGh37i7PSaZARRs
when you try through https://cards-dev.twitter.com/validator
or https://t.me/@WebpageBot
Doesn't show anything.
Let's make it to show recent user mint in their collection to make it a bit random and recent.
In Description show user address or Twitter identity if available

Seems extra } is there 
![image](https://user-images.githubusercontent.com/5887929/122226467-4f9d2300-ceb6-11eb-839d-d544790f634b.png)

**Comment by roiLeo** [comment]
In views/Profile.vue,
```
get firstNFT()
```
need to return first nft (nft[0]) metadata image.

I'm new to the project, Is there any utils that we can call from the view to read ipfs data?

By the way extra '}' is at the end of the line 224.

**Comment by vikiival** [comment]
Hmm it's not so easy at this point because nfts from subquery does not have image, only metadata.

> Is there any utils that we can call from the view to read ipfs data?
yup 
```ts
import { fetchNFTMetadata } from '@/components/rmrk/utils';

const nftMeta = await fetchNFTMetadata(nft[0])
const image  = nftMeta.image;

```
