### ISSUE TITLE
CLASSIC minting: Adding NFT to collection without listing it for sale (not working)

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4654]
### Is your feature request related to a problem?

Classic minting: Adding NFT to your collection that already exists but not listing it for sale is not working. 

I wanted to mint it with no price (so it would not be for sale). Not possible because:
<img width="926" alt="Screenshot 2023-01-10 at 16 05 34" src="https://user-images.githubusercontent.com/104380776/211590408-b737e150-d1a6-4ad0-a08e-b18549ebb087.png">
or
<img width="910" alt="Screenshot 2023-01-10 at 16 21 24" src="https://user-images.githubusercontent.com/104380776/211590846-35c85562-66c4-488c-8bc2-e8add23a133c.png">

I could not proceed.

### Describe the solution you would like

If the price is 0 or nothing we should still be able to mint that NFT. In this case, it will just not be listed for sale, but you will be able to see it minted in the collection.

### Describe alternatives you have considered

Nope

**Comment by roiLeo** [comment]
✌️
