### ISSUE TITLE
Sentry team plan 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4659]
Hey, it seems Sentry caught every day like over 100 errors (spike is when Pinata did upgrade) and I guess it would be nice to take a peak together on new errors. 
The best what would be if Sentry could automatically log errors to our issues would be my ideal desired scenario, so we don't have many manual work to do and trust machines which actually offload some cognitive load. 

![image](https://user-images.githubusercontent.com/5887929/211829508-c0aaca93-4700-40aa-83e7-95cc7c405f39.png)
![image](https://user-images.githubusercontent.com/5887929/211818576-798840b4-b8d5-42f3-ab34-92fa6629a251.png)
![image](https://user-images.githubusercontent.com/5887929/211830049-8f2cf5f9-1bf9-4c68-bfac-13ce6bb7df8b.png)
![image](https://user-images.githubusercontent.com/5887929/211830346-843d1ebf-ec06-465c-8153-65b7022eeb7a.png)

A lot of errors are still happening, even with a recent drop.

So I've taken a team plan, which has unlimited team members. 

I made @preschian @vikiival  admin so they can invite you (@roiLeo)  to mitigate some errors people haven't reported here 
I'll play with integrations to be more seamless.

Happy to peak and mitigate many errors and improve the user experience! 

## Replays
I was thinking of using this 
- https://docs.sentry.io/platforms/javascript/session-replay/
- https://github.com/kodadot/nft-gallery/issues/4663

## Profiling
Plus we can resolve some issues taking a while for a good experience

- https://docs.sentry.io/product/profiling/

## Others
- https://geekflare.com/frontend-web-monitoring/
I'm not proficient in which error tracking is best, yet happy to adjust, for now going with team plan and mitigating most of errors would be good to go I guess:)

## Alternatives
- https://www.appsignal.com/
- https://www.airbrake.io/pricing

**Comment by Jarsen136** [comment]
> Does anyone know how to filter/ignore on sentry? for example, don't send to sentry if the browser/user-agent from `localhost` or `HeadlessChrome`
> 
> * https://forum.sentry.io/t/filtering-events-by-browser-name/15482
> * https://docs.sentry.io/platforms/javascript/configuration/filtering/
> 
> ![image](https://user-images.githubusercontent.com/734428/211863018-b3957b46-f9cd-4692-b6e4-f61e764fa79d.png)
Hey, @preschian  I would like to help. I will make a follow PR to solve it later.

By the way, could you pls invite me to be a member of the sentry team?

**Comment by yangwao** [comment]
Turns out, most of the errors were something we don't know 😏

![image](https://user-images.githubusercontent.com/5887929/212539204-d85aa0ae-1ccb-4840-bb5f-8c1caa52e882.png)


>Profiling
>Plus we can resolve some issues taking a while for a good experience

>[docs.sentry.io/product/profiling](https://docs.sentry.io/product/profiling/)

Reading profiling could be done in separate issue
-  https://docs.sentry.io/product/performance/getting-started/
- https://docs.sentry.io/platforms/javascript/guides/vue/performance/

Closing till now then!
