### ISSUE TITLE
add `SENTRY_AUTH_TOKEN` env to github secrets

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4679]
> > need to add `SENTRY_AUTH_TOKEN` env to netlify
> 
> done this part, let's test it?

need to put in github secrets

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/4671#issuecomment-1380651619_

**Comment by vikiival** [comment]
Added yesterday 

![image](https://user-images.githubusercontent.com/22471030/212335657-4197c24a-d220-400a-806f-affed7102c9b.png)
