### ISSUE TITLE
`NeoButton` UI component icon

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#4689]
We need to find a smart way to use (fontawesome) icon in `libs/ui` components

might be needed in some PR, you could start to use it in footer btn

**Comment by prachi00** [comment]
should we even use fontawesome? because most of the buttons we have in our design on figma looks pretty different from fontawesome

**Comment by roiLeo** [comment]
> should we even use fontawesome? because most of the buttons we have in our design on figma looks pretty different from fontawesome

fontawesome is used for footer buttons it will be easier to start on this one.
You can always try to suggest a solution to pass svg as prop.
