### ISSUE TITLE
[ERR] EvalError: [KODADOT::SUBAPI] Error: cannot get instance at wss://rpc.basilisk.cloud

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#4702]
### What happened?

When you create a new collection, it crashes at the point of "Uploading data to IPFS". Error message: 

![obrázok](https://user-images.githubusercontent.com/81104034/212476112-6a733e61-8b76-4aa8-98c8-418249e37daa.png)

### Please reproduce in steps

Creating a new collection. Upload an intro image for a collection - error

### Expected Behavior

ERR] EvalError: [KODADOT::SUBAPI] Error: cannot get instance at wss://rpc.basilisk.cloud

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS, SubWallet

### Screenshots

scr is up

### Payment link for reward

https://kodadot.xyz/transfer?target=FqCJeGcPidYSsvvmT17fHVaYdE2nXMYgPsBn3CP9gugvZR5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
I heard that @jak-pan has fingers in it 👁️:snake::eye:

**Comment by jak-pan** [comment]
Have problem with hostings would be better to switch to `wss://basilisk-rpc.dwellir.com` in the meantime
