### ISSUE TITLE
Twitter template for KodaDotFaucet 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#471]
In a similar fashion https://faucet.goerli.mudit.blog/ to boost our KodaDot Faucet, let's create a subpage that will help create Twitter template where someone could post their KSM address as well

- [ ] maybe at /faucet ?
- [ ] add button to homepage
- [ ] input box with their KSM address or probably fetch it from their extension when logged in
- [ ] engage to tweet
- [ ] put some engaging text tweet should have

**Comment by niklasp** [comment]
were is the faucet located? is this issue about the UI only or about creating a faucet that actualle sends tkens?

**Comment by yangwao** [comment]
The faucet doesn't exist, so yeah issue is about some best serverless bot to drip a minimal amount to mint. 
Best with some limits like account needs to have like 100 followers, works once per week &c

I guess since then the idea has evolved, but it's still valid when I review it, would be nice to have this one to remove barriers to someone acquiring KSM (or other native assets of a particular para chain) and we don't need that having some grants form, which requires some sort of attention.  

Would like to take this @niklasp ?

### Ref
#1875

**Comment by joelamouche** [comment]
I feel like this is a pretty big task and could be broken down into two: one for the Front End and one for the Back End.
Also do you have a link to an example of Kodadot implementing serverless?

**Comment by JustLuuuu** [comment]
not relevant anymore
