### ISSUE TITLE
Check later on @nuxt/pwa

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4719]
> currently there is no official pwa modules for nuxt3/bridge, for temporary using this [kevinmarrec/nuxt-pwa-module](https://github.com/kevinmarrec/nuxt-pwa-module)

let's check on @nuxt/pwa module later 
- https://github.com/nuxt-community/pwa-module

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/4713#issuecomment-1383905551_

**Comment by yangwao** [comment]
Do we have PWA now?

**Comment by roiLeo** [comment]
> Do we have PWA now?

yessir, `@vite-pwa/nuxt` module is installed but no "refresh content" modal

**Comment by roiLeo** [comment]
package installed, maybe need configuration, `<ClientOnly>` and pwa card (`$pwa?.offlineReady || $pwa?.needRefresh`)
