### ISSUE TITLE
Update the price of an NFT on cascade 

### ISSUE THREAD

**Issue by CdrsAlejandro** [kodadot/nft-gallery#472]
Hello guys! In case that the user wants to change or add the price of an NFT (With copies) in the gallery, the user would have to update the price one by one and it's kinda tedious, so in order to update this on cascade @vikiival and i had the idea to use the Symbol of the NFT as a key to change the other copies of the NFT, at the moment that the user wants to update or add a price on their NFT we grab the Symbol from the NFT and compare the price with the other NFTs that the user has on it's profile with the same Symbol and if the other NFTs with the same symbol doesn't have a price we add the same price that the user put in the first copy of the same NFT.

**Comment by JustLuuuu** [comment]
we have multilist 
<img width="818" alt="Screenshot 2024-07-31 at 13 24 07" src="https://github.com/user-attachments/assets/1e1f627c-c617-488c-9574-38758d5e37b5">
