### ISSUE TITLE
revisit gtm for vue3 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4730]
> is it safe if I remove gtm script? seems like a newer version of workbox is unable to cache gtm script. this is the error count from the workbox 

Why would you want to remove it? we use it to integrate google analytics
maybe try to update package to vue3 version or disable plugin in dev mode

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/4729#issuecomment-1384943734_

**Comment by roiLeo** [comment]
> btw, is it still being used internally?

Yes, we still receive data and we need to migrate code to GA4

> 1. seems like cloudflare already had built-in analytics for us, even track Core Web Vitals

What's that? can we track same stuff as GA? (region, device, lifecycle etc..)

> 2. in terms of performance, GA will hurts the performance https://www.simpleanalytics.com/blog/google-analytics-performance-impact-using-google-lighthouse

I am always open to any alternative solution since GA don't fully respect GDPR (I'm switching to matomo on self-hosted website)

**Comment by yangwao** [comment]
> 1. seems like cloudflare already had built-in analytics for us, even track Core Web Vitals

cf is good, but they lack history, only available for last 21 days iirc and different insights 

![image](https://user-images.githubusercontent.com/5887929/214277825-00486990-6588-433a-856f-9fdc09399bfd.png)

> What's that? can we track same stuff as GA? (region, device, lifecycle etc..)

it's semi ok, but more likely basic one

> in terms of performance, GA will hurts the performance [simpleanalytics.com/blog/google-analytics-performance-impact-using-google-lighthouse](https://www.simpleanalytics.com/blog/google-analytics-performance-impact-using-google-lighthouse)

using some async load?

**Comment by yangwao** [comment]
huh seems we've removed for while? 
![image](https://user-images.githubusercontent.com/5887929/214278692-ef622b5a-5320-40b7-8e0a-b9d98847d652.png)
