### ISSUE TITLE
Gallery item redesign: Description more important than Properties.

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4734]
### Is your feature request related to a problem?

Gallery item redesign: @exezbcz
When you open any NFT you can see this:
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/104380776/212900564-eae5f9be-60d7-4f81-9565-442cfd00a0c1.png">
It will automatically open the properties of the NFT. There is not much info you can learn about the art piece from Properties.

### Describe the solution you would like

I would suggest after opening an NFT; you will see Description by default. Not properties. For a buyer, I think the Description is more interesting (especially when not many artists use more than one property).

So when you open an NFT, you will first see the Description (then you can click on the Properties if you want).

### Describe alternatives you have considered

Maybe also switch Properties with Description? Like this:
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/104380776/212901280-79e7f0e8-5ec3-4e73-9183-db34839d22f2.png">

Not necessary.

**Comment by yangwao** [comment]
yes, let's make it and swap it
