### ISSUE TITLE
How user goes to collection view from item? 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4736]
doing user testing and realizing there is no link going to collection as we had before? 
@exezbcz 

maybe make link from more from this collection? 

![image](https://user-images.githubusercontent.com/5887929/212906853-a1fc81e6-f9c5-44f0-b4dc-21f010e01b48.png)

**Comment by yangwao** [comment]
i'm dumb, right under name

**Comment by JustLuuuu** [comment]
> i'm dumb, right under name

wait, why I don't see it anywhere? Collection: Luna witches.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/104380776/213163138-ca179fa1-4bca-40aa-b0a8-2d40bdd75caf.png">

Yesterday it was there 😫
