### ISSUE TITLE
Fix lighthouse report

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#474]
Currently KodaDot has not so good lighthouse stats.

<img width="584" alt="Screenshot 2021-06-18 at 11 57 45" src="https://user-images.githubusercontent.com/22471030/122544381-0a4f3180-d02d-11eb-8903-2193c1ae1775.png">

Deliverables:
- [ ] Fix performance
- [ ] Optional: fix other fields

**Comment by yangwao** [comment]
That's just time to load the bundle?

**Comment by yangwao** [comment]
I guess it's getting a bit worse at my side.
Topped up to p3 and $$:)
We want to see at least 80 for performance and 100 on rest.

![image](https://user-images.githubusercontent.com/5887929/131880204-cb7a98e4-4471-4b25-bd39-891a4bf0fff5.png)

**Comment by ksbek** [comment]
@yangwao I can handle this issue. Please assign me this issue.

**Comment by yangwao** [comment]
On desktop gives me 63
![image](https://user-images.githubusercontent.com/5887929/132136320-a77ee2c2-e7fe-404d-8a75-bf14a2fb7d99.png)

Mobile 35 
![image](https://user-images.githubusercontent.com/5887929/132136359-4cd2b615-8412-4553-874d-62f5c088c181.png)

So hope we can optimize something on the bundle, somehow :)

**Comment by yangwao** [comment]
Hello, @ksbek any progress on this?

**Comment by yangwao** [comment]
Meanwhile checking that it's time to cut bundle as average build time is.. quite high 
![image](https://user-images.githubusercontent.com/5887929/133576862-f452c9f6-bedb-4060-8e37-e6573c15fb8c.png)

**Comment by yangwao** [comment]
This issue is free for grab and quite important for us to keep it rolling checking on bundle.

**Comment by yangwao** [comment]
> On desktop gives me 63 ![image](https://user-images.githubusercontent.com/5887929/132136320-a77ee2c2-e7fe-404d-8a75-bf14a2fb7d99.png)

![image](https://user-images.githubusercontent.com/5887929/161727214-f9d2cbee-ff26-41ae-a690-c7fb165f7077.png)
 
> Mobile 35 ![image](https://user-images.githubusercontent.com/5887929/132136359-4cd2b615-8412-4553-874d-62f5c088c181.png)

![image](https://user-images.githubusercontent.com/5887929/161727302-ac1f9001-3dc1-4de4-8301-7dcd132dd120.png)

Seems how we load landing page impacted performance a lot.

**Comment by vikiival** [comment]
> Seems how we load landing page impacted performance a lot.

👀 may some async loading would be oki for this

**Comment by kkukelka** [comment]
created metaissue to track progress on this one https://github.com/kodadot/nft-gallery/issues/2816
