### ISSUE TITLE
Directory not empty `.nuxt\pwa\icons`

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#4747]
after bumping nuxt-bridge to the latest version, our CI sometimes throw an error like this. currently, need to retry the github actions if you guys find this error
![image](https://user-images.githubusercontent.com/734428/213116640-f597338f-04e7-47aa-bc11-50c8ac736d96.png)

**Comment by roiLeo** [comment]
I've already come across this https://github.com/kodadot/nft-gallery/pull/4713#pullrequestreview-1249707076
