### ISSUE TITLE
Reduce using nuxt-property-decorator and use composition API

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4750]
We need to reduce using `nuxt-property-decorator` first and use composition API instead. It will help us to migrate to vue3/nuxt3
https://github.com/nuxt-community/nuxt-property-decorator/issues/83#issuecomment-1245139696. at least for newer components
related: https://github.com/kodadot/nft-gallery/issues/2893

And I think we face this problem also https://github.com/nuxt-community/nuxt-property-decorator/issues/83#issuecomment-1246615441; most of the library is still not ready in nuxt3. And maybe some libs/modules are not compatible also in nuxt-bridge

It seems we have a lot of them (484 mentions)

- https://github.com/kodadot/nft-gallery/search?p=1&q=nuxt-property-decorator

Part of
---
- https://github.com/kodadot/nft-gallery/issues/2690

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/2690#issuecomment-1280409802_
            
## Ref
- https://github.com/kodadot/nft-gallery/issues/2893

**Comment by yangwao** [comment]
It's improving! 

[465 code results in kodadot/nft-gallery](https://github.com/kodadot/nft-gallery/search?p=1&q=nuxt-property-decorator)

**Comment by yangwao** [comment]
[456 code results](https://github.com/kodadot/nft-gallery/search?p=1&q=nuxt-property-decorator)

<img src="https://media4.giphy.com/media/3osxYhMyxzZCLCJLhe/giphy.gif"/>

**Comment by yangwao** [comment]
[415 code results](https://github.com/kodadot/nft-gallery/search?p=1&q=nuxt-property-decorator) in [kodadot/nft-gallery](https://github.com/kodadot/nft-gallery)

<img src="https://media3.giphy.com/media/yRRh94bjTNdXW/giphy.gif"/>

**Comment by roiLeo** [comment]
Can't manage to use `layout()` with nuxt-bridge

**Comment by yangwao** [comment]
> 178 files

<img src="https://media0.giphy.com/media/3o6ZsVLtrVPHjcxXDa/giphy.gif"/>

**Comment by yangwao** [comment]
👀

![image](https://github.com/kodadot/nft-gallery/assets/5887929/c1f6f7e6-f2d1-4b5a-8e8f-194fd8826ccb)

https://github.com/search?q=repo%3Akodadot%2Fnft-gallery+nuxt-property-decorator&type=code

**Comment by yangwao** [comment]
156 👀

![image](https://github.com/kodadot/nft-gallery/assets/5887929/e6ac8877-6cca-4405-81d0-2a4c7c6218c6)

<img src="https://media4.giphy.com/media/8L0wWucm72M3l99zAs/giphy.gif"/>

**Comment by yangwao** [comment]
144 files 👀

**Comment by roiLeo** [comment]
144 files .. again 🪨

**Comment by yangwao** [comment]
141 files 👀

**Comment by yangwao** [comment]
134 👀👀👀

**Comment by yangwao** [comment]
👀👀👀
125 👀
👀👀👀

**Comment by yangwao** [comment]
115 😏

**Comment by yangwao** [comment]
88 files 😳

**Comment by yangwao** [comment]
78 files 🤩

**Comment by yangwao** [comment]
63 files 🤯

**Comment by yangwao** [comment]
54 🫣

**Comment by vikiival** [comment]
34 🔢

**Comment by yangwao** [comment]
> 34 🔢

[search shows 50](https://github.com/kodadot/nft-gallery/search?p=1&q=nuxt-property-decorator), maybe cached?

**Comment by vikiival** [comment]
> [search shows 50](https://github.com/kodadot/nft-gallery/search?p=1&q=nuxt-property-decorator), maybe cached?

Well yes and no

[Number of .vue components](https://github.com/search?q=repo%3Akodadot%2Fnft-gallery+nuxt-property-decorator+language%3AVue&type=code&l=Vue)

**Comment by yangwao** [comment]
It's moving

43 / 30

**Comment by yangwao** [comment]
35 / 24

**Comment by yangwao** [comment]
29 / 18 

<img src="https://media2.giphy.com/media/yGwmppGsJDwCQ/giphy.gif"/>

**Comment by yangwao** [comment]
26 / 15 
<img src="https://media1.giphy.com/media/5qt1W9W0cWGKex7l2p/giphy.gif"/>

**Comment by yangwao** [comment]
18 / 7 

nuxt3 is getting closer
you can vote on prediction market btw - https://app.zeitgeist.pm/markets/238
<img src="https://media4.giphy.com/media/bLBvTeuKNi16iclrJV/giphy.gif"/>

**Comment by yangwao** [comment]
Very last three components.

**Comment by yangwao** [comment]
Last two?
- #7038 
- #7030

**Comment by vikiival** [comment]
> Very last ~three~ two components.

Time to update [STYLE_GUIDE.md](https://github.com/kodadot/nft-gallery/blob/ead66732e1197e3f24e792ae030bfa3e68f160dc/STYLE_GUIDE.md?plain=1#L93)

And check if we use some of the last mixins

**Comment by yangwao** [comment]
12 / 1 

<img src="https://media3.giphy.com/media/naiatn5LxTOsU/giphy.gif"/>

**Comment by vikiival** [comment]
According Create component we do not use typescript mixins

**Comment by yangwao** [comment]
12 / 1
if someone wants to have a look at the very last one.

**Comment by yangwao** [comment]
- https://github.com/search?q=repo%3Akodadot%2Fnft-gallery+nuxt-property-decorator&type=code
delete all mixins and remove nuxt-property-decorator from package.json?

**Comment by yangwao** [comment]
Done in 
- #7117
