### ISSUE TITLE
Redesign Minting experience // simplify minting experience

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4752]
Backlog till new design, discuss here
- https://github.com/kodadot/nft-gallery/discussions/3898

@VladoTheBoi will do the research on what to 
- consolidate
- upgrade
- polish

 in our minting experience, feel free to reach him if you have something we should not forget 

## Ref
- #614

**Comment by VladoTheBoi** [comment]
So we want to redesign the look of the minting form it self as well as change the whole navigation that leads to minting right?  As that is quite misleading from what I've read so far.

**Comment by yangwao** [comment]
> As that is quite misleading from what I've read so far.

I would propose rework whole flow how it works for users as current flow is pretty broken. We can do better :)

**Comment by VladoTheBoi** [comment]
So I have somewhat finalized the minting redesign. I have a few questions:
1. What exactly means when user enables "Explicit content"?
2. We currently have different flow when minting into collection or just minting (simple) an NFT. Is it possible to do this in one flow where user would have to choose a collection but would have an option "No collection" which would just mint the NFT? 
3. If there is enough or more information inputs in Create Collection and Create NFT flows than needed. 
- Create collection has: logo image, banner image, name, description, select blockchain, explicit content
- Create NFT has: file, name, description, select collection, select blockchain, price (can choose currency), royalties, number of copies, explicit content. 
If there is something missing or some unsupported things, please let me know.

4. Also regarding supported things on different blockchains. If there is something that is not available on specific blockchain.

![landing page - main](https://user-images.githubusercontent.com/95911767/222743219-a933e135-3558-4845-bdc6-81d61cf13db8.png)
![landing page - main-1](https://user-images.githubusercontent.com/95911767/222743236-03b1b43c-2c93-4d2b-a344-adec17b85d26.png)
![Create New Collection](https://user-images.githubusercontent.com/95911767/222743260-6b51dab3-115c-4c38-8ced-d3243902bf62.png)
![Create NFT](https://user-images.githubusercontent.com/95911767/222743368-4d4ea51b-fff5-461b-ba90-130fe2978358.png)

**Comment by roiLeo** [comment]
Wow looks neat! I can answer some of your questions

> 1. What exactly means when user enables "Explicit content"?

- NSFW content
 
> 2. We currently have different flow when minting into collection or just minting (simple) an NFT. Is it possible to do this in one flow where user would have to choose a collection but would have an option "No collection" which would just mint the NFT?

- possible, but I think we will have to wait for the collection to be created on chain

> 3. If there is enough or more information inputs in Create Collection and Create NFT flows than needed.
>     * Create collection has: logo image, banner image, name, description, select blockchain, explicit content

- add n° of MAX items
- collection type?

>     * Create NFT has: file, name, description, select collection, select blockchain, price (can choose currency), royalties, number of copies, explicit content.

- attributes!
- don't know what "number of copies" refer

> 4. Also regarding supported things on different blockchains. If there is something that is not available on specific blockchain.

- rmrkv1 doesn't have offers nor royalties
- bsx will have auction feature

I would put the possibility to choose the network at the beginning

**Comment by VladoTheBoi** [comment]
> NSFW content

yes i know the meaning of it, I just dont know what exactly it changes when user enables this. 
Do you need to have explicit content allowed somewhere to see it? Is it marked somehow in the NFT detail page? etc.. :) 

> possible, but I think we will have to wait for the collection to be created on chain

I meant that the NFT would not belong to any collection. If thats possible. 
But you made a good point that we could also add "create collection" as an option which is what you were probably refering to 

>add n° of MAX items
collection type?

decided to not put the item limitation into collection as it is not really needed. I talked to 2 artists and they said that there is no real value to be able to limit this, because when you limit the size and then decide that you would like to add some NFTs to it, you cant. So by default it would be unlimited as it gives artists more choices. 

Collection type? What do you mean?

>attributes!
don't know what "number of copies" refer

attributes you mean something like properties right? Something like OpenSea have? 
Didnt know if we support this or not so I didnt bother rn.
<img width="439" alt="Screenshot 2023-03-03 at 15 47 31" src="https://user-images.githubusercontent.com/95911767/222750538-b63ef0ae-2d24-4f5f-8f5e-c5129e4f39c1.png">

and number of copies is basically the supply of the particular NFT. In other words, Editions as it is called rn in Koda.

>rmrkv1 doesn't have offers nor royalties
bsx will have auction feature

noted :) will look into the auction feature what it does

>I would put the possibility to choose the network at the beginning (& don't forget about dark mode 😃 )

I also have this flow prepared, but the reason I added this into the form for now is that user would have to click min 2-3 times as of this flow to get to the minting form page, and would not even have the option to change the blockchain afterwards. So you can basically change anything you want in the flow itselft without the need to go from the beginning. 

Dark mode will be done once I am certain with the flow so that I would have to re-do it several time :)

**Comment by roiLeo** [comment]
> yes i know the meaning of it, I just dont know what exactly it changes when user enables this. Do you need to have explicit content allowed somewhere to see it? Is it marked somehow in the NFT detail page? etc.. :)

It mean user is going to mint nsfw content, then we shoul be able to filter them on explore page (#285)

> I meant that the NFT would not belong to any collection. If thats possible. 

Not possible on certain chain. possible on rmrkv1 I think

>But you made a good point that we could also add "create collection" as an option which is what you were probably refering to

If we want to create a NFT it need to be attached to a collection.
Flow is: select your existing collection then create nft

> decided to not put the item limitation into collection as it is not really needed. I talked to 2 artists and they said that there is no real value to be able to limit this, because when you limit the size and then decide that you would like to add some NFTs to it, you cant. So by default it would be unlimited as it gives artists more choices.

I don't agree, I think that there is an added value to limit the products of a collection. It can attract more people and increase the value. Just like what we have with fashion, car etc..

> Collection type? What do you mean?

I've seen that onn bsx you can set Collection Type which "determines its purpose and usage" maybe if user want to create an audio collection or video only collection etc..

> attributes you mean something like properties right? Something like OpenSea have? Didnt know if we support this or not so I didnt bother rn. 

Yep we support this kind of stuff but it's pretty basic for now, this can be extended as desired.

For now we have something like this (key => value)
![Screenshot 2023-03-03 at 16-14-39 KodaDot Low fees and low carbon minting KodaDot - NFT Market Explorer](https://user-images.githubusercontent.com/9987732/222756789-e62d485c-774e-4f1e-8da3-ccfd4b1057d1.png)

> noted :) will look into the auction feature what it does

It's not ready yet but keep in mind we will introduce in a near futur.

> I also have this flow prepared, but the reason I added this into the form for now is that user would have to click min 2-3 times as of this flow to get to the minting form page, and would not even have the option to change the blockchain afterwards. So you can basically change anything you want in the flow itselft without the need to go from the beginning.

we may have a problem on create collection flow, I'll expand later

**Comment by VladoTheBoi** [comment]
>Not possible on certain chain. possible on rmrkv1 I think

Ok, so then this option would not be present where its not supported. Basilisk for now. 

>If we want to create a NFT it need to be attached to a collection.
Flow is: select your existing collection then create nft

But this applies only for Basillisk no?

>I don't agree, I think that there is an added value to limit the products of a collection. It can attract more people and increase the value. Just like what we have with fashion, car etc..

You can always limit it yourself by not minting more items into the collection than you desire. 
So if you want it to have only 10 items, then you mint 10 items but still have the option to mint more of you decide.

>I've seen that onn bsx you can set Collection Type which "determines its purpose and usage" maybe if user want to create an audio collection or video only collection etc..

Probably depends how it would be used afterwards. It would probably be just for filtering collections right? 

>Yep we support this kind of stuff but it's pretty basic for now, this can be extended as desired.

So no limitations here?

**Comment by roiLeo** [comment]
> > If we want to create a NFT it need to be attached to a collection.
> > Flow is: select your existing collection then create nft
> 
> But this applies only for Basillisk no?

IMO, this should be on unified on all chain.

> You can always limit it yourself by not minting more items into the collection than you desire. So if you want it to have only 10 items, then you mint 10 items but still have the option to mint more of you decide.

But this could allow us to add new collection filter
![Screenshot 2023-03-03 at 17-15-30 Singular Kusama-native NFTs #RMRK #NFT](https://user-images.githubusercontent.com/9987732/222771636-e9667f17-aac6-41f0-a3be-97a3ccf5512e.png)

> > I've seen that onn bsx you can set Collection Type which "determines its purpose and usage" maybe if user want to create an audio collection or video only collection etc..
> 
> Probably depends how it would be used afterwards. It would probably be just for filtering collections right?

Yep. but I'm not sure about this one and how we can use it to our advantage.


> > Yep we support this kind of stuff but it's pretty basic for now, this can be extended as desired.
> 
> So no limitations here?

limitation is only your imagination 😉 
(technically speaking I think there is a limitation but I don't know the maximum)

**Comment by yangwao** [comment]
Hopefully we can close on this soon and we could make it soon as dedicated page at 
- mint.kodadot.xyz
- create.kodadot.xyz

**Comment by VladoTheBoi** [comment]
I've finished design for desktop. Please have a look and let me know if you have any questions. 
Prototype should work with most of the states, hovers etc. Also left a short comment on some components and its states next to the design. Working on finishing mobile and darkmode. 

Static designs: https://www.figma.com/file/GVkcT73q9LcbMAc6y15zzP/kodadot-working-file?node-id=6380-89140&t=nfo3BPJgUsRLpCna-4
Prototype: https://www.figma.com/file/GVkcT73q9LcbMAc6y15zzP/kodadot-working-file?node-id=6502-91358&t=nfo3BPJgUsRLpCna-4

There are however some things regarding tags I would like to discuss.
<img width="321" alt="Screenshot 2023-04-21 at 0 14 46" src="https://user-images.githubusercontent.com/95911767/233498627-ec5457a9-7f75-4557-8c06-e75fb3177cbb.png">
tags that I want to discuss.

**Comment by VladoTheBoi** [comment]
Mobile finished 📱 ✅

**Comment by VladoTheBoi** [comment]
Dark mode 99% done ✅ 
Need to only revise some small details (tags, toggles and 1 title) - note for me. 

Removing Design-Request label. Issue can be grabbed.

**Comment by yangwao** [comment]
Let's 
- make new issue Simple Mint v2 
- publish designs there
- close this one 🥳

**Comment by VladoTheBoi** [comment]
Moved to #5939 Closing.
