### ISSUE TITLE
Replace vuex with pinia/useState

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#4755]
"Nuxt no longer provides a Vuex integration. Instead, the official Vue recommendation is to use pinia, which has built-in Nuxt support via a [Nuxt module](https://pinia.vuejs.org/ssr/nuxt.html)." https://nuxt.com/docs/migration/configuration#vuex

- pinia support nuxt bridge https://pinia.vuejs.org/ssr/nuxt.html
- useState composables https://nuxt.com/docs/getting-started/state-management

related code:
- https://github.com/search?q=repo%3Akodadot%2Fnft-gallery+getters.&type=code
- https://github.com/search?q=repo%3Akodadot%2Fnft-gallery+dispatch%28&type=code
- https://github.com/search?q=repo%3Akodadot%2Fnft-gallery+commit%28&type=code

**Comment by roiLeo** [comment]
## Progress

- [x] lang #5057 
- [x] wallet #5057 
- [ ] fiat #5138 
- [ ] exploreFilters #5139 
- [ ] assets
- [ ] chain
- [ ] explorer
- [ ] history
- [ ] identity
- [ ] identityMint
- [ ] pinning
- [ ] preferences
- [ ] setting
- [ ] index?

**Comment by preschian** [comment]
@vikiival @roiLeo since we are moving forward with pinia, do we still need `@kodadot1/vuex-options`?

**Comment by roiLeo** [comment]
> do we still need `@kodadot1/vuex-options`?

🤔 question is will it work with Nuxt3? 
one option would be to rewritte it to pinia

**Comment by vikiival** [comment]
> @vikiival @roiLeo since we are moving forward with pinia, do we still need `@kodadot1/vuex-options`?

Good Q
happy to deprecate,
Move majority to statick

**Comment by yangwao** [comment]
<img src="https://media0.giphy.com/media/KtPjuhm119ggU/giphy.gif"/>

**Comment by roiLeo** [comment]
Last piece is on #6210, don't know what happened if we remove code
