### ISSUE TITLE
Different drop shadow

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#4759]
![image](https://user-images.githubusercontent.com/90852205/213256761-52611607-d184-4734-95fc-c6237efc81e0.png)
how hard is it to make the drop shadow as the bottom picture instead of the top one?

**Comment by prachi00** [comment]
@exezbcz are we still making this change?

**Comment by roiLeo** [comment]
IMO not possible without tons of css

duplicate #8370
