### ISSUE TITLE
Incorrect display of a collection

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#4775]
### What happened?

Recently I was creating a new collection on BSX, this time the upload went correctly, but the collection remained under a numeric name.  I then uploaded (minted) NFTs to this collection, some loaded, others didn't load to this day. 

Where is the problem? 
The collection I am concerned about:
https://kodadot.xyz/bsx/collection/2551182625

### Please reproduce in steps

standard minting procedure....

### Expected Behavior

functionality...

### What browsers are you seeing the problem on?

Chrome, Firefox

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

![obrázok](https://user-images.githubusercontent.com/81104034/213491439-7f83ab35-37ff-4b6a-bf95-7fb17b52e3d1.png)

### Payment link for reward

https://kodadot.xyz/transfer?target=bXjrHpyJzSczJuuqmtN6nqCnd5b7KFa5LK1rBtF1tUHDYzp8N

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
temporary hotfix on beta

https://github.com/kodadot/nft-gallery/pull/4783

**Comment by yangwao** [comment]
@jkdizajn it's out, btw nice collection! ;)

we will look on it on https://github.com/kodadot/snek/issues/137

- https://beta.kodadot.xyz/bsx/gallery/2551182625-6
- https://kodadot.xyz/bsx/gallery/2551182625-6


![image](https://user-images.githubusercontent.com/5887929/213744591-659bc2b4-fe5d-4068-9a1a-a1e223ac5f2b.png)

**Comment by jkdizajn** [comment]
> @jkdizajn it's out, btw nice collection! ;)
> 
> we will look on it on [kodadot/snek#137](https://github.com/kodadot/snek/issues/137)
> 
>     * https://beta.kodadot.xyz/bsx/gallery/2551182625-6
> 
>     * https://kodadot.xyz/bsx/gallery/2551182625-6
> 
> 
> ![image](https://user-images.githubusercontent.com/5887929/213744591-659bc2b4-fe5d-4068-9a1a-a1e223ac5f2b.png)

THX bro <3

**Comment by roiLeo** [comment]
closed as fixed
