### ISSUE TITLE
Changes in Waifu minter

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#4777]
We plan to upgrade the experience of waifu minter and use it more inside the KodaDot UI.

1. Replace Email with login (auth)

So user should be logged in

<img width="756" alt="Screenshot 2023-01-19 at 17 14 59" src="https://user-images.githubusercontent.com/22471030/213495341-9450ead2-6d96-4e4c-a796-a8110277a34f.png">

2. change AI model
 - #4722
 
3. KodaMinter should auto transfer the NFT to logged in owner

**Comment by JustLuuuu** [comment]
We talked that minting will be available a few times per month. I think we also talked that it will be limited 1 NFt per person per collection. in this case:

### **Ideas for the campaign name:** 
- January waifu - February waifu - collect them all: Once a month big mining event!
- KodaWaifu series # 1: Magical anime girls (let's use prompts that can create your magical character - fairy, witch, mysterious, wand, elve ears)
- KodaWaifu series # 1: Enchanting ladies

If we always write KodaWaifu series # 1..2..3..: (name of these series)....... people would be motivated to collect them (we can also do a competition after some time, if you collect some number of waifus you can win something)

### **Ideas for the collection description:**
- This adorable KodaDot collection features a variety of anime-inspired characters, each with their own unique abilities and personalities. From powerful witches to playful fairies, these magical girls will charm their way into your heart. Each NFT is one-of-a-kind and beautifully illustrated, making them the perfect addition to any collection. Whether you're a fan of anime or just love cute and whimsical designs, you're sure to find a magical girl that speaks to you. With a limited number available, don't miss your chance to own one of these enchanting NFTs.

- A lost anime waifu wandered through the digital world, searching for her place in the world. She encountered many challenges and obstacles, but she never gave up. She pushed through and eventually, she was discovered by a collector who saw her unique beauty and value. He added her to his NFT wallet, where she would always be safe and appreciated as a one-of-a-kind digital asset. And they both lived happily ever after.

### **Ideas for accessories/prompts:** 
- vampire's teeth, halo (svatoziara), feathers in hair, cap 🧢, flag in hand, holding a pet, ear muffs, crown, flowers in hand

### **Ideas for cover pic:**
- Keep it simple: mint nice waifu and just add KodaLogo at the bottom 
- Collage of waifus?: use random waifus you minted (or ones from previous mining events) and put them all in one collage Something like this:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/104380776/213521905-41cdabc7-2e26-4627-b63d-81366d0050a8.png">
- Keep it complicated: ask Exez for a thumbnail template we can reuse for different collections (I still think the first two options will look better

I'm excited to see how it goes! 🥹

**Comment by yangwao** [comment]
> 1. Replace Email with login (auth)

adding Discord & Twitter login to join and follow us? 🤔

**Comment by DeluneClaire** [comment]
Can we add for Valentine's campaign stuff like: in love, madly in love, broken heart, with roses, with chocolate, drinking wine, charmed, in red...
