### ISSUE TITLE
Upgrade fontawesome to v6

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#4788]
> ufff, that check from font awesome does not look good xd, is there thinner version or? I would stick to the think one if its possible.

I revert it back for now. thinner is only on the pro version on fontawesome. free version on the newest version looks thinner

fa v5: https://fontawesome.com/v5/icons/check?s=solid&f=classic
fa v6: https://fontawesome.com/icons/check?s=solid&f=classic

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/4782#issuecomment-1399182696_
            
upgrade `@fortawesome/*` packages to v6

**Comment by yangwao** [comment]
we can chip for pro version if so, yet w design we thought go w/o much icons. what's the price? $99/yr?

**Comment by roiLeo** [comment]
IMO there are some better alternative to fa6 (ref #796) or we can try to integrate [nuxt-icon](https://github.com/nuxt-modules/icon) which wrap [icones](https://icones.js.org/).

**Comment by yangwao** [comment]
> IMO there are some better alternative to fa6 (ref #796) or we can try to integrate [nuxt-icon](https://github.com/nuxt-modules/icon) which wrap [icones](https://icones.js.org/).

we are looking on it w/ @exezbcz 

> seems like it doesn't support nuxt-bridge [nuxt-modules/icon#21](https://github.com/nuxt-modules/icon/issues/21)

oops, so what are odds we can use it in horizon of 8 weeks ?

**Comment by yangwao** [comment]
> maybe start using fa v6 icons in the design?

are sure we can start using FA v6 ? In past there was some issue with fortawesome & Vue3 https://www.npmjs.com/package/@fortawesome/vue-fontawesome

**Comment by yangwao** [comment]
@preschian let me know

if fa6 would go I'm easy for going for PRO

**Comment by yangwao** [comment]
> this is the tricky one. when looking for modules/plugins need to check the package should be compatible with nuxt-bride + nuxt3 also

Yeah we are in pitty transition and quite complicated stuff, I'm hopeful here

> just wondering, how do we share private fa tokens with the other contributors if we are using the pro version?

cf-worker with host origins for example or we will figure out, there is no power in verse can stop us ;)

**Comment by yangwao** [comment]
> so, the developer that forked our repo needs to configure that first before running `pnpm install`

I see, hmm, some fallback if token is not available? or it will throw tons of errors?

**Comment by yangwao** [comment]
okay to move on, bc it's cascading blocking at least 4+ following issues. 

I can think of distributing tokens to recent frequent contributors and let's go :)

**Comment by VladoTheBoi** [comment]
Sorry about closing and reopening, didnt know it is a button :D

**Comment by roiLeo** [comment]
We might want to integrate [iconify](https://icon-sets.iconify.design/) (or [icones.js](https://icones.js.org/)) for that purposes this will allow us to have easy access to multiple icon pack.

**Comment by exezbcz** [comment]
@roiLeo yup, that would be cool. I am actually using their figma plugin

or maybe upgrade to the sharp icons from Fa and wait till they update the rest since many things are "coming soon"

**Comment by VladoTheBoi** [comment]
FA released new sharp light icons in March 27. Not sure how many regular sharp icons were there before, rn its 3205 in each light, regular and solid. Do we want to use FA then or we want to integrate iconify somehow as well?  
I can see we've set FA regular as a base for now.
