### ISSUE TITLE
Alignment of buttons in the gallery item is off

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#4796]
i guess this is for another issue? 
![image](https://user-images.githubusercontent.com/90852205/213710595-aaf40bf2-0208-4841-94cb-d626f39422a7.png)

_Originally posted by @exezbcz in https://github.com/kodadot/nft-gallery/issues/4766#issuecomment-1398418160_
            
- @exezbcz can say more 
- please close if duplicate

**Comment by petersopko** [comment]
- https://github.com/kodadot/nft-gallery/issues/4785

**Comment by vikiival** [comment]
Thanks @petersopko
