### ISSUE TITLE
Round robin for IPFS gateways

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#48]

**Comment by yangwao** [comment]
Here is the list of gateways 
https://ipfs.github.io/public-gateway-checker/
Some gateways are down that was this idea raised to cover UX-first experience
- For fasted experience, would be nice to serve it from 
-- gateway.pinata.cloud
-- cloudflare-ipfs.com
-- ipfs.fleek.co (our IPFS version is deployed there so I bet it would be great experience)
-- ipfs.infura.io - ethereum standard
-- dweb.link - repacked ipfs.io gw but someone else operates this? whenever gateway.ipfs.io & ipfs.io is down, dweb.link is usually up

![image](https://user-images.githubusercontent.com/5887929/107623755-20ea1400-6c5a-11eb-8c73-2a385a7de4e8.png)

**Comment by yangwao** [comment]
for now we have dedicated pinata gateway, solved for today
