### ISSUE TITLE
Extend flipper with hold period 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4821]
- https://dune.com/cryptuschrist/Wallet-Stats-Dash

![image](https://user-images.githubusercontent.com/5887929/214315248-9901d271-2ce9-4c0c-9ef0-2b3d72f8895b.png)

**Comment by yangwao** [comment]
Ups, we forgot about this one @exezbcz in 

- #5272 
- #5000

**Comment by exezbcz** [comment]
@yangwao Should I still give this one thought? I think adding one data row to the card will fix this:D If we were to include it for both holders and flippers, wouldn't it make more sense for holders?
