### ISSUE TITLE
kodadot.xyz not loading in nova wallet 

### ISSUE THREAD

**Issue by ERussel** [kodadot/nft-gallery#4827]
### What happened?

When trying to open kodadot.xyz in Nova Wallet DApp browser it is not loading. Error from the dev console is attached.

![image_2023-01-25_14-14-19](https://user-images.githubusercontent.com/570634/214565880-b15412f6-77c0-4c0b-a124-2dd170e917bf.png)

### Please reproduce in steps

1) Open Nova Wallet app
2) Go to Browser tab
3) Put "kodadot" into the search field
4) Tap on found KodaDot option
5) Browser is opened but nothing loads

### Expected Behavior

DApp browser for KodaDot is loaded and wallet account is requested

### What browsers are you seeing the problem on?

Mobile iOS Safari (WebKit)

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

No

### Which wallet you are using?

Nova Wallet

### At which chain did you encounter bug?

Basilisk, MoonSama, RMRK

### Screenshots

https://user-images.githubusercontent.com/570634/214567060-eef8921d-4aa2-4b9e-81c9-15589d97de1d.MP4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustLuuuu** [comment]
Yeah not working on iOS probably. I tried it too on my iPhone.

**Comment by yangwao** [comment]
Hey @ERussel is this still thing? We did few updates recently. I don't have iOS tho.

**Comment by ERussel** [comment]
Hey @yangwao still can reproduce on iOS. I think it is related to some part of the code that treats Safari with polkadot js extension at the same time in the wrong way.

**Comment by yangwao** [comment]
hey @ERussel if you can check now, it should be available on https://beta.kodadot.xyz
