### ISSUE TITLE
Add Identity creation also on Basilisk

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4832]
### Is your feature request related to a problem?

When someone opens kodadot.xyz it will automatically open bsx version. If someone wants to create on-chain identity they need to go back to RMRK. 

### Describe the solution you would like

Is it possible to add identity creation also to Basilisk? For now it's possible only on RMRK

### Describe alternatives you have considered

Unite RMRK and BSX so people don't need to think about where to click.

**Comment by roiLeo** [comment]
Meanwhile this is already done
