### ISSUE TITLE
vue-gtag reporting

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4856]
Does ga works properly? As on CF web analytics are some numbers.

![image](https://user-images.githubusercontent.com/5887929/215322170-a249b849-b3b5-4c63-953a-3b7ce9ae9150.png)

- https://github.com/kodadot/nft-gallery/pull/4815

**Comment by roiLeo** [comment]
Something strange 
<img width="655" alt="Capture d’écran 2023-01-30 à 8 20 12 AM" src="https://user-images.githubusercontent.com/9987732/215412370-09d02d72-9442-4e4e-8ad3-752336c992f7.png">

**Comment by roiLeo** [comment]
> and cookies could be enabled by default, on "X" just disappear toast.

I don't agree with that. User won't be able to disable tracking services.

**Comment by yangwao** [comment]
Then enable on "X" ? or keep accept?

**Comment by yangwao** [comment]
Also drop could be no one clicks accept or ublock?

**Comment by yangwao** [comment]
Notion on mobile has Accept All only. I would go this way.

![IMG_20230206_114129_724.jpg](https://user-images.githubusercontent.com/5887929/216951099-50fe1769-2e05-4ecf-8cba-ab612068efe8.jpg)

Ours could be made more mobile friendly?

![IMG_20230206_114132_238.jpg](https://user-images.githubusercontent.com/5887929/216951101-d7f4e553-7ac5-4e40-93d9-4a464d5da562.jpg)

**Comment by yangwao** [comment]
@roiLeo can we move on with this?

**Comment by roiLeo** [comment]
> Notion on mobile has Accept All only. I would go this way.

We don't have cookie policy when it should be mandatory

> Ours could be made more mobile friendly?

If you say so..

> @roiLeo can we move on with this?

move on what? code won't change, user should have possibility to decline tracking

**Comment by yangwao** [comment]
> move on what? code won't change,

Dropped numbers means we just did not turned it on by default since now? Just want to gain insight why it's happening showing 0? 

CF dash showing 230 users on 2/2/2023 where GA 0. 
Do you think all that 230 visits did not clicked accept or blocking tracking at all?

Oh also found some requirement for GA4 instead having UA (this we have i guess rn?)

![image](https://user-images.githubusercontent.com/5887929/216989372-b3530ca7-94bb-4c20-b17a-cae0ac91ba1d.png)

**Comment by roiLeo** [comment]
> Dropped numbers means, that tracking does not turn on by default since now?

=> default: false
=> accept: enable

> I just want to gain insight why it's happening showing 0.
> I also found some requirement for GA4 instead having UA (this we have i guess rn?)

could you share me GA4 config as I don't have access, I'll try to debug this.

> CF dash showing 230 users on 2/2/2023 where GA 0. 
> Do you think all that 230 visits did not clicked accept or blocking tracking at all?

I don't know how CF track user, what data is stored? how long is it kept?
We need to inform user about these tracking services. (privacy policy)

**Comment by yangwao** [comment]
> => accept: enable

that also means no-one clicks it, mmm

> could you share me GA4 config as I don't have access, I'll try to debug this.

shared u admin to `medina....@gmail`, there seems GA4 properties (?)

> We need to inform user about these tracking services. (privacy policy)

either, probably their general ToS ?

> I don't know how CF track user, what data is stored? how long is it kept?

- #4918 
- #4928

**Comment by yangwao** [comment]
Can we have numbers back please?

**Comment by roiLeo** [comment]
> Can we have numbers back please?

Seems to be an issue with nuxt-brigde and plugins

Btw #4928 is still needed..

**Comment by preschian** [comment]
> Seems to be an issue with nuxt-brigde and plugins

what if we implement the GA with a vanilla approach, without a plugin?

**Comment by roiLeo** [comment]
> > Seems to be an issue with nuxt-brigde and plugins
> 
> what if we implement the GA with a vanilla approach, without a plugin?

Yeah I thought about that one using `useHead()`, thing is I don't know if we can use publicRuntime to "hide" GA id

**Comment by roiLeo** [comment]
> does GA Id and `UA-` stuff are the same thing? seems like it will show it publicly

Yep this is visible in source code, but shoud be set in a env var in order to set different code according to the domain

**Comment by yangwao** [comment]
> set different code according to the domain

that would be nice actually have diff GA for each env, that would help filter out some numbers and cases

**Comment by yangwao** [comment]
> Btw #4928 is still needed..

full filled, ready to be added

**Comment by roiLeo** [comment]
> full filled, ready to be added

⏳

**Comment by roiLeo** [comment]
Looking good
![Screenshot 2023-05-16 at 14-06-07 Analytics Accueil](https://github.com/kodadot/nft-gallery/assets/9987732/3cefe7ff-b89f-45c2-bca3-a20c9f13501e)

closed by #6006 , remind me to fix ga integration after Nuxt3 migration (#2690)
