### ISSUE TITLE
Smart & Simple Assets overview in wallet

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4871]
Thinking out loud that user could see their assets on sidebar, i.e. total count of NFT assets, collections, sales count & amount, and some other things, like flipped amount, it could be done bit ahead till we line up redesign on profile.

Case when user want to click through lot of accounts and check their status?  

<img width="368" alt="image" src="https://user-images.githubusercontent.com/5887929/215741783-fc4ac086-fe67-43c2-9d69-a6c4462cd3e0.png">

**Comment by yangwao** [comment]
from @jkdizajn if we can put incoming offer on your NFT, now probably we don't have it anywhere?

**Comment by yangwao** [comment]
ok, I've heard @exezbcz is working on this 👀

**Comment by yangwao** [comment]
> total count of NFT assets, collections, sales count & amount, and some other things, like flipped amount, it could be done bit ahead till we line up redesign on profile.

This can go to the new portfolio page

**Comment by exezbcz** [comment]
done with profile + wallet merge, continue to: 
- #5820
