### ISSUE TITLE
Add shop link to landing navbar and footer

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#4875]
### Is your feature request related to a problem?

We need to input https://shop.kodadot.xyz into our navbar and footer

Positioning might be adjusted, but it needs to be added there.

### Describe the solution you would like

/

### Describe alternatives you have considered

/

### Screenshots

/

### Are there opened related issues?

/

**Comment by exezbcz** [comment]
I think it would better only in footer, in navbar there are only app related links?

**Comment by cryptodamsky** [comment]
> I think it would better only in footer, in navbar there are only app related links?
> 
> edit: once the article is published, maybe pin it first among other articles on the landing page.

I’ve seen a lot of instances where this is linked in navbar as swag is one of our domains. But will let somebody else decide this :)

**Comment by yangwao** [comment]
> into our navbar

post link which DEXes has it there?

**Comment by exezbcz** [comment]
hmm, was thinking more about the kodadot section rather than the icon section
![image](https://user-images.githubusercontent.com/90852205/217290431-2523dbf1-477d-4b57-b4a2-c785d8937d21.png)

**Comment by roiLeo** [comment]
> hmm, was thinking more about the kodadot section rather than the icon section

![Screenshot 2023-02-07 at 16-41-42 KodaDot - NFT Market Explorer](https://user-images.githubusercontent.com/9987732/217291791-57f99cda-6e74-4825-8be4-59718af4287f.png)

Since we have 2 collumn of 4 items I though adding one more would break aesthetic.
lmk where exactly you want this link and what text should be displayed

**Comment by DeluneClaire** [comment]
> > hmm, was thinking more about the kodadot section rather than the icon section
> 
> ![Screenshot 2023-02-07 at 16-41-42 KodaDot - NFT Market Explorer](https://user-images.githubusercontent.com/9987732/217291791-57f99cda-6e74-4825-8be4-59718af4287f.png)
> 
> Since we have 2 collumn of 4 items I though adding one more would break aesthetic. lmk where exactly you want this link and what text should be displayed

Actually, the KodaDot just under the one size looks kind of strange I think... We could just think of some names for the specific sections and add the stuff under it, so it wouldn't look that strange if on one side is more or less.

Maybe two main sections: Marketplace and Resources and under divide the categories?

**Comment by exezbcz** [comment]
> > hmm, was thinking more about the kodadot section rather than the icon section
> 
> ![Screenshot 2023-02-07 at 16-41-42 KodaDot - NFT Market Explorer](https://user-images.githubusercontent.com/9987732/217291791-57f99cda-6e74-4825-8be4-59718af4287f.png)
> 
> Since we have 2 collumn of 4 items I though adding one more would break aesthetic. lmk where exactly you want this link and what text should be displayed

yup, got it, makes perfect sense, what about 3x3? There would be problem with responsivity no?  I don´t think its a big issue to break the aesthetics :D 
![image](https://user-images.githubusercontent.com/90852205/217637677-f9ecbb7c-db4a-45f6-8a6d-30bfbc51d29a.png)

**Comment by roiLeo** [comment]
Sooo 
2 colums 3 row?
what would be the links list?

**Comment by exezbcz** [comment]
> 

3 columns and 3 rows? or would it look weird? 

if yes, 2 columns, one columns with 5 rows and the other one with 4
