### ISSUE TITLE
Create Faucet bot for dripping initial minting costs

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4877]
Right now it's painful if people want to mint on Kusama or Basilisk.

To tackle this, it's would be good to have faucet which would sent you KSM or BSX for first 20 mints 

We can trade amount for user actions
- Twitter follow -- oauth and give us follow @kodadot 
- Discord join to our Discord server 
- Join our Telegram? 

User will authenticate with wallet, sign payload to verify address and faucet will send them money

**Comment by vikiival** [comment]
Current ways to onboard:
- Genart - @JustLuuuu 
- otherwise minting feees are cheap
