### ISSUE TITLE
Upcoming March release

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4884]
Candidates to be in March release 

- https://github.com/kodadot/nft-gallery/issues/4257
- https://github.com/kodadot/nft-gallery/issues/4617
- https://github.com/kodadot/nft-gallery/pull/4863
- https://github.com/kodadot/nft-gallery/issues/4444
---
- https://github.com/kodadot/nft-gallery/issues/4474
- https://github.com/kodadot/nft-gallery/issues/4840
- https://github.com/kodadot/nft-gallery/issues/4532
- https://github.com/kodadot/nft-gallery/issues/4830
- https://github.com/kodadot/nft-gallery/issues/4437
- https://github.com/kodadot/nft-gallery/issues/4862

**Comment by yangwao** [comment]
Pushed to production
- https://github.com/kodadot/nft-gallery/pull/5142

**Comment by exezbcz** [comment]
added few things to the explore v0.9 
- #4474

**Comment by vikiival** [comment]
Bigger cards on explore:
- https://github.com/kodadot/nft-gallery/pull/5135

Filter selection is also visible on the top:
- https://github.com/kodadot/nft-gallery/pull/5127

Wallet shows USD price of Basilisk
- https://github.com/kodadot/nft-gallery/pull/5097

New gallery detail has sharing buttons
- https://github.com/kodadot/nft-gallery/pull/5118

Collection has insanely nice hero picture
- https://github.com/kodadot/nft-gallery/pull/5093

Sharing options are also visible for hero component
- https://github.com/kodadot/nft-gallery/pull/5101

Sort by button got new color
- https://github.com/kodadot/nft-gallery/pull/5102

Denver styled Waifus
- https://github.com/kodadot/nft-gallery/pull/5121

New menubar for collection detail
- https://github.com/kodadot/nft-gallery/pull/5106

**Comment by vikiival** [comment]
cc @yangwao, @DeluneClaire
