### ISSUE TITLE
Not loading NFTs/collections, why is this keeping happening?

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4885]
### What happened?

I wanted to browse collections and NFTs, but some of them did not load. I tried RMRK, BSX, beta.kodadot, incognito mode. I also deleted the cache and cookies.

It keeps happening very randomly. Sometimes it loads them, sometimes not. Sometimes I can see 90% of NFTs, and it will not load 1-2 pieces. Sometimes it works 100%. 

This is not happening for the first time; a few artists in the past also pointed it out to me. From a user perspective, it is very annoying, and frustrating, and it makes our platform look very buggy. 
Can we come up with a permanent solution for this?

<img width="1420" alt="Screenshot 2023-02-01 at 12 34 24" src="https://user-images.githubusercontent.com/104380776/216034357-ed872d2b-b698-491f-915c-940e7046528a.png">
<img width="1440" alt="Screenshot 2023-02-01 at 12 38 46" src="https://user-images.githubusercontent.com/104380776/216034383-0d53459a-0c19-4b15-9648-c5260e6d2018.png">
<img width="1439" alt="Screenshot 2023-02-01 at 12 37 25" src="https://user-images.githubusercontent.com/104380776/216034388-e02f3879-507f-4713-9b54-f456746f88c2.png">
<img width="1417" alt="Screenshot 2023-02-01 at 12 37 07" src="https://user-images.githubusercontent.com/104380776/216034390-6d7496e0-09be-4ec7-a589-90f57a4cd161.png">

Waiting helps a little (only sometimes) but still, this is after 5 min of waiting:
<img width="1436" alt="Screenshot 2023-02-01 at 12 58 10" src="https://user-images.githubusercontent.com/104380776/216036528-fb57ec0a-1f6a-4926-8f1b-92d629a08bf2.png">

### Please reproduce in steps

Browse collections, open a collection... try also opening NFTs that are not loaded

### Expected Behavior

- Loading everything as it should
- In case Im doing something wrong or I need to do something (delete cookies?), get a notification that will tell me what to do. 
- In case there is an issue with the platform get a notification: "We are sorry if some of our NFTs are not loading properly......"

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Are you logged in?

None

### At which chain did you encounter bug?

Basilisk, Kusama

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
On collections I can see some errors, but pictures loads to me well

![image](https://user-images.githubusercontent.com/5887929/216038598-b486586c-3873-4e88-ac67-41547ce60b26.png)

on kodadot.xyz at items, it loads yet I still got some errors?

![image](https://user-images.githubusercontent.com/5887929/216038858-e2a1e916-5d52-43eb-aa5e-bf8fcea23746.png)

**Comment by yangwao** [comment]
Found seems this is the error 
- https://github.com/kodadot/nft-gallery/issues/4889

**Comment by yangwao** [comment]
> aw, checking. let me rollback it first

seems service worker was delaying this I guess and yeah it's happening for me as well now.

**Comment by yangwao** [comment]
Chuckles related
- https://github.com/kodadot/workers/pull/29

**Comment by yangwao** [comment]
okay works now, let's invetigate further 
![image](https://user-images.githubusercontent.com/5887929/216051741-79567913-344f-4ac1-bd8d-9ba46ee47ab7.png)

**Comment by JustLuuuu** [comment]
It seems okay now, the last thing that is not loading is this "newest list": Invarch banners
<img width="1448" alt="Screenshot 2023-02-01 at 15 18 44" src="https://user-images.githubusercontent.com/104380776/216068664-731678be-6c0a-49d0-b27e-d355b5d53cd5.png">

**Comment by yangwao** [comment]
> not loading is this "newest list": Invarch banners

yes, that was fix for this moring.. yet instead fixing 1%, that fix broke 100% of kodadot :D 

continue to 
- https://github.com/kodadot/nft-gallery/issues/4872
