### ISSUE TITLE
Explorer - adding more NFTs in a row

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4895]
### Is your feature request related to a problem?

When you click on explore - gallery, it will show you all the minted NFTs but only 3 per row. Would be awesome to have the option to see more than 3 in a row. We have this option when you open a specific collection, but not in a gallery explorer.

### Describe the solution you would like

I often visit other marketplaces and I really enjoy it when I can see more NFTs on the screen without excessive scrolling.
For example this Tezos marketplace: 
<img width="1448" alt="Screenshot 2023-02-02 at 10 09 17" src="https://user-images.githubusercontent.com/104380776/216282286-974264f6-6fe3-4807-8b49-4b9fd9f52884.png">
<img width="1442" alt="Screenshot 2023-02-02 at 10 14 51" src="https://user-images.githubusercontent.com/104380776/216282347-bdc9abb7-06ae-4812-9d38-d4c0546f35ec.png">

Our gallery explorer: 
<img width="1435" alt="Screenshot 2023-02-02 at 10 18 45" src="https://user-images.githubusercontent.com/104380776/216282832-31b74481-6494-4dd6-b63c-0de0a8ba2884.png">

### Describe alternatives you have considered

Just add "small display" to the gallery. I would also make this option as a "primary" or "default" just because it looks better.

**Comment by yangwao** [comment]
> duplicate
> 
> * [redesign: dynamic change grid card size #4444](https://github.com/kodadot/nft-gallery/issues/4444)

yes, plus thinking we could have full width mode

**Comment by roiLeo** [comment]
continue in #5164
