### ISSUE TITLE
Verified artists 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4896]
### Is your feature request related to a problem?

There are a lot of NFT collections on KodaDot that have only one piece of NFT or are sketchy or just random. We should definitely think about how to filter these collections and accounts from real, promising artists. 

One of the options is to have **verified accounts**. In this case, we would have to consider how to verify them (what criteria we should set). We can also do it internally or externally (maybe Kilt protocol - they offered similar services). If needed, I can do my research and check other marketplaces to see how they set these conditions.

### Describe the solution you would like

- Option to verify artists
- Have verified badge
- Option to filter collections, the gallery, and profiles by verified status. 

### Describe alternatives you have considered

Delete weird collections? (not an ideal solution because minting is for everyone). But still, it looks ugly, NFTs and collections like this (our logo minted..etc.).
<img width="1414" alt="Screenshot 2023-02-02 at 10 40 42" src="https://user-images.githubusercontent.com/104380776/216288629-d2fea3a7-164d-4e08-a95c-b10be7ec1f5f.png">

**Comment by roiLeo** [comment]
related with #2595

**Comment by yangwao** [comment]
We can think of making off-chain worker for this, easy peasy dashboard and someone can could  help us verify these people, making DD and so on. However best I would prefer on-chain, we are doing it for good reputation of content on our platform.

- #4862

**Comment by exezbcz** [comment]
yes! 
![image](https://user-images.githubusercontent.com/90852205/232142169-aa829f2b-31dc-4906-bbcc-15783ff8de18.png)

**Comment by exezbcz** [comment]
Verification page 👀  How hard would that be? The user will request verification. Then it will be displayed like that


![image](https://github.com/kodadot/nft-gallery/assets/90852205/42d2aaf9-55ab-4c63-8717-c36adf38bf43)

**Comment by vikiival** [comment]
@JustLuuuu said I can close
