### ISSUE TITLE
Sort & Search & Toggle

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#49]
Sort
- date
- price of sale
- by count of appreciation 
- type - ebook, text, audiobook
- ~type (image, animation, audio,) - ".mp4", ".gif" in search~

Toggle
- all items | bundles
- LIST, SEND, CONSUME as tags?

~Search~
- ~author~
- ~collection~
- ~name~

**Comment by vikiival** [comment]
Related to #53

**Comment by yangwao** [comment]
#35

**Comment by vikiival** [comment]
Docs: https://docs.mongodb.com/manual/reference/operator/query/

**Comment by yangwao** [comment]
- [ ] Update search input with search string into URL

**Comment by yangwao** [comment]
- [ ] put a search into navbar, as search should be kept contextual all the time for the user's attention (span)

**Comment by abhisar2006** [comment]
HI,

1. We are able to search in "SpotLight".
2. Search Bar is available on the gallery.
3. Sort and filter from #35 is not done yet,
