### ISSUE TITLE
Name is double when someone has identity

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#4905]
Name is double when someone has identity
<img width="122" alt="Screenshot 2023-02-02 at 17 40 45" src="https://user-images.githubusercontent.com/22471030/216386690-84eae3a7-d024-419f-a157-787bdf2b1bcb.png">

_Originally posted by @vikiival in https://github.com/kodadot/nft-gallery/issues/4901#issuecomment-1414040427_

**Comment by Jarsen136** [comment]
emm The wallet name above is off-chain and we could edit the name in the wallet. So it's totally different from the identity IMO. 

Or we would like to merge these two in to one place if they are the same?

**Comment by vikiival** [comment]
cc @exezbcz

**Comment by exezbcz** [comment]
> emm The wallet name above is off-chain and we could edit the name in the wallet. So it's totally different from the identity IMO.
> 
> Or we would like to merge these two in to one place if they are the same?

yup, the bottom is your address, the top is you wallet name in polkadot js. I dont know but i dont name my wallets with my identity :D  Not sure if we should to fix this somehow, I dont think its a big deal?
