### ISSUE TITLE
Explore v0.9 feedback

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#4906]
Here we go again. 

### Sidebar
![image](https://user-images.githubusercontent.com/90852205/216390824-c33caaed-8e47-4e99-a415-5abb1880335d.png)
- we are changing it a bit
   - it does not have borders all around
   - it does not change to bold when its active

make buy now default when you open the explore - user can than close the breadcrumbs
- own filter disabled when user is not connected; maybe we can add tooltip saying: connect your wallet to use this filter? 

### Spacing 
![image](https://user-images.githubusercontent.com/90852205/216391959-38557d77-b87c-4f6f-a7a5-0c8e9c65cdcb.png)
- space between explore +buttons and the line separating content is too large, make it smaller please
![image](https://user-images.githubusercontent.com/90852205/216392243-e88cb146-525a-4173-a7a6-6f82ad9e841c.png)
- gap between side bar and nft cards is too small
- whole spacing is also connected with 
- #4857 

### Connected Issues
- #4444

**Comment by roiLeo** [comment]
![artworks-000528979299-op8qu5-t500x500](https://user-images.githubusercontent.com/9987732/216568007-cf4f4b62-71e1-454a-b425-455aa3e36db9.jpg)


### Checkbox (need to create NeoCheckbox based on [Oruga checkbox](https://oruga.io/components/checkbox.html))
- [ ] 1px solid border
- [ ] remove radius
- [ ] font-weight bold when active

### Filters

- [ ] > make buy now default when you open the explore - user can than close the breadcrumbs
- [x] > own filter disabled when user is not connected

### Spacing
- [x] > space between explore +buttons and the line separating content is too large, make it smaller please
- [x] > gap between side bar and nft cards is too small
(I've increase it a bit)
- [ ] > whole spacing is also connected with [Smaller side margins #4857](https://github.com/kodadot/nft-gallery/issues/4857)
Need to rework [spacing helpers](https://bulma.io/documentation/helpers/spacing-helpers/)

> ### Connected Issues
> 
>     * [redesign: dynamic change grid card size #4444](https://github.com/kodadot/nft-gallery/issues/4444)

**Comment by exezbcz** [comment]
> * [ ]  1px solid border
> * [ ]  remove radius
> * [ ]  font-weight bold when active
> 

- Don't get me wrong about the bold font-weight; we're getting rid of it.
>we are changing it a bit
>it does not have borders all around
>it does not change to bold when its active

the screenshot above shows the side bar in active and nonactive state. We might also remove the hover effect based on the complexity of implementing it.

**Comment by yangwao** [comment]
What's outstanding for feedback?

**Comment by exezbcz** [comment]
> What's outstanding for feedback?

sidebar styling
