### ISSUE TITLE
Teleport integration in action buttons in single click // automatic bridging

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#4917]
What about giving users the choice to buy with one click even if they don't have the amount on the network where the nfts is, but they do have the amount on, say, kusama?

Example: buying nft from bsx - not having ksm on bsx, still option to buy nft from gallery detail without going through the bridging process. 

There would be a modal and somewhat distinct buy button to let you know what would happen.

**Comment by yangwao** [comment]
we chatted back in August to abstract this interaction for users for multicurrency case. 
Can we maybe hijack wallet dialog for this? Where user will contextual swap coins needed to buy, like confirm dialog and then buy?

**Comment by exezbcz** [comment]
continue to: 
- #7643
