### ISSUE TITLE
Recent Paraspell package failing at build

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4925]
Seems like recent ParaSpell build is failing when we bumped to recent one
@​paraspell/sdk	[^0.0.25 -> ^0.0.27](https://renovatebot.com/diffs/npm/@paraspell%2fsdk/0.0.25/0.0.27)

@dudo50 

Logs
https://github.com/kodadot/nft-gallery/actions/runs/4098927747/jobs/7072346868#step:7:17

**Comment by dudo50** [comment]
@yangwao we will look into this asap.

**Comment by dudo50** [comment]
@yangwao in v 0.0.27, we have introduced a change of Polkadot packages into Peer dependencies. This was suggested to us by the Basilisk FE team. Could you install missing dependencies by the following command? This should fix the issue you are having. We will have to document this change in our readme. I will do that today.

`pnpm i  @polkadot/api @polkadot/types @polkadot/api-base @polkadot/apps-config`

**Comment by yangwao** [comment]
Maybe you should make it as breaking change? 0.1.0

You can read more - https://semver.org/

**Comment by dudo50** [comment]
Thanks for the advice, it will be done today.

**Comment by dudo50** [comment]
@yangwao, released as `@paraspell/sdk@1.0.1` now. Last version without peer dependencies is 0.0.25.
