### ISSUE TITLE
Create Cookie Policy

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4928]
> We don't have cookie policy when it should be mandatory

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/issues/4856#issuecomment-1418880986_

**Comment by roiLeo** [comment]
I've heard that you store emails without informing users 😒

**Comment by yangwao** [comment]
> I've heard that you store emails without informing users 😒

in which field? on-chain identity? 

Substack are handled through their ToS I guess.

**Comment by roiLeo** [comment]
> in which field? on-chain identity?
> 
> Substack are handled through their ToS I guess.

AI minting but I think you've changed that recently

**Comment by yangwao** [comment]
let me fix this
