### ISSUE TITLE
Explorer input max min left overs 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4930]
Explorer input max min 
- change the color of icon in dark mode.
-  Let's add a new translation key for it. 
- https://github.com/kodadot/nft-gallery/pull/4924/files/272c608265fc9bddd9f77aa44ac184bd36bce352#diff-243018571f28605fceba0ba9db964d3c1a8b5e9a00152d26f383eb09bd5bd071R39
- https://github.com/kodadot/nft-gallery/pull/4924/files/272c608265fc9bddd9f77aa44ac184bd36bce352#diff-243018571f28605fceba0ba9db964d3c1a8b5e9a00152d26f383eb09bd5bd071R30

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/4924#issuecomment-1419470147_

**Comment by maderi21** [comment]
👋
