### ISSUE TITLE
Adding Merch Shop on the web

### ISSUE THREAD

**Issue by DeluneClaire** [kodadot/nft-gallery#4943]
### Is your feature request related to a problem?

Since we have opened a new merch shop It would be good to have it on the KodaDot web too.

### Describe the solution you would like

I would put it here at the bottom as "Shop" and then it directs you to the shop. 

<img width="408" alt="Snímek obrazovky 2023-02-08 v 10 47 50" src="https://user-images.githubusercontent.com/104791453/217494796-bcb728a3-60cc-45d7-8d7f-8204f79afae4.png">

Here is the link: https://shop.kodadot.xyz/

### Describe alternatives you have considered

I'm not sure if there is needed a design for this or if it can be easily added by code... But should be added there anyway...

**Comment by roiLeo** [comment]
ref #4939 & #4875 (https://github.com/kodadot/nft-gallery/issues/4875#issuecomment-1420988055)

**Comment by DeluneClaire** [comment]
> Yes... I just saw there is already an issue... my bad.
