### ISSUE TITLE
Broken 💔 image size on mobile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#495]
At https://kodadot.xyz/rmrk/detail/8001646-DE9F84C58887199B5F-HUFP-HUNGRY_FOR_PIZZA-0000000000000001

https://user-images.githubusercontent.com/5887929/123040142-8e216900-d3f3-11eb-9291-4b3e2e44b58b.mp4

![Screenshot_2021-06-23-07-20-42-467_com android chrome](https://user-images.githubusercontent.com/5887929/123040152-91b4f000-d3f3-11eb-892e-c520a287719b.jpg)

Ironically, on others pictures it seems fine!

**Comment by roiLeo** [comment]
This happened because an SVG is loaded with a fixed height & width.
SVG are showed in an iframe but :
> If you use an  <iframe> to embed your SVG, setting height and width on the <svg> won’t change the size of the frame; you’ll just get scrollbars inside your iframe if the SVG is too big.

### Possible solution 
replace the svg size with percentage (100%)

**Comment by yangwao** [comment]
> This happened because an SVG is loaded with a fixed height & width.
> SVG are showed in an iframe but :
> 
> > If you use an  <iframe> to embed your SVG, setting height and width on the  won’t change the size of the frame; you’ll just get scrollbars inside your iframe if the SVG is too big.
> 
> ### Possible solution
> replace the svg size with percentage (100%)

Okay, let's try, I can test if it fixes the stuff :)

**Comment by yangwao** [comment]
Seems working 
![image](https://user-images.githubusercontent.com/5887929/124113651-f6afbc00-da6b-11eb-904b-a6330e35628c.png)
