### ISSUE TITLE
Add skeleton when switching through explore sections

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#4957]
The default now is that the "no results found" message is shown. 
![image](https://user-images.githubusercontent.com/90852205/217891911-748ba0e7-da73-4bc8-8edc-b661581174b5.png)
- took a while to take this screenshot
- I think it would be better if there was some sort of preload skeleton like on search

**Comment by exezbcz** [comment]
this would be pretty nice, at least for the general results - when no filter is applied - it's pretty clear that there's going to be an item

**Comment by roiLeo** [comment]
completed
