### ISSUE TITLE
Spotlight only collections worth of spotlighting

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#4959]
### Is your feature request related to a problem?

**Spotlight** on the landing page is currently (I think) spotlighting only new collections as they are minted. This way, we have some ugly collections there. 

<img width="1397" alt="Screenshot 2023-02-09 at 18 49 49" src="https://user-images.githubusercontent.com/104380776/217896920-ee81c653-ff7f-4ed0-85e8-324ec211cb95.png">

### Describe the solution you would like

I would suggest changing them manually. Probably open an issue once in a while where we add links to collections that can be spotlighted. 
- Every time a new collab-collection is out
- Artists with a good art
- New collection (but only pretty ones)
- Benefit for artists who are close to KodaDot
- Ones with higher sales
 

### Describe alternatives you have considered

I think this can be done only manually if you want to avoid having random artwork there. 
Once we have verified users, we can make this spotlight only available for them or something like that.

**Comment by roiLeo** [comment]
Hello!
Code is already implemented for this feature as we currently have a curated list for rmrk chain but not for bsx.
Feel free to drop adress of your favorite collection.

**Comment by JustLuuuu** [comment]
> Hello! Code is already implemented for this feature as we currently have a curated list for rmrk chain but not for bsx. Feel free to drop adress of your favorite collection.

Perfect, I'm not sure how many collections can be spotlighted. Just start from the top. Can you please also change the RMRK ones? They did not change for ages. Thank you very much!

Basilisk:
https://kodadot.xyz/bsx/collection/14022023
https://kodadot.xyz/bsx/collection/2551182625
https://kodadot.xyz/bsx/collection/2608295324
https://kodadot.xyz/bsx/collection/3579963603
https://kodadot.xyz/bsx/collection/945672150
https://kodadot.xyz/bsx/collection/1825819407
https://kodadot.xyz/bsx/collection/1635680444

Kusama/RMRK:
https://kodadot.xyz/rmrk/collection/900D19DC7D3C444E4C-MECHWOM
https://kodadot.xyz/rmrk/collection/4A43156FE23E061C03-SNK
https://kodadot.xyz/rmrk/collection/08C79124CAC59DC643-BOREDBARRO?page=1
https://kodadot.xyz/rmrk/collection/160a6f4320f11acb25-LCKWV?page=1
https://kodadot.xyz/rmrk/collection/800f8a914281765a7d-KITTY
https://kodadot.xyz/rmrk/collection/0a24c7876a892acb79-RADTOADZ?page=1
