### ISSUE TITLE
Subsocial v1 integration - feedback

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#498]
Once initial Subsocial integration is merged, we found few UX-bugs https://github.com/kodadot/nft-gallery/pull/458

- [ ] when commenting on enabled NFT, show other comments
- [x] SUB avatar doesn't load when you have one
- [ ] link to your SUB notifications
- [ ] **somehow** tell the user in KodaDot that has new notifications
- [ ] how to get SUB tokens for commenting

**Comment by yangwao** [comment]
We might disable it till lack of capacity #686

**Comment by yangwao** [comment]
This was quite early, yet we missed right product. Having collection announcements is good way to go

**Comment by siman** [comment]
Hey @yangwao , what was quite early?
