### ISSUE TITLE
Collection and Item names are not showing 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4984]
https://kodadot.xyz/bsx/gallery/14022023-1

![image](https://user-images.githubusercontent.com/5887929/218335096-98d26791-1c45-4f84-9f98-4593c2f5fcef.png)

seems did not help
- https://github.com/kodadot/snek/commit/a6f69d5461aeb968df37ceae946738c37eca845c

seems synced 
https://squiki.kodadot.workers.dev/status/snekk

```json
{
"id": 2510,
"name": "005",
"squidName": "snekk",
"status": "SYNCED",
"syncStatus": {
"totalBlocks": 2748549,
"currentBlock": 2748549
},
"api": {
"status": "AVAILABLE"
},
"deploy": {
"status": "DEPLOYED"
},
"processor": {
"status": "SYNCED",
"syncState": {
"totalBlocks": 2748549,
"currentBlock": 2748549
}
},
"deploymentUrl": "https://squid.subsquid.io/snekk/graphql"
}
```

**Comment by yangwao** [comment]
@vikiival had already fixed it, but If I understand it right, how we use Promise race for resolving, it takes first response even if it's 404, what was this case, which is not so well engineered?

**Comment by roiLeo** [comment]
Didn't work for me on `/snek/gallery/331660682-7` Null on name, empty description

Do we loose some data on minting?

```graphql
query MyQuery {
  nftEntityById(id: "331660682-7") {
    blockNumber
    createdAt
    meta {
      description
      image
      name
    }
    metadata
    name
  }
}
```
```json
{
  "data": {
    "nftEntityById": {
      "blockNumber": "1707909",
      "createdAt": "2023-02-10T16:43:36.108000Z",
      "meta": null,
      "metadata": "ipfs://ipfs/bafkreibwt5qrwvzo4yw3rh56fik3n4fkylx77xnujp4q4thrzxrbd6es74",
      "name": null
    }
  }
}
```

**Comment by yangwao** [comment]
Probably we have still some weak place somewhere 🥵

**Comment by vikiival** [comment]
> 🦑 Releasing the squid at git@github.com:kodadot/snek.git#2f74fc470963c826c6bc9ce9d19af9bc8e91695c

**Comment by roiLeo** [comment]
Still empty :/

```json
{
  "data": {
    "nftEntityById": {
      "blockNumber": "1707909",
      "createdAt": "2023-02-10T16:43:36.108000Z",
      "meta": {
        "description": "",
        "image": "ipfs://ipfs/bafkreiaw22vk33kdc2ozn4unt772v6ylfzf34vq5i2cdtwgfmvcp2kwuzy",
        "name": ""
      },
      "metadata": "ipfs://ipfs/bafkreibwt5qrwvzo4yw3rh56fik3n4fkylx77xnujp4q4thrzxrbd6es74",
      "name": ""
    }
  }
}
```
I'll try to run indexer on my own to see what's happenning

**Comment by vikiival** [comment]
Which chain sir?

**Comment by roiLeo** [comment]
> Which chain sir?

> /snek/gallery/331660682-7

snek maybe check kodadot/snek#141
