### ISSUE TITLE
Unintuitive minting fee process on BSX / KSM

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/nft-gallery#4995]
### Is your feature request related to a problem?

So i’ve bridged some KSM to BSX so i can pay for fees. We are promoting that the fees are close to 0 or cents, so i imagine 1.62 dollars should be enough to mint a collection.

Apparently, it’s not enough and the UI doesn’t even tell me how much i need, therefore i’m not sure if i should bridge 1 ksm or 5 ksm to the chain which i for example don’t want.

### Describe the solution you would like

I’d like to see details of the mint itself. How much i’m paying for transaction and how much i’m paying to the marketplace as a fee of service. 

It will also help me to find out how many more KSM i need to bridge to the BSX chain.

This is standard on most interfaces working with some currencies and it helps to build transparency

### Describe alternatives you have considered

Even if this was listed somewhere in docs, as an end user i cannot imagine going to docs to find out how much i’ll pay for transaction and mint fees, not speaking of always fluctuating price of the fee asset.

### Screenshots

<img width="558" alt="image" src="https://user-images.githubusercontent.com/92786519/218706289-bf1396fb-98e7-4921-ba24-9343afcda275.png">

**Comment by roiLeo** [comment]
Something wrong with balance as it show 0 KSM, we made a change recently on this file. I'll take a look.
