### ISSUE TITLE
Sales and Hot only shopwing one last sale

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5009]
### What happened?

Last sales: showing only one last art sale. Looks empty here.
<img width="1464" alt="Screenshot 2023-02-14 at 18 47 53" src="https://user-images.githubusercontent.com/104380776/218817959-518689d2-8c35-4863-b66f-0bb653f28566.png">

Same in Hot:
<img width="1451" alt="Screenshot 2023-02-14 at 18 48 17" src="https://user-images.githubusercontent.com/104380776/218818022-c9db4ef9-17ff-409a-b2a0-08cde0e77028.png">

### Please reproduce in steps

Kusama, Stats, Sales + Hot

### Expected Behavior

show at least 10 last sales? 

### Are you logged in?

None

### Screenshots

done

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
Sales page are hidden for now, untill new design
