### ISSUE TITLE
SEO optimizations 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5030]
Right now on searching various terms in connection with KodaDot doesn't yield any results, nor collection or collectible page.

<img width="709" alt="image" src="https://user-images.githubusercontent.com/5887929/219464327-83f16699-9198-4376-bfa7-dcef55fa7cc8.png">

Creating sitemap.xml or better SEO would help us on this I guess?

> kodadot nft collectibles

Give some poor results

**Comment by Gavin-Gong** [comment]
We used SSG mode(`{ssr: false, target: 'static'}`) to generate the website, but there is no any content html fragment or SEO meta tag that defined with `nuxt.config.ts` in the generated html. The behavior is so strange. 

<img width="782" alt="image" src="https://user-images.githubusercontent.com/9414378/224491966-14a9a4e3-0524-42d0-b484-a2d6c2cbcaa8.png">

**Comment by yangwao** [comment]
Closing in favour
- https://github.com/kodadot/ops-internal/issues/366
