### ISSUE TITLE
Bought NFT not updated

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5043]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/90852205/219948018-8143bd9f-15f1-490f-98e2-10efd56a6fa3.png">

nft: 
https://beta.kodadot.xyz/rmrk/gallery/16693671-EC306760418F319267-PCKHU-RPHKQZC--0000000000000003

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/90852205/219948004-16c1ab5e-2ec1-4b69-8378-823bfce63114.png">

transaction: 
https://kusama.subscan.io/extrinsic/16703518-4

When I bought it, the nft is no updating its status. Its more than 30 minutes now

**Comment by roiLeo** [comment]
IMO this is a backend issue as last `BUY` interraction we have is from block 16658871

**Comment by yangwao** [comment]
This was resolved iirc
