### ISSUE TITLE
Visiting rmrk2 collection links directly doesn't work

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5063]
After merging 
- https://github.com/kodadot/nft-gallery/pull/5028

This URL worked on deployment 
- https://deploy-preview-5028--koda-nuxt.netlify.app/rmrk2/collection/90c6619c6b94fcfd34-EVRLOOT_RESOURCES?page=1

but doesn't work on beta?

- https://beta.kodadot.xyz/rmrk2/collection/90c6619c6b94fcfd34-EVRLOOT_RESOURCES?page=1

**Comment by vikiival** [comment]
We have super aggressive cache for vuex-options and for some reason it takes a while

**Comment by yangwao** [comment]
doesn't work in incognito either 🥸

**Comment by vikiival** [comment]
> doesn't work in incognito either 🥸

Sir I advise you to make a short 2000m rowing session. 

TL;DR 

Looks like we broke build by #5028 🧠 

![think-anime](https://user-images.githubusercontent.com/22471030/220281683-44fca252-a803-4132-8627-c52244f37969.gif)

**Comment by vikiival** [comment]
Yup it's there

![Uploading Screenshot 2023-02-21 at 08.55.14.png…]()

**Comment by yangwao** [comment]
Hence I see RMRK2 on landing, I still can't open link above on beta. 
Manually I can click through there.

Any ideas?

**Comment by yangwao** [comment]
yes! seems working, closing,.thank you!
