### ISSUE TITLE
netlify Build failed 

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#5066]
- on pnpm install

```
Lockfile is up to date, resolution step is skipped
 ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '/@polkadot/networks/10.4.1' in pnpm-lock.yaml
```

**Comment by vikiival** [comment]
maybe by #5028 ?

**Comment by roiLeo** [comment]
> maybe by #5028 ?

![FPRVpzPXIBwon9d](https://user-images.githubusercontent.com/9987732/220280616-9d1e8aea-0908-4a3c-bc22-ec0ee2428149.jpg)

**Comment by vikiival** [comment]
Thanks for hotfix @roiLeo ❤️❤️❤️
