### ISSUE TITLE
Sorting by Most supply for rmrk2 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5086]
This should show collections with most items I guess? 

https://beta.kodadot.xyz/rmrk2/explore/collectibles?page=1&sort=supply_DESC

![image](https://user-images.githubusercontent.com/5887929/220437595-7b7ff8df-1e6f-4dad-8749-bda72f2cb272.png)

**Comment by roiLeo** [comment]
Very laggy but wfm 

![Screenshot 2023-02-22 at 14-57-29 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer](https://user-images.githubusercontent.com/9987732/220641508-a136954d-c609-42f2-b0e2-3465177f40bb.png)

might be a worker issue? 

throws some IPFS Err 
```log
{
  "message": "Network Error",
  "name": "AxiosError",
  "code": "ERR_NETWORK",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {
      "FormData": null
    },
    "headers": {
      "Accept": "application/json, text/plain, */*"
    },
    "baseURL": "https://ipfs.io/",
    "withCredentials": false,
    "method": "get",
    "url": "https://image-beta.w.kodadot.xyz/ipfs/bafkreicg7cozrgptdxqffglznb34exb5e6eg5bwcrcpcskguw3y4z7tj6a"
  },
  "request": {},
  "response": {}
}
```

**Comment by yangwao** [comment]
> Very laggy but wfm

would this resolver solve this @vikiival ?

**Comment by vikiival** [comment]
> > Very laggy but wfm
> 
> 
> 
> would this resolver solve this @vikiival ?


It is more metadata issue than data resolver
