### ISSUE TITLE
Deleting collections on Kusama/BSX

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5090]
### Is your feature request related to a problem?

I tested the minting process a few times, and after that, I have in my profile a few collections that I will never use again. Is there any chance we can delete these collections? Is it possible? I cannot see them in my profile but when I create a new collection its there. It doesn't look good, and it's a reminder that something was not working before 😄.
<img width="808" alt="Screenshot 2023-02-22 at 09 48 21" src="https://user-images.githubusercontent.com/104380776/220570788-a934b7ca-7dd1-4418-a17d-9221876fbb29.png">

### Describe the solution you would like

Delete them

### Describe alternatives you have considered

-

**Comment by roiLeo** [comment]
related with #4546 

You should be able to see trash button in collection page for bsx
![Screenshot 2023-02-22 at 10-04-02 Shaders 🔲 KodaDot - NFT Market Explorer](https://user-images.githubusercontent.com/9987732/220572766-08a4aec1-16b7-4e3f-94b3-a668b1aca183.png)

**Comment by JustLuuuu** [comment]
> You should be able to see trash button in collection page for bsx !


yes, but if you have 0 NFTs in the collection, you cannot see the collection page or anywhere in your profile. You will see it only when you are in Create, adding NFTs to collections.

**Comment by roiLeo** [comment]
You're right, meanwhile here's your list:
- https://beta.kodadot.xyz/bsx/collection/128894557
- https://beta.kodadot.xyz/bsx/collection/2347949712
- https://beta.kodadot.xyz/bsx/collection/1586273532
- https://beta.kodadot.xyz/bsx/collection/3666832606
- https://beta.kodadot.xyz/bsx/collection/3471298763
- https://beta.kodadot.xyz/bsx/collection/625743142

**Comment by JustLuuuu** [comment]
> You're right, meanwhile here's your list:

That's so nice from you, thank you, deleted them 🔥

**Comment by roiLeo** [comment]
won't fix bsx
