### ISSUE TITLE
form validation message displayed in wrong locale

### ISSUE THREAD

**Issue by floyd-li** [kodadot/nft-gallery#5119]
Hi guys I use browser with Chinese and the input validation message is displayed in Chinese, I also tries to set diffrent language but it still displayed in Chinese
<img width="1621" alt="capture" src="https://user-images.githubusercontent.com/16473062/221397155-fb8a6b96-31f8-419f-a31e-9b3bf3d6a56d.png">

**Comment by Jarsen136** [comment]
The message is from the HTML5 default browser message, and it follows the language setting on the user's browser.
Related with https://github.com/buefy/buefy/issues/148

I guess we have no plan to fix this for now

**Comment by roiLeo** [comment]
Hey! This is coming from your navigator preferences, if you want validation message in english then you should change your browser language.

closing this for now as won't fix
