### ISSUE TITLE
Remove Edgeware/node-types from vue-api

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#512]
Probably part of vue-api? 
They seem have obsolete node version
![image](https://user-images.githubusercontent.com/5887929/123442960-b963ae00-d5d5-11eb-90ba-9a17036f2796.png)

**Comment by vikiival** [comment]
Yup, can release new version today

**Comment by vikiival** [comment]
Closed in 8ca9b1b26c6a4cf2d0fce7b03914599927d1035c
