### ISSUE TITLE
Artist is unable to burn his NFT from collection

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5125]
### What happened?

One artist approached me with an issue. He wanted to burn some NFTs in his collection. He had an issue only with one NFT. 

He had already burned something from that collection and it worked.

Its this NFT: https://kodadot.xyz/bsx/gallery/2608295324-3

### Please reproduce in steps

After burning, it will just go back to his collection. It's not showing the "burn" activity of that particular NFT in history. No notifications. 

### Expected Behavior

burning

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### At which chain did you encounter bug?

Basilisk

### Screenshots

- none

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
Looks like everything has failed

![Screenshot 2023-04-07 at 12 23 57](https://user-images.githubusercontent.com/22471030/230592806-1e63163b-2ab7-45e3-a194-239773e01aaa.png)

**Comment by vikiival** [comment]
![Screenshot 2023-04-07 at 12 24 31](https://user-images.githubusercontent.com/22471030/230592937-10957762-0aa5-4144-a78d-b41ce910535d.png)

**Comment by JustLuuuu** [comment]
Artist is still unable to burn his NFT

**Comment by roiLeo** [comment]
@JustLuuuu could you ping artist to try again?

**Comment by JustLuuuu** [comment]
> @JustLuuuu could you ping artist to try again?

on canary? beta or production?

**Comment by roiLeo** [comment]
it should be fixed in production (#6106), beta (#6105) and canary (#6058)

**Comment by JustLuuuu** [comment]
The artist was able to burn his NFT thx @roiLeo for your help 🔥
