### ISSUE TITLE
Bought NFT and it charged me twice + it's still on for a sale

### ISSUE THREAD

**Issue by DeluneClaire** [kodadot/nft-gallery#5126]
### What happened?

I have bought an NFT, first it showed misatke and the button for buy was still blue, so i thought maybe some bug and went to buy the NFT again, but it charged me two times + the NFT is still listed and its still available for anyone to buy.

This the [NFT.](https://kodadot.xyz/rmrk/gallery/16693659-EC306760418F319267-PCKHU-RPHKQZC--0000000000000002)

Here are the transactions:
<img width="1193" alt="Snímek obrazovky 2023-02-27 v 13 34 38" src="https://user-images.githubusercontent.com/104791453/221565154-5643a45f-f4da-40bd-9d03-3205bd158630.png">

### Please reproduce in steps

I clicked on buy and confirmed the transaction. Looked like didn't get through so I made it again and it still doesn't show that it is sold + the transaction was made two times.

### Expected Behavior

Even though there is some bug, I think it shouldn't let the user buy one NFT two times + the NFT is still shown as not sold... And expected behavior is that if the user pays for an NFT, then owns the NFT afterward and is not charged two times.

### What browsers are you seeing the problem on?

Desktop Firefox

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### At which chain did you encounter bug?

Kusama

### Screenshots

<img width="798" alt="Snímek obrazovky 2023-02-27 v 13 35 44" src="https://user-images.githubusercontent.com/104791453/221565419-55bdf1ea-ccda-41da-8753-b35b4b789a3a.png">

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustLuuuu** [comment]
Lol, this looks like a serious issue. I can still buy it and I cannot see any "buy" in the Activity.
<img width="1405" alt="Screenshot 2023-02-27 at 13 37 30" src="https://user-images.githubusercontent.com/104380776/221565873-f639eaa0-e0ce-4654-b37d-be7e0df5445b.png">
<img width="558" alt="Screenshot 2023-02-27 at 13 38 31" src="https://user-images.githubusercontent.com/104380776/221565974-dd1c7954-e3b4-48c0-83d2-10d97dc245d1.png">

**Comment by roiLeo** [comment]
Tx looks oki you are indeed the owner. 
We may have a backend issue.
same as #5043 

@vikiival indexer stuck?

**Comment by vikiival** [comment]
https://squiki.kodadot.workers.dev/status/rubick

@roiLeo looks like synced

**Comment by vikiival** [comment]
So what I have observed this issue is related only to this particular collection 

I tested that on my NFT

https://kodadot.xyz/rmrk/gallery/14463286-8CC1B91E899D9BE40E-HYPER-HYPER_REACTIVE_SPIRALS-0000000000000001

And `BUY` works as intended 

My bet is that it is because of `--` in name and buy cannot handle that

**Comment by JustLuuuu** [comment]
this issue is too old to reproduce
