### ISSUE TITLE
Not loading NFTs/ collections

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5128]
### What happened?

I was testing [Denver waifu minting on beta](https://beta.kodadot.xyz/bsx/waifu), and after I minted [my waifu](https://beta.kodadot.xyz/bsx/gallery/26022023-1?page=1) it took it maybe 30 minutes to load:
![photo_2023-02-27 13 49 08](https://user-images.githubusercontent.com/104380776/221568017-14fc0da7-7e19-4530-8d62-692757f9340c.jpeg)

I can see it now, but that loading time is not normal.

### Please reproduce in steps

-

### Expected Behavior

load faster

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

None

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustLuuuu** [comment]
Oh, I can also see that [this collection is not loading properly](https://beta.kodadot.xyz/rmrk/collection/64F5867915CADA7250-UNSEEN); its on Kusama. It was minted more than 40 minutes ago. NFT in it is visible but not the collection picture.
<img width="779" alt="Screenshot 2023-02-27 at 13 46 49" src="https://user-images.githubusercontent.com/104380776/221568761-17c27efd-c5e1-41f3-8e0d-d1a2e87c366e.png">

**Comment by JustLuuuu** [comment]
[another one](https://kodadot.xyz/rmrk/gallery/16820686-64F5867915CADA7250-UNSEEN-GLACIAL_WORLD-0000000000000002) minted 16 minutes ago not loading: 
![Uploading Screenshot 2023-02-27 at 17.02.20.png…]()

**Comment by yangwao** [comment]
I sense it's issue with putting things on NFTStorage instead to directly to R2 ?

<img width="395" alt="image" src="https://user-images.githubusercontent.com/5887929/221697076-1b156481-4ef4-4bf0-b36b-96ffca3e4a61.png">

**Comment by yangwao** [comment]
Clicked on link in waifu minter to land on collection and it failed @vikiival 
https://beta.kodadot.xyz/rmrk/collection/26022023

<img width="655" alt="image" src="https://user-images.githubusercontent.com/5887929/221697163-406d19d0-6ae1-4acc-8726-fb4cf147d85f.png">

**Comment by yangwao** [comment]
yup it fails to fetch image 
https://beta.kodadot.xyz/bsx/gallery/26022023-4


<img width="1316" alt="image" src="https://user-images.githubusercontent.com/5887929/221697882-3e75f048-4e8a-45cb-b19b-39fbdf524311.png">
