### ISSUE TITLE
waifu minter link to collection after mint

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5131]
Clicked on link in waifu minter after render to land on collection and it failed redirect me to rmrk prefix @vikiival 
https://beta.kodadot.xyz/rmrk/collection/26022023

<img width="655" alt="image" src="https://user-images.githubusercontent.com/5887929/221697163-406d19d0-6ae1-4acc-8726-fb4cf147d85f.png">

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/5128#issuecomment-1447190668_

**Comment by vikiival** [comment]
53304c2243ae1961b7211807c91960601b4a8132
