### ISSUE TITLE
Automatic bridging for Basilisk

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5162]
### Is your feature request related to a problem?

Im not a developer, so I'm unsure if this will be possible. But it would be very cool if people could **buy Basilisk NFTs without manually bridging KSM** through https://app.basilisk.cloud/#/cross-chain or https://apps.karura.network/bridge. Its one extra step and it's hard to explain it to someone without experience and knowledge about the NFTs. 

### Describe the solution you would like

Adding one extra transaction confirmation that will automatically bridge the needed amount of KSM from your wallet to Basilisk and afterward proceed with the payment. 

### Describe alternatives you have considered

add some information about it to platform on visible place

**Comment by yangwao** [comment]
We have https://beta.kodadot.xyz/teleport-bridge yet we chatted w/ @exezbcz month+ ago it could be incorporated to the wallet sidebar to change it **contextually** without leaving same window for the user.

**Comment by exezbcz** [comment]
yup, had somewhat similar idea 
@yangwao here
- #4917
