### ISSUE TITLE
New option: More NFTs on one page

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5164]
### Is your feature request related to a problem?

It would be cool to see more NFTs on one page. I know that something is also cooking with design changes but Im not sure what. So feel free to close this issue if the discussion is already somewhere. 

My idea is to have a third option here that will enable the option to make the NFTs even smaller:
<img width="1408" alt="Screenshot 2023-03-03 at 14 45 19" src="https://user-images.githubusercontent.com/104380776/222736279-4d445fdd-c856-4156-83df-2b93c92e32af.png">

Having this option in profiles (collected NFTs) but also in explorer, collection view, etc. 
I want to be able to change the preview and click between these options. 
Example from Opensea:
<img width="1438" alt="Screenshot 2023-03-03 at 14 49 32" src="https://user-images.githubusercontent.com/104380776/222736692-6c2d8d2c-abd8-474d-83bd-9795ae5ad496.png">

### Describe the solution you would like

- 

### Describe alternatives you have considered

-

**Comment by exezbcz** [comment]
same as 
- #4895 

no? Few changes are already on explore
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/90852205/222756209-92f798f3-2bd9-4148-82f5-4b87746062c5.png">
Is this count appropriate?
Few changes are still not live, so it will be a bit different

**Comment by JustLuuuu** [comment]
> Is this count appropriate? Few changes are still not live, so it will be a bit different

I would still go for the third option of showing maybe 8 in a row. But I will leave the final decision to someone else. I just really liked that open sea view. 😂
