### ISSUE TITLE
RMRK2 Collection names 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5186]
![telegram-cloud-photo-size-4-5778635058477907056-y](https://user-images.githubusercontent.com/90852205/223158184-0b9107bf-206e-4caf-bbbb-fc50efcc614b.jpg)

![telegram-cloud-photo-size-4-5778635058477907057-y](https://user-images.githubusercontent.com/90852205/223158248-0dfbab7a-46ee-4e70-a938-e9e7d7ca5d42.jpg)

Collection name in gallery item detail is showing as an id, even though it has a name.

![image](https://user-images.githubusercontent.com/90852205/223158488-d89d8f6f-4265-4761-bc1d-d3ee63e81693.png)
- hover card has the same issue 

same with nft cards
nft card:
![image](https://user-images.githubusercontent.com/90852205/223158686-af1080fd-6ae3-401c-8d98-1b6d38b14f9d.png)
collection:
![image](https://user-images.githubusercontent.com/90852205/223158746-6a673b26-0e52-4615-9dad-1fb6190fd154.png)

**Comment by zj9495** [comment]
the collection name returned empty text seems to be the problem, any information on how to get the real collection name?
<img width="1829" alt="image" src="https://user-images.githubusercontent.com/17064586/224916021-5e42bf0e-771b-4f2a-8027-7cbfa0488296.png">

**Comment by roiLeo** [comment]
meanwhile this has been fixed on indexer side (maybe https://github.com/kodadot/rubick/commit/55e625d94c4d9c4654f99aea6cd2ba898c78fca0)
