### ISSUE TITLE
Showing RMRK2 latest lists on landing

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5196]
Show latest sales in latest sales strip from RMRK2

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/5887929/223443833-138f6e3c-2f5d-4655-8f98-c3e0747cd246.png">

**Comment by floyd-li** [comment]
raise a PR to for this issue https://github.com/kodadot/nft-gallery/pull/5252
seems subsquid.io service did't response correct result. hope some one can check this.

**Comment by vikiival** [comment]
Closed in d362009beaf3f65c5bcbc561362c9ce2932ecc97

<img width="1792" alt="Screenshot 2023-03-21 at 12 16 17" src="https://user-images.githubusercontent.com/22471030/226590380-82289e36-c83c-4749-b41d-b4dff932c951.png">


<img width="1255" alt="Screenshot 2023-03-21 at 12 15 17" src="https://user-images.githubusercontent.com/22471030/226590410-0e146a03-fa60-47a8-a934-4675faf99cfd.png">

**Comment by yangwao** [comment]
@vikiival can you post screenshot from landing it's working?

**Comment by vikiival** [comment]
Made hard reset at **15:42**
