### ISSUE TITLE
Spotlight collections for landing for RMRK2

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5198]
Name down RMRK2 collections we would like to spotlight 
hint - https://singular.app/rankings/kusama for all time high sales?

I guess this best suite for @JustLuuuu to name cool ones 😎

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/5887929/223481937-63425dc5-c876-41f1-bffc-67ad27bcb7d6.png">

**Comment by floyd-li** [comment]
just made query `collectionLastList` and it returns empty result at https://squid.subsquid.io/rubick/v/009-rc0/graphql, while it's okay at https://squid.subsquid.io/rubick/graphql

seems the `name` of `collectionEntities` is empty so the `name_not_eq: ""` condition filtered them. can someone check it?
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/16473062/224763172-edce1b3b-9216-4029-994e-c562a3ee8e0d.png">

**Comment by yangwao** [comment]
> empty result at [squid.subsquid.io/rubick/v/009-rc0/graphql](https://squid.subsquid.io/rubick/v/009-rc0/graphql),

meanwhile new URL is 
> https://squid.subsquid.io/marck/graphql

**Comment by yangwao** [comment]
we can reuse some from 

- #5384

**Comment by exezbcz** [comment]
yeah, this would be nice. 

There lets pick random 15 collection from this 

[beta.kodadot.xyz/rmrk2/collection/be15890524c6e9b359-WIZARD?page=1](https://beta.kodadot.xyz/rmrk2/collection/be15890524c6e9b359-WIZARD?page=1)
[beta.kodadot.xyz/rmrk2/collection/66241b171becfd500e-EGG?page=1](https://beta.kodadot.xyz/rmrk2/collection/66241b171becfd500e-EGG?page=1)
[beta.kodadot.xyz/rmrk2/collection/342f12106eab6d904c-YOUDLE](https://beta.kodadot.xyz/rmrk2/collection/342f12106eab6d904c-YOUDLE)
[beta.kodadot.xyz/rmrk2/collection/3e6f301b0a0b1a0e4e-MRWH?page=1](https://beta.kodadot.xyz/rmrk2/collection/3e6f301b0a0b1a0e4e-MRWH?page=1)
[beta.kodadot.xyz/rmrk2/collection/8ac9852f42a86a395d-8GDSY?page=1](https://beta.kodadot.xyz/rmrk2/collection/8ac9852f42a86a395d-8GDSY?page=1)
[beta.kodadot.xyz/rmrk2/collection/72559667d353e6dc0d-HUBIM?page=1](https://beta.kodadot.xyz/rmrk2/collection/72559667d353e6dc0d-HUBIM?page=1)
[beta.kodadot.xyz/rmrk2/collection/7a147cba01afccbf17-GA](https://beta.kodadot.xyz/rmrk2/collection/7a147cba01afccbf17-GA)
[beta.kodadot.xyz/rmrk2/collection/9692fa834afcce2d3e-RNDM?page=1](https://beta.kodadot.xyz/rmrk2/collection/9692fa834afcce2d3e-RNDM?page=1)
[beta.kodadot.xyz/rmrk2/collection/a2a383db29d7601e4b-TONICS/activity](https://beta.kodadot.xyz/rmrk2/collection/a2a383db29d7601e4b-TONICS/activity)
[beta.kodadot.xyz/rmrk2/collection/800f8a914281765a7d-KITTY/activity](https://beta.kodadot.xyz/rmrk2/collection/800f8a914281765a7d-KITTY/activity)
[beta.kodadot.xyz/rmrk2/collection/c210bd52d397099b2c-JPS?page=1](https://beta.kodadot.xyz/rmrk2/collection/c210bd52d397099b2c-JPS?page=1)
[beta.kodadot.xyz/rmrk2/collection/7cf9daa38281a57331-BSS/activity](https://beta.kodadot.xyz/rmrk2/collection/7cf9daa38281a57331-BSS/activity)
[beta.kodadot.xyz/rmrk2/collection/f69287204232615e37-NEP4I/activity](https://beta.kodadot.xyz/rmrk2/collection/f69287204232615e37-NEP4I/activity)
[beta.kodadot.xyz/rmrk2/collection/22708b368d163c8007-KV/activity](https://beta.kodadot.xyz/rmrk2/collection/22708b368d163c8007-KV/activity)
[beta.kodadot.xyz/rmrk2/collection/dac5c7f54029d0e73c-HXAI8/activity](https://beta.kodadot.xyz/rmrk2/collection/dac5c7f54029d0e73c-HXAI8/activity)
[beta.kodadot.xyz/rmrk2/collection/2644199cf3652aaa78-KK01/activity](https://beta.kodadot.xyz/rmrk2/collection/2644199cf3652aaa78-KK01/activity)
[beta.kodadot.xyz/rmrk2/collection/b45943b4edbf6f5c0f-SKYLAB_ARTEMIS_R4VENS/activity](https://beta.kodadot.xyz/rmrk2/collection/b45943b4edbf6f5c0f-SKYLAB_ARTEMIS_R4VENS/activity)
[beta.kodadot.xyz/rmrk2/collection/dac5c7f54029d0e73c-XCHIMPZ/activity](https://beta.kodadot.xyz/rmrk2/collection/dac5c7f54029d0e73c-XCHIMPZ/activity)
[beta.kodadot.xyz/rmrk2/collection/be15890524c6e9b359-TRUSTED/activity](https://beta.kodadot.xyz/rmrk2/collection/be15890524c6e9b359-TRUSTED/activity)


list can be seen here: 
- #5384

**Comment by exezbcz** [comment]
okay, closing in favor of 
- #5910
