### ISSUE TITLE
Store high-resolution image to cf-images

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#5202]
additional notes:
- seems like most of the rmrk2 items use a high-resolution image. it means, it can be heavy for our pages
related issue: https://github.com/kodadot/nft-gallery/issues/2229

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/5192#issuecomment-1459557857_

**Comment by roiLeo** [comment]
Oh! maybe that's why we noticed some slowdowns ref #5086

**Comment by roiLeo** [comment]
IMO, we can try something with nuxt/image (#4426), wdyt?

**Comment by vikiival** [comment]
Hmm, rmrk2 should serve something called thumbnail that should be super tiny, will explore

**Comment by yangwao** [comment]
@preschian https://developers.cloudflare.com/images/cloudflare-images/transform/flexible-variants/ you probably explored this one?

**Comment by preschian** [comment]
closing this. solved and tested in: https://github.com/kodadot/workers/pull/54
