### ISSUE TITLE
migrate prettier to rome

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#5220]
[Rome](https://rome.tools/) is a unified **formatter**/**linter**

### Specs:
- remove prettier files
- migrate config
- update husky cmd
- vscode extension.json

**Comment by floyd-li** [comment]
seems Rome doesn't support `.vue` SFC file for now, do you really want to replace with it?
https://github.com/rome/tools/issues/2572#issue-1230761320

**Comment by roiLeo** [comment]
> seems Rome doesn't support `.vue` SFC file for now, do you really want to replace with it?

Thank you for this information I was not aware of this.
I'll close it for now we may consider this at a later stage.
