### ISSUE TITLE
Custom creators slugs 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#524]
@vikiival had an idea we should offer users some custom slugs so they will populate their profiles easier on their Twitter, Instagrams, what's over.
There is a way we can hijack Subquery for this

> Probably have some mechanism like
> artists could reserve at some short domain, for imaginary k.xyz/deeplogic through making PR to repository some json which will create it for them, as hosting in at static would be best.
In technologic, it could be just redirected page which will forward the client to the destination of the origin artist, this way we can virtualize links for artists.
> DM @yangwao for more information

![image](https://user-images.githubusercontent.com/5887929/112435025-7b3fbf80-8d44-11eb-839b-a588d3f79e1a.png)

**Comment by JustLuuuu** [comment]
@exezbcz  nice , 2021

**Comment by JustLuuuu** [comment]
We will introduce this soon, will open new issue for it, thx wao
