### ISSUE TITLE
Menu bar not closing plus bug

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5243]
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/90852205/224663157-5275a8c6-e6a3-4a93-94be-224246ec1549.png">

- the cross icon is not working as close button 

plus there is weird bug that when you click item again when you are on the items already, the buy now filter disappear
- or when you switch from items to collection and back to items

**Comment by Jarsen136** [comment]
related with #5241 #5244
