### ISSUE TITLE
Minting a collection results in collection name [[ Rare Waifu ]]

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#5266]
in beta - snek
tried to mint a collection named ```Neon 🌟```
result: collection name [[ Rare Waifu ]]

![image](https://user-images.githubusercontent.com/22791238/224949433-e2996dba-4696-4feb-865f-746720763ae4.png)

**Comment by vikiival** [comment]
Can you please provide link to transaction / your account id ?

**Comment by daiagi** [comment]
account:

bXm3fZoQkHNgt74RQfL9o4rbtbH7tSaHZnJAYtipTxR9qNFo4

not sure how to find the transaction

**Comment by roiLeo** [comment]
related kodadot/snek#168

**Comment by vikiival** [comment]
```
🦑 Releasing the squid at git@github.com:kodadot/snek.git#8d816b1e3cb50e7f77bb791d1102fd20672b33cf
◷ You may now detach from the build process by pressing Ctrl + C. The Squid deployment will continue uninterrupted.
◷ The new squid will be available as soon as the deployment is complete.
```
