### ISSUE TITLE
Viki Ross mobile newsletter input 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5282]
![image](https://user-images.githubusercontent.com/90852205/225623249-4f3a36bd-3f87-4294-add6-56769d5a01ae.png)

Cc @exezbcz wdyt

_Originally posted by @vikiival in https://github.com/kodadot/nft-gallery/issues/5281#issuecomment-1471668924_
            

so we will put the subscribe button to the second row but it will be still one container (top and bottom part connected

**Comment by vikiival** [comment]
@roiLeo approves

![225587083-e375d91d-b4df-4cf7-b75e-6baa68051290](https://user-images.githubusercontent.com/22471030/225626949-f978c568-c300-4165-a433-6a968de88e14.jpg)

**Comment by roiLeo** [comment]
![bob](https://user-images.githubusercontent.com/9987732/225628645-3b274fea-34b8-44cc-883b-862504b7b614.jpg)
