### ISSUE TITLE
Collection edit UI

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5286]
we will have a new ui for editing/customizing collection for owners - mainly because introducing big banner on collection detail 

# Figma 
- collection detail handoff 
- https://www.figma.com/file/7BWdGiowrvTucpSFLE0kRX/Collection-detail-handoff?node-id=0%3A1&t=cKi2EVd3pPHjX4n4-1

# Main
![image](https://user-images.githubusercontent.com/90852205/225712029-8c90c3f6-66e3-4397-b072-41769e223e8f.png)
- it's quite similar to the sidebar for wallet connect - its only sharing the style but position is in the middle of a screen as popup
- Collection owner can get there once he click through more options and then select "edit collection" 
![image](https://user-images.githubusercontent.com/90852205/225712548-3a3e7836-72f1-4444-99e8-0ff9bad0b66b.png)

## Icon 
- Owner can choose to change collection logo/icon - the current one would be displayed in solid stroke 
![image](https://user-images.githubusercontent.com/90852205/225713205-fcb0a0ca-a07b-481d-b2d2-d48710ed11d0.png)
- if there is not anything filled, it looks like this:
![image](https://user-images.githubusercontent.com/90852205/225713315-98187839-9dd1-4893-bbb1-d104bb3df42a.png)

## Banner
![image](https://user-images.githubusercontent.com/90852205/225713975-92ddd75b-2bf1-45ee-a026-26093aac8bb1.png)
- you can drop your files into the field or select file. 
- here are the states for hovering over or dragging file over it
![image](https://user-images.githubusercontent.com/90852205/225714251-634f958b-f13c-448e-a34f-3f79505ed24b.png)

- question for you, should we include supported types? If yes, what are they for banner? the main ones png, jpg etc

## Social links
![image](https://user-images.githubusercontent.com/90852205/225715041-893e52ba-f811-4ea3-8b6b-3fa95acd76eb.png)
- option for the owner to link certain links for the collection 
- links that are filled out will be shown on the page among social links buttons - left side
- active state for the input is in the figma as well - its the same as with price input on explore

## Save changes 
- primary button - hover effect to bg color

I think we could maybe expand the options in future - something like name edit etc, but for now I think it works Thank you!

**Comment by roiLeo** [comment]
Wait.. I'm pretty sure it's not possible to edit/customize already minted collection. 
Once it's minted data is "frozen" on chain. (from what I understand on Bsx and Rmrkv1)

**Comment by exezbcz** [comment]
@roiLeo ah okay, and is it possible code it or is it just one of the specifications of those networks? 

I think that for the social links we can store it off chain no? Or at least that is how opensea does it no? 

Correct me if I am wrong 
Thanks!

**Comment by roiLeo** [comment]
> @roiLeo ah okay, and is it possible code it or is it just one of the specifications of those networks?

networks specification that don't enable these features but I may be wrong I've seen it's possible to update some metadata part on eth.

> I think that for the social links we can store it off chain no? Or at least that is how opensea does it no?

Hmm.. alright why not but it has a cost, we will need to maintain external database (off chain)
I don't really like this solution because for me it goes against the chain and data will not persist as before.
I'm still open to discussion if there is really a gain in displaying this data.

**Comment by exezbcz** [comment]
yes, understand. The banner on the collection that has different size than profile pic is why I did this customize ui. And also the social links - but not sure how to store it tho if its not possible to have it onchain for each collection - maybe @vikiival would know?

**Comment by vikiival** [comment]
Can push it to Supabase imo :D or mint is as metadata and push it to chain via `system.remark`

**Comment by vikiival** [comment]
But First we should make ability to upload banner on the collection

**Comment by yangwao** [comment]
- Logo we could put coming soon as it's currently immutable, yet in future people could change it for reason
- For banner, there is two options, on-chain, mint it while at creating collection, set it into stone, yet if someone want to mint 1k collection, it will be 1001. Off-chain, it's probably best if we store one more pic on r2, yet we don't know for example if pictures are still used after change (or we will find good way to figure out)
- I would add instagram field for social links

**Comment by vikiival** [comment]
> store one more pic on r2

You still need some way how to make refference for the picture 😇

**Comment by exezbcz** [comment]
updated 
![image](https://user-images.githubusercontent.com/90852205/226389086-0cadf3c9-fef9-442d-a3de-33c9e37223dd.png)

**Comment by yangwao** [comment]
> You still need some way how to make refference for the picture 😇

yeah, I was thinking for some off-chain config.json for collections till we will be putting it on-chain

**Comment by yangwao** [comment]
Time for some flex.
Would be nice if we can have single service for fandoms as well if possible, wyt?

**Comment by roiLeo** [comment]
> Time for some flex. Would be nice if we can have single service for fandoms as well if possible, wyt?

we should try to keep it on chain, maybe in Identity pallet

**Comment by yangwao** [comment]
> we should try to keep it on chain

what's pro being on-chain for this?

Identity pallet has lot of limitations iirc.

**Comment by roiLeo** [comment]
> what's pro being on-chain for this?

- can be reused across plateform (singular, fandom, kodadot etc..)
- can be fetched/updated through rpc calls
- new project can build on top of that

> Identity pallet has lot of limitations iirc.

Yes, unfortunately. 
Imo we should first focus on #2329, and try to implement the rest something like an external db (but it would need secret keys, limit api usage...)

**Comment by yangwao** [comment]
> * can be reused across plateform (singular, fandom, kodadot etc..)

if it will be HTTP endpoint, how it differs? 

> try to implement the rest something like an external db (but it would need secret keys, limit api usage...)

I prefer off-chain first, quick iterations and then we can figure out on-chain, don't want to repeat dumb mistakes ala carte RMRK team 😎

**Comment by exezbcz** [comment]
Are any ui changes needed?

**Comment by yangwao** [comment]
> CORS, domain validation, server maintenance

API keys?

**Comment by vikiival** [comment]
Rmrk v1 and v2 wont allow this. 
Basilisk neither. 
On-chain metadata mutation works only for Statemine

**Comment by roiLeo** [comment]
> Rmrk v2 wont allow this. 

ain't it the goal of "Lego Nft"? or "multi-asset NFT"?

Or another way, would it be possible to update ipfs metadata file?

**Comment by vikiival** [comment]
>  would it be possible to update ipfs metadata file?

Except `Statemine` it is not possible to update collection metadata

**Comment by roiLeo** [comment]
> You can't edit a file once it's on IPFS.

Okay that what I was looking from [ipfs discuss](https://discuss.ipfs.tech/t/how-can-i-delete-or-edit-file/5107)
