### ISSUE TITLE
Changing royalty settings

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#5288]
### Is your feature request related to a problem?

In case I decide in the future to change my licence fees, it is not possible...

### Describe the solution you would like

When I create a new NFT, I can assign a specific address (or myself) to pay royalties. I would be very happy if this feature could be changed after minting. 

### Describe alternatives you have considered

If I decided to support a friendly project by giving a certain percentage of the sales. 
I don't know if this is technically possible and if it is fair, I understand that speculations could arise with this. 
There could be a stipulation that only the original owner of NFT can change the royalty owner and only until someone buys NFT, then the change would never be possible.

**Comment by exezbcz** [comment]
yes, I think if it is possible we can integrate it into #5286 and turn it into page instead of pop up

**Comment by roiLeo** [comment]
continue to assethub royalty
