### ISSUE TITLE
Why did you choose to build on Kusama/Polkadot and not Ethereum?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#529]
This is a super frequent question as probably the most expensive of NFTs are happening on Ethereum.

Reasoning
We choose Kusama/Polkadot because it's using Substrate, which is a framework for building upgradeable, modular and efficient blockchains. Generally, we are building on Substrate, because we will benefit from shared security, interoperability scalability and strong economy security. We believe that costs for actions at Ethereum may be high in future and its current PoW is not environmentally friendly. We believe in network effects of Kusama/Polkadot effects from other parachains. A rich ecosystem of runtime and pallets https://substrate.dev/awesome-substrate/ which offer long-term composability from the various teams. We inherit properties from https://wiki.polkadot.network/docs/learn-comparisons/.
You can learn here why Substrate is awesome https://www.parity.io/blog/what-is-substrate/

Ref https://www.parity.io/blog/what-is-substrate/

**Comment by yangwao** [comment]
@archnomics  Let's make PR to the faq and add it to another faq 
https://github.com/kodadot/nft-gallery/blob/main/src/locales/en.json

**Comment by cryptodamsky** [comment]
Question added to FAQ on the main page and  FAQ in ![docs](https://docs.kodadot.xyz/FAQ.html).

Closing

- #1604

**Comment by yangwao** [comment]
Can you link exactly where it's mentioned in FAQ? As I don't see it

**Comment by yangwao** [comment]
ah got it https://kodadot.xyz/rmrk/faq#Why-did-you-choose-to-build-on-Kusama/Polkadot-and-not-Ethereum?
