### ISSUE TITLE
Cannot access beta.kodadot.xyz

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5291]
![image](https://user-images.githubusercontent.com/90852205/225896704-644e497d-89b4-4c50-9db8-75558fe184ba.png)

**Comment by yangwao** [comment]
lol someone merged something wrong and won't properly tested, logs look ok

![image](https://user-images.githubusercontent.com/5887929/225897204-740a0c7c-eec7-4b38-921e-dc8eb22a15e1.png)

**Comment by yangwao** [comment]
https://64143e062470790007bda86d--koda-nuxt.netlify.app/ 

this one works merged by https://github.com/kodadot/nft-gallery/commit/19f8df386c7b0509169e726bd5dc65e2daf15ef2

later one doesn't, which I don't see reason it's doesn't builds.. 
- https://github.com/kodadot/nft-gallery/commit/9c5963226fe8ccdc783820db1412c9e658b3a5a9

**Comment by yangwao** [comment]
Suspect some Netlify glitch as #5290 builts well and works https://deploy-preview-5290--koda-nuxt.netlify.app/

![image](https://user-images.githubusercontent.com/5887929/225899085-e4d29fab-87e7-4003-878c-3723a36f6f9b.png)

**Comment by yangwao** [comment]
![image](https://user-images.githubusercontent.com/5887929/225899476-d974ec4f-143e-47c0-9504-bf8d8671fc8c.png)

let's watch logs if it's builts and try in 5m https://app.netlify.com/sites/koda-nuxt/deploys/6414573299990f0a9daabd01

**Comment by yangwao** [comment]
Might be suspect on generate 👀

https://app.netlify.com/sites/koda-nuxt/deploys/6414573299990f0a9daabd01#L622

Um, it's working 

![image](https://user-images.githubusercontent.com/5887929/225900477-965dcf5f-f02c-4ff2-a7a3-eaa831c9c02d.png)

**Comment by exezbcz** [comment]
nice :D
