### ISSUE TITLE
Transfer doesn't trigger signer window 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5316]
When I've tried top up payout bot, transfer doesn't work, doesn't trigger signer pop-up 

Seems we should use another RPC node? 

going on this url
- https://beta.kodadot.xyz/transfer/?target=G29NScLSew5zqwmJAPupvJWDCDkpxKUhDnMeVdD2BBcnHar&usdamount=1000

![image](https://user-images.githubusercontent.com/5887929/226610401-b8b9649b-b8e3-469f-b41a-b90c54315a2b.png)

broke on beta and production seems

**Comment by yangwao** [comment]
now it's tryin to connect to localhost 🤔

![image](https://user-images.githubusercontent.com/5887929/226611595-f54db28b-4564-4abd-837e-01e58c7fc6e9.png)

**Comment by vikiival** [comment]
👋

**Comment by yangwao** [comment]
Seems being stuck indefinitely  
![image](https://user-images.githubusercontent.com/5887929/226716669-a62d8829-2179-4548-a651-4e3bf664e6e3.png)
