### ISSUE TITLE
Show finalised and best block to transfer

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5319]
Seems being stuck indefinitely (3m+ and counting)
No transaction did not go through, no change on subscan

![image](https://user-images.githubusercontent.com/5887929/226716669-a62d8829-2179-4548-a651-4e3bf664e6e3.png)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/5316#issuecomment-1478450102_

**Comment by vikiival** [comment]
Dwelir node is gone

![image](https://user-images.githubusercontent.com/22471030/226724769-74a60e28-1af9-421f-9c8e-ecb5e34d0a9d.png)

**Comment by yangwao** [comment]
We can add finalized / best to transfer. 
As client connects, yet doesn't have finalized blocks, I don't know what's going on, this would help give clue to switch different node.

**Comment by yangwao** [comment]
Or maybe switch to another node if best-finalized is bigger than, let's say 10-30 blocks, usually it's difference of less than 3-5 blocks 

![image](https://user-images.githubusercontent.com/5887929/226937793-b5663995-d455-49e7-b2db-94f663ca676f.png)

- https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.dotters.network%2Fkusama#/explorer

**Comment by yangwao** [comment]
- #5575 
- #5677
