### ISSUE TITLE
Replace vuex-settings to static in code

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#5326]
Seems like we have a ton of the issues that prefixes are heavily cached on the client a lot of people experience issues with cache.

![photo_2023-03-22 19 06 48](https://user-images.githubusercontent.com/22471030/226997702-e6f89d79-d4eb-497e-a1ab-7e524cfcf6f7.jpeg)

Tasks:
- [ ] move `static` package from kodadot/packages here as a new workspace folder
- [ ] where possible (except Settings store - will be separated issue) 

ht/ @DeluneClaire, @yangwao

**Comment by yangwao** [comment]
Hey, on beta I still don't see rmrk2 and on production i don't see TNKR
- #5372 

![telegram-cloud-photo-size-4-5834626949388024482-y](https://user-images.githubusercontent.com/5887929/227720684-fec37f03-b148-4603-85db-0495d9ecba0e.jpg)
