### ISSUE TITLE
Unzip functionality and other leftovers for massmint upload picture

### ISSUE THREAD

**Issue by prachi00** [kodadot/nft-gallery#5328]
should unzip and check contents
maybe use something like https://www.npmjs.com/package/unzipper
@roiLeo  @vikiival  do we have some unzipping capabilities already?

_Originally posted by @daiagi in https://github.com/kodadot/nft-gallery/pull/5300#discussion_r1144189127_

**Comment by roiLeo** [comment]
continue in #5662
