### ISSUE TITLE
High Risk Security Vulnerability

### ISSUE THREAD

**Issue by x676f64** [kodadot/nft-gallery#533]
I am a security researcher who has identified a high risk security vulnerability but do not wish to publish this information publicly. How would you like me to disseminate this information to your team? Do you have a PGP public key that you can share with me? There are other avenues to deliver this information but not sure what y'all are setup for.

**Comment by x676f64** [comment]
I have communicated to the account KodaDot#3588 on the KodaDot NFT Official Discord some details about the vulnerability and am awaiting a response. Before transmitting this information, I verified this user had administrator entitlements on the server and was in fact staff of KodaDot.

Issue is unresolved at this point in time.

**Comment by yangwao** [comment]
Hey, yes we've chatted. 
Detected un-used Textile package which doesn't serve any critical stuff https://github.com/kodadot/nft-gallery/pull/535
Thus our IPFS secrets should be protected behind serverless functions, keen elaborate if you have found something.
Thread https://twitter.com/vikiival/status/1411635424896983041

Thanks for reporting. Feel free to DM me further, we'd be delighted to have someone to help us with security stuff.
