### ISSUE TITLE
Statistics for rmrk2 are empty 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5341]
### What happened?

Stats showing nothing
<img width="1429" alt="Screenshot 2023-03-23 at 13 53 17" src="https://user-images.githubusercontent.com/104380776/227210902-2408aad4-3b58-405b-a6e4-4fcd606819ce.png">
<img width="1429" alt="Screenshot 2023-03-23 at 13 56 13" src="https://user-images.githubusercontent.com/104380776/227211073-bb8e052f-d3ba-421a-8fe9-29a5440bf709.png">
<img width="1448" alt="Screenshot 2023-03-23 at 13 56 23" src="https://user-images.githubusercontent.com/104380776/227211078-71b252cb-257a-4b1b-94b1-95db4f4b0072.png">
<img width="1444" alt="Screenshot 2023-03-23 at 13 56 18" src="https://user-images.githubusercontent.com/104380776/227211083-f14c74ad-8adf-401d-9197-21b11743d966.png">

### Please reproduce in steps

Go to KodaDot—open stats.

### Expected Behavior

see stats

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

No

### Which wallet you are using?

PolkadotJS

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
This would need resolver on rubick I guess
- [kodadot/rubick](https://github.com/kodadot/rubick)

Can we reuse same from rmrk1 ? @vikiival

**Comment by vikiival** [comment]
It is a bug that I am aware of:

- https://github.com/kodadot/rubick/issues/199

**Comment by JustLuuuu** [comment]
rmrk is not our priority
