### ISSUE TITLE
Collections: Sort by - selecting two filters will not load any NFTs

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5342]
### What happened?

Selecting two sorting filters:
- EXPLORE - ITES - working ✅
- EXPLORE - COLLECTIONS - not working ❌

Collections:
Old + recently interacted:
<img width="1453" alt="Screenshot 2023-03-23 at 13 58 36" src="https://user-images.githubusercontent.com/104380776/227211852-6e6eddde-56f9-4f69-86e6-d6c65f0c7bbb.png">

New+ Unpopular
<img width="1453" alt="Screenshot 2023-03-23 at 13 58 36" src="https://user-images.githubusercontent.com/104380776/227212048-8f155d33-c087-491a-8fa0-f4a640e2d40f.png">

Most Supply + New
<img width="1436" alt="Screenshot 2023-03-23 at 14 00 31" src="https://user-images.githubusercontent.com/104380776/227212121-e1d1e152-8c1f-4047-9036-de888cd22542.png">

and more......

### Please reproduce in steps

Explore - collections

### Expected Behavior

sort things

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

No

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
ref #5086

**Comment by JustLuuuu** [comment]
works now
