### ISSUE TITLE
top collections on landing are missing for rmrk2

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5343]
### What happened?

Go to https://beta.kodadot.xyz/rmrk2 - main page. Top collections are missing
<img width="1458" alt="Screenshot 2023-03-23 at 14 05 05" src="https://user-images.githubusercontent.com/104380776/227213244-ba072b42-ee08-469d-a958-7697e33784dd.png">

### Please reproduce in steps

Go to https://beta.kodadot.xyz/rmrk2 - main page. Top collections are missing

### Expected Behavior

show top collections

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

None

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
This would need resolver on rubick I guess
- https://github.com/kodadot/rubick

Can we reuse same from rmrk1 ? @vikiival

**Comment by vikiival** [comment]
> This would need resolver on rubick I guess
> 
> - https://github.com/kodadot/rubick
> 
> 
> 
> Can we reuse same from rmrk1 ? @vikiival 

Man the code is the litteraly same 👀👀👀👀
Except disanled cache.

**Comment by roiLeo** [comment]
> Man the code is the litteraly same 👀👀👀👀 Except disanled cache.

Would it be good if we reuse same resolver but withtout cache system? or it will increase server resources?

**Comment by vikiival** [comment]
> > Man the code is the litteraly same 👀👀👀👀 Except disanled cache.
> 
> 
> 
> Would it be good if we reuse same resolver but withtout cache system? or it will increase server resources?
> 
> 

Thanks to extended data system i think its time to extend cachce system
