### ISSUE TITLE
Create collection fees in BSX instead of KSM

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#5344]
is this expected that fees will be in BSX instead of KSM?

currently e2e test error because of this

<img width="1624" alt="Screenshot 2023-03-23 at 20 38 42" src="https://user-images.githubusercontent.com/734428/227221560-b67a1032-5a3e-43be-b451-0b5ee65d6cc5.png">

**Comment by roiLeo** [comment]
might be related with #5305

**Comment by roiLeo** [comment]
can't we just skip this test until we find a solution?
