### ISSUE TITLE
Can’t click on footer links on kodadot.xyz

### ISSUE THREAD

**Issue by helloitsdamsky** [kodadot/nft-gallery#5354]
### What happened?

I know it’s working on beta, however links in  footer on main site kodadot.xyz are not clickable. Let’s fix this please. 

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Desktop Chrome

### Are you logged in?

None

### Screenshots

![image](https://user-images.githubusercontent.com/92786519/227528013-2f31c314-c76e-4810-be15-19cdaab20c26.png)

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
It will be fixed in next release

**Comment by helloitsdamsky** [comment]
> It will be fixed in next release

Yes, yet fixes like this are super important for people who want to get new information and it’s been like this for how long, 2, 3 weeks? That’s quite unacceptable. Several ppl messaged me about this

**Comment by yangwao** [comment]
> it’s been like this for how long, 2, 3 weeks?

my bet since last release, maybe more 

- #5233

**Comment by vikiival** [comment]
> > it’s been like this for how long, 2, 3 weeks?
> 
> 
> 
> my bet since last release, maybe more 
> 
> 
> 
> - #5233 

Last release was merged 9 days ago 😇
