### ISSUE TITLE
Cannot return null for non-nullable field 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5367]
![image](https://user-images.githubusercontent.com/90852205/227706765-7aa57fe6-497b-4a0a-a440-988c3e56a9cb.png)
![image](https://user-images.githubusercontent.com/90852205/227706828-6d4a8fd4-685a-4546-ab15-7c2cf5b2657b.png)
- connected wallet

**Comment by roiLeo** [comment]
maight be indexer issue at that time
