### ISSUE TITLE
Identities not showing up on production

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5375]
https://kodadot.xyz/bsx/gallery/1299595206-1

![image](https://user-images.githubusercontent.com/5887929/227722327-2ef251e4-fe63-47e1-808d-fdfd481be24b.png)

https://beta.kodadot.xyz/bsx/gallery/1299595206-1

![image](https://user-images.githubusercontent.com/5887929/227722335-9e61e2cf-3319-4c2e-92e1-02b566fbe4ab.png)

well, it was push recently from beta to prod, so I would say version should be 1:1

maybe related
- #5373

**Comment by roiLeo** [comment]
Have you set your identity on bsx chain?

Mine looks like this
**BSX** => `/bsx/u/bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW`

![Screenshot 2023-08-09 at 16-34-57 NFT Artist Profile on KodaDot KodaDot - NFT Market Explorer](https://github.com/kodadot/nft-gallery/assets/9987732/1ee5ed9c-c3f3-45ab-8917-f060ae16a1b9)

**SNEK** => `/snek/u/bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW`

![Screenshot 2023-08-09 at 16-35-25 NFT Artist Profile on KodaDot KodaDot - NFT Market Explorer](https://github.com/kodadot/nft-gallery/assets/9987732/6a6d0a0e-c925-47a9-9aed-c5fd28e1f29f)

**Comment by vikiival** [comment]
Identities no longer present on KodaDot
