### ISSUE TITLE
Show all offers happend on item

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5379]
We found w/ @exezbcz that we are showing limited amount of offers that happened on item

https://kodadot.xyz/bsx/gallery/1299595206-1

![image](https://user-images.githubusercontent.com/5887929/227723858-63f385fe-a8db-4e19-885d-7ca0d1e75015.png)

![image](https://user-images.githubusercontent.com/5887929/227723915-f5a6ef3d-14d5-4d01-a6cd-a5e18f3d7dc2.png)

Also I guess we could show ACCEPTED OFFER instead of BUY it was like that?

**Comment by prachi00** [comment]
@yangwao I dont understand this issue, for this nft, the query seems to return 3 results only
![Screen Shot 2023-03-26 at 4 06 08 PM](https://user-images.githubusercontent.com/39299315/227810451-898bb922-830e-4f73-b1e2-ec9e12e569cc.png)

**Comment by prachi00** [comment]
> @yangwao I dont understand this issue, for this nft, the query seems to return 3 results only ![Screen Shot 2023-03-26 at 4 06 08 PM](https://user-images.githubusercontent.com/39299315/227810451-898bb922-830e-4f73-b1e2-ec9e12e569cc.png)

![Screen Shot 2023-03-26 at 4 06 24 PM](https://user-images.githubusercontent.com/39299315/227810464-96eb15b8-c01e-403d-9960-63f54e08b8f2.png)

**Comment by exezbcz** [comment]
@prachi00 More events happened than this.
