### ISSUE TITLE
Errors appeared

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5387]
### What happened?

Our artist ambassador's first experience after opening KodaDot. He is not sure what happened. 
![photo_2023-03-26 16 54 41](https://user-images.githubusercontent.com/104380776/227784199-380b18a0-2119-48c2-9ce8-fe15971d172c.jpeg)

### Please reproduce in steps

Visiting KodaDot - not logged in

### Expected Behavior

Not showing errors

### Are you logged in?

None

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Edit**: He was just refreshing the page. Also, he is asking what happened. If someone can explain to me why this happened, it would be cool, because I'm not sure what to answer

**Comment by yangwao** [comment]
Looks like indexer issue to me happening on bsx

cc @vikiival 
![image](https://user-images.githubusercontent.com/5887929/227922508-e8794dbc-3fa7-421c-8682-fe3287f9d04f.png)

**Comment by vikiival** [comment]
> Looks like indexer issue to me happening on bsx

BSX is a default indexer

All indexers (except rmrk2) does not show any output 

@JustLuuuu can you provide please more information? 
Was it prod or beta ? 

I see no errors in chrome/safari/firefox, I also tried incognito.

**Comment by vikiival** [comment]
> Looks like indexer issue to me happening on bsx

BSX is a default indexer

All indexers (except rmrk2) does not show any output 

@JustLuuuu can you provide please more information? 
Was it prod or beta ? 

I see no errors in chrome/safari/firefox, I also tried incognito.

**Comment by JustLuuuu** [comment]
> > Looks like indexer issue to me happening on bsx
> 
> BSX is a default indexer
> 
> All indexers (except rmrk2) does not show any output
> 
> @JustLuuuu can you provide please more information? Was it prod or beta ?
> 
> I see no errors in chrome/safari/firefox, I also tried incognito.

It was on prod. Artist just refreshed the page. I don't have more info from him. I can tell him to give me more info next time.

**Comment by roiLeo** [comment]
closed by #5402
