### ISSUE TITLE
Do not throw errors on Landing page

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#5401]
### What happened?

From idea that appeared in 

- #5387

It would be nice to remove this toast from landing page.
Because it breaks the first impression.

### Please reproduce in steps

~ 

### Expected Behavior

- Remove error toast from landing 
- Log it into console
- push error into sentry

### Screenshots

![227784199-380b18a0-2119-48c2-9ce8-fe15971d172c](https://user-images.githubusercontent.com/22471030/228248641-92ec0d8c-2abd-43c6-959e-ff8c623ac1a1.jpeg)

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
related with #5402

**Comment by vikiival** [comment]
Closing in favour of https://github.com/kodadot/nft-gallery/issues/5402
