### ISSUE TITLE
Hide error message for user

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5402]
I'd like to avoid visual error messages for user as it produces negative sentiment for user and rather redirect to catch it to sentry.

We've got numerous reports on this, even users can't do nothing about it.

![image](https://user-images.githubusercontent.com/5887929/228248324-a835c5c3-7a7e-4b2a-a76a-62b9a004c56d.png)

**Comment by Jarsen136** [comment]
👋
