### ISSUE TITLE
Slow loading rmrk2 on explorer 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5411]
Sometimes takes up to 30 seconds to load first pics, is it because indexer still crunching? 

![telegram-cloud-photo-size-4-5843660438137584385-y](https://user-images.githubusercontent.com/5887929/228358513-24bc1b9f-45ac-4e5f-bca8-39b1d140a7f1.jpg)

**Comment by yangwao** [comment]
Might be slightly improved
- #5425 

but thing is we have FAT QUERY on explorer right now, any idea how we can improve first load impression for user?

**Comment by JustLuuuu** [comment]
rmrk2 is not a priority atm
