### ISSUE TITLE
Improve Latest Sales/Newest List loading time

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#5414]
one of the queries can take 12s to return the data. this screenshot is from rmrk2. make it synchronous

maybe feasible on FE side?

<img width="547" alt="Screenshot 2023-03-29 at 13 40 46" src="https://user-images.githubusercontent.com/734428/228447918-b38a98ec-e8d2-40c4-af63-1f04c8f54829.png">

**Comment by yangwao** [comment]
![image](https://user-images.githubusercontent.com/5887929/228913327-c4d10353-898c-4441-bd23-2a2716cb1ba7.png)

4.92s for https://squid.subsquid.io/marck/graphql is still quite lot hmm 🤔
