### ISSUE TITLE
Resources on lastEvent query for rmrk2

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#5415]
currently lastEvent query on rmrk2 doesn't have `resources` field

https://squid.subsquid.io/rubick/v/009-rc0/graphql

<img width="177" alt="Screenshot 2023-03-29 at 13 45 50" src="https://user-images.githubusercontent.com/734428/228448808-ef087bb1-7e82-408f-8803-a9368fec26a0.png">

**Comment by roiLeo** [comment]
continue in kodadot/rubick#203
