### ISSUE TITLE
new domains deployments for kodadot

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5420]
currently we will have new stuff

- mint.kodadot -> hyper-mint branch where we try not break things for while so we have working stuff 
- alpha.kodadot -> cf-pages? to have consistency probably is good idea for opengraph and others but I would set canary.kodadot to netlify to mitigate some builds or so
- beta.kodadot will move to cf-pages probably.

Happy line
---
- [x] onboarding -> hello.kodadot -> gitbook for easier manuals focused on better onboarding
- [x] https://canary.kodadot.xyz - Netlify `main`
- [x] https://beta.kodadot.xyz - Netlify `beta` 
- [x] fandom.deno.dev -> https://fandom.kodadot.xyz - to demonstrate our first collection with custom store front and upsell kodadot easier

**Comment by vikiival** [comment]
onboarding.kodadot -> hello.kodadot?

**Comment by yangwao** [comment]
uff, cf getting complicated bit 
![image](https://user-images.githubusercontent.com/5887929/228851454-b60a5920-2e17-4fd1-b229-cfe2dd1a6b4d.png)

**Comment by yangwao** [comment]
It's temporary and it's working, we will be breaking more Canary which is still love beloved `main` so nothing changes here 

- `main` - https://canary.kodadotx.xyz 
- `beta` - https://beta.kodadot.xyz 

Flow will be `main` -> `beta` -> `hyper-jpeg`

**Comment by yangwao** [comment]
- https://hello.kodadot.xyz

![image](https://user-images.githubusercontent.com/5887929/229234484-cf270549-27ac-46ed-ae37-a705c505d882.png)

**Comment by yangwao** [comment]
- https://beta.nft-gallery-5ci.pages.dev
- https://main.nft-gallery-5ci.pages.dev
both seems works but 522 
- https://canary-cf.kodadot.xyz
- https://beta-cf.kodadot.xyz

**Comment by yangwao** [comment]
> uff, cf getting complicated bit

well doesn't work

but I've also made surprise

- [x] https;//rmrk2.kodadot.xyz

**Comment by vikiival** [comment]
> > uff, cf getting complicated bit
> 
> 
> 
> well doesn't work
> 
> 
> 
> but I've also made surprise
> 
> 
> 
> - [x] https://rmrk2.kodadot.xyz 
> 
> 

![image](https://user-images.githubusercontent.com/22471030/229346346-dfa60a95-82d4-4977-bc01-28acf08cedd7.png)

**Comment by vikiival** [comment]
> - https://hello.kodadot.xyz
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/5887929/229234484-cf270549-27ac-46ed-ae37-a705c505d882.png)
> 
> 

Love it 😍

**Comment by yangwao** [comment]
> [x] [rmrk2.kodadot.xyz](https://rmrk2.kodadot.xyz)

yup, something wrong with dns & certs 🤔 works now!
![image](https://user-images.githubusercontent.com/5887929/229461593-d115696a-4817-44c2-ac41-ef37270ea2b3.png)

another branch deploys

- [x] - https://main--koda-nuxt.netlify.app/
- [x] - https://beta--koda-beta.netlify.app/

**Comment by yangwao** [comment]
updated netlify deploy from
![image](https://user-images.githubusercontent.com/5887929/229461837-6c0459cd-c39b-4158-9b47-f15441b38dfb.png)
to 
`pnpm run generate:pnpm` as netlify supports it finally!

**Comment by yangwao** [comment]
summary
---

CF deployment
----
[beta.nft-gallery-5ci.pages.dev](https://beta.nft-gallery-5ci.pages.dev/)
[main.nft-gallery-5ci.pages.dev](https://main.nft-gallery-5ci.pages.dev/)

Netlify
---
- [main--koda-nuxt.netlify.app](https://main--koda-nuxt.netlify.app/)
- [beta--koda-beta.netlify.app](https://beta--koda-beta.netlify.app/)

Fandom
---
[fandom.kodadot.xyz](https://fandom.kodadot.xyz/)

Testing
--
- [canary.kodadot.xyz](https://canary.kodadot.xyz/) - Netlify main
- [beta.kodadot.xyz](https://beta.kodadot.xyz/) - Netlify beta
- rmrk2.kodadot.xyz pointing now on `main`

**Comment by yangwao** [comment]
cc
@daiagi

**Comment by roiLeo** [comment]
> ## summary
> ## dev flow is
> 
> `main` -> `beta` -> `production` `canary.k` -> `beta.k` -> `kodadot.xyz`
> ## onboarding materials
> 
>     * https://hello.kodadot.xyz (gitbook)
> 
> 
> ## CF deployment
> 
>     * [beta.nft-gallery-5ci.pages.dev](https://beta.nft-gallery-5ci.pages.dev/)
> 
>     * [main.nft-gallery-5ci.pages.dev](https://main.nft-gallery-5ci.pages.dev/)
> 
> 
> ## Netlify
> 
>     * [main--koda-canary.netlify.app](https://main--koda-canary.netlify.app/)
> 
>     * [beta--koda-beta.netlify.app](https://beta--koda-beta.netlify.app/)
> 
> 
> ## Fandom
> 
>     * [fandom.kodadot.xyz](https://fandom.kodadot.xyz/)
> 
> 
> ## Testing
> 
>     * [canary.kodadot.xyz](https://canary.kodadot.xyz/) - Netlify main
> 
>     * [beta.kodadot.xyz](https://beta.kodadot.xyz/) - Netlify beta
> 
>     * https://rmrk2.kodadot.xyz pointing now on `main`

This need to be somewhere in doc
