### ISSUE TITLE
New social media cards design for collection

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5426]
At Kodadot we've been at the forefront having first these social cards showing price and items. 
I would like to see new overlay for collection

Thing is what we want to show on card? I guess first minted NFT is good start, later it could be banner and PFP of collection, items, owners and total volume, floor is kinda useless info for now.

I think we can show dynamic information based on for
- item
- collection
- user profile (whale,collector,creator)

![telegram-cloud-photo-size-4-5871650392113262247-x](https://user-images.githubusercontent.com/5887929/228660069-38a1cd9c-91b3-4b1e-8f48-b947873d21b3.jpg)

![telegram-cloud-photo-size-4-5842614003715649316-x](https://user-images.githubusercontent.com/5887929/228660093-c2c4e401-9d08-4cdd-9e3b-6ff13b727b6b.jpg)

![telegram-cloud-photo-size-4-5847319007244431576-x](https://user-images.githubusercontent.com/5887929/228660405-e0b27f79-3929-48b9-b316-444c3f4b981b.jpg)

- https://opensea.io/krunker/created
- https://opensea.io/collection/meka-legends-genesis
- https://opensea.io/collection/parallelalpha

**Comment by VladoTheBoi** [comment]
Where exactly are these cards used and can be seen?

**Comment by yangwao** [comment]
> Where exactly are these cards used and can be seen?

in socials, like twitter,FB,telegram,discord fetches preview picture of collection to let user know what's collection about before clicks on it

**Comment by JustLuuuu** [comment]
user profile pic? or user name? what if artist did not set his identity?

**Comment by VladoTheBoi** [comment]
And you mean user profile of the creator?

**Comment by JustLuuuu** [comment]
> And you mean user profile of the creator?

yeah but we don't have profile pic for users yet.

**Comment by yangwao** [comment]
> yeah but we don't have profile pic for users yet.

- #2009

**Comment by yangwao** [comment]
Seems previews are working, let's crack on this one :)

- https://github.com/kodadot/nft-gallery/issues/5567

**Comment by yangwao** [comment]
Meanwhile in other universe 
- https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation
- ht @vikiival

**Comment by vikiival** [comment]
Or quick hacking via workers x [vercel/satori](https://github.com/vercel/satori)

https://og-playground.vercel.app/

**Comment by vikiival** [comment]
Also nuxt version 
https://github.com/harlan-zw/nuxt-og-image/releases/tag/v2.0.0

**Comment by yangwao** [comment]
Yes it's coming

https://twitter.com/steventey/status/1694426190088651140

![image](https://github.com/kodadot/nft-gallery/assets/5887929/71b08718-a2e0-4825-b40f-ae198aad1f5a)

**Comment by vikiival** [comment]
READING: https://vercel.com/guides/displaying-article-headlines-in-social-previews
REPO: https://github.com/steven-tey/og

**Comment by yangwao** [comment]
Seems making it easy going and not to bloat with text will be tricky

![image](https://github.com/kodadot/nft-gallery/assets/5887929/26e43661-d29b-4498-a7d9-8df8ae01347a)

- https://github.com/kodadot/workers/pull/194

**Comment by roiLeo** [comment]
- closed in kodadot/workers#194
