### ISSUE TITLE
Buy celebration notification

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5433]
When user is buying NFTs, will get those toasts.

First screen, when is looking to sign transaction and take bit longer, won't notice background one as signer is there
![image](https://user-images.githubusercontent.com/5887929/228847823-57961e3d-db91-4c46-b279-c6890bc7f034.png)

Background one our design should replace this one if so 
![image](https://user-images.githubusercontent.com/5887929/228847944-f57b085f-1883-4007-b305-69d98d1abcb2.png)

and if possible, make it stay there for while, like 30 seconds and add some [X] if so :)

**Comment by roiLeo** [comment]
Bonus: #1384 [confetti](https://github.com/valgeirb/vue-confetti-explosion)?

**Comment by yangwao** [comment]
> Bonus: #1384 [confetti](https://github.com/valgeirb/vue-confetti-explosion)?

<img src="https://media0.giphy.com/media/gk3R16JhLP8RUka2nD/giphy.gif"/>

I already forget about 1384, that's must bee 8+ yangwao's eras back.

**Comment by yangwao** [comment]
Closing this as someone else will raise it anyway till we fix it 
- #5458
