### ISSUE TITLE
Profile Twitter links not working

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5443]
### What happened?

Hello, one artist shared her new collection on Twitter:
https://twitter.com/sparkeyed_/status/1641726531654254592?s=20

It looks like this: 
<img width="594" alt="Screenshot 2023-03-31 at 11 18 35" src="https://user-images.githubusercontent.com/104380776/229080034-300f08dd-6cd9-41ba-835f-644469c8520b.png">

We have already solved this issue before:
- https://github.com/kodadot/nft-gallery/issues/5268

Its a bug? I think maybe this is different because it's a collection, not an individual NFT. 
Can we also have thumbnail previews for the collection?

### Please reproduce in steps

share collection on Twitter

### Expected Behavior

have preview

### What browsers are you seeing the problem on?

Desktop Chrome

### Are you logged in?

None

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
> yes, we should support the user page also. anyone on @kodadot/internal-dev maybe wanna try?

yes, we usually been fetching last image from their mints for socials.

**Comment by preschian** [comment]
> Hello, one artist shared her new collection on Twitter:
> [twitter.com/sparkeyed_/status/1641726531654254592?s=20](https://twitter.com/sparkeyed_/status/1641726531654254592?s=20)

it works now, even that status also now shows the opengraph image
