### ISSUE TITLE
Use new rmrk2 endpoint everywhere 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5444]
Seems item is using still old one, despite 

- #5425 

![image](https://user-images.githubusercontent.com/5887929/229105680-04915402-9d32-4fda-94cb-d91b98379eba.png)

seems collection is same
- https://beta.kodadot.xyz/rmrk2/collection/7e982817a2d2575031-C6N4I/activity

![image](https://user-images.githubusercontent.com/5887929/229106123-6a34cab6-1e04-4298-8c34-e5518d63f70d.png)

**Comment by yangwao** [comment]
seems kodadot.xyz is it using (we don't show there rmrk2 anyway)

but beta.kodadot.xyz is back using old endpoint on landing

![image](https://user-images.githubusercontent.com/5887929/229107762-3c0ddc05-577f-4eac-8045-de52b959b0ec.png)

Are we using this, right?
- https://github.com/kodadot/nft-gallery/blob/main/libs/static/src/indexers.ts

**Comment by yangwao** [comment]
are we using this for rmrk2? 
https://github.com/kodadot/nft-gallery/blob/main/utils/constants.ts

**Comment by vikiival** [comment]
![Uploading Screenshot 2023-03-31 at 13.51.39.png…]()
