### ISSUE TITLE
Does buy on rmrk2 works? 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5447]
Tried to buy this but even after minutes I'm not on activity tab
 
https://beta.kodadot.xyz/rmrk2/gallery/12369104-7e982817a2d2575031-C6N4I-0043_KU_SILVERWINGS-00000044

https://kusama.subscan.io/account/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd?tab=transfer

![image](https://user-images.githubusercontent.com/5887929/229121185-0ec75f4a-ca09-45d7-9cb7-e6536308f780.png)

**Comment by vikiival** [comment]
<img width="1183" alt="Screenshot 2023-03-31 at 14 50 05" src="https://user-images.githubusercontent.com/22471030/229124562-dcf2a8a3-79a1-4758-882d-180fb4381b99.png">

<img width="989" alt="Screenshot 2023-03-31 at 14 44 55" src="https://user-images.githubusercontent.com/22471030/229124582-f69d8dc7-2652-41b2-8b7c-e928bc0de7f0.png">


It's issue with @subsquid. already notified the team

**Comment by vikiival** [comment]
Works as intended

![Screenshot 2023-03-31 at 15 17 53](https://user-images.githubusercontent.com/22471030/229130740-d1dcec2b-115b-4709-b6ca-bda378b5c1e6.png)

**Comment by JustLuuuu** [comment]
Then its slow af, I bought this NFT: https://beta.kodadot.xyz/rmrk2/gallery/12163241-a0c4801b6dbf04c674-312YA-23_DUTCH_NFT_ART_COLORFUL_SERIE-00000023 and I still see it for sale and Im not owner after few minutes of waiting.

**Comment by yangwao** [comment]
if indexer is synced, it works!
I'll keep this one open to monitor if not happening again, lowering prio

- https://squiki.kodadot.workers.dev/status/marck
![telegram-cloud-photo-size-4-5852876381392846384-m](https://user-images.githubusercontent.com/5887929/229169197-d9bdee19-3b3d-481c-8e0b-1cc95768db64.jpg)

![image](https://user-images.githubusercontent.com/5887929/229169144-4536cb9d-2abc-49d1-ab7c-f584ed97d43b.png)

![image](https://user-images.githubusercontent.com/5887929/229169167-89cc1b05-fac6-41d0-8f5f-bcec689d5a60.png)

**Comment by vikiival** [comment]
```
◷ Compressing the squid to marck-v1.tar.gz ... 149 file(s) ✔️
🦑 Releasing the squid
◷ Uploading marck-v1.tar.gz... ✔️
```

**Comment by vikiival** [comment]
We were waiting for metadata, now they are dropped after 8s

**Comment by yangwao** [comment]
Maybe we can check on this how fast is it, if good enough, we can maybe close on this?

**Comment by vikiival** [comment]
8 sec after tx finalized

<img width="1001" alt="Screenshot 2023-04-12 at 13 48 34" src="https://user-images.githubusercontent.com/22471030/231447995-5ea7a63f-9c08-41f8-b8a8-12c0d2e0c87a.png">
