### ISSUE TITLE
Hide Offers if they are not avaliable on RMRK2

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5451]
Open any RMRK2 NFT and you will see next to activity log offers. You cannot click on it because it's not supported. But then, why have it at all?

I would consider hiding this option.

<img width="890" alt="Screenshot 2023-03-31 at 16 34 54" src="https://user-images.githubusercontent.com/104380776/229150607-6b31cc02-cea0-4372-826c-60ed12d90926.png">

**Comment by roiLeo** [comment]
see https://github.com/kodadot/nft-gallery/issues/4438#issuecomment-1338170304

I think offers will be available with rmrk3

**Comment by exezbcz** [comment]
Because once we have everything multichain, the ui will not change every time, and it will be at least consistent. @JustLuuuu 

this will makes much more sense with multichain explore, search, notifications, you name it.

**Comment by JustLuuuu** [comment]
good point, I did not realized that. Lets close the issue then.
