### ISSUE TITLE
Activity log not working

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5452]
### What happened?

Activity-log not working - showing wrong things. I was checking[ this NFT](https://beta.kodadot.xyz/rmrk2/gallery/12369104-7e982817a2d2575031-C6N4I-0043_KU_SILVERWINGS-00000044), and playing with the activity. Not working.

<img width="890" alt="Screenshot 2023-03-31 at 16 34 54" src="https://user-images.githubusercontent.com/104380776/229151446-1a11f1d9-a0c6-4a36-aa69-b6fb587bf6ef.png">
<img width="891" alt="Screenshot 2023-03-31 at 16 33 33" src="https://user-images.githubusercontent.com/104380776/229151464-5924399c-d091-4ccd-a846-708c9287fba0.png">

Video
---

https://user-images.githubusercontent.com/104380776/229151581-8e2c08ca-2ef3-4e44-ba1f-180ce0a5e6a4.mov

### Please reproduce in steps

Open any NFT on RMRK2 - click on Activity and try it

### Expected Behavior

shopw correct activity

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

None

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by exezbcz** [comment]
ah, i see the problem, you are only deselecting one at a time - if its grey that means that its selected - by default when you open the gallery item, all settings are active. 

@JustLuuuu I have to rethink bit the buttons or the default state when you open gallery, this should not happen :D

**Comment by JustLuuuu** [comment]
> @JustLuuuu I have to rethink bit the buttons or the default state when you open gallery, this should not happen :D

lol, I thought its the opposite. I was sure that I'm selecting only one :DD

**Comment by exezbcz** [comment]
@JustLuuuu yeah, its my bad - it should be clear what state is selected - it could be confusing when you open that and everything is selected by default

**Comment by yangwao** [comment]
*UX researcher enters room*

<img src="https://media2.giphy.com/media/XGJWj3U6iQMxj8TLYa/giphy.gif"/>
<img src="https://media3.giphy.com/media/U7bZeU3T0UTxfdgq71/giphy.gif"/>
