### ISSUE TITLE
Rethink BUYing experience 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5458]
> I believe there should be either a toast menu once you sign the message (you don't have to wait for the transaction to go through) or a modal with some step-by-step explanations and transaction details, followed by a redesigned congratulations message. by @exezbcz 

![image](https://user-images.githubusercontent.com/5887929/229171397-b023f6af-0dcb-453f-b639-679ea125d004.png)

![image](https://user-images.githubusercontent.com/5887929/229171304-da98efdc-728c-41da-bd8a-550f1b33d3c8.png)

![image](https://user-images.githubusercontent.com/5887929/229171828-b658971a-b38d-4394-9171-fbbf2c5f9e68.png)

![image](https://user-images.githubusercontent.com/5887929/229171786-bea71464-1ff6-4d8f-8f4f-9482c5092c4e.png)

History
---
Netscape was most popular browser in 1996 - https://en.wikipedia.org/wiki/Netscape_Navigator

Ref
---
- https://github.com/kodadot/nft-gallery/issues/5433#issuecomment-1491397807

**Comment by yangwao** [comment]
Any news?

**Comment by exezbcz** [comment]
@yangwao yup, working on that

**Comment by exezbcz** [comment]
q for @kodadot/internal-dev 
How precisely can we show the contextual message of what you are signing? E.g., buying - once you click confirm, the signing modal could display the context/phrase you are signing purchase tx.

**Comment by vikiival** [comment]
> show the contextual message of what you are signing?

You can get any dynamic data into modal

```
You are going to buy {{ nft.name }} for {{ nft.price }} KSM
This transactions will be published to {{ chain }} chain

[cancel]                           [submit]
```

**Comment by exezbcz** [comment]
@vikiival oki oki, and when is the transaction pending? Is it possible as well?

**Comment by exezbcz** [comment]
@vikiival Yeah, I phrased it badly. Last q, contextual message while the tx is pending? :D

**Comment by vikiival** [comment]
Sure sir, whatever for you 😇

**Comment by yangwao** [comment]
Related @exezbcz or can we close in favour?

- #6372
