### ISSUE TITLE
Pictures shows but then disappears 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5460]
- https://beta.kodadot.xyz/rmrk2/gallery/16037174-f809131fc9c1dbac31-MKDIR-GOING_WALKABOUT-00000001

https://user-images.githubusercontent.com/5887929/229201371-0acb7b39-a238-4454-8c76-43544dfaa1f1.mov

![image](https://user-images.githubusercontent.com/5887929/229201390-f07e4637-5b4b-4459-9724-d3f6d11d01ae.png)

**Comment by prachi00** [comment]
@yangwao is this still an issue? I see this 
![Screen Shot 2023-04-02 at 3 37 45 PM](https://user-images.githubusercontent.com/39299315/229382890-a7f0475c-1692-492f-9bcc-290c8a51e67f.png)

**Comment by yangwao** [comment]
seems showing well, not sure what was fixed, thanks for notice!

![image](https://user-images.githubusercontent.com/5887929/230120915-8a41aec5-adc2-4dcc-a1a9-b1a714b70d4b.png)
