### ISSUE TITLE
Freshly minted NFT doesn’t show up after redirection

### ISSUE THREAD

**Issue by helloitsdamsky** [kodadot/nft-gallery#5465]
### What happened?

Minted an NFT using simple mint, redirected to an NFT and it doesn’t show up.

This is honestly quite an issue because user isn’t sure if the nft was minted or not. They can’t even share it.

### Please reproduce in steps

Minted an NFT using simple mint, redirected to an NFT and it doesn’t show up.

### Expected Behavior

For it to show

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

None

### Which wallet you are using?

Talisman

### At which chain did you encounter bug?

Kusama

### Screenshots

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/92786519/229275378-f0016e37-44a5-449b-904e-c3693e571035.png">

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
This is related with https://github.com/kodadot/workers/pull/37 I believe? @vikiival

**Comment by vikiival** [comment]
> This is related with https://github.com/kodadot/workers/pull/37 I believe? @vikiival 


Yes and

- https://github.com/kodadot/workers/pull/55

**Comment by yangwao** [comment]
We can at least mock this for user when got redirected.
- #4752

**Comment by yangwao** [comment]
Works like after 15 seconds for me 

![image](https://user-images.githubusercontent.com/5887929/234035038-aec78dfd-2216-4d42-93d6-09f928c81879.png)

**Comment by helloitsdamsky** [comment]
There’s no redirection, on profile when i click on the nft (which showed up after one minute in collection, i can’t see anything.

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/92786519/234049942-27423825-40d8-4968-bbc3-8e41b7d5e8bd.png">

https://canary.kodadot.xyz/rmrk/gallery/17623798-C6E2CA836BD86CBD05-PLACE-DREAMY_PLACE_IN_CZECH_REPUBLIC-0000000000000002
