### ISSUE TITLE
In artist profile: Not showing all collections created by the artist

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5466]
### What happened?

[Kusama Dark Side](https://beta.kodadot.xyz/rmrk2/collection/7e982817a2d2575031-Y007N?page=1) and [Ku colletion](https://beta.kodadot.xyz/rmrk2/collection/7e982817a2d2575031-C6N4I?page=1) is not showing between collections created by [this artist](https://beta.kodadot.xyz/rmrk2/u/FSJkXLHuWYfB8DYejjFKX4bkFjb7dMt9RvVpq6D5LUQLY6x?tab=nft&page=1&sort=blockNumber_ASC).

Zluchkayaa is the creator of the 2 mentioned collections:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/104380776/229278147-1f11d9c2-ad03-4cfe-9479-a666cf6783f0.png">

In her profile. If you click on collections, you see only 3. They are all on RMRK2.

<img width="1470" alt="Screenshot 2023-04-01 at 11 25 47" src="https://user-images.githubusercontent.com/104380776/229278092-14a1cd68-4e06-4b8e-8f0b-e5a4670d6fc6.png">

you can see those NFTs between NFTs in her profile but not in collections. Not sure why

### Please reproduce in steps

Open for example [this]([Kusama Dark Side](https://beta.kodadot.xyz/rmrk2/collection/7e982817a2d2575031-Y007N?page=1) ) collection and chceck creator.

Then open [this artis](https://beta.kodadot.xyz/rmrk2/u/FSJkXLHuWYfB8DYejjFKX4bkFjb7dMt9RvVpq6D5LUQLY6x?tab=collection)t and look at collections.

### Expected Behavior

Show all collections created by artist

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

None

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustLuuuu** [comment]
Another example: RubenTopia:

This collections are created by him but you cannot see them in his profile: https://beta.kodadot.xyz/rmrk2/collection/c095ca1430a05e7d6b-TOPIA?page=1 
https://beta.kodadot.xyz/rmrk2/collection/c095ca1430a05e7d6b-7?page=1 
....

**Comment by yangwao** [comment]
ou nou, this is bad ass

**Comment by yangwao** [comment]
I guess I've cracked mystery. Thing is that they've been collection issuer on RMRKv1, but as they did migrated it, they did not claimed it from RMRK Migrator address which is actually issuer on RMRKv2, that's case for mints at least and I sense with collections it is somehow.. very close to same.. dum dum dumdumdum

I sense this will result in some uberhacking

**Comment by yangwao** [comment]
Apparently it's that issuer of collection is RMRK Official or RMRK Migrator and we are showing current owner, where in profile we are showing only issued collection by that address, so mistake is bit in collection rather in profile. We can maybe glue something to work it.. maybe we could add new tab "Owned Collections" and we will reflect in #2009 it better.

- https://canary.kodadot.xyz/ksm/collection/e0b9bdcc456a36497a-SQSQ/activity?mint=true

**Comment by vikiival** [comment]
The problem is that we show that creator is currentOwner and not and an issuer

Therefore `created by` should be `issuer`
and if current owner is not equal to issuer show
`owned by`

![Screenshot 2023-04-16 at 15 40 35](https://user-images.githubusercontent.com/22471030/232315394-d57b333d-dc13-44a7-bb2d-10ce2bbf5479.png)

**Comment by vikiival** [comment]
same applies for 

```json
{
  "data": {
    "collectionEntityById": {
      "id": "7e982817a2d2575031-Y007N",
      "name": "Kusama Dark Side",
      "issuer": "EXZLG911C35TBhi2b2m3G1pEFhn5NvEhyZxXHye6ffX2b77",
      "currentOwner": "FSJkXLHuWYfB8DYejjFKX4bkFjb7dMt9RvVpq6D5LUQLY6x"
    }
  }
}
```
