### ISSUE TITLE
Two specific NFTs are not loading in Newest List.

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5468]
### What happened?

These two NFTs are not loading at all. I waited long enough. When you open them - NFTs will load.
<img width="1460" alt="Screenshot 2023-04-01 at 11 44 25" src="https://user-images.githubusercontent.com/104380776/229278864-6dbb4043-3b18-4b6d-88e1-d16363d7a937.png">

[This one:](https://beta.kodadot.xyz/rmrk2/gallery/15084794-54bbd380dc3baaa27b-EVRLOOT-MARKETCART_MAKESHIFT-00003262)
<img width="1229" alt="Screenshot 2023-04-01 at 11 44 44" src="https://user-images.githubusercontent.com/104380776/229278872-06165134-179f-4813-bcce-6db5d384c61b.png">

[This one:](https://beta.kodadot.xyz/rmrk2/gallery/13327235-54bbd380dc3baaa27b-EVRSOULS-Berserker-00000194)
<img width="1383" alt="Screenshot 2023-04-01 at 11 44 50" src="https://user-images.githubusercontent.com/104380776/229278867-71fe3fda-7050-4309-bd64-b4313d4518f2.png">

### Please reproduce in steps

Open kodadot.xyz scroll to see newest list and find those two NFTs

### Expected Behavior

load them

### Are you logged in?

None

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustLuuuu** [comment]
https://rmrk2.kodadot.xyz/rmrk2/gallery/13790572-b45943b4edbf6f5c0f-SKYLAB_ARTEMIS_R4VENS-MODIFIED_R4VEN-00000966
<img width="1435" alt="Screenshot 2023-04-04 at 17 15 19" src="https://user-images.githubusercontent.com/104380776/229839360-92f7ce8e-3443-40f8-bdf0-518a175ff541.png">

**Comment by yangwao** [comment]
- #5498

**Comment by roiLeo** [comment]
feel free to reopen if 3D model won't load
