### ISSUE TITLE
RMRK2 card detail

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5469]
Can we have a small RMRK2 on the bottom right corner of the preview cards?

We have _Basilisk, Kusama_ already there. It would be nice to have something for RMRK2 NFTS.
<img width="1454" alt="Screenshot 2023-04-01 at 11 54 49" src="https://user-images.githubusercontent.com/104380776/229279351-45d4d2d4-11b5-492d-bc7d-01e2dd14ee24.png">

For RMRK2 it's empty. Newest list and latest sales.
<img width="1444" alt="Screenshot 2023-04-01 at 11 55 23" src="https://user-images.githubusercontent.com/104380776/229279361-6fd2c4b9-bc1a-4d0d-b403-45c0aee74f0e.png">

<img width="1396" alt="Screenshot 2023-04-01 at 11 56 05" src="https://user-images.githubusercontent.com/104380776/229279365-080aef58-823c-4a91-8b85-df1b26c440b2.png">

**Comment by yangwao** [comment]
Being done here 
- https://github.com/kodadot/nft-gallery/issues/5435

**Comment by vikiival** [comment]
Continue in https://github.com/kodadot/nft-gallery/issues/5435

Thanks for issue @JustLuuuu <3
