### ISSUE TITLE
Sorting by Most supply not working

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5470]
### What happened?

Sorting collection by most supply does not work (will not load anything). Sorting them by least supple looks like working (will load collections). 
<img width="1469" alt="Screenshot 2023-04-01 at 14 04 04" src="https://user-images.githubusercontent.com/104380776/229287740-fc4d638f-1a84-4bdd-b453-20205e5d6481.png">

<img width="1469" alt="Screenshot 2023-04-01 at 14 03 57" src="https://user-images.githubusercontent.com/104380776/229287744-03374385-4a5e-4192-8afc-9de9b54b458d.png">

### Please reproduce in steps

Explore collections - most/least supply

**Comment by leo-anderson-x** [comment]
seems backend issue, the query is correct
![CleanShot 2023-04-03 at 21 45 24@2x](https://user-images.githubusercontent.com/128157824/229513466-4bfc0482-307b-4bbb-9cc5-e67543dc358e.png)
![CleanShot 2023-04-03 at 21 45 51@2x](https://user-images.githubusercontent.com/128157824/229513520-3d4a39e1-d253-43b9-85a6-9e1721b7a247.png)

**Comment by roiLeo** [comment]
Duplicate #5086

**Comment by JustLuuuu** [comment]
<img width="2836" alt="Screenshot 2023-05-10 at 18 12 56" src="https://github.com/kodadot/nft-gallery/assets/104380776/38935a46-6b58-4a97-977b-da19869fbc8b">
still not working

**Comment by JustLuuuu** [comment]
works for me
