### ISSUE TITLE
Switching between Kusama and Basilisk

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5490]
Changing the network in explore is not working properly. It should automatically switch between networks after you change it. The video will explain it best.

Click on explore - collection/items and for example Kusama. After that, if you change the network to Basilisk in the filter menu, it will load you Basilisk NFTs but on top of the page, if you click on explore, you are still in Kusama even though all the loaded NFTs are from Basilisk. It's a small detail, but it should be united so it does not confuse newcomers.

https://user-images.githubusercontent.com/104380776/229450577-ca8f9849-9ea7-4bb6-86a2-be8f7519a915.mov

**Comment by exezbcz** [comment]
Yep, this part is broken for like the third time :D 

- pr that is solving this: 
- #5472

**Comment by roiLeo** [comment]
closed by #5450
