### ISSUE TITLE
Collection preview doesn't show in searchbar

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5500]
### What happened?

doesn't shows collection profile

### Please reproduce in steps

search some collection like "Ku*" on rmrk2

### Expected Behavior

![image](https://user-images.githubusercontent.com/5887929/229527759-839b9815-43c5-41c3-ac14-fa65a813a84b.png)

I would also change it to square picture as it's small wyt @exezbcz 

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

canary.kodadot.xyz

### Are you logged in?

None

### Screenshots

![image](https://user-images.githubusercontent.com/5887929/229527644-1a4b8806-ca8a-497c-b3cf-7a107a7b0221.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by exezbcz** [comment]
yes, the icon should be much bigger 
![image](https://user-images.githubusercontent.com/90852205/229530177-d7431822-99d4-45bd-b856-0898c6e077b9.png)
- 48px vs 62px in figma
![image](https://user-images.githubusercontent.com/90852205/229530281-76d96dcf-09c4-4141-ba10-0c4b6d2f32eb.png)
- I would personally leave the icon rounded for now 
- One thing I would change is that the circle is oval :D 
![image](https://user-images.githubusercontent.com/90852205/229530599-f223fbc4-e4f4-40dc-bd48-c146ca3ff378.png)

**Comment by yangwao** [comment]
> * I would personally leave the icon rounded for now

I mean we show squarish in activity, why not keep it consistent for small previews? Circle would be good for example if it's person, not collection?

**Comment by yangwao** [comment]
also I was thinking maybe adding some level of zoom for picture like %10 if that won't cripple those PFPs?

**Comment by exezbcz** [comment]
@yangwao hmm, why zoom? they are imported as square by default no?

**Comment by yangwao** [comment]
up for grab and with 
- #5679 combo for anyone

**Comment by exezbcz** [comment]
<img src="https://media3.giphy.com/media/39zbpCQocXLi0/giphy.gif"/>
