### ISSUE TITLE
Some icons are gone and back again 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5501]
Noticed some icons are gone, but I guess it's something to do as I've changed underlying domain from `koda-nuxt.netlify.app` to `koda-canary.netlify.app`

![image](https://user-images.githubusercontent.com/5887929/229532071-52dba08a-4e35-46d3-b766-73d414bc5c3e.png)

Close me in 14 days from now, I guess once last PR which has old deployment is gone, it's should be this issue gone as well

---
#5420

**Comment by roiLeo** [comment]
Please @preschian be careful with sharing sensitive screenshot as I don't want to see my personal email floating around

**Comment by vikiival** [comment]
> Please @preschian be careful with sharing sensitive screenshot as I don't want to see my personal email floating around

Agree, otherwise you get these really good offers

<img width="504" alt="Screenshot 2023-04-04 at 10 39 12" src="https://user-images.githubusercontent.com/22471030/229736766-c1eb5bb3-4f66-4e9e-b6f1-4357f1e0f8a1.png">

**Comment by yangwao** [comment]
> . @yangwao can you test it to login and adjust this settings [fontawesome.com/kits/54f29b7997/settings](https://fontawesome.com/kits/54f29b7997/settings)?


I don't see any emails from fontawesome :< nor reset doesn't work 😅
