### ISSUE TITLE
Sorting: explained

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5510]
### Is your feature request related to a problem?

I wanted to open a new issue that we are missing Sorting by Popular, but then I found that it was already opened by @exezbcz. This issue:
- #5335

I think the options we have in sorting can be confusing.
- Unpopular = with the least activity (I think)
- Recently interacted = is the opposite of unpopular (?) - with recent activity (BUT not MY activity, recently interacted in general?)

<img width="1422" alt="Screenshot 2023-04-04 at 09 53 30" src="https://user-images.githubusercontent.com/104380776/229727116-4fd63e80-3a72-45f3-a045-caa694477d2b.png">

### Describe the solution you would like

Can we have that pop-up hovering window (idk what you call it) that we have for example for minting?
<img width="1436" alt="Screenshot 2023-04-04 at 09 57 43" src="https://user-images.githubusercontent.com/104380776/229727094-b3283c5b-8daf-409c-93e0-8bee4bd484d7.png">

With a very short text that explains the options?
- Old/new - these maybe don't need explanations
- Unpopular = with the least activity, least interacted ones
- Recently interacted = NFTs with the most interactions 
- Least/most supply = also shortly explained

### Describe alternatives you have considered

**Better naming** - I already wrote my idea in #5335 but let me copy-paste it here:

I would use the same naming for **unpopular/recently interactive** options. Ideas:  Unpopular/Popular. Least activity/Most activity. Recent activity/Least activity

**Comment by JustLuuuu** [comment]
I also noticed that we have different names for **Old First/New first** for collection and **Oldest/Recently created** for NFTs (items). Basically, it's the same thing... but in one case we are searching in collections and in another case in Items. It would be good to have the same naming. 

<img width="957" alt="Screenshot 2023-04-04 at 10 13 54" src="https://user-images.githubusercontent.com/104380776/229730656-b38040d5-8f6d-4fa3-aab2-85a7b00512a4.png">
<img width="1395" alt="Screenshot 2023-04-04 at 10 14 02" src="https://user-images.githubusercontent.com/104380776/229730648-38306597-f865-4c22-b6bd-3de3b0509ea9.png">

**Comment by roiLeo** [comment]
> Can we have that pop-up hovering window (idk what you call it) that we have for example for minting? 
> 
> With a very short text that explains the options?
> 
>     * Old/new - these maybe don't need explanations
> 
>     * Unpopular = with the least activity, least interacted ones
> 
>     * Recently interacted = NFTs with the most interactions
> 
>     * Least/most supply = also shortly explained

I don't think it's a good idea to add tooltip as it would add some noise on the screen.

> ### Describe alternatives you have considered
> 
> **Better naming** - I already wrote my idea in #5335 but let me copy-paste it here:
> 
> I would use the same naming for **unpopular/recently interactive** options. Ideas: Unpopular/Popular. Least activity/Most activity. Recent activity/Least activity


Feel free to list what you want to see instead. maybe @exezbcz can help with better naming.
Here's some example from popular marketplace:
 
![Screenshot 2023-04-04 at 10-16-21 Marketplace](https://user-images.githubusercontent.com/9987732/229733445-646090a7-69bf-4ec3-9a0e-244823363437.png)

![Screenshot 2023-04-04 at 10-20-06 Bored Ape Yacht Club LooksRare](https://user-images.githubusercontent.com/9987732/229733459-02716d4f-6a4b-472b-a8fb-32f8bd6c6c7a.png)

![Capture d’écran 2023-04-04 à 10 17 41 AM](https://user-images.githubusercontent.com/9987732/229733502-71d957b3-ff7f-4b5a-bd33-cfde91fceb28.png)

**Comment by exezbcz** [comment]
Hmm, I would not put the tooltip there, agree with roileo that it would be than redundant noise. 

How is unpopular defined? least interacted right? 
what about this? 
![image](https://user-images.githubusercontent.com/90852205/229745628-8f9cc662-6fd7-4009-8b16-6dfad5d7339e.png)

- i would also switch the recently created to newest? If we would like to add recently listed, we can then divide it again 

Recently interacted = most interacted in short time horizon no? At Least for us.

I would also switch the order of price


not sure about the serial number? Is it useful?
