### ISSUE TITLE
Remove Snyk

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#5511]
Since @yangwao installed https://socket.dev/ about a week ago.
I do not think that we need double security tooling

+ Snyk makes this annoying PRs (#5508) without updating lock

**Comment by yangwao** [comment]
yup disabled deleted, hopefully we don't get some sec issue 😅
![image](https://user-images.githubusercontent.com/5887929/229782850-de7405ad-9b3c-40b4-9742-0d2f0985c0cd.png)
