### ISSUE TITLE
Missclick? Isn't this suppose to be RMRK2?

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5515]
<img width="1440" alt="Screenshot 2023-04-04 at 16 31 18" src="https://user-images.githubusercontent.com/104380776/229829297-a1d6a51a-50e6-402a-a96b-d5cea25b51f1.png">

**Comment by yangwao** [comment]
@vikiival that's because merge of rmrkv1 & rmrkv2 ?

![image](https://user-images.githubusercontent.com/5887929/230897928-b4227e3e-b59b-43c5-91d7-4d3be78cb45b.png)

**Comment by JustLuuuu** [comment]
If you click on the bottom Kusama, it will change to RMRK2: 
<img width="402" alt="Screenshot 2023-04-10 at 15 39 20" src="https://user-images.githubusercontent.com/104380776/230921705-56c083d0-064b-4eea-bbd2-8c4d0f0cecaa.png">

It should stay same so its not confusing

**Comment by JustLuuuu** [comment]
I guess I don't like this: 😂 three different names for one thing. Live on beta

<img width="1441" alt="Screenshot 2023-04-12 at 13 53 46" src="https://user-images.githubusercontent.com/104380776/231467420-a0752672-f6c6-4d13-83d0-d07066db50eb.png">


![zlQRKF](https://user-images.githubusercontent.com/104380776/231467452-95073959-d240-4a4a-8e5c-a72c868e116b.gif)

**Comment by vikiival** [comment]
Naming ;D will try to unify that
