### ISSUE TITLE
Collection information, more details

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5532]
A suggestion to add more details to the collection view:
- Number of NFTs for sale (listed/for sale) 
- Last sale (in KSM)
- Highest sale (in KSM)
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/104380776/229289798-be573f4c-0b8c-47db-87f0-59389be434f6.png">

**Comment by yangwao** [comment]
related
- #5362

**Comment by roiLeo** [comment]
closed by #8433
