### ISSUE TITLE
Super heavy loading on activity 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5540]
there is pretty intense loading on some collection activity like this: https://canary.kodadot.xyz/rmrk2/collection/dac5c7f54029d0e73c-6AFVH/activity

items load fairly quickly but once you switch to activity, everything starts to be laggy
it has lot of items: 
![image](https://user-images.githubusercontent.com/90852205/230567503-9fb9d7f5-a6aa-4510-bb9a-67cf77a2023c.png)

ends with: 
![image](https://user-images.githubusercontent.com/90852205/230567709-d87ee62f-bf06-4975-a02e-dc995e326347.png)

**Comment by leo-anderson-x** [comment]
After we finish #4552, it should be fixed?

**Comment by roiLeo** [comment]
> After we finish #4552, it should be fixed?

Depends, activity graph will also be impacted. 
Maybe we should limit first to 100 last events and then try to add pagination.

**Comment by exezbcz** [comment]
@roiLeo and if we would like to keep infinity scroll on events? Is there any solution for that

**Comment by roiLeo** [comment]
> @roiLeo and if we would like to keep infinity scroll on events? Is there any solution for that

no problem, we can keep infininty scroll on events with a limit (like we do on item or collection).
Thing is we can't show all events data on graph without having client browser go brrrrr.

**Comment by yangwao** [comment]
Related
- https://github.com/kodadot/nft-gallery/issues/5574

**Comment by yangwao** [comment]
> Maybe we should limit first to 100 last events and then try to add pagination.

We just debugged and seems like needs to lazy load queries on holders, flippers and activity.

**Comment by daiagi** [comment]
should be improved by #5608

**Comment by yangwao** [comment]
I guess moving this to for more quality fix
- #5388
