### ISSUE TITLE
Identity creation Error

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5566]
### What happened?

[This artist](https://kodadot.xyz/rmrk/u/H1scXqBBis6xobc9tSWjqAiHAe8X71xcgkbau8xgWm2xc2a?page=1) has problem with identity creation. He keeps getting this error: 
Error: createType(Call):: Call: failed decoding identity.setIdentity:: Struct: failed on args: {"info":"{"additional":"Vec<(Data,Data)>","display":"Data","legal":"Data","web":"Data","riot":"Data","email":"Data","pgpFingerprint":"Option<[u8;20]>","image":"Data","twitter":"Data"}"}:: Struct: failed on info: {"additional":"Vec<(Data,Data)>","display":"Data","legal":"Data","web":"Data","riot":"Data","email":"Data","pgpFingerprint":"Option<[u8;20]>","image":"Data","twitter":"Data"}:: Struct: failed on web: {"_enum":{"None":"Null","Raw":"Bytes","BlakeTwo256":"H256","Sha256":"H256","Keccak256":"H256","ShaThree256":"H256"}}:: Data.Raw values are limited to a maximum length of 32 bytes

Picture:
---
You can clearly see that he has enough KSM to create his identity
![dkhhd](https://user-images.githubusercontent.com/104380776/230713112-a335c725-39d2-40cb-b528-5320eb57fb86.png)

### Please reproduce in steps

Create identity

### Expected Behavior

create it normally

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Kusama

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustLuuuu** [comment]
> #4835

In this case, it would be good if the popup will state this information. So people know what they did wrong. Is there also a reason why is it limited to 32 characters? :)

**Comment by roiLeo** [comment]
> In this case, it would be good if the popup will state this information. So people know what they did wrong.

Yep sorry for that we forgot to include/test rmrk chain, it was already present on bsx/snek

> Is there also a reason why is it limited to 32 characters? :)

I don't really know about this one it's more of a chain related thing (maybe size?), but you're right 32chars is not much.

**Comment by yangwao** [comment]
- https://github.com/kodadot/nft-gallery/issues/4751

**Comment by yangwao** [comment]
> but you're right 32chars is not much.

it's meant for website, not for long URLs well, 32 should be enough? also it's on-chain thing so it eats space on validators 🤔 but maybe if it's prunned idk
