### ISSUE TITLE
no margin on collection items 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5582]
![image](https://user-images.githubusercontent.com/90852205/230866351-e36a5555-4050-48c0-b254-7473b595513e.png)
- when burger menu is not opened, the cards dont have bottom margin

**Comment by leo-anderson-x** [comment]
I'm not sure if I understand correctly... but on my side, there is always a margin bottom regardless of whether the burger menu is opened or not:

https://user-images.githubusercontent.com/128157824/230907582-676f68e3-2542-4bb8-94ab-ffd148f455b3.mp4

**Comment by exezbcz** [comment]
> I'm not sure if I understand correctly... but on my side, there is always a margin bottom regardless of whether the burger menu is opened or not:
> 
> https://user-images.githubusercontent.com/128157824/230907582-676f68e3-2542-4bb8-94ab-ffd148f455b3.mp4
> 
> 

Go to collection

**Comment by leo-anderson-x** [comment]
👋
