### ISSUE TITLE
rmrk2 img thumbnail doesn't load 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5583]
okay so I recently tried to mint a nft on singular - on rmrk2 - just to see how it's displayed then in our app

There is different thing in minting where you choose how is nft displayed on preview (on the card) and then in the detail - It can be different img - and there is an issue 

see this collection on singular 
https://singular.app/collectibles/kusama/9238a1cfd0db7ecd2b-SPRING?isVerified=false&sortBy=nfts:minted_at_block:desc
![image](https://user-images.githubusercontent.com/90852205/230869476-8e98dcca-d3f8-4542-b6d8-a8f47cb0404d.png)
- There is an item - for which I chose a different image for the outside cover - that shows up when you open the detail:
![image](https://user-images.githubusercontent.com/90852205/230869578-23d8c207-60cb-4a38-884c-cfa26323d69d.png)

on kodadadot there is only the preview visible on the cards 
![image](https://user-images.githubusercontent.com/90852205/230869755-cd63e370-b734-4bd7-8002-4e1582672478.png)
but detail does not load correctly
![image](https://user-images.githubusercontent.com/90852205/230869801-41f9a867-a7fe-408d-a28c-1e2dca46887a.png)

- I think it was already reported somewhere - if so, close it please

**Comment by roiLeo** [comment]
Test on https://beta.kodadot.xyz/ksm/gallery/17405564-9238a1cfd0db7ecd2b-SPRING-FIRST-00000001

**Comment by exezbcz** [comment]
@roiLeo cover = img in gallery on kodadot 

The issue was that I set a different cover than the image seen in the gallery item.

**Comment by roiLeo** [comment]
> @roiLeo cover = img in gallery on kodadot

I know just wanted to share the path for future reference

> The issue was that I set a different cover than the image seen in the gallery item.

Did you set something directly on singular app?
