### ISSUE TITLE
Collection cards on profile 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5584]
Lets replace the old collection cards in profile with the new ones. 
![image](https://user-images.githubusercontent.com/90852205/230875017-664653df-4d80-45c3-b44b-34490620ae26.png)
![image](https://user-images.githubusercontent.com/90852205/230875059-b0ea044a-13da-481e-87d9-bde0feba7d8c.png)

**Comment by yangwao** [comment]
Continue to 
- https://github.com/kodadot/nft-gallery/issues/5032
