### ISSUE TITLE
Add Medium articles to landing page:

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5587]
Is it possible to add [Medium](https://medium.com/kodadot) articles to our landing page? Having Medium + Substack articles here:
<img width="1447" alt="Screenshot 2023-04-10 at 15 51 13" src="https://user-images.githubusercontent.com/104380776/230914406-5b34f64c-e3cd-4919-b90e-1c900254e18c.png">

Or maybe create a separate category for Medium articles? Articles on Medium are mostly updates, news. Substack is only for artsy stuff now - Ride on Art

**Comment by JustLuuuu** [comment]
> one section for articles is enough imo, wdyt?

Yeah, I would prefer that too. But is it possible to add Medium and Substack articles in one section?

**Comment by exezbcz** [comment]
@JustLuuuu for sure!

**Comment by roiLeo** [comment]
Meanwhile changed to beehiiv
