### ISSUE TITLE
NFT links - not working in Twitter chat? 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5588]
Here we go again. 😂
NFT links not working in chat on Twitter:

One artist sent me his freshly minted NFT. [This link](https://kodadot.xyz/rmrk/gallery/17381192-9AFFD71D65E3DBBF29-HIBERNATIO-HIBERNATION_MODE-0000000000000001). It looks like this:
<img width="373" alt="Screenshot 2023-04-10 at 16 44 54" src="https://user-images.githubusercontent.com/104380776/230924940-b059d0a4-700c-466d-8e1e-d8baf281c25e.png">

Collection links are working
<img width="328" alt="Screenshot 2023-04-10 at 16 51 15" src="https://user-images.githubusercontent.com/104380776/230935687-7be5a49c-207b-407d-b598-160f5045c342.png">

Profile links not working
<img width="357" alt="Screenshot 2023-04-10 at 16 50 22" src="https://user-images.githubusercontent.com/104380776/230925740-a24a7a94-4a6d-46e8-9ba9-0c406dd157c9.png">

**Comment by yangwao** [comment]
We are on it 🍯
- #5567

**Comment by yangwao** [comment]
https://beta.kodadot.xyz/rmrk/gallery/17381192-9AFFD71D65E3DBBF29-HIBERNATIO-HIBERNATION_MODE-0000000000000001

https://www.opengraph.xyz/url/https%3A%2F%2Fbeta.kodadot.xyz%2Frmrk%2Fgallery%2F17381192-9AFFD71D65E3DBBF29-HIBERNATIO-HIBERNATION_MODE-0000000000000001

![image](https://user-images.githubusercontent.com/5887929/230975717-00fad11b-e256-4678-b3ac-a40059fc923b.png)

**Comment by yangwao** [comment]
tested w/ 

https://www.opengraph.xyz/url/https%3A%2F%2Fcanary.kodadot.xyz%2Fksm%2Fgallery%2F17533944-6607dc83a701808263-NRENB-WIFE_OF_A_REKT-00000005


<img width="427" alt="image" src="https://user-images.githubusercontent.com/5887929/233183673-d52fe48f-9d80-4bf0-87da-079625899eab.png">
