### ISSUE TITLE
Distinguish between RMRKv1 and RMRKv2 ?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5593]
It's bit confusing plus we should keep showing on cards which one is Kusama and which RMRK2 

![image](https://user-images.githubusercontent.com/5887929/231168246-36ede469-7d4c-4d5a-8448-f3299ce5712d.png)

![image](https://user-images.githubusercontent.com/5887929/230989949-909a4d12-32ee-4353-aaf4-e5c8c11f6187.png)

![image](https://user-images.githubusercontent.com/5887929/230990044-162adaf9-9bb7-4591-a0af-e20fa9888d01.png)

**Comment by JustLuuuu** [comment]
#5515
