### ISSUE TITLE
Unable to change asset fee in BSX

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5595]
### What happened?

I wanted to change my asset fee from BSX to KSM. I got this pop-up:
<img width="1449" alt="Screenshot 2023-04-11 at 10 24 19" src="https://user-images.githubusercontent.com/104380776/231104990-c13dcb2e-b4d4-4eee-aa85-e14486a18273.png">

Then I tried again and it just got stuck:
<img width="1450" alt="Screenshot 2023-04-11 at 10 25 15" src="https://user-images.githubusercontent.com/104380776/231105066-b20ab4b3-3a3c-45a2-abdc-c4a576a9dcf4.png">

My BSx address: bXgn4ZTcKDjafGdbMnuF8TLJFxwMKFtB1cVJWBYWVPbocBHX6 
I tried to change the account - on my other account, it was working flawlessly. When I tried this account again. It just got the same error and it was not working.

### Please reproduce in steps

Assets - change asset fee

### Expected Behavior

change asset fee

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustLuuuu** [comment]
Is it because I have 0 bridged KSM and 0,00011 or how much BSX tokens in this wallet?

**Comment by JustLuuuu** [comment]
Now its not working also for my second account where I have enough balance. Im stuck on loading. 
<img width="1461" alt="Screenshot 2023-04-11 at 11 07 40" src="https://user-images.githubusercontent.com/104380776/231112524-fc5afb73-485a-4724-9f92-8bce7f47adfa.png">

**Comment by roiLeo** [comment]
feel free to reopen if it still happen but I can't reproduce it
