### ISSUE TITLE
Teleport not working KSM -> BSX

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5597]
I tried two accounts on production and on beta. But none of them works. Its loading for me.
<img width="1445" alt="Screenshot 2023-04-11 at 11 12 26" src="https://user-images.githubusercontent.com/104380776/231113606-cc3f2bc6-1e37-4166-afe2-4b042233b962.png">

**Comment by JustLuuuu** [comment]
I just tested this again. From BSX to KSM it was working but from KSM to BSX it was not.

**Comment by yangwao** [comment]
Let me guess 😅
- https://github.com/kodadot/nft-gallery/issues/4925
- https://github.com/kodadot/nft-gallery/issues/5497

**Comment by VladoTheBoi** [comment]
> I just tested this again. From BSX to KSM it was working but from KSM to BSX it was not.

yes, tested today too and didnt work for as long as 40 minutes .. :/

**Comment by dudo50** [comment]
The issue might be because of an outdated version of XCM SDK. In the latest 2.0.5 everything works as expected. 
Tested on the main net:
https://kusama.subscan.io/extrinsic/19115039-2

Our team will update SDK for you and open PR to resolve this issue.
