### ISSUE TITLE
Offers tab doesn't show all offers, comparing to Notification

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#5616]
From https://github.com/kodadot/nft-gallery/pull/5442#pullrequestreview-1376274810
> Tested on `/snek/gallery/331660682-7`, I can see 4 "offer" events in NotificationBox but only 2 row in Offers tab maybe remove expired?
> <img width="866" alt="Capture d’écran 2023-04-07 à 4 42 38 PM" src="https://user-images.githubusercontent.com/9987732/230628043-d391a584-90f0-4ae6-9b65-66cdc960ecd8.png">

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/5581#pullrequestreview-1378853325_

Account address: 
`bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW`

**Comment by yangwao** [comment]
I think this is what we've noticed with @exezbcz that in Offers tab we are not showing all offers?

**Comment by roiLeo** [comment]
> i think i've filtered expired offers in notification. is it still there?

Yep, stil present

```gql
query notificationsByAccount {
  offers(where: { nft: { id_eq: "331660682-7" } }) {
    id
    caller
    expiration
    price
    status
  }
  stats: offersConnection(
    orderBy: id_ASC
    where: { nft: { id_eq: "331660682-7" } }
  ) {
    total: totalCount
  }
}
``` 
2 results while your query show 4 results

**Comment by roiLeo** [comment]
won't fix bsx
