### ISSUE TITLE
Activity doesnt shows transfer nor sales yet lot of holders

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5619]
- https://canary.kodadot.xyz/ksm/collection/9ecdab6f55355b191a-GAMMA_BUBL/activity?transfer=true&sale=true
- https://canary.kodadot.xyz/ksm/collection/9ecdab6f55355b191a-GG_XPS/activity?sale=true&transfer=true

![image](https://user-images.githubusercontent.com/5887929/231457725-f8678e5a-9bc2-437b-9658-8f18e5e2d8ba.png)

maybe @daiagi would know?

**Comment by daiagi** [comment]
I'll check

**Comment by daiagi** [comment]
![image](https://user-images.githubusercontent.com/22791238/231466580-83fe0a05-97e3-4743-89c5-7bc7b2b67dcb.png)


🤔

**Comment by vikiival** [comment]
Hello I just release marck v2 

I made a ton of fixes for last days so hope it would be done

```
◷ Compressing the squid to marck-v2.tar.gz ... 152 file(s) ✔️
🦑 Releasing the squid
◷ Uploading marck-v2.tar.gz... ✔️
◷ Preparing the squid... ✔️
Downloading squid archive from https://storage.googleapis.com/subsquid-rest-api-tmp-upload/tmp/8917c7ec-37a4-4b9d-9b46-c5d10355b21c.tar.gz...
Extracting archive...
Extracted 153 files from archive, hash 63a2eac066f957ed2553528d75b3729a2705a652
◷ You may now detach from the build process by pressing Ctrl + C. The Squid deployment will continue uninterrupted.
◷ The new squid will be available as soon as the deployment is complete.
◷ Building the squid... ⡿
```

**Comment by vikiival** [comment]
Possible fixes: 
- kodadot/rubick#231 
- kodadot/rubick#233
- kodadot/rubick#234
- kodadot/rubick#237

**Comment by yangwao** [comment]
Collection stats are showing now 

![image](https://user-images.githubusercontent.com/5887929/232035659-0303839d-2bc2-4c6a-a5ff-6a08d2bed629.png)

**Comment by vikiival** [comment]
As I mentioned in - https://github.com/kodadot/rubick/issues/235

There was a bug on indexer I updated new version and it seems to be working correctly
