### ISSUE TITLE
Congratulations pop-up appeared too soon

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5622]
Got this on **beta**: 
Triet to buy [this](https://beta.kodadot.xyz/ksm/gallery/15975192-7092505797a30ccf48-NEON%20BABES-NEON_BABE_11-00000011?page=4) RMRK2 NFT.

The moment I clicked on Buy - Confirm the pop-up appeared.
I did not have a chance to sign up the transaction first.  

<img width="1443" alt="Screenshot 2023-04-12 at 15 01 12" src="https://user-images.githubusercontent.com/104380776/231466201-4dc35447-faf6-41da-b4ae-259aab211e16.png">

Video here
---

https://user-images.githubusercontent.com/104380776/231466694-dfa7308f-1a10-43ce-96e5-c41f22d4d67a.mov

**Comment by JustLuuuu** [comment]
After buying one a.. in the end I got only this sad pop-up:
<img width="514" alt="Screenshot 2023-04-12 at 15 16 50" src="https://user-images.githubusercontent.com/104380776/231469520-5de54da6-2515-440b-9e1c-9ed3f6f2c8a1.png">

**Comment by exezbcz** [comment]
yeah, this is not specific to rmrk2
- #5458

- It would be helpful to display the congratulations after the transaction has been completed.
