### ISSUE TITLE
Landing page KSM price is different from actual NFT price

### ISSUE THREAD

**Issue by degenofdotsama** [kodadot/nft-gallery#5624]
### Is your feature request related to a problem?

the Newly listed NFTs show a price but if you click on the NFT it then displays a much lower price.  This price difference may cause NFTs to be overlooked and passed over due to a much higher cost than the NFT is actually listed for on the site.

### Describe the solution you would like

Sync the prices

### Describe alternatives you have considered

none

### Screenshots

<img width="516" alt="Screenshot 2023-04-12 at 08 53 28" src="https://user-images.githubusercontent.com/88508554/231480698-4bfa3aea-29ec-40ad-b162-258d3816195d.png">
<img width="1034" alt="Screenshot 2023-04-12 at 08 54 16" src="https://user-images.githubusercontent.com/88508554/231480708-4e2678e1-b5ff-4f09-b68e-e7bbab8c2f79.png">
<img width="1042" alt="Screenshot 2023-04-12 at 08 54 39" src="https://user-images.githubusercontent.com/88508554/231480719-006a18d3-b8d4-4aab-badb-1a05d8f7367e.png">

**Comment by JustLuuuu** [comment]
Yeah, I can confirm that probably all **New Listed** NFTs on the https://kodadot.xyz/ landing page that are RMRK2 have the wrong prices.

**Comment by vikiival** [comment]
The prices in detail are correct

**Comment by yangwao** [comment]
I guess it's issue that Singular shows prices calculated with their fee and not real on-chain prices?
