### ISSUE TITLE
Make SimpleMint workable with RMRK2

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#5645]
### What happened?

After 
- #5631 
will be merged minting on KodaDot can be intergrated.

Currently Simple mint supports only V1 and it would be nice to support V2

### Please reproduce in steps

~

### Expected Behavior

Mint should work with Simple mint

**BLOCKED BECAUSE we need to figure out how to do it without rewriting whole simple mint**

### Are you logged in?

None

### Screenshots

~

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Want someone take look on this one?

**Comment by roiLeo** [comment]
can we delete current simple mint as rmrkV1 is no longer relevant?

**Comment by yangwao** [comment]
> can we delete current simple mint as rmrkV1 is no longer relevant?

yes
- #5939
