### ISSUE TITLE
add popular basilisk collections for sidebar 👀🤝

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5656]
we could probably do this for basilisk collections 👀🤝

@JustLuuuu if you could help point out for bsx collections

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/pull/5654#issuecomment-1507427877_

**Comment by floyd-li** [comment]
should i add these all for `bsx`?

**Comment by roiLeo** [comment]
closed by #5756
