### ISSUE TITLE
Squash reviewpad comments into one and update one comment after push 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5660]
Hey I love @reviewpad service it's providing us @marcelosousa, yet it's bit spammy now, especially in our PRs which goes lot of discussions and especially amount of iterations we have in one PR, like push new code after code review from someone.

Would be possible squash these messages into one comment and best updating that one comment? 
Seems it's now post **two messages everytime someone do push**  and then I need scrolling through to gain overview about PR, where half screen is reviewpad 😄

I would like to see if it would be possible to update original comment as it will stay on top and not dilute discussion, wyt? 

- https://github.com/kodadot/nft-gallery/pull/5581

![image](https://user-images.githubusercontent.com/5887929/232038543-9fd3b860-4112-4b61-8b41-5330bbc13e96.png)

![image](https://user-images.githubusercontent.com/5887929/232038605-260a26ba-1f7b-48c0-b124-7ce37ae2d0b4.png)

**Comment by vikiival** [comment]
cc @marcelosousa 🥺 🙏

**Comment by marcelosousa** [comment]
Thanks for that feedback. We're working on it!
In the meantime I've opened https://github.com/kodadot/nft-gallery/pull/5663 so that the automatic summarize only happens when the PR is opened. Then during the PR process, anyone can use `/reviewpad summarize` to get the summary at that moment.

**Comment by vikiival** [comment]
Love it, thank you very much ❤️
