### ISSUE TITLE
Sidebars open over each other

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5672]
- the sidebars are stacking on top of each other - notification sidebar and wallet sidebar 
- it should close the last one and open the new one 
- the overlay is also applied twice now - screen gets even darker 
![image](https://user-images.githubusercontent.com/90852205/232143869-edf00129-b24e-45f3-83d6-9dbc804d84c8.png)
![image](https://user-images.githubusercontent.com/90852205/232143961-c4e39398-b476-43f1-b3c1-5471c8441acf.png)

**Comment by yangwao** [comment]
sidebar enabled in pinia store soon

**Comment by exezbcz** [comment]
wallet sidebar double stacking as well 
- open sidebar, switch network, open sidebar again

![image](https://user-images.githubusercontent.com/90852205/232223336-92d08dfb-9884-436b-ae14-60fa580b4d10.png)
![image](https://user-images.githubusercontent.com/90852205/232223347-93e92e8d-cbdf-43e1-8d68-54d7938571e0.png)

**Comment by exezbcz** [comment]
any update on this? 👀

**Comment by exezbcz** [comment]
![Trade Offer](https://github.com/kodadot/nft-gallery/assets/90852205/4f69c892-c7f7-4545-9e40-7d195f7edce6)

**Comment by exezbcz** [comment]
lmao not sure whether I have the creativity to create better meme :D

**Comment by exezbcz** [comment]
![Sad Pablo Escobar](https://github.com/kodadot/nft-gallery/assets/90852205/e8d23497-5063-49f0-9417-eefb045d1959)

**Comment by roiLeo** [comment]
This one not so easy, I've wasted a lot of time trying to find a proper way to correct this problem.

either we try to correct it with what we currently have (but in a few months this code will no longer be used), or we can try to migrate to #6277 first, I vote 2nd option

**Comment by exezbcz** [comment]
> or we can try to migrate to #6277 first, I vote 2nd option

Yup, I am for the long-term solutions. 


 
> edit2: nvm found a workaround (#6407)

nice! I will check
