### ISSUE TITLE
Sort popular collection alphabetically

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5680]
Once done
- #5384 

![image](https://user-images.githubusercontent.com/5887929/232222817-dc7278a8-7f8e-43cd-9ae0-f94ca542ba95.png)

**Comment by floyd-li** [comment]
added in this commit https://github.com/kodadot/nft-gallery/pull/5654/commits/5c663ea78d5fb4c2a49ce17e247960c2c5c35276

**Comment by roiLeo** [comment]
closed by #5654
