### ISSUE TITLE
Show latest list price of item on newest list at landing

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5686]
on landing newest list shows 222 KSM

![image](https://user-images.githubusercontent.com/5887929/232233946-5a527ccd-0abd-40d5-8efc-ab5e627495ab.png)

when u click u see 90

https://canary.kodadot.xyz/ksm/gallery/12153247-dac5c7f54029d0e73c-HXAI8-TWENTYFOURSEVEN-00000085

![image](https://user-images.githubusercontent.com/5887929/232233927-c256bb43-da7a-448e-a009-10bd312a7120.png)

**Comment by roiLeo** [comment]
indexer issue
