### ISSUE TITLE
Scroll loading on collection

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5692]
once the end is reached and you want to scroll up, there is a weird event when it removes some items, than add them again, hover them all and again.  

see video: 

https://user-images.githubusercontent.com/90852205/232286855-8bae145e-a0b6-450d-9935-a32358d5d446.mov

tested here: https://canary.kodadot.xyz/ksm/collection/a0c4801b6dbf04c674-P1Z70?listed=true&sort=price_ASC

**Comment by yangwao** [comment]
infinity scroll booty call

<img src="https://media2.giphy.com/media/dZEoQE2qlzwx3IP98G/giphy.gif"/>

**Comment by Jarsen136** [comment]
I seem could not reproduce the scroll bug on my side.

![Kapture 2023-04-20 at 12 29 27](https://user-images.githubusercontent.com/31397967/233260149-8ff06da0-df68-4a27-b74c-df30d28b2a75.gif)

**Comment by exezbcz** [comment]
@Jarsen136 dont scroll continuously, the thing is that its loading in a weird way, just wait on the end a bit, once it loads scroll down, wait, scroll up - still happens to me, try that on explore as well

**Comment by Jarsen136** [comment]
> @Jarsen136 dont scroll continuously, the thing is that its loading in a weird way, just wait on the end a bit, once it loads scroll down, wait, scroll up - still happens to me, try that on explore as well

I did scroll down and wait on the end for a while, but still could not reproduce it. I guess it's a compatibility issue related to Windows OS or browser.

**Comment by exezbcz** [comment]
@Jarsen136 I am on osx, chrome

**Comment by JustLuuuu** [comment]
I have the same issue when I tried to sort Kusama NFTs by price low.

https://user-images.githubusercontent.com/104380776/233967354-4f36b401-56ac-42b7-add8-40bfeb87f8ff.mov

**Comment by roiLeo** [comment]
closed by #7110
