### ISSUE TITLE
NFT Interaction history 

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#570]
**Is your feature request related to a problem? Please describe.**
As user I would like to see the interactions  in the NFT detail

**Describe the solution you'd like**
Simple accordion card under the share card in NFT detail

**Additional context**
there is field for that called interactions in the graphQL.

So task is simple:
- [ ] have a table with following columns -> Type From To Amount Date
- [ ] extend the graphql query with the interaction field
- [ ] show :)

In case of any question feel free to hit me up on Discord/ Telegram/ Twitter.

**Comment by yangwao** [comment]
I guess we have designs from Xylo somewhere on this 👀

Maybe we could add some graph as OpenSea has?

https://opensea.io/assets/0x1a92f7381b9f03921564a437210bb9396471050c/5503
![image](https://user-images.githubusercontent.com/5887929/125273044-d0f8a180-e30c-11eb-95db-6f845b779d65.png)
