### ISSUE TITLE
Artist dashboard

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#571]
**Is your feature request related to a problem? Please describe.**
As a creator I would love to see statistics for myself
- Total earned
- Number of sales
- Avg history price
- [add your creativity here]

**Additional context**
This can be done by one or two queries via subquery (I can help here)

For Chart library I don't have any preference.

In case of any question feel free to hit me up on Discord/ Telegram/ Twitter.

### Ref 
- #1285

**Comment by yangwao** [comment]
Continue to #1285
