### ISSUE TITLE
Showing accurate item count on collection card

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5734]
I went through the search bar, searched 420, clicked on collection and there is only 1 item 
![image](https://user-images.githubusercontent.com/90852205/233276046-a3947954-28a4-4ba2-91c3-ee6052f97d19.png)

if i check the same collection on explore, it has 110 items
![image](https://user-images.githubusercontent.com/90852205/233276117-2eea5631-0bcf-439b-908c-20cd9834b640.png)
- when I click on the collection card, there is only one item as well 

no sorting applied

**Comment by exezbcz** [comment]
ah, found the problem, I was at the rmrk1 network

on rmrk2, there is like 3 of the same collections 
![image](https://user-images.githubusercontent.com/90852205/233276981-ccfe7efa-904a-472a-ab61-7543fd971dda.png)
is it a bug or its a duplicate? Same goes for the rmrk1 collection

**Comment by roiLeo** [comment]
> searched 420, clicked on collection and there is only 1 item

😎 
 
> if i check the same collection on explore, it has 110 items ![image](https://user-images.githubusercontent.com/90852205/233276117-2eea5631-0bcf-439b-908c-20cd9834b640.png)
> 
>     * when I click on the collection card, there is only one item as well
> 
> 
> no sorting applied

Items are burned since they have migrated on rmrkv2

![Capture d’écran 2023-04-20 à 8 50 04 AM](https://user-images.githubusercontent.com/9987732/233284030-cd273437-bd97-49c5-a719-5a5572dcd3d7.png)

> on rmrk2, there is like 3 of the same collections ... is it a bug or its a duplicate? Same goes for the rmrk1 collection

Looks the same but not the same, check out description, Id and stuff.

**Comment by exezbcz** [comment]
> Items are burned since they have migrated on rmrkv2

yeah, oki, we should display the real item count on collection card then?

**Comment by roiLeo** [comment]
> yeah, oki, we should display the real item count on collection card then?

hmm.. we won't be able to see original nftCount? are we sure about that?

**Comment by exezbcz** [comment]
@roiLeo that is not original no? I am thinking about displaying the actual count of items, after burning

**Comment by roiLeo** [comment]
> @roiLeo that is not original no? I am thinking about displaying the actual count of items, after burning

`nftCount`: 110 => means that the creator mint 110 items
`supply`: 1 => means that there is only 1 item available (not burned)

Question is should we keep original nftCount? 
I would still like to keep somewhere the possibility of knowing how many items where mint on the collection.
