### ISSUE TITLE
Use new resolver for stats in collection view

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5737]
We will have faster loading times on collection views

- https://github.com/kodadot/loligo/issues/10

RMRK2
---
- https://github.com/kodadot/rubick/pull/236 - waiting for deployment iirc @vikiival will write when it's done 

Basilisk
---
- https://github.com/kodadot/snek/pull/170

**Comment by JustLuuuu** [comment]
stats changed
