### ISSUE TITLE
square for NFTs in search bar

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5744]
oh if we can get square for NFTs like in 
- https://github.com/kodadot/nft-gallery/pull/5738

I've forgot about to add that to issue :|

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/5742#issuecomment-1516691802_

**Comment by Jarsen136** [comment]
Yes, it would work as expected after merging into main branch.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/31397967/233519230-36aafd9e-2820-4f94-946c-75283828b25f.png">
