### ISSUE TITLE
Custom metadata // Bring your own Metadata

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#575]
**Is your feature request related to a problem? Please describe.**
As user I would like to add custom traits to the attributes array.

**Describe the solution you'd like**
Have button along with to add custom metadata

**Comment by chris-saburo** [comment]
Hi @vikiival I am willing to work for this tasks. :)

**Comment by chris-saburo** [comment]
@vikiival @yangwao  where should I add the button for metainfo ?

**Comment by vikiival** [comment]
Currently to we pass tags to the metadata (check example [here](https://gateway.pinata.cloud/ipfs/Qme5pysggSArv38AUF6BfVXkCjoKZUYf5E5XivnwP2Q3Dj)) which is basically [Attribute[]](https://github.com/kodadot/nft-gallery/blob/494134e799030ff6fa016fa40afe5369eab1cc4c/src/components/rmrk/service/scheme.ts#L17).

The goal here is to have a [Collapse](https://buefy.org/documentation/collapse) with an additional form which will contains all properties of the [Attribute](https://github.com/kodadot/nft-gallery/blob/494134e799030ff6fa016fa40afe5369eab1cc4c/src/components/rmrk/service/scheme.ts#L17) (display_type, trait_type, value). After submit a form should be cleared and the "new" tag should be added to the existing `<TagInput/>`

Checks: 
 - [ ] create separated component (Attribute Form)
 - [ ] create separated component (Attribute form within Collapse)
 - [ ] on submit clear attribute form and add the tag to the tag input values
 - [ ] make sure that it is pinned correctly

**Comment by yangwao** [comment]
Related https://github.com/kodadot/nft-gallery/issues/417

**Comment by vikiival** [comment]
Closed by a36283484470f1cea1b444ca09eb8ac34709ee62
