### ISSUE TITLE
Tagging your NFT as NSFW does nothing

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5762]
### What happened?

For example [this NFT](https://kodadot.xyz/rmrk/gallery/17384275-C46E1CCC37647EC061-NEO-FEMAI_5-0000000000000005). I can see in properties that it is NSFW but still, it's possible to see it in explorer, newest list and etc.

### Suggestions:
- add in settings a button that will allow you to hide all NSFW content (make sure that settings stay the same even after you log out - right now, everything you set in settings will be changed back to default when you log out and log in again)
- blurr picture + small icon on the picture with NSWF text (so people know that it is not blurry NFT uploaded but SWF)
- when you click on this blurred NFT you get a notification that this NFT is NSWF do you want to open it?
- add a filter in collection/NFT explorer - filter out NSF works.

I would not:
- hide picture from explorer + newest list, latest sale - this can be discriminating for artists (blurring + other suggestions should be enough)

### Please reproduce in steps

Check [this](https://kodadot.xyz/rmrk/collection/C46E1CCC37647EC061-NEO?page=1) collection.

### Expected Behavior

Do something to prevent us from becoming a porn site.

### Are you logged in?

None

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
Link #285 & #5455
