### ISSUE TITLE
Settings - Interface - most of these tings do nothing?

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5764]
I opened this issue a few moments ago:
- #5763 

I played with settings even more and it looks like most of the things in the **settings Interface** do nothing. Maybe its time to check everything we have there, **_delete things we are not using or are not working, and make it simple_**. Keep only the necessary stuff. It's better to have fewer options that are working .

**Just a reminder** - these settings will change back to default every time you log off or you close the tab. So it's kinda useless to have a lot of settings if you need to change them every time you want to use kodadot platform.  

Same with turning off minting fees
- #5555

**Comment by Jarsen136** [comment]
> Just a reminder - these settings will change back to default every time you log off or you close the tab. So it's kinda useless to have a lot of settings if you need to change them every time you want to use kodadot platform.

>Same with turning off minting fees

> https://github.com/kodadot/nft-gallery/issues/5555

I will check it

**Comment by JustLuuuu** [comment]
<img width="1433" alt="Screenshot 2024-07-31 at 17 06 00" src="https://github.com/user-attachments/assets/07682bf3-73a4-4b18-8185-344511df6f20">
