### ISSUE TITLE
Hide FemAI Neo collection from production and beta

### ISSUE THREAD

**Issue by helloitsdamsky** [kodadot/nft-gallery#5779]
### Is your feature request related to a problem?

It’s a huge issue to see stuff like this on a public site which doesn’t have any 18+ restrictions. This is a huge problem and can backfire on us and hurt our credibility. Nobody cares that  it’s *permisionless*. We are running the platform and it’s our responsibility

### Describe the solution you would like

Until this is resolved, https://github.com/kodadot/nft-gallery/issues/5762

hide the collection from beta and kodadot.xyz

https://kodadot.xyz/rmrk/collection/C46E1CCC37647EC061-NEO?page=1

### Describe alternatives you have considered

//

### Screenshots

//

### Are there opened related issues?

//

**Comment by exezbcz** [comment]
- we can show it again after: 
- #5772

**Comment by roiLeo** [comment]
Hello, I understand your concern but we are not able to hide a particular collection.
We currently can hide all collections from `H1scXqBBis6xobc9tSWjqAiHAe8X71xcgkbau8xgWm2xc2a` address if it's important

**Comment by helloitsdamsky** [comment]
> We currently can hide all collections from `H1scXqBBis6xobc9tSWjqAiHAe8X71xcgkbau8xgWm2xc2a` address if it's important

Yes, it’s fairly important to push this to production site and beta until the issue above is resolved
