### ISSUE TITLE
New FAQs Questions

### ISSUE THREAD

**Issue by anettrolikova** [kodadot/nft-gallery#58]
- What does Accounts do? Can I insert address and see all artists work ?
- Why do I have to create collection then mint my NFT?
- What is multimedia data?
- How can I delete my artwork from KodaDot gallery if I uploaded wrong format?
- What format of picture and multimedia is the best for upload through  KodaDot ? (JPG/PNG/ PSD and size in px/inch)

**Comment by yangwao** [comment]
📟  @cryptodamsky

**Comment by cryptodamsky** [comment]
SInce @thea-exe got rid of half of our FAQ and removed obsolete questions, these seem to be one of those that would definitely go out.
 
 If you don’t want to add any of these Q to our FAQ @thea-exe , we can close this issue. Just lmk.

**Comment by cryptodamsky** [comment]
We are not at the time of market where ppl would be asking or seeking answers for these question so once we will be, we can add them in or insert them into playbook. For now i dont see the importance to add those specific questions

**Comment by thea-exe** [comment]
Completely agree, we'll update our FAQ when KodaDot advances a bit more but these questions don't seem to be useful currently
