### ISSUE TITLE
upgrade to Node v19 or v20

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5800]
Seems we are also running old Node v16 which ends support this year.

Can we upgrade to v19 or v20?

![image](https://user-images.githubusercontent.com/5887929/234066546-207efbd8-4c19-44c0-a3da-e157e9fff7c6.png)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/5799#issuecomment-1520533352_

**Comment by preschian** [comment]
seems blocked. one package only support <17

```
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your Node version is incompatible with "/@apollo/federation/0.27.0_graphql@15.8.0".

Expected version: >=12.13.0 <17.0
```

**Comment by yangwao** [comment]
Can we open issue in their repository kindly asking them when there will be support newer version or find replacement? 
Also option to support them with small amount $ as sponsorship if that helps fater.

**Comment by preschian** [comment]
btw, the recommended version is using an even-numbered version. so, either v18 or v20. but for now, I think it's better to use v18, because active LTS is still on node v18

for a faster patch, I think we can patch that package. let me check

**Comment by yangwao** [comment]
okay let's go with v18  
it's still has active till oct2023 and maintanance 4/2025, hopefully we will be migrated till then to vue3 :)

**Comment by preschian** [comment]
> hopefully we will be migrated till then to vue3 :)

this is the big question. can we migrate to vue 3 🙈🤣
