### ISSUE TITLE
Why is offer status ACTIVE on offers that are expired?

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5803]
Can someone explain me this? Why is the status **active** if the offer is expired?
Go to your profile - offers made:
<img width="1432" alt="Screenshot 2023-04-25 at 09 17 36" src="https://user-images.githubusercontent.com/104380776/234202678-c342508d-32f4-41c7-8d79-fac803c3059f.png">

Is that intention or a bug? When the offer expires, the status should change to something else.

**Comment by roiLeo** [comment]
> Can someone explain me this? Why is the status **active** if the offer is expired? 

Offer is still `ACTIVE` but expired means that your offer amount (0.1000KSM) is still fronzen on chain.
You need to withdraw it in order to recover the amount. (https://github.com/kodadot/nft-gallery/issues/3790#issuecomment-1220609148)

> Is that intention or a bug?

it is indeed intentional (we have many issues related with this like #3401)

> When the offer expires, the status should change to something else.

Well since offer is still "ACTIVE" what should be the status then?

**Comment by JustLuuuu** [comment]
> Offer is still `ACTIVE` but expired means that your offer amount (0.1000KSM) is still fronzen on chain. You need to withdraw it in order to recover the amount. ([#3790 (comment)](https://github.com/kodadot/nft-gallery/issues/3790#issuecomment-1220609148))

Okay, I understand now. I did not know I needed to cancel my offer even after it had expired. I think we should add this information somewhere for people like me. 😄 Maybe just small text under the table saying that: _if your offer is expired, cancel it to release your locked KSM_.

I checked active offers in stats and there are a lot of them that are expired and still active:
<img width="1393" alt="Screenshot 2023-04-25 at 10 38 52" src="https://user-images.githubusercontent.com/104380776/234222539-69b9dedd-909b-47c5-a525-022963bafec7.png">

> Well since the offer is still "ACTIVE" what should be the status then?

In this case, keep it - now I understand the point of it 😅

Isn't it possible to make it automatic? Releasing KSM after expiration?

**Comment by roiLeo** [comment]
> Maybe just small text under the table saying that: _if your offer is expired, cancel it to release your locked KSM_.

🆙 this!

> Isn't it possible to make it automatic? Releasing KSM after expiration?

Nope I don't think it's possible since only NftOwner or the person sending the offer CAN withdraw the offer.
(ref kodadot/snek#13 to handle expired offers)
