### ISSUE TITLE
Gallery item detail doesn't canary

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5808]
Gallery item detail is not loading on canary 

- https://canary.kodadot.xyz/rmrk/gallery/17623223-883BD191919E9ECC15-CNR-013-0000000000000014

![image](https://user-images.githubusercontent.com/5887929/234278691-7ec407ca-1800-4b1a-8a72-23a1b0990c73.png)

**Comment by Jarsen136** [comment]
Fixed by https://github.com/kodadot/nft-gallery/pull/5809
