### ISSUE TITLE
Chain magically changes on reload from ksm to bsx on sales page and gives wrong results

### ISSUE THREAD

**Issue by prachi00** [kodadot/nft-gallery#5813]
### What happened?

https://www.loom.com/share/98e17a7eca7a47cdb4f692099db2e65a

### Please reproduce in steps

.

### Expected Behavior

.

### Are you logged in?

None

### Screenshots

.

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
won't fix, sales page are hidden for now
