### ISSUE TITLE
Profile sidebar simplifications // Smart & Simple Assets

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5820]
![image](https://user-images.githubusercontent.com/90852205/234785432-4a053760-bd66-4d02-b342-48d5fcbb858f.png)

### Design
- in handoff main file, page profile simplifications: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=145%3A4743&t=okpSSqS7Bxdgbqik-1

# Basics
- we will merge wallet sidebar and profile dropdown together
- after connecting, there will be only icon of your account
- after you connect, you can click on the icon - sidebar will open
- preconnect and after connect states will stay the same on mobile/desktop

### Desktop
- on desktop, you will have two button in the navbar, one being connect button, the other profile
- profile will keep its hover state - you can hover over to change language and dark mode
- connect button will open wallet connect

### Mobile
- options in burger menu staying the same 
![image](https://user-images.githubusercontent.com/90852205/234787217-2c4b331b-f471-4e25-8084-bf2e7d32a86b.png)
- once you click connect, wallet sidebar is opened

### Desktop
- connect button disappears, only profile icon is visible with your account icon

### Mobile 
- this section changes to: 
   - profile from account and wallet
   - light mode button is not there
![image](https://user-images.githubusercontent.com/90852205/234787671-67f0b4da-83ab-4279-b697-e16ba535ee0c.png)
- once you click account, top part remains the same, only the content changes - sidebar into mobile view 
![image](https://user-images.githubusercontent.com/90852205/234787982-87cf09ec-f51c-42d9-8d89-0bffbf1427dc.png)

## Sidebar 
- it's fairly similar to the wallet sidebar 
- top part saying its profile with cross close button
![image](https://user-images.githubusercontent.com/90852205/234788352-4d99e068-c81e-4fc1-89e6-64be455d1472.png)

### account part
(from left to right)
  - icon, without drop shadow this time
  - name on top, profile view underneath (name is address, or onchain id when possible)
  - copy and quit button - copy will result in tooltip saying - address added to clipboard (or something we already have) Quit button wont close the sidebar but will take you to wallet connect sidebar (this way we don't have to have a change account button) 
    - If i found out its its bad, we can change it in future 
  - button has a hover effect, see component in figma please
  
### Recent NFTs
- this serves as an small overview of the account, quick hint what nfts the wallet has. 
- there is room for 3 nfts, if user does not have any -> this section is not displayed and also heading recent nfts is removed 

### Assets
<img width="441" alt="image" src="https://user-images.githubusercontent.com/90852205/234800711-b49f905e-0b3e-43c7-b2fc-4ba28e759c43.png">

- basically a old wallet sidebar
- but we have to improve it so its displaying the correct data 
- network is added
- we dont have multichain yet in smart assets view
- #4865 
- portfolio view redirects to current assets page - it will be soon redesigned as well 
- add funds works like credit button now - ramp network

### Links 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/90852205/234803567-78dbea94-9aa0-44a2-b0e1-dc7330308991.png">

- the hover is only on the text itself - changing to its hover color (k-hovergrey in light mode, shade in dark mode) 
- the links will take you to other subpages 

### Bottom part
![image](https://user-images.githubusercontent.com/90852205/234887751-794644e6-7cdd-4237-94a0-f99fcb42adfb.png)
- dark mode, once you click it will change to dark mode and the text to light mode
- language - when you click, dropdown is displayed with all the language options 
![image](https://user-images.githubusercontent.com/90852205/234888053-4f3a8b32-e02f-4e35-a615-1b7fd61638b9.png)
- settings will take you to current settings page 
- hover on these things is following the design - k-grey to k-black in light mode, k-grey to k-white in darkmode 

### Other
- there is also screen with a small line/dialog saying create onchain identity
![image](https://user-images.githubusercontent.com/90852205/234889503-98ac3de1-fc8a-4051-99b2-0b9513f58373.png)
- It would be useful to notify users who do not already have a onchain identity.
- is it possible to show it to user few times, if they dont close it manually. If they do, remember to not show it again? Clicking outside the "close" area will take you to the onchain identity page

As always, if you have any questions, please ask 🚀 
Thanks!

**Comment by exezbcz** [comment]
![Sad Pablo Escobar](https://github.com/kodadot/nft-gallery/assets/90852205/8576dd80-f4e2-499a-883b-09753d367fa1)

**Comment by yangwao** [comment]
![X, X Everywhere](https://github.com/kodadot/nft-gallery/assets/5887929/aec227fe-b27c-4e36-b170-b2d60044957d)

**Comment by exezbcz** [comment]
@yangwao 
![Distracted Boyfriend](https://github.com/kodadot/nft-gallery/assets/90852205/1effed7b-be26-4b9a-ae68-b6c8886652cb)
pls like that

**Comment by roiLeo** [comment]
> we dont have multichain yet in smart assets view
> 
> [Multi-chain assets in wallet dialog #4865](https://github.com/kodadot/nft-gallery/issues/4865)

IMO this change without a proper Identity indexer will greatly increase loading time

**Comment by yangwao** [comment]
> Identity indexer will greatly increase loading time

indeed! boosting it
- https://github.com/kodadot/nft-gallery/issues/4753

**Comment by yangwao** [comment]
Anyone from @kodadot/internal-dev would like to pick this one?

**Comment by preschian** [comment]
> would like to pick this one?

I will try 👋

**Comment by preschian** [comment]
in progress:
- [x] https://github.com/kodadot/nft-gallery/pull/6112
- [x] https://github.com/kodadot/nft-gallery/pull/6131

1 left:
- [ ] unify sidebar on mobile and set identity
