### ISSUE TITLE
Inappropriate content on the landing

### ISSUE THREAD

**Issue by DeluneClaire** [kodadot/nft-gallery#5825]
### Is your feature request related to a problem?

I don't think this is a appropriate content which should be seen or if then definitely not on the landing

<img width="1396" alt="Snímek obrazovky 2023-04-28 v 12 02 04" src="https://user-images.githubusercontent.com/104791453/235118769-bc5f6645-f2b0-4eba-a09c-4ec387edb2bd.png">

### Describe the solution you would like

Hide it from the landing page and maybe add something like if its this kind of content then its blurred and it asks you if you want to see the content or no. But then even kids under 18 can sees it so... this probably should be even minted...

### Describe alternatives you have considered

-

**Comment by yangwao** [comment]
Being done in
- https://github.com/kodadot/nft-gallery/issues/5772
