### ISSUE TITLE
RMRK2 create - collection: Waiting is too long

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5827]
I created a collection on RMRK2 and I had to wait around 5 minutes for it to appear in Create - NFT. I think that is too long. Can we do something about it and make it a bit faster? So artists don't lose their patience. 

tested on beta

**Comment by yangwao** [comment]
> I had to wait around 5 minutes for it to appear in Create - NFT. I think that is too long. Can we do something about it and make it a bit faster? So artists don't lose their patience.

usually it's under <1 minute but I guess we are not refreshing that list iirc

- #4752
