### ISSUE TITLE
Collection preview not working on Twitter (again)

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5830]
Our favorite issue is here again guys. 😅 This time it is a link to collections. It would be cool to have a nice preview. On Opengraph it is showing that it is supposed to look different. 
**Twitter post**: https://twitter.com/KodaDot/status/1650511041871093762 
<img width="637" alt="Screenshot 2023-04-29 at 11 30 34" src="https://user-images.githubusercontent.com/104380776/235295963-f5795183-52e5-4b49-989b-1c4d387425ae.png">

idk where is problem this time

**Comment by yangwao** [comment]
calling alchemist

<img src="https://giphy.com/gifs/desktoppaints-animation-cinemagraph-3tHY45vhVveLHbBBWx" />

**Comment by yangwao** [comment]
Seems working by opengraph, maybe twitter bots are fetching something differently? 
- #5567

**Comment by preschian** [comment]
> Our favorite issue is here again guys. 😅

oh no 😅

seems working now? afaik, there are no updates/changes/deployment from our side
![Screenshot 2023-05-02 165810](https://user-images.githubusercontent.com/734428/235637094-6e7069ee-5795-4f88-95b6-41722aef6fdf.png)

**Comment by roiLeo** [comment]
closed as completed
