### ISSUE TITLE
No top collection on rmrk2 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5837]
![image](https://user-images.githubusercontent.com/90852205/235362473-e818d420-b2a3-4785-b941-ad22d42ca2ea.png)

**Comment by exezbcz** [comment]
duplicate of #5343

I think I saw some top collection on landing - at least from rmrk1 no?

**Comment by yangwao** [comment]
yup closing in fav #5343 

your contribution counts
