### ISSUE TITLE
Migrate KodaDot into Nuxt framework 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#584]
We have quite big chunks loading upfront and would be great to move to Nuxt as the App is getting bigger and loads slower.
### Requirements to keep. 

- [Docs](https://nuxtjs.org/docs/2.x/features/rendering-modes)
- [ ] deployment through Netlify - simple keep it in jam stack as possible as we don't want to hustle servers, serverless is allowed :)
- [ ] would we need to migrate to vercel or can we stick with Netlify? For sake avoid switching costs at the current stage.

### What we will gain?
- [x] faster load times
- [x] better router?

**Comment by JKrupinski** [comment]
A lot of work to migrate
just FYI in august there will be public beta Nuxt 3
Q4 - Stable version for production

I wonder if it's possible to migrate to Nuxt 3 since you use a lot of packages which may not work with Vue 3

**Comment by vikiival** [comment]
What if we migrate to Nuxt 2 ? 

> since you use a lot of packages which may not work with Vue 3

Which ones ? I am aware that Buefy wont work

**Comment by JKrupinski** [comment]
> What if we migrate to Nuxt 2 ?
> 
> > since you use a lot of packages which may not work with Vue 3
> 
> Which ones ? I am aware that Buefy wont work

Didn't check which one's but you will now after creating new project with vue 3 and installing them

**Comment by JKrupinski** [comment]
> > A lot of work to migrate
> 
> Opportunity for you to get through challenges 
> 
> > just FYI in august there will be public beta Nuxt 3
> > Q4 - Stable version for production
> > I wonder if it's possible to migrate to Nuxt 3 since you use a lot of packages which may not work with Vue 3
> 
> Yeah, I would stick to Nuxt v2 till now :)
> Checking it right now and I would stick with 2.15 https://github.com/nuxt/nuxt.js/releases/tag/v2.15.7
> 
> I guess we would have a lot of improvements from that, like speedy load times and easier PR for other parachain teams and technologies there I guess so.

not sure when you will migrate to Nuxt 2 how easy it will be to migrate to Nuxt 3
but for sure it can be beneficial

**Comment by vikiival** [comment]
> not sure when you will migrate to Nuxt 2 how easy it will be to migrate to Nuxt 3
The problem is that we would have to rewrite all the components into the composition API.
However, we can use the [Nuxt Composition API](https://composition-api.nuxtjs.org) so the migration from Vue/Nuxt 2 -> 3 would be simplier

**Comment by yangwao** [comment]
> A lot of work to migrate just FYI in august there will be public beta Nuxt 3 Q4 - Stable version for production
> 
> I wonder if it's possible to migrate to Nuxt 3 since you use a lot of packages which may not work with Vue 3

lol actually fa6 so far works only with vue3

**Comment by yangwao** [comment]
Continue in #1060
