### ISSUE TITLE
Wrong prefix in create

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#5846]
### Step to reproduce:
- first go to https://canary.kodadot.xyz/rmrk/create/
- click on searchbar
- it show BSX items on RMRK chain

### Bonus
- we shouldn't fetch data on first load /rmrk/create
- `series` query should be fetch only when user click on navbar
- series limit to 5 data but we fetch 10 images
<img width="679" alt="Capture d’écran 2023-05-02 à 3 54 53 PM" src="https://user-images.githubusercontent.com/9987732/235687767-bad9969f-bb83-4d36-b98c-67c179146ae3.png">

**Comment by Jarsen136** [comment]
> ### Step to reproduce:
> * first go to https://canary.kodadot.xyz/rmrk/create/
> * click on searchbar
> * it show BSX items on RMRK chain

It should also be fixed in PR #5847
tesed on https://deploy-preview-5847--koda-canary.netlify.app/rmrk/create/





> 
> ### Bonus
> * we shouldn't fetch data on first load /rmrk/create

It's a prefetch for the search I guess.

> * `series` query should be fetch only when user click on navbar
> * series limit to 5 data but we fetch 10 images
> 

These things could be explored on another issue, as it's no related to the url `prefix`

**Comment by roiLeo** [comment]
closed by #5847
