### ISSUE TITLE
Emoji picker should have KodaDot colors

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#585]
**Is your feature request related to a problem? Please describe.**
As a user, I want to have an emoji picker in the KodaDot colors

Current emoji picker is gray  background and white borders
<img width="469" alt="Screenshot 2021-08-04 at 15 25 59" src="https://user-images.githubusercontent.com/22471030/128189256-edd35293-d507-48eb-aa9b-04bab091e152.png">

**Describe the solution you'd like**
I want the emoji picker to be black and it should have pink borders

**Describe alternatives you've considered**
Just edit the CSS variables for the emoji picker

**Comment by monstar1995** [comment]
![image](https://user-images.githubusercontent.com/56657208/128380845-f1dda531-d4e0-4ec5-a029-006c648af94c.png)
```
.emoji-picker {
  --ep-color-bg: #000 !important;
  --ep-color-border: #db2980 !important;
}
```

By adding this code, I was able to make the colors of emoji-picker like that.

**Comment by vikiival** [comment]
Hey @monstar1995, 
thanks for the comment! 

Can you make a PR please ? 

By the was also the input's background should be black I have missed that.
Also I would change the active color (green to pink)

**Comment by monstar1995** [comment]
@vikiival 
https://github.com/kodadot/nft-gallery/pull/588

**Comment by roiLeo** [comment]
I've seen on [component page](https://github.com/joaoeudes7/V-Emoji-Picker#props) that there is already a 'dark' prop that we can use.

![Screenshot 2021-08-12 at 15-49-04 Fading Pixel Head](https://user-images.githubusercontent.com/9987732/129208500-8611ee2d-03f7-4704-aabd-39ce76564eba.png)

You can still overide css after that
```css
--ep-color-bg: #191B1A;
--ep-color-sbg: #212221;
--ep-color-border: #3E3D42;
--ep-color-text: #f0f0f0;
--ep-color-active: #009688;
```
