### ISSUE TITLE
Checking your balance is confusing for people who are not familiar with KodaDot

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5850]
Checking your balance is confusing for people who are not familiar with KodaDot: 
---
Changing the network and changing the balance in your wallet can be really confusing for a newcomer.

I'm sure we had more issues with this but when you swap between networks and at the same time you have an open sidebar with your wallet, it shows you a weird balance. You need to turn off the sidebar, change the network and then open your wallet to see the current correct balance. If you don't close the sidebar your balance will probably be wrong (showing the wrong currency, not showing all assets etc.) In this case - it's necessary to refresh the page. BUT refreshing the page will change the network back to Basilisk. 

It's just a mix of smaller issues together I'm sure some of them were already opened. But imagine that you are newbie with no skills who wants to mint and you have no idea where your ksm is. 

Also, I just had a chat with one artist who was very confused about why he could not see his KSM in his wallet. He was connected to the BSX chain. If we want to be more user-friendly, we have to expect that people (especially artists) are not skilled enough to understand the differences between our networks. 

**Suggested solution:**
---
- wallet view: see all your assets on all networks together in the wallet without it changing when you change network. 
  - Assets on Kusama: ...... 
  - Assets on Basilisk: ..... 
- For now add to tutorials (I will also add some additional info for people who actually check tutorials - just some extra paragraph about being aware of what chain they are currently at and why they don't see their balance).

**Comment by JustLuuuu** [comment]
Added [this to tutorials](https://hello.kodadot.xyz/knowledgebase/tutorials/networks-on-kodadot) but still, if we want to be more user-friendly we need to think about better solutions.

**Comment by yangwao** [comment]
@JustLuuuu are some of your concerns solved here by new design @exezbcz ? 
- https://github.com/kodadot/nft-gallery/issues/5820

**Comment by JustLuuuu** [comment]
> @JustLuuuu are some of your concerns solved here by new design @exezbcz ?

yes

but not this one: 
- https://github.com/kodadot/nft-gallery/issues/4865 - being able to see all balances without changing network. looks like I will have to wait for this one a bit longer

**Comment by yangwao** [comment]
> * have to wait for this one a bit longer

hopefully summer would have bad weather so we don't go out often 😄

**Comment by exezbcz** [comment]
@JustLuuuu that is correct, I made a small improvement to display network next to the asset. Multichain hopefully soon...
