### ISSUE TITLE
All NFTs in collections are not visible

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5853]
UPDATE: if you open any collection on beta to see NFTs in it you cannot see them! 

Minted NFT not visible in collection: The artist minted this RMRK2 [collection](https://beta.kodadot.xyz/ksm/collection/7C4F2330F148B37477-CANARY/activity) on **beta**. Same on the **canary**: not visible. He also minted one NFT in the collection. When you open the collection you cannot see the NFT. "Whoops...."

<img width="1451" alt="Screenshot 2023-05-03 at 13 55 49" src="https://user-images.githubusercontent.com/104380776/235909988-e6b03a5a-880f-4b8e-bb8a-92443e7bb91c.png">

But you can see that it was minted in the Activity bar + you can see on the top right corner that there is 1 NFT (1 Item) in the collection. 
<img width="1437" alt="Screenshot 2023-05-03 at 13 55 57" src="https://user-images.githubusercontent.com/104380776/235909986-eef9b550-3a9d-4952-aafd-0fb7fd24af41.png">

**Comment by yangwao** [comment]
I sense it's something that @vikiival was promoting marck v3 to production...

**Comment by yangwao** [comment]
I think @vikiival didn't realized that which version and how we are using it and did not tested back?

https://github.com/kodadot/nft-gallery/blob/419759f0ad571ea2e1fddd1a1578a737d4f5cb46/utils/constants.ts#L49

https://github.com/kodadot/nft-gallery/blob/419759f0ad571ea2e1fddd1a1578a737d4f5cb46/libs/static/src/indexers.ts#L12

**Comment by vikiival** [comment]
Done

**Comment by yangwao** [comment]
Works at least on beta, idk why canary is dead 

![image](https://user-images.githubusercontent.com/5887929/236196730-ea5c016b-f928-44e6-8f4a-542fa808e902.png)

**Comment by yangwao** [comment]
We will be looking forward test for marckV3 on collection view
