### ISSUE TITLE
canary down? 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5861]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/90852205/236211265-66402b5e-4f1c-4804-824a-7136723048db.png">
- everything else works 
-

**Comment by yangwao** [comment]
seesm cf pages been down and sometimes if build doesn't builds, it remove existing & working deployment and replace it with... none. So I've did retry deployment and it has worked again. 

thank you for coming to my ted talk 

<img src="https://media3.giphy.com/media/kvQb0oRiksFy4WxWkb/giphy.gif"/>
