### ISSUE TITLE
Congratulations pop up too soon 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#5867]
first steps for: 
- #5458 
![image](https://user-images.githubusercontent.com/90852205/236470675-fe032a69-d894-4c83-b299-287c764723dd.png)

can we please make sure the congratulations and other popups are displayed after the actual transaction go through

- It would be ideal to resolve this by Saturday, as @JustLuuuuu will be having a workshop on buying nfts.

**Comment by JustLuuuu** [comment]
#5622

**Comment by exezbcz** [comment]
continue to #5622
