### ISSUE TITLE
Transfer: not working on production

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5878]
I wanted to use the transfer on KodaDot, but got stuck here:
<img width="1456" alt="Screenshot 2023-05-08 at 13 13 25" src="https://user-images.githubusercontent.com/104380776/236810154-f439de7a-7df4-4810-853f-ef7248add498.png">

Working on beta.

**Comment by yangwao** [comment]
worked for me on canary and it should be on production already
