### ISSUE TITLE
Miscellaneous edits

### ISSUE THREAD

**Issue by anettrolikova** [kodadot/nft-gallery#59]
- Credit to " Buy Kusama" or "Buy KSM"
- in Create rename "Token" to "NFT"
- replace telegram symbol in "Create Collection" with folder plus icon [https://fontawesome.com/icons/folder-plus?style=solid](https://fontawesome.com/icons/folder-plus?style=solid)
- replace TG symbol in "Mint Token" with image icon [https://fontawesome.com/icons/image?style=solid](https://fontawesome.com/icons/image?style=solid)
- in create change "i" icon for smaller
- delete switch and "Upload to KodaDot"
- in Content rename "Description" to "Artwork description"

**Comment by abhisar2006** [comment]
Hi,

- Buy KSM - Done
- Rename to NFT - Done
- Folder Icon - Not Done
- Cannot find this one
- Change to 'i' icon - done 
- In Gallery Item, Description shows as 'Legend'

**Comment by yangwao** [comment]
Seems resolved meanwhile, all good!
