### ISSUE TITLE
Make RMRK2 chain as default on rmrk2.kodadot.xyz

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5909]
can we set it as default on rmrk2.kodadot.xy too? 

so when someone opens rmrk2.kodadot.xyz it will switch them to rmrk2 :)

thanks!

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/5892#issuecomment-1540692133_

**Comment by yangwao** [comment]
@Jarsen136 can you bring this one up? Seems on rmrk2.kodadot.xyz doesn't switch to rmrk2 which is strange 🤔

**Comment by Jarsen136** [comment]
> @Jarsen136 can you bring this one up? Seems on rmrk2.kodadot.xyz doesn't switch to rmrk2 which is strange 🤔

It looks like `rmrk2.kodadot.xyz` did not be deployed with the same branch as on the `kodadot.xyz`. Could you pls check if it deploy properly?

**Comment by yangwao** [comment]
I see now, seems CloudFlare and Github has bad day

It works now, disabled cache well.

![image](https://github.com/kodadot/nft-gallery/assets/5887929/73db517a-c9c2-46f9-842a-6470c01c5162)
