### ISSUE TITLE
Keep user logged in with last used account as a default

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#592]
**Is your feature request related to a problem? Please describe.**
When you approve the permissions for the polkadot extension, app should select the first account as a default.

**Comment by mies47** [comment]
Hi @yangwao, I'd like to do this.

**Comment by yangwao** [comment]
probably #2516 related

**Comment by vikiival** [comment]
when #2574 will be merged this issue will become obsolete
