### ISSUE TITLE
RMRK2 search is slow

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5921]
I thought that I was not able to find any collections in search on rmrk2 - on production. The problem is that it was too slow and I had to wait a few seconds to get any results. 

First I got this message (picture). It would be better not to get a message about no results. Just let it load till it finds a specific collection. 

<img width="1447" alt="Screenshot 2023-05-11 at 14 10 15" src="https://github.com/kodadot/nft-gallery/assets/104380776/2b101505-ebac-4f0f-b4f7-a9e65f78c73e">

**Comment by vikiival** [comment]
- #5795

**Comment by yangwao** [comment]
> First I got this message (picture). It would be better not to get a message about no results. Just let it load till it finds a specific collection.

yes, I've spotted it 2mo+ ago and designed with @vikiival supercharged search as it's majority our hits 
- #5795
