### ISSUE TITLE
Twitter previews are on strike again

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5923]
It's this time of the month again when our Twitter previews are not working. 😂 on Kusama, NFT

I tried opengraph and it looks like this:
<img width="1426" alt="Screenshot 2023-05-11 at 16 23 37" src="https://github.com/kodadot/nft-gallery/assets/104380776/aed54c14-fe57-4310-8471-71a86bad3719">

**Comment by roiLeo** [comment]
This is a know issue (https://github.com/kodadot/workers/issues/88) maybe try to share with a `https://beta.kodadot.xyz/...` link

**Comment by yangwao** [comment]
Works on beta.
on production sadly doesn't work, something must happen due CF and Github outage, I would retry in week or so or try reach CF-pages support or idk what can be wrong here

**Comment by roiLeo** [comment]
continue in https://github.com/kodadot/workers/tree/main/ssr-opengraph
