### ISSUE TITLE
App should handle canceling tx correctly

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#594]
![D6960219-1967-4EB6-8BD0-DB38B15F25A2](https://user-images.githubusercontent.com/22471030/128695834-0082eec0-3b5f-4fee-af1f-ae20cfdc4d7e.jpeg)
.

**Comment by vikiival** [comment]
Chris is working on the issue

**Comment by chris-saburo** [comment]
@vikiival could you describe the more detail issue requirement? I did try to reproduce the issue so far but it didn't work out.
so I hope you would list more detail the way to reproduce the issue and then expected behaviour.

**Comment by vikiival** [comment]
Steps to reproduce
1. Open any nft detail
2. Emote
3. When the signer (extenstion) shows up cancel the transaction

**Comment by chris-saburo** [comment]
@vikiival 

![image](https://user-images.githubusercontent.com/47330358/129605173-646b66ea-be2a-4ace-ad48-64d197a4688b.png)

**Comment by yangwao** [comment]
> @vikiival
> 
> ![image](https://user-images.githubusercontent.com/47330358/129605173-646b66ea-be2a-4ace-ad48-64d197a4688b.png)
> 
> When I click the Emote, then it shows the above image.
> When I try to close it, it doesn't work. so that is issue. right?

yes, I recall so that's it, as originally I've reported it internally.

**Comment by chris-saburo** [comment]
Hi @yangwao , it is working correctly.
It is really strange...

**Comment by yangwao** [comment]
Thing is that loader will keep hang there until you click elsewhere and once you cancel transaction, it should go away as there nothing to wait from user perspective.
