### ISSUE TITLE
Some collections are not loading when using Statemine 

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#5940]
### What happened?

When testing the canary version of the NFT Gallery that uses the Statemine network, some collections/items do not load properly, some have a name but not load the image, some doesn't even have a name on it. 

### Please reproduce in steps

- Choose Statemine as your network
- Go to Explore Collections or items

### Expected Behavior

Every collection/ should load their images properly

### What browsers are you seeing the problem on?

Desktop Firefox

### At which address did you encounter bug?

canary.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### Screenshots

![images not loading properly](https://github.com/kodadot/nft-gallery/assets/36627808/01f89d70-e69c-4154-bd5c-2d4c749a24aa)
![itens not loading properly](https://github.com/kodadot/nft-gallery/assets/36627808/ce965173-7bbe-465c-a7d0-24f88f92d70c)
![unnamed collections](https://github.com/kodadot/nft-gallery/assets/36627808/bb5e8223-7637-4879-8279-9c5a3f24fc95)

### Relevant log output

```shell
error [BasicImage] to load: https://image-beta.w.kodadot.xyz/ipfs/QmYK58GeYcGMbjjfPDo69jsUU4A8PpLEyPcxBY1yJCSnD1 
error { target: img.has-ratio, isTrusted: true, srcElement: img.has-ratio, currentTarget: img.has-ratio, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
instrument.js:107:32
    j instrument.js:107
    value consola.browser.js:395
    value consola.browser.js:338
    a consola.browser.js:319
    value consola.browser.js:329
    value consola.browser.js:294
    onImageError BasicImage.vue:1
    VueJS 4
    emit chunk-07da0ba7.js:206
    onError chunk-07da0ba7.js:199
    VueJS 3
    r helpers.js:83
```

### Payment link for reward

https://kodadot.xyz/transfer?target=FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9&usdamount=??&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
feel free to reopn
