### ISSUE TITLE
Unable To mint on localhost

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#5949]
### What happened?

encounter while testing massmint minting
i am now unable to mint on RMRK on localhost

tested on main branch => not related to massmint itself

### Please reproduce in steps

on local host
kusama network
try minting an NFT
got ```unable to retrieve keypair 'H2a3UNNEUL7e2WZYR47twJr4KEbyXZn9gBYnWzxdpqyJ2Q3'```

### Expected Behavior

be able to mint

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

localhost

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Kusama

### Screenshots

![image](https://github.com/kodadot/nft-gallery/assets/22791238/29483ea5-77c7-4510-9904-cd942ec184f1)

![image](https://github.com/kodadot/nft-gallery/assets/22791238/cd3d3fc8-ae36-44c2-b3d8-549098d99422)

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
maybe https://docs.kodadot.xyz/tutorials/how-to-fix-error-keypair.html#_1-are-you-using-a-ledger-hardware-wallet can help?

**Comment by daiagi** [comment]
cheers :)
that was it
Thanks

**Comment by daiagi** [comment]
nope.
still have the issue

![image](https://github.com/kodadot/nft-gallery/assets/22791238/bf4c5370-8c09-4063-ac04-27dd582133d4)



![image](https://github.com/kodadot/nft-gallery/assets/22791238/9b45b2e7-9f7a-4d22-81a3-2699caf7c0f3)

**Comment by daiagi** [comment]
#### tried it all


- refresh meta
- remove other extensions
- update chrome
- re import wallets
- reinstall extension
- restart computer

nothing helped

**Comment by yangwao** [comment]
Seems same as 
- https://github.com/kodadot/nft-gallery/issues/5956


idea what's going on?

maybe some package update?


fyi on `beta` you can get working stuff

**Comment by preschian** [comment]
@daiagi @yangwao could you test with this PR https://github.com/kodadot/nft-gallery/pull/5958. tested on snek

![Screenshot 2023-05-14 153509](https://github.com/kodadot/nft-gallery/assets/734428/8d67ca75-63f1-46f4-b195-406218d629be)
