### ISSUE TITLE
Unable to run dev with new node 18 on Mac

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#5961]
### What happened?

`node: --openssl-legacy-provider is not allowed in NODE_OPTIONS`

### Please reproduce in steps

To be able to build

### Expected Behavior

~

### Are you logged in?

None

### Screenshots

<img width="848" alt="Screenshot 2023-05-14 at 16 25 56" src="https://github.com/kodadot/nft-gallery/assets/22471030/bbd53cf5-5ab8-4b8c-baca-b402f244ad1f">

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
It builds without that.

<img width="779" alt="Screenshot 2023-05-14 at 16 29 50" src="https://github.com/kodadot/nft-gallery/assets/22471030/2a3e8818-cb5e-4285-992f-48fdb1774dc1">

cc @preschian ?

**Comment by preschian** [comment]
> It builds without that.

hhmm, let me open the PR to remove that. afaik in the pipelines will fail, so we need to add that env on github actions, netlify, and cf

**Comment by roiLeo** [comment]
Build ok for me on OSX
```bash
> nuxi prepare && cross-env NODE_OPTIONS=--openssl-legacy-provider PORT=9090 nuxi dev

Nuxi 3.0.0                                                                                                                                                              08:58:43
✔ Sentry reporting is enabled (client side: enabled, server side: enabled)                                                                                  nuxt:sentry 08:58:44
ℹ Production build                                                                                                                                                      08:58:44
ℹ Bundling only for client side                                                                                                                                         08:58:44
ℹ Target: static                                                                                                                                                        08:58:44
ℹ Using components loader to optimize imports                                                                                                                           08:58:44
ℹ Discovered Components: .nuxt/components/readme.md                                                                                                                     08:58:44
✔ Builder initialized                                                                                                                                                   08:58:44
✔ Nuxt files generated                                                                                                                                                  08:58:44
✔ Types generated in .nuxt                                                                                                                                              08:58:44

                                                                                                                                                                        08:59:27
✔ Client
  Compiled successfully in 40.76s
✔ Nitro built in 186 ms                                                                                                                                           nitro 08:59:34
ℹ Waiting for file changes
```

**Comment by preschian** [comment]
> Build ok for me on OSX

interesting, does it fails in your local if remove `openssl-legacy-provider` env?

**Comment by roiLeo** [comment]
To update to node 18 I've just:
```
pnpm env use --global 18
pnpm add -g pnpm
```

**Comment by vikiival** [comment]
> What's in `boom-vuex-settings`? 👀

Research for #5979

**Comment by Jarsen136** [comment]
Build ok for me too on OSX 👀  
My node version is v18.16.0

<img width="304" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/4c30f4f6-048c-476d-a98d-e0c9cb702a8e">

**Comment by stephenjason89** [comment]
@vikiival i have the same issue on node 18.13
Upgrading to node 18.17 fixes it

**Comment by vikiival** [comment]
> @vikiival i have the same issue on node 18.13
> Upgrading to node 18.17 fixes it
> 
> https://github.com/kodadot/nft-gallery/pull/6651

I use dev-experimental so we can close this
