### ISSUE TITLE
can't see emojis on gallery Item

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#597]
**Describe the bug**
We can see emoji on gallery list but we can't see emoji on item when logged off.

**To Reproduce**
1. Go to Gallery
2. Find an Item with one or more emojis
3. Click on it
4. Emoji is not visible on Gallery item

**Expected behavior**
Show emojis on Item or hide it on list.

**Screenshots**
#### Gallery list with an emoji
![Screenshot 2021-08-12 at 15-19-41 Low minting fees and carbonless NFTs](https://user-images.githubusercontent.com/9987732/129203897-d6d03929-b231-4fd8-bf37-2c00a9ac2e79.png)

#### Gallery Item without emoji
![Screenshot 2021-08-12 at 15-20-46 Kulupu - Part of the Substrate DNA](https://user-images.githubusercontent.com/9987732/129204059-ac7ff769-4abd-43a4-b257-07f3f30b8e25.png)

**Additional context**
#589 related

**Comment by chris-saburo** [comment]
@vikiival @yangwao @roiLeo let me figure it out this issue.

**Comment by yangwao** [comment]
Seems fix in #598 wasn't correct because you want to show exact emojis like whenever you are logged in. 
I haven't realized that we want to show on gallery item exact emoji.
Till now it's reverted by #602 

@chris-saburo can you create a new PR where you fix it way users can see exact emojis?

**Comment by vikiival** [comment]
The bug appeared after we closed #589
