### ISSUE TITLE
💥⚰️ Vuex Options (MILESTONE)

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#5979]
I see that we are getting various unwanted side effects by having / maintaining [vuex-options](https://github.com/kodadot/packages/tree/main/vuex-options) 

So I will be adding issues to get rid of dependency on this package.
The it's deeply rooted in the codebase (because we were relying on it the past).
I'll be also hacking with some non-trivial ones

Tasks:
- [x] #5984
- [x] #5980
- [x] #5982
- [x] #5983

Issues caused by this:
- [x] #5977

**Comment by yangwao** [comment]
we got progress on this!

**Comment by roiLeo** [comment]
## TODO:
 in `transfer.vue`
- remove `dispatch('setApiUrl', ...)`
- replace `$store.getters['availableNodesByPrefix']`

**Comment by yangwao** [comment]
Related
---
- #6460 

cc @Jarsen136

**Comment by vikiival** [comment]
Does this mean we are out of vuex?

**Comment by vikiival** [comment]
<img width="1292" alt="Screenshot 2023-08-10 at 12 58 59" src="https://github.com/kodadot/nft-gallery/assets/22471030/f9c48670-7cc3-4449-8635-0ad33d581026">
