### ISSUE TITLE
Transfer works only for Kusama

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#5980]
I was trying PR #5969 which adds prefix for the routes.
Unfortunately I got into point when I was using `Statemine (stmn)` but I was connected on `Kusama`

(Image shows route `from` and top right is chain which it is going to use)
<img width="586" alt="Screenshot 2023-05-15 at 12 25 58" src="https://github.com/kodadot/nft-gallery/assets/22471030/257bb16f-fb73-438f-945a-900b31f9cba7">

Moreover commit b146f968e013babe10e9b24c750abdef34de7a11 added ability to try different RPCs.

Which can be solved more elegant

```ts
import { InstantApi as Api } from '@kodadot1/sub-api'
import { ALTERNATIVE_ENDPOINT_MAP } from '@kodadot1/static'

const { urlPrefix } = usePrefix()
const endpoints = ALTERNATIVE_ENDPOINT_MAP[urlPrefix]
const API = await (new API(endpoints)).getInstance()
```

Deliverables:
- [ ] Make sure that transfer works on any supported chain
- [ ] Remove dependency from vuex-options

**Comment by yangwao** [comment]
- #6100 
- #6088

**Comment by roiLeo** [comment]
#6245?

**Comment by daiagi** [comment]
@roiLeo  why reopened?

looks working (at least for statemine)
https://assethub-kusama.subscan.io/extrinsic/0xc5ff92734a21c796e603ba6cc4bca365e24c3f484067061018219d9cecc7a038

![image](https://github.com/kodadot/nft-gallery/assets/22791238/6a95ccb9-d482-4d05-ab92-78ec10b9a5c1)

**Comment by roiLeo** [comment]
> @roiLeo why reopened?
> 
> looks working (at least for statemine) https://assethub-kusama.subscan.io/extrinsic/0xc5ff92734a21c796e603ba6cc4bca365e24c3f484067061018219d9cecc7a038

I don't remember why I've link another issue, continue in #5575
