### ISSUE TITLE
Stop propagating setUrlPrefix

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#5982]
App should not dispatch `$store.dispatch('setUrlPrefix', value)` to update prefix in the Settings store

<img width="630" alt="Screenshot 2023-05-15 at 13 04 32" src="https://github.com/kodadot/nft-gallery/assets/22471030/b1b75881-fa58-40cc-9644-e788c608d52b">

**Comment by yangwao** [comment]
<img src="https://media2.giphy.com/media/l4JyMJghOyHyT2O9G/giphy.gif"/>

**Comment by vikiival** [comment]
Is that köttbullar coming to your belly?

**Comment by yangwao** [comment]
> coming to your belly?

or outside my belly 4th time today

**Comment by roiLeo** [comment]
closed by #6111
