### ISSUE TITLE
Remove dependency on `currentUrlPrefix`

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#5984]
The ultimate goal of KodaDot is to be a multichain explorer and if you want to do a specific action it should be located under the chain prefix.

However some parts of the app are dependent of the prefix from the `vuex-options` 

<img width="572" alt="Screenshot 2023-05-15 at 13 13 59" src="https://github.com/kodadot/nft-gallery/assets/22471030/752b0494-64de-4ce1-bfc1-20e1c0ba891c">

Make sure that :
- [ ] `usePrefix` is using prefix only from the url
- [ ] routes that needs **any** on-chain operation are under the prefix folder
- [ ] properly test

This is a non-trivial task so proceed with care

**Comment by roiLeo** [comment]
What do you think about rewritting it to pinia and move it under kodadot repo?

**Comment by yangwao** [comment]
<img src="https://media2.giphy.com/media/gpmARWm3Pwypq/giphy.gif"/>

**Comment by roiLeo** [comment]
<img width="362" alt="Capture d’écran 2023-06-16 à 10 17 18 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/037dca52-4713-4eba-954d-2f1b011e8348">

close in #6142
