### ISSUE TITLE
Collection activity

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5989]
https://canary.kodadot.xyz/stmn/collection/18/activity

![image](https://github.com/kodadot/nft-gallery/assets/5887929/c66bb241-3d22-4fb7-8731-e22face13192)

https://canary.kodadot.xyz/stmn/collection/117/activity

![image](https://github.com/kodadot/nft-gallery/assets/5887929/20e112fa-6fb9-457f-82cf-b12700a0fd78)

probably very important collection

https://canary.kodadot.xyz/stmn/collection/2022/activity

loads really long 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/47b45050-9a17-4e4c-8f5c-5ac19094c7a0)

**Comment by yangwao** [comment]
if anyone is up for grab

**Comment by daiagi** [comment]
hmm am i missing something or non of these collections exist on chain?

here is my collection, works fine:

https://canary.kodadot.xyz/stmn/collection/13/activity

and next collection id is 17 => collection 18, 117 and 2022 can't exist

![image](https://github.com/kodadot/nft-gallery/assets/22791238/2f8c7bba-fdfc-45d1-87fb-9e1ce1b8f7ee)

**Comment by daiagi** [comment]
collection 18 exists already
https://canary.kodadot.xyz/stmn/collection/18/activity

**Comment by daiagi** [comment]
closing as there is nothing to do here
collection activity on statemine works  already
