### ISSUE TITLE
Landing - Search

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5992]

**Comment by Jarsen136** [comment]
Could we also close issues #5990 and #5991 ?

**Comment by yangwao** [comment]
I search "Decoded" from landing 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/8f174319-b0a6-43ad-a152-01a647f3f8ca)

btw new stmn is gone and now ahk, hopefully end users won't be confused

![image](https://github.com/kodadot/nft-gallery/assets/5887929/264f3bb7-5a61-4444-9d16-ab34a7e8b25d)
