### ISSUE TITLE
Front page suggestions

### ISSUE THREAD

**Issue by anettrolikova** [kodadot/nft-gallery#60]
- "KodaDot NFT Explorer" should be out of the box and in the centre of page, delete waving emoji
- "🛍️👀 Browse & Shop NFT collectables" rename to " 🖼 Visit out NFT collectibles gallery"
- add FAQs into upper bar where is "create, gallery, extra"
- rename "🆕 New here? We have F.A.Q.!" to " ❓Visit our FAQs if you are struggling with KodaDot"
- "🖨 Create your NFT collectables" rename to " 🎨 Create your NFTs collectibles"
- "📣 Feedback? We'd be happy to discuss it." rename to " 🗣 Found issue? Have Feedback? Create issue on our GitHub"
- Twitter and Medium should be on bottom - bigger space between above links
- "Read our story, how we started." rename to "Read out stories"  or "Visit our Blog"

**Comment by XyloDrone** [comment]
If the new design is implemented as such, these should  be resolved 

![Screenshot 2021-05-19 at 00 09 02](https://user-images.githubusercontent.com/84407059/118734507-71af7100-b836-11eb-9758-e206b0ea8eb1.png)

@anettrolikova would like o hear your opinion on this as well :)

**Comment by XyloDrone** [comment]
FAQ and About design sections
![Screenshot 2021-05-19 at 00 46 37](https://user-images.githubusercontent.com/84407059/118736986-c1446b80-b83b-11eb-80bb-df2a03fdf549.png)
![Screenshot 2021-05-19 at 00 46 46](https://user-images.githubusercontent.com/84407059/118736987-c1dd0200-b83b-11eb-83ad-a170ed9599c0.png)

**Comment by anettrolikova** [comment]
I'm glad that KodaDot UI is getting some make over :) 

I have some feedback: 
Regarding the front page I'd suggest to put this part into the centre of the page (not leave it on left side)
![image](https://user-images.githubusercontent.com/44020788/118973899-79743000-b972-11eb-96d0-588361e76d3b.png)

Same with other elements on the rest of the mockups. I would suggest to place them to centre of the page instead of centring the elements on left

**Comment by vikiival** [comment]
Implemented  ❤️
