### ISSUE TITLE
Make a KodaDot instance for Westend

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#600]
- [x] Add westend to vue-settings
- [x] redeploy subquery instance on westend
- [x] Update instructions

**Comment by vikiival** [comment]
Make sure you are running the lastest main.

update `.env.local` 
```
VUE_APP_SUBQUERY_URL=https://api.subquery.network/sq/vikiival/magick-west
```

in `subquery.ts`
uncomment 
```ts
uri: process.env.VUE_APP_SUBQUERY_URL || 'https://api.subquery.network/sq/vikiival/magick'
```

To obtain some Westend Tokens (WND) [join faucet on Element](https://matrix.to/#/#westend_faucet:matrix.org)

**Comment by yangwao** [comment]
Please make PR to `main-westend` to have a public instance of that as well

**Comment by vikiival** [comment]
Still a thing for the Nuxt impl.

h/t @prachi00 for ping
