### ISSUE TITLE
Broken links on main page

### ISSUE THREAD

**Issue by poppyseedDev** [kodadot/nft-gallery#6003]
### What happened?

links on main page [Kodadot](https://kodadot.xyz/) are broken

that includes link pointing to:
 - faq.page https://hello.kodadot.xyz/knowledgebase/general-1/faq
 - about : https://hello.kodadot.xyz/knowledgebase/general/faq
 - referal program: https://hello.kodadot.xyz/knowledgebase/technical/kodadots-programs/artist-referral-program
 - artist ambasadors: https://hello.kodadot.xyz/knowledgebase/technical/kodadots-programs/artist-ambassador-program
 - ambasador program: https://hello.kodadot.xyz/knowledgebase/technical/kodadots-programs/ambassador-program

### Please reproduce in steps

Go to https://kodadot.xyz/ main page or https://beta.kodadot.xyz/

Links work in [canary.koda](https://canary.kodadot.xyz/)

### Expected Behavior

Change page links

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Are you logged in?

None

### Screenshots

![image](https://github.com/kodadot/nft-gallery/assets/30662672/331fca5f-cbf9-45f0-8a3b-ff7db122ab66)

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
Hello, this will be fixed in next release (check out https://canary.kodadot.xyz/ to see upcoming version)

**Comment by yangwao** [comment]
Being fixed in 
- https://github.com/kodadot/nft-gallery/pull/6009
