### ISSUE TITLE
Help users easier to report bugs 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#601]
Probably whenever user hit 404 like this one -> https://nft.kodadot.xyz//rmrk/detail/8816531-726ef17b504db9d71d-PARG-UNTITLED_5-0000000000000004 

We should link in the last sentence way to report bug easier for them `https://github.com/kodadot/nft-gallery/issues/new?assignees=&labels=bug&template=bug_report.md&title=`

For example

**If you think this should't happen, report us by [creating bug issue with steps to reproduce and screenshot](https://github.com/kodadot/nft-gallery/issues/new?assignees=&labels=bug&template=bug_report.md&title=)**

![image](https://user-images.githubusercontent.com/5887929/129697433-afad924b-89a4-4010-a76e-a85b7b731f67.png)

**Comment by roiLeo** [comment]
Closed in #640
