### ISSUE TITLE
Music Collection is not displayed correctly

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#6015]
### What happened?

The music collection is not displayed correctly. The browser only displays the cover image of the collection. The music format (mp3) is not displayed. 

### Please reproduce in steps

https://github.com/kodadot/nft-gallery/assets/81104034/12705db0-d27b-4dc8-a4c2-4413a8bf606a

### Expected Behavior

I was expecting a display similar to the Sungullar

### What browsers are you seeing the problem on?

Chrome, Firefox

### At which address did you encounter bug?

rmrk2.kodadot.xyz, beta.kodadot.xyz, kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

https://github.com/kodadot/nft-gallery/assets/81104034/0dbd02bc-69b3-41e3-822f-41fa6a93cd4b

### Payment link for reward

https://beta.kodadot.xyz/transfer?target=FqCJeGcPidYSsvvmT17fHVaYdE2nXMYgPsBn3CP9gugvZR5&usdamount=0&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
👋
