### ISSUE TITLE
Balance at address does not display correctly

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#6016]
### What happened?

After logging into my account via polkadotJS wallet, I get an incorrect balance. 

### Please reproduce in steps

I open a new browser window, I want to log in, I log in with my wallet 

### Expected Behavior

I was expecting correct balance data

### What browsers are you seeing the problem on?

Chrome, Firefox

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

![obrázok](https://github.com/kodadot/nft-gallery/assets/81104034/60e55df9-b5f6-4af3-8e52-916534417733)

![obrázok](https://github.com/kodadot/nft-gallery/assets/81104034/36b4bb4d-8d62-4190-90b3-cc17daaeff0b)

![obrázok](https://github.com/kodadot/nft-gallery/assets/81104034/766ec217-574b-4d11-8da9-730daef0db84)

### Payment link for reward

https://beta.kodadot.xyz/transfer?target=FqCJeGcPidYSsvvmT17fHVaYdE2nXMYgPsBn3CP9gugvZR5&usdamount=0&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by visitskyworld** [comment]
@yangwao can I take this one?

**Comment by yangwao** [comment]
> @yangwao can I take this one?

sure!

**Comment by roiLeo** [comment]
is it still relevant?

**Comment by roiLeo** [comment]
Feel free to reopen if it's still happening
