### ISSUE TITLE
Chose Network button dissapears when using mobile

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6029]
### What happened?

When resizing the screen or using a mobile phone to access Kodadot, the Change Network button disappears, making it only possible to change networks either by manually writing it in the address bar or choosing to browser assets in a specific network. 

### Please reproduce in steps

- Access Kodadot using a mobile phone
- try to change to a different network

### Expected Behavior

The change network button should be visible: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/247fdfd0-8a3d-4c4e-91f5-0c656db94518)

### What browsers are you seeing the problem on?

Desktop Firefox, Mobile Android Chrome, Mobile Firefox

### At which address did you encounter bug?

canary.kodadot.xyz, beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### At which chain did you encounter bug?

Basilisk, Kusama

### Screenshots

![image](https://github.com/kodadot/nft-gallery/assets/36627808/8d253760-c253-44de-99cb-1dac1eb2df44)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daiagi** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/22791238/a6e633de-cf37-4603-8ba9-d1fecf953660)

isn't this supposed to act as sort of network switch?

**Comment by exezbcz** [comment]
@daiagi nope, that is shortcut to explore/network

**Comment by brano-hozza** [comment]
👋🏼
