### ISSUE TITLE
Collection not showing when using different devices with same account - Nova Wallet | JSON acc

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6030]
### What happened?

Even tough I'm using the same account on both mobile phone and android emulator (JSON acc), it wont show the collection I've created on one of them. This issue happens when browsing the app trough Nova Wallet

### Please reproduce in steps

- Open Nova Wallet
- Create Collection
- Go to another device that is using the same account
- Try to fetch collections

### Expected Behavior

The same collection I've created should load if I'm using the same account on another device

### What browsers are you seeing the problem on?

Mobile Firefox

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Screenshots

<img src="https://github.com/kodadot/nft-gallery/assets/36627808/315c8bf1-044a-46cf-b498-75702029855e" height="500" height="100"><img src="https://github.com/kodadot/nft-gallery/assets/36627808/ca0af7af-8653-4cf9-8f83-e3abd7ba4468" height="500" height="100">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
Still happening?

**Comment by prury** [comment]
> Still happening?

nope, just retested, thank you
