### ISSUE TITLE
overlapping display at chart on mobile

### ISSUE THREAD

**Issue by poppyseedDev** [kodadot/nft-gallery#6037]
### What happened?

Overlapping display at charts on mobile

### Please reproduce in steps

Go to for example to

https://kodadot.xyz/ksm/gallery/12384490-c210bd52d397099b2c-JPS-JAPANDAS_238-00000238

### Expected Behavior

Easy to fix

### What browsers are you seeing the problem on?

Mobile Android Chrome, Mobile Firefox

### Are you logged in?

None

### Screenshots

![Screenshot_20230517_204232_Chrome](https://github.com/kodadot/nft-gallery/assets/30662672/c4f08e8b-c533-4600-b148-fb1f32708e7b)

### Payment link for reward

https://kodadot.xyz/rmrk/transfer?target=HsvQ55ffgH5o4pfMVFAvNR835PVrFjR1W7jisn6gD7F7jFu&usdamount=0&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daiagi** [comment]
@kodadot/design-squad where should the time range button be placed on mobile?
