### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by poppyseedDev** [kodadot/nft-gallery#6039]
### What happened?

Keyboard shortcuts not working

I think some of these shortcuts are a bit useless / nobody is using them. My suggestion is reduce the scope of shortcuts, so you can easily maintain them.

relevant issue: https://github.com/kodadot/nft-gallery/issues/2283

Shortcut | Action
-- | --
g + n | not working 
g + p | not working
g + r | not working - add only `?page=1` to end of url
g + a | not working
g + c | not working 
g + s | not working 
g + m | page does not exist - https://kodadot.xyz/ksm/mint
g + t | refreshes page, but nothing happens
g + i | works - Go to series insights - https://kodadot.xyz/series-insight
g + d | Go to creators directory - works but instead of going to creator dir, goes to spotlight - https://kodadot.xyz/spotlight
c + u | Copy current URL - works

---

Shortcut | Action
-- | --
e + p | not working
e + h | not working
e + d | not working
a + b | not working
a + s | not working
a + c | not working
a + l | not working

---

Shortcut | Action
-- | --
f + b | Filter buy now - works
f + n |  not working
f + o |  not working
f + e | not working
f + c | not working

### Please reproduce in steps

https://kodadot.xyz/settings?tab=keyboardShortcuts

### Expected Behavior

https://kodadot.xyz/settings?tab=keyboardShortcuts

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

No

### Screenshots

![image](https://github.com/kodadot/nft-gallery/assets/30662672/2d41b2c3-7b24-4a60-8c6f-95154064c901)

### Payment link for reward

https://kodadot.xyz/rmrk/transfer?target=HsvQ55ffgH5o4pfMVFAvNR835PVrFjR1W7jisn6gD7F7jFu&usdamount=0&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Good idea, we can sweep old ones as they are after redesigning not working and we will be looking on brining hot search first and make for power users more usable 
- https://github.com/kodadot/research/issues/61
