### ISSUE TITLE
Show prices with royalties on RMRK2

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#6042]
So there are differences between prices on rmrk2 on singular/Koda. Singular shows prices with their fee and royalties and on KodaDot we show what's real on-chain. On top of it, we also add royalties and a 3% market fee (but not visible fro users).

It would be nice to have the option to see the real price of NFT - so we avoid the issue when people pay more than they expect and become mad at us. I don't mind the way we do it but I think it's necessary to be able to see the right place. Imagine going shopping buying something for 50 USD and then paying 70. 

This can backlash on us.

**Comment by helloitsdamsky** [comment]
> I would display it with fees and royalties as a consumer you want to know what you are actually paying. no one likes hidden taxes 🙂
