### ISSUE TITLE
Artist unable to burn NFT for 3 months

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#6048]
This artist is writing me every few days. He is not able to burn one of his NFTs, not on production/beta/canary. I don't know what to say to him anymore. 

This issue was reported and solved previously but it did not work. I reopened it, but no one has picked it up yet. He has been waiting for it for 3 months. Please can someone check it?
- https://github.com/kodadot/nft-gallery/issues/5125

**Comment by roiLeo** [comment]
Tested on `/snek/gallery/807893860-6` and it worked for me.
I tried to reproduce the same situation on `/snek/gallery/3124270296-2` (Canceled offer, Item has price) and then tried to burned item but didn't work.

Here are the tx:
- (listed item) [0x730852e9db007e971e7595307a915286de951edc6dafc92d442cf31e5504375b](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-basilisk-rpc.hydration.dev#/explorer/query/0x730852e9db007e971e7595307a915286de951edc6dafc92d442cf31e5504375b)
- (unlisted item) [0x3cfc43aaeb29e176e0c422cd72f876601d885251061124048f277dae589f9ae5 ](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-basilisk-rpc.hydration.dev#/explorer/query/0x3cfc43aaeb29e176e0c422cd72f876601d885251061124048f277dae589f9ae5)

then I tweak a bit tx and it workd
- [0x34720dac5e92c51788690af367aca8e27b5182febc0d96150f73237aa11345f1](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-basilisk-rpc.hydration.dev#/explorer/query/0x34720dac5e92c51788690af367aca8e27b5182febc0d96150f73237aa11345f1)

I'll prepare a fix

**Comment by preschian** [comment]
may I know which button/page the artist clicked the burn button on?

seems like the artist call a different module
`module=utility, call=batch`
ref: https://basilisk.subscan.io/extrinsic/3388957-2

it should be
`module=nft, call=burn`
ref: https://basilisk.subscan.io/account/extrinsic/bXiT4QSofbPhtUzL78VR8vCSsSchoEHMcdFdNSgitSgpMqB7Y?module=nft&call=burn&result=all&signedChecked=signed%20only&startDate=&endDate=&startBlock=&endBlock=&timeType=date&version=94

**Comment by JustLuuuu** [comment]
Fixed by @roiLeo
