### ISSUE TITLE
Emotes should be grouped together

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#605]
**Describe the bug**
As you can see on the image below: NTF is emoted twice with the 😍 emoji.
<img width="1269" alt="Screenshot 2021-08-17 at 16 39 01" src="https://user-images.githubusercontent.com/22471030/129746847-3a224953-d8f1-4901-9c37-c402e9cd74d8.png">

**To Reproduce**
1. Go to [the NFT](https://nft.kodadot.xyz/rmrk/detail/8754764-5ec6b315c97f8f284b-EIB3Z-KULUPU_PART_OF_THE_SUBSTRATE_DNA-0000000000000004)
2. See error

**Expected behavior**
Instead of  2x[😍 1] I would like to have 1x [😍 2]

**Comment by roiLeo** [comment]
Don't know if these help but second emoji key is lowercase. I will try to fix this.
