### ISSUE TITLE
Add attribute button almost invisible

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6073]
### What happened?

The add attribute button is almost invisible when trying to create RMRK2 NFTs

### Please reproduce in steps

- Chose RMRK2 as chain
- Go to Create
- Click on "Show On Chain Attributes"

### Expected Behavior

Button should be more visible

### What browsers are you seeing the problem on?

Firefox

### At which address did you encounter bug?

canary.kodadot.xyz, beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### Screenshots

https://github.com/kodadot/nft-gallery/assets/36627808/1eb456ec-6c7b-4868-831b-9d5bdcf38e6b

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
DarkMode ftw!
