### ISSUE TITLE
Bug: BSX and Snek address Translation -> Can't Mint NFT

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#6074]
@prury you have discovered a bug with the wallet address not getting updated to ```bsx``` address
for me it seems to only happen on chrome and not in Firefox:

### Firefox - OK

![image](https://github.com/kodadot/nft-gallery/assets/22791238/9b3406f6-cdb0-4ddb-9363-1c42e3f2b0ca)

### Chrome - Not OK

![image](https://github.com/kodadot/nft-gallery/assets/22791238/b58fe494-6e20-4c51-8657-3f4500d8b0c1)

in chrome: works in canary, doesn't work in beta:

### Chrome - Canary - OK

![image](https://github.com/kodadot/nft-gallery/assets/22791238/3e8ec510-081e-4901-8b3d-3dc6062cf641)

### Chrome - Beta - Not OK

![image](https://github.com/kodadot/nft-gallery/assets/22791238/ad3b1638-43c0-4689-be63-c97b341bfd17)

### Firefox - Beta - OK

![image](https://github.com/kodadot/nft-gallery/assets/22791238/1e45ea69-c4aa-410a-af7a-7cbf60657a1a)

_Originally posted by @daiagi in https://github.com/kodadot/nft-gallery/issues/5882#issuecomment-1557922745_

**Comment by daiagi** [comment]
* https://github.com/kodadot/nft-gallery/pull/5882#issuecomment-1553956982

>oh, nvm, seems like I've got an unrelated issue. reproduce:
>1. visit other than `snek` pages, e.g: https://canary.kodadot.xyz/rmrk/explore/collectibles
>2. open `snek` page in a new tab, e.g: https://canary.kodadot.xyz/snek/create/?tab=Collection
>3. bug: my wallet address is not updated to `snek` address

**Comment by daiagi** [comment]
update:
clearing local storage resolves it. not sure if anything more needs to be done

**Comment by roiLeo** [comment]
> update: disconnecting and reconnecting wallet resolves it clearing local storage also resolves it
> 
> not sure if anything else needs to be done here 

I can't reproduce it :(

**Comment by daiagi** [comment]
@roiLeo I think it had to do with a bad redirect in massmint that caused ksm format address to be written in local store instead of bsx format address


That issue is fixed
