### ISSUE TITLE
List KodaDot supporting RMRK2 in polkadot wiki

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6093]
2. In section https://wiki.polkadot.network/docs/learn-nft#rmrk 
> Two marketplaces for RMRK-based NFTs exist with hundreds of projects already launched:
> [Singular](https://singular.rmrk.app/), the official marketplace 
 I would add here Kodadot with link to items on RMRK2 https://rmrk2.kodadot.xyz/ksm/explore/items?listed=true

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/4847#issuecomment-1559691853_

**Comment by yangwao** [comment]
@poppyseeddev you want to take this? 👀

**Comment by yangwao** [comment]
> Hey there, is this still open? or not updated?

hey, yes!

Needs to be listed here I guess

**Comment by iMac7** [comment]
@yangwao the docs seem to have changed since the last time this issue was interacted with. 
[This](https://wiki.polkadot.network/docs/learn-nft-projects#kodadot) is now where there are details about Kodadot. Please confirm again where and what content should be posted if this is still relevant.

**Comment by springshine0925** [comment]
👋
