### ISSUE TITLE
Audio Resource follow-up

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#6108]
hello, good job! The audio is already working. If it could be:
1. put there an auto-stop when the second audio starts
2. cover image could be in the background of the player 

https://github.com/kodadot/nft-gallery/assets/81104034/9e0e3851-37e8-4667-94db-25dc94090203

_Originally posted by @jkdizajn in https://github.com/kodadot/nft-gallery/issues/6031#issuecomment-1563404515_

**Comment by roiLeo** [comment]
- ref #7275
