### ISSUE TITLE
Add ability to unlist NFT when is on sale

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#611]
When a user accidentally list NFT for sale, would be nice to have a button there ppl can unlist it but not burn it.
Now way around @vikiival suggest is to LIST it for 0 KSM which not everyone gets.
Having a dedicated **UNLIST** button would be way easier for creators to achieve.
![image](https://user-images.githubusercontent.com/5887929/130033708-013ab125-c865-4d96-a511-46eacdddc587.png)

**Comment by vikiival** [comment]
From the UX perspective I would put the `UNLIST` button under the price.


![Screenshot 2021-08-30 at 13 59 07](https://user-images.githubusercontent.com/22471030/131335829-29d2f279-dd8e-4048-8752-9db946b5e690.png)

<img width="298" alt="Screenshot 2021-08-30 at 13 59 11" src="https://user-images.githubusercontent.com/22471030/131335739-7595d23d-89fa-4ab0-a712-3d3021e8c586.png">
