### ISSUE TITLE
Neo input and Neo field follow up issues 

### ISSUE THREAD

**Issue by prachi00** [kodadot/nft-gallery#6116]
> 
> In case there is any desciptive text lets have it like this. It also done this here: #5939
> 
> <img alt="Screenshot 2023-05-22 at 17 55 04" width="769" src="https://user-images.githubusercontent.com/95911767/239963709-507db5ef-fd84-4f77-9682-fceb7e7130de.png">
> Also please change the error color to match our red which is #FF5757 (k-red) Either than that error messages can stay as is (under textfield left) until further change.

@prachi00 I posted this, not sure you've seen that. Still several things need change:
- Title is Bold
- title is 12px from textfield 
- if subtitle present, its 4px under title and 12px from textfield
- charcount is 4px under textfield, alligned right
- padding within a textfield is **16px on sides** and **12px Top&Bottom** 
- change error color to #FF5757 (k-red)

_Originally posted by @VladoTheBoi in https://github.com/kodadot/nft-gallery/issues/5870#issuecomment-1561894999_
    
    
    
    Others:
    

- [ ]  fix icon danger issue with oruga input
- [ ] alignment of add button in transfer

**Comment by roiLeo** [comment]
Imo we should make inputs looks the same as on https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=142-2180&t=CtA9QgCXL4bDR5c3-0

I'll check it if no one is assigned

**Comment by prury** [comment]
>  alignment of add button in transfer

You did fix most of it, but the one above is still missing
