### ISSUE TITLE
Update KodaDot sitemap generator

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6121]
Can we have new sitemap generator?

Currently we have google search console
![image](https://github.com/kodadot/nft-gallery/assets/5887929/69947d01-6a99-450e-b5a4-c580a3c3d635)

https://kodadot.xyz/sitemap.xml
I bet we have new pages meanwhile 😎

![image](https://github.com/kodadot/nft-gallery/assets/5887929/1fc58ca3-8b55-49ee-a09a-41ce89b6f219)

**Comment by roiLeo** [comment]
✌️

**Comment by yangwao** [comment]
got something to fix this one?
