### ISSUE TITLE
What files and pages we can delete from KodaDot?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6130]
Follow up from
- #4750 

To speed up migration, I would recommend 
- delete components/pages 
- migrate to 
  - hello.kodadot.xyz
  - developers.kodadot.xyz

Search candidates here
---
- https://github.com/search?q=repo%3Akodadot%2Fnft-gallery+nuxt-property-decorator&type=code&p=1

Candidates for deletion
---
- https://github.com/kodadot/nft-gallery/blob/56fb758084dfa61fa408e6bcb3ed2e496f4eceb7/pages/rmrk/create.vue#L17
- https://github.com/kodadot/nft-gallery/blob/56fb758084dfa61fa408e6bcb3ed2e496f4eceb7/pages/partnership.vue#L13
- https://github.com/kodadot/nft-gallery/blob/56fb758084dfa61fa408e6bcb3ed2e496f4eceb7/pages/rmrk/admin.vue#L6 (does it even work?)
- https://github.com/kodadot/nft-gallery/blob/56fb758084dfa61fa408e6bcb3ed2e496f4eceb7/components/rmrk/Create/Admin/AdminPanel.vue#L73
- https://github.com/kodadot/nft-gallery/blob/56fb758084dfa61fa408e6bcb3ed2e496f4eceb7/components/settings/KeyboardShortcuts.vue#L48 (we will have new anyway)
- https://github.com/kodadot/nft-gallery/blob/56fb758084dfa61fa408e6bcb3ed2e496f4eceb7/components/landing/EsSustainability.vue#L138 --> hello
- https://github.com/kodadot/nft-gallery/blob/56fb758084dfa61fa408e6bcb3ed2e496f4eceb7/pages/transform.vue#L33 - no needed I guess

**Comment by roiLeo** [comment]
completed, removed unused pages.

maybe https://github.com/kodadot/nft-gallery/blob/main/pages/sustainability.vue could be improved
