### ISSUE TITLE
Unable to buy BSX NFTs - Insufficient funds - Bridged KSM

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6134]
### What happened?

The Insufficient funds message shows even if i have some Basilisk KSM

https://github.com/kodadot/nft-gallery/assets/36627808/c052edf0-01a2-44b2-9ea7-b3e65cbb5f72

KSM as fee asset:
![image](https://github.com/kodadot/nft-gallery/assets/36627808/2c869b92-272d-44c4-a805-25a1f45ac662)

Related: [[#issue:58]](https://github.com/kodadot/nft-gallery/issues/5284)

Maybe it has to do with the ED for Basilisk KSM? Nope: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/41eceff3-f194-4ac2-8728-49612205e2eb)

### Please reproduce in steps

Just try to buy a BSX NFT with a low amount of Basilisk KSM

### Expected Behavior

To be able to click on the BUY button

### What browsers are you seeing the problem on?

Chrome, Firefox

### At which address did you encounter bug?

canary.kodadot.xyz, beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### Screenshots

Î

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
won't fix
