### ISSUE TITLE
 feat: Add volume sort to ExploreSort #5699 

### ISSUE THREAD

**Issue by ajeetj13006** [kodadot/nft-gallery#6136]
### What happened?

1. Sort by Filter Automatic deselected if page refresh: 
2. If Multiple Sort by filter Applied then List does not appear, List continuously Loading:

### Please reproduce in steps

Issue 1: 
Steps: 
a. Click the Sort by filter and select the Most Volume/ Least Volume
b. Wait for the Sorting 
c. Refresh the browser

Issue 2:  
Steps: 
a. Click the Sort by filter and select multiple filter
b. Wait for the Sorting 

### Expected Behavior

Issue 1:  After the browser refresh, Selected filter should not deselected Automatically

Issue 2: List should be sorted according to selected filter

### What browsers are you seeing the problem on?

Desktop Firefox

### Are you logged in?

None

### Screenshots

https://recordit.co/xH3DiV5mNR

 https://recordit.co/xbksIxHFvH

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
completed on AH
