### ISSUE TITLE
Mass mint UI for collectibles

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#614]
To mint collectibles, let's say 100+ NFTs, we need some better interface for the audience.
To achieve this, in v0 version would be nice to have folder structure or best, .zip
You'll first need a mint collection and then mint NFT inside it.

- [ ] select collection you minted in original UI
- [ ] way creator can select zip or multiple files
- [ ] description for NFTs could be in .txt or .json, supporting both would be perfect
- [ ] structure could be like, awesome_art.jpeg which will be matched with awesome_art.txt
- [ ] lines in particular order would be for 
  - NAME
  - Description
  - price
 
A. Mass mint every independent version
The next version could be like awesome_art_1.jpeg and awesome_art_2.jpeg and within instruction.txt could be inside file on each line structure like
  - awesome_art_1.jpeg
  - NAME
  - Description
  - price

This would preserve if you minting in other files and matching the description, maybe this would be interesting to have as well. 

B. Mass mint with the same desc, price and add a prefix to number # (by @jkdizajn)
- 1.jpg, 2.jpg, 3.jpg, 4.jpg &c
- NAME
- Description
- Price

If you want to work on this issue, DM me on Discord yangwao and we can work on that

**Comment by jkdizajn** [comment]
This would be very great for me...

**Comment by vikiival** [comment]
Work in progress
https://github.com/kodadot/nft-gallery/compare/main...614-mass-mint

**Comment by vikiival** [comment]
Tasks:
- [ ] Update Mass Mint to new pinning
- [ ] Ability to set price
- [ ] Test range query syntax

Good to have: 
- [ ] Write article

**Comment by vikiival** [comment]
UX/UI bugs

- [ ] show NFT's index
- [ ] if user has no collection redirect him/her to the Collection mint
- [ ] on NFT remove show notification

**Comment by yangwao** [comment]
Let's make PR and test it?

**Comment by vikiival** [comment]
Regarding to the `Mass Mint` implementation I haven't touch it since September 2021.

But what we learned: 
- It would be much safer to do it as a CLI or so.
- Because when the fileupload drops in the middle (let's say 50/100) you are basically f*ked

**Comment by joelamouche** [comment]
I am using a CLI script to mass mint Substraknights here (https://github.com/joelamouche/rmrk2-examples/tree/dev). Is this for rmrk?

**Comment by vikiival** [comment]
> Is this for rmrk?

I think generally for every chain. 
So far we have only RMRK Classic as a package `@kodadot1/minimark` but other chains/implementations will come.

**Comment by joelamouche** [comment]
Supporting every chain is going to be way more complicated...

**Comment by yangwao** [comment]
We will "resolve" it at 
- https://github.com/kodadot/nft-gallery/discussions/3898

**Comment by yangwao** [comment]
@VladoTheBoi is working on it, maybe some updates are coming soon 😏

**Comment by yangwao** [comment]
Continue to 
- #4964
