### ISSUE TITLE
Minting - not enough funds 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6143]
Correct me if I am wrong, but do I need bsx tokens to pay for mint? 
- if yes, it should be clearly stated that the tx costs this and that
![image](https://github.com/kodadot/nft-gallery/assets/90852205/efc23d58-ca16-423c-88ae-0f01a277e8d0)
- I have enough ksm on the Basilisk network, but it does not let me mint.

**Comment by JustLuuuu** [comment]
maybe related to #6134
