### ISSUE TITLE
Long item name: unable to see it all without openning

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6148]
### Is your feature request related to a problem?

When browsing trough a specific collection: https://canary.kodadot.xyz/ksm/collection/7C4F2330F148B37477-CELES?collectionId=7C4F2330F148B37477-CELES&listed=false and looking at a similar issue #6113, the same approach about adding a tool-tip when hovering trough a long named item inside a collection could help the user experience. 

in the collection above, the names are too large, and images are all the same, making it difficult for the user to check the series numbers. 

### Describe the solution you would like

tooltip when hovering over names

### Describe alternatives you have considered

|

### Screenshots

![image](https://github.com/kodadot/nft-gallery/assets/36627808/90bdc5c0-12ff-4615-9ce8-89fba643df4c)

**Comment by justskinny5** [comment]
@prury  @JustLuuuu Hi~ I noticed that it already had tooltip when hovering over names. So this feature request has already been done, right? Or is there anything I could do with it? 

![CleanShot 2023-08-25 at 15 34 19@2x](https://github.com/kodadot/nft-gallery/assets/17610879/d4d07b69-4b6d-4a02-9a3e-d1ee7d1c5ba7)

**Comment by prury** [comment]
> 
> @prury @JustLuuuu Hi~ I noticed that it already had tooltip when hovering over names. So this feature request has already been done, right? Or is there anything I could do with it?

humm, yeah, this one got solved already, just don't know by which PR

**Comment by justskinny5** [comment]
> > @prury @JustLuuuu Hi~ I noticed that it already had tooltip when hovering over names. So this feature request has already been done, right? Or is there anything I could do with it?
> 
> humm, yeah, this one got solved already, just don't know by which PR

get it. Let's close this issue~

**Comment by prury** [comment]
Already solved
