### ISSUE TITLE
Continue unlockable items page

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6163]
Tasks
---
- [x] https://github.com/kodadot/nft-gallery/issues/6204
- [ ] refactor unlockable items by comments in https://github.com/kodadot/nft-gallery/pull/6137#discussion_r1217605814
- [ ] add strip to running collection per drop (reuse same item from galery item/landing)
- [x] #6185 
- [x] #6205 
- [x] #6206 

happy line
---
- [x] #6186 
- [x] #6164
- [x] https://github.com/kodadot/nft-gallery/issues/6171

working version
---
- https://canary.kodadot.xyz/stmn/unlockable

_Originally posted by @daiagi in https://github.com/kodadot/nft-gallery/pull/6137#pullrequestreview-1462245688_

**Comment by yangwao** [comment]
@exezbcz can drop success notification
@daiagi if you want to help with mobile! :)

**Comment by yangwao** [comment]
hmmm seems we are missing phases on unlockable page @Jarsen136 👀

<img width="631" alt="image" src="https://github.com/kodadot/nft-gallery/assets/5887929/5afe73d7-49e2-47eb-9b53-ccf57f0fe3d7">

**Comment by Jarsen136** [comment]
> hmmm seems we are missing phases on unlockable page @Jarsen136 👀
> 
> 
> 
> <img width="631" alt="image" src="https://github.com/kodadot/nft-gallery/assets/5887929/5afe73d7-49e2-47eb-9b53-ccf57f0fe3d7">
> 
> 

These relevant code were commented by @vikiival. I will bring them back soon later

**Comment by yangwao** [comment]
I think it's not anymore p1, yet would be good to recheck

**Comment by roiLeo** [comment]
Done?

**Comment by vikiival** [comment]
> Done?

Cc @yangwao I think its done.
