### ISSUE TITLE
Profile Collection logos not loading - Canary

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6168]
### What happened?

When you go to the Profile page using the canary version, the images that should be the logo of each collection are not loading
(loads normally on beta)

### Please reproduce in steps

Log in -> Profile -> Collections tab

### Expected Behavior

Collection logos should load

### What browsers are you seeing the problem on?

Desktop Firefox

### At which address did you encounter bug?

canary.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### At which chain did you encounter bug?

Basilisk, Kusama

### Screenshots

![image](https://github.com/kodadot/nft-gallery/assets/36627808/996908c1-1a1a-48fb-906c-56cdd070661a)

### Relevant log output

```shell
no specific log shows up
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
Could you please share URL where it's happening? Do we have same behavior on beta?

**Comment by roiLeo** [comment]
> To check, you must have a collection of your own, check your profile page, inside the collections tab, and see if your collection logos load properly. Nope, beta is working properly

Alright! looks like it's happening on all chain

![Screenshot 2023-06-08 at 15-53-55 NFT Artist Profile on KodaDot KodaDot - NFT Market Explorer](https://github.com/kodadot/nft-gallery/assets/9987732/99f4d8e5-f3fb-4c92-8451-6fb13ffe587d)

**Comment by prury** [comment]
> > To check, you must have a collection of your own, check your profile page, inside the collections tab, and see if your collection logos load properly. Nope, beta is working properly
> 
> Alright! looks like it's happening on all chain
> 
> ![Screenshot 2023-06-08 at 15-53-55 NFT Artist Profile on KodaDot KodaDot - NFT Market Explorer](https://user-images.githubusercontent.com/9987732/244402295-99f4d8e5-f3fb-4c92-8451-6fb13ffe587d.png)

exactly!

**Comment by roiLeo** [comment]
wfm
<img width="1436" alt="Capture d’écran 2023-08-07 à 8 49 41 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/e47f752a-e366-4cf4-8bac-ee0d3bdd2448">
