### ISSUE TITLE
Add option to clear identity 

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6188]
### Is your feature request related to a problem?

When setting identities, we could also offer the possibility to clear that identity and getting the deposit back. 
would not make a lot of sense for some other chains, unless their token goes really up in value, but for Polkadot, the current deposit is around $100.

### Describe the solution you would like

- A button inside the identity page allowing the person to clear their identity.
- fields should be pre-filled with their existent identity.
- locked previous identity deposit could be shown

more info: 
https://support.polkadot.network/support/solutions/articles/65000181981#Clearing-an-Identity

### Describe alternatives you have considered

using polkadot.js

**Comment by exezbcz** [comment]
yeah totally missed this one, sorry for duplicate :D
