### ISSUE TITLE
Polkadot issue on canary

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#6198]
Compared to beta:  
- we have polkadot chain on canary ??? (see screenshot)
- we don't have polkadot balance in wallet anymore

<img width="1209" alt="Capture d’écran 2023-06-09 à 5 26 22 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/5636b16d-b12b-4e77-9f6d-88c9a862b4fa">

**Comment by yangwao** [comment]
> * we have polkadot chain on canary

it's for having DOT in routing in transfer iirc 

> * we don't have polkadot balance in wallet anymore

I can see 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/924348b7-deaa-4342-b011-2f2b16ee94a7)

Yet in some way we could hide it, but will be solved with multichain profile I guess
