### ISSUE TITLE
Disabling Other price options

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6225]
### What happened?

When creating a NFT on RMRK2, a lot of different units are shown as options

### Please reproduce in steps

RMRK2 -> Create - NFT - Price

### Expected Behavior

Only KSM should show

### What browsers are you seeing the problem on?

Firefox

### At which address did you encounter bug?

canary.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### Screenshots

![image](https://github.com/kodadot/nft-gallery/assets/36627808/532b8f85-7a48-4f1d-9ca2-24668f45323f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
Meanwhile 
![Screenshot 2023-10-17 at 16-18-56 Create carbonless NFTs](https://github.com/kodadot/nft-gallery/assets/9987732/d733e75d-61c0-40fb-91f3-8cf1e535727a)
