### ISSUE TITLE
Music nfts card visual

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6237]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/3dd57f6b-e076-4c28-b23c-57a34dbf7666)
- lets match the style to the cards around
- player to the middle of the "img" preview 
https://canary.kodadot.xyz/ksm/gallery/13943908-cc89eac7f82ae14164-BIRBTAPES

**Comment by roiLeo** [comment]
- ref #7275
