### ISSUE TITLE
Item not loading 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6238]
- looks like its a music nft
- its not loading 
- https://canary.kodadot.xyz/ksm/gallery/13943908-cc89eac7f82ae14164-BIRBTAPES
![image](https://github.com/kodadot/nft-gallery/assets/90852205/4fdbed94-aa5a-4390-9da8-e1f7ba8bd82d)

not sure if this works 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/a8911951-c20b-4f60-b2a9-7456d4136b06)

**Comment by roiLeo** [comment]
might be indexer issue 
<img width="740" alt="Capture d’écran 2023-06-15 à 5 23 30 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/d3be1b1e-4736-4cdb-9704-bea2ad7fabd4">

**Comment by roiLeo** [comment]
not on chain
