### ISSUE TITLE
Typing into navbar search input not working 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6255]
did some testing on mobile 
- when you scroll down on the landing page on mobile and click on the search icon, it resets the scroll position with keeping the navbar search bar active. When you type and hit enter, the input cursor switches to the search bar on the landing page. 

- it should open the results without resetting the scroll position.
![telegram-cloud-photo-size-4-5794007188811922265-y](https://github.com/kodadot/nft-gallery/assets/90852205/a0f4fce5-1d2c-4f73-9139-04dd0b4cce8f)
![telegram-cloud-photo-size-4-5794007188811922266-y](https://github.com/kodadot/nft-gallery/assets/90852205/9435eb9a-a32d-4f9e-84e6-6904b321150f)

**Comment by leo-anderson-x** [comment]
> it should open the results without resetting the scroll position.

@exezbcz I tested with https://canary.kodadot.xyz, the current behavior is as you said. seems no issue now

**Comment by exezbcz** [comment]
> > it should open the results without resetting the scroll position.
> 
> @exezbcz I tested with https://canary.kodadot.xyz, the current behavior is as you said. seems no issue now

Still happens on canary for me
