### ISSUE TITLE
collection cards on profile page

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#6258]
go to profile page
collections tab
images don't work

experienced on ksm, rmrk and statemine (canary, beta and production)

![image](https://github.com/kodadot/nft-gallery/assets/22791238/3d363cc4-c7ae-44b0-adcb-99e0e0a6bd33)

**Comment by JustLuuuu** [comment]
related #6168

**Comment by roiLeo** [comment]
looks like working now
