### ISSUE TITLE
Unlockable numbers numbers do not match 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#6259]
I was checking the drop page with waifu minter, and I'm not sure why these numbers are like this: 

Here you can see the total available items: 224/300

<img width="735" alt="Screenshot 2023-06-17 at 15 06 10" src="https://github.com/kodadot/nft-gallery/assets/104380776/25fa7564-fb2f-4cf6-9c3f-cc1ac2500330">

But if you open the collection, you can see only 74 items minted. 

<img width="308" alt="Screenshot 2023-06-17 at 15 06 18" src="https://github.com/kodadot/nft-gallery/assets/104380776/b922bd8e-6f72-4eca-b495-8db651ad132f">

Its bit confusing - what are those 224/300 numbers for?

**Comment by Jarsen136** [comment]
> I was checking the drop page with waifu minter, and I'm not sure why these numbers are like this:
> 
> Here you can see the total available items: 224/300
> 
> <img alt="Screenshot 2023-06-17 at 15 06 10" width="735" src="https://user-images.githubusercontent.com/104380776/246611855-25fa7564-fb2f-4cf6-9c3f-cc1ac2500330.png">
> But if you open the collection, you can see only 74 items minted.
> 
> <img alt="Screenshot 2023-06-17 at 15 06 18" width="308" src="https://user-images.githubusercontent.com/104380776/246611860-b922bd8e-6f72-4eca-b495-8db651ad132f.png">
> Its bit confusing - what are those 224/300 numbers for?

74 minted items + 224 available items = 300 total items. The 300 total amount could be changed to another number if needed.

**Comment by exezbcz** [comment]
> 74 minted items

*76

**Comment by Jarsen136** [comment]
> > 74 minted items
> 
> *76

Thanks, you are right : )

**Comment by exezbcz** [comment]
@JustLuuuu, those are available nfts to be minted - the whole drop consists of 300 nfts. When the 0/300 is reached, there are no nfts left.
