### ISSUE TITLE
Make mass mint available for everyone

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6268]
![image](https://github.com/kodadot/nft-gallery/assets/5887929/b976e502-a410-4244-a2b9-294573ee8caf)

We will make it available for the public, and we will do the silent release 👀

Apparently some CSS flex is required here too 😉

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/4964#issuecomment-1596133660_

**Comment by exezbcz** [comment]
yes sir:
- #6267
