### ISSUE TITLE
Paid drop ui 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6288]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/8f760c13-bf42-4697-80de-beedd3f3589d)
since we will have one drop page with paid mint, there is a UI for that
- its similar to the gallery item layout - price, button 
- I have added also a separator for clear layout
- above the progress line, there is no longer price, but % minted

handoff file with drop page design updated

- modals and signing will be made in separate issue

**Comment by roiLeo** [comment]
completed?

**Comment by exezbcz** [comment]
probably yeah, done differently anyway
