### ISSUE TITLE
Review failing checks on PRs 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#630]
we would like to have passing checks on PR and I should probably figure out which are failing
probably remove LGTM actions and gifs, it was fun and seems sentiment gifs don't work that great 

i.e. 

![image](https://user-images.githubusercontent.com/5887929/130597385-3004ba55-e6ad-495c-887b-f3f03194ad07.png)

oh with this may add Stale bot and linting?

**Comment by roiLeo** [comment]
Closed in #726 & #701
