### ISSUE TITLE
Activity sections styling

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6306]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/697d8577-77b2-4dcf-b8a9-a42a34de1f13)

- font weight to regular
- remove lines on every row, separator should be only between events

**Comment by roiLeo** [comment]
>     * font weight to regular
> 
>     * remove lines on every row, separator should be only between events

Is it for mobile only or on all device?

**Comment by exezbcz** [comment]
@roiLeo yes, when the table changes to vertical scroll.

**Comment by exezbcz** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/163d57a5-0255-40bb-b5c7-e9d420980704)
 
![This Is Where I'd Put My Trophy If I Had One](https://github.com/kodadot/nft-gallery/assets/90852205/ce72d34f-fda9-40c5-929d-a769703b9bb6)

xd
