### ISSUE TITLE
Fix landing page OG properties

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6308]
https://www.opengraph.xyz/url/https%3A%2F%2Fkodadot.xyz

![image](https://github.com/kodadot/nft-gallery/assets/5887929/9c5f2150-ac72-4a84-9b62-6edcacbe74c8)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/0a4a0a79-6224-4b61-af0e-448c82d94d80)

I think this explains why we don't have nothing there? 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/d42594c8-a453-4c2b-a63f-c491ed932401)

og:title I would put KodaDot - Go To Polkadot NFT marketplace
og:description Multi-chain NFT marketplace across Polkadot parachains

**Comment by roiLeo** [comment]
wut??
![Capture d’écran 2023-06-22 à 11 19 45 AM](https://github.com/kodadot/nft-gallery/assets/9987732/a8c33bff-6b05-4438-a39c-cf0157fdb9f5)

**Comment by yangwao** [comment]
> wut??

yes, I'm pretty aware of this, yet this is what OG bots sees 

<img src="https://media0.giphy.com/media/d7nbEwZV5FZrG18ptK/giphy.gif"/>

**Comment by preschian** [comment]
I put the additional context here https://github.com/kodadot/workers/issues/104#issuecomment-1602286160

**Comment by roiLeo** [comment]
Nice 🚀 fix from @preschian 
<img width="908" alt="Capture d’écran 2023-06-22 à 11 51 02 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/2febac4d-2cc2-4896-97a9-ab139651b0bd">

**Comment by abhisheknaiidu** [comment]
is this still open? @roiLeo @preschian ?

**Comment by roiLeo** [comment]
Closed by kodadot/workers#109

**Comment by yangwao** [comment]
> is this still open? @roiLeo @preschian ?

hey feel free to pick any other open issue, we have many of them 😉
