### ISSUE TITLE
Wallet connecting flow

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6316]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/79c46373-22b9-45e5-8cdc-add6994c0ef8)

I am thinking aloud, but would it be possible to show your accounts before authorization? The auth sign from your wallet (in my case polkadot js) would then come after I choose one account

Wdyt? Is it possible? if yes, I will create design and lets implement it, it will be less confusing - because I have seen that for many people the wallet connecting ends with the step of signing something in their wallet/popup.

**Comment by roiLeo** [comment]
I don't think it's possible you'll have to authorize app to show accounts, it's a security
