### ISSUE TITLE
Create selection 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6318]
Right now the selection of what you are going to create differs from simple mint and mass mint, it would be nice to combine them. 
- simple mint: 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/e7393fa8-183f-45da-9bf2-2997922bd99b)

- mass mint
![image](https://github.com/kodadot/nft-gallery/assets/90852205/3e0ed898-19e5-4249-830e-9bfee1fb671f)

@EthVlad, I was thinking that maybe we could get rid of the top selection from the mass mint - the easiest solution. wdyt?

**Comment by EthVlad** [comment]
yy, for sure, I was expecting that the navigation will be implemented within #5939 but we can do it beforehand.

**Comment by exezbcz** [comment]
@EthVlad I think the only thing needed is to update the mass mint part if there is any change, because I assume the top selection on mass mint won't be there anymore and will be done with pre-landing. 

The navigation is not implemented yet, I wanted to create a design backlog.

**Comment by EthVlad** [comment]
Made it hopefully understandable [here](https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1122-20719&mode=design&t=fOtDc9k7BgGVAxbt-4).

**Comment by EthVlad** [comment]
@kodadot/internal-dev rn we have this navigation tab on prod which is not working. Can we atleast remove it so that it looks like in the picture? 
Navigation itselft can be done later.
![Mass Mint](https://github.com/kodadot/nft-gallery/assets/95911767/2234df56-d426-4e38-885d-4ce08fa1ac28)

**Comment by roiLeo** [comment]
> @kodadot/internal-dev rn we have this navigation tab on prod which is not working. Can we atleast remove it so that it looks like in the picture below? Navigation itself which is in designs can be done after that. 

Meanwhile it look like this

![Screenshot 2023-08-07 at 08-45-41 Kodadot Massmint KodaDot - NFT Market Explorer](https://github.com/kodadot/nft-gallery/assets/9987732/79c36ebd-6c2b-4bfd-9ea1-9c937e5eac4b)

**Comment by daiagi** [comment]
so.... what needs to be done here?

**Comment by exezbcz** [comment]
@daiagi I think remaking simple mint now would be a better pick 
- #5939 
- it could be included there, or as a followup

**Comment by newraina** [comment]
@exezbcz still valid? seems nothing need to be done now

**Comment by exezbcz** [comment]
@newraina nope, it was fixed with this: https://github.com/kodadot/nft-gallery/pull/6459
