### ISSUE TITLE
Robots.txt is invalid

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#6330]
<img width="581" alt="Screenshot 2023-06-26 at 13 44 28" src="https://github.com/kodadot/nft-gallery/assets/22471030/79136e43-7408-47a3-988e-8134c261dff4">

https://developer.chrome.com/docs/lighthouse/seo/invalid-robots-txt/?utm_source=lighthouse&utm_medium=devtools

first iteration #6286

**Comment by yangwao** [comment]
Yes, just found that same! :D 

ref
- #6286

**Comment by yangwao** [comment]
I think the current state of https://kodadot.xyz/robots.txt is not valid.

```
User-agent: *
Disallow: */collection/
Disallow: */details/
Disallow: */gallery/
Disallow: */u/
Disallow: */transfer

Sitemap: https://kodadot.xyz/sitemap.xml
```

![image](https://github.com/kodadot/nft-gallery/assets/5887929/c74c91e5-da37-4af4-91b3-efc0aead69b6)

**Comment by iMac7** [comment]
@yangwao what issue caused this to be reopened? :thinking:
