### ISSUE TITLE
Connect button on Nova wallet is kinda off

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#6331]
I opened Nova Wallet and I wanted to log in. Connect button appeared like this: 

![IMG_4011](https://github.com/kodadot/nft-gallery/assets/104380776/815f05b5-7453-48af-9289-745b2f793c0c)

Connect button is on top of the other text (light mode).

Maybe also be good to add an option to connect to your wallet on the main landing page (with no need to open the menu)? Just a suggestion. Or just put connect on the top of the list

**Comment by JustLuuuu** [comment]
This is still an issue, not its not possible to click on Language 
https://github.com/kodadot/nft-gallery/assets/104380776/084cb4cc-9ca8-421b-973e-79c166d1041e

**Comment by exezbcz** [comment]
The "Connect" button should be located at the bottom of the screen, either after scrolling or always sticking to the bottom. (I will create a version for that - I believe it would be the best
- It's not listed first because the bottom is where your thumb can reach best.

**Comment by JustLuuuu** [comment]
> Since it's a CTA where would you put this button? maybe @kodadot/design-squad has some ideas?

The button should not overlap with other menu options. 😄 If this was intentional, then it's intentionally looking broken 🥲 Maybe just add it as an extra option in the menu. - it can be distinguished by the color. 

Or adding it under it? As we have in the normal mobile version - even that is broken 
- https://github.com/kodadot/nft-gallery/issues/6702

But you got the idea:
![IMG_6360](https://github.com/kodadot/nft-gallery/assets/104380776/146f9adf-42d6-4ce8-8dbb-7c59a62ba2fe)

**Comment by iMac7** [comment]
@JustLuuuu @yangwao this is still an issue across different browsers. The cookie banner is off too


Opera GX (not sure if in opera as well)
![opera_gx](https://github.com/kodadot/nft-gallery/assets/76876702/e16e8520-4e28-42e0-a618-567f9f2fa7bd)


MS Edge
![edge_not_scrolled](https://github.com/kodadot/nft-gallery/assets/76876702/4a949880-a25c-4bff-ba61-f71982d1b33e)

(Still on Edge)
Scrolling down to find the button makes the entire sidenav scroll, looks like unexpected behavior. Cookie banner also off here.
![edge_scrolled_down](https://github.com/kodadot/nft-gallery/assets/76876702/3a8cd0fe-a5e9-4881-82dc-6457e16dd093)


Should the size of buttons be reduced further, or a new scrolling behavior be introduced?
