### ISSUE TITLE
Can we change logo to something better 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6345]
Seems we got on first position yet would be nice to pimp our logo to something nicer?

I would vote for the outline version, wyt @exezbcz 

https://twitter.com/danieltbar/status/1673899815749718022

![image](https://github.com/kodadot/nft-gallery/assets/5887929/b494ffda-97da-4fc2-b9e6-9e0cd6d5e828)

**Comment by roiLeo** [comment]
Can we change org logo too? 🥺 

![koda 200x200](https://github.com/kodadot/nft-gallery/assets/9987732/8032ac01-fab7-4c83-8a86-1e644ac879b5)

**Comment by yangwao** [comment]
> Can we change org logo too? 🥺

pick some good mashup 👀

https://shop.kodadot.xyz/p/kodadot-logo-mashups-6-t-shirt/

> ![koda 200x200](https://user-images.githubusercontent.com/9987732/249395083-8032ac01-fab7-4c83-8a86-1e644ac879b5.png)

I mean, could be, yet I think we can do better 😅

**Comment by roiLeo** [comment]
![koda-4](https://github.com/kodadot/nft-gallery/assets/9987732/ef6884a2-43b8-49c4-a8b7-f5bde404776e)
![koda-3](https://github.com/kodadot/nft-gallery/assets/9987732/d5572e54-6c0d-4c8c-b8aa-7cb660a43808)
![koda-2](https://github.com/kodadot/nft-gallery/assets/9987732/8c236737-9b57-4b0a-bbaa-150129e6336d)
![koda-1](https://github.com/kodadot/nft-gallery/assets/9987732/f1a937e2-981b-45ed-b1e8-90a910df2309)

**Comment by exezbcz** [comment]
> I would vote for the outline version, wyt @exezbcz

<img src="https://media2.giphy.com/media/OkzCcGn5fY29e7bvpS/giphy.gif"/>

**Comment by yangwao** [comment]
We have three candidates, we used first one on Linkedin as on that small canvas, it's less shapes are more readable.

![clean](https://github.com/kodadot/nft-gallery/assets/5887929/987e3781-689a-4c01-9e43-2f92e5a7c61b)
![Frame 766 (1)](https://github.com/kodadot/nft-gallery/assets/5887929/73b284b8-dc0d-4c3c-a250-ab8a75242666)
![Frame 766](https://github.com/kodadot/nft-gallery/assets/5887929/973c555e-2763-454b-8197-4815e7ce2d13)

**Comment by prury** [comment]
i do enjoy a nice gradient

**Comment by roiLeo** [comment]
https://github.com/kodadot/nft-gallery/issues/6345#issuecomment-1610945279
![im-waiting-daffy-duck](https://github.com/kodadot/nft-gallery/assets/9987732/c7df1f8e-2581-4d11-bf0b-853fd4282477)

**Comment by EthVlad** [comment]
Hey, I refined the edges on the logo, also has shadow behind the straight "K" part at the top which looks better imho and more logical. 
![Koda - svg logo](https://github.com/kodadot/nft-gallery/assets/95911767/293911cc-26d7-497b-bb78-34dee62485fc)

**Comment by exezbcz** [comment]
@EthVlad thanks, I left it out by mistake.

**Comment by EthVlad** [comment]
> @EthVlad thanks, I left it out by mistake.

np :)

**Comment by exezbcz** [comment]
Seems like @roiLeo is feeling pretty happy!
<img src="https://media2.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif"/>
