### ISSUE TITLE
Mass minting not working on Statemine

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#6347]
### What happened?

Mass mint is not working on statemine. Working on other networks. 

### Please reproduce in steps

Go to mass mint and try clicking here:
<img width="1412" alt="Screenshot 2023-06-28 at 12 14 33" src="https://github.com/kodadot/nft-gallery/assets/104380776/143e4677-1b86-412a-a2fb-bc01df68d21c">

It will lead you here:
<img width="1056" alt="Screenshot 2023-06-28 at 12 14 27" src="https://github.com/kodadot/nft-gallery/assets/104380776/62f5639d-7049-4b2f-8776-9d6d6245a261">

### Expected Behavior

mint

### What browsers are you seeing the problem on?

Desktop Chrome

### Are you logged in?

None

### Screenshots

already added

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
maybe it will be fixed with #6251

**Comment by daiagi** [comment]
fixed by
* #6251 
stmn/create page did not yet exist
