### ISSUE TITLE
Free Drop: Error: Prefix not found

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6353]
> Is it just me or are anyone also getting this error: “Error: Prefix not found” 
> I’m using the latest version of Nova 😊

Looks like Nova Wallet and Free drop

> I’ve tried with both drops available

![telegram-cloud-photo-size-4-5830397634962111492-y](https://github.com/kodadot/nft-gallery/assets/5887929/a0572bc3-5fa5-4980-a6aa-8abce545a34e)

**Comment by AshutoshSingh72** [comment]
> > > Is it just me or are anyone also getting this error: “Error: Prefix not found”
> > > I’m using the latest version of Nova 😊
> > 
> > 
> > Looks like Nova Wallet and Free drop
> 
> <img alt="image" width="1017" src="https://user-images.githubusercontent.com/31397967/250581922-b3d3c0c1-9d05-400b-b0ab-3b00e1f23154.png">
> I think it's related to the paid minting instead of the free drop. As far as I know, the functionality for paid minting on statemint network is not ready.

It's ready checkout polkadot-punks.vercel.app

**Comment by yangwao** [comment]
closing as there will be issue for paid mints
