### ISSUE TITLE
Meta tags url being set to localhost on cloudflare pages (canary/beta/production)

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#6404]
| netlify deployment | cf-pages deployment |
|--------|--------|
| ![image](https://github.com/kodadot/nft-gallery/assets/734428/bdfda4fc-e818-43a1-8d01-8cdf35ef8b81) | ![image](https://github.com/kodadot/nft-gallery/assets/734428/f0d1ca02-3a0d-4bfc-8594-cd1411a26ca3) | 

need to add the same env on cf-pages? cc @yangwao 
ref: https://community.cloudflare.com/t/pages-deployment-url-in-process/491316

**Comment by yangwao** [comment]
What should be added? I haven't been checking this repo recently

**Comment by roiLeo** [comment]
Looks oki now

<img width="806" alt="Capture d’écran 2023-08-07 à 8 30 33 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/79cabd64-090f-4c26-af33-753398fed358">
