### ISSUE TITLE
Are using GA4 or UA for GA?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6410]
I'm not sure, I constantly clicking skip for now 😅

If UA, should we migrate to GA4 I bet? 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/ba0d2a4c-ce94-4079-b9e8-111e2838544e)

**Comment by roiLeo** [comment]
check your .env, if it start with `UA-***` then it's UA, if it start with `G-***` it's ga4.

From what I can see that has been shared with me it's UA, you need to migrate to GA4
