### ISSUE TITLE
Mass minting page - adjust size

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#6423]
After opening mass minting, it looks like this on my Chrome browser:

<img width="1459" alt="Screenshot 2023-07-11 at 14 42 27" src="https://github.com/kodadot/nft-gallery/assets/104380776/d221fc83-2310-482f-ac7a-04c7cf7960c5">

**Needs change:**
---
I would suggest adjusting the size so the button "next". so you can see it all without scrolling down a bit.

**Comment by daiagi** [comment]
related with
#6034

**Comment by exezbcz** [comment]
continue to 
- #7210
