### ISSUE TITLE
Transfer Redesign handover

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6460]
The final design can be found [here](https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=890-14850&t=Ft1lbluGKjwxPDhR-4). 

Feel free to grab it.

![image](https://github.com/kodadot/nft-gallery/assets/5887929/ad827f54-483d-44ea-811e-b5c96423bc6e)

Ref
---
- https://github.com/kodadot/nft-gallery/issues/6210

_Originally posted by @EthVlad in https://github.com/kodadot/nft-gallery/issues/5575#issuecomment-1600667031_

**Comment by roiLeo** [comment]
hello @Jarsen136 what's stopping us to use this page (?redesign=true) instead of `<TransferOld />`? mobile version looks oki to me, I kinda want to delete old one.

**Comment by Jarsen136** [comment]
> hello @Jarsen136 what's stopping us to use this page (?redesign=true) instead of `<TransferOld />`? mobile version looks oki to me, I kinda want to delete old one.

Only part of the styles have been implemented, however, the functionality is still not complete. It still relies on the work of some issues.  #6466 #6468
