### ISSUE TITLE
Giving basic education about NFT to new users.

### ISSUE THREAD

**Issue by ConsultVerraton** [kodadot/nft-gallery#647]
**Is your feature request related to a problem? Please describe.**
As Non-Fungible Tokens (NFTs) are an emerging form of investment, many new users would not be able to understand the concept behind it and how KodaDot is working on this as a platform. 

**Describe the solution you'd like**
While many users do their own research, it would be a great idea to add literature about NFTs in the FAQs and Tutorials. 
To start with, hyperlinking other articles on NFT would be a great start, we can always come up with our own write-up in the future. The same can be applied to videos and other media.

**Describe alternatives you've considered**
We can also have ambassadors and influencers talking about NFT and KodaDot but that can be done in a later milestone.

**Comment by cryptodamsky** [comment]
Basic NFT explanation and workflow is running in the documentation under

https://docs.kodadot.xyz/how-to-make-nft.html#create-a-piece-of-art

**Comment by yangwao** [comment]
There will be an ambassador program
- #2040
