### ISSUE TITLE
Statemine collections missing!

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#6477]
If you open Statemine, there are collections missing. You cannot see Decoded 2023 collections there. https://kodadot.xyz/stmn/explore/collectibles

There are currently only 19 collections!
<img width="1377" alt="Screenshot 2023-07-28 at 10 52 04" src="https://github.com/kodadot/nft-gallery/assets/104380776/1808752d-482f-4040-947a-0b147556f702">

Same on Canary. Where are they?

**Comment by vikiival** [comment]
There is some unknown bug related to collections on the subsquid indexer 
Downgraded to lower version
