### ISSUE TITLE
Drops are missing on KodaDot

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6478]
I have a demonstration for 60 ppl in an hour and drops aren't working :) 

https://kodadot.xyz/stmn/drops

![image](https://github.com/kodadot/nft-gallery/assets/5887929/5424ce2b-3ad9-45e9-a7ef-8132448d71ee)

**Comment by prury** [comment]
they do work on canary

**Comment by yangwao** [comment]
@vikiival can we release it ?

**Comment by vikiival** [comment]
yup

**Comment by vikiival** [comment]
Merged on beta in #6480

**Comment by yangwao** [comment]
hope it would work
