### ISSUE TITLE
Adding more information about NFT for new Users.

### ISSUE THREAD

**Issue by abhisar2006** [kodadot/nft-gallery#648]
**Is your feature request related to a problem? Please describe.**
As Non-Fungible Tokens (NFTs) are an emerging form of investment, many new users would not be able to understand the concept behind it and how KodaDot is working on this as a platform.

**Describe the solution you'd like**
While many users do their own research, it would be a great idea to add literature about NFTs in the FAQs and Tutorials.
To start with, hyperlinking other articles on NFT would be a great start, we can always come up with our own write-up in the future. The same can be applied to videos and other media.

**Describe alternatives you've considered**
We can also have ambassadors and influencers talking about NFT and KodaDot but that can be done in a later milestone.

**Link**
Linked to #647

**Comment by cryptodamsky** [comment]
Question "What are NFTS?" was added both to ![FAQ](https://kodadot.xyz/rmrk/faq) on main page and to ![docs](https://docs.kodadot.xyz/FAQ.html).

- #1604 

Will soon add more thorough explanation of NFTs to ![docs](https://docs.kodadot.xyz/FAQ.html) which we can use to easily explain nfts to newcomers, friends, family, influencers.

CC: https://github.com/kodadot/docs/issues/2
