### ISSUE TITLE
Notification Modal "Locking" scroll

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#6484]
### What happened?

Notification Modal can be closed by
1. clicking the navbar icon again
2. clicking on the "X" icon in the modal
3. clicking outside the modal

sometimes, closing the modal doesn't release the "y-scroll" lock
i.e 
open modal
close modal
can't scroll

### Please reproduce in steps

see above

### Expected Behavior

able to scroll

### What browsers are you seeing the problem on?

Desktop Chrome

### Are you logged in?

None

### Screenshots

![image](https://github.com/kodadot/nft-gallery/assets/22791238/70a1f837-2d54-4b85-8d4d-e19e0a88f392)

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
#6669, #6667
