### ISSUE TITLE
add How to withdraw DOT

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#649]
I get it that lot of people want to pay up their bills for rewards or bounties we've sent them and are happy to make it easier to deliver it. 

Would be awesome to extend the current https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md with a section 
- [ ] withdraw KSM to my account USD/EUR (?)
- [ ] withdraw KSM to paypal

I guess this is non-technical task and anyone from our stewards can link up tutorials there

**Comment by AndreyGrin** [comment]
I use crypto.com to withdraw any crypto. I got their debit card. You will need to convert KSM to ETH (or other supported) and sell crypto to top-up the card. Card can be used to get cash or pay bills or anything else online + some cash back will return in their native token CRO.

**Comment by archnomics** [comment]
@AndreyGrin Have you documented your workflow?  We can include it to the docs as currently, we only have Binance and Huobi workflow.

**Comment by yangwao** [comment]
what is $KSM, we are moving to $DOT :)

**Comment by yangwao** [comment]
this can be put to hello.kodadot.xyz I guess
