### ISSUE TITLE
Polkadot and Kusama NFTs are the same

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#6494]
I'm just curious. This is in production. We have Polkadot NFTs. But they are showing the same NFTs as Kusama NFTs(rmrk). Is that intentional? 

<img width="1369" alt="Screenshot 2023-07-30 at 10 53 50" src="https://github.com/kodadot/nft-gallery/assets/104380776/42104e40-9254-4b69-a305-dbe72a693456">

**Comment by yangwao** [comment]
cc @vikiival

**Comment by vikiival** [comment]
Yes this is intentional as i MUST specify the indexer and we agreed with @yangwao back then that it could work as a placeholder. 

Other option i can do is spin up dummmy api that would return nothing

**Comment by preschian** [comment]
Can we remove `polkadot`? Since we already had ahk and ahp?

**Comment by vikiival** [comment]
> Can we remove `polkadot`? Since we already had ahk and ahp?

Yes and payouts wont work 😏

**Comment by preschian** [comment]
We can filter that out in here right? we already do that for beta env

https://github.com/kodadot/nft-gallery/blob/929a427a5bfe71cf6e1ebe73bc5eb8a1942a454c/utils/chain.ts#L21-L33

**Comment by vikiival** [comment]
Ok let's proceed like that 👍
