### ISSUE TITLE
Don't allow user into make action if balance is insufficient

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#65]
We are quite full of these errors from NFT creators thus, we want to prevent this and solve it upstream.

We won't let user going forward unless has balance.
That includes actions like
- [ ] mint
- [x] buy
- [x] send
- [x] consume

**Comment by abhisar2006** [comment]
Hi,

We can close this one as a user cannot create NFT with insufficient Balance.

![Screenshot (522)](https://user-images.githubusercontent.com/30148793/133628483-26408dda-ad26-49ab-9e0e-f5a06d585069.png)

**Comment by yangwao** [comment]
No, that's **already an error**. 
We need to prevent users from clicking before having costs for minting on balance.

**Comment by marswong** [comment]
@yangwao please review my proposal:

1. maintain the latest balance of current account with a new state `accountBalance` and listen to balance change once account log in or switch account.
2. maintain a new state `loadingAccountBalance` which means querying latest balance of current account and `loadingAccountBalance` should be `true` during the query of balance.
3. fork the `exec` function of `src/utils/transactionExecutor.ts` to  be part of `src/utils/mixins/txMixin.ts`, which should consume the `accountBalance` state.
4. the UI related to transaction should consume the `accountBalance` and `loadingAccountBalance` state. While `loadingAccountBalance` is `true`, the action of transaction should display a loading state (e.g: set the `loading` props of button with `loadingAccountBalance`). While `accountBalance` doesn't meet the call, the action of transaction should display a disabled state with a tooltip about "insufficient balance".

If there is no problem with this proposal, please assign this issue to me :)

**Comment by yangwao** [comment]
> @yangwao please review my proposal:
> 
> 1. maintain the latest balance of current account with a new state `accountBalance` and listen to balance change once account log in or switch account.
> 2. maintain a new state `loadingAccountBalance` which means querying latest balance of current account and `loadingAccountBalance` should be `true` during the query of balance.
> 3. fork the `exec` function of `src/utils/transactionExecutor.ts` to  be part of `src/utils/mixins/txMixin.ts`, which should consume the `accountBalance` state.
> 4. the UI related to transaction should consume the `accountBalance` and `loadingAccountBalance` state. While `loadingAccountBalance` is `true`, the action of transaction should display a loading state (e.g: set the `loading` props of button with `loadingAccountBalance`). While `accountBalance` doesn't meet the call, the action of transaction should display a disabled state with a tooltip about "insufficient balance".
> 
> If there is no problem with this proposal, please assign this issue to me :)

Let's wait for @vikiival @roiLeo opinion and let's start. 
Meanwhile I've assigned you

**Comment by yangwao** [comment]
Prevent user from minting when has insufficient balance, other actions send/consume/list/buy been solved in action component

**Comment by yangwao** [comment]
Continue to #2799
