### ISSUE TITLE
Only one blog is shown on the `canary.kodadot.xyz/blog/`

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/nft-gallery#6509]
### What happened?

The rest of the blogs are missing.
<img width="1045" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/8a0992f4-5221-4ee4-b548-d4cb3a0ca642">

The bug should be introduced from this PR https://github.com/kodadot/nft-gallery/pull/6505

<img width="623" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/98f825d0-288b-44c2-8c82-33d6dcaff027">

### Please reproduce in steps

canary.kodadot.xyz/blog/

### Expected Behavior

All blogs could be displayed correctly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
Hello, I've done it on purposes as there should be only one hero card. Check out figma design if you want to integrate the others article

**Comment by Jarsen136** [comment]
> Hello, I've done it on purposes as there should be only one hero card. Check out figma design if you want to integrate the others article

I understand your concern, but this implementation blocks new articles to release. Before the design of the blog page is done, people have no way to see the list of blogs then. https://github.com/kodadot/nft-gallery/issues/6474

**Comment by roiLeo** [comment]
Feel free to uncomment code blocks but I prefer to release final design before something uncomplete goes out.
I can work on it next week

**Comment by roiLeo** [comment]
Looks like it's being done in #6525
