### ISSUE TITLE
Mobile tooltip update gallery

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6512]
Please @kodadot/internal-dev do refactor as well as needed

chains are perfect now! thanks to everyone involved

but oops, seems like mobile is wrong again:

![image](https://github.com/kodadot/nft-gallery/assets/36627808/f16ef649-511b-4e7a-a1b4-45f229fb186b)

_Originally posted by @prury in https://github.com/kodadot/nft-gallery/issues/6448#issuecomment-1660269992_

**Comment by floyd-li** [comment]
👋
