### ISSUE TITLE
Page reload when clicking on view article

### ISSUE THREAD

**Issue by AshutoshSingh72** [kodadot/nft-gallery#6524]
### What happened?

When i click on blogs in footer and then i click on view articles page reloads and redirects me to the homepage 
### **Bug Bounty address**
- [x] My DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v&usdamount=0&donation=true)

### Please reproduce in steps

Go to kodadot go to footer then click on blogs next click on view article

### Expected Behavior

page reloads and redirects to hompage

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

canary.kodadot.xyz, beta.kodadot.xyz, kodadot.xyz

### Are you logged in?

None

### At which chain did you encounter bug?

Basilisk, Kusama

### Screenshots

https://github.com/kodadot/nft-gallery/assets/78789916/6baa30a2-c471-459a-a668-2bbacb51a9d6

### Payment link for reward

https://kodadot.xyz/dot/transfer?target=158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v&usdamount=0&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by preschian** [comment]
@AshutoshSingh72 do you want to try to fix it?

**Comment by AshutoshSingh72** [comment]
> @AshutoshSingh72 do you want to try to fix it?

yeah i can there is one more pull request can you review it https://github.com/kodadot/nft-gallery/pull/6521 i'm starting to work on this but i didn't got my bug report bounty 😅 i'm waiting for it and starting to solve this one for sure

**Comment by preschian** [comment]
> > @AshutoshSingh72 do you want to try to fix it?
> 
> yeah i can there is one more pull request i made can you review it #6521 i'm starting to work on this but i didn't got my bug report bounty 😅 i'm waiting for it and starting to solve this one for sure

that one I leave it to @yangwao

**Comment by AshutoshSingh72** [comment]
> > > @AshutoshSingh72 do you want to try to fix it?
> > 
> > 
> > yeah i can there is one more pull request i made can you review it #6521 i'm starting to work on this but i didn't got my bug report bounty 😅 i'm waiting for it and starting to solve this one for sure
> 
> that one I leave it to @yangwao

Ah ok i'll do this i hope i get it pulled quickly
