### ISSUE TITLE
Kodadot not reflecting ownership changes when using statemine

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6530]
### What happened?

Mr. @daiagi helped me troubleshooting this specific bug:
Transaction: https://assethub-kusama.subscan.io/extrinsic/5060519-2
NFT: https://canary.kodadot.xyz/stmn/gallery/u-2024-11160
User profile: https://canary.kodadot.xyz/stmn/u/FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9?tab=collected

Chain transaction successful, but no NFT appears on user side and neither changes its ownership in the gallery.

@vikiival 

### Expected Behavior

should be owned by buyer

### What browsers are you seeing the problem on?

Firefox

### At which address did you encounter bug?

canary.kodadot.xyz

**Comment by daiagi** [comment]
Is something wrong on indexer maybe?
a few buy transactions on statemine were executed well on the chain but no change of state is shown in Kodadot

this one for example:
https://assethub-kusama.subscan.io/extrinsic/5060255-2

bought the nfts:
https://kodadot.xyz/stmn/gallery/6-8
https://kodadot.xyz/stmn/gallery/6-15
https://kodadot.xyz/stmn/gallery/6-17

at the moment of writing this comment, 6 hours after the transaction, still, these NFT's don't show change of ownership

**Comment by vikiival** [comment]
gm,
as @daiagi said this could be an issue from the squid side. 
I will look into it

**Comment by vikiival** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/22471030/c4b72fef-cd89-4c32-b171-3b2837686874)

Looks like that by unknown reasons indexer crashed. I downgraded prod to v3 and will check what happened to v4

**Comment by daiagi** [comment]
@prury 
all your NFT as shown as yours at the moment:

https://canary.kodadot.xyz/stmn/u/FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9?tab=collected&page=1

**Comment by prury** [comment]
> @prury all your NFT as shown as yours at the moment:
> 
> https://canary.kodadot.xyz/stmn/u/FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9?tab=collected&page=1

their STATE show as MINE now, ty both!
