### ISSUE TITLE
Drop page not working 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6534]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/e5f3da8f-687f-44ed-9f2d-1a249781f5e4)
- waiting more than 5 minutes 
- nothing visible on profile 
- https://canary.kodadot.xyz/stmn/drops/free-drop

close if it is turned off on purpose

**Comment by Jarsen136** [comment]
I just made a test. The free drop still works for me.

<img width="1270" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/c4dbe583-5499-4c8c-8108-a0f004a7c505">

**Comment by exezbcz** [comment]
hmm, weird, still nothing for me
![image](https://github.com/kodadot/nft-gallery/assets/90852205/ac70116f-14db-43e0-92cd-7769fdebc863)
![image](https://github.com/kodadot/nft-gallery/assets/90852205/8f08fcfa-91ec-41ab-b2ff-dc3026cfd235)
![image](https://github.com/kodadot/nft-gallery/assets/90852205/a52e30f3-afbb-4c65-b73e-27f39f63ded5)

**Comment by yangwao** [comment]
it maybe bc of old deployment and you have cached one bundle my bet as we had micro outage on canary few hours back and your drops ran through cache and maybe missed something new, just my few cents

**Comment by yangwao** [comment]
@exezbcz clear cache try again

**Comment by exezbcz** [comment]
@yangwao cleared cache, tried again, works 
<img src="https://media0.giphy.com/media/Yqnq2cw2eF1gA38OHn/giphy.gif"/>
