### ISSUE TITLE
Gallery item

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6536]
Check if everything works oin gallery item
- i.e. if we show audio/video media properly
- i.e. if we can show onchain nfts

**Comment by daiagi** [comment]
video doesn't work:

https://kodadot.xyz/stmn/gallery/u-117-3111

compare with 
https://singular.app/collectibles/statemine/117/3111

**Comment by preschian** [comment]
can be fixed with this https://github.com/kodadot/nft-gallery/issues/6638

**Comment by preschian** [comment]
You can try to add `?original=true` in the URL image

https://image-beta.w.kodadot.xyz/ipfs/QmPdKdaCmwsG8bmZjUBbWwa37JTBBNutruB3cL3G2YmKMS?original=true
