### ISSUE TITLE
First time minting on Statemine

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6538]
Hey I'm checking minting for Statemine and this is where I land after clicking on Multiple NFTs

Then I have a button on the left back to onboarding. 

Not sure if it's glitch or intentional but even as inner KodaDot I'm confused, why it's landing there? 

Where is simple mint for Statemine?

cc @EthVlad 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/1ab0984b-6282-467c-b206-9e415986bd12)

It's follow-up from this 

- https://github.com/kodadot/nft-gallery/issues/5987
- #5939

**Comment by prury** [comment]
> Hey I'm checking minting for Statemine and this is where I land after clicking on Multiple NFTs
> 
> Then I have a button on the left back to onboarding.
> Not sure if it's glitch or intentional but even as inner KodaDot I'm confused, why it's landing there?
> 

here it drives me to massmint onboarding


> Where is simple mint for Statemine?
> 

i thought you guys were waiting to release it following a marketing campaign or something similar, but i did find strange because i remember this PR: #6251. last monday i even asked viki on Discord about why we didn't release classic statemine minting yet

**Comment by yangwao** [comment]
> we didn't release classic statemine minting yet

we can do 
- #5939

**Comment by AshutoshSingh72** [comment]
@yangwao pr merged close this issue
