### ISSUE TITLE
Remove Instance from NFT Form

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#66]
Some users don't know what to put inside `instance` field (check image below)

![Screen Shot 2021-02-16 at 13 15 13](https://user-images.githubusercontent.com/22471030/108061735-07c9d480-7059-11eb-8582-fc9009fd1aa5.png)

I think that we should remove it from UI and derive it from `name` 
```js
slugify(nft.name, '_')
```

**Comment by Swader** [comment]
Yeah, that's definitely more user friendly

**Comment by vikiival** [comment]
Closed in #78
