### ISSUE TITLE
Statemine collection not loading

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#6618]
This collection on statemine is not loading properly: production and canary too
- https://kodadot.xyz/stmn/collection/88
- https://canary.kodadot.xyz/stmn/collection/88

<img width="1438" alt="Screenshot 2023-08-08 at 16 43 03" src="https://github.com/kodadot/nft-gallery/assets/104380776/37872987-5f88-4132-b99b-9ab0334ddd7c">

**Comment by preschian** [comment]
the creator put metadata and image on s3 bucket, not ipfs

```json
{
  "name": "ASM Brains #5413",
  "description": "Token 5413 minted By Altered_State_Machine",
  "image": "https://polkadot-data.s3.us-east-2.amazonaws.com/metadata/nfts-88/nfts-88_item-5413-img.jpg",
  "license": "License name",
  "licenseUri": "https://license.com",
  "tags": [
    "Art",
    "Ethereum"
  ],
  "attributes": [
    {
      "label": "GENERATION",
      "value": "Genesis"
    },
    {
      "label": "COLORS",
      "value": "Blue Orange Pale Pink"
    }
  ]
}
```

**Comment by preschian** [comment]
steps to support non-ipfs format:
1. need to extend image workers. WIP: https://github.com/kodadot/workers/pull/136
2. adjust our UI to hit a new endpoint if metadata/image/mediaUri is from a custom URL
3. adjust our UI to validate metadata as a json

seems like the creator of nft can update their nft metadata after minting on AssetHub. can someone confirm? I see there is `setMetadata()` from extrinsic. if that is the case, we can extend no.3 to show a popup to the user in gallery detail page and tell them that something like "metadata invalid". It would be good if the creator could update their nft metadata directly in our UI

![image](https://github.com/kodadot/nft-gallery/assets/734428/3eb166f4-48a3-47ea-8acc-d4c7e90cf70b)

**Comment by roiLeo** [comment]
https://kodadot.xyz/ahk/collection/88
![Screenshot 2023-10-13 at 15-55-33 ASM Brains](https://github.com/kodadot/nft-gallery/assets/9987732/bb5ddcaf-d987-4bb8-87ee-c77c2106f68f)

**Comment by preschian** [comment]
@roiLeo why close the issue? Please see the console error. And try to visit one of the items. some features are not working, such as download and details tab

**Comment by roiLeo** [comment]
> @roiLeo why close the issue? Please see the console error. And try to visit one of the items. some features are not working, such as download and details tab

Collection loads well on my side check screenshots

**Comment by preschian** [comment]
the error was not only load the image in the collection page, the asset/metadata url was on non ipfs
