### ISSUE TITLE
Buy now on explorer doesn't work

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6621]
https://canary.kodadot.xyz/stmn/explore/items?listed=true

it shows me NFTs w/o price able to buy

![image](https://github.com/kodadot/nft-gallery/assets/5887929/e4f1af5d-2995-447a-8c33-7205ca7961ad)

**Comment by daiagi** [comment]
I am unable to reproduce

**Comment by exezbcz** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/a9e7be39-d0db-4444-8427-9f86ebae5470)
It might help idk
