### ISSUE TITLE
Replace buy switch with new style

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6624]
I know there are works on the profile, yet can we speed run this small switch?

otherwise profile will be not that ugly :) 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/c7b49ee7-7641-44e0-9030-25ef55fc4f26)

**Comment by yangwao** [comment]
mybb

https://github.com/kodadot/nft-gallery/assets/5887929/b91cd1f1-3113-4b10-a78d-7b7eac466205

**Comment by exezbcz** [comment]
closing, continue to 
- #6663
