### ISSUE TITLE
Dance in cart

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6625]
I would like to see items in cart expanded at most.
Collection name probably smaller size?

At price we can skip those small amounts less than $1 
so instead of 96.5000 KSM -> 96 KSM

Follow design best 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/ab695373-d7d8-4a9f-a712-12d2eb0fc85a)

**Comment by god-of-js** [comment]
👋
