### ISSUE TITLE
Buy now spinning wheel 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6626]
> showing the loader spinner on the button and keeping the button visible while the wallet modal is open turned out quite challenging and is not included in this PR.

- follow up for #6372 

when a user does not have a connected wallet, instead of the confirmation popup, the buy now button changes state, with a loading circle - wallet connect sidebar is opened
![image](https://github.com/kodadot/nft-gallery/assets/90852205/fe390068-73e3-4d24-bdd1-a7ea097704b2)

when the wallet is connected, the confirmation dialog is opened

**Comment by roiLeo** [comment]
https://www.youtube.com/watch?v=xyQC_PXL1G4

![weenie-weeniedog](https://github.com/kodadot/nft-gallery/assets/9987732/7e35733b-5c3e-4478-a145-c7ab47f48c2d)

**Comment by hassnian** [comment]
👋
