### ISSUE TITLE
Is canary down?

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#6630]
<img width="1292" alt="Screenshot 2023-08-09 at 13 04 08" src="https://github.com/kodadot/nft-gallery/assets/22471030/d0aef98d-7a12-4d4f-9e1f-0925778cb6e2">

For people it works:

- @exezbcz 
- @brano-hozza

For people it does not:

- @JustLuuuu 
- @hladikes

@kodadot/internal-dev can I ask you to test it ?

Seems should be problem with cache but it did not help for me

![photo_2023-08-09 13 12 20](https://github.com/kodadot/nft-gallery/assets/22471030/8afb098f-ac3d-43da-ab0c-5b2c5c268452)

**Comment by vikiival** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/22471030/1edc3c53-1fdb-4edf-af15-c9ddf644364c)

**Comment by roiLeo** [comment]
Down for me

**Comment by daiagi** [comment]
Down for me as well

**Comment by preschian** [comment]
up for me

related with this I guess https://github.com/kodadot/nft-gallery/issues/6518

**Comment by preschian** [comment]
same error, let me retry the deployment

now, it throws an error even without a SENTRY token

**Comment by preschian** [comment]
how about now? still down for you guys?

**Comment by roiLeo** [comment]
> how about now? still down for you guys?

wfm

**Comment by yangwao** [comment]
> Seems should be problem with cache but it did not help for me

for those who "worked" is because they got served through service-worker locally and connecting to same endpoints.

For those in incognito probably doesn't 

wfm

let's move to 
- https://github.com/kodadot/nft-gallery/issues/6518
