### ISSUE TITLE
Cart sidebar - burguer menu won't close when clicking cart on mobile

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6650]
### What happened?

https://github.com/kodadot/nft-gallery/assets/36627808/e3e4f9b7-3a41-4b53-8ac8-ece4a7821fa8

### Please reproduce in steps

Mobile -> Menu -> Cart

### Expected Behavior

burguer menu should close when clicking the cart option

### What browsers are you seeing the problem on?

Desktop Firefox

### At which address did you encounter bug?

canary.kodadot.xyz

### Are you logged in?

Yes

**Comment by roiLeo** [comment]
could changes from #6643 & #6642

**Comment by prury** [comment]
> could come from #6643 & #6642

definitely 

@yangwao @vikiival pls don't make me check already merged PRs too 😢

**Comment by roiLeo** [comment]
> pls don't make me check already merged PRs too 😢

It's my fault too I thought the code was good, I'll prepare a hotfix

**Comment by prury** [comment]
> > pls don't make me check already merged PRs too 😢
> 
> It's my fault too I thought the code was good, I'll prepare a hotfix

haha, i was being overly emotional

![7vbz4t](https://github.com/kodadot/nft-gallery/assets/36627808/62a5f7bd-5699-4f6d-865d-4e100bbb7d51)

**Comment by roiLeo** [comment]
I'll close this one as it seems to be fixed in #6653 

Now the only thing missing is that it scroll to top on mobile only
