### ISSUE TITLE
Cart svg icon

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#6655]
Looks like it's not coming from the same icon pack

![Screenshot 2023-08-10 at 16-02-51 KodaDot - NFT Market Explorer](https://github.com/kodadot/nft-gallery/assets/9987732/1733606c-33a9-4c8c-9a9d-9b50595ae3db)

What can we improve:
- fix size
- fix line weight
- replace icon with [FontAwesome equivalent](https://fontawesome.com/search?q=cart&o=r)

wdyt @exezbcz

**Comment by preschian** [comment]
@exezbcz oh, I forgot to inform you. I just found out that we can upload custom icons on FA
- https://fontawesome.com/docs/web/add-icons/upload-icons/
- https://fontawesome.com/docs/web/add-icons/upload-icons/icon-design/
- https://fontawesome.com/docs/web/add-icons/upload-icons/prep-icons/

give me the icons and I will upload it to our FA kits

**Comment by exezbcz** [comment]
@preschian Nice! oki let me create it from the fa icon, its now from something else

**Comment by exezbcz** [comment]
@preschian can I please get the password to the font awesome pro? I do need to download the SVG pro icon for customization

**Comment by preschian** [comment]
Ah, good idea. Where is the good place to share the password? In case the other members want it also

**Comment by exezbcz** [comment]
@preschian maybe set up bitwarden? And then share access through dms or something like that idk, not privacy expert :DDD

**Comment by preschian** [comment]
@exezbcz @EthVlad sent it to you fa creds through discord

**Comment by roiLeo** [comment]
> sent it to you fa creds through discord

Hey! I might need your help since I can't use fa pro with nuxt3. 
Do I need to setup particular packages?

**Comment by preschian** [comment]
> Hey! I might need your help since I can't use fa pro with nuxt3.
> Do I need to setup particular packages?

oh, which error is this? on fa pro we only put this script on head
https://github.com/kodadot/nft-gallery/blob/ab6647986974d9708cee4828cc7b6bfb792fa0b9/nuxt.config.js#L126-L130

I also sent the fa creds to you on discord

**Comment by roiLeo** [comment]
> > Hey! I might need your help since I can't use fa pro with nuxt3.
> oh, which error is this? on fa pro we only put this script on head

Grid icon for example:
<img width="440" alt="Capture d’écran 2023-09-12 à 1 24 42 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/5caa80b8-c704-4740-aa8f-435c7434bc8e">
<img width="150" alt="Capture d’écran 2023-09-12 à 1 24 30 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/889bb4a6-bc11-40de-a40a-b47bd411a4b4">

I would normally add them in `icon.ts` config file but since they are imported from another package I don't really know how to handle it

**Comment by exezbcz** [comment]
yeah, this is needed. We miss the crossed-out icon on Explore now

<img width="229" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/5ae373ce-3a30-4d61-a9ba-30a727409ee5">

I will create a custom one that we can import to fa

**Comment by exezbcz** [comment]
okay, I have two icons. The crossed-out is based on a regular sharp icon named cart-shopping **(20px version)** 
https://fontawesome.com/icons/cart-shopping?f=sharp&s=regular

svg: 
![custom-shopping](https://github.com/kodadot/nft-gallery/assets/90852205/129f0838-534e-431f-8750-a911b9be58ce)


Could someone please add it to our collection? I was unable to log in using the provided credentials. Thank you!

**Comment by exezbcz** [comment]
what about this guys 👀 


it currently does not show the active state 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/95ef75fe-fdd3-4a44-b9ac-d3c7758ac7b0)

**Comment by exezbcz** [comment]
Anyone from @kodadot/internal-dev

**Comment by roiLeo** [comment]
> Anyone from @kodadot/internal-dev

wassup? active state is cross-cart?

**Comment by exezbcz** [comment]
> > Anyone from @kodadot/internal-dev
> 
> wassup? active state is cross-cart?

Exactly sir

**Comment by roiLeo** [comment]
you've put your finger on something

**Comment by exezbcz** [comment]
> that's not pleasant.

to code or? :D
