### ISSUE TITLE
Collection and profile pages down 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6660]
Collection page: 
https://canary.kodadot.xyz/ahk/collection/32
![telegram-cloud-photo-size-4-5956027051867748678-y](https://github.com/kodadot/nft-gallery/assets/90852205/3a12b98a-955e-4066-bc27-c5f1bb6e235c)

https://canary.kodadot.xyz/ahk/collection/8
![image](https://github.com/kodadot/nft-gallery/assets/90852205/8c1b20e4-d11b-4874-afee-8396f290c9ae)

- profile is not working as well on the network

**Comment by yangwao** [comment]
we will be back on air in 7 minutes 

<img src="https://media2.giphy.com/media/jRSAMwdWD2QvFcKREB/giphy.gif"/>
