### ISSUE TITLE
canary.kodadot.xyz flashbang 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6697]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/ad7353b8-2960-47ab-b09d-cc77acb62b18)
https://canary.kodadot.xyz/

something with cloudfare i guess

**Comment by yangwao** [comment]
hmm 😄 +99 pts for meme

**Comment by yangwao** [comment]
@preschian any ide? maybe this one? 
- https://github.com/kodadot/nft-gallery/pull/6690

**Comment by yangwao** [comment]
https://main.nft-gallery-5ci.pages.dev/ actually works, that's its where canary points


<img width="883" alt="image" src="https://github.com/kodadot/nft-gallery/assets/5887929/3ddefb33-1053-4f5c-b430-134b95414072">

**Comment by preschian** [comment]
> @preschian any ide? maybe this one?
> 
> * [ci: exit on failed to parse #6690](https://github.com/kodadot/nft-gallery/pull/6690)

hhmm latest deployment for the `main` branch is this one https://82e0ff71.nft-gallery-5ci.pages.dev/ looks fine. Checking which point canary to

**Comment by yangwao** [comment]
Netlify doesn't build 

https://app.netlify.com/sites/koda-canary/deploys/64d8c5fd3c560e00085faf48 

```
2:04:43 PM: stderr: [fatal] Unexpected end of JSON input
2:04:43 PM:   at JSON.parse (<anonymous>)
2:04:43 PM:   at node_modules/.pnpm/@nuxt+bridge-edge@3.0.0-27889410.9247608_@babel+core@7.22.9_sass@1.64.0_vue@2.7.14/node_modules/@nuxt/bridge-edge/dist/shared/bridge-edge.93ceedc4.mjs:348:164
2:04:43 PM:   at async Nuxt.callHook (node_modules/.pnpm/hable@3.0.0/node_modules/hable/dist/hable.js:1:959)
2:04:43 PM:   at async node_modules/.pnpm/@nuxt+webpack-edge@2.16.0-27720022.54e852f_patch_hash=erfbavqcsxdsfzuhctu4pd6xii_typescript@4.9.5_vue@2.7.14/node_modules/@nuxt/webpack-edge/dist/webpack.js:1925:7
2:04:43 PM: exit(1)
```

**Comment by preschian** [comment]
> Netlify doesn't build

> [main.nft-gallery-5ci.pages.dev](https://main.nft-gallery-5ci.pages.dev/) actually works, that's its where canary points

but we are using cf-pages for canary, right?

**Comment by yangwao** [comment]
> cf-pages for canary, right?

Yes, but Netlify should also work as we are using it for PR deploys

**Comment by yangwao** [comment]
https://app.netlify.com/sites/koda-canary/deploys/64d8b96b9e2f1b000845b118
but other errors looks completely different 

<img width="527" alt="image" src="https://github.com/kodadot/nft-gallery/assets/5887929/760e3b88-420b-4279-a6d8-8beef6ab0422">

**Comment by preschian** [comment]
Anyway, this PR https://github.com/kodadot/nft-gallery/pull/6690 is expected to stop deployment if the build error occurs. Because, if the build fails and continues the deployment, it will show an error page like this https://github.com/kodadot/nft-gallery/issues/6630#issue-1842915927

**Comment by preschian** [comment]
> [main.nft-gallery-5ci.pages.dev](https://main.nft-gallery-5ci.pages.dev/) actually works, that's its where canary points

netlify is already fine as expected. for canary should be pointing to this page

**Comment by preschian** [comment]
I will try to add a subdomain again pointing to main.nft-gallery-5ci.pages.dev, to trigger DNS. I suspect this is related to DNS stuff

**Comment by preschian** [comment]
I turn off from "Proxied" to "DNS only", looks fine now

![image](https://github.com/kodadot/nft-gallery/assets/734428/d66b8cd0-e9f3-4e35-8501-98ca3aeb3fad)


could you check again @exezbcz @yangwao 
- https://canary-cf.kodadot.xyz/
- https://canary.kodadot.xyz/

**Comment by preschian** [comment]
I will try to turn it back on again

**Comment by yangwao** [comment]
> I turn off from "Proxied" to "DNS only", looks fine now

but then workers for OG previews would not work no?

**Comment by preschian** [comment]
> but then workers for OG previews would not work no?

correct, at the moment OG previews won't work on `canary` if I turn that off

**Comment by preschian** [comment]
I found weird stuff

1. we already point `canary.kodadot.xyz` to https://main.nft-gallery-5ci.pages.dev/. but the page is different. there is no cart icon, and the line above Spotlight is different. I suspect that `canary.kodadot.xyz` is still cache in the wrong version

![Screenshot 2023-08-14 020717](https://github.com/kodadot/nft-gallery/assets/734428/066d23e2-2868-4d9f-9eee-4a30f148479b)

| main.nft-gallery-5ci.pages.dev | canary.kodadot.xyz |
|--------|--------|
| ![Screenshot 2023-08-14 020734](https://github.com/kodadot/nft-gallery/assets/734428/48caa79e-e847-4e8c-8565-9ccda6f9e3d3) | ![Screenshot 2023-08-14 020737](https://github.com/kodadot/nft-gallery/assets/734428/4527580e-1166-488d-9787-48ece15998f8) | 

2. I added another subdomain to test it out. But, the page returns 522. It says, "Please contact your hosting provider". Meanwhile, our hosting provider is Cloudflare Pages 😅

![image](https://github.com/kodadot/nft-gallery/assets/734428/2ee0843f-c09f-4fe0-bfa5-ce4d1edb8421)

| 82e0ff71.nft-gallery-5ci.pages.dev | another-canary.kodadot.xyz |
|--------|--------|
| ![Screenshot 2023-08-14 021814](https://github.com/kodadot/nft-gallery/assets/734428/494a3829-a0fb-4ec1-817a-48ed8d49dc4f) | ![Screenshot 2023-08-14 021811](https://github.com/kodadot/nft-gallery/assets/734428/3c71a682-5285-4417-b276-53942941207d) |

**Comment by preschian** [comment]
This isn't very pleasant. Want to move to another hosting platform? cc @yangwao 
pick one Vercel or Netlify

It seems like I can use Edge Middleware from Vercel to move our prerender-workers https://vercel.com/docs/concepts/functions/edge-middleware

**Comment by preschian** [comment]
@yangwao already added some subdomain points to netlify. if this is blocked for you, @exezbcz, you can check our other subdomain in https://canary-netlify.kodadot.xyz/

**Comment by preschian** [comment]
solved, this is the root cause. I turn off the "Auto Minify" options now from Cloudflare dashboard

![image](https://github.com/kodadot/nft-gallery/assets/734428/afd7eaa5-774a-4e52-babe-d27410e6aec1)

It should be fine again. try to press `Ctrl/Cmd + Shift + R` if still get a blank page

![image](https://github.com/kodadot/nft-gallery/assets/734428/1eb934ce-06e8-430b-bf72-4862a59da6e2)


ref:
- https://community.cloudflare.com/t/the-page-error-when-turn-on-proxied-option/544471/14?u=preschian
- https://developers.cloudflare.com/speed/optimization/content/auto-minify/#auto-minify

**Comment by exezbcz** [comment]
@preschian works for me, thanks!

**Comment by yangwao** [comment]
> I found weird stuff

yes, happened few times, hopefuly autominify will resolve it

**Comment by yangwao** [comment]
Related, which caused bug
- https://github.com/kodadot/nft-gallery/pull/6707
