### ISSUE TITLE
I still see Statemine & Statemint, not AHK or AHP

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6698]
Incognito canary.kodadot.xyz

https://canary.kodadot.xyz/stt/explore/collectibles

<img width="488" alt="image" src="https://github.com/kodadot/nft-gallery/assets/5887929/067520e0-3974-4aa1-8f65-79434087d638">

https://canary.kodadot.xyz/ahp/explore/collectibles

<img width="880" alt="image" src="https://github.com/kodadot/nft-gallery/assets/5887929/12ec748c-253d-47dd-8ae3-e60e4cb75452">

**Comment by yangwao** [comment]
lol on https://main.nft-gallery-5ci.pages.dev/ it's oke

**Comment by preschian** [comment]
solved by https://github.com/kodadot/nft-gallery/issues/6697#issuecomment-1676456146
