### ISSUE TITLE
Different offer price and offer notifications

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6726]
### What happened?

Was offered some $ for my NFT, almost missed because the notification button won't show me there is one offer to my NFT.
Incoming offers says 1 BSX while other places says 1 KSM. 

![image](https://github.com/kodadot/nft-gallery/assets/36627808/df49891b-575b-4851-b236-ed452f19df99)

![image](https://github.com/kodadot/nft-gallery/assets/36627808/b5661e8f-28de-459c-b372-780da2789d47)

![image](https://github.com/kodadot/nft-gallery/assets/36627808/8fb8ed62-571f-4cc4-a659-c550e0494bee)

https://canary.kodadot.xyz/bsx/gallery/1676410053-2

date not showing as well on who made the offer( will prob be solved by profile redesign)
![image](https://github.com/kodadot/nft-gallery/assets/36627808/6087fb84-30c9-4494-b728-fc3b7962665a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by exezbcz** [comment]
> button won't show me there is one offer

This is not yet possible iirc, we would have to have an off-chain service for notifications

**Comment by prury** [comment]
Solved by PR above
