### ISSUE TITLE
Wrong price on the index page

### ISSUE THREAD

**Issue by jsidorenko** [kodadot/nft-gallery#6739]
### What happened?

On the index page, I see the NFT price in DOT, while the collection lives on Kusama.
Not sure if that's the desired behaviour, but even so, the price displayed is wrong. It shows [0.1930 KSM](https://deploy-preview-6735--koda-beta.netlify.app/ahk/gallery/u-2024-11270) vs. 48.25 DOT. I guess you've picked the first listing price here (not the last one) and wrongly applied the conversion by the number of decimals.

### Please reproduce in steps

https://deploy-preview-6735--koda-beta.netlify.app/
1) Select the PolkadotHub
2) On the index page, scroll down to Newest List
3) see the wrong prices in DOT

### Expected Behavior

If the collection is on Kusama (or Kusama AssetHub), then the prices should be displayed in KSM (or calculated properly)

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

<img width="281" alt="image" src="https://github.com/kodadot/nft-gallery/assets/5252494/1ee4d88f-f3bb-4b5a-a104-1323b3dc942f">

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by preschian** [comment]
seems like has been fixed

https://canary.kodadot.xyz/ahk/gallery/u-2024-11270

![image](https://github.com/kodadot/nft-gallery/assets/734428/12fcb994-6418-487a-8a1b-cc5bd78a0881)

![image](https://github.com/kodadot/nft-gallery/assets/734428/3428d590-06dc-4407-a4ee-4776c8192de4)

**Comment by yangwao** [comment]
> seems like has been fixed
> 
> [canary.kodadot.xyz/ahk/gallery/u-2024-11270](https://canary.kodadot.xyz/ahk/gallery/u-2024-11270)

cc @jsidorenko

**Comment by jsidorenko** [comment]
nope :) pls read the "Steps to reproduce"

**Comment by jsidorenko** [comment]
<img width="1507" alt="image" src="https://github.com/kodadot/nft-gallery/assets/5252494/50399bbb-8788-4cf2-9ee9-1521c9267c59">
try to click on any of those nfts and compare the price

**Comment by preschian** [comment]
> nope :) pls read the "Steps to reproduce"

aahh sorry, I miss the 1st step. yes, this is incorrect, it shows based on the prefix. this is on `bsx` prefix

![image](https://github.com/kodadot/nft-gallery/assets/734428/312d4d45-d3f3-4122-929a-53cea31fabf9)

**Comment by preschian** [comment]
It seems like two issues here:

1. invalid token on FE side. I will check on this one
2. price is not updated. seems like from indexer
