### ISSUE TITLE
Activity tab gallery item left right padding 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6743]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/e88d1383-28be-449a-ad04-2144491d7989)
- should be 32px from design, but in app is 24px - so 24px is it :D 
- left and right padding here
<img width="83" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/d47ac67f-4713-438b-bcda-c99200af144b">

**Comment by floyd-li** [comment]
👋
