### ISSUE TITLE
Add current KSM price and link to extrinsic to Transfer dialog 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#675]
1. Display link for the transaction which was made on Subscan using generated extrinsic, i.e. 
**0x256768b350ed980fd6dfb1d6172807be8765b04f475f3c315f5632bdd0417568** linking to 
https://kusama.subscan.io/extrinsic/0x256768b350ed980fd6dfb1d6172807be8765b04f475f3c315f5632bdd0417568

Somewhere permanent, no in snackbar, best if you can add there copy to clipboard button.

2. Display somewhere current price of $KSM. You can find a way how we fetch prices from coingecko in kodadot.

![image](https://user-images.githubusercontent.com/5887929/131681991-ba3611cd-0fe4-42ac-abc9-d60716d8ac46.png)

For more check this PR how is Transfer made https://github.com/kodadot/nft-gallery/pull/672

**Comment by prachi00** [comment]
@yangwao is the transaction link suppose to show up here only that is /transfer route? Since I believe it will go away once you click on a different route and hence wont be permanent

**Comment by yangwao** [comment]
> @yangwao is the transaction link suppose to show up here only that is /transfer route? Since I believe it will go away once you click on a different route and hence wont be permanent

Yes, on transfer only, that would be more than enough I guess :)
