### ISSUE TITLE
NFT set_attribute calls ignored by UI?

### ISSUE THREAD

**Issue by niklasp** [kodadot/nft-gallery#6774]
### What happened?

I am minting an NFT here: https://assethub-kusama.subscan.io/extrinsic/5163694-2
and then setting the attribute: https://assethub-kusama.subscan.io/extrinsic/5163738-2
the kodadot UI does not display the attributes in the "properties" tab: https://kodadot.xyz/ahk/gallery/97-5812

Also on this item: https://kodadot.xyz/ahk/gallery/97-2583060150 Only properties from the metadata are displayed while there are many set_attribute calls for the nft present in this extrinsic: https://assethub-kusama.subscan.io/extrinsic/5163596-2

I also checked the substrate portal if attributes are really saved to nft and they are, see the output on [this gist](https://gist.github.com/niklasp/172d9e0325e208e9b60cf86411652c06)

Is it because there is metadata? Does the ui take set_attribute calls into account? are they overriden by the metadata?

### Please reproduce in steps

mint an nft, do a `set_attribute` extrinsic, check the UI, attributes are not displayed in Kodadot

### Expected Behavior

attributes to be a merge from the metadata attributes and the attributes set in `set_attribute` extrinsics

### At which address did you encounter bug?
- beta.kodadot.xyz
- kodadot.xyz
- canary.kodadot.xyz

### At which address did you encounter bug?

Kusama Asset Hub

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=DT7kRjGFvRKxGSx5CPUCA1pazj6gzJ6Db11xmkX4yYSNK7m

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
@niklasp do they match?

https://gist.github.com/niklasp/172d9e0325e208e9b60cf86411652c06

```json
{
  "data": {
    "nftEntityById": {
      "id": "97-2583060150",
      "name": "Rare 155",
      "metadata": "ipfs://ipfs/bafkreiclmzoac3ubsv3h64knrstp2xh3pbf5boqj7z52f6cmul3icnrc44",
      "image": "ipfs://ipfs/bafybeighe3zho4w5jagp2rgpsnugkenhwejmy5yxtcbqn4js3ajepr3i3q",
      "attributes": [
        {
          "trait": "image",
          "value": "ipfs://ipfs/bafybeighe3zho4w5jagp2rgpsnugkenhwejmy5yxtcbqn4js3ajepr3i3q"
        },
        {
          "trait": "referendum",
          "value": "166"
        },
        {
          "trait": "meetsRequirements",
          "value": "true"
        },
        {
          "trait": "voter",
          "value": "DT7kRjGFvRKxGSx5CPUCA1pazj6gzJ6Db11xmkX4yYSNK7m"
        },
        {
          "trait": "amountLockedInGovernance",
          "value": "26"
        },
        {
          "trait": "voteDirection",
          "value": "Nay"
        },
        {
          "trait": "delegatedConvictionBalance",
          "value": "0"
        },
        {
          "trait": "royalty",
          "value": "28"
        },
        {
          "trait": "recipient",
          "value": "DhvRNnnsyykGpmaa9GMjK9H4DeeQojd5V5qCTWd1GoYwnTc"
        },
        {
          "trait": "rarity",
          "value": "rare"
        },
        {
          "trait": "totalSupply",
          "value": "74"
        },
        {
          "trait": "name",
          "value": "Rare 155"
        },
        {
          "trait": "description",
          "value": "This is a rare NFT 155"
        },
        {
          "trait": "artist",
          "value": "🦄🦄🦄🦄🦄"
        },
        {
          "trait": "typeOfVote",
          "value": "direct"
        }
      ],
      "meta": {
        "attributes": []
      }
    }
  }
}
```

**Comment by preschian** [comment]
> Also on this item: [kodadot.xyz/ahk/gallery/97-2583060150](https://kodadot.xyz/ahk/gallery/97-2583060150) Only properties from the metadata are displayed while there are many

hi, yes, currently we show properties from metadata only. you can extend here

https://github.com/kodadot/nft-gallery/blob/881fdd43003b8b39d58498789af71944fccab401/components/gallery/GalleryItemDescription.vue#L205-L214

I still get `null` from the indexer

![image](https://github.com/kodadot/nft-gallery/assets/734428/a559e181-dc8f-4b4a-9322-2576543dd7b4)

**Comment by vikiival** [comment]
> I still get null from the indexer

Check pr #6778

**Comment by niklasp** [comment]
Thanks for adressing this quickly. Looks like they match! When can i expect on kodadot.xyz?

**Comment by yangwao** [comment]
> When can i expect on kodadot.xyz?

we are waiting for few PRs being raised and merged and shortly, my humble eta is today EOD

**Comment by niklasp** [comment]
I don't know what you think but imo the attributes from `set_attribute` extrinsics should overwrite those from the metadata in case of duplicates. aka

```js
//pseudocode
const nftProperties = {
  ...attributesFromMetadata,
  ...attributesFromExtrinsics,
}
```

**Comment by vikiival** [comment]
> I don't know what you think but imo the attributes from `set_attribute` extrinsics should overwrite those from the metadata in case of duplicates. aka

Continue in #6785
