### ISSUE TITLE
Distinguish between NFT collected vs obtained

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#678]
Now you can see under this profile, that the last NFT was not bought, but it was sent to the address.
Where for example first NFT was bought. We should think about how to separate those two on UI as future collectors might be spammed in the future.

https://nft.kodadot.xyz/rmrk/u/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd

obtained by SEND https://nft.kodadot.xyz/rmrk/detail/9038614-bc486ed2f30f59f974-ACS-KODA_TOKEN_MEME-0000000000000005
bought by BUY https://nft.kodadot.xyz/rmrk/detail/6650640-0E54E51D92AECA5749-FLASH%20CRASH-FLASH_CRASH-0000000000000002

**Comment by XyloDrone** [comment]
Related to #1190

**Comment by yangwao** [comment]
Continue to https://github.com/kodadot/nft-gallery/issues/898
