### ISSUE TITLE
App favicon replacement

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6784]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/d789d62e-227a-4227-be9b-72fa4ca2508c)
![image](https://github.com/kodadot/nft-gallery/assets/90852205/d11696be-6db4-4970-abb7-e560ff40fa75)
asset: 
### PNG
![Klight V4-favicon](https://github.com/kodadot/nft-gallery/assets/90852205/53c35ca2-feff-483a-af2b-734d03aaafb4)
bigger one 
![Klight V4](https://github.com/kodadot/nft-gallery/assets/90852205/097a9f63-ba02-4b80-a3b9-2ff744b310e0)
### SVG
here if you prefer svg favicon: 
![Klight V4-favicon](https://github.com/kodadot/nft-gallery/assets/90852205/1e7be1c9-7ba1-4fb3-9b94-ba297db00cfd)

**Comment by roiLeo** [comment]
- ref #3345
