### ISSUE TITLE
Do not show burned NFTs in the UI

### ISSUE THREAD

**Issue by obxium** [kodadot/nft-gallery#679]
**Is your feature request related to a problem? Please describe.**

It is completely confusing to display burned NFTs in the gallery views. Most platforms do not do this because once something is burned it exists on-chain only, and there is no good reason to keep displaying that token in the UI.

What's worse, is that if I create a few new tokens in experimentation which are then burned, these worthless tokens are cluttering up my profile and confusing both buyers and collectors.

**Describe the solution you'd like**

Hide burned tokens from all UI presentation views by default.

**Describe alternatives you've considered**

If people really want to see their burned tokens, a separate functionality could be added to provide for that.

**Additional context**

![burned](https://user-images.githubusercontent.com/37124389/131859595-1c4f11e2-6fb2-4181-af43-bbab24c878a5.png)

The items with a 🔥 emoji on them in this screenshot should just not appear at all. This is pretty much the standard across all NFT platforms and so it would be nice to see it here too.

Thanks!

**Comment by yangwao** [comment]
Agree. Let's add p1 & $$ to it.
Related #426
