### ISSUE TITLE
GLB does not trigger preview upload 

### ISSUE THREAD

**Issue by obxium** [kodadot/nft-gallery#680]
**Describe the bug**

I minted an NFT with a GLB media file:

https://nft.kodadot.xyz/rmrk/detail/9050726-34BE282B68C3F03135-FLTS-FRACTAL_LOTUS_1-0000000000000001

The media is not present on any browser that I have access to (most contemporary browsers at latest versions). Instead it looks like this, showing only the KodaDot logo in place of the GLB.

<img width="1213" alt="Screen Shot 2021-09-02 at 10 23 30" src="https://user-images.githubusercontent.com/37124389/131861241-c6abc8cb-2489-465f-bf3b-c1fe73dbcc5a.png">

The file in question, [FLOW1.glb](http://obxium.com/images/fractal-lotus/FLOW1.glb) is approximately 38MB in size. I have used various tools, such as [glTF Validator](https://github.khronos.org/glTF-Validator/) to ensure that the GLB file content is valid, and it is valid.

**To Reproduce**
1. Go to https://nft.kodadot.xyz/rmrk/mint
2. Click on the **Drop your NFT here or click to upload. We support various media types (BMP, GIF, JPEG, PNG, SVG, TIFF, WEBP, MP4, OGV, QUICKTIME, WEBM, GLB, FLAC, MP3, JSON)** uploader
3. Complete required fields
4. **CLICK TO CREATE NFT(S)**

Observe that the finished NFT does not correctly display the GLB model.

**Expected behavior**

The GLB model content should appear within the figure element for the image-preview div.

**Screenshots**

<img width="1213" alt="Screen Shot 2021-09-02 at 10 23 30" src="https://user-images.githubusercontent.com/37124389/131867253-620b8ff7-3434-4dee-ab35-e20e1fb704fd.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2
 - Browser Chrome
 - Version Version 93.0.4577.63 (Official Build)

**Additional context**

I also tried this on contemporary versions of other Desktop browsers to the same effect.

**Comment by vikiival** [comment]
Looks like GLB does not trigger preview upload 

<img width="831" alt="Screenshot 2021-09-03 at 11 04 27" src="https://user-images.githubusercontent.com/22471030/131980192-a29ac6ea-666a-4434-ac80-f350d04757ec.png">
<img width="821" alt="Screenshot 2021-09-03 at 11 04 36" src="https://user-images.githubusercontent.com/22471030/131980203-9dc3c2fe-f842-4aa9-a51a-5521e808145b.png">

**Comment by vikiival** [comment]
@obxium : 
The trick is that files (like mov, json) trigger additional field called poster/cover
then If this field is visible app automatically constructs JSON like

```js
{
  "image": secondFile,
  "animation_url": file
}
```

If the preview upload is not triggered app constructs JSON: 

```js
{
  "image": file,
}
```

In `GalleryItem.vue` I only chceck the mimetype of the secondFile. Thus It fails on render.

But I think we can fix it without re-mint

**Comment by obxium** [comment]
Ahh makes sense @vikiival. Thanks for the explanation.

Is is possible then to use the GLB file again as the value to the poster/cover field in order to have it render in gallery view for the next ones I need to mint?

**Comment by yangwao** [comment]
In gallery view, what would be super heavy on objects I guess as GLB objects are quite big, it's an option to have it.
If we can make it make it load on hover or something like that, that might work. 
You want to save user bandwidth to not load 12x30MB+ files upfront :)

**Comment by obxium** [comment]
> In gallery view, what would be super heavy on objects I guess as GLB objects are quite big, it's an option to have it.
> If we can make it make it load on hover or something like that, that might work.
> You want to save user bandwidth to not load 12x30MB+ files upfront :)

Makes sense, so what do I need to do to have it appear on the actual object page like here:

https://nft.kodadot.xyz/rmrk/detail/5419739-241B8516516F381A-FRACTAL-LOTUS-FRACTAL-LOTUS-1-0000000000000001

Just set the value in `animation_url`?

**Comment by roiLeo** [comment]
> Just set the value in `animation_url`?

Yes this should work!

**Comment by yangwao** [comment]
So time to solve it, somehow? 😄

**Comment by vikiival** [comment]
<img width="1680" alt="Screenshot 2021-09-24 at 21 09 34" src="https://user-images.githubusercontent.com/22471030/134727810-7b3bb006-4918-4a16-8ac9-ad4148337b6c.png">

**Comment by yangwao** [comment]
Closed in #791

**Comment by vikiival** [comment]
Need to convince drop upload to spawn another drop upload for the second file

**Comment by onerawartist** [comment]
![Annotation_2021-11-01_215837.png](https://user-images.githubusercontent.com/71472224/139752771-a5d456e2-d48c-4a07-921a-6ecd06fe2f70.png)

I was told on discord to post my report here ^^
