### ISSUE TITLE
Seems analytics stopped working

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6811]
With a recent canary down, I noticed that ENV for Ganalytics has been removed for production, which could be, but even replacing the back, seems doesn't work.

cc @preschian 
added you to GA 

- #6697 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/99d707c8-e9b7-4ba6-9a19-35303b5510f9)

**Comment by preschian** [comment]
oopps, checking

seems like I forgot to pass the env here https://github.com/kodadot/nft-gallery/blob/main/script/generate.mjs#L20

**Comment by preschian** [comment]
<img width="574" alt="Screenshot 2023-08-19 at 7 03 13 PM" src="https://github.com/kodadot/nft-gallery/assets/734428/66402f95-90bc-4796-8f7d-82d1e42ab63a">
