### ISSUE TITLE
Improvements to landing page SEO

### ISSUE THREAD

**Issue by thnaylor** [kodadot/nft-gallery#6839]
### Is your feature request related to a problem?

Lighthouse is reporting SEO issues on the landing page and scores can be improved.

- network list
- footer social media links
- shopping cart
- Tap targets are not sized appropriately

### Describe the solution you would like

network list
- The network list component has no href links on the network and uses a click event function for navigation and changing the prefix. We could add an to href the links and prevent default actions on the link so the function still does it's job.

footer social media links
- Footer social links uses a click event to the list instead of adding hrefs to the links. Possibly just change it to use hrefs to open a new window instead?

shopping cart
- Shopping cart in the navbar is using an anchor link but it's not actually a link. Possibly change this to use a more appropriate element.

tap targets are not sized appropriately
- On mobile the links in the footer are not atleast 48x48. This would change the UI so it will probably need design intervention to fix.

### Describe alternatives you have considered

/

### Non crawlable links
![image](https://github.com/kodadot/nft-gallery/assets/22052693/657c9715-a94e-4ed0-a566-c7584b57c2e5)

### Mobile
![image](https://github.com/kodadot/nft-gallery/assets/22052693/17080505-ef5b-46a6-be16-c6583af37597)

### Are there opened related issues?

https://github.com/kodadot/nft-gallery/issues/2816

**Comment by yangwao** [comment]
I guess last is related to 
- #6798
