### ISSUE TITLE
Transfer + Sale could be merged to one row in collection activity?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6840]
https://kodadot.xyz/ahk/collection/u-2024/activity

if someone buy NFTs, why it needed to show Sale and Transfer with same credentials? would be possible to duplicate it?

![image](https://github.com/kodadot/nft-gallery/assets/5887929/47e03065-f6df-480f-972a-f9e9ad6972e0)

**Comment by exezbcz** [comment]
Why duplicate it? I would remove the transfer when the sale event happens. It's clear the person now owns the nft. That's what the "from, to" columns are.

**Comment by roiLeo** [comment]
continue in #8226
