### ISSUE TITLE
Test i18n functionality.

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#6846]
It may still be on English version on your side. (check the sreenshot here https://github.com/kodadot/nft-gallery/pull/6834#issue-1858101833)
 Look like there is something wrong with our i18n functionality. After I set the new language on the sidebar and then reload, the language version would turn back to English. 

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/pull/6834#issuecomment-1685273732_

**Comment by yangwao** [comment]
I think there was some hiccups with i18n in past and with migration we will be flexing that one too

**Comment by prury** [comment]
unrelated but related:
some locales also need to be updated in order to reflect the many code changes

**Comment by roiLeo** [comment]
> unrelated but related: some locales also need to be updated in order to reflect the many code changes

link #4868, would you like to work on a particular translation?

**Comment by vikiival** [comment]
> some locales also need to be updated in order to reflect the many code changes

Thinking of using some GPT-3 .. LLM Model to do the heavy lifting

**Comment by prury** [comment]
> 
> link #4868, would you like to work on a particular translation?

Portuguese!

**Comment by roiLeo** [comment]
closed by https://github.com/kodadot/nft-gallery/pull/8299
