### ISSUE TITLE
replace dead bird in footer - Bird is ded, X is new vigilant

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6851]
![image](https://github.com/kodadot/nft-gallery/assets/5887929/d4e30708-79a2-43e0-883d-313ae70cdf49)

-> 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/3fb94261-cce0-4f54-8199-37924a4eb197)

**Comment by thnaylor** [comment]
I see 4 other places around the codebase the "dead bird" is being used. I wonder if we should change them all?

**Comment by yangwao** [comment]
yes 

<img src="https://media2.giphy.com/media/v8k9PaAQphzwI/giphy.gif"/>

**Comment by stephenjason89** [comment]
May i have this? LOL this issue is funny 😄

**Comment by exezbcz** [comment]
<img width="1505" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/eebcee86-c8d9-43d0-a469-d16dd587aec6">
its on font-awesome, lets go

**Comment by exezbcz** [comment]
@stephenjason89 yes, you can take it

**Comment by stephenjason89** [comment]
Thanks guys, will do it tomorrow. It's night time here 😊

**Comment by stephenjason89** [comment]
👋
