### ISSUE TITLE
Ramping service not working?

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#6864]
I tried to add funds to my wallet, but ramping service decided that it was not working. On production. Does this mean we don't have ramping service at all? What happened to Banx?

<img width="890" alt="Screenshot 2023-08-21 at 20 38 43" src="https://github.com/kodadot/nft-gallery/assets/104380776/83f74267-d9fb-4c04-9c57-85a1f72116ae">

**Comment by yangwao** [comment]
They changed something, we are on it
- #6722

**Comment by yangwao** [comment]
Most likely closed in upcoming days by
- #7119
