### ISSUE TITLE
Mixed items in collection

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6873]
https://canary.kodadot.xyz/ahk/collection/u-1002
two collections merged into one view? 
<img width="2001" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/95523506-f891-445d-891a-245b1a8f032b">
- see the cards. They have different collection id

**Comment by roiLeo** [comment]
might be fixed by #6868

**Comment by exezbcz** [comment]
@roiLeo yeah, thanks!
