### ISSUE TITLE
Cannot type decimals on list value field on Basilisk

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6884]
### What happened?

Trying to write values that have decimals resets the input: 

https://github.com/kodadot/nft-gallery/assets/36627808/15cee9e9-a356-4268-ada6-90339e4e1f53

**Comment by peoray** [comment]
can I pick this up if it's ready to be worked on

**Comment by prury** [comment]
> can I pick this up if it's ready to be worked on

Sure, go on

**Comment by peoray** [comment]
Can I get more details on the implementation? Especially where to look. I can see `Royalty rate` in the form allows decimal (0.15), so my first guess would be to do the same for `amount`

**Comment by justskinny5** [comment]
@prury hi, I tested it on Snek and it works fine. it seems like it was fixed?

https://github.com/kodadot/nft-gallery/assets/17610879/60de464b-531c-452a-b289-98d94cbb9850

**Comment by prury** [comment]
> 
> @prury hi, I tested it on Snek and it works fine. it seems like it was fixed?
> CleanShot.2023-08-30.at.20.51.38.mp4

oh, thanks for checking, yes, checked here and seems to be fixed, closing this one then
