### ISSUE TITLE
Deploy ask! implementation on Jupyter A1

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#690]
- [ ] https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.jupiter-poa.patract.cn#/explorer
- [ ] check article on deployment
- [ ] ????
- [ ] PROFIT

**Comment by yangwao** [comment]
https://polkadot.polkassembly.io/post/949

**Comment by vikiival** [comment]
In the meantime we can try `ink!`

**Comment by yangwao** [comment]
<img src="https://media4.giphy.com/media/QSSVcSKeQYJpu/giphy.gif"/>

- #3099
