### ISSUE TITLE
Collections showing all the other items insted of its own items

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6912]
### What happened?

go to https://canary.kodadot.xyz/bsx/collection/1865909717
or any collection, it will not show the NFTs of that specific collection

![image](https://github.com/kodadot/nft-gallery/assets/36627808/3a6e90fb-9e67-42fe-bb54-7437cd67c331)

#6868 fixes it

**Comment by yangwao** [comment]
Same for me

![Screenshot_20230823_200436_Chrome.jpg](https://github.com/kodadot/nft-gallery/assets/5887929/9daf8338-25a6-46dd-a23d-02f0df7050c9)

**Comment by roiLeo** [comment]
<img width="1385" alt="Capture d’écran 2023-10-17 à 4 27 17 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/db65661a-799a-4c26-b77c-99a022bb4ee7">
