### ISSUE TITLE
ohmyfetch package deprecated

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#6913]
- use nuxt equivalent
- or https://github.com/unjs/ofetch

**Comment by yangwao** [comment]
> * use nuxt equivalent

this would be best?

**Comment by Jarsen136** [comment]
> > * use nuxt equivalent
> 
> this would be best?

Inside vue component scope, we could use `usefetch` from nuxt composable. While on the utils functions, we need a fetch suitable fetch package.


>  ofetch is auto-imported by Nuxt and used by the [useFetch](https://nuxt.com/docs/api/composables/use-fetch) composable.
#ref: https://nuxt.com/docs/getting-started/data-fetching

`ofetch` should be a good choice for nuxt migrate.
