### ISSUE TITLE
Followup: Token switching buttons inside transfer - redesign on mobile

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#6929]
### What happened?

Goes after #6895
Redesign the token buttons on transfer for them to look like design: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/0f90d338-bb1f-4ccf-af9d-a9e24da4a6f2)

https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=692-6761&mode=design

**Comment by floyd-li** [comment]
gonna take it after prev pr get merged
