### ISSUE TITLE
Update sub-api package

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#6931]
https://www.npmjs.com/package/@kodadot1/sub-api

- ref https://github.com/kodadot/packages/issues/160

⚠️ we still use `import Connector from '@kodadot1/sub-api'`

**Comment by yangwao** [comment]
breaking version incoming

**Comment by roiLeo** [comment]
Hello @vikiival any idea how to rewrite these lines with new version of sub-api?
https://github.com/kodadot/nft-gallery/blob/347e99cc735303f9f656a1982292de584bcd756a/components/transfer/Transfer.vue#L751-L753
