### ISSUE TITLE
update new logo to og social cards 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6942]
till will be fixed, I would add new logo, white one probably as currently we can't detect what is background / collection image there

![image](https://github.com/kodadot/nft-gallery/assets/5887929/fd01aeb0-bd92-4781-9024-45dde0193933)

- #5426 

https://twitter.com/KodaDot/status/1695046915388293392

**Comment by Jarsen136** [comment]
> till will be fixed, I would add new logo, white one probably as currently we can't detect what is background / collection image there
> 
It's related to the service `og-image-green-seven.vercel.app`
I would like to make it but only the team member on vercel could reach that service I guess. @yangwao

**Comment by roiLeo** [comment]
same as https://github.com/AndreyGrin/og-image/pull/2 or wait for SSR

**Comment by yangwao** [comment]
Meanwhile done here for collections
- https://github.com/kodadot/workers/pull/194
