### ISSUE TITLE
Not calculating usd total amount in confirmation modal 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6943]
<img width="446" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/eb01cfeb-dfb8-4c61-b548-07f7e2d171eb">
<img width="207" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/a87e536f-bf24-40e1-974b-d0f8f2cb0acc">

**Comment by xiiiAtCn** [comment]
👋

**Comment by prury** [comment]
here it works 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/eec65ad8-c898-4404-990e-237e5f1ea8e0)

**Comment by exezbcz** [comment]
@prury did you manage to reproduce the bug? 👀

**Comment by prury** [comment]
> @prury did you manage to reproduce the bug? 👀

i did manage do reproduce another one that its similar 😄

Polkadot Assethub: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/e0fe5cc1-4efb-4460-a580-761ec0e9e85a)

**Comment by xiiiAtCn** [comment]
@exezbcz could you tell me how to reproduce this bug? I tried several times but not catch this wierd dialog.

**Comment by exezbcz** [comment]
Did not manage to find any steps to reproduce, One thing that happened to me was the incorrect amount calculation on Polkadot asset hub
