### ISSUE TITLE
Wrong Price in items explorer

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#6961]
### What happened?

DOT price and usd price are not matched in shopping cart and in confirm purchase modal
USD price is 100X lower then it should be

### Please reproduce in steps

1.go here:
/ahp/gallery/0-18

add it to shopping cart
USD price should be 100X more (in shopping cart)

2. go to any item in ahp explore
/ahp/explore/items?listed=true

click ' buy now"
USD price in the confirm purchase modal should be 100X more

### Expected Behavior

matching price

### Are you logged in?

None

### Screenshots

![image](https://github.com/kodadot/nft-gallery/assets/22791238/655e404f-1594-4d0f-93b1-445e045dae4c)

![image](https://github.com/kodadot/nft-gallery/assets/22791238/3d26e5f2-f9c2-4fb4-8a98-699b89202256)

![image](https://github.com/kodadot/nft-gallery/assets/22791238/7895b580-f581-4e0e-be26-81dd5c16d9d6)

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
related to https://github.com/kodadot/nft-gallery/issues/6943
