### ISSUE TITLE
Balance issues on Create collection and Create Token in Basilisk

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#6995]
I wanted to create a collection on Basilisk

1. If I am paying fees in KSM, I want to see my KSM balance, not BSX balance

![image](https://github.com/kodadot/nft-gallery/assets/22791238/d19542df-5c93-430a-9ae5-cd84c948e9d1)

2. I can't mint a collection, even though I have a sufficient balance of both BSX and KSM

![image](https://github.com/kodadot/nft-gallery/assets/22791238/4a006c09-371f-4b7b-9c0d-9802103182cd)

3. same issue when trying to mint NFT on Basilisk

**Comment by prury** [comment]
Related: #6134
