### ISSUE TITLE
HTML lang attribute missing

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7001]
It needs to be added to static HTML layout and should be ok for rest of pages?

![image](https://github.com/kodadot/nft-gallery/assets/5887929/b791a464-9f4a-4b6a-8f29-baf4720ea43e)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/81aa45c1-d1e3-4b70-af6a-2411f071a0d8)

**Comment by roiLeo** [comment]
might comes from [ssr-opengraph](https://github.com/kodadot/workers/blob/main/ssr-opengraph/src/index.tsx) workers

**Comment by Jarsen136** [comment]
> might comes from [ssr-opengraph](https://github.com/kodadot/workers/blob/main/ssr-opengraph/src/index.tsx) workers

I agree. Let's have a try. https://github.com/kodadot/workers/pull/144

**Comment by vikiival** [comment]
Deployed
https://github.com/kodadot/workers/actions/runs/6026487706
