### ISSUE TITLE
Follow up: Fix quick explore links on mobile - modal not closing

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7004]
### What happened?

Introduced by #6989 

https://github.com/kodadot/nft-gallery/assets/36627808/65cda528-0c4b-44ca-bc71-795e7bc45d35

**Comment by prury** [comment]
my bad, Exez already opened a similar one

**Comment by exezbcz** [comment]
Continue to: 
- #7003

gotta go fast 
<img src="https://media3.giphy.com/media/gjfbSsz2EnNMLpRyqb/giphy.gif"/>

**Comment by prury** [comment]
let me close it properly
