### ISSUE TITLE
Collection/NFT creation not working on Basilisk or koda is not reflecting chain changes

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7016]
### What happened?

Tried several times today: 
https://basilisk.subscan.io/tx/0xc1c032d4180d53237cd75ea38e847282b5f08804fcd124fb3e2726fda4a876ab
https://canary.kodadot.xyz/bsx/collection/282897835-3

https://basilisk.subscan.io/tx/0xb6de0a32377a3a3e60f84fcf3cf55ee2792d01a671f4077cfdb3604d709fd089
https://canary.kodadot.xyz/bsx/collection/830716288

https://basilisk.subscan.io/tx/0x95267efa8c286d3dd96450e63854ac68335376f7bad4733902643f5e090a2e5f
https://canary.kodadot.xyz/bsx/collection/3683667089

https://basilisk.subscan.io/tx/0xf40c9239d98ad6129974033863811f717bd067df1a03b26b0ce2ccc7db215d03
https://canary.kodadot.xyz/bsx/collection/3701960329

### Please reproduce in steps

Create on BSX, collection or NFT

**Comment by vikiival** [comment]
Transaction passed more of an issue from indexer / rpc side

**Comment by yangwao** [comment]
Related ?
- https://github.com/kodadot/snek/issues/184

**Comment by vikiival** [comment]
Yup fixed in

- https://github.com/kodadot/snek/pull/185

Deploying rn 

- https://github.com/kodadot/snek/actions/runs/6025069399

**Comment by vikiival** [comment]
One more

- https://github.com/kodadot/snek/actions/runs/6025377375

**Comment by vikiival** [comment]
Third 
- https://github.com/kodadot/snek/actions/runs/6026455318

**Comment by vikiival** [comment]
@prury 
Indexer should be fully working again, please let me know if some other error occurs.
If you see all your NFTs/collection please close this

<img width="720" alt="Screenshot 2023-08-30 at 18 09 02" src="https://github.com/kodadot/nft-gallery/assets/22471030/c4991587-38c5-4c3b-b07e-50dadb4ddd86">

**Comment by prury** [comment]
issue solved!
