### ISSUE TITLE
Adds Job section

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#702]
We will be looking for talent, on a perpetual basis. 
Just need fillup one-liners there so it can spread the word:)

- technical product manager for metaprime
- BD & comms
- AAA frontend devs
- Substrate devs
- growth hacker if there will be good one!
- Meme lords and great stewards?

**Comment by vikiival** [comment]
kodadot.xyz/jobs ?

**Comment by roiLeo** [comment]
closed in #1696
