### ISSUE TITLE
In creating mint on we should calculate costs for existential deposit

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7020]
For 
- AHP
- AHK
- BSX

![Screenshot_20230829_112138_Telegram.jpg](https://github.com/kodadot/nft-gallery/assets/5887929/ab3a173d-9df6-4785-a613-72b659fc0535)

Related
---
- #6738

**Comment by preschian** [comment]
How much ED for bsx and ahk?

**Comment by vikiival** [comment]
AHK - 0.000033333333 KSM
BSX - 1.0000 BSX || or some KSM denomination need to ask

cc @jak-pan

**Comment by vgantchev** [comment]
The Basilisk chain has the following EDs:
* 0,000297 KSM
* 1 BSX
