### ISSUE TITLE
Assets page does not show balance

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#7025]
select Basilisk network
Go to assets page

![image](https://github.com/kodadot/nft-gallery/assets/22791238/e5c6771d-e1cb-43d4-9bfb-c2df50a4c8ca)

**Comment by yangwao** [comment]
Maybe?
- https://github.com/kodadot/snek/issues/184

**Comment by dmackjaygee0321** [comment]
👋

**Comment by roiLeo** [comment]
- closed as completed
