### ISSUE TITLE
Refactor SearchSuggestion - NFT search suggestions won't load

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7028]
NFT search suggestions won't load
same for navbar search

Probably fixed, but checking to be sure
- #6999 

https://github.com/kodadot/nft-gallery/assets/36627808/86cec300-31e4-44bd-9b7a-308c143887ff

_Originally posted by @prury in https://github.com/kodadot/nft-gallery/issues/6999#issuecomment-1696071583_

**Comment by prury** [comment]
it works @yangwao

**Comment by newraina** [comment]
can be closed

**Comment by prury** [comment]
> can be closed

yup, ty, closed as completed by #6999
