### ISSUE TITLE
Status signaling for collections

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#703]
mne by sa ešte v nahladoch kolekcií toto velmi páčilo - či už z pohľadu kupujúceho (lahšie sa rozhodne, že dobre tak toto ludia kupujú, to kúpim aj ja) tak aj z pohladu predávajúceho (že fíha, tak už 10 ludí vlastní nftčko z mojej kolekcii? :smile: )

To engage more collectibles as SoV from the perspective of collectors and appreciate the great work of creators, would be nice to leverage subquery to enhance the collection view for 
- [ ] number of items
- [ ] owners (number of address that has it?)
- [ ] floor price (this would be a harder one but I guess WAGMI!)
- [ ] total volume traded
- [ ] 24h volume traded

originally raised by @jkdizajn
![image](https://user-images.githubusercontent.com/5887929/132475508-b95225de-6aad-40dc-9195-cef05a5da4f0.png)

i.e collections to test 
- https://nft.kodadot.xyz/rmrk/collection/cadffbe2992cea506c-CAVDO
- https://nft.kodadot.xyz/rmrk/collection/900D19DC7D3C444E4C-KSMG22

or feel free put one we should do test case against!

**Comment by vikiival** [comment]
Yes we need that panel!

**Comment by vikiival** [comment]
>  volume traded could be done

Is this an all time metric or just last 24 hrs ?

**Comment by jkdizajn** [comment]
> 
> 
> > volume traded could be done
> 
> Is this an all time metric or just last 24 hrs ?

No, this is the total volume, i think...

**Comment by roiLeo** [comment]
> Yes we need that panel!
> 
> Afaik, there is already a component for that in Bulma/Buefy

[This one](https://bulma.io/documentation/layout/level/)

**Comment by yangwao** [comment]
> Is this an all time metric or just last 24 hrs ?

I guess we can go for both, total and 24h ?
