### ISSUE TITLE
Fix failed payments on pull-requests

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7035]
- mix of issues looks like
- 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/a8cc8e61-7ae2-4e30-8844-4cfe995b4a67)

- https://polkadot.subscan.io/account/14SprTXXg5Bdgj8qV6ds57mevDwAib4SKLg6R8Lc6TzeDcLa?tab=transfer

![image](https://github.com/kodadot/nft-gallery/assets/5887929/348a75cd-e6a7-453e-9fbb-f82b7984add0)

- add your failed PRs, will process tmrw

- impressive, bot hijack 😅 seems Github Webhooks <> Autocode Gateway has some delayed dispatch
- https://github.com/kodadot/nft-gallery/pull/7011#issuecomment-1697932071
- ah here we go github degraded webhooks
- https://www.githubstatus.com/
![image](https://github.com/kodadot/nft-gallery/assets/5887929/2961690e-7c7a-41ab-a9c7-e91534e11d62)

**Comment by yangwao** [comment]
pay 30 usd

**Comment by justskinny5** [comment]
https://github.com/kodadot/nft-gallery/pull/7018 is failed

**Comment by thnaylor** [comment]
#7017 failed

**Comment by hassnian** [comment]
#6895 failed

**Comment by yangwao** [comment]
4 out of 6 done

Fixed
---
- #6985 
- #7018 
- #7017 
- #6895

**Comment by yangwao** [comment]
I think 6999 was double so it should be ok! 
If anyone found failed payment, feel free reopen.
