### ISSUE TITLE
KodaDot Landing: Translating partially

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7046]
One artist has an issue: Our platform is partially translated into Russian. He speaks Russian, but still, it's annoying.
It's happening for him only on KodaDot. 

![2023-08-30 13 12 08](https://github.com/kodadot/nft-gallery/assets/104380776/2ac4f26b-ef00-4789-918d-8e7946641eaa)

**Comment by Jarsen136** [comment]
related to https://github.com/kodadot/nft-gallery/issues/3916

**Comment by yangwao** [comment]
> He speaks Russian, but still, it's annoying.

@JustLuuuu  can he get us someone to do the whole translation?

**Comment by JustLuuuu** [comment]
> > He speaks Russian, but still, it's annoying.
> 
> @JustLuuuu can he get us someone to do the whole translation?

Im sure he can. I will ask. the thing is that he speaks English and he wants it to stay in English. I would just make sure that the landing is not translated at all to Russian. Its not the priority to have it in Russian and we decided few months ago that we don't want to have that many options with translations because it was messy and translations were not updated.

The goal of this issue was to try to fix the translating part so it does not translate. We don't have russian as an options so I have no idea why did it translate :D

<img width="238" alt="Screenshot 2023-08-30 at 15 37 16" src="https://github.com/kodadot/nft-gallery/assets/104380776/fa0713e0-e7f1-4812-b064-ea938ae3034b">

**Comment by roiLeo** [comment]
> The goal of this issue was to try to fix the translating part so it does not translate. We don't have russian as an options so I have no idea why did it translate :D

Check browser language settings.

**Comment by Jarsen136** [comment]
> > The goal of this issue was to try to fix the translating part so it does not translate. We don't have russian as an options so I have no idea why did it translate :D
> 
> Check browser language settings.

It should come from our projects as we have the translation JSON for russian. It's related to the i18n modules.
<img width="422" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/b31a4feb-4da9-4bee-97bd-7c693ec38851">
