### ISSUE TITLE
Introduce basic testing framework

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#707]
I was long time skipping this but I guess hence will be transitioning to #584 Nuxt, we want to avoid as many dragons along the road. Thus having some testing suite would be more than welcome to keep some flow is present.

Ideas for the testing framework we should use and why?

**Comment by JKrupinski** [comment]
Jest for unit tests
Cypress for e2e tests
I think they are easy to use and most known

**Comment by vikiival** [comment]
Playwright looks hot

https://github.com/galacticcouncil/Basilisk-ui/blob/develop/e2e-tests/utils/polkadot-dapp-utils.ts

**Comment by yangwao** [comment]
Meanwhile we have tests, after all 

- #3451 
- #3689
