### ISSUE TITLE
Making minting on Asset Hub Polkadot Minting work before Berlin? 😄

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7086]
Can we focus on making minting on Asset Hub Polkadot Minting work before Berlin? 😄

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/7049#issuecomment-1702457229_

**Comment by vikiival** [comment]
Cc @daiagi i can check That

**Comment by daiagi** [comment]
Nothing needs to be done
Works already on canary
https://canary.kodadot.xyz/ahp/gallery/4-1
[mint collection tx](https://assethub-polkadot.subscan.io/extrinsic/4484236-2)
[mint token + list tx](https://assethub-polkadot.subscan.io/extrinsic/4484248-2)

**Comment by yangwao** [comment]
> Nothing needs to be done

cc @JustLuuuu 
https://canary.kodadot.xyz/ahp/create?tab=Collection
