### ISSUE TITLE
Highlight for AHK and AHP collection deposit is refundable

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7097]
I think we could highlight that deposit is refundable somewhere in UI after destroying collection

**Comment by exezbcz** [comment]
And is burn working? I dont have any collection personally.

**Comment by exezbcz** [comment]
is this it? 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/98470088-0511-423b-af3b-e9d36f51760e)
