### ISSUE TITLE
Recommend ES6+ methods bot

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7106]
Is there Eslint or another bot to suggest this? 
As I've seen this is quite common here and there

![image](https://github.com/kodadot/nft-gallery/assets/5887929/4f00317c-5c49-4b3f-985f-f773613ecef3)

rel
---
- https://github.com/kodadot/nft-gallery/pull/7076

**Comment by stephenjason89** [comment]
Should I also update the STYLE_GUIDE? I'll make a PR for it tomorrow
<img width="1078" alt="image" src="https://github.com/kodadot/nft-gallery/assets/3810177/61e4b343-6f1b-49b5-a849-69f0a12e6e3a">

**Comment by floyd-li** [comment]
maybe this rule can help?
https://github.com/airbnb/javascript#iterators--nope

**Comment by yangwao** [comment]
> Should I also update the STYLE_GUIDE? I'll make a PR for it tomorrow

I guess so



> airbnb/javascript#iterators--nope

we can adopt, but not whole as it's quite big

**Comment by floyd-li** [comment]
> we can adopt, but not whole as it's quite big

yes. i may update the config for this one later
