### ISSUE TITLE
Some Trending Collections not showing all its items on RMRK

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7114]
### What happened?

By looking at these collections activity, i can tell that they have a lot more items than they are showing in the explorer: 

<img src="https://github.com/kodadot/nft-gallery/assets/36627808/a0557b20-a632-493d-8caa-2dea1318f10d" width="600">

 https://canary.kodadot.xyz/rmrk/collection/dac5c7f54029d0e73c-HXAI8

<img src="https://github.com/kodadot/nft-gallery/assets/36627808/bb799ba3-6a37-4e1b-9edb-84aa0c8157b3" width="600">

https://canary.kodadot.xyz/rmrk/collection/2644199cf3652aaa78-KK01

**Comment by floyd-li** [comment]
i believed this is related with this:

https://github.com/kodadot/nft-gallery/blob/fb68f30d60824c8d3552203af9e0547d74a4ce1f/queries/subsquid/general/nftListWithSearch.graphql#L16-L21

we do not display burned items in the list. should we display all including burned items?

**Comment by prury** [comment]
> i believed this is related with this:
> 
> https://github.com/kodadot/nft-gallery/blob/fb68f30d60824c8d3552203af9e0547d74a4ce1f/queries/subsquid/general/nftListWithSearch.graphql#L16-L21
> 
> we do not display burned items in the list. should we display all including burned items?

thanks for researching it! nope, we should not display burned items, thank you, closing this one
