### ISSUE TITLE
Classic mint on AssetHub Kusama not working

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7127]
This was merged 3 days ago:
- https://github.com/kodadot/nft-gallery/pull/7091

Today, I tried to create a collection on Asset Hub Kusama, and it's not working. I got stuck in here:
<img width="1458" alt="Screenshot 2023-09-04 at 13 33 01" src="https://github.com/kodadot/nft-gallery/assets/104380776/3dde9154-24cd-4717-bdab-e49a867b114b">

I need this to work asap

**Comment by vikiival** [comment]
@JustLuuuu can you please give more content? 
Was it canary / prod?
Which browser?

**Comment by yangwao** [comment]
last relase was 3 days ago
- https://github.com/kodadot/nft-gallery/pull/7093

**Comment by JustLuuuu** [comment]
> @JustLuuuu can you please give more content? Was it canary / prod? Which browser?

chrome, its in production, the artist pointed it out to me and when I tried it its was not working.

**Comment by vikiival** [comment]
Hello,

I just minted Waifu from prod, via chrome.
If it was stuck on upload it is possible that you artist uploaded a big file?
Or how is your internet connection?

<img width="903" alt="Screenshot 2023-09-04 at 12 54 11" src="https://github.com/kodadot/nft-gallery/assets/22471030/546e1555-472b-40a7-80cf-41bc68056b7a">

**Comment by vikiival** [comment]
But thanks to you I found very funny bug
- #7128

**Comment by JustLuuuu** [comment]
Its working for me now. Idk where the issue was. Maybe the internet. I will connect with the artist and let you know.

**Comment by vikiival** [comment]
> I will connect with the artist and let you know.

please once you get response please close issue as not planned or edit the description, thanks

**Comment by JustLuuuu** [comment]
the issue did not appear again
