### ISSUE TITLE
RMRK2 minting error

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7133]
### What happened?

An artist using Nova wallet is unable to add more NFTs to her collection. She was able to add one. Now she is getting an error.

Collection: https://kodadot.xyz/ksm/collection/A20986FF921B82A06C-WHC one NFT was added; next one is not possible. Wallet: Nova wallet.

Error message:
![2023-09-04 15 50 28](https://github.com/kodadot/nft-gallery/assets/104380776/eb8e2748-6106-4d50-8ed2-05384ee2b47e)

### Please reproduce in steps

Nova Wallet: minting NFT (adding NFT to existing collection)

### Expected Behavior

mint without issues

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Screenshots

added

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustLuuuu** [comment]
her address: GEn74YSY6scZRozMi1prDyMP6toAz6stgiFK1LWzGSZB4TC it was yesterday around 3 pm CET. She tried to mint later - it worked. But still, getting wrrors like this is discouraging

**Comment by vikiival** [comment]
Hey @JustLuuuu looks like Nova Wallet has some problems with provided RPC nodes. I will try to reach them, can he/she try to mint it via Desktop?

**Comment by JustLuuuu** [comment]
> Hey @JustLuuuu looks like Nova Wallet has some problems with provided RPC nodes. I will try to reach them, can he/she try to mint it via Desktop?

Sadly no, I asked her about that. I also told her to try it again, restart and turn off everything. One other artist was able to mint properly. So lets see
