### ISSUE TITLE
Error Message Not Consistent With Language Settings

### ISSUE THREAD

**Issue by xiiiAtCn** [kodadot/nft-gallery#7151]
### What happened?

I set `Language` to English. But the error message shows in Chinese.

### Please reproduce in steps

1. Choose chain `Kusama`
2. `Create` -> `Classic`

### Expected Behavior

error message shows in which language I choose

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Kusama

### Screenshots

<img width="1199" src="https://github.com/kodadot/nft-gallery/assets/22696500/ac3ed9b3-2c3c-4330-a08b-b67fff69350f">

### Payment link for reward

 [Payout](https://kodadot.xyz/dot/transfer?target=12jXHf7yYF4wTRjDPbwFB24V1nVRPRkuU2S8Ke5ZWTfvyBGW&usdamount=8.82&donation=true)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
this is the expected result, please change your browser language if you want to see message in english
