### ISSUE TITLE
Listing NFT for sale: Showing approximate price in USD

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7157]
## Example that is already working
Its possible to see the approximate price in USD if you are using the Teleport Bridge feature on KodaDot. If you open Teleport and decide to teleport your assets, you are able to see how much of the assets you are Teleporting. Like this: 
<img width="1375" alt="Screenshot 2023-09-05 at 12 46 44" src="https://github.com/kodadot/nft-gallery/assets/104380776/44c658dc-ad9d-4228-92b5-0f701f10da26">

## Suggestion - Listing NFT for Sale
It would be very cool to have this option (to see the price in USD) also when you list NFT for sale:

1) After you create a collection and decide to add NFT to the collection and directly list it for sale. I checked on rmrk2 and assethub we don't have it now.
Create - NFT:
<img width="1420" alt="Screenshot 2023-09-05 at 12 49 00" src="https://github.com/kodadot/nft-gallery/assets/104380776/c87d3ab1-f3aa-4d15-b2e3-80a7d0a84ed9">

2) When you decide to list the NFt you own for sale:
Profile - Collected/Created NFTs - List for sale
<img width="1435" alt="Screenshot 2023-09-05 at 12 52 16" src="https://github.com/kodadot/nft-gallery/assets/104380776/259807e8-e61d-433b-9354-1779755626a3">

Both these options should show how much you are setting the price for approximately. To make it easier for people to decide what price should their NFT have. And to make it more user friendly.

**Comment by exezbcz** [comment]
> 3\. When you decide to list the NFt you own for sale:
>     Profile - Collected/Created NFTs - List for sale

As mentioned in last week's meta :D 

- https://github.com/kodadot/nft-gallery/issues/7026


we could add it to simple mint v2 design, lets add the USD value to the price input field 
- Please follow the same design pattern as in the teleport
