### ISSUE TITLE
Dashboard for NFT drop

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#716]
The first iteration for NFT drops. 
When you open collection, there should be a button to distribute NFTs to list of addresses

- put a list of addresses to send
- check if the address has an existential deposit 
- if an address does not have it, send it
- show approx costs for drop incl sending existential deposit and transaction fees
- construct batch tx

existential deposit is 33.3333 micro KSM

**Comment by yangwao** [comment]
- #6300 
- #6478 

and soon with admin panel for drops we can make this one to close?

**Comment by JustLuuuu** [comment]
we have drop pages: https://kodadot.xyz/ahp/drops/rift
