### ISSUE TITLE
Make notifications more actionable

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7160]
Can we include a link on a current item bought, for example?
I think we are losing good CTA action from users here

![image](https://github.com/kodadot/nft-gallery/assets/5887929/ddc199c2-3212-4588-9aa0-635f50d1c69f)

**Comment by exezbcz** [comment]
Partly solved here: 
- https://github.com/kodadot/nft-gallery/issues/10090

will add more styles gradually, we have a success modal for this case
