### ISSUE TITLE
Format for the mass minting

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#7162]
### Is your feature request related to a problem?

Mass minting is nice but the instructions are bit unclear

<img width="775" alt="Screenshot 2023-09-05 at 15 31 23" src="https://github.com/kodadot/nft-gallery/assets/22471030/f597d24b-5749-4003-aa23-cca66fecc15e">

### Describe the solution you would like

How should the files look like? 

### Describe alternatives you have considered

~

### Screenshots

<img width="453" alt="Screenshot 2023-09-05 at 15 27 12" src="https://github.com/kodadot/nft-gallery/assets/22471030/b6e117ae-1432-4531-b6ba-da686d5fcb5e">

**Comment by prury** [comment]
Indeed, 
Correct format is as follows:

file: 1.jpg
name: nftname1
description: nft description 1
price: 0.5 KSM

file: 2.jpg
name: nftname2
description: nft description 2
price: 0.6 KSM

file: 3.jpg
name: nftname3
description: nft description3
price: 0.7KSM

**Comment by exezbcz** [comment]
duplicate: 
- https://github.com/kodadot/nft-gallery/issues/6034

**Comment by daiagi** [comment]
Closing this issue.
I'll handle #6034
