### ISSUE TITLE
RMRK2: .glb file not possible to mint

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7180]
### What happened?

The same artist as in issue #7176 has an issue on production - RMRK2. 
[This artist](https://twitter.com/decentralize___) is trying to mint 3D files - .glb. He managed to mint one NFT in his collection: https://kodadot.xyz/ksm/collection/26A39DB07731155A62-DFW. He has a problem trying to upload the second NFT. 

The moment he click on the glb. file he will got this small red notification (Please Select a file)
![ez_aco9P](https://github.com/kodadot/nft-gallery/assets/104380776/9fd50578-7ac9-4c25-b5c0-6a3192dc886a)

Video:

https://github.com/kodadot/nft-gallery/assets/104380776/196e1248-c557-4864-9ab5-7285f4859a11

### Please reproduce in steps

**Mint rmrk2**: Create: NFT (add nft to existing collection) - upload the NFT .glb file (get small notification)

### Expected Behavior

upload the NFT

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Screenshots

added

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustLuuuu** [comment]
0:06 seconds of the video: <img width="1450" alt="Screenshot 2023-09-06 at 12 06 18" src="https://github.com/kodadot/nft-gallery/assets/104380776/ec2c5713-9783-48af-8438-a00db609cbc5">

There is no glb in the options? Maybe that has something to do with it

**Comment by roiLeo** [comment]
> There is no glb in the options? Maybe that has something to do with it

yes

**Comment by JustLuuuu** [comment]
@roiLeo 
<img width="405" alt="Screenshot 2023-09-08 at 10 16 49" src="https://github.com/kodadot/nft-gallery/assets/104380776/2e8ef7e0-48fb-4da0-b60c-6ab3f7c3e4a9">

Should I reopen this issue?

**Comment by roiLeo** [comment]
> Should I reopen this issue?

this has not been released on prod yet, try on canary.kodadot.xyz/ or wait for new release (imo early afternoon)

**Comment by JustLuuuu** [comment]
> new

Ah sorry, my bad, ofc I don't see the release.
