### ISSUE TITLE
Drops page redirect to NFT doesn’t show the nft, mint doesn’t update

### ISSUE THREAD

**Issue by helloitsdamsky** [kodadot/nft-gallery#7186]
### What happened?

I went to drops on AHK and minted a shanghai waifu t-shirt.
After redirect (which takes very long),  the NFT doesn’t show up
When i come back, the state isn’t updated and i can mint the NFT again, which shouldn’t be possible

address used ( AHK ) H56NQrVAH4oyJPiYVqhTsA3uTcfAdcNaYtkfEGai9jyVnhE

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

canary.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

<img width="420" alt="image" src="https://github.com/kodadot/nft-gallery/assets/92786519/032bfc77-3997-444f-9f57-f15889a5e2c1">

### Relevant log output

```shell
/ didnt show bug
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarsen136** [comment]
This issue should have been solved recently. Could you please share the URL that dose not show your NFT? @helloitsdamsky 

https://kodadot.xyz/ahk/collection/32
<img width="1312" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/be12bbb8-9b91-47f5-8a04-dbef1eb084eb">

**Comment by helloitsdamsky** [comment]
> One possility is that frontend does not count that there should be one drop per address.

when i came back to the minting, i could remint like i didn’t do anything
