### ISSUE TITLE
Clearing localstorage will glitch the app (Unable to retrieve a keypair)

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7187]
Artist (tg: @Frankford18) is trying to mint his collection: https://kodadot.xyz/ahk/collection/120
Production, AssetHub

He is getting this error:
![2023-09-06 13 58 48](https://github.com/kodadot/nft-gallery/assets/104380776/f0ff724f-37ab-4809-833e-8add914a9eb1)

What it is?

**Comment by roiLeo** [comment]
https://docs.kodadot.xyz/tutorials/how-to-fix-error-keypair.html#_2-browser-update might help

Maybe try to clear browser cache?

**Comment by JustLuuuu** [comment]
> https://docs.kodadot.xyz/tutorials/how-to-fix-error-keypair.html#_2-browser-update might help
> 
> Maybe try to clear browser cache?

thank you, will tell him to try

**Comment by JustLuuuu** [comment]
> https://docs.kodadot.xyz/tutorials/how-to-fix-error-keypair.html#_2-browser-update might help
> 
> Maybe try to clear browser cache?

he did, he tried to do it all - all steps in the document you sent, he has no metadata update in polkadot.js and he ist still getting this error. His address: HC8PkF1x3LLTVpFXNuy2i8h7btKk5ZGxDX8dFZPaLPV2m87

**Comment by JustLuuuu** [comment]
He tried:
- delete cookies, cache
- restart laptop
- remove and add wallet (by accident)
- update his metadata in the wallet
- I sent him more funds

His reply:
![IMG_6891](https://github.com/kodadot/nft-gallery/assets/104380776/00cf578a-24e9-47eb-b5ae-3382f56ef3c7)

**Comment by vikiival** [comment]
@roiLeo would you think it would be too bad to spawn prompt and ask user which wallet does he use?

**Comment by vikiival** [comment]
@JustLuuuu for the context this bug happens when app is trying to find a wallet which user used to log in. If app fails to do this task, it would try to find your Wallet JSON in localStorage (aka keyring) and when it also fails it will spawn this dialog.

I am thinking to remove the keypair storage but need another fallback for the user

**Comment by roiLeo** [comment]
> @roiLeo would you think it would be too bad to spawn prompt and ask user which wallet does he use?

wdym? looks bad for UX, maybe we can throw error in sentry.
does this occur before or after the validation popup in extension?

**Comment by vikiival** [comment]
> does this occur before or after the validation popup in extension?

As I wrote above the error is thrown when app cannot find wallet we can try rather say unable to communicate with wallet please relogin

**Comment by vikiival** [comment]
I would still open issue to rework the signing 😇🫶

**Comment by roiLeo** [comment]
> I would still open issue to rework the signing 😇🫶

could you please share step to reproduce?

**Comment by vikiival** [comment]
1. Login
2. Clear localstorage
3. Sign anything

This should fail imo

**Comment by vikiival** [comment]
Yup I was able to reproduce :)

<img width="1668" alt="Screenshot 2023-12-27 at 10 39 54" src="https://github.com/kodadot/nft-gallery/assets/22471030/adcff3a2-5bb6-4ff2-a470-b93ea7abe36b">
