### ISSUE TITLE
Ahk new collections are not appearing in search

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7192]
I noticed that new collections on ahk on production minted recently are not appearing in search properly. 

## Mexican Toys:
- https://kodadot.xyz/ahk/collection/121
- Does not appear when you search for it
<img width="1431" alt="Screenshot 2023-09-06 at 18 41 27" src="https://github.com/kodadot/nft-gallery/assets/104380776/ffec48b6-aa68-4a12-8358-67329eb69a14">

- Appears when you click See All:
<img width="1419" alt="Screenshot 2023-09-06 at 19 05 11" src="https://github.com/kodadot/nft-gallery/assets/104380776/9194d35d-13d7-4272-bf75-b44cd8f8ce4a">

## Mixed collection
- https://kodadot.xyz/ahk/collection/125
- Does not appear when you search for it
<img width="1392" alt="Screenshot 2023-09-06 at 18 59 54" src="https://github.com/kodadot/nft-gallery/assets/104380776/1f850b0c-ab64-4f1e-8ce5-b6f50e6c61f5">

- appears when you click enter(see all)
<img width="1417" alt="Screenshot 2023-09-06 at 18 59 59" src="https://github.com/kodadot/nft-gallery/assets/104380776/f36e26db-297c-4a5a-a563-50c2a6fd08c3">

## Decoded Hybrid collection
- works (older collection)
<img width="1438" alt="Screenshot 2023-09-06 at 19 01 03" src="https://github.com/kodadot/nft-gallery/assets/104380776/02eefe5c-bd45-4790-96ba-9ad70ddb7948">

**Comment by vikiival** [comment]
Looks like bug on my side

**Comment by yangwao** [comment]
update?

**Comment by vikiival** [comment]
Updated all chains: `ahk, ahp, ksm` with last minted collections in 180 days (in case of Ah*, 30 in case of ksm), with min supply of (5, 20 in ksm)

<img width="616" alt="Screenshot 2023-09-25 at 14 26 32" src="https://github.com/kodadot/nft-gallery/assets/22471030/41dd5272-206d-45e4-a704-9081fc9da789">

**Comment by vikiival** [comment]
<img width="680" alt="Screenshot 2023-09-25 at 14 33 36" src="https://github.com/kodadot/nft-gallery/assets/22471030/3c0081a1-76a1-462f-9490-5012b1d3883d">

Apparently there is a bug

<img width="1680" alt="Screenshot 2023-09-25 at 14 34 42" src="https://github.com/kodadot/nft-gallery/assets/22471030/b76387c6-8b24-407b-b615-52981d675521">

**Comment by Jarsen136** [comment]
> Apparently there is a bug
> 
> <img alt="Screenshot 2023-09-25 at 14 34 42" width="1680" src="https://user-images.githubusercontent.com/22471030/270341934-b76387c6-8b24-407b-b615-52981d675521.png">

The collection id is missing on the result from the search api `https://polysearch.w.kodadot.xyz/search` @vikiival 
<img width="1590" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/a235ccda-9af2-406a-b6af-4237caf9a789">

**Comment by vikiival** [comment]
kk will do

**Comment by roiLeo** [comment]
![Screenshot 2023-10-13 at 15-08-27 KodaDot - NFT Market Explorer](https://github.com/kodadot/nft-gallery/assets/9987732/f8d6435b-816e-4048-a258-ac213b24d0ed)
