### ISSUE TITLE
Make stories like component for NFTs

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#720]
Amazing would be to have created component from NFTs.

I would start with feeding NFTs from creators profile, i.e. one **random** from each collection. 

Approaches could differ after time when we discover what's right there :)

- new mints by users from who you already collected something before.

![IMG_20210912_111720](https://user-images.githubusercontent.com/5887929/132982095-472f60e7-d7eb-4399-b0aa-e1001a4caaae.jpg)

**Comment by JustLuuuu** [comment]
we have latest mints in sidebar
