### ISSUE TITLE
Teleport: KSM from Statemine (ahk) to Kusama chain not working properly (Missing existencial deposit pop-up)

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7213]
## Issue
One artist (tg hannahpolza) noticed this issue and I had to try. And yes, there is an issue, teleport not working as it should. When you select max amount of KSM to teleport, your transaction will be shown as finalized, but the assets will stay on the chain. The problem is that existential deposit must be reserved.

I tried to Teleport my 0,1 KSM (max amount) from AssetHubKusama (Statemine) back to the Kusama (relay) chain.
My address: CdvMAsr7B9WxpUKRRTKpDjzz2G5F95p9F6EdcgxpBTuVmWY
After using teleport and signing the transaction, it showed me that it was "finalized." Sadly, my funds did not move anywhere and stayed on AssetHubKusama. - It is because there is an existential deposit of 0.000033333 KSM. 

Status of my funds on Polkadot.js before trying it:
<img width="688" alt="Screenshot 2023-09-08 at 15 57 10" src="https://github.com/kodadot/nft-gallery/assets/104380776/a36830fb-ea77-4661-810d-6b67f14cd63e">

## How it went:
1. I selected max amount: 
<img width="1445" alt="Screenshot 2023-09-08 at 15 54 42" src="https://github.com/kodadot/nft-gallery/assets/104380776/e51db2c7-1af0-4278-b513-52cf87e5d730">

2. After signing the transaction:
<img width="1470" alt="Screenshot 2023-09-08 at 15 55 02" src="https://github.com/kodadot/nft-gallery/assets/104380776/3acfde0f-c929-4258-bff8-367f16ea9b64">

3. Transaction was finalized.
<img width="1448" alt="Screenshot 2023-09-08 at 15 55 43" src="https://github.com/kodadot/nft-gallery/assets/104380776/c539920b-e10b-4f2a-a24c-834b57c044cb">

## My wallet after:
Even though it showed that the transaction was finalized. My funds stayed.
<img width="669" alt="Screenshot 2023-09-08 at 15 58 56" src="https://github.com/kodadot/nft-gallery/assets/104380776/aa6576b1-a9c6-4ac1-a6a6-154baaaf0d86">

## Subscan:
- https://assethub-kusama.subscan.io/account/CdvMAsr7B9WxpUKRRTKpDjzz2G5F95p9F6EdcgxpBTuVmWY?tab=xcm_transfer
<img width="1254" alt="Screenshot 2023-09-08 at 16 13 36" src="https://github.com/kodadot/nft-gallery/assets/104380776/7a027774-e6ce-4353-acbf-5564f7a06f5f">

The problem is the existential deposit - Why I didn't get notified about it? (pop-up: your transaction is higher than the existential deposit) - Transaction should not show that its finalized if its not.

**Comment by dudo50** [comment]
I already pointed out this problem in the following issue: https://github.com/kodadot/nft-gallery/issues/6601
The max amount should transfer less than the actual max because there will not be enough currency left to pay for fees on the origin chain.

**Comment by AshutoshSingh72** [comment]
😂 funny luu look at the screenshot there is comma ( , ) there should be a point .
