### ISSUE TITLE
Show user estimate for minting in seconds/minutes

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#722]
Whenever use makes interaction within the chain, it's good to tell them an approximate estimate based on previous times. Best in seconds countdown, probably also to show time when action was dispatched from the user, so we can better overview what might go wrong at which time.

Things to matter to have
- [ ] distinguish if the chain has finalization issues, i.e. there are more than n-blocks than usual, probably if diff is more than 5 
![image](https://user-images.githubusercontent.com/5887929/133046937-cd1cc8f9-9cdf-4c0b-933d-b94d89254c24.png)
- [ ] prepare component that's based on inputs tells you how much RMRK operations happens so we can reuse it for mass-minting, sending emojis, send, transfer, mass-send, i.e. nft drops i.e., minting collection based simple mint vs classic mint, whatever.

Testing would be in place to figure out the rest cases I did not write down.

This will help on UX side, whenever users have waited 5minutes+ and probably some error or disconnection from rpc happened on their side.

**Comment by JustLuuuu** [comment]
we have this - thx exez
