### ISSUE TITLE
Finish tutorial for Mass Mint

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#725]
**Is your feature request related to a problem? Please describe.**
there is a branch https://github.com/kodadot/nft-gallery/compare/main...614-mass-mint

And there is a tutorial for users

<img width="952" alt="Screenshot 2021-09-14 at 10 19 55" src="https://user-images.githubusercontent.com/22471030/133222345-9956cd35-f953-42b1-a141-8a47d954647f.png">
<img width="952" alt="Screenshot 2021-09-14 at 10 20 01" src="https://user-images.githubusercontent.com/22471030/133222367-b5d7b18e-92cc-45e0-9256-5c8aaec9eaa8.png">

**Describe the solution you'd like**
I want the tutorial to be finished

**How does the mass mint works?**
Ping me on [Discord](https://discord.gg/2qG9zK9QeX)

**Comment by JustLuuuu** [comment]
we have this
