### ISSUE TITLE
Teleport not working with Nova Wallet

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#7259]
### What happened?

trying to send funds from Kusama to Statemine not working , shows cancelled after confirming the transaction, tried multiple times same result

### Please reproduce in steps

Go to the teleport page using the nova wallet and try sending

### Expected Behavior

the transaction should go through

### At which address did you encounter bug?

canary.kodadot.xyz, kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Nova Wallet

### Screenshots

https://github.com/kodadot/nft-gallery/assets/44554284/5343ca78-2341-47cb-b773-935498dfd769

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudo50** [comment]
I will check if there is not an issue on our XCM SDK side and will get back with the result from the test shortly.

**Comment by dudo50** [comment]
Seems to work well on our end. Probably you try to send more than you can. See this issue for reference: https://github.com/kodadot/nft-gallery/issues/7213

**Comment by dudo50** [comment]
Just tested it on main net also and it works fine. 
Extrinsic id: https://assethub-kusama.subscan.io/xcm_message/kusama-9d270aa27bc44b5e1b829b322fb9ff4628cfc596
<img width="576" alt="Screenshot 2023-09-17 at 13 49 39" src="https://github.com/kodadot/nft-gallery/assets/55763425/9e7d2868-3b3d-4603-a9e0-d02b634daffa">
