### ISSUE TITLE
POAP page claim: Limit mint per wallet

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7270]
Looks like on https://poap.kodadot.art its possible to mint NFT more than once on one wallet. That is against the whole idea if POAPs. 

Please limit mint to 1 NFT per wallet. 

I accidentally minted Berlin POAP NFT twice on my wallet and now I have two poaps. 

Collection: https://kodadot.xyz/ahp/collection/10/activity

Proof that Im not the only one: 
![image](https://github.com/kodadot/nft-gallery/assets/104380776/89625952-c146-491a-8329-ebe4d12b6d65)
![image](https://github.com/kodadot/nft-gallery/assets/104380776/51b93522-f2f8-4705-b78c-d906b2e52a57)

**Comment by yangwao** [comment]
y u no sleep 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/06248ac2-ff03-4699-92b9-ff549329c896)

**Comment by vikiival** [comment]
Closing as fix needs to be done on worker side:

- https://github.com/kodadot/private-workers/issues/41
