### ISSUE TITLE
Facing some indexer problems, images not loading.

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7271]
### What happened?

Am i the only one? 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/12f557e8-1906-4c7b-885d-c915ce5e66ce)
@vikiival

**Comment by prury** [comment]
seems that it got solved by itself

**Comment by vikiival** [comment]
It was more issue of the image worker cc @preschian

**Comment by preschian** [comment]
> It was more issue of the image worker cc @preschian

I think in the screenshot above the error was "400 bad request" from stick
