### ISSUE TITLE
Use native webshare API on mobiles

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#731]
**Is your feature request related to a problem? Please describe.**
Current share menu is not so nice on mobile

**Describe the solution you'd like**
.it would be nice to use webshare api

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

https://css-tricks.com/how-to-use-the-web-share-api/

**Comment by prachi00** [comment]
@vikiival @yangwao I can pick this up
