### ISSUE TITLE
Floor button not working in mass list  

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7321]
- floor button selector does not work when clicking it for the first time, after you click the +5% etc., then it works
- 

https://github.com/kodadot/nft-gallery/assets/90852205/139b1a74-5515-41c6-99bd-79da4b93e4aa

![image](https://github.com/kodadot/nft-gallery/assets/90852205/c9dc61d1-df82-4b9c-af15-9f3f2585dda7)

**Comment by exezbcz** [comment]
still an issue 👀

**Comment by prachi00** [comment]
so what is not working? isnt floor price suppose to reset?

**Comment by exezbcz** [comment]
@prachi00 nope, it should set all the available items to collection floor
