### ISSUE TITLE
Mass list popup visible after leaving my profile 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7323]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/89e33cc5-b39c-4a93-87de-91d01513f414)
- steps to reproduce 

https://github.com/kodadot/nft-gallery/assets/90852205/cdaebe18-d09f-4599-bcc5-855331a7164a

- should be cleared and removed after leaving the profile page.

**Comment by floyd-li** [comment]
better go after this #7289
