### ISSUE TITLE
A small cosmetic change in mass minting

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7339]
I hope this is a simple request. In case someone decides to sell two and more NFTs please change: _List item_ to _List item**S**_ (plural)

I selected two items to be listed and its showing List item not items: (dramatically wrong)
<img width="1202" alt="Screenshot 2023-09-24 at 13 38 23" src="https://github.com/kodadot/nft-gallery/assets/104380776/25d1ef48-6bbc-42f1-848d-3c0eb44c4e2f">

**Comment by prury** [comment]
Thank you Lu, it got fixed in #7289

**Comment by roiLeo** [comment]
closed by #7289
