### ISSUE TITLE
Create changelog process to generate changelog automatically

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#734]
I guess to generate our update logs for the public, the best would be to handle it right away from PRs as it could be made easily and automatized like https://blog.atomist.com/keep-a-changelog/

The goal will be to use releases and generate changelog.md like those https://github.com/olivierlacan/keep-a-changelog/blob/main/CHANGELOG.md

Abhisar will take look on that:)

**Comment by abhisar2006** [comment]
Hi,

So I found two good options for us to use regarding changelogs.

1. auto-changelog : [NPM Package](https://www.npmjs.com/package/auto-changelog) or [Git Repo](https://github.com/cookpete/auto-changelog) 
This needs to be installed as a dependency and would automatically add a changelog.MD in the root with changes. The Tutorial is extensive and the repo is regularly updated.

2. Automatic Changelog generator. [GitHub Marketplace](https://github.com/marketplace/actions/automatic-changelog-generator). This is a free product in the GitHub MarketPlace. It has more options and flexibility but is directly installed on the GitHub repository and runs in the background.

I feel both of them have pros and cons and would be a good idea if it can be tested on a branch or locally first. I'll continue to look for more options but these two seem pretty positve.

**Comment by roiLeo** [comment]
[This](https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/#introducing-auto-generated-release-notes) might help.

**Comment by yangwao** [comment]
Just in time! Briefly skimming, that's looks exactly what we should have
there!

**Comment by vikiival** [comment]
First can go out I think
https://github.com/kodadot/nft-gallery/releases/tag/untagged-5bd022b71f4c3efa83c3
