### ISSUE TITLE
Identity page no longer fetching identities on Basilisk

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7362]
### What happened?

Balances load fine, but not created identity

![image](https://github.com/kodadot/nft-gallery/assets/36627808/1ad0c0fe-3be5-44c1-aa63-be14c286a5a4)

![image](https://github.com/kodadot/nft-gallery/assets/36627808/d5a1e5f7-55fc-4d70-9d48-2366d66ea320)

https://basilisk.subscan.io/tx/0x8edce8a1b55fa9ebd580e8639ec344357f5a4406edc22196804d99777aa2ea77

**Comment by newraina** [comment]
Seems like the identity feature only operates on KSM and DOT. I attempted to use it on https://canary.kodadot.xyz/identity, but couldn't switch to the BSX network. Can you give it another try on canary? Also, I observed that the UI of the identity feature is currently dissimilar to your screenshot.

**Comment by prury** [comment]
> Seems like the identity feature only operates on KSM and DOT. I attempted to use it on https://canary.kodadot.xyz/identity, but couldn't switch to the BSX network. Can you give it another try on canary? Also, I observed that the UI of the identity feature is currently dissimilar to your screenshot.

Yeah, a lot got changed in this two weeks, and i remember something about a unified identity that would only work on kusama, will check it properly in my morning, thanks for looking into that!

**Comment by prury** [comment]
yup, not it seems unified, closing
