### ISSUE TITLE
Clarify double spends on RMRK to FAQ

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#737]
We need to refer people to this in our FAQ. We need to clarify that it's out of our control how RMRK works and we are using SubQuery to have any recent state in KodaDot, latter we will recommend people using NFTs on BSX as it will have runtime logic there.

> Hey for this cases we've introduced using SubQuery, but if someone's transaction is on same block, it may happen. But that's because of nature of RMRK, has no chain-logic and we are working to support more quality NFTs on https://bsx.fi/ and latter on 📐-metaprime

@archnomics could finish this making PR to FAQ :)

**Comment by archnomics** [comment]
I've just lifted it from the technical FAQ from the Medium post.

Do I need to include SubQuery in the wording? I assume it's under the hood for the future MetaPrime network.

![image](https://user-images.githubusercontent.com/20751231/133611672-8a97c87b-95ed-4ba6-8bb9-4e14b479bf73.png)

https://kodadot.gitbook.io/knowledgebase/technical/faq

**Comment by yangwao** [comment]
SubQuery is separate from MetaPrime. Yes, you can write there we are currently relying on SubQuery which offers the most up-to-date finalized blocks if everything is working as expected.

I guess it's worth using it and putting it to our FAQ.

**Comment by yangwao** [comment]
Circling back, @archnomics let's make PR https://github.com/kodadot/nft-gallery/blob/main/src/locales/en.json

Ad - https://kodadot.gitbook.io/knowledgebase/technical/faq - how users will find it?

**Comment by archnomics** [comment]
It's included in the https://linktr.ee/kodadot for the meantime.

How can we better direct them there? Add link from the website?

**Comment by yangwao** [comment]
> How can we better direct them there? Add a link from the website?

Use our native FAQ please - https://kodadot.xyz/rmrk/faq by adding the translation to the  https://github.com/kodadot/nft-gallery/blob/main/src/locales/en.json

**Comment by yangwao** [comment]
Let's check on this @cryptodamsky

**Comment by cryptodamsky** [comment]
> Let's check on this @cryptodamsky

Will put this to **docs** and add it for the next update coming to #1962

**Comment by cryptodamsky** [comment]
Is currently running in docs:
https://docs.kodadot.xyz/FAQ.html#can-someone-double-buy-my-art

Will be part of  #1962

**Comment by cryptodamsky** [comment]
This question has been added to FAQ by PR #1962

**Comment by roiLeo** [comment]
How can double buy happen if when this https://github.com/rmrk-team/rmrk-substrate/blob/4f9f37a59aa41ff7964c2077a9f09e18141a24ca/pallets/rmrk-market/src/lib.rs#L491 and where the $ goes to?
