### ISSUE TITLE
Page slowing down firefox becoming a common ocurrency

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7374]
### What happened?

anybody else has seen a similar message on other browsers? 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/b77fd1a7-c9bc-47e2-93e6-a22697c02e35)

**Comment by yangwao** [comment]
is that happening on nuxt.kodadot.xyz too?

**Comment by prury** [comment]
First time on Nuxt today: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/f3c96083-6526-481c-8960-5e0670417e5f)

**Comment by yangwao** [comment]
I think could be some huge query?

**Comment by prury** [comment]
will reopen if stumble upon another occurrence
