### ISSUE TITLE
Some of the Polkadot Sub0 POAP NFTs are not loading properly in collection // 500 on image worker

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7397]
### What happened?

Freshly minted collection this morning - official Sub0 POAP NFTs - some of them are not loaded properly. Because its the official Polkadot NFT collection, it would be good if we could solve this asap. I noticed that epic NFTs in collection have issues the most. 

Asset Hub Polkadot.

Collection: https://kodadot.xyz/ahp/collection/13
Example NFT that is not working:  
- https://kodadot.xyz/ahp/gallery/13-957
- https://kodadot.xyz/ahp/gallery/13-731
- https://kodadot.xyz/ahp/gallery/13-565

### Please reproduce in steps

Open the [collection](https://kodadot.xyz/ahp/collection/13) and find the ones that are not loading

### Expected Behavior

load them all

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

None

### Screenshots

<img width="1439" alt="Screenshot 2023-09-28 at 11 02 15" src="https://github.com/kodadot/nft-gallery/assets/104380776/bb3c1eac-3111-4c38-9b73-f9a33203f6e7">

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
works fine for me

<img width="1395" alt="Capture d’écran 2023-09-28 à 11 09 22 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/72fd33a2-e1c7-41ed-b128-ebb6bdfaf490">

**Comment by JustLuuuu** [comment]
> works fine for me
> 

event those?
- https://kodadot.xyz/ahp/gallery/13-957
- https://kodadot.xyz/ahp/gallery/13-731
- https://kodadot.xyz/ahp/gallery/13-565

**Comment by roiLeo** [comment]
> even those?
> 
> https://kodadot.xyz/ahp/gallery/13-957

- yes

>  https://kodadot.xyz/ahp/gallery/13-731

- yes
 
>  https://kodadot.xyz/ahp/gallery/13-565

- yes


but https://kodadot.xyz/ahp/gallery/13-853 doesn't load for me

**Comment by roiLeo** [comment]
> > works fine for me
> 
> even this one? https://kodadot.xyz/ahp/gallery/13-732 

<img width="700" alt="Capture d’écran 2023-09-28 à 11 16 20 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/01419422-fbd2-447f-9220-85a439afa939">

**Comment by JustLuuuu** [comment]
weird maybe it just needs much more time to load

**Comment by yangwao** [comment]
Same here
https://kodadot.xyz/ahp/collection/13

![image](https://github.com/kodadot/nft-gallery/assets/5887929/9f869f0b-5b89-47f0-979f-885243a51ea2)

**Comment by yangwao** [comment]
cc @vikiival @preschian 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/6103bcd5-eb24-43ae-b626-b863fb18abbc)

**Comment by daiagi** [comment]
@roiLeo  try to disable cache

![image](https://github.com/kodadot/nft-gallery/assets/22791238/baf882ed-6db1-48fc-9e48-96264cc32bcb)

**Comment by roiLeo** [comment]
IMO Kodadot worker issue check image repo

**Comment by yangwao** [comment]
btw seems it works ok on Nuxt?
- https://nuxt.kodadot.xyz/ahp/collection/13

**Comment by vikiival** [comment]
> btw seems it works ok on Nuxt?

Possible because it does not DDOS the image service

**Comment by preschian** [comment]
Deployed workarounds:
- https://github.com/kodadot/workers/pull/162/files
- https://github.com/kodadot/workers/pull/163/files

Please reopen the issue if anyone still gets the error
