### ISSUE TITLE
PermaFrost landing in KodaDot

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#741]
Similar to our deck, we need to clarify to incoming users from the Arweave ecosystem what PermaFrost is and how it will function in the future. 
We also need to collect early interest to beta test usage of PermaFrost to keep the discussion rolling on both sides.
- [ ] tally form to notion
- [ ] content copy to collect it
- [ ] explain what is permafrost, similar content we've had in the deck
- [ ] Video from OWF Demo Day form Clara https://www.youtube.com/watch?v=udLWGUZ7X7M

**Comment by yangwao** [comment]
Oh we will record probably our own video 😄

**Comment by XyloDrone** [comment]
anybody on this? do we still need it on landing or can it go into other places :D
