### ISSUE TITLE
Asset Hub is down ❌

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7419]
### Tried on Canary and production:
The page is laggy, not loading, and its very slow. Only asset kub Kusama/Polkadot. Please fix it asap - Poeple are claiming official Polkadot Sub0 NFTs and we got people asking about this or complaining on twitter - this is not good. 

Go to kodadot.xyz (or canary) and open explore collections: 

## AKH
<img width="1463" alt="Screenshot 2023-09-30 at 09 47 52" src="https://github.com/kodadot/nft-gallery/assets/104380776/81957f8d-1839-4b0e-aae2-55033a95be68">

## AHP
<img width="1442" alt="Screenshot 2023-09-30 at 09 46 54" src="https://github.com/kodadot/nft-gallery/assets/104380776/2f772f01-3d32-44e1-b276-c897f7ebd407">

@kodadot/internal-dev

**Comment by AshutoshSingh72** [comment]
exactly i'm trying but not working i guess server crashed due sub 0 nft holders engagement

**Comment by AshutoshSingh72** [comment]
i was thinking it's my internet issue

**Comment by AshutoshSingh72** [comment]
may i try to fix i'm watching people complaining about kodadot bug

**Comment by AshutoshSingh72** [comment]
https://x.com/ThomasR_SupDup/status/1707875966876373274?s=20

**Comment by JustLuuuu** [comment]
> may i try to fix i'm watching people complaining about kodadot bug

I'm not a dev, so idk where is the the problem. if you know how to fix it, fix it, but we need a quick fix.

**Comment by AshutoshSingh72** [comment]
> > may i try to fix i'm watching people complaining about kodadot bug
> 
> I'm not a dev, so idk where is the the problem. if you know how to fix it, fix it, but we need a quick fix.

i'll try my best luu

**Comment by vikiival** [comment]
> AKH

It's issue of the Image GW cc @preschian 

> AHP

It's issue from the indexer as it cannot handle that big query :)
- https://github.com/kodadot/stick/pull/106

In the release currently
