### ISSUE TITLE
Passion feed

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#744]
Show only feed from already collected artists to collector by address its account is logged in.

- [ ] add it switch to the main gallery view to switch to passion feed. Switch between ALL <> PASSION
- [ ] query 
   1. where a collector is a current owner but not the issuer
   2. all nft where issuer is in array from list 1

To see in the tables only those from who you already collected, add it to 
- [ ] spotlight, 
- [ ] series-insights

MetaPassion feed -- discovery
- [ ] you can follow someone else passion feed

**Comment by Kutko0** [comment]
@yangwao I can take on this one

**Comment by vikiival** [comment]
@Kutko0 how is it going ?

**Comment by yangwao** [comment]
Updated so we can have switch on top of 
- [ ] spotlight
- [ ] series-insight
to show only related artists/collectibles to collectors

**Comment by yangwao** [comment]
Continue to 
- #2222 
- #2223

**Comment by XyloDrone** [comment]
MetaPassion feed -- discovery

you can follow someone else passion feed

---

would it be worth asking users if they wish to make their passion feed public? I have a feeling that not everyone would like to make this available for everyone to see...

**Comment by vikiival** [comment]
> would it be worth asking users if they wish to make their passion feed public

that means we would have to use some storage to save this info

**Comment by XyloDrone** [comment]
Hmm, is this an issue or is it troublesome? Because I'm thinking some people wouldn't like their feeds public. For an eg. imagine someone's twitter feed was public, I don't think everyone wants that out there. :D Might be a bit nicer to give people the option to choose if it is possible :D
