### ISSUE TITLE
Simplify queries on view pages

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#7464]
### What happened?

`metadata` on view pages are fetched over and over again from the GW recreating O(n^2) complexity (in simple words each image waits for metadata to be fetched). All these data should be either cached on client as we had on IndexedDB - https://github.com/kodadot/nft-gallery/issues/3338
or simplify queries on KodaDot - `images` and `media` are always present in the data.

### Please reproduce in steps

1. Go to https://kodadot.xyz/ahp/explore/items?listed=true

2. Open developer tools > network > fetch/xhr

See that tons of metadata are loaded

### Expected Behavior

Use `image` `media` field from subsquid 

### Are you logged in?

None

### Screenshots

<img width="647" alt="Screenshot 2023-10-02 at 13 36 00" src="https://github.com/kodadot/nft-gallery/assets/22471030/d4c71474-99c3-4513-854d-f0c5322af132">

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
> `All these data should be either cached on client as we had on IndexedDB - #3338 

if we can do without it would be great

> or simplify queries on KodaDot - `images` and `media` are always present in the data.

Yes!
