### ISSUE TITLE
Thumbnail image on collection site not correct display

### ISSUE THREAD

**Issue by jkdizajn** [kodadot/nft-gallery#747]
Hlásim chybu , pri obrázkoch ktoré nie sú 1:1, zobrazuje náhľadový obrázok cez názov kolekcii

translate: 
I'm reporting a bug , for images that are not 1:1, it displays a thumbnail image over the collection name

Link to collection: 
https://nft.kodadot.xyz/rmrk/collection/900D19DC7D3C444E4C-KSMG22

![obrázok](https://user-images.githubusercontent.com/81104034/133884962-ae580ecf-1791-4dd1-9341-f523473f1d98.png)

**Comment by vikiival** [comment]
Thanks for the report @jkdizajn. 😌
