### ISSUE TITLE
Followup: Profile tabs item count

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7472]
### What happened?

To do: 

> so, instead of adding to the existing query, maybe create a new query?
so that both the existing and the new could be called in parallel, hopefully reducing load time

https://github.com/kodadot/nft-gallery/pull/7318#issuecomment-1742044843 by @daiagi 

- Ahk count still wrong
https://deploy-preview-7318--koda-canary.netlify.app/ahk/u/FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9?tab=owned&buy_now=false

@hassnian lmk if there is anything else to add

**Comment by hassnian** [comment]
nope , maybe just  add a goes after  #7318

**Comment by hassnian** [comment]
actually I think we can close this one,  we already have #7437

**Comment by prury** [comment]
> actually I think we can close this one, we already have #7437

my bad, did not saw this one, closing!
