### ISSUE TITLE
Permafrost has 10MB file limit

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#750]
We need to clarify that using permafrost user is limited to 10 MB

**Comment by abhisar2006** [comment]
We can add it to the FAQs and in "*" note on the upload space.

**Comment by yangwao** [comment]
> We can add it to the FAQs and in "*" note on the upload space.

Translation file is here https://github.com/kodadot/nft-gallery/blob/main/src/locales/en.json
Make PR

Propose changes in visual way if so
