### ISSUE TITLE
Better skeleton for Drops

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#7515]
**current**
<img width="1022" alt="Capture d’écran 2023-10-05 à 11 20 07 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/f089ea5f-c268-4c3a-8ae4-5077e2c4bc9a">

**vs**
<img width="1022" alt="Capture d’écran 2023-10-05 à 11 20 41 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/2f3aa6b4-83f3-4926-8961-4846a65a9365">

**Comment by exezbcz** [comment]
This would be nice
