### ISSUE TITLE
Make unified button for sharing and linking

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#752]
Let's deliver same style to the sharing button as we have already on other buttons, with clean rectangle borders

Needs replacement on 
- profile https://nft.kodadot.xyz/rmrk/u/EJMCExEPNyuq6EofbvwD2ErZKwuZCJVTFhiDcDwuW12c187
- collection https://nft.kodadot.xyz/rmrk/collection/4c4a2f66cde689450b-CHGL100
Right now 
![image](https://user-images.githubusercontent.com/5887929/133973476-7cfc6452-3f26-4909-b9b2-b6e112ab8e6c.png)

The desired look for button, recycle one from actions?
![image](https://user-images.githubusercontent.com/5887929/133973679-873a221a-5f54-4064-854d-cf00b09f8b29.png)

**Comment by prachi00** [comment]
@yangwao I'll pick this up

**Comment by yangwao** [comment]
@prachi00 I've assigned you!:)
