### ISSUE TITLE
Update production keys on Ramp Network

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7523]
> I would merge it and then will update keys to production ones on `nuxt` 
I believe we will migrate sooner to `nuxt` than Ramp will get back to me.

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/6727#issuecomment-1748910720_

**Comment by prury** [comment]
Localhost: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/d84d221b-07ab-4fcd-8210-3f819f00919b)

**Comment by yangwao** [comment]
done, still waiting to approve prod key from them
