### ISSUE TITLE
Having beta channel / contextual deployments for KodaDot

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#754]
Think about how we can achieve have a beta channel where we can test some new features and have them battle-tested till they hit mainstream exposure.

Thinking aloud about the switch button which by **default is off** and once enabled, we can start enabling features.

- having json, where you can enable/disable accessibility for new features for mainstream users
- probably will be always on for beta?
- having a survey, where can collect feedback probably, feedback channel on discord, is good but it could be messy, probably direct people straight to the github, but non-tech savvy having some tally form?
- have a beta-testers audience
- have proper way to have great and rich reports about bugs, critical

First feature we can start testing out with #753

**Comment by vikiival** [comment]
Can we set some specific ENV variables per branch?

**Comment by yangwao** [comment]
Apparently there is context env https://stackoverflow.com/questions/49720743/branch-specific-environment-variables-on-netlify
ref 
- https://docs.netlify.com/configure-builds/environment-variables/
- https://www.netlify.com/blog/2020/05/21/localize-your-environment-variables-by-context-with-build-plugins/
- https://docs.netlify.com/site-deploys/overview/#deploy-contexts

recall plugin which can set env based on branch prefix i.e.
in theory it might works 😄

**Comment by vikiival** [comment]
<img src="https://http.cat/202">

**Comment by yangwao** [comment]
Installed https://github.com/cball/netlify-plugin-contextual-env#readme

**Comment by rhaicode** [comment]
Regarding feature toggling, you might want to check launchdarkly

**Comment by yangwao** [comment]
Memo, we have https://beta.kodadot.xyz meanwhile
