### ISSUE TITLE
Get extrinsic's hash when callback is passed

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#755]
Whenever has exec callback it is not possible to get transaction's hash

```ts
const hash = statusCb ? await transfer.signAndSend(alicePair, statusCb) : await transfer.signAndSend(alicePair);
return typeof hash === 'function' ? hash : hash.toHex();
```

what I think is that `transfer.signAndSend(alicePair) === transfer.hash`
but I need to investigate.

This is important for @prachi00's transfer function

**Comment by yangwao** [comment]
Let's fast track it 👀
