### ISSUE TITLE
Profile item count not working? 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7550]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/1b3971b2-d298-477f-a86f-2fd44b3a69e7)
https://canary.kodadot.xyz/ksm/u/GnMcJyFCwB1E8hTwfatmXatdJ2n4ZD3Hx8znJUDJhkKVuLW?tab=owned

- https://github.com/kodadot/nft-gallery/pull/7493

**Comment by exezbcz** [comment]
ah its for the nuxt version only, ic, my bad 


would it be possible to apply it to the normal deployment?

**Comment by roiLeo** [comment]
> ah its for the nuxt version only, ic, my bad

I heard that we'll be releasing new version in the upcomming week.

> would it be possible to apply it to the normal deployment?

only major bug fix or critical bug, I think we can do without this feature.
