### ISSUE TITLE
Show html media in full size in gallery item - responsivity issue

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#7556]
### What happened?

Currently both `canary` and #7524 show just a 'portion' of the html media. 
Therefore user need to scroll to see 'other' parts 

### Please reproduce in steps

1. Open https://canary.kodadot.xyz/snek/gallery/3919361082-3
2. See that just a bit of html media is visible
3. scroll in the image to see others

### Expected Behavior

1. I want to see a full view of the media by default

### Screenshots

<img width="1012" alt="273550115-fe63f4d4-67b6-4617-8f94-1e9ccb2aa5a1" src="https://github.com/kodadot/nft-gallery/assets/22471030/b3b64bb3-501f-4edb-a961-345c7b7aa8b3">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
What's wrong?
I see it normally here
- https://github.com/kodadot/nft-gallery/pull/7524

https://deploy-preview-7524--nuxt-kodadot.netlify.app/snek/gallery/3919361082-3

![image](https://github.com/kodadot/nft-gallery/assets/5887929/fd40ed1e-6f77-43c6-b89d-ff4e3e088769)

**Comment by vikiival** [comment]
https://github.com/kodadot/nft-gallery/assets/22471030/b8fbdaf8-4d31-4b03-a4bf-e5c9bc0adf52

**Comment by Allan2000-Git** [comment]
check for overflow:hidden and make the parent width:100%

**Comment by Jarsen136** [comment]
> check for overflow:hidden and make the parent width:100%

Would you like to take a try and raise a PR for this fix?

**Comment by vikiival** [comment]
https://github.com/kodadot/nft-gallery/assets/22471030/6c6028df-c85d-4bab-964a-a9ac73f2e263

**Comment by roiLeo** [comment]
fixed somewhere
