### ISSUE TITLE
Migration UI - 2 - Review

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7561]
part of a bigger issue:
- #7552 

# Review
- you will get there by clicking any button with label "migrate...." on the cards 
- the UI divides here to migration of the mentioned collection or only the items inside. 

## Migrate collection
<img width="437" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/be07efe1-f1a4-44c1-b059-e6f2c9406077">

- top part review - sign (same as in the admin panel) 
- contextual message ( connected with)
- then there is migrate collection 
- there is picture of the collection, name and message that the name will stay the same.
- divider, and now for the harder part. 
- there is row that shows "items available for migration" 
- little message: 
   - >Please note that at this stage, only items you own can be migrated. For other items, you will need to pre-sign them to allow others to follow your migration initiative.
- If I understand correctly, you cannot migrate items you don't own. Therefore, you pre-sign for others and give them access to follow your migration once they decide to do so. 
- is that correct @vikiival ? 
- then there is route explained
<img width="565" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/c6c767c4-b462-4edc-a913-9a60a5b0bbf1">

- divider and then costs, those are also similar to the #7241 
- collapsable fee breakdown, divided into network fee and then existential deposit, and then kodadot fee (if there will be any..) 
- then a row of estimated total fees. 

### bottom part 
- here is acknowledgment before you proceed, its irreversible and you should know it. 
- disabled button till you don't check the checkbox 

## Migrate items
<img width="599" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/d908736e-8f00-4378-865f-b92ee61fd20d">
- missing available items and the info part. 
- only 2 items max are shown and then there is text of how many items are left. 
- >+ 10 more items from the same collection

**Comment by yangwao** [comment]
hey @kodadot/internal-dev if someone would pick this up, please?
It should be non-blocking, till @vikiival delivers script.

**Comment by vikiival** [comment]
@exezbcz in this screen we should check user's balance

**Comment by yangwao** [comment]
@exezbcz is there a step where we are checking if the user has enough funds on that destination chain? 
I failed to find on designs

**Comment by preschian** [comment]
im still on it this one, until congrats page

**Comment by exezbcz** [comment]
@yangwao Since this is similar to the modal, the button behaves the same way when the user has no funds. This means the disabled button displays: Insufficient "asset" on "network". The state is revealed after checking the checkbox. 

One improvement is adding network labels to all costs in the breakdown and differentiating between networks for the total. Will edit the issue soon.

**Comment by exezbcz** [comment]
# Updates 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/367f8175-4add-4b45-9b8c-da57eda31a8b)

- updated under the previous version

## Changes list
- overview collection different copy tooltip
![image](https://github.com/kodadot/nft-gallery/assets/90852205/eacbbc39-e7b9-4f94-9a6d-b637be7c2c8e)


- better fee breakdown - divided into networks 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/9b301365-ba95-46c8-8b7d-13e3872a3c9a)

- make the breakdown collapsed by default, please

**Comment by vikiival** [comment]
@exezbcz one thing to be clear:

Shouldn't be this: `Paid on AssetHub (Polkadot)`?

![Screenshot 2023-10-23 at 13 14 39](https://github.com/kodadot/nft-gallery/assets/22471030/87ace592-0630-4d6c-a47d-a7769b8a9e04)

**Comment by exezbcz** [comment]
> @exezbcz one thing to be clear:
> 
> Shouldn't be this: `Paid on AssetHub (Polkadot)`?
> 
> ![Screenshot 2023-10-23 at 13 14 39](https://github.com/kodadot/nft-gallery/assets/22471030/87ace592-0630-4d6c-a47d-a7769b8a9e04)
> 

Correct, will edit
