### ISSUE TITLE
select all mass list not working

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7566]
https://github.com/kodadot/nft-gallery/assets/90852205/d33b1f6b-4c3d-4622-bd6d-6cc8c59b74e9

- should select all non-listed items visible on the page (it shouldn't ignore filters etc.)

**Comment by hassnian** [comment]
it's working , tested it https://nuxt.kodadot.xyz/,  seems to not work https://canary.kodadot.xyz/ 

https://github.com/kodadot/nft-gallery/assets/44554284/730224fa-eff5-456e-874a-e32097629ece

**Comment by exezbcz** [comment]
> [canary.kodadot.xyz](https://canary.kodadot.xyz/) seems to not wor

yeah, its okay, The nuxt version will be soon on main.
