### ISSUE TITLE
Statemine integration into KodaDot placeholder

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#757]
Let's briefly draft what's going on work on Statemine

**Branch**: https://github.com/kodadot/nft-gallery/compare/main-nuxt..statemine-nuxt
**SubQuery**: https://github.com/vikiival/unique

Deliverables: (According to the proposal)
- [x]  Make a page dedicated to creating a unique (NFT) with a simple workflow
- [x]  Ability to create a Class (collection)
- [ ]  Show class detail with metadata
    - [x]  Collection
    - [ ]  Metadata?
- [x]  Show minted NFTs in explorer mode
- [ ]  Ability to set and remove approval for instances
    - [ ]  Set
    - [ ]  Remove
- [ ]  Display metadata for particular NFT (instance)
- [ ]  Transfer (send) ownership for class and instance
    - [ ]  Class
    - [x]  Instance
- [ ]  Set metadata for class and instance
    - [ ]  Class
    - [ ]  Instance
- [ ]  Set attributes for class and instance
    - [ ]  Class
    - [ ]  Instance
    - [x]  Component
- [x]  Burn an instance
    - [x]  Remove instance from Graphql
- [ ]  Clear metadata and attributes.
    - [ ]  Metadata
    - [ ]  Attributes
- [ ]  Implement a page to teleport KSM between Kusama and Statemine
- [ ]  Extend [vue-polkadot/api](https://github.com/vue-polkadot/vue-ui/tree/master/packages/vue-api) to handle multiple (parallel connections).
- [ ]  Provide check if a user has enough balance on Statemine / Kusama to be able to mint and transfer a collection.
- [ ]  Implement a GraphQL schema for Classes and instances
- [ ]  Extend the embeddable component that will work with the Statemine implementation (note: embeddable component -> **<iframe/>** which would work as a page generator to show particular collections or by addresses on other existing web applications )
- [ ]  Write introduction article around experience with development around unique pallet implementation

**Comment by vikiival** [comment]
Copied state from internal Notion

**Comment by vikiival** [comment]
Closing in favour of #1536
