### ISSUE TITLE
Change tab order on creators profile 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#758]
# Right now we have an order
- Created
- Collected
- Sold
- Collections

# Let's change it to
- Created - probably you want to be first impressed by unorganized creators stuff
- Collection - you want to get **filtered** output 
- Sold - which we're actually sold
- Collected - not sure if this is quite important unless you are a collector 

So literally just swap Collected <> Collection
![image](https://user-images.githubusercontent.com/5887929/134144422-59183076-c2f9-4f2e-99da-3a7c79f1ae25.png)

**Comment by PuneetDabral** [comment]
sir can i do my contribution here i am new in open source as  well in github all i need is your supoort

**Comment by vikiival** [comment]
@PuneetDabral looks like @prachi00 already made a pull request, but there are also [many tasks which are beginner friendly](https://github.com/kodadot/nft-gallery/labels/good%20first%20issue)

Also do not forget to [join our Discord](https://discord.gg/kBYM3K8e) so we can help you.

**Comment by PuneetDabral** [comment]
ok sir i was already join your discord community .....
