### ISSUE TITLE
nuxt3 seo isues and og-image cards 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7587]
I've noticed there might be some dragons and I would like to see use of other og generation tools as we can be more flexible on that? if I get it right

- https://github.com/GrabarzUndPartner/nuxt-speedkit/issues/542
- #5031 
- https://github.com/kodadot/nft-gallery/issues/5426
- https://github.com/kodadot/nft-gallery/issues/5426#issuecomment-1691577851
- #7997 
- https://nuxt.com/modules?category=SEO

done
-
- ~~https://github.com/harlan-zw/nuxt-og-image/releases/tag/v2.0.0~~
- ~~https://github.com/harlan-zw/nuxt-og-image/tree/main~~

**Comment by roiLeo** [comment]
- link https://github.com/kodadot/nft-gallery/pull/7575#issuecomment-1754798859

**Comment by yangwao** [comment]
Meanwhile, the sad dolphin at bay 
- https://canary.kodadot.xyz/ahp/gallery/13-1164
- https://www.opengraph.xyz/url/https%3A%2F%2Fcanary.kodadot.xyz%2Fahp%2Fgallery%2F13-1164
![image](https://github.com/kodadot/nft-gallery/assets/5887929/fedd87bf-9125-4d6e-b302-dccbed040bef)

**Comment by roiLeo** [comment]
Some progress

<img width="491" alt="Capture d’écran 2023-10-10 à 5 13 28 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/1ce54e3b-237e-41c0-bfa3-97f554d49938">

- ref kodadot/workers#171

**Comment by roiLeo** [comment]
From my recent finding, I think it will be fixed once released since opengraph (ssr-opengraph worker) only check `*.kodadot.xyz` & `kodadot.xyz` (not `*--nuxt-kodadot.netlify.app`)

**Comment by roiLeo** [comment]
Oops

![Screenshot 2023-10-10 at 18-48-13 504 GATEWAY_TIMEOUT](https://github.com/kodadot/nft-gallery/assets/9987732/797b8da0-44e7-44ef-8f12-7bb5b5dc43c7)

**Comment by roiLeo** [comment]
Tried to setup `og-image` package, it doesn't work without `ssr` support

**Comment by yangwao** [comment]
Worth inspecting this one? 
- https://github.com/harlan-zw/nuxt-seo-kit

**Comment by yangwao** [comment]
> it doesn't work without `ssr` support

apparently you don't need SSR if it is possible to use it with Cloudflare workers ?

**Comment by preschian** [comment]
> > it doesn't work without `ssr` support
> 
> apparently you don't need SSR if it is possible to use it with Cloudflare workers ?

probably this one looks feasible, let me check

at least let replace `AndreyGrin/og-image` first

**Comment by yangwao** [comment]
Some of issues have been resolved by
- https://github.com/kodadot/workers/pull/194
![image](https://github.com/kodadot/nft-gallery/assets/5887929/67f2c80c-172a-494e-ba97-f11ac3f27209)
