### ISSUE TITLE
Mass list of stacked items

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7599]
I was thinking about listing one of the NFts I have twice. I realized that mass listing automatically selects both of the NFTs. In the next step, Im able to remove it one, but still not sure if mass listing of stacked NFTs should work this way. Maybe have an option after clicking to select if you want to list the whole stack or just one NFT?

<img width="905" alt="Screenshot 2023-10-10 at 21 55 03" src="https://github.com/kodadot/nft-gallery/assets/104380776/d0166739-b6f9-48d3-bbe4-cddb79dff230">

idk just wanted to raise awareness.

**Comment by daiagi** [comment]
as it is implemented in #7641
it will add to the cart all of the NFTs that are not listed

if I remember correctly from some comment by @exezbcz , this was considered a feature

to choose just 1 does raise the question of which one, but I guess it doesn't matter much since they are the same

**Comment by exezbcz** [comment]
> if I remember correctly from some comment by @exezbcz , this was considered a feature

I don't exactly remember what I said, but It still makes sense to me. Tried to find the comment but did not manage to. 

> Maybe have an option after clicking to select if you want to list the whole stack or just one NFT?

too complicated imo


> to choose just 1 does raise the question of which one, but I guess it doesn't matter much since they are the same

correct, if you want to list only one, you can do it from the item detail. 


I will keep this open, with iterated mass select and list it will be clearer.

**Comment by exezbcz** [comment]
done in 
- https://github.com/kodadot/nft-gallery/issues/9183
