### ISSUE TITLE
Add mailto to email contact on user profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#760]
Right now you copy it clipboard, which might be okayish if you want to pass it to someone.
Taking it from here, let's add there ```mailto:``` with all perks.

Let's add this 
```
mailto:creator?subject=I%20like%20your%20Creation%20on%20KodaDot&body=Hey%2C%20I've%20found%20your%20creation%20on%20KodaDot%20interesting.%0D%0ACan%20you%20please%20tell%20me%20more%20about%20it%3F
```

ref 
- https://css-tricks.com/snippets/html/mailto-links/
- https://mailtolink.me/
- 
![image](https://user-images.githubusercontent.com/5887929/134145107-5ca33f4a-ac49-4e4a-b255-b568d42bce34.png)

**Comment by prachi00** [comment]
I'll do this @yangwao
