### ISSUE TITLE
Empty previews on social networks

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7608]
https://canary.kodadot.xyz/ksm/gallery/18630137-B9F14D738824A41D42-TOKUNFT-TOKUNFT_347-00000347

https://www.opengraph.xyz/url/https%3A%2F%2Fcanary.kodadot.xyz%2Fksm%2Fgallery%2F18630137-B9F14D738824A41D42-TOKUNFT-TOKUNFT_347-00000347
![image](https://github.com/kodadot/nft-gallery/assets/5887929/6996e98f-499b-49f7-9111-e18e81851238)

**Comment by yangwao** [comment]
loaded after time huh

![image](https://github.com/kodadot/nft-gallery/assets/5887929/8fae9973-786b-42db-b093-d88815c4fe0c)

**Comment by roiLeo** [comment]
Gallery preview are worker issue, you need to trigger robot cache to be able to see updated image

[here](https://developers.facebook.com/tools/debug/) is a tool that can be usefull
