### ISSUE TITLE
Claim Physical drop button

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7613]
### What happened?

There used to be a Claim Physical drop inside NFTs minted by the drops page, where is it? got disabled? 

![image](https://github.com/kodadot/nft-gallery/assets/36627808/db6a35d0-c909-48b6-b598-3b10503bb577)

### At which address did you encounter bug?

canary.kodadot.xyz, beta.kodadot.xyz, kodadot.xyz

**Comment by prury** [comment]
@yangwao was it disabled on purpose?

**Comment by vikiival** [comment]
Probably nuxt migration?

**Comment by roiLeo** [comment]
> Probably nuxt migration?

keywise worker said no

**Comment by roiLeo** [comment]
maybe issue with collection name (`ahp-u-8`?)

![Capture d’écran 2023-10-12 à 3 46 24 PM](https://github.com/kodadot/nft-gallery/assets/9987732/a21882be-7453-4a59-8cde-52137864b038)

**Comment by vikiival** [comment]
Updated

**Comment by prury** [comment]
> Updated

![image](https://github.com/kodadot/nft-gallery/assets/36627808/6715792a-cde4-4139-bcd8-8287b1868c25)

**Comment by prury** [comment]
Free drop still won't show it tho

**Comment by vikiival** [comment]
> Free drop still won't show it tho

What is the collection url?

**Comment by prury** [comment]
> > Free drop still won't show it tho
> 
> What is the collection url?

https://canary.kodadot.xyz/ahp/collection/6

**Comment by vikiival** [comment]
updated ^-^

**Comment by prury** [comment]
working!
