### ISSUE TITLE
DOT Drop not identifying previously minted NFT

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7614]
### What happened?

go to -> https://canary.kodadot.xyz/ahp/drops/dot-drop

last one minted was me: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/7240ceb0-1b27-45f0-95e9-7d082e6b36fe)

but when i enter the page, it lets me mint me again:

![image](https://github.com/kodadot/nft-gallery/assets/36627808/815d3077-009a-4f2f-9cd8-517720b4fd44)

it is supposed to be like that for the DOT drop?

**Comment by Jarsen136** [comment]
> it is supposed to be like that for the DOT drop?

I'm not sure if it's allowed to mint items multiple times for dot dorp. Do you have any idea? @vikiival

**Comment by vikiival** [comment]
Honestly, i dont know
But anything you can buy is possible to buy. Free drops are allowed as one per address

**Comment by Jarsen136** [comment]
> Honestly, i dont know But anything you can buy is possible to buy. Free drops are allowed as one per address

Thank you for your answer. I guess we could close this issue then.
