### ISSUE TITLE
Integrate SubSquid to avoid our current SPOF

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#762]
In heat of #761 #759 
I'm up to integrate SubSquid. This will avoid the upcoming wreckage of KodaDot as SubQuery is a **single point of failure** and there is a weak mitigation strategy from their side to cover our ass in that case. Seems SubQuery is understaffed on this.

They've said 
> will check it tomorrow.
> I will have a look once available

Which is unbearable and brings us to a complete halt of our services. In retrospect, is not the first time we have [unhealthy state of indexer](https://explorer.subquery.network/subquery/vikiival/magick)

**Comment by vikiival** [comment]
@unknow112 would you like to pick it up? 

<img width="218" alt="Screenshot 2021-11-26 at 11 29 43" src="https://user-images.githubusercontent.com/22471030/143566733-08a635cd-a735-4c66-b65a-cd81f0060f2c.png">

**Comment by yangwao** [comment]
meanwhile using subsquid already
