### ISSUE TITLE
Opening link on my phone loads wrong logo in dark mode

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7629]
Opening any kodadot link on my phone opens kodadot page with dark mode but with logo for the light mode:

![image](https://github.com/kodadot/nft-gallery/assets/104380776/1ea8ae1c-5b56-48e3-9e60-e16f19d4662c)

production, mobile

**Comment by exezbcz** [comment]
should be fixed by: 
- #7618 

once there is release, it will be fixed on production as well, let me know if it works for you on canary
