### ISSUE TITLE
Infinite scroll loading items without skeletons or borders, leaving gaps

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7642]
### What happened?

Observe: 

https://github.com/kodadot/nft-gallery/assets/36627808/db5f0290-d8b2-4b35-8fa2-6102d6dc326a

### Please reproduce in steps

Explore items -> scroll down fast

### Expected Behavior

Should load in a organized way and gaps should not be present

**Comment by preschian** [comment]
> Explore items -> scroll down fast

No need to scroll down fast I guess. If I visit this collection, there are gaps also https://kodadot.xyz/ahk/collection/101

![image](https://github.com/kodadot/nft-gallery/assets/734428/23d18603-c125-4e25-a470-542f205741e0)
