### ISSUE TITLE
stacked cards styling 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7652]
after: 
- #7641 

Design: 
<img width="494" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/26de799b-1935-42ed-b758-2a3349c0f39e">

In the current version, there is one more stroke: 
<img width="446" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/80768e68-d925-4164-8457-49cef8e05dde">
+ The shadow and stroke drop shadow have different grey colors. Please have a look in the figma - https://www.figma.com/file/OwAEyE0QDPn3tHXZbyot1o/Explore-v0.9?type=design&node-id=0%3A1&mode=design&t=tCSZE6FYkEXqV85Z-1

**Comment by daiagi** [comment]
>In the current version, there is one more stroke:

@exezbcz some artworks have black/white/transperent background
in this cases, removing that stroke looks weird


### without
![image](https://github.com/kodadot/nft-gallery/assets/22791238/436169f6-59e6-41f9-8cca-67ab83818f23)


### with
![image](https://github.com/kodadot/nft-gallery/assets/22791238/4e49cb7d-bea2-47c7-a259-3a814cccb275)
