### ISSUE TITLE
Ability to send various amounts in transfer

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7677]
Currently on transfer I can't send to two various address two different amounts
- https://canary.kodadot.xyz/dot/transfer?usdamount=442

The best would be to extend ability w/o harming the current batch format URL 

https://github.com/kodadot/nft-gallery/assets/5887929/625e0dc2-947b-4f97-8e01-fa9b77f9ada5

**Comment by Jarsen136** [comment]
Does it solve your problem? Turn off `Send same amount` switch button. @yangwao 

<img width="811" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/fb5307d2-3f6d-429b-a356-e9f221b7afc6">

**Comment by yangwao** [comment]
> Does it solve your problem?

lol ok, did not notice it as it's completely white lol 

https://github.com/kodadot/nft-gallery/assets/5887929/7eaa1a2a-5e78-47a8-b57f-8db150acdaea
