### ISSUE TITLE
Seems blog articles are not in sitemap?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7681]
https://kodadot.xyz/0-sitemap.xml

![image](https://github.com/kodadot/nft-gallery/assets/5887929/f104f7dc-fa2c-4bec-91f3-465209cb402a)

**Comment by roiLeo** [comment]
`// TODO: uncomment code`

https://github.com/kodadot/nft-gallery/blob/9d2eb81dca4651a3aeaf2abc1302eeaa867bc5ea/nuxt.config.js#L276-L285

**Comment by yangwao** [comment]
> // TODO: uncomment code

do it

<img src="https://media4.giphy.com/media/wi8Ez1mwRcKGI/giphy.gif"/>
