### ISSUE TITLE
Spotlighted, Newest list and newest sale are not appearing all the time

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7688]
This happened to me a few times today (randomly). When I opened kodadot in a new tab or clicked on Koda logo to return to the main landing page: **it did not load spotlighted, newest list and latest sale.** - check the video

Not sure why is this happening, sometimes it worked and sometimes not. Only noticed it on ahp, production. 

https://github.com/kodadot/nft-gallery/assets/104380776/84451948-e322-4cc1-823b-2e217f103f8d

**Comment by prury** [comment]
@JustLuuuu on /dot these pages are disabled on purpose, and i believe we even disabled dot from the chain list, maybe your bookmark address still points to it?

**Comment by roiLeo** [comment]
Closing as not planned, `DOT` chain is just for the transfer page
