### ISSUE TITLE
Hide generative drop from the deployments

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#7737]
### What happened?

Since gen art is not implemented, some people are asking why is it on prod

![IMG_7102](https://github.com/kodadot/nft-gallery/assets/22471030/09060100-80c8-4fdc-bf50-5c30075832ae)

### Please reproduce in steps

1. Go to drops
2. Open chained
3. See nothing

### Expected Behavior

Genart should be hiden on *.kodadot.xyz deployments
(Prod, canary, beta)

### Are you logged in?

None

### Screenshots

_

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
still need to hide it?
