### ISSUE TITLE
Can't load Referendum drop  - wrong metadata

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7739]
It looks like wrong parsing URL as there is `ipfs://` in cf ipfs URL 

https://canary.kodadot.xyz/ahk/gallery/180-3691204538

```
Access to fetch at 'https://cloudflare-ipfs.com/ipfs/ipfs://ipfs/QmbM7cNWybBCCxyzUBQxhJ25qJ4Ecv7fGDgbFtFnhaSvaT' (redirected from 'https://image-beta.w.kodadot.xyz/ipfs/ipfs://ipfs/QmbM7cNWybBCCxyzUBQxhJ25qJ4Ecv7fGDgbFtFnhaSvaT') from origin 'https://canary.kodadot.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CO
```

Seems their metadata has wrong format? 

`"image": "ipfs://ipfs/ipfs://ipfs/QmbM7cNWybBCCxyzUBQxhJ25qJ4Ecv7fGDgbFtFnhaSvaT",`

`"mediaUri": "ipfs://ipfs/ipfs://ipfs/QmbM7cNWybBCCxyzUBQxhJ25qJ4Ecv7fGDgbFtFnhaSvaT",`

https://image-beta.w.kodadot.xyz/ipfs/bafkreidpi55n4lhjsn45eg6jopsiwptenyqarl7pyfg2xa52erpt4qhvwe

**Comment by yangwao** [comment]
Probably we should not show collections with broken metadata, maybe validator of metadata of collection we index?

**Comment by roiLeo** [comment]
![Screenshot 2023-12-15 at 10-40-48 deef - Something is Brewing - common #3691204538](https://github.com/kodadot/nft-gallery/assets/9987732/31799a3a-6393-4a10-bdae-7833454b6cdb)
