### ISSUE TITLE
New logo on social preview?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7750]
v4 logo on previews would be good
mind also that twitter put text where it s well

mobile
---
![Screenshot_20231020_105921_X.jpg](https://github.com/kodadot/nft-gallery/assets/5887929/cdf449b7-705e-4d94-b8ab-e84eddeffaad)

desktop
---
![image](https://github.com/kodadot/nft-gallery/assets/5887929/ddef69e7-3b08-4f9a-bfb7-2fb07b586229)

ref
---
- #5426
- #6942

**Comment by roiLeo** [comment]
closed in kodadot/workers#194
