### ISSUE TITLE
Nuxt 3.8 upgrade broke Cloudflare deploy?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7754]
CF builds broke since Nuxt@3.8
cc @roiLeo 

- https://github.com/kodadot/nft-gallery/commit/1e77b91cd0c91fe232f740b4d7fe1d96aafe842f
- #7749 
- https://github.com/kodadot/nft-gallery/pull/7755

```
14:42:09.790 | Finished
-- | --
14:42:09.790 | Found _worker.js in output directory. Uploading.
14:42:11.170 | ✨ Compiled Worker successfully
14:42:11.212 | Found _routes.json in output directory. Uploading.
14:42:11.225 | Validating asset output directory
14:42:12.223 | Deploying your site to Cloudflare's global network...
14:42:14.577 | Parsed 1 valid header rule.
14:42:16.612 | Uploading... (390/654)
14:42:17.722 | Uploading... (478/654)
14:42:17.954 | Uploading... (566/654)
14:42:18.851 | Uploading... (654/654)
14:42:18.851 | ✨ Success! Uploaded 264 files (390 already uploaded) (3.11 sec)
14:42:18.851 |  
14:42:19.917 | ✨ Upload complete!
14:42:21.318 | Uploading to dependency cache
14:42:21.326 | Skipping build output cache as it's not supported for your project
14:42:27.020 | Success: Dependencies uploaded to build cache.
14:42:28.681 | Success: Assets published!
14:42:33.033 | Error: Failed to publish your Function. Got error: Error 8000057: Overlapping rules in `_routes.json` are not allowed. Rule "/_nuxt/builds/*" is overlapped by "/_nuxt/*". Remove one of the rules to continue.
``

**Comment by yangwao** [comment]
> What's the command used in cloudflare config?

![image](https://github.com/kodadot/nft-gallery/assets/5887929/dc8e0bdc-2e28-48cf-a211-25727ed02f45)

> no error with netlify

yeah, strange.

> maybe cleare deploy cache and re deploy?

it was failing on a series of other merged PRs, so I doubt don't this one is issue

```
Error: Failed to publish your Function. Got error: Error 8000057: Overlapping rules in `_routes.json` are not allowed. Rule "/_nuxt/builds/*" is overlapped by "/_nuxt/*". Remove one of the rules to continue.
````

Isn't some new rules need to be configured?

**Comment by roiLeo** [comment]
Looks like nitro based issue https://github.com/nuxt/nuxt/issues/23796

**Comment by yangwao** [comment]
> Looks like nitro based issue [nuxt/nuxt#23796](https://github.com/nuxt/nuxt/issues/23796)

seems we are in the front rows 

<img src="https://media3.giphy.com/media/13KHP8IeczIhos/giphy.gif"/>

we can try this one 

> If you don't want to use the new experimental manifest feature, add experimental: { appManifest: false } to your defineNuxtConfig. This will make the deployment on Cloudflare work again.
