### ISSUE TITLE
Bump Polkadot packages to latest versions

### ISSUE THREAD

**Issue by dudo50** [kodadot/nft-gallery#7766]
### Is your feature request related to a problem?

As I am unsure if bumping Polkadot JS libs to the latest versions won't break the build I am suggesting it in an issue. It should resolve multiple peer dependency warnings.

### Describe the solution you would like

Bump polkadot JS libs

Alternatively, consider putting this code to package.json

```
"peerDependencyRules": {
      "allowedVersions": {
        "@polkadot/util": "12",
        "@polkadot/util-crypto": "12"
      }
```

### Describe alternatives you have considered

-

**Comment by roiLeo** [comment]
✅ completed
