### ISSUE TITLE
Use skeleton for images while loading

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#777]
**Is your feature request related to a problem? Please describe.**
Looks like users are super confused when they see the KodaDot logo as a placeholder.

**Describe the solution you'd like**
I would like to replace the current `<img />` tag with `b-image` that supports [skeleton placeholder](https://buefy.org/documentation/image/#placeholder) (example no. 3)

**Additional context**
Make sure that: 
- [ ] You won't break any magic CSS functionality

<img width="1407" alt="Screenshot 2021-09-23 at 09 12 27" src="https://user-images.githubusercontent.com/22471030/134467712-24fb2c43-b76f-451f-8c28-d4e43af333c0.png">

**Comment by roiLeo** [comment]
Isn't this already done with `BasicImage` Component?

**Comment by vikiival** [comment]
Jup!
Created in 2186c68ca6a77db4432b09ddfdead9e32b45f793
