### ISSUE TITLE
Collection view broken on mobile

### ISSUE THREAD

**Issue by poppyseedDev** [kodadot/nft-gallery#7773]
![Screenshot_20231022_172832_Firefox.jpg](https://github.com/kodadot/nft-gallery/assets/30662672/16c54199-16a2-467b-9264-b9fcf9fde68e)

**Comment by daiagi** [comment]
looking a the screenshot l understand that the broken page is /explore/collections on rmrk

I opened it on Android phone on
chrome
firefox
brave
nova wallet

so far so good

@poppyseedDev  could you provide more details on how to reproduce?

**Comment by poppyseedDev** [comment]
Firefox broser on mobile phone https://canary.kodadot.xyz/ksm/explore/collectibles
It's visible only through phone and not if you set your browser to phone.

**Comment by roiLeo** [comment]
> Firefox broser on mobile phone https://canary.kodadot.xyz/ksm/explore/collectibles It's visible only through phone and not if you set your browser to phone.

Tested on Android Firefox & Firefox focus but can't reproduce your bug, maybe try to clear your phone browser cache
