### ISSUE TITLE
Choose first account from accounts by default

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#778]
When I open up an app, it asks me permission to read my accounts but will not choose an address in the login field

expected behaviour would be to select first address by default

**Comment by prachi00** [comment]
@yangwao I'll try to do this

**Comment by vikiival** [comment]
It had some bug afaik 👀

**Comment by yangwao** [comment]
Closing in favour https://github.com/kodadot/nft-gallery/issues/837
