### ISSUE TITLE
Different font in Minting

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7787]
Create: NFT: Single NFT - there is  a bid different font in one of the options when you fill it. Is that intentional? It seems a bit weird to have only this text different.

<img width="1527" alt="Screenshot 2023-10-23 at 15 42 10" src="https://github.com/kodadot/nft-gallery/assets/104380776/9142c9d5-2b8d-4db1-b99e-cff49b3a2f89">

Close up
---
it looks a bit off 
<img width="824" alt="Screenshot 2023-10-23 at 15 44 41" src="https://github.com/kodadot/nft-gallery/assets/104380776/55114167-11d1-437c-8f6a-45a057da359e">

**Comment by Jarsen136** [comment]
It should be solved in #7792
