### ISSUE TITLE
Remove Carbonless Fee.

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7789]
UPDATE: Remove the Carbonless fee from Kodadot.
---
I talked with @yangwao, and we decided to remove (or turn off) this fee for now. We can re-introduce it again in the future if that is something people will want. At the moment this is not important - and we are still carbon neutral. Please remove this fee from KodaDot.

### Initial issue:
Create: NFT: Single NFT (any chain) - in this issue screenshot from rmrk2. 

I tried to go to the minting page and create an NFt, but I noticed that the fee Im supposed to pay is not including Carbonless payment (1 USD for creating an NFT). This picture is from rmrk2 but its the same on other chains.

<img width="1261" alt="Screenshot 2023-10-23 at 16 09 53" src="https://github.com/kodadot/nft-gallery/assets/104380776/4ed11323-5755-4fb1-a8ac-6b4cf09b38a3">

- **We **MUST** show the real total costs someone is paying**. Are people paying that 1 USD from the NFT? (I asked viki and he said he thinks that yes). In this case it must be included in that deposit costs: At the moment we are showing **WRONG** amount.
- Consider adding a carbonless toggle (on/of) back to minting process
- Why is it called deposit on rmrk2/kusama too? from what I know deposit is only on ahk and ahp - on rmrk2 and kusama its normal fee they pay (not returnable)

**Comment by JustLuuuu** [comment]
UPDATE: added to the issue itself: Remove the Carbonless fee from KodaDot. (agreed with yangwao)

**Comment by exezbcz** [comment]
fee turned off by default - p4 now

**Comment by roiLeo** [comment]
off now
