### ISSUE TITLE
Teleport Kusama to KusamaHub not working

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#7798]
![image](https://github.com/kodadot/nft-gallery/assets/22791238/ba2d315e-ab11-4676-a391-cc4133e1525a)

related?

* https://github.com/kodadot/nft-gallery/pull/7765

**Comment by roiLeo** [comment]
Yes might be, looks like it was working for @prury.
maybe try to clear node_modules and install packages

**Comment by dudo50** [comment]
@roiLeo , @prury, please let us know if the problem is still present. We have tested all possible scenarios before pushing PR so should be working fine, but a mistake might have happened from our side also.

With kind regards,
Team ParaSpell

**Comment by daiagi** [comment]
works on canary
