### ISSUE TITLE
More from this collection pictures dont load? 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7829]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/d4dcab9a-5f7e-4e0c-a979-2f22c8784d44)

on collection everything okay
![image](https://github.com/kodadot/nft-gallery/assets/90852205/f691e32c-5be3-4690-8b2d-a036d6c5dcaf)
![image](https://github.com/kodadot/nft-gallery/assets/90852205/11fcd0ac-0972-4838-aac9-f56e4539f400)

**Comment by vikiival** [comment]
Can you please share url of the collection?

**Comment by roiLeo** [comment]
![Screenshot 2024-01-06 at 00-35-34 Tricky RMRK2 Experience Free Promo #1575](https://github.com/kodadot/nft-gallery/assets/9987732/8ad824d1-3c00-46d2-80d7-61b72f21e222)
