### ISSUE TITLE
Fix profile page on mobile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#783]
Right now seems some container is not working well on mobile and horizontal scroll shouldn't not be there.

Worth fixing

Test url 
https://kodadot.xyz/rmrk/u/CocvTCrHM2bcLGNFTVGd71AuvVPFVPbJknDiLJAmNEAfLzi
https://user-images.githubusercontent.com/5887929/134555280-0b4cb161-f42b-489d-8909-d574f305df59.mp4

**Comment by prachi00** [comment]
@yangwao I'll check this
