### ISSUE TITLE
Skeleton loaders for newest list and latest sales

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7835]
- I think it would be nice to introduce some sort of loader for these carousels - every time you enter the home page and scroll, it loads after getting to the bottom and seeing the footer 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/48e0c5e5-ba0e-4afd-9c78-1de6364b0496)

**Comment by prury** [comment]
Indeed Exez, and they are taking more time to load than they previously did: 

https://github.com/kodadot/nft-gallery/assets/36627808/d2ac3552-14be-4fa9-910e-1266519b152c

**Comment by yangwao** [comment]
> they are taking more time to load

it's still slow with Stellate?

**Comment by preschian** [comment]
how about the changes in this PR #8667

Previously, the component loaded if all the queries were settled. This means waiting until longer queries are settled (rmrk/ksm > 1s)

In #8667, the component should be loaded once the faster query has already settled. No need to wait until all the queries are settled
