### ISSUE TITLE
Generative drop cards have same cover img 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7839]
I'm just backlogging here

             > > Done
> > ![image](https://user-images.githubusercontent.com/31397967/277553769-cf8adb20-b4fa-4fd7-8b77-bd8ff25088c5.png)
> 
> they all have the same cover image even if NFTs are different

It's intended because we set the same preview image for every image.  
ref https://github.com/kodadot/nft-gallery/issues/7580#issue-1935121606

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/7745#issuecomment-1777417172_

issue: 
- https://github.com/kodadot/workers/issues/169

**Comment by vikiival** [comment]
Closing for the sake of #7844
