### ISSUE TITLE
Current generative drops are not unlockable

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7843]
And I think generative drops are currently not unlockables.

![image](https://github.com/kodadot/nft-gallery/assets/5887929/0aa33935-c247-451a-8859-206167359f3d)

ref
---
- #7838 
- #7580

**Comment by Jarsen136** [comment]
> And I think generative drops are currently not unlockables.

How about hiding this part for now?

**Comment by vikiival** [comment]
> How about hiding this part for now?

You can check if it's unlockable by queriing keywise service

**Comment by Jarsen136** [comment]
> > How about hiding this part for now?
> 
> You can check if it's unlockable by queriing keywise service

Thank you, but I still need to know how to deal with the collection if that isn't unlockable. Hiding this section or changing the text etc.

**Comment by vikiival** [comment]
Hide
