### ISSUE TITLE
Remove generative art and music tags from hovercard 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7852]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/73e9a6ad-04f0-4990-ba4d-d8dbd3541d21)
- keep them on normal cards 
- also the preview does not load: https://kodadot.xyz/ahk/collection/176

**Comment by JustLuuuu** [comment]
https://github.com/kodadot/nft-gallery/assets/104380776/549655bb-76b0-4fa8-ad86-cc52a04f2185

Previews kind of suck

**Comment by exezbcz** [comment]
> Previews kind of suck

 we have issue for that, this is about the hover cards

**Comment by yangwao** [comment]
> Previews kind of suck

Duplicate or similar or same

- #7844 
- #7839
