### ISSUE TITLE
Better form validation

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#786]
**Is your feature request related to a problem? Please describe.**
It would be super nice to have unified components and have validation for them.

**Describe the solution you'd like**
Use [vee-validate](https://github.com/logaretm/vee-validate)

**Describe alternatives you've considered**
... may @JKrupinski, @AndriiHrynchuk would know other alternatives

**Comment by roiLeo** [comment]
I prefer if we can use html 5 built-in form validation features.
This validation generally doesn't require much JavaScript and built-in form validation has better performance.

**Comment by AndreyGrin** [comment]
html 5 validation is pretty easy and can cover most of the cases. 
Does that `vee-validate` can work nicely with UI libraries?

**Comment by codomposer** [comment]
👋

**Comment by vikiival** [comment]
Can you please take issues no older than 180 days?

**Comment by codomposer** [comment]
Okay, I will, can you check your telegram?
