### ISSUE TITLE
Wrong count for grouped item on explorer items

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7864]
On items explorer shows "3x"
https://canary.kodadot.xyz/ahk/explore/items?listed=true
![image](https://github.com/kodadot/nft-gallery/assets/5887929/f7f9503c-0184-426f-84ff-8e05a1bf5f70)

When you open collection it's 55
https://canary.kodadot.xyz/ahk/collection/176
![image](https://github.com/kodadot/nft-gallery/assets/5887929/77e9ad08-9dfe-4cc3-80c9-4b727fab35bd)

**Comment by exezbcz** [comment]
its listed=true 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/3adfc26c-e091-453e-9c49-4be59bac8f16)

- this is when you remove the buy now filter

**Comment by daiagi** [comment]
can close?
