### ISSUE TITLE
No network in filter when on explore for the first time 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7871]
![telegram-cloud-photo-size-4-5904399466205658906-y](https://github.com/kodadot/nft-gallery/assets/90852205/c408c29d-ea6c-4373-a167-900e14b82f7c)
- we recently remade how the dropdown behaves on mobile
- #7779 

there is no network inputted when you enter the explore on mobile for the first time - you have to select it first

**Comment by prury** [comment]
your address bar shows that you are on the DOT chain 😛

**Comment by exezbcz** [comment]
@prury its about this sir 
<img width="104" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/4617754c-1b10-4547-a913-1fa4f0467294">

**Comment by prury** [comment]
> @prury its about this sir <img alt="image" width="104" src="https://user-images.githubusercontent.com/90852205/281131485-4617754c-1b10-4547-a913-1fa4f0467294.png">

exactly, you probably entered into the transfer page, clicked on dot and then got to explore -> items, changing your chain to dot instead of Ahp and we do not show any info on the DOT chain
