### ISSUE TITLE
Menu buttons on mobile 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7878]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/b73da42d-282e-4acc-8cf8-140b5a5d93f2)
lets change it to 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/9b9bef66-d3c7-4a43-8a68-6fdb9d9451e3)

**Comment by prachi00** [comment]
what are we changing exactly?

**Comment by exezbcz** [comment]
> what are we changing exactly? 

Bottom part
