### ISSUE TITLE
massming onboarding code block broken

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#7885]
pretty sure that there used to be a code block here with proper new lines and indents:

![image](https://github.com/kodadot/nft-gallery/assets/22791238/d3419c79-6761-47ac-b659-9d95fc66a46d)

actually if people follow this as it is right now the txt will not work

also should add line in the txt description saying that need a line gap between one block and another (block being the details of single nft) @exezbcz 

this space is important:
![image](https://github.com/kodadot/nft-gallery/assets/22791238/da092e84-25b4-415d-bd1a-2fe64be455f9)

**Comment by roiLeo** [comment]
missing `<pre>` tag?
NVM In #7132, I've changed `Markdown` component to make it compatible with nuxt3

possible solution:
- reintroduce hightlight.js and make it work with markdown-it
- use nuxt/content to render markdown content
