### ISSUE TITLE
Error in signing in a transaction to create a collection on kusama asset hub on 

### ISSUE THREAD

**Issue by Ozeddd** [kodadot/nft-gallery#7890]
### What happened?

Trying to create a collection on kusama asset hub and  it continues to say it couldn't contact network provider when trying to sign transaction 

### Please reproduce in steps

Try create a collection on kusama asset hub using Nova wallet then sign transaction. 

### Expected Behavior

When I click on sign transaction, I expect the transaction to be signed in and the collection be created. 

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Screenshots

![IMG_20231030_131242_689](https://github.com/kodadot/nft-gallery/assets/125272946/dfc0630b-e051-4ed2-8472-582bde6f6b57)

### Payment link for reward

DK8qzstmWSixWiTzomSJbpjDBKztWXnpLQG43aFFTb1WixX

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ozeddd** [comment]
Another artist has the same problem. 
![Uploading IMG_20231030_160922_796.jpg…]()

**Comment by AshutoshSingh00001** [comment]
what's your internet speed because it seems much likely to be an in app issue
