### ISSUE TITLE
Deactivating buy now on RMRK2 is showing empty first result

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7928]
### What happened?

![image](https://github.com/kodadot/nft-gallery/assets/36627808/dbb1edc1-2e6c-49e4-b9e8-6b39e2c58320)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
can't reproduce maybe it was comming from [this](https://canary.kodadot.xyz/ksm/gallery/20397899-48c2f61e58b57af315-ZTGBDGS-LAUNCH-CAMPAIGN-TRADING-ANY-BADGE-common-FSVs5BUcNq22hXHQvw2K8EYDXAz6gwCee3xqXxErGfR7NhM-PUNDIT:0x7ebd8b9425) item
