### ISSUE TITLE
Create Twitter bot to Tweet when there is production update

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#795]
Probably deploy serverless twitter bot which will tweet once we merge new stuff into production branch, current `rmrk-lite` in future we will have more of them, like per parachain, upcoming are basilisk and statemine

Could be merged with https://github.com/kodadot/nft-gallery/issues/734 somehow

Idea behind this is, I can write a changelog in something like tweets, i.e. if we have 3 features in the current upgrade, format for tweets would be tweet per line? Or actually standardize PR changelog so twitter bot can parse that.

tweet thread 
- this brings new colours to the profile
- this optimizes bundle so kodadot now loads faster on your device
- enjoy new sharing buttons

**Comment by Kutko0** [comment]
I would like to take on this one as my first issue, sorry if it takes some time

**Comment by yangwao** [comment]
overcomplicated, now we have a release page https://github.com/kodadot/nft-gallery/releases and folks doing threads cherry-picking important stuff
