### ISSUE TITLE
Card preview for nft 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#7951]
https://canary.kodadot.xyz/ksm/gallery/12961474-3629a3ff458d113e25-WEAR-FLAME_HAIR-00000009
![image](https://github.com/kodadot/nft-gallery/assets/90852205/e3e47a5f-ab91-4db1-ae19-7224c3fe6f69)

**Comment by hassnian** [comment]
seems to be working

![CleanShot 2023-11-11 at 14 45 45@2x](https://github.com/kodadot/nft-gallery/assets/44554284/20505507-8f86-437b-b86c-62e433ed0aea)
