### ISSUE TITLE
Current NovaWallet bugs

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7970]
@prury can you please go through our app and try every single screen if at current stage at canary is everything is working on mobile? 
We've got fair reports from artists and we want to be for them seamless choice number one.

I would like to lookup on 
- responsive issues
- minting
- signing
- mass minting
- claiming drops
- fiat on-ramp
- explorer/collection view
- gallery item list + buy trade

Feel free post edit this issue and track bugs you've found so we can have a look on them

**by prury:** 
## Working: 

- Transak goes as far as asking for e-mail
- Ramp goes as far as asking for e-mail
- Free drop was properly minted
- Unlockable item of Free drop appears
- Explore filters seems to be working ok
- Transfer works: [tx](https://kusama.subscan.io/extrinsic/20496178-2)
- Teleport works: [tx](https://kusama.subscan.io/xcm_message/kusama-99cb59afa78a4f7afd64dac0d0658be6f0b280d2)
- Massmint worked fine, redirected properly, listing ok (Tested on RMRK2)
- Delist works

## Encountered problems: 
- [x] #8083
- [x] #8078
- [x] #8120
- [ ] [Carbon-less its still active by default](https://github.com/kodadot/nft-gallery/assets/36627808/a97fcb59-b527-485f-923b-13e3d682c6b3)
- [x] #8707
- [x] #8127
- [x] #8708
- [x] #8530
- [x] #8192
- [x] #8121
- [ ] Deposit values for collection Creation are way more than what we require: [Image](https://github.com/kodadot/nft-gallery/assets/36627808/7d2b1c6a-e279-4a4f-80d4-c91190f5bc9b)
- [ ] Clicking on blog article links take 3-5 seconds to redirect
- [x] #8155
- [x] #8166
- [x] #8159
- [x] #8170
- [x] #8158
- [x] #8081
- [x] #8082
- [ ] #8726 

🚨 i may have stumbled upon a bug on nova where their app asks for signing but the pop up stays on the background(to be confirmed)

Observations: 
Overall user experience is poor, often you have to reload the page and transactions take more time than usual
Tested on Android - Xiaomi device

**Comment by prury** [comment]
@yangwao sure, Luu asked me this as well, please give me permission to edit your issue

**Comment by yangwao** [comment]
> please give me permission to edit your issue

yes, you can triage

**Comment by prury** [comment]
> > please give me permission to edit your issue
> 
> yes, you can triage

hahahaha, when i meant permission, its because i cannot edit your issue:

![image](https://github.com/kodadot/nft-gallery/assets/36627808/1a8b71d5-2892-4b5f-98d8-b0a263af21a8)

**Comment by yangwao** [comment]
> its because i cannot edit your issue:

please try now? thought triage should work

**Comment by prury** [comment]
> > its because i cannot edit your issue:
> 
> please try now? thought triage should work

works now, ty!

**Comment by JustLuuuu** [comment]
https://github.com/kodadot/nft-gallery/issues/8013

**Comment by hassnian** [comment]
tested some on ios 

> - Copy address, pay me link, recurring payment buttons on transfer do not work 

✅ working for [me ](https://github.com/kodadot/nft-gallery/assets/44554284/3c5eff94-c85c-4fe5-9f7f-fd550bf15182)

> Deposit values for collection Creation are way more than what we require

✅ working [image](https://github.com/kodadot/nft-gallery/assets/44554284/e5ee62ab-f288-4e2e-9978-d1e8538b8390)

> download image doesn't work

❌ didn't work 

> [Drop upload images not loading](https://github.com/kodadot/nft-gallery/assets/36627808/6f24e952-0832-40f9-baab-da7ccce3c5a2)

✅ working  [img](https://github.com/kodadot/nft-gallery/assets/44554284/40b93ced-962e-4a63-b554-3e2bedff8210)

**Comment by prury** [comment]
> tested some on ios
> 
> > * Copy address, pay me link, recurring payment buttons on transfer do not work
> 
> ✅ working for [me ](https://github.com/kodadot/nft-gallery/assets/44554284/3c5eff94-c85c-4fe5-9f7f-fd550bf15182)
> 
> > Deposit values for collection Creation are way more than what we require
> 
> ✅ working [image](https://github.com/kodadot/nft-gallery/assets/44554284/e5ee62ab-f288-4e2e-9978-d1e8538b8390)
> 
> > download image doesn't work
> 
> ❌ didn't work
> 
> > [Drop upload images not loading](https://github.com/kodadot/nft-gallery/assets/36627808/6f24e952-0832-40f9-baab-da7ccce3c5a2)
> 
> ✅ working [img](https://github.com/kodadot/nft-gallery/assets/44554284/40b93ced-962e-4a63-b554-3e2bedff8210)

thank you!

**Comment by preschian** [comment]
the list that doesn't work on me (ios)
```
Full Screen button not working on Gallery item
exiting on ramp screen
🚨 Change price never asks for transaction
download image doesn't work
Listing never asks for signing(for already minted items)
```

**Comment by daiagi** [comment]
running list of issues reported but i can't reproduce
- [x] #8083
- [x] #8120
- [x] [Carbon-less its still active by default](https://github.com/kodadot/nft-gallery/assets/36627808/a97fcb59-b527-485f-923b-13e3d682c6b3)
- [x] [Drop upload images not loading](https://github.com/kodadot/nft-gallery/assets/36627808/6f24e952-0832-40f9-baab-da7ccce3c5a2)
- [x] [image not loading on create nft modal](https://github.com/kodadot/nft-gallery/assets/36627808/e0ba884b-2e2e-49f2-a500-dd9a262a3613)
- [x] Copy address, pay me link, recurring payment buttons on transfer do not work
- [x] Pretty much nothing related to copy/paste works there
- [x] Clicking on blog article links take 3-5 seconds to redirect

- [x] download image doesn't work

**Comment by prury** [comment]
@daiagi i think i may have found a way...and it runs on Linux
tried my way with some known emulators and finally stumbled upon https://developer.android.com/studio/run/emulator
(other android emulators only go as far as android version 9)
takes some time before it installs everything and download some modules, but i was able emulate an Android version 12 system and reproduce this first minting bug on the issue above (image has same properties as collection)

<img src="https://github.com/kodadot/nft-gallery/assets/36627808/6fd1776d-d752-45b6-9b34-32b35f12be50" height="500">

it should have a mushroom image there instead of image above
https://canary.kodadot.xyz/ahk/gallery/276-2

emulator UI:
![image](https://github.com/kodadot/nft-gallery/assets/36627808/9b120672-0a8e-424b-bef4-8ebc75ecea4d)
we don't really need the novawallet.apk, downloaded it just in case

its also possible to download images from other android versions

**Comment by prury** [comment]
statistics: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/e6e4eac6-13e7-41f3-890a-c0860ddee15b)
![image](https://github.com/kodadot/nft-gallery/assets/36627808/66670072-d4e8-4c12-8411-c2575e726a8e)
![image](https://github.com/kodadot/nft-gallery/assets/36627808/a2a763ab-7406-4334-8f0e-ffae5554d407)
![image](https://github.com/kodadot/nft-gallery/assets/36627808/3aedfcbe-2cb0-477a-bb8b-326e714312ff)

**Comment by yangwao** [comment]
> android version mobile users use the most?

focus on newest one, in our case A13

**Comment by daiagi** [comment]
@yangwao regardless, I solved most of the bugs already
Ramiming only toast position and inability to mint files from Google drive

**Comment by exezbcz** [comment]
anything left? 👀

**Comment by prury** [comment]
> anything left? 👀

minting from google drive and deposit values when creating nft (will recheck this one)

**Comment by yangwao** [comment]
thank you @prury & @daiagi fixing up things! 
we can probably unpin when done and close this one

**Comment by yangwao** [comment]
getlemen, you done amazing job!

<img src="https://media0.giphy.com/media/jtQpRa3y7S2Ke3JvQE/giphy.gif"/>

**Comment by prury** [comment]
> getlemen, you done amazing job!
> 
> ![](https://camo.githubusercontent.com/4c9c5e13d8edbbef625da6ddce840fd7f2279b900dbdc89ad48731a79c488cfb/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6a745170526133793753324b65334a7651452f67697068792e676966) [ ![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6a745170526133793753324b65334a7651452f67697068792e676966](https://camo.githubusercontent.com/4c9c5e13d8edbbef625da6ddce840fd7f2279b900dbdc89ad48731a79c488cfb/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6a745170526133793753324b65334a7651452f67697068792e676966) ](https://camo.githubusercontent.com/4c9c5e13d8edbbef625da6ddce840fd7f2279b900dbdc89ad48731a79c488cfb/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6a745170526133793753324b65334a7651452f67697068792e676966) [ ](https://camo.githubusercontent.com/4c9c5e13d8edbbef625da6ddce840fd7f2279b900dbdc89ad48731a79c488cfb/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6a745170526133793753324b65334a7651452f67697068792e676966)

Thank you dear @yangwao!
