### ISSUE TITLE
crash on localhost chrome

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#7989]
Chrome browser
localhost

Ubuntu - not that it should matter

![image](https://github.com/kodadot/nft-gallery/assets/22791238/e3e545bf-7eac-4322-882f-1d89ac786678)

**Comment by roiLeo** [comment]
have you tried to clear node_modules & reinstall?

**Comment by daiagi** [comment]
just did
didn't fix it

all good for you @roiLeo ?

**Comment by roiLeo** [comment]
it does work on my side, fresh chrome install, main branch

<img width="294" alt="Capture d’écran 2023-11-09 à 1 04 55 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/ffcb63ec-2676-4f44-b365-7b6f90b6b620">

**Comment by yangwao** [comment]
> have you tried to clear node_modules & reinstall?

or purge global node_modules cache 👀

**Comment by daiagi** [comment]
did:
1. fresh clone of nft-gallery
2. `npm cache clean --force`
3. `pnpm store prune`
4. pnpm store path => delete all using `rm -rf`

result
 it  worked once. now back where it was before
 same on Brave btw
 
 @kodadot/internal-dev  anyone else have these issues?
 
 currently I can only use firefox to develop

**Comment by preschian** [comment]
Several days ago, this issue blocked my development on localhost #7967

now, probably related to this https://github.com/nuxt/nuxt/issues/24196. could you try this PR #8018?

**Comment by daiagi** [comment]
>Now, it's probably related to this https://github.com/nuxt/nuxt/issues/24196. Could you try this PR https://github.com/kodadot/nft-gallery/pull/8018?

improved speed of dev server in firefox, did not help the crash issue

>And try to open it on incognito? There may be some conflicts with the extensions.

jackpot
 did  quite get to the root of it yet but it seems that Talsiman wallet is the culprit

**Comment by yangwao** [comment]
> * non-incoginto - same crash as I reported even with all extensions uninstalled

if you open it on the new chrome profile or chrome canary? - https://www.google.com/chrome/canary/

**Comment by daiagi** [comment]
update:

uninstall -> reinstall Chrome did not help

>if you open it on the new chrome profile or chrome canary? - https://www.google.com/chrome/canary/

Linux is not supported

**Comment by yangwao** [comment]
> Linux is not supported

maybe 
- https://www.chromium.org/getting-involved/dev-channel/ 
- https://www.google.com/chrome/browser/?platform=linux&extra=devchannel

**Comment by daiagi** [comment]
works on chrome-dev
https://www.google.com/chrome/browser/?platform=linux&extra=devchannel

**Comment by daiagi** [comment]
No vpn
I can try with but hard to believe it's related

**Comment by vikiival** [comment]
> I can try with but hard to believe it's related

Actually a lot of things stops working if you use VPN ;D
cc @helloitsdamsky can say more

**Comment by vikiival** [comment]
Still an issue?

**Comment by daiagi** [comment]
seems ok
