### ISSUE TITLE
Hover card of generative minted NFTs not loading image // Generative collection preview on hover card

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7996]
Check any generative card: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/c15c5f90-592d-4add-bfbb-457540c7acd7)

**Comment by yangwao** [comment]
I think there was issue to remove that icon from there?

**Comment by exezbcz** [comment]
rel 
- https://github.com/kodadot/nft-gallery/issues/7852
