### ISSUE TITLE
Change OG image to show price in USD 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#7997]
We are right now showing KSM and we should show USD best 

https://canary.kodadot.xyz/ahp/gallery/35-8
![image](https://github.com/kodadot/nft-gallery/assets/5887929/736bf373-329a-4591-9c4f-bc1b5579b3ab)

**Comment by JustLuuuu** [comment]
and new logo https://github.com/kodadot/kodadot-presskit/blob/main/pre-v4/png/KodalightV4.png 😇

**Comment by roiLeo** [comment]
> We are right now showing KSM and we should show USD best

-> worker issue

> and new logo https://github.com/kodadot/kodadot-presskit/blob/main/pre-v4/png/KodalightV4.png 😇

-> AndreyGrin/og-image issue


Please could we duplicate `pre-v4` to `v-4`

**Comment by yangwao** [comment]
> -> AndreyGrin/og-image issue

we can use finally this I guess? https://nuxt.com/modules/og-image

**Comment by yangwao** [comment]
- https://github.com/kodadot/nft-gallery/issues/7587#issuecomment-1767936541

**Comment by yangwao** [comment]
Meanwhile it's working thanks to @preschian just need to add price
- https://github.com/kodadot/workers/pull/194
![image](https://github.com/kodadot/nft-gallery/assets/5887929/195eab26-fd59-4023-bc94-f8db92ab55c4)

**Comment by yangwao** [comment]
I think @preschian can take the lead on this one. 
Injecting USD price should be fair easy with
- https://github.com/kodadot/nft-gallery/pull/8036 ?

**Comment by preschian** [comment]
> I think @preschian can take the lead on this one. Injecting USD price should be fair easy with
> 
> * [feat: kodaprice #8036](https://github.com/kodadot/nft-gallery/pull/8036) ?

sure, will continue to this one
