### ISSUE TITLE
Teleport: quick chain swap

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8000]
I was going to use teleport and I wanted to teleport from AHP to Polkadot. Once I opened teleport my options looked like int he picture. I automatically clicked on the arrow in the middle, thinking it would swap the chains:

<img width="1429" alt="Screenshot 2023-11-09 at 17 19 52" src="https://github.com/kodadot/nft-gallery/assets/104380776/b69ab536-eeff-4f9f-a089-0de9312aad81">

But looks like it does not work that way. Maybe it will be nice to implement that in the future. Click in the arrow and AHP will swap to Polkadot and otherwise.

**Comment by roiLeo** [comment]
will be closed by #7984

**Comment by exezbcz** [comment]
soon merged
