### ISSUE TITLE
List for sale from Profile does nothing

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8010]
The list for sale does nothing.

Change Price works flawlessly

![image](https://github.com/kodadot/nft-gallery/assets/5887929/bba86b78-5bad-4940-a976-0d1912b06cb6)

**Comment by yangwao** [comment]
switching on mobile and back started working. weiird. 

oh, on canary it works, tho

**Comment by yangwao** [comment]
no, does nothing on canary, seems legit weird glitch/bug 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/5234667a-1576-467a-bff1-215bc88b79a9)

**Comment by prury** [comment]
@yangwao how to reproduce?

here: 
https://github.com/kodadot/nft-gallery/assets/36627808/49ede0ac-8e27-4dcf-9aec-2928f8e5bd58

**Comment by daiagi** [comment]
>@yangwao how to reproduce?

just listed this one from profile as well (on canary)
https://canary.kodadot.xyz/ahk/gallery/196-27
![image](https://github.com/kodadot/nft-gallery/assets/22791238/8eb66f48-4143-42b4-b170-d049b8639b18)

**Comment by yangwao** [comment]
no errors in console

> Version 119.0.6045.105 (Official Build) (arm64)
> OSX latest Version 14.1.1 (23B81)

https://github.com/kodadot/nft-gallery/assets/5887929/b105d72c-921e-4643-9b44-0a47c19d1257

**Comment by yangwao** [comment]
> Version 119.0.6045.105 (Official Build) (arm64)

updated to recent chrome stable, same to me

Version 119.0.6045.123 (Official Build) (arm64)

If it's not happening for you 

oh now even on kodadot.xyz has stopped working 😅

**Comment by yangwao** [comment]
> how to reproduce?
> just listed this one from profile as well (on canary)

I've improved description to be more descriptive for bug. 
Listing on sale works once selected well and when I was able to trigger through mobile has worked after selection. 

Issue is I can't select it :/

**Comment by daiagi** [comment]
only issue i found so far is
1. on a stacked cards, click list for sell
2. no check mark
3. rest (background and mini list popup) works well for me

![image](https://github.com/kodadot/nft-gallery/assets/22791238/f18ea0bc-a18a-4bf6-a589-75ad977f3134)
