### ISSUE TITLE
Error: No response recieved from endpoint:

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8013]
An artist has this issue minting on Nova wallet - AHK
Her address: GCFRnbhJSEUWGfbPA3LvU2T1eRAtRDP722mm65GeNEsbVYD

https://github.com/kodadot/nft-gallery/assets/104380776/ede0ab93-e8d5-4091-8d35-8a02b6906920

Her collection: https://kodadot.xyz/ahk/collection/262

### She then tried to mint on laptop
She got this notification: Even though her NFTs are not in the collection
![image_2023-11-10_16-03-00](https://github.com/kodadot/nft-gallery/assets/104380776/6daeea3f-d1ca-4b8c-9c7e-2d82e6a744b3)

![photo_2023-11-10 15 55 03](https://github.com/kodadot/nft-gallery/assets/104380776/49aac8d8-8828-410b-830e-be8bdde995c9)

**Comment by JustLuuuu** [comment]
Uploading Screen Recording 2023-11-13 at 11.48.41.mov…

looks like more peeps have this issue

**Comment by roiLeo** [comment]
- https://assethub-kusama.subscan.io/account/GCFRnbhJSEUWGfbPA3LvU2T1eRAtRDP722mm65GeNEsbVYD

![Screenshot 2023-11-13 at 10-05-59 Subscan Aggregate Substrate ecological network high-precision Web3 explorer](https://github.com/kodadot/nft-gallery/assets/9987732/ae227a6a-30e6-445e-a979-f63cbbe2758c)

`max_supply`: 1

**Comment by roiLeo** [comment]
collection burned, no longer relevant
