### ISSUE TITLE
Size of K placeholder in activity of collection

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8029]
Is it intended to look like this? 
cc @exezbcz 

- https://canary.kodadot.xyz/ksm/collection/dac5c7f54029d0e73c-XCHIMPZ/activity

![image](https://github.com/kodadot/nft-gallery/assets/5887929/96bf59d7-9aaf-4534-ab06-c7fd85da2742)

oh and actually doesn't show item picture properly as after clicking it loads proper item

**Comment by exezbcz** [comment]
> Is it intended to look like this?

guess sir

answer: no :D

**Comment by daiagi** [comment]
@exezbcz 
the placeholders supplied here
https://github.com/kodadot/nft-gallery/pull/7698#issuecomment-1768981046

have no padding. 
please if you could supply the placeholders as they should appear

**Comment by prury** [comment]
related #7926

**Comment by exezbcz** [comment]
@daiagi sure sir


same as with the old zip file, there are multiple levels of compression

[darkmodeplaceholderpadding.zip](https://github.com/kodadot/nft-gallery/files/13339780/darkmodeplaceholderpadding.zip)
[Whiteplaceholderpadding.zip](https://github.com/kodadot/nft-gallery/files/13339781/Whiteplaceholderpadding.zip)

thanks!
