### ISSUE TITLE
Burn NFT: Error message

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8039]
I tried to delete an NFT I own (not created) but I own it - its my POAP NFT I received. [This](https://kodadot.xyz/ahk/gallery/u-2023-292) one.

Once I clicked on burn, I got an Error message:

<img width="1408" alt="Screenshot 2023-11-13 at 13 13 44" src="https://github.com/kodadot/nft-gallery/assets/104380776/68512362-30fb-4cbe-937d-366d16a19f9c">

https://github.com/kodadot/nft-gallery/assets/104380776/086e7f5f-618d-45cd-9215-d4babf231ec2

Also @preschian said[ this PR ](https://github.com/kodadot/nft-gallery/pull/7960/files) was open the button to all users.

**Comment by preschian** [comment]
> Also @preschian said[ this PR ](https://github.com/kodadot/nft-gallery/pull/7960/files) was open the button to all users.

oohh, sorry, I thought the error was on "delete collection". So, it's not related to the PR I referred 🙏
