### ISSUE TITLE
Auto-teleport working from NovaWallet?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8043]
It got Canceled after Signing tx, @prury can you please check?

Listing NFTs and Buying should be enough to confirm if its working or what can be wrong

![telegram-cloud-photo-size-5-6237553194523802376-y](https://github.com/kodadot/nft-gallery/assets/5887929/1ffa1269-9274-42b0-9054-2d03a47ae304)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/d0f56a67-9b67-404d-bc73-ddb0753eab2f)

**Comment by prury** [comment]
@yangwao as stated on https://github.com/kodadot/nft-gallery/issues/7970, buying on ahk or RMRK2 not working on nova, it fires the teleport page, funds get teleported but buying never asks for signing

**Comment by daiagi** [comment]
works for m
![photo1700806273](https://github.com/kodadot/nft-gallery/assets/22791238/86f836f8-945b-4ff3-a5d3-7179b152ec92)
e

[teleport tx](https://kusama.subscan.io/extrinsic/20692657-4)
[buy tx](https://assethub-kusama.subscan.io/extrinsic/5856365-2)

**Comment by daiagi** [comment]
can we close @prury @yangwao
