### ISSUE TITLE
missing image after minting

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#8052]
![image](https://github.com/kodadot/nft-gallery/assets/22791238/7b2e7072-ac1b-4984-ac51-1289a1686288)

recently I've seen a few times that the image is missing after minting

refreshing usually (but not always) solves it
yet is a bad minting experience

## Reproduce:

Mint anything 
seen on AHK

**Comment by yangwao** [comment]
adding wait time on minting page would solve this? is picture right away available on image worker?

**Comment by daiagi** [comment]
> adding wait time on minting page would solve this? is picture right away available on image worker?

I think not
seems to me that as long as you don't look at the card from another page (explore/ collection/ profile)
it stays empty
once it load on another page then all works as it should

**Comment by preschian** [comment]
any error response from network/console?

**Comment by daiagi** [comment]
> any error response from network/console?

unrelated console error:
something to do with auto teleport?
![image](https://github.com/kodadot/nft-gallery/assets/22791238/cccfbcd5-4807-47fe-9908-8b50fa0e6b52)


there it is. it appeared eventually. just took verrrrryyyyy looooooong time
![image](https://github.com/kodadot/nft-gallery/assets/22791238/2fc1bc6a-3cb0-4ed9-8b3e-cd2757b21dc1)

**Comment by preschian** [comment]
wow 6 min, so long

I added preheat the file, but it seems like it does not work https://github.com/kodadot/nft-gallery/blob/70a1fccd6af6b9778d02cee81bdb3f74db57d370/utils/ipfs.ts#L165

> adding wait time on minting page would solve this?

how about adding this method? ensure the image return 200 and then redirect to gallery detail

**Comment by daiagi** [comment]
>how about adding this method? ensure the image return 200 and then redirect to gallery detail

wouldn't that just move the waiting to the minting page?

**Comment by preschian** [comment]
> wouldn't that just move the waiting to the minting page?

yes actually

or

directly upload the image to our cf-images (after preheat) `https://imagedelivery.net/jk5b6spi_m_-9qC4VTnjpg/CID/public`

then, redirect to gallery detail page while adding the cf-images to the query params `kodadot.xyz/ahk/gallery/268-2?image=https://imagedelivery.net/jk5b6spi_m_-9qC4VTnjpg/CID/public`

but currently we don't have some endpoint to upload to our cf-images

with this, we can skip IPFS stuff I guess

**Comment by daiagi** [comment]
I wonder why it began happening in the first place
didn't use to be a problem

**Comment by preschian** [comment]
I guess that because ipfs gateway needs time to resolve newly created assets

Scenario:
- Let's say we are pinning ipfs assets to `gateway-a`

on image workers:
- check on `gateway-b`, ❌
- check on `gateway-c`, ❌
- check on `gateway-d`, ✅. then return
this is why the worker will take longer to return, because need to check through `gateway-b` and `gateway-c` first

On image worker, it will check from ipfs gateway one by one within three gateways until resolved or return null. ref: https://github.com/kodadot/workers/blob/main/image/src/utils/ipfs.ts
