### ISSUE TITLE
toast in wrong place

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#8082]
![photo1700132816(1)](https://github.com/kodadot/nft-gallery/assets/22791238/92c12269-88af-4eff-aefb-7b0fbc788f92)

@exezbcz  i think we can get rid of this toast completely . wdyt?

**Comment by exezbcz** [comment]
yeah, I will make issue for modals on mobile tomorrow or later today. It should also solve the overflowing etc.


we can get rid of it on mobile devices yes
