### ISSUE TITLE
🚨 Minting a NFT on Ahk redirects fine, but the NFT minted has the same image/properties as the collection | tx NFT

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#8083]
@prury how long ago did you test that?
tries now and it works
https://kodadot.xyz/ahk/collection/268
and I remember we solved this bug (unrelated to mobile/nova) in the past

I think we can mark it as done

**Comment by prury** [comment]
@daiagi minting on Ahk on nova not even working no more, just stays on loading screen and never asks for signing, at least on my side. 
fyi: I'm not using any android emulator or mobile simulation on browsers for these tests, i'm using my own mobile device.

**Comment by prury** [comment]
was able to mint and the same occurred: https://assethub-kusama.subscan.io/extrinsic/5805025-2

**Comment by daiagi** [comment]
@prury  for some reason your `set_meatdata` extrinsic is sent out with empty data
![image](https://github.com/kodadot/nft-gallery/assets/22791238/a6a66b28-873a-4549-afc6-53530278a774)

as a fallback, you sen the collection's image as a result

i am facing no such issue
![photo1700206137](https://github.com/kodadot/nft-gallery/assets/22791238/cd9d87d2-9b7f-430f-9130-395e53fb2b8f)

![image](https://github.com/kodadot/nft-gallery/assets/22791238/4c49b3f6-35b0-4678-91b6-90c45787b04f)


https://assethub-kusama.subscan.io/extrinsic/5805025-2


### Update metadata

I'm guessing here, but do you know how to update Nova's wallet metadata? 
if not dm me and i'll help

maybe it will solve the issue

**Comment by daiagi** [comment]
Continue in #8726
