### ISSUE TITLE
Drop Page: Remove old drops 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8084]
@vikiival Can we remove old drops from Drop page? Copenhagen and berlin.... it was quite some time ago, they are outdated, and they dont have any traction. It will clear page for new drops.

<img width="1394" alt="Screenshot 2023-11-16 at 14 18 17" src="https://github.com/kodadot/nft-gallery/assets/104380776/de26c76d-1c6d-4966-9d2e-787673ab0abd">

I would suggest to do a Christmas version Drop page. It should be available soon (Christmas are coming). Maybe try different model this time? This model has very nice and cute waifus but they all look too much alike.

**Comment by vikiival** [comment]
> This model has very nice and cute waifus but they all look too much alike.

https://replicate.com/cjwbw/anything-v4.0

These are the current setting please feel free to play with the propmpt, 
probably you can get better results

```json
{
    "prompt": "medium digital painting of smiling artistic latina anime waifu with brown hair, wearing fashion clothes, flat lighting, Ljubjana in the background, saturated colors",
    "negative_prompt": "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name",
		"width": 512,
    "height": 512,
    "num_outputs": 4,
    "guidance_scale": 7,
    "num_inference_steps": 50
}
```

**Comment by vikiival** [comment]
Removed the drops

![Screenshot 2023-11-16 at 14 46 38](https://github.com/kodadot/nft-gallery/assets/22471030/8e24e19b-20e4-43a6-bbb1-9f9bc57b4d4b)
