### ISSUE TITLE
List is not showing on chart but appears in activity

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8108]
https://canary.kodadot.xyz/ahp/collection/38/activity
![image](https://github.com/kodadot/nft-gallery/assets/5887929/95f84525-8f33-481b-b9e1-95bd227255ba)

**Comment by daiagi** [comment]
@yangwao , once upon a time , you requested to remove outliers from the chart, in order to make it look more neat
this is a result of that

maybe a solution will be to only clean outliers if there is a large enough amount of data points?
how will we define that? what is large enough?

or we can compare the dataset size before and after outlier removal, and only remove if less then (10%?) of points have been remove
i.e clean/dirty > 0.9

or?

**Comment by yangwao** [comment]
> maybe a solution will be to only clean outliers if there is a large enough amount of data points?
> how will we define that? what is large enough?

> One common method is to use the interquartile range (IQR). A data point is considered a low outlier if it falls more than 1.5 times the IQR below the first quartile (Q1), and a high outlier if it falls more than 1.5 times the IQR above the third quartile (Q3)
[3](https://www.freecodecamp.org/news/what-is-an-outlier-definition-and-how-to-find-outliers-in-statistics/)
.

> add small checkbox in chart settings to remove outliers

this would be nice and probably default on?

**Comment by daiagi** [comment]
>One common method is to use the interquartile range (IQR). A data point is considered a low outlier if it falls more than 1.5 times the IQR below the first quartile (Q1), and a high outlier if it falls more than 1.5 times the IQR above the third quartile (Q3)

regardless of the method, statistics is only valuable when the dataset is large enough.
that is, more often then not, not the case for us

>or add small checkbox in chart settings to remove outliers

ok ,  @exezbcz  could you draw for me where you want it?

**Comment by exezbcz** [comment]
> >One common method is to use the interquartile range (IQR). A data point is considered a low outlier if 
> ok ,  @exezbcz  could you draw for me where you want it?
> 
> 

Yesss, of course. Mr pen on my way
