### ISSUE TITLE
Listing NFT with Auto Teleport: showing wrong text

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8114]
I listed my NFT for sale.
AHP - Pareidoscope - Auto teleport
<img width="1420" alt="Screenshot 2023-11-17 at 00 16 44" src="https://github.com/kodadot/nft-gallery/assets/104380776/409e51d0-aed4-4994-972a-720494a36db5">

After clicking on list and Auto teleport its shows "Confirm Purchase". 

Im not buying frens, Im selling 😎

**Comment by exezbcz** [comment]
> Im not buying frens, Im selling 😎

not right move



yeah, missed this, would be nice to change it accordingly to the modals

mint - confirm minting 
listing - confirm listing

**Comment by exezbcz** [comment]
continue to: 
- https://github.com/kodadot/nft-gallery/issues/8134
