### ISSUE TITLE
Offers page: My offers

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8122]
What needs to be done?
---
Sinc there are still some offers out there on Basilisk:

<img width="522" alt="Screenshot 2023-11-17 at 11 07 36" src="https://github.com/kodadot/ops-internal/assets/104380776/6557c94d-1971-4d36-83dd-d606fd11c6ca">

Now its possible to see incoming offers but not offers you made. Would be cool add them here:
<img width="1415" alt="Screenshot 2023-11-17 at 11 08 39" src="https://github.com/kodadot/ops-internal/assets/104380776/61891908-5e08-4536-b8a8-3a85e7721881">

I know BSX has noi priority now but we had offers page before so maybe its not that complicated to add that

**Comment by roiLeo** [comment]
won't fix
