### ISSUE TITLE
Full screen and Theatre mode is broken on desktop

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#813]
**Describe the bug**
Unrelated to #806 as it was broken before

In before #809 :
<img width="1680" alt="Screenshot 2021-09-27 at 14 50 58" src="https://user-images.githubusercontent.com/22471030/134912715-ae34376e-8daa-4dbc-827b-33eb851f127d.png">

<img width="1680" alt="Screenshot 2021-09-27 at 14 51 01" src="https://user-images.githubusercontent.com/22471030/134912691-97e3eb91-5d54-4b6e-9781-023923daab68.png">

**Comment by vikiival** [comment]
After #809 :
<img width="1680" alt="Screenshot 2021-09-27 at 14 59 15" src="https://user-images.githubusercontent.com/22471030/134912992-932833c4-1000-40a5-a39b-0345059fec5f.png">
<img width="1680" alt="Screenshot 2021-09-27 at 14 59 17" src="https://user-images.githubusercontent.com/22471030/134912997-182b5f48-083c-4142-a95d-a26f1f10ddfe.png">

**Comment by yangwao** [comment]
Re #806 - theatre mode is also broken, more pics in this comment https://github.com/kodadot/nft-gallery/issues/806#issuecomment-927824121

**Comment by vikiival** [comment]
Closed in #814
