### ISSUE TITLE
Cancelling offer on bsx not working

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8131]
Jose cannot cancel his offer he made:

![image](https://github.com/kodadot/nft-gallery/assets/104380776/fb13b60b-6ce1-49d8-bb91-88991da625f1)

his question: Can sendme the extrinsic? To remove it

**Comment by hassnian** [comment]
bsx was down , try again if online should work

**Comment by JustLuuuu** [comment]
Artist managed to do it now.

**Comment by roiLeo** [comment]
> Artist managed to do it now.

External issue, we already have RPC fallback if indexer down
