### ISSUE TITLE
Neutral tones change and system

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8137]
It was in Figma drafted for a long time, and I finally convinced myself to finish it :D 

## figma file
new page with components and colors
![image](https://github.com/kodadot/nft-gallery/assets/90852205/407e6d69-e72b-4214-b57b-28780bf9df35)
https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=5311%3A18771&mode=design&t=5BXhDaQFMuwQI7wZ-1

# Why? 
There was a lot of confusion about the grey colors, it was not really robust structure. I won't talk about the naming...
Pairs of colors that were in light mode didn't have a good pair in the dark mode. 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/cf5cff19-02ea-4448-b81b-3bc90b4489cd)

so, what are the pairs now? 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/f3612bef-3860-41f2-bc81-18dd7f8f066d)

- described in figma.
- pairs are in the row
- k-grey, shade, hovergrey now replaced with alternatives with "neutral" naming 

I think best would be to import the whole neutral color part
![image](https://github.com/kodadot/nft-gallery/assets/90852205/551fc171-6569-42a0-9a84-d23f58b7139c)
- its 13 colors, not all are used.

### import

<details>
<summary>Code</summary>

 {
    "hex": "#ffffff",
    "rgb": "rgb(255, 255, 255)",
    "token": "neutral-1"
  },
  {
    "hex": "#fcfcfc",
    "rgb": "rgb(252, 252, 252)",
    "token": "neutral-2"
  },
  {
    "hex": "#f5f5f5",
    "rgb": "rgb(245, 245, 245)",
    "token": "neutral-3"
  },
  {
    "hex": "#f0f0f0",
    "rgb": "rgb(240, 240, 240)",
    "token": "neutral-4"
  },
  {
    "hex": "#d9d9d9",
    "rgb": "rgb(217, 217, 217)",
    "token": "neutral-5"
  },
  {
    "hex": "#bfbfbf",
    "rgb": "rgb(191, 191, 191)",
    "token": "neutral-6"
  },
  {
    "hex": "#8c8c8c",
    "rgb": "rgb(140, 140, 140)",
    "token": "neutral-7"
  },
  {
    "hex": "#595959",
    "rgb": "rgb(89, 89, 89)",
    "token": "neutral-8"
  },
  {
    "hex": "#454545",
    "rgb": "rgb(69, 69, 69)",
    "token": "neutral-9"
  },
  {
    "hex": "#262626",
    "rgb": "rgb(38, 38, 38)",
    "token": "neutral-10"
  },
  {
    "hex": "#1f1f1f",
    "rgb": "rgb(31, 31, 31)",
    "token": "neutral-11"
  },
  {
    "hex": "#141414",
    "rgb": "rgb(20, 20, 20)",
    "token": "neutral-12"
  },
  {
    "hex": "#000000",
    "rgb": "rgb(0, 0, 0)",
    "token": "neutral-13"
  }

</details>

 
## Examples
lets use k-shade as an example 

k-shade had hex color #CCCCCC 
- its now changed to #d9d9d9 - based on system = neutral-5 
- it also has a dark mode pair with hex code of #454545 - in the neutral color system its neutral-9 

rel
- #8113

**Comment by shashkovdanil** [comment]
@exezbcz what do you think about something like this https://www.figma.com/community/plugin/1222415071406554904/tokens-to-tailwind-css?

The idea is that we take the colors from figma and automatically sync them with tailwind.config

**Comment by exezbcz** [comment]
> The idea is that we take the colors from figma and automatically sync them with tailwind.config

That sounds nice, if it would help with the offload of some manual work I am for it. 

what are the steps to set it up?

**Comment by roiLeo** [comment]
colors implemented

https://github.com/kodadot/nft-gallery/blob/f22a4233d0ffb42430c32ba597ee99c1f577d19e/libs/ui/tailwind.config.js#L54-L68
