### ISSUE TITLE
Artist unable to add NFTs to his collection

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8151]
Artist unable to add NFTs to his rmrk2 collection. Just fiy his collection originally minted on rmrk1 then migrated to rmrk2. He wants to add NFT to rmrk2 collection. 
RMRK1 collection: https://kodadot.xyz/rmrk/collection/362f9efe7813f79902-SIK
RMRK2 collection: same collection migrated to RMRK2: https://kodadot.xyz/ksm/collection/362f9efe7813f79902-SIK 

- one was rmrk1 and the other rmrk2 migrated
- he is logged in with the collection owner ACC
- unable to see his collection in the Select collection field:

![2023-11-19 18 13 40](https://github.com/kodadot/nft-gallery/assets/104380776/634c5346-9fac-48fe-8981-70edcae04bc3)
![2023-11-19 18 13 34](https://github.com/kodadot/nft-gallery/assets/104380776/ce58e7ef-8fdb-42b2-829e-abbc70fc86b8)

**Comment by SimonKraus** [comment]
you beat me to it :D for further questions cc
thanks luu
