### ISSUE TITLE
Too many zeros in decimals

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8173]
Why are we showing so many zeros? ahp/ahp etc... I know that we are rounding on 4 decimals, but in case we have a number like 0.5 it would be good to show it as 0.5 not 0.5000. 

<img width="1439" alt="Screenshot 2023-11-21 at 13 42 40" src="https://github.com/kodadot/nft-gallery/assets/104380776/a9b447df-b733-4687-8f13-75a9139c283a">

<img width="1220" alt="Screenshot 2023-11-21 at 13 46 00" src="https://github.com/kodadot/nft-gallery/assets/104380776/280474cc-eb32-41fc-a77a-235b1f06d14e">

**Comment by roiLeo** [comment]
Please provide a link so we can test it
