### ISSUE TITLE
Polkadot Js extension refusing to connect

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8175]
Some of the Artists that minted before used mobile with the Js extension actually. Kiwi Browser supports extension. One artist has an issue connecting to his Polkadotjs wallet. Video:

https://github.com/kodadot/nft-gallery/assets/104380776/7bd0ce82-1138-4f89-984a-d91e2dfeb983

**Comment by roiLeo** [comment]
![Screenshot_20231121-150541.png](https://github.com/kodadot/nft-gallery/assets/9987732/c7ccb69d-cc31-4909-9b68-43316116644b)

**Comment by JustLuuuu** [comment]
yeah same i didnt know about this. With kiwi browser its possible but I never used it before and I guess its not that known. I will ask him about the account. What do you mean by available?

**Comment by roiLeo** [comment]
> yeah same i didnt know about this. With kiwi browser its possible but I never used it before and I guess its not that known. I will ask him about the account. What do you mean by available?

When I check my Polkadot Extension on Kiwi Browser I can see my account, from the video it doesn't look like it has account

**Comment by JustLuuuu** [comment]
Closing this issue because the artist let us know that he can log in now. So probably it was some issue on his side.
