### ISSUE TITLE
Migration collection preview broken

### ISSUE THREAD

**Issue by damskyftw** [kodadot/nft-gallery#8189]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

<img width="1410" alt="image" src="https://github.com/kodadot/nft-gallery/assets/92786519/cfe66820-10a1-452e-9c7d-6160e946a19e">

### Please reproduce in steps

https://canary.kodadot.xyz/migrate

### Expected Behavior

/

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

canary.kodadot.xyz

### Are you logged in?

Yes

### At which chain did you encounter bug?

Kusama

### Screenshots

/

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by exezbcz** [comment]
- the migration card does not have a preview 

could you please provide a link for the collection that is displayed there?
