### ISSUE TITLE
copy link does not work on Android nova wallet

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/nft-gallery#8191]
I just found that on Android nova, the functionality of `copy link` does not work at all, while on IOS it works.

![image](https://github.com/kodadot/nft-gallery/assets/31397967/9d68a588-52f1-4f18-a7a0-380aceb328e4)

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/8188#issuecomment-1823016804_

**Comment by daiagi** [comment]
works for me btw, but doesn't for @prury 

looks like device / Android version dependent
