### ISSUE TITLE
Add migration to sidebar 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8196]
<img width="356" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/3033ec15-fdb8-402a-bd40-ef55105d9618">

- since migration is ready and close to being announced to public, we should add it to the sidebar 

The button will have a name "Migrate" 

more additions are coming, followup soon

**Comment by exezbcz** [comment]
cc @Jarsen136 could you pick up? 👀

**Comment by prury** [comment]
@exezbcz why not disabled and with coming soon text?

**Comment by exezbcz** [comment]
> @exezbcz why not disabled and with coming soon text?

Because it's ready

**Comment by prury** [comment]
> > @exezbcz why not disabled and with coming soon text?
> 
> Because it's ready

migration itself is, imho needs a lot more testing and some improvements before releasing it, see https://github.com/kodadot/nft-gallery/issues/7552#issuecomment-1824450795

waiting for your action part still needs to be written, right now is only showing item that we have from other collections

**Comment by exezbcz** [comment]
@prury ah okay, thanks for the insights. We can just not merge the pr if someone makes it

**Comment by prury** [comment]
> @prury ah okay, thanks for the insights. We can just not merge the pr if someone makes it

there is an open PR with it already, see link above
