### ISSUE TITLE
Migration UI - Collection was migrated by owner

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#8206]
I just realized this section cc @vikiival 
How do we get the status, once the owner of the collection is already migrated? For this UI:

<img width="512" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/59b9507c-f164-4d6b-b3e5-c5581d02bbe3">

**Comment by vikiival** [comment]
> How do we get the status, once the owner of the collection is already migrated? For this UI:

Hello, I updated the endpoint so you can get list of collection that you have at least one presignature

**Comment by preschian** [comment]
@vikiival Thank you Vik, I added the button checker here https://github.com/kodadot/nft-gallery/pull/8201/commits/0ab18e7c693e957fbf576ba01d1744d6e8b582f3. 

I have not tested this section until the congratulations page, I will test the functionality in a separate PR

**Comment by preschian** [comment]
@prury found another case that was not able migrate this collection https://canary.kodadot.xyz/rmrk/collection/7EA1DCF47E98A25067-NOT_SO_GRE
