### ISSUE TITLE
Drop has unsynced numbers of mints?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8207]
https://kodadot.xyz/ahp/drops/swirls

available 223 out of 256 

33 out of 256 minted

and bottom strip

42 is latest mint?

![image](https://github.com/kodadot/nft-gallery/assets/5887929/a6650daf-abee-4a90-a290-101132c7e05f)

**Comment by yangwao** [comment]
> I'm not able to mint it. is that expected?

regarding this, I think we don't have queue and we should have some sort of lazy mint and some collision or race condition is happening

**Comment by roiLeo** [comment]
> anyway, I'm not able to mint it. is that expected? I got `Each address can mint only once` 

<img width="582" alt="Capture d’écran 2023-11-23 à 1 06 15 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/5fb62b56-ce84-43ca-84c5-6b5c9dce9259">

**Comment by yangwao** [comment]
Capture should be async no?

**Comment by yangwao** [comment]
> Capture should be async no?

or it wasn't async 

https://github.com/kodadot/nft-gallery/pull/8208/files

**Comment by yangwao** [comment]
anyway, this is huge desync tbh 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/c276cee0-7ccf-4b51-a07d-dafaa193bc27)
