### ISSUE TITLE
Reward past contributions for translations

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#821]
We want to pay off work that has been contributed to the code.

Thus those who don't write explicitly, we will reward in future $KODA tokens.
Otherwise, we can reward your contribution right away in $KSM.

Please link up your PR with your KSM so I can process that.

For more info join Discord https://discord.gg/35hzy2dXXh

Time to close up this and reflect in $KODA will be in circa 6 months, may change depends on other stuff.

**Comment by ferhatsirin77** [comment]
FvXhLy1Zypp5BSx5Dr85QzEGd8VNSRxLhGBSN1ZeZtVg2xZ

**Comment by yangwao** [comment]
> FvXhLy1Zypp5BSx5Dr85QzEGd8VNSRxLhGBSN1ZeZtVg2xZ

Linking to it's PR https://github.com/kodadot/nft-gallery/pull/81
As @ferhatsirin77 has been a quite a long time around with helping Reddit,I'm sending $200 right away in KSM through https://nft.kodadot.xyz/transfer/?target=FvXhLy1Zypp5BSx5Dr85QzEGd8VNSRxLhGBSN1ZeZtVg2xZ
https://kusama.subscan.io/extrinsic/0xb779d1457d63e84705610f9e7dc0e7568cb760c41fbcf161b890509d534ea2f0

**Comment by ferhatsirin77** [comment]
Thank you for your generosity bro. Always happy to be with you in Kodadot project and make progress together! Peace out!

**Comment by yangwao** [comment]
Closing.

If you found this issue and want to become ambassador, feel free reach out 

https://docs.kodadot.xyz/ambassador-program/ambassador-intro#the-opportunity
