### ISSUE TITLE
Generate button styling 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8210]
<img width="255" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/cccc35a6-1d27-4cbd-bb18-b4f89a3e8de2">
yes

figma: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=394%3A6126&mode=design&t=l1TcJ28FYqEEyCTn-1

<img width="345" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/a229fed8-5004-493b-b924-058376d6e940">

**Comment by roiLeo** [comment]
take your pick https://fontawesome.com/search?o=r&c=spinners
