### ISSUE TITLE
Not able to mint on Assethubs or Kusama

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#8220]
CORS imagedelivery
preheat fails

![image](https://github.com/kodadot/nft-gallery/assets/36627808/e65fb201-c5b0-4319-b018-d8f6604016f4)

txs: (transactions are successful)

https://assethub-kusama.subscan.io/tx/0xb79140cec97adbcabee27ea0c04d3fa1c753f0b6f7d1f30cfaa40ac1d8a203df
https://assethub-kusama.subscan.io/tx/0x0f790ab00c32c002dc369b2f2851cd1adfd0d14f75ef95f02973901e8135e4f1

**Comment by prury** [comment]
@vikiival @preschian

**Comment by yangwao** [comment]
related, yet needs some tune 
- https://github.com/kodadot/nft-gallery/pull/8185

**Comment by preschian** [comment]
Interesting 🤔 no CORS error, and the preheat looks fine. But I can't find my NFT in the UI

![Screenshot 2023-11-24 055548](https://github.com/kodadot/nft-gallery/assets/734428/9c5b02f5-5180-43ad-8d80-c6449b90fefa)


https://assethub-kusama.subscan.io/block/0xecff797bd0d36d44b6cc23caf056333b0cd6cddb6b61962893b1fdc787375377?tab=extrinsic

**Comment by preschian** [comment]
Oh, I suspect that the indexer on the ahk was stuck. Because on ahp looks fine

- https://assethub-polkadot.subscan.io/block/0xaa704e32d42195762854f417ece970b1762b47eebe5488a8fe5aa4245b50fe44
- https://canary.kodadot.xyz/ahp/gallery/16-4

**Comment by prury** [comment]
> Oh, I suspect that the indexer on the ahk was stuck. Because on ahp looks fine
> 
>     * https://assethub-polkadot.subscan.io/block/0xaa704e32d42195762854f417ece970b1762b47eebe5488a8fe5aa4245b50fe44
> 
>     * https://canary.kodadot.xyz/ahp/gallery/16-4

the ones i minted earlier are still not showing

**Comment by preschian** [comment]
I put the issue here https://github.com/kodadot/stick/issues/153

**Comment by preschian** [comment]
closing this

- cors issue -> will return cors issue when uploading the same image twice. Because the image already exists in cf-images. Then, the preheat will hit `imagedelivery` domain
- stuck on indexer -> fixed it here https://github.com/kodadot/stick/issues/153 by Vik

**Comment by vikiival** [comment]
> cors issue -> will return cors issue when uploading the same image twice. Because the image already exists in cf-images. Then, the preheat will hit imagedelivery domain

Please log it somehwere so we are aware of this
