### ISSUE TITLE
Generative drop preview on cards 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8221]
I guess we have the same issue here. 

- https://github.com/kodadot/nft-gallery/issues/7844

I think Viki mentioned something with the screenshot worker, so not sure if it will be fixed once the main issue is solved 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/cd20492a-0a2a-4be5-a405-281a6994036a)

**Comment by helloitsdamsky** [comment]
This should be fixed asap, otherwise we can’t even show the activity / items page

**Comment by yangwao** [comment]
Which part doesn't work? That it shows fallback now? If so, that's bc capture service broke during mint and being restored today so until cache so should work properly

**Comment by exezbcz** [comment]
@yangwao it is issue from yesterday 

>so not sure if it will be fixed once the main issue is solved

**Comment by yangwao** [comment]
> it is issue from yesterday
> 
> >

technically it's still same tho
