### ISSUE TITLE
Migration UI kit to `tailwindcss`

### ISSUE THREAD

**Issue by shashkovdanil** [kodadot/nft-gallery#8222]
### Is your feature request related to a problem?

We migrated `NeoButton` component to tailwindcss. Next step is migration of other components from `libs/ui`

### Describe the solution you would like

List of components:

- [x] [CardArticle](https://github.com/kodadot/nft-gallery/issues/8223)
- [x] [MediaItem](https://github.com/kodadot/nft-gallery/issues/8232)
- [x] [NeoAutocomplete](https://github.com/kodadot/nft-gallery/issues/8335)
- [x] [NeoAvatar](https://github.com/kodadot/nft-gallery/issues/8337)
- [x] [NeoCarousel](https://github.com/kodadot/nft-gallery/issues/8339)
- [x] [NeoCheckbox](https://github.com/kodadot/nft-gallery/issues/8340)
- [x] [NeoCollapsible](https://github.com/kodadot/nft-gallery/issues/8342)
- [x] [NeoDatepicker](https://github.com/kodadot/nft-gallery/issues/8344)
- [x] [NeoDropdown](https://github.com/kodadot/nft-gallery/issues/8348)
- [x] [NeoIcon](https://github.com/kodadot/nft-gallery/issues/8349)
- [x] [NeoInput](https://github.com/kodadot/nft-gallery/issues/8352)
- [x] [NeoInputItems](https://github.com/kodadot/nft-gallery/issues/8354)
- [x] NeoLoading
- [x] [NeoMessage](https://github.com/kodadot/nft-gallery/pull/8509)
- [x] [NeoModal](https://github.com/kodadot/nft-gallery/pull/8473)
- [x] [NeoModalExtend](https://github.com/kodadot/nft-gallery/pull/8514)
- [x] [NeoModalHead](https://github.com/kodadot/nft-gallery/pull/8516)
- [x] [NeoNotification](https://github.com/kodadot/nft-gallery/pull/8517)
- [x] [NeoPagination](https://github.com/kodadot/nft-gallery/pull/8518)
- [x] [NeoRadio](https://github.com/kodadot/nft-gallery/pull/8543)
- [x] [NeoSecondaryButton](https://github.com/kodadot/nft-gallery/pull/8503)
- [x] [NeoSelect](https://github.com/kodadot/nft-gallery/pull/8502)
- [x] NeoSidebar
- [ ] [NeoSkeleton](https://github.com/kodadot/nft-gallery/pull/8541)
- [x] [NeoSlider](https://github.com/kodadot/nft-gallery/pull/8520)
- [x] [NeoSteps](https://github.com/kodadot/nft-gallery/pull/8524)
- [x] [NeoStickyModal](https://github.com/kodadot/nft-gallery/pull/8540)
- [x] NeoSwitch
- [x] [NeoTable](https://github.com/kodadot/nft-gallery/pull/8473)
- [x] [NeoTabs](https://github.com/kodadot/nft-gallery/pull/8523)
- [x] [NeoTooltip](https://github.com/kodadot/nft-gallery/pull/8521)
- [x] NeoUpload
- [x] TheImage

Since these components are used in many places, you should not rewrite them all in one PR, better 1 component 1 task. This task is something like Epic Task

### Describe alternatives you have considered

--

### Are there opened related issues?

https://github.com/kodadot/nft-gallery/issues/8113
https://github.com/kodadot/nft-gallery/issues/8071

**Comment by exezbcz** [comment]
I will make library in the handoff file with all the button components till end of week

**Comment by exezbcz** [comment]
## Update

components done, in the figma

there are also some changes 
- regular button now has a height of 40px instead of 36. Will work better as a touchpoint

The large button is on the other hand smaller - 52px instead of 56 

- newly added focus state on a recommendation from @shashkovdanil 

both light and dark mode

![image](https://github.com/kodadot/nft-gallery/assets/90852205/4bbef83f-36a9-461c-9eab-fd9cdcf020be)

**Comment by roiLeo** [comment]
https://github.com/kodadot/nft-gallery/blob/8a32d119cd7a18cd1f4b64b9e9c1c18480f6fd13/libs/ui/src/histoire.scss#L2
