### ISSUE TITLE
Swap Chain / collection in Minting? 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8227]
Hey @exezbcz, what do you think about this small change? I would swap these two options in the minting a Single NFT.

<img width="1425" alt="Screenshot 2023-11-23 at 23 26 36" src="https://github.com/kodadot/nft-gallery/assets/104380776/06339dbe-f52b-4575-b321-a3ccc5cc62c7">

I feel like selecting a chain is the first thing you do and then you should be choosing which collection. Not the otherwise. Let's start from bigger group (chain) and go to a smaller group (collection). 

It would feel more natural.

**Comment by exezbcz** [comment]
already mentioned here: 

- https://github.com/kodadot/nft-gallery/issues/7956

> reordered sections - Network put before collection selection; it did not make sense the other way around
