### ISSUE TITLE
Timed Score

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#825]
With the first version of #824 it was a good estimate to have at least some basic.
Next, we would like to give collectors a better idea of how fast artists' art is gonna sell out.

Reflect on-chain actions, like mean time between mint -> list, list -> buy/sale. 
Making an average on top of the collection and artist of all their mints can help us estimate a better overview of how fast they are sellout, if they, for example, do NFT drops on a frequent basis or how it's trending their crafts on sales.

**Comment by XyloDrone** [comment]
Hmm, maybe this is a number that can be on top of an artist profile? <---LMK and will add to design. 

Side note: I do feel like this might have some negative connotations(like competition)
