### ISSUE TITLE
Persist data from subquery

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#826]
**Is your feature request related to a problem? Please describe.**
There are some pages (like `/spotlight`) that could benefit from cached queries.

**Describe the solution you'd like**
There is something called [apollo3-cache-persist](https://www.npmjs.com/package/apollo3-cache-persist) which could be used for this

**Additional context**
Deliverables:
- [ ] implement
- [ ] chceck if it's working

**Comment by yangwao** [comment]
Link pls apollo3-cache-persist 👀

**Comment by yangwao** [comment]
Meanwhile we've solved with subsquid
