### ISSUE TITLE
Email signup modal for free drops 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8260]
Okay, here we go

Best would be to finish this first: 
- #8163 

Which goes after this: 
- https://github.com/kodadot/nft-gallery/pull/8124

![image](https://github.com/kodadot/nft-gallery/assets/90852205/526569f4-f82a-4bde-84fb-25f74435e56e)

# Design
figma: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1458%3A19091&mode=design&t=7Fm85PwD32HjEeNw-1
- quite simple 
- input
- cta - this one is greyed out till you input a valid email address, then it changes to the active button

I have also played with the button style a bit to make it pop, you know hihi 

Tried to replicate the button using code, and this is what I achieved to do

https://codepen.io/exezbcz/pen/dyaKxdb

It has only one line instead of the two with a gap and the text style is not correct, also the hover is not quite it. I would like to remove the "shine" once you hover over and just leave the button white

- the button animation is not obligatory

**Comment by yangwao** [comment]
having this before upcoming drop on this Wednesday (29/11) would be doable

**Comment by hassnian** [comment]
👋

**Comment by roiLeo** [comment]
missing explicit consent on UI

**Comment by exezbcz** [comment]
@roiLeo will add

**Comment by exezbcz** [comment]
@roiLeo updated 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/19b4fb86-e376-4910-89da-811008d330c9)

cc @hassnian
