### ISSUE TITLE
Dashboard to see KodaDot creators & collectors

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#827]
https://open.spotify.com/track/0PiKaKQ6gtovR4DtVg8aNn?si=d47e44c89d214082

Time to highlight and give back to believers of Kodadot. 
We will be preparing a dashboard, where will show only those who we're using KodaDot for minting artwork and buying through KodaDot.
There might be a token, coming.

For sales, transactions landed to our sustainability address
For Creators, @vikiival knows how to distinguish.

Literally could be done as a filter for the existing spotlight with a switch button I guess.

**Comment by vikiival** [comment]
> For sales, transactions landed to our sustainability address
You have to check if it landed because of IPFS support or sale

**Comment by JustLuuuu** [comment]
> There might be a token, coming.

@exezbcz, 2021
