### ISSUE TITLE
Unable to open any generative NFT Image

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8273]
I need to download high-quality Swirls images for the exhibition where we will be exhibiting them. I'm unable to "maximalize" the image. The option is missing:

<img width="1455" alt="Screenshot 2023-11-27 at 14 37 05" src="https://github.com/kodadot/nft-gallery/assets/104380776/fbd81eda-f295-4a45-8e63-fe73840786f8">

I'm only able to download 350kb versions.. which is not enough. they will look shitty on big screens.

<img width="252" alt="Screenshot 2023-11-27 at 14 38 21" src="https://github.com/kodadot/nft-gallery/assets/104380776/b7900b4b-c492-4fc4-888f-45f08c1014e2">

Please help. The deadline for files for the exhibition is tomorrow.

**Comment by roiLeo** [comment]
it's not really an image that's why it's generative

you can still link us which image you want in high quality and we can try to provide them for you.

**Comment by roiLeo** [comment]
Nevermind max size I can get for swirls original image is 370kb ☹️

**Comment by roiLeo** [comment]
> Here is example of HQ image (size 3.19 MB)

Nice! could you provide the others for @JustLuuuu ?

**Comment by roiLeo** [comment]
Hmmm... It's true that this gen Image depend on your screen resolution.

Maybe @JustLuuuu can provide the needed resolution for TV/exposition.

**Comment by JustLuuuu** [comment]
yeah it works!! Amazing thx for this ... 1,5mb when I downloaded the NFT, can I have a question, is that enough for  2160x2160px resolution TV?

**Comment by JustLuuuu** [comment]
> Yes, it should be enough, right now the images are downloaded at 2000x2000 resolution

you are the best 💥
