### ISSUE TITLE
Resize on mass list while entering fixed price

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8282]
https://github.com/kodadot/nft-gallery/assets/5887929/18a4bd85-e25f-4a1c-b8c7-978561563576

**Comment by exezbcz** [comment]
https://github.com/kodadot/nft-gallery/pull/8255

hm weird, thought it was fixed there

**Comment by Jarsen136** [comment]
> #8255
> 
> hm weird, thought it was fixed there

It did have been fixed in #8255
env: https://canary.kodadot.xyz/
