### ISSUE TITLE
NFT have serial number in their name when they shouldn't

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#8300]
for example
/ahk/gallery/268-7

minted with name "test"
shows with name "test #7"

![image](https://github.com/kodadot/nft-gallery/assets/22791238/c0a66f09-aef3-4a98-bcfa-d32b3dd7f7db)

**Comment by roiLeo** [comment]
link #8100 & #8105

**Comment by JustLuuuu** [comment]
yeah this artist experienced this in his collections: https://kodadot.xyz/ahk/u/Gy9MVKkraocbNfv7JBAK5eUk4cKFsSGFg5BLo5LEqjmzJEa?tab=collections

**Comment by vikiival** [comment]
Duplicate of #9169
