### ISSUE TITLE
Drop loading button

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8307]
New drop snowflake: https://kodadot.xyz/ahp/drops/snowflakes.

Loading screen looks boring, I thought we got stuck, can we make it more attractive? 

https://github.com/kodadot/nft-gallery/assets/104380776/488f70b6-61a1-4c1b-a982-32cd862e4514

Also not possible to close this popup:

https://github.com/kodadot/nft-gallery/assets/104380776/5f7b9dfc-b2b0-444d-b63f-e8d1d04a60bd

@Jarsen136 ? 🥹

**Comment by Jarsen136** [comment]
> New drop snowflake: https://kodadot.xyz/ahp/drops/snowflakes.
> 
> Loading screen looks boring, I thought we got stuck, can we make it more attractive?
> 

@exezbcz Do you have some UI idea about this status? This status is that it is generating/capturing nft picture.

<img width="442" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/da0fe6a6-e7c7-4bbd-b92f-210a2f4b0afa">

> Also not possible to close this popup:

will fix it

**Comment by Jarsen136** [comment]
> > @exezbcz Do you have some UI idea about this status? This status is that it is generating/capturing nft picture.
> 
> eh.
> 
> yeah, but its not done :D
> 
> * [Claim drop modals and flow  #8163](https://github.com/kodadot/nft-gallery/issues/8163)


I guess there is a hotfix. When clicking the mint button, we could display the modal immediately and increase the loading time to about 2 minutes. How about it? As you have mentioned in https://github.com/kodadot/nft-gallery/issues/8296

**Comment by exezbcz** [comment]
@Jarsen136 yes, agree
