### ISSUE TITLE
Add sorting by sale price on collection & profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#831]
Would be good to have sorted by price on top of 

- [x] profile
- [x] collection

That could also include having a filter to show only for sale NFTs, collectors unnecessary doesn't need to see ones which is not for sale.

Use switch [ ] - "**Buy Now**"

**Comment by yangwao** [comment]
Seems gallery getting upgrade soon 👀
![image](https://user-images.githubusercontent.com/5887929/135835895-66a7e0a4-fc14-4f16-b817-e3532532176b.png)

**Comment by yangwao** [comment]
@roiLeo What about having this one? 😇

**Comment by roiLeo** [comment]
closed in #890 & #875
