### ISSUE TITLE
Price worker doesn't work?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8311]
Can't use transfer bc of this. 

Seems out of all fallbacks this doesn't work? How we can improve so this doesn't happens again? 

cc @kodadot/internal-dev 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/1395892c-de07-41c3-856f-66c5aeffbf70)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/0c497fe1-8c13-4e23-a9de-47fb5bca200a)

on switching
![image](https://github.com/kodadot/nft-gallery/assets/5887929/b0acf46b-96c9-4da9-bf51-b5d3c793b234)

**Comment by preschian** [comment]
eh, checking
