### ISSUE TITLE
Implement error tracking on client

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#834]
We need rapidly start registering errors we might encounter to deliver better quality for our service
Feel free integrate something, we can then change keys or env once PR is made!:)

### Has free plans
- https://www.bugsnag.com/pricing -- used by Netlify afaik? (7.5k events/1seat)
  - https://www.bugsnag.com/platforms/vue-js 
- https://sentry.io/pricing/ 
  - https://sentry.io/for/vue/	

### Pricey tho
- https://logrocket.com/ - can record session to see how it happened 
- https://raygun.com/
- https://trackjs.com/pricing/

### Reading
- https://flatlogic.com/blog/10-best-error-monitoring-and-error-tracking-tools/

### Decision window
- probably something which discounts open source projects if possible 
- really fluffy pots of integration, like webhooks at least so we can have some sort of emergency channel if something something goes terrible wrong and cut down times on response 

add some others which we should have

**Comment by yangwao** [comment]
@roiLeo :P 

ref 
- #1200

**Comment by roiLeo** [comment]
It seems to me that it is possible to track (js/client) errors with google analitycs

**Comment by preschian** [comment]
do we still don't have a tracker on the client? https://sentry.io/welcome/ seems a good option

**Comment by yangwao** [comment]
made kodadot team and invited you 
https://docs.sentry.io/platforms/javascript/configuration/sampling/
