### ISSUE TITLE
Migration `NeoDatepicker` to `tailwindcss`

### ISSUE THREAD

**Issue by shashkovdanil** [kodadot/nft-gallery#8344]
### Is your feature request related to a problem?

Context is [here](https://github.com/kodadot/nft-gallery/issues/8222) 

### Describe the solution you would like

--

### Describe alternatives you have considered

--

### Are there opened related issues?

https://github.com/kodadot/nft-gallery/issues/8222

**Comment by roiLeo** [comment]
> @roiLeo help me please, what we can do with this component? It's not used anywhere in the project

I don't think we need to migrate this one
