### ISSUE TITLE
(Transfer) - show list of last 10/50/100 transactions from account

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#835]
In https://nft.kodadot.xyz/transfer would be great to show on the right list of the **10/50/100 last transaction from the account you are sending**

Could be an easy table, with to & amount

| to | amount |  
|--|--|
| FvXhLy1....Vg2xZ | 0.6 KSM |
| HS6QkRu....LE9QL | 0.0098 KSM |
| ... | ... KSM | 

Where on clicking on 
- [ ] address would prefill it to transfer to that address
- [ ] amount would prefill it to transfer with address and amount
 
I.e in my case [CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd](https://kusama.subscan.io/account/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd)
![image](https://user-images.githubusercontent.com/5887929/135852707-913a889c-7544-4274-8e6d-0c09ba399082.png)

Maybe later add time field? but not needed now.

@prachi00 maybe you want to have look at this?

Optionally use subscan API? best if not needed, but here your decision!

**Comment by JustLuuuu** [comment]
no priority at all - no needed, closing
