### ISSUE TITLE
Not loading NFTs in collection

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8358]
this NFTs from poap minter are not loading: https://kodadot.xyz/ahk/gallery/287-1

Poap minter: https://poap.kodadot.art/argentina

Ahk

Event is today and we need this to work. 

![image](https://github.com/kodadot/nft-gallery/assets/104380776/3efb60c7-99f4-4c96-adbc-8142397e0416)

This needs to be solved asap.

**Comment by roiLeo** [comment]
Loads for me, I just had to go to media
https://image.w.kodadot.xyz/ipfs/bafybeifjqsh5xthmtjb5dkun3xxezgc3xj7g6tcl3k3nlx2aqs4egolr6a/media.mp4
![Screenshot 2023-12-02 at 10-47-48 KodaChain Argentina #1](https://github.com/kodadot/nft-gallery/assets/9987732/2c0013de-4e7f-4e53-9415-8d093e701bc4)

**Comment by roiLeo** [comment]
<img width="1364" alt="Capture d’écran 2023-12-22 à 10 55 39 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/33acf65c-e1b9-4a50-9df9-9621eaab82df">
