### ISSUE TITLE
Toasts design

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8363]
Do we have a design for toasts? It seems like forgotten about them bit
cc @exezbcz 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/4c91928b-de1f-4860-b99a-15e091771e35)

**Comment by panda6151025** [comment]
👋

**Comment by hassnian** [comment]
@panda6151025 this issues is not ready to pick  , design request label has not been removed

![CleanShot 2024-05-13 at 09 21 39@2x](https://github.com/kodadot/nft-gallery/assets/44554284/a0c91776-eaf3-414a-ad6f-d84fbf99ac00)

**Comment by hassnian** [comment]
closed by #10096
