### ISSUE TITLE
mobile section headings 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8369]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/86ecd176-a29d-4f0b-9b8f-1673b4bdaec5)
![image](https://github.com/kodadot/nft-gallery/assets/90852205/10670d8c-f211-4e2a-a778-2371cf6ba258)

- should be heading 3 
- 31px size 

it should be applied from the same breakpoint the top part changes, I believe its 480px width

**Comment by roiLeo** [comment]
No more Spotlight
