### ISSUE TITLE
Royalties on Generative drops not working: Sha22

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8376]
This collection: https://kodadot.xyz/ahp/collection/38
Chain: AHP
Royalty account: https://www.subscan.io/account/1RWmphfVQAwfGAizAqy6ymaTvoc8rknHji6As1YxUWSGpta
They were supposed to get 20%

Problem
---
- There is already some trading volume, and they did not receive their royalties. 
- royalties are not showing on NFTs nor in the buying process

**Comment by roiLeo** [comment]
might help for debugging:
- https://assethub-polkadot.subscan.io/extrinsic/5078005-3

**Comment by daiagi** [comment]
what viki pointed out is likely the case
ask them to top up their AHP balance by at least 1 dot

**Comment by vikiival** [comment]
![Screenshot 2023-12-15 at 13 02 10](https://github.com/kodadot/nft-gallery/assets/22471030/6adaab76-3d21-493d-95dc-91594502d399)


Royalty is there, existential deposit was updated.

**Comment by JustLuuuu** [comment]
> Royalty is there, existential deposit was updated.
will they recieve previous royalties or should I reimburse them that amount?
