### ISSUE TITLE
Not able to buy an NFT: Weird Error message

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8377]
I tried to buy one NFT from this collection: https://kodadot.xyz/ahk/collection/223 specifically this NFT: https://kodadot.xyz/ahk/gallery/223-3

I have had enough of KSM, my account: CwaBDMrkTa5Yo9iWcqTGV7xU1GfSjTCbvPk2T4psxGLPrPJ. 

But I got this error:
<img width="1420" alt="Screenshot 2023-12-03 at 16 11 42" src="https://github.com/kodadot/nft-gallery/assets/104380776/11cc40a3-bf6c-4481-a509-4417e19d1056">

Right now, Im not a happy buyer. I tried to buy an NFt after a long time, and I got an error on my first item. 😭

**Comment by roiLeo** [comment]
could be related with #8511

**Comment by roiLeo** [comment]
Should be resolved now
