### ISSUE TITLE
Set collection max supply via separate call

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#8391]
### What happened?

@prury found out in - https://github.com/kodadot/nft-gallery/pull/8389

> @roiLeo made a collection with limited supply and it still shows unlimited:

> https://deploy-preview-8389--koda-canary.netlify.app/ahk/collection/289

This is caused by a bug in Polkadot SDK - https://github.com/paritytech/polkadot-sdk/issues/2293

and therefore we cannot pick it up in the indexer yet - https://github.com/kodadot/stick/issues/147

### Please reproduce in steps

1. Create a collection on ah*
2. Set max supply to any arbitrary number (1000)
3. UI will not pick the number

### Task

1. remove the max from `create()` call
2. if `max` is set append new call to the batch `api.tx.nfts.setCollectionMaxSupply(id, max)`
3. Enjoy

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
Meanwhile https://github.com/paritytech/polkadot-sdk/commit/1bdfb29587800a00aad62acb7222b77b6c2701e7

**Comment by vikiival** [comment]
@jsidorenko when can we expect release to ksm / dot?

**Comment by jsidorenko** [comment]
I have no idea.. usually, it takes 3 weeks to get released, although, for my last fix it took 6 months after I merged it to get onchain
