### ISSUE TITLE
Show royalties on collection

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#8396]
### Is your feature request related to a problem?

We have in KodaDot support for global collection royalty. This saves a lot of money when artist sets it in the Collection instead of NFT (`0.4` vs `n * 0.4`).

However this royalty is not visible on our UI.

### Describe the solution you would like

Similar to - #8389 

I would like to see royalty and recipient on the UI.
Royalty (denomintated in %) should be visible under the statistics `royalty ${royalty}%`
recipient should be under the creator - identicon should be visible.

### Describe alternatives you have considered

@exezbcz can guide better probably

**Comment by AshutoshSingh00001** [comment]
@vikiival I'm probably wrong but don't you think that setting royalty to each nft is inconvenient for artist like other blockchains they set royalty on collections

**Comment by JustLuuuu** [comment]
> oh it's just an on-chain attribute btw it might need to have destination address (other than collection owner)

yeah that is okay

**Comment by Jarsen136** [comment]
The `recipient` is invalid here 👀 

<img width="348" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/f688e350-b114-4403-bbf7-cbae10cbc477">

**Comment by vikiival** [comment]
> The recipient is invalid here 👀

Please open an issue in the stick repo 👍

**Comment by roiLeo** [comment]
> oh it's just an on-chain attribute

Can't we propose RFC like [ERC-2981](https://eips.ethereum.org/EIPS/eip-2981) on polkadot?
As external marketplace will be able to bypass this "royalty" system.

**Comment by roiLeo** [comment]
closed as completed
