### ISSUE TITLE
PRs not getting assigned properly to reviewers

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#8399]
sometimes only @yangwao gets assigned to review

![image](https://github.com/kodadot/nft-gallery/assets/36627808/e1dfc711-e75b-4404-8b15-e29595787d06)

before it was selecting people from code review group, now its selecting from internal dev

**Comment by roiLeo** [comment]
excepted behavior?
https://github.com/kodadot/nft-gallery/commit/d791e8c242e9c176adafe221ac678145e1f1d40d

**Comment by prury** [comment]
> excepted behavior? [d791e8c](https://github.com/kodadot/nft-gallery/commit/d791e8c242e9c176adafe221ac678145e1f1d40d)

but why some PRs gets only one person assigned

**Comment by roiLeo** [comment]
> but why some PRs gets only one person assigned

![steve-carrell-magic](https://github.com/kodadot/nft-gallery/assets/9987732/3e3f71c2-8fd0-4352-827c-223078eb3d01)

**Comment by prury** [comment]
@roiLeo was it solved? Because I'm manually setting reviewers for every PR

should viki and yangwao be requested for code review?
