### ISSUE TITLE
Loading modal slowness

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#8406]
if i wait for all my balances to load and then do any action, it loads again, what is it loading for? balances? collection floor? 

https://github.com/kodadot/nft-gallery/assets/36627808/e045c6a3-0d93-43f9-8f90-987dc6eef462

**Comment by prury** [comment]
Same with NFT creation, balances already says i have enough balance to mint, yet, it checks again for balance

**Comment by yangwao** [comment]
Sounds like same issue we have in transfer where it waits till it loads $ till I can use it

**Comment by hassnian** [comment]
> I think we have to change text color to black here
> 
> ![image](https://private-user-images.githubusercontent.com/19692986/288085491-4443565d-c761-4d1a-94b2-fc4b9e8162e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjIyMzUsIm5iZiI6MTcwMTkyMTkzNSwicGF0aCI6Ii8xOTY5Mjk4Ni8yODgwODU0OTEtNDQ0MzU2NWQtYzc2MS00ZDFhLTk0YjItZmM0YjllODE2MmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA0MDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNGY5MjlkYjI0NzVhM2ZmMDBlMTI5MzI0ZTI2ZjlmNWI2MGJiY2U4NDllZThhMDMzNDg0MTljNDc0MzE1OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-CiTukRNs7Ie-xUwbJTALaUVf2LCuYlvv_Oxuj0lKs)

fixed #8304

**Comment by hassnian** [comment]
👋
