### ISSUE TITLE
Footer replacement with beehiiv posts

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8423]
Substack publications are on hold, and we have this more actual 
https://kodadotweeklyroundup.beehiiv.com/

showing last three posts from our publications is fair

https://developers.beehiiv.com/docs/v2/ab0d2f8ee91c2-show

API stuff should be somewhere around 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/47157d58-a1c4-4a9f-a9e8-30509bc9d379)

replace with this

![image](https://github.com/kodadot/nft-gallery/assets/5887929/05a7ecf1-ad81-442b-8318-69020d8fc35c)

**Comment by exezbcz** [comment]
so the change would be to use the same cover img as on beehiiv. And from the bottom part, we will use only the heading.

**Comment by yangwao** [comment]
ready for take if someone want to help

**Comment by preschian** [comment]
Can someone send me the `publicationId` and `token` to my telegram? It seems like the API was not public. Or is there any public API?

- https://developers.beehiiv.com/docs/v2/84b282584290d-index
- https://support.beehiiv.com/hc/en-us/articles/13091918395799-Where-can-I-find-my-publication-ID-
