### ISSUE TITLE
Collection top part changes 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8433]
# Artist/creator
the first step of displaying artist's more 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/d66f91ba-be17-49c7-ba99-465f67737d2e)

When hovering over the black name, or address - it changes to the hover color and displays hover card 

its the same thing we have in every confirm modal

min and max-width here 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/6aa92597-69af-4a5b-be15-c169e29e2b5c)

updated in handoff small things 
https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1287-18959&mode=design&t=4aU3fi9XZLeGOpWb-11

# Stats 
plus, reordered the right column

![image](https://github.com/kodadot/nft-gallery/assets/90852205/b6f320c9-a75e-4896-b05b-2faa4b9973f6)

- changed font to 16px, bigger gaps 
- supply/listed row 
- network moved to the row under creator 

## Mobile
![image](https://github.com/kodadot/nft-gallery/assets/90852205/1c3db1fc-8ce2-449b-9e30-5af423a71a55)
- here as well

**Comment by roiLeo** [comment]
Hello, in this new design where would you put royalty percent & account? (#8396)

**Comment by exezbcz** [comment]
@roiLeo let me think, probably to the right columns, not sure if it fits well the artist place. 


will update hopefully soon

**Comment by exezbcz** [comment]
took some time, here is better version

**Comment by roiLeo** [comment]
Where to put royalty recipient address?

**Comment by exezbcz** [comment]
@roiLeo 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/487d4bf0-17d7-409d-9a73-8ffd6ce9e3ef)

it's not super important info, thus I put it into the tooltip

is there anything else I forgot to include and would be nice to have? 👀
