### ISSUE TITLE
Fullscreen show only a part of the image

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#8450]
it should show the full image, like it was before.

https://github.com/kodadot/nft-gallery/assets/36627808/ecbd01e6-4c76-433c-8643-1430d58d1a60

**Comment by roiLeo** [comment]
<img width="1329" alt="Capture d’écran 2023-12-26 à 8 00 02 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/118ab3c0-fe40-46e0-b7d9-2072e8e529c3">

closed by #8448
