### ISSUE TITLE
Visual gap in drops new claim drop modal flow

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8456]
> that 8 second delay can make meh impression tbh

https://github.com/kodadot/nft-gallery/assets/5887929/906f47d7-7912-4db7-bb95-319398613603

> atm it's a visual est, so it should wait  till what time ? 

> 0 seconds ?

_Originally posted by @hassnian in https://github.com/kodadot/nft-gallery/issues/8440#issuecomment-1845421709_

**Comment by hassnian** [comment]
👋
