### ISSUE TITLE
Upcoming drop: Wallstreet - change status

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8465]
This is the next upcoming drop - from what I heard, it's going to be out tomorrow. Can we change the status from **_Ended_** to **_Soon_** or something similar?

<img width="780" alt="Screenshot 2023-12-07 at 16 15 40" src="https://github.com/kodadot/nft-gallery/assets/104380776/efe2249e-9456-4745-a52f-60422096859f">

Check it here: https://kodadot.xyz/ahp/drops

**Comment by yangwao** [comment]
https://kodadot.xyz/ahp/drops/wallstreet
