### ISSUE TITLE
After buying NFTs, offer listing those NFTs 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8466]
It will help people to flip and trade NFTs much faster.

Now I need to go to the profile and select them one by one again.

cc @exezbcz 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/91442aa5-b790-4eda-889a-7ec89f84c8ff)

**Comment by exezbcz** [comment]
will look probably the same as new drop page claim, just needs some testing

**Comment by exezbcz** [comment]
done in 
- #8978
