### ISSUE TITLE
Art is not showing on AHK

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8471]
https://kodadot.xyz/ahk/gallery/302-8

![image](https://github.com/kodadot/nft-gallery/assets/5887929/19cc02e8-ff58-4bac-89cf-48286f79fd2c)

**Comment by JustLuuuu** [comment]
![Uploading Screenshot 2023-12-08 at 11.32.54.png…]()
works for me too

**Comment by yangwao** [comment]
maybe some cache ,wfm 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/b14ef36e-89df-4016-8467-f4337863f2b8)
