### ISSUE TITLE
Script or someone doing it manually? 

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#8488]
https://polkadot.subscan.io/account/13QmsdDF12nCCG5PuaXXDtTUqTwHkBLnXP8qwRzf2hxhFM1u?tab=transfer

if you follow the trail from this account, you could see that it has been transferring dot from one account to another in order to mint as many wall street nfts as possible

**Comment by yangwao** [comment]
airdrop farming is real bro 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/77c7fecf-038d-4a50-9f36-eab022b52053)

**Comment by yangwao** [comment]
Well, it would be on point to have some Sankey diagram for this, but let's see, it's good people have appetite to game it

**Comment by yangwao** [comment]
we will see here :D 
- #8495
