### ISSUE TITLE
remove Basilisk related code

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8490]
I think we will decide on a date, and we can drop a code related to BSX 

> PLUS there is BSX rpc error 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/4a58d409-4886-45b3-8116-e9fd2e04de82)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/8486#issuecomment-1847346309_

**Comment by prury** [comment]
let's do it! maybe some announcement on twitter in order for ppl solve their business there?

**Comment by JustLuuuu** [comment]
Didn't we want to give them a chance to migrate their collections?

**Comment by yangwao** [comment]
Let's remove the code regarding Basilisk
- https://github.com/search?q=repo%3Akodadot%2Fnft-gallery%20basilisk&type=code

**Comment by yangwao** [comment]
hey @kodadot/internal-dev we've got end-of-year cleaning of code base 😅 to hunt some performance. If anyone wants to take a bite. Probably could be done in more PRs so we don't turn of some of our major critical features.

🙏

**Comment by roiLeo** [comment]
tag new release before?

**Comment by vikiival** [comment]
> tag new release before?

For sure there will be release with tag before

**Comment by prury** [comment]
i would leave teleport and transfer enabled tho if you guys think it makes sense
