### ISSUE TITLE
HolderOf Motherboard drop 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8495]
For next week we will come up with another rule where people need to be holders of Motherboard collection to claim drop
- https://canary.kodadot.xyz/ahp/collection/50

![image](https://github.com/kodadot/nft-gallery/assets/5887929/0c58d9d1-59e3-4b6b-b6c5-281c69d90f8b)

- Let @exezbcz prepare the design and we can make it ready as a secondary drop for next week
- ~~Drop will be free~~, yet the required balance for this drop would be 2 DOT on Assets Hub to make it more **premium**
- @vikiival can drop a snippet if needed something on frontend (?)
- https://github.com/kodadot/nft-gallery/issues/8482

**Comment by vikiival** [comment]
> @vikiival can drop a snippet if needed something on frontend (?)

Yes all minting will be done on the frontend therefore:

1. You need to check if user has enough balance as @yangwao stated - 2 DOTs

2. Perform mint

```ts
const collectionId = '51' // this number will come from DB 
const item = '1' // you will need to listen to RPC node to get number of items so basically you will take items.
const { accountId } = useAuth()

const ownedItems = useQuery() // fetch sn of nfts from motherboard (it's collection 50)

const call = api.tx.nfts.mint(collectionId, item, accountId, { ownedItem: ownedItems.at(0).sn, mintPrice: null }
)

// submit tx :)
```

[to query number of items](https://polkadot.js.org/docs/api/start/api.query.subs/#subscriptions-with-params)

```ts
const sub = api.query.nfts.collection('50', subscriber)


const subscriber = (data) => console.log(data.items)

```

<img width="1637" alt="Screenshot 2023-12-11 at 16 10 55" src="https://github.com/kodadot/nft-gallery/assets/22471030/bd28784f-f3cc-44f5-b420-bc432e6d9202">


3. After tx is in block (2/3) you need to call waifu API (**BE AWARE THAT THIS IS NEW ROUTE**)


```ts

type UpdateRequest = {
  sn: number,
  hash: string,
  account: string 
}

export const updateWaifu = async (body: DoRequest, campaign: string) => {
  const value = await api<DoResponse>(`do/${campaign}`, {
    method: 'PUT',
    body,
  }).catch((error: FetchError) => {
    throw new Error(`[WAIFU::PUT::DO] Unable to CAMPAIGN for reasons ${error.data}`)
  })

  return value
}
```

> Drop will be free

@yangwao won't as the caller is responsible for deposit - 0.215 DOT .)

**Comment by yangwao** [comment]
> responsible for deposit - 0.215 DOT

ok, so **drop will cost 0.215DOT**

**Comment by vikiival** [comment]
> ok, so drop will cost 0.215DOT

Well it's refundable deposit ;D

**Comment by exezbcz** [comment]
design is in the original design 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/61882e68-f55a-4c4f-8bca-c53262f183e7)
https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=394-6126&mode=design&t=24r41xUB3tUOH8bw-11


will just make a confirmation modal so auto teleport can be enabled

**Comment by vikiival** [comment]
I made the test drop at https://kodadot.xyz/ahk/drops/flatwhite 
you need to have `ChaosFlake` (ahk/collection/290) to be able to mint .

cc @Jarsen136 can you please pick it up?

**Comment by vikiival** [comment]
> 1 Per Wallet

cc @exezbcz not true as you can mint as much nfs as you own in motherboard collection :)

**Comment by exezbcz** [comment]
> > 1 Per Wallet
> 
> cc @exezbcz not true as you can mint as much nfs as you own in motherboard collection :)

That is leftover from different design 

I will find the issue

**Comment by Jarsen136** [comment]
>I made the test drop at https://kodadot.xyz/ahk/drops/flatwhite
>you need to have ChaosFlake (ahk/collection/290) to be able to mint .
>cc @Jarsen136 can you please pick it up?

Ok. I will check it.

> > ok, so drop will cost 0.215DOT
> 
> Well it's refundable deposit ;D

What should we do to handle both the deposit and refund?   @vikiival

**Comment by vikiival** [comment]
> What should we do to handle both the deposit and refund

It is handled by chain.

- https://github.com/kodadot/nft-gallery/issues/8495#issuecomment-1850284559

Deposit is deducted automatically by chain.

and it is refunded once used removes the nft

**Comment by vikiival** [comment]
cc @Jarsen136 any help?

**Comment by Jarsen136** [comment]
> cc @Jarsen136 any help?

Yes, I need some help from you. I will raise a WIP PR and message you later.
