### ISSUE TITLE
Royalties are not paid on AssetHub

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#8511]
### What happened?

I wanted to test if royalties work on AssetHub.
Confirmation modal shows that I will pay 11.3 dot

<img width="414" alt="Screenshot 2023-12-10 at 13 34 23" src="https://github.com/kodadot/nft-gallery/assets/22471030/058b0e87-2824-404c-8af8-c9339a179fc8">

However when I check the transactions I will pay only: 10.3 DOT

![Screenshot 2023-12-10 at 13 35 53](https://github.com/kodadot/nft-gallery/assets/22471030/e8e0164d-54be-4f31-aa38-6e5ce0d5d7be)

### Please reproduce in steps

1. Open any NFT with royalty like: https://kodadot.xyz/ahp/collection/49
2. Buy It
3. No royalty is paid to the user.

### Expected Behavior

I expect that royalty is paid to the user.

### To implement
Example

https://kodadot.xyz/ahp/gallery/49-37

```ts
type Tip = {
  collection: string,
  item: string,
  receiver: string,
  amount: bigint | string
}

const tips: Tips[] = [
   {
      collection: "49",
      item: "37",
      receiver: "5FFG7GHAR2F2xCb5bqaLQrdgNGdtEL64tYgZimRBHDjuxVuA",
      amount: "10000000000"
    }
]

// TODO: check royalty validity
// If it is valid add to batch when user is paying
const call = api.tx.nfts.payTips(tips)

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
Preferably someone from @kodadot/internal-dev ?

**Comment by JustLuuuu** [comment]
- #8376

**Comment by roiLeo** [comment]
👋

**Comment by roiLeo** [comment]
we need to handle tips on indexer side

link https://github.com/paritytech/polkadot-sdk/blob/f6ae145813b2e213b39f09f713d3ccbdd9376f6b/substrate/frame/nfts/src/lib.rs#L1747

No need to add unecessary data
> ```ts
> type Tip = {
>   collection: string,
>   item: string,
>   receiver: string,
>   amount: bigint | string
> }
> 
> const tips: Tips[] = [
>    {
>       collection: "49",
>       item: "37",
>       receiver: "5FFG7GHAR2F2xCb5bqaLQrdgNGdtEL64tYgZimRBHDjuxVuA",
>       amount: "10000000000"
>     }
> ]
> 
> // TODO: check royalty validity
> // If it is valid add to batch when user is paying
> const call = api.tx.nfts.payTips(tips)
> ```

**Comment by vikiival** [comment]
> we need to handle tips on indexer side

Pay_tips is never called on KodaDot, see images above :)

**Comment by roiLeo** [comment]
> Pay_tips is never called on KodaDot, see images above :)

yup but that doesn't stop it from having it on indexer since user may be confused of losing found (in short we need to display it in activity)

**Comment by vikiival** [comment]
> yup but that doesn't stop it from having it on indexer since user may be confused of losing found (in short we need to display it in activity)

agree that's why you opened issue - https://github.com/kodadot/stick/issues/158

**Comment by daiagi** [comment]
why isn't this working?

https://github.com/kodadot/nft-gallery/commit/b6f31df20367df5ff8329fac9d044460b62d9361

**Comment by roiLeo** [comment]
> why isn't this working?

because royalties has been set at the collection level

**Comment by vikiival** [comment]
> because royalties has been set at the collection level

But still the data are replicated to nft entity. 

Maybe the reason is that i was trying to buy single nft instead of using shopping menu?

**Comment by JustLuuuu** [comment]
Tomorrow's drop is also supposed to have royalties. Will you be guys able to fix it before? ❤️

https://github.com/kodadot/ops-internal/issues/1140

**Comment by vikiival** [comment]
cc @daiagi can you please check ? 🥺 🙏

**Comment by daiagi** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/22791238/9ebec5e7-67dc-4f94-a985-9626724d9b95)


![image](https://github.com/kodadot/nft-gallery/assets/22791238/bd2f7357-54c7-4ec2-860e-551b5e3443d1)


https://assethub-polkadot.subscan.io/extrinsic/5225078-2


not seeing the problem

**Comment by JustLuuuu** [comment]
oh yes, it looks like royalties are in his account; he did not see them because Encrypt Wallet is not showing funds on Assethub. he already managed to teleport them. This issue is still on:

- #8376
