### ISSUE TITLE
Remove bulma flex helpers and change it with tailwindcss

### ISSUE THREAD

**Issue by shashkovdanil** [kodadot/nft-gallery#8556]
Context is here: https://github.com/kodadot/nft-gallery/discussions/8066

The first step of removing bulma from the project I'm going to do is to remove flex classes such as:

`is-flex`
`is-align-items-*`
`is-justify-content-*`
`is-flex-direction-*`
`is-flex-grow-*`

These are the least dangerous classes, which have an exact equivalent in tailwindcss

cc @roiLeo can I start doing this?

**Comment by roiLeo** [comment]
> cc @roiLeo can I start doing this?

let's go 🚀
