### ISSUE TITLE
Migration onboarding after opening sidebar 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8562]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/86a33837-5299-4e30-af6c-1079da06ac7a)
![image](https://github.com/kodadot/nft-gallery/assets/90852205/354faa8d-8fe6-4265-9d52-3dde30014346)

**Comment by prury** [comment]
duplicated #8474

**Comment by exezbcz** [comment]
@prury but you don't have meme there -_-


Yeah, continue there
