### ISSUE TITLE
Whirls preview not loading properly

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#8568]
@vikiival 
appears to be firefox only

https://github.com/kodadot/nft-gallery/assets/36627808/ed7a7b94-ae5e-4a9c-af1a-764acbadc3ae

**Comment by roiLeo** [comment]
p5.js throw issue, where can we find this sketch?

note that https://editor.p5js.org/sabhab1/sketches/gj396tEn4 doesn't work for me on firefox neither

**Comment by yangwao** [comment]
cc @JustLuuuu can you please test all art we have in pipeline on other browsers, thanks.

**Comment by vikiival** [comment]
Should be fixed now cc @prury

**Comment by JustLuuuu** [comment]
> cc @JustLuuuu can you please test all art we have in pipeline on other browsers, thanks.

Its already fixed by artist, there was a small issue that was fixed pretty quick once we notified artist. I dont use other browsers, not sure if Im the person for testing.

**Comment by prury** [comment]
> Should be fixed now cc @prury

![image](https://github.com/kodadot/nft-gallery/assets/36627808/64d165f3-8057-42f5-b70a-0c0f93de91f8)
