### ISSUE TITLE
Link whirls to landing

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8571]
Link this collection: https://kodadot.xyz/ahp/drops/whirls

Here on landing:
<img width="559" alt="Screenshot 2023-12-14 at 16 21 01" src="https://github.com/kodadot/nft-gallery/assets/104380776/3f0c5eef-60d2-42e2-b368-612fe99bf687">

**Comment by Jarsen136** [comment]
DONE
