### ISSUE TITLE
Token - belowMinimum Error

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#8587]
i am not sure if it is a bug or what's going on
@vikiival  ?

but now i am facing mysterious Token: Below Minimum error:

![image](https://github.com/kodadot/nft-gallery/assets/22791238/4f7073ed-d4c9-4e3e-a9be-3893ce845cf2)

https://assethub-polkadot.subscan.io/extrinsic/5229366-2

account has plenty of money to cover costs

https://www.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8

_Originally posted by @daiagi in https://github.com/kodadot/nft-gallery/issues/8582#issuecomment-1857223992_

**Comment by vikiival** [comment]
It's already tracked in
- #8512

https://assethub-polkadot.subscan.io/account/1L2xstToYKYE3m7R2qLM8MMpGQNmioSkMpx39QcxQucgnNZ
