### ISSUE TITLE
Drops: History

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8591]
Consider adding a tab for the **History of Drops** or **Dops that ended**. 

Every time we finish dropping and we delete the drop page from Drops, the page looks like this: .. bit empty.. not very exciting.
<img width="1282" alt="Screenshot 2023-12-15 at 12 55 55" src="https://github.com/kodadot/nft-gallery/assets/104380776/c9d9732e-3c9b-4b8b-b463-1be61537cac4">

I think each drop is our big achievement - they are popular and cool, and each drop, is our success. Even after minting out, still enables people to play with it. They can still play with the generator, which is cool. Since we dont have that many drops it would be very nice to be able to check the history of drops. At least people can play with the code and generator.

**My idea would be either:**
1.  leave **Ended** drops in the Drop page, and later if there are too many of them, add just filter or something like that so people can see active drops (or showing new drops on the top of the page always). This point is simple but it would need to come up with new status for Drops that are Upcoming because now upcoming Drops that are not yet open are marked as "Ended". 
2.  Create some new tab/viewer/ new design/ some viewer - this would need much more work and probably new design.

Im opening this issue so we can brainstorm ideas, maybe it will be easier once we implement "calendar" feature. But still worth of chat.

**Comment by exezbcz** [comment]
continue to
- #9329
