### ISSUE TITLE
Person unable to mint last drop

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8605]
An artist who created last drop is not able to mint the last drop. He has already collected from motherboard and he has enough dot in his wallet. Bought his motherload NFT 20 min ago. 

Address: 5DniiTqqM84wbQkZLMTgkZd2wLHXSr8ZsPZeji7DgpBKomLW

Error message: 
![image](https://github.com/kodadot/nft-gallery/assets/104380776/779d8a67-5814-4fa9-95e4-d0ac8f3d7afd)

**Comment by yangwao** [comment]
Seems same
- #8611
