### ISSUE TITLE
Identical NFTs in Chroma drop

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8607]
Atimtay (artist behind this drop noticed this)

Chroma drop, some NFts have the same identitucal pictures. This should not happen.

![image](https://github.com/kodadot/nft-gallery/assets/104380776/3aabc4a9-b81e-4b7f-9827-cb90dd4555ac)

these 2 pieces are identical - that they both have the same hash, isn't the hash passed from the transaction hash after the purchase is completed? Does polkadot chain produces same ophash for different transactions?

this single line of not symmetric triangles are supposed to be rare

**Comment by yangwao** [comment]
- https://canary.kodadot.xyz/ahp/gallery/51-78
- https://canary.kodadot.xyz/ahp/gallery/51-71

Interesting, though we already mitigated this

**Comment by vikiival** [comment]
Broken preview:
- https://canary.kodadot.xyz/ahp/gallery/51-86
- https://canary.kodadot.xyz/ahp/gallery/51-84
- https://canary.kodadot.xyz/ahp/gallery/51-83
- https://canary.kodadot.xyz/ahp/gallery/51-80
- https://canary.kodadot.xyz/ahp/gallery/51-75
- https://canary.kodadot.xyz/ahp/gallery/51-46

**Comment by JustLuuuu** [comment]
**Same**:
https://kodadot.xyz/ahp/gallery/51-34
https://kodadot.xyz/ahp/gallery/51-40

**Comment by JustLuuuu** [comment]
- https://kodadot.xyz/ahp/gallery/51-93
- https://kodadot.xyz/ahp/gallery/51-92

**Comment by JustLuuuu** [comment]
- Should be solved via https://github.com/kodadot/nft-gallery/pull/9516
