### ISSUE TITLE
Set royalties on Chrome collection

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8608]
This collection: https://kodadot.xyz/ahp/collection/51
 - we agreed on 15% royalties with Atimtay.
 - I don't see royalties in properties

**Comment by Jarsen136** [comment]
<img width="1061" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/6845e098-c042-4d3d-9d33-874361fd5ffc">

Here is it @JustLuuuu
