### ISSUE TITLE
HolderOf mobile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8609]
Mobile?

![Screenshot_20231215_145010_Chrome.jpg](https://github.com/kodadot/nft-gallery/assets/5887929/da0296b3-1984-46c4-be40-31bfd6bc23b8)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/pull/8569#issuecomment-1857915623_

**Comment by JustLuuuu** [comment]
- #8606

**Comment by exezbcz** [comment]
best would be to stack on top 

- cta button on the bottom 

from top to bottom
- holder of
- required funds 
- cta button
