### ISSUE TITLE
Wrong drop required balance - should be 2 DOT 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8618]
I sense it was broken in some merge conflict resolution set required balance to 200 DOT, should be 2 DOT

https://canary.kodadot.xyz/ahp/drops/chroma

![image](https://github.com/kodadot/nft-gallery/assets/5887929/1a8e956a-3505-40bf-9f4a-5adc17745f2e)

this is good 

https://beta.kodadot.xyz/ahp/drops/chroma

![image](https://github.com/kodadot/nft-gallery/assets/5887929/3016e063-fa47-4daa-9541-2a82b0bffbbf)

**Comment by vikiival** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/22471030/162ed60b-482a-4f0c-b5c9-293596ed5815)

![image](https://github.com/kodadot/nft-gallery/assets/22471030/2ccb77b1-1b6e-408d-9e0f-c8c2877aa04c)
