### ISSUE TITLE
[DOCS] Different minted nft as I've generated

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8623]
What I've seen on drop page ( no error in console ) 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/b636cdc8-eefe-4ac5-9622-70c6afdd6465)

what I get

![image](https://github.com/kodadot/nft-gallery/assets/5887929/ad4bd4f6-d007-41bb-8191-cf5137dc22b7)

ok after refresh

![image](https://github.com/kodadot/nft-gallery/assets/5887929/f1de64cf-71b2-4528-b496-a0b544853c4c)

any explainer?

**Comment by Jarsen136** [comment]
> any explainer?

It's expected but we could show some toast to inform users.

<img width="362" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/95aedd77-4b9c-4405-9dcf-9d4a397ed5fc">

**Comment by yangwao** [comment]
> show some toast to inform users.

Please refresh in 20 seconds, setting the metadata.

**Comment by Jarsen136** [comment]
> > show some toast to inform users.
> 
> Please refresh in 20 seconds, setting the metadata.

I'm not sure if it's possible 
cc @vikiival

**Comment by vikiival** [comment]
It still same same as free drop, it is minted in batches every minute.

**Comment by JustLuuuu** [comment]
> So TL;DR:
> 
> At this current rate we have ~40 tx/min (this will be fixed once we do smarter way of doing txs).
> 
> At this point It would be nice to have page about drops on hello and explain that it takes a bit time for KodaBot to update metadata.
> 
> cc @JustLuuuu

Open an issue in ops internal with all info you want me to include. Do you want separate page or should I include this to drop pages? But still I think not many people read hello page before drop :D

**Comment by vikiival** [comment]
Continue in - https://github.com/kodadot/ops-internal/issues/1335
