### ISSUE TITLE
Not able to buy nft 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8630]
even though there are error codes, I don't really understand why the transaction does not go through 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/4008eb7e-60c0-4464-b378-39f39c79f809)
I am trying to buy this nft: https://canary.kodadot.xyz/ahp/gallery/52-385

from this account: 1cQB9WUTtwyH3H4Ksn7pLfJvMLCxtzQHbUNhZtVBasoX3X9

![image](https://github.com/kodadot/nft-gallery/assets/90852205/9fc8dd87-2ce7-4bfb-9d7b-09ac9adf2792)

What is the issue here?

**Comment by daiagi** [comment]
#8587 
Royalty recipient address have balance less then ED


should be fixed by #8512

**Comment by exezbcz** [comment]
leaving this open as i cannot buy single nft from the first row 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/77339395-2bc9-4e19-b892-9dd12d989f9c)

**Comment by yangwao** [comment]
solved meanwhile I guess
