### ISSUE TITLE
Bit confusing if scrolled down

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8642]
Can we change that scroll-up arrow... bigger? 

I was looking where is that low floor, until I noticed that there are **[items]** I did not realized I'm on bottom 😅

![image](https://github.com/kodadot/nft-gallery/assets/5887929/8efaef3e-faba-41cf-a2de-681e3ea5211f)

**Comment by exezbcz** [comment]
> Can we change that scroll-up arrow... bigger?

it's not even there in the picture, is it?

**Comment by roiLeo** [comment]
link duplicate #7445

**Comment by yangwao** [comment]
> it's not even there in the picture, is it?

You people wouldn't believe what I've seen

![Screenshot_20231218_082607_Chrome.jpg](https://github.com/kodadot/nft-gallery/assets/5887929/8f271f9f-d2d9-443e-a286-e77666bed83a)

**Comment by exezbcz** [comment]
> > it's not even there in the picture, is it?
> 
> You people wouldn't believe what I've seen
> 
> ![Screenshot_20231218_082607_Chrome.jpg](https://github.com/kodadot/nft-gallery/assets/5887929/8f271f9f-d2d9-443e-a286-e77666bed83a)
> 
> 

You won't believe it was already seen 
> link duplicate #7445

**Comment by exezbcz** [comment]
so what is needed to be done? can you please rephrase the requirements please @yangwao

**Comment by exezbcz** [comment]
reopen if still issue
