### ISSUE TITLE
Unable to buy Whirls due royalties?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8644]
Unable to buy Whirls. I would not introduce royalties for upcoming drops until it is working flawlesly

![image](https://github.com/kodadot/nft-gallery/assets/5887929/23e14ed2-2c4d-4c57-b13e-d70fdb34adb8)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/0c36335e-1ba8-4938-b6ba-829448b01ad8)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/79f9fd67-1200-487b-8fb4-c75f02a06284)

**Comment by yangwao** [comment]
Same
- #8630

**Comment by exezbcz** [comment]
hotfix to send ed to the wallet?

**Comment by yangwao** [comment]
> hotfix to send ed to the wallet?

I guess so lol but if artist "accidentally" send its away, it shutdowns trading again 😄

**Comment by exezbcz** [comment]
@yangwao https://statemint.subscan.io/extrinsic/0x79387d2e75b9cf6e202e48e84e6f3522e703fc3f58a7b0c79f5d7134ea1b1be6


now we can sweep

**Comment by exezbcz** [comment]
> I guess so lol but if artist "accidentally" send its away

he wont
<img src="https://media4.giphy.com/media/3orieNJOuPUOI6tyBa/giphy.gif"/>
