### ISSUE TITLE
Buy now filter at profile 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8657]
If it's disabled, should it show only unlisted items? and when enabled only listed items? Or maybe rethink filters?

https://github.com/kodadot/nft-gallery/assets/5887929/b2368846-4c22-4b3d-9869-f522c8ac7a6e

**Comment by exezbcz** [comment]
> should it show only unlisted items

nope, "not listed" filter would have to be active

**Comment by roiLeo** [comment]
not planned, normal behavior
