### ISSUE TITLE
spotlight curated?

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8670]
In case you want to have spotlighted our collections, we can open an issue for it, guys can do it pretty quickly. Just prepare a list of collections you like. Or maybe they will be able to put only KodaDot Minter collections there.

_Originally posted by @JustLuuuu in https://github.com/kodadot/nft-gallery/issues/8663#issuecomment-1862601574_
            

lets list some collection then or?

**Comment by JustLuuuu** [comment]
@kodadot/internal-dev - can we for a spotlight select collections from one artist? https://kodadot.xyz/ahp/u/15CoYMEnJhhWHvdEPXDuTBnZKXwrJzMQdcMwcHGsVx5kXYvW
That Spotlight will be automaticlly showing only collections from KodaDot Minter - each time we do a drop it will automatically be spotlighted.

If no then I would go for:
- https://kodadot.xyz/ahp/collection/38
- https://kodadot.xyz/ahp/gallery/40-1
- https://kodadot.xyz/ahp/collection/46
- https://kodadot.xyz/ahp/collection/49
- https://kodadot.xyz/ahp/collection/50
- https://kodadot.xyz/ahp/collection/51
- https://kodadot.xyz/ahp/collection/52

**Comment by roiLeo** [comment]
here is the full list:
https://github.com/kodadot/nft-gallery/blob/a3bd8ab4783130b66d6387ac11e328a16bd587a3/components/carousel/utils/useCarouselSpotlight.ts#L6-L48

> **Option 1:** @kodadot/internal-dev - can we for a spotlight select collections from one artist? This [profile](https://kodadot.xyz/ahp/u/15CoYMEnJhhWHvdEPXDuTBnZKXwrJzMQdcMwcHGsVx5kXYvW) - KodaDot Minter. That Spotlight will automatically show only collections from KodaDot Minter - each time we do a drop, it will automatically be spotlighted.

not implemented yet

> **Option 2:** If not then I would manually set these as spotlighted. We will have to add new ones manually. From oldest to newest:

please provide only collection link
