### ISSUE TITLE
Person not able to mint

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8673]
Address: 5DwFrJRZEcDEomoNb8ahrZ31se1iceCvd48w6VvKy8BEkPyH
Cannot mint Chroma NFT because he apparently bought NFT used before. 

Can we pls send him an NFT from this collection? @vikiival. 

I am aware of this issue but not sure what will be the solution and when it will be available

Contact: Discord: cyphertux.eth
 
https://github.com/kodadot/nft-gallery/assets/104380776/d6cfd90a-b319-4267-82ac-1475ad992751

**Comment by yangwao** [comment]
will be solved in 
- https://github.com/kodadot/nft-gallery/pull/8656

**Comment by daiagi** [comment]
solved?

**Comment by vikiival** [comment]
> Can we pls send him an NFT from this collection? @vikiival.

Please do a followup issue in the ops repo

**Comment by JustLuuuu** [comment]
opened an issue to drop them NFt in ops, Im closing this one since it was solved
