### ISSUE TITLE
Landing top collection floor is wrong?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8675]
Seems when I open collection there are different numbers than on landing? 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/f3870d9d-bafd-4a8f-99b7-5f520099ffcd)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/1fe97c85-e1fb-460d-8612-0b800da4fd01)

**Comment by roiLeo** [comment]
kodadot/stick#142

**Comment by yangwao** [comment]
looks closed?

**Comment by roiLeo** [comment]
related with #8839
