### ISSUE TITLE
Chroma Lattice event

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#8677]
`/ahp/gallery/51-120`

https://beta.kodadot.xyz/ahp/gallery/51-120

=> mint
=> burn
=> mint again new

is it allowed?

**Comment by yangwao** [comment]
technically yes, I don't see issue :D ethically doesn't look best

**Comment by roiLeo** [comment]
> technically yes, I don't see issue :D ethically doesn't look best maybe if people want to burn and get new variation because today is different weather

won't fix then

![0gkhf1mi37541](https://github.com/kodadot/nft-gallery/assets/9987732/19c6cb25-899f-4823-b27f-fc3d99eb870c)
