### ISSUE TITLE
Signing transactions automatic 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8686]
IMO you should not click the button on the bottom every time you complete a step and want to continue 
- transactions should popup automatically, as they do when buying nft and using autoteleport 
- make the transactions popup automatically after the preceding is completed

**Comment by exezbcz** [comment]
hmm it appears that here its automatic and next step is started once the last one is finished 

https://github.com/kodadot/nft-gallery/pull/8437#issuecomment-1847117717

maybe @prury knows? 👀

**Comment by prury** [comment]
> hmm it appears that here its automatic and next step is started once the last one is finished 
> 
> https://github.com/kodadot/nft-gallery/pull/8437#issuecomment-1847117717
> 
> maybe @prury knows? 👀 

Yes, on that PR i only click the button once and wait for transaction signing pop ups to appear
