### ISSUE TITLE
Can't retry migration signing if cancelled

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#8700]
If i cancel the first transaction, i have to refresh the page to retry and loader state stays the same:

https://github.com/kodadot/nft-gallery/assets/36627808/6b247fd0-33cd-48d4-9029-eed39c6eebfd

**Comment by preschian** [comment]
@kodadot/internal-dev Hi, in that video, `prury` cancelled the talisman popup. Is there a way to capture that state? I only get the same status with `Unknown`. Would be good if I can get other than `Unknown` https://github.com/kodadot/nft-gallery/blob/0e16eb15a72909df15b5671d1803acf7a5839fda/composables/useTransactionStatus.ts#L9

At the moment, I added a "try again" button when the `tx` threw an error https://github.com/kodadot/nft-gallery/pull/9139

**Comment by vikiival** [comment]
We can extend with cancelled, the signer returns that as far as i know

**Comment by preschian** [comment]
> We can extend with cancelled, the signer returns that as far as i know

can anyone show me the code example? or help me to extend `useTransactionStatus` and add `cancelled` status?

**Comment by vikiival** [comment]
> can anyone show me the code example? or help me to extend `useTransactionStatus` and add `cancelled` status?

`useMetaTransaction` line 74 

```ts
const isCancelled = e.message === 'Cancelled'
```

most probably you would have to extend `useTransactionStatus` to give you optimal response

**Comment by prury** [comment]
Tried again on canary, 15m after PR got into prod and problem persists

**Comment by preschian** [comment]
> > can anyone show me the code example? or help me to extend `useTransactionStatus` and add `cancelled` status?
> 
> `useMetaTransaction` line 74
> 
> ```ts
> const isCancelled = e.message === 'Cancelled'
> ```
> 
> most probably you would have to extend `useTransactionStatus` to give you optimal response

thank you 🙏



> Tried again on canary, 15m after PR got into prod and problem persists

sorry, for `cancelled` action I just added here https://github.com/kodadot/nft-gallery/pull/9302
