### ISSUE TITLE
burn doesn't work for ahk?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8704]
I clicked [BURN]

first go warning Websocket disconnected and now this 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/882b5bf5-fa05-4460-92ea-939930c64beb)

**Comment by roiLeo** [comment]
parity asset-hub endpoint is off

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-asset-hub-rpc.polkadot.io#/explorer
