### ISSUE TITLE
parity asset-hub endpoint is off

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#8705]
parity asset-hub endpoint is off

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-asset-hub-rpc.polkadot.io#/explorer

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/issues/8704#issuecomment-1865944001_
            

## What to do

Use alternative endpoint on error, same as transfer
- on list
- on buy
- on burn 
- on check drop eligibility

**Comment by yangwao** [comment]
related I guess? 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/3cdc03a8-dfd3-4594-81b8-532d3b6916a5)

**Comment by roiLeo** [comment]
yes

**Comment by yangwao** [comment]
we should use priority for these two
![image](https://github.com/kodadot/nft-gallery/assets/5887929/b9d344ad-94a8-4d66-a784-e955438934f7)

**Comment by roiLeo** [comment]
https://github.com/kodadot/nft-gallery/blob/main/libs/static/src/endpoints.ts
