### ISSUE TITLE
preview after NFT christmas city drop mint is stuck

### ISSUE THREAD

**Issue by damskyftw** [kodadot/nft-gallery#8710]
<img width="1487" alt="image" src="https://github.com/kodadot/nft-gallery/assets/92786519/4c1b03a8-aa56-45e0-9f9e-30fd99ca792c">

**Comment by roiLeo** [comment]
- related with kodadot/workers#232?

**Comment by damskyftw** [comment]
Also, we can just skip the preview ^^

**Comment by yangwao** [comment]
seems previews are working already in collection
 https://canary.kodadot.xyz/ahp/collection/60

**Comment by exezbcz** [comment]
fixed and related to the capture service, reopen for next drop :D
