### ISSUE TITLE
og image for drop page has blue pictures 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8712]
<img width="431" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/59941ec0-b782-452f-a707-3310edfa9a26">
tried refreshing the preview using preview bot on telegram, but its not the case

**Comment by roiLeo** [comment]
<img width="413" alt="Capture d’écran 2023-12-21 à 2 43 00 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/afff40cf-4279-4666-a611-dab8e0f1a50f">
<img width="413" alt="Capture d’écran 2023-12-21 à 2 43 16 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/565d0ffe-4548-4d0a-bdc1-f8f3dbb463e0">

**Comment by exezbcz** [comment]
@roiLeo yup, good its correct for collection

**Comment by roiLeo** [comment]
<img width="413" alt="Capture d’écran 2023-12-21 à 2 49 23 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/4936d2b8-a4aa-4221-96f6-6617f92bb4e4">

**Comment by roiLeo** [comment]
am I color blind?

**Comment by exezbcz** [comment]
@roiLeo 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/c455e3f2-6f9e-4c9a-ae31-9d66d53e6b14)

does not look like it, I was not sure one of the posted imgs is for ahk/drops/christmascity
