### ISSUE TITLE
Link Series to homepage

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#872]
As it's sort of our **premium** feature right now, we should not miss it out on homepage 
![image](https://user-images.githubusercontent.com/5887929/136800273-614be95e-f6ec-451c-8dd1-d7451e8f981a.png)

**Comment by hisergiorojas** [comment]
I would like to work on this issue.

**Comment by hisergiorojas** [comment]
Where should the Series be in the list of premium features?
