### ISSUE TITLE
Gas fees Was deducted but my fund was not transferred

### ISSUE THREAD

**Issue by vackss73** [kodadot/nft-gallery#8733]
My address - 12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn

I was doing a transfer from my PolkaDot asset hub to native Polka Dot but the fee got deducted every time and the funds were not transferred I did it like 10 times but its still the same

**Comment by roiLeo** [comment]
- https://polkadot.subscan.io/account/12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn
- https://assethub-polkadot.subscan.io/account/12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn

Did you try to transfer less than 1 DOT?

<img width="322" alt="Capture d’écran 2023-12-22 à 10 23 17 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/bf1d8e0a-ee4c-4d84-8d5c-e8e645acf4c6">

- https://hello.kodadot.xyz/multi-chain/existential-deposit

**Comment by vackss73** [comment]
I am transferring 1.85 dot

**Comment by prury** [comment]
@roiLeo 
seems that transactions are going to the chain but xcm is failing
![image](https://github.com/kodadot/nft-gallery/assets/36627808/38681634-94f2-4828-9f12-9820c0cc742c)

**Comment by vackss73** [comment]
So what should I do?

**Comment by vikiival** [comment]
Cc @dudo50

**Comment by dudo50** [comment]
@vackss73 could you please provide more details?

Failed transact asset is usually error with insufficient balance.

Did you use max transfer feature?

**Comment by dudo50** [comment]
@vikiival, I was able to replicate issue when using max transfer feature.
<img width="676" alt="Screenshot 2023-12-22 at 19 53 57" src="https://github.com/kodadot/nft-gallery/assets/55763425/ce40aa5d-cbe9-4cb7-be6d-3172273c4843">

I have suggested in another issue, that this is fee related as I am able to send assets if I manually input 1DOT for example.
https://github.com/kodadot/nft-gallery/issues/8614#issuecomment-1858987480

@roiLeo, @hassnian  - My suggestion is to bump up fees further by 0.005 to 0.015 from previous 0.01 on Polkadot (2-3cents more approx). Kusama seems to work fine so it does not require any bumps. Fees may have changed with recent demand for DOT Ordinals and Polkadot being pushed in terms of TXs per Block.

**Comment by dudo50** [comment]
@vikiival , I was able to replicate error, that @vackss73 got. Unfortunately only on Polkadot. AssetHubPolkadot works just fine for me when I use max transfer option.

Indeed @hassnian pointed out correctly, Polkadot now won't let you do XCM transactions that would slash your account. 
(So if you have 1.85 Dot on Polkadot, you can transfer about 0.7 DOT)

However, slashing and max transfers work just fine for me in AssetHubPolkadot (Through KodaDot UI).
<img width="483" alt="Screenshot 2023-12-22 at 21 09 27" src="https://github.com/kodadot/nft-gallery/assets/55763425/3e8fd161-2f23-401f-b7d5-43d1b560a473">


<img width="751" alt="Screenshot 2023-12-22 at 21 12 16" src="https://github.com/kodadot/nft-gallery/assets/55763425/c798182f-b334-440f-80e2-809ff3f32d16">

Transaction ID:
0x54d133b31c92b5204f9b36b2849495a965e3baaf29c18356e96f37d62baddf0a 

<img width="444" alt="Screenshot 2023-12-22 at 21 12 54" src="https://github.com/kodadot/nft-gallery/assets/55763425/c738a71e-939f-4069-894e-eb2456e3f2a4">

**Comment by vikiival** [comment]
Thank you very much!

**Comment by vackss73** [comment]
> @vackss73 could you please provide more details?
> 
> Failed transact asset is usually error with insufficient balance.
> 
> Did you use max transfer feature?

I am transferring 1.82 dot balance is 1.84 everytime fee gets deducted but txn didn't happn

**Comment by dudo50** [comment]
> > @vackss73 could you please provide more details?
> > 
> > Failed transact asset is usually error with insufficient balance.
> > 
> > Did you use max transfer feature?
> 
> I am transferring 1.82 dot balance is 1.84 everytime fee gets deducted but txn didn't happn

Could you try to transfer 1.5 dot first? So we can see if it is fee related or problem is somewhere else. This should leave enough tokens on asset hub for you to not get your account slashed and not loose any tokens.

**Comment by vackss73** [comment]
> > > @vackss73 could you please provide more details?
> > > 
> > > Failed transact asset is usually error with insufficient balance.
> > > 
> > > Did you use max transfer feature?
> > 
> > I am transferring 1.82 dot balance is 1.84 everytime fee gets deducted but txn didn't happn
> 
> Could you try to transfer 1.5 dot first? So we can see if it is fee related or problem is somewhere else. This should leave enough tokens on asset hub for you to not get your account slashed and not loose any tokens.

Yeah it was successful what was the issue and wht about rest balance???

**Comment by dudo50** [comment]
> t was successful what was the issue and wht about rest balance???

Once fees are bumped a little you should be able to transfer the rest. I will notify the team to make this change ASAP.

@vikiival, please notify the team to try this fix: https://github.com/kodadot/nft-gallery/issues/8733#issuecomment-1868040760 mentioned in the lower part of the comment.

As suspected, SDK works as expected. Issue is fee related.

**Comment by vikiival** [comment]
> Is there any compensation for me I wasted my time and also fees for this bug.

Yes please follow the bug template with the payment link. Otherwise we cannot send you the funds

**Comment by vackss73** [comment]
> > Is there any compensation for me I wasted my time and also fees for this bug.
> 
> Yes please follow the bug template with the payment link. Otherwise we cannot send you the funds

How to do that I have no idea can you guide me ?

**Comment by daiagi** [comment]
@vackss73 
fill a bug report here
https://github.com/kodadot/nft-gallery/issues/new?assignees=&labels=bug&projects=&template=bug.yml&title=Be+descriptive+and+short

including your payment address
as for description just type #8733 and it will link it to here

**Comment by vackss73** [comment]
> @vackss73 
> fill a bug report here
> https://github.com/kodadot/nft-gallery/issues/new?assignees=&labels=bug&projects=&template=bug.yml&title=Be+descriptive+and+short
> 
> including your payment address
> as for description just type #8733 and it will link it to here

Payment detail will be my PolkaDot wallet adress??

**Comment by daiagi** [comment]
>Payment detail will be my PolkaDot wallet adress??

yes
