### ISSUE TITLE
Funds transfer issue on assets hub

### ISSUE THREAD

**Issue by vackss73** [kodadot/nft-gallery#8746]
### What happened?

So the issue that happened to me was that I was transferring around 1.85 dot from assets hub to native PolkaDot but each time the gas fees was deducted but mu funds didn't moved out I tried lowering the amount of transfer but still the same I did this like 10+ time. I missed dota inscription because of this and also wasted 2 days for this issue after two days the issue got resolved ,issue #8733 . But it already did a lot of wastage and chaos . It worked only when I transferred 75% of the fund ,and the rest is still there
My address -12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn

### Please reproduce in steps

Just go to assets hub  and use teleport transfer your funds little less than max amount just as for the gas

### Expected Behavior

Gas fee deducted but transaction didn't happened. It didn't even showed any error so that I can have a clarity 

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman, SubWallet

### Screenshots

![Screenshot_2023-12-24-23-54-49-860_com android chrome](https://github.com/kodadot/nft-gallery/assets/136322711/9004b825-465f-4a47-9272-5707f1a1b933)

### Wallet Address & Transaction hash

Address - 12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn

Hash of one of the txn - 0x297bf561deca21770a78c615b4600a14128d67da2125e3f199c4ed617e5e4868

### Payment link for reward

Polkadot address for payment - 12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
Please use the template correctly in the original issue
