### ISSUE TITLE
Fund transfer problem on assetshub

### ISSUE THREAD

**Issue by vackss73** [kodadot/nft-gallery#8751]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

So the issue that happened to me was that I was transferring around 1.85 dot from assets hub to native PolkaDot but each time the gas fees was deducted but mu funds didn't moved out I tried lowering the amount of transfer but still the same I did this like 10+ time. I missed dota inscription because of this and also wasted 2 days for this issue after two days the issue got resolved ,issue #8733 . But it already did a lot of wastage and chaos . It worked only when I transferred 75% of the fund ,and the rest is still there
My address -12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn

### Please reproduce in steps

Just go to kodadot, assetshub then teleport and try to teleport funds little less then the total amount for the fees 

### Expected Behavior

Everytime when I did transaction fee got deducted,but the funds didn't moved out 

### What browsers are you seeing the problem on?

Desktop Chrome, Mobile Firefox, Other

### Are you logged in?

Yes

### Which wallet you are using?

Talisman, SubWallet

### Screenshots

![Screenshot_2023-12-24-23-54-49-860_com android chrome](https://github.com/kodadot/nft-gallery/assets/136322711/894db6b2-5538-45b0-b57b-b8ad37f4e484)

### Wallet Address & Transaction hash

Wallet adress - 12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn

Txn hash - 0x297bf561deca21770a78c615b4600a14128d67da2125e3f199c4ed617e5e4868

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daiagi** [comment]
probably solved in #8740

**Comment by vackss73** [comment]
> probably solved in #8740 

Yeah but I am playing for reward 👀

**Comment by vackss73** [comment]
> > probably solved in #8740 
> 
> Yeah but I am applying for reward 👀

Any updtae on this ??

**Comment by daiagi** [comment]
@vikiival @yangwao

**Comment by vikiival** [comment]
> @vikiival @yangwao 

Bot cannot send funds without properly filled template

**Comment by vackss73** [comment]
> > @vikiival @yangwao 
> 
> Bot cannot send funds without properly filled template

Ok tbh I ve never used GitHub in my life . But still can you tell what I am missing out . So that I can correct that

**Comment by yangwao** [comment]
@vackss73 use template; otherwise cannot be processed or we will close this without reward

**Comment by vackss73** [comment]
> @vackss73 use template; otherwise cannot be processed or we will close this without reward 

I am using big report template. Is that wrong tempelate. atleast tell which template to use or what am I doing wrong here.i am newbie
