### ISSUE TITLE
Add highest sale

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#877]
Would be nice to see the highest sale for 
- [x] collections
- [ ] series view

Add a column with the highest sale to the series insight. 

#### side notes
But has an issue that how we know it's not a washtrade?

Could be joined with somewhere on top of 
- #1818
### Ref
- #2801

It's already in collections meanwhile
![image](https://user-images.githubusercontent.com/5887929/162746733-043292a2-a938-4c95-9ab9-26c7574de5fa.png)

**Comment by KngZhi** [comment]
I'll check this.

**Comment by KngZhi** [comment]
Working on [rubick](https://github.com/kodadot/rubick/pull/54).

**Comment by vikiival** [comment]
Made bounty higher as @KngZhi made a resolver :) 

https://github.com/kodadot/rubick/pull/54

**Comment by KngZhi** [comment]
lol, thanks, learned a lot from your slides!! 😆
