### ISSUE TITLE
Series sales insights for recent NFT transactions

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#878]
Would be nice to see recent transactions for collections (last 5/10?) like foldable component from Artist Spotlight to see which pieces from collections has sold and for how much.
Like we can have there some list 
| Item | To | Amount | 
|--|--|--|
| Magician #478 | E5dzUc...6vvBKv | 0.784 KSM |
| Magician #499 | E5dzUc...6vvBKv | 0.784 KSM |

Foldable component from Artist spotlight
![image](https://user-images.githubusercontent.com/5887929/136972387-a1f0d17a-20b9-4120-ae11-135f1c853948.png)

💳 goes to mcbeaster | 0xV on our discord

**Comment by roiLeo** [comment]
> Foldable component from Artist spotlight ![image](https://user-images.githubusercontent.com/5887929/136972387-a1f0d17a-20b9-4120-ae11-135f1c853948.png)

There is a Bug to fix here, green box shadow should only be on nft card where `currentOwner === accountId`
