### ISSUE TITLE
Drop date/time timezone

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#8786]
same date/time on different drops: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/5ff967f7-487b-44a1-b8b9-aedac0ae001e)

dates not considering timezone, correct one for me would be 13:00
![image](https://github.com/kodadot/nft-gallery/assets/36627808/8a9f4870-d6b5-4f61-97ee-13d46c1daa5d)

mint phase says open, even tho its not: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/30abf3ec-15d4-4a2a-b0c5-54cc4361b74f)

no testing round this time?

**Comment by vikiival** [comment]
> no testing round this time?

Lol we can do

**Comment by prury** [comment]
> > no testing round this time?
> 
> Lol we can do

😄 let me know, when/how

**Comment by yangwao** [comment]
I think done or solved meanwhile?

**Comment by prury** [comment]
> I think done or solved meanwhile?

let's see when new drop hits the drop page, let me change the issue name

**Comment by vikiival** [comment]
Correct on Canary

<img width="1619" alt="Screenshot 2024-01-04 at 11 49 57" src="https://github.com/kodadot/nft-gallery/assets/22471030/bd910513-cabb-45af-a740-36707df56fcc">
