### ISSUE TITLE
Fees deducted but assets not transferred 

### ISSUE THREAD

**Issue by vackss73** [kodadot/nft-gallery#8787]
### What happened?

So the issue that happened to me was that I was transferring around 1.85 dot from assets hub to native PolkaDot but each time the gas fees was deducted but mu funds didn't moved out I tried lowering the amount of transfer but still the same I did this like 10+ time. I missed dota inscription because of this and also wasted 2 days for this issue after two days the issue got resolved ,issue #8733 . But it already did a lot of wastage and chaos . It worked only when I transferred 75% of the fund ,and the rest is still there
My address -12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn

### Please reproduce in steps

Just go to kodadot, assetshub then teleport and try to teleport funds little less then the total amount for the fees

### Expected Behavior

Everytime when I did transaction fee got deducted,but the funds didn't moved out

### What browsers are you seeing the problem on?

Chrome, Mobile Android Chrome, Mobile Firefox

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman, SubWallet

### Screenshots

![assethub](https://github.com/kodadot/nft-gallery/assets/136322711/7d80cbc2-cb93-4fac-b913-fb7ea017491c)

### Wallet Address & Transaction hash

12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn

Txn hash - 0x297bf561deca21770a78c615b4600a14128d67da2125e3f199c4ed617e5e4868

### Payment link for reward

https://kodadot.xyz/dot/transfer?target=12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn&usdamount=0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vackss73** [comment]
> ### What happened?
> 
> So the issue that happened to me was that I was transferring around 1.85 dot from assets hub to native PolkaDot but each time the gas fees was deducted but mu funds didn't moved out I tried lowering the amount of transfer but still the same I did this like 10+ time. I missed dota inscription because of this and also wasted 2 days for this issue after two days the issue got resolved ,issue #8733 . But it already did a lot of wastage and chaos . It worked only when I transferred 75% of the fund ,and the rest is still there
> My address -12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn
> 
> ### Please reproduce in steps
> 
> Just go to kodadot, assetshub then teleport and try to teleport funds little less then the total amount for the fees
> 
> ### Expected Behavior
> 
> Everytime when I did transaction fee got deducted,but the funds didn't moved out
> 
> ### What browsers are you seeing the problem on?
> 
> Chrome, Mobile Android Chrome, Mobile Firefox
> 
> ### At which address did you encounter bug?
> 
> kodadot.xyz
> 
> ### Are you logged in?
> 
> Yes
> 
> ### Which wallet you are using?
> 
> Talisman, SubWallet
> 
> ### Screenshots
> 
> ![assethub](https://github.com/kodadot/nft-gallery/assets/136322711/7d80cbc2-cb93-4fac-b913-fb7ea017491c)
> 
> 
> ### Wallet Address & Transaction hash
> 
> 12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn
> 
> Txn hash - 0x297bf561deca21770a78c615b4600a14128d67da2125e3f199c4ed617e5e4868
> 
> ### Relevant log output
> 
> _No response_
> 
> ### Payment link for reward
> 
> https://kodadot.xyz/dot/transfer?target=12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn&usdamount=0
> 
> ### Code of Conduct
> 
> - [X] I agree to follow this project's Code of Conduct

What's the update on this ??

**Comment by vackss73** [comment]
> ### What happened?
> 
> So the issue that happened to me was that I was transferring around 1.85 dot from assets hub to native PolkaDot but each time the gas fees was deducted but mu funds didn't moved out I tried lowering the amount of transfer but still the same I did this like 10+ time. I missed dota inscription because of this and also wasted 2 days for this issue after two days the issue got resolved ,issue #8733 . But it already did a lot of wastage and chaos . It worked only when I transferred 75% of the fund ,and the rest is still there
> My address -12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn
> 
> ### Please reproduce in steps
> 
> Just go to kodadot, assetshub then teleport and try to teleport funds little less then the total amount for the fees
> 
> ### Expected Behavior
> 
> Everytime when I did transaction fee got deducted,but the funds didn't moved out
> 
> ### What browsers are you seeing the problem on?
> 
> Chrome, Mobile Android Chrome, Mobile Firefox
> 
> ### At which address did you encounter bug?
> 
> kodadot.xyz
> 
> ### Are you logged in?
> 
> Yes
> 
> ### Which wallet you are using?
> 
> Talisman, SubWallet
> 
> ### Screenshots
> 
> ![assethub](https://github.com/kodadot/nft-gallery/assets/136322711/7d80cbc2-cb93-4fac-b913-fb7ea017491c)
> 
> 
> ### Wallet Address & Transaction hash
> 
> 12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn
> 
> Txn hash - 0x297bf561deca21770a78c615b4600a14128d67da2125e3f199c4ed617e5e4868
> 
> ### Relevant log output
> 
> _No response_
> 
> ### Payment link for reward
> 
> https://kodadot.xyz/dot/transfer?target=12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn&usdamount=0
> 
> ### Code of Conduct
> 
> - [X] I agree to follow this project's Code of Conduct

Why is no one lookin into this @vikiival @yangwao

**Comment by vikiival** [comment]
I have deleted your messages as were spammy (basically quoting issue two times).

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 8.19 USD/DOT ~ 1.221 $DOT
🧗 [12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn](https://polkadot.subscan.io/account/12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn)
🔗 [0x024103738a1fa4d498501ad1ec198bc328d10dd3d9275475845243b9ead0e40d](https://polkadot.subscan.io/extrinsic/0x024103738a1fa4d498501ad1ec198bc328d10dd3d9275475845243b9ead0e40d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)
