### ISSUE TITLE
SQ update 0.22.0

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#879]
From James

*New Release*
Update @subql/node to 0.22.0

- Upgrade priority: High. To align with runtime upgrade of Kusama and Polakdot, upgraded api will support Metadata V14 and .
- Update Polkadot/api to 6.3.1 to support metadata v14 (# 505)
- Fetch service throw error with block height when failed fetch block (# 492)
- Throw errors when connection dropped by http, and exit (# 519)
- Addition fix for Poi service with if condition (# 508)
- Support project manifest 0.2.0 (# 495)

https://github.com/subquery/subql/pull/523

This new release is required for all Polkadot or Kusama projects due to the new runtime upgrade, due to happen at https://kusama.subscan.io/block/9621150 for Kusama and https://polkadot.subscan.io/block/7228980 for Polkadot

Also query 0.7.3 is recommended too

**Comment by vikiival** [comment]
Closed in 09715b4e73bfa48c9d0d060074094a5e6de6e2a3
