### ISSUE TITLE
Chroma Lattice Drop page confused

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8802]
I will show you this amazing picture and who can say what is wrong on this drop page of Chroma Lattice? 
- AHP
- Production
- Drop Page: https://kodadot.xyz/ahp/drops/chroma
- Account logged: 1NFfEH3yspdEgLnhZ5QWgb7B2z5LNCAE3HUo5nDxF5MqTcj

<img width="1440" alt="Screenshot 2023-12-29 at 19 32 08" src="https://github.com/kodadot/nft-gallery/assets/104380776/a49656ba-fc18-4b96-8739-8d7195ae95c5">

Whats wrong
---
1. I own Chroma Lattice NFT so **instead of Not Eligible it should show: Show NFT**
2. Its showing that I don't have 2 DOT on AHP - but look - I have 2,7 DOT

**Comment by exezbcz** [comment]
> * I own Chroma Lattice NFT so **instead of Not Eligible it should show: Show NFT**

why

**Comment by Jarsen136** [comment]
The root issue is that the api side does not return the minted result for the current account.
@vikiival has already said that there is no return based on the consideration of avoiding being hacked.
There should be another better solution to solve this issue. 
`https://waifu-me.kodadot.workers.dev/drops/chroma/accounts/1NFfEH3yspdEgLnhZ5QWgb7B2z5LNCAE3HUo5nDxF5MqTcj`

Once this api returns the correct minted data for the current account, the below button will be shown.



<img width="476" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/e961de7b-233a-484a-9cb6-a437910a54fc">

**Comment by vikiival** [comment]
> The root issue is that the api side does not return the minted result for the current account.


The issue is that we do not track result of this particular drop. 

Please open an issue and I will try to fix it for upcomming drop

**Comment by exezbcz** [comment]
maybe something like requirements section would be nice

it will go like this: 


requirements
- checkbox - holder of this nft ... (here can also be a dropdown so you select what nft you use for the right to mint 
- checkbox - 0.2 on polkadot assethub

**Comment by Jarsen136** [comment]
> > The root issue is that the api side does not return the minted result for the current account.
> 
> The issue is that we do not track result of this particular drop.
> 
> Please open an issue and I will try to fix it for upcomming drop

Thank you! Here is it https://github.com/kodadot/private-workers/issues/29

**Comment by exezbcz** [comment]
meanwhile 
- #8886

**Comment by vikiival** [comment]
Follow in #8886
