### ISSUE TITLE
Not able to mint Chroma Lattice - already claimed nft

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8804]
A person has a problem with minting Chroma Lattice NFTs. He is using a private address he does not want to disclose yet.

He has 3 motherboards - only one used to mint Chroma Lattice - he minted one Chroma Lattice - two left. 

- he has more than 2 DOts on the asset hub Polkadot
- owns another 2 motherboards that were not used and they don't show the banner that they were used before
- he should be eligible to mint (even though he has one chroma lattice already) because he has two more - from what I have been told he should be able to mint one chroma lattice for every "unused" motherboard he has.

Problem
---

it seems that if one has more  .motherboards, and some were not used, the system has a bug. Ideally, the UI should maybe display this somehow.something that tells you how many chrome lattice can you still mint.

**Comment by yangwao** [comment]
>
should maybe display this somehow.something that tells you how many chrome lattice can you still mint.

I think it's now trying the first one? Or let user choose which one to use for holderOf?

**Comment by JustLuuuu** [comment]
> > 
> 
> should maybe display this somehow.something that tells you how many chrome lattice can you still mint.
> 
> I think it's now trying the first one? Or let user choose which one to use for holderOf?

Well, he has 3 motherboards and he should be able to claim 3 chroma lattices with them. But he is not able to claim it, only one. even though those two were not used to claim NFT. I gues our system can see one that was used and it does not let him to mint more.

**Comment by filippoweb3** [comment]
Well, I tried gain, now I have multiple boards that do not have the banner showing the board has be used for claims. I have way more than 2 DOT on asset hub and I get the error below 

<img width="636" alt="Screenshot 2023-12-30 at 17 35 46" src="https://github.com/kodadot/nft-gallery/assets/110459737/9d8f33fc-30c7-4620-a729-8de0469e83f3">

**Comment by vikiival** [comment]
As a quickfix can you transfer "the" used .mb to other address? 

We will def look into this.

**Comment by yangwao** [comment]
Hey @filippoweb3, we will have a quick design, hopefully in the upcoming days, ready for implementation as holderOf is bit experimental, and we've opened a request for changes in the parity repository for indexers to make it easier 
- https://github.com/kodadot/nft-gallery/issues/8841
