### ISSUE TITLE
Video NFTs not loading at all on iOS

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8805]
Videos not loading on the phone at all. On my phone, I opened [this](https://kodadot.xyz/ahk/gallery/126-20) video NFT -  is not working.
- Production, AHK
May be related to #8729 - but the issue is a bit different because the video NFT can be loaded on a desktop, but not on a phone. 
![IMG_9943](https://github.com/kodadot/nft-gallery/assets/104380776/1afdbef4-b153-4b2a-afc7-ca1fd235f658)

**Comment by roiLeo** [comment]
![Screenshot_20231229-213331.png](https://github.com/kodadot/nft-gallery/assets/9987732/79b72644-0526-49a7-8402-35accdec648a)

Wfm on Android.

Could you try using Nova Wallet or Subwallet?

I remember we had some issue in the past with iOS & safari

**Comment by JustLuuuu** [comment]
> I remember we had some issue in the past with iOS & safari

Nova wallet: 
Not working. I have iphone
![IMG_9943 3](https://github.com/kodadot/nft-gallery/assets/104380776/e254be61-2eaf-47c4-9997-d8a3b6eddd1e)

**Comment by roiLeo** [comment]
- link #236

**Comment by preschian** [comment]
related: https://github.com/kodadot/workers/issues/187

only on iOS

**Comment by roiLeo** [comment]
Looks like a server related issue, I can reproduce it on Safari browser and sometimes take some time to load on firefox

- https://image-beta.w.kodadot.xyz/ipfs/bafybeig6uwnvwmfnn2rx3mdwddwqawrrmru4hs655svawe2lacouzygtra
