### ISSUE TITLE
Auto teleport signing does not popup wallet 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8819]
https://github.com/kodadot/nft-gallery/assets/90852205/26a62884-7630-48cc-aba5-0b7c4de6516c

when I click buy now, or finish purchase from the cart, in the signing step, there is no wallet popup

![image](https://github.com/kodadot/nft-gallery/assets/90852205/ffae5cad-d0da-49da-90cd-6090208375fc)

tried refreshing

tested here: https://canary.kodadot.xyz/ahp/explore/items?listed=true&collections=63&sort=price_ASC

- it does not work for me on any nft

**Comment by hassnian** [comment]
seems to be working let me know if the issue still persists   

https://github.com/kodadot/nft-gallery/assets/44554284/74960ceb-8668-4217-a3f6-3278edd59f64

https://github.com/kodadot/nft-gallery/assets/44554284/1b5ea94d-9e67-4e1e-b3e6-65e5dab2eb58

**Comment by exezbcz** [comment]
@hassnian will try later today

**Comment by exezbcz** [comment]
did not try, but looks like I am not the only one 


![telegram-cloud-photo-size-4-5857318700426838158-y](https://github.com/kodadot/nft-gallery/assets/90852205/c8c2c616-9f27-44eb-ab0a-2bdc76d18083)



for this user, the popup probably did not even display

- he was clicking on the circle next to the heading.... :D 

- it should also probably rotate the circle when it's waiting for the signature - as it's done in the simple signing 


cc @hassnian

**Comment by exezbcz** [comment]
anything we can do? 

I just cant sign the autoteleport, seems like issue of ed or something like that 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/e78c2074-a634-45c6-8dd2-6d9d62315919)


https://github.com/kodadot/nft-gallery/assets/90852205/268ca4ec-f6e2-4f5c-9f1b-3affad36768b

can we solve it?

**Comment by hassnian** [comment]
> anything we can do?
> 
> I just cant sign the autoteleport, seems like issue of ed or something like that ![image](https://private-user-images.githubusercontent.com/90852205/299696233-e78c2074-a634-45c6-8dd2-6d9d62315919.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMjUxNzIsIm5iZiI6MTcwNjMyNDg3MiwicGF0aCI6Ii85MDg1MjIwNS8yOTk2OTYyMzMtZTc4YzIwNzQtYTYzNC00NWM2LThkZDItNmQ5ZDYyMzE1OTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDAzMDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlN2RhY2Q5NmE0NDllYWE5NGVkMzJiZmNjYjgyNWNlY2M0ZmYzYWI1YmU4ZTEwMTdiNmJiMzUxYTMwNmY3OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Wen1Gkz1Wok0JMXtAn7q8ZrQgBwmYizjbmNZGulQsU)
> 
>  Screen.Recording.2024-01-25.at.15.18.50.mov 
> can we solve it?

will check

**Comment by daiagi** [comment]
@hassnian  any findings?

**Comment by hassnian** [comment]
> @hassnian any findings?

got busy with other issues, wasn't able to check 

feel free to pick it up.

**Comment by daiagi** [comment]
@exezbcz  please confirm issue is resolved

i have tried about 15 times on differant NFT's in the "Genera" collection
the auto-teleport sign modal opened every single time

![image](https://github.com/kodadot/nft-gallery/assets/22791238/53bff19a-f827-4370-8feb-e2c5dd8ddd12)
