### ISSUE TITLE
Search on mobile doesn't show results

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8824]
https://github.com/kodadot/nft-gallery/assets/5887929/ad19ee07-c444-4683-91ae-8bbe53ed6362

**Comment by vikiival** [comment]
As far as @prury is aware, there was no dropdown since begining

**Comment by exezbcz** [comment]
for some nostalgia and og design 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/f80ced55-d47c-4473-a984-5c4f7d5ff348)
https://www.figma.com/file/3iOjW12ERFRDSVnpLuhQmf/landing-page-handoff?type=design&node-id=1305-5613&mode=design&t=NpeMsabFiLoRp7Uj-11


not sure if its still the best solution tho, let me put design request here
