### ISSUE TITLE
Show Kodadot Fee on when buying NFT

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#8827]
![image](https://github.com/kodadot/nft-gallery/assets/36627808/cc3cdde3-09af-43f3-b03e-2974e8cb1193)

**Comment by exezbcz** [comment]
already there 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/b4703afe-77be-403c-9ce8-fc3a82db66d1)


is it a percentage or fixed value @prury ?

**Comment by prury** [comment]
> already there - this is the minting modal 
> ![image](https://github.com/kodadot/nft-gallery/assets/90852205/b4703afe-77be-403c-9ce8-fc3a82db66d1)
> 
> 
> is it a percentage or fixed value @prury ?

Percentage, 3% as viki said on internal group

**Comment by exezbcz** [comment]
maybe lets rename kodadot fee to service fee 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/75055f95-d544-4433-aac9-e119d7f72264)


there is also tooltip 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/39ab1554-4a02-464b-a437-dfa649e4496c)


- updated in figma confirmation modals 
- https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=6072-16139&mode=design&t=tJPyjQmoBo7raPMb-11
![image](https://github.com/kodadot/nft-gallery/assets/90852205/bb3950f5-d697-4774-92bd-5ccf4f7a8902)
