### ISSUE TITLE
Buy now toggle shuffles with collections stats

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#883]
When you flip BUY now, it changes collections stats which I guess should not?

Video is here, referenced PR https://github.com/kodadot/nft-gallery/pull/875 
https://github.com/kodadot/nft-gallery/pull/875#issuecomment-940875037

https://user-images.githubusercontent.com/5887929/136938544-61425713-4bcd-403b-9c36-cd6c4b0a2f87.mov

**Comment by roiLeo** [comment]
closed in #983
