### ISSUE TITLE
Stuck on Minting

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8836]
Person: Woltah on TG
Address: 138hRafN6iv2sYrtgDcyY8mvdED4Wr58z1vF4jkKGSr6c172
Problem: The artist is unable to mint NFT.
Chain: Polkadot Asset Hub
He is stuck on this step:

![2024-01-03 11 04 59](https://github.com/kodadot/nft-gallery/assets/104380776/1a672c38-02c2-4b8f-b0e1-1b3fd446220a)

Explanation: This happens when I create a single NFT. I hit the button “Create New NFT” then it gets stuck on “Doing Some Magic”
My collection used to be in Unlimited supply, I changed it to 1 supply only coz I thought it would fix it but it didn’t. I got more NFTs to put in my collection but limited to 1 - **still he was not able to mint any NFT in the collection.**

**Comment by hassnian** [comment]
@JustLuuuu  this is prod right ?

@yangwao  #8823 fixes this , can we merge it to prod ?

![CleanShot 2024-01-03 at 15 42 21@2x](https://github.com/kodadot/nft-gallery/assets/44554284/b7d21c77-ce6c-49e7-949c-83a225b3258a)

**Comment by vikiival** [comment]
> fixes this , can we merge it to prod ?
> 
> 

We will do release today / tomorrow
