### ISSUE TITLE
Top collections showing wrong or delayed floor price? 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8839]
![image](https://github.com/kodadot/nft-gallery/assets/5887929/9ff35d99-7dfe-4976-92e0-64b8bbf27fde)

motherboard now
![image](https://github.com/kodadot/nft-gallery/assets/5887929/9dbe36eb-1c82-4ac2-8563-c827ad5ffbd2)
swirls
![image](https://github.com/kodadot/nft-gallery/assets/5887929/bf26fede-afa0-47fd-8e11-49e534859fd0)
genera
![image](https://github.com/kodadot/nft-gallery/assets/5887929/a1187a39-97fc-4c9d-9d32-23a52d230f62)
and so on

**Comment by roiLeo** [comment]
closed by kodadot/stick#165?

**Comment by exezbcz** [comment]
@roiLeo still there 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/c79fbeff-19d3-4a10-8f1f-1062b658fe07)
![image](https://github.com/kodadot/nft-gallery/assets/90852205/c2eb4783-c501-45d6-a642-114291863843)

**Comment by roiLeo** [comment]
closed by #8931
