### ISSUE TITLE
Drop page not showing

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8840]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/c22c2d43-2268-4786-8786-fb29efe5800d)
https://canary.kodadot.xyz/ahp/drops/genera

it should be visible even when its ended

**Comment by Jarsen136** [comment]
It works for me. Feel free to reopen it if you can reproduce it.
![image](https://github.com/kodadot/nft-gallery/assets/31397967/4cdc9027-5a30-4a40-b796-e76185b9a3ff)
