### ISSUE TITLE
holderOf - automatically choose unused item to claim drop

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8841]
Currently, we have an issue that people who own 2+ motherboards, where one was used for claim. 
Situation
- 
One item was used for a claim Chroma Lattice, and the second was not; they can not claim drop where it is required holderOf `.motherboard` as the current code uses the first one, which is claimed already for user.

In design could be highlighted to show how many claims user has left to do claim using holderOf or automatically show user which motherboard would be used for claim for easy and quick design

Related
-
- https://github.com/kodadot/nft-gallery/issues/8804
- https://github.com/kodadot/nft-gallery/issues/8611

**Comment by exezbcz** [comment]
continue to: 
- https://github.com/kodadot/nft-gallery/issues/8886
