### ISSUE TITLE
NeoButton variant conflicts 

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#8852]
seems there are some conflicts between neobutton --k-accent and --rounded 

https://github.com/kodadot/nft-gallery/pull/8838#issuecomment-1875331761
![CleanShot 2024-01-04 at 18 51 23@2x](https://github.com/kodadot/nft-gallery/assets/44554284/00ceb5fc-9c3c-4b00-8de0-585efbceff9a)

**Comment by roiLeo** [comment]
closed by #8851
