### ISSUE TITLE
Coretime Issues

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#8854]
- [See your nft not always appear and when it appears its leading to wrong number NFT](https://github.com/kodadot/nft-gallery/assets/36627808/9014cd03-c8ff-4f5a-af5b-64f0774e7652)

See your NFT only appears in one of my accounts and when it appears it leads me to an NFT i did not mint.

i think the correct flow would be show See Your NFT button only right after minting, and if the user refresh the page, claim button is available again, is that correct @vikiival ?

**Comment by roiLeo** [comment]
any errors in console?

**Comment by prury** [comment]
> any errors in console?
Leo, i'll close since it was only on coretime drop and worked well for the Split drop
