### ISSUE TITLE
drop-page - url on minting success seems doesn't work?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8857]
<img width="176" alt="image" src="https://github.com/kodadot/nft-gallery/assets/5887929/02b2bb0e-6c0d-4d09-ab38-b44e58632531">

https://assethub-polkadot.subscan.io/extrinsic/0100000a7d4448a00000

**Comment by hassnian** [comment]
@vikiival can we get the same txHash type as /do for /claim

**Comment by vikiival** [comment]
> hmmm I'm confused , /do/{campaign} returns txHash , doesn't it ?

Yes it does, but it is a timestamp of insert into KV.

I can remove/ change the name if it is confusing.

**Comment by hassnian** [comment]
ahhh ic got confused by the name ,

can we get a tx hash to use here ?

![image](https://github.com/kodadot/nft-gallery/assets/44554284/0a071dde-438a-40bb-9a79-8c89e8c8423d)
