### ISSUE TITLE
DRY information on series

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#886]
I guess, once I'm on Kusama (or another network like BSX or Statemine), it's sufficient to show KSM just in the header, not trailing at every number. It would be good if someone to want to copy-pasta it somewhere but from viewing numbers, it's unnessecary. 

Save users brain load, whenever possible ❤️‍🔥

Re headline
> The top NFTs on RMRK, ranked by volume, floor price and other statistics.
-->
> The top NFTs on RMRK, ranked by volume, floor price and various pseudo metrics.

![image](https://user-images.githubusercontent.com/5887929/137101582-663e6005-f1d7-40a0-99a7-f212880ab937.png)

Re progress, love it, it's much nicer now, kudos to @roiLeo !:)
My OCD is less triggered once cols are sorted

**Comment by roiLeo** [comment]
## Curent state

partially done 

## To do
Use [custom-headers](https://buefy.org/documentation/table/#custom-headers) to inform users what kind of currency is used/displayed
