### ISSUE TITLE
Implement allow list for drops

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8862]
This will help us test things on production and sell it as VIP drop as well 

Simple list, some csv where we can put list of addresses to allowed to mint even mint would be enabled.

we can add design that allow list phase enabled or so

**Comment by roiLeo** [comment]
Or whitelist_buyer

**Comment by yangwao** [comment]
cc @exezbcz

**Comment by exezbcz** [comment]
probably done in #9171 	
>phases
