### ISSUE TITLE
NFts minted and the nft generated to mint are totally different 

### ISSUE THREAD

**Issue by vackss73** [kodadot/nft-gallery#8863]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

The issue happened during the split nft minting. The nft which I generated to mint ( the one which I liked ) and the nft minted that came into my wallet is totally different . I am damn sure that it's not the nft I generated to mint. Additionally I want to add that my network connection is 5g which works really good and also the page was refreshed to the latest. I am really disappointed to the nft I got . I don't like it's attributes. Here is the link to it https://kodadot.xyz/ahp/gallery/66-64
@vik

### Please reproduce in steps

Just go to mint generate nft which you like and mint and confirm that the nft is same to the Nft you generated

### Expected Behavior

Minted NFt is totally different 

### What browsers are you seeing the problem on?

Mobile Android Chrome, Mobile Firefox

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS, Talisman, SubWallet

### Screenshots

![Screenshot_2024-01-04-22-17-53-037_com android chrome](https://github.com/kodadot/nft-gallery/assets/136322711/ba127f94-baea-40a7-9b85-1ad8f8c07b16)

### Wallet Address & Transaction hash

Wallet address - 12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn

### Payment link for reward

https://kodadot.xyz/dot/transfer?target=12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn&usdamount=30

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vackss73** [comment]
> ### Is there an existing issue?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> The issue happened during the split nft minting. The nft which I generated to mint ( the one which I liked ) and the nft minted that came into my wallet is totally different . I am damn sure that it's not the nft I generated to mint. Additionally I want to add that my network connection is 5g which works really good and also the page was refreshed to the latest. I am really disappointed to the nft I got . I don't like it's attributes. Here is the link to it https://kodadot.xyz/ahp/gallery/66-64
> @vik
> 
> ### Please reproduce in steps
> 
> Just go to mint generate nft which you like and mint and confirm that the nft is same to the Nft you generated
> 
> ### Expected Behavior
> 
> Minted NFt is totally different 
> 
> ### What browsers are you seeing the problem on?
> 
> Mobile Android Chrome, Mobile Firefox
> 
> ### At which address did you encounter bug?
> 
> kodadot.xyz
> 
> ### Are you logged in?
> 
> Yes
> 
> ### Which wallet you are using?
> 
> PolkadotJS, Talisman, SubWallet
> 
> ### At which chain did you encounter bug?
> 
> _No response_
> 
> ### Screenshots
> 
> ![Screenshot_2024-01-04-22-17-53-037_com android chrome](https://github.com/kodadot/nft-gallery/assets/136322711/ba127f94-baea-40a7-9b85-1ad8f8c07b16)
> 
> 
> ### Wallet Address & Transaction hash
> 
> Wallet address - 12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn
> 
> ### Relevant log output
> 
> _No response_
> 
> ### Payment link for reward
> 
> https://kodadot.xyz/dot/transfer?target=12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn&usdamount=30
> 
> ### Code of Conduct
> 
> - [X] I agree to follow this project's Code of Conduct

Any update on this ?? @vikiival

**Comment by vikiival** [comment]
Please recheck your nft again. We were updating entropy 😇
