### ISSUE TITLE
Change the sorting view bars *side bar + top bar* to be more intuitive 

### ISSUE THREAD

**Issue by poppyseedDev** [kodadot/nft-gallery#8868]
### Is your feature request related to a problem?

Most often I want to see which items are listed and orded from low to high by price. So to do this I have to click Buy now button + sort buy price low to high.
 
 I didn't know that I have to click the buy now button if @JustLuuuu  haven't told me about it. Its super unintuitive. Why are there some things on the top and some things on the bottom. Is the sidebar a placeholder for more features to be added in the future? However I think less is more.
 Also how does selecting multiple items at the same time work? Here I am selecting oldest + recently interacted + price: low to high
 
<img width="1139" alt="Screenshot 2024-01-04 at 19 55 29" src="https://github.com/kodadot/nft-gallery/assets/30662672/6ffb18d3-82c8-4e0c-a6d0-6b78657b5de9">

 Also you have the advance filters and then you click on it and you have one item, I think that is unnecessary.

### Describe the solution you would like

A more simplified overview, which is a bit more intuitve. Maybe instead of saying buy now, say listed ...

### Describe alternatives you have considered

<img width="1427" alt="Screenshot 2024-01-04 at 19 45 53" src="https://github.com/kodadot/nft-gallery/assets/30662672/4f99a3e2-a285-4392-9de6-55da620ca252">

**Comment by exezbcz** [comment]
should be partly solved there 
- https://github.com/kodadot/nft-gallery/issues/8890
