### ISSUE TITLE
Weird decimal behaviour in list dialog

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8880]
Seems when I want to input `1.1` it only show `1` and I need to put `11`, `leftarrow` and `.` also other weird with decimal rounding?

https://github.com/kodadot/nft-gallery/assets/5887929/2462665f-685a-4b41-b3a2-a93bce707569

**Comment by roiLeo** [comment]
wfm
https://github.com/kodadot/nft-gallery/assets/9987732/b846f344-ca40-4697-80d3-f87c734fe1c7

**Comment by exezbcz** [comment]
@roiLeo it does not work in the individual inputs 

![Uploading image.png…]()

**Comment by roiLeo** [comment]
> @roiLeo it does not work in the individual inputs

Oh! I see thanks for clarification I am able to reproduce it.
Should be `type="number"` instead
