### ISSUE TITLE
Top collection load only five collection

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8883]
happens randomly but frequently so definitely reproducible by refreshing

![image](https://github.com/kodadot/nft-gallery/assets/5887929/97d5ecca-d345-4d18-a859-1d6ff1d2bd15)

![telegram-cloud-photo-size-4-5816432531619300100-y](https://github.com/kodadot/nft-gallery/assets/5887929/209693c9-bcd1-4d3b-98c3-0c86d2b4ca38)

**Comment by roiLeo** [comment]
How to reproduce it?
