### ISSUE TITLE
Identity badge is not so trustworthy

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#8921]
hmmm badge is not so trustworthy I can spoof any address and name myself as someone already knowed, otherwise code lgtm

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/8907#pullrequestreview-1810557868_

### What we can do to improve it

Same as polkassembly, show badge near verified identities (judgement)

![Screenshot 2024-01-09 at 13-51-42 OpenGov](https://user-images.githubusercontent.com/9987732/295211831-c9109b04-cfe8-417a-8b3d-64bbd49d70ec.png)
![Screenshot 2024-01-09 at 13-51-58 OpenGov](https://user-images.githubusercontent.com/9987732/295211839-100c46b2-ef97-4773-a05f-1b8c6d087c3b.png)

**Comment by JustLuuuu** [comment]
would be cool to have this 🚀

**Comment by exezbcz** [comment]
yeah, but the person still had to pay 145 USD to create the identity 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/1e86cba9-9160-4301-9cc1-709d9c783d85)

- in the future, I would like to also distinguish between verified ID and unverified ID

for example, Twitter does it, you pay, you get a check, and you can have the same name, in our case the underlying address is what distinguishes


>but yeah could be removed ~ 

- replaced better 

not sure with what
