### ISSUE TITLE
Add Fullscreen view for generative art 

### ISSUE THREAD

**Issue by Lammetje** [kodadot/nft-gallery#8923]
### Is your feature request related to a problem?

Hi is it possible to view an artwork fullscreen ?

### Describe the solution you would like

A way to view the artwork fullscreen, because its nice for collectors as well

### Describe alternatives you have considered

Its a suggestion

**Comment by exezbcz** [comment]
there currently is afaik, but the support is not ideal, you cannot see the whole square.


thus adding design request and I will try figure out better way
