### ISSUE TITLE
One decimal in top collections for different region

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8938]
Look like it's related to the number format in different regions. I will check it

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/8937#issuecomment-1884780126_

**Comment by Jarsen136** [comment]
> Look like it's related to the number format in different regions. I will check it
> 
> _Originally posted by @Jarsen136 in [#8937 (comment)](https://github.com/kodadot/nft-gallery/pull/8937#issuecomment-1884780126)_

<img width="317" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/42d8e3e4-fd81-477b-a9b1-0af29f4ec66a">

<img width="293" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/032cec0f-9ec4-41c5-8764-fafacdca13f5">
