### ISSUE TITLE
Assembly Drop

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#8950]
- the animation is not playing inside gallery item as it does on windows test drop
![image](https://github.com/kodadot/nft-gallery/assets/36627808/d2246af8-bb2b-4cc4-b0a0-bc07ae2e536f)

- royalties has been set to 10% on issue but its 15% on collection 
- art also not centered

**Comment by vikiival** [comment]
Ahh :D fuk

I played myself

**Comment by prury** [comment]
@vikiival please check fullscreen as well: 

<img src="https://github.com/kodadot/nft-gallery/assets/36627808/b765fd0d-b7cb-4048-8196-62cad8d96ca8" height="300">

**Comment by prury** [comment]
also just to be sure, drop not yet showing on /drops

**Comment by vikiival** [comment]
> also just to be sure, drop not yet showing on /drops

Showing on /drops

> royalties has been set to 10% on issue but its 15% on collection

Yes that is my bad we had small desync with @JustLuuuu and you cannot mutate royalty once its set. 

I have opened issue - https://github.com/kodadot/stick/issues/193
