### ISSUE TITLE
link for tx at drop minting

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8954]
it lead me here
- https://assethub-polkadot.subscan.io/extrinsic/0100000cc74fbfe00000
![image](https://github.com/kodadot/nft-gallery/assets/5887929/0e0af5de-743f-477f-8ef2-a80092e02f25)

**Comment by Jarsen136** [comment]
It‘s the same as https://github.com/kodadot/nft-gallery/issues/8857
