### ISSUE TITLE
Drops page should be limited to 1280px breakpoint

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#8955]
Can we use the biggest possible breakpoint and not full width at drops? 
Maybe slimmer looks much better

🤢

![telegram-cloud-photo-size-4-5836804287353700041-y](https://github.com/kodadot/nft-gallery/assets/5887929/699ffbf3-6118-451b-8861-19c79cf5dc9e)

**Comment by exezbcz** [comment]
done in: 
- #9171
