### ISSUE TITLE
Replay animation

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#8959]
Once animation ends on [Assembly](https://canary.kodadot.xyz/ahp/collection/76) NFT, it stops like this:

<img width="1410" alt="Screenshot 2024-01-11 at 17 44 00" src="https://github.com/kodadot/nft-gallery/assets/104380776/097b55aa-f262-48af-8e7f-593594ba26ef">

It would be nice to have a button - restart animation, or something like that, it will give peeps one more button to "play" with. More interactive.

PS I know I can refresh the page 😅

**Comment by exezbcz** [comment]
- #9737
