### ISSUE TITLE
Brave .js login failure

### ISSUE THREAD

**Issue by hueeee** [kodadot/nft-gallery#897]
Unable to access kodadot profile in Brave browser.

Page UI displays blank account selection.

-Windows 10 x64
-Brave browser v.1.9.72
![kodadot001](https://user-images.githubusercontent.com/92551459/137399037-353e1bdd-9282-4a8b-846f-6a6444227e7a.jpg)

**Comment by hueeee** [comment]
It has not happened since shortly after the ticket was posted, all good to
remove imo

Xoxo :3

**Comment by yangwao** [comment]
happily to give you a bounty, hence we have incentivized bug bounty 
https://docs.kodadot.xyz/incentives/incentivized-bug-reporting.html#rewards

generate the link here with your address https://kodadot.xyz/transfer/

**Comment by yangwao** [comment]
Okay, reach me on Discord and happy to process bounty for bug reporting. 
Closing as we want to clear fixed bugs! :)
