### ISSUE TITLE
Views counter

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#901]
We can think of increment views on nfts using functions and using ThreadDB for that? Let's discuss it later @vikiival

**Comment by exezbcz** [comment]
Hey, time travel. Is this what we're doing? :D

**Comment by roiLeo** [comment]
links to #4593

**Comment by vikiival** [comment]
https://backyardcoder.me/posts/implementing-a-page-view-counter/

**Comment by yangwao** [comment]
be carefull with time travel
<img src="https://media4.giphy.com/media/7TZvWKVkm0xXi/giphy.gif"/>

- #4862

**Comment by yangwao** [comment]
Yes continue to 
- #4593
