### ISSUE TITLE
Waifu minter not working

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9024]
https://kodadot.xyz/ahk/waifu not working
address I used: DiUmeFmtG8VFVPuXS5VWz9cRm4k7JrmxdGuY2tWrW98dWPi

<img width="711" alt="Screenshot 2024-01-16 at 17 30 42" src="https://github.com/kodadot/nft-gallery/assets/104380776/69911db0-d589-40a9-809c-7f6a7de1a9c1">

fix or hide minter

**Comment by roiLeo** [comment]
duplicate #7751
