### ISSUE TITLE
Bought a NFT but kodadot does not reflect it

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#9029]
### What happened?

Bought two .motherboard nfts , one using canary , second one using prod , it's as if the buy event didn't go through but it did 

## Wallets
[1yHddTK4XihjK2DJE8g3oKV5d51TKPmnaCdYgPPTWqm6Ed4](https://assethub-polkadot.subscan.io/account/1yHddTK4XihjK2DJE8g3oKV5d51TKPmnaCdYgPPTWqm6Ed4?tab=nft_transfer) -> wallet 1

[13ESPNx9ipHBV3edToBWt4NvRwuw6mGYcK27ai4ad8F5LzbV](https://assethub-polkadot.subscan.io/account/13ESPNx9ipHBV3edToBWt4NvRwuw6mGYcK27ai4ad8F5LzbV?tab=nft_transfer) -> wallet 2

## NFTs

https://kodadot.xyz/ahp/gallery/50-788 -> using wallet 1 -> [tx](https://assethub-polkadot.subscan.io/extrinsic/5457518-2)

![CleanShot 2024-01-17 at 10 50 06@2x](https://github.com/kodadot/nft-gallery/assets/44554284/4c39a883-e753-4202-a7ef-448713ad627a)

https://kodadot.xyz/ahp/gallery/50-240 -> using wallet 2 -> [tx](https://assethub-polkadot.subscan.io/extrinsic/5457316-2)

![CleanShot 2024-01-17 at 10 52 34@2x](https://github.com/kodadot/nft-gallery/assets/44554284/cd16acc0-3d4c-4fa4-8c48-175cb48cf999)

indexer issue ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hassnian** [comment]
@preschian any thoughts ? kinda need this for #9027

**Comment by preschian** [comment]
Oooh, it seems like yes. Indexer issue. All our indexers are stuck.

<img width="548" alt="Screenshot 2024-01-17 at 1 56 23 PM" src="https://github.com/kodadot/nft-gallery/assets/734428/f7726b17-7bc6-4288-8269-a775076dacf8">

cc @kodadot/internal-dev

**Comment by roiLeo** [comment]
![Screenshot 2024-01-17 at 08-33-07 Subsquid Cloud](https://github.com/kodadot/nft-gallery/assets/9987732/6967c079-a29a-4f89-85e8-262a86794a58)
