### ISSUE TITLE
Humanize errors

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#9038]
### Is your feature request related to a problem?

Sometimes an error on KodaDot could happen and user is confused when (s)he sees error like `{AlreadyExists: 
The item ID has already been used for an item. }`

### Describe the solution you would like

Instead it would be nice to have contextual errors - in mint this means some `sn` mismatch (bad calculation) 
- in drop it means that someone already claimed same nft

1. Rework state for error throwing (should return some object or smth)
2. Compile translation files for top errors (https://assethub-kusama.subscan.io/runtime)
3. 

### Describe alternatives you have considered

We need to rethink error notifications properly.

**Comment by JustLuuuu** [comment]
Maybe related too:
- #7160 
- https://github.com/kodadot/nft-gallery/issues/4121

**Comment by yangwao** [comment]
Maybe we can wire up notifications with some [Report this problem] so we can have it filled right away with more debug information or actually Sentry should handle this gracefully

**Comment by yangwao** [comment]
Drop popular errors and we can start styling them better

**Comment by vikiival** [comment]
> Drop popular errors and we can start styling them better

1. https://assethub-kusama.subscan.io/runtime/Nfts?version=1001002
2. CMD +F `Error Types`

* AlreadyExists - trying to mint NFT that already exists
* BadWitness - when calling doing drop with price or holder of and do not supply the value
* MaxSupplyReached - trying to mint NFT to already full collection
* AlreadyClaimed - when you try to use the same nft for holder of twice
* CollectionNotEmpty - when destroying non-empty collection
* WitnessRequired- when calling doing drop with price or holder of and do not supply the object

**Comment by exezbcz** [comment]
continue to:
- https://github.com/kodadot/nft-gallery/issues/10109
