### ISSUE TITLE
Drop 18.1. settings 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9043]
<img width="270" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/4014966f-3c04-4836-b12c-92d9d55338db">

As the team agreed, the drop should be **free**, with **0.5 holding on AHP** required. 

- need to change the button 
<img width="707" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/d58fdc9c-640f-4f6d-aef6-5c7f0bbf41a4">

## Claim flow
- please double check whether the flow is correct 
- not sure in what order is it

### signup 
- there should be signup banner + check if user subscribed 
this: 
<img width="786" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/c517def5-e92d-4346-9b42-697adf256e14">

and this after: 
<img width="562" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/669f5b77-a0e3-49ad-8255-6f7d4488dac1">

### Auto teleport
if user does not have the required balance (0.5 DOT on AHP) we have autoteleport 

this one 
<img width="874" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/b800ec81-55f6-4145-a451-ebb8d1e53a12">

## Done 
- if all requirements are met, it proceeds to the claim modal - after minted it shows the congrats 
<img width="533" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/6966009d-3b2f-4bdf-a630-45e4585a6c92">

thanks!

**Comment by vikiival** [comment]
It was fixed :)

<img width="896" alt="Screenshot 2024-01-18 at 13 38 37" src="https://github.com/kodadot/nft-gallery/assets/22471030/396809c7-35fd-46ad-aa6b-0b709b90adbf">
