### ISSUE TITLE
Make top collections on landing more engaging

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9045]
Briefly talked with @exezbcz about this and we should show only 4 results at first load to not bloat user with information and rest will be clickable by some arrows. 

We can expand the row with some information from collections like 
- Owners - 880
- Listed/Minted  12% 127 / 1024
I think https://www.tensor.trade/ is already doing it for the reason, I guess; sooner we deliver, the better, I guess. 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/1d82303f-189d-4be1-bc01-1303534615db)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/0d9c7560-ff9d-4444-83c0-33f71eb33a1e)

**Comment by JustLuuuu** [comment]
Just random feedback from one artist: the Platform is now more 'token' focussed and less the artist, on the homepage for example you see what project it is but not the artist. For the future we should also keep this in mind

**Comment by exezbcz** [comment]
@JustLuuuu noted and agree

the thing is that we don't have profile customization and on-chain identity costs some money.

**Comment by exezbcz** [comment]
continue to #9309
