### ISSUE TITLE
Add royalty to .cpu

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9054]
There was supposed to be royalty on .cpu collection.
Royalty: 5% 
to this address: 1VshyWpZUt8mgtWKgv9pgj8Gin99Wg5PCaDL3iCABixQbUP
Mentioned here:
- https://github.com/kodadot/ops-internal/issues/1271

Pls can you add it?

**Comment by roiLeo** [comment]
ops issue, please transfer it to the right repository

**Comment by vikiival** [comment]
Resolved, next time @JustLuuuu this is ops related issue :)
