### ISSUE TITLE
Translation in hn (hindi)

### ISSUE THREAD

**Issue by TouchstoneTheDev** [kodadot/nft-gallery#9055]
### Is your feature request related to a problem?

There is no hindi translation.

### Describe the solution you would like

I want to translate for hindi.

### Describe alternatives you have considered

hi.json is there but it's plain english or hi might not be hindi.
if it's i'll tranlate in hindi and make a PR.
So I hope it'll considered as a whole ! because hi.json is there but it's plain english or hi might not be hindi.

### Are there opened related issues?

no

**Comment by roiLeo** [comment]
Hi! thanks for the interest, but first we need to homogenize the keys in the translation file to make it easier to set up the json files for each language. we'll let you know once it's ready to be translated.

**Comment by TouchstoneTheDev** [comment]
hmm seriously tell me asap i have started trans :O  
btw the prev translation was not really a translation so my tranlation will be considered as a whole ?
Are this active ?
https://docs.kodadot.xyz/contrib-helpers.html#rewards

**Comment by yangwao** [comment]
Hey @TouchstoneTheDev, thank you. I think we have a lot of users from India, and that's something we can look up. I think current way is to edit hi.json 
- https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json

If this is would help thrive KodaDot in India, I'm up for it 

https://en.wikipedia.org/wiki/Languages_of_India?useskin=vector
> Hindi is the fastest growing language of India, followed by Kashmiri in the second place, with Meitei (officially called Manipuri) as well as Gujarati, in the third place, and Bengali in the fourth place, according to the 2011 census of India

**Comment by TouchstoneTheDev** [comment]
> Hi! thanks for the interest, but first we need to homogenize the keys in the translation file to make it easier to set up the json files for each language. we'll let you know once it's ready to be translated.

Hmm as I can see there is some diff in the line of translations betn hi and fr (prev translation contribution) . I guess it corresponds to the @roiLeo is talking about.
if yes why is it so ?

![image](https://github.com/kodadot/nft-gallery/assets/101004444/60bf3da7-6d7f-459d-9a5e-55195775c187)
![image](https://github.com/kodadot/nft-gallery/assets/101004444/26a8edea-69db-4c52-8c58-8529e657b6c4)

**Comment by yangwao** [comment]
> Which i hope should be considered as whole and label $$

Yes $$ if you done it all. 

$ if it's partial translate of most important phrases which are shown, like

- from start till https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L109
- sort - https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L413
- autoteleport - https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L1592
- https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L1566
- https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L1466

bonus points if you translate sidebar, drops and collections buy & sale, that's our target for now, thanks

**Comment by TouchstoneTheDev** [comment]
node >= 18.17
ain't working should directly open PR or first issue then PR ? nvm install 18
nvm use 18 is working

**Comment by TouchstoneTheDev** [comment]
i

> > Which i hope should be considered as whole and label $$
> 
> Yes $$ if you done it all.
> 
> $ if it's partial translate of most important phrases which are shown, like
> 
> * from start till https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L109
> * sort - https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L413
> * autoteleport - https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L1592
> * https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L1566
> * https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L1466
> 
> bonus points if you translate sidebar, drops and collections buy & sale, that's our target for now, thanks

Mission complete https://github.com/kodadot/nft-gallery/pull/9088#issue-2092536195

**Comment by TouchstoneTheDev** [comment]
> > Which i hope should be considered as whole and label $$
> 
> Yes $$ if you done it all.
> 
> $ if it's partial translate of most important phrases which are shown, like
> 
> * from start till https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L109
> * sort - https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L413
> * autoteleport - https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L1592
> * https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L1566
> * https://github.com/kodadot/nft-gallery/blob/main/locales/hi.json#L1466
> 
> bonus points if you translate sidebar, drops and collections buy & sale, that's our target for now, thanks

Hi this wasn't considered as $$ ? @yangwao
