### ISSUE TITLE
Cant click on item after filtering 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9071]
https://github.com/kodadot/nft-gallery/assets/90852205/9a726978-e4ec-4e27-a49d-ebd903d6c5ed

comment for the video: me hovering over it - i am clicking with my mouse

to reproduce: filter on profile based on collection, then click 

https://canary.kodadot.xyz/ahp/gallery/51-9

- this is the URL i get when clicking - but my UI stays on profile ....

![image](https://github.com/kodadot/nft-gallery/assets/90852205/0d2c00f7-1f12-4cb9-94ba-395489644a97)

**Comment by AnmolBansalDEV** [comment]
is there any way to test this without buying NFTs, have already set up the local repository?

**Comment by roiLeo** [comment]
wfm, could you double check

https://github.com/kodadot/nft-gallery/assets/9987732/a6bc8433-d5e3-4f25-9c07-c37ac66872d4
