### ISSUE TITLE
Introduce complexity labels to issues

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#908]
Seems it's time to bit help ppl identify issues that might be complex.

Basic concepts/contructs are how we will point out new coming devs which issues are for juniors vs seniors. Originally thought that "good first issue" was that tag, but I guess not many ppl gets it :)

**Comment by roiLeo** [comment]
ref #4445

**Comment by roiLeo** [comment]
<img width="621" alt="Capture d’écran 2023-08-16 à 11 05 27 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/e88f8508-731a-42ef-9f37-03af1ff575ae">
