### ISSUE TITLE
Remove offer event filter from activity at collection

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9087]
When we will start working on offers, we will re-add it again

![image](https://github.com/kodadot/nft-gallery/assets/5887929/b6829004-38c2-4be5-bb31-7265faa5a141)

**Comment by Jarsen136** [comment]
It's the same issue as https://github.com/kodadot/nft-gallery/issues/9072

**Comment by yangwao** [comment]
> It's the same issue

it's match
