### ISSUE TITLE
Scrolling on item when sidebar opened 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9091]
https://github.com/kodadot/nft-gallery/assets/90852205/ffbc8698-681f-43f9-9dd6-d2a77be2365c

**Comment by prachi00** [comment]
isnt this the expected behaviour?

**Comment by roiLeo** [comment]
> isnt this the expected behaviour?

for me it is, @exezbcz let us know if we should block content when sidebar are oppened. (I think this was an issue in the past)

**Comment by exezbcz** [comment]
> for me it is, @exezbcz let us know if we should block content when sidebar are oppened. (I think this was an issue in the past)

yeah, lets leave it like that if it caused issues
