### ISSUE TITLE
Buying que 🛒 checkout 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#910]
To have less interruptions from extension for user collecting NFTs, would be nice to have something like *🛒* and user can put it into que to get NFTs in batch.

That would require new view to show you what you plan to acquire, literally like in e-shop experience, check if NFTs are available before sending batch transaction.

Edit, seems I was anticipating this pretty right 
https://www.gem.xyz/collection/boredapeyachtclub/

![image](https://user-images.githubusercontent.com/5887929/162431416-6aadbec5-47bf-4006-93cf-caf2116c7640.png)

**Comment by yangwao** [comment]
So @exezbcz, are closing this one 👀
- #6371

**Comment by exezbcz** [comment]
@yangwao yes
