### ISSUE TITLE
Implement new drop worker

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#9104]
### Is your feature request related to a problem?

Many issues comes from the fact that we use really hacky version of drops worker. 
It can be safely deprecated.

### Task

Your task is to implement new worker called [fxart](https://fxart.kodadot.workers.dev)

and it works bit differently than the waifu worker

[The whole README is here](https://github.com/kodadot/private-workers/tree/main/fxart)

But TL;DR user first need to allocate the "ticket" which assigns him/her a serial number that can be used

If it is paid (price > 0) drop  you need to wait for transaction **to be successfully finished** (this does not work now :))

Once you get blocknumber and txhash of the TX it is safe to call finish api.

For free drop you will allocate, (there will be step to sign something but we do not have design for that yet) and call finish.

### Describe alternatives you have considered

Other apis were untouched.

If something is unclear/missing please hit me up or open issue in private-worker repo

**Comment by yangwao** [comment]
Hello, can someone @kodadot/internal-dev  pick up this please? It's bit urgent as we need to test things ahead and connect it with 
- https://github.com/kodadot/nft-gallery/issues/8862

**Comment by vikiival** [comment]
> @hassnian would be interested.

@hassnian does not have access to private workers

**Comment by yangwao** [comment]
> @hassnian does not have access to private workers

done

**Comment by preschian** [comment]
Maybe @hassnian wants to try to pick that up?

meanwhile, I ask some questions here: https://github.com/kodadot/private-workers/issues/42

**Comment by vikiival** [comment]
maybe TL;DR for this issue. 

* call `/drops/allocate/:id` - is in the readme 
result from api 

```json
{
  "result": {
    "id": "1",
    "name": "Name #1",
    "image": "ipfs://bafkreidm72homzr3rg5vdasm7kq5s4nuyq"
  }
}
```

* if drop is paid - then call `api.tx.nfts.mint`- params are already part of the code

* await previous step to be finished 

* call /drops/do/:id - body 
```json
{
  "sn": ${id that was returned from allocation},
  "txHash": "${tx hash from previous step}",
  "address": "${accountId}"
}
```


this is basically all that needs to be done to close this . cc @preschian
