### ISSUE TITLE
Aesthetic Alchemy: Identical mints

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9142]
These two mints are identical:
<img width="562" alt="Screenshot 2024-01-26 at 12 06 50" src="https://github.com/kodadot/nft-gallery/assets/104380776/ff45bb62-f351-4e0c-8149-53a62b1b3834">

[This one](https://kodadot.xyz/ahp/gallery/82-253) and t[his one](https://kodadot.xyz/ahp/gallery/82-252).

How did it happen?
This should not happen next time. Minted by the same address.

**Comment by prury** [comment]
https://canary.kodadot.xyz/ahk/gallery/379-18
https://canary.kodadot.xyz/ahk/gallery/379-19
![image](https://github.com/kodadot/nft-gallery/assets/36627808/7283290f-1f93-46aa-8c69-83431e676d5f)

**Comment by exezbcz** [comment]
is there anything we can do @vikiival ?

**Comment by vikiival** [comment]
The art is not same:

First does not respect that api needs to be called after success mint (cc @preschian)

![image](https://github.com/kodadot/nft-gallery/assets/22471030/6d9e5504-b94c-429c-8329-314cd867b75d)

Second is oki

![image](https://github.com/kodadot/nft-gallery/assets/22471030/67aed45e-cb28-41c8-a904-745b8f33c723)

Why you see the same pictures is that app does not respect the fact that should only use image data from the iframe and not the capture service cc @Jarsen136

**Comment by JustLuuuu** [comment]
Does it have solution?

**Comment by Jarsen136** [comment]
> Why you see the same pictures is that app does not respect the fact that should only use image data from the iframe and not the capture service cc @Jarsen136

I do not understand tbh. I guess it's because the user opens two tabs at the same time and then he mints twice with the same variation.

A possible solution would be to force random variation after every refresh. In other words, the solution is to remove the default value and always return a new one.
 wdyt ? @vikiival

**Comment by vikiival** [comment]
> I do not understand tbh.

You should never call 

https://github.com/kodadot/nft-gallery/blob/9fbb9e57ffb09b021e33399c4bb23d1884e6e0c8/composables/drop/useGenerativeDropMint.ts#L115

And the only way how to obtain image is this:

https://github.com/kodadot/nft-gallery/blob/9fbb9e57ffb09b021e33399c4bb23d1884e6e0c8/composables/drop/useGenerativeDropMint.ts#L57

>  In other words, the solution is to remove the default value and always return a new one.

There should be no default value imo

**Comment by Jarsen136** [comment]
> > I do not understand tbh.
> 
> You should never call
> 
> https://github.com/kodadot/nft-gallery/blob/9fbb9e57ffb09b021e33399c4bb23d1884e6e0c8/composables/drop/useGenerativeDropMint.ts#L115
> 
> And the only way how to obtain image is this:
> 
> https://github.com/kodadot/nft-gallery/blob/9fbb9e57ffb09b021e33399c4bb23d1884e6e0c8/composables/drop/useGenerativeDropMint.ts#L57
> 
> > In other words, the solution is to remove the default value and always return a new one.
> 
> There should be no default value imo

Will raise a PR for it
