### ISSUE TITLE
Signing modal consistency follow up

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9146]
> I think it's over drop and we can push it to beta so we can collectively test out
> Otherwise it would needs consistently maintain conflicts

If @exezbcz spot something can report or close this one 

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/9002#issuecomment-1911723289_

**Comment by exezbcz** [comment]
nothing found yet. Tested transfer, listing, buying
