### ISSUE TITLE
node >= 18.17 isn't working

### ISSUE THREAD

**Issue by TouchstoneTheDev** [kodadot/nft-gallery#9159]
### Is your feature request related to a problem?

node >= 18.17
 isn't working

### Describe the solution you would like

nvm use 18 is working
i would like to submit a PR to update "doc of project setup for first time"

### Describe alternatives you have considered

NA

### Are there opened related issues?

No

**Comment by yangwao** [comment]
Hello, we've recently switched to Node v20 

- https://github.com/kodadot/nft-gallery/pull/9141

you can help fix these two

[developers.kodadot.xyz/contributing/how-to-start-contributing.html#prerequisites](https://developers.kodadot.xyz/contributing/how-to-start-contributing.html#prerequisites)
[hello.kodadot.xyz/be-part-of-kodadot/join-as-a-developer/contributing-as-a-developer](https://hello.kodadot.xyz/be-part-of-kodadot/join-as-a-developer/contributing-as-a-developer)
