### ISSUE TITLE
Clicking on user pop-over breaks page redirection/refresh

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9178]
Access canary -> explore collections -> enter inside collection -> click on user popover to go to its profile -> try to switch tabs or click links on navbar: 

https://github.com/kodadot/nft-gallery/assets/36627808/d5520990-ebe6-42ed-8e3b-fd4ec1e14324

U is null

Same occurs when going to settings -> and then create -> nft

**Comment by Temidayo32** [comment]
@prury the error also occurs in kodadot.xyz

**Comment by prury** [comment]
> @prury the error also occurs in https://kodadot.xyz

oh, true, thank you!
