### ISSUE TITLE
Image does not work on collection view

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#9194]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

A lot of image is not shown on collection

### Please reproduce in steps

1. [GO to](https://kodadot.xyz/ahp/collection/87)
2. See that image is not loaded

### Expected Behavior

Image should be loaded

### Screenshots

<img width="1123" alt="Screenshot 2024-01-30 at 11 27 09" src="https://github.com/kodadot/nft-gallery/assets/22471030/a97cdfc4-f592-492e-bd8f-7ef28c86860e">

### Relevant log output

```shell
<img data-v-bfdc4f31="" src="https://kodadot.xyz/cdn-cgi/imagedelivery/jk5b6spi_m_-9qC4VTnjpg/bafybeifugoxy237lhqbnxvdewphivzqbgmvw676zgxwvcxxpdjzgeakeke/image.jpeg/h=88" height="88" alt="Florist's" data-nuxt-img="" srcset="https://kodadot.xyz/cdn-cgi/imagedelivery/jk5b6spi_m_-9qC4VTnjpg/bafybeifugoxy237lhqbnxvdewphivzqbgmvw676zgxwvcxxpdjzgeakeke/image.jpeg/h=176 2x" class="object-fit-cover">
```

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
wfm?
![image](https://github.com/kodadot/nft-gallery/assets/5887929/f803d519-9f57-4791-8dcb-5d504af46905)

**Comment by AnmolBansalDEV** [comment]
+1 wfm
![image](https://github.com/kodadot/nft-gallery/assets/86472377/54c16754-3eaf-4fdc-b718-8842cb594b76)

**Comment by vikiival** [comment]
Still relevant

https://kodadot.xyz/ahp/collection/89

**Comment by vikiival** [comment]
![IMG_4813](https://github.com/kodadot/nft-gallery/assets/22471030/c840037f-12d6-4b70-b431-34525775962b)

**Comment by vikiival** [comment]
Another one 

<img width="1680" alt="Screenshot 2024-02-05 at 19 55 51" src="https://github.com/kodadot/nft-gallery/assets/22471030/d6003451-3bbf-4f5f-bd04-dc3878099257">
