### ISSUE TITLE
Drops weekly reminder at drops page

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9200]
Usually, newcomers doesn't know we have regular Thursday drops at 3 pm and it would be nice to add a blank card with a way to add it to their calendar in some way with .ics for example or with Google cal to remind come back 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/13b3435b-0945-4efb-8cfc-0514a998d62c)

**Comment by exezbcz** [comment]
somewhere next to the drop heading it would be better IMO

**Comment by yangwao** [comment]
> somewhere next to the drop heading it would be better IMO 

Legit too, just somewhere to collect recurring users 😁

**Comment by yangwao** [comment]
- #9202

**Comment by exezbcz** [comment]
continue to: 
- #9329
