### ISSUE TITLE
Cookie popup covering menu 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9213]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/56d61168-b464-4a16-a0e9-f480a65466fb)
- the burger menu should be over the cookie banner, not under

**Comment by roiLeo** [comment]
hmmm.. I disagree with that

Cookie banner SHOULD be highest z-index

<details>
  <summary>some examples</summary>
  
  
<img width="436" alt="Capture d’écran 2024-01-31 à 4 30 18 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/b019244d-160d-4dfa-bf77-b02dc4a88c62">
<img width="337" alt="Capture d’écran 2024-01-31 à 4 29 00 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/84f47db8-7571-4587-b167-e32fff03c1dd">

  
</details>

**Comment by exezbcz** [comment]
@roiLeo fair, thanks!
