### ISSUE TITLE
Polkadot Awesomes NFT side -> "Profile" image doesn't appear

### ISSUE THREAD

**Issue by Vdotdot** [kodadot/nft-gallery#9216]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

<img width="396" alt="Screenshot 2024-01-31 at 22 23 22" src="https://github.com/kodadot/nft-gallery/assets/118908821/834f607a-68ea-4ddc-b8bd-89da4e219a80">

### Please reproduce in steps

See the image what I uploaded. Thanks!

### Expected Behavior

See the image what I uploaded. Thanks!

### What browsers are you seeing the problem on?

Desktop Chrome

### Are you logged in?

None

### Screenshots

See the image what I uploaded. Thanks!

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hassnian** [comment]
same as #9194
