### ISSUE TITLE
Add friendly Discord servers page

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#925]
Was thinking that we could add friendly Discord servers as their fandom cultures to KodaDot page

- hydra / basilisk
- chaosDAO
- PolkadotUniversity
- who is next?

**Comment by yangwao** [comment]
@cryptodamsky maybe you want to take look and we can then put it on the page! :)

**Comment by cryptodamsky** [comment]
> @cryptodamsky maybe you want to take look and we can then put it on the page! :)

I'll go through some favorite discords in dotsama community and post them here. This sounds good, we could establish some sort of connection with them, mark them as "friendly" and offer support regarding nfts or smth on our server. Would be also good if we were displayed somewhere on their page/server

**Comment by cryptodamsky** [comment]
Adding:

@mousedao
@polkadotmafia

**Comment by cryptodamsky** [comment]
Added https://twitter.com/Polkadot_FR to our discord as friendly discord

Contacted:
- mousedao
- polkadotmafia

**Comment by cryptodamsky** [comment]
So far it looks like this :)


On our side:
![fr](https://user-images.githubusercontent.com/92786519/151993865-b8cec659-77a2-4ac9-a36d-e5867deaa2c4.png)

On their side:
![fr2](https://user-images.githubusercontent.com/92786519/151994020-e9d720d2-1dd9-4c1e-87cd-320a5a360f23.png)
