### ISSUE TITLE
Generative carousel duplicated 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9261]
not sure what are the steps to reproduce

![image](https://github.com/kodadot/nft-gallery/assets/90852205/05d1f248-3ea8-4639-8d81-6dc24ed0dd28)

sometimes the page opens like this
- it is fixed after 10 seconds on the page

**Comment by yangwao** [comment]
Continue to 
- https://github.com/kodadot/nft-gallery/issues/9215
