### ISSUE TITLE
Action button in modal not full width 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9263]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/feb22138-527c-4369-a79b-0e0bad485238)
- button in the modal should fill the modal 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/9474a644-9ed9-4b35-9d0e-caf4ff4171bd)

**Comment by hassnian** [comment]
already fixed 😄 #9259
