### ISSUE TITLE
lot of notifications on profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9272]
1. buy something
2. after congrats go to your profile
3. boom

![image](https://github.com/kodadot/nft-gallery/assets/5887929/e697b867-f9ab-4bf8-958b-3c489d0f0f5a)

**Comment by exezbcz** [comment]
afaik @hassnian was solving this one in
- #9208

**Comment by hassnian** [comment]
> afaik @hassnian was solving this one in
> 
> - #9208 

yes, this is fixed there
