### ISSUE TITLE
Collection icon picture is not loading 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9287]
I suspect resize parameter is issue
- https://kodadot.xyz/ahp/collection/89

Maybe @preschian can have a look?

![image](https://github.com/kodadot/nft-gallery/assets/5887929/2b5f72f4-19a0-4b61-b630-ace65908bc42)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/7aff70d1-d751-4360-bb2a-5e30cc330e3e)

Probably similar one
---
- https://github.com/kodadot/nft-gallery/issues/9194
- https://github.com/kodadot/nft-gallery/issues/9216

**Comment by preschian** [comment]
> I suspect resize parameter is issue

checking. Yes, I guess so since the banner loads properly but not the icon
