### ISSUE TITLE
Motherboard collection banner and pfp

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9295]
could we please change the collection banner to this img? 

the current collection banner is quite dark and it does not reflect the nfts inside the collection that much 

- we put a design on a t-shirt, not a nft in the collection 

![motherboard332694248804297](https://github.com/kodadot/nft-gallery/assets/90852205/7bd1b0da-515a-4147-ba8c-623621ef7048)

question: does it have to be nft?

**Comment by JustLuuuu** [comment]
Good idea, it will look better, and also we have this design in the shop. So perfect.

**Comment by vikiival** [comment]
That is ops internal issue 👀
