### ISSUE TITLE
Implement new features to Drop

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9296]
SailWings: https://kodadot.xyz/ahp/drops/sailwings

The artist behind this collection told me that there is in the code implemented to his art:
- save art by "s" and 
- save frame by "v"

I tried it and it's not working on KodaDot for this collection. - **Maybe it will work once the art is minted? I tried it only on the drop page.**

Anyway, this is not the first time art has had this extra features. Some artists are implementing these things to code all the time, it saves various formats, changes the art, etc. 

1) Would be good to support this
2) Would be good to have it somewhere visible - not in description. As description on Koda is partially hidden. Fxhash has it in description. - which is meh. @exezbcz wdyt should it be part of desc?

<img width="1113" alt="Screenshot 2024-02-06 at 12 44 26" src="https://github.com/kodadot/nft-gallery/assets/104380776/507f871e-d033-420d-911a-1ea433a4bbc6">

**Comment by JustLuuuu** [comment]
Okay so we support this, thats amazing, so i guess now the only question is if we wanna be adding that to descriptions or just somewhere else, maybe in details of the NFT?

**Comment by JustLuuuu** [comment]
@preschian 

https://kodadot.xyz/ahp/gallery/91-64 I tried clicking s and v and it didn't do anything. I did in on item page and also after opening the art.

**Comment by preschian** [comment]
@JustLuuuu, if you click the link on "Animated Media", it will open the art in the new tab. Then, you can press the shortcut.

Currently, it still doesn't work to press the shortcut on the gallery detail page. does it work on fxhash gallery detail page?

<img width="554" alt="image" src="https://github.com/kodadot/nft-gallery/assets/734428/917b1c4f-3ae9-41a9-9528-eef25c338f80">

**Comment by JustLuuuu** [comment]
> Currently, it still doesn't work to press the shortcut on the gallery detail page. does it work on fxhash gallery detail page?

It does not. You are right. But they have this button "open" where they can do that. Which is more convenient than searching in details and clicking on animated media. Maybe we should have that too?

**Comment by preschian** [comment]
> But they have this button "open" where they can do that.

Yes, I think it would be nice if we had that too

**Comment by JustLuuuu** [comment]
Moving to https://github.com/kodadot/nft-gallery/issues/9355
