### ISSUE TITLE
Hardcode or add rest of old drops on landing?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9318]
on mobile is not an issue but on desktop is looks bad 
we can do one more release in 24h-48h once fixed  
<img width="1708" alt="image" src="https://github.com/kodadot/nft-gallery/assets/5887929/a5712bf8-11ff-4683-a219-3a6707be22b5">

**Comment by Temidayo32** [comment]
@yangwao I don't understand what the problem here is. 😕

**Comment by exezbcz** [comment]
any takers @kodadot/internal-dev 👀

**Comment by preschian** [comment]
Currently, I cannot access some of the databases through the dashboard. I will update it once it is up.

<img width="297" alt="Screenshot 2024-02-09 at 13 24 55" src="https://github.com/kodadot/nft-gallery/assets/734428/21a289b6-e8f6-441d-b9c7-13ceebd2f69d">

**Comment by vikiival** [comment]
I see it on your screenshot 👀. 

Cc may @yangwao can check your permissions. 

![image](https://github.com/kodadot/nft-gallery/assets/22471030/fe3433f7-6a39-4a79-b71f-f2e904727fd3)

**Comment by preschian** [comment]
seems like down (regional), no?

but I don't see the down infos in here https://www.cloudflarestatus.com/

**Comment by preschian** [comment]
added florist, but it shows "Coming Soon"

it was a different schema, I guess. checking

**Comment by vikiival** [comment]
> added florist, but it shows "Coming Soon"
> 
> 
> 
> it was a different schema, I guess. checking

You can use starting_at field in new schema 👀
