### ISSUE TITLE
Drop page loading indicator 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9320]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/f6a65825-953c-44dc-a0f8-ce36036343d2)
- should be probably only disabled for few seconds till it generates

**Comment by exezbcz** [comment]
like this one production
<img width="583" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/b5c313e3-df13-4056-b7fa-8cd38b4eaee9">

**Comment by prury** [comment]
also loading state for when this button is like that: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/a170cab2-3295-42dd-85e9-9925d872fa6c)

maybe the three dots loading, wdyt

**Comment by exezbcz** [comment]
@prury yeah, on my todo
