### ISSUE TITLE
SailWings: Preview not visible after minting

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9324]
After minting NFT from the latest drop, preview after minting was not loaded. After waiting it did not change.

<img width="1163" alt="Screenshot 2024-02-08 at 15 05 13" src="https://github.com/kodadot/nft-gallery/assets/104380776/0748816c-62bd-4670-bb13-1ee2909a030e">

**Comment by preschian** [comment]
old issue, already fixed
