### ISSUE TITLE
SailWings: preview of NFT #23 not working

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9326]
[This NFT](https://kodadot.xyz/ahp/gallery/91-23) preview looks like this:
<img width="603" alt="Screenshot 2024-02-08 at 16 18 44" src="https://github.com/kodadot/nft-gallery/assets/104380776/3c714905-ad4c-4c2d-b1a2-c249b286a7da">

NFT itself looks different - its loaded

**Comment by roiLeo** [comment]
close as completed
<img width="1398" alt="Capture d’écran 2024-02-15 à 9 49 13 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/f2237a91-306d-42ba-b7d8-69b28467cc64">
