### ISSUE TITLE
Serial number not based on nfts minted 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9327]
<img width="548" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/c07c5e6b-9011-4282-bf80-22e8cb5ff1c9">

<img width="483" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/7cd99686-26f6-4ad8-99c6-6912c50b7432">

so there is 39 nfts minted

<img width="311" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/12161499-a9f6-46e6-bbf5-83596d10d72c">
and this is serial number 50

**Comment by roiLeo** [comment]
duplicate #9328 see https://github.com/kodadot/nft-gallery/issues/9328#issuecomment-1935434409
