### ISSUE TITLE
SailWing: Numbering is off

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9328]
We have 38 NFTs in collection but we are already on number 49. Numbering is not working properly, some numbers are skipped.  <img width="1178" alt="Screenshot 2024-02-08 at 16 22 54" src="https://github.com/kodadot/nft-gallery/assets/104380776/e28a071b-cf6c-4d70-90ca-b5901ce8344c">

We are missing some numbers - 6,7,8,10,11..... Where did they go?

**Comment by roiLeo** [comment]
I don't think we can do anything about that since it got already minted

**Comment by JustLuuuu** [comment]
> I don't think we can do anything about that since it got already minted

isnt is possible to add missing numbers with next mints? 🤔
