### ISSUE TITLE
SailWing: broken previews

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9335]
![image](https://github.com/kodadot/nft-gallery/assets/5887929/0c917df4-cc1b-439d-be02-56daa45a9b3a)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/d5941ff0-83b6-4f86-a03c-1539c9ec80a9)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/a250b06f-3a13-4681-b0df-5f7bbc46f4e9)

**Comment by vikiival** [comment]
It is a bug on the frontend side. App should not allow you to mint if you do not have preview. 


But I will fix the broken previews

**Comment by roiLeo** [comment]
> But I will fix the broken previews

is there an endpoint to force reload preview?

**Comment by vikiival** [comment]
> > But I will fix the broken previews
> 
> 
> 
> is there an endpoint to force reload preview?
> 

Nope but we can open an issue for that in private workers 👀

**Comment by vikiival** [comment]
<img width="464" alt="Screenshot 2024-02-14 at 13 49 03" src="https://github.com/kodadot/nft-gallery/assets/22471030/a192d35a-d715-441b-a800-6ccb68f50d46">
<img width="486" alt="Screenshot 2024-02-14 at 13 48 53" src="https://github.com/kodadot/nft-gallery/assets/22471030/13c51999-135d-46fb-af05-b6eeaa50cb8e">
