### ISSUE TITLE
Where is my Sale notification?

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9363]
I sold an NFT and this is how the platform looked like when I logged in:
<img width="1442" alt="Screenshot 2024-02-10 at 21 14 08" src="https://github.com/kodadot/nft-gallery/assets/104380776/13c04757-d181-4651-b910-843a3a2cc769">

### Where is my notification?
Where is my notification or anything that indicates that I had sale? I had to click on the bell to see the sale:

<img width="1445" alt="Screenshot 2024-02-10 at 21 14 26" src="https://github.com/kodadot/nft-gallery/assets/104380776/5dcb1a40-f19f-4c63-afd5-a70d29e2f2da">

**Comment by JustLuuuu** [comment]
tested it with a different account and it's not working.

**Comment by hassnian** [comment]
@JustLuuuu from what I can see there wasn't a sale notification to begin with, so this would be a feature 

regarding the count, should it show all events? , most likely not right , maybe only recent ones (7 days or some period of time), or show non-dismissed events 

atm we don't have a way to dismiss an event

I was thinking something like this , cc @exezbcz  

![CleanShot 2024-02-11 at 08 22 37](https://github.com/kodadot/nft-gallery/assets/44554284/4e6df42f-bddd-44bf-9df7-0fd94e31115c)

**Comment by hassnian** [comment]
talked with exezbcz and **onchain notifications** are no longer supported
