### ISSUE TITLE
Speed up loading of drop cards on landing

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9369]
Sometimes it's there like 5s and I'm on 1Gbit optics 😅 

If you can come up with some "caching" idea, it seems like those "edge" workers are always waiting for something ?
cc @preschian @vikiival 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/630c58c5-f9e8-4f6e-a65b-b59876ae8caf)

**Comment by vikiival** [comment]
Response from workers is in miliseconds. 

I guess that is it is waiting for response from image worker. 

Moreover we can give it higher loading priority and lazy load other cards.

**Comment by exezbcz** [comment]
ref: 
- https://github.com/kodadot/nft-gallery/issues/9349

**Comment by preschian** [comment]
> If you can come up with some "caching" idea

This is what I thought, also. Currently, the response time from fxart is roughly 700ms. I created a new issue here: https://github.com/kodadot/private-workers/issues/58.

<img width="497" alt="image" src="https://github.com/kodadot/nft-gallery/assets/734428/da2006a6-a018-4cb4-89f1-572128fc8256">

---

Try to disable one of the endpoints; it will always show a loading skeleton.

<img width="508" alt="image" src="https://github.com/kodadot/nft-gallery/assets/734428/066ebaa6-fc4e-4a42-92fd-607d0665d87a">
