### ISSUE TITLE
Please remove Stellate logo from footer

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9400]
![image](https://github.com/kodadot/nft-gallery/assets/5887929/d2e2ca80-2a10-4c4f-add9-da1c86cb8264)

we will be using https://api.kodadot.xyz

**Comment by prachi00** [comment]
@yangwao @roiLeo where is the code for this page? is it a different repo?

**Comment by Jarsen136** [comment]
> where is the code for this page? is it a different repo?

It's at the footer @prachi00 
<img width="1353" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/ae3cc2b6-2053-46eb-9cb6-aa9e761d9834">

**Comment by prachi00** [comment]
> > where is the code for this page? is it a different repo?
> 
> It's at the footer @prachi00 <img alt="image" width="1353" src="https://private-user-images.githubusercontent.com/31397967/304876526-ae3cc2b6-2053-46eb-9cb6-aa9e761d9834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NTU2MTgsIm5iZiI6MTcwNzk1NTMxOCwicGF0aCI6Ii8zMTM5Nzk2Ny8zMDQ4NzY1MjYtYWUzY2MyYjYtMjA1My00NmViLTljYjYtYWE5ZTc2MWQ5ODM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDAwMDE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNjAwOWZlYTQzMzkyZjc0ZmEwYTg4OTViMDdkYzk2NTk3ZTk2ZDk0YzMwMTQ1MGU2MmZiYzA3MzgxNjc2OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FSjNV_0SZDNgfmN5aj_-Lns4oBlrvksxSvh1FjQ8bek">

oh right, my bad 😅
