### ISSUE TITLE
Auto teleport info styling 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9402]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/118ed976-3963-443a-b57b-5e2853ff7b30)
not sure why there are two values

design: 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/b084d405-1719-4e73-933f-3cae72716f32)

https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=4354-15507&mode=design&t=F3RttyIQTA1B5Yq8-11

**Comment by Jarsen136** [comment]
It works for me. Maybe effected by chrome extension?

<img width="247" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/1f3bf760-d7fb-4264-805c-9fee7426fe36">
