### ISSUE TITLE
Claimed check failed on Holder of drop 

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/nft-gallery#9404]
After digging into the code, I discovered that the existing claim check no longer worked. 

It would cause several bugs:
1. incorrect available minted amount on holder of drop page. (related to https://github.com/kodadot/nft-gallery/issues/9390)
2. minting error when try to minting multiple holder of drop. (related to https://github.com/kodadot/private-workers/issues/64)

Here is method to claimed check.
<img width="417" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/c3d423a1-beb3-430d-ac6a-3d1b4cd8f7f3">

It always returns null regardless of which NFT is checked.
<img width="509" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/02e9d723-d100-41dc-9871-a548a8d9398b">

<img width="1198" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/5e2ad5e0-f873-42be-bfa0-1953e98fe115">

## expect solution
Find the correct method to check if the NFT has been claimed on the holderOf drops page.

**Comment by Jarsen136** [comment]
> ## expect solution
> Find the correct method to check if the NFT has been claimed on the holderOf drops page.

@vikiival  Do you have any idea ?

**Comment by vikiival** [comment]
So I got the last value (0x003300000 vs 0x0079010000)

![image](https://github.com/kodadot/nft-gallery/assets/22471030/b4828337-871c-4b69-b244-be1bd5c82e5f)
![image](https://github.com/kodadot/nft-gallery/assets/22471030/904cacd5-d5f2-499f-806e-a124c5b2da47)

Read carefully:
1. Convert the collection to hex
2. Construct the number - if is length 2 - pad it right with two zeros
If the length is 3 - pad it right with one zero and put the first digit in the end
If the lenght is 4 - swap the pair  - aka first two letters go last 
3. When you have number from step two construct the full format - 0x00${theMagic}0000
