### ISSUE TITLE
Can we lift minting per one address for holderOf?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9421]
Can we lift that limit, to 30 per address, as default?

 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/69d58aff-d0e0-4a05-b0c5-3b7ef9c32d08)

**Comment by Jarsen136** [comment]
<img width="236" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/0f70af1c-24de-4d7e-a6ed-07af31460380">

`28` is the total amount of the `holderOf` nfts that you have
`10` is the amount of ntfts that are not been used for claim drop. 

In short, there is no minting limit for per address, as long as you have enough nfts that not been used.

**Comment by Jarsen136** [comment]
> > `10` is the amount of ntfts that are not been used for claim drop.
> 
> well thing is that was when was drop launched I had this and haven't minted any. So how it's possible?
> 
> After mint 10 of them I can't mint :D
> 
> ![image](https://private-user-images.githubusercontent.com/5887929/305110789-62ff3734-7a31-4e36-9c78-7992c53ed244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDgzOTgsIm5iZiI6MTcwODAwODA5OCwicGF0aCI6Ii81ODg3OTI5LzMwNTExMDc4OS02MmZmMzczNC03YTMxLTRlMzYtOWM3OC03OTkyYzUzZWQyNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMTQ0MTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzVlMTllYmM4Mzk1YjhmZGQ4OGM1ZGUwNmM5NTAzNzQxOGU3MjBjMTRkNzEyODRmYmNmZDA4OTczNDkxNTc3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5ZEKwXXi44nGPJO4OmUCf3IaQOtbap0xH64qiAL1Nxs)

Oh I found the bug. Thanks for testing : )
