### ISSUE TITLE
Restart Generation Animation

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9429]
The only way how to restart [Echo animation](https://kodadot.xyz/ahp/gallery/95-89) is to refresh the page.
Consider have an option to refresh animation in the other way - maybe add a button play. or something

https://github.com/kodadot/nft-gallery/assets/104380776/185a1273-a584-4e05-8e28-53f49f8cf769

**Comment by exezbcz** [comment]
continue to
- https://github.com/kodadot/nft-gallery/issues/9737
