### ISSUE TITLE
Some Echo are animating, some are not 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9430]
ah, seems like they take time to load and they start to animating? 
maybe cache?
also maybe button to restart animation?

not
-
- https://canary.kodadot.xyz/ahp/gallery/95-89
- https://canary.kodadot.xyz/ahp/gallery/95-93
- https://canary.kodadot.xyz/ahp/gallery/95-39
- https://canary.kodadot.xyz/ahp/gallery/95-29

ok
-
- https://canary.kodadot.xyz/ahp/gallery/95-78
- https://canary.kodadot.xyz/ahp/gallery/95-88
- https://canary.kodadot.xyz/ahp/gallery/95-90

**Comment by vikiival** [comment]
Can someone please describe the bug? 

https://github.com/kodadot/nft-gallery/assets/22471030/7750d788-7b13-4746-ace0-d85ce2021558

**Comment by JustLuuuu** [comment]
When you opened random NFT, some of them were static. Different people had different NFTs that were static. But I tested it again and it seems working.

**Comment by preschian** [comment]
fixed
