### ISSUE TITLE
Reviewers not being assigned to PRs

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9479]
manually assigned some to recent PRs

**Comment by yangwao** [comment]
wondering why, I haven't changed anything regarding to this

**Comment by preschian** [comment]
need some access?

<img width="667" alt="image" src="https://github.com/kodadot/nft-gallery/assets/734428/5a01d9ff-1708-4867-9bcf-c4c6f6637c63">

**Comment by yangwao** [comment]
changed it to write, let's see

**Comment by prury** [comment]
i think now only one person is being assigned

**Comment by yangwao** [comment]
This is already working I guess?

**Comment by prury** [comment]
> This is already working I guess?

was not working super well, but I'll close it for now and keep an eye on it

**Comment by prury** [comment]
sometimes it only assigns one reviewer,  still happening

**Comment by yangwao** [comment]
> sometimes it only assigns one reviewer, still happening

could be some load balancing, let me look

**Comment by yangwao** [comment]
Ah switched from round-robin to load balance and brought @vikiival @daiagi back to the game 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/05eaacdb-732d-4ecf-83ff-7d2abeea4e80)

lmk @prury if it's good now

**Comment by prury** [comment]
all good now
