### ISSUE TITLE
Drop shows incorrect remaining mint number 

### ISSUE THREAD

**Issue by RedAlchemistia** [kodadot/nft-gallery#9493]
### What happened?

when i go to mint drop page and select any given drop i see that the value of remaining drop is incorrect
![show of minted art bug 2](https://github.com/kodadot/nft-gallery/assets/157763905/bb6a80e8-c937-499a-9e6c-14bfc30d6f2d)
![show remaining mint bug 1](https://github.com/kodadot/nft-gallery/assets/157763905/441ad09f-f510-4154-8c82-98d74bad184e)

### Please reproduce in steps

go to drop page - eg: click sailwings drop here  https://kodadot.xyz/ahp/drops/sailwings
after clicking sailwings drop we see that there is a false display of remaining number of drop
and also to verify we can go to collection page to see the number of drop being minted out 

### Expected Behavior

display of remaining number of drop in the drop page should not lag behind

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

![show of minted art bug 2](https://github.com/kodadot/nft-gallery/assets/157763905/e068a6ec-f826-448e-8fea-2936d1c4753f)
![show remaining mint bug 1](https://github.com/kodadot/nft-gallery/assets/157763905/78d3d23c-010b-4cd6-a05c-87fbad8722d7)

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prury** [comment]
thank you for opening the issue, we are currently trying to fix it for the next drop
(from manually counting the nfts i reached the amount of 151)
the problem itself its the generated serial number after the nfts, its not truly sequential

**Comment by yangwao** [comment]
which issue / pr is it?

**Comment by prury** [comment]
> which issue / pr is it?

https://github.com/kodadot/private-workers/issues/57
could not find the issue viki is talking about tho

**Comment by JustLuuuu** [comment]
- https://github.com/kodadot/nft-gallery/issues/9328

**Comment by RedAlchemistia** [comment]
sailwing nft numbering is printed correctly, some nft skipped serial numbering
