### ISSUE TITLE
LEADLIGHT: Change collection banner

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9504]
Please change the banner picture of [this collection](https://canary.kodadot.xyz/ahp/drops/fields). Here is a cover pic with 5760x2240 res.

![cover 5760x2240](https://github.com/kodadot/nft-gallery/assets/104380776/14467e4e-fe5c-4f2f-ab71-f490e508426b)

Please ideally before the drop date this Thursday.

**Comment by vikiival** [comment]
For collection or drop?
![image](https://github.com/kodadot/nft-gallery/assets/22471030/c0424755-bded-4ced-a900-e86e9c067175)
