### ISSUE TITLE
LEADLIGHT: Change details on landing

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9507]
As we renamed collection FIELDS to LEADLIGHT, please can we update also the landing page? It shows the old name.. but once you click on it Drop page already is updated to the new name and details.

<img width="1703" alt="Screenshot 2024-02-21 at 13 11 16" src="https://github.com/kodadot/nft-gallery/assets/104380776/ef357e76-96c9-4427-9427-cce4007177e5">

Pic that can be used for banner (it was changed too)
![cover 5760x2240](https://github.com/kodadot/nft-gallery/assets/104380776/990e13cd-18e1-4b0a-9257-d564d47cdfd2)

**Comment by vikiival** [comment]
![Screenshot 2024-02-22 at 00 01 52](https://github.com/kodadot/nft-gallery/assets/22471030/2a07e7f4-e85e-4d2c-9256-1e83578a439f)
