### ISSUE TITLE
Linkable history chart to transactions

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#952]
Would be amazing, especially for various investigations, to link **date to block** to block explorer, like Subscan for record and clarity in data.

This is how looks subscan link https://kusama.subscan.io/block/10059886

![image](https://user-images.githubusercontent.com/5887929/139246281-e9a5fd58-eabf-486d-b322-8969da02c29b.png)

**Comment by yangwao** [comment]
@vikiival  👀

**Comment by vikiival** [comment]
Closed in #1211
