### ISSUE TITLE
Code checker Variation loading time 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9538]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/9856de14-712d-43d7-9eb7-2497f60e23e2)
![telegram-cloud-photo-size-5-6253355706350681453-y](https://github.com/kodadot/nft-gallery/assets/90852205/e75f4d5f-c63f-4918-9674-7f54cdd925e2)
the loading time is loading forever 

probably cc @daiagi 👀 

we don't have the art file, will try to obtain it

**Comment by yangwao** [comment]
> the loading time is loading forever

can you try with them this one? 
https://canary-netlify.kodadot.xyz/code-checker

**Comment by exezbcz** [comment]
@yangwao 


@daiagi sent him this one https://deploy-preview-9394--koda-canary.netlify.app/code-checker and it works

**Comment by daiagi** [comment]
closing
was fixed by https://github.com/kodadot/workers/pull/258
