### ISSUE TITLE
older Holderof drops not showing requirements

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9554]
As far as i remember, https://canary.kodadot.xyz/ahp/drops/chroma was a holderof drop, yet, if i navigate to it, it has just an empty public sale state

![image](https://github.com/kodadot/nft-gallery/assets/36627808/86e74f14-eee9-4c1b-b830-8c61392f7691)

**Comment by Jarsen136** [comment]
<img width="241" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/0e062ce1-a6c4-42fb-983e-c5df7a7e0921">

data issue? cc @preschian

**Comment by preschian** [comment]
> data issue? cc @preschian

fixed, correct, migration db issue
