### ISSUE TITLE
Add farcaster icon to footer

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9576]
Link to https://warpcast.com/~/channel/koda

![Screenshot_20240228_112835_Chrome.png](https://github.com/kodadot/nft-gallery/assets/5887929/62261971-4c66-4989-9e1e-5960816e3de0)

**Comment by wangyangjun** [comment]
@yangwao I am a little confused about this ticket as I am quite new here. Do we need add an icon in footer of website https://kodadot.xyz/ which links to https://warpcast.com/~/channel/koda? The icon should be something like? 
<img width="56" alt="Screenshot 2024-02-28 at 21 09 21" src="https://github.com/kodadot/nft-gallery/assets/3423330/3c9b7415-00c9-4afa-b4bd-a1e7dae367d2">

So the location of the new icon should be under `Join Our Community`. Is that right? 
<img width="1635" alt="Screenshot 2024-02-28 at 21 06 59" src="https://github.com/kodadot/nft-gallery/assets/3423330/58377b00-aa8f-48fb-9a7a-e4981bc170a7">

**Comment by yangwao** [comment]
Yes, you're right, yet use an icon for Farcaster.

One you've sent is for the client "Warpcast" most popular currently:)

**Comment by wangyangjun** [comment]
@yangwao How could I assign this issue to myself?
