### ISSUE TITLE
farcaster icon at light mode

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9582]
icon at light mode
<img width="383" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/1a538c9d-35b5-40a7-a8cf-e95438aa4752">

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/9578#issuecomment-1969991388_

**Comment by iMac7** [comment]
:wave:
