### ISSUE TITLE
History Chart redesign

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#961]
- Add emojis for actions
- 🖼   MINT 
- 📰   LIST 
- 🤝   BUY 
- ✈️  SEND 
- 🎁  GIFT 
- 🔥  BURN 

- Add dropdown show only particular actions as more traded NFTs will have huge history
 
![image](https://user-images.githubusercontent.com/5887929/139443817-35e34a12-a06b-4283-91ee-b6081a46b74a.png)

Adoptions come from https://hic.af/objkt/476690

**Comment by roiLeo** [comment]
We are currently renaming interaction label:

(OG interaction => Kodadot interaction)
MINTNFT => CREATE
LIST => SET-PRICE
SEND => GIFT
CONSUME => BURNT 

Should we keep it like this?
What emoji for MINTNFT => CREATE?
Where would be the dropdown?

**Comment by yangwao** [comment]
> We are currently renaming interaction label:
> 
> (OG interaction => Kodadot interaction) MINTNFT => CREATE LIST => SET-PRICE SEND => GIFT CONSUME => BURN
> 
> Should we keep it like this? 

Yup, let's keep it

What emoji for MINTNFT => CREATE? Where would be the dropdown?

🖼

Updated desc

@vikiival has suggestion we can put labels as translations
