### ISSUE TITLE
Numbering is not working - POAP ETHDEnver

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9616]
Again this issue, will be reporting it everytime it appears till someone smart solves it. ❤️

It was POAP for ETHDenver event.
**This collection**: https://kodadot.xyz/ahp/collection/107
**NFTs in collection**: 833
**Numbering on NFTs**: we got to number #1121

This makes it ugly and confusing af.

**Comment by exezbcz** [comment]
> ugly

not sure about this one, but yeah, frequent issue :D

**Comment by vikiival** [comment]
No longer a thing
