### ISSUE TITLE
Integrate Estuary and use it instead Pinata

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#963]
We've got invited in Lisbon to use Estuary https://estuary.tech/

Bigger files and more reliable storage with more gateways than Pinata, we've bet it should be cheaper.

**Comment by vikiival** [comment]
We are quite limited with the current key generation.
But there should be an update.
<img width="865" alt="Screenshot 2021-10-31 at 15 21 45" src="https://user-images.githubusercontent.com/22471030/139588096-9af89567-d1d1-47a1-b981-6751961c2ef6.png">
