### ISSUE TITLE
move minting logic out of components

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#9636]
minting logic and associated functions (submitRaffle, allocateRaffle for example) are repeated between `Generative`, `PaidGenerative` and `holderOfGenerative`

extract as much as possible to reusable utils / composable and re use across components

**Comment by Temidayo32** [comment]
I will be interested in working on this issue once it is ready to be worked on.

**Comment by yangwao** [comment]
I would prefer someone from @kodadot/internal-dev as they're well familiar with codebase

**Comment by Temidayo32** [comment]
@yangwao  Okay, alright. Thanks for the information.

**Comment by yangwao** [comment]
@daiagi, do you plan to start working on it? As I see it a blocker for 
- https://github.com/kodadot/nft-gallery/pull/9711

I would like to see it done or someone else can take over

**Comment by daiagi** [comment]
Mmm I don't think it's a blocker
But yes. I'll take care of it

**Comment by yangwao** [comment]
> Mmm I don't think it's a blocker

ah I thought this needs to be done against branch 
`https://github.com/kodadot/nft-gallery/tree/drops-refactor` and then needs to be merged main.

If it can be done parallel, there is no rush.

**Comment by daiagi** [comment]
@yangwao 
i suggest merging `drops-refactor` into main after #9709 

majority of refactor is done, rest, including this, can continue on main

**Comment by yangwao** [comment]
@daiagi let's finish, it won't go for the upcoming release, so you have a free runway for this

**Comment by daiagi** [comment]
Can close this
@hassnian already extracted logic out in massmint pr and leftovers are handled in #9750
