### ISSUE TITLE
No success modal and can only mint once message

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9649]
https://github.com/kodadot/nft-gallery/assets/36627808/d82f3e7b-4ba4-428a-b256-c966a7204ab4

**Comment by vikiival** [comment]
What is the http status from the reuquest?

**Comment by vikiival** [comment]
Cc @kodadot/internal-dev pls

**Comment by Jarsen136** [comment]
wfm

<img width="447" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/9ff5c0a5-ca6a-4bec-b6bd-759b5c45516e">

**Comment by prury** [comment]
> wfm

it is not always tho, intermittent bug

**Comment by daiagi** [comment]
>not seem relevant anymore

not relevant
the error could come from any one of

- `allocateClaim`
- `fetchDropStatus`
- `fetchNft`

**Comment by vikiival** [comment]
See that readme was left unread 😌

![image](https://github.com/kodadot/nft-gallery/assets/22471030/589d9cd1-8339-4802-9ebc-13e08d26640a)

**Comment by daiagi** [comment]
@vikiival @preschian 

409 mint already claimed

![image](https://github.com/kodadot/nft-gallery/assets/22791238/14d3ce0c-d2bd-4b89-95bb-5db8573857a9)


request:

```json
{
"sn":61,
"txHash":"0xf12d93137091ceefb3b915ad0d023856c9497e2ae70b28051743cd99e6b25c24",
"address":"DBVPJeM91LawsF8dqphFYmdPwtxfpXqbgBtVaxn41CT3Amn"
}
```

**Comment by vikiival** [comment]
> 409 mint already claimed

So it means that reqest to assign metadata for particular NFT has been already sent. 
Sending it again would result into overwriting the metadata.

**Comment by preschian** [comment]
Oh, maybe there is some glitch on the UI that calls the endpoint multiple times? On allocate claim, we already filter sn with `claimed === 0`

**Comment by vikiival** [comment]
> Oh, maybe there is some glitch on the UI that calls the endpoint multiple times?

Highly possible :)
