### ISSUE TITLE
The ( HOW DO I SET IDENTITY? ) Link doesn't take you anywhere

### ISSUE THREAD

**Issue by onerawartist** [kodadot/nft-gallery#965]
the last question on this page:

https://nft.kodadot.xyz/rmrk/faq
take you to this link:

https://guide.kusama.network/docs/en/mirror-learn-identity#docsNav

error: Page Not Found

-------------
im not a coder, but i think this is important for new people on the platform

**Comment by yangwao** [comment]
go to the https://kodadot.xyz/identity and you can set identity right away from kodadot now 

![image](https://user-images.githubusercontent.com/5887929/139586641-eabf4bb6-6182-4ba0-b27a-6667d2b4aa48.png)
