### ISSUE TITLE
Migrator: Add Link 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9664]
Link in FAQ page 4/4 not working

https://github.com/kodadot/nft-gallery/assets/104380776/7a421fbb-c13b-4b94-896a-66cde11ffdd1

**Comment by exezbcz** [comment]
@JustLuuuu there was meant to be hello page

**Comment by JustLuuuu** [comment]
ok pls add this link there: https://hello.kodadot.xyz/multi-chain/migrator
