### ISSUE TITLE
Drop sequence not correct

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9669]
![image](https://github.com/kodadot/nft-gallery/assets/36627808/7be07f1c-42db-4958-8667-829945dd79d2)

**Comment by vikiival** [comment]
Cc @preschian

**Comment by preschian** [comment]
This is expected in the current architecture. For now, by default, it is sorted from the newest. Whoever claims it first will be the earliest. I think I should revive this PR: https://github.com/kodadot/nft-gallery/pull/9551. You can sort by serial number in that PR

<img width="1414" alt="Screenshot 2024-03-08 at 08 10 29" src="https://github.com/kodadot/nft-gallery/assets/734428/edea3c5c-84ca-466c-bbc0-78407257da78">

You can see the same result in my test here: https://github.com/kodadot/private-workers/pull/76#issuecomment-1956622224.

**Comment by prury** [comment]
> This is expected in the current architecture. For now, by default, it is sorted from the newest. Whoever claims it first will be the earliest. I think I should revive this PR: #9551. You can sort by serial number in that PR
> <img alt="Screenshot 2024-03-08 at 08 10 29" width="1414" src="https://private-user-images.githubusercontent.com/734428/311084671-edea3c5c-84ca-466c-bbc0-78407257da78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MDMzOTMsIm5iZiI6MTcwOTkwMzA5MywicGF0aCI6Ii83MzQ0MjgvMzExMDg0NjcxLWVkZWEzYzVjLTg0Y2EtNDY2Yy1iYmMwLTc4NDA3MjU3ZGE3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxMzA0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmNlMzc3MTg2NGY3MjBhNGY1M2JiYzRlMmFhMGE5MjI4MTBjNDlmZmJkMTMxZDNlYzYxM2I3ODI0NjliMmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KMDErCc9Ec-I8u1phnOZ-rAkPyCA2E8KrAwRJvDIblc">
> 
> You can see the same result in my test here: [kodadot/private-workers#76 (comment)](https://github.com/kodadot/private-workers/pull/76#issuecomment-1956622224).

understood, thanks for explaining

**Comment by vikiival** [comment]
Still there are few serial nubmers missing.

**Comment by prury** [comment]
> Still there are few serial nubmers missing.

which ones viki? 
counted them on preschian PR and it seems ok: 
https://deploy-preview-9675--koda-canary.netlify.app/ahp/drops/motifs?sort=sn_ASC

**Comment by vikiival** [comment]
Number five was missing back then


![Screenshot 2024-03-08 at 22 10 49](https://github.com/kodadot/nft-gallery/assets/22471030/29ca8380-e408-42e5-8500-50177eae86de)
