### ISSUE TITLE
Two bugs at drop page currently 8/3/2024

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9678]
I've tried after mint click [list] and dialog disappeared 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/5b376e77-a613-4974-ac7b-42eddfc6b4f3)

yet when I tried to mint new iteration, the same identical dialogue with same mint surfaced 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/192d3ed0-f1e5-4f91-a598-f158ea69d17e)

Here after minting dialog disappeared 
and when tried mint new variation, shows previous mint

https://github.com/kodadot/nft-gallery/assets/5887929/98b03559-7a93-49e4-9bc7-df455810254f

Listing is easily replicable, @prury is there report for that or PR for this one?

https://github.com/kodadot/nft-gallery/assets/5887929/9d4446b8-40da-4819-ac3d-f8b06216aeb2

**Comment by prury** [comment]
listing modal: 
- https://github.com/kodadot/nft-gallery/issues/9670
- https://github.com/kodadot/nft-gallery/pull/9673

**Comment by yangwao** [comment]
> yesterday release was in a hurry

Why hurry? 
Where it broke, can you point out in code?
We always know the release date ahead. 
It's every Thursday, previous weeks it was Wednesdays, but seems some things have been missing.

**Comment by prury** [comment]
> > yesterday release was in a hurry
> 
> Why hurry? Where it broke, can you point out in code? We always know the release date ahead. It's every Thursday, previous weeks it was Wednesdays, but seems some things have been missing.

oh i mean, hurry on our side to deliver, release date is fine

came from here unfortunately: 
- https://github.com/kodadot/nft-gallery/pull/9650

**Comment by yangwao** [comment]
> bug was solved on other pages but it affected drops

![image](https://github.com/kodadot/nft-gallery/assets/5887929/d58e233c-ce76-4791-bcb3-43ff6a5e48a8)

Do we reflect this scope in the tests? If not, let's add it to prevent this in the future, please 🙏🏾

**Comment by prury** [comment]
> 
>  If not, let's add it to prevent this in the future, please 🙏🏾

certainly, thank you

**Comment by yangwao** [comment]
> yet when I tried to mint new iteration, the same identical dialogue with same mint surfaced

Former solved on canary, continue here
https://github.com/kodadot/nft-gallery/issues/9697
