### ISSUE TITLE
Drop collection wont load

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9680]
https://kodadot.xyz/ahp/drops/refraction

![image](https://github.com/kodadot/nft-gallery/assets/5887929/bd91fb4b-312e-4a4e-91ed-91efb1da8aa9)

**Comment by preschian** [comment]
Eh, afaik, there is no deployment on Fxart at the moment. 

It looks good on https://www.cloudflarestatus.com/

<img width="339" alt="image" src="https://github.com/kodadot/nft-gallery/assets/734428/f8ef1b60-9af1-4eae-a5ec-2608d4cc14b8">

Is it still a blank page on your side?

**Comment by preschian** [comment]
oohh, it took longer to realize, seems like it related to this https://github.com/kodadot/private-workers/issues/85

on it

**Comment by preschian** [comment]
I just deployed this branch to beta: https://github.com/kodadot/private-workers/pull/90. how about now?

**Comment by yangwao** [comment]
> how about now?

works for now, what was issue?

**Comment by preschian** [comment]
> what was issue?

TIL that there is possibly undefined information from cf data (`c.req.raw.cf`). Need to escape it properly
