### ISSUE TITLE
Listing at drop page shows default picture

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9699]
Is it possible to show the currently minted item as on the previous page of the dialogue? 
I've seen it, and on the listing, I see the default.

![image](https://github.com/kodadot/nft-gallery/assets/5887929/78e0daf4-28d8-40d0-9904-34eea93b0fd2)

**Comment by daiagi** [comment]
seems to be working well here:
* #9709 
https://deploy-preview-9709--koda-canary.netlify.app/


![image](https://github.com/kodadot/nft-gallery/assets/22791238/3b218ada-7324-4fc6-a97e-20ead823ad63)
