### ISSUE TITLE
Update OG cards accordingly 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9703]
@exezbcz can drop the design 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/ebe8b77c-89bc-4c5b-8cf9-6ca8d0645036)

**Comment by exezbcz** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/8f7effeb-1197-47a2-a3cf-9ef2970e6f09)
here we go

**Comment by exezbcz** [comment]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/8f7effeb-1197-47a2-a3cf-9ef2970e6f09)
here we go

**Comment by yangwao** [comment]
If anyone can pick it up from @kodadot/internal-dev

**Comment by yangwao** [comment]
cc @preschian, have everything been deployed?

![image](https://github.com/kodadot/nft-gallery/assets/5887929/6e2ae7ee-7554-4e4e-955b-0e13fd7e085a)

**Comment by preschian** [comment]
> cc @preschian, have everything been deployed?

I think each social media platform has its own cache implementation. Looks fine on fb

![image](https://github.com/kodadot/nft-gallery/assets/734428/4318081b-7f49-447a-a1b5-6576bef50094)

**Comment by preschian** [comment]
another workaround is using another URL for the image, it can help to bypass the cache

**Comment by preschian** [comment]
will deploy this https://github.com/kodadot/workers/pull/267 for an attempt

**Comment by preschian** [comment]
updated

<img width="488" alt="Screenshot 2024-03-28 at 18 08 03" src="https://github.com/kodadot/nft-gallery/assets/734428/c7865ee2-2aeb-45b6-8d8d-55f9ada6622e">

**Comment by yangwao** [comment]
> its own cache implementation

yeah that's why added parameter but well

perfect 

> updated

**Comment by yangwao** [comment]
TYSM @preschian for quick reply!
