### ISSUE TITLE
Mobile responsivity issues

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9721]
Can be seen on: **mobile 360px width**

**transfer:**

![image](https://github.com/kodadot/nft-gallery/assets/36627808/27aa386a-7c76-4bc3-a63c-94075424c133)

**burguer menu spacing before icon and shopping cart alignment:** 

![image](https://github.com/kodadot/nft-gallery/assets/36627808/588d3ab1-d858-4629-99d3-35148f211829)

**Comment by floyd-li** [comment]
maybe we could split the sender into 2 lines like this? since the qty length is not fixed and it did not display well in such small width

wdyt? @exezbcz 

![CleanShot 2024-03-20 at 10 35 17@2x](https://github.com/kodadot/nft-gallery/assets/16473062/036cde1c-5d69-420f-9339-4d6538b6dbbb)

**Comment by exezbcz** [comment]
@floyd-li valid, thank you
