### ISSUE TITLE
Whitelisted collection for generative strip

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9726]
to ensure this does not happen again 
- https://github.com/kodadot/nft-gallery/pull/9724

We can maybe whitelist collection from **koda minter on AHP**

![telegram-cloud-photo-size-4-6019427052693865590-y](https://github.com/kodadot/nft-gallery/assets/90852205/9c0c3903-7268-441c-902d-5bcce0a0e08a)

**Comment by vikiival** [comment]
That is the issue for private workers.  

select * from campaigns order by created_at desc limit 5

Cc @preschian
