### ISSUE TITLE
Changing from one drop another still shows the previous one

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9729]
https://github.com/kodadot/nft-gallery/assets/36627808/6097fa4d-ab73-41e2-a822-707a1e3b6755

**Comment by Jarsen136** [comment]
This bug is from #9709 instead of canary env

https://deploy-preview-9709--koda-canary.netlify.app/

**Comment by prury** [comment]
> This bug is from #9709 instead of canary env
> 
> https://deploy-preview-9709--koda-canary.netlify.app/
> 
> 

Correct, Refactor PR is referenced above

**Comment by Temidayo32** [comment]
@prury I am not certain about the workflow. The PR that introduced the bug haven't been merged yet. To fix this bug, would the PR owner adjust their PR?

**Comment by daiagi** [comment]
Hi
fixed in #9709 
closing
