### ISSUE TITLE
pre-render svg for og social cards

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#973]
Right now when you check animated SVG you don't get a preview for social cards which is pitty.

ideation would be set serverless function which would fetch very last frame, 95%? from NFT and show it?

**Comment by yangwao** [comment]
Maybe @AndriiHrynchuk can chek on this 👀

**Comment by AndriiHrynchuk** [comment]
on it. I remember we used to have separate field for preview images. Currently I see that preview for 3D NFTs not shown as well. Are there are any changes made to metas?

**Comment by yangwao** [comment]
I recall for 3D this was added recently we can use for 3D #1022 
But SVG is quite different, probably I would target 2/3 frames from the total length. or let's aim 75%th frame ?
As some stuff fade out 
Example https://nft.kodadot.xyz/rmrk/detail/9948415-900D19DC7D3C444E4C-EXCANARY-EXPECT_CANARY_34-0000000000000034

**Comment by AndreyGrin** [comment]
got it working on free account but there are memory limit exists so animation can play max around 6 seconds. Paid plan can handle longer animations.

**Comment by AndreyGrin** [comment]
deployed to Vercel. One small thing is required to add from Kodadot as well, will make PR

**Comment by roiLeo** [comment]
continue in https://github.com/kodadot/workers/tree/main/ssr-opengraph
