### ISSUE TITLE
Collected by sometimes doesn't show and shows same collectors+numbers at different drops

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9731]
Sometimes doesn't load Collected By on Drops 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/400eb212-9267-42eb-b696-31bb5d404f22)

Vs how it should look like 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/00ffc4a0-d256-44ad-bbe6-59bd9af7654a)

---
and another strange bug I see different numbers which are suspicious same from other drops 
ah and same component shows on other drops 

---
![image](https://github.com/kodadot/nft-gallery/assets/5887929/055a3114-2367-4c74-929c-f1a8e13ba657)
vs 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/1d898ee7-1dd9-489b-ba20-daafe7632649)
---
![image](https://github.com/kodadot/nft-gallery/assets/5887929/b07c8415-afb1-4f18-bd67-f82590f2d20a)
vs
![image](https://github.com/kodadot/nft-gallery/assets/5887929/7a0a3b91-cc61-4f88-b900-39b33253ea2e)
---
![image](https://github.com/kodadot/nft-gallery/assets/5887929/92aae093-f52d-4cec-9379-2a43f50d70d7)
vs
![image](https://github.com/kodadot/nft-gallery/assets/5887929/9809c7e4-a280-4f65-8266-db0c1b8e9c72)

**Comment by Temidayo32** [comment]
@yangwao I have checked this out locally. And I didn't see this error. I have done some basic testing using `console.log`. Specifically, in `useCollectionActivity.ts`, I used `console.log` to return the length of the array of collectors of each drop, and the result is accurate and consistent with expected behaviour.  

```
console.log({ owner: Object.keys(owners.value).length })
```

**Comment by Temidayo32** [comment]
I am not sure, but you want to check #9709 as it might have introduced the error.  It can easily fixed.
