### ISSUE TITLE
Mint already claimed

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9738]
first attempt at minting Purple pill test drop showed me this error: 

![image](https://github.com/kodadot/nft-gallery/assets/36627808/00584e53-c7a3-4e06-bd78-e11ed65e6863)

transaction: 
https://assethub-kusama.subscan.io/tx/0xaefb8e8df57be0b5c88f2b05d9a6487d63484153b5ef5a33430deb5f3914c54c

NFT was minted but success modal was not present

**Comment by prury** [comment]
related: 
- #9649

**Comment by vikiival** [comment]
cc @Jarsen136 / @preschian ?
