### ISSUE TITLE
Merge `drops-refactor` to `main`

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9739]
Once this PR is merged, let's make PR to merge `drops-refactor` to `main` 
- https://github.com/kodadot/nft-gallery/pull/9711

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/9711#issuecomment-1994390342_

Current conflicts

![image](https://github.com/kodadot/nft-gallery/assets/5887929/f1a35d7d-9e0b-4f9d-b01c-5438638d4b6e)

**Comment by yangwao** [comment]
@daiagi can you raise PR and resolve those three conflicts ahead, please? 

I know from #9711 there would likely be some other, but till then we can have these done:)

Thank you!

**Comment by daiagi** [comment]
ok
