### ISSUE TITLE
Collected by gone

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9757]
![image](https://github.com/kodadot/nft-gallery/assets/36627808/822491b1-1fb4-4960-994b-3de7a0bfd4ea)

**Comment by yangwao** [comment]
@daiagi maybe something was removed while merging? I recall seen it at 9711

**Comment by prury** [comment]
> 
> @prury you can make tests for that as it's kinda important social signal thing to be there :)

sure

**Comment by daiagi** [comment]
Yes I must have fudged it up some where in the refactoring

**Comment by yangwao** [comment]
> Yes I must have fudged it up some where in the refactoring

yup, let's raise PR please, I want to release it with today's release 🙏 
- #9758

**Comment by yangwao** [comment]
or if anyone from @kodadot/internal-dev want to take on this? Not sure if @daiagi is working on this.

**Comment by daiagi** [comment]
hi @yangwao  just started working on this right now

**Comment by yangwao** [comment]
@daiagi any updates? Gonna release in 3 mins

**Comment by daiagi** [comment]
@yangwao 

sorry i can't make it on time
@kodadot/internal-dev  if someone could jump in here

problem seems to be reactivity of 

```
const { owners } = useCollectionActivity({
  collectionId: drop.value?.collection,
})
```


in `GenerativeLayout`


HOWEVER.


maybe i was wrong to say it is from the refactor as it is missing in `kodadot.xyz` as well


![image](https://github.com/kodadot/nft-gallery/assets/22791238/098c90e1-56e2-4523-863c-e3e92ab47b37)

**Comment by yangwao** [comment]
> if someone could jump in here

can't you just revert what you've deleted at some point? 
The code is supposed to be there, and it was working well.

> maybe i was wrong to say it is from the refactor as it is missing in `kodadot.xyz` as well

It was there. You are already looking at pushed production. However on various deploy previews noticed it glitching.
- #9731
