### ISSUE TITLE
ID already in use

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9759]
I guess my comment was missed at https://github.com/kodadot/nft-gallery/pull/9711#issuecomment-1995125485

tested again and was able to reproduce

opened 2 different accounts in different anonymous browser tabs and minted 5 nfts each at the same time:

error at: 0:34

edit: also messes nft serial numbering

https://github.com/kodadot/nft-gallery/assets/36627808/2a1c1f53-2e5d-4143-bd16-65392b1f6a82

**Comment by yangwao** [comment]
looks like queue is not used or?

**Comment by prury** [comment]
> looks like queue is not used or?

not sure, but if ppl massmint drops at a similar time we will see errors like this happening

**Comment by vikiival** [comment]
- https://github.com/kodadot/private-workers/issues/97
