### ISSUE TITLE
I broke drops

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9762]
sn:36 is already minted and it offers me to mint it even if i refresh the page: 

https://github.com/kodadot/nft-gallery/assets/36627808/b0d4afd2-397a-48c6-bed8-4f5a675a8446

![image](https://github.com/kodadot/nft-gallery/assets/36627808/8536a5cd-ec77-4d5e-aa2a-be80746c4f75)

**Comment by prury** [comment]
cc: @yangwao

**Comment by vikiival** [comment]
Cc @preschian

**Comment by yangwao** [comment]
minted few and haven't happed so far tho, but I know we have this for while

**Comment by prury** [comment]
> minted few and haven't happed so far tho, but I know we have this for while

cool cool, i saw it
yes, we had this problem for a while, but let's hope no id gets stuck like it did on the test drop
i can also see that minting ids are scrambled, number 15 just got minted

**Comment by prury** [comment]
@yangwao it broke right now

**Comment by vikiival** [comment]
- https://github.com/kodadot/private-workers/issues/97
