### ISSUE TITLE
nfts.AlreadyExists The item id has already been used for an item

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9765]
It seems we are not using our minting queue properly.

- https://github.com/kodadot/nft-gallery/issues/9762
- https://github.com/kodadot/nft-gallery/issues/9759
- https://github.com/kodadot/nft-gallery/issues/9738 (related probably)
- https://github.com/kodadot/nft-gallery/issues/9847

**Comment by yangwao** [comment]
We got public roasting 
- https://twitter.com/rom1_dot/status/1772747036175028268

**Comment by vikiival** [comment]
> can we do something please @kodadot/internal-dev

- https://github.com/kodadot/private-workers/issues/97
