### ISSUE TITLE
Add collection insight distribution showing number items owned and unique owners

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#978]
The first number means how many items are owned and then we could add unique owners
![image](https://user-images.githubusercontent.com/5887929/139654384-63606f39-0750-4526-ab51-eb166e6ce5b1.png)
From these two numbers, we could distil ownership distribution, which says how much is owned collection 

![image](https://user-images.githubusercontent.com/5887929/139654357-d50010ed-f237-4caa-a0e6-6f074a193d29.png)

Tested on https://kodadot.xyz/rmrk/collection/dac5c7f54029d0e73c-HXAI8

Inspired by https://solanart.io/collections/thetower
![image](https://user-images.githubusercontent.com/5887929/139653798-d7a31134-2cc0-4615-a8e8-d014371da7e3.png)

**Comment by roiLeo** [comment]
On "ITEMS" activity, you would like to display:
(owned items) / (unique owners) ?
What will be displaying on "OWNED" activity?

In solarnart it's displaying:
(listed nfts in collection) / (collection length)

(Preview from Apes collection with solarnart implementation)
<img width="343" alt="Capture d’écran 2021-11-01 à 12 58 34 PM" src="https://user-images.githubusercontent.com/9987732/139668683-7b6799cd-a611-4aba-9887-2a0b96e822ca.png">

**Comment by yangwao** [comment]
Distribution was solved in #1037  
So still we can add this there 

> On "ITEMS" activity, you would like to display: (owned items) / (unique owners) ? What will be displaying on "OWNED" activity?
> 
> In solarnart it's displaying: (listed nfts in collection) / (collection length)

Oh, I was a bit confused when doing research, yes this is what I've meant originally

Items 
(listed nfts in collection) / (collection length) 

Owners
(unique owners)

**Comment by yangwao** [comment]
I've expanded bit @roiLeo hope it make sense now! :)

From owners currently we count distribution index but it can give you insight on "how" is collection distributed if someone is interested in hard numbers.

Re items
make sense to show listed and total as when you buy some ppl don't list it etc and that could show another collections dynamics etc

**Comment by yangwao** [comment]
Odds that it will be fixed in #1124

**Comment by yangwao** [comment]
Okay closing in favour #1124
