### ISSUE TITLE
Some NFTs not updated to genart iterations

### ISSUE THREAD

**Issue by preschian** [kodadot/nft-gallery#9788]
Claim 10 drops, but after 1 hour, it is still not updated to Genart. On db, it's already set claimed to 1. It means from UI already called this line https://github.com/kodadot/private-workers/blob/bbeab56fb3832f50895a4c32ed8b41202928c978/fxart/src/routes/drops.ts#L536-L541

Stuck on minting service? https://github.com/kodadot/private-workers/blob/bbeab56fb3832f50895a4c32ed8b41202928c978/fxart/src/utils/mint.ts#L56-L68

<img width="1399" alt="image" src="https://github.com/kodadot/nft-gallery/assets/734428/1716ab9a-185e-4815-bee1-0dc37f00bab3">

**Comment by exezbcz** [comment]
<img width="3008" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/83e8697d-f48f-4c9a-aeff-eccf9e741037">
yup, does not look good

**Comment by preschian** [comment]
Hi, @kodadot/internal-dev. Does anyone know how to fix this? Does the trigger minting service solve the issue? If so, how do I do that?

does anyone know about this service? https://github.com/kodadot/private-workers/blob/bbeab56fb3832f50895a4c32ed8b41202928c978/fxart/src/utils/mint.ts#L3

some of the IDs are also still not updated yet
- https://kodadot.xyz/ahp/gallery/112-15
- https://kodadot.xyz/ahp/gallery/112-14
- https://kodadot.xyz/ahp/gallery/112-52

**Comment by vikiival** [comment]
> Hi, @kodadot/internal-dev. Does anyone know how to fix this? Does the trigger minting service solve the issue? If so, how do I do that?


The only case this can happen if user fails to mint nft and we still send success signal to fxart worker. 


I have already asked many times to do checking properly on the frontend
> 
> does anyone know about this service?

Yes I wrote is as Deno is only runtime able to handle polkadot-js 

I can transfer it to kodadot.

**Comment by preschian** [comment]
> The only case this can happen if user fails to mint nft and we still send success signal to fxart worker.

Mint was looking fine here: https://assethub-polkadot.subscan.io/extrinsic/5863144-2. Isn't?

How to reproduce:
- block `do/:id` endpoint
- claim the drops, reload page
- the item won't update to genart
- in this case, that nft will always "claimed = 0"

<img width="328" alt="image" src="https://github.com/kodadot/nft-gallery/assets/734428/946630d1-f432-430b-a7b3-7d6669cf8aae">


> Claim 10 drops, but after 1 hour, it is still not updated to Genart. On db, it's already set claimed to 1. It means from UI already called this line [kodadot/private-workers@bbeab56/fxart/src/routes/drops.ts#L536-L541](https://github.com/kodadot/private-workers/blob/bbeab56fb3832f50895a4c32ed8b41202928c978/fxart/src/routes/drops.ts#L536-L541)

On "Convergate" is slightly different. It's already "claimed = 1". meanwhile, on our code, set to "claimed = 1" is only on this line https://github.com/kodadot/private-workers/blob/bbeab56fb3832f50895a4c32ed8b41202928c978/fxart/src/routes/drops.ts#L536-L541

**Comment by vikiival** [comment]
> Mint was looking fine here: https://assethub-polkadot.subscan.io/extrinsic/5863144-2. Isn't?

Probably you set bad tx
![Screenshot 2024-03-19 at 12 18 48](https://github.com/kodadot/nft-gallery/assets/22471030/250797f6-32ea-46cc-88da-f39c4cbc1182)


Then probably waifu worker had to fail :)
that is case when non-existent nft is in batch for set metadata

**Comment by preschian** [comment]
Then how do we fix that? Trigger waifu.deno should be able to fix it, right? Because the data (hash, user, etc) is already on the db

This user has two items that have not generated to genart https://kodadot.xyz/ahp/u/13Do5NPVxuNd6Qud4qvpzV8xcHuW2xab3CWrz6KaoSwL6n5t

**Comment by vikiival** [comment]
So what I have observed at @preschian's case is that his tx to mint and bot's tx to [update metadata has been included in same block](https://assethub-polkadot.subscan.io/block/5863139)

metadata update is `5863139-2` where @preschian's mint is `5863139-3`

therefore frontend sent the call to "finish" claiming too early.

## Why do I think so? 

Usually every tx in KodaDot is waiting for tx finalization (my block + 2 blocks after ).

Having desync like this is possible when:
1. User signed tx
2. after signature -> api call was sent to `fxart` api
3. kodabot included these requests into batch tx

**Comment by daiagi** [comment]
@vikiival @preschian 
what's the haps on this?

do you need my help here on anything?

**Comment by vikiival** [comment]
> do you need my help here on anything?

Yes 

transform this json

```json
[
  {
    "name": "calls",
    "type": "Vec<asset_hub_polkadot_runtime:RuntimeCall>",
    "type_name": "Vec<<T as Config>::RuntimeCall>",
    "value": [
      {
        "call_index": "3418",
        "call_module": "Nfts",
        "call_name": "set_metadata",
        "params": [
          {
            "name": "collection",
            "type": "U32",
            "value": 112
          },
          {
            "name": "item",
            "type": "U32",
            "value": 80
          },
          {
            "name": "data",
            "type": "Vec<U8>",
            "value": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/0.json"
          }
        ]
      },
      {
        "call_index": "3418",
        "call_module": "Nfts",
        "call_name": "set_metadata",
        "params": [
          {
            "name": "collection",
            "type": "U32",
            "value": 112
          },
          {
            "name": "item",
            "type": "U32",
            "value": 81
          },
          {
            "name": "data",
            "type": "Vec<U8>",
            "value": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/1.json"
          }
        ]
      },
      {
        "call_index": "3418",
        "call_module": "Nfts",
        "call_name": "set_metadata",
        "params": [
          {
            "name": "collection",
            "type": "U32",
            "value": 112
          },
          {
            "name": "item",
            "type": "U32",
            "value": 82
          },
          {
            "name": "data",
            "type": "Vec<U8>",
            "value": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/2.json"
          }
        ]
      },
      {
        "call_index": "3418",
        "call_module": "Nfts",
        "call_name": "set_metadata",
        "params": [
          {
            "name": "collection",
            "type": "U32",
            "value": 112
          },
          {
            "name": "item",
            "type": "U32",
            "value": 83
          },
          {
            "name": "data",
            "type": "Vec<U8>",
            "value": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/3.json"
          }
        ]
      },
      {
        "call_index": "3418",
        "call_module": "Nfts",
        "call_name": "set_metadata",
        "params": [
          {
            "name": "collection",
            "type": "U32",
            "value": 112
          },
          {
            "name": "item",
            "type": "U32",
            "value": 84
          },
          {
            "name": "data",
            "type": "Vec<U8>",
            "value": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/4.json"
          }
        ]
      },
      {
        "call_index": "3418",
        "call_module": "Nfts",
        "call_name": "set_metadata",
        "params": [
          {
            "name": "collection",
            "type": "U32",
            "value": 112
          },
          {
            "name": "item",
            "type": "U32",
            "value": 95
          },
          {
            "name": "data",
            "type": "Vec<U8>",
            "value": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/5.json"
          }
        ]
      },
      {
        "call_index": "3418",
        "call_module": "Nfts",
        "call_name": "set_metadata",
        "params": [
          {
            "name": "collection",
            "type": "U32",
            "value": 112
          },
          {
            "name": "item",
            "type": "U32",
            "value": 96
          },
          {
            "name": "data",
            "type": "Vec<U8>",
            "value": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/6.json"
          }
        ]
      },
      {
        "call_index": "3418",
        "call_module": "Nfts",
        "call_name": "set_metadata",
        "params": [
          {
            "name": "collection",
            "type": "U32",
            "value": 112
          },
          {
            "name": "item",
            "type": "U32",
            "value": 97
          },
          {
            "name": "data",
            "type": "Vec<U8>",
            "value": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/7.json"
          }
        ]
      },
      {
        "call_index": "3418",
        "call_module": "Nfts",
        "call_name": "set_metadata",
        "params": [
          {
            "name": "collection",
            "type": "U32",
            "value": 112
          },
          {
            "name": "item",
            "type": "U32",
            "value": 98
          },
          {
            "name": "data",
            "type": "Vec<U8>",
            "value": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/8.json"
          }
        ]
      },
      {
        "call_index": "3418",
        "call_module": "Nfts",
        "call_name": "set_metadata",
        "params": [
          {
            "name": "collection",
            "type": "U32",
            "value": 112
          },
          {
            "name": "item",
            "type": "U32",
            "value": 99
          },
          {
            "name": "data",
            "type": "Vec<U8>",
            "value": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/9.json"
          }
        ]
      }
    ]
  }
]
```

to this format: 

```json
[
  {
    "chain": "ahp",
    "collection": "112",
    "sn": "80",
    "metadata": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/0.json"
  }
]
```

aka to array of objects

**Comment by daiagi** [comment]
@vikiival i guess you mean in fxart worker hander, don't you?

**Comment by vikiival** [comment]
> @vikiival i guess you mean in fxart worker hander, don't you? 

No literally mean what was said above. I need you to transfrorm that json above to the format below :)

**Comment by daiagi** [comment]
```json
[
  {
    "chain": "ahp",
    "collection": "112",
    "sn": "80",
    "metadata": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/0.json"
  },
  {
    "chain": "ahp",
    "collection": "112",
    "sn": "81",
    "metadata": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/1.json"
  },
  {
    "chain": "ahp",
    "collection": "112",
    "sn": "82",
    "metadata": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/2.json"
  },
  {
    "chain": "ahp",
    "collection": "112",
    "sn": "83",
    "metadata": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/3.json"
  },
  {
    "chain": "ahp",
    "collection": "112",
    "sn": "84",
    "metadata": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/4.json"
  },
  {
    "chain": "ahp",
    "collection": "112",
    "sn": "95",
    "metadata": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/5.json"
  },
  {
    "chain": "ahp",
    "collection": "112",
    "sn": "96",
    "metadata": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/6.json"
  },
  {
    "chain": "ahp",
    "collection": "112",
    "sn": "97",
    "metadata": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/7.json"
  },
  {
    "chain": "ahp",
    "collection": "112",
    "sn": "98",
    "metadata": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/8.json"
  },
  {
    "chain": "ahp",
    "collection": "112",
    "sn": "99",
    "metadata": "ipfs://bafybeidmbsl2yvdjk3m5el3j4q5m5rd4zkao6nj3ekbsxdorftgk42ivcy/9.json"
  }
]
```

**Comment by vikiival** [comment]
Thank you @daiagi 

https://assethub-polkadot.subscan.io/extrinsic/0x5d745070314395afe4f2db4188be28379ee74317d0ba4210c9ac659c0857f52d

**Comment by vikiival** [comment]
![Screenshot 2024-03-25 at 11 35 39](https://github.com/kodadot/nft-gallery/assets/22471030/d843cd2d-8947-448f-83c2-6cb8b3b1a9de)
