### ISSUE TITLE
Sort NFT by most sales asc/dsc

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#979]
- add a view to the collection
- gallery
- profile

**Comment by XyloDrone** [comment]
Related to #1023

**Comment by XyloDrone** [comment]
this seems like it is already done but requires just a name change from cheapest/most expensive to asc/dsc

**Comment by prachi00** [comment]
@yangwao @XyloDrone will check this one

**Comment by prachi00** [comment]
<img width="381" alt="Screenshot 2022-03-24 at 3 42 36 PM" src="https://user-images.githubusercontent.com/39299315/159893859-61557136-0165-41ac-b828-f95510d86c73.png">
@XyloDrone change these texts is all that is left right?

**Comment by XyloDrone** [comment]
Yup! @cryptodamsky , I think we had another comment on the filters from the survey… can you recall what it was? :D

**Comment by prachi00** [comment]
<img width="353" alt="Screenshot 2022-03-24 at 3 54 01 PM" src="https://user-images.githubusercontent.com/39299315/159896024-33e311fd-694b-468c-b7f2-41a17eca41a6.png">
@XyloDrone should it be like this or just ASC ?

**Comment by XyloDrone** [comment]
That’s great :D

**Comment by cryptodamsky** [comment]
> Yup! @cryptodamsky , I think we had another comment on the filters from the survey… can you recall what it was? :D

Yup, it was sort by rank and volume :)

**Comment by cryptodamsky** [comment]
And we were also saying, that having - long time no interaction is kinda useless? No collector would probably look for this :D + its gonna show rly old stuff i guess?
