### ISSUE TITLE
User balance won't load

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9805]
Opening an issue to an artist that can't seem to see balances when logging on kodadot

Was reported by dvekukolki on telegram( who is in touch with said artist) 

Address: 15kVXAMrNzgb4KmbqUsocgM54bdMVQq2TcBNYdLXDf6GWH42

![IMG_20240318_150516_388.jpg](https://github.com/kodadot/nft-gallery/assets/36627808/b32a04a4-06bd-4cca-becb-09ce9e153fe3)

Artist says that balances stays the same as image above and won't load.

User also tried with vpn on and off

**Comment by Jarsen136** [comment]
When I try to mock this address, it works well to load the balance. It should be a VPN issue.

<img width="346" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/ad81f0a3-bb01-44e4-8b67-6e98f9754f40">
