### ISSUE TITLE
Add Collection view

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#981]
Would be perfect to have a collection view only. 
You can recycle stuff from series, URL could be https://kodadot.xyz/rmrk/collections

Have cards of the collection showing pictures of the collection
Showing short stats like 
- number of items collected / total assets, 
- unique owners
- volume
- floor price
Adding pagination like showing only 3x3 would be enough 

Inspiration 
- https://singular.rmrk.app/collectibles?page=1&curated=true&verified=true&showCollections=yes
- https://solsea.io/collections

**Comment by TK-Development** [comment]
Let me take a look.
But before implementing this one, I have a question, who can answer me?
