### ISSUE TITLE
Add to Cal

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9813]
Is this intentional?
<img width="868" alt="Screenshot 2024-03-19 at 22 01 41" src="https://github.com/kodadot/nft-gallery/assets/104380776/b2c306d7-b670-4ba7-b36c-ccf996392757">

Where: open drop pages.

Add to Cal - seems a bit weird shortcut

**Comment by exezbcz** [comment]
yes

**Comment by yangwao** [comment]
Add to Calendar?
