### ISSUE TITLE
Add Sub.id to profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#982]
Whenever user lands on https://kodadot.xyz/rmrk/u/CmMkskdeDpSoU2xKnZ214JkgFZKmMCZXoYyJfHYB1X1aihy can check sub.id profile through https://sub.id/#/CmMkskdeDpSoU2xKnZ214JkgFZKmMCZXoYyJfHYB1X1aihy

Suggested placement till now would be under users twitter
![image](https://user-images.githubusercontent.com/5887929/139658421-be07de2d-aa3a-4ea2-a4eb-ca4e340fbfb3.png)

**Comment by fairywellos** [comment]
@yangwao Do we have svg for sub id? Currently, I just used svg for subscan.
![Screen Shot 2021-11-02 at 8 41 19 AM](https://user-images.githubusercontent.com/53324919/139848415-2a344a11-5a9e-441b-aa53-e0c16e95dba4.png)

**Comment by vikiival** [comment]
```html
<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="7.231 66.216 255.786 255.419" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><g transform="matrix(0.1, 0, 0, -0.1, 7.11949, 321.788269)" stroke="none"><path d="M1099 2545 c-305 -50 -542 -174 -748 -390 -268 -284 -394 -678 -336 -1055 41 -275 156 -508 348 -706 492 -510 1294 -525 1802 -33 209 202 337 450 380 739 100 654 -347 1292 -1000 1430 -131 27 -331 34 -446 15z m-269 -1240 l0 -605 -145 0 -145 0 0 605 0 605 145 0 145 0 0 -605z m834 590 c192 -50 340 -202 391 -400 20 -80 20 -300 0 -380 -53 -202 -200 -349 -400 -400 -45 -11 -117 -15 -297 -15 l-238 0 0 605 0 605 243 0 c186 0 257 -4 301 -15z"></path><path d="M1418 1684 c-5 -4 -8 -175 -8 -381 l0 -373 87 0 c102 0 155 21 203 78 51 61 70 144 70 296 0 217 -41 314 -153 361 -42 17 -188 32 -199 19z"></path></g></svg>
```

can't upload svg

**Comment by fairywellos** [comment]
@vikiival After using the svg above - I'm seeing like this.(a little dark color as far as I'm seeing)
would you confirm that it's what you intended to use?
![Screen Shot 2021-11-02 at 9 53 27 AM](https://user-images.githubusercontent.com/53324919/139860867-fa1d4b53-a1fd-46e8-b171-bc65aaf759f4.png)

**Comment by vikiival** [comment]
Fresh logos for you
[Sub.ID-logo.zip](https://github.com/kodadot/nft-gallery/files/7461403/Sub.ID-logo.zip)

**Comment by fairywellos** [comment]
@vikiival Thanks
