### ISSUE TITLE
Something is wrong with buying

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9825]
On collection, I've added items to the cart (there was nothing in the bottom right corner like at the listing); on the sidebar, I clicked buy, and nothing popped. 

I sense is some upcoming glitch. 

and now after buying it spinning kinda long than usual like for 5 minutes already.

oh and after not so successful buying items are still in cart, on purpose?
maybe separate bug? 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/684da35c-172f-4697-9fa3-098b98815309)

**Comment by prury** [comment]
works fine for me on KusamaHub

https://github.com/kodadot/nft-gallery/assets/36627808/18bf5e56-da14-44a5-9de3-bb8f9d25805f
