### ISSUE TITLE
Add service worker for Nuxt

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#984]
We need to have service worker to update clients once there is new version available 

@dezine2dev will check on this for #843 

https://pwa.nuxtjs.org/setup

Current https://beta.kodadot.xyz 
![image](https://user-images.githubusercontent.com/5887929/141774315-686ed3e1-2ae2-4d03-9bc2-f876206b55fe.png)

https://kodadot.xyz looks like this
Current 
![image](https://user-images.githubusercontent.com/5887929/141774357-56a79f3d-b6e6-4894-8318-4868bb0b412c.png)

**Comment by yangwao** [comment]
@dezine2dev pinging on this, I haven't seen it working in last PRs

**Comment by dezine2dev** [comment]
I did not work on this yet. Will check it asap
