### ISSUE TITLE
The Break drop breaking my browser

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9840]
nothing happens when i access it and browser gets so slow it affects other pages and i have to restart it: 

https://github.com/kodadot/nft-gallery/assets/36627808/4a149e9d-02cc-46b7-afcf-a7d3cbb55ce4

**Comment by exezbcz** [comment]
the name is on spot

**Comment by yangwao** [comment]
> browser gets so slow

I'm wondering how it passed our checker https://canary.kodadot.xyz/code-checker

**Comment by prury** [comment]
> > browser gets so slow
> 
> I'm wondering how it passed our checker https://canary.kodadot.xyz/code-checker

it did not passed on my PC

**Comment by prury** [comment]
While some old NFTs still break my computer if i access them, the refactored code sent by the artist no longer freezes my browser
