### ISSUE TITLE
The Break: Minting issues - unable to mint NFT 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9847]
## What happened
Minting The break

### First try: 
I opened kodadot.xyz went to Drops, The Break, and the first variation that appeaerd I liked. I clicked on mint. I signed the transaction, and my popup window disappeared, and it looked like nothing happened. I was just on drop page.

### Second try:
I refreshed the page and minted again:
https://github.com/kodadot/nft-gallery/assets/104380776/10738858-d880-4cd0-8ac9-8e1904acf907

This happened

### Third try:
I generated totally new variation and got the same error again
<img width="644" alt="Screenshot 2024-03-22 at 10 18 29" src="https://github.com/kodadot/nft-gallery/assets/104380776/358e2cd8-2721-45a7-b13c-53fa6276e43e">

I tried 3 times and I was not able to mint the NFT. 😪

**Comment by JustLuuuu** [comment]
Getting this error pretty often: 
<img width="640" alt="Screenshot 2024-03-22 at 10 29 26" src="https://github.com/kodadot/nft-gallery/assets/104380776/2960e3ce-286a-4947-a7b5-af42c06b2804"> 

This time in another wallet (1NFfEH3yspdEgLnhZ5QWgb7B2z5LNCAE3HUo5nDxF5MqTcj). I tried to mint after I closed the popup window in the first try

**Comment by JustLuuuu** [comment]
## **Update**: 
After getting this error once, Im **not able to mint from this collection on the selected wallet at all**. I tried refreshing page, I tried leaving the drop page and going back to it. I tried log out from wallet and log in again. And Im always getting the same error. 

<img width="640" alt="Screenshot 2024-03-22 at 10 29 26" src="https://github.com/kodadot/nft-gallery/assets/104380776/57bb049a-ab59-4280-8b21-0ee228a91697">

## My experience summary: 
Total tries of minting: 9
Wallets used: 2 different wallets
Numbers of NFTs I was able to mint:  only 1

😪 I wonder how many people were discouraged by the same experience.

**Comment by hassnian** [comment]
related https://github.com/kodadot/nft-gallery/issues/9765

**Comment by vikiival** [comment]
- https://github.com/kodadot/private-workers/issues/97
