### ISSUE TITLE
Current layout display on Collection & Profile

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#986]
**Describe the bug**
On collection page, the current layout button is not active

**To Reproduce**
1. Go to any **collecion** id
2. See current layout display

**Expected behavior**
When on collection, activate button with current display

**Screenshots**
#### Current
<img width="137" alt="Capture d’écran 2021-11-01 à 2 16 18 PM" src="https://user-images.githubusercontent.com/9987732/139677573-4fcc59dc-f78c-4c13-8ada-4d2c953b2002.png">

#### Excepted
<img width="137" alt="Capture d’écran 2021-11-01 à 2 16 49 PM" src="https://user-images.githubusercontent.com/9987732/139677668-661a28be-e8f9-49e0-a5a1-425eb502d47e.png">

**Additional context**
We need to create a ```<ToggleLayout />``` component for #967

**Comment by prachi00** [comment]
@roiLeo is this still an issue? as I don't see it happening anymore.

**Comment by roiLeo** [comment]
> 
> 
> @roiLeo is this still an issue? as I don't see it happening anymore.

merged in #1003 but we still need a ToggleLayout component

**Comment by prachi00** [comment]
> > @roiLeo is this still an issue? as I don't see it happening anymore.
> 
> merged in #1003 but we still need a ToggleLayout component

Sure, will pick that up then

**Comment by roiLeo** [comment]
closed by @prachi00 if I'm right but can't find the linked PR
