### ISSUE TITLE
The Break: Not responding properly

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9872]
Someone from our followers has an issue with loading The Break (and also other generative drops). the guy tried all 3 browsers he had. I am not sure why he has this issue because, on my laptop, it works smoothly and with no freezing.
<img width="702" alt="Screenshot 2024-03-24 at 17 55 58" src="https://github.com/kodadot/nft-gallery/assets/104380776/86254242-e87e-43a8-88f7-e8acf2951c4c">

<img width="318" alt="Screenshot 2024-03-24 at 17 52 40" src="https://github.com/kodadot/nft-gallery/assets/104380776/f4769330-e144-4a3a-80a1-9c870951b0eb">

Video
---

https://github.com/kodadot/nft-gallery/assets/104380776/6b9d9237-6149-4a40-9153-1151bbaa846f

**Comment by JustLuuuu** [comment]
Update from a different person:
<img width="330" alt="Screenshot 2024-03-24 at 17 53 50" src="https://github.com/kodadot/nft-gallery/assets/104380776/ce7b0ec9-15ad-47c1-a973-6339545d2fa3">

**Comment by JustLuuuu** [comment]
<img width="743" alt="Screenshot 2024-03-25 at 13 38 13" src="https://github.com/kodadot/nft-gallery/assets/104380776/3db17fe9-aaeb-40f6-aa34-55939336b0b6">

**Comment by daiagi** [comment]
it's a problem with the break code using webgl.
discussed in the telegram group

the solution was to add "not using webgl" item to the drop checker

**Comment by vikiival** [comment]
Artist was notified, as there is no action from our side / there is no need to fix this I am closing this issue
