### ISSUE TITLE
Offchain profiles - profile v3 - app preparation

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9876]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/195f3645-f391-426b-99bd-80aa02b63981)

## Random order 

- [x] https://github.com/kodadot/nft-gallery/issues/9873
- [x] https://github.com/kodadot/nft-gallery/issues/9879
- [x] https://github.com/kodadot/nft-gallery/issues/9925
- [x] https://github.com/kodadot/nft-gallery/issues/9941
- [x] https://github.com/kodadot/nft-gallery/issues/10233
- [x] https://github.com/kodadot/nft-gallery/issues/10359
- [x] https://github.com/kodadot/nft-gallery/issues/10457

related: 
- https://github.com/kodadot/nft-gallery/issues/4753
- https://github.com/kodadot/nft-gallery/issues/3420
- https://github.com/kodadot/nft-gallery/issues/10448

will update

**Comment by yangwao** [comment]
Done?
