### ISSUE TITLE
Add skeletons to collections

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#988]
When user opening collection, would be amazing to have a skeleton at 
- collection name
- creator
- analytics like items, owned, floor price volume traded 24h volume traded
- items 

https://kodadot.xyz/rmrk/collection/0E76E3AC15B4C1FA1E-FROST

![image](https://user-images.githubusercontent.com/5887929/139685373-3485724f-4a6d-44a6-b923-47345a14817f.png)

**Comment by fairywellos** [comment]
Let me take a look

**Comment by fairywellos** [comment]
@yangwao Seems like the details above are already implemented.
![Screen Shot 2021-11-02 at 9 26 40 AM](https://user-images.githubusercontent.com/53324919/139855810-9b154e82-9712-4859-b7af-a220679114dd.png)

**Comment by yangwao** [comment]
Hey, skeletons are used when data is loading to the client to keep users' attention in place where data show up

**Comment by fairywellos** [comment]
pass issue to @roiLeo as I think that it's better to handle on his end with the necessary details further.

**Comment by roiLeo** [comment]
closed in #1147
