### ISSUE TITLE
PINK Drop: date change

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9881]
From my information, PINK Drop is this Thursday, not in 3 hours. 🚀 Can we change it?

<img width="364" alt="Screenshot 2024-03-26 at 17 37 05" src="https://github.com/kodadot/nft-gallery/assets/104380776/691f1d59-896f-43cc-889b-b91d669cd4e2">

**Comment by Jarsen136** [comment]
@vikiival We should change the incorrect date on the database

**Comment by vikiival** [comment]
![Screenshot 2024-03-26 at 12 02 56](https://github.com/kodadot/nft-gallery/assets/22471030/cf3c2e2c-94ea-4332-898b-07edc6f230cd)
