### ISSUE TITLE
Drops - not working!

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9887]
When I click on Drops on KodaDot - they are not loading. Other things are working just not the Drops!

https://github.com/kodadot/nft-gallery/assets/104380776/d2153f8a-6b46-4247-9178-c18f283e4235

**Comment by exezbcz** [comment]
+1, refresh, incognito does not work

**Comment by Jarsen136** [comment]
@vikiival db issue, could you pls check it?

![image](https://github.com/kodadot/nft-gallery/assets/31397967/8ee5b170-0112-4381-ad5d-128f9582d919)

**Comment by vikiival** [comment]
Why are we fetching status on drop page?

![Screenshot 2024-03-27 at 11 35 16](https://github.com/kodadot/nft-gallery/assets/22471030/0be7dc99-a6ee-488d-815e-311e41375abf)

**Comment by Jarsen136** [comment]
> Why are we fetching status on drop page?
> 

Because some drops do not have `minted` data, but we have to display it on the drop card UI

![image](https://github.com/kodadot/nft-gallery/assets/31397967/ac1a0e75-b0a5-4383-923a-98acf7c90aad)
