### ISSUE TITLE
Related strip of NFTs contextual to NFT item

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#990]
Continue from 
- https://github.com/kodadot/nft-gallery/issues/782
- https://github.com/kodadot/nft-gallery/issues/478

Make component as two rows, both scrollable

First would show more from the current collection with a horizontal scroll, limit to 3-10 NFTs, show only BUY now and recent minted, newest and cheapest?

Second would show previously viewed NFTs, which would be stored at users localstorage, with 3-10 last NFTs viewed

**Comment by preschian** [comment]
Hi, I will try this one
