### ISSUE TITLE
drop calendar is not on production?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9907]
but on canary works

![image](https://github.com/kodadot/nft-gallery/assets/5887929/180c1e4c-fca0-4a3f-af7f-9f11ae97a150)

**Comment by hassnian** [comment]
seems prod worker is not up to date 

![CleanShot 2024-03-28 at 15 27 39@2x](https://github.com/kodadot/nft-gallery/assets/44554284/95a28457-097b-46e4-9e38-711a9d63f03c)

**Comment by yangwao** [comment]
> seems prod worker is not up to date

@preschian

**Comment by yangwao** [comment]
TYSM
![image](https://github.com/kodadot/nft-gallery/assets/5887929/df88805b-832b-497d-a4f8-0e8e4037df53)
