### ISSUE TITLE
Change footer in pure text 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9913]
wyt @exezbcz 
ours 
![image](https://github.com/kodadot/nft-gallery/assets/5887929/b0224cf1-bb35-4b5c-be86-89f6b0b97d9a)
into
![image](https://github.com/kodadot/nft-gallery/assets/5887929/e965204e-6969-4847-990b-87544475af08)

**Comment by exezbcz** [comment]
@yangwao yes
