### ISSUE TITLE
Mint seems not open after 3pm CET?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9917]
cc @preschian @vikiival 

https://kodadot.xyz/ahp/drops/shapes

![image](https://github.com/kodadot/nft-gallery/assets/5887929/45d1b426-8675-4ae0-9a21-ace83f1c2e1f)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/e69d59fd-9ff4-4de1-9514-896ba8cc4af7)

**Comment by vikiival** [comment]
p1 on this one
- https://github.com/kodadot/private-workers/issues/31
