### ISSUE TITLE
Frame preview sometimes doesn't work on new mint

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9923]
Any idea?

https://warpcast.com/yangwao/0x2c3404c7

![Screenshot_20240328_155207_Warpcast.png](https://github.com/kodadot/nft-gallery/assets/5887929/a19419f2-b1da-42da-be9b-b3bfb9d680d0)

**Comment by vikiival** [comment]
Prob issue with the gateway, 
we use `ipos` worker now so this should not occur anymore
