### ISSUE TITLE
Minted NFT #16 (The break) not showing on collection

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9932]
user minted sn #16 and when you go to collection its not showing there, also not showing when i access the nft directly

https://assethub-polkadot.subscan.io/account/13b1wQcZXhWYxjwY9jdJkyJZu5p9TwFEXZnSEBPhca9kaAUN

<img src="https://github.com/kodadot/nft-gallery/assets/36627808/e1419338-26bf-4c82-aed3-1c25ceced742" height="200">

https://kodadot.xyz/ahp/gallery/113-16

minted so far:

![image](https://github.com/kodadot/nft-gallery/assets/36627808/a84dec61-e588-408d-816a-7f94a360b04e)

**Comment by vikiival** [comment]
![Screenshot 2024-03-30 at 09 04 10](https://github.com/kodadot/nft-gallery/assets/22471030/5111ed39-f3c9-4ef2-a06b-2ba673c7db72)


https://kodadot.xyz/ahp/gallery/113-16
