### ISSUE TITLE
Disable/Hide The Break

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9939]
As the Break is not wokring for a lot of people - can we disable mint and add a text explaining that its temporarily stopped? 

![image](https://github.com/kodadot/nft-gallery/assets/104380776/cd96ec9c-047d-420c-9830-727716844c37)

It will be better than having users with bad experience. Hide or do something. idk what but till artists fixes the code.

**Comment by vikiival** [comment]
since - #9910 was merge I will hide and disable it
