### ISSUE TITLE
Minted NFTs not being shown on app

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9950]
Minted monotifs 71 and 72

https://canary.kodadot.xyz/ahk/gallery/403-71

and they are not available on kodadot app, even if transaction was successful 

https://assethub-kusama.subscan.io/tx/0x8e5b648975aa9c3565f556af238e226a5861856343d4250ea086c87ded7333d6

took at look at subsquid panel and everything seems ok there

**Comment by Jarsen136** [comment]
It's maybe some delay?

![image](https://github.com/kodadot/nft-gallery/assets/31397967/a75449d2-2b50-4e17-9345-001edfad0de4)

**Comment by prury** [comment]
> It's maybe some delay?
> 
> ![image](https://github.com/kodadot/nft-gallery/assets/31397967/a75449d2-2b50-4e17-9345-001edfad0de4)
> 

Viki fixed it for us on internal chat
