### ISSUE TITLE
Add time/date on Phase for future drops

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9958]
https://kodadot.xyz/ahp/drops/tilescape

current state: 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/0d205209-3cd6-4396-8c6c-70efa20ecc13)

design: 

![image](https://github.com/kodadot/nft-gallery/assets/36627808/107ec3c1-3cb0-4c2a-888f-286ff39839dd)

**Comment by vikiival** [comment]
![Screenshot 2024-04-02 at 11 05 12](https://github.com/kodadot/nft-gallery/assets/22471030/9a4b4e27-7261-4ecb-b58d-f8dc852845eb)
