### ISSUE TITLE
`Holder of` test Drop not working

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9968]
- Complexity/Reflection of the sound drops are no longer listed as test drops on canary
- Trying to mint on reflection of the sound shows this error when uploading to IPFS: [image](https://github.com/kodadot/nft-gallery/assets/36627808/3937a976-823a-4b30-acde-8dffe8f0144b)
- Complexity is set up to use Geolocation [image](https://github.com/kodadot/nft-gallery/assets/36627808/9ecdaafe-ee73-4697-aca4-82c8389b0e5e) (Please remove)

Related issue: #9926 

https://canary.kodadot.xyz/ahk/drops/complexity
https://canary.kodadot.xyz/ahk/drops/reflection

**Comment by vikiival** [comment]
> Could we try to fix it with another art resource? @vikiival

Yes
