### ISSUE TITLE
Flex on NFT storage 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9974]
cc @preschian 
@vikival is gonna check

maybe we can try swap to Filebase? since we are it paying anyways iirc

![image](https://github.com/kodadot/nft-gallery/assets/5887929/d2986e8f-77b8-42eb-ba28-6dd7da2412cb)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/00d7b4ec-0b01-4f90-9b49-6281eb1b92ea)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/83f4f17c-fa19-4e46-b985-1fd15b965ff9)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/9956#issuecomment-2036798599_

**Comment by vikiival** [comment]
- fixed in kodadot/workers#270
