### ISSUE TITLE
Wrong share text on farcaster

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9982]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/9325f833-2433-45d9-b8e3-6be74aec9523)
I've minted a generative art piece on Koda #115-2404202980/256

also minted this: 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/7e0fe0be-f2cc-4e5f-8ec1-73be6916366f)

this number 2404202980 is redundant 

so something is broken there

**Comment by prury** [comment]
yup, we still adjusting sn on places, ty

**Comment by daiagi** [comment]
@prury 
any upadtes?

something needs to be done?
