### ISSUE TITLE
Tilescape elements without sn and with same image

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9987]
elements without sn and with same image: 
https://canary.kodadot.xyz/ahp/drops/tilescape

![image](https://github.com/kodadot/nft-gallery/assets/36627808/0eef4a38-d2ff-4f44-8949-28a3b1129a68)

cc: @preschian

**Comment by preschian** [comment]
checking~

**Comment by preschian** [comment]
I thoughts it's related with https://github.com/kodadot/nft-gallery/issues/9725. turns out it's different root cause
