### ISSUE TITLE
Listed filter being added after route change 

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#9995]
not sure how, but i was able to get this result twice when testing PR: (buy now filter appearing on collections)

still trying to understand how to reproduce it

![image](https://github.com/kodadot/nft-gallery/assets/36627808/64d30a27-2232-4cf3-8b42-19a85715f817)

how to reproduce: 

https://github.com/kodadot/nft-gallery/assets/36627808/706fa301-ca2a-4a84-9c27-3f4c4181da69

_Originally posted by @prury in https://github.com/kodadot/nft-gallery/issues/9959#issuecomment-2035368514_

**Comment by exezbcz** [comment]
lel the video on how to reproduce the bug look like tutorials on how to get an infinite money glitch :D
